[#search_service]
= Search Service

[abstract]
The _Search Service_ supports the creation of specially purposes indexes for _Full Text Search_.

== Understanding Search

_Search_ represents _Full Text_ search.
The indexes that it creates and uses are entirely separate from and different to those of the _Index Service_.
Full Text Search provides extensive capabilities for natural-language querying.
These include:

* _Language-aware_ searching; allowing users to search for, say, the word `beauties`, and additionally obtain results for `beauty` and `beautiful`.
+
{blank}

* _Scoring_ of results, according to relevancy; allowing users to obtain result-sets that only contain documents awarded the highest scores.
This keeps result-sets manageably small, even when the total number of documents returned is extremely large.
+
{blank}

* _Fast indexes_, which support a wide range of possible text-searches.
+
{blank}

The Search Service requires the Data Service, but does not require, and has no relation to the Index Service or Query Service.

For extensive details on how to use the service, see xref:fts:full-text-intro.adoc[Full Text Search: Fundamentals].
