= Couchbase Server Privacy FAQ

In connection with Couchbase’s provision of our on-premise products, Couchbase provides functionality that, if enabled, will automatically (1) check the version of the product you have installed against the latest version available, and (2) collect information about use and experience with the product every time an administrator interacts with the administrator user interface (the “Admin UI”) using HTTPS Post. If you decide to keep this functionality enabled, we will collect configuration, usage and performance data, including cluster information (such as settings and configuration, software version, cluster ID, load levels, and resource quotas), and browser and network information (such as IP address, inferred geolocation only at the city level, and browser type) (collectively with the foregoing, the “Performance Data”). This Performance Data does not allow us to track your specific interactions or usage of the Couchbase products. We use the Performance Data to make our products more useful to all of our customers as a whole. We never access or collect any data stored within the products. Below you can find additional information about what kind of data we collect and how we handle all data securely. You can disable this feature at any time by accessing the Admin UI settings page and deselecting the checkbox. 

== Types of Data Collected

If you choose to leave the functionality enabled, the Performance Data automatically collected consists of all or any of the following data:

* *Configuration Data*: Data about how Couchbase products have been configured and related environment information. Examples include version information, and configuration and settings.
* *Cluster Usage Data*: Data about how Couchbase products are being used. Examples include cluster unique identification number, age of the cluster, memory allocated to the cluster, number and types of nodes, number of data containers within each cluster, and how much hard disk is allocated to a cluster.
* *Cluster Operational Data*: Data about the performance of the Couchbase products measured in cluster and node performance metrics. Examples include node uptime, average operation of each cluster and node, and average number of queries per node. 
* *Network and Browser Information*: Data about the network and browser interacting with the Admin UI, which consists of IP address, inferred geolocation (only down to the city level), and browser type.

Limited personal data is collected as part of the Performance Data in the form of IP address and browser information described above. We do not use this personal data to identify you or your use of the product. We process all data in accordance with our https://www.couchbase.com/privacy-policy[privacy] and https://www.couchbase.com/resources/security[security] policies and as outlined below.

== Use of the Performance Data

The purposes for which Couchbase uses the Performance Data are as follows: 

* *Product Improvement*: Couchbase uses this information to improve the products we offer to our customers such as:
** To detect and fix bugs in the products and understand product improvement opportunities. 
** To help prioritize future product roadmap features.
** To analyze the rate of deployment and usage of our products.
** To prioritize the order in which certain configurations of the product should be tested.
** To benchmark or assess usage of the products across geographies.
** To make pricing and packaging decisions (e.g. add/modify SKUs based on usage patterns).
* *Marketing & Sales*: Couchbase may use the information to inform its marketing and sales strategies. For example, we may use this information to decide which geographies to target in our marketing campaigns or when we expand our sales force. We do not use this information to market directly to specific administrators who may have provided the Performance Data through this feature. 

Couchbase may update this information from time to time to reflect changes in our products, data collected and use practice.  We encourage you to periodically review this page to keep informed. For more information about what kind of information Couchbase may receive generally, please review our https://www.couchbase.com/privacy-policy[privacy policy]. 

== Security Best Practices

Couchbase has established, implemented and is maintaining enterprise grade https://www.couchbase.com/resources/security[security best practices] for all of its products and applies these processes and procedures to the collection of the Performance Data. The Performance Data will be transferred to Couchbase over an encrypted channel and will be stored in secure Couchbase facilities, protected by internal policies and controls, and will be available for analysis. Once received, the Performance Data will be analyzed and the information collected will be used to improve our products and services, fix problems and inform deployment and usage best practices for our products. Couchbase takes security very seriously and multiple measures such as physical security, access control and multi-tiered security technology are used to protect the Performance Data. The following section provides more details about how we protect the Performance Data:  

* *Secure Transmission*: The Performance Data is transmitted securely on the wire to Couchbase (with TLS 1.2 protocol) every time an administrator accesses the Admin UI (if enabled). The Performance Data is transmitted to a secure Couchbase backend.  
* *Encryption at Rest*: The Performance Data is encrypted at rest using LUKS disc encryption.  
* *Restricted Access*: The Performance Data is accessible to Couchbase employees on a need to know basis. Performance Data can be shared across Couchbase teams to enable cross-product correlation. The Performance Data is not shared with partners or third parties.
* *Data Retention*: Data is retained only as long as needed for the specific uses and in any event, no longer than is necessary for these purposes.