= Licenses for Third-Party Components

This section contains licensing information for some third-party components that are used by Couchbase Server.
We are thankful to all individuals that have created these third-party components.

IMPORTANT: The complete list of licenses for Couchbase Server is available on the https://www.couchbase.com/legal/agreements[Legal Agreements^] page.

== PCRE LICENSE

PCRE is a library of functions to support regular expressions whose syntax and semantics are as close as possible to those of the Perl 5 language.

Regular expression support is provided by the PCRE library package, which is open source software, written by Philip Hazel, and copyright by the University of Cambridge, England.

The source is available at ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/[^].

== APACHE LICENSE, VERSION 2.0

The section on xref:analytics:introduction.adoc[Analytics]
contains some material derived from the https://ci.apache.org/projects/asterixdb/index.html[Apache AsterixDB^]
documentation under the Apache License, Version 2.0.
