= ADVISOR Function
:description: pass:q[The `ADVISOR` function provides index recommendations to optimize query response time. \
There are two main scenarios for using this function.]
:page-topic-type: concept
:page-status: Couchbase Server 7.0
:page-edition: Enterprise Edition
:imagesdir: ../../assets/images

:n1ql: xref:n1ql-language-reference
:select: {n1ql}/selectintro.adoc
:update: {n1ql}/update.adoc
:delete: {n1ql}/delete.adoc
:merge: {n1ql}/merge.adoc
:advise: {n1ql}/advise.adoc
:rules: {n1ql}/advise.adoc#recommendation-rules

:monitor: xref:manage:monitor/monitoring-n1ql-query.adoc
:sys-completed-req: {monitor}#sys-completed-req
:sys-tasks-cache: {monitor}#sys-tasks-cache

:index-advisor: xref:tools:query-workbench.adoc#index-advisor
:completed-limit: xref:settings:query-settings.adoc#completed-limit

{description}
One is to invoke the index advisor _immediately_ for a given query or set of queries; the other is to start a session in which every query of interest is collected for a set time period, then invoke the index advisor _asynchronously_ for that collection of queries when the session ends.
Within these two scenarios, this function has several different usages.
The operation and output of each usage depends on the function's single argument.
For clarity, each usage is listed separately on this page.

[[advisor-string]]
== ADVISOR(`string`)

=== Description

When used with a string argument, the function invokes the index advisor for a single N1QL query.
The index advisor works with {select}[SELECT], {update}[UPDATE], {delete}[DELETE], or {merge}[MERGE] queries.

=== Arguments

string::
A string, or an expression which resolves to a string, containing a single N1QL query.

=== Return Value

Returns an index advisor results object with the following properties.

[[results]]
**Results**

[options="header", cols="~a,~a,~a"]
|===
|Name|Description|Schema

|**current_used_indexes** +
__optional__
|If the query engine can select any current primary or secondary indexes to use with an input query, this is an array of Index objects, each giving information about one of the current indexes.

If the query engine cannot select a current index to use with an input query, this field does not appear.
|< <<indexes,Indexes>> > array

|**recommended_covering_indexes** +
__optional__
|If the index advisor recommends any indexes, this is an array of Index objects, each giving information about one of the recommended indexes.

If the index advisor cannot recommend any covering indexes, this field does not appear.
|< <<indexes,Indexes>> > array

|**recommended_indexes** +
__optional__
|If the index advisor recommends any indexes, this is an array of Index objects, each giving information about one of the recommended indexes.

If the index advisor cannot recommend any indexes, this field does not appear.
|< <<indexes,Indexes>> > array
|===

[[indexes]]
**Indexes**

[options="header", cols="~a,~a,~a"]
|===
|Name|Description|Schema

|**index** +
__required__
|The N1QL command used to define the index.
|string

|**statements** +
__required__
|An array of Statement objects, each giving information about one of the N1QL input queries associated with this index.
|< <<statements,Statements>> > array
|===

[[statements]]
**Statements**

[options="header", cols="3a,11a,4a"]
|===
|Name|Description|Schema

|**run_count** +
__required__
|When the function is used with a single N1QL input query, this is always 1.

When the function is used with an array of queries, or a collection of queries from a session, this is the number of times that this N1QL input query occurs in the input array or session.
|integer

|**statement** +
__required__
|The N1QL input query.
|string
|===

=== Example

.Get index advice for a single query
====
[source,n1ql]
----
include::example$functions/advisor-single.n1ql[]
----

.Result
[source,json]
----
include::example$functions/advisor-single.jsonc[]
----

Only one statement occurs in these results, because the function was called with a single query input.
In this case, the index advisor identifies one index which is currently used by the query, and recommends one secondary index.
No covering indexes are recommended.
====

[[advisor-array]]
== ADVISOR(`array`)

=== Description

When used with an array argument, the function invokes the index advisor for multiple N1QL queries.
The index advisor works with {select}[SELECT], {update}[UPDATE], {delete}[DELETE], or {merge}[MERGE] queries.

=== Arguments

array::
An array of strings, or an expression which resolves to an array of strings, each of which contains a N1QL query.

=== Return Value

Returns an <<results,index advisor results>> object.

=== Examples

.Get index advice for multiple queries
====
[source,n1ql]
----
include::example$functions/advisor-multiple.n1ql[]
----

.Result
[source,json]
----
include::example$functions/advisor-multiple.jsonc[]
----

In this case, the index advisor recommends an index which would be suitable for both of the input queries.
====

.Get index advice for recent completed requests
====
This example uses a subquery to get an array of statements from the {sys-completed-req}[system:completed_requests] catalog.

[source,n1ql]
----
include::example$functions/advisor-recent.n1ql[]
----

.Result
[source,json]
----
include::example$functions/advisor-recent.jsonc[tags=current;recommended;ellipsis]
----

In this case, the index advisor recommends several covering indexes and secondary indexes, each of which would be suitable for multiple recent queries.
(Results are truncated for brevity.)
====

[[advisor-session-start]]
== ADVISOR(`start_obj`)

=== Description

When used with a `start_obj` object argument, the function can be used to start an index advisor session.
As long as the session is running, any queries that meet the criteria you specify are collected for later analysis.

By default, the session continues running for the duration you specify when you start the session.
At the end of the duration, the index advisor analyzes any queries that have been collected by this session.
The session and any resulting index advice are retained in the _tasks cache_.
You can then <<advisor-session-get,get the results>> for this session to see the index advice.

=== Arguments

start_obj::
An object with the following properties:

action;;
[Required] The string `start`.

profile;;
[Optional] A string specifying the user profile whose queries you want to collect.
If omitted, all queries are collected.

response;;
[Optional] A string representing a duration.
All completed queries lasting longer than this threshold are collected for analysis by the index advisor.
Valid time units are `ns` (nanoseconds), `us` (microseconds), `ms` (milliseconds), `s` (seconds), `m` (minutes), or `h` (hours).
If omitted, the default setting is `0s`.

duration;;
[Required] A string representing a duration.
The index advisor session runs for the length of this duration.
Valid time units are `ns` (nanoseconds), `us` (microseconds), `ms` (milliseconds), `s` (seconds), `m` (minutes), or `h` (hours).

query_count;;
[Optional] An integer specifying the maximum number of queries to be collected for analysis by the index advisor.
If omitted, the default setting is the same as the service-level {completed-limit}[completed-limit] setting.
You can change the service-level `completed-limit` setting to change the default for this property.

=== Return Value

Returns an object with the following property:

[options="header", cols="3a,11a,4a"]
|===
|Name|Description|Schema

|**session** +
__required__
|The name of the index advisor session.
You will need to refer to this name to <<advisor-session-get,get the results>> for this session, or to <<advisor-session-stop,stop>>, <<advisor-session-abort,abort>>, or <<advisor-session-purge,purge>> this session.
|string (UUID)
|===

=== Example

.Start an index advisor session
====
The following example starts an index advisor session to run for one hour.
All completed queries taking longer than 0 seconds will be collected.

[source,n1ql]
----
include::example$functions/advisor-start.n1ql[]
----

.Result
[source,json]
----
include::example$functions/advisor-start.jsonc[]
----
====

[[advisor-session-list]]
== ADVISOR(`list_obj`)

=== Description

When used with a `list_obj` object argument, the function can be used to list index advisor sessions.
Each index advisor session is stored as a scheduled task in the {sys-tasks-cache}[system:tasks_cache] catalog.

=== Arguments

list_obj::
An object with the following properties:

action;;
[Required] The string `list`.

status;;
[Optional] A string specifying the status of the index advisor sessions to list.
This must be one of the following:
+
--
* `completed` -- only list completed sessions
* `active` -- only list active sessions
* `all` -- list all sessions
--
+
If omitted, the default is `all`.

=== Return Value

Returns an array of tasks cache objects, each of which has the following properties.

[[tasks-cache]]
**Tasks Cache**

[options="header", cols="3a,11a,4a"]
|===
|Name|Description|Schema

|**tasks_cache** +
__required__
|A nested object that gives information about an index advisor session.
|<<session,Session>>
|===

[[session]]
**Session**

[options="header", cols="3a,11a,4a"]
|===
|Name|Description|Schema

|**class** +
__required__
|The class of the session; in this case, `advisor`.
|string

|**delay** +
__required__
|The scheduled duration of the session.
|string (duration)

|**id** +
__required__
|The internal ID of the session.
|string (UUID)

|**name** +
__required__
|The name of the session.
You will need to refer to this name to <<advisor-session-get,get the results>> for this session, or to <<advisor-session-stop,stop>>, <<advisor-session-abort,abort>>, or <<advisor-session-purge,purge>> this session.
|string (UUID)

|**node** +
__required__
|The node where the session was started.
|string (address)

|**state** +
__required__
|The state of the session:

* `scheduled` -- the session is active.
* `cancelled` -- the session was stopped.
* `completed` -- the session is completed.
|enum (cancelled, completed, scheduled)

|**subClass** +
__required__
|The subclass of the session; in this case, `analyze`.
|string

|**submitTime** +
__required__
|The date and time when the function was called to start the session.
|string (date-time)

|**startTime** +
__optional__
|The date and time when the session started.

If the session is still active, this field is not present.
|string (date-time)

|**stopTime** +
__optional__
|The date and time when the session stopped.

If the session is still active, this field is not present.
|string (date-time)

|**results** +
__optional__
|An array containing a single <<results,index advisor results>> object.

If the session is still active, this field is not present.
|< <<results,Results>> > array
|===

Returns an empty array if there are no index advisor sessions in the tasks cache.

=== Example

.List all index advisor sessions
====
[source,n1ql]
----
include::example$functions/advisor-list.n1ql[]
----

.Result
[source,json]
----
include::example$functions/advisor-list.jsonc[tags=completed;cancelled;ellipsis]
----

(Results are truncated for brevity.)
====

[[advisor-session-stop]]
== ADVISOR(`stop_obj`)

=== Description

When used with a `stop_obj` object argument, the function can be used to stop an index advisor session.
In this case, the session is stopped, and the index advisor analyzes any queries that have been collected by this session so far.
The session and any resulting index advice are retained in the tasks cache.
You can then <<advisor-session-get,get the results>> for this session to see the index advice.

=== Arguments

stop_obj::
An object with the following properties:

action;;
[Required] The string `stop`.

session;;
[Required] A string specifying the name of a session.

=== Return Value

Returns an empty array.

=== Example

.Stop an index advisor session
====
[source,n1ql]
----
include::example$functions/advisor-stop.n1ql[]
----

.Result
[source,json]
----
include::example$functions/advisor-stop.jsonc[]
----
====

[[advisor-session-abort]]
== ADVISOR(`abort_obj`)

=== Description

When used with an `abort_obj` object argument, the function can be used to abort an index advisor session.
In this case, the session is stopped, and the session is removed from the tasks cache.

=== Arguments

abort_obj::
An object with the following properties:

action;;
[Required] The string `abort`.

session;;
[Required] A string specifying the name of a session.

=== Return Value

Returns an empty array.

=== Example

.Abort an index advisor session
====
[source,n1ql]
----
include::example$functions/advisor-abort.n1ql[]
----

.Result
[source,json]
----
include::example$functions/advisor-abort.jsonc[]
----
====

[[advisor-session-get]]
== ADVISOR(`get_obj`)

=== Description

When used with a `get_obj` object argument, the function can be used to get the results of a completed index advisor session.
The index advisor is invoked for any collected {select}[SELECT], {update}[UPDATE], {delete}[DELETE], or {merge}[MERGE] queries.

=== Arguments

get_obj::
An object with the following properties:

action;;
[Required] The string `get`.

session;;
[Required] A string specifying the name of a session.

=== Return Value

Returns an array containing an array, which in turn contains an <<results,index advisor results>> object.

Returns an empty array if the specified session collected no queries, or if the specified session does not exist.

=== Example

.Get index advice for an index advisor session
====
[source,n1ql]
----
include::example$functions/advisor-get.n1ql[]
----

.Result
[source,json]
----
include::example$functions/advisor-get.jsonc[tags=current;covering;recommended;ellipsis]
----

(Results are truncated for brevity.)
====

[[advisor-session-purge]]
== ADVISOR(`purge_obj`)

=== Description

When used with a `purge_obj` object argument, the function can be used to purge the results of a completed index advisor session from the tasks cache.

=== Arguments

purge_obj::
An object with the following properties:

action;;
[Required] The string `purge`.

session;;
[Required] A string specifying the name of a session.

=== Return Value

Returns an empty array.

=== Example

.Purge an index advisor session
====
[source,n1ql]
----
include::example$functions/advisor-q9.n1ql[]
----

.Result
[source,json]
----
include::example$functions/advisor-q9.jsonc[]
----
====

== Related Links

* The {advise}[ADVISE] statement -- also describes the index advisor {rules}[recommendation rules]
* The {index-advisor}[Index Advisor] in the Query Workbench
* The {sys-tasks-cache}[system:tasks_cache] catalog