= Aggregate Functions
:page-topic-type: reference

Aggregate functions take multiple values from documents, perform calculations, and return a single value as the result.
The function names are case insensitive.

You can only use aggregate functions in `SELECT`, `LETTING`, `HAVING`, and `ORDER BY` clauses.
When using an aggregate function in a query, the query operates as an aggregate query.

Aggregate functions take one argument, which is used to compute the aggregate function.
The `COUNT` function can also take a wildcard ({asterisk}) or a path with a wildcard (path.{asterisk}) as its argument.

If there is no input row for the group, `COUNT` functions return `0`.
All other aggregate functions return NULL.

== ARRAY_AGG([.var]`expression`)

=== Return Value
Returns array of the non-MISSING values in the group, including NULL values.

=== Examples
====
List all values of the `Cleanliness` reviews given.

[source,n1ql]
----
SELECT ARRAY_AGG(reviews[0].ratings.Cleanliness) AS Reviews FROM `travel-sample`;
----

.Results
[source,json]
----
[
  {
    "Reviews": [
      -1,
      -1,
      -1,
      -1,
      -1,
...
----
====

== ARRAY_AGG(DISTINCT [.var]`expression`)

=== Return Value
Returns array of the distinct non-MISSING values in the group, including NULL values.

=== Examples
====
List all unique values of the `Cleanliness` reviews given.

[source,n1ql]
----
SELECT ARRAY_AGG(DISTINCT reviews[0].ratings.Cleanliness) AS Reviews FROM `travel-sample`;
----

.Results
[source,json]
----
[
  {
    "UniqueReviews": [
      -1,
      1,
      2,
      3,
      4,
      5
    ]
  }
]
----
====

== AVG([.var]`expression`)

=== Return Value
Returns arithmetic mean (average) of all the number values in the group.

=== Examples
====
The average altitude of airports in the `travel-sample` keyspace.

[source,n1ql]
----
SELECT AVG(geo.alt) AS AverageAltitude FROM `travel-sample` WHERE type="airport";
----

.Results
[source,json]
----
[
  {
    "AverageAltitude": 870.1651422764228
  }
]
----
====

== AVG(DISTINCT [.var]`expression`)

=== Return Value
Returns arithmetic mean (average) of all the distinct number values in the group.

=== Examples
====
The average number of airline route stops vs.
the `DISTINCT` average of airline route stops.

[source,n1ql]
----
SELECT AVG(stops) FROM `travel-sample`; <1>

SELECT AVG(DISTINCT stops) FROM `travel-sample`; <2>
----
====

<1> Results in 0.0002 since nearly all docs have 0 stops.
<2> Results in 0.5 since the docs contain only 1 or 0 stops.

== COUNT(*)

=== Return Value
Returns count of all the input rows for the group, regardless of value.

=== Examples
====
The number of documents in `travel-sample`.

[source,n1ql]
----
SELECT COUNT(*) AS CountAll FROM `travel-sample`;
----

.Results
[source,json]
----
[
  {
    "CountAll": 31591
  }
]
----
====

== COUNT([.var]`expression`)

=== Return Value
Returns count of all the non-NULL and non-MISSING values in the group.

=== Examples
====
The number of documents with an airline route stop in `travel-sample` regardless of its value.

[source,n1ql]
----
SELECT COUNT(stops) AS CountOfStops FROM `travel-sample`;
----

.Results
[source,json]
----
[
  {
    "CountOfStops": 24024
  }
]
----
====

== COUNT(DISTINCT [.var]`expression`)

=== Return Value
Returns count of all the distinct non-NULL and non-MISSING values in the group.

=== Examples
====
The number of unique values of airline route stops in `travel-sample`.

[source,n1ql]
----
SELECT COUNT(DISTINCT stops) AS CountOfDistinctStops FROM `travel-sample`;
----

.Results
[source,json]
----
[
  {
    "CountOfSDistinctStops": 2 <1>
  }
]
----
====

<1> Because there are only 0 or 1 stops.

== COUNTN([.var]`expression`)

=== Return Value
Returns a count of all the numeric values in the group.

=== Examples
====
The count of numeric values in a mixed group.

[source,n1ql]
----
SELECT COUNTN(list.val) AS CountOfNumbers
FROM [
  {"val":1},
  {"val":1},
  {"val":2},
  {"val":"abc"}
] AS list;
----

.Results
[source,json]
----
[
  {
    "CountOfNumbers": 3
  }
]
----
====

== COUNTN(DISTINCT [.var]`expression` )

=== Return Value
Returns a count of all the distinct numeric values in the group.

=== Examples
====
The count of unique numeric values in a mixed group.

[source,n1ql]
----
SELECT COUNTN(DISTINCT list.val) AS CountOfNumbers
FROM [
  {"val":1},
  {"val":1},
  {"val":2},
  {"val":"abc"}
] AS list;
----

.Results
[source,json]
----
[
  {
    "CountOfNumbers": 2
  }
]
----
====

== MAX([.var]`expression`)

=== Return Value
Returns the maximum non-NULL, non-MISSING value in the group in N1QL collation order.

=== Examples
====
Max of an integer field – Find the northernmost latitude of any hotel in `travel-sample`.

[source,n1ql]
----
SELECT MAX(geo.lat) AS MaxLatitude FROM `travel-sample` WHERE type="hotel";
----

.Results
[source,json]
----
[
  {
    "MaxLatitude": 60.15356
  }
]
----
====

====
Max of a string field – Find the hotel whose name is last alphabetically in `travel-sample`.

[source,n1ql]
----
SELECT MAX(name) AS MaxName FROM `travel-sample` WHERE type="hotel";
----

.Results
[source,json]
----
[
  {
    "MaxName": "pentahotel Birmingham"
  }
]
----
====

That result might have been surprising since lowercase letters come after uppercase letters and are therefore "higher" than uppercase letters.
To avoid this uppercase/lowercase confusion, you should first make all values uppercase or lowercase, as in the following example.

====
Max of a string field, regardless of case – Find the hotel whose name is last alphabetically in `travel-sample`.

[source,n1ql]
----
SELECT MAX(UPPER(name)) AS MaxName FROM `travel-sample` WHERE type="hotel";
----

.Results
[source,json]
----
[
  {
    "MaxName": "YOSEMITE LODGE AT THE FALLS"
  }
]
----
====

== MIN([.var]`expression`)

=== Return Value
Returns the minimum non-NULL, non-MISSING value in the group in N1QL collation order.

=== Examples
====
Min of an integer field – Find the southernmost latitude of any hotel in `travel-sample`.

[source,n1ql]
----
SELECT MIN(geo.lat) AS MinLatitude FROM `travel-sample` WHERE type="hotel";
----

.Results
[source,json]
----
[
  {
    "MinLatitude": 32.68092
  }
]
----
====

====
Min of a string field – Find the hotel whose name is first alphabetically in `travel-sample`.

[source,n1ql]
----
SELECT MIN(name) AS MinName FROM `travel-sample` WHERE type="hotel";
----

.Results
[source,json]
----
[
  {
    "MinName": "'La Mirande Hotel"
  }
]
----
====

That result might have been surprising since some symbols come before letters and are therefore "lower" than letters.
To avoid this symbol confusion, you can specify letters only, as in the following example.

====
Min of a string field, regardless of preceding non-letters – Find the first hotel alphabetically in `travel-sample`.

[source,n1ql]
----
SELECT MIN(name) AS MinName FROM `travel-sample` WHERE type="hotel" AND SUBSTR(name,0)>="A";
----

.Results
[source,json]
----
[
  {
    "MinName": "AIRE NATURELLE LE GROZEAU Aire naturelle"
  }
]
----
====

== SUM([.var]`expression`)

=== Return Value
Returns sum of all the number values in the group.

=== Examples
====
The sum total of all airline route stops in `travel-sample`.

NOTE: In the travel-sample bucket, nearly all flights are non-stop (0 stops) and only six flights have 1 stop, so we expect 6 flights of 1 stop each, a total of 6.

[source,n1ql]
----
SELECT SUM(stops) AS SumOfStops FROM `travel-sample`;
----

.Results
[source,json]
----
[
  {
    "SumOfStops": 6 <1>
  }
]
----
====

<1> Because there are 6 routes * 1 stop each = 6

== SUM(DISTINCT [.var]`expression`)

=== Return Value
Returns arithmetic sum of all the distinct number values in the group.

=== Examples
====
The sum total of all unique numbers of airline route stops in `travel-sample`.

[source,n1ql]
----
SELECT SUM(DISTINCT stops) AS SumOfDistinctStops FROM `travel-sample`;
----

.Results
[source,json]
----
[
  {
    "SumOfDistinctStops": 1 <1>
  }
]
----
====

<1> Because there are only 0 and 1 stops per route; and 0 + 1 = 1

== Related Links

xref:n1ql-language-reference/groupby.adoc[GROUP BY Clause] for GROUP BY, LETTING, and HAVING clauses.
