= Cost-Based Optimizer
:page-topic-type: concept
:page-edition: Enterprise Edition
:imagesdir: ../../assets/images
:description: The cost-based optimizer takes into account the cost of memory, CPU, network transport, and disk usage when choosing the optimal plan to execute a query.

// Cross-references
:query-settings: xref:settings:query-settings.adoc
:queryUseCBO: {query-settings}#queryUseCBO
:use-cbo-srv: {query-settings}#use-cbo-srv
:use_cbo_req: {query-settings}#use_cbo_req
:n1ql: xref:n1ql-language-reference
:select: {n1ql}/selectintro.adoc
:update: {n1ql}/update.adoc
:delete: {n1ql}/delete.adoc
:merge: {n1ql}/merge.adoc
:insert: {n1ql}/insert.adoc
:explain: {n1ql}/explain.adoc
:updatestatistics: {n1ql}/updatestatistics.adoc
:optimizer-hints: {n1ql}/optimizer-hints.adoc
:query-hints: {n1ql}/query-hints.adoc
:ordered-hint: {query-hints}#ordered
:keyspace-hints: {n1ql}/keyspace-hints.adoc
:index-hint: {keyspace-hints}#index
:use-nl-hint: {keyspace-hints}#use_nl
:use-hash-hint: {keyspace-hints}#use_hash
:collation: {n1ql}/datatypes.adoc#collation
:query-service: xref:learn:services-and-indexes/services/query-service.adoc
:query-service-architecture: {query-service}#query-service-architecture
:query-execution: {query-service}#query-execution
:query-settings: xref:manage:manage-settings/general-settings.adoc#query-settings

[abstract]
{description}

[[overview]]
== Overview

The _cost-based optimizer_ (CBO) is a feature available in Couchbase Server Enterprise Edition that enables the Query service to create the most efficient plan to execute a query.

The execution of a query involves {query-execution}[many possible operations]: scan, fetch, join, filter, and so on.
When the query processor is planning the query execution, there may be several possible choices for each operation: for example, there may be different possible indexes, or a choice of join types.
With each of these operations, some of these choices are quicker and more efficient than others.
The query processor attempts to choose the most efficient options when creating the query execution plan.
The legacy {query-service-architecture}[rules-based optimizer] (RBO), as its name suggests, takes a rules-based approach; but this does not always lead to the optimum query plan.

The cost-based optimizer uses metadata and statistics to estimate the amount of processing (memory, CPU, network traffic, and I/O) required for each operation.
It compares the cost of alternative routes, and then selects the query-execution plan with the least cost.

.Query execution flow, showing the cost-based optimizer using statistics and metadata
[mermaid,cbo_query_execution_flow,svg]
....
graph LR
    accTitle: Query execution flow
    A[SQL++<br>Statement] --> B[[SQL++<br>Parser]]
    B --> D[[Semantic<br>Analyzer]]
    C([System<br>metadata]) --> D
    E([Statistics and<br>Metadata]) --> X
    D --> X
    X --> G[Query Explain<br>Plan]
    X --> H["Query Execution Tree<br>(Query Plan)"]
    H --> I[[Executor]]
    I --> J[/"Debug Info<br>(Query Profile)"/]
    I --> K[/Query Results/]

   subgraph Optimizer
   X["Plan A #10003;<br>Scan: Cost 12 <br>Fetch: Cost 17 <br>Join: Cost 7<br>Total: 23"]
   Y["Plan B #10007;<br>Scan: Cost 20 <br>Fetch: Cost 25 <br>Join: Cost 7<br>Total: 52"]
   Z["Plan C #10007;<br>Scan: Cost 18 <br>Fetch: Cost 36 <br>Join: Cost 14<br>Total: 68"]
   end
....

The cost-based optimizer can generate a query plan for {select}[SELECT], {update}[UPDATE], {delete}[DELETE], {merge}[MERGE], and {insert}[INSERT INTO with SELECT] queries.

****
As an analogy, imagine that you need to travel from one side of a major city to the other by train.
There may be many options available to you: commuter rail, metro, or light rail.
You may also need to change from one service to another at an interchange station, perhaps more than once.
By combining the fastest services with the smallest number of changes and the shortest wait time at each interchange, you can get to your destination in the most efficient way.

Of course, to plan your route, you need to have knowledge of the train frequencies, the size and accessibility of the interchange stations, and how busy the services are likely to be at the time when you travel.
Each of these factors imposes a cost on the options that are available to you.
If you have a greater knowledge and experience of the city's rail network, you will be better informed about these costs, and better able to plan the optimum journey.
****

[[advantages]]
== Advantages of the Cost-Based Optimizer

The cost-based optimizer calculates a cost for a query plan that takes into consideration resource usages during query execution, thus can potentially generate an optimum query plan.

[[index-selection]]
=== Index Selection

The cost-based optimizer takes into consideration the characteristics of each qualified index, and thus can better differentiate between similar indexes.
The cost-based optimizer also reduces the need for intersect scans, since it can determine whether one index is better than another based on cost information.

Refer to {index-hint}[INDEX] for an example.

[[join-method]]
=== Join Method

In Couchbase Server Enterprise Edition, two join methods are supported: nested-loop join and hash join.
With the legacy {query-service-architecture}[rules-based optimizer], nested-loop join is used by default, and hash join is only considered when a USE HASH hint is specified.
With the cost-based optimizer, both join methods are considered, and the optimizer chooses a join method based on cost information.

Refer to {use-nl-hint}[USE_NL] and {use-hash-hint}[USE_HASH] for examples.

[[join-enumeration]]
=== Join Enumeration

ifeval::['{page-component-version}' == '7.1']
_(Introduced in Couchbase Server 7.1)_
endif::[]

With the legacy {query-service-architecture}[rules-based optimizer], joins are performed in the order in which they are specified in the query, and no reordering of joins is considered.
With the cost-based optimizer, different join orders can be considered, and the optimizer chooses the optimal join order based on cost information.

Refer to {ordered-hint}[ORDERED] for an example.

[[optimizer-stats]]
== Optimizer Statistics

The cost-based optimizer uses keyspace statistics, index statistics, and distribution statistics.
Before you can use the cost-based optimizer with a query, you _must_ first gather the statistics that it needs using the {updatestatistics}[UPDATE STATISTICS] statement.

If the cost-based optimizer cannot properly calculate cost information for any step of a query plan, e.g. due to lack of the necessary optimizer statistics, the Query service falls back on the {query-service-architecture}[rules-based {sqlpp} optimizer] to generate a query plan.

The cost-based optimizer uses the following statistics.

For keyspaces:

* The number of documents in the keyspace.
* The average document size.

For indexes using standard index storage:

* The number of items in the index.
* The number of index pages.
* The resident ratio.
* The average item size.
* The average page size.
* The number of documents indexed.

For indexes using memory-optimized index storage:

* The number of items in the index.
* The average item size.

For data:

* Distribution statistics -- refer to <<distribution-stats,the section below>>.

[[distribution-stats]]
== Distribution Statistics

The cost-based optimizer can collect distribution statistics on predicate expressions.
These predicate expressions may be fields, nested fields, array expressions, or any of the expressions supported as an index key.

The distribution statistics enable the optimizer to estimate the cost for predicates like `c1 = 100`, `c1 >= 20`, or `c1 < 150`.
They also enable cost estimates for join predicates such as `t1.c1 = t2.c2`, assuming distribution statistics exist for both `t1.c1` and `t2.c2`.

[[distribution-bins]]
=== Distribution Bins

The optimizer takes a sample of the values returned by the expression across the keyspace.
These sample values are sorted into _distribution bins_ by data type and value.

. Values with different data types are placed into separate distribution bins.
(A field may contain values of several different data types across documents.)

. After being separated by data type, values are sorted further into separate bins depending on their value.

The distribution bins are of approximately equal size, except for the last distribution bin for each data type, which could be a partial bin.

[[overflow-bins]]
=== Overflow Bins

For each distribution bin, the number of distinct values is calculated, as a fraction of the total number of documents.

If a particular value is highly duplicated and represents more than 25% of a distribution bin, it is removed from the distribution bin and placed in an _overflow bin_.
MISSING, NULL, or boolean values are always placed in an overflow bin.

[[boundary-bins]]
=== Boundary Bins

Each distribution bin has a maximum value, which acts as the minimum value for the next bin.

A _boundary bin_ containing no values is created before the first distribution bin of each different data type.
The boundary bin contains no values.
This provides the minimum value for the first bin of each type.

[[histogram]]
=== Histogram

The boundary bins, distribution bins, and overflow bins for each data type are chained together in the {collation}[default ascending collation order] used for {sqlpp} data types:

* MISSING
* NULL
* FALSE
* TRUE
* number
* string
* array
* object
* binary (non-JSON)

This forms a histogram of statistics for the index-key expression across multiple data types.

.Distribution bins and boundary bins for integers, strings, and arrays
[mermaid,cbo_distribution_bins,svg]
....
graph LR
    accTitle: Distribution bins
    D --- E
    I --- J
    
    subgraph Integer Values
    A[Size: 25%<br>Distinct: 23 <br>Max: 300] --- B
    B[Size: 25%<br>Distinct: 49 <br>Max: 2000] --- C
    C[Size: 25%<br>Distinct: 88 <br>Max: 8000] --- D
    D[Size: 25%<br>Distinct: 3 <br>Max: 10000]
    end

    subgraph String Values
    E[Boundary] --- F
    F["Size: 25%<br>Distinct: 92 <br>Max: &ldquo;A232&rdquo;"] --- G
    G["Size: 25%<br>Distinct: 23 <br>Max: &ldquo;F348&rdquo;"] --- H
    H["Size: 25%<br>Distinct: 20 <br>Max: &ldquo;L283&rdquo;"] --- I
    I["Size: 25%<br>Distinct: 3 <br>Max: &ldquo;Z82&rdquo;"]
    end

    subgraph Array Values
    J[Boundary] --- K
    K["Size: 25%<br>Distinct: 48 <br>Max: [234]"] --- L
    L["Size: 25%<br>Distinct: 28 <br>Max: [948]"]
    end
....

[[resolution]]
=== Resolution

The number of distribution bins is determined by the _resolution_.

The default resolution is `1.0`, meaning each distribution bin contains 1% of the documents, and therefore 100 bins are required.
The minimum resolution is `0.02` (5000 distribution bins) and the maximum is `5.0` (20 distribution bins).
The cost-based optimizer calculates the bin size based on the resolution and the number of documents in the collection.

The resolution can be specified when you use the {updatestatistics}[UPDATE STATISTICS] statement.

[[sample-size]]
=== Sample Size

The size of the sample that is collected when gathering statistics is determined by the _sample size_.

The cost-based optimizer calculates a default minimum sample size based on the resolution information.
You can optionally specify the sample size when you use the {updatestatistics}[UPDATE STATISTICS] statement.

If you do not specify a sample size, or if the specified sample size is smaller than the default minimum sample size, the default minimum sample size is used instead.

[[settings-and-parameters]]
== Settings and Parameters

The cost-based optimizer is enabled by default.
You can enable or disable it as required.

* The {use_cbo_req}[request-level] `use_cbo` parameter specifies whether the cost-based optimizer is enabled per request.
If a request does not include this parameter, the node-level setting is used.

* The {use-cbo-srv}[node-level] `use-cbo` setting specifies whether the cost-based optimizer is enabled for a single query node.
It defaults to `true`.

* The {queryUseCBO}[cluster-level] `queryUseCBO` setting enables you to specify the node-level setting for all the nodes in the cluster.

You can also enable or disable the cost-based optimizer using the {query-settings}[Query Settings] in the Couchbase Web Console.

If the cost-based optimizer is not enabled, the Query service falls back on the {query-service-architecture}[rules-based {sqlpp} optimizer].

=== Optimizer Hints

ifeval::['{page-component-version}' == '7.1']
_(Introduced in Couchbase Server 7.1)_
endif::[]

In Couchbase Server 7.1 and later, you can supply hints to the optimizer within a specially-formatted hint comment.
For example, you can specify a particular index; specify a join method for a particular join; or request that the query should use the join order as written.
For further details, refer to {optimizer-hints}[Optimizer Hints].

[[operations]]
== Using the Cost-Based Optimizer

When enabled, the optimizer performs the following tasks when a query is executed:

. Rewrite the query if necessary, in the same manner as the previous rules-based optimizer.

. Use the distribution histogram and index statistics to estimate the _selectivity_ of a predicate -- that is, the number of documents that the optimizer expects to retrieve which satisfy this predicate.

. Use the selectivity to estimate the _cardinality_ -- that is, the number of documents remaining after all applicable predicates are applied.

. Use the cardinality to estimate the cost of different access paths.

. Compare the costs and generate a query execution plan with the lowest cost.

As described above, the cost-based optimizer can choose the optimal join method for each join, and rewrites the query to use the optimal join ordering.

The optimizer adds cost and cardinality estimates to every step in the query plan.
You can see these estimates using the {explain}[EXPLAIN] command.
Refer to the documentation for the {updatestatistics}[UPDATE STATISTICS] statement to see examples of how to generate optimizer statistics, and queries that use these optimizer statistics to calculate cost information in order to generate a query plan.

== Related Links

* {updatestatistics}[UPDATE STATISTICS] statement
* {optimizer-hints}[] overview
* Blog post: https://blog.couchbase.com/?p=7384&preview=true[Cost Based Optimizer for Couchbase N1QL^]