= DELETE
:page-topic-type: reference

DELETE immediately removes the specified document from your keyspace.
DELETE uses the following syntax:

----
DELETE FROM keyspace-ref
[USE KEYS clause]
[WHERE clause]
[LIMIT clause]
[RETURNING clause]
----

*keyspace-ref*

Specifies the data source from which to delete the document.
You can add an optional namespace name to the keyspace name in this way:

----
[ (namespace-name :)] keyspace-name
----

Currently, only the `default` namespace is available.
For example, `default:{backtick}travel-sample{backtick}` indicates the `travel-sample` keyspace in the `default` namespace.
If the namespace name is omitted, the default namespace in the current session is used.

*USE KEYS clause*_(optional)_

Specifies the keys of the data items to be deleted.
Keys can be any expression.

----
USE [PRIMARY] KEYS expression
----

*WHERE clause*_(optional)_

Specifies the condition that needs to be met for data to be deleted.

----
WHERE condition
----

*LIMIT clause*_(optional)_

Specifies the greatest number of objects that can be deleted.
This clause must have a non-negative integer as its upper bound.

----
LIMIT expression
----

*RETURNING clause*_(optional)_

Returns the data you deleted as specified in the [.var]`result_expression`.

----
RETURNING (result-expression [, result-expression]* | [RAW | ELEMENT ] expression)
----

*RBAC Privileges*

User executing the DELETE statement must have the _Query Delete_ privilege granted on the target keyspace/bucket.
If the statement has any RETURNING clauses that need data read, then the _Query Select_ privilege is also required on the keyspaces referred in the respective clauses.
For more details about user roles, see
xref:learn:security/authorization-overview.adoc[Authorization].

In summary, see the below table.

.{empty}
[cols="^400,^1980,^1773,^1773"]
|===
| # | Delete Query Contains | Query Delete Permissions Needed | Query Select Permissions Needed

| Q1
| WHERE clause
| Yes
| No

| Q2
| a subquery
| Yes
| Yes

| Q3
| RETURNING clause
| Yes
| Yes
|===

*Q1 Examples* that require the _Query Delete_ privilege on `pass:c[`travel-sample`]`.

----
DELETE FROM `travel-sample` WHERE type = "hotel";

DELETE FROM `travel-sample` WHERE type = "hotel" RETURNING *;
----

*Q1 Example* that requires the _Query Delete_ privilege on `pass:c[`travel-sample`]` and on `pass:c[`beer-sample`]`.

----
DELETE FROM `travel-sample` WHERE city
IN (SELECT raw city FROM `beer-sample` WHERE city IS NOT MISSING);
----

*Q2 Example* that requires the _Query Delete_ and _Query Select_ privilege on `pass:c[`travel-sample`]`.

----
DELETE FROM `travel-sample`
WHERE city =  (SELECT MAX(city) FROM `travel-sample`
----

*Q3 Example* that requires the _Query Delete_ and _Query Select_ privilege on `pass:c[`travel-sample`]`.

----
DELETE FROM `travel-sample`
WHERE city = "San Francisco"
RETURNING meta().id
----

*Example 4*:  Query that deletes product10.

----
DELETE FROM product p USE KEYS "product10" RETURNING p

"results": [
    {
        "p": {
            "categories": [
                "Luggage"
            ],
            "color": "sky blue",
            "dateAdded": "2014-05-06T15:52:18Z",
            "dateModified": "2014-05-06T15:52:18Z",
            "description": "This product is available on
                \u003ca target=\"_blank\"
                href=\"http://www.amazon.com/gp/product/
                B005HNKFSM/ref=s9_hps_bw_g198_ir011?pf_rd_m=ATVPDKIKX0DER\
                u0026pf_rd_s=merchandised-search-5\u0026pf_
                rd_r=D182EDFE2F434403B401\u0026pf_rd_t=101\
                u0026pf_rd_p=1486061902\u0026pf_rd_i=15743161
                \"\u003eAmazon.com\u003c/a\u003e.",
            "imageURL": "http://ecx.images-amazon.com/
                images/I/51KiHy-Y-2L._SY220_.jpg",
            "name": "Briggs \
                u0026 Riley Luggage Executive Clamshell Backpack",
            "productId": "product10",
            "reviewList": [
                "review47",
                "review873",
                "review1224",
                "review2203",
                "review2242",
                "review6162",
                "review6825",
                "review7300",
                "review9934"
            ],
            "type": "product",
            "unitPrice": 231.2
        }
    }
]
----

*Example 5*:  Query that deletes the product that is priced at 5.25.

----
DELETE FROM product p
WHERE p.unitPrice = 5.25
RETURNING p.productId

"results": [
        {
            "productId": "product99"
        }
    ]
----
