= Indexing Metadata Information
:description: Couchbase Server allows indexing on selected metadata fields, for example the expiration and CAS properties.
:page-topic-type: reference

{description}
This improves performance of queries involving predicates on the metadata fields, such as expired documents or recently modified documents.

== Overview

The xref:n1ql:n1ql-language-reference/metafun.adoc#meta[META()] function enables you to return the metadata for a keyspace or document.
To index a selected metadata field, you must use a xref:n1ql-language-reference/nestedops.adoc#field-selection[nested expression] containing the `META()` function and the required property, for example `META().id`.

The property name must be separated from the `META()` function by a dot (`.`) and only the following metadata properties can be indexed.
If you attempt to build an index on a metadata field that is not indexable, an error is returned.

cas::
include::./metafun.adoc[tag=metadata-cas]

expiration::
include::./metafun.adoc[tag=metadata-expiration]
+
Note that this property gives correct results only when used in a xref:n1ql-language-reference/covering-indexes.adoc[Covered Index].

id::
include::./metafun.adoc[tag=metadata-id]

The `META()` function does not require a keyspace parameter when creating an index, since it implicitly uses the keyspace being indexed.

== Examples

.Find two documents that have no expiration date
====
.Index
[source,n1ql]
----
CREATE INDEX idx_expir ON `travel-sample` ( META().expiration );
----

.Query
[source,n1ql]
----
SELECT META().id, META().expiration
FROM `travel-sample`
WHERE META().expiration = 0
ORDER BY META().id
LIMIT 2;
----

.Results
[source,json]
----
[
  {
    "expiration": 0,
    "id": "airline_10"
  },
  {
    "expiration": 0,
    "id": "airline_10123"
  }
]
----
====

.Find all documents whose meta ID tag starts with a letter higher than "g"
====
.Index
[source,n1ql]
----
CREATE INDEX idx_id ON `travel-sample` (META().id );
----

.Query
[source,n1ql]
----
SELECT name, META().id
FROM `travel-sample`
WHERE META().id > "g"
LIMIT 2;
----

.Results
[source,json]
----
[
  {
    "id": "hotel_10025",
    "name": "Medway Youth Hostel"
  },
  {
    "id": "hotel_10026",
    "name": "The Balmoral Guesthouse"
  }
]
----
====

.Find the two most recently modified hotel documents
====
.Index
[source,n1ql]
----
CREATE INDEX idx_cas ON `travel-sample` ( META().cas );
----

.Query
[source,n1ql]
----
SELECT name, META().cas
FROM `travel-sample`
WHERE type="hotel"
ORDER BY META().cas DESC
LIMIT 2;
----

.Results
[source,json]
----
[
    {
        "cas": 1503510338735374337,
        "name": "Hotel Formule 1"
    },
    {
        "cas": 1503510338734850048,
        "name": "Harbour Cottage Gardenstown"
    }
]
----
====
