= N1QL Language Reference
:page-topic-type: concept

:createindex: xref:n1ql-language-reference/createindex.adoc
:alterindex:  xref:n1ql-language-reference/alterindex.adoc
:dropindex: xref:n1ql-language-reference/dropindex.adoc
:selectintro: xref:n1ql-language-reference/selectintro.adoc
:insert: xref:n1ql-language-reference/insert.adoc
:update: xref:n1ql-language-reference/update.adoc
:delete: xref:n1ql-language-reference/delete.adoc
:upsert: xref:n1ql-language-reference/upsert.adoc

[abstract]
The N1QL reference guide describes the N1QL language structure, syntax, and shows how to run N1QL queries from a command line.
It also provides reference information about the basic elements in N1QL which can be combined to build N1QL statements.

== N1QL Language Structure

The N1QL language structure is composed of statements, expressions, and comments.

=== Statements

N1QL statements are categorized into the following groups:

* *Data Definition Language* (DDL) statements to {createindex}[create indexes], {alterindex}[modify indexes], and {dropindex}[drop indexes].
* *Data Manipulation Language* (DML) statements to {selectintro}[select], {insert}[insert], {update}[update], {delete}[delete], and {upsert}[upsert] data into JSON documents.

[[N1QL_Expressions]]
=== Expressions

The following are the different types of N1QL expressions:

* xref:n1ql-language-reference/aggregatefun.adoc[aggregate]
* xref:n1ql-language-reference/arithmetic.adoc[arithmetic]
* xref:n1ql-language-reference/collectionops.adoc[collection]
* xref:n1ql-language-reference/comparisonops.adoc[comparison]
* xref:n1ql-language-reference/conditionalops.adoc[conditional]
* xref:n1ql-language-reference/constructionops.adoc[construction]
* xref:n1ql-language-reference/functions.adoc[function call]
* xref:n1ql-language-reference/identifiers.adoc[identifier]
* xref:n1ql-language-reference/literals.adoc[literal-value]
* xref:n1ql-language-reference/logicalops.adoc[logical]
* <<nested-path-exp,nested expression>>
* xref:n1ql-language-reference/stringfun.adoc[string]
* xref:n1ql-language-reference/subqueries.adoc[subquery]

=== Comments

N1QL supports block comments and line comments.

==== Block Comments

----
/*  [ [text] | [newline] ]+  */
----

A block comment starts with `/{asterisk}` and ends with `{asterisk}/`.
The query engine ignores the start and end markers `/{asterisk}&nbsp;{asterisk}/`, and any text between them.

A block comment may start on a new line, or in the middle of a line after other N1QL statements.
A block comment may contain line breaks.

There may also be further N1QL statements on the same line after the end of a block comment -- the query engine does _not_ ignore these.

==== Line Comments

[.status]#Couchbase Server 6.5#

----
-- [text]
----

A line comment starts with two hyphens `--`.
The query engine ignores the two hyphens, and any text following them up to the end of the line.

A line comment may start on a new line, or in the middle of a line after other N1QL statements.
A line comment may not contain line breaks.

[#nested-path-exp]
== Nested Path Expressions

In N1QL, nested paths indicate an expression to access nested sub-documents within a JSON document or expression.

For example, the latitude of a location in the `type="airport"` documents in the `pass:c[`travel-sample`]` are in the `geo` sub-document and can be addressed as the nested path `pass:c[`travel-sample`.geo.lat]`:

----
SELECT airportname, city, geo, round(geo.lat) as latitude
FROM `travel-sample` t1
WHERE t1.type = "airport" LIMIT 1;

[
  {
    "airportname": "Calais Dunkerque",
    "city": "Calais",
    "geo": {
      "alt": 12,
      "lat": 50.962097,
      "lon": 1.954764
    }
    "latitude": 51,
  }
]
----

Dot Notation (.) is used to access sub-document fields within a document.
