[#n1ql-lang-ref]
= N1QL Language Reference
:page-type: concept

[abstract]
The N1QL reference guide describes the N1QL language structure, syntax, and shows how to run N1QL queries from a command line.
It also provides reference information about the basic elements in N1QL which can be combined to build N1QL statements.

== N1QL Language Structure

The N1QL language structure is composed of statements, expressions, and comments.

Statements:: N1QL statements are categorized into the following groups:
* *Data Definition Language* (DDL) statements to xref:n1ql-language-reference/createindex.adoc[create indexes], modify indexes, and xref:n1ql-language-reference/dropindex.adoc[drop indexes].
* *Data Manipulation Language* (DML) statements to xref:n1ql-language-reference/selectintro.adoc[select], xref:n1ql-language-reference/insert.adoc[insert], xref:n1ql-language-reference/update.adoc#topic_11_8[update], xref:n1ql-language-reference/delete.adoc[delete], and xref:n1ql-language-reference/upsert.adoc#topic_11_9[upsert] data into JSON documents.

[[N1QL_Expressions]]Expressions:: The following are the different types of N1QL expressions:
* xref:n1ql-language-reference/aggregatefun.adoc#topic_8_1[aggregate]
* xref:n1ql-language-reference/arithmetic.adoc[arithmetic]
* xref:n1ql-language-reference/collectionops.adoc#topic_7_1[collection]
* xref:n1ql-language-reference/comparisonops.adoc#topic_7_2[comparison]
* xref:n1ql-language-reference/conditionalops.adoc#topic_7_3[conditional]
* xref:n1ql-language-reference/constructionops.adoc#topic_7_4[construction]
* xref:n1ql-language-reference/functions.adoc#topic_8[function call]
* xref:n1ql-language-reference/identifiers.adoc#topic_6[identifier]
* xref:n1ql-language-reference/literals.adoc#topic_5[literal-value]
* xref:n1ql-language-reference/logicalops.adoc#topic_7_5[logical]
* <<nested-path-exp,nested expression>>
* xref:n1ql-language-reference/stringfun.adoc#topic_8_12[string]
* xref:n1ql-language-reference/subqueries.adoc#topic_9[subquery]

Comments::
N1QL supports block comments with the following syntax:
+
----
/*  [ [text] | [newline] ]+  */
----

[#nested-path-exp]
== Nested Path Expressions

In N1QL, nested paths indicate an expression to access nested sub-documents within a JSON document or expression.

For example, the latitude of a location in the `type="airport"` documents in the `pass:c[`travel-sample`]` are in the `geo` sub-document and can be addressed as the nested path `pass:c[`travel-sample`.geo.lat]`:

----
SELECT airportname, city, geo, round(geo.lat) as latitude
FROM `travel-sample` t1
WHERE t1.type = "airport" LIMIT 1;

[
  {
    "airportname": "Calais Dunkerque",
    "city": "Calais",
    "geo": {
      "alt": 12,
      "lat": 50.962097,
      "lon": 1.954764
    }
    "latitude": 51,
  }
]
----

Dot Notation (.) is used to access sub-document fields within a document.
