= Logical Operators
:page-topic-type: concept

Logical terms let you combine other expressions using xref:n1ql-language-reference/booleanlogic.adoc[Boolean logic].
N1QL provides the following logical operators:

* AND
* OR
* NOT

In N1QL, logical operators have their usual meaning.
However, boolean propositions can evaluate to NULL or MISSING as well as to TRUE and FALSE.
The logical truth tables for these operators therefore use four-valued logic.

[#logical-op-and]
== AND

----
condition AND condition
----

AND evaluates to TRUE only if both conditions are TRUE.

.AND Truth Table
[cols="s,d,d,d,d"]
|===
| | TRUE | FALSE | NULL | MISSING

| TRUE
| TRUE
| FALSE
| NULL
| MISSING

| FALSE
| FALSE
| FALSE
| FALSE
| FALSE

| NULL
| NULL
| FALSE
| NULL
| MISSING

| MISSING
| MISSING
| FALSE
| MISSING
| MISSING
|===

[#or-operator]
== OR

----
condition OR condition
----

OR evaluates to TRUE if one of the conditions is TRUE.

.OR Truth Table
[cols="s,d,d,d,d"]
|===
| | TRUE | FALSE | NULL | MISSING

| TRUE
| TRUE
| TRUE
| TRUE
| TRUE

| FALSE
| TRUE
| FALSE
| NULL
| MISSING

| NULL
| TRUE
| NULL
| NULL
| NULL

| MISSING
| TRUE
| MISSING
| NULL
| MISSING
|===

[#logical-op-not]
== NOT

----
NOT condition
----

NOT evaluates to TRUE if the expression does not match the condition.

.NOT Truth Table

[cols="s,d"]
|===
| | NOT

| TRUE
| FALSE

| FALSE
| TRUE

| NULL
| NULL

| MISSING
| MISSING
|===

== Related Links

For further details, refer to xref:n1ql-language-reference/booleanlogic.adoc[Boolean Logic].