= Miscellaneous Utility Functions
:page-topic-type: reference
:page-partial:
:example-caption!:
:description: Miscellaneous utility functions enable you to perform tasks beyond the usual evaluation and transformation of data.

{description}
For example, there are functions to retrieve information about a document or item, perform base64 encoding and decoding, generate UUIDs, and control the flow of a query.

[[abort,ABORT()]]
== ABORT(`expression`)

=== Description

Generates an error.
The error message contains the text specified by the given [.var]`expression`.

This function is useful for flow control when xref:n1ql:n1ql-language-reference/createfunction.adoc[creating inline user-defined functions].
You can use xref:n1ql:n1ql-language-reference/conditionalops.adoc[conditional operators] to check the parameters, and use this function to generate an error if something is wrong.

=== Arguments

expression:: An expression resolving to a string.

=== Return Value

The function does not return a return value.

If this function is executed in a query, it causes the query to halt with an error code 5011.
The error message contains the text specified by the given [.var]`expression`.

When this function is executed by a user-defined function, it causes the query to halt with an error code 10109.
The error message shows the name of the user-defined function and contains the text specified by the given [.var]`expression`.

=== Examples

[[abort-ex1,ABORT() Example 1]]
.Abort a query
====

.Query
[source,n1ql]
----
SELECT ABORT("Something went wrong");
----

.Result
[source,json]
----
[
  {
    "code": 5011,
    "msg": "Abort: \"Something went wrong\". - cause: \"Something went wrong\""
  }
]
----
====

[[abort-ex2,ABORT() Example 2]]
.User-defined function with error checking
====

.Function
[source,n1ql]
----
CREATE OR REPLACE FUNCTION rstr(vString, vLen) LANGUAGE INLINE AS
CASE
  WHEN NOT IS_STRING(vString)
    THEN ABORT("Search string is not a string")
  WHEN NOT IS_NUMBER(vLen)
    THEN ABORT("Substring length is not a number")
  WHEN vLen > LENGTH(vString)
    THEN ABORT("Substring longer than search string")
  ELSE SUBSTR(vString, LENGTH(vString) - vLen, vLen)
END;
----

.Test invalid string argument
[source,n1ql]
----
EXECUTE FUNCTION rstr(100, 4);
----

.Result
[source,json]
----
[
  {
    "code": 10109,
    "msg": "Error executing function rstr : \"Search string is not a string\" - cause: \"Search string is not a string\""
  }
]
----

.Test invalid number argument
[source,n1ql]
----
EXECUTE FUNCTION rstr("Couchbase", "foo");
----

.Result
[source,json]
----
[
  {
    "code": 10109,
    "msg": "Error executing function rstr : \"Substring length is not a number\" - cause: \"Substring length is not a number\""
  }
]
----

.Test out-of-range value
[source,n1ql]
----
EXECUTE FUNCTION rstr("Couchbase", 10);
----

.Result
[source,json]
----
[
  {
    "code": 10109,
    "msg": "Error executing function rstr : \"Substring longer than search string\" - cause: \"Substring longer than search string\""
  }
]
----

.Test with valid arguments
[source,n1ql]
----
EXECUTE FUNCTION rstr("Couchbase", 4);
----

.Result
[source,json]
----
[
  "base"
]
----
====

[[base64,BASE64()]]
== BASE64(`expression`)

_Alias_: <<base64-encode>>

=== Description

Returns the https://en.wikipedia.org/wiki/Base64[base64^] encoding of the given [.var]`expression`.

=== Arguments

expression:: An expression representing any supported N1QL datatype.

=== Return Value

A string representing the base64 encoding of the input expression.
If the input expression is `missing`, the return value is also `missing`.

=== Example

[[base64-ex,BASE64() Example]]
====
.Query
[source,n1ql]
----
SELECT BASE64([1, 2, 3, 4]) AS `array`,
       BASE64(false) AS `boolean`,
       BASE64(missing) AS `missing`,
       BASE64(null) AS `null`,
       BASE64(1234) AS `number`,
       BASE64( {"a": 1, "b": 2, "c": [1, 2, 3]} ) AS `object`,
       BASE64("Couchbase") AS `string`;
----

.Result
[source,json]
----
[
  {
    "array": "WzEsMiwzLDRd",
    "boolean": "ZmFsc2U=",
    "null": "bnVsbA==",
    "number": "MTIzNA==",
    "object": "eyJhIjoxLCJiIjoyLCJjIjpbMSwyLDNdfQ==",
    "string": "IkNvdWNoYmFzZSI="
  }
]
----
====

[[base64-encode,BASE64_ENCODE()]]
== BASE64_ENCODE(`expression`)

Alias of <<base64>>.

[[base64-decode,BASE64_DECODE()]]
== BASE64_DECODE(`expression`)

=== Description

Reverses the encoding done by the <<base64>> or <<base64-encode>> functions.

=== Arguments

expression:: An expression representing a valid base64-encoded string.

=== Return Value

The decoded value of the input expression.
If the input expression is `missing`, the return value is also `missing`.

=== Example

[[base64-decode-ex,BASE64_DECODE() Example]]
====
.Query
[source,n1ql]
----
SELECT BASE64_DECODE("WzEsMiwzLDRd") AS `array`,
       BASE64_DECODE("ZmFsc2U=") AS `boolean`,
       BASE64_DECODE(missing) AS `missing`,
       BASE64_DECODE("bnVsbA==") AS `null`,
       BASE64_DECODE("MTIzNA==") AS `number`,
       BASE64_DECODE("eyJhIjoxLCJiIjoyLCJjIjpbMSwyLDNdfQ==") AS `object`,
       BASE64_DECODE("IkNvdWNoYmFzZSI=") AS `string`;
----

.Result
[source,json]
----
[
  {
    "array": [
      1,
      2,
      3,
      4
    ],
    "boolean": false,
    "null": null,
    "number": 1234,
    "object": {
      "a": 1,
      "b": 2,
      "c": [
        1,
        2,
        3
      ]
    },
    "string": "Couchbase"
  }
]
----
====

[[flatten_keys,FLATTEN_KEYS()]]
== FLATTEN_KEYS(`expr1` [ ASC | DESC ], `expr2` [ASC | DESC], ...)

ifeval::['{page-component-version}' == '7.1']
_(Introduced in Couchbase Server 7.1)_
endif::[]

=== Description

This function can only be used when defining an index key for an xref:n1ql:n1ql-language-reference/indexing-arrays.adoc[array index].

If you need to index multiple fields within an array, this function enables you to _flatten_ the specified expressions, and index them as if they were separate index keys.
All subsequent index keys are accordingly moved to the right.
Queries will be xref:n1ql-language-reference/selectintro.adoc#index-selection[sargable] and will generate spans.

=== Arguments

expr1, expr2, ...:: [At least 1 and at most 32 argument-values are required]
Each argument is an expression over a field within an array, which constitutes an array index key.
+
Arguments can be modified with `ASC` or `DESC` to specify the xref:n1ql:n1ql-language-reference/createfunction.adoc#index-order[sort order] of the index key.
If this modifier is omitted, the default sort order is `ASC`.
Outside modifiers are not allowed.

Note that `FLATTEN_KEYS()` cannot be used recursively.

=== Return Value

The return value is a flattened list of array elements for use in an array index key.

=== Examples

For examples, refer to xref:n1ql:n1ql-language-reference/indexing-arrays.adoc#examples[Array Indexing Examples].

[[len,LEN()]]
== LEN(`expression`)

ifeval::['{page-component-version}' == '7.1']
_(Introduced in Couchbase Server 7.1)_
endif::[]

=== Description

A general function to return the length of an item.

=== Arguments

expression:: An expression representing any supported N1QL datatype.

=== Return Value

The return value is usually a number, depending on the datatype of the input expression.

[cols="1,3"]
|===
| Input Expression | Return Value

| String
| The number of code points in the string -- equivalent to xref:n1ql-language-reference/stringfun.adoc#fn-str-length[LENGTH()].

| Object
| The field count -- equivalent to xref:n1ql-language-reference/objectfun.adoc#fn-obj-length[OBJECT_LENGTH()].

| Array
| The number of elements -- equivalent to xref:n1ql-language-reference/arrayfun.adoc#fn-array-length[ARRAY_LENGTH()].

| Binary
| The size of the binary object.

| Boolean
| `1`

| Number
| The number of characters in the number's text representation.

| MISSING
| `missing`

| NULL
| `null`
|===

For any item not listed above, the return value is `null`.

=== Example

[[len-ex,LEN() Example]]
====
.Query
[source,n1ql]
----
SELECT LEN([1, 2, 3, 4]) AS `array`,
       LEN(false) AS `boolean`,
       LEN(missing) AS `missing`,
       LEN(null) AS `null`,
       LEN(1234) AS `number`,
       LEN( {"a": 1, "b": 2, "c": [1, 2, 3]} ) AS `object`,
       LEN("Couchbase") AS `string`;
----

.Result
[source,json]
----
[
  {
    "array": 4,
    "boolean": 1,
    "null": null,
    "number": 4,
    "object": 3,
    "string": 9
  }
]
----
====

[[meta,META()]]
== META( {startsb} `keyspace_expr` {endsb} ) {startsb} .`property` {endsb}

=== Description

This function returns the xref:learn:data/data.adoc#metadata[metadata] for the document or keyspace specified by [.var]`keyspace_expr`.
The metadata is returned as a JSON object.

To return a single property from the metadata, you must use a xref:n1ql-language-reference/nestedops.adoc#field-selection[nested expression] containing the `META()` function and the required property, for example `META().id`.
The supported metadata properties are described below.

You can use the `META()` function with a property to xref:n1ql-language-reference/indexing-meta-info.adoc[index metadata information].
Only certain metadata properties are indexable; these are indicated in the description below.

You can also use the `META()` function with a property in the predicate of an xref:n1ql:n1ql-language-reference/join.adoc#section_ek1_jnx_1db[ANSI JOIN Clause].

=== Arguments

keyspace_expr::
[Optional.
Default is current keyspace.]
+
String or an expression that results in a keyspace or a document.
This argument is not required when creating an index, since the `META()` function implicitly uses the keyspace being indexed.

property::
[Optional] The name of a single metadata property.
The property name must be separated from the `META()` function by a dot (`.`) and may be one of the following:

cas:::
// tag::metadata-cas[]
Value representing the current state of an item which changes every time the item is modified.
For details, refer to xref:java-sdk:howtos:concurrent-document-mutations.adoc[Concurrent Document Mutations].
// end::metadata-cas[]
+
This property is indexable.

expiration:::
// tag::metadata-expiration[]
Value representing a document's expiration date.
A value of 0 (zero) means no expiration date.
For details, refer to xref:java-sdk:howtos:kv-operations.adoc#document-expiration[KV Operations].
// end::metadata-expiration[]
+
This property is indexable.

flags:::
Value set by the SDKs for non-JSON documents.
For details, refer to xref:java-sdk:howtos:transcoders-nonjson.adoc[Non-JSON Documents].
+
This property is not indexable.
If you attempt to build an index on this property, an error is returned.

id:::
// tag::metadata-id[]
Value representing a document's unique ID number.
// end::metadata-id[]
+
This property is indexable.

type::: Value for the type of document; currently only `json` is supported.
+
This property is not indexable.
If you attempt to build an index on this property, an error is returned.

=== Return Value

The bare function returns a JSON object containing the specified document's metadata.
When the function is used with a property as part of a nested expression, the expression returns the JSON value of the property.

=== Examples

[[meta-ex1,META() Example 1]]
.Return all metadata
====
[source,n1ql]
----
SELECT META() AS metadata
FROM `travel-sample`.inventory.airline
LIMIT 3;
----

.Results
[source,json]
----
[
  {
      "metadata": {
          "cas": 1583859008179798016,
          "expiration": 0,
          "flags": 33554432,
          "id": "airline_10",
          "type": "json"
      }
  },
  {
      "metadata": {
          "cas": 1583859008180846592,
          "expiration": 0,
          "flags": 33554432,
          "id": "airline_10123",
          "type": "json"
      }
  },
  {
      "metadata": {
          "cas": 1583859008181895168,
          "expiration": 0,
          "flags": 33554432,
          "id": "airline_10226",
          "type": "json"
      }
  }
]
----
====

[[meta-ex2,META() Example 2]]
.Return a single metadata property
====
[source,n1ql]
----
SELECT META().id AS id
FROM `travel-sample`.inventory.airline
LIMIT 3;
----

.Results
[source,json]
----
[
  {
    "id": "airline_10"
  },
  {
    "id": "airline_10123"
  },
  {
    "id": "airline_10226"
  }
]
----
====

[[meta-ex3,META() Example 3]]
.Return a single metadata property for a specified keyspace
====
[source,n1ql]
----
SELECT META(route).id AS id -- <1>
FROM `travel-sample`.inventory.route
JOIN `travel-sample`.inventory.airport
ON route.sourceairport = airport.faa
WHERE airport.city = "Paris"
LIMIT 3;
----

.Results
[source,json]
----
[
  {
    "id": "route_10136"
  },
  {
    "id": "route_10137"
  },
  {
    "id": "route_10138"
  }
]
----
====

<1> You must specify a keyspace for the `META()` function because there is more than one FROM term.

For examples showing how to index metadata information, refer to xref:n1ql-language-reference/indexing-meta-info.adoc[Indexing Meta Info].

For examples showing how to use metadata information in the predicate of an ANSI JOIN clause, refer to xref:n1ql:n1ql-language-reference/join.adoc[JOIN Clause].

[[pairs,PAIRS()]]
== PAIRS(`obj`)

=== Description

This function generates an array of arrays of {startsb}[.var]``field_name``, ``value``{endsb} pairs of all possible fields in the given JSON object [.var]`obj`.

NOTE: Nested sub-object fields are explored recursively.

=== Arguments

obj:: An xref:n1ql-language-reference/constructionops.adoc#object-construction[object constructor].

=== Return Value

Array of {startsb}[.var]``field_name``, ``value``{endsb} arrays for each field in the input object [.var]`obj`.

* If [.var]`obj` has nested objects, then fields of such nested sub-objects are also explored and corresponding inner-array elements are produced.
* If [.var]`obj` is an array, then each element of the array is explored and corresponding inner-array elements are produced.
* If [.var]`obj` is a primitive data type of integer or string, then it returns NULL, as they don't have a name.
* If [.var]`obj` is an array of primitive data types, then it returns an empty array `[]`.
* If [.var]`obj` is an array of objects, then it returns an array of objects.

[NOTE]
====
When the field_name is in curly brackets, it's treated as an array and returns an array; but without curly bracket, it's treated as a primitive data type and returns NULL.
For example,

* `PAIRS(public_likes)` returns NULL
* `+PAIRS({public_likes})+` returns an array
====

=== Examples

[[pairs-example1,PAIRS() Example 1]]
.Input value of a nested object
====
.Query
[source,n1ql]
----
SELECT t        AS orig_t,
       PAIRS(t) AS pairs_t
FROM   `travel-sample`.inventory.airport t
LIMIT  1;
----

.Result
[source,json]
----
[
  {
    "orig_t": {
      "airportname": "Calais Dunkerque",
      "city": "Calais",
      "country": "France",
      "faa": "CQF",
      "geo": {
        "alt": 12,
        "lat": 50.962097,
        "lon": 1.954764
      },
      "icao": "LFAC",
      "id": 1254,
      "type": "airport",
      "tz": "Europe/Paris"
    },
    "pairs_t": [
      [
        "id",
        1254
      ],
      [
        "city",
        "Calais"
      ],
      [
        "faa",
        "CQF"
      ],
      [
        "geo",
        {
          "alt": 12,
          "lat": 50.962097,
          "lon": 1.954764
        }
      ],
      [
        "lon",
        1.954764
      ],
      [
        "alt",
        12
      ],
      [
        "lat",
        50.962097
      ],
      [
        "type",
        "airport"
      ],
      [
        "tz",
        "Europe/Paris"
      ],
      [
        "airportname",
        "Calais Dunkerque"
      ],
      [
        "country",
        "France"
      ],
      [
        "icao",
        "LFAC"
      ]
    ]
  }
]
----
====

[[pairs-example2,PAIRS() Example 2]]
.Input value of an array
====
.Query
[source,n1ql]
----
SELECT public_likes          AS orig_t,
       PAIRS(public_likes)   AS pairs_array_t,
       PAIRS({public_likes}) AS pairs_obj_t
FROM   `travel-sample`.inventory.hotel
LIMIT  1;
----

.Result
[source,json]
----
[
  {
    "orig_t": [
      "Julius Tromp I",
      "Corrine Hilll",
      "Jaeden McKenzie",
      "Vallie Ryan",
      "Brian Kilback",
      "Lilian McLaughlin",
      "Ms. Moses Feeney",
      "Elnora Trantow"
    ],
    "pairs_array_t": [],
    "pairs_obj_t": [
      [
        "public_likes",
        [
          "Julius Tromp I",
          "Corrine Hilll",
          "Jaeden McKenzie",
          "Vallie Ryan",
          "Brian Kilback",
          "Lilian McLaughlin",
          "Ms. Moses Feeney",
          "Elnora Trantow"
        ]
      ],
      [
        "public_likes",
        "Julius Tromp I"
      ],
      [
        "public_likes",
        "Corrine Hilll"
      ],
      [
        "public_likes",
        "Jaeden McKenzie"
      ],
      [
        "public_likes",
        "Vallie Ryan"
      ],
      [
        "public_likes",
        "Brian Kilback"
      ],
      [
        "public_likes",
        "Lilian McLaughlin"
      ],
      [
        "public_likes",
        "Ms. Moses Feeney"
      ],
      [
        "public_likes",
        "Elnora Trantow"
      ]
    ]
  }
]
----
====

[[pairs-example3a,PAIRS() Example 3a]]
.Input value of a primitive (field document string) data type
====
.Query
[source,n1ql]
----
SELECT country        AS orig_t,
       PAIRS(country) AS pairs_t
FROM   `travel-sample`.inventory.airport
LIMIT  1;
----

.Result
[source,json]
----
[
  {
    "orig_t": "France",
    "pairs_t": null
  }
]
----
====

[[pairs-example3b,PAIRS() Example 3b]]
.Input value of a primitive (constant) data type
====
.Query
[source,n1ql]
----
SELECT PAIRS("N1QL")             AS constant_string,
       PAIRS(4)                  AS constant_int,
       PAIRS([1,2,3])            AS constant_int_array,
       PAIRS({"name" : 3})       AS object_constant_int,
       PAIRS({"name" : [1,2,3]}) AS object_constant_int_array;
----

.Result
[source,json]
----
[
  {
    "constant_int": null,
    "constant_int_array": [],
    "constant_string": null,
    "object_constant_int": [
      [
        "name",
        3
      ]
    ],
    "object_constant_int_array": [
      [
        "name",
        [
          1,
          2,
          3
        ]
      ],
      [
        "name",
        1
      ],
      [
        "name",
        2
      ],
      [
        "name",
        3
      ]
    ]
  }
]
----
====

[[pairs-example4,PAIRS() Example 4]]
.Input value of an array of objects
====
.Query
[source,n1ql]
----
SELECT reviews[*].ratings,
       PAIRS({reviews[*].ratings}) AS pairs_t
FROM   `travel-sample`.inventory.hotel
LIMIT  1;
----

.Result
[source,json]
----
[
  {
    "pairs_t": [
      [
        "ratings",
        [
          {
            "Cleanliness": 5,
            "Location": 4,
            "Overall": 4,
            "Rooms": 3,
            "Service": 5,
            "Value": 4
          },
          {
            "Business service (e.g., internet access)": 4,
            "Check in / front desk": 4,
            "Cleanliness": 4,
            "Location": 4,
            "Overall": 4,
            "Rooms": 3,
            "Service": 3,
            "Value": 5
          }
        ]
      ],
      [
        "ratings",
        {
          "Cleanliness": 5,
          "Location": 4,
          "Overall": 4,
          "Rooms": 3,
          "Service": 5,
          "Value": 4
        }
      ],
      [
        "ratings",
        {
          "Business service (e.g., internet access)": 4,
          "Check in / front desk": 4,
          "Cleanliness": 4,
          "Location": 4,
          "Overall": 4,
          "Rooms": 3,
          "Service": 3,
          "Value": 5
        }
      ],
      [
        "Cleanliness",
        5
      ],
      [
        "Location",
        4
      ],
      [
        "Overall",
        4
      ],
      [
        "Rooms",
        3
      ],
      [
        "Service",
        5
      ],
      [
        "Value",
        4
      ],
      [
        "Cleanliness",
        4
      ],
      [
        "Location",
        4
      ],
      [
        "Rooms",
        3
      ],
      [
        "Value",
        5
      ],
      [
        "Business service (e.g., internet access)",
        4
      ],
      [
        "Check in / front desk",
        4
      ],
      [
        "Overall",
        4
      ],
      [
        "Service",
        3
      ]
    ],
    "ratings": [
      {
        "Cleanliness": 5,
        "Location": 4,
        "Overall": 4,
        "Rooms": 3,
        "Service": 5,
        "Value": 4
      },
      {
        "Business service (e.g., internet access)": 4,
        "Check in / front desk": 4,
        "Cleanliness": 4,
        "Location": 4,
        "Overall": 4,
        "Rooms": 3,
        "Service": 3,
        "Value": 5
      }
    ]
  }
]
----
====

[[uuid,UUID()]]
== UUID()

=== Description

Generates a universally unique identifier (UUID) according to https://www.ietf.org/rfc/rfc4122.txt[RFC 4122^].

=== Arguments

None.

=== Return Value

A string representing a version 4 UUID.

=== Example

[[uuid-ex,UUID() Example]]
====
This query will return a different UUID each time you run it.

.Query
[source,n1ql]
----
SELECT UUID() AS uuid;
----

.Results
[source,json]
----
[
  {
    "uuid": "2ca78bd8-0a28-4d68-995f-0da5e20e0964"
  }
]
----
====

For further examples using `UUID()`, refer to the xref:n1ql-language-reference/insert.adoc[INSERT] and xref:n1ql-language-reference/merge.adoc[MERGE] statements.
