= Object Functions
:description: pass:q[If you want to try the examples on this page, you must first run the following query to insert additional data to the `travel-sample` bucket.]
:page-topic-type: concept

[#load-example-data]
{description}

WARNING: Please note that the query below will alter the data in your sample buckets.
To restore your sample data, remove and reinstall the `travel-sample` bucket.
Refer to xref:manage:manage-settings/install-sample-buckets.adoc[Sample Buckets] for details.

[source,n1ql]
----
UPDATE `travel-sample`.inventory.route
SET schedule[0] = {"day" : 7, "special_flights": [
                    {"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                    {"flight": "AI333", "utc": "3:33:33"},
                    {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}
                  ] }
WHERE destinationairport = "CDG" AND sourceairport = "TLV";
----


:load-example-warning: pass:q[Make sure that you have run the `UPDATE` command described in xref:load-example-data[this section] before running the example(s).]

== OBJECT_ADD()

This function adds new attributes and values to a given object and returns the updated object.

----
OBJECT_ADD(object, new_attr_key, new_attr_value)
----

Note that:

* This function does not perform key substitution.
* If you add a duplicate attribute (that is, if the key is found), it returns an error or NULL object.
* If [.var]`new_attr_key` or [.var]`new_attr_value` is MISSING, or if [.var]`new_attr_key` is NULL, it returns the [.var]`object` unmodified.
* If [.var]`object` is not an object or NULL, it returns a NULL value object.

=== Examples

====
.Example
[source,n1ql]
----
SELECT schedule[0] AS original,
       OBJECT_ADD(schedule[0], "day_new", 1) AS output
FROM `travel-sample`.inventory.route
LIMIT 1;
----

.Results
[source,json]
----
[
  {
    "original": {
      "day": 0,
      "flight": "AF198",
      "utc": "10:13:00"
    },
    "output": {
      "day": 0,
      "day_new": 1,
      "flight": "AF198",
      "utc": "10:13:00"
    }
  }
]
----
====

[[fn-obj-concat,OBJECT_CONCAT()]]
== OBJECT_CONCAT(`expr`, `expr` ...)

=== Description

This function concatenates the input objects and returns a new object.
It requires a minimum of two input objects.

=== Arguments

expr:: An expression representing an object.

=== Returns

An object constructed by concatenating all the input objects.
If any of the input objects contain the same attribute name, the attribute from the last relevant object in the input list is copied to the output, and similarly-named attributes from earlier objects in the input list are ignored.

=== Examples

====
.Example
[source,n1ql]
----
SELECT OBJECT_CONCAT({"abc":1},{"def":2},{"fgh":3},{"fgh":4},{"fgh": [5, 6, 7]});
----

.Results
[source,json]
----
[
  {
    "$1": {
      "abc": 1,
      "def": 2,
      "fgh": [
        5,
        6,
        7
      ]
    }
  }
]
----
====

[[fn-obj-inner-pairs,OBJECT_INNER_PAIRS()]]
== OBJECT_INNER_PAIRS(`expression`)

=== Description

This function returns an array of objects, containing the names and values of each attribute in the input object.
It is particularly useful when iterating over multiple objects in an array, as it collates the values from similarly-named attributes into a single nested array.

In this case, the function does not return a value from any object which does not contain the shared attribute name, rather like an INNER JOIN.
For an illustration, refer to the examples below.

=== Arguments

expression:: An expression representing an object.

=== Return Value

An array of objects, each containing two attributes:

name:: The name of an attribute in the source object.

val:: The value of an attribute in the source object; or an array, containing the collated values of similarly-named attributes in the source objects.

The objects in the array are sorted by attribute name, in N1QL collation order.

=== Examples

.Single object
====
.Query
[source,n1ql]
----
SELECT OBJECT_INNER_PAIRS({"flight": "AI444", "utc": "4:44:44", "codename": "green"}) AS inner_pairs;
----

.Results
[source,json]
----
[
  {
    "inner_pairs": [
      {
        "name": "codename",
        "val": "green"
      },
      {
        "name": "flight",
        "val": "AI444"
      },
      {
        "name": "utc",
        "val": "4:44:44"
      }
    ]
  }
]
----
====

.Iterating over objects in an array
====
In this example, notice that where the source objects have similarly-named attributes, the values from each of those attributes are collated into a single array in the output.

.Example
[source,n1ql]
----
WITH special_flights AS ([{"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                          {"flight": "AI333", "utc": "3:33:33", "alert": "red"},
                          {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}])
SELECT OBJECT_INNER_PAIRS(special_flights[*]) AS inner_pairs;
----

.Results
[source,json]
----
[
  {
    "inner_pairs": [
      {
        "name": "alert",
        "val": "red"
      },
      {
        "name": "codename",
        "val": [
          "green",
          "yellow"
        ]
      },
      {
        "name": "flight",
        "val": [
          "AI444",
          "AI333",
          "AI222"
        ]
      },
      {
        "name": "utc",
        "val": [
          "4:44:44",
          "3:33:33",
          "2:22:22"
        ]
      }
    ]
  }
]
----
====

[[fn-obj-inner-values,OBJECT_INNER_VALUES()]]
== OBJECT_INNER_VALUES(`expression`)

=== Description

This function returns an array, containing the values of each attribute in the input object.
It is particularly useful when iterating over multiple objects in an array, as it collates the values from similarly-named attributes into a single nested array.

In this case, the function does not return a value from any object which does not contain the shared attribute name, rather like an INNER JOIN.
For an illustration, refer to the examples below.

=== Arguments

expression:: An expression representing an object.

=== Return Value

An array of the values contained within the source object.
The values in the array are sorted by the corresponding attribute names in the source object, in N1QL collation order.

=== Examples

.Single object
====
.Example
[source,n1ql]
----
SELECT OBJECT_INNER_VALUES({"flight": "AI444", "utc": "4:44:44", "codename": "green"}) AS inner_values;
----

.Results
[source,json]
----
[
  {
    "inner_values": [
      "green",
      "AI444",
      "4:44:44"
    ]
  }
]
----
====

.Iterating over objects in an array
====
In this example, notice that where the source objects have similarly-named attributes, the values from each of those attributes are collated into a single array in the output.

.Example
[source,n1ql]
----
WITH special_flights AS ([{"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                          {"flight": "AI333", "utc": "3:33:33", "alert": "red"},
                          {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}])
SELECT OBJECT_INNER_VALUES(special_flights[*]) AS inner_values;
----

.Results
[source,json]
----
[
  {
    "inner_values": [
      "red",
      [
        "green",
        "yellow"
      ],
      [
        "AI444",
        "AI333",
        "AI222"
      ],
      [
        "4:44:44",
        "3:33:33",
        "2:22:22"
      ]
    ]
  }
]
----
====

== OBJECT_LENGTH(expression)

This function returns the number of name-value pairs in the object.
You can specify an object or an expression that evaluates to an object.

IMPORTANT: {load-example-warning}

.Example
[source,n1ql]
----
SELECT OBJECT_LENGTH(R.schedule[0])
FROM `travel-sample`.inventory.route AS R
LIMIT 1;
----

.Results
[source,json]
----
[
    {
        "$1": 3
    }
]
----

== OBJECT_NAMES(expression)

This function returns an array containing the attribute names of the object, in N1QL collation order.

IMPORTANT: {load-example-warning}

.Example
[source,n1ql]
----
SELECT OBJECT_NAMES(R.schedule[0])
FROM `travel-sample`.inventory.route AS R
LIMIT 1;
----
.Results
[source,json]
----
[
  {
    "$1": [
      "day",
      "flight",
      "utc"
    ]
  }
]
----

[[fn-obj-pairs,OBJECT_PAIRS()]]
== OBJECT_PAIRS(`expression`)

_Alias_: *OBJECT_OUTER_PAIRS(expression)*

=== Description

This function returns an array of objects, containing the names and values of each attribute in the input object.
It is particularly useful when iterating over multiple objects in an array, as it collates the values from similarly-named attributes into a single nested array.

In this case, the function returns a null entry from any object which does not contain the shared attribute name, rather like an OUTER JOIN.
For an illustration, refer to the examples below.

=== Arguments

expression:: An expression representing an object.

=== Return Value

An array of objects, each containing two attributes:

name:: The name of an attribute in the source object.

val:: The value of an attribute in the source object; or an array, containing the collated values of similarly-named attributes in the source objects.

The objects in the array are sorted by attribute name, in N1QL collation order.

=== Examples

.Single object
====
.Query
[source,n1ql]
----
SELECT OBJECT_PAIRS({"flight": "AI444", "utc": "4:44:44", "codename": "green"}) AS outer_pairs;
----

.Results
[source,json]
----
[
  {
    "outer_pairs": [
      {
        "name": "codename",
        "val": "green"
      },
      {
        "name": "flight",
        "val": "AI444"
      },
      {
        "name": "utc",
        "val": "4:44:44"
      }
    ]
  }
]
----
====

.Iterating over objects in an array
====
In this example, notice that where the source objects have similarly-named attributes, the values from each of those attributes are collated into a single array in the output.

.Example
[source,n1ql]
----
WITH special_flights AS ([{"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                          {"flight": "AI333", "utc": "3:33:33", "alert": "red"},
                          {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}])
SELECT OBJECT_PAIRS(special_flights[*]) AS outer_pairs;
----

.Results
[source,json]
----
[
  {
    "outer_pairs": [
      {
        "name": "alert",
        "val": [
          null,
          "red",
          null
        ]
      },
      {
        "name": "codename",
        "val": [
          "green",
          null,
          "yellow"
        ]
      },
      {
        "name": "flight",
        "val": [
          "AI444",
          "AI333",
          "AI222"
        ]
      },
      {
        "name": "utc",
        "val": [
          "4:44:44",
          "3:33:33",
          "2:22:22"
        ]
      }
    ]
  }
]
----
====
Starting Couchbase Server version 4.6.0, the results generated by this function use the word "val" for value instead of the N1QL reserved word "value".

For example:

----
"results": [
    { "$1": [ { "name": "key1", "val": "val1" } ]
    }
]
----
====

== OBJECT_PUT()

This function adds new or updates existing attributes and values to a given object, and returns the updated object.

----
OBJECT_PUT(object, attr_key, attr_value)
----

Note that:

* If [.var]`attr_key` is found in the object, it replaces the corresponding attribute value by [.var]`attr_value`.
* If [.var]`attr_value` is MISSING, it deletes the corresponding existing key (if any), like [.cmd]`object_remove()`.
* If [.var]`attr_key` is MISSING, it returns a MISSING value.
* If [.var]`attr_key` is not an object, it returns a NULL value.

=== Examples

====
.Example
[source,n1ql]
----
SELECT schedule[0] AS original,
       OBJECT_PUT(schedule[0], "day", 1) AS output
FROM `travel-sample`.inventory.route
LIMIT 1;
----

.Results
[source,json]
----
[
  {
    "original": {
      "day": 0,
      "flight": "AF198",
      "utc": "10:13:00"
    },
    "output": {
      "day": 1,
      "flight": "AF198",
      "utc": "10:13:00"
    }
  }
]
----
====

[[fn-obj-rename,OBJECT_RENAME()]]
== OBJECT_RENAME(`input_obj`, `old_field`, `new_field`)

=== Description

Renames the attribute `old_field` to `new_field` in the JSON input object `input_obj`.

=== Arguments

input_obj:: Any JSON object, or N1QL expression that can evaluate to a JSON object, representing the search object.

old_field:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, representing the old (original) attribute name inside the JSON object `input_obj`.

new_field:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, representing the new attribute name to replace `old_field` inside the JSON object `input_obj`.

=== Return Value

The input object with the new attribute name.
Note that if the new attribute name already exists in the input object, the original attribute with that name is replaced.

=== Examples

.Changing the field name
====
.Example
[source,n1ql]
----
SELECT t AS original,
       OBJECT_RENAME(t, "name", "new_name") AS output
FROM `travel-sample`.inventory.airline AS t
LIMIT 1;
----

.Results
[source,json]
----
[
  {
    "original": {
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "name": "40-Mile Air",
      "type": "airline"
    },
    "output": {
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "new_name": "40-Mile Air",
      "type": "airline"
    }
  }
]
----
====

== OBJECT_REMOVE()

This function removes the specified attribute and corresponding values from the given object.

----
OBJECT_REMOVE(object, attr_key)
----

Note that:

* If the [.var]`attr_key` is MISSING, it returns a MISSING value.
* If the [.var]`attr_key` is not an object, it returns a NULL value.

=== Examples

====
.Example
[source,n1ql]
----
SELECT schedule[0] AS original,
       OBJECT_REMOVE(schedule[0], "day") AS output
FROM `travel-sample`.inventory.route
LIMIT 1;
----

.Results
[source,json]
----
[
  {
    "original": {
      "day": 0,
      "flight": "AF198",
      "utc": "10:13:00"
    },
    "output": {
      "flight": "AF198",
      "utc": "10:13:00"
    }
  }
]
----
====

====
.Example
[source,n1ql]
----
SELECT OBJECT_REMOVE( {"abc":1,"def":2,"fgh":3},"def");
----

.Results
[source,json]
----
{
    "requestID": "ddddde59-e648-4ed7-a772-f25e7a522acc",
    "signature":
    { "$1": "object" }
    ,
    "results": [
        {
            "$1": { "abc": 1, "fgh": 3 }
        }
    ],
    "status": "success",
    "metrics":
    { "elapsedTime": "778.603µs",
      "executionTime": "750.448µs",
      "resultCount": 1,
      "resultSize": 96 }
}
----
====

== OBJECT_REPLACE(input_obj, old_value, new_value)

*Description*:: Replaces all occurrences of the value `value_old` to `value_new` in the JSON input object `input_obj`.

*Arguments*::
*input_obj*;; Any JSON object, or N1QL expression that can evaluate to a JSON object, representing the search object.

*old_value*;; A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, representing the old (original) value name inside the JSON object `input_obj`.

*new_value*;; A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, representing the new value name to replace `old_value` inside the JSON object `input_obj`.

=== Examples

.Replace any occurrences of "airline" with "airplane"
====

.Example
[source,n1ql]
----
SELECT t AS original,
       OBJECT_REPLACE(t, "airline", "airplane") AS output
FROM `travel-sample`.inventory.airline AS t
LIMIT 1;
----

.Results
[source,json]
----
[
  {
    "original": {
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "name": "40-Mile Air",
      "type": "airline"
    },
    "output": {
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "name": "40-Mile Air",
      "type": "airplane"
    }
  }
]
----
====

== OBJECT_UNWRAP(expression)

This function enables you to unwrap an object without knowing the name in the name-value pair.
It accepts only one argument and if the argument is an object with exactly one name-value pair, this function returns the value in the name-value pair.
If the argument is MISSING, it returns MISSING.
For all other cases, it returns NULL.

IMPORTANT: {load-example-warning}

.Example
----
SELECT OBJECT_UNWRAP( {"name": "value"} );

"results" : [
    {
        "$1": "value"
    }
]
[[fn-obj-values,OBJECT_VALUES()]]
== OBJECT_VALUES(expression)

_Alias_: *OBJECT_OUTER_VALUES(expression)*

=== Description

This function returns an array, containing the values of each attribute in the input object.
It is particularly useful when iterating over multiple objects in an array, as it collates the values from similarly-named attributes into a single nested array.

In this case, the function returns a null entry from any object which does not contain the shared attribute name, rather like an OUTER JOIN.
For an illustration, refer to the examples below.

=== Arguments

expression:: An expression representing an object.

=== Return Value

An array of the values contained within the source object.
The values in the array are sorted by the corresponding attribute names in the source object, in N1QL collation order.

=== Examples

.Single object
====
.Example
[source,n1ql]
----
SELECT OBJECT_VALUES({"flight": "AI444", "utc": "4:44:44", "codename": "green"}) AS outer_values;
----

.Results
[source,json]
----
[
  {
    "outer_values": [
      "green",
      "AI444",
      "4:44:44"
    ]
  }
]
----
====

.Iterating over objects in an array
====
In this example, notice that where the source objects have similarly-named attributes, the values from each of those attributes are collated into a single array in the output.

.Example
[source,n1ql]
----
WITH special_flights AS ([{"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                          {"flight": "AI333", "utc": "3:33:33", "alert": "red"},
                          {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}])
SELECT OBJECT_VALUES(special_flights[*]) AS outer_values;
----

.Results
[source,json]
----
[
  {
    "outer_values": [
      [
        null,
        "red",
        null
      ],
      [
        "green",
        null,
        "yellow"
      ],
      [
        "AI444",
        "AI333",
        "AI222"
      ],
      [
        "4:44:44",
        "3:33:33",
        "2:22:22"
      ]
    ]
  }
]
----
====
