= Pattern-Matching Functions
:page-topic-type: reference

Pattern-matching functions allow you to find regular expression patterns in strings or attributes.
Regular expressions can formally represent various string search patterns using different special characters to indicate wildcards, positional characters, repetition, optional or mandatory sequences of letters, etc.
N1QL functions are available to find matching patterns, find position of matching pattern, or replace a pattern with a new string.

For more information on all supported REGEX patterns, see https://golang.org/pkg/regexp/syntax/[^].

NOTE: Couchbase Server 4.x N1QL supports regular expressions supported by The Go Programming Language version 1.4.2.
From Couchbase Server 5.0, The Go Programming Language version 1.8 is supported.

[#section_regex_contains]
== REGEXP_CONTAINS(`expression`, `pattern`)

This function has an alias <<aliases,REGEX_CONTAINS()>>.

=== Arguments

expression:: String, or any N1QL expression that evaluates to a string.

pattern:: String representing a supported regular expression.

=== Return Value

Returns TRUE if the string value contains any sequence that matches the regular expression pattern.

=== Example

====
[source,N1QL]
----
SELECT name
FROM `travel-sample`
WHERE type = "landmark" AND REGEXP_CONTAINS(name, "In+.*")
LIMIT 5;
----

.Results
[source,json]
----
[
  {
    "name": "Beijing Inn"
  },
  {
    "name": "Sportsman Inn"
  },
  {
    "name": "In-N-Out Burger"
  },
  {
    "name": "Mel's Drive-In"
  },
  {
    "name": "Inverness Castle"
  }
]
----
====

[#section_regex_like]
== REGEXP_LIKE(`expression`, `pattern`)

This function has an alias <<aliases,REGEX_LIKE()>>.

=== Arguments

expression:: String, or any N1QL expression that evaluates to a string.

pattern:: String representing a supported regular expression.

=== Return Value

Returns TRUE if the string value exactly matches the regular expression pattern.

=== Example

====
[source,N1QL]
----
SELECT name
FROM `travel-sample`
WHERE type = "landmark" and REGEXP_LIKE(name, "In+.*")
LIMIT 5;
----

.Results
[source,json]
----
[
  {
    "name": "In-N-Out Burger"
  },
  {
    "name": "Inverness Castle"
  },
  {
    "name": "Inverness Museum & Art Gallery"
  },
  {
    "name": "Inverness Botanic Gardens"
  },
  {
    "name": "International Petroleum Exchange"
  }
]
----
====

[#section_regex_position]
== REGEXP_POSITION(`expression`, `pattern`)

This function has an alias <<aliases,REGEX_POSITION()>>.

=== Arguments

expression:: String, or any N1QL expression that evaluates to a string.

pattern:: String representing a supported regular expression.

=== Return Value

Returns first position of the occurrence of the regular expression _pattern_ within the input string _expression_.
Returns -1 if no match is found.
Position counting starts from zero.

=== Example

====
The following query finds positions of first occurrence of vowels in each word of the _name_ attribute.

[source,N1QL]
----
SELECT name, ARRAY REGEXP_POSITION(x, "[aeiou]") FOR x IN TOKENS(name) END
FROM `travel-sample`
WHERE type = "hotel"
LIMIT 2;
----

.Results
[source,json]
----
[
  {
    "$1": [
      1,
      1,
      1
    ],
    "name": "Medway Youth Hostel"
  },
  {
    "$1": [
      1,
      2,
      1
    ],
    "name": "The Balmoral Guesthouse"
  }
]
----
====

[#section_regex_replace]
== REGEXP_REPLACE(`expression`, `pattern`, `repl` [, `n`])

This function has an alias <<aliases,REGEX_REPLACE()>>.

=== Arguments

expression:: String, or any N1QL expression that evaluates to a string.

pattern:: String representing a supported regular expression.

repl:: String, or any N1QL expression that evaluates to a string.

n:: [Optional] The maximum number of times to find and replace the matching pattern.

=== Return Value

Returns new string with occurrences of pattern replaced with _repl_.
If _n_ is given, at the most _n_ replacements are performed.
If _n_ is not provided, all matching occurrences are replaced.

=== Examples

.{blank}
====
[source,N1QL]
----
SELECT REGEXP_REPLACE("N1QL is Sql(infact, sql++) for NoSql", "[sS][qQ][lL]", "SQL"),
       REGEXP_REPLACE("Winning innings Inn", "[Ii]n+", "Hotel", 6),
       REGEXP_REPLACE("Winning innings Inn", "[IiNn]+g", upper("inning"), 2);
----

.Results
[source,json]
----
[
  {
    "$1": "N1QL is SQL(infact, SQL++) for NoSQL",
    "$2": "WHotelHotelg HotelHotelgs Hotel",
    "$3": "WINNING INNINGs Inn"
  }
]
----
====

.{blank}
====
In this example, the query retrieves first 4 documents and replaces the pattern of repeating n with emphasized ‘NNNN’.

[source,N1QL]
----
SELECT name, REGEXP_REPLACE(name, "n+", "NNNN") as new_name
FROM `travel-sample`
LIMIT 4;
----

.Results
[source,json]
----
[
  {
    "name": "40-Mile Air",
    "new_name": "40-Mile Air"
  },
  {
    "name": "Texas Wings",
    "new_name": "Texas WiNNNNgs"
  },
  {
    "name": "Atifly",
    "new_name": "Atifly"
  },
  {
    "name": "Jc royal.britannica",
    "new_name": "Jc royal.britaNNNNica"
  }
]
----
====

[[aliases]]
== Aliases

Each pattern-matching function has an alias whose name begins with `REGEX_`.

* `REGEX_CONTAINS()` is an alias for <<section_regex_contains,REGEXP_CONTAINS()>>.
* `REGEX_LIKE()` is an alias for <<section_regex_like,REGEXP_LIKE()>>.
* `REGEX_POSITION()` is an alias for <<section_regex_position,REGEXP_POSITION()>>.
* `REGEX_REPLACE()` is an alias for <<section_regex_replace,REGEXP_REPLACE()>>.