= PREPARE
:page-type: concept

== PREPARE statement

_prepare:_

----
 PREPARE [ name ( FROM | AS ) ] statement
----

The PREPARE statement prepares a query.
A name can optionally be specified.
A JSON array is returned that contains one result that has the properties:

* [.param]`name`: If present, this will be the name given to the PREPARE statement.
If not, a name is generated.
* [.param]`operator`: the execution plan of the statement being prepared.
* [.param]`signature`: the signature of the statement being prepared.
* [.param]`text`: the full PREPARE statement text.
* [.param]`encoded_plan`: the full prepared statement in encoded format.
The encoded plan can be included in addition to the prepared parameter in a request to execute a prepared statement.
If the name given by the prepared parameter is unrecognized, the query engine will decode and execute the prepared statement given by the [.param]`encoded_plan` parameter.
The decoded prepared statement will be saved by the query engine so the next request that uses its name will succeed.

Repeatedly preparing a statement with the same name will result in the statement being overwritten.
A PREPARE statement that uses a name that was used for a different statement will result in a duplicate name error.

Prepared statements are stored in memory until you restart the Couchbase Server.
After restarting the server, you must prepare the statements again before you can execute the prepared statements.

For information on how to use prepared statements with various SDKs, refer to xref:java-sdk::common/n1ql-query.adoc#prepare-stmts[Querying with N1QL] and xref:nodejs-sdk::n1ql-queries-with-sdk.adoc[N1QL from the SDK].

*RBAC Privileges*

User executing the PREPARE statement must have the privileges of the statement being prepared.
For more details about user roles, see xref:security:security-authorization.adoc[Authorization].

For example,

To execute the following statement, user must have the _Query Select_ privilege on both keyspaces `pass:c[`travel-sample`]` and `pass:c[`beer-sample`]`.

----
PREPARE SELECT * FROM `travel-sample`
WHERE city = (SELECT RAW city FROM `beer-sample`)
----

To execute the following statement, user must have the _Query Update_ and _Query Select_ privileges on `pass:c[`travel-sample`]`.

----
PREPARE UPDATE `travel-sample`
SET city = "San Francisco" WHERE lower(city) = "sanfrancisco"
RETURNING *
----

== EXECUTE statement

For details, see xref:n1ql-language-reference/execute.adoc[EXECUTE].
