= String Functions
:description: String functions perform operations on a string input value and returns a string or other value.
:page-topic-type: reference

{description}

NOTE: If any arguments to any of the following functions are [.out]`MISSING` then the result is also [.out]`MISSING` (i.e.
no result is returned).
Similarly, if any of the arguments passed to the functions are `NULL` or are of the wrong type (e.g.
an integer instead of a string), then `NULL` is returned as the result.

[#fn-str-concat]
== CONCAT([.var]`string1`, [.var]`string2`, …)

=== Description
This function takes two or more strings and returns a new string after concatenating the input strings.
If there are fewer than two arguments, then it returns an error.

=== Arguments
string1, string2, \...:: [At least 2 are required] The strings, or valid xref:n1ql-language-reference/index.adoc[expressions] which evaluate to strings, to be concatenated together.

=== Return Value
A new string, concatenated from the input strings.

=== Examples
====
[source,n1ql]
----
SELECT CONCAT("abc", "def", "ghi") AS concat;
----

[source,json]
----
[
  {
    "concat": "abcdefghi"
  }
]
----
====

[#fn-str-concat2]
== CONCAT2([.var]`separator`, [.var]`arg1`, [.var]`arg2`, …)

=== Description
This function takes the input strings, or arrays of strings, and concatenates them with the specified separator between each input string.
If there are fewer than two arguments, then it returns an error.

=== Arguments
separator:: [Required] The string to separate the input strings.
If no separator is required, specify the empty string "".

arg1, arg2, \...:: [At least 1 is required] The strings, or arrays of strings, to be concatenated together.

=== Return Value
A new string, concatenated from the inputs, with the separator between each input.
Arrays of strings are flattened and concatenated in the same order.
If there is only one string argument, the separator is not used.

If any argument or array element is MISSING, returns MISSING.
If any argument or array element is non-string, returns NULL.

=== Examples
====
[source,n1ql]
----
SELECT CONCAT2('-','a','b',['c','d'],['xyz']) AS c1,
CONCAT2('-','a') AS c2,
CONCAT2('-',['b']) AS c3;
----

[source,json]
----
[
  {
    "c1": "a-b-c-d-xyz",
    "c2": "a",
    "c3": "b"
  }
]
----
====

[#fn-str-contains]
== CONTAINS(in_str, search_str)

=== Description
Checks whether or not the specified search string is a substring of the input string (i.e.
exists within).
This returns `true` if the substring exists within the input string, otherwise `false` is returned.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to search within.

search_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to search for.

=== Return Value
A boolean, representing whether the search string exists within the input string.

=== Examples
====
[source,n1ql]
----
SELECT CONTAINS("N1QL is awesome", "N1QL") as n1ql,
       CONTAINS("N1QL is awesome", "SQL") as no_sql;
----

[source,json]
----
{
    "results": [
        {
            "n1ql": true,
            "no_sql": false
        }
    ]
}
----
====

[#fn-str-initcap]
== INITCAP(in_str)

=== Description
Converts the string so that the first letter of each word is uppercase and every other letter is lowercase (known as 'Title Case').

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to convert to title case.

=== Return Value
A string, representing the input string converted to title case.

=== Limitations
This function capitalizes the initial letter of every word in the sentence, this means that even short words such as "the" and "or" will be capitalized.
This does not strictly follow title case conventions used in the writing domain.

=== Examples
====
[source,n1ql]
----
SELECT INITCAP("N1QL is awesome") as n1ql;
----

[source,json]
----
{
    "results": [
        {
            "n1ql": "N1ql Is Awesome"
        }
    ]
}
----
====

[#fn-str-length]
== LENGTH(in_str)

_Equivalent_: xref:n1ql-language-reference/metafun.adoc#len[LEN()]

=== Description
Finds the length of a string, where length is defined as the number of code points within the string.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to find the length of.

=== Return Value
An integer representing the length of the string.

=== Examples
====
[source,n1ql]
----
SELECT LENGTH("N1QL is awesome") AS ascii,
       LENGTH("Café") AS diacritic,
       LENGTH("🙂") AS emoji,
       LENGTH("") AS zero;
----

[source,json]
----
{
    "results": [
        {
            "ascii": 15,
            "diacritic": 5,
            "emoji": 4,
            "zero": 0
        }
    ]
}
----
====

[#fn-str-lower]
== LOWER(in_str)

=== Description
Converts all characters in the input string to lower case.
This is useful for canonical comparison of string values.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to convert to lower case.

=== Return Value
A string representing the input string converted to lower case.

=== Examples
====
[source,n1ql]
----
SELECT LOWER("N1QL is awesome") as n1ql;
----

[source,json]
----
{
    "results": [
        {
            "n1ql": "n1ql is awesome"
        }
    ]
}
----
====

[#fn-str-lpad]
== LPAD(in_str, size [, char])

ifeval::['{page-component-version}' == '7.1']
_(Introduced in Couchbase Server 7.1)_
endif::[]

=== Description
Pads a string with leading characters.
The function adds characters to the beginning of the string to pad the string to a specified length.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to add the leading characters to.

size:: An integer, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to an integer, that specifies the desired length of the result string.

char::
[Optional; default is Unicode U+0020, i.e. space
`" "`]
+
A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that represents the characters to add to the input string.

=== Return Value
A string representing the input string with leading characters added.

* If the specified size is smaller than the length of the input string, the input string is truncated and no padding is added.
* If the specified size is larger than the length of the input string, but shorter than the length of the input string plus the padding characters, the padding characters are truncated.
* If the specified size is greater than the length of the input string plus the padding characters, the padding characters are repeated in order until the specified size is reached.

=== Examples
====
[source,n1ql]
----
SELECT LPAD("N1QL is awesome", 20) AS implicit_padding,
       LPAD("N1QL is awesome", 20, "-*") AS repeated_padding,
       LPAD("N1QL is awesome", 20, "987654321") AS truncate_padding,
       LPAD("N1QL is awesome", 4, "987654321") AS truncate_string;
----

[source,json]
----
{
    "results": [
        {
            "implicit_padding": "     N1QL is awesome",
            "repeated_padding": "-*-*-N1QL is awesome",
            "truncate_padding": "98765N1QL is awesome",
            "truncate_string": "N1QL"
        }
    ]
}
----
====

[#fn-str-ltrim]
== LTRIM(in_str [, char])

=== Description
Removes all leading characters from a string.
The function removes all consecutive characters from the beginning of the string that match the specified characters and stops when it encounters a character that does not match any of the specified characters.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to remove the leading characters from.

char::
[Optional; default is whitespace, i.e.
space `" "`, tab `"\t"`, newline `"\n"`, formfeed `"\f"`, or carriage return `"\r"`]
+
A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that represents the characters to trim from the input string.
Each character in this string will be trimmed from the input string, it is therefore not necessary to delimit the characters to trim.
For example, specifying a character value of `"abc"` will trim the characters "a", "b" and "c" from the start of the string.

=== Return Value
A string representing the input string with leading characters removed.

=== Examples
====
[source,n1ql]
----
SELECT LTRIM("...N1QL is awesome", ".") as dots,
       LTRIM("     N1QL is awesome", " ") as explicit_spaces,
       LTRIM("	  N1QL is awesome") as implicit_spaces,
       LTRIM("N1QL is awesome") as no_dots;
----

[source,json]
----
{
    "results": [
        {
            "dots": "N1QL is awesome",
            "explicit_spaces": "N1QL is awesome",
            "implicit_spaces": "N1QL is awesome",
            "no_dots": "N1QL is awesome"
        }
    ]
}
----
====

[#fn-str-mask]
== MASK(in_str [, options])

ifeval::['{page-component-version}' == '7.1']
_(Introduced in Couchbase Server 7.1)_
endif::[]

=== Description
Overlays specified characters in the string with masking characters.
This may be useful when returning sensitive information, such as credit card numbers or email addresses.

=== Arguments

in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that represents the string to mask.

options:: An object containing the following possible parameters:

mask;; A string containing masking characters that will be used to overlay the input string.
May optionally also contain _hole_ characters, representing gaps in the mask; and _inject_ characters, that are inserted into the output.
(Default: `pass:c[********]`)

hole;; A string containing the character or characters used to indicate holes in the mask string.
(Default: space)

inject;; A string containing the character or characters in the mask string that are inserted into the output, rather than overlaying the input.
(Default: none)

length;; Determines the length of the output string.
(Default: missing)

* If this property is missing, or set to anything other than `"source"`, the length of the output is dynamic.
Any characters in the input up to the anchor point (see below) are included in the output.
The mask then starts at the anchor point, and continues for the length of the specified mask string.
Any characters in the input beyond the end of the mask are deleted.
This method may therefore obscure the number of characters in the input.

* If the value is `"source"`, the length of the output is the same as the length of the input.
Any characters in the input up to the anchor point are included in the output.
The mask then starts at the anchor point.
If the mask is _longer than_ the remaining length of the input, the mask is truncated to fit.
If the mask string is _shorter than or the same length as_ the remaining length of the input, the mask continues for the length of the specified mask string.
Any characters in the input beyond the end of the mask are included in the output.

anchor;; Determines where in the input string the mask should start.
Possible values are `"start"`, `"end"`, a regular expression string, a positive integer, or a negative integer.
(Default: `"start"`)

* `"start"` -- the mask begins at the start of the input and is applied towards the end.

* `"end"` -- the mask begins at the end of the input and is applied from the end towards the start.

* Regular expression -- the mask begins at the first point in the input which matches the regular expression, and is applied towards the end.
If you need to match the strings `"start"` or `"end"`, use patterns such as `"[s]tart"` or `"[e]nd"`.

* Positive integer -- the mask begins the specified number of characters after the start of the input, and is applied towards the end.

* Negative integer -- the mask begins the specified number of characters before the end of the input, and is applied towards the start.

+
+
If an anchor places the mask outside the boundaries of the input string, the input string is returned unchanged.

=== Return Value
A string representing the masked input string.

=== Examples
====
Default mask, custom mask, custom mask demonstrating holes.

[source,n1ql]
----
SELECT MASK('SomeTextToMask') AS mask,
       MASK('SomeTextToMask', {"mask": "++++"}) AS mask_custom,
       MASK('SomeTextToMask', {"mask": "++++    ++++"}) AS mask_hole;
----

[source,json]
----
{
    "results": [
        {
            "mask": "********",
            "mask_custom": "++++",
            "mask_hole": "++++Text++++"
        }
    ]
}
----
====

====
Mask with character injection.

[source,n1ql]
----
SELECT MASK('1234abcd5678efgh', {"mask": "****-****-****-####",
                                 "hole": "#",
                                 "inject": "-"}) AS mask_inject;
----

[source,json]
----
{
    "results": [
        {
            "mask_inject": "****-****-****-efgh"
        }
    ]
}
----
====

====
Mask anchored to the end of the source, with the output length determined by the source.

[source,n1ql]
----
SELECT MASK('1234abcd5678efgh', {"mask": "****", "anchor": "end", "length": "source"})
AS end_anchor;
----

[source,json]
----
{
    "results": [
        {
            "end_anchor": "1234abcd5678****"
        }
    ]
}
----
====

====
Mask anchored at the pattern `d5`.

[source,n1ql]
----
SELECT MASK('1234abcd5678efgh', {"mask": "****", "anchor": "d5"}) AS regex_anchor;
----

[source,json]
----
{
    "results": [
        {
            "regex_anchor": "1234abc****"
        }
    ]
}
----
====

====
Mask anchored 2 characters from the end of the source, with length determined by the input string.

[source,n1ql]
----
SELECT MASK('1234abcd5678efgh', {"mask": "****", "anchor": -2, "length": "source"})
AS negative_anchor
----

[source,json]
----
{
    "results": [
        {
            "negative_anchor": "1234abcd56****gh"
        }
    ]
}
----
====

====
Mask anchored at the 14th character, with length determined by the input string.

[source,n1ql]
----
SELECT MASK('1234abcd5678efgh', {"mask": "****", "anchor": 14, "length": "source"})
AS positive_anchor;
----

[source,json]
----
{
    "results": [
        {
            "positive_anchor": "1234abcd5678ef**"
        }
    ]
}
----
====

[#fn-str-position]
== POSITION(in_str, search_str)

=== Description
Finds the first position of the search string within the string, this position is zero-based, i.e., the first position is 0.
If the search string does not exist within the input string then the function returns -1.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to search within.

search_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to search for.

=== Return Value
An integer representing the first position of the search string.

=== Examples
====
[source,n1ql]
----
SELECT POSITION("N1QL is awesome", "awesome") as awesome,
       POSITION("N1QL is awesome", "N1QL") as n1ql,
       POSITION("N1QL is awesome", "SQL") as sql
----

[source,json]
----
{
    "results": [
        {
            "awesome": 8,
            "n1ql": 0,
            "sql": -1
        }
    ]
}
----
====

[#fn-str-repeat]
== REPEAT(in_str, n)

=== Description
Creates a new string which is the input string repeated the specified number of times.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to repeat.

n:: An integer, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to an integer, that is the number of times to repeat the string.

=== Return Value
A string representing the string generated by repeating the input string.

=== Limitations
It is possible to generate very large strings using this function.
In some cases the query engine may be unable to process all of these and cause excessive resource consumption.
It is therefore recommended that you first validate the inputs to this function to ensure that the generated result is a reasonable size.

=== Examples
====
[source,n1ql]
----
SELECT REPEAT("N1QL", 0) as empty_string,
       REPEAT("N1QL", 3) as n1ql_3;
----

[source,json]
----
{
    "results": [
        {
            "empty_string": "",
            "n1ql_3": "N1QLN1QLN1QL"
        }
    ]
}
----
====

[#fn-str-replace]
== REPLACE(in_str, search_str, replace [, n ])

=== Description
Replaces occurrences of a given substring in an input string.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to search for replacements in.

search_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to replace.

replace:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to replace the search string with.

n:: [Optional; default is all instances of the search string are replaced]
+
An integer, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to an integer, which represents the number of instances of the search string to replace.
If a negative value is specified then all instances of the search string are replaced.

=== Return Value
A string representing the input string with the specified substring replaced.

=== Examples
====
[source,n1ql]
----
SELECT REPLACE("SQL SQL SQL", "S", "N1", -2) as negative_n,
       REPLACE("SQL SQL SQL", "S", "N1", 2) as replace_2,
       REPLACE("SQL SQL SQL", "S", "N1") as replace_all;
----

[source,json]
----
{
    "results": [
        {
            "negative_n": "N1QL N1QL N1QL",
            "replace_2": "N1QL N1QL SQL",
            "replace_all": "N1QL N1QL N1QL"
        }
    ]
}
----
====

[#fn-str-reverse]
== REVERSE(in_str)

=== Description
Reverses the order of the characters in a given string.
i.e.
The first character becomes the last character and the last character becomes the first character etc.
This is useful for testing whether or not a string is a palindrome.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to reverse.

=== Return Value
A string representing the input string with its characters reversed.

=== Examples
====
[source,n1ql]
----
SELECT REVERSE("N1QL is awesome") as n1ql,
       REVERSE("racecar") as palindrome;
----

[source,json]
----
{
    "results": [
        {
            "n1ql": "emosewa si LQ1N",
            "palindrome": "racecar"
        }
    ]
}
----
====

[#fn-str-rpad]
== RPAD(in_str, size [, char])

ifeval::['{page-component-version}' == '7.1']
_(Introduced in Couchbase Server 7.1)_
endif::[]

=== Description
Pads a string with trailing characters.
The function adds characters to the end of the string to pad the string to a specified length.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to add the trailing characters to.

size:: An integer, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to an integer, that specifies the desired length of the result string.

char::
[Optional; default is Unicode U+0020, i.e. space
`" "`]
+
A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that represents the characters to add to the input string.

=== Return Value
A string representing the input string with trailing characters added.

* If the specified size is smaller than the length of the input string, the input string is truncated and no padding is added.
* If the specified size is larger than the length of the input string, but shorter than the length of the input string plus the padding characters, the padding characters are truncated.
* If the specified size is greater than the length of the input string plus the padding characters, the padding characters are repeated in order until the specified size is reached.

=== Examples
====
[source,n1ql]
----
SELECT RPAD("N1QL is awesome", 20) AS implicit_padding,
       RPAD("N1QL is awesome", 20, "-*") AS repeated_padding,
       RPAD("N1QL is awesome", 20, "123456789") AS truncate_padding,
       RPAD("N1QL is awesome", 4, "123456789") AS truncate_string;
----

[source,json]
----
{
    "results": [
        {
            "implicit_padding": "N1QL is awesome     ",
            "repeated_padding": "N1QL is awesome-*-*-",
            "truncate_padding": "N1QL is awesome12345",
            "truncate_string": "N1QL"
        }
    ]
}
----
====

[#fn-str-rtrim]
== RTRIM(in_str [, char])

=== Description
Removes all trailing characters from a string.
The function removes all consecutive characters from the end of the string that match the specified characters and stops when it encounters a character that does not match any of the specified characters.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to convert to remove trailing characters from.

char::
[Optional; default is whitespace, i.e.
space `" "`, tab `"\t"`, newline `"\n"`, formfeed `"\f"`, or carriage return `"\r"`]
+
A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that represents the characters to trim from the input string.
Each character in this string will be trimmed from the input string, it is therefore not necessary to delimit the characters to trim.
For example specifying a character value of `"abc"` will trim the characters `"a"`, `"b"` and `"c"` from the start of the string.

=== Return Value
A string representing the input string with its trailing characters removed.

=== Examples
====
[source,n1ql]
----
SELECT RTRIM("N1QL is awesome...", ".") as dots,
       RTRIM("N1QL is awesome     ", " ") as explicit_spaces,
       RTRIM("N1QL is awesome     ") as implicit_spaces,
       RTRIM("N1QL is awesome") as no_dots;
----

[source,json]
----
{
    "results": [
        {
            "dots": "N1QL is awesome",
            "explicit_spaces": "N1QL is awesome",
            "implicit_spaces": "N1QL is awesome",
            "no_dots": "N1QL is awesome"
        }
    ]
}
----
====

[#fn-str-split]
== SPLIT(in_str [, in_substr])

=== Description
Splits the string into an array of substrings, based on the specified separator string.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to split.

in_substr:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the substring to split the input string on.

=== Return Value
An array of strings containing the strings created by splitting the input string.

=== Examples
====
[source,n1ql]
----
SELECT SPLIT("N1QL is awesome", " ") as explicit_spaces,
       SPLIT("N1QL is awesome") as implicit_spaces,
       SPLIT("N1QL is awesome", "is") as split_is
----

[source,json]
----
{
    "results": [
        {
            "explicit_spaces": [
                "N1QL",
                "is",
                "awesome"
            ],
            "implicit_spaces": [
                "N1QL",
                "is",
                "awesome"
            ],
            "split_is": [
                "N1QL ",
                " awesome"
            ]
        }
    ]
}
----
====

[#fn-str-substr]
== SUBSTR(in_str, start_pos [, length])

=== Description
Returns the substring (of given length) starting at the provided position.
The position is zero-based, i.e.
the first position is 0.
If position is negative, it is counted from the end of the string; -1 is the last position in the string.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to convert to extract the substring from.

start_pos:: An integer, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to an integer, that is the start position of the substring.

length:: [Optional; default is to capture to the end of the string]
+
An integer, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to an integer, that is the length of the substring to extract.

=== Return Value
A string representing the substring extracted from the input string.

=== Examples
====
[source,n1ql]
----
SELECT SUBSTR("N1QL is awesome", 3) as end_of_string,
       SUBSTR("N1QL is awesome", 3, 1) as single_letter,
       SUBSTR("N1QL is awesome", 3, 3) as three_letters
----

[source,json]
----
{
    "results": [
        {
            "end_of_string": "L is awesome",
            "single_letter": "L",
            "three_letters": "L i"
        }
    ]
}
----
====

[#fn-str-suffixes]
== SUFFIXES(in_str)

=== Description
Generates an array of all the suffixes of the input string.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to generate the suffixes of.

=== Return Value
An array of strings containing all of the suffixes of the input string.

=== Examples
====
[source,n1ql]
----
SELECT SUFFIXES("N1QL is awesome") as n1ql
----

[source,json]
----
{
    "results": [
        {
            "n1ql": [
                "N1QL is awesome",
                "1QL is awesome",
                "QL is awesome",
                "L is awesome",
                " is awesome",
                "is awesome",
                "s awesome",
                " awesome",
                "awesome",
                "wesome",
                "esome",
                "some",
                "ome",
                "me",
                "e"
            ]
        }
    ]
}
----
====

The following example uses the `SUFFIXES()` function to index and query the airport names when a partial airport name is given.

====
[source,n1ql]
----
CREATE INDEX autocomplete_airport_name
ON `travel-sample`.inventory.airport ( DISTINCT ARRAY array_element FOR array_element
IN SUFFIXES(LOWER(airportname)) END )
----

[source,n1ql]
----
SELECT airportname
FROM `travel-sample`.inventory.airport
WHERE ANY array_element
IN SUFFIXES(LOWER(airportname)) SATISFIES array_element LIKE 'washing%' END
----

[source,json]
----
{
    "results": [
        {
            "airportname": "Ronald Reagan Washington Natl"
        },
        {
            "airportname": "Washington Dulles Intl"
        },
        {
            "airportname": "Baltimore Washington Intl"
        },
        {
            "airportname": "Washington Union Station"
        }
    ]
}
----
====

This https://dzone.com/articles/a-couchbase-index-technique-for-like-predicates-wi[blog^] provides more information about this example.

[#fn-str-title]
== TITLE(in_str)

Alias for <<fn-str-initcap,INITCAP()>>.

[#fn-str-token]
include::partial$n1ql-language-reference/fun-token.adoc[]

[#fn-str-trim]
== TRIM(in_str [, char])

=== Description
Removes all leading and trailing characters from a string.
The function removes all consecutive characters from the beginning and end of the string that match the specified characters and stops when it encounters a character that does not match any of the specified characters.
This function is equivalent to calling `LTRIM()` and `RTRIM()` successively.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to convert to remove trailing and leading characters from.

char::
[Optional; default is Unicode U+0020, i.e.
`" "`]
+
A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that represents the characters to trim from the input string.
Each character in this string will be trimmed from the input string, it is therefore not necessary to delimit the characters to trim.
For example specifying a character value of `"abc"` will trim the characters `"a"`, `"b"` and `"c"` from the start of the string.

=== Return Value
A string representing the input string with trailing and leading characters removed.

=== Examples
====
[source,n1ql]
----
SELECT TRIM("...N1QL is awesome...", ".") as dots,
       TRIM("     N1QL is awesome     ", " ") as explicit_spaces,
       TRIM("     N1QL is awesome     ") as implicit_spaces,
       TRIM("N1QL is awesome") as no_dots;
----

[source,json]
----
{
    "results": [
        {
            "dots": "N1QL is awesome",
            "explicit_spaces": "N1QL is awesome",
            "implicit_spaces": "N1QL is awesome",
            "no_dots": "N1QL is awesome"
        }
    ]
}
----
====

[#fn-str-upper]
== UPPER(in_str)

=== Description
Converts all characters in the input string to upper case.

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to convert to upper case.

=== Return Value
A string representing the input string converted to upper case.

=== Examples
====
[source,n1ql]
----
SELECT UPPER("N1QL is awesome") as n1ql;
----

[source,json]
----
{
    "results": [
        {
            "n1ql": "N1QL IS AWESOME"
        }
    ]
}
----
====

[#fn-str-urlencode]
== URLENCODE(plain_string)

=== Description
Returns the input string encoded for use in a URL

=== Arguments
plain_string:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to URL-encode.

=== Return Value
The input string, with any reserved characters replaced by percent encoding.

If the input argument is MISSING, returns MISSING.
If the input argument is non-string, returns NULL.

=== Example
====
[source,text]
----
SELECT%20name%20FROM%20%60travel-sample%60.inventory.hotel%20LIMIT%201%3B
----

====

[#fn-str-upper]
== URLDECODE(encoded_string)

=== Description
Decodes the URL-encoded input string and returns the resulting plain string

=== Arguments
in_str:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, that is the string to convert to upper case.

=== Return Value
A string representing the input string converted to upper case.

=== Example
====
[source,text]
----
SELECT%20name%20FROM%20%60travel-sample%60.inventory.hotel%20LIMIT%201%3B”) AS decode;
SELECT name FROM travel-sample.inventory.hotel LIMIT 1;
----
====
