= N1QL Support for Couchbase Transactions
:page-topic-type: tutorial
:page-status: Couchbase Server 7.0
:imagesdir: ../../assets/images
:description: N1QL offers full support for Couchbase ACID transactions.

// Cross-references
:insert: xref:n1ql:n1ql-language-reference/insert.adoc
:upsert: xref:n1ql:n1ql-language-reference/upsert.adoc
:delete: xref:n1ql:n1ql-language-reference/delete.adoc
:update: xref:n1ql:n1ql-language-reference/update.adoc
:merge: xref:n1ql:n1ql-language-reference/merge.adoc
:select: xref:n1ql:n1ql-language-reference/selectintro.adoc
:execfunction: xref:n1ql:n1ql-language-reference/execfunction.adoc
:prepare: xref:n1ql:n1ql-language-reference/prepare.adoc
:execute: xref:n1ql:n1ql-language-reference/execute.adoc
:transactions: xref:learn:data/transactions.adoc
:cbq-shell: xref:tools:cbq-shell.adoc
:txid: xref:settings:query-settings.adoc#txid
:tximplicit: xref:settings:query-settings.adoc#tximplicit
:txstmtnum: xref:settings:query-settings.adoc#txstmtnum
:txtimeout_req: xref:settings:query-settings.adoc#txtimeout_req
:txtimeout-srv: xref:settings:query-settings.adoc#txtimeout-srv
:scan_consistency: xref:settings:query-settings.adoc#scan_consistency
:transactional-scan-consistency: xref:settings:query-settings.adoc#transactional-scan-consistency

// Related links
:begin-transaction: xref:n1ql-language-reference/begin-transaction.adoc
:set-transaction: xref:n1ql-language-reference/set-transaction.adoc
:savepoint: xref:n1ql-language-reference/savepoint.adoc
:commit-transaction: xref:n1ql-language-reference/commit-transaction.adoc
:rollback-transaction: xref:n1ql-language-reference/rollback-transaction.adoc

[abstract]
N1QL offers full support for Couchbase ACID transactions.

Starting with Couchbase Server 7.0, N1QL offers full support for Couchbase ACID transactions.
Refer to {transactions}[Transactions] for an overview of Couchbase transactions.

* Only DML statements are permitted within a transaction: {insert}[INSERT], {upsert}[UPSERT], {delete}[DELETE], {update}[UPDATE], {merge}[MERGE], {select}[SELECT], {execfunction}[EXECUTE FUNCTION], {prepare}[PREPARE], or {execute}[EXECUTE].

* The `EXECUTE FUNCTION` statement is only permitted in a transaction if the user-defined function does not contain any subqueries other than `SELECT` subqueries.

* The `PREPARE` and `EXECUTE` statements are only permitted in a transaction for the DML statements listed above.

All statements within a transaction are sent to the same Query node.

== Statements

N1QL provides the following statements in support of Couchbase transactions.
Refer to the documentation for each statement for more information and examples.

* To begin a transaction, refer to {begin-transaction}[BEGIN TRANSACTION].
* To specify transaction settings, refer to {set-transaction}[SET TRANSACTION].
* To set a savepoint, refer to {savepoint}[SAVEPOINT].
* To rollback a transaction, refer to {rollback-transaction}[ROLLBACK TRANSACTION].
* To commit a transaction, refer to {commit-transaction}[COMMIT TRANSACTION].

== Settings and Parameters

The Query service provides the following node-level settings and request-level parameters in support of Couchbase transactions.
Refer to the documentation for each parameter for more information and examples.

* The {txid}[txid] request-level parameter specifies the transaction to which a statement belongs.

* The {tximplicit}[tximplicit] request-level parameter specifies that a statement is a single transaction.

* The {txstmtnum}[txstmtnum] request-level parameter specifies the transaction statement number.

* The {txtimeout_req}[txtimeout] request-level parameter and {txtimeout-srv}[txtimeout] node-level setting specify the maximum time to spend on a transaction before timing out.

In addition, the {scan_consistency}[scan-consistency] request-level parameter is used to specify the transactional scan consistency.
Refer to {transactional-scan-consistency}[Transactional Scan Consistency] for details.

== Worked Example

This worked example guides you through a complete Couchbase transaction session using the {cbq-shell}[cbq shell].

[[preparation]]
=== Preparation

. Start the cbq shell and connect to the Couchbase cluster.
+
[source,shell]
----
$ cbq -e http://localhost:8091 -u Administrator -p password
----

. For the purposes of this worked example, create a temporary keyspace called `test`.
+
For example, if you have already installed the `travel-sample` bucket, create a scope called `transaction` within that bucket, and then create a collection called `test` within that scope. Note that "transaction" is a reserved N1QL keyword, so the name of the `transaction` scope must be delimited with backticks `{backtick}{backtick}`.
+
[source,shell]
----
cbq> CREATE SCOPE `travel-sample`.`transaction`;
cbq> CREATE COLLECTION `travel-sample`.`transaction`.test;
----

. Create a primary index on the `test` keyspace, so that you can query and update the documents in this keyspace.
+
[source,shell]
----
cbq> CREATE PRIMARY INDEX ON `travel-sample`.`transaction`.test;
----

. Set the default query context for the following statements, assuming that you have created the `test` collection within the `pass:c[`travel-sample`.`transaction`]` scope.
+
[source,shell]
----
cbq> \set -query_context `travel-sample`.`transaction`;
----

. If necessary, make sure the transaction timeout is set to a reasonably long duration, so that the transaction will not time out as you work through this worked example.
+
[source,shell]
----
cbq> \set -txtimeout "30m";
----

=== Transaction

. Start the transaction.
+
[source,shell]
----
cbq> BEGIN WORK;
----
+
Notice the statement returns a transaction ID.
Since you are using the cbq shell, all statements within this session are assumed to be part of this transaction until you rollback or commit the transaction.
+
[source,json]
----
[
    {
        "txid": "6dfa9dd6-303f-4adc-a99f-e05a44485c45"
    }
]
----

. Create a document in the `test` keyspace with the ID `abc2`, containing a single attribute `a`.
+
[source,shell]
----
cbq> INSERT INTO test VALUES("abc2", {"a":1});
----

. Set a savepoint:
+
[source,shell]
----
cbq> SAVEPOINT s1;
----

. Update the specified documents in the `test` keyspace to include a second attribute `b`.
+
[source,shell]
----
cbq> UPDATE test AS d SET d.b = 10 WHERE d.a > 0;
----

. Check the content of the specified documents in the `test` keyspace.
+
[source,shell]
----
cbq> SELECT d.*, META(d).id FROM test AS d WHERE d.a >= 0;
----
+
Notice the `abc2` document now has two attributes: `a` and `b`.
+
[source,json]
----
[
    {
        "a": 1,
        "b": 10,
        "id": "abc2"
    }
]
----

. Set a second savepoint.
+
[source,shell]
----
cbq> SAVEPOINT s2;
----

. Update the specified documents in the `test` keyspace to include a third attribute named `c`.
+
[source,shell]
----
cbq> UPDATE test AS d SET d.b = 10, d.c = "xyz" WHERE d.a > 0;
----

. Check the content of the specified documents in the `test` keyspace.
+
[source,shell]
----
cbq> SELECT d.*, META(d).id FROM test AS d WHERE d.a >= 0;
----
+
Notice the `abc2` document now has three attributes: `a`, `b`, and `c`.
+
[source,json]
----
[
    {
        "a": 1,
        "b": 10,
        "c": "xyz",
        "id": "abc2"
    }
]
----

. Roll back the transaction to the second savepoint.
+
[source,shell]
----
cbq> ROLLBACK TRAN TO SAVEPOINT s2;
----

. Check the content of the specified documents in the `test` keyspace again.
+
[source,shell]
----
cbq> SELECT d.*, META(d).id FROM test AS d WHERE d.a >= 0;
----
+
Notice the `abc2` document again has only two attributes: `a` and `b`.
+
[source,json]
----
[
    {
        "a": 1,
        "b": 10,
        "id": "abc2"
    }
]
----

. Roll back the entire transaction.
+
[source,shell]
----
cbq> ROLLBACK WORK;
----

. Check the content of the specified documents in the `test` keyspace again.
+
[source,shell]
----
cbq> SELECT d.*, META(d).id FROM test AS d WHERE d.a >= 0;
----
+
Notice the `abc2` document no longer exists.

=== Finishing Off

. You can now exit the cbq shell.
+
[source,shell]
----
cbq> \quit;
----

== Related Links

* Blog post: https://blog.couchbase.com/transactions-n1ql-couchbase-distributed-nosql/[N1QL Transactions^].