= N1QL Support for Couchbase Transactions
:page-topic-type: concept
:imagesdir: ../../assets/images
:description: N1QL offers full support for Couchbase ACID transactions.
:tabs:
:page-partial:

// N1QL cross-references
:insert: xref:n1ql:n1ql-language-reference/insert.adoc
:upsert: xref:n1ql:n1ql-language-reference/upsert.adoc
:delete: xref:n1ql:n1ql-language-reference/delete.adoc
:update: xref:n1ql:n1ql-language-reference/update.adoc
:merge: xref:n1ql:n1ql-language-reference/merge.adoc
:select: xref:n1ql:n1ql-language-reference/selectintro.adoc
:execfunction: xref:n1ql:n1ql-language-reference/execfunction.adoc
:prepare: xref:n1ql:n1ql-language-reference/prepare.adoc
:execute: xref:n1ql:n1ql-language-reference/execute.adoc

// Learn cross-references
:transactions: xref:learn:data/transactions.adoc
:roles: xref:learn:security/roles.adoc

// Manage cross-references
:install-sample-buckets: xref:manage:manage-settings/install-sample-buckets.adoc
:sys-transactions: xref:manage:monitor/monitoring-n1ql-query.adoc#sys-transactions

// Tools cross-references
:query-workbench: xref:tools:query-workbench.adoc
:cbq-shell: xref:tools:cbq-shell.adoc
:n1ql-rest-api: xref:n1ql:n1ql-rest-api/index.adoc

// Settings cross-references
:txid: xref:settings:query-settings.adoc#txid
:tximplicit: xref:settings:query-settings.adoc#tximplicit
:txstmtnum: xref:settings:query-settings.adoc#txstmtnum
:kvtimeout: xref:settings:query-settings.adoc#kvtimeout
:txtimeout_req: xref:settings:query-settings.adoc#txtimeout_req
:txtimeout-srv: xref:settings:query-settings.adoc#txtimeout-srv
:queryTxTimeout: xref:settings:query-settings.adoc#queryTxTimeout
:atrcollection_req: xref:settings:query-settings.adoc#atrcollection_req
:atrcollection-srv: xref:settings:query-settings.adoc#atrcollection-srv
:cleanupclientattempts: xref:settings:query-settings.adoc#cleanupclientattempts
:cleanuplostattempts: xref:settings:query-settings.adoc#cleanuplostattempts
:cleanupwindow: xref:settings:query-settings.adoc#cleanupwindow
:queryCleanupClientAttempts: xref:settings:query-settings.adoc#queryCleanupClientAttempts
:queryCleanupLostAttempts: xref:settings:query-settings.adoc#queryCleanupLostAttempts
:queryCleanupWindow: xref:settings:query-settings.adoc#queryCleanupWindow
:numatrs_req: xref:settings:query-settings.adoc#numatrs_req
:numatrs-srv: xref:settings:query-settings.adoc#numatrs-srv
:queryNumAtrs: xref:settings:query-settings.adoc#queryNumAtrs
:scan_consistency: xref:settings:query-settings.adoc#scan_consistency
:durability_level: xref:settings:query-settings.adoc#durability_level
:transactional-scan-consistency: xref:settings:query-settings.adoc#transactional-scan-consistency

// Related links
:begin-transaction: xref:n1ql-language-reference/begin-transaction.adoc
:set-transaction: xref:n1ql-language-reference/set-transaction.adoc
:savepoint: xref:n1ql-language-reference/savepoint.adoc
:commit-transaction: xref:n1ql-language-reference/commit-transaction.adoc
:rollback-transaction: xref:n1ql-language-reference/rollback-transaction.adoc

[abstract]
N1QL offers full support for Couchbase ACID transactions.

Starting with Couchbase Server 7.0, N1QL offers full support for Couchbase ACID transactions based on optimistic concurrency.
Refer to {transactions}[Transactions] for an overview of Couchbase transactions.

include::partial$n1ql-language-reference/transaction-restrictions.adoc[]

== Statements

N1QL provides the following statements in support of Couchbase transactions.
Refer to the documentation for each statement for more information and examples.

* To begin a transaction, refer to {begin-transaction}[BEGIN TRANSACTION].
* To specify transaction settings, refer to {set-transaction}[SET TRANSACTION].
* To set a savepoint, refer to {savepoint}[SAVEPOINT].
* To rollback a transaction, refer to {rollback-transaction}[ROLLBACK TRANSACTION].
* To commit a transaction, refer to {commit-transaction}[COMMIT TRANSACTION].

== Settings and Parameters

The Query service provides settings and parameters in support of Couchbase transactions.
Refer to the documentation for each parameter for more information and examples.

|===
| Setting{nbsp}/ Parameter | Description

| {txid}[txid] request-level parameter
| Specifies the transaction to which a statement belongs.

| {tximplicit}[tximplicit] request-level parameter
| Specifies that a statement is a single transaction.

| {txstmtnum}[txstmtnum] request-level parameter
| Specifies the transaction statement number.

| {kvtimeout}[kvtimeout] request-level parameter
| Specifies the maximum time to spend on a KV operation within a transaction before timing out.

| {durability_level}[durability_level] request-level parameter
| Specifies the transactional durability level.

| {txtimeout_req}[txtimeout] request-level parameter +
{txtimeout-srv}[txtimeout] node-level setting +
{queryTxTimeout}[queryTxTimeout] cluster-level setting
| Specify the maximum time to spend on a transaction before timing out.

| {atrcollection_req}[atrcollection] request-level parameter +
{atrcollection-srv}[atrcollection] node-level setting
| Specify where the active transaction record is stored.

| {cleanupclientattempts}[cleanupclientattempts] node-level setting +
{queryCleanupClientAttempts}[queryCleanupClientAttempts] cluster-level setting

{cleanuplostattempts}[cleanuplostattempts] node-level setting +
{queryCleanupLostAttempts}[queryCleanupLostAttempts] cluster-level setting
| Specify how expired transactions are cleaned up.

| {cleanupwindow}[cleanupwindow] node-level setting +
{queryCleanupWindow}[queryCleanupWindow] cluster-level setting
| Specify how frequently active transaction records are checked for cleanup.

| {numatrs_req}[numatrs] request-level parameter +
{numatrs-srv}[numatrs] node-level setting +
{queryNumAtrs}[queryNumAtrs] cluster-level setting
| Specify the total number of active transaction records.
|===

In addition, the {scan_consistency}[scan-consistency] request-level parameter is used to specify the transactional scan consistency.
Refer to {transactional-scan-consistency}[Transactional Scan Consistency] for details.

== Query Tools

To create a Couchbase transaction using N1QL, you can use any of the tools that you use to run a N1QL query: the {query-workbench}[Query Workbench], the {cbq-shell}[cbq shell], or the {n1ql-rest-api}[Query REST API].
There are slight differences in the way these tools operate when creating Couchbase transactions.
These are explained in the sections below.

Note that some Couchbase SDKs provide APIs to support Couchbase transactions.
For further details, refer to {transactions}[Transactions].

TIP: For a walkthrough of how to create a transaction and use other transaction statements with the Query Workbench, cbq shell, or Query REST API, see xref:n1ql:n1ql-language-reference/transactions-walkthrough.adoc[].

=== Couchbase Transactions with the Query Workbench

* To execute a transaction containing multiple statements, compose the sequence of statements in the Query Editor.
Each statement must be terminated with a semicolon.
After each statement, you must press kbd:[Shift+Enter] to start a new line _without_ executing the query.
You can then click btn:[Execute] to execute the transaction.

* To execute a single statement as a transaction, simply enter the statement in the Query Editor and click btn:[Run as TX].

* In either case, you do not need to specify the `txid` parameter or the `tximplicit` parameter.
If you need to specify any other parameters for the Couchbase transaction, you can use the query run-time preferences window.

=== Couchbase Transactions with the cbq shell

* To execute a transaction containing multiple statements, you can create the transaction one statement at a time.
Once you have started a transaction, all statements within the cbq shell session are assumed to be part of the same transaction until you rollback or commit the transaction.
In this case, you don't need to set the `txid` parameter.
footnote:[You must be using cbq shell version 2.0 or above to use the automatic transaction ID functionality.]

* Alternatively, you can use the `tximplicit` parameter to run a single statement as a transaction.
In this case, you do not need to specify the `txid` parameter either.

* You can specify parameters for the Couchbase transaction using the `\SET` command.

=== Couchbase Transactions with the Query REST API

* To execute a transaction containing multiple statements, you can create the transaction one statement at a time.
Once you have started the transaction, you must set the `txid` parameter to specify the transaction to which each subsequent statement belongs.

* Alternatively, you can use the `tximplicit` parameter to run a single statement as a transaction.
In this case, you do not need to specify the `txid` parameter.

* You can specify parameters for the Couchbase transaction as body parameters or query parameters alongside the query statement.

== Monitoring

You can monitor active Couchbase transactions using the `system:transactions` catalog.
For more information, refer to {sys-transactions}[system:transactions].

== Permissions

When developing a transaction with an SDK, the transaction may contain a mixture of key-value operations and query statements.

include::learn:partial$transaction-privileges.adoc[]


== Related Links

* Blog post: https://blog.couchbase.com/transactions-n1ql-couchbase-distributed-nosql/[Couchbase Transactions: Elastic, Scalable, and Distributed^].
