= Type Functions
:description: Type functions perform operations that check or convert expressions.
:page-topic-type: concept

[abstract]
{description}

NOTE: If any arguments to any of the following functions are [.out]`MISSING` then the result is also [.out]`MISSING` (i.e.
no result is returned).
Similarly, if any of the arguments passed to the functions are `NULL` or are of the wrong type (e.g.
an integer instead of a string), then `NULL` is returned as the result.


== ISARRAY(expression)

=== Description

Returns True if expression is an array, otherwise returns MISSING, NULL or false.

=== Examples
====
[source,n1ql]
----
SELECT ISARRAY(true) AS `boolean`,
       ISARRAY(MISSING) AS `missing`,
       ISARRAY(NULL) AS `null`,
       ISARRAY(123) AS `number`,
       ISARRAY("hello world") AS `string`,
       ISARRAY([1, 2, 3]) AS `array`,
       ISARRAY({"hello": "world"}) AS `object`;
----

[source,json]
----
[
  {
    "array": true,
    "boolean": false,
    "null": null,
    "number": false,
    "object": false,
    "string": false
  }
]
----
====

== ISATOM(expression)

=== Description

Returns True if expression is a Boolean, number, or string, otherwise returns MISSING, NULL or false.

=== Examples
====
[source,n1ql]
----
SELECT ISATOM(true) AS `boolean`,
       ISATOM(MISSING) AS `missing`,
       ISATOM(NULL) AS `null`,
       ISATOM(123) AS `number`,
       ISATOM("hello world") AS `string`,
       ISATOM([1, 2, 3]) AS `array`,
       ISATOM({"hello": "world"}) AS `object`;
----

[source,json]
----
[
  {
    "array": true,
    "boolean": false,
    "null": null,
    "number": false,
    "object": false,
    "string": false
  }
]
----
====

== ISBOOLEAN(expression)

=== Description

Returns True if expression is a Boolean, otherwise returns MISSING, NULL or false.

=== Examples
====
[source,n1ql]
----
SELECT ISBOOLEAN(true) AS `boolean`,
       ISBOOLEAN(MISSING) AS `missing`,
       ISBOOLEAN(NULL) AS `null`,
       ISBOOLEAN(123) AS `number`,
       ISBOOLEAN("hello world") AS `string`,
       ISBOOLEAN([1, 2, 3]) AS `array`,
       ISBOOLEAN({"hello": "world"}) AS `object`;
----

[source,json]
----
[
  {
    "array": true,
    "boolean": false,
    "null": null,
    "number": false,
    "object": false,
    "string": false
  }
]
----
====

== ISNUMBER(expression)

=== Description

Returns True if expression is a number, otherwise returns MISSING, NULL or false.

=== Examples
====
[source,n1ql]
----
SELECT ISNUMBER(true) AS `boolean`,
       ISNUMBER(MISSING) AS `missing`,
       ISNUMBER(NULL) AS `null`,
       ISNUMBER(123) AS `number`,
       ISNUMBER("hello world") AS `string`,
       ISNUMBER([1, 2, 3]) AS `array`,
       ISNUMBER({"hello": "world"}) AS `object`;
----

[source,json]
----
[
  {
    "array": true,
    "boolean": false,
    "null": null,
    "number": false,
    "object": false,
    "string": false
  }
]
----
====

== ISOBJECT(expression)

=== Description

Returns True if expression is an object, otherwise returns MISSING, NULL or false.

=== Examples
====
[source,n1ql]
----
SELECT ISOBJECT(true) AS `boolean`,
       ISOBJECT(MISSING) AS `missing`,
       ISOBJECT(NULL) AS `null`,
       ISOBJECT(123) AS `number`,
       ISOBJECT("hello world") AS `string`,
       ISOBJECT([1, 2, 3]) AS `array`,
       ISOBJECT({"hello": "world"}) AS `object`;
----

[source,json]
----
[
  {
    "array": true,
    "boolean": false,
    "null": null,
    "number": false,
    "object": false,
    "string": false
  }
]
----
====

ISSTRING(expression)

Returns True if expression is a string, otherwise returns MISSING, NULL or false.

== ISSTRING(expression)

=== Description

Returns True if expression is a string, otherwise returns MISSING, NULL or false.

=== Examples
====
[source,n1ql]
----
SELECT ISSTRING(true) AS `boolean`,
       ISSTRING(MISSING) AS `missing`,
       ISSTRING(NULL) AS `null`,
       ISSTRING(123) AS `number`,
       ISSTRING("hello world") AS `string`,
       ISSTRING([1, 2, 3]) AS `array`,
       ISSTRING({"hello": "world"}) AS `object`;
----

[source,json]
----
[
  {
    "array": true,
    "boolean": false,
    "null": null,
    "number": false,
    "object": false,
    "string": false
  }
]
----
====

TYPE(expression)

Returns one of the following strings, based on the value of expression:

* "missing"
* "null"
* "boolean"
* "number"
* "string"
* "array"
* "object"
* "binary"

== TYPE(expression)

=== Description

Returns one of the following strings, based on the value of expression:

* "missing"
* "null"
* "boolean"
* "number"
* "string"
* "array"
* "object"
* "binary"

=== Examples
====
[source,n1ql]
----
SELECT TYPE(true) AS `boolean`,
       TYPE(MISSING) AS `missing`,
       TYPE(NULL) AS `null`,
       TYPE(123) AS `number`,
       TYPE("hello world") AS `string`,
       TYPE([1, 2, 3]) AS `array`,
       TYPE({"hello": "world"}) AS `object`;
----

[source,json]
----
[
  {
    "array": true,
    "boolean": false,
    "null": null,
    "number": false,
    "object": false,
    "string": false
  }
]
----
====

== Type-Conversion Functions
:description: The following converts the supplied expression to a (data type).

TOARRAY(expression)

Returns array as follows:

* MISSING is MISSING.
* NULL is NULL.
* Arrays are themselves.
* All other values are wrapped in an array.

TOATOM(expression)

Returns atomic value as follows:

* MISSING is MISSING.
* NULL is NULL.
* Arrays of length 1 are the result of TOATOM() on their single element.
* Objects of length 1 are the result of TOATOM() on their single value.
* Booleans, numbers, and strings are themselves.
* All other values are NULL.

TOBOOLEAN(expression)

Returns Boolean as follows:

* MISSING is MISSING.
* NULL is NULL.
* False is false.
* Numbers +0, -0, and NaN are false.
* Empty strings, arrays, and objects are false.
* All other values are true.

TONUMBER(expression)

Returns number as follows:

* MISSING is MISSING.
* NULL is NULL.
* False is 0.
* True is 1.
* Numbers are themselves.
* Strings that parse as numbers are those numbers.
* All other values are NULL.

TOOBJECT(expression)

Returns object as follows:

* MISSING is MISSING.
* NULL is NULL.
* Objects are themselves.
* All other values are the empty object.

TOSTRING(expression)

Returns string as follows:

* MISSING is MISSING.
* NULL is NULL.
* False is "false".
* True is "true".
* Numbers are their string representation.
* Strings are themselves.
* All other values are NULL.
