= UNNEST_POS Function
:page-topic-type: reference
:imagesdir: ../assets/images
:description: Use the UNNEST_POS() function to return the position of each element in an unnested array.

[abstract]
{description}

You can use the `UNNEST_POS()` function with the xref:n1ql-language-reference/unnest.adoc[UNNEST Clause] to return the position of each element in an unnested array. 

[[fn-unnest-pos,UNNEST_POS()]]
== UNNEST_POS(`expr`)

This function has a synonym <<fn-unnest-position>>.

=== Description

The `UNNEST_POS` function takes an unnested array and returns the position value of each element in the array.

=== Arguments

expr:: [Required] The alias of the unnested array from an xref:n1ql-language-reference/unnest.adoc[UNNEST Clause]. 

=== Return Values

The `UNNEST_POS` function returns the position of each element in the unnested array, `expr`, as an integer. It returns each position value as a separate row in JSON format. The first element in the array is at position `0`. 

In all other cases, the `UNNEST_POS` function returns `NULL` or `MISSING`.

=== Example

====
In the following example, the `UNNEST_POS` function takes the result of an `UNNEST` Clause on a given array, `a1`. The `UNNEST` function returns the position of each element in the unnested `a1` array , `u`, as the `upos` value. 

[source,N1QL]
----
include::example$functions/unnest-pos.n1ql[]
----

.Results
[source,json]
----
include::example$functions/unnest-pos.jsonc[]
----
====

[[fn-unnest-position,UNNEST_POSITION()]]
== UNNEST_POSITION(`expr`)

Synonym of <<fn-unnest-pos>>.

== Related Links

- xref:n1ql-language-reference/unnest.adoc[UNNEST Clause]
- xref:n1ql-language-reference/from.adoc[FROM Clause]