= UPDATE
:page-topic-type: concept

UPDATE replaces a document that already exists with updated values.

_update:_

----
UPDATE keyspace-ref [use-keys-clause] [set-clause] [unset-clause] [where-clause] [limit-clause] [returning-clause]
----

_set-clause:_

----
SET path = expression [update-for] [ , path = expression [update-for] ]*
----

_update-for:_

----
FOR variable (IN | WITHIN) path  (, variable (IN | WITHIN) path)* [WHEN condition ] END
----

_unset-clause:_

----
UNSET path [update-for] (, path [ update-for ])*
----

_keyspace-ref:_ Specifies the keyspace for which to update the document.

You can add an optional namespace-name to the keyspace-name in this way:

namespace-name:keyspace-name.

__use-keys-clause:__Specifies the keys of the data items to be updated.
Optional.
Keys can be any expression.

__set-clause:__Specifies the value for an attribute to be changed.

_unset-clause:_ Removes the specified attribute from the document.

_update-for:_ The update for clause uses the FOR statement to iterate over a nested array and SET or UNSET the given attribute for every matching element in the array.

__where-clause:__Specifies the condition that needs to be met for data to be updated.
Optional.

__limit-clause:__Specifies the greatest number of objects that can be updated.
This clause must have a non-negative integer as its upper bound.
Optional.

__returning-clause:__Returns the data you updated as specified in the `result_expression`.

*RBAC Privileges*

User executing the UPDATE statement must have the _Query Update_ privilege on the target keyspace.
If the statement has any clauses that needs data read, such as SELECT clause, or RETURNING clause, then _Query Select_ privilege is also required on the keyspaces referred in the respective clauses.
For more details about user roles, see
xref:learn:security/authorization-overview.adoc[Authorization].

For example,

To execute the following statement, user must have the _Query Update_ privilege on `pass:c[`travel-sample`]`.

----
UPDATE `travel-sample` SET foo = 5
----

To execute the following statement, user must have the _Query Update_ privilege on the `pass:c[`travel-sample`]` and _Query Select_ privilege on `pass:c[`beer-sample`]`.

----
UPDATE `travel-sample`
SET foo = 9
WHERE city = (SELECT raw city FROM `beer-sample` WHERE type = "brewery"
----

To execute the following statement, user must have the _Query Update_ privilege on `pass:c[`travel-sample`]` and _Query Select_ privilege on `pass:c[`travel-sample`]`.

----
UPDATE `travel-sample`
SET city = "San Francisco"
WHERE lower(city) = "sanfrancisco"
RETURNING *
----

*Example*

The following statement changes the "type" of the product, "odwalla-juice1" to "product-juice".

----
UPDATE product USE KEYS "odwalla-juice1" SET type = "product-juice" RETURNING product.type

"results": [
        {
            "type": "product-juice"
        }
    ]
----

This statement removes the "type" attribute from the "product" keyspace for the document with the "odwalla-juice1" key.

----
UPDATE product USE KEYS "odwalla-juice1" UNSET type RETURNING product.*

"results": [
        {
            "productId": "odwalla-juice1",
            "unitPrice": 5.4
        }
    ]
----

This statement unsets the "gender" attribute in the "children" array for the document with the key, "dave" in the `tutorial` keyspace.

----
UPDATE tutorial t USE KEYS "dave" UNSET c.gender FOR c IN children END RETURNING t

"results": [
        {
            "t": {
                "age": 46,
                "children": [
                    {
                        "age": 17,
                        "fname": "Aiden"
                    },
                    {
                        "age": 2,
                        "fname": "Bill"
                    }
                ],
                "email": "dave@gmail.com",
                "fname": "Dave",
                "hobbies": [
                    "golf",
                    "surfing"
                ],
                "lname": "Smith",
                "relation": "friend",
                "title": "Mr.",
                "type": "contact"
            }
        }
    ]
----

Starting version 4.5.1, the UPDATE statement has been improved to SET nested array elements.
The FOR clause is enhanced to evaluate functions and expressions, and the new syntax supports multiple nested FOR expressions to access and update fields in nested arrays.
Additional array levels are supported by chaining the FOR clauses.
// <codeblock>Syntax</codeblock>

.Example
----
UPDATE default
    SET i.subitems = ( ARRAY OBJECT_ADD(s, 'new', 'new_value' )
        FOR s IN i.subitems END )
            FOR s IN ARRAY_FLATTEN(ARRAY i.subitems
                FOR i IN items END, 1) END;
----
