= UPSERT
:page-topic-type: concept

Used to insert a new record or update an existing one.
If the document doesn’t exist it will be created.
UPSERT is a combination of INSERT and UPDATE.

[.var]`upsert:`

----
UPSERT INTO keyspace-ref [insert-values | insert-select]  [ returning-clause]
----

[.var]`keyspace-ref:`

----
[(namespace-name :)]  keyspace [ [AS] alias]
----

[.var]`keyspace:`

----
identifier
----

[.var]`insert-values:`

----
 [ (  [ PRIMARY ] KEY , VALUE ) ]  values-clause [, values-clause]*
----

[.var]`values-clause:`

----
VALUES ( expression, expression )
----

[.var]`insert-select`

----
( [PRIMARY] KEY expression [ , VALUE expression ] ) select
----

[.var]`returning-clause:`

----
 RETURNING (result-expression [, result-expression]* | [RAW | ELEMENT ] expression)
----

[.var]`result-expression:`

----
[path . ]  * | expression [ [ AS ] alias ]
----

[.var]`path:`

----
identifier [ [ expression ] ] [ . path ]
----

[.var]`keyspace-ref`: Specifies the keyspace into which to upsert the document.

You can add an optional namespace-name to the keyspace-name in this way:

[.var]`namespace-name`:[.var]``keyspace-name``.

Currently, only the `default` namespace is available.
For example, `default:{backtick}travel-sample{backtick}` indicates the `travel-sample` keyspace in the `default` namespace.
If the namespace name is omitted, the default namespace in the current session is used.

[.var]`insert-values`: Specifies the values to be upserted.

[.var]`insert-select`: Specifies the values to be upserted as a SELECT statement.

[.var]`returning-clause`: Returns the data you upserted as specified in the [.var]`result_expression`.

*RBAC Privileges*

User executing the UPSERT statement must have the _Query Update_ and _Query Insert_ privileges on the target keyspace.
If the statement has any RETURNING clauses, then the _Query Select_ privilege is also required on the keyspaces referred in the respective clauses.
For more details about user roles, see
xref:learn:security/authorization-overview.adoc[Authorization].

For example,

To execute the following statement, user must have the _Query Update_ and _Query Insert_ privileges on `pass:c[`travel-sample`]`.

----
UPSERT INTO `travel-sample` (KEY, VALUE)
VALUES ("key1", { "type" : "hotel", "name" : "new hotel" })
----

To execute the following statement, user must have the _Query Update_ and _Query Insert_ privileges on the `pass:c[`travel-sample`]` bucket and _Query Select_ privilege on `pass:c[`travel-sample`]` (for RETURNING clause).

----
UPSERT INTO `travel-sample` (KEY, VALUE)
VALUES ("key1", { "type" : "hotel", "name" : "new hotel" })
RETURNING *
----

To execute the following statement, user must have the _Query Update_ and _Query Insert_ privileges on the `pass:c[`travel-sample`]` bucket and _Query Select_ privilege on `pass:c[`beer-sample`]`.

----
UPSERT INTO `travel-sample` (KEY foo, VALUE bar)
SELECT foo, bar FROM `beer-sample`
----

== Example

The following statement upserts values for [.in]`odwalla-juice1` into the [.in]`product` document:

----
UPSERT INTO product (KEY, VALUE) VALUES ("odwalla-juice1", { "productId": "odwalla-juice1",
      "unitPrice": 5.40, "type": "product", "color":"red"}) RETURNING * ;

"results": [
        {
            "color": "red",
            "productId": "odwalla-juice1",
            "type": "product",
            "unitPrice": 5.4
        }
    ]
----
