= User-Defined Functions
:description: You can call a user-defined function in any expression where you can call a built-in function.
:page-topic-type: concept
:page-edition: Enterprise Edition
:imagesdir: ../../assets/images
:page-partial:

[abstract]
{description}

== RBAC Privileges

To execute global internal functions, you must have the *Execute Global Functions* role.
To execute scoped internal functions, you must have the *Execute Scope Functions* role, with permissions on the specified bucket and scope.

To execute global external functions, you must have the *Execute Global External Functions* role.
To execute scoped external functions, you must have the *Execute Scope External Functions* role, with permissions on the specified bucket and scope.

For more details about user roles, see
xref:learn:security/authorization-overview.adoc[Authorization].

== Description

When you have created a user-defined function, you can call it in any expression, just like a built-in function.
User-defined functions have the same syntax as built-in functions, with brackets `()` to contain any arguments.

The name of the function is usually an unqualified identifier, such as `func1` or `{backtick}func-1{backtick}`.
In this case, the path to the function is determined by the current xref:n1ql:n1ql-intro/sysinfo.adoc#query-context[query context].

To call a global function in a particular namespace, the function name must be a qualified identifier with a namespace, such as `default:func1`.
Similarly, to call a scoped function in a particular scope, the function name must be a qualified identifier with the full path to a scope, such as `default:{backtick}travel-sample{backtick}.inventory.func1`.
Refer to xref:n1ql-language-reference/createfunction.adoc#context[Global Functions and Scoped Functions] for more details.

NOTE: The name of a user-defined function _is_ case-sensitive, unlike that of a built-in function.
You must call the user-defined function using the same case that was used when it was created.

It is not possible to call a user-defined function in an expression if the function has side effects, such as performing mutations.
When you do this, an error is generated.

== Arguments

A user-defined function has zero, one, or more arguments, separated by commas, just like a built-in function.
Each argument is a {sqlpp} expression required by the function.

If the function was created with named parameters, you must supply all the arguments that were specified when the function was created.
If the function was created without named parameters, you cannot supply an argument.
If the function is variadic, you can supply as many arguments as needed, or none.

include::partial$n1ql-language-reference/udf-output.adoc[]

== Examples

Refer to xref:n1ql-language-reference/createfunction.adoc[CREATE FUNCTION] for details on creating user-defined functions.

For simplicity, none of these examples implement any data validation or error checking.
If necessary, you can use xref:n1ql:n1ql-language-reference/conditionalops.adoc[conditional operators] to check the parameters of a user-defined function, and the xref:n1ql:n1ql-language-reference/metafun.adoc#abort[ABORT()] function to generate an error if something is wrong.

.Inline function with expression
====
The following statement creates a function called `to_meters`, which converts feet to meters.

[source,sqlpp]
----
CREATE FUNCTION to_meters(...) { args[0] * 0.3048 };
----

The following query uses the `to_meters` function to express the elevation of the selected airports in meters above mean sea level (mamsl).
The built-in ROUND function is used to round the output to zero decimal places.

.Query
[source,sqlpp]
----
SELECT airportname, ROUND(to_meters(geo.alt)) AS mamsl
FROM `travel-sample`.inventory.airport
LIMIT 5;
----

.Result
[source,json]
----
[
  {
    "airportname": "Calais Dunkerque",
    "mamsl": 4
  },
  {
    "airportname": "Peronne St Quentin",
    "mamsl": 90
  },
  {
    "airportname": "Les Loges",
    "mamsl": 130
  },
  {
    "airportname": "Couterne",
    "mamsl": 219
  },
  {
    "airportname": "Bray",
    "mamsl": 111
  }
]
----
====

.Inline function with subquery
====
The following statement creates a function called `locations`, which selects name and address information from all documents with the specified activity in the `landmark` keyspace.

[source,sqlpp]
----
include::example$n1ql-language-reference/udf-locations-define.n1ql[]
----

The following query uses the `locations` function as the FROM term in a SELECT query.
Compare this query with xref:n1ql-language-reference/from.adoc#ex-subquery-1[Example 2 in FROM Subquery].

.Query
[source,sqlpp]
----
include::example$n1ql-language-reference/udf-locations-query.n1ql[]
----

.Result
[source,json]
----
include::example$n1ql-language-reference/udf-locations-query.jsonc[]
----
====

.External functions
====
For this example, it is assumed that you have created two external functions:

. A function called `geohash`, which depends on the JavaScript `encodeGeoHash` function in the `geohash-js` library;
. A function called `adjacent`, which depends on the JavaScript `calculateAdjacent` function in the `geohash-js` library.

Refer to xref:n1ql-language-reference/createfunction.adoc#ex-external[Example 7 in CREATE FUNCTION] for details.

The following query uses the `geohash` and `adjacent` functions to find the 9-figure geohash of the selected hotel, and the geohashes immediately to the north, south, west, and east.

.Query
[source,sqlpp]
----
SELECT area,
       adjacent(area, "top") AS north,
       adjacent(area, "bottom") AS south,
       adjacent(area, "left") AS west,
       adjacent(area, "right") AS east
FROM `travel-sample`.inventory.hotel
LET area = SUBSTR(geohash(geo.lat, geo.lon), 0, 9)
WHERE name = "Sachas Hotel";
----

.Result
[source,json]
----
[
  {
    "area": "gcw2m05h1",
    "east": "gcw2m05h4",
    "north": "gcw2m05h3",
    "south": "gcw2m055c",
    "west": "gcw2m05h0"
  }
]
----

To view the first geohash on a map, go to http://geohash.org/gcw2m05h1 and follow one of the links provided.
You can view the other geohashes by editing the URL.
At the latitude of the selected hotel, each geohash represents an area of approximately 3 𐄂 5 meters.
====

== Related Links

* To create user-defined functions, refer to xref:n1ql-language-reference/createfunction.adoc[CREATE FUNCTION].
* To execute user-defined functions, refer to xref:n1ql-language-reference/execfunction.adoc[EXECUTE FUNCTION].
* To view user-defined functions, refer to xref:manage:monitor/monitoring-n1ql-query.adoc#sys-functions[Monitor Queries].
* To drop user-defined functions, refer to xref:n1ql-language-reference/dropfunction.adoc[DROP FUNCTION].
