= User-Defined Functions
:page-topic-type: reference
:page-status: Developer Preview
:imagesdir: ../../assets/images
:page-partial:

[abstract]
You can call a user-defined function in any expression where you can call a built-in function.

include::ROOT:partial$developer-preview.adoc[tag=admonition]

// == RBAC Privileges
// 
// TODO: Waiting for new RBAC roles to be implemented for user-defined functions.
// For more details about user roles, see
// xref:learn:security/authorization-overview.adoc[Authorization].

== Description

When you have created a user-defined function, you can call it in any expression, just like a built-in function.
User-defined functions have the same syntax as built-in functions, with brackets `()` to contain any arguments.

The name of the function may be an unqualified identifier, such as `func1` or `{backtick}func-1{backtick}`, or a qualified identifier with a namespace, such as `default:func1`.

NOTE: The name of a user-defined function _is_ case-sensitive, unlike that of a built-in function.
You must call the user-defined function using the same case that was used when it was created.

== Arguments

A user-defined function has zero, one, or more arguments, separated by commas, just like a built-in function.
Each argument is a N1QL expression required by the function.

If the function was created with named parameters, you must supply all the arguments that were specified when the function was created.
If the function was created without named parameters, it is variadic, and you can supply as many arguments as needed.

include::partial$n1ql-language-reference/udf-output.adoc[]

== Examples

For simplicity, none of these examples implement any data validation or error checking.

(Refer to xref:n1ql-language-reference/createfunction.adoc#create-function-inline[Inline Functions] for details on creating inline user-defined functions.)

.Inline function with expression
====
The following statement creates a function called `to_meters`, which converts feet to meters.

[source,n1ql]
----
CREATE FUNCTION to_meters() { args[0] * 0.3048 };
----

The following query uses the `to_meters` function to express the elevation of the selected airports in meters above mean sea level (mamsl).
The built-in ROUND function is used to round the output to zero decimal places.

.Query
[source,n1ql]
----
SELECT airportname, ROUND(to_meters(geo.alt)) AS mamsl
FROM `travel-sample`
WHERE type = "airport"
LIMIT 5;
----

.Result
[source,json]
----
[
  {
    "airportname": "Calais Dunkerque",
    "mamsl": 4
  },
  {
    "airportname": "Peronne St Quentin",
    "mamsl": 90
  },
  {
    "airportname": "Les Loges",
    "mamsl": 130
  },
  {
    "airportname": "Couterne",
    "mamsl": 219
  },
  {
    "airportname": "Bray",
    "mamsl": 111
  }
]
----
====

.Inline function with subquery
====
The following statement creates a function called `locations`, which selects name and address information from all documents of the specified type in the `travel-sample` bucket.

[source,n1ql]
----
CREATE FUNCTION locations(vType) { (
  SELECT id, name, address, city
  FROM `travel-sample`
  WHERE type = vType) };
----

The following query uses the `locations` function as the FROM term in a SELECT query.
Compare this query with Example 2 in the section on xref:n1ql-language-reference/from.adoc#select-expr[FROM Subquery].

.Query
[source,n1ql]
----
SELECT l.name, l.city
FROM locations("landmark") as l
WHERE l.city = "Gillingham";
----

.Result
[source,json]
----
[
  {
    "city": "Gillingham",
    "name": "Royal Engineers Museum"
  },
  {
    "city": "Gillingham",
    "name": "Hollywood Bowl"
  },
  {
    "city": "Gillingham",
    "name": "Thai Won Mien"
  },
  {
    "city": "Gillingham",
    "name": "Spice Court"
  },
  {
    "city": "Gillingham",
    "name": "Beijing Inn"
  },
  {
    "city": "Gillingham",
    "name": "Ossie's Fish and Chips"
  }
]
----
====

== Related Links

* To create user-defined functions, refer to xref:n1ql-language-reference/createfunction.adoc[CREATE FUNCTION].
* To execute user-defined functions, refer to xref:n1ql-language-reference/execfunction.adoc[EXECUTE FUNCTION].
* To view user-defined functions, refer to xref:manage:monitor/monitoring-n1ql-query.adoc#sys-functions[Monitor Queries].
* To drop user-defined functions, refer to xref:n1ql-language-reference/dropfunction.adoc[DROP FUNCTION].
