= Backup and Restore

[abstract]
In a production environment, as part of an overall Disaster Recovery plan, you must plan to back up your entire cluster periodically.
This helps ensure that you do not lose information in the event of a serious failure and minimizes data inconsistency when a restore is required.

Couchbase provides multiple means to facilitate backup and restore:

* Using [.cmd]`cbbackupmgr` Tool
+
Couchbase Backup Manager is an enterprise-grade backup and restore utility that is available in the Couchbase Server Enterprise Edition only.
Designed for the Enterprise Edition, it replaces the [.cmd]`cbbackup` and [.cmd]`cbrestore` tools as the primary and recommended means of backup and restore for Enterprise customers from version 4.5 and above.
It enables backup and restore of data, indexes, and bucket configurations at a dramatically increased speed over the previous generation tools.
All backups can be performed on a live running cluster.
For more information on cbbackupmgr, see xref:enterprise-backup-restore.adoc[[.cmd]`cbbackupmgr` Tool].

* Using [.cmd]`cbbackup` and [.cmd]`cbrestore` Tools
+
The [.cmd]`cbbackup` and [.cmd]`cbrestore` tools provide simple yet effective backup and restore capabilities to Couchbase Server.
+
The cbbackup tool enables you to backup a single node, single buckets, or the entire cluster into a flexible backup structure.
The cbrestore tool restores data into the same or different clusters and buckets.
+
For more information on these tools, see xref:cli:cbtools/cbbackup.adoc[[.cmd]`cbbackup`] and xref:cli:cbtools/cbrestore.adoc[[.cmd]`cbrestore`].

NOTE: Due to the active nature of Couchbase Server, it is impossible to create a complete in-time backup and snapshot of the entire cluster.
Because the data is always being updated and modified, it is not possible to take an accurate snapshot.

NOTE: You must back up and restore your entire cluster to minimize any data inconsistencies.
Couchbase is always per-item consistent but does not guarantee total cluster consistency or in-order persistence.
