= cbbackupmgr
:description: pass:q[`cbbackupmgr` is a tool for managing the backup and restore of Couchbase-Server data.]

[abstract]
{description}

== Understanding cbbackupmgr

The `cbbackupmgr` tool backs up and restores data, scripts, configurations, and more.
It allows large data sets to be managed with extremely high performance.
Use of AWS S3 storage is supported.

Only Full Administrators can use `cbbackupmgr`; which is available in Couchbase Server _Enterprise Edition_ only.
Note that `cbbackupmgr` is _not_ backward compatible with backups created by means of `cbbackup`.

=== Planning for Disaster Recovery

Backup and restore capabilities are critical to an overall Disaster Recovery Plan, and ensuring thereby business continuity.
Administrators are therefore recommended to define plans for both https://en.wikipedia.org/wiki/Recovery_time_objective[Recovery Time Objective^] (RTO) and https://en.wikipedia.org/wiki/Recovery_point_objective[Recovery Point Objective^] (RPO), and make use of `cbbackupmgr` correspondingly.

=== Backup Repositories

All backup is stored in and recovered from a [.term]_Backup Repository_.
In turn, a [.term]_Backup Repository_ is stored in a Backup Archive on the filesystem.
Each backup job in the [.term]_Backup Repository_ stores its backup in two ways:

* All bucket data is stored in a small, secondary database.
* All bucket creation scripts and configuration files are stored on the file system, as files.

=== Tool Locations

The `cbbackupmgr` tool is installed, with all other tools, in the following _per platform_ locations:

.Backup Tool Locations
[cols="1,5"]
|===
| Operating system | Directory locations

| Linux
| [.path]_/opt/couchbase/bin/cbbackupmgr_

| Windows
| [.path]_C:\Program Files\Couchbase\Server\bin\cbbackupmgr_

Assumes default installation location

| Mac OS X
| [.path]_/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin/cbbackupmgr_
|===

== How the Backup and Restore Tool Works

By default, the [.cmd]`cbbackupmgr` tool performs incremental backups to back up only the new data.
However, on a new cluster and for the first time, this tool generates a full backup.
Each of the subsequent, incremental backups take a fraction of the time taken by the full backup.

== Archive Repository

The backup archive is a directory that contains a set of backup repositories as well as logs for the backup client.
The backup directory should be modified only by the backup client, and any modifications that are not done by that client might result in a corruption of backup data.

Only one backup client can access the backup archive at one time.
If multiple instances of the backup client are running on the same archive at the same time, this might result in corruption.
To prevent such corruption instances, you may be required to create multiple backup archives depending on your use case.

[#version-compatibility]
== Version Compatibility

For 6.5 and all later versions, `cbbackupmgr` can be used to back up data either from a cluster running its own version, or from a cluster running a prior, _compatible_ version.
For example, the 6.6.0 tool can back up data from a cluster running 6.6.0, 6.5.x, 6.0.x, or 5.5.x.
It can also be used to restore _to_ any of those versions data previously backed up _from_ any of those versions.

The following table lists the compatible cluster-versions for each version of `cbbackupmgr`.
Unless otherwise specified, backup and restore apply both to _local_ and to _cloud_ data.

.Compatibility Requirements for Backup and Restore
[cols="5,3,3,3,3,3,3,3,3"]
|===
| *cbbackupmgr version*
| *7.2*
| *7.1*
| *7.0*
| *6.6*
| *6.5.x*
| *6.0.x*
| *5.5.x*
| *5.0.x*

| 7.2
| ✓
| ✓
| ✓
| ✓
| 
|
|
|

| 7.1
|
| ✓
| ✓
| ✓
| ✓*
|
|
|

| 7.0
|
|
| ✓
| ✓
| ✓*
| ✓*
|
|

| 6.6.0 and above
|
|
|
| ✓
| ✓*
| ✓*
| ✓*
|

| 6.5
|
|
|
|
| ✓
| ✓
| ✓
|

| 6.0.x
|
|
|
|
|
| ✓
|
|

| 5.5.x
|
|
|
|
|
|
| ✓
|

| 5.0.x
|
|
|
|
|
|
|
| ✓

|===

&#42; For local backup only -- _not_ for cloud.
