= Collections via REST

[abstract]
_Collections_ can be managed by means of the Couchbase REST API.

[#Using the REST API]
== Using the REST API

The following sequence of commands assumes that Couchbase Server has been installed, initialized, and provisioned on a _Ubuntu_ system.
Note, however, that the sequence should work identically on other Linux systems; as well as on MacOS and Windows systems.

At the command-line prompt, proceed as follows:

. Create a bucket, named `testBucket`, using the `/pools/default/buckets` REST method:
+
----
curl -X POST -u Administrator:password \
http://localhost:8091//pools/default/buckets \
-d name=testBucket \
-d bucketType=couchbase \
-d autoCompactionDefined=false \
-d evictionPolicy=valueOnly \
-d threadsNumber=3 \
-d replicaNumber=1 \
-d compressionMode=passive \
-d maxTTL=0 \
-d replicaIndex=0 \
-d conflictResolutionType=seqno \
-d ramQuotaMB=100 \
-d flushEnabled=0
----
+
For information on this REST call and its parameters, see xref:rest-api:rest-bucket-create.adoc[Creating and Editing Buckets].

. Create a scope. This is a POST operation, using the `/pools/default/buckets/_<bucket>_/collections` endpoint, and specifying the `-name` parameter.
+
----
curl -u Administrator:password -X POST \
http://localhost:8091/pools/default/buckets/testBucket/collections \
-d name=my_scope
----
+
If successful, the command returns a _uid_ for the action (this is principally for internal use, and need not be tracked by the user):
+
----
{"uid":1}
----
+
Now, examine the collections _manifest_ for the specified bucket.
This is a GET operation, using the same endpoint as the previous POST, with no parameter.
+
----
curl -u Administrator:password -X GET \
http://localhost:8091/pools/default/buckets/testBucket/collections
----
+
This returns the following output:
+
----
{"my_scope":{},"_default":{"_default":{}}}
----
+
Formatted, this output is as follows:
+
----
{
  "my_scope": {},
  "_default": {
    "_default": {}
  }
}
----
+
This output shows that the bucket now contains two scopes, which are `my_scope` and `_default`.
The `_default` scope contains a single collection, which is also named `_default`.
