= Collections via CLI

[abstract]
_Collections_ can be managed by means of the Couchbase CLI.

[#Using the CLI]
== Using the CLI

The following sequence of CLI commands demonstrates how to create, examine, and delete scopes and collections.
It assumes that Couchbase Server has been installed, initialized, and provisioned on a _Ubuntu_ system.
Note, however, that the sequence should work identically on other Linux systems; as well as on MacOS and Windows systems.

At the command-line prompt, proceed as follows:

. Create a bucket, named `test-bucket`, using the couchbase-cli `bucket-create` command.
+
----
/opt/couchbase/bin/couchbase-cli bucket-create \
--cluster localhost:8091 --username Administrator \
--password password --bucket testBucket --bucket-type couchbase
--bucket-ramsize 100
----
+
If the command is successful, the following output is displayed:
+
----
SUCCESS: Bucket created
----
+
For more information on this command, see xref:cli:cbcli/couchbase-cli-bucket-create.adoc[bucket-create].

. Using the `cbstats` command, check that collections have been enabled, and check the maximum size for collections, then for scopes:
+
----
/opt/couchbase/bin/cbstats -u Administrator -p password localhost:11210 -b testBucket all | grep collections
----
+
The following output is displayed:
+
----
ep_collections_enabled:                                true
ep_collections_max_size:                               1000
----
+
This indicates that collections are enabled, and that a maximum number 1000 collections can be created for the bucket.
+
Check the maximum size for scopes:
+
----
/opt/couchbase/bin/cbstats -u Administrator -p password localhost:11210 -b testBucket all | grep scopes
----
+
The following output is displayed:
+
----
ep_scopes_max_size:                                    100
----
+
The output indicates that a maximum number of 100 scopes can be created for the bucket.

. Create a scope, using the couchbase-cli `collection-manage` command.
The `--bucket` parameter specifies the name of the bucket within which the scope will be created; and the `--create-scope` parameter specifies the name of the scope.
+
----
/opt/couchbase/bin/couchbase-cli collection-manage \
--cluster http://localhost:8091 \
--username Administrator \
--password password \
--bucket testBucket \
--create-scope my_scope
----
+
If the command is successful, the following output is displayed:
+
----
SUCCESS: Scope created
----

. List the scopes now contained by the bucket `testBucket`.
+
----
/opt/couchbase/bin/couchbase-cli collection-manage \
-c localhost \
--username Administrator \
--password password \
--bucket testBucket \
--list-scopes
----
+
The following output is displayed:
+
----
_default
my_scope
----
+
This indicates that `testBucket` now contains two scopes.
One is the `_default`, the other is the newly created scope `my_scope`.

. Use `collection-manage` successively, to create two collections within `my_scope`.
The name of the collection to be created is specified with the `--create-collection` parameter, using a path in dot format (that is, in the form _scope-name.collection-name_) to specify the destination scope.
Then, list the collections in the scope, using collection-manage with the `--list-collections` parameter.
+
Create the `my_scope.my_collection_in_my_scope_1` collection:
+
----
/opt/couchbase/bin/couchbase-cli `collection-manage` -c localhost \
--username Administrator \
--password password \
--bucket testBucket \
--create-collection my_scope.my_collection_in_my_scope_1
----
+
On success, the output is as follows:
+
----
SUCCESS: Collection created
----
+
Create the `my_scope.my_collection_in_my_scope_2` collection:
+
----
/opt/couchbase/bin/couchbase-cli collection-manage -c localhost \
--username Administrator \
--password password \
--bucket testBucket \
--create-collection my_scope.my_collection_in_my_scope_2
----
+
On success, the output is as again follows:
+
----
SUCCESS: Collection created
----
+
Now, list all collections:
+
----
/opt/couchbase/bin/couchbase-cli collection-manage -c localhost \
--username Administrator \
--password password \
--bucket testBucket \
--list-collections my_scope
----
+
If the command is successful, the output features a list of all created collections within `my_scope`:
+
----
my_collection_in_my_scope_1
my_collection_in_my_scope_2
----
+
The output indicates that `my_scope` now contains the collections `my_collection_in_my_scope_1` and `my_collection_in_my_scope_1`.

. Create a collection in the `_default` scope, and then list collections within that scope.
+
----
/opt/couchbase/bin/couchbase-cli collection-manage -c localhost \
--username Administrator \
--password password \
--bucket testBucket \
--create-collection _default.my_collection_in_default_scope
----
+
On success, the following output is displayed:
+
----
SUCCESS: Collection created
----
+
Now, list collections within the scope:
+
----
/opt/couchbase/bin/couchbase-cli collection-manage -c localhost \
--username Administrator \
--password password \
--bucket testBucket \
--list-collections _default
----
+
On success, a list of the collections in the scope is displayed:
+
----
my_collection_in_default_scope
_default
----
+
The output indicates that the _default scope now contains two collections, which are the `_default` collection, and the newly created collection `my_collection_in_default_scope`.
