= Configure Client Certificates

[abstract]
Couchbase Server supports client-authentication by means of X.509
certificates.

[#couchbase-client-authentication]
== Couchbase Client Authentication

Couchbase clients can authenticate by means of X.509 certificates. This
page explains how client certificates can be prepared for a Java client. It
also provides information on TLS levels, and on supported ciphers.

For a list of Couchbase-Server ports that provide secure connectivity to
clients, see
xref:learn:clusters-and-availability/connectivity.adoc[Connectivity].

[#cert_auth_for_java_client]
== Configure Certificates for a Java Client

Once the root certificate for a Couchbase Server-node has been deployed, a
Java client can authenticate by means of an appropriately prepared keystore,
and so gain access to the Data, Query, and Search Services.

Proceed as follows.
Note that these instructions use the Ubuntu 16 environment previously configured
in
xref:manage:manage-security/configure-server-certificates.adoc[Configure
Server Certificates].

. Define environment variables for the name of the keystore to be created, and its password.
+
[source,bash]
----
export KEYSTORE_FILE=my.keystore
export STOREPASS=storepass
----

. If necessary, install a package containing the `keytool` utility:
+
[source,bash]
----
sudo apt install openjdk-9-jre-headless
----

. Within the top-level, `SSLCA` directory that you created, generate the keystore.
Note that the password you specify for the alias, by means of the `--keypass` flag, must be identical to the password you specify for the keystore, by means of the `--storepass` flag.
In this case, both passwords are specified as `&#36;&#123;STOREPASS&#125;`; which resolves to `storepass`.
+
[source,bash]
----
keytool -genkey -keyalg RSA -alias selfsigned \
-keystore ${KEYSTORE_FILE} -storepass ${STOREPASS} -validity 360 -keysize 2048 \
-noprompt  -dname "CN=${USERNAME}, OU=None, O=None, L=None, S=None, C=US" -keypass ${STOREPASS}
----

. Generate the certificate signing-request:
+
[source,bash]
----
keytool -certreq -alias selfsigned -keyalg RSA -file my.csr \
-keystore ${KEYSTORE_FILE} -storepass ${STOREPASS} -noprompt
----

. Generate the client certificate, signing it with the intermediate private key:
+
[source,bash]
----
openssl x509 -req -in my.csr -CA ./${INT_DIR}/${INTERMEDIATE}.pem \
-CAkey ./${INT_DIR}/${INTERMEDIATE}.key -CAcreateserial -out clientcert.pem -days 365
----

. Add the root certificate to the keystore:
+
[source,bash]
----
keytool -import -trustcacerts -file ./${ROOT_DIR}/${ROOT_CA}.pem \
-alias root -keystore ${KEYSTORE_FILE} -storepass ${STOREPASS} -noprompt
----

. Add the intermediate certificate to the keystore:
+
[source,bash]
----
keytool -import -trustcacerts -file ./${INT_DIR}/${INTERMEDIATE}.pem \
-alias int -keystore ${KEYSTORE_FILE} -storepass ${STOREPASS} -noprompt
----

. Add the client certificate to the keystore:
+
[source,bash]
----
keytool -import -keystore ${KEYSTORE_FILE} -file clientcert.pem \
-alias selfsigned -storepass ${STOREPASS} -noprompt
----

This concludes preparation of the Java client's keystore.
Copy the file (in this case, `my.keystore`) to a location on a local filesystem
from which the Java client can access it.

[#enabling-client-security]
== Securing Client Access with TLS

For an application to communicate securely with Couchbase Server, SSL/TLS must
be enabled on the client side.
Enablement requires a copy of the certificate used by Couchbase Server: this can be accessed from the Couchbase Web Console, as described in
xref:manage:manage-security/manage-security-settings.adoc#root-certificate-security-screen-display[Root
Certificate].

Note that if, at some point, this certificate gets regenerated on the server-side, a copy of the new version must be obtained, and the client re-enabled.
