= Configure Server Certificates

[abstract]
Couchbase Server Enterprise Edition supports X.509 certificates, for
the encryption of communications between the server and
networked clients.

[#certificate-management-preparation]
== Certificate-Management Preparation

Before configuring certificates for Couchbase Server, see the conceptual and architectural information provided in xref:learn:security/certificates.adoc[Certificates].

[#configure-server-side-certificates]
== Configure Server-Side Certificates

The following steps configure X.509 certificates for Couchbase Server on Ubuntu 16.
Use the `sudo` command where appropriate.

. Create working directories:
+
----
mkdir -p {public,private,requests}
----
+
The `public` directory will be used to store certificates and public keys, the `private` to store private keys.
The `requests` directory will store _certificate signing requests_, which are the materials generated from private keys to be subsequently signed, as _certificates_, by an appropriate authority.

. Define certificate extensions for the cluster.
+
_Certificate extensions_ specify how a certificate is to be used.
When an attempt is made to use the certificate, all usage-requirements must be satisfied for the certificate to be usable.
+
For example, the certificate's public key can be constrained, by means of the `keyUsage` extension, to providing _digital signatures_ rather than _key encipherment_; or vice versa.
Or, it can be expressly permitted to provide both.
Meanwhile, the `subjectAltName` extension can be used to specify the _DNS name_ and _IP address_ of the server on which the certificate resides; so that the certificate becomes invalid if deployed in any different context.
+
For detailed information on certificate extensions, see the http://https://tools.ietf.org/html/rfc5280#section-4.2.1[Standard Extensions] section of the http://https://tools.ietf.org/html/rfc5280[Internet X.509 Public Key Infrastructure Certificate and Certificate Revocation List (CRL Profile)].
+
The most convenient way of specifying certificate extensions is by means of a file, provided as a parameter to the `openssl` command used to create the certificate.
The extensions for the server might be defined as follows:
+
----
cat > server.ext <<EOF
basicConstraints=CA:FALSE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer:always
extendedKeyUsage=serverAuth
keyUsage = digitalSignature,keyEncipherment
subjectAltName = DNS:node2.cb.com,IP:10.143.192.102
EOF
----
+
Note that these extensions assume that the DNS name of the server-node is `node2.cb.com`, and its IP address is `10.143.192.102`.
If experimentation is being performed locally, the `/etc/hosts` file for the local machine should contain a line such as the following:
+
----
10.143.192.102  node2.cb.com
----

. Create a private key for the cluster.
+
An RSA asymmetric _private key_ allows the _decryption_ of data previously _encrypted_ by the corresponding RSA asymmetric _public key_.
Note that in the key-creation sequence, the public key is _derived from_ the private, and therefore created after it.
+
Enter the following:
+
----
openssl genrsa -out ca.key 2048
----
+
The output of this command, `ca.key`, is the private key for the cluster.

. Create the _certificate_ (that is, the file containing the public key) for the cluster.
+
Enter the following:
+
----
openssl req -new -x509 -days 3650 -sha256 -key ca.key -out ca.pem -subj "/CN=Couchbase Root CA"
----
+
The `x509` flag indicates that an x509 structure, rather than a _request_ should be generated.
The `days` flag spcifies the number of days for which the certificate should be active.
The hashing algorithm used for digital-signature creation for the certificate is specified as `sha256`.
The private `key` file on which the certificate is to be based is specified as `ca.key`, and the output certificate is named as `ca.pem`.
The certificate's _issuer_ is specified to have the `CN` (_Common Name_) of `Couchbase Root CA`: this will indeed be the root certificate for the Couchbase Server-cluster to be accessed.
+
The output of the command is the certificate `ca.pem`.
This contains the public key that corresponds to the cluster's private key, `ca.key`.
+
Optionally, the public key within the certificate can be displayed as follows:
+
----
openssl x509 -in ./ca.pem -noout -pubkey
----
+
The output has approximately the following appearance:
+
----
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3HMfiSjCwakfMbA20HUd
V372JbQG9UGjf9V3xyMa90IHFD8cFjPYao7SZOpe0nkm2UmZRgQbTwWxC4CZqrYZ
pyrWLn9rjDFkzzbRjMRcZv2D0s0KkPrNYxfHj3cL/j5bpB4/hquvb4RglMkyyJo9
mVx19lF4mtEsBqPGZBGArbzeArn4c1e6I4mqIfb9Vne/7vhIzLLSXoT5FmifWyGQ
4B9BSIrE9Ildwhez699MGfj+N+0xg2wTOIUVNvS1c5gF/uDS6t9Aswb60W+hjtF4
d1ZBKBIVkmPGX0XOgGtdndXza4sjVkh3bB/ipWo9zUJYwFCWkofbqGeSnSz9n9o6
fwIDAQAB
-----END PUBLIC KEY-----
----
+
Note that by substituting other flags for `pubkey`, other characteristics of the certificate can be displayed.
`issuer` displays the certificate's issuer, and `subject` its subject (in both cases, `subject= /CN=Couchbase Root CA`).
The `version`, `serial`, `subject-hash`, and more can also be displayed.
+
The _entire certificate_ can be displayed as text, by means of the following command:
+
----
openssl x509 -text -noout -in ./ca.pem
----

. Create a private key for the server node.
+
In addition to the root certificate and private key for the entire cluster, `ca.pem` and `ca.key` respectively, a _node_ certificate and private key must also be created.
The node certificate and private key will reside on each node of the cluster.
The node certificate will specify the root certificate, `ca.pem`, as its issuer; and thereby records the chain of authority whereby clients may choose to trust it.
When deployed, the node certificate must be named `chain.pem`, and the node private key `pkey.key`.
+
Create the node private key as follows:
+
----
openssl genrsa -out private/couchbase.default.svc.key 2048
----
+
The output file is `couchbase.default.svc.key`, which is the private key for the node.

. Create a certificate signing request for the node certificate.
+
Enter the following command:
+
----
openssl req -new -key private/couchbase.default.svc.key -out requests/couchbase.default.svc.csr -subj "/CN=Couchbase Server"
----
+
The `key` specified as the input for the request is `couchbase.default.svc.key`, which was created in the last step.
The output request-file is specified as `couchbase.default.svc.csr`.
Note that the request file can be inspected as text, by entering the following command:
+
----
openssl req -text -noout -verify -in ./requests/couchbase.default.svc.csr
----

. Create a self-signed certificate for the node.
+
Enter the following:
+
----
openssl x509 -CA ca.pem -CAkey ca.key -CAcreateserial -days 365 -req \
-in requests/couchbase.default.svc.csr -out public/couchbase.default.svc.pem \
-extfile server.ext
----
+
For further information on certificate-deployment, see xref:cli:cbcli/couchbase-cli-ssl-manage.adoc[ssl-manage] and xref:rest-api:rest-encryption.adoc[Encryption On-the-Wire API].
