= Configure SAML
:description: You can enable _Structured Authentication Markup Language_ (SAML)  authentication that allows users to log into the Couchbase Server Web Console. This authentication methods offers features such as single sign on, two-factor authentication, and centralized authentication administration.

[abstract]
{description}

See xref:learn:security/authentication-domains.adoc#saml-authentication[SAML Authentication] for an overview of SAML authentication. 

== Prerequisites

Before configuring SAML authentication consider the following:

Identity Provider::
SAML authentication relies on an _Identity Provider_ (IdP) to authenticate a user with the Couchbase Server Web Console. Couchbase Server supports the following IdPs:
+
* Okta
* Microsoft Azure AD
+
Note: Other IdPs may work. Couchbase Server was tested with the IdPs in the previous list.
+
Your IdP may have its own requirements for interacting with services like Couchbase Server. See your IdP's documentation to understand its requirements. 

Certificates::
 SAML authentication requires encryption. You need a key and certificate for your Couchbase cluster to use when encrypt and decrypt this data. You can use a unique certificate specifically for SAML authnetication. You can also use the same certificate you use for client authentication. 
 +
 Most IdPs expect certificates that are signed by a _Certificate Authority_ (CA) to verify authenticity. You can use a certificate signed by an intermediate certificate that was in turn signed by a CA if you also provide the intermediate certificate. For example, suppose your organization creates a certificate for you that they sign using a certificate signed by a CA. You can use this certificate with an IdP that requires CA-signed certificates by including a copy of the CA-signed certificate. The IdP uses the intermediate certificate to verify the authenticity of your cluster's certificate.
 + 
 You can supply Couchbase Server with a certificate to authenticate messages from and encrypt SAML messages to the IdP. Your IdP provides this certificate to you. 

Trusted Fingerprints::
Instead of using an IdP-provided certificate, you can choose to use trusted fingerprints for verifying the authenticity of an IdP SAML message. Using fingerprints reduces the overhead of verification. 

Network Configuration::
Some IdPs do not require a direct network connection to your Couchbase Server. Instead, the user's browser transmits the authentication request and response between Couchbase Server and the IdP. However, some IdPs may want to connect to services such as Couchbase Server to verify SAML metadata such as the certificate. This connection enables frequent key rotation, which helps increase security. Verify any inbound network connection requirements with your IdP. 
+
If you restrict your Couchbase cluster's access to the Internet, consider granting it access to the IdP. Allowing this connection makes SAML configuration easier and automates updating the IdP's certificates when they change due to key rotation.  

IdP Metadata::
Couchbase Server needs metadata about the IdP to be able to accept authentication messages from it. If your Couchbase Cluster can connect to the IdP, you can have it directly retrieve the IdP's metadata. See your IdP's documentation for this URL. You can configure Couchbase Server to periodically refresh this metadata to learn of changes to the IdP's configuration.
+
If Couchbase Server cannot connect to the IdP, you can upload a a file containing the metadata. 

Group and Roles Management::
Decide whether you'll manage group and role membership in Couchbase Server or in the IdP. If you decide to manage groups and roles in Couchbase Server, create Couchbase Server users in the external authentication realm. Assign these users the groups and roles they need. If you choose to manage groups and roles in the IdP, create SAML attributes that you'll map to Couchbase Server groups and roles. Edit the users in the IdP so their attributes reflect the groups and roles they need. 

NameID and User Identity::
Sets the format your IdP uses to identify authenticated users. The SAML authentication message sent from the IdP to Couchbase Server identify the user using a format called NameID. The nameID format is a colon-delimited string. It can be one of the following values:
+
* `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified` does not set a format for the user identity. It can be any text string. This is the most common value.
* `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress` sets the format to an email address.
* `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` uses a unique identifier that remains constant across different IdPs and services.
* `urn:oasis:names:tc:SAML:2.0:nameid-format:transient` uses a unique but temporary identifier 
+
Instead of relying on the nameID, you can also have Couchbase Server get the username from an attribute in the SAML message. Use an attribute instead of the nameID if the IdP uses a format that doesn't match Couchbase Server usernames. For example, suppose the IdP only supports identifying users using an email address instead of a username. In this case, you can have the IdP send the user's username in an attribute. Then configure Couchbase Server to extract the username from the attribute instead of using the nameID.

== Configure SAML with the UI

To configure SAML authentication using Web Console:

. In the navigation bar, click *Security*.
. In the navigation menu, click *SAML*.
. Turn on the *Enabled* toggle.
. Complete the following procedures to finish configuring SAML:
.. <<configure-couchbase-metadata>>
.. <<configure-the-idp>>
.. <<configure-single-sign-on>>
.. Optionally, <<configure-advanced-settings>>. 

### Configure Couchbase Metadata

Under *Metadata*, enter information about your Couchbase Server and organization. Most of these fields supply contact information to your IdP and do not affect the authentication process. The exceptions are:

SP Entity ID::
A URL that identifies your Couchbase Server to the IdP. You add this URL to your IdP's configuration so it can identify which service the user is authenticating with. This field is optional. If you do not enter a value, Couchbase Server uses a URL based on the node's fully qualified domain name, port number, and the path to the metadata page (`/saml/metadata`). 
SP Base URL Type::
This option controls hostname in the URL that the IdP redirects the user's browser to after authentication. Choose this option based on the address users enter to connect to your Couchbase Server:
+
* *Node address* sends the user back to the self-reported address of the node the user is logging into. 
* *Alternate node address* sends the user to the node's alternate address. See xref:learn:clusters-and-availability/connectivity.adoc#alternate-addresses[Alternate Addresses].
* *Custom URL* sends the user to the URL you enter in *Custom URL* which appears when you select this option. Select this option when users use some other URL when connecting to nodes in the cluster. For example, if you use a load balancer to redirect users to nodes, enter its URL here. 

Key and Certificates::
Add the Couchbase Server's private key and certificate. Either copy and paste their content or upload them by clicking bth:[Select File]. If the certificate was not directly signed by a CA, added any intermediate certificates in *Certificate chain*. 

### Configure the IdP

Under *Identity Provider Configuration*, enter the information about your IdP: 

Load IDP metadata from::
Choose to either provide the IdP's metadata URL or to upload a snapshot of its metadata in a file. If you provide a URL, you can have Couchbase Server refresh the metadata periodically.
Verify remote peer::
Select to enable verification of the IdP's certificate. If you enable this option, supply a copy of the IdP's certificate in *CA Certificates*.   
Validate metadata using trusted fingerprints::
Select to enable using fingerprints instead of a certificate to authenticate the metadata from the IdP. Select *Use trusted fingerprints for metadata bootstrap only* to limit using fingerprint verification to just the initial retrieval of the metadata. Select *Always use trusted fingerprints to validate signatures in SAML...* to use fingerprints to validate all SAML messages instead of just metadata.
Trusted Fingerprints::
Add the IdP's trusted fingerprints if you're using them to validate the IdP's messages.

=== Configure Single Sign-On

Under the *Single Sign-On* section, configure how Couchbase Server and the IdP communicate about user authentication.

Authentication IDP Binding::
Logout IDP Binding::
Select *Post* if Couchbase Server should use POST messages to send authentication and logout requests to the IdP. Select *Redirect* if Couchbase Server should use URL parameters instead.
Validate assertion signature::
Validate assertion envelope signature::
Select to have Couchbase verify the signature of either the SAML assertions or the entire SAML envelope the IdP sends. You should enable at least one form of signature validation based on how your IdP signs its messages.

NameID format::
Enter the format that the IdP uses to identify the user. You must enter a value here, even if you configure Couchbase Server to use an attribute for the username.

Username attribute::
Select if you want to use a SAML attribute for the username and enter the attribute's name in *Username attribute*. 

Groups attribute::
Select if you want the IdP to manage group membership. Enter the name of the attribute in the *Groups attribute* box. Enter the separator character in *Groups separator* if your IdP sends lists of groups in a string. If you want Couchbase Server to only use a subset of the group names that the IdP sends it, enter a regular expression in *Groups filter*. Couchbase Server only applies a group to the user if the group's name matches the regular expression. 

Roles attribute::
Select if you want the IdP to manage user roles. Works the same way the Groups attribute works.

=== Configure Advanced Settings

In most cases you do not need to change the settings under *Advanced*. If you're having an issue with the SAML integration, these settings may help resolve it. Most of these settings are self-explanatory. The following settings require 

Value of SP metadata cacheDuration attribute::
Sets how long the IdP caches Couchbase Server's metadata. This value is in https://en.wikipedia.org/wiki/ISO_8601#Durations[ISO8601 duration format^]. The default value `P1M` sets this duration to one month.

SP Assertion Dupe Check::
When you select *Enable Dupe Check*, Couchbase Server prevents a user from reusing an IdP's SAML assertion to connect a second time. When you select *Enable Dupe Check*, you can choose whether this restriction applies to all nodes or just a single node. Select the *Global* option to prevent users from reusing a SAML assertion on any node in the cluster. Select *Local* to prevent reuse on the same node. The *Local* option does allow a user reuse a SAML assertion to log into a different node.

== Configuring Okta as a SAML IdP
Follow these steps to configure Okta as a SAML IdP for Couchbase Server.

. Log into your Okta administrator account.
. Under *Applictions* click *Applications*.
. Click btn:[Create App Integration].
. Select *SAML 2.0* and click btn:[Next].
. In *App Name*, enter a name for your Couchbase Server and click btn:[Next].
. In the *General* section, configure Okta's integration with Couchbase Server. The following table lists the Couchbase Server fields and their corresponding Okta fields.
+
|===
|Okta Field |Couchbase field |Notes

|*Single sign-on URL*
|*Current SP consume URL*
|*Current SP consume URL* appears in Couchbase Server's SAML Configuration page after you enable SAML authentication. This value is the URL of the couchbase node plus the path `saml/consume`. You can add a placeholder value in Okta initially. After enabling SAML in Couchbase Server, update the value in Okta. 

|*Audience URI*
|*SP Entity ID*
|If you do not enter a value in *SP Entity ID*, use the URL shown in *Current SP metadata URL* after enabling SAML in Couchbase Server.

|*Name ID format*
|*NameID format*
|Okta lists just the description of the format instead of the entire format string. For example, select *Unspecified* in Okta's *Name ID format* list if you entered `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified` in Couchbase's *NameID format* field.
|===
. In *Application username* field, choose the Okta attribute that corresponds to the Couchbase Server username. For example, choose *Okta username* if the username in Okta is the same as the username in Couchbase Server. Choose any value if you're using a SAML attribute instead of the SAML subject to set the username for Couchbase Server. 
. Under *Attribute Statements* add entries for any Okta attributes you to want to pass to Couchbase Server as SAML attributes. For example, suppose you want to use a SAML attribute to pass the user's roles from Okta to Couchbase. Then choose a name for the SAML attribute and enter it under the *Name* column. Under the *Value* column, select the Okta attribute for the roles. Later, enter the attribute name in the *Roles attribute* field on the Couchbase Server's SAML page.
. Configure the SAML attribute name under *Group Attribute Statements* if you're using the user's Okta's group membership to set the user's Couchbase Server groups. In the *Name* column, enter the attribute name you set in *Groups attribute* field of the Couchbase Server SAML configuration page.
. Click btn:[Next] and then btn:[Finish].
. The *Sign On* tab contains the information you need to enter into the Couchbase Server SAML configuration page. Click *More details* to show all of the information you need. 
. Copy the Okta values in the following table to their corresponding fields on the SAML page.
+
|===
|Okta Value |SAML Page Field|Notes

|*Metadata URL*
|*URL* under *Metadata* 
|

|*Signing Certificate*
|*CA Certificates* under *Metadata*
|*CA Certificates* is hidden until you select *Verify remote peer*. You can download the certificate from Okta by clicking btn:[Download] and then upload it to Couchbase Server by clicking btn:[Select File].
|===
. Fill in the rest of the Couchbase Server SAML page as explained in <<configure-saml-with-the-ui>>.
. In Okta, click the *Assignments* tab.
. Assign users who need to log into the Couchbase Server Web Console to the Okta application you just created. See the Okta documentation for the steps you need to take.

== Configure SAML with the REST API

To configure a SAML IdP to authenticate users for the Web Console using the REST API, use the `/settings/saml` endpoint. The following example demonstrates calling this endpoint using Curl. 



