= Configure LDAP

[abstract]
Couchbase Server can be configured to authenticate the user by means of an LDAP server; and to recognize the LDAP _groups_ of which the user is a member.

[#understanding-ldap-authentication]
== Understanding LDAP Authentication.

For authentication purposes, Couchbase Server can be configured to exchange information with an LDAP server.
This allows the user, when they attempt to access Couchbase Server by presenting their credentials, to be authenticated on the LDAP server.
It also allows _LDAP group_ information for the authenticated user to be retrieved from the LDAP server, and duly mapped to groups and group-based roles defined on Couchbase Server.

This page provides examples of how to configure Couchbase Server to work with an LDAP server.
For an overview of Couchbase authentication, see xref:learn:security/authentication-overview.adoc[Authentication].

[#examples-on-this-page-node-addition]
== Examples on This Page

The examples in the subsections below show how to configure LDAP; using the xref:manage:manage-security/configure-ldap.adoc#configure-ldap-with-the-ui[UI], the xref:manage:manage-security/configure-ldap.adoc#configure-ldap-with-the-cli[CLI], and the xref:manage:manage-security/configure-ldap.adoc#configure-ldap-with-the-rest-api[REST API] respectively.
The examples assume:

* A one-node cluster already exists; and is named after its IP address: `10.142.192.101`.
It is running the Data and Query services, and has the `travel-sample` bucket installed.
(To access and install this, see xref:manage:manage-settings/install-sample-buckets.adoc[Sample Buckets].)

* The cluster has the Full Administrator username of `Administrator`, and password of `password`.

* A fully configured LDAP server is available at `172.23.124.25`, port `389`.

Each example also shows how to _associate_ Couchbase Server groups with LDAP groups: once LDAP communication has been configured to retrieve users' LDAP groups, these can be _associated_ with existing Couchbase-Server groups.
Consequently, the user who has membership to one or more LDAP-defined groups, and who is successfully authenticated for access to Couchbase Server via LDAP, inherits the Couchbase-Server roles provided by the associated Couchbase-Server groups.

[#configure-ldap-with-the-ui]
== Configure LDAP with the UI

TBA

[#configure-ldap-with-the-cli]
== Configure LDAP with the CLI

To configure an LDAP server to be used as a point of authentication for Couchbase Server, use the xref:cli:cbcli/couchbase-cli-setting-ldap.adoc[setting-ldap] command.

----
/opt/couchbase/bin/couchbase-cli setting-ldap \
--cluster http://10.143.192.101 --username Administrator \
--password password --authentication-enabled 1 \
--authorization-enabled 1 --hosts 172.23.124.25 --port 389 \
--disable-cert-validation --encryption none \
--query-dn domain=LOCAL --query-pass querypassword \
--group-query %D?memberOf?base
----

This call references the LDAP server at `172.23.125.25`, on port `389`, and specifies `--authorization-enabled` and `--authentication-enabled` for the user-credentials that will be passed from Couchbase Server.
The `--group-query` retrieves the LDAP groups of which the user is a member.

If successful, the call produces the following output:

----
SUCCESS: LDAP settings modified
----

For more information, see the command reference for xref:cli:cbcli/couchbase-cli-setting-ldap.adoc[setting-ldap].

[#reference-ldap-groups-with-cli]
=== Reference LDAP Groups with the CLI

Both Couchbase Server and LDAP support _groups_.
Each group's privileges are shared by the group's members.
If LDAP communication has been configured to retrieve users' LDAP groups, these can be associated with existing Couchbase-Server groups and group-associated roles.
This is handled by means of the xref:cli:cbcli/user-manage.adoc[user-manage] command.
For example:

----
/opt/couchbase/bin/couchbase-cli user-manage -c 10.143.192.101 \
--username Administrator --password password \
--set-group --group-name admins --roles admin \
--group-description "Couchbase Server Administrators" \
--ldap-ref domain=admins
----

This establishes a Couchbase Server group named `admins`, each of whose members is granted the `admin` (the `Full Administrator`) role.
It additionally references the LDAP group `admins`: from this point, LDAP-authenticated Couchbase Server users who are in the LDAP 'admins' group are placed in the Couchbase Server 'admins' group, and thereby are granted the 'admin' role.

[#configure-ldap-with-the-rest-api]
== Configure LDAP with the REST API

To configure an LDAP server to be used as a source of authentication for Couchbase Server, use the `pools` endpoint, as follows:

----
curl -v -X GET -u Administrator:password \
http://10.143.192.101:8091/pools \
-d authentication_enabled=true \
-d authorization_enabled=true \
-d hosts=172.23.124.25 \
-d port=389 \
-d encryption=TLS \
-d max_parallel_connections=100 \
-d server_cert_validation=false \
-d max_cache_size=10000 \
-d request_timeout=5000 \
-d nested_groups_enabled=false \
-d nested_groups_max_depth=10 \
-d cache_value_lifetime=300000 \
-d groups_query %D?memberOf?base \
-d query_dn='domain=LOCAL' \
-d query_pass=querypassword
----

This call references the LDAP server at `172.23.125.25`, on port `389`, enabling authorization and authentication for user-credentials to be passed from Couchbase Server.

For more information, see xref:rest-api:rest-configure-ldap.adoc[Configure LDAP].

[#reference-ldap-groups-with-the-rest-api]
=== Reference LDAP Groups with the REST API

----
curl -v -X PUT -u Administrator:password \
http://10.143.192.101:8091/settings/rbac/groups/admins \
-d roles=admin \
-d description=Couchbase+Server+Administrators \
-d ldap_group_ref=domain%3Dadmins
----

This establishes a Couchbase Server group named `admins`, each of whose members is granted the `admin` (the `Full Administrator`) role.
It additionally references the LDAP group `admins`: from this point, LDAP-authenticated Couchbase Server users who are in the LDAP 'admins' group are placed in the Couchbase Server 'admins' group, and thereby are granted the 'admin' role.

For more information, see xref:rest-api:rbac.adoc[Role Based Admin Access (RBAC)].
