= Configure Client Certificates

[abstract]
Couchbase Server supports client-authentication by means of X.509
certificates.

[#couchbase-client-authentication]
== Couchbase Client Authentication

Couchbase clients can authenticate by means of X.509 certificates. This
page explains how client certificates can be prepared for a Java client. It
also provides information on TLS levels, and on supported ciphers.

For a list of Couchbase-Server ports that provide secure connectivity to
clients, see
xref:learn:clusters-and-availability/connectivity.adoc[Connectivity].

[#cert_auth_for_java_client]
== Configure Certificates for a Java Client

Once the root certificate for a Couchbase Server-node has been deployed, a
Java client can authenticate by means of an appropriately prepared keystore,
and so gain access to the Data, Query, and Search Services.

Proceed as follows.
Note that these instructions use the Ubuntu 16 environment previously configured
in
xref:manage:manage-security/configure-server-certificates.adoc[Configure
Server Certificates].

. Define environment variables for the name of the keystore to be created, and its password.
+
[source,bash]
----
export KEYSTORE_FILE=my.keystore
export STOREPASS=storepass
----

. If necessary, install a package containing the `keytool` utility:
+
[source,bash]
----
sudo apt install openjdk-9-jre-headless
----

. Within the top-level, `SSLCA` directory that you created, generate the keystore.
Note that the password you specify for the alias, by means of the `--keypass` flag, must be identical to the password you specify for the keystore, by means of the `--storepass` flag.
In this case, both passwords are specified as `&#36;&#123;STOREPASS&#125;`; which resolves to `storepass`.
+
[source,bash]
----
keytool -genkey -keyalg RSA -alias selfsigned \
-keystore ${KEYSTORE_FILE} -storepass ${STOREPASS} -validity 360 -keysize 2048 \
-noprompt  -dname "CN=${USERNAME}, OU=None, O=None, L=None, S=None, C=US" -keypass ${STOREPASS}
----

. Generate the certificate signing-request:
+
[source,bash]
----
keytool -certreq -alias selfsigned -keyalg RSA -file my.csr \
-keystore ${KEYSTORE_FILE} -storepass ${STOREPASS} -noprompt
----

. Generate the client certificate, signing it with the intermediate private key:
+
[source,bash]
----
openssl x509 -req -in my.csr -CA ./${INT_DIR}/${INTERMEDIATE}.pem \
-CAkey ./${INT_DIR}/${INTERMEDIATE}.key -CAcreateserial -out clientcert.pem -days 365
----

. Add the root certificate to the keystore:
+
[source,bash]
----
keytool -import -trustcacerts -file ./${ROOT_DIR}/${ROOT_CA}.pem \
-alias root -keystore ${KEYSTORE_FILE} -storepass ${STOREPASS} -noprompt
----

. Add the intermediate certificate to the keystore:
+
[source,bash]
----
keytool -import -trustcacerts -file ./${INT_DIR}/${INTERMEDIATE}.pem \
-alias int -keystore ${KEYSTORE_FILE} -storepass ${STOREPASS} -noprompt
----

. Add the client certificate to the keystore:
+
[source,bash]
----
keytool -import -keystore ${KEYSTORE_FILE} -file clientcert.pem \
-alias selfsigned -storepass ${STOREPASS} -noprompt
----

This concludes preparation of the Java client's keystore.
Copy the file (in this case, `my.keystore`) to a location on a local filesystem
from which the Java client can access it.

[#working-with-supported-protocols]
== Setting the TLS Minimum Version

Couchbase Server client-libraries support client-side encryption, using the Transport Layer Security (TLS).
TLS versions 1.0, 1.1, and 1.2 are supported: the highest-supported version of TLS is recommended.

The minimum TLS version to be used can be set with either the CLI or the REST API.

[#setting-tls-version-with-the-cli]
=== Setting the minimum TLS Version with the CLI

To set the minimum TLS version with the CLI, use the xref:cli:cbcli/couchbase-cli-setting-security.adoc[setting-security] command as follows:

----
/opt/couchbase/bin/couchbase-cli setting-security \
-c 10.143.192.101:8091 \
-u Administrator \
-p password \
--set \
--tls-min-version tlsv1.1
----

The `set` flag indicates that a value is to be set.
The `tls-min-version` flag specifies the appropriate minimum TLS value, which can be `tlsv1.1` or `tlsv1.2`.

If successful, the command returns the following success-message:

----
SUCCESS: Security settings updated
----

For more information, see xref:cli:cbcli/couchbase-cli-setting-security.adoc[setting-security]

[#setting-tls-version-with-the-rest-api]
=== Setting the Minimum TLS Version with the REST API

To set the minimum TLS version with the REST API use the `POST /settings/security` http method and URI, as follows:

----
curl  -u Administrator:password -v -X POST \
http://10.143.192.101:8091/settings/security \
-d 'tlsMinVersion=tlsv1.2'
----

The `tlsMinVersion` flag specifies the minimum TLS version to be used; which can be `tlsv1`, `tlsv1.1`, or `tlsv1.2`.
If successful, the command gives a `200 OK` message, and returns and empty array.

For more information, see xref:rest-api:rest-setting-security.adoc[Manage Encryption Settings].

[#enabling-client-security]
== Securing Client Access with TLS

For an application to communicate securely with Couchbase Server, SSL/TLS must
be enabled on the client side.
Enablement requires a copy of the certificate used by Couchbase Server: this can be accessed from the Couchbase Web Console, as described in
xref:manage:manage-security/manage-security-settings.adoc#root-certificate-security-screen-display[Root
Certificate].

Note that if, at some point, this certificate gets regenerated on the server-side, a copy of the new version must be obtained, and the client re-enabled.

[#overriding-supported-ciphers]
== Managing Cipher-Suite Preferences

To support TLS, Couchbase Server uses by default a list of high-security OpenSSL ciphers, available from the underlying operating system.
This cipher-suite in this default list can be over-ridden with a custom-specified subset.
Within a cipher-suite list, cipher-suites are specified in order of preference; with the most preferred at the top, and the least preferred at the bottom.

When a TLS connection is established between a client application and Couchbase Server, using the secure port 18091, a _handshake_ occurs, as defined by the _TLS Handshake Protocol_.
As part of this exchange, the client sends to the server the client's own _cipher-suite list_; which specifies the cipher-suites that the client itself supports, in the client's own order of preference.

Since server and client each have a list, and since each list may include a subset of the same cipher-suites, but in a different order of preference, Couchbase Server provides a setting that allows predetermination of whether the server's or the client's preferential order is the one now used by Couchbase Server in making the selection.

Once the selection has been made by Couchbase Server, Couchbase Server notifies the client, and secure communication can begin.

Cipher-suites can be managed with either the CLI or the REST API, as described below.

[#manage-ciphers-with-the-cli]
=== Manage Cipher-Suites with the CLI

To manage cipher-suites with the CLI, use the xref:cli:cbcli/couchbase-cli-setting-security.adoc[setting-security] command as follows:



, by setting the `COUCHBASE_SSL_CIPHER_LIST` environment variable: this must be performed _before_ starting Couchbase Server.
The environment variable can be set in either of the following ways:

* Specify an explicit list of ciphers to be used.
For example:
+
----
COUCHBASE_SSL_CIPHER_LIST="DHE-DSS-AES128-SHA,CAMELLIA128-SHA"
----

* Specify ciphers by security-level.
For example, to specify that all ciphers in both _medium_ and _high_ categories
be used, enter the following:
+
----
COUCHBASE_SSL_CIPHER_LIST="MEDIUM,HIGH"
----

To display the ciphers available on your Linux platform for a particular security level, use the `openssl` command.
For example, to display the _high_-level ciphers, enter the following:

----
openssl ciphers -v 'HIGH'
----

To check the current value of the `COUCHBASE_SSL_CIPHER_LIST` environment variable, type `printenv` at the Linux prompt: this returns a list of all currently set environment variables.
