= Manage Authentication

[abstract]
To access Couchbase Server, administrators and applications must be authenticated.
_Authentication_ is a process for identifying a user who is attempting to access a system.

== Passing Credentials

Couchbase-Server authentication relies on _credentials_, which must be passed
into the system by the user who is attempting access.
Credentials can be entered manually, or passed into the system by an
application.
The credentials passed must match ones already stored and accessible by the
system: if a match is achieved, the user is thereby recognized, and so _may_ be
granted access.
If no match is achieved, the user is denied access.

To access Couchbase Server, administrators authenticate by means of a username
and password.
These credentials can be validated by Couchbase Server itself: alternatively if
the Enterprise Edition of Couchbase Server for Linux is used, validation can
be performed either on a network-accessible directory-server, by means of
the _Lightweight Directory Access Protocol_ (LDAP); or by means of the
_Pluggable Authentication Modules_ (PAM) authentication-framework.
