= Manage Native Encryption at Rest
:description: pass:q[Couchbase Server's native encryption at rest protects sensitive data by encrypting it when writing it to disk.]
:tabs:
:page-toclevels: 2
[.edition]#{enterprise}#

[abstract]
{description}
This feature is transparent to the database's users. 
Couchbase Server automatically decrypts data when read from disk and encrypts it when writing it to disk.
For an overview of native encryption at rest, see xref:learn:security/native-encryption-at-rest-overview.adoc[].



You can only use encryption at rest on 

Enabling encryption at rest is a two step process:

. Create at least one encryption key.
Couchbase Server uses these keys to encrypt its own encryption keys for data. 
. Enable encryption for one or more types of data. 
You can encrypt:
+
* All data in a bucket
* Logs
* Configuration data
* Audit data

The following sections explain these steps in greater detail.

## Creating Encryption Keys

Before encrypting data at rest, you must create at least one encryption key.
You can limit what type of data each key can encrypt or limit them to . 

### Requirements

For each key you create, you must choose a Key Management Service (KMS) that maintains the key for you.
You have three options to choose from:

* Amazon's AWS KMS 
* Any KMS that implements the Key Management Interoperability Protocol (KMIP) 
* Couchbase Server

See xref:learn:security/native-encryption-at-rest-overview.adoc#kms[Encryption Key Management Services] for more information.

You must decide what your encryption can encrypt. 
You can create an encryption key that can encrypt any data and sign other keys.
You can also choose to limit what data the key can be use to encrypt, or configure it to only encrypt other encryption keys. 
See learn:security/native-encryption-at-rest-overview.adoc#keys[Encryption at Rest Keys] for more information.

You must have the proper privileges to create encryption keys.
Only users with the xref:learn:security/roles.adoc#full-admin[Full Admin] or xref:learn:security/roles.adoc#security-admin[Security Admin] roles can create encryption keys. 

### Create an Encryption Key Using the Couchbase Server Web Console

To create an encryption key using the Couchbase Server Web Console:

. Select menu:Security[] on the main menu.
. Click the menu:Encryption at Rest[] tab.
. Click the btn[Add Encryption Key] button.
. In the *Add Encryption Key* dialog, enter a name for your key in the *Name* box.
. If you want to limit what your key can encrypt, click *Configure* to expand the list of uses. 
Then choose what you want to your key to be able to encrypt.

+
If you want to limit which buckets your key can be used to encrypt, deselect *Data* and then select the buckets.

. Under *Key Type*, choose the KMS you want to manage your key.
The option you choose changes the fields in the rest of the dialog.

. Depending on the KMS you chose, enter the details to complete creating the encryption key:
+
[{tabs}]
====
AWS::
+
--
[start=8]
. Enter the Amazon Resource Name (ARN) for the encryption key and the AWS Region in which the KMS is located.
. Choose whether to enable the AWS Instance Metadata Service.
Enable this option if your Couchbase Server cluster runs on AWS EC2 instances and uses IAM roles to access other AWS services. 
. Enter the paths on your cluster where you have stored the AWS crendital, config, and profile files.
. Verify that your settings work by clicking the btn:[Test Encryption Key Settings] button.

--

KMIP::
+
--
To use a KMIP-compatible KMS:

[start=8]
. Enter the host and port number for the KMS server, and choose a timeout for network connections.
. Choose which certificates to use when verifying the identity of the KMS, or choose to not verify.
. Enter the details for the client certificate Couchbase Server uses to authenticate with the KMS including how to encrypt the certificate passphrase.
. Choose whether you want Couchbase Server to fetch the key from the KMS and encrypt data itself, or if you want the KMS to encrypt the data for you. 
--

Auto-Generated::
+
--
This option has Couchbase Server manage the key.
To complete creating the key:

[start=8]
. Choose whether you want to use the cluster's master password or another encryption key to encrypt your new key.
If you want to use another encryption key, you must an existing one that allows itself to be used as a Key Encryption Key (KEK).
. Decide whether you want Couchbase Server to cache the key.
This setting lets Couchbase Server keep the key unencrypted in memory so it does not have to decrypt it for each read or write.
. Decide whether you want to have the keys auto rotate. 
If you choose to rotate them, enter how often, and select a date and time for the first rotation.
See xref:learn:secrutiy/native-encryption-at-rest-overview.adoc#rotation-expiration[Encryption Key Rotation and Expiration] for more information about key rotation.
--

====

### Create an Encryption Key Using the REST API

The REST API's `/settings/encryptionKey` endpoint lets you create and manage encryption keys.  

Users with xref:learn:security/roles.adoc#bucket-admin[Bucket Admin] or Cluster Admin roles can enable encryption for rest for buckets as long as an encryption key exists that is allowed to create the bucket. 



// Notes:
// bucket-admin, no access to security in Web Console. Can apply encryption at rest to bucket if a suitable key exists.
// cluster-admin can enable encryption at rest for a bucket. Cannot access Secrutiy settings.