[#rotate-keys]
= Manually Rotate Encryption-at-rest Keys
:description: pass:q[You can have Couchbase Server automatically rotate the encryption-at-rest keys it manages based on a schedule you set when creating the key.]
:tabs:
:page-topic-type: guide
:page-toclevels: 3
:keywords: encryption at rest, security
:page-edition: Enterprise Edition
:page-topic-type: reference

You can also manually have Couchbase Server rotate a key that it manages.
To rotate an encryption-at-rest key managed by an external Key Management System (KMS), you must use the KMS tools to rotate the key.
Then have Couchbase Server re-encrypt Data Encryption Keys (DEKs) with the new key.

When you rotate an encryption-at-rest key, Couchbase Server:
* Creates a new version of the key (or retrieves a new key from the external KMS).
* Uses the new key version to encrypt any new data.
* Marks the old key version as inactive.
The old key version remains available to decrypt data that was encrypted with it until the data is re-encrypted with the new key.

NOTE: Rotating an encryption-at-rest key does not re-encrypt all data at the time of rotation.
Couchbase Server re-encrypts data as it writes it.
To force re-encryption of all data, see xref:manage:manage-security/manually-drop-DEKs-reencrypt-data.adoc#drop-deks[Manually Drop DEKs and Re-encrypt Data].

Required Privileges::
* Full Admin or Security Admin for keys that encrypt audit, configuration, or log data, or that encrypt other encryption-at-rest keys (KEKs).
* Full Admin or Cluster Admin for keys that encrypt any bucket in the cluster.
* Bucket Admin (with privileges on the relevant bucket) for keys that encrypt specific buckets.

== Manually Rotate a Couchbase Server-Managed Encryption-At-Rest Key

You can manually rotate encryption-at-rest keys that Couchbase Server manages if a key has been compromised.
You can also rotate keys if your security requirements have changed.

When you rotate an encryption-at-rest key, Couchbase Server creates a new key and uses it to re-encrypt all DEKs that were encrypted with the previous version of the key.
This process does not re-encrypt data, as the DEKs do not change.

To manually rotate a Couchbase-Managed encryption-at-rest key using the Couchbase Server Web Console:

. Click menu:Security[] on the main menu.
. Click the menu:Encryption at Rest[] tab.
. Click the encryption key you want to rotate.
. Click the btn:[Rotate] button next to the key you want to rotate.

To manually rotate an encryption-at-rest key, send a POST request to the `/controller/rotateEncryptionKey/{KEY_ID}` endpoint, where `{KEY_ID}` is the ID of the key you want to rotate.
See xref:rest-api:security/encryption-at-rest/rotate-encryption-at-rest-key.adoc[] for more information about manually rotating encryption-at-rest keys using the REST API.

== Manually Rotate an Encryption-at-rest Key Managed by AWS KMS

To rotate an encryption-at-rest key managed by AWS KMS, you must use AWS's tools to rotate the key.
See https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html[Rotate AWS KMS keys^] to learn how to rotate keys in AWS KMS.
Once you have rotated the key in AWS KMS, have Couchbase Server re-encrypt any DEKs encrypted with the previous version of the key.

To re-encrypt the DEKs with the rotated key using the Couchbase Server Web Console:

. Click menu:Security[] on the main menu.
. Click the menu:Encryption at Rest[] tab.
. Click the encryption key that you rotated in AWS KMS.
. Click btn:[Rotate] next to the key you want to rotate.

To re-encrypt the DEKs using the REST API, send a POST request to the `/controller/rotateEncryptionKey/{KEY_ID}` endpoint, where `{KEY_ID}` is the ID of the key that you rotated in AWS KMS.
See xref:rest-api:security/encryption-at-rest/rotate-encryption-at-rest-key.adoc[] for more information about manually rotating encryption-at-rest keys using the REST API.

== Manually Rotate an Encryption-at-rest Key Managed by GCP Cloud KMS

For GCP Cloud KMS-managed keys, rotation creates a new key version in GCP Cloud KMS. Couchbase Server retrieves the new key version and uses it for subsequent encryption operations.
Previous key versions remain available in GCP Cloud KMS to decrypt data encrypted with them.

Using the Web Console

. Click menu:Security[] on the main menu.
. Click the menu:Encryption at Rest[] tab.
. Click the encryption key that you rotated in GCP Cloud KMS
. Click btn:[Rotate] next to the key you want to rotate.
Couchbase Server contacts GCP Cloud KMS to create a new key version.

To rotate the key using the REST API, see xref:rest-api:security/encryption-at-rest/rotate-encryption-at-rest-key.adoc[].

== Manually Rotate an Azure Key Vault Key
For Azure Key Vault-managed keys, rotation creates a new key version in Azure Key Vault.
Couchbase Server retrieves the new key version and uses it for subsequent encryption operations.
Previous key versions remain available in Azure Key Vault to decrypt data encrypted with them.

Using the Web Console

. Click menu:Security[] on the main menu.
. Click the menu:Encryption at Rest[] tab.
. Find the Azure Key Vault key you want to rotate in the encryption keys list.
. Click btn:[Rotate] next to the key.
Couchbase Server contacts Azure Key Vault to create a new key version.

To rotate the key using the REST API, see xref:rest-api:security/encryption-at-rest/rotate-encryption-at-rest-key.adoc[].

== Manually Rotate a HashiCorp Vault Key
For HashiCorp Vault-managed keys, rotation creates a new key version in the Vault Transit secrets engine.
Couchbase Server retrieves the new key version and uses it for subsequent encryption operations.
Previous key versions remain available in the Transit engine to decrypt data encrypted with them, subject to the key's min_decryption_version setting.

Using the Web Console:

. Click menu:Security[] on the main menu.
. Click the menu:Encryption at Rest[] tab.
. Find the HashiCorp Vault key you want to rotate in the encryption keys list.
. Click btn:[Rotate] next to the key.
Couchbase Server contacts HashiCorp Vault to rotate the Transit key.

To rotate the key using the REST API, see xref:rest-api:security/encryption-at-rest/rotate-encryption-at-rest-key.adoc[].

== Manually Rotate an Encryption-at-rest Key Managed by a KMIP KMS

You must use the KMS's tools to rotate the keys it manages.
Couchbase Server cannot trigger the rotation of a key managed by an external KMS.
Consult your KMS's documentation to learn how to rotate its keys.

[NOTE]
====
When configuring external KMS integration, make sure that all required key and certificate files are present
at the exact file paths specified during key creation.
These files must exist on every node in the cluster, including any nodes added during a rebalance operation.

Couchbase Server does not create these files automatically.
If any of these files are missing or located at a different path, encryption initialization or rebalance operations can fail.
For example, the Client Private Key Path (PEM format) must exist at the same specified location on all nodes before you create or edit a KMIP key.
====

Some KMIP KMSs require you to create a new key with a new ID when rotating a key. 
In this case, when you rotate a key in the KMS, you must update the key ID in Couchbase Server.

To update the key ID in Couchbase Server using the Couchbase Server Web Console:

. Click menu:Security[].
. Click menu:Encryption at Rest[].
. Click the KMIP KMS encryption key that you rotated.
. Click the btn:[Edit].
. In the *Edit Encryption Key* dialog, change the *KMIP Key ID* to the new key ID and click btn:[Save Encryption Key].

To update the key ID in Couchbase Server using the REST API, use the `/settings/encryptionKeys/{KEY_ID}` endpoint to modify the key. 
The `KEY_ID` path parameter is the Couchbase Server ID of the key you want to update. 
Update the `activeKey.kmipId` attribute in the `data` object to the new key ID.

The following example updates the KMIP key ID of the encryption-at-rest key with the Couchbase Server `id` of `3` to the a KMIP key ID:

[source,console]
----
curl -sS -u Administrator:password  \
     -X PUT   http://127.0.0.1:8091/settings/encryptionKeys/3   \
       --data-binary @- <<EOF | jq
{
  "name": "Example KMIP Key",
  "type": "kmip-aes-key-256",
  "usage": [
    "KEK-encryption"
  ],
"data": {
      "port": 5696,
      "host": "kms.example.com",
      "certPath": "/scripts/certs/cb_cert.pem",
      "keyPath": "/scripts/certs/cb_key.pem",
      "activeKey": {
        "kmipId": "5b7e1ee1-33e5-4468-b168-50f391e8baa4"
    }
  }
}
EOF
----

The result of running this command looks like this:

[source,json]
----
{
  "data": {
    "port": 5696,
    "host": "kms.example.com",
    "reqTimeoutMs": 30000,
    "keyPath": "/scripts/certs/cb_key.pem",
    "keyPassphrase": "******",
    "encryptionApproach": "useGet",
    "certPath": "/scripts/certs/cb_cert.pem",
    "caSelection": "useCbCa",
    "encryptWith": "nodeSecretManager",
    "historicalKeys": [
      {
        "id": "afba44fb-4ae5-4d40-b1e1-3a661b0948e1",
        "kmipId": "0788edb1-1418-4225-903b-bc1f9f59aa4d",
        "creationDateTime": "2025-08-07T18:46:15Z"
      }
    ],
    "activeKey": {
      "id": "78130a6c-2a5f-4941-92ee-52223f473e01",
      "kmipId": "5b7e1ee1-33e5-4468-b168-50f391e8baa4",
      "creationDateTime": "2025-08-07T18:49:38Z"
    }
  },
  "id": 3,
  "name": "Example KMIP Key",
  "type": "kmip-aes-key-256",
  "usage": [
    "KEK-encryption"
  ],
  "creationDateTime": "2025-08-07T18:46:15Z"
}
----

See xref:rest-api:security/encryption-at-rest/manage-encryption-keys.adoc#create-key[Create or Update an Encryption-at-Rest Key] for more information about updating encryption-at-rest keys using the REST API.

IMPORTANT: When you change the KMIP key ID, Couchbase Server starts re-encryption the DEKs that used the old key with the new key.
However, this process may take some time.
Be sure that the KMS does not delete the old key until Couchbase Server has finished re-encrypting the DEKs with the new key.

== Rotation Intervals
You can configure automatic key rotation by setting a rotation interval when you create or edit an encryption key.
The rotation interval determines how often Couchbase Server automatically rotates the key.

[cols="2,3,3"]
|===
| Setting | Description | Default

| DEK Rotation Interval
| How often Couchbase Server generates a new data encryption key (DEK).
When the interval elapses, Couchbase Server creates a new DEK and uses it for new writes.
| 30 days

| DEK Life Time
| How long a DEK remains available to decrypt data after it has been rotated.
After the lifetime expires, Couchbase Server drops the DEK from memory.
Any data still encrypted with the expired DEK must be re-encrypted before it can be read.
|365 days

| KEK Rotation Interval
| How often Couchbase Server rotates the key encryption key (KEK).
When the interval elapses, Couchbase Server creates a new version of the KEK and re-wraps the DEKs with the new version.
|365 days

NOTE: Setting a short DEK rotation interval increases security but may increase the number of DEKs that Couchbase Server must manage.
Setting a short DEK lifetime forces re-encryption sooner but may cause temporary performance impact as data is re-encrypted.

You can configure these settings when creating or editing an encryption key via the Web Console or the REST API.
For auto-generated keys, set the rotationIntervalInDays and nextRotationTime fields in the data object.



