= Manually Dropping DEKs, Re-encrypting Data, and Deleting Encryption Keys
:description: pass:q[You can have Couchbase Server drop the data encryption keys (DEKs) for a bucket or data type, which forces the system to generate a new replacement DEK and re-encrypt all associated data.]
:tabs:
:page-topic-type: guide
:page-toclevels: 3
:keywords: encryption at rest, security
:page-edition: Enterprise Edition
:page-topic-type: reference

You may choose to perform this operation if you suspect that your DEKs have been compromised.
Once the re-encryption process is complete, the old DEKs are permanently removed.

[#drop-deks]
== Manually Drop DEKs and Re-encrypt Data

You can have Couchbase Server drop the data encryption keys (DEKs) for a bucket or type of data and re-encrypt the data with new DEKs.
When you drop the DEKs for a bucket or type of data, Couchbase Server creates a new replacement DEK and uses it to re-encrypt all of the data in the bucket or of that type.
Then it removes the old DEKs.

NOTE: Dropping DEKs is not the same as DEK rotation.
DEK rotation consists of two parallel processes.
First, new DEKs are generated periodically and used for newly written data.
This process alone does not trigger re-encryption. 
Second, expired DEKs are automatically removed once they reach their configured lifetime.
If data encrypted with an expired DEK still exists, it is re-encrypted before the key is removed.
However, re-encryption only occurs if the data was not already re-encrypted naturally through compaction or other write activity.

=== Drop DEKs for a Bucket

To drop DEKs for a bucket using the Couchbase Server Web Console:

. Click menu:Buckets[] on the main menu.
. Click the name of the bucket whose DEKs you want to rotate.
. Click btn:[Re-encrypt].
. In the *Confirm Rotate DEKs & Re-encrypt Data* dialog, click btn:[Rotate DEKs & Re-encrypt] to confirm you want to rotate the DEKs and re-encrypt the data.

IMPORTANT: This process re-encrypts all data in the bucket.
Depending on the amount of data the bucket stores, this process can take a long time and could affect the performance of the cluster.

To learn how to drop DEKs for a bucket using the REST API, see xref:rest-api:security/encryption-at-rest/drop-encryption-deks.adoc#drop-bucket[Drop DEKs and Re-encrypt Data for a Bucket].

=== Drop DEKs for Audit, Configuration, or Log Data

To drop DEKs for audit, configuration, or log data using the Couchbase Server Web Console:

. Click menu:Security[] on the main menu.
. Click the menu:Encryption at Rest[] tab.
. Click btn:[rotate DEKs and re-encrypt now] under *Configuration Encryption*, *Logs Encryption*, or *Audit Encryption* depending on the type of data whose DEKs you want to drop.

To learn how to drop DEKs for  audit, configuration, or log data using the REST API, see xref:rest-api:security/encryption-at-rest/drop-encryption-deks.adoc#drop-type[Drop DEKs and Re-encrypt Data for a Bucket].

== Deleting Encryption Keys

You can delete an encryption key using the Couchbase Server Web Console or the REST API.
You cannot delete an encryption key that is actively encrypting data.
You must first disable encryption for all data that uses the key, or reassign the data to a different encryption key.

Important: Deleting an encryption key is irreversible. 
Once deleted, any data that was encrypted with the key and has not been re-encrypted with a different key becomes permanently inaccessible.

=== Delete an Encryption-At-Rest Key Using the Couchbase Server Web Console

To delete an encryption key using the Couchbase Server Web Console:

. Click menu:Security[] on the main menu.
. Click the menu:Encryption at Rest[] tab.
. Click the encryption key you want to delete.
. Click the btn:[Delete] button next to the key you want to delete.
. In the *Confirm Delete* dialog, click btn:[Delete Encryption Key] to confirm you want to delete the key.

=== Delete an Encryption-At-Rest Key Using the REST API

To delete an encryption key using the REST API, send a DELETE request to the `/settings/encryptionKey/{KEY_ID}` endpoint.

The following example shows how to delete the encryption key with the `id` `13` using the REST API:

include::rest-api:example$encryption-at-rest/manage-key-examples.adoc[tag=delete-key]
