= Security Management Overview
:description: Couchbase Server can be rendered highly secure.
:page-aliases: security:security-in-applications,security:security-user-input

[abstract]
{description}

[#couchbase-server-security]
== Couchbase Server Security

Couchbase Server can be rendered highly secure.
System-areas available to be managed include:

* _Networked access, by administrators, users, and applications_: Can be secured with TLS, using dedicated Couchbase Server-ports. Cipher-suites, TLS levels, and console-access can be individually managed.
Networked communications between nodes within the cluster can also be secured: see xref:manage:manage-nodes/apply-node-to-node-encryption.adoc[Manage Node-to-Node Encryption], for details.

* _Authentication_: Can be handled by passing credentials explicitly, or by means of client certificates.
_External_ (as well as _Local_) authentication-domains are supported: therefore, authentication-mechanisms based on _Native LDAP_, _saslauthd_, and _PAM_ can be used.
For the recommended process, see xref:manage:manage-security/configure-ldap.adoc[Configure LDAP].

* _Authorization_: Couchbase _Role-Based Access Control_ ensures that each authenticated user is checked for the system-defined _roles_ (and,
by due association, _privileges_) they have been assigned.
This allows access to be granted or denied them, based on the type of system-resource they are trying to access, and the operation they wish to perform.
Roles can be assigned by _user_ and by _group_.
For details, see xref:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups, and Roles].

* _Auditing_: Can be enabled on actions performed on Couchbase Server, so that reviews can occur.
See xref:manage:manage-security/manage-auditing.adoc[Manage Auditing],

* _Certificates_: These can be defined and established for the cluster.
Additionally, certificates presented by clients attempting server-access can be permitted.
See xref:manage:manage-security/manage-certificates.adoc[Manage Certificates].

* _Logs_: These can be _redacted_, ensuring that no private information is shared.
Information is provided in xref:manage:manage-logging/manage-logging.adoc[Manage Logging].

* _Sessions_: Can be configured for termination following periods of user-inactivity.
This is described in xref:manage:manage-security/manage-sessions.adoc[Manage Sessions].

See the navigation panel at the left, for details of additional management procedures documented in this section.
