= Security Management Overview
:page-aliases: security:security-in-applications,security:security-user-input

[abstract]
Couchbase Server can be rendered highly secure.

[#couchbase-server-security]
== Couchbase Server Security

Couchbase Server can be rendered highly secure. System-areas available to be
managed include:

* _Networked access, by administrators, users, and applications_: Can be
secured with TLS, using dedicated Couchbase Server-ports. Ciphers, TLS
levels, and console-access can be individually managed.

* _Authentication_: Can be handled by passing credentials explicitly, or
by means of client certificates. _External_ (as well as _Local_)
authentication-domains
are supported: therefore, _LDAP_ and _PAM_ authentication-mechanisms can
be used.

* _Authorization_: Couchbase _Role-Based Access Control_ ensures that
each authenticated user is checked for the system-defined _roles_ (and,
by due association, _privileges_) they have been assigned. This allows
access to be granted or denied them, based on the type of system-resource they
are trying to access, and the operation they wish to perform.

* _Auditing_: Can be enabled on actions performed on Couchbase Server, so that
reviews can occur.

* _Certificates_: These can be defined and established for the cluster.
Additionally, certificates presented by clients attempting server-access
can be permitted.

* _Logs_: These can be _redacted_, ensuring that no private information is
shared.

* _Sessions_: Can be configured to terminate, following periods of
user-inactivity.

See the subsections provided in this section, for details of the
required management procedures.
