= cbcat
:description: pass:q[The `cbcat` tool decrypts and displays the contents of encrypted logs and archive files.]
:totoro: the next major release of Couchbase Server
:page-status: {totoro}
:page-topic-type: reference

[abstract]
{description}

== Syntax

The basic syntax is:

----
cbcat [options] file(s)
----

where `file(s)` is a list of files to decrypt and view.

== Description

This tool is available in {totoro} and later.

When encryption at rest is active, Couchbase Server encrypts sensitive data stored on disk.
This includes log files and archive files generated by Couchbase Server and by services that are running in the cluster.
The `cbcat` tool enables you to decrypt and view the contents of encrypted logs and archive files that were created when encryption at rest was active.

Depending upon your platform, this tool is at the following locations:

[cols="1,3"]
|===
| Operating system | Location

| Linux
| `/opt/couchbase/bin/`

| Windows
| `C:\Program Files\Couchbase\Server\bin\`

| Mac OS X
| `/Applications/CouchbaseServer.app/Contents/Resources/couchbase-core/bin/`
|===

== Options

--with-dump-keys <filename>::
The name and location of the `dump-keys` binary.
If not specified, the default is `/opt/couchbase/bin/dump-keys`.

--with-gosecrets <filename>::
The name and location of the `gosecrets.cfg` configuration file.
If not specified, the default is `/opt/couchbase/var/lib/couchbase/config/gosecrets.cfg`.

--password <password>::
The password to use for authentication or as decryption key.
Use `-` to read from standard input.

--with-keystore <json>::
The JSON containing the keystore to use.
Use `-` to read from standard input.

--print-header::
Prints a header with the file name before the content of the file.

--dump-encryption-header::
Prints information from the encryption header if the file is encrypted.

--version::
Displays the program version.

--help::
Displays help text.

== Environment Variables

CB_DUMP_KEYS_DEBUG::
Set this environment variable to enable debug output to see the command line used to run the `dump-keys` program.

== See Also

* xref:learn:security/native-encryption-at-rest-overview.adoc[]
* xref:manage:manage-security/manage-native-encryption-at-rest.adoc[]
* xref:rest-api:security/encryption-at-rest/encryption-at-rest.adoc[]
