= cbft-bleve for Scorch Indexes
:page-topic-type: reference

[abstract]
The `cbft-bleve` tool supports commands that return information on _Scorch_ index partitions.

== Using cbft-bleve on Scorch indexes.

The basic syntax is as follows:

----
cbft-bleve scorch [command] [index-store-path] [snapshot] [flags]
----

The available `commands` are listed in the sections below.
A `command` _must_ be specified.
Note that a command summary can be printed to standard output, by entering `cbft-bleve scorch --help`.

The `index-store-path`, which is mandatory, is the filesystem path of the `store` subdirectory, located under the directory for the _Scorch_ index partition.
See xref:cli:cbft-bleve-scorch.adoc##specifying-index-partitions[Specifying Index Partitions].

The `snapshot` is a reference to a particular _snapshot_, within a _Scorch_-index partition, on which information is to be retrieved.
See immediately below.

== Understanding Snapshots

Each _Scorch_ index contains 3 _snapshots_, each of which represents the state of all indexed data at a particular point in time.
This supports the possibility of _rollback_ of the index.
By default, three snapshots are maintained continually.
Each snapshot is referred to by a unique integer known as the _snapshot epoch_.
Some `commands` used by `cbft-bleve scorch` refer to a specific snapshot epoch.
Information on currently available snapshot epochs and their unique identifying integers is returned by means of the `snapshot` command.

== snapshot

The `snapshot` command prints a list of _snapshot epochs_ that currently exist for a specified Scorch index partition.
The syntax is as follows:

----
cbft-bleve scorch snapshot [index-store-path]
----

=== Example: Print Snapshot Epochs

The following example prints out the snapshot epochs for the specified index partition:

----
/opt/couchbase/bin/cbft-bleve scorch snapshot \
/Library/Application\ Support/Couchbase/var/lib/couchbase/data/@fts/\
demoIndex_1125629e41599ad8_92af29e5.pindex/store/
----

If successful, the command prints the following:

----
2020/01/20 22:08:11 cbauth: key: fts/remoteClients registered for tls config updates
snapshot epoch: 37
snapshot epoch: 36
snapshot epoch: 1
----

== ascii

The `ascii` command prints an ascii representation of the _segments_ in a snapshot.
The syntax is as follows:

----
cbft-bleve scorch ascii [index-store-path] [snapshot]
----

The `snapshot`, which is mandatory, must be the unique integer associated with a _snapshot epoch_ for the specified index, as returned by the `snapshot` command.

=== Example: Print an ASCII Representation

The following example prints an ascii representation of the segments in the snapshot specified for an index partition.

----
/opt/couchbase/bin/cbft-bleve scorch ascii \
/Library/Application\ Support/Couchbase/var/lib/couchbase/data/@fts\
demoIndex_1125629e41599ad8_92af29e5.pindex/store/\
37
----

If successful, the command returns the following:

----
2020/01/20 22:28:17 cbauth: key: fts/remoteClients registered for tls config updates
37    37:  5433 / 5433 -   .........................
----
