[#topic_iwl_zy4_1v]
= cbft-bleve-dump

The cbft-bleve-dump utility allows you to print all the rows in the specified index.
This is helpful for troubleshooting because the index or index fragments can be examined without access to the Couchbase Server.

NOTE: The parameter `-index` is required (not optional) and it specifies the path to the index to dump.
The remaining parameters describe special modes and are optional.

.cbft-bleve-dump parameters
[#table_sxy_ccp_1v,cols="25,76"]
|===
| Parameters | Description

| `-index`
| Required.
Specifies the path to the index to dump.

| `-dictionary`
| Optional.
Prints the term dictionary for the specified field.

| `-docID`
| Optional.
Print all the rows pertaining to the single specified document.

| `-fields`
| Optional.
Print the field names and field ids in the index.

| `-mapping`
| Optional.
Print a JSON serialization of the index mapping.
|===

If none of these alternate modes have been specified it will dump all rows in the index.

*Permission Required*

This command line tool only accesses data via the file system.
Ensure that you have the appropriate permissions from the host OS.

.Sample Usage
----
/opt/couchbase/bin/cbft-bleve-dump -mapping -index default_index_36f4f5d91743e793_1000041c.pindex/
    
{
"default_mapping":
Unknown macro: { "enabled"}
,
"type_field": "_type",
"default_type": "_default",
"default_analyzer": "standard",
"default_datetime_parser": "dateTimeOptional",
"default_field": "_all",
"byte_array_converter": "json",
"analysis": {}
}
----

.Sample: dictionary term
 $ cbft-bleve-dump -dictionary name -index default_index_44be2a419953e436_0a44bddb.pindex/ | awk '{print $3 ", " $1}' | sort -n -r | head -10

This example prints the top ten terms listing along with the number of occurrences.
