= cbft-bleve for Moss Indexes
:page-topic-type: reference

[abstract]
The `cbft-bleve` tool supports commands that return information on _Moss_ index partitions.

The top-level syntax for `cbft-bleve` is provided at xref:cli:cbft-bleve.adoc[cbft-bleve].
All commands except xref:cli:cbft-bleve-scorch.adoc[scorch] and xref:cli:cbft-bleve-zap.adoc[zap] apply to _Moss_ indexes, and are described on this page.

[#flags]
== Flags

The following flags are optional for `cbft-bleve` commands for Moss indexes.
Note the usage here: `field` is synonymous with `key`; and `term` with `value`.
Therefore, for a `field` named `country`, the associated `terms` might include `france`, `united kingdom`, `united states`, and so on.

* `-c`, `--count` `int`.
The maximum number of terms to which the command is to be applied, per field.
The default is `100`.
Only _some_ commands can use this flag.

* `-f`, `--field` `string`.
A field to which command-execution should be restricted.
The default is for the command to be executed on _all_ fields.
Only _some_ commands can use this flag.

* `-h`, `--help`.
Prints help text to standard output.
_All_ commands can use this flag.

The `-c` and `-f` options are demonstrated in the second example for the xref:cli:cbft-bleve-moss.adoc#check[check] command, immediately below.

[#check]
== check

The `check` command checks for consistency the contents of a specified _Moss_ index partition.
Its syntax is as follows.

----
cbft-bleve check [index-path] [flags]
----

The `index-path`, which is mandatory, is the filesystem path to the index-partition.
The optional xref:cli:cbft-bleve-moss.adoc#flags[flags] are those standard for all Moss-related `cbft-bleve` commands.

=== Example: Check Consistency without Flags

In the following example, the `check` command is used without flags, to check the consistency of a specified _Moss_-index partition.

----
/opt/couchbase/bin/cbft-bleve check \
/opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex
----

If successful, the command returns output the initial lines of which are as follows.

----
2020/01/22 07:43:36 cbauth: key: fts/remoteClients registered for tls config updates
checking fields: [type tz country faa geo.alt geo.lat geo.lon icao id airportname city _all schedule.utc schedule.day schedule.flight sourceairport distance equipment stops airline airlineid destinationairport content phone name address email geo.accuracy hours url activity title free_internet reviews.author reviews.content reviews.date reviews.ratings.Cleanliness reviews.ratings.Location reviews.ratings.Overall reviews.ratings.Rooms reviews.ratings.Service reviews.ratings.Sleep Quality reviews.ratings.Value description free_parking pets_ok vacancy free_breakfast public_likes price state image image_direct_url callsign iata directions reviews.ratings.Check in / front desk reviews.ratings.Business service (e.g., internet access) fax alt reviews.ratings.Business service checkin checkout tollfree alias]
checking field: 'type'
field contains 5 terms
done checking 5 terms, found 0 problems
checking field: 'tz'
field contains 15 terms
done checking 15 terms, found 0 problems
checking field: 'country'
field contains 4 terms
done checking 4 terms, found 0 problems
checking field: 'faa'
field contains 276 terms
done checking 100 terms, found 0 problems
checking field: 'geo.alt'
field contains 3195 terms
done checking 100 terms, found 0 problems

  .
  .
  .
----

Thus, the list of fields to be checked is printed first (this containing _all_ fields, since no restriction has been specified); then, each field is separately listed; along with the number of terms associated with it, the number of those terms that have been checked, and the number of problems encountered with those terms, during checking.
Note that in cases where the number of terms specified to be associated with a field is greater than `100`, only `100` terms are indicated to have been checked.

=== Example: Check Consistency with Flags

In the following example, the `check` command is again used, this time with flags:
the sole `field` to be checked is specified as `geo.alt`; and the number of terms within it is raised to `150`, from the default of `100`:

----
sudo /opt/couchbase/bin/cbft-bleve check /opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex -c 150 -f geo.alt
----

If successful, the command returns output as follows.

----
2020/01/22 07:49:58 cbauth: key: fts/remoteClients registered for tls config updates
checking fields: [geo.alt]
checking field: 'geo.alt'
field contains 3195 terms
done checking 150 terms, found 0 problems
----

Thus, only the `geo.alt` field has been checked, with `150` associated terms.

== count

The `count` command prints to standard output the total number of documents referred to in the specified index partition.
Its syntax is as follows:

----
cbft-bleve count [index-path] [flags]
----

The `index-path` must be the pathname of a _Moss_-index partition, on the current node.
The value of the optional xref:cli:cbft-bleve-moss.adoc#flags[flags] parameter can only be `-h`, `--help`.

=== Example: Count Documents in an Index Partition

The following example counts the documents referred to in a specified Moss-index partition:

----
/opt/couchbase/bin/cbft-bleve count /opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex
----

If successful, this command displays the following:

----
2020/01/17 04:24:47 cbauth: key: fts/remoteClients registered for tls config updates
5286
----

The total number of documents referred to in the index partition is thereby confirmed as `5286`.

== dictionary

The `dictionary` command prints to standard output the _term dictionary_ for a specified field in a specified _Moss_-index partition.
The syntax is as follows:

----
cbft-bleve dictionary [index-path] [field-name] [flags]
----

The `index-path` must be the pathname of a _Moss_-index partition, on the current node.
The optional `field-name` is the name of a specific field within the index partition, for which term-dictionary content should be returned: if this is is not specified, the default is for term-dictionary content on _all_ fields to be returned.
The value of the optional xref:cli:cbft-bleve-moss.adoc#flags[flags] parameter can only be `-h`, `--help`.

=== Example: Return the Dictionary for All Fields

The following example returns the term dictionary for all fields on a specified index partition.

----
/opt/couchbase/bin/cbft-bleve dictionary \
/opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex name
----

If successful, the command displays output whose initial lines are as follows:

----
2020/01/17 04:26:12 cbauth: key: fts/remoteClients registered for tls config updates
1 - 1
24 - 1
4 - 1
40 - 1
500 - 1
55 - 1
575 - 1
58 - 1
9 - 1
a16 - 1
abbey - 2
aberdulais - 1
abergele - 1
aberystwyth - 1
absinthe - 1
abu - 1
ace - 1
adobe - 1
african - 1
aiguille - 1
  .
  .
  .
----

== dump

The `dump` command dumps the entire or partial contents of a specified _Moss_-index partition.
The syntax takes two alternative forms:

----
cbft-bleve dump [index-path] [flags]

cbft-bleve dump [index-path][command] [flags]
----

The `index-path`, which is mandatory, is the filesystem path to the index-partition: if only this is specified, the `dump` command dumps the entire contents of the specified index partition.

The optional `command` can be one of the following:

* `doc`.
Only the rows relating to a specified document id are dumped.
This id must follow the `index-path`: thus, the syntax becomes `cbft-bleve dump doc [index-path] [doc-id]`.

* `fields`.
Only the `field` rows from the index partition are dumped.
The complete syntax for the command becomes `cbft-bleve dump fields [index-path]`.

The value of the optional xref:cli:cbft-bleve-moss.adoc#flags[flags] parameter can only be `-h`, `--help`.

=== Example: Dump an Entire Index Partition

The following command dumps the entire contents of the specified index partition.

----
/opt/couchbase/bin/cbft-bleve dump /opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex
----

If successful, the command displays output whose initial lines appear as follows:

----
2020/01/20 06:06:07 cbauth: key: fts/remoteClients registered for tls config updates
Backindex DocId: `airline_10` Terms Entries: [field:0 terms:"airline"  field:53 terms:"mile" terms:"air"  field:2 terms:"united" terms:"states"  field:54 terms:"q5"  field:7 terms:"mla"  field:11 terms:"\\\014" terms:",\006\000H\000\000\000\000\000" terms:"40" terms:"airline" terms:"states" terms:"mla" terms:"P\003\000$" terms:"mile" terms:"air" terms:"L0\004@" terms:"8\030\002 \000\000\000" terms:"@\014\001\020\000\000" terms:"$\014\001\020\000\000\000\000\000\000" terms:"X\001@" terms:"00\004@\000\000\000\000" terms:"T\030\002" terms:"4\003\000$\000\000\000\000" terms:"D`\t\000\000" terms:"<\001@\022\000\000\000" terms:"united" terms:"q5" terms:" \001@\022\000\000\000\000\000\000\000" terms:"H\006\000H\000" terms:"(`\t\000\000\000\000\000\000"  field:8 terms:",\006\000H\000\000\000\000\000" terms:"4\003\000$\000\000\000\000" terms:"<\001@\022\000\000\000" terms:"@\014\001\020\000\000" terms:"P\003\000$" terms:"T\030\002" terms:"\\\014" terms:" \001@\022\000\000\000\000\000\000\000" terms:"H\006\000H\000" terms:"$\014\001\020\000\000\000\000\000\000" terms:"L0\004@" terms:"X\001@" terms:"(`\t\000\000\000\000\000\000" terms:"00\004@\000\000\000\000" terms:"8\030\002 \000\000\000" terms:"D`\t\000\000"  field:24 terms:"air" terms:"40" terms:"mile" ], Stored Entries: []
Key:   62 61 69 72 6c 69 6e 65 5f 31 30
Value: 0a 0b 08 00 12 07 61 69 72 6c 69 6e 65 0a 0d 08 35 12 04
  .
  .
  .
----

=== Example: Dump Rows for a Document

The following command uses the `doc` option to dump the rows that correspond to the document `airline_10`.

----
/opt/couchbase/bin/cbft-bleve dump doc \
/opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex airline_10
----

If successful, the command displays output whose initial lines are as follows:

----
2020/01/20 06:10:37 cbauth: key: fts/remoteClients registered for tls config updates
Term: `airline` Field: 0 DocId: `airline_10` Frequency: 1 Norm: 1.000000 Vectors: [Field: 0 Pos: 1 Start: 0 End 7 ArrayPositions: []uint64(nil)]
Key:   74 00 00 61 69 72 6c 69 6e 65 ff 61 69 72 6c 69 6e 65 5f 31 30
Value: 01 80 80 80 fc 03 00 01 00 07 00

Term: `states` Field: 2 DocId: `airline_10` Frequency: 1 Norm: 0.707107 Vectors: [Field: 2 Pos: 2 Start: 7 End 13 ArrayPositions: []uint64(nil)]
Key:   74 02 00 73 74 61 74 65 73 ff 61 69 72 6c 69 6e 65 5f 31 30
Value: 01 f3 89 d4 f9 03 02 02 07 0d 00
  .
  .
  .
----

=== Example: Dump Index Fields

The following command uses the `fields` option to dump only the `fields` rows of the index:

----
/opt/couchbase/bin/cbft-bleve dump fields \
/opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex
----

If successful, the command displays output whose initial lines are as follows:

----
2020/01/20 06:13:00 cbauth: key: fts/remoteClients registered for tls config updates
Field: 0 Name: type
Key:   66 00 00
Value: 74 79 70 65 ff

Field: 1 Name: tz
Key:   66 01 00
Value: 74 7a ff

Field: 2 Name: country
Key:   66 02 00
Value: 63 6f 75 6e 74 72 79 ff
----

== fields

The `fields` command lists the fields in a specified _Moss_-index partition.
The syntax is as follows:

----
cbft--bleve fields [index-path] [flags]
----

The `index-path`, which is mandatory, is the filesystem path to the index-partition.
The command dumps the entire contents of the specified index partition.

The value of the optional xref:cli:cbft-bleve-moss.adoc#flags[flags] parameter can only be `-h`, `--help`.

=== Example: List Fields in an Index

The following command lists the fields in a specified index partition.

----
/opt/couchbase/bin/cbft-bleve fields /opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex
----

If successful, the command displays output whose initial lines are as follows:

----
2020/01/20 06:49:20 cbauth: key: fts/remoteClients registered for tls config updates
0 - type
1 - tz
2 - country
3 - faa
4 - geo.alt
5 - geo.lat
6 - geo.lon
7 - icao
8 - id
9 - airportname
10 - city
11 - _all
12 - schedule.utc
13 - schedule.day
14 - schedule.flight
  .
  .
  .
----

== mapping

The `mapping` command prints to standard output the _mapping_ used for a specified _Moss_-index partition.
The syntax is as follows:

----
cbft-bleve mapping [index path] [flags]
----

The `index-path`, which is mandatory, is the filesystem path to the index-partition.
The command prints the mapping for the specified index partition.
The optional xref:cli:cbft-bleve-moss.adoc#flags[flags] are those standard for all Moss-related `cbft-bleve` commands.

=== Example: Print the Mapping for an Index Partition

The following example prints out the mapping for a specified index partition:

----
/opt/couchbase/bin/cbft-bleve mapping /opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex
----

If successful, the command prints out the following:

----
2020/01/17 04:31:20 cbauth: key: fts/remoteClients registered for tls config updates
{
  "default_mapping": {
    "enabled": true,
    "dynamic": true
  },
  "type_field": "_type",
  "default_type": "_default",
  "default_analyzer": "standard",
  "default_datetime_parser": "dateTimeOptional",
  "default_field": "_all",
  "store_dynamic": false,
  "index_dynamic": true,
  "docvalues_dynamic": true,
  "analysis": {}
}
----

== query

The `query` command executes a specified query against a specified _Moss_-index partition.
The syntax is as follows:

----
cbft-bleve query [index-path] [query] [flags]
----

The `index-path`, which is mandatory, is the filesystem path to the index-partition.
The `query` is as described in xref:fts:fts-queries.adoc[Understanding Queries].
The optional flags are as follows:

[cols="1,2"]
|===
| Flag | Description

| `-X`, `--explain`
| Explain the result scoring.

| `-f`, `--field string`
| Restrict the query to the field specified by `string`.
By default, no restriction is applied.
This parameter is not applied to _query-string_ queries.

| `--fields`
| Load stored fields.
If this is not specified, fields are not loaded.

| `--highlight`
| Highlight matching text in results.

| `-l`, `--limit int`
| Limit the number of results returned.
The default is `10`.

| `-r`, `--repeat int`
| Repeat the query this many times.
The default is `1`.

| `-s`, `--skip int`
| Skip this many results.
The default is `0`.

| `-b`, `--sort-by string`
| Sort the results by the specified field.

| `-t`, `--type string`
| The type of query to be run.
The default is `'query_string'` query.

| `--help`
| Prints help text to standard output.

|===

=== Example: Submit Query

The following example applies to the specified index partition a _query-string_ query that returns all hotels whose cleanliness rating is greater than `4`.

----
/opt/couchbase/bin/cbft-bleve query /opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex 'reviews.ratings.Cleanliness:>4'
----

If successful, the command returns the following:

----
2020/01/20 07:40:23 cbauth: key: fts/remoteClients registered for tls config updates
108 matches, showing 1 through 10, took 22.54727ms
    1. hotel_21673 (1.220367)
    2. hotel_26139 (1.220367)
    3. hotel_5335 (1.220367)
    4. hotel_15978 (1.220367)
    5. hotel_21665 (1.220367)
    6. hotel_21679 (1.220367)
    7. hotel_35667 (1.220367)
    8. hotel_635 (1.220367)
    9. hotel_4397 (1.220367)
   10. hotel_16458 (1.220367)
----

== registry

The `registry` command prints to standard output a list of the _analyzers_, _tokenizers_ and other components used by a specified _Moss_-index partition.

The syntax is as follows:

----
cbft-bleve registry [flags]
----

The optional xref:cli:cbft-bleve-moss.adoc#flags[flags] are those standard for all Moss-related `cbft-bleve` commands.

=== Example: Print the Registry for an Index

The following command prints out the registry for the specified index partition:

----
/opt/couchbase/bin/cbft-bleve registry \
/opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex
----

If successful, the command produces output whose initial lines are as follows:

----
2020/01/17 04:44:07 cbauth: key: fts/remoteClients registered for tls config updates
Char Filter Types:
	regexp

Char Filter Instances:
	asciifolding
	html
	zero_width_spaces

Tokenizer Types:
	exception
	regexp

Tokenizer Instances:
	letter
	single
	unicode
	web
	whitespace

Token Map Types:
	custom

Token Map Instances:
	articles_ca
	articles_fr
	articles_ga
	articles_it
	stop_ar
	stop_bg
    .
    .
    .
----

== Additional Commands

The following, additional commands are supported:

* `scorch`.
Returns information on a _Scorch_-index partition.
For information, see xref:cli:cbft-bleve-scorch.adoc[cbft-bleve for Scorch Indexes].

* `zap`.
Returns information on a _Zap_ file.
For information, see xref:cli:cbft-bleve-zap.adoc[cbft-bleve for Zap Files].
