= cbft-bleve
:page-topic-type: reference

[abstract]
The `cbft-bleve` tool returns information on a _Full Text Index_ partition.

== Syntax

----
cbft-bleve [command] [ --help ]
----

The `command` specified as the principal argument to `cbft-bleve` can be any one of the following.
(Note that each possible argument entails it own, additional syntax: all of which is described and exemplified on this page, further below.)

[cols="1,2"]
|===
| Command | Description

| `check`
| Checks the contents of a specified _Moss_-index partition.

| `count`
| Counts the number of documents referenced by a specified _Moss_-index partition.

| `dictionary`
| Prints to standard output the _term dictionary_ for a specified field in a specified _Moss_-index partition.

| `dump`
| Dumps the contents of a specified _Moss_-index partition.

| `fields`
| Lists the fields in a specified _Moss_-index partition.

| `mapping`
| Prints to standard output the _mapping_ used for a specified _Moss_-index partition.

| `query`
| Executes a specified query against a specified _Moss_-index partition.

| `registry`
| Prints to standard output the _analyzers_, _tokenizers_ and other components used by a specified _Moss_-index partition.

| `scorch`
| Establishes that the specified index partition on which information is to returned is a _Scorch_-index partition.

| `zap`
| Estabishes that the specified path is that of a `zap` file, on which information is to be returned.

| `--help`
| When a value for `command` is _not_ specified, prints help text to standard output, describing the acceptable values of `command`.
When a value for `command` _is_ specified, prints help text describing the additional syntax entailed by the specified value.

|===

== Specifying Index Partitions

The _Search_ Service divides each _Full Text Index_ into _partitions_.
The default number of partitions per index is six.
For information, see xref:fts:fts-creating-indexes.adoc#index-partitions[Index Partitions].

Most commands that can be used with the `cbft-bleve` tool take as their principal argument the filesystem path of an index partition.
Index partitions  are themselves _directories_.
The name of each (whether it is a _Moss_ or a _Scorch_ index) is formed from the _user-defined index-name_, the _uuid of the user-defined index_, and the _partition id_: these are connected with underscores, and given the `.pindex` suffix.
For example, `myIndex_690ef363c7557832_13aa53f3.pindex`.

Index partitions can be found in the following locations, on each node running the Search Service:

[cols="2,6"]
|===
| OS | Location

| _Linux_
| /opt/couchbase/var/lib/couchbase/data/@fts/

| _Windows_
| C:\Program Files\couchbase\server\var\lib\couchbase\data\@fts\

| _MacOS_
| /Library/Application Support/Couchbase/var/lib/couchbase/data/@fts/

|===

To specify a _Moss_ index partition, the pathname of the `.pindex` directory (located in one of the `@fts` directories listed above) should be given.
To specify a _Scorch_ index partition, the pathname of the `store` subdirectory (located in the `.pindex` directory) should be given.
To specify a `zap` file, the pathname of the `.zap` file itself (located in the `store` subdirectory, under the `.pindex` directory) should be given.
Examples of all cases are provided below.

Note that on Linux and MacOS, supervisor permission may be required to view and access index partitions: therefore, the `sudo` command should be used as appropriate.

== Per-Command Syntax

Each of the top-level commands that can be specified as a value to `cbft-bleve` entails its own syntax.
The `scorch` and `zap` values refer to a specified  `Scorch` index and a `zap` file, respectively.
All other top-level commands refer to a specified  _Moss_ index.

Syntax and command-line examples for `cbft-bleve` when applied to:

* _Moss_ indexes, is provided at xref:cli:cbft-bleve-moss.adoc[cbft-bleve for Moss Indexes].

* _Scorch_ indexes, is provided at xref:cli:cbft-bleve-scorch.adoc[cbft-bleve for Scorch Indexes].

* _Zap_ files, is provided at xref:cli:cbft-bleve-zap.adoc[cbft-bleve for Zap Files].
