= cbft-bleve for Scorch Indexes
:page-topic-type: reference

[abstract]
The `cbft-bleve` tool supports commands that return information on _Scorch_ index partitions.

== Using cbft-bleve on Scorch indexes.

The basic syntax is as follows:

----
cbft-bleve scorch [command] [index-store-path] [snapshot] [flags]
----

The available `commands` are listed in the sections below.
A `command` _must_ be specified.
Note that a command summary can be printed to standard output, by entering `cbft-bleve scorch --help`.

The `index-store-path`, which is mandatory, is the filesystem path of the `store` subdirectory, located under the directory for the _Scorch_ index partition.
See xref:cli:cbft-bleve.adoc#specifying-index-partitions[Specifying Index Partitions].

The `snapshot` is a reference to a particular _snapshot_, within a _Scorch_-index partition, on which information is to be retrieved.
See immediately below.

The `flags` argument can always be `--help`, which prints help text to standard output.
Additional values are indicated as appropriate, below.

== Understanding Snapshots

Each _Scorch_ index contains three _snapshots_, each of which represents the state of all indexed data at a particular point in time.
This supports the possibility of _rollback_ of the index.
By default, three snapshots are maintained continually.
Each snapshot is referred to by a unique integer known as the _snapshot epoch_.
Some `commands` used by `cbft-bleve scorch` refer to a specific snapshot epoch.
Information on currently available snapshot epochs and their unique identifying integers is returned by means of the `snapshot` command.

== snapshot

The `snapshot` command prints a list of _snapshot epochs_ that currently exist for a specified Scorch index partition.
The syntax is as follows:

----
cbft-bleve scorch snapshot [index-store-path] [flags]
----

=== Example: Print Snapshot Epochs

The following example prints out the snapshot epochs for the specified index partition:

----
/opt/couchbase/bin/cbft-bleve scorch snapshot \
/Library/Application\ Support/Couchbase/var/lib/couchbase/data/@fts/\
demoIndex_1125629e41599ad8_92af29e5.pindex/store/
----

If successful, the command prints the following:

----
2020/01/20 22:08:11 cbauth: key: fts/remoteClients registered for tls config updates
snapshot epoch: 37
snapshot epoch: 36
snapshot epoch: 1
----

== ascii

The `ascii` command prints an ascii representation of the _segments_ in a snapshot.
The syntax is as follows:

----
cbft-bleve scorch ascii [index-store-path] [snapshot]
----

The `snapshot`, which is mandatory, must be the unique integer associated with a _snapshot epoch_ for the specified index, as returned by the `snapshot` command.

=== Example: Print an ASCII Representation

The following example prints an ascii representation of the segments in the snapshot specified for an index partition.

----
/opt/couchbase/bin/cbft-bleve scorch ascii \
/Library/Application\ Support/Couchbase/var/lib/couchbase/data/@fts\
demoIndex_1125629e41599ad8_92af29e5.pindex/store/\
37
----

If successful, the command returns the following:

----
2020/01/20 22:28:17 cbauth: key: fts/remoteClients registered for tls config updates
37    37:  5433 / 5433 -   .........................
----

== deleted

The `deleted` prints the _deleted_ bitmaps for the segments in a specified snapshot.
The syntax is as follows:

----
cbft-bleve scorch deleted [index-store-path] [snapshot] [flags]
----

The `snapshot`, which is mandatory, must be the unique integer associated with a _snapshot epoch_ for the specified index, as returned by the `snapshot` command.

=== Example: Print the Deleted Bitmap

The following example prints the deleted bitmap for the segments in the specified snapshot.

----
/opt/couchbase/bin/cbft-bleve scorch deleted \
/Library/Application\ Support/Couchbase/var/lib/couchbase/data/@fts/\
demoIndex_1125629e41599ad8_92af29e5.pindex/store/ 37
----

If successful, the command returns the following:

----
2020/01/17 20:52:22 cbauth: key: fts/remoteClients registered for tls config updates
0 <nil>
----

== info

The `info` command prints information on a specified index partition.
The syntax is as follows:

----
cbft-bleve scorch info [index-store-path] [flags]
----

=== Example: Print Info on an Index Partition

The following example prints information on the specified Scorch index partition.

----
/opt/couchbase/bin/cbft-bleve scorch info \
/Library/Application\ Support/Couchbase/var/lib/couchbase/data/@fts/\
demoIndex_1125629e41599ad8_92af29e5.pindex/store/
----

If successful, the command returns the following:

----
2020/01/20 22:40:32 cbauth: key: fts/remoteClients registered for tls config updates
doc count: 5433
----

== internal

The `internal` command prints the internal `kv` pairs within a snapshot.
The syntax is as follows:

----
cbft-bleve scorch internal [index-store-path] [snapshot] [flags]
----

The `snapshot`, which is mandatory, must be the unique integer associated with a _snapshot epoch_ for the specified index, as returned by the `snapshot` command.

The `flags` argument can be `-a` or `--ascii`; which indicates that the values are to be printed in ascii.

=== Example: Print KV Pairs

The following example provides an ascii print-out of the `kv` pairs for the specified index-snapshot:

----
/opt/couchbase/bin/cbft-bleve scorch internal \
/Library/Application\ Support/Couchbase/var/lib/couchbase/data/@fts/\
demoIndex_1125629e41599ad8_92af29e5.pindex/store/ \
37 -a
----

If successful, the command provides the following output:

----
2020/01/20 22:47:40 cbauth: key: fts/remoteClients registered for tls config updates
42 ?
43 ?
_mapping {"types":{"product":{"enabled":true,"dynamic":true,"properties":{"price":{"enabled":true,"dynamic":false,"fields":[{"name":"price","type":"number","index":true,"include_term_vectors":true,"include_in_all":true}]}}}},"default_mapping":{"enabled":false,"dynamic":true},"type_field":"_type","default_type":"_default","default_analyzer":"standard","default_datetime_parser":"dateTimeOptional","default_field":"_all","store_dynamic":false,"index_dynamic":true,"docvalues_dynamic":true,"analysis":{}}
o:39 {"seqStart":0,"seqEnd":0,"snapStart":0,"snapEnd":501,"failOverLog":[[149680438380220,0]]}
36 ?
41 ?
38 ?
o:33 {"seqStart":0,"seqEnd":0,"snapStart":0,"snapEnd":484,"failOverLog":[[81822404584738,0]]}
o:36 {"seqStart":0,"seqEnd":0,"snapStart":0,"snapEnd":492,"failOverLog":[[174103028649261,0]]}
o:37 {"seqStart":0,"seqEnd":0,"snapStart":0,"snapEnd":486,"failOverLog":[[110924524680780,0]]}
o:41 {"seqStart":0,"seqEnd":0,"snapStart":0,"snapEnd":497,"failOverLog":[[155103402616817,0]]}
o:43 {"seqStart":0,"seqEnd":0,"snapStart":0,"snapEnd":507,"failOverLog":[[217538306806458,0]]}
33 ?
37 ?
o:42 {"seqStart":0,"seqEnd":0,"snapStart":0,"snapEnd":492,"failOverLog":[[47136605887494,0]]}
34 ?
o:35 {"seqStart":0,"seqEnd":0,"snapStart":0,"snapEnd":485,"failOverLog":[[181174121062964,0]]}
40 ?
o:34 {"seqStart":0,"seqEnd":0,"snapStart":0,"snapEnd":499,"failOverLog":[[128188523546156,0]]}
o:38 {"seqStart":0,"seqEnd":0,"snapStart":0,"snapEnd":486,"failOverLog":[[161601347095991,0]]}
o:40 {"seqStart":0,"seqEnd":0,"snapStart":0,"snapEnd":504,"failOverLog":[[38787600199365,0]]}
35 ?
39 ?
----
