= cbft-bleve for Moss Indexes
:page-topic-type: reference

[abstract]
The `cbft-bleve` tool supports commands that return information on _Moss_ index partitions.

The full top-level syntax for `cbft-bleve` is provided at xref:cli:cbft-bleve.adoc[cbft-bleve].
All commands _except_ `scorch` and `zap` apply to _Moss_ indexes, and are listed in the sections below.

[#flags]
=== Flags

The following flags are optional for all `cbft-bleve` commands for Moss indexes.

* `-c`, `--count` `int`
+
The number of terms within the index that are to be checked.
The default is `100`.

* `-f`, `--field` `string`
A field to which the check should be restricted.
The default is that _all_ fields are checked.

== check

The `check` command checks the contents of a specified _Moss_ index.
Its syntax is as follows.

----
check [index-path] [flags]
----

The `index-path`, which is mandatory, is the filesystem path to the index-file.
The optional xref:cli:cli-bleve-moss.adoc#flags[flags] are those standard for all Moss-related `cbft-bleve` commands.

In the following example, the `check` command is used to check the consistency of a specified _Moss_ partition-index.
No flags are used.
Only the initial lines of the (substantial) output is represented.

----
/opt/couchbase/bin/cbft-bleve check \
/opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex
----

If successful, the command returns output the initial lines of which are as follows.
Note that the list of fields to be checked is printed first; then, each field and the number of terms it contains is listed, along with the number of problems encountered with the field.

----
2020/01/17 04:20:49 cbauth: key: fts/remoteClients registered for tls config updates
checking fields: [type tz country faa geo.alt geo.lat geo.lon icao id airportname city _all schedule.utc schedule.day schedule.flight sourceairport distance equipment stops airline airlineid destinationairport content phone name address email geo.accuracy hours url activity title free_internet reviews.author reviews.content reviews.date reviews.ratings.Cleanliness reviews.ratings.Location reviews.ratings.Overall reviews.ratings.Rooms reviews.ratings.Service reviews.ratings.Sleep Quality reviews.ratings.Value description free_parking pets_ok vacancy free_breakfast public_likes price state image image_direct_url callsign iata directions reviews.ratings.Check in / front desk reviews.ratings.Business service (e.g., internet access) fax alt reviews.ratings.Business service checkin checkout tollfree alias]
checking field: 'type'
field contains 5 terms
done checking 5 terms, found 0 problems
checking field: 'tz'
field contains 15 terms
done checking 15 terms, found 0 problems
checking field: 'country'
field contains 4 terms
done checking 4 terms, found 0 problems
checking field: 'faa'
field contains 276 terms
  .
  .
  .
----

== count

The `count` commands prints to standard output the total number of documents referred to in the specified index partition.
Its syntax is as follows:

----
cbft-bleve count [index-path] [flags]
----

The `index-path` must be the pathname of a _Moss_ index partition, on the current node.
The optional xref:cli:cli-bleve-moss.adoc#flags[flags] are those standard for all Moss-related `cbft-bleve` commands.

The following example counts the documents referred to in a specified Moss index partition, and uses no flags:

----
/opt/couchbase/bin/cbft-bleve count \
/opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex
----

If successful, the `count` command displays output similar to the following:

----
2020/01/17 04:24:47 cbauth: key: fts/remoteClients registered for tls config updates
5286
----

The total number of documents referred to in the index partition is thereby confirmed as `5286`.

== dictionary

The `dictionary` command prints to standard output the _term dictionary_ for a specified field in a specified _Moss_-index partition.
The syntax is as follows:

----
cbft-bleve dictionary [index-path] [field-name] [flags]
----

The `index-path` must be the pathname of a _Moss_ index partition, on the current node.
The optional `field-name` is the name of a specific field within the index partition, for which term-dictionary content should be returned: if this is is not specified, the default is for term-dictionary content on _all_ fields to be returned.

The optional xref:cli:cli-bleve-moss.adoc#flags[flags] are those standard for all Moss-related `cbft-bleve` commands.

The following example returns the term dictionary for all fields on a specified index partition.

----
/opt/couchbase/bin/cbft-bleve dictionary \
/opt/couchbase/var/lib/couchbase/data/@fts/\
mossIndex_690ef363c7557832_54820232.pindex name
----

If successful, the command displays output the initial lines of which are as follows:

----
2020/01/17 04:26:12 cbauth: key: fts/remoteClients registered for tls config updates
1 - 1
24 - 1
4 - 1
40 - 1
500 - 1
55 - 1
575 - 1
58 - 1
9 - 1
a16 - 1
abbey - 2
aberdulais - 1
abergele - 1
aberystwyth - 1
absinthe - 1
abu - 1
ace - 1
adobe - 1
african - 1
aiguille - 1
  .
  .
  .
----
