= cbqueryreportgen
:description: pass:q[The `cbqueryreportgen` tool returns the complete details of any Query service to generate reports.]
:page-status: Couchbase Server 8.0
:page-component: Query
ifndef::doctype-manpage[:doctitle: cbqueryreportgen]
:page-component-version: 8.0
:page-topic-type: reference

[abstract]
A query tool that returns the complete details of any Query Service to generate reports.

== Syntax

----
cbqueryreportgen [-<args>
                  [ -c, --cluster <cluster> ]
                  [ -u, --username <username> ]
                  [ -p, --password <password> ]
                  [ -k, --keyspace <keyspace> ]
                  [ -t1, --start-time <start-time> ]
                  [ -t2, --end-time <end-time> ]
                  [ -o, --output <output> ]
                  [ -l, --limit <limit> ]
                  [ -v, --verbose ]
                  [ -h, --help ] 
                 ]
----


== Description

ifeval::['{page-component-version}' == '8.0'] 
This tool is only available in Couchbase Server 8.0 and later.
endif::[]

The `cbqueryreportgen` command connects to a Couchbase cluster and generates performance reports based on the Query Service's AWR statistics.

The tool allows you to specify a time range for the report. You can specify 2 different time periods, allowing a report to be generated that compares query statistics over the different time periods. You can also specify the type of report and the output format. By default, the output of the command is a report in HTML format. You can save the generated report to a file or print it to the standard output.

Depending upon your platform, this tool is at the following locations:

[cols="1,3"]
|===
| Operating system | Location

| Linux
| [.path]`/opt/couchbase/bin/`

| Windows
| [.path]`C:\Program Files\Couchbase\Server\bin\`

| Mac OS X
| [.path]`/Applications/CouchbaseServer.app/Contents/Resources/couchbase-core/bin/`
|===

== Options 

Required flags: 

The following flags are required to run the `cbqueryreportgen` command.

The `-c, --cluster` flag specifies the hostname of the Couchbase cluster. Example: `cbqueryreportgen couchbase://localhost`.

The `-u, --username` flag specifies the username of the Couchbase cluster. Example: `cbqueryreportgen --username Administrator`.

The `-p, --password` flag specifies the password of the Couchbase cluster. Example: `cbqueryreportgen --password password`.

The `-k, --keyspace` flag specifies the keyspace. The keyspace is the AWR repository in the `bucket.scope.collection` format. Example: `travel-sample._default.awr`.

The `-t1` and `-t2` flags specify the start-time and end-time for the report. Enter both start-time and end-time as `t1,t2` in the `YYYY-MM-DDTHH:MM:SS` format. Example: `2025-09-01T00:00:00,2025-09-02T00:00:00`.

The `-o, --output` flag specifies the output file to write the report to. Example: `cbqueryreportgen.html`.

Optional flags:

The `-l, --limit` flag specifies the maximum number of results to include for every query. The default is `1000`.

The `-v, --verbose` flag enables verbose logging for debugging purposes.

The `-h, --help` flag prints the help information.

For more information about how the specific command works, run `cbqueryreportgen --help`.

The `--version` flag prints to the console the version number of the Couchbase Server.

== Example

This example creates a report showing all of the statistics for a single day.
The AWR repository is `travel-sample._default.awr`. It's assumed that you have already specified this as the AWR repository, and created an index on the document key in the configured AWR location.

====
[source,sh]
----
cbqueryreportgen -c couchbase://localhost \
-u Administrator -p password \
-k travel-sample._default.awr \
-o report.html \
-t1 '2025-09-01T00:00:00,2025-09-01T23:59:59'
----
====

The output of the command is a report in HTML format, saved to the file `cbqueryreportgen.html`.

== See Also 

For detailed information, see xref:n1ql:n1ql-manage/query-awr.adoc[Automatic Workload Repository].
