= cbreset_password
:page-topic-type: reference

[abstract]
The [.cmd]`cbreset_password` tool is used to reset the built-in administrator account's password.

== Syntax

The basic syntax to reset the administrative password:

----
cbreset_password [hostname]:[port]
----

This results in output as follows:

----
Please enter the new administrative password (or <Enter> for system generated password):
----

Enter a password of six characters or more or accept the system generated password.
After entering a password or accepting a generated one, the system prompts for confirmation:

----
Running this command will reset administrative password.
Do you really want to do it? (yes/no)yes
----

== Description

This tool is found in the following locations, depending upon your platform:

[cols="1,3"]
|===
| Operating System | Location

| Linux
| [.path]_/opt/couchbase/bin/cbreset_password_

| Windows
| [.path]_C:\Program Files\Couchbase\Server\bin\cbreset_password_

| Mac OS X
| [.path]_/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin/cbreset_password_
|===

== Options

None

== Example

Reset the password and shows a successful response.

----
# cbreset_password 10.5.2.117:8091

Please enter the new administrative password (or <Enter> for system generated password):

Running this command will reset administrative password.
Do you really want to do it? (yes/no)yes
Resetting administrative password...
Password for the the user Administrator was successfully replaced.
----

*Response*

The following example response shows a system generated password.

----
Resetting administrative password...
Password for the user Administrator was successfully replaced. New password is Uxye76FJ
----

*Response errors*

There are a few possible errors from this command:

----
{error,<<"The password must be at least six characters.">>}

{error,<<"Failed to reset administrative password. Node is not initialized.">>}
----

The first error message indicates that the password wasn't long enough.
The second error message indicates that Couchbase Server is not yet configured and running.
