= CLI reference

[abstract]
Couchbase Server command-line interface (CLI) tools are provided to manage and monitor clusters, servers, vBuckets, XDCR, and so on.

By default, the CLI tools are installed into the following locations on each platform:

[cols="50,313"]
|===
| Operating System | Directory Locations

| Linux
| [.path]_/opt/couchbase/bin_, [.path]_/opt/couchbase/bin/install_, and [.path]_/opt/couchbase/bin/tools_

| Windows
| [.path]_C:\Program Files\couchbase\server\bin_, [.path]_C:\Program Files\couchbase\server\bin\install_, and [.path]_C:\Program Files\couchbase\server\bin\tools_.

| Mac OS X
| [.path]_/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin_

[.path]_/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin/tools_

[.path]_/Applications/Couchbase Server.app/Contents/Resources/couchbasecore/bin/install_
|===

== Managing diagnostics

The command-line interface provides commands to start, stop, and report status for log collection.
You can collect diagnostics through the command-line interface by using either the xref:cbcli-intro.adoc[[.cmd]`couchbase-cli`] couchbase-cli tool or the xref:cbcollect-info-tool.adoc[[.cmd]`cbcollect_info`] cbcollect_info tool.
