=== FROM Term

The *FROM term* is a keyspace reference or expression which defines the input object(s) for the query, representing the left-hand side of the `{clause}` clause.

The FROM term is recursive, which enables you to chain the `{clause}` clause with any of the terms which are permitted in the `FROM` clause, including other `{clause}` clauses.
For more information, see the page on the xref:n1ql-language-reference/from.adoc[FROM] clause.

There are restrictions on what types of FROM terms may be chained and in what order -- see the descriptions on this page for more details.

A summary of the different types of FROM term is given in the following table.

[#table_vrv_nxx_1db,cols="1,3"]
|===
| Type | Example

| xref:n1ql-language-reference/from.adoc#sec_from-keyspace[keyspace identifier]
a|
[source,N1QL]
----
`travel-sample`
----
| xref:n1ql-language-reference/from.adoc#generic-expr[generic expression]
a|
[source,N1QL]
----
20+10 AS Total
----
| xref:n1ql-language-reference/from.adoc#select-expr[subquery]
a|
[source,N1QL]
----
SELECT t1.country, ARRAY_AGG(t1.city), SUM(t1.city_cnt) AS apnum
FROM (
  SELECT city, city_cnt, ARRAY_AGG(airportname) AS apnames, country
  FROM `travel-sample`
  WHERE type = "airport"
  GROUP BY city, country
  LETTING city_cnt = COUNT(city)
) AS t1
WHERE t1.city_cnt > 5;
----
| previous xref:n1ql-language-reference/join.adoc[join], xref:n1ql-language-reference/nest.adoc[nest], or xref:n1ql-language-reference/unnest.adoc[unnest]
a|
[source,N1QL]
----
SELECT *
FROM `travel-sample` AS rte
JOIN `travel-sample` AS aln
  ON rte.airlineid = META(aln).id
NEST `travel-sample` AS lmk
  ON aln.landmarkid = META(lmk).id;
----
|===
