=== Placement

The `{clause}` clause cannot be the first term within the `FROM` clause; it must be preceded by another FROM term.
The term immediately preceding the `{clause}` clause represents the left-hand side of the `{clause}` clause.

You can chain the `{clause}` clause with any of the other permitted FROM terms, including other `{clause}` clauses.
For more information, see the page on the xref:n1ql-language-reference/from.adoc[FROM] clause.

There are restrictions on what types of FROM terms may be chained and in what order -- see the descriptions on this page for more details.

The types of FROM term that may be used as the left-hand side of the `{clause}` clause are summarized in the following table.

[#table_vrv_nxx_1db,cols="1,3"]
|===
| Type | Example

.^| xref:n1ql-language-reference/from.adoc#sec_from-keyspace[keyspace identifier]
a|
[source,N1QL]
----
`travel-sample`.inventory.hotel
----
.^| xref:n1ql-language-reference/from.adoc#generic-expr[generic expression]
a|
[source,N1QL]
----
20+10 AS Total
----
.^| xref:n1ql-language-reference/from.adoc#select-expr[subquery]
a|
[source,N1QL]
----
SELECT ARRAY_AGG(t1.city) AS cities,
  SUM(t1.city_cnt) AS apnum
FROM (
  SELECT city, city_cnt, country,
    ARRAY_AGG(airportname) AS apnames
  FROM `travel-sample`.inventory.airport
  GROUP BY city, country
  LETTING city_cnt = COUNT(city)
) AS t1
WHERE t1.city_cnt > 5;
----
.^| previous xref:n1ql-language-reference/join.adoc[join], xref:n1ql-language-reference/nest.adoc[nest], or xref:n1ql-language-reference/unnest.adoc[unnest]
a|
[source,N1QL]
----
SELECT *
FROM `travel-sample`.inventory.route AS rte
JOIN `travel-sample`.inventory.airport AS apt
  ON rte.destinationairport = apt.faa
NEST `travel-sample`.inventory.landmark AS lmk
  ON apt.city = lmk.city
LIMIT 5;
----
|===
