= Manage Documents
:imagesdir: ../../assets/images
:page-topic-type: guide
:page-pagination:
:description: Couchbase Web Console provides a graphical interface that you can use to view and edit documents.

// FIXME: Needs further information about spreadsheet view, copying existing records, etc.

[abstract]
{description}

[.signpost]
image:ROOT:couchbase-logo.svg["Couchbase Server", 25.6]
This page is for Couchbase Server.
For Couchbase Capella, see xref:cloud:clusters:data-service/manage-documents.adoc[].

== Access Documents in the Couchbase Web Console

You can use the *Documents* tool to view and manage documents in a database.

To display the *Documents* tool, do one of the following:

* In the Couchbase Web UI, click menu:Documents[].

* Alternatively, click menu:Buckets[], then click the *Documents* link for any bucket, scope, or collection.

[#retrieve-documents]
== Retrieve Documents

You can use the *Documents* tool to retrieve and view the individual documents contained within a bucket, scope, or collection on the database.
The retrieved documents are summarized in a table format, with a row for each retrieved document.
Document retrieval controls at the top of the summary control the retrieval and display of documents.

The *Documents* tool has the following controls:

* *Keyspace*: A set of three related drop-down menus:

** A drop-down menu that displays the name of the bucket whose documents are shown.
You can use the drop-down menu to select from a list of buckets in the current database.

** A drop-down menu that displays the name of the scope whose documents are shown.
The `_default` scope is the default.
You can use the drop-down menu to select from a list of all the scopes within the current bucket.

** A drop-down menu that displays the name of the collection whose documents are shown.
The `_default` collection is the default.
You can use the drop-down menu to select from a list of all the collections within the current scope.

* *Limit*: The maximum number of rows (documents) to retrieve and display at once.

* *Offset*: The number of documents in the entire set of the current bucket that is skipped, before display begins.

* *Document ID*: Accepts the ID value of a specific document.
Leave this field blank to retrieve documents based on *Limit* and *Offset*.

* *show range*: Enables you to enter starting ID and ending ID values to specify a range of ID values.

* *SQL++ WHERE*: Accepts a {sqlpp} query -- specifically, a WHERE clause which determines the subset of documents to show.

To retrieve a set of documents:

. Use the *Keyspace* drop-down menus to specify the location of the documents you want to view.
The set of retrieved documents is automatically updated based on your selections.

. (Optional) Use *Limit*, *Offset*, *Document IT*, or *SQL++ WHERE* to specify a set of documents, then click btn:[Retrieve Docs] to retrieve the documents based on your configuration.

== View and Edit Existing Documents

To view and edit a document:

. <<retrieve-documents,Retrieve>> a set of documents.

. Click on a document name, or click the pencil icon icon:pencil[] next to the document name.

+
Toggle the following tabs:

+
[#json-metadata,cols="1,2",options="header"]
|===

|Tab
|Description

|*Data*
|Comprises a series of key-value pairs sometimes expressed as name-value pairs.
You can make modifications to key-values.

|*Metadata*
|View the document's metadata.

It's not possible to edit a document's metadata as Couchbase Server generates when the document is saved.
For more information, see xref:learn:data/data.adoc#metadata[document metadata].

|===

. Click btn:[Save] to save your changes.

== Create Documents

To create a document:

. Click btn:[Add Document].
. Enter the *Document ID* and edit the *Data* contents of the document.
. Click btn:[Save] to create the document.

== Delete Documents

To delete a document:

. <<retrieve-documents,Retrieve>> the document to display it in the results area.
. Click the Trash icon icon:trash[] next to the document name.
. Click btn:[Delete].

== Related Links

To import a set of JSON documents or a CSV file, see xref:manage:import-documents/import-documents.adoc[].
