[#reference_k2m_fql_ns]
= dcpagg
:page-type: reference

[abstract]
Retrieves statistics that are logically grouped and aggregated together by prefixes.

== Syntax

----
cbstats HOST:11210 dcpagg
----

== Description

This command retrieves statistics that are logically grouped and aggregated together by prefixes.

For example, if all your DCP connections started with the string `xdcr:` or `replication:`, you could use the command [.cmd]`cbstats dcpagg` to request statistics grouped by everything before the first colon character, giving you a set for `xdcr:` statistics and a set for `replication:` statistics.

The following table describes the aggregated DCP statistics.

.Aggregated DCP statistics
[cols="2,3"]
|===
| Name | Description

| `[prefix]:count`
| Number of connections matching this prefix

| `[prefix]:producer_count`
| Total producer connections with this prefix

| `[prefix]:items_sent`
| Total items sent with this prefix

| `[prefix]:items_remaining`
| Total items remaining to be sent with this prefix

| `[prefix]:total_bytes`
| Total number of bytes sent with this prefix

| `[prefix]:total_backlog_size`
| Total backfill items remaining to be sent with this prefix
|===

== Options

None

== Example

The following example shows a request for a set of aggregated DCP statistics:

----
# ./cbstats 10.5.2.54:11210 dcpagg
----

Here's the output from the command:

----
 :total:backoff:                 0
 :total:count:                   6
 :total:items_remaining:         0
 :total:items_sent:              0
 :total:producer_count:          3
 :total:total_backlog_size:      0
 :total:total_bytes:             6630
 replication:backoff:            0
 replication:count:              6
 replication:items_remaining:    0
 replication:items_sent:         0
 replication:producer_count:     3
 replication:total_backlog_size: 0
 replication:total_bytes:        6630
----
