= vbucket-seqno
:page-topic-type: reference

[abstract]
Provides seqno statistics for vBuckets.

== Syntax

Request syntax:

----
cbstats host:11210 [common options] vbucket-seqno [vbid]
----

== Description

This command provides details connected to the sequence number (seqno) for the specified vBucket, or for each vBucket if none is specified.

include::cbstats-vbucket-details.dita[tag=cbstats-vbucket-details/stat_id]

.vBucket seqno statistics
|===
| Name | Description

| `abs_high_seqno`
| The last seqno assigned by this vBucket.

| `high_seqno`
| The last seqno assigned by this vBucket, or in case of replica, the last closed checkpoint's end seqno.

| `last_persisted_seqno`
| The last persisted seqno for the vBucket.

| `purge_seqno`
| The last seqno purged by the compactor.

| `uuid`
| The current vBucket uuid.

| `last_persisted_snap_start`
| The last persisted snapshot start seqno for the vBucket.

| `last_persisted_snap_end`
| The last persisted snapshot end seqno for the vBucket.
|===

== Options

.vbucket-seqno options
[cols="1,2"]
|===
| Option | Description

| [.var]`vbid`
| vBucket ID.
In a standard system this will be between 0 and 1023.
If not provided as part of the command then details for all vBuckets are shown.
|===

For common [.cmd]`cbstats` options, see xref:cbstats-intro.adoc[[.cmd]`cbstats`].

== Example

*Request*

----
cbstats localhost:11210 -u Administrator -p password -b beer-sample vbucket-seqno 1023
----

*Response*

----
 vb_1023:abs_high_seqno:            10
 vb_1023:high_seqno:                10
 vb_1023:last_persisted_seqno:      10
 vb_1023:last_persisted_snap_end:   10
 vb_1023:last_persisted_snap_start: 10
 vb_1023:purge_seqno:               0
 vb_1023:uuid:                      66069026212209
----
