[#cbstats-warmup]
= warmup

[abstract]
Shows statistics related to the node warmup.

== Syntax

The basic syntax is:

----
cbstats [host]:[dataport] -b [bucket_name] -p [bucket_password] raw warmup
----

== Description

If a Couchbase Server node is starting up for the first time, it creates any database files that are necessary and begins serving data immediately.
However, if there is already data on the disk, usually because the node rebooted or the service restarted, the node needs to read all of this data of the disk before it can begin serving data.
This process is called [.term]_warmup_ and it can take some time depending on the size of the data.

The information about server warmup includes the status of warmup and whether warmup is enabled.
The bucket must be specified for the bucket statistics; it does not need to be specified if the default bucket statistics is requested.

The following statistics are of particular interest when monitoring the warmup:

ep_warmup_thread::
The overall indication of whether or not warmup is still running.
Look for values: running and complete.

ep_warmup_state::
This describes which phase of warmup is currently running.
Look for values: loading keys, loading access log, and done.
* When `ep_warmup_state` is loading keys, compare `ep_warmup_key_count` (current number) with `ep_warmup_estimated_key_count` (target number).
* When `ep_warmup_state` is loading access log, compare `ep_warmup_value_count` (current number) with `ep_warmup_estimated_value_count` (target number).

.cbstats warmup stats
[cols="3,4,3"]
|===
| Statistic | Description | Value Type

| ep_warmup
| Shows if warmup is enabled /disabled.
| String values: enabled or disabled

| ep_warmup_dups
| Number of failures due to duplicate keys.
| Integer

| ep_warmup_estimated_key_count
| The estimated number of keys in database.
| Integer.
Default: unknown

| ep_warmup_estimate_time
| Thne estimated time in microseconds to do warmup.
| Integer.

| ep_warmup_estimated_value_count
| The estimated number of key data to read based on the access log.
| Integer.
Default: unknown

| ep_warmup_keys_count
| Number of keys warmed up.
| Integer

| ep_warmup_keys_time
| Total time (in microseconds)  spent by loading persisted keys.
| Integer

| ep_warmup_min_items_threshold
| Enable data traffic after loading this percentage of key data.
| Integer

| ep_warmup_min_memory_threshold
| Enable data traffic after filling this % of memory.
| Integer (%)

| ep_warmup_oom
| Number of out of memory failures during warmup.
| Integer

| ep_warmup_state
| The current state of the warmup thread.
| String

| ep_warmup_thread
| Warmup thread status.
| String values: running or complete

| ep_warmup_time
| Total time spent by loading data (warmup).
| Integer (microseconds)

| ep_warmup_value_count
| Number of values warmed up.
| Integer
|===

== Options

The following are the command options:

.warmup options
[cols="1,3"]
|===
| Option | Description

| `bucket_password`
| The password for the bucket.

| `bucket_name`
| Name of the bucket.
|===

== Example

*Request*

----
cbstats 10.5.2.117:11210 warmup
----

*Response*

Example response:

----
 ep_warmup:                       enabled
 ep_warmup_dups:                  0
 ep_warmup_estimate_time:         57546
 ep_warmup_estimated_key_count:   0
 ep_warmup_estimated_value_count: unknown
 ep_warmup_key_count:             0
 ep_warmup_keys_time:             529022
 ep_warmup_min_items_threshold:    100
 ep_warmup_min_memory_threshold:  100
 ep_warmup_oom:                   0
 ep_warmup_state:                 done
 ep_warmup_thread:                complete
 ep_warmup_time:                  529192
 ep_warmup_value_count:           0
----
