= allocator
:page-topic-type: reference

[abstract]
The `allocator` command, used by `cbstats`, provides memory-related information for a specified bucket.

== Description

The `allocator` command, used by `cbstats`, provides memory-related information for a specified bucket.

== Syntax

----
cbstats host:[port] [common options] allocator
----

The `host` must be the hostname or IP address of a node within the cluster.
The port must be `11210`.
The `common options` must include a username and password, and a reference to a bucket defined on the cluster.
For a complete list of `common options`, see the table provided on the introductory page for xref:cli:cbstats-intro.adoc#common-options[cbstats].

The `allocator` command takes no `command options`.

== Example

The following call returns memory-related information on the `travel-sample` bucket.

----
/opt/couchbase/bin/cbstats -u Administrator -p password \
-b travel-sample 10.143.194.101:11210 \
allocator
----

If successful, the command returns output whose initial section resembles the following.
(Note that the full output is extensive, and features tabular configurations that may require console-width to be manually extended, for the displayed data to be properly reviewed.)

----
___ Begin jemalloc statistics ___
Version: "5.2.1-0-gea6b3e973b477b8061e0076bb257dbd7f3faa756"
Build-time option settings
  config.cache_oblivious: false
  config.debug: false
  config.fill: true
  config.lazy_lock: false
  config.malloc_conf: ""
  config.opt_safety_checks: false
  config.prof: true
  config.prof_libgcc: true
  config.prof_libunwind: false
  config.stats: true
  config.utrace: false
  config.xmalloc: false
Run-time option settings
  opt.abort: false
  opt.abort_conf: false
  opt.confirm_conf: false
  opt.retain: true
  opt.dss: "secondary"
  opt.narenas: 1
  opt.percpu_arena: "disabled"
  opt.oversize_threshold: 8388608
  opt.metadata_thp: "disabled"
  opt.background_thread: true (background_thread: true)
  opt.dirty_decay_ms: 10000 (arenas.dirty_decay_ms: 10000)
  opt.muzzy_decay_ms: 0 (arenas.muzzy_decay_ms: 0)
  opt.lg_extent_max_active_fit: 6
  opt.junk: "false"
  opt.zero: false
  opt.tcache: true
  opt.lg_tcache_max: 15
  opt.thp: "default"
  opt.prof: true
  opt.prof_prefix: "jeprof"
  opt.prof_active: false (prof.active: false)
  opt.prof_thread_active_init: true (prof.thread_active_init: true)
  opt.lg_prof_sample: 19 (prof.lg_sample: 19)
  opt.prof_accum: false
  opt.lg_prof_interval: -1
  opt.prof_gdump: false
  opt.prof_final: false
  opt.prof_leak: false
  opt.stats_print: false
  opt.stats_print_opts: ""
Profiling settings
  prof.thread_active_init: true
  prof.active: false
  prof.gdump: false
  prof.interval: 0
  prof.lg_sample: 19
Arenas: 2
Quantum size: 16
Page size: 4096
Maximum thread-cached size class: 32768
Number of bin size classes: 36
Number of thread-cache bin size classes: 41
Number of large size classes: 196
      .
      .
      .
----
