= checkpoint
:page-type: reference

[abstract]
Provides detailed information on per-vBucket checkpoint data structure.

== Syntax

Request syntax:

----
cbstats host:11210 [common options] checkpoint
----

== Description

This command provides detailed information on per-vBucket checkpoint data structure.

NOTE: Requesting checkpoint stats impacts the performance and should not be used frequently.

The identifier for each vBucket statistic begins with the string `vb_` followed by the vBucket ID and a colon.

.cbstats checkpoint values
[cols="100,219"]
|===
| Stat | Description

| `cursor_name:cursor_checkpoint_id`
| Checkpoint ID at which the cursor [.var]`cursor_name` is pointing now.

| `cursor_name:cursor_seqno`
| The seqno at which the cursor [.var]`cursor_name` is pointing now.

| `cursor_name:num_visits`
| Number of times a batch of items have been drained from a checkpoint of [.var]`cursor_name`.

| `cursor_name:num_items_for_cursor`
| Number of items remaining for the cursor [.var]`cursor_name`.

| `open_checkpoint_id`
| ID of the current open checkpoint.

| `num_conn_cursors`
| Number of referencing DCP cursors.

| `num_checkpoint_items`
| Number of total items in a checkpoint data structure.

| `num_open_checkpoint_items`
| Number of items in the open checkpoint.

| `num_checkpoints`
| Number of checkpoints in a checkpoint data structure.

| `num_items_for_persistence`
| Number of items remaining for persistence.

| `state`
| The state of the vBucket for which this checkpoint contains data.

| `last_closed_checkpoint_id`
| The last closed checkpoint number.

| `persisted_checkpoint_id`
| The last persisted checkpoint number.

| `mem_usage`
| Total memory taken up by items in all checkpoints under given manager.
|===

== Options

There are no options for this command.
For common [.cmd]`cbstats` options, see xref:cbstats-intro.adoc[[.cmd]`cbstats`].

== Example

*Request*

----
cbstats localhost:11210 -u Administrator -p password -b beer-sample checkpoint
----

*Response:*

----
 vb_0:last_closed_checkpoint_id:           4
 vb_0:mem_usage:                           121
 vb_0:num_checkpoint_items:                2
 vb_0:num_checkpoints:                     1
 vb_0:num_conn_cursors:                    1
 vb_0:num_items_for_persistence:           0
 vb_0:num_open_checkpoint_items:           0
 vb_0:open_checkpoint_id:                  5
 vb_0:persisted_checkpoint_id:             4
 vb_0:persistence:cursor_checkpoint_id:    5
 vb_0:persistence:cursor_seqno:            10
 vb_0:persistence:num_visits:              6
 vb_0:state:                               active
 ...
 vb_9:last_closed_checkpoint_id:           3
 vb_9:mem_usage:                           121
 vb_9:num_checkpoint_items:                2
 vb_9:num_checkpoints:                     1
 vb_9:num_conn_cursors:                    1
 vb_9:num_items_for_persistence:           0
 vb_9:num_open_checkpoint_items:           0
 vb_9:open_checkpoint_id:                  4
 vb_9:persisted_checkpoint_id:             3
 vb_9:persistence:cursor_checkpoint_id:    4
 vb_9:persistence:cursor_seqno:            6
 vb_9:persistence:num_visits:              6
 vb_9:state:                               active
----
