= durability-monitor
:page-topic-type: reference

[abstract]
Provides durability statistics in relation to vBuckets.

== Syntax

Request syntax:

----
cbstats host:11210 [common options] durability-monitor [vbid]
----

== Description

This command provides durability statistics for the specified vBucket..

[#stat_id]
The identifier for each vBucket statistic begins with the string `vb_` followed by the vBucket ID and a colon.
For example, for vBucket 1023, the identifier for the `uuid` statistic is `vb_1023:uuid`.

.Durability Monitor
|===
| Name | Description

| `high_prepared_seqno`
| The highest sequence number among the prepared durable writes for the vBucket.
_Prepared_ durable writes are those in progress, and therefore not yet
committed or aborted.
The _highest_ sequence number is that of the durable write that has most recently met its durability requirements on the node for the vBucket.
The durability requirements depend on the durability level specified for the write.

| `last_aborted_seqno`
| The sequence number of the last aborted durable write for the vBucket.

| `last_committed_seqno`
| The sequence number of the last committed durable write for the vBucket.

| `high_completed_seqno`
| The highest sequence number among the completed durable writes for the vBucket.
_Completed_ includes both _aborted_ and _committed_.

| `last_tracked_seqno`
| The sequence number of the last durable write to be tracked for the vBucket.

|===
