= collections
:description: Provides information on collections.
:page-topic-type: reference

[abstract]
{description}

== Syntax

----
cbstats host:11210 [common options] collections
  [ <scope>.<collection> | id <collectionID> ]
----

== Description

Displays information on collections.

== Options

When used without a command-specific option, the `collections` command returns information on all collections for the specified bucket, on the specified node.
If the `<scope>.<collection>` option is used, the command returns information on the collection so specified.
If the `id <collectionID>` option is used, the command returns information on the collection whose id is passed as the `<collectionID>` argument.

For common [.cmd]`cbstats` options, see xref:cli:cbstats-intro.adoc[cbstats].

== Examples

The following command retrieves all collections-related information for the bucket `travel-sample`, on the specified node:

----
/opt/couchbase/bin/cbstats localhost:11210 \
-u Administrator -p password \
-b travel-sample collections
----

The output is as follows:

----
0x0:0x0:collections_mem_used:  20962645
0x0:0x0:data_size:             2820666
0x0:0x0:history:               true
0x0:0x0:items:                 4264
0x0:0x0:name:                  _default
0x0:0x0:ops_delete:            0
0x0:0x0:ops_get:               0
0x0:0x0:ops_store:             31591
0x0:0x0:scope_name:            _default
0x8:0x8:collections_mem_used:  22171
0x8:0x8:data_size:             22598
0x8:0x8:history:               true
0x8:0x8:items:                 4
0x8:0x8:name:                  users
0x8:0x8:ops_delete:            0
0x8:0x8:ops_get:               0
0x8:0x8:ops_store:             40
0x8:0x8:scope_name:            tenant_agent_04
0x8:0x9:collections_mem_used:  0
0x8:0x9:data_size:             21120
0x8:0x9:history:               true
0x8:0x9:items:                 0
0x8:0x9:name:                  bookings
0x8:0x9:ops_delete:            0
0x8:0x9:ops_get:               0
0x8:0x9:ops_store:             0
0x8:0x9:scope_name:            tenant_agent_04
0x9:0xa:collections_mem_used:  17917
0x9:0xa:data_size:             22930
0x9:0xa:history:               true
0x9:0xa:items:                 4
0x9:0xa:name:                  users
0x9:0xa:ops_delete:            0
0x9:0xa:ops_get:               0
0x9:0xa:ops_store:             33
0x9:0xa:scope_name:            tenant_agent_03
0x9:0xb:collections_mem_used:  0
0x9:0xb:data_size:             21120
0x9:0xb:history:               true
0x9:0xb:items:                 0
0x9:0xb:name:                  bookings
0x9:0xb:ops_delete:            0
0x9:0xb:ops_get:               0
0x9:0xb:ops_store:             0
0x9:0xb:scope_name:            tenant_agent_03
0xa:0xc:collections_mem_used:  0
0xa:0xc:data_size:             20680
0xa:0xc:history:               true
0xa:0xc:items:                 0
0xa:0xc:name:                  bookings
0xa:0xc:ops_delete:            0
0xa:0xc:ops_get:               0
0xa:0xc:ops_store:             0
0xa:0xc:scope_name:            tenant_agent_02
0xa:0xd:collections_mem_used:  11248
0xa:0xd:data_size:             22320
0xa:0xd:history:               true
0xa:0xd:items:                 3
0xa:0xd:name:                  users
0xa:0xd:ops_delete:            0
0xa:0xd:ops_get:               0
0xa:0xd:ops_store:             20
0xa:0xd:scope_name:            tenant_agent_02
0xb:0xe:collections_mem_used:  0
0xb:0xe:data_size:             21120
0xb:0xe:history:               true
0xb:0xe:items:                 0
0xb:0xe:name:                  bookings
0xb:0xe:ops_delete:            0
0xb:0xe:ops_get:               0
0xb:0xe:ops_store:             0
0xb:0xe:scope_name:            tenant_agent_01
0xb:0xf:collections_mem_used:  6464
0xb:0xf:data_size:             21207
0xb:0xf:history:               true
0xb:0xf:items:                 1
0xb:0xf:name:                  users
0xb:0xf:ops_delete:            0
0xb:0xf:ops_get:               0
0xb:0xf:ops_store:             11
0xb:0xf:scope_name:            tenant_agent_01
0xc:0x10:collections_mem_used: 0
0xc:0x10:data_size:            20900
0xc:0x10:history:              true
0xc:0x10:items:                0
0xc:0x10:name:                 bookings
0xc:0x10:ops_delete:           0
0xc:0x10:ops_get:              0
0xc:0x10:ops_store:            0
0xc:0x10:scope_name:           tenant_agent_00
0xc:0x11:collections_mem_used: 1195
0xc:0x11:data_size:            20460
0xc:0x11:history:              true
0xc:0x11:items:                0
0xc:0x11:name:                 users
0xc:0x11:ops_delete:           0
0xc:0x11:ops_get:              0
0xc:0x11:ops_store:            2
0xc:0x11:scope_name:           tenant_agent_00
0xd:0x12:collections_mem_used: 13366848
0xd:0x12:data_size:            1808943
0xd:0x12:history:              true
0xd:0x12:items:                3234
0xd:0x12:name:                 route
0xd:0x12:ops_delete:           0
0xd:0x12:ops_get:              0
0xd:0x12:ops_store:            24024
0xd:0x12:scope_name:           inventory
0xd:0x13:collections_mem_used: 35566
0xd:0x13:data_size:            23866
0xd:0x13:history:              true
0xd:0x13:items:                20
0xd:0x13:name:                 airline
0xd:0x13:ops_delete:           0
0xd:0x13:ops_get:              0
0xd:0x13:ops_store:            187
0xd:0x13:scope_name:           inventory
0xd:0x14:collections_mem_used: 523264
0xd:0x14:data_size:            84899
0xd:0x14:history:              true
0xd:0x14:items:                276
0xd:0x14:name:                 airport
0xd:0x14:ops_delete:           0
0xd:0x14:ops_get:              0
0xd:0x14:ops_store:            1968
0xd:0x14:scope_name:           inventory
0xd:0x15:collections_mem_used: 3739332
0xd:0x15:data_size:            578596
0xd:0x15:history:              true
0xd:0x15:items:                126
0xd:0x15:name:                 hotel
0xd:0x15:ops_delete:           0
0xd:0x15:ops_get:              0
0xd:0x15:ops_store:            917
0xd:0x15:scope_name:           inventory
0xd:0x16:collections_mem_used: 3252975
0xd:0x16:data_size:            427301
0xd:0x16:history:              true
0xd:0x16:items:                603
0xd:0x16:name:                 landmark
0xd:0x16:ops_delete:           0
0xd:0x16:ops_get:              0
0xd:0x16:ops_store:            4495
0xd:0x16:scope_name:           inventory
manifest_uid:                  1
----

Each line of the output presents a data _key_.
Each key is of the format `scopeID` &#58; `collectionID` &#58; `datumLabel`.
Each `scopeID` or `collectionID` is a hexadecimal number, prefixed by `0x`.
Each `datumLabel` is a string.
Each data key is concluded with a colon, and the associated value is presented to the right of the colon.

Within the output, each successive group of lines presents information on one of the collections for the specified bucket, on the specified node.

The first collection is identified, on each of the first nine lines, as `0x0:0x0`; and, on line five, as the `&#95;default` collection.

Line one displays, in _bytes_, the total memory used by this collection (here, `20962645`).
Line two displays the total disk space occupied by this collection for the specified bucket, on the specified node: this total (here, `2820666`) is, again, expressed in _bytes_.
Line three indicates whether changes made to documents in the collection are _captured_, so that a historical record is maintained: if the value is `true`, a record is being maintained (note that the value can only be `true` when _Magma_ has been configured as the storage engine for the bucket).
Line four displays the number of items within the collection (here, `4264`).

Lines six to eight display the numbers of deletions, gets, and writes for documents within this collection (which are `0`, `0`, and `31591`, respectively).
The eighth line identifies the scope within which this collection resides: in this case, the scope is the `&#95;default` scope.

Subsequent lines describe other scopes and collections within `travel-sample`.

The `manifest_uid` value (here, `1`) is associated with the current state of collections on the node; and will be incremented whenever a collections-related change is made.

The following command returns information on a collection specified by means of the `<scope>.<collection>` option:

----
/opt/couchbase/bin/cbstats 127.0.0.1:11210 \
-u Administrator -p password \
-b travel-sample collections inventory.airline
----

The output is as follows:

----
0xd:0x13:collections_mem_used: 36012
0xd:0x13:data_size:            126471
0xd:0x13:items:                187
0xd:0x13:name:                 airline
0xd:0x13:ops_delete:           0
0xd:0x13:ops_get:              0
0xd:0x13:ops_store:            0
0xd:0x13:scope_name:           inventory
----

The output, for the `airline` collection, within the `inventory` scope, is thus a subset of that which was returned above, for _all_ collections.

The following command returns information on the same collection, specified by means of the `id <collectionID>` option:

----
/opt/couchbase/bin/cbstats 127.0.0.1:11210 \
-u Administrator -p password \
-b travel-sample collections id 0x13
----

The `id` here specified, `0x13`, was previously identified, in the output for _all_ collections, as that for `airline`.
The output is again as follows:

----
0xd:0x13:collections_mem_used: 36012
0xd:0x13:data_size:            126471
0xd:0x13:items:                187
0xd:0x13:name:                 airline
0xd:0x13:ops_delete:           0
0xd:0x13:ops_get:              0
0xd:0x13:ops_store:            0
0xd:0x13:scope_name:           inventory
----

== See Also

For an overview of scopes and collections, see xref:learn:data/scopes-and-collections.adoc[Scopes and Collections].

For a step-by-step explanation of creating scopes and collections with the CLI, see xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc#manage-scopes-and-collections-with-the-cli[Manage Scopes and Collections with the CLI].
For a comparable explanation with the REST API, see xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc#manage-scopes-and-collections-with-the-rest-api[Manage Scopes and Collections with the REST API].

To use `cbstats` to provide further details on collections, see the reference page for the
xref:cli:cbstats/cbstats-collections-details.adoc[collections-details] command.
