[#cbstats-vbucket]
= vbucket

[abstract]
Provides detailed statistics on a per vbucket granularity.

== Syntax

Request syntax for vBucket:

----
cbstats [host]:11210 vbucket
cbstats [host]:11210 vbucket-details [vbid]
cbstats [host]:11210 vbucket-seqno [vbid]
----

These commands are used as follows:

* [.cmd]`vbucket`: Lists all available vBuckets and provides information about their type: active, replica, pending or dead.
* [.cmd]`vbucket-details`: Uses the option `vbid`  to provide statistics for a specific vBucket.
* [.cmd]`vbucket-seqno`: Uses the option `vbid` to provide details connected to the vBucket's sequence number.

== Description

The [.cmd]`vbucket` command shows whether a vBucket is an active, replica, pending or dead vBucket.

.Notable vBucket-details stats
[cols="100,217"]
|===
| Stat | Description

| `db_data_size`
| Total size of useful data in the database file on disk, measured in bytes.

| `db_file_size`
| Total size of the database file on disk (including un-compacted stale data), measured in bytes.

| `drift_ahead_threshold`
| Threshold at which positive drift will trigger an update to drift_ahead_exceeded, measured in nanoseconds.

| `drift_ahead_threshold_exceeded`
| How many mutations have been observed with a drift above the drift_ahead_threshold.

| `drift_behind_threshold`
| The threshold at which positive drift will trigger an update to drift_behind_exceeded.
The value is displayed in nanoseconds as a positive value, but is converted to a negative value for actual exception checks.

| `drift_behind_threshold_exceeded`
| How many mutations have been observed with a drift below the drift_behind_threshold.

| `logical_clock_ticks`
| How many times the hybrid logical clock has had to increment the logical clock.

| `max_cas_str`
| The vBucket’s current maximum hybrid logical clock timestamp.
In general, this statistic shows the value issued to the last mutation or in certain cases the largest timestamp the vBucket has received (when the received timestamp is ahead of the local clock).
Displayed as a human readable ISO-8601 timestamp (UTC).

| `num_items`
| Total number of items in the vbucket.

| `num_non_resident`
| Total number of items which are not resident in memory for this vbucket.

| `total_abs_drift`
| Accumulated drift observed by the vBucket.
Drift is always accumulated as an absolute value.

| `total_abs_drift_count`
| How many updates have been applied to total_abs_drift, for the purpose of average or rate calculations.
|===

== Options

.vbucket options
[cols="1,2"]
|===
| Option | Description

| `vbid`
| vBucket ID (in a standard system this will be between 0 and 1023).
If not provided as part of the command then details for all vBuckets are shown.
|===

== Examples

*Requests*

----
cbstats 192.0.2.1:11210 vbucket
----

----
cbstats 192.0.2.1:11210 vbucket-details 115
----

----
cbstats 192.0.2.1:11210 vbucket-seqno 115
----

*Responses*

Example response for `vbucket`:

----
 vb_0:    replica
 vb_1:    replica
 vb_10:   replica
 vb_100:  active
 vb_1000: replica
 vb_1001: replica
 vb_1002: replica
 vb_1003: replica
 vb_1004: replica
 vb_1005: replica
 ...
----

Example response for `vbucket-details 115`:

----
 vb_115:                                 active
 vb_115:bloom_filter:                    ENABLED
 vb_115:bloom_filter_key_count:          0
 vb_115:bloom_filter_size:               95851
 vb_115:db_data_size:                    28473
 vb_115:db_file_size:                    98395
 vb_115:drift_ahead_threshold:           5000000000
 vb_115:drift_ahead_threshold_exceeded:  0
 vb_115:drift_behind_threshold:          5000000000
 vb_115:drift_behind_threshold_exceeded: 0
 vb_115:high_seqno:                      31
 vb_115:ht_cache_size:                   44546
 vb_115:ht_item_memory:                  44546
 vb_115:ht_memory:                       26656
 vb_115:logical_clock_ticks:             9
 vb_115:max_cas:                         1484657322073980930
 vb_115:max_cas_str:                     2017-01-17T12:48:42.73980930
 vb_115:num_ejects:                      4
 vb_115:num_items:                       31
 vb_115:num_non_resident:                4
 vb_115:num_temp_items:                  0
 vb_115:ops_create:                      31
 vb_115:ops_delete:                      0
 vb_115:ops_reject:                      0
 vb_115:ops_update:                      0
 vb_115:pending_writes:                  0
 vb_115:purge_seqno:                     0
 vb_115:queue_age:                       0
 vb_115:queue_drain:                     32
 vb_115:queue_fill:                      32
 vb_115:queue_memory:                    0
 vb_115:queue_size:                      0
 vb_115:rollback_item_count:             0
 vb_115:total_abs_drift:                 0
 vb_115:total_abs_drift_count:           0
 vb_115:uuid:                            265143847629643
----

Example response for `vbucket-seqno 115`:

----
 vb_115:abs_high_seqno:            31
 vb_115:high_seqno:                31
 vb_115:last_persisted_seqno:      31
 vb_115:last_persisted_snap_end:   31
 vb_115:last_persisted_snap_start: 31
 vb_115:purge_seqno:               0
 vb_115:uuid:                      265143847629643
----
