[#cbstats-timing]
= [.cmd]`timings`

[abstract]
Provides timing statistics.

== Syntax

The request syntax:

----
cbstats [host]:[dataport] timings
----

== Description

The timing stats provide histogram data from high-resolution timers over various operations within the system.

== Options

None

== Example

The following example, uses the 10.5.2.117 host and the default port, 11210:

----
cbstats 10.5.2.117:11210 timings
----

*Response*

The following is sample output from `cbstats timings`:

----
disk_commit (1024 total)
    0 - 1s : (100.00%) 1024 ###################################################
    Avg    : (     1s)
 get_stats_cmd (30663276 total)
    0 - 1us       : (  0.05%)    14827 
    1us - 2us     : (  6.56%)  1995778 ##
    2us - 4us     : ( 41.79%) 10804626 ##############
    4us - 8us     : ( 45.20%)  1044043 #
    8us - 16us    : ( 45.49%)    89929 
    16us - 32us   : ( 45.90%)   124472 
    32us - 64us   : ( 46.38%)   148935 
    64us - 128us  : ( 56.17%)  2999690 ###
    128us - 256us : ( 68.57%)  3804009 ####
    256us - 512us : ( 69.91%)   411281 
    512us - 1ms   : ( 78.77%)  2717402 ###
    1ms - 2ms     : ( 96.36%)  5391526 #######
    2ms - 4ms     : ( 99.05%)   826345 #
    4ms - 8ms     : ( 99.96%)   278727 
    8ms - 16ms    : (100.00%)    11443 
    16ms - 32ms   : (100.00%)      217 
    32ms - 65ms   : (100.00%)       19 
    65ms - 131ms  : (100.00%)        7 
    Avg           : (  347us)
 disk_vbstate_snapshot (93280 total)
    32us - 64us   : ( 15.34%) 14308 ######
    64us - 128us  : ( 74.74%) 55413 #########################
    128us - 256us : ( 91.39%) 15532 #######
    256us - 512us : ( 95.69%)  4007 #
    512us - 1ms   : ( 99.49%)  3546 #
    1ms - 2ms     : ( 99.95%)   423 
    2ms - 4ms     : ( 99.99%)    43 
    4ms - 8ms     : (100.00%)     4 
    2s - 4s       : (100.00%)     4 
    Avg           : (  190us)
 notify_io (4 total)
    4us - 8us   : ( 25.00%) 1 ############
    16us - 32us : ( 75.00%) 2 ########################
    32us - 64us : (100.00%) 1 ############
    Avg         : (   17us)
----

The following are the possible return values, which depend on what occurred on the data bucket:

.Return values
[cols="1,3"]
|===
| Values | Description

| `bg_load`
| Background fetches waiting for disk

| `bg_wait`
| Background fetches waiting in the dispatcher queue

| `data_age`
| Age of data written to disk

| `disk_commit`
| Time waiting for a commit after a batch of updates

| `disk_del`
| Wait for disk to delete an item

| `disk_insert`
| Wait for disk to store a new item

| `disk_vbstate_snapshot`
| Time spent persisting vbucket state changes

| `disk_update`
| Wait time for disk to modify an existing item

| `get_cmd`
| Servicing get requests

| `get_stats_cmd`
| Servicing get_stats requests

| `set_vb_cmd`
| Servicing vbucket set state commands

| `item_alloc_sizes`
| Item allocation size counters (in bytes)

| `notify_io`
| Time for waking blocked connections

| `storage_age`
| Time since most recently persisted item was initially queued for storage.

| `tap_mutation`
| Time spent servicing tap mutations
|===
