= collections
:page-topic-type: reference

[abstract]
Provides information on collections.

== Syntax

----
cbstats host:11210 [common options] collections <scope.collection | id collectionID>
----

== Description

Displays information on collections.

== Options

When specified without a command-specific option, the command returns information on all collections for the specified bucket, on the specified node.
If the `scope.collection` option is used, the command returns information on the collection specified by means of the stated path.
If the `id collectionID` option is used, the command returns information on the collection whose name is specified by `collectionID`, and whose id is specified by `id`.

For common [.cmd]`cbstats` options, see xref:cli:cbstats-intro.adoc[cbstats].

== Examples

The following command retrieves all collections-related information on the bucket `travel-sample`, on the specified node:

----
/opt/couchbase/bin/cbstats localhost:11210 \
-u Administrator -p password \
-b travel-sample collections
----

The output is as follows:

----
0x0:0x0:disk_size:  19827828
0x0:0x0:items:      31592
0x0:0x0:mem_used:   21760360
0x0:0x0:name:       _default
0x0:0x0:ops_delete: 0
0x0:0x0:ops_get:    0
0x0:0x0:ops_store:  1
0x0:0x0:scope_name: _default
0x8:0x9:disk_size:  68762
0x8:0x9:items:      2
0x8:0x9:mem_used:   291
0x8:0x9:name:       MyCollection
0x8:0x9:ops_delete: 0
0x8:0x9:ops_get:    2
0x8:0x9:ops_store:  2
0x8:0x9:scope_name: MyScope
manifest_uid:       4
----

Each line of the output presents a data _key_.
Each key is of the format `scopeID` &#58; `collectionID` &#58; `datumLabel`.
Each `scopeID` or `collectionID` is a hexadecimal number, prefixed by `0x`.
Each `datumLabel` is a string.
Each data key is concluded with a colon, and the associated value is presented to the right of the colon.

Within the output, each group of eight lines presents information on one of the collections for the specified bucket, on the specified node.

The first collection is identified as `0x0:0x0`, and is identified (on line four) as the `&#95;default` collection.
Line one of the output displays the total disk space occupied by this collection for the specified bucket, on the specified node: this total (here, `19827828`) is expressed in _bytes_.
The second line displays the number of items within the collection.
The third line displays, again in _bytes_, the total memory used by this collections (here, `21760360`).
The subsequent three lines display the numbers of deletions, gets, and writes for documents within this collection.
The eighth line identifies the scope within which this collection resides: in this case, the scope is the `&#95;default` scope.

The second collection is identified as `0x8:0x9`, named `MyCollection`.
It is shown to occupy `68762` bytes of disk space, and `291` bytes of memory.
It resides within the scope `MyScope`, and has currently experienced zero deletions, two gets, and two writes.

(Note that the `_default` collection is indeed provided by default, within the `_default` scope, for every Couchbase or Ephemeral bucket.
The collection `MyCollection` is one that has been custom-created by the administrator, and does not appear in the sample bucket `travel-sample` by default.)

The `manifest_uid` here associated with the current state will be incremented whenever a change is made to collections on the current node.

The following command returns information on a collection specified by means of the `scope.collection` option:

----
/opt/couchbase/bin/cbstats 127.0.0.1:11210 \
-u Administrator -p password \
-b travel-sample collections MyScope.MyCollection
----

The output is as follows:

----
0x8:0x9:disk_size:  68762
0x8:0x9:items:      2
0x8:0x9:mem_used:   291
0x8:0x9:name:       MyCollection
0x8:0x9:ops_delete: 0
0x8:0x9:ops_get:    2
0x8:0x9:ops_store:  2
0x8:0x9:scope_name: MyScope
----

The output is thus the targeted subset of that which was returned above, for _all_ collections.

The following command returns information on the same collection, specified by means of the `id collectionID` option:

----
/opt/couchbase/bin/cbstats 127.0.0.1:11210 \
-u Administrator -p password \
-b travel-sample collections id 0x9
----

The `id` specified is thus `0x9`, already identified in the output for all collections as the id for `MyCollection`.
The output is as follows:

----
0x8:0x9:disk_size:  68762
0x8:0x9:items:      2
0x8:0x9:mem_used:   291
0x8:0x9:name:       MyCollection
0x8:0x9:ops_delete: 0
0x8:0x9:ops_get:    2
0x8:0x9:ops_store:  2
0x8:0x9:scope_name: MyScope
----

== See Also

For an overview of scopes and collections, see xref:learn:data/scopes-and-collections.adoc[Scopes and Collections].

For a step-by-step explanation of creating scopes and collections with the CLI, see xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc#manage-scopes-and-collections-with-the-cli[Manage Scopes and Collections with the CLI].
For a comparable explanation with the REST API, see xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc#manage-scopes-and-collections-with-the-rest-api[Manage Scopes and Collections with the REST API].

To use `cbstats` to provide further details on collections, see the reference page for the
xref:cli:cbstats/cbstats-collections-details.adoc[collections-details] command.
