= collections-details
:page-topic-type: reference
:page-status: Developer Preview

[abstract]
Provides low-level details on collections.

== Syntax

----
cbstats host:11210 [common options] collections-details [vbucket-reference]
----

== Description

This command is used to provide low-level details on collections, for a specified bucket.
This includes details identifying the existing collections; and vBucket-specific details, which include sequence numbers and item counts.

== Options

The optional `vbucket-reference` parameter is an integer, in the range of `0` to `1023` inclusive, specifying a particular vBucket.
If a vBucket is specified, the only details returned are the vBucket-specific details for that vBucket.
If no vBucket is specified, vBucket-specific details for all vBuckets are returned, as well as details identifying the existing collections for the bucket.

For common [.cmd]`cbstats` options, see xref:cli:cbstats-intro.adoc[cbstats].

== Examples

The following command retrieves collections-details on all vBuckets for `travel-sample`:

----
/opt/couchbase/bin/cbstats -u Administrator -p password -b travel-sample \
localhost:11210 collections-details
----

The initial section of the output is as follows:

----
0x0:0x0:name:                     _default
0x8:0x9:name:                     MyCollection
manifest_uid:                     4
vb_0:0x0:high_seqno:              38
vb_0:0x0:items:                   38
vb_0:0x0:persisted_high_seqno:    38
vb_0:0x0:scope:                   0x0
vb_0:0x0:start_seqno:             0
vb_0:0x9:high_seqno:              41
vb_0:0x9:items:                   0
vb_0:0x9:persisted_high_seqno:    41
vb_0:0x9:scope:                   0x8
vb_0:0x9:start_seqno:             41
vb_0:collections:                 2
vb_0:manifest:uid:                4
vb_1:0x0:high_seqno:              29
vb_1:0x0:items:                   29
vb_1:0x0:persisted_high_seqno:    29
      .
      .
      .
----

Each line of the output presents a data _key_.
Each key is of the format `scopeID` &#58; `collectionID` &#58; `datumLabel`.
Each `scopeID` or `collectionID` is a hexadecimal number, prefixed by `0x`.
Each `datumLabel` is a string.
Each data key is concluded with a colon, and the associated value is presented to the right of the colon.

The initial two lines provide information that identifies existing collections.
Two are listed, which are the `_default` collection, and `MyCollection`.
Each is identified with hexadecimal numbers: the `_default` collection is identified as `0x0` (residing within scope `0x0`); and `MyCollection` as `0x9` (residing in scope `0x8`).

(Note that the `_default` collection is indeed provided by default, within the `_default` scope, for every Couchbase or Ephemeral bucket.
The collection `MyCollection` is one that has been custom-created by the administrator, and does not appear in the sample bucket `travel-sample` by default.)

The `manifest_uid` here associated with the current state will be incremented whenever a change is made to collections on the current node.

Subsequent information in the output relates to each vBucket corresponding to `travel-sample`, on the current node.
The vBuckets are numbered, from `0` to `1023`.
For each vBucket, information is provided on sequence numbers and total items.

The following command specifies a `vbucket-reference`, thereby returning information on the specified vBucket only:

----
/opt/couchbase/bin/cbstats -u Administrator -p password \
-b travel-sample localhost:11210 collections-details 8
----

Details for vBucket `8` are duly returned:

----
vb_8:0x0:high_seqno:           26
vb_8:0x0:items:                26
vb_8:0x0:persisted_high_seqno: 26
vb_8:0x0:scope:                0x0
vb_8:0x0:start_seqno:          0
vb_8:0x9:high_seqno:           29
vb_8:0x9:items:                0
vb_8:0x9:persisted_high_seqno: 29
vb_8:0x9:scope:                0x8
vb_8:0x9:start_seqno:          29
vb_8:collections:              2
vb_8:manifest:uid:             4
----

== See Also

For an overview of scopes and collections, see xref:learn:data/scopes-and-collections.adoc[Scopes and Collections].

For a step-by-step explanation of creating scopes and collections with the CLI, see xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc#manage-scopes-and-collections-with-the-cli[Manage Scopes and Collections with the CLI].
For a comparable explanation with the REST API, see xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc#manage-scopes-and-collections-with-the-rest-api[Manage Scopes and Collections with the REST API].

To use `cbstats` to provide higher-level information on collections, see the reference page for the xref:cli:cbstats/cbstats-collections.adoc[collections] command.
