= Installing the Couchbase Python SDK
:description: pass:q[In this tutorial, you're going to create a skeleton application for interacting with the student database you created in xref:install-couchbase-server.adoc[]]
:page-pagination: full

include::partial$tutorial-globals.adoc[]

[abstract]
{description}

== Prerequisites

Before you begin, you will need Python Version {minimum-python-version} installed on your machine.
If you don't have a Python installed (or you have version 2 or less) then you will have to install Python3

For further information on installing Python, take a look at xref:python-sdk:hello-world:start-using-sdk.adoc[Install and Start Using the Python SDK with Couchbase Server].

NOTE: xref:python-sdk:hello-world:start-using-sdk.adoc[Install and Start Using the Python SDK with Couchbase Server] will also show you how to install the Couchbase SDK.

== Install the Couchbase Python SDK
If you have not already done so, then you can install the Couchbase Python SDK by running the following command inside a terminal window:
