= Developer Preview

[abstract]
The _Developer Preview_, available with Couchbase Server Enterprise Edition 6.5 Beta, allows developers to experiment with early versions of forthcoming Couchbase technology.
Pre-release documentation is provided here, in a temporary location, for purposes of test and development.

[#collections]
== Collections

The Developer Preview includes _collections_.
These are data containers that can be created within any bucket whose type is either _Couchbase_ or _Ephemeral_.
This allows data-items optionally to be assigned to different collections according to content-type.

For the Developer Preview, collections can be managed by either the _REST API_ or the _CLI_.
For more information, see xref:developer-preview/collections/collections-overview.adoc[Collections Overview].

[#enter-dp]
== Enter Developer Preview Mode

Developer Preview Mode can be entered by means of a command-line interface.
Note that Developer Preview _cannot be disabled, once it is enabled_.
If you do enter Developer Preview Mode, you will not be able to upgrade.
Under no circumstances should Developer Preview Mode be used in a production environment.

To enter Developer Preview Mode, follow the instructions below.
Note that the instructions assume a Ubuntu Linux environment: however, they should work on any Ubuntu or recent Windows system.
For the appropriate command-paths, see xref:cli:cli-intro.adoc[CLI Reference].

[#test-for-dp]
=== Test for Developer Preview Mode Enablement

To test whether Developer Preview Mode has been enabled, enter the `enable-developer-preview` command at the command line, using the `--list` flag, and specifying the cluster-address, and the Full Administrator username and password:

----
/opt/couchbase/bin/couchbase-cli enable-developer-preview \
--list -c localhost:8091 -u Administrator -p password
----

If the cluster is not in Developer Preview Mode, the following output is displayed:

----
Cluster is NOT in developer preview mode
----

If the cluster _is_ in Developer Preview Mode, the output is as follows:

----
Cluster is in developer preview mode
----

[#switch-on-dp]
=== Enter Developer Preview Mode

To enter Developer Preview Mode, enter the `enable-developer-preview` command at the command line, using the `--enable` flag, and specifying the cluster-address, and the Full Administrator username and password:

----
/opt/couchbase/bin/couchbase-cli enable-developer-preview \
--enable -c localhost:8091 -u Administrator -p password
----

The following notification and prompt are provided:

----
Developer preview cannot be disabled once it is enabled. If you enter developer preview mode you will not be able to upgrade. DO NOT USE IN PRODUCTION.
Are you sure [y/n]:
----

To enter Developer Preview Mode, enter `y` against the prompt, and hit return:

----
Are you sure [y/n]: y
----

The following confirmation is now displayed:

----
SUCCESS: Cluster is in developer preview mode
----

You may now use the feature provided with the Developer Preview.
To use _Collections_, see the xref:introduction:developer-preview/collections/collections-overview.adoc[Collections Overview].
