////
Contains the diagrams used in the JavasScript UDF section
////

// tag::inline-call-sequence[]
[plantuml]
....
@startuml
 
 actor Dev
 participant JSEngine
 participant QueryEngine
 database Bucket
 
 Dev ->> JSEngine: JS: var q = select …
 activate JSEngine
 JSEngine ->> QueryEngine : N1QL(…) call
 activate QueryEngine
 QueryEngine ->> JSEngine  : return query
 deactivate QueryEngine
 JSEngine ->> Dev : return q
 deactivate JSEngine

    loop Every document in q
      Dev ->> JSEngine   : operate on document
      JSEngine ->> QueryEngine ++ : get document
      QueryEngine ->> Bucket ++ : get document
      Bucket ->> QueryEngine -- : retrieved document
      QueryEngine ->> JSEngine -- : retrieved document
    end
@enduml
....
// end::inline-call-sequence[]

// tag::transactions-and-iterators[]
[plantuml]
....
@startuml


start

:start transaction;
note right: Transaction started before the initial\nN1QL statement is called
: var q = execute N1QL statement;
 
 while (next q?) is (yes)
 
   : process q;
   
 endwhile (no)
 
:commit or rollback;

stop

@enduml
....
// end::transactions-and-iterators[]


// tag::data-transformation[]
[plantuml]
....
@startuml

skinparam componentStyle rectangle

left to right direction

[Run N1QL statement] --> [Transform JSON data] : {item1, item2, item3}
[Transform JSON data] -->  return  : {item1, item3}

@enduml
....
// end::data-transformation[]

// tag::udf-scopes-diagram[]
.Scopes for JavaScript Libraries
[plantuml#scopes-for-udf]
----
@startuml
allow_mixing

skinparam actorStyle Awesome

component "getBusinessDays(...)" <<Reference function>> as referenceFunction 

frame "my-library" as MyLibrary {
   file "getBusinessDays(startDate, \nendDate)" as getBusinessDays

}

referenceFunction ---> getBusinessDays 
actor "user" as user

node "Couchbase cluster" as cluster

database "travel-sample" as bucket

node "inventory" <<scope>> as inventory
node "tenant" <<scope>> as tenant

cluster -- bucket
bucket -- inventory
bucket -- tenant

inventory --- MyLibrary : my-library in inventory scope

user ---right---> referenceFunction

note top of user #Ivory
  can access the getBusinessDays function
  as long as s/he is working 
  inside the '"Inventory Scope" context
end note



@enduml
----
// end::udf-scopes-diagram[]

// tag::banking-scope-scenario[]
.Using Multipe Scopes
[plantuml#banking-scope-scenario]
----
@startuml

allow_mixing
skinparam actorStyle Awesome


actor "US\nUser" as USUser
actor "UK\nUser" as UKUser


database "Banking\nDatabase" as bankingDatabase {

    node "UK Bank Scope" as UKBankScope {
    
      frame "bank-library" as UKLibrary {
        file "getInterestInSterling(termInYears, rate)" as interestInSterling
      } 
    }
    
    node "US Bank Scope" as USBankScope {
    
    frame "bank-library" as USLibrary {
      file "getInterestInDollars(termInYears, rate)" as interestInDollars
      }
    }
    
}


component "GetInterest(...)" <<Reference Function>> as UKReferenceFunction
component "GetInterest(...)" <<Reference Function>> as USReferenceFunction


UKReferenceFunction --> interestInSterling : references
UKUser --> UKReferenceFunction

USReferenceFunction --> interestInDollars : references
USUser --> USReferenceFunction

note left of UKUser #Ivory
  **UK** User is logged on with
  the BankingDatabase.**UKBank**
  context scope
end note

note right of USUser #Ivory
  **US** User is logged on with
  the BankingDatabase.**USBank**
  context scope
end note

note as referenceFunctionNote #Ivory
  Two reference functions with the same name,
  but pointing at different JavaScript functions 
  in different libraries in different scopes.
end note

referenceFunctionNote .. UKReferenceFunction
referenceFunctionNote .. USReferenceFunction

@enduml
----
// end::banking-scope-scenario[]