////
Contains the diagrams used in the JavasScript UDF section
////

// tag::inline-call-sequence[]
[plantuml]
....
@startuml
 
 actor Dev
 participant JSEngine
 participant QueryEngine
 database Bucket
 
 Dev ->> JSEngine: JS: var q = select …
 activate JSEngine
 JSEngine ->> QueryEngine : N1QL(…) call
 activate QueryEngine
 QueryEngine ->> JSEngine  : return query
 deactivate QueryEngine
 JSEngine ->> Dev : return q
 deactivate JSEngine

    loop Every document in q
      Dev ->> JSEngine   : operate on document
      JSEngine ->> QueryEngine ++ : get document
      QueryEngine ->> Bucket ++ : get document
      Bucket ->> QueryEngine -- : retrieved document
      QueryEngine ->> JSEngine -- : retrieved document
    end
@enduml
....
// end::inline-call-sequence[]

// tag::transactions-and-iterators[]
[plantuml]
....
@startuml


start

:start transaction;
note right: Transaction started before the initial\nN1QL statement is called
: var q = execute N1QL statement;
 
 while (next q?) is (yes)
 
   : process q;
   
 endwhile (no)
 
:commit or rollback;

stop

@enduml
....
// end::transactions-and-iterators[]


// tag::data-transformation[]
[plantuml]
....
@startuml

skinparam componentStyle rectangle

left to right direction

[Run N1QL statement] --> [Transform JSON data] : {item1, item2, item3}
[Transform JSON data] -->  return  : {item1, item3}

@enduml
....
// end::data-transformation[]

// tag::udf-scopes-diagram[]
.Scopes for JavaScript Libraries
[plantuml#scopes-for-udf]
----
@startuml
allow_mixing

left to right direction
skinparam actorStyle Awesome
skinparam linetype polyline
skinparam linetype ortho

component "getBusinessDays(...)" <<N1QL User-Defined Function>> as n1qlUDFunction 

  frame "my-library" as MyLibrary {
  
   file "getBusinessDays(startDate, \nendDate)" as getBusinessDays

  }

note right of MyLibrary #Ivory 
  The library can reside at the
  cluster level or the scope level
end note

n1qlUDFunction --> getBusinessDays 
actor "user" as user

cloud "Couchbase cluster" as cluster

node "scope" as scope

scope <.. MyLibrary

cluster <.. MyLibrary

user --> n1qlUDFunction

note top of user #Ivory
  can access the getBusinessDays function
  as long as s/he is working 
  inside the '"Scope" context
end note

@enduml
----
// end::udf-scopes-diagram[]

// tag::banking-scope-scenario[]
.Using Multipe Scopes
[plantuml#banking-scope-scenario]
----
@startuml

allow_mixing
skinparam actorStyle Awesome


actor "US\nUser" as USUser
actor "UK\nUser" as UKUser


database "Banking\nDatabase" as bankingDatabase {

    node "UK Bank Scope" as UKBankScope {
    
      frame "bank-library" as UKLibrary {
        file "getInterestInSterling(termInYears, rate)" as interestInSterling
      } 
    }
    
    node "US Bank Scope" as USBankScope {
    
    frame "bank-library" as USLibrary {
      file "getInterestInDollars(termInYears, rate)" as interestInDollars
      }
    }
    
}


component "GetInterest(...)" <<N1QL User-Defined Function>> as UKReferenceFunction
component "GetInterest(...)" <<N1QL User-Defined Function>> as USReferenceFunction


UKReferenceFunction --> interestInSterling : references
UKUser --> UKReferenceFunction

USReferenceFunction --> interestInDollars : references
USUser --> USReferenceFunction

note left of UKUser #Ivory
  **UK** User is logged on with
  the BankingDatabase.**UKBank**
  context scope
end note

note right of USUser #Ivory
  **US** User is logged on with
  the BankingDatabase.**USBank**
  context scope
end note

note as referenceFunctionNote #Ivory
  Two N1QL User-Defined Functions with the same name,
  but pointing at different JavaScript functions 
  in different libraries in different scopes.
end note

referenceFunctionNote .. UKReferenceFunction
referenceFunctionNote .. USReferenceFunction

@enduml
----
// end::banking-scope-scenario[]

// tag::javascript-scopes[]
.Javascript UDFs Structure
[plantuml#javascript-scopes]
....
@startuml

frame Cluster {

    frame "global library" as globalLibrary #white {
    
        component function3 #Ivory [
                        
function globalUKHoliday(... args) {
    ...       
}
        
        ]
    
        component function4 #Ivory [
                        
function globalUSHoliday(... args) {
    ...       
}
        
        ]
    }

    database "Bucket" {
        
        node "Scope" #White {
          
            frame "my-library" #White {
                    
             component function1 #Ivory [
                            
function add(x, y) {
    ...       
}
            
            ]
                   
        }     
    }
}

@enduml
....
// end::javascript-scopes[]
