////
The libraries and scope section can be reused in the guides section
////
[#libraries-and-scopes]
= Libraries and Scopes

JavaScript functions are stored inside a `library`. 
A library can contain one or more functions, and can also be assigned to a `scope` which allows for a libraries to partitioned for logical grouping. 

// tag::scoping-diagram[]
include::partial$diagrams.adoc[tags=javascript-scopes]

As shown in xref:javascript-scopes[xrefstyle=short], a JavaScript function library can exist as:

* A global library accessible across the cluster.
* A library (`bucket-library`) that is available to anyone with access the bucket.
* The library `my-library` lives within the `Bucket.Scope`, so can only be accessed by users with access rights to that scope.
// end::scoping-diagram[]

NOTE: You can find an introduction to scopes in our xref:tutorials:buckets-scopes-and-collections.adoc#scopes_and_collections[Couchbase Tutorials]

Furthermore, access restrictions can be applied to scopes, so that only certain groups of users will be able to access collections and libraries within that scope.

include::partial$diagrams.adoc[tags=udf-scopes-diagram]

The user does not call the JavaScript functions (shown here as `getBusinessDays(startDate, endDate)`) directly; a *N1QL User-Defined Function* is defined to act a reference caller to the JavaScript function. 
This makes it possible to define multiple entry points to the same JavaScript function, allowing for the same function to be supplied with different parameter lists. 
(For more information on variable parameter lists, see xref:javascript-udfs:calling-javascript-from-n1ql.adoc#variadic-parameters[Calling N1QL from JavaScript]) 

NOTE: In Couchbase terminology, you would set the user's `context` to `travel-sample.inventory` in order for him/her to run the functions in `my-library`. 