[#concept_bf4_glh_ht]
= Atomic Counters

[abstract]
You can atomically increment or decrement the numerical value of special counter documents

== #Anonymous Section#

----
counter(docid, value)
counter(docid, -value)
----

----
>>> cb.counter('counter_id', delta=20, initial=100).value
100L
>>> cb.counter('counter_id', delta=1).value
101L
>>> cb.counter('counter_id', delta=-50).value
51L
----

Once created, the counter can be incremented or decremented atomically by a given amount or _delta_.
Specifying a positive delta increments the value and specifying a negative one decrements it.
When a counter operation is complete, the application receives the current value of the counter, after the increment.

Couchbase counters are 64-bit unsigned integers in Couchbase, and do not wrap around if decremented beyond 0, however they will wrap around if incremented past their maximum value (which is the maximum value contained within a 64 bit integer).
Many SDKs will limit the _delta_ argument to the value of a _signed_ 64 bit integer.

xref:expiry.adoc#concept_o53_kps_zs[Expiration] times can also be specified when using counter operations.

xref:cas-concurrency.adoc#concept_iq4_bts_zs[CAS] values are not used with counter operations since counter operations are atomic.
The intent of the counter operation is to simply increment the current server-side value of the document.
If you wish to only increment the document if it is at a certain value, then you may use a normal [.api]`upsert` function with CAS:

[source,python]
----
rv = cb.get('counter_id')
value, cas = rv.value, rv.cas
if should_increment_value(value):
  cb.upsert('counter_id', value + increment_amount, cas=cas)
----

== Counter in other SDKs
