[#concept_cgn_flg_lt]
= Enhanced Durability

[abstract]
Couchbase 4.0 offers additional durability options which provide clearer semantics in the face of failover.

Prior to Couchbase 4.0, durability was only implemented using the xref:cas-concurrency.adoc#concept_iq4_bts_zs[CAS].
Since the CAS changed for each mutation, a client could normally determine if the mutation was persisted on a given node if the item existed on the node with the same CAS.

The core issue with CAS-based checking is that a different CAS on a replica may either be a result of:

[#ul_wf2_ylg_lt]
* Client contention: The CAS is different from the current mutation because it been changed by a subsequent mutation (one performed _after_ our current client)
* Slow propagation: The mutation has not yet been propagated to all replicas
* Failover: The CAS has changed because the master was failed over and control has been transferred to a replica which is using an older copy.

== Sequence number based durability

[#ul_cff_vmg_lt]
* A random identifier representing (called a [.underline]#UUID#) the current cluster state.
This state is changed whenever something happens to the cluster (for example, a failover).
* A counter value which is associated with the current state.

Applications may enable this extra sequence data to be sent for each mutation response.
This data is then transparently used by the SDK to use sequence number-based durability checking.

Unlike CAS-based polling, it is simple to distinguish various failure cases:

[#ul_jvy_kng_lt]
* If the _UUID_ is equal, but the sequence number is lower than the expected value, then it means the mutation has not yet been propagated.
* If the UUID is equal, and the sequence number is greater or equal to the current mutation, it means the current mutation has been propagated.
* If the UUID is different than the one available at the client, it means the mutation has been lost.

== Enabling enhanced durability via the SDK

----
from couchbase.bucket import Bucket
cb = Bucket('couchbase://localhost/default?fetch_mutation_tokens=1
----
