[#concept_vxy_gjg_ps]
= Developer guide

[abstract]
The developer guide provides general information about interacting with Couchbase Server.

For specific information about programming for Couchbase Server, refer to the xref:sdks:intro.adoc#concept_yqn_tjg_ps[SDK guides].
The SDK guides explain how to set up your development environment and provide language-specific code examples.

Couchbase SDKs have the most capable APIs available for accessing data.
They provide a consistent and idiomatic experience for your language.

Click on your language for instructions on setting up a development environment.

* xref:sdks:c-2.4/c-intro.adoc#concept_zhc_crm_pp[C SDK 2.4/2.5]
* xref:sdks:go-beta/introduction.adoc#concept_z3r_zgq_44[Go SDK 1.0]
* xref:sdks:java-2.2/java-intro.adoc#concept_l11_ppm_pp[Java SDK 2.2]
* xref:sdks:dotnet-2.2/dotnet-intro.adoc#concept_m1n_rqm_pp[.NET SDK 2.2]
* xref:sdks:node-2.0/introduction.adoc#concept_z3r_zgq_44[Node.js SDK 2.0/2.1]
* xref:sdks:php-2.0/php-intro.adoc#concept_z3r_zgq_44[PHP SDK 2.0/2.1]
* xref:sdks:python-2.0/introduction.adoc#py-intro[Python SDK 2.0]
* http://docs.couchbase.com/developer/dev-guide-3.0/ruby-sdk.html[Ruby]

Couchbase SDKs attempt to follow common verbs and semantics (as much as the individual language allows).
Examples of using SDKs will be demonstrated in Python, but can easily be mimicked in other languages.
Many examples are also available in other languages.
The full listing of examples can be found at: https://github.com/couchbaselabs/devguide-examples[].
