[#concept-devguide-retrieving]
= Retrieving documents

[abstract]
Retrieve stored documents from Couchbase

----
document = get(docid)
----

NOTE: This section discusses retrieving documents using their IDs, or primary keys.
Documents can also be accessed using secondary lookups via xref:querying.adoc[Query] and MapReduce.
Primary key lookups are performed using the key-value API, which simplifies use and increases performance (as applications may interact with the KV store directly, rather than a secondary index or query processor).

== Retrieving documents using the SDK

In Couchbase, documents are stored with their IDs.
Retrieving a document via its ID is the simplest and quickest operation in Couchbase.

....
>>> result = cb.get('docid')
>>> print result.value
{'json': 'value'}
....

Examples of retrieving a document using an SDK:

https://github.com/couchbaselabs/devguide-examples/blob/master/c/retrieving.cc[C] | https://github.com/couchbaselabs/devguide-examples/blob/master/python/retrieving.py[Python] | https://github.com/couchbaselabs/devguide-examples/blob/master/java/src/main/java/com/couchbase/devguide/Retrieving.java[Java] | .NET | https://github.com/couchbaselabs/devguide-examples/blob/master/go/retrieving.go[Go] | https://github.com/couchbaselabs/devguide-examples/blob/master/nodejs/retrieving.js[node.js]

== Retrieving via the command line

 $ cbc cat docid
 docid                CAS=0x8234c3c0f213, Flags=0x0. Size=16
 {"json":"value"}

== Retrieving JSON documents

== Retrieving non-JSON documents

== Retrieving multiple documents

== Retrieving and setting expiration

== Primary key lookups using N1QL

----
SELECT * FROM default USE KEYS ["docid"];
----

----
SELECT * FROM default WHERE META(default).id = "docid";
----
