= Installing the Couchbase Java SDK
:description: In this tutorial, you're going to create a skeleton application for interacting with the student database you created previously.
:page-pagination: full

include::partial$tutorial-globals.adoc[]

[abstract]
{description}

== Prerequisites

Java is a fairly popular programming language these days, so we're going to use it to build our student/course application.
To keep things as light as possible (this is a tutorial, after all), we're not going to worry about building a web front end or REST service, just a few methods to read/write our documents to the database.

You will need a few things installed on your machine before you begin:

* The Java Software Development Kit (version {minimum-jdk-version})
* Apache Maven (version {minimum-maven-version})

TIP: https://sdkman.io/[SDKMan^] is the easiest way to install and manage JDKs and Maven on your host machine.

== Set up

Create the following directory structure on your machine:

include::partial$student-mvn-directory-structure.adoc[tags="basic"]

Create a new file in the directory called `pom.xml` in the `student` directory.
The pom file should be populated as follows:

.pom.xml
[source, xml]
----
include::{java-sample-location}pom.xml[]
----

<1> The `dependencies` section lists all the libraries required to build the application.
In our case, we only need the Couchbase client SDK (version 3.2.1, in this case).

include::partial$student-mvn-directory-structure.adoc[tags="location-of-pom.xml"]

You can test the setup is correct by opening a terminal window and changing to the `student` directory.
Run the build script to pull in all the dependencies.

[source,console]
----
mvn install
----

== Next steps

You're now ready to write your xref:java-tutorial/creating-the-students-collection.adoc[first Couchbase application].
