[#chooseYourNextSteps]
= Choose Your Next Steps

[abstract]
Now, to complete the _Getting Started_ sequence: consider your options as to what to do next, in order to continue improving your knowledge.
The Couchbase documentation-set provides detailed information on all aspects of the system; and this section lists some of the important areas you can visit.

== Where to Learn More

By navigating to the sections listed below, you can increase your knowledge of the areas you've already looked at — installation, configuration, and N1QL-querying — and also learn about new and (in some cases) quite advanced topics; such as multi-node clustering, fail-over, replication, and statistical analysis.

== Installation and Configuration

Couchbase Server is supported on numerous popular operating systems.
A complete list can be found in the section xref:install:install-platforms.adoc[Supported Platforms].
You may now wish to install Couchbase Server directly on one or more additional platforms: so, first, check to ensure that the platforms are supported.

Then, take a look at the information provided in xref:install:install-intro.adoc[Installing On-Premises].
This gives you links to installation-procedures for each of the individual platforms.

Couchbase Server can be run in a variety of configurations.
You can perform configuration by means of the Couchbase Web Console, via the Couchbase Command Line Interface (_CLI_), or with the Couchbase _REST_ API.
See the section xref:install:init-setup.adoc[Initialize the Cluster], for details.

Periodically, you will also need to stop and start individual server-nodes.
Information on doing this is provided in the section xref:install:startup-shutdown.adoc[Couchbase Server Startup and Shutdown].

== Querying with N1QL

As you've already seen, you can query Couchbase Server manually, using the N1QL query language and the xref:tools:query-workbench.adoc[Query Workbench] provided by the Couchbase Web Console.
A full introduction to N1QL can be found in the section xref:sdk:n1ql-query.adoc[Querying with N1QL]: note that this includes information on using `cbq`, which allows N1QL queries to be entered at the command line.

Additionally, N1QL queries can be specified by means of the Couchbase _REST_ API.
For information on doing so, see the section xref:n1ql:n1ql-rest-api/index.adoc[N1QL REST API]

== Using the Couchbase SDK

If you downloaded and ran the example provided in xref:run-hello-world.adoc[Run _Hello World!_], you've already gained some insight into the Couchbase SDK.
That example was written in node.js: but the Couchbase SDK also provides versions in Java, .NET, Go, C, PHP, and Python.

Under the *DEVELOPERS* tab in the vertical navigation-bar to the left, you'll find detailed information on all aspects of the Couchbase SDK, and how to use it.
First, take a look at the section xref:sdk:nodejs/start-using-sdk.adoc[Start Using the SDK].
Towards the upper right of that page is a pull-down menu, which allows you to select a language.
The page for the language you select provides information on installing supportive modules and libraries; as well as code-examples, to get you started with development.

== Concepts and Architecture

Your hands-on progress with Couchbase Server will be greatly helped by a good _conceptual_ knowledge.
This is provided under the *CONCEPTS & ARCHITECTURE* tab, visible in the vertical navigation-bar, to the left.
Start by looking at the xref:concepts:concepts-intro.adoc[Overview]; then, go from there.

== Administration

If you are an administrator, your priority will be to learn about system-setup and cluster-management.
So, access the documentation under the *ADMINISTRATORS* tab, visible in the navigation-bar; which includes extensive information on clusters, data-buckets, indexing, replication, security, and more.

== Integration

In some cases, you may wish to integrate Couchbase Server with another, different data-repository.
For example, you might wish to continue using your current _Elasticsearch_ database for the performance of free text searches; and extend these searches to Couchbase Server-data, so that Couchbase-documents can be retrieved.
For this to be possible, data must be shared between the repositories, and your querying coordinated between them.

Under the *INTEGRATIONS* tab, you can find information about Elasticsearch and all other repositories with which you can integrate Couchbase Server, thereby enriching your existing search-and-retrieval mechanisms.

== Additional Information

You can find extensive reference information on APIs, analytics, and tools under the *REFERENCES* tab, in the navigation-bar.
*RELEASE NOTES* can also be accessed there.
