[#doAQuickInstall]
= Do a Quick Install

[abstract]
First-time users can get Couchbase Server running simply and rapidly by using Docker.
Once you install Docker, you can use a single command to download and install a pre-configured version of Couchbase Server Enterprise Edition on your computer.

NOTE: The Docker container image that is used in this topic is meant to set up a 'sandbox' version of Couchbase Server.
It's based on the Enterprise Edition and contains scripts that automatically configure several Couchbase components during installation.
Although this particular image works great for a demo, it is not meant for production.
For information about using containers to run Couchbase Server in production, see xref:install:running-couchbase-in-containers.adoc#run-couchbase-in-containers[Running Couchbase Server in Containers & Orchestration].

[#initialize-cluster-web-console]
== Download and Install Docker

Docker is a freely available application that lets you install a fully-configured instance of Couchbase Server with a single command.
To set up Docker on your computer, go to the https://www.docker.com/get-docker[Docker installation page^] and follow the instructions.

== Use Docker to Install Couchbase Server

Once Docker is installed on your computer, you can go ahead and install Couchbase Server.

NOTE: You may need administrative or root privileges on your computer to complete the installation.

Open a console window on your computer and enter the following command:

----
docker run -t --name db -p 8091-8094:8091-8094 -p 11210:11210 couchbase/server-sandbox:5.5.0
----

When you run the command, Docker downloads, installs, and configures Couchbase Server.
Eventually, Couchbase Server is started in a Docker virtual environment:

----
.
.
.
Starting Couchbase Server -- Web UI available at http://<ip>:8091
and logs available in /opt/couchbase/var/lib/couchbase/logs
Configuring Couchbase Server.  Please wait (~60 sec)...
Configuration completed!
Couchbase Admin UI: http://localhost:8091
Login credentials: Administrator / password
----

From this point onward, don't close the console while you're using Couchbase Server; this terminates both Docker and Couchbase Server.

== Next

You can now proceed to the next step: xref:look-at-the-results.adoc#lookAtTheResults[Explore the Server Configuration].

== Other Destinations

* xref:install:install-intro.adoc[Installing Couchbase Server]: Explains how to install Couchbase Server directly onto your host, without the use of Docker or any other virtual environment.
This kind of direct install is very common for production-deployments, as well as development and testing activities.
* xref:install:init-setup.adoc#topic12527[Initializing the Cluster]: Provides a detailed explanation of how to custom-configure Couchbase Server at start-up.
This is the procedure you will certainly use in production; as well as for testing different configurations.
The available options include use of the Couchbase Server Web Console, the Couchbase REST API, and the Couchbase Command Line Interface.
* xref:install:startup-shutdown.adoc[Couchbase Server Startup and Shutdown]: Explains how to start and stop the server using the commands that are specific to your underlying platform.
