= Quick installation and setup
:page-topic-type: concept

[abstract]
You can install Couchbase Server on Linux, Microsoft Windows, or OS X systems.
These streamlined instructions will help you get up and running right away in a nonproduction environment so you can start learning how to use Couchbase Server.

IMPORTANT: Use the quick installation and setup instructions on this page only to try out Couchbase Server.
If you are installing Couchbase Server for development, test, or production purposes, set up Couchbase Server by following the xref:install:init-setup.adoc[detailed setup instructions] in the [.cite]_Installation Guide_.

NOTE: You can also read about sizing the Couchbase Server cluster in the blog http://blog.couchbase.com/how-many-nodes-part-1-introduction-sizing-couchbase-server-20-cluster[How many nodes?^].

== Download Couchbase Server

If you haven't already downloaded Couchbase Server, get it now from the *Couchbase Server downloads* page.

== Install on Red Hat or CentOS Linux systems

To install on Red Hat Enterprise Linux (RHEL) or CentOS Linux:

. Log on to the server as root.
. Enter the following command to install Couchbase Server, replacing [.var]`couchbase-server-version.rpm` with the name of the file you downloaded:

 $ rpm --install couchbase-server-version.rpm
+
Couchbase Server starts automatically after the installation completes.

== Install on Debian or Ubuntu Linux systems

To install on Debian or Ubuntu Linux:

. Log on to the server as root.
. Enter the following command to install https://help.ubuntu.com/community/OpenSSL[OpenSSL^], replacing [.var]`version` with a specific version number of OpenSSL:

 $ apt-get install libsslversion

. Enter the following command to install Couchbase Server, replacing [.var]`couchbase-server-version.deb` with the name of the file you downloaded:

 $ dpkg -i couchbase-server-version.deb
+
Couchbase Server starts automatically after the installation completes.

== Install on OS X systems

If you have an existing installation:

. Shut down any running instances of Couchbase Server.
. Delete any previous installations either by using the command line or by dragging the Couchbase Server application to the Trash.
. Open a Terminal window and delete any application support files from previous installations:

 $ rm -rf ~/Library/Application\Support/Couchbase
 $ rm -rf ~/Library/Application\Support/Membase

To install Couchbase Server:

. Download the zip file with the Couchbase Server package.
. Expand the downloaded zip file (if it didn't expand automatically) and open the folder.
+
The folder contains the Couchbase Server application and [.path]_README.txt_ file.

. Move the [.path]_Couchbase Server_ file to the [.path]_Applications_ folder.
. Start Couchbase Server by double-clicking the application icon.
+
If you get a message that says you can't run Couchbase Server due to security restrictions, right-click the icon for Couchbase Server and choose [.ui]*Open* from the pop-up menu.

== Install on 64-bit Microsoft Windows systems

To install on Microsoft Windows:

. Double-click the downloaded executable file to start the installer.
. Follow the installer prompts.
 ** If desired, you can change the installation location.
 ** If the default port is unavailable, the installer prompts you for a different port to use for server administration.
 ** When the installer asks if you want to increase the number of ephemeral ports, click [.ui]*Yes*.
. After the installation is complete, restart Couchbase Server to apply the port changes.

== Set up Couchbase Server

Set up Couchbase Server when you start the Couchbase Web Console for the first time.

IMPORTANT: Use the quick installation and setup instructions on this page only to try out Couchbase Server.
If you are installing Couchbase Server for development, test, or production purposes, set up Couchbase Server by following the xref:install:init-setup.adoc[detailed setup instructions] in the [.cite]_Installation Guide_.

To set up Couchbase Server in a nonproduction environment, you can accept the default values provided on most of the set-up screens.

. Open a browser and navigate to http://[.var]`hostname`:8091/.
. In the URL, [.var]`hostname` represents the name or IP address of the computer that hosts Couchbase Server.
If Couchbase Server is running locally, enter `localhost` for the host name.
. Click [.ui]*Setup*.
. On the [.ui]*Configure Server* screen (Step 1 of 5), click [.ui]*Next* to accept the default values for a new cluster.
. On the [.ui]*Sample Buckets* screen (Step 2 of 5), under [.ui]*Available Samples* select the two samples we will use later in this tutorial: [.ui]*beer-sample* and [.ui]*travel-sample* and click [.ui]*Next*.
. On the [.ui]*Create Default Bucket* screen (Step 3 of 5), under Memory Size set the [.ui]*Per Node RAM Quota* to 100 MB and click [.ui]*Next*.
. On the [.ui]*Notifications* screen (Step 4 of 5), enter your registration information, agree to the terms and conditions, and click [.ui]*Next*.
. On the [.ui]*Configure Server* screen (Step 5 of 5), enter and verify a password for the administrator account, and click [.ui]*Next*.
+
The Couchbase Web Console opens and displays the [.ui]*Cluster Overview*.

While the  Couchbase Web Console is open,  click on the tabs in the top menu and look at the screens to familiarize yourself with the information and available options.
