= Start Here!

[abstract]
If you are a first-time user, you can get a great, quick introduction to using Couchbase Server, just by reading this section.
In a few brief steps, you obtain direct experience of installing, running, and performing interactive queries on the server.

[#initialize-cluster-web-console]
== Steps for First-Time Users

You'll now be guided through some of the key aspects of Couchbase Server.
At the conclusion of the sequence, you'll have attained an excellent starting-point for further, more detail-driven activities.
The steps are as follows:

. Do a Quick Install

. Look at the Results

. Run Your First N1QL Query

. Choose Your Next Steps

If, at any stage, you decide that you wish to depart from the sequence, and make an immediate deep-dive into a specific topic, you can do so: by means of links to _Other Destinations_.

Alternatively, if you do elect to work continuously through the whole sequence (as indeed we suggest), you ultimately arrive at the xref:choose-your-next-steps.adoc[Choose Your Next Steps] section; which provides a comprehensive list of options for gaining further knowledge of Couchbase server.

Now proceed to xref:do-a-quick-install.adoc[Do a Quick Install].
