// Starter Kits for Couchbase Developers
= Starter Kits
:page-role: tiles
:url-guides-org: https://github.com/couchbase-guides
:!sectids:
:description: Starter kits are repositories containing example code to get you started with various development projects.

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title,
  div.contributor-list-box,
  div#preamble,
  nav.pagination {
    flex-basis: 100%;
  }
</style>
++++
endif::[]

{description}

== Couchbase Server in Docker

Start a Couchbase Server Docker Container and connect to the server using the Couchbase CLI.

{url-guides-org}/couchbase-docker[Learn more]

== Couchbase Server on Amazon EC2

Start an EC2 instance and connect to the server using the Couchbase CLI.

{url-guides-org}/couchbase-amazon-cli[Learn more]

== Couchbase Server with ASP.NET Core

Create a "`hello world`" ASP.NET Core web application that uses Couchbase Server as the backend database.

{url-guides-org}/asp-net-core-mvc[Learn more]

== Couchbase with Java SDK

Create a Java application that uses Couchbase Server as the backend to store a JSON document.

{url-guides-org}/java-sdk[Learn more]

== Couchbase with Node.js using Express Framework

Create a "`hello world`" Node.js web application that uses Couchbase Server as the backend database.

{url-guides-org}/nodejs-express[Learn more]

== Couchbase with NativeScript using Angular

Create a "`hello world`" NativeScript mobile application that uses Couchbase Server, NativeScript, and Angular.

{url-guides-org}/nativescript-angular[Learn more]

== Couchbase with Python SDK

Create a simple Python application to store and retrieve a JSON document in Couchbase Server.

{url-guides-org}/python-sdk[Learn more]

== Couchbase Lite (CBL) on Android

Build an Android application consisting of a single activity that performs CRUD operations and uses Couchbase Lite to store documents locally on the device.

{url-guides-org}/java-android[Learn more]

== Couchbase Backup

Learn how to create backups from Couchbase Server.

{url-guides-org}/couchbase-backup[Learn more]

== Couchbase Restore

Learn how to restore backups to Couchbase Server.

{url-guides-org}/couchbase-restore[Learn more]

== Write Your Own Starter Kit

Use these guidelines to build your own guide using AsciiDoc and push it to the couchbase-guides Github repository.

{url-guides-org}/how-to-write-a-guide[Learn more]
