[#topic227]
= Monitoring

[abstract]
Monitoring is a critical element for a successful deployment.

This section provides an overview of the different monitoring capabilities available in Couchbase Server explains how to use them to learn more about cluster status, performance metrics, and other operational parameters.

== Statistics monitoring methods

Couchbase Server provides different methods for collecting data about the state of a running cluster:

. Couchbase Server features a rich, web-based administration console for monitoring data collected from running deployments and providing visual and email-based alerts based on that data.
+
See the section xref:settings:configure-alerts.adoc[Email Alerts] for more details.

. Couchbase Server also provides a REST interface that can be queried for access to current and historic statistics that the cluster stores.
+
See xref:rest-api:rest-cluster-email-notifications.adoc#rest-cluster-alerts[Setting Email Notifications] to configure email alerts with the REST API.

. In addition to the previously listed methods, Couchbase Server stores per node statistics that can be polled through a client that uses the binary protocol or with the xref:cli:cbstats-intro.adoc#cbstats-intro[cbstats] utility.
