= Backup Service

[abstract]
The Backup Service allows full and incremental data-backups to be scheduled, and also allows the scheduling of _merges_ of previously made data-backups.

[#backup-service-overview]
== Overview

The Backup Service supports the scheduling of full and incremental data backups, either for specific individual buckets, or for all buckets on the cluster.
It also allows the scheduling of _merges_ of previously made backups.
Data to be backed up can also be selected by _service_: for example, the data for the _Data_ and _Index_ Services alone might be selected for backup, with no other service's data included.

The service &#8212; which is also referred to as _cbbs_ (Couchbase Backup Service) &#8212; can be configured and administered by means of the Couchbase Web Console UI, the CLI, or the REST API.

[#backup-service-and-cbbackupmgr]
== The Backup Service and cbbackupmgr

The Backup Service's underlying backup tasks are performed by `cbbackupmgr`, which can also be used independently, on the command line, to perform backups and merges.
The Backup Service and `cbbackupmgr` (when the latter is used independently) have the following, principal differences:

* Whereas the Backup Service allows backup, restore, and archiving to be configured for the local cluster, and also permits restore to be configured for a remote cluster; `cbbackupmgr` allows backup, restore, and archiving each to be configured either for the local or for a remote cluster.

* Whereas `cbbackupmgr` allows backups, merges, and other related operations only to be executed individually, the Backup Service provides automated, recurrent execution of such operations.

See xref:backup-restore:enterprise-backup-restore.adoc[cbbackupmgr], for more information.

Note that both the Backup Service and `cbbackupmgr` allow _full_ and _incremental_ backups.
Unlike the Backup Service, `cbbackupmgr` requires a new repository to be created for each new, full backup (successive `cbbackupmgr` backups to the same repository being incremental).
Both allow incremental backups, once created, to be merged, and their data deduplicated.
Both use the same backup archive structure; and allow the contents of backups to be listed, and specific documents to be searched for.

[#backup-service-architecture]
== Backup-Service Architecture

The Backup Service has a _leader-follower_ architecture.
This means that one of the cluster's Backup-Service nodes is elected by ns_server to be the _leader_; and is thereby made responsible for dispatching backup tasks; for handling the addition and removal of nodes from the Backup Service; for cleaning up orphaned tasks; and for ensuring that global storage-locations are accessible by all Backup-Service nodes.

If the _leader_ becomes unresponsive, or is lost due to failover, the Backup Service ceases operation; until a rebalance has been performed.
During the course of this rebalance, ns_server elects a new leader, and the Backup Service resumes, using the surviving Backup-Service nodes.

[#plans]
== Plans

The Backup Service is automated through the scheduling of _plans_, defined by the administrator.
A plan contains the following information:

* The data of which services is to be backed up.

* The _schedule_ on which backups (or backups and merges) will be performed.

* The type of task to be performed: this can either be _one or more backups_, or _one or more backups and one or more merges_.
Backups can be _full_ or _incremental_.

[#repositories]
== Repositories

A _repository_ is a location that contains backed up data.
The location must be accessible to all nodes in the cluster, and must be assigned a name that is unique across the cluster.
A repository is defined with reference either to _a specific bucket_, or to _all buckets on the cluster_.
Data from each specified bucket will be backed up in the specified repository.

A repository is defined with reference to a specific _plan_.
Once repository-definition is completed, backups (or backups and merges) are performed of the data in the specified bucket (or buckets), with the data being saved in the repository on the schedule specified in the plan.

[#inspecting-and-restoring]
== Inspecting and Restoring

The Backup Service allows inspection to be performed on the history of backups made to a specific repository.
Plans can be created, reviewed and deleted.
Individual documents can be searched for, in respositories.

Data from individual or selected backups within a repository can be _restored_ to the cluster, to a specified bucket.
Document keys and values can be _filtered_, to ensure that only a subset of the data is restored.

[#archiving-and-importing]
== Archiving and Importing

If a repository no longer needs to be _active_ (that is, with ongoing backups and merges continuing to occur), it can be _archived_: this means that the repository is still accessible, but no longer receives data backups.

An archived repository can be _deleted_, so that the Backup Service no longer keeps track of it.
Optionally, the data itself can be retained, on the local filesystem.

A deleted repository whose data still exists can be _imported_ back into the cluster, if required.
Once imported, the repository can be _read_ from, but no longer receives data backups.

[#avoiding-task-overlap]
== Avoiding Task Overlap

Although the Backup Service allows automated tasks to be scheduled for repetition at intervals as small as one minute, administrators are recommended typically not to lower the interval below fifteen minutes; and always to ensure that the interval is large enough to allow each scheduled task-repetition ample time to complete before the next is due to commence; even in the event of unanticipated network latency.

If, due to an interval-specification that is too small, a scheduled task attempts to start while its prior repetition is still ongoing, the new task fails, stops running, and is not restarted.
In such circumstances, if the scheduled task is a backup, all data continues to be backed up by the prior repetition; and will be backed up again by any subsequent repetition that starts after the completion of the prior repetition.

[#see-also]
== See Also

For information on using the Backup Service by means of Couchbase Web Console, see xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc[Manage Backup and Restore].
For reference pages on the Backup Service REST API, see xref:rest-api:backup-rest-api.adoc[Backup Service API].
For information on the port numbers used by the Backup Service, see xref:install:install-ports.adoc[Couchbase Server Ports].
For a list of audit events used by the Backup Service, see xref:audit-event-reference:audit-event-reference.adoc[Audit Event Reference].
