= Resources Under Access Control

[abstract]
Couchbase Server applies RBAC to a defined set of _resources_.
The Couchbase Full Administrator can assign a _role_ to a defined user; the
role being associated with one ore more privileges either on an individual,
named resource; or on all resources within a _resource-type_ group.

[#access-controlled-resources]
== Access-Controlled Resources

The following Couchbase Server-resources are always access-controlled:

* *Clusters*.

* *XDCR Cluster References*.

* *Query Service*.

* *Analytics Shadow Data Sets*.

* *System Catalogs*.
Including:
+
The following diagnostics are provided:
+
[cols="1,3"]
|===
| System Catalogs
a|
* xref:n1ql:n1ql-intro/sysinfo.adoc#querying-datastores[system:datastores]
* xref:n1ql:n1ql-intro/sysinfo.adoc#querying-namespaces[system:namespaces]
* xref:n1ql:n1ql-intro/sysinfo.adoc#querying-keyspaces[system:keyspaces]
* xref:n1ql:n1ql-intro/sysinfo.adoc#querying-dual[system:dual]

| Monitoring Catalogs
a|
* xref:n1ql:n1ql-intro/sysinfo.adoc#title__Toc272567208[system:indexes]
* <<topic_nvs_ghr_dz/sys-prepared,system:prepareds>>
* <<topic_nvs_ghr_dz/sys-completed-req,system:completed_requests>>
* <<topic_nvs_ghr_dz/sys-active-req,system:active_requests>>
* <<topic_nvs_ghr_dz/section_wwl_tsm_n1b,system:my_user_info>>

| Security Catalogs
a|
* <<topic_nvs_ghr_dz/section_pt1_fxt_n1b,system:user_info>>
* system:nodes
* <<topic_nvs_ghr_dz/section_t5h_wxt_n1b,system:applicable_roles>>

| Other
a|
* xref:monitoring:monitoring-n1ql-query.adoc#vitals[vitals]

NOTE: These are only available using REST APIs.
|===

* *Buckets*.
Note that buckets have three independently access-controllable features, each of which should be considered an individual resource-type:

 ** *Settings*.
Includes

Bucket Type::


Ejection Method::


Conflict Resolution method::


Protocol Port::


Auto-Compaction::


Flush::


compact::


delete::


 ** *Statistics*.
Includes _ops_, _gets_, _sets_, and _deletes_ per second.
Also includes information on memory-usage, disk-related activity, and status on indexing, querying, and XDCR activity.

 ** *Data*.
Includes _data_ and _meta-data_ for all objects within a bucket.


* *XDCR Bucket Replication*.

* *Indexes*.
Including _Views_, _Primary Indexes_, _Global Secondary Indexes_, and Search _Indexes_.

* *UI Access*.
Allows login to _Couchbase Web Console_.
The features available are role-dependent.

* *Curl Access*.
Allows execution of the N1QL CURL function by externally authenticated users.

* *Eventing*.
Allows configuration and scheduling of the _Eventing Service_.

* *Pools*.
