= set tap_param
:page-topic-type: reference

[abstract]
The disk write queues quota impacts the rate of data sent from source nodes to destination nodes.

== Syntax

The basic syntax is:

----
cbepctl [host]:11210  -b [bucket_name] -u [username] -p [password] set tap_param [parameter] [value]
cbepctl [host]:11210  -b [bucket_name] -u [username] -p [password] set tap_param tap_throttle_queue_cap [value]
cbepctl [host]:11210  -b [bucket_name] -u [username] -p [password] set tap_param tap_throttle_cap_pcnt [value]
----

== Description

One of the specific uses of the command [.cmd]`set tap_param` is to change the default maximum items for a disk write queue.
This impacts replication of data that occurs between source and destination nodes within a cluster.
Both data that a node receives from client applications and replicated items that it receives are placed on a disk write queue.
If there are too many items waiting in the disk write queue at any given destination, Couchbase Server reduces the rate of data that is sent to a destination.
This process is also known as [.term]_backoff_.

By default, when a disk write queue contains one million items a Couchbase Server node reduces the rate it sends out data to be replicated.
This setting can be changed to be the greater of 10% of the items at a destination node or a specific number.

== Options

The following are the command options:

.tet ap_param optioins
[cols="25,36"]
|===
| Parameter | Description

| `tap_keepalive`
| Seconds to hold a named tap connection.

| `tap_throttle_queue_cap`
| The maximum disk write queue size when tap streams are put into a temporary 5-second pause.
Infinite means there is no cap.

| `tap_throttle_cap_pcnt`
| The maximum number of items in the disk write queue as a percentage of all items on a node.
At this point, tap streams are put into a temporary, 5-second pause.

| `tap_throttle_threshold`
| Percentage of memory in use when tap streams are put into a temporary, 5-second pause.
|===

== Examples

Change the default bucket setting to specify that a replica node sends a request for backoff when it has two million items.

----
cbepctl 10.5.2.117:11210 set tap_param tap_throttle_queue_cap 2000000
----

The following example for the default bucket changes the default percentage used to manage the replication stream.
If the items in a disk write queue reach the greater of this percentage or a specified number of items, replication requests slow down.

The threshold is set to 15% of all items at a replica node.
When a disk write queue on a replica node reaches this point, it requests replication backoff.

----
cbepctl 10.5.2.117:11210 set tap_param tap_throttle_cap_pcnt 15
----

*Response*

The following example responses show a two million setting and a 15% threshold:

----
setting param: tap_throttle_queue_cap 2000000
set tap_throttle_queue_cap to 2000000

setting param: tap_throttle_cap_pcnt 15
set tap_throttle_cap_pcnt to 15
----
