= set vbucket_param
:page-topic-type: reference

[abstract]
The `set vbucket_param` command establishes the `max_cas` of a specific vBucket.

== Description

The `set vbucket_param` command establishes the `max_cas` of a specific vBucket.
The settings takes effect immediately, but is _not_ persistent across node-restarts: therefore, following a node-restart, the command should be executed again if necessary, to re-establish the desired setting.

This and all other `cbepctl` commands are intended only for use either _by_ or _under the strict and explicit guidance of_ Couchbase Customer Support.

== Syntax and Example

The syntax for `set vbucket_param` is as follows:
----
cbepctl [host]:11210 -b [bucket-name] -u [administrator-name]
  -p [administrator-password] set vbucket_param [parameter] [vbucket-id] [value]
----

The `parameter` must be `max_cas`.
Its associated `vbucket-id` must be a vBucket ID.
The `value` must be an integer, which specifies the new `max_cas` for the vBucket.
The specified integer will be interpreted as an unsigned 64-bit integer.

== Errors

Failure to specify a bucket produces the following error message: `No access to bucket:default - permission denied or bucket does not exist.`
A malformed command produces the error `cbepctl: error: Unknown command`.
Improperly specified credentials return an error message similar to `Authentication error for user:Administrat3or bucket:travel-sample`.
Use of the wrong port-number displays the error `Connection error: [Errno 111] Connection refused`.

Incorrectly specifying a parameter returns the error `Error: Bad parameter <specified-parameter>`.
Specifying a `value` greater than the maximum permitted returns the error `Error: KEY_ENOENT : Not Found :`.
