= set replication_param
:page-topic-type: reference
:page-aliases: cli:set-tap_param

[abstract]
The `set replication_param` command establishes parameters for the management of replication streams.

== Description

If, on a particular node, disk-write queues accumulate a large number of items, of if memory becomes constrained, the input from incoming replication streams can be _throttled_: this reduces the rate at which other nodes are sending replications to the node.
The `set replication_param` command establishes the parameters whereby this is achieved.

All settings take effect immediately, but are _not_ persistent across node-restarts: therefore, following a node-restart, commands should be executed again if necessary, to re-establish desired settings.

This and all other `cbepctl` commands are intended for use either _by_ or _under the strict and explicit guidance of_ Couchbase Customer Support.

== Syntax and Examples

The syntax for `set replication_param` is as follows:
----
cbepctl [host]:11210 -b [bucket-name] -u [administrator-name]
  -p [administrator-password] set replication_param [parameter] [value]
----

The options for the `parameter` and its associated `value` are as follows:

=== replication_throttle_queue_cap

The `value` must be an integer, which specifies a disk-write queue-size (as a number of queued mutations).
When this size is reached for the vBuckets that correspond to the specified bucket, on the specified node, input from all replication streams to these vBuckets is throttled.

The following example establishes the `replication_throttle_queue_cap` as 2,000,000:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set replication_param replication_throttle_queue_cap 2000000
----

If successful, the command returns the following:

----
setting param: replication_throttle_queue_cap 2000000
set replication_throttle_queue_cap to 2000000
----

=== replication_throttle_cap_percent

The `value` must be an integer, which specifies a percentage of the total number of items contained by the vBuckets that correspond to the specified bucket, on the specified node.
When the number of items in these vBuckets' disk-write queue is equal to the number corresponding to this percentage, input from replication streams to these vBuckets is throttled.

The following example establishes `replication_throttle_cap_percent` as 15%:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set replication_param replication_throttle_cap_pcnt 15
----

If successful, the command returns the following:

----
setting param: replication_throttle_cap_pcnt 15
set replication_throttle_cap_pcnt to 15
----

=== replication_throttle_threshold

The `value` must be an integer, which specifies a percentage of the memory allocated to the vBuckets that correspond to the specified bucket, on the specified node.
When this percentage of the memory for these vBuckets is full, input from replication streams to these vBuckets is throttled.

The following example establishes `replication_throttle_threshold` as 95%:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set replication_param replication_throttle_threshold 95
----

If successful, the command returns the following:

----
setting param: replication_throttle_threshold 95
set replication_throttle_threshold to 95
----
