= set flush_param
:page-topic-type: reference

[abstract]
The `set flush_param` command establishes parameters related to memory and storage.

== Description

The `set flush_param` command  establishes parameters related to memory and storage: including key-access scanning, memory threshold configuration, compaction, queue management, compression ratio settings, defragmentation, expiration, task scheduling, and thread allocation.
The command is applied with reference to a specific bucket and a specific node: therefore, parameter-modifications are applied only to the vBuckets that correspond to the named bucket, on the specified node.

All settings take effect immediately, but are _not_ persistent across node-restarts: therefore, following node-restart, the command should be executed again if necessary, to re-establish the modifications.

This and all other `cbepctl` commands are intended only for use either _by_ or _under the strict and explicit guidance of_ Couchbase Customer Support.

== Syntax and Examples

The syntax for `set flush_param` is as follows:
----
cbepctl [host]:11210 -b [bucket-name] -u [administrator-name]
  -p [administrator-password] set flush_param [parameter] [value]
----

The acceptable values for `parameter` are as follows:

[cols="3,3,3"]
|===

| xref:cli:cbepctl/set-flush_param.adoc#access_scanner_enabled[access_scanner_enabled]
| xref:cli:cbepctl/set-flush_param.adoc#alog_sleep_time[alog_sleep_time]
| xref:cli:cbepctl/set-flush_param.adoc#alog_task_time[alog_task_time]

| xref:cli:cbepctl/set-flush_param.adoc#backfill_mem_threshold[backfill_mem_threshold]
| xref:cli:cbepctl/set-flush_param.adoc#bg_fetch_delay[bg_fetch_delay]
| xref:cli:cbepctl/set-flush_param.adoc#bfilter_enabled[bfilter_enabled]

| xref:cli:cbepctl/set-flush_param.adoc#bfilter_residency_threshold[bfilter_residency_threshold]
| xref:cli:cbepctl/set-flush_param.adoc#compaction_exp_mem_threshold[compaction_exp_mem_threshold]
| xref:cli:cbepctl/set-flush_param.adoc#compaction_write_queue_cap[compaction_write_queue_cap]

| xref:cli:cbepctl/set-flush_param.adoc#dcp_min_compression_ratio[dcp_min_compression_ratio]
| xref:cli:cbepctl/set-flush_param.adoc#defragmenter_enabled[defragmenter_enabled]
| xref:cli:cbepctl/set-flush_param.adoc#defragmenter_interval[defragmenter_interval]

| xref:cli:cbepctl/set-flush_param.adoc#defragmenter_age_threshold[defragmenter_age_threshold]
| xref:cli:cbepctl/set-flush_param.adoc#defragmenter_chunk_duration[defragmenter_chunk_duration]
| xref:cli:cbepctl/set-flush_param.adoc#exp_pager_enabled[exp_pager_enabled]

| xref:cli:cbepctl/set-flush_param.adoc#exp_pager_stime[exp_pager_stime]
| xref:cli:cbepctl/set-flush_param.adoc#exp_pager_initial_run_time[exp_pager_initial_run_time]
| xref:cli:cbepctl/set-flush_param.adoc#item_compressor_interval[item_compressor_interval]

| xref:cli:cbepctl/set-flush_param.adoc#item_compressor_chunk_duration[item_compressor_chunk_duration]
| xref:cli:cbepctl/set-flush_param.adoc#pager_active_vb_pcnt[pager_active_vb_pcnt]
| xref:cli:cbepctl/set-flush_param.adoc#max_size[max_size]

| xref:cli:cbepctl/set-flush_param.adoc#mem_high_wat[mem_high_wat]
| xref:cli:cbepctl/set-flush_param.adoc#mem_low_wat[mem_low_wat]
| xref:cli:cbepctl/set-flush_param.adoc#min_compression_ratio[min_compression_ratio]

| xref:cli:cbepctl/set-flush_param.adoc#mutation_mem_threshold[mutation_mem_threshold]
| xref:cli:cbepctl/set-flush_param.adoc#timing_log[timing_log]
| xref:cli:cbepctl/set-flush_param.adoc#warmup_min_memory_threshold[warmup_min_memory_threshold]

| xref:cli:cbepctl/set-flush_param.adoc#warmup_min_items_threshold[warmup_min_items_threshold]
| xref:cli:cbepctl/set-flush_param.adoc#num_reader_threads[num_reader_threads]
| xref:cli:cbepctl/set-flush_param.adoc#num_writer_threads[num_writer_threads]

| xref:cli:cbepctl/set-flush_param.adoc#num_auxio_threads[num_auxio_threads]
| xref:cli:cbepctl/set-flush_param.adoc#num_nonio_threads[num_nonio_threads]
| xref:cli:cbepctl/set-flush_param.adoc#xattr_enabled[xattr_enabled]

| xref:cli:cbepctl/set-flush_param.adoc#mem_used_merge_threshold_percent[mem_used_merge_threshold_percent]
|
|

|===

The options for the `value` associated with each `parameter` are as follows:

=== access_scanner_enabled

The `value` must be a Boolean, specifying whether the _access scanner_ is enabled or disabled: the access scanner runs periodically, to determine the frequency with which keys are accessed.
Setting `value` to `true` enables; `false` disables.

The following example enables the access scanner for the bucket `travel-sample` on the specified node:

----
/opt/couchbase/bin/cbepctl 10.143.186.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param access_scanner_enabled true
----

If successful, the command returns the following:

----
setting param: access_scanner_enabled true
set access_scanner_enabled to true
----

=== alog_sleep_time

The `value` must be an integer specifying the interval that must elapse between successive runs of the access scanner, in minutes.
By default, the scanner process runs once every 24 hours at 10:00 AM GMT.

The following example specifies that five minutes should elapse:

----
/opt/couchbase/bin/cbepctl 10.143.186.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param alog_sleep_time 5
----

If successful, the command returns the following:

----
setting param: alog_sleep_time 5
set alog_sleep_time to 5
----

=== alog_task_time

The `value` must be an integer that specifies the hour, in UTC time, at which the access scanner is next scheduled to run: the minimum value is `0`, maximum is `23`.
By default, the scanner process runs once every 24 hours, at 10:00 AM GMT.
To reduce the cluster-wide impact of running this task, it should be given a different start time, on each node in the cluster.

The following example specifies that the access scanner should next run at 12:00 noon:

----
/opt/couchbase/bin/cbepctl 10.143.186.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param alog_task_time 12
----

If successful, the command returns the following:

----
setting param: alog_task_time 12
set alog_task_time to 12
----

=== backfill_mem_threshold

The `value` must be an integer that represents a percentage of the memory assigned to the named bucket.
When this percentage of the bucket's memory is full, _backfill tasks_ are backed off.

The following example sets `backfill_mem_threshold` to 80%.

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param backfill_mem_threshold 80
----

If successful, the command returns the following:

----
setting param: backfill_mem_threshold 80
set backfill_mem_threshold to 80
----

=== bg_fetch_delay

The `value` must be an integer that represents the number of seconds that must elapse before a required background fetch is executed.

The following example sets `bg_fetch_delay` to `3`.

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param bg_fetch_delay 3
----

If successful, the command returns the following:

----
setting param: bg_fetch_delay 3
set bg_fetch_delay to 3
----

=== bfilter_enabled

The `value` must be a Boolean: `true` enables _Bloom filters_; `false` disables.

_Bloom filters_, which are enabled by default, improve the performance of cache management when _full ejection_ has been configured.
(See xref:learn:data/buckets.adoc[Buckets] for information on ejection).

The following example enables Bloom filters for the `travel-sample` bucket, on the specified node:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param bfilter_enabled true
----

If successful, the command returns the following:

----
setting param: bfilter_enabled true
set bfilter_enabled to true
----

=== bfilter_residency_threshold

The `value` must be a floating point number, specifying a ratio of in-memory to on-disk items.
When the current, actual ratio goes below this number, if the ejection-policy has been set to _full_, all items are represented in the Bloom filter.
The minimum value is `0.0`, the maximum `1.0`.

The following example establishes the ratio-threshold as `0.1`:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param bfilter_residency_threshold 0.1
----
If successful, the command returns the following:

----
setting param: bfilter_residency_threshold 0.1
set bfilter_residency_threshold to 0.1
----

=== compaction_exp_mem_threshold

The `value` must be an integer, which represents the threshold, as a percentage, of the memory-quota for the named bucket, above which the compaction process will not queue expired documents for deletion.

The following example sets `compaction_exp_mem_threshold` to 65%:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param compaction_exp_mem_threshold 65
----

If successful, the command returns the following:

----
setting param: compaction_exp_mem_threshold 65
set compaction_exp_mem_threshold to 65
----

=== compaction_write_queue_cap

The `value` must be an integer, specifying a percentage of items currently in the write-queue that are compaction tasks.
Whenever this percentage is reached, all new compaction tasks are made to sleep, until existing compaction tasks have left the queue, and the percentage has thus fallen.

The following example sets `compaction_write_queue_cap` to 65%:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param compaction_write_queue_cap 65
----

If successful, the command returns the following:

----
setting param: compaction_write_queue_cap 65
set compaction_write_queue_cap to 65
----

=== dcp_min_compression_ratio

The `value` must be a floating point number, which represents the minimum accepted ratio of the document's size in compressed form, to its size in uncompressed form.
If a document is to be transmitted that is already in compressed form and its compression ratio is either equal to or greater than the minimum, it will be transmitted in that form by any DCP producer, to any DCP consumer that has compression enabled.
If the compression ratio of the document is less than the minimum, the document is transmitted in uncompressed form.

The following example sets `dcp_min_compression_ratio` to 0.3:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param dcp_min_compression_ratio 0.3
----

If the command is successful, it returns the following:

----
setting param: dcp_min_compression_ratio 0.3
set dcp_min_compression_ratio to 0.3
----

=== defragmenter_enabled

The `value` must be a Boolean: `true` enables the _active memory defragmenter_, `false` disables.
The default is `true`.

For information, see xref:learn:buckets-memory-and-storage/memory.adoc#active-memory-defragmenter[Active Memory Defragmenter].

The following example enables the defragmenter:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param defragmenter_enabled true
----

If successful, the command returns the following:

----
setting param: defragmenter_enabled true
set defragmenter_enabled to true
----

=== defragmenter_interval

The `value` must be an integer, specifying the number of seconds that must elapse between successive runnings of the defragmenter.

The following example sets the `defragmenter_interval` to 20 seconds:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param defragmenter_interval 20
----

If successful, the command returns the following:

----
setting param: defragmenter_interval 20
set defragmenter_interval to 20
----

=== defragmenter_age_threshold

The `value` must be an integer, specifying how _old_ a document must be, in terms of how many times the defragmenter has been run since the document's creation, before it is to be considered a candidate for defragmentation.

The following example sets the value of `defragmenter_age_threshold` to 3:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param defragmenter_age_threshold 3
----

If successful, the command returns the following:

----
setting param: defragmenter_age_threshold 3
set defragmenter_age_threshold to 3
----

=== defragmenter_chunk_duration

The `value` must be an integer, which specifies the number of milliseconds for which the defragmenter runs, before being paused, so as to resume after the established `defragmenter_interval`.

The following example sets the `defragmenter_chunk_duration` to 1000:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param defragmenter_chunk_duration 1000
----

If successful, the command returns the following:

----
setting param: defragmenter_chunk_duration 1000
set defragmenter_chunk_duration to 1000
----

=== exp_pager_enabled

The `value` must be a Boolean: `true` enables the _expiry pager_; `false` disables.
See xref:learn:buckets-memory-and-storage/memory.adoc#expiry-pager[Expiry Pager].

The following example enables the expiry pager:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param exp_pager_enabled true
----

If successful, the command returns the following:

----
setting param: exp_pager_enabled true
set exp_pager_enabled to true
----

=== exp_pager_stime

The `value` must be an integer, which specifies the number of minutes that must elapse between successive runs of the expiry pager.
The default value is 60.

The following example sets `exp_pager_stime` to 30:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param exp_pager_stime 30
----

If successful, the command returns the following:

----
setting param: exp_pager_stime 30
set exp_pager_stime to 30
----

=== exp_pager_initial_run_time

The `value` must be _either_:

* An integer from `0` to `23`, specifying the hour at which the first run of the expiry pager will occur.

* `disable`: which causes the expiry pager to be run after `exp_pager_stime` has elapsed.

The following example disables `exp_pager_initial_run_time`:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param exp_pager_initial_run_time disable
----

If successful, the command returns the following:

----
setting param: exp_pager_initial_run_time -1
set exp_pager_initial_run_time to -1
----

=== item_compressor_interval

The `value` must be an integer, specifying the time (in milliseconds) that must elapse between successive runs of the _item compressor_.
The default value is 250.

The following example sets the `item_compressor_interval` to 200:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param item_compressor_interval 200
----

If successful, the command returns the following:

----
setting param: item_compressor_interval 200
set item_compressor_interval to 200
----

=== item_compressor_chunk_duration

The `value` must be an integer, which specifies (in milliseconds) the duration for which the item compressor will run, before pausing, and resuming following the established `item_compressor_interval`.
The default value is 20.

The following example sets the `item_compressor_chunk_duration` to 50:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param item_compressor_chunk_duration 50
----

If successful, the command returns the following:

----
setting param: item_compressor_chunk_duration 50
set item_compressor_chunk_duration to 50
----

=== pager_active_vb_pcnt

The `value` must be an integer, which specifies the percentage of items ejected by the item pager that must be items from _active_ vBuckets.
The default setting is `60`.

Note that by decreasing the percentage of active items ejected, more active items are kept in memory: this may increase performance.
However, since this means fewer replicas are kept in memory, in the event of node failure, additional disk-retrievals may be required: this may lessen performance.

The following example sets `pager_active_vb_pcnt` to 30:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param pager_active_vb_pcnt 30
----

If successful, the command returns the following:

----
setting param: pager_active_vb_pcnt 30
set pager_active_vb_pcnt to 30
----

=== max_size

The `value` must be an integer, which specifies the maximum amount of memory used by the server.

The following sets the `max_size` for the bucket to 30 MB:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param max_size 30
----

If successful, the command returns the following:

----
setting param: max_size 30
set max_size to 30
----

=== mem_high_wat

The `value` must be an integer, which is the percentage of the memory allocated as `max_size` that constitutes the _high watermark_ for the bucket.
See xref:learn:buckets-memory-and-storage/memory.adoc#ejection[Ejection], for a description of watermarks.
The default is `85`.

The following command sets the high watermark for the bucket on the given node to 87%:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param mem_high_wat 87
----

If successful, the command returns the following:

----
setting param: mem_high_wat 87
set mem_high_wat to 87
----

=== mem_low_wat

The `value` must be an integer, which is the percentage of the memory allocated as `max_size` that constitutes the _low watermark_ for the bucket.
See xref:learn:buckets-memory-and-storage/memory.adoc#ejection[Ejection], for a description of watermarks.
The default is `75`.

The following command sets the low watermark for the bucket on the given node to 74%:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param mem_low_wat 74
----

If successful, the command returns the following:

----
setting param: mem_low_wat 74
set mem_low_wat to 74
----

=== min_compression_ratio

The `value` must be a floating point number, which represents the minimum accepted ratio of the document's size in compressed form, to its size in uncompressed form.
If a document to be saved is already in compressed form, and its compression ratio is either equal to or greater than the minimum, it is saved in that form.
If the compression ratio of the document is less than the minimum, the document is saved in uncompressed form.
The minimum setting is `0.0`; the default setting 1.2.

The following example sets `min_compression_ratio` to 0.3:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param min_compression_ratio 0.3
----

If the command is successful, it returns the following:

----
setting param: min_compression_ratio 0.3
set min_compression_ratio to 0.3
----

=== mutation_mem_threshold

The `value` must be an integer, which specifies a percentage of bucket-memory: when this percentage has been consumed, new mutations are not accepted by the bucket on this node; and an _out-of-memory_ message is returned to clients.
The default value (and recommended absolute maximum) is 95%.

The following example sets `mutation_mem_threshold` to 80%:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample set flush_param mutation_mem_threshold 80
----

If successful, the command returns the following:

----
setting param: mutation_mem_threshold 80
set mutation_mem_threshold to 80
----

=== timing_log

The `value` must be a path to a directory within which detailed timing statistics will be logged.

The following example sets the log-destination to `/home/user`:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param timing_log /home/user
----

If successful, the command returns the following:

----
setting param: timing_log /home/user
set timing_log to /home/user
----

=== warmup_min_memory_threshold

The `value` must be an integer, which is the percentage of bucket-allocated memory that should be available during warmup, before data-serving commences.

The following example sets `warmup_min_memory_threshold` to 70%:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param warmup_min_memory_threshold 70
----

If successful, the command returns the following:

----
setting param: warmup_min_memory_threshold 70
set warmup_min_memory_threshold to 70
----

=== warmup_min_items_threshold

The `value` must be an integer, which specifies the minimum number of items that should be available in memory during warmup, before data-serving commences.
The minimum is `0`, the maximum `100`.

The following example sets `warmup_min_items_threshold` to 100:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param warmup_min_items_threshold 100
----

If successful, the command returns the following:

----
setting param: warmup_min_items_threshold 100
set warmup_min_items_threshold to 100
----

=== num_reader_threads

The `value` must be an integer, which specifies the number of _reader_ threads to be used.
The minimum (and default) is `4`; the maximum is `64`.
See xref:learn:buckets-memory-and-storage/storage.adoc#threading[Threading], for information.

The following example sets the number of reader threads to `8`:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param num_reader_threads 8
----

If successful, the command returns the following:

----
setting param: num_reader_threads 8
set num_reader_threads to 8
----

=== num_writer_threads

The `value` must be an integer, which specifies the number of _writer_ threads to be used.
The minimum (and default) is `4`; the maximum is `64`.
See xref:learn:buckets-memory-and-storage/storage.adoc#threading[Threading], for information.

The following example sets the number of writer threads to `8`:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param num_writer_threads 8
----

If successful, the command returns the following:

----
setting param: num_writer_threads 8
set num_writer_threads to 8
----

=== num_auxio_threads

The `value` must be an integer, which specifies the number of threads allocated to auxillary I/O operations.

The follow example sets the number of auxillary I/O threads to `4`:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param num_auxio_threads 4
----

If successful, the command returns the following:

----
setting param: num_auxio_threads 4
set num_auxio_threads to 4
----

=== num_nonio_threads

The `value` must be an integer, which specifies the number of threads allocated to non-I/O operations.

The follow example sets the number of non-I/O threads to `4`:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param num_nonio_threads 4
----

If successful, the command returns the following:

----
setting param: num_nonio_threads 4
set num_nonio_threads to 4
----

=== xattr_enabled

The `value` must be a Boolean, which specifies whether xref:learn:data/extended-attributes-fundamentals.adoc[Extended Attributes] are enabled for the bucket: `true` enables, `false` disables.
The default is `true`.

The following example enables extended attributes for the bucket:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password\
-b travel-sample \
set flush_param xattr_enabled true
----

If successful, the command returns the following:

----
setting param: xattr_enabled true
set xattr_enabled to true
----

=== mem_used_merge_threshold_percent

The `value` must be an integer, which is a percentage.
This percentage is used to calculate the threshold at which a per core memory counter is accumulated into a global memory counter.
If _n_ is specified, the parameter is calculated as follows: _n_% of `max_size` / _number-of-CPUs_.

In the following example, `mem_used_merge_threshold_percent` is specified as 30:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param mem_used_merge_threshold_percent 30
----

If successful, the command returns the following:

----
setting param: mem_used_merge_threshold_percent 30
set mem_used_merge_threshold_percent to 30
----

== Errors

Failure to specify a bucket produces the following error message: `No access to bucket:default - permission denied or bucket does not exist.`
A malformed command produces the error `cbepctl: error: Unknown command`.
Improperly specified credentials return an error message similar to `Authentication error for user:Administrat3or bucket:travel-sample`.
Use of the wrong port-number displays the error `Connection error: [Errno 111] Connection refused`.

Incorrectly specifying a parameter returns the error `Error: Bad parameter <specified-parameter>`.
Specifying a `value` greater than the maximum permitted returns the error `Error: KEY_ENOENT : Not Found :`.
