= set flush_param
:page-topic-type: reference

[abstract]
The `set flush_param` command establishes bucket parameters for managing the reading and writing of data.

== Description

The `set flush_param` command  establishes parameters for scanning, memory thresholds, compaction, queue management, compression ratios, defragmentation, expiration, and threading.
The command is applied with reference to a specific bucket and a specific node: therefore, the new parameters are applied to the vBuckets that correspond to the named bucket, on the specified node.
All settings take effect immediately.
Parameter-modifications are _not_ persistent across node-restarts: therefore, following node-restart, the command should be executed again if necessary, to re-establish the modifications.

== Syntax and Examples

The syntax for `set flush_param` is as follows:
----
cbepctl [host]:11210 -b [bucket-name] -u [administrator-name]
  -p [administrator-password] set flush_param [parameter] [value]
----

The options for `parameter` and the associated `value` are as follows:

=== access_scanner_enabled

The `value` must be a Boolean, specifying whether the _access scanner_ is enabled or disabled: `true` enables, `false` disables.

The following example enables the access scanner for the bucket `travel-sample` on the specified node:

----
/opt/couchbase/bin/cbepctl 10.143.186.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param access_scanner_enabled true
----

If successful, the command returns the following:

----
setting param: access_scanner_enabled true
set access_scanner_enabled to true
----

=== alog_sleep_time

The `value` must be an integer specifying the interval that must elapse between successive runs of the access scanner, in minutes.

The following example specifies that two minutes should elapse:

----
/opt/couchbase/bin/cbepctl 10.143.186.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param alog_sleep_time 2
----

If successful, the command returns the following:

----
setting param: alog_sleep_time 2
set alog_sleep_time to 2
----

=== alog_task_time

The `value` must be an integer that specifies the hour, in UTC time, at which the access scanner is next scheduled to run: minimum value is `0`, maximum is `23`.

The following example specifies that the access scanner should next run at 12:00 noon:

----
/opt/couchbase/bin/cbepctl 10.143.186.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param alog_task_time 12
----

If successful, the command returns the following:

----
setting param: alog_task_time 12
set alog_task_time to 12
----

=== backfill_mem_threshold

The `value` must be an integer that represents a percentage of the memory assigned to the named bucket.
When this percentage of the bucket's memory is full, _backfill tasks_ are backed off.

The following example sets `backfill_mem_threshold` to 80%.

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param backfill_mem_threshold 80
----

If successful, the command returns the following:

----
setting param: backfill_mem_threshold 80
set backfill_mem_threshold to 80
----

=== bg_fetch_delay

The `value` must be an integer that represents the number of seconds that must elapse before a background fetch is executed.

The following example sets `bg_fetch_delay` to 3.

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param bg_fetch_delay 3
----

If successful, the command returns the following:

----
setting param: bg_fetch_delay 3
set bg_fetch_delay to 3
----

=== bfilter_enabled

The `value` must be a Boolean: `true` enables _Bloom filters_; `false` disables.

_Bloom filters_, which are enabled by default, improve the performance of cache management when _ejection_ for the bucket has been configured (at the time of bucket-creation) to _full_.
(See xref:learn:data/buckets.adoc[Buckets]).

The following example enables Bloom filters for the `travel-sample` bucket, on the specified node:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param bfilter_enabled true
----

If successful, the command returns the following:

----
setting param: bfilter_enabled true
set bfilter_enabled to true
----

=== bfilter_residency_threshold

The `value` must be a floating point number, specifying the resident ratio-threshold below which all items will be considered in the bloom filters, when the ejection-policy has been set to _full_.
The minimum value is `0.0`, the maximum `1.0`.

The following example establishes the ratio-threshold as `0.5`:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param bfilter_residency_threshold 0.5
----
If successful, the command returns the following:

----
setting param: bfilter_residency_threshold 0.5
set bfilter_residency_threshold to 0.5
----

=== compaction_exp_mem_threshold

The `value` must be an integer, which represents the threshold, as a percentage, of the memory-quota for the named bucket, above which the compaction process will not queue expired documents for deletion.

The following example sets `compaction_exp_mem_threshold` to 65%:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param compaction_exp_mem_threshold 65
----

If successful, the command returns the following:

----
setting param: compaction_exp_mem_threshold 65
set compaction_exp_mem_threshold to 65
----

=== compaction_write_queue_cap

The `value` must be an integer, specifying, as a percentage, the _disk write queue threshold_, above which compaction tasks are made to sleep, if pending compaction tasks already exist in the queue.

The following example sets `compaction_write_queue_cap` to 65%:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param compaction_write_queue_cap 65
----

If successful, the command returns the following:

----
setting param: compaction_write_queue_cap 65
set compaction_write_queue_cap to 65
----

=== dcp_min_compression_ratio

The `value` must be a floating point number, which represents the minimum accepted ratio of the document's size in compressed form, to its size in uncompressed form.
If a document is to be written that is already in compressed form and its compression ratio is either equal to or greater than the minimum, it will be transmitted in that form by any DCP producer, to any DCP consumer that has compression enabled.
If the compression ratio of the document is less than the minimum, the document is transmitted in uncompressed form.
The minimum setting is `0.0`, the maximum `1.0`.

The following example sets `dcp_min_compression_ratio` to 0.3:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param dcp_min_compression_ratio 0.3
----

If the command is successful, it returns the following:

----
setting param: dcp_min_compression_ratio 0.3
set dcp_min_compression_ratio to 0.3
----

=== defragmenter_enabled

The `value` must be a Boolean: `true` enables the defragmenter, `false` disables.
The default is `true`.

The following example enables the defragmenter:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param defragmenter_enabled true
----

If successful, the command returns the following:

----
setting param: defragmenter_enabled true
set defragmenter_enabled to true
----

=== defragmenter_interval

The `value` must be an integer, specifying the number of seconds that is the period of time to elapse between successive runnings of the defragmenter, when enabled.

The following example sets the `defragmenter_interval` to 20 seconds:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param defragmenter_interval 20
----

If successful, the command returns the following:

----
setting param: defragmenter_interval 20
set defragmenter_interval to 20
----

=== defragmenter_age_threshold

The `value` must be an integer, specifying how _old_ a document must be, in terms of how many times the defragmenter has been run since the document's creation, before it is to be considered a candidate for degragmentation.

The following example sets the value of `defragmenter_age_threshold` to 3:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param defragmenter_age_threshold 3
----

If successful, the command returns the following:

----
setting param: defragmenter_age_threshold 3
set defragmenter_age_threshold to 3
----

=== defragmenter_chunk_duration

The `value` must be an integer, which specifies the number of milliseconds for which the defragmenter runs, before being paused, so as to resume after the established `defragmenter_interval`.

The following example sets the `defragmenter_chunk_duration` to 1000:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param defragmenter_chunk_duration 1000
----

If successful, the command returns the following:

----
setting param: defragmenter_chunk_duration 1000
set defragmenter_chunk_duration to 1000
----

=== exp_pager_enabled

The `value` must be a Boolean: `true` enables the _expiry pager_; `false` disables.
See xref:learn:buckets-memory-and-storage/memory.adoc#expiry-pager[Expiry Pager].

The following example enables the expiry pager:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param exp_pager_enabled true
----

If successful, the command returns the following:

----
setting param: exp_pager_enabled true
set exp_pager_enabled to true
----

=== exp_pager_stime

The `value` must be an integer, which specifies the number of minutes that must elapse between successive runs of the expiry pager.

The following example sets `exp_pager_stime` to 3:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param exp_pager_stime 3
----

If successful, the command returns the following:

----
setting param: exp_pager_stime 3
set exp_pager_stime to 3
----

=== exp_pager_initial_run_time

The `value` must be _either_:

* An integer from `0` to `23`, specifying the hour at which the first run of the expiry pager will occur.

* `disable`: which causes the expiry pager to be run after `exp_pager_stime` has elapsed.

The following example disables `exp_pager_initial_run_time`:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param exp_pager_initial_run_time disable
----

If successful, the command returns the following:

----
setting param: exp_pager_initial_run_time -1
set exp_pager_initial_run_time to -1
----

=== item_compressor_interval

The `value` must be an integer, specifying the time (in milliseconds) that must elapse between successive runs of the _item compressor_.

The following example sets the `item_compressor_interval` to 2000:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param item_compressor_interval 2000
----

If successful, the command returns the following:

----
setting param: item_compressor_interval 2000
set item_compressor_interval to 2000
----

=== item_compressor_chunk_duration

The `value` must be an integer, which specifies (in milliseconds) the duration for which the item compressor will run, before pausing, and resuming following the established `item_compressor_interval`.

The following example sets the `item_compressor_chunk_duration` to 1000:

----
/opt/couchbase/bin/cbepctl 10.143.194.101:11210 \
-u Administrator -p password \
-b travel-sample \
set flush_param item_compressor_chunk_duration 1000
----

If successful, the command returns the following:

----
setting param: item_compressor_chunk_duration 1000
set item_compressor_chunk_duration to 1000
----

alog_sleep_time, alog_task_time::
Couchbase Server has an optimized xref:learn:buckets-memory-and-storage/memory.adoc#initialization-and-warmup[disk warmup].
Couchbase Server pre-fetches a list of most-frequently accessed keys and fetches these documents first.
The server runs a periodic scanner process which determines which keys are most frequently used.
The `cbepctl flush_param` command is used to change the initial time and the interval for the process.
For example, the initial time and interval might be changed to accommodate a peak time when an application needs these keys to be quickly available.
+
By default, the scanner process runs once every 24 hours at 10:00 AM GMT.
To reduce the cluster-wide impact of running this task, stagger the start time to a different value on each node in the cluster.

exp_pager_stime::
The `cbepctl flush_param exp_pager_stime` command sets the time interval for disk cleanup.
Couchbase Server does lazy xref:learn:buckets-memory-and-storage/memory.adoc#expiry-pager[expiration], that is, expired items are flagged as deleted rather than being immediately erased.
Couchbase Server has a maintenance process that periodically looks through all information and erases expired items.
By default, this maintenance process runs every 60 minutes, but it can be configured to run at a different interval.
+
NOTE: The compaction process will also remove expired items.

mem_low_wat, mem_high_wat, pager_active_vb_pcnt::
xref:learn:buckets-memory-and-storage/memory.adoc#ejection[Ejection] means that documents are removed from RAM but the key and metadata remain.
If the amount of RAM used by items reaches the high water mark (upper threshold), both active and replica data are ejected until the memory usage (amount of RAM consumed) reaches the low water mark (lower threshold).
The server determines that items are not recently used based on a not-recently-used (NRU) value.
+
Use the `mem_low_wat`, `mem_high_wat`, and `pager_active_vb_pcnt` settings to change the server thresholds for ejection.
+
WARNING: Do not change the ejection defaults unless required by Couchbase Support.

mutation_mem_threshold::
By default, Couchbase Server sends clients a temporary out-of-memory error message if RAM is 95% consumed and only 5% RAM remains for overhead.
Use the `cbepctl set flush_param mutation_mem-threshold` command parameter to change this threshold value.
+
NOTE: Do not change this default to a higher value.
However, this value might be reduced if you need more RAM for system overhead such as disk queue or for server data structures.

== Options

The following are the command options:

.set flush_param options
|===
| Option | Description

| `alog_sleep_time`
| Access scanner interval (minute)

| `alog_task_time`
| Access scanner next task time (UTC)

| `backfile_mem_threshold`
| Memory threshold (%) on the current bucket quota before backfill task is made to back off.

| `bg_fetch_delay`
| Delay before executing a bg fetch (test feature).

| `couch_response_timeout`
| timeout in receiving a response from CouchDB.

| `exp_pager_stime`
| Expiry Pager interval.
Time interval that Couchbase Server waits before it performs cleanup and removal of expired items from disk.
Setting this value to `0` will disable the Expiry Pager from running.

| `flushall_enabled`
| Deprecated.
Enable flush operation.

| `pager_active_vb_pcnt`
| Percentage of active vBuckets items among all ejected items by item pager.

| `max_size`
| Maximum memory used by the server.

| `mem_high_wat`
| High water mark in bytes.

| `mem_low_wat`
| Low water mark in bytes.

| `mutation_mem_threshold`
| Amount of RAM that can be consumed in that caching layer before clients start receiving temporary out of memory messages.

| `timing_log`
| Path to log detailed timing stats.

| `warmup_min_memory_threshold`
| Memory threshold (%) during warmup to enable traffic.

| `warmup_min_items_threshold`
| Item number threshold (%) during warmup to enable traffic.

| `klog_compactor_queue_cap`
| Queue cap to throttle the log compactor.

| `klog_max_log_size`
| Maximum size of a mutation log file allowed.

| `klog_max_entry_ratio`
| Max ratio of # of items logged to # of unique items.

| `pager_unbiased_period`
| Period after last access scanner run during which item pager preserve working set.

| `queue_age_cap`
| Maximum queue age before flushing data.

| `max_txn_size`
| Maximum number of items in a flusher transaction.

| `min_data_age`
| Minimum data age before flushing data.

| `item_compressor_interval`
| How often the item compressor task should be run, in milliseconds.
Default value is 250.

| `item_compressor_chunk_duration`
| Maximum time, in milliseconds, for which the item compressor task is run, before being paused, and then resumed according to the established `item_compressor_interval`.
Default value is 20.

| `min_compression_ratio`
| Minimum allowed ratio of each item's uncompressed form to its compressed form.
If the actual ratio is less than this value, the item is stored in uncompressed form.
Default value is 1.2.
|===

NOTE: *%* You must use the percentage sign in order to set the value by percentage.

== Examples

*Examples for setting the access scanner process*

To change the time interval when the access scanner process runs to every 20 minutes.

----
cbepctl 10.5.2.117:11210 -b foo-bucket -u Administrator -p password \
set flush_param alog_sleep_time 20
----

To change the initial time that the access scanner process runs from the 2:00 AM UTC default to 11:00 PM UTC.

----
cbepctl 10.5.2.117:11210 -b foo-bucket -u Administrator -p password \
set flush_param alog_task_time 23
----

This response shows the time interval changed to 20 minutes.

----
setting param: alog_sleep_time 20
set alog_sleep_time to 20
----

This response shows the initial access scanner run time changed to 11:00 PM UTC.

----
setting param: alog_task_time 23
set alog_task_time to 23
----

*Examples for setting the disk cleanup*

The following example sets the cleanup process to run every 600 seconds (10 minutes).
This is the interval that Couchbase Server waits before it tries to remove expired items from disk.

----
cbepctl 10.5.2.117:11210 -b foo-bucket -u Administrator -p password \
set flush_param exp_pager_stime 600
----

The following example response shows the cleanup process set to 600 seconds.

----
setting param: exp_pager_stime 600
set exp_pager_stime to 600
----

*Examples for setting the out-of-memory error message*

In this example, the threshold is reduced to 65% of RAM.

----
cbepctl 10.5.2.117:11210 -b foo-bucket -u Administrator -p password \
set flush_param mutation_mem_threshold 65%
----

The following example response shows the RAM threshold set to 65%.

----
setting param: mutation_mem_threshold 65
set mutation_mem_threshold to 65
----

*Example for setting the low water mark*

The low water mark sets the lower threshold of RAM for a specific bucket on a node.
The item pager stops ejecting items once the low water mark is reached.

The following example sets the low water mark percentage to 70% of RAM.

----
cbepctl 10.5.2.117:11210 -b foo-bucket -u Administrator -p password \
set flush_param mem_low_wat 70%
----

*Example for setting the high water mark*

The high water mark set the amount of RAM consumed by items that must be breached before infrequently used active and replica items are ejected.

The following example sets the high water mark percentage to 80% of RAM for a specific bucket on a node.
This means that items in RAM on this node can consume up to 80% of RAM before the item pager begins ejecting items.

----
cbepctl 10.5.2.117:11210 -b foo-bucket -u Administrator -p password \
set flush_param mem_high_wat 80%
----

*Examples for setting percentage of ejected items*

Based on the NRU algorithm, the server ejects active and replica data from a node.
By default, the server is configured to 60% active items and 40% replica data from a node.

The following example increases the percentage of active items that can be ejected from a node to 50%.

----
cbepctl 10.5.2.117:11210 -b foo-bucket -u Administrator -p password \
set flush_param pager_active_vb_pcnt 50
----

Be aware of potential performance implications when changing the percentage of ejected items.
It may be more desirable to eject as many replica items as possible and limit the amount of active data that can be ejected.
By doing so, active data from a source node is maximized while maintaining incoming requests to that node.
However, if the server is ejecting a very large percentage of replica data and a node fails, the replica data is not immediately available.
In this case, the items are retrieved from disk and put back into RAM before the request is fulfilled.

The following example response shows the low water mark, high water mark, and percentage of ejected items being set.

----
setting param: mem_low_wat 70
set mem_low_wat to 70

setting param: mem_high_wat 80
set mem_high_wat to 80

setting param: pager_active_vb_pcnt 50
set pager_active_vb_pcnt to 50
----
