= set vbucket_param
:page-topic-type: reference

[abstract]
The `set vbucket_param` command establishes the `max_cas` of a specific vBucket.

== Description

The `set vbucket_param` command establishes the `max_cas` of a specific vBucket.
The settings takes effect immediately, but is _not_ persistent across node-restarts: therefore, following a node-restart, the command should be executed again if necessary, to re-establish the desired setting.

This and all other `cbepctl` commands are intended for use either _by_ or _under the strict and explicit guidance of_ Couchbase Customer Support.

== Syntax and Example

The syntax for `set vbucket_param` is as follows:
----
cbepctl [host]:11210 -b [bucket-name] -u [administrator-name]
  -p [administrator-password] set vbucket_param [parameter] [vbucket-id] [value]
----

The `parameter` must be `max_cas`.
Its associated `vbucket-id` must be a vBucket ID.
The `value` must be an integer, which specifies the new `max_cas` for the vBucket.
The specified integer will be interpreted as an unsigned 64-bit integer.
