= bucket-edit
:page-topic-type: reference

[abstract]
Modifies an existing bucket.

== Syntax

The basic syntax is:

----
couchbase-cli bucket-edit -c [host]:8091 -u [admin] -p [password] [options]
----

== Description

The command [.cmd]`bucket-edit` edits an existing bucket.
It has the subset of options available for the other [.cmd]`bucket-*` commands.

== Options

The following are the command options:

.bucket-edit options
[cols="25,44"]
|===
| Option | Description

| `--bucket=BUCKETNAME`
| Named bucket to act on.

| `--bucket-eviction-policy=[valueOnly{vbar}fullEviction]`
a|
Define the eviction policy: full eviction or value-only eviction.

IMPORTANT: Changing the bucket ejection policy will invoke a bucket restart, resulting in temporary inaccessibility of data while the bucket warms up.

| `--bucket-password=PASSWORD`
| Bucket password.

| `--bucket-priority=[low{vbar}high]`
a|
Bucket priority compared to other buckets.

IMPORTANT: Changing the bucket priority will invoke a bucket restart, resulting in temporary inaccessibility of data while the bucket warms up.

| `--bucket-ramsize=RAMSIZEMB`
a|
Bucket RAM quota in MB.

NOTE: This option does not apply to memcached-style buckets since you cannot change the RAM quota on a memcached bucket.

| `--bucket-replica=COUNT`
| Replication count.

| `--bucket-type=TYPE`
| Bucket type, either memcached or Couchbase.

| `--enable-flush=[0{vbar}1]`
| Enables and disables flush (enable=1, disable=0).
|===

== Examples

To edit a bucket for RAM size:

----
couchbase-cli bucket-edit -c 192.168.0.1:8091 -u Administrator -p password \
--bucket=test_bucket --bucket-ramsize=200
----

To modify a bucket to high priority:

----
couchbase-cli bucket-edit -c 192.168.0.1:8091 -u Administrator -p password \
--bucket=test_bucket --bucket-priority=high
----

To modify a dedicated port bucket and set the eviction policy to `fullEviction`:

----
couchbase-cli bucket-edit -c 192.168.0.1:8091 -u Administrator -p password \
--bucket=test_bucket --bucket-ramsize=400 \
--bucket-eviction-policy=fullEviction --enable-flush=1
----
