= collect-logs-start
:page-topic-type: reference

[abstract]
Starts the cluster-wide log collection.

== Syntax

The basic syntax is:

----
couchbase-cli collect-logs-start -c [host]:8091 -u [admin] -p [password]
        { --nodes=node1,node2,... | --all-nodes }
        [--upload --upload-host=host --customer=name [--ticket=ticketNumber ] ]
----

== Description

This command initiates a log collection process.
You must specify whether to collect logs from all nodes or only from the specified nodes.

You can optionally request that the logs be uploaded to Couchbase Server, in which case you must include the name of your organization and (optionally) a support ticket number.

== Options

The following are the command options:

.collect-logs-start options
[cols="117,100"]
|===
| Option | Description

| `--customer=name`
| Name of the customer sending the logs.
This name is mandatory when the option `--upload` is specified.

| `--nodes=HOST[:PORT],HOST[:PORT]`
| Specifies the subset of nodes from which the logs are collected.

| `--ticket=ticketNumber`
| Number of the support ticket (optional)

| `--upload`
| Collects logs to a specified host.

| `--upload-host=host`
| The host to which the logs are uploaded.
This name is mandatory when the option `--upload` is specified.
|===

== Examples

To upload all logs from the customer ABC to a specified server and connect it with the support ticket AB12345.
The upload host is a remote internet server such as AWS S3.

----
couchbase-cli collect-logs-start -c 192.168.0.1:8091 -u Administrator -p password \
--all-nodes --upload-host=192.200.0.1:8091 --customer=ABC --ticket=AB12345
----
