[#cbcli-node-recovery]
= [.cmd]`recovery`

[abstract]
Recovers one or more servers.

== Syntax

The basic syntax is:

----
couchbase-cli recovery -c [host]:8091 -u [admin] -p [password]
    --server-recovery=[host]:[port]
    --recovery-type=[delta|full]
----

== Description

To re-add a server node to a cluster, use the [.cmd]`recovery` command with the `--recovery-type` parameter.

== Options

The following are the command options:

.Recovery options
[#table_recovery-type,cols="103,100"]
|===
| Option | Description

| `--server-recovery=[host]:[port]`
| Server to recover

| `--recovery-type=[delta|full]`
| Type of recovery to be performed for the node: `delta` or `full`.
|===

== Examples

To set incremental node recovery type for a server:

----
couchbase-cli recovery -c 192.168.0.1:8091 -u Administrator -p password \   	
--server-recovery=192.168.0.2	--recovery-type=delta
----

*Example sequence: Set failover, re-add, recover, and rebalance*

The following example shows a failover, readd, recovery and rebalance operations in a sequence:

. A node in a cluster is gracefully failed over.
. The node is re-added to the cluster.
. Delta recovery is implemented for the node.
. The rebalancing operation is implemented.

----
couchbase-cli failover -c 192.168.0.1:8091 -u Administrator -p password \   	
--server-failover=192.168.0.2
----

----
couchbase-cli server-readd -c 192.168.0.1:8091 -u Administrator -p password \    	
--server-add=192.168.0.2
----

----
couchbase-cli recovery -c 192.168.0.1:8091 -u Administrator -p password \    	
--server-recovery=192.168.0.2 --recovery-type=delta
----

----
couchbase-cli rebalance -c 192.168.0.1:8091 -u Administrator -p password
----
