[#reference_u1v_x45_ls]
= [.cmd]`server-readd`

[abstract]
Re-adds the failed-over server.

== Syntax

The basic syntax is:

----
couchbase-cli server-readd -c [host]:8091 -u [admin] -p [password] [options]
----

== Description

Use this command to re-add the failed-over server to the cluster.

WARNING: The `server-readd` command is deprecated.
Use the xref:cbcli/server-readd.adoc[recovery command] instead, which allows you to specify a recovery method.

== Options

The following are the command options:

.server-readd options
[cols="123,100"]
|===
| Options | Description

| `--server-add=HOST[:PORT]`
| Server to re-add to the cluster.

| `--server-add-username=USERNAME`
| The administrator username to re-add the server.

| `--server-add-password=PASSWORD`
| The administrator password to re-add the server.

| `--group-name=GROUPNAME`
| The group to which this server belongs (Enterprise Edition only).
|===

== Examples

Re-adds the server to the cluster::

----
couchbase-cli server-readd -c 192.168.0.1:8091 -u Administrator -p password
----
