= setting-ldap
:page-topic-type: reference

[abstract]
Set the Lightweight Directory Access Protocol (LDAP) settings.

== Syntax

The basic syntax is:

----
couchbase-cli setting-ldap -c [host]:8091 -u [admin] -p [password]
    [options]
----

NOTE: LDAP cannot be used for the bucket authentication.

== Description

Use this command to set various options for LDAP.

== Options

The following are the command options:

.setting-ldap options
[cols="5,8"]
|===
| Options | Description

| `--ldap-admins=`
| Setting up full LDAP administrators, comma-separated.

| `--ldap-roadmins=`
| Setting up a read-only LDAP administrators, comma-separated.

| `--ldap-enabled=[0{vbar}1]`
| Enables the LDAP protocol for authentication (yes=1, no=0).

| `--ldap-default=[admin {vbar} roadmins {vbar} none]`
| Sets the default LDAP accounts.
|===

== Examples

Set the full LDAP administrator AdminLDAP and enable the LDAP protocol for authentication:

----
couchbase-cli setting-ldap -c 192.168.0.1:8091 -u Administrator -p password \
--ldap-admins AdmninLDAP --ldap-enabled 1
----

*Response*

Unless you are running Couchbase Server Enterprise Edition on Linux that supports LDAP authentication, you will get an error message:

----
ERROR: unable to set LDAP auth settings (400) Bad Request
       This http API endpoint is only supported in enterprise edition running on GNU/Linux
----
