[#feedback]
= Providing Feedback

[abstract]
We look forward to your feedback about Couchbase Server and provide several ways you can send us your comments.

. Open a browser and log in to the https://issues.couchbase.com/[Couchbase issue tracker].
+
The [.uicontrol]*Create Issue* form is displayed.
. {blank}
+
Select [.uicontrol]*Couchbase Server* project for Server issues, a client library project for SDK issues, or [.uicontrol]*Couchbase Documentation* for documentation issues.
. {blank}
+
Select [.uicontrol]*Bug* if the product isn't behaving as you expected or [.uicontrol]*Improvement* to suggest improvements to the existing behavior.
. {blank}
 .. [.uicontrol]*Summary*: Enter a one-line title that summarizes the issue.
 .. [.uicontrol]*Affected Version*: Select [.uicontrol]*4.5*
 .. [.uicontrol]*Environment*: Enter a full description of your environment, including operating system, client SDK name and version, deployment model.
For the deployment model information, indicate whether it's a multinode or single node installation, and which enabled services you have enabled (data, index, and query).
 .. [.uicontrol]*Description*: Enter a detailed description of the issue.
Describe what you were doing, what your expected results are, and the actual results.
You can also upload attachments with additional information.
. {blank}
