= Release Notes for Couchbase Server 7.1
:description: Couchbase Server 7.1 introduces scopes and collections, which provide new database organization structures within Couchbase.

{description} It also brings new capabilities to the Query Service in addition to support for scopes and collections.

Take a look at xref:introduction:whats-new.adoc[What's New?] for a list of new features and improvements in this release.

[#release-710]
== Release 7.1 (May 2022)

Couchbase Server 7.1 was released in May 2022.
This release contains new features and fixes to issues.

[#new-features-improvements-710]
=== New Features

This section highlights the notable new features and improvements in this release.

* Couchbase Server now permits multiple root certificates to maintained in a _trust store_ for the cluster.
See xref:learn:security/using-multiple-cas.adoc[Using Multiple Root Certificates].

* Couchbase Server now supports _PKCS #1_ and _PKCS #8_ &#8212; in each case, only for use with private keys.
See xref:learn:security/certificates.adoc#private-key-formats[Private Key Formats].

* Registration procedures are now provided for encrypted private keys associated with node-certificates.
See xref:rest-api:upload-retrieve-node-cert.adoc#json-passphrase-registration[JSON Passphrase Registration].

* _System Events_ are now provided, to record significant events on the cluster.
See xref:learn:clusters-and-availability/system-events.adoc[System Events].

* New roles are provided for the administration of _Sync Gateway_, especially in the context of Couchbase Capella.
These roles are listed at xref:learn:security/roles.adoc[Roles].

* TLS 1.3 cipher-suites can now by used by all services; and by the Cluster Manager, XDCR, and Views.
See xref:learn:security/on-the-wire-security.adoc[On the Wire Security].

[#supported-platforms-710]
=== New Supported Platforms

This release adds support for the following platforms:

* MacOS Big Sur for development only

* Amazon Linux (ARM)

See xref:install:install-platforms.adoc[Supported Platforms] for the complete list of supported platforms.


[#fixed-issues-710]
=== Fixed Issues

This section highlights the notable issues fixed in this release.

==== XDCR

[#table_fixedissues_v71-clustermanager,cols="25,66"]
|===
|Issue | Description

| https://issues.couchbase.com/browse/MB-9982[MB-9982^]
| *Summary*: XDCR should be incremental on topology changes.

XDCR checkpointing is now entirely persistent through topology-changes on the source cluster.
This provides improved performance when failover and rebalance occur on the source cluster.

|===

[#known-issues-701]
=== Known Issues

This section highlights some of the known issues in this release.

==== Query Service

[#table-known-issues-701-query-service, cols="25,66"]
|===
|Issue | Description


| https://issues.couchbase.com/browse/MB-50936[MB-50936^]
| *Summary*: Implement defs.CheckMixedModeCallback for mixed mode checks

Any attempt to execute a function with N1QL udfs replicated from a 7.1 node will fail with "no library found in worker" on a 7.0.x node.

*Workaround*: If possible, all nodes in cluster should be running under version 7.1 or higher.
|===
