= Release Notes for Couchbase Server 6.5 Beta

Couchbase Server 6.5 Beta brings many sought-after relational capabilities to the NoSQL world.
This release seeks to improve developer agility, reduce total cost of ownership, enhance manageability, and provide more enterprise-grade security and performance. 

include::ROOT:partial$beta-disclaimer.adoc[tag=admonition]

Take a look at xref:introduction:whats-new.adoc[What's New?] for a list of new features and improvements in this release.

[#release-650]
== Release 6.5.0

Couchbase Server 6.5 Beta was released in August 2019.

[#changes-in-behavior-650]
=== Major Changes in Behavior from Previous Releases

This section notes major changes in behavior from previous releases.

==== Backup and Restore

===== Compression

In the previous versions of Couchbase Server, value compression always occurred on the backup client. 

Starting with version 6.5, `cbbackupmgr` will leverage Server compression and back up the documents as compressed whenever possible.
If the data is compressed by default, it will be backed up as compressed.
If the data is not compressed, it will be compressed first and then backed up when value compression is opted. This improves the performance by reducing the size of the data set to back up for transmission on the pipe and for the backup itself.

==== Networking

This release introduces the following networking changes:

* The Search Service now uses port 9130 / 19130 for node-to-node traffic.
+
The Search Service also no longer uses an encrypted port unless xref:learn:clusters-and-availability/node-to-node-encryption.adoc[node-to-node encryption] is enabled.
In Couchbase Server 6.0 Enterprise Edition, the Search Service explicitly required encrypted port 18094 for xref:learn:services-and-indexes/services/search-service.adoc[scatter-gather] operations between nodes running the Search Service (even if you were still using unencrypted port 8094 for client-to-node traffic).
Starting in Couchbase Server 6.5, the Search Service uses gRPC over port 9130 / 19130 for all node-to-node traffic, and no longer uses an encrypted port for intra-cluster communication unless xref:learn:clusters-and-availability/node-to-node-encryption.adoc[node-to-node encryption] is enabled.

* The amount of required ports in the 21100-21299 range has been drastically reduced, and are effectively replaced by the following ports for purposes of cluster management traffic and communication:
** 21100 / 21150: Node-to-node communication
** 21200 / 21250: Node-local communication
** 21300 / 21350: Node-local communication

For more information about required network ports, refer to xref:install:install-ports.adoc[Network and Firewall Requirements].

[#supported-platforms-650]
=== New Supported Platforms

This release adds support for the following platforms:

* CentOS 8
* macOS 10.14 "Mojave" (Development only)
* Oracle Linux 8
* SUSE Linux Enterprise Server 15
* Microsoft Windows Server 2019

See xref:install:install-platforms.adoc[Supported Platforms] for the complete list of supported platforms.

[#deprecation-650]
=== Deprecated and Removed Platforms

Starting with this release, the following platforms are no longer supported:

* CentOS 6
* macOS 10.12 "Sierra"
* Oracle Linux 6
* Red Hat Enterprise Linux 6
* SUSE Linux Enterprise Server 11
* Windows Server 2012

Starting with this release, the following browsers are no longer supported:

* Microsoft Internet Explorer


[#known-issues-650]
=== Known Issues

This section highlights some of the known issues in this release. 

==== Analytics Service

[#table_knownissues_v650-analytics,cols="25,66"]
|===
| Issue | Description

| https://issues.couchbase.com/browse/MB-35385[MB-35385^]
| *Summary:* When node to node encryption is enabled, the Analytics service restarts to bind the ports using the right protocol. However, if a request comes in before the service is ready, it returns an HTTP 500 error.
|===

==== Eventing Service

[#table_knownissues_v650-eventing,cols="25,66"]
|===
| Issue | Description

| https://issues.couchbase.com/browse/MB-31639[MB-31639^]
| *Summary*: The `cbbackupmgr` utility fails to backup a cluster with Eventing service for a user with "Data Backup & Restore" role.

| https://issues.couchbase.com/browse/MB-30772[MB-30772^]
| *Summary*: Killing an Eventing process externally may result in a loss of timers that have been dequeued but not run to completion.
|===

==== Index Service and Views

[#table_knownissues_v650-gsi-views,cols="25,66"]
|===
| Issue | Description

| https://issues.couchbase.com/browse/MB-19869[MB-19869^]
| *Summary*: Rebalance fails when taking out failedover nodes running views, in certain circumstances.
|===

==== Install and Upgrade

[#table_knownissues_v650-install-upgrade,cols="25,66"]
|===
| Issue | Description

| https://issues.couchbase.com/browse/MB-35448[MB-35448^]
| *Summary*: When upgrading to version 6.5, `rpm -U` does not automatically shutdown and startup Couchbase Server. 

| https://issues.couchbase.com/browse/MB-33522[MB-33522^]
| *Summary*: The `cbupgrade` script fails to upgrade single node IPv6 clusters.
|===

==== Query Service

[#table_knownissues_v650-query,cols="25,66"]
|===
| Issue | Description

| https://issues.couchbase.com/browse/MB-35463[MB-35463^]
| *Summary*: Returning an array from a N1QL JavaScript function results in a failure.

| https://issues.couchbase.com/browse/MB-35444[MB-35444^]
| *Summary*: A JOIN query is found to hang in some scenarios.

| https://issues.couchbase.com/browse/MB-35007[MB-35007^]
| *Summary*: A runtime error may be seen when an inline function is using a secondary index. 
|===

==== Tools, Web Console (UI), and REST API

[#table_knownissues_v650-tools-ui-rest-api,cols="25,66"]
|===
| Issue | Description

| https://issues.couchbase.com/browse/MB-35305[MB-35305^]
| *Summary*: The progress bar for `cbbackupmgr` is incorrect when there is a high purge sequence number.

| https://issues.couchbase.com/browse/MB-35111[MB-35111^]
| *Summary*: The rollback logic on DCP disconnect incorrectly reports that the backup was successful and hence does not retry.
|===

[#fixed-issues-650]
=== Fixed Issues

See the Couchbase https://issues.couchbase.com/issues/?filter=17532[issue tracker^] for the list of fixes in this release.


