= enableReplicaCatchupOnRebalance

When `disableFileTransferRebalance` is `false`, the rebalance process copies FTS index partitions between nodes instead of regenerating them from scratch.
It tracks its progress when copying active index partitions by comparing the partition sequence numbers between the source and target nodes.
This progress tracking helps the rebalance process make sure that it copies all of the partitions to the target.

By default, the rebalance process does not track its progress when copying replica index partitions. 
Not having rebalance track its duplication of replica index partitions reduces its overhead. 
However, it does increase the possibility that later rebalances could encounter issues.

By setting the `enableReplicaCatchupOnRebalance` option to `true`, you can have rebalances track their progress when copying replica index partitions.
Enabling this option has rebalance track its duplication of replica partitions the same way it tracks its duplication active partitions.  
Using this option increases the overhead of performing a rebalance. 

NOTE: This option only has an effect when `disableFileTransferRebalance` is `false`.
If `disableFileTransferRebalance` is `true`, rebalance does not copy index partitions.
See xref:fts:fts-advanced-settings-disable-file-transfer-rebalance.adoc[] for additional information.

.Enable replica catchup during rebalance
[source,console]
----
curl -XPUT -H "Content-type:application/json" \
http://<Administrator>:<pwd>@<node>:8094/api/managerOptions \
 -d '{"enableReplicaCatchupOnRebalance": "true"}' 
----

To turn off having rebalances track their progress of copying replica partitions, use the following command:

.Disable replica catchup during rebalance
[source,console]
----
curl -XPUT -H "Content-type:application/json" \
http://<Administrator>:<pwd>@<node>:8094/api/managerOptions \
 -d '{"enableReplicaCatchupOnRebalance": "false"}' 
----