= Index Creation Options

In order to answer complex questions against text. FTS indexes have to be highly configurable because languages are varied, flexible and rich. The Search service provides a number of options to customize these indexes either during their creation or their subsequent modification.

Choosing the right configuration to meet your application’s objective ensures that your index has both good performance and minimal resource requirements. 

See the  [text analysis with FTS blog](https://blog.couchbase.com/full-text_search_text_analysis/) to understand various phases of the text analysis in FTS.  You can also play with different analyzers on [blevesearch site](http://bleveanalysis.couchbase.com/analysis).

The various configuration options for Full Text Index are as follows:

* xref:fts-type-identifiers.adoc[Type Identifiers]
* xref:fts-type-mappings.adoc[Type Mappings]
* xref:fts-index-analyzers.adoc[Index Analyzers]
* xref:fts-custom-filters.adoc[Custom Filters]
* xref:fts-date-time-parsers.adoc[Date Time Parsers]
* xref:fts-default-settings.adoc[Default Settings]
* xref:fts-index-replicas.adoc[Index Replicas]
* xref:fts-index-type.adoc[Index Type]
* xref:fts-index-partitions.adoc[Index Partitioning]
