= Point Query

[abstract]
A GeoJSON Point Query against any GeoJSON type.

[.status]#Couchbase Server 7.1.2#

= Point Query

A GeoJSON query via a GeoShape of Point to GeoJSON types in the index using the 3 relations intersects, contains, and within.

== Point `Intersects` Query

A point `intersection` query sample is given below.

[source, json]
----
{
  "query": {
    "field": "<<fieldName>>",
    "geometry": {
      "shape": {
        "type": "point",
        "coordinates": [1.954764, 50.962097]
      },
      "relation": "intersects"
    }
  }
}
----

Intersection rules for the Query Point in the GeoShape with other indexed GeoJSON shapes in the document set are as given below.

[#geospatial-distance-units,cols="1,2"]
|===
| Intersects (relation) +
Document Shape|{nbsp} +
Point (GeoShape)

| Point
| Matches when the query point overlaps the point in the document (as point is a non-closed shapes).

| LineString
| Matches when the query point overlaps any of the line endpoints in the document (as linestring is a non-closed shapes).

| Polygon
| Matches when the query point lies within the area of the polygon.

| MultiPoint
| Matches when the query point overlaps with any of the many points in the multipoint array in the document.

| MultiLineString
| Matches when the query point overlaps with any of the linestring endpoints in the multilinestring array in the document.

| MultiPolygon
| Matches when the query point lies within the area of any of the polygons in the multipolygon array in the document.

| GeometryCollection
| Matches when the query point overlaps with any of the heterogeneous (above 6) shapes in the geometrycollection array in the document.

| Circle
| Matches when the query point lies within the area of the circular region in the document.

| Envelope
| Matches when the query point lies within the area of the rectangular/bounded box region in the document.

|=== 

== Point `Contains` Query

As the point is a non-closed/single spot there is no difference between `intersects` and `contains` query for this GeoShape.
The guiding rules for the `contains` relation are exactly similar to that `intersects`.

A point `contains` query sample is given below.

[source, json]
----
{
  "query": {
    "field": "<<fieldName>>",
    "geometry": {
      "shape": {
        "type": "point",
        "coordinates": [1.954764, 50.962097]
      },
      "relation": "contains"
    }
  }
}
----
 
== Point `WithIn` Query

As the point is a non-closed shape, it is not possible for it to contain any larger shapes other than just the point itself.

A point `contains` query sample is given below.

[source, json]
----
{
  "query": {
    "field": " << fieldName >> ",
    "geometry": {
      "shape": {
        "type": "point",
        "coordinates": [1.954764, 50.962097]
      },
      "relation": "within"
    }
  }
}
----
 
[#geospatial-distance-units,cols="1,2"]
|===
| WithIn (relation) +
Document Shape|{nbsp} +
Point (GeoShape)

| Point (document shape)
| Matches when the query point is exactly the same point in the document.

|===
