= Scopes and Collections
:description: pass:q[The Couchbase Enterprise Server 7.0 provides _collections_ and _scopes_.]
:page-status: Developer Preview

[abstract]
{description}
Only a subset of the planned functionality is included in order to support early access and experimentation.

[#scopes-introduction]
== Scopes
A _scope_ is a mechanism for the grouping of multiple collections.
Up to 100 scopes can be created per bucket. Collection-names must be unique within their scope.

Collections might be assigned to different scopes according to content-type, or to deployment-phase (i.e., test versus production). Applications can be assigned per-scope access rights, allowing each application to access only those collections it requires.

[#collections-and-scopes]
== Collections

A _collection_ is a data container, defined on Couchbase Server, within a bucket whose type is either _Couchbase_ or _Ephemeral_.
Up to 1000 collections can be created per bucket.

Bucket-items can optionally be assigned to different collections according to content type.
For example, within a bucket that contains travel information, documents that relate specifically to _airports_ might be assigned to an _airports_ collection, while documents that relate to _hotels_ might be assigned to a _hotels_ collection, and so on.


[#naming-for-scopes-and-collection]
== Naming for Scopes and Collections

User-defined scopes and collections must be assigned user-defined names.
Such names:

* Must be between 1 and 30 characters in length.
* Can only contain the characters `A-Z`, `a-z`, `0-9`, and the symbols `_`, `-`, and `%`.
* Cannot start with `_` or `%`.

[#default-scope-and-collection]
== Default Scope and Collection

In the Developer Preview, every created bucket is automatically given a _default scope_, and within it, a _default collection_.
Each is named `_default`.
All documents created within the bucket without reference to specific scopes or collections are saved in the default collection within the default scope.
The default scope and collection cannot be dropped.

[#bucket-set-up]
== Bucket Set-Up

Scopes and collections exist within _buckets_.
Therefore, to test scopes and collections, at least one bucket must be created.
The following options are available for bucket-creation:

* xref:manage:manage-buckets/create-bucket.adoc[Couchbase Web Console]
* xref:rest-api:rest-bucket-create.adoc[Couchbase REST API]
* xref:cli:cbcli/couchbase-cli-bucket-create.adoc[Couchbase CLI]

The examples provided in this section use a bucket named `testBucket`, which is created in turn with the REST API and CLI.
Note that the CLI examples demonstrate how to use the `cbstats` command to return information on collections, including the number of documents each contains.
To provide documents to be counted, the `cbc create` CLI facility is used.

[#limitations]
== Limitations

The following limitations apply to scopes and collections, as made available in Developer Preview mode, in Couchbase Server Enterprise Edition 6.5:

* Scopes and collections are supported by the Data Service only.
This means that _key-value_ data-access _can_ be experimented with.

* Scopes and collections are _not_ supported by the Index, Query, Search, Eventing, and Analytics Services.
This means that data-access by means of these services should _not_ be attempted, using any bucket within which a scope or collection has been explicitly created.
Note that these services _will_ provide support for scopes and collections in future.

* Scopes and collections are _not_ supported by _Role-Based Access Control_: therefore, access to individual scopes and collections cannot be permitted or denied on the basis of assigned _roles_.
Note that Role-Based Access Control _will_ provide support for scopes and collections in future.


