= Understanding Queries

[abstract]
Full Text Search allows queries to be performed on Full Text Indexes.
Queries can be performed by means of the Couchbase Web Console, the Couchbase REST API, N1QL (using xref:n1ql:n1ql-language-reference/searchfun.adoc[search functions] in the Query service), or the Couchbase SDK.

[#query-specification-options]
== Query-Specification Options

Full Text Search allows a range of query options.
These include:

* Input-text and target-text can be _analyzed_: this transforms input-text into _token-streams_, according to different specified criteria, so allowing richer and more finely controlled forms of text-matching.
* The _fuzziness_ of a query can be specified, so that the scope of matches can be constrained to a particular level of exactitude.
A high degree of fuzziness means that a large number of partial matches may be returned.
* Multiple queries can be specified for simultaneous processing, with one given a higher _boost_ than another; so ensuring that its results are returned at the top of the set.
* _Regular expressions_ and _wildcards_ can be used in text-specification for search-input.
* _Compound_ queries can be designed, such that an appropriate conjunction or disjunction of the total result-set can be returned.

All the above options, and others, are explained in detail on the page xref:fts-query-types.adoc[Query Types].

For information on how to execute queries, see xref:fts-performing-searches.adoc[Performing Searches].

[#sorting-results]
== Sorting Results

The results returned from a Full Text Search can be _sorted_: by *id*, *score*, *field*, and more.
Details are provided in xref:fts-sorting.adoc[Sorting Query Results].

[#query-response-objects]
== Query Response Objects

Every Full Text Search query provides a _response object_.
This contains the query-result; and consists of individual child-objects that respectively contain _status_, a _request-copy_, the number of _hits_ (or matches) achieved, and (optionally) _facets_, which provide aggregation information.

[#scan-consistency]
=== Scan Consistency
__Optional__

To specify the consistency guarantee/constraint for index scanning, the accepted values are:

``::
This is the default mode of operation. An empty string represents the "not_bounded" setting - no timestamp vector is used in the index scan.
This is the fastest mode, because it avoids the costs of obtaining the vector and waiting for the index to catch up to the vector.

`at_plus`::
This implements bounded consistency.
The request includes a scan_vector parameter and value, which is used as a lower bound.
This can be used to implement read-your-own-writes (RYOW).

----
{
  "explain": true,
  "fields": [],
  "query": {
      ...
  },
  "ctl": {
    "consistency": {
      "level": "at_plus"
    }
  }
}
----

For full information, see xref:fts-response-object-schema.adoc[Handling Response Objects].
