= Supported Queries
:page-aliases: query-types.adoc 

[abstract]
With Full Text Search you can perform queries on Full Text Indexes. You can perform the queries either by using Couchbase Web Console, the Couchbase REST API, N1QL (using search functions in the Query service), or the Couchbase SDK.

[#query-specification-options]
== Query-Specification Options

Full Text Search allows a range of query options. These include:

* Input-text and target-text can be _analyzed_: this transforms input-text into _token-streams_, according to different specified criteria, so allowing richer and more finely controlled forms of text-matching.
* The _fuzziness_ of a query can be specified so that the scope of matches can be constrained to a particular level of exactitude.
A high degree of fuzziness means that a large number of partial matches may be returned.
* Multiple queries can be specified for simultaneous processing, with one given a higher _boost_ than another, so ensuring that its results are returned at the top of the set.
* _Regular expressions_ and _wildcards_ can be used in text-specification for search-input.
* _Compound_ queries can be designed, such that appropriate conjunction or disjunction of the total result-set can be returned.

All the above options, and others, are explained in detail on the page xref:fts-query-types.adoc[Query Types].

For information on how to execute queries, see xref:fts-performing-searches.adoc[Performing Searches].

This section includes the following supported queries:

* xref:fts-supported-queries-match.adoc[Match]
* xref:fts-supported-queries-term.adoc[Term]
* xref:fts-supported-queries-numeric-range.adoc[Numeric range]
* xref:fts-supported-queries-phrase.adoc[Phrase]
* xref:fts-supported-queries-geo-spatial.adoc[Geo spatial]

