= Geospatial Queries

[abstract]
_Geospatial_ queries return documents that contain location in either legacy Geopoint format or standard GeoJson

== Geopoint (type geopoint)

Legacy or Geopoint documents which specify a geographical location. 

For these queries the Search service lets the users index the single dimensional geopoint/location fields and perform various bounding queries like point-distance, bounded-rectangle and bounded-polygon against the indexed geopoint field.  

For higher level shapes and structures refer to GeoJSON below.

== GeoJSON (type geojson)

For these queries the Search service supports higher dimensional patial structures that enable the users to approximate a large variety of real life shapes like a postal or jurisdictional region boundaries, a route for a delivery vehicle or an airline career or the boundaries of various water bodies like a river, lake, stream etc. 

In particular the Search service now supports the GeoJSON spatial data formats on spherical geodesics in release 7.1.2. 

GeoJSON is a geospatial data interchange format based on JavaScript Object Notation (JSON).
It defines several types of JSON objects and the manner in which they are combined to represent data about geographic features, their properties, and their spatial extents. 
GeoJSON uses a geographic coordinate reference system, World Geodetic System 1984, and units of decimal degrees.  

In particular the Search service supports the GeoJSON spatial data formats on https://s2geometry.io/devguide/s2cell_hierarchy.html[spherical geodesics] via S2 cells.

This new support for GeoJSON standards https://www.rfc-editor.org/rfc/rfc7946[RFC 7946] allows users to address use cases like:

- Finding all the documents with any GeoJSON shapes that contain the query shape.
- Finding all the documents with any GeoJSON shapes that reside within the query shape.
- Finding all the documents with any GeoJSON shapes that intersect with the query shape.

And the supported GeoJSON shapes in the Search service are:

- Point
- LineString
- Polygon
- MultiPoint
- MultiLineString
- MultiPolygon
- GeometryCollection

In addition to the above shapes, Search also supports a couple of additional custom shapes to make the spatial approximations easier for users to utilize.  The two extra shapes supported are:

- Circle
- Envelope
