= ftsMemoryQuota

The `ftsMemoryQuota` setting controls the maximum usable memory for the FTS Search service from the total amount of RAM available in the system. 

Sparing enough RAM memory for the filesystem cache is crucial to override the ftsMemoryQuota.

The FTS Search service recommends a minimum of 512 MB memory-resident ratio for its index. However, users can spare more memory quota for a healthy resident ratio of the index. This lets the system have sufficient memory available to perform indexing, querying, or other lifecycle operations like rebalances, etc.

Using the manager option, users can control the FTS/Search service's memory quota at run time without a service reboot.

== Spare enough memory for filesystem cache
Another important aspect while configuring the Search memory quota is to leave sufficient leeway RAM for the Operating System to manage the file system cache.

The Search’s internal text indexing library (bleve) uses memory mapping for the index files, so having enough RAM extra for the operating system helps in keeping the hot regions of index files in the file system cache memory. 

This helps in better search performance.
The usual guideline is to set the Search memory quota to 60-70% of the available RAM in a Search node.

Configuring enough RAM memory in the system and allocating sufficient Search quota memory is essential for optimal search performance.

=== Example

[source,console]
----
curl -XPUT -H "Content-type:application/json" http://username:password@<ip>:8094/api/managerOptions \-d '{
    "ftsMemoryQuota": "1024"
}
----