= Searching with SDK

[.column]
=== {empty}
[.content]
Couchbase provides several SDKs to allow applications to access a Couchbase cluster and Mobile SDKs to carry the application to the edge. 


.Links to various SDK documentation

[[analyzer_languages_5.5]]
[cols="1,4,4"]
|===
| SDK | Details | Link

|C SDK
|The Couchbase C SDK (`libcouchbase`) enables C and C++ programs to access a Couchbase Server cluster.
The C SDK is also commonly used as a core dependency of SDKs written in other languages to provide a common implementation and high performance.
Libcouchbase also contains the `cbc` suite of command line tools.
|xref:3.3@c-sdk:howtos:full-text-searching-with-sdk.adoc[C SDK 3.3]

| .NET SDK
| The .NET SDK enables you to interact with a Couchbase Server cluster from the .NET Framework using any Common Language Runtime (CLR) language, including C#, F#, and VB.NET. 
It offers both a traditional synchronous API and an asynchronous API based on the Task-based Asynchronous Pattern (TAP).
|xref:3.3@dotnet-sdk:howtos:full-text-searching-with-sdk.adoc[.NET SDK 3.3]

|Go SDK
|The Couchbase Go SDK allows you to connect to a Couchbase Server cluster from Go.
The Go SDK is a native Go library and uses the high-performance `gocbcore` to handle communicating to the cluster over Couchbase's binary protocols.
|xref:2.5@go-sdk:howtos:full-text-searching-with-sdk.adoc[Go SDK 2.5]

| Java SDK
| The Java SDK forms the cornerstone of our JVM clients.
It allows Java applications to access a Couchbase Server cluster.
The Java SDK offers traditional synchronous APIs and scalable asynchronous APIs to maximize performance.
|xref:3.3@java-sdk:howtos:full-text-searching-with-sdk.adoc[Java SDK 3.3]

| Kotlin SDK
| Our new Kotlin SDK allows Kotlin applications to access a Couchbase Server cluster.
|xref:1.0@kotlin-sdk:howtos:full-text-search.adoc[Kotlin SDK 1.0]

|Node.js SDK
|he Node.js SDK allows you to connect to a Couchbase Server cluster from Node.js.
The Node.js SDK is a native Node.js module using the very fast `libcouchbase` library to handle the communication with the cluster over the Couchbase binary protocol.
|xref:4.1@nodejs-sdk:howtos:full-text-searching-with-sdk.adoc[Node.js SDK 4.1]

|PHP SDK
|The PHP SDK allows you to connect to a Couchbase Server cluster from PHP.
The PHP SDK is a native PHP extension and uses the Couchbase high-performance C library `libcouchbase` to handle the communication to the cluster over Couchbase binary protocols.
|xref:4.0@php-sdk:howtos:full-text-searching-with-sdk.adoc[PHP SDK 4.0]

|Python SDK
|The Python SDK allows Python applications to access a Couchbase Server cluster.
The Python SDK offers a traditional synchronous API and integration with twisted, gevent, and asyncio.
It depends on the C SDK (`libcouchbase`) and utilizes it for performance and reliability.
|xref:4.0@python-sdk:howtos:full-text-searching-with-sdk.adoc[Python SDK 4.0]

|Ruby SDK

|The Ruby SDK allows Ruby applications to access a Couchbase Server cluster. 
The Ruby SDK includes high-performance native Ruby extensions to handle communicating to the cluster over Couchbase's binary protocols.
|xref:3.3@ruby-sdk:howtos:full-text-searching-with-sdk.adoc[Ruby SDK 3.3]

| Scala SDK
| Our new Scala SDK allows Scala applications to access a Couchbase Server cluster.
It offers synchronous, asynchronous, and reactive APIs for flexibility and maximum performance.
|xref:1.3@scala-sdk:howtos:full-text-searching-with-sdk.adoc[Scala SDK 1.3]
