= Understanding Analyzers
:description: Analyzers increase search-awareness by transforming input text into token-streams, which permit the management of richer and more finely controlled forms of text-matching.

[abstract]
{description}
An analyzer consists of modules, each of which performs a particular, sequenced role in the transformation.

[#principles-of-text-analysis]
== Principles of Text-Analysis

_Analyzers_ pre-process input-text submitted for Full Text Search; typically, by removing characters that might prohibit certain match-options.

The analysis is performed on document-contents when indexes are created and is also performed on the input-text submitted for a search.
The benefit of analysis is often referred to as _language awareness_.

For example, if the input-text for a search is `enjoyed staying here`, and the document-content contains the phrase `many enjoyable activities`, the dictionary-based words do not permit a match.
However, by using an analyzer that (by means of its inner _Token Filter_ component) _stems_ words, the input-text yields the tokens `enjoy`, `stay`, and `here`; while the document-content yields the tokens `enjoy` and `activ`.
By means of the common token `enjoy`, this permits a match between `enjoyed` and `enjoyable`.

Since different analyzers pre-process text in different ways, effective Full Text Search depends on the right choice of the analyzer, for the type of matches that are desired.

Couchbase Full Text Search provides a number of pre-constructed analyzers that can be used with Full Text Indexes.
Additionally, analyzers can be custom-created by means of the Couchbase Web Console.
The remainder of this page explains the architecture of analyzers and describes the modular components that Couchbase Full Text Search makes available for custom-creation.
It also lists the pre-constructed analyzers that are available and describes the modules that they contain.

For examples of both selecting and custom-creating analyzers by means of the Couchbase Web Console.

[#analyzer-architecture]
== Analyzer Architecture

Analyzers are built from modular components:

* *Character Filters* remove undesirable characters from input: for example, the `html` character filter removes HTML tags, and indexes HTML text-content alone.
* *Tokenizers* split input-strings into individual _tokens_, which together are made into a _token stream_.
The nature of the decision-making whereby splits are made, differs across tokenizers.
* *Token Filters* are chained together, with each performing additional post-processing on each token in the stream provided by the tokenizer.
This may include reducing tokens to the _stems_ of the dictionary-based words from which they were derived, removing any remaining punctuation from tokens, and removing certain tokens deemed unnecessary.

Each component-type is described in more detail below.
Note that these components can be used to custom-create an analyzer by means of the Couchbase Web Console.


