= size/from or offset/limit
:description: This pagination settings can be used to obtain a subset of results and works deterministically when combined with a certain sort order.

{description}

Using `size/limit` and `offset/from` would fetch at least `size + from` ordered results from a partition and then return the `size` number of results starting at offset `from`.

Deep pagination can therefore get pretty expensive when using `size + from` on a sharded index due to each shard having to possibly return large resultsets (at least `size + from`) over the network for merging at the coordinating node before returning the `size` number of results starting at offset `from`.

The default sort order is based on _score_ (relevance) where the results are ordered from the highest to the lowest score.

== Example

Here's an example query that fetches results from the 11th onwards to the 15th that have been ordered by _score_ ..

----
{
  "query": {
      "match": "California",
      "field": "state"
  },
  "size": 5,
  "from": 10
}
----

#----
{
  "query": {
      "match": "California",
      "field": "state"
  },
  "offset": 5,
  "limit": 10
}
----#