= Consistency
:description: A mechanism to ensure that the Full Text Search (FTS) index can obtain the most upto date version of the document written to a collection or a bucket.

[abstract]
{description}

The consistency mechanism provides xref:fts-consistency-vectors.adoc[Consistency Vectors] as objects in the search query that ensures FTS index searches all your last data written to the vBucket. 

The search service does not respond to the query until the designated vBucket receives the correct sequence number. 

The search query remains blocked while continuously polling the vBucket for the requested data. Once the sequence number of the data is obtained, the query is executed over the data written to the vBucket.


When using this consistency mode, the query service will ensure that the indexes are synchronized with the data service before querying.

== Workflow to understand Consistency

1. Create an FTS index in Couchbase.
2. Write a document to the Couchbase cluster. 
3. Couchbase returns the associate vector to the app, which needs to issue a query request with the vector.
4. The FTS index starts searching the data written to the vBucket.

In this Workflow, it is possible that the document written to vBucket is not yet indexed. So, when FTS starts searching that document, the most up-to-date document versions are not retrieved, and only the indexed versions are queried.

Therefore, the Couchbase server provides a Consistency mechanism to overcome this issue and ensures that the FTS index can search the most upto date document written to vBucket.