= Sorting with Objects

Fine-grained control over sort-procedure can be achieved by specifying _objects_ as array-values in the `sort` field.

Each object can have the following fields:

* `by`: Sorts results on `id`, `score`, or a specified `field` in the Full Text Index.

* `field`: Specifies the name of a field on which to sort.
Used only if `field` has been specified as the value for the `by` field; otherwise ignored.

* `missing`: Specifies the sort-procedure for documents with a missing value in a field specified for sorting.
The value of `missing` can be `first`, in which case results with missing values appear _before_ other results; or `last` (the default), in which case they appear _after_.

* `mode`: Specifies the search-order for index-fields that contain multiple values (in consequence of arrays or multi-token analyzer-output).
The `default` order is undefined but deterministic, allowing the paging of results from `from (_offset_)`, with reliable ordering.
To sort using the minimum or maximum value, the value of `mode` should be set to either `min` or `max`.

* `type`: Specifies the type of the search-order field value. 
For example, `string` for text fields, `date` for DateTime fields, or `number` for numeric/geo fields.

To fetch more accurate sort results, we strongly recommend specifying the `type` of the sort fields in the sort section of the search request.

== Example

The example below shows how to specify the object-sort.

----
{
  "explain": false,
  "fields": [
     "*"
   ],
   "highlight": {},
   "query": {
     "match": "bathrobes",
     "field": "reviews.content",
     "analyzer": "standard"
   },
   "size" : 10,
   "sort": [
      {
       "by" : "field",
       "field" : "reviews.ratings.Overall",
       "mode" : "max",
       "missing" : "last",
       "type": "number"
      }
   ]
}
----

NOTE: The above sample assumes that the `travel-sample` bucket has been loaded, and a default index has been created on it. 

For information on loading sample buckets, see xref:manage:manage-settings/install-sample-buckets.adoc[Sample Buckets]. For instructions on creating a default Full Text Index by means of the Couchbase Web Console, see xref:fts-performing-searches.adoc[Performing Searches].

This query sorts search-results based on `reviews.ratings.Overall` — a field that is normally multi-valued because it contains an array of different users' ratings.

When there are multiple values, the highest `Overall` ratings are used for sorting.

Hotels with no `Overall` rating are placed at the end.

The following example shows how the `sort` field accepts _combinations_ of strings and objects as its value.

----
{
   
   "sort": [
      "country",
      {
       "by" : "field",
       "field" : "reviews.ratings.Overall",
       "mode" : "max",
       "missing" : "last",
        "type": "number"
      },
      {
       "by" : "field",
       "field" : "reviews.ratings.Location",
       "mode" : "max",
       "missing" : "last",
       "type": "number"
      },
      "-_score"
   ]
}
----

