[[fn-array-position,ARRAY_POSITION()]]
= ARRAY_POSITION([.var]`expr`, [.var]`val`)

== Description
This function returns the first position of the specified [.var]`value` within the array [.var]`expression`.

The array position is zero-based; that is, the first position is 0.

See also <<fn-array-binary-search>>.

== Arguments
expr:: [Required] The array you want to search.

val:: [Required] The value whose position you want to know.

== Return Values
An integer representing the first position of the input [.var]`val`, where the first position is 0.
If the value [.var]`val` occurs more than once within the array [.var]`expr`, only the first position is returned.

It returns -1 if the input [.var]`val` does not exist in the array.

If one of the arguments is `MISSING`, it returns `MISSING`.

If either of the arguments are non-array values, it returns `NULL`.

== Example

Find which position "Brian Kilback" is in the `public_likes` array.

[source,n1ql]
----
SELECT ARRAY_POSITION(t.public_likes, "Brian Kilback") AS array_position
FROM `travel-sample` t
WHERE type="hotel"
LIMIT 1;
----

.Results
[source,json]
----
[
  {
    "array_position": 4
  }
]
----