= Pre-Constructed Analyzers

A number of pre-constructed analyzers are available, and can be selected from the Couchbase Web Console.
For examples of selection, see xref:fts-creating-indexes.adoc[Creating Indexes].
The basic analyzers are as follows.
See the sections above for details on the referenced analyzer-components.

* *keyword*: Creates a single token representing the entire input, which is otherwise unchanged.
This forces exact matches, and preserves characters such as spaces.
* *simple*: Analysis by means of the *Unicode* tokenizer and the *to_lower* token filter.
* *standard*: Analysis by means of the *Unicode* tokenizer, the *to_lower* token filter, and the *stop* token filter.
* *web*: Analysis by means of the *Web* tokenizer and the  *to_lower* token filter.

Additionally, a range of analyzers is provided for the specific support of certain languages; as shown by the table immediately below.

.Supported Analyzer Languages
[[analyzer_languages_5.5]]
[cols="1,4"]
|===
| Name | Language

| ar
| Arabic

| cjk
| Chinese {vbar} Japanese {vbar} Korean

| ckb
| Kurdish

| da
| Danish

| de
| German

| en
| English

| es
| Spanish (Castilian)

| fa
| Persian

| fi
| Finnish

| fr
| French

| hi
| Hindi

| hu
| Hungarian

| it
| Italian

| nl
| Dutch

| no
| Norwegian

| pt
| Portuguese

| ro
| Romanian

| ru
| Russian

| sv
| Swedish

| tr
| Turkish
|===
