= Query Types

[abstract]
Couchbase Full Text Search supports multiple types of query.

[#introduction-to-query-types]
== Introduction to Query Types

Full Text Search allows text-data to be _queried_.
Multiple options are provided for ensuring the right kinds of match.
This page describes the purpose of each query-type, and provides sample JSON objects that indicate how queries can be constructed.

Available query-types include:

Simple Queries:: Accept input-text in the form of words and phrases, and attempt to find matches across bodies of text that have been _indexed_.
_Analyzers_ are applied to both input and target, potentially to strip out unnecessary characters, reduce words to the basic stems on which matching should occur, handle punctuation, and more.
Additionally, match accuracy-levels can be specified; and multiple queries can be expressed together, with their respective priorities _boosted_, (to ensure their results' prominence in the eventual result-set).
Compound Queries:: Accept multiple queries simultaneously, and return either the _conjunction_ of results from the result-sets, or a _disjunction_.
Range Queries:: Accept ranges for dates and numbers, and return documents that contain values within those ranges.
Query String Queries:: Accept _query strings_, which express query-requirements in a special syntax.
Geospatial Queries:: Accept _longitude_-_latitude_ coordinate pairs, in order to return documents that specify a geographical location.
Non-Analytic Queries:: Accept words and phrases on which exact matches only are returned.
No analysis is performed.
Special Queries:: For testing purposes, return either all of the documents in an index, or none.

These query-types are explained in greater detail below.
Examples are provided, using the Couchbase REST API query-syntax.
(Note that Full Text Search can also be performed with the Couchbase Web Console and the Couchbase SDK.)
The JSON data refers to the `travel-sample` bucket, and assumes that demonstration full text indexes have been created, as described in xref:fts-demonstration-indexes.adoc[Demonstration Indexes].

To run the examples using `curl`, use the following syntax:

[source,console]
----
$ curl -u Administrator:password -X POST -H "Content-Type: application/json" \
  -d '{your query in JSON here...}' \
  http://localhost:8094/api/index/index_name/query
----

Note that the examples below show only the JSON fragments that constitute non-generic parts of the queries they describe.
For actual use in a Full Text Search, these JSON fragments should be wrapped in the following generic configuration:

[source,json]
----
{
  "explain": false,
  "fields": [
    "*"
  ],
  "highlight": {},
  "query":{ your_query_details_here }
}
----

For more information on using the REST API to perform queries, see xref:fts-searching-with-the-rest-api.adoc[Searching with the REST API].

[#simple-queries]
== Simple Queries

[[match-query]]
=== Match Query

A match query _analyzes_ input text, and uses the results to query an index.
Options include specifying an analyzer, performing a _fuzzy match_, and performing a _prefix match_.
By default, the analyzer used for the input-text is that previously used on the target-text, during index-creation.
For information on analyzers, see xref:fts-using-analyzers.adoc[Understanding Analyzers].

When fuzzy matching is used, if the single parameter is set to a non-zero integer, the analyzed text is matched with a corresponding level of fuzziness.
The maximum supported fuzziness is 2.

When a prefix match is used, the [.param]`prefix_length` parameter specifies that for a match to occur, a prefix of specified length must be shared by the input-term and the target text-element.

The following JSON object demonstrates specification of a match query:

[source,json]
----
{
 "match": "location hostel",
 "field": "reviews.content",
 "analyzer": "standard",
 "fuzziness": 2,
 "prefix_length": 4
}
----

A match query is also demonstrated by means of the Java SDK, in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].

[[match-phrase-query]]
=== Match Phrase Query

The input text is analyzed, and a phrase query is built with the terms resulting from the analysis.
This type of query searches for terms in the target that occur _in the positions and offsets indicated by the input_: this depends on _term vectors_, which must have been included in the creation of the index used for the search.

For example, a match phrase query for `location for functions` is matched with `locate the function`, if the standard analyzer is used: this analyzer uses a _stemmer_, which tokenizes `location` and `locate` to `locat`, and reduces `functions` and `function` to `function`.
Additionally, the analyzer employs _stop_ removal, which removes small and less significant words from input and target text, so that matches are attempted on only the more significant elements of vocabulary: in this case  `for` and `the` are removed.
Following this processing, the tokens `locat` and `function` are recognized as _common to both input and target_; and also as being both _in the same sequence as_, and _at the same distance from_ one another; and therefore a match is made.

[source,json]
----
{
 "match_phrase": "very nice",
 "field": "reviews.content"
}
----

A match phrase query is also demonstrated by means of the Java SDK, in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].

=== Fuzzy Query

A _fuzzy query_ matches terms within a specified _edit_ (or _Levenshtein_) distance: meaning that terms are considered to match when they are to a specified degree _similar_, rather than _exact_.
A common prefix of a stated length may be also specified as a requirement for matching.

Fuzziness is specified by means of a single integer.
For example:

[source,json]
----
{
 "term": "interest",
 "field": "reviews.content",
 "fuzziness": 2
}
----

__Fuzziness__ is demonstrated by means of the Java SDK, in the context of the _term query_ (see below), in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].
Note that two such queries are specified, with the difference in fuzziness between them resulting in different forms of match, and different sizes of result-sets.

=== Prefix Query

A _prefix_ query finds documents containing terms that start with the specified prefix.

[source,json]
----
{
 "prefix": "inter",
 "field": "reviews.content"
}
----

=== Regexp Query

A _regexp_ query finds documents containing terms that match the specified regular expression.

[source,json]
----
{
 "regexp": "inter.+",
 "field": "reviews.content"
}
----

A regexp query is also demonstrated by means of the Java SDK, in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].

=== Wildcard Query

A _wildcard_ query uses a wildcard expression, to search within individual terms for matches.
Wildcard expressions can be any single character (`?`) or zero to many characters (`*`).
Wildcard expressions can appear in the middle or end of a term, but not at the beginning.

[source,json]
----
{
 "wildcard": "inter*",
 "field": "reviews.content"
}
----

A wildcard query is also demonstrated by means of the Java SDK, in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].

=== Boolean Field Query

A _boolean field_ query searches fields that contain boolean `true` or `false` values.
A boolean field query searches the actual content of the field, and should not be confused with the <<boolean-query,boolean queries>> (described below, in the section on compound queries) that modify whether a query must, should, or must not be present.

[source,json]
----
{
 "bool": true,
 "field": "free_breakfast"
}
----

[#compound-queries]
== Compound Queries

=== Conjunction Query (AND)

A _conjunction_ query contains multiple _child queries_.
Its result documents must satisfy all of the child queries.

[source,json]
----
{
 "conjuncts":[
   {"field":"reviews.content", "match": "location"},
   {"field":"free_breakfast", "bool": true}
 ]
}
----

A conjunction query is also demonstrated by means of the Java SDK, in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].

=== Disjunction Query (OR)

A _disjunction_ query contains multiple _child queries_.
Its result documents must satisfy a configurable `min` number of child queries.
By default this `min` is set to 1.
For example, if three child queries — A, B, and C — are specified, a `min` of 1 specifies that the result documents should be those returned uniquely for A (with all returned uniquely for B and C, and all returned commonly for A, B, and C, omitted).

[source,json]
----
{
 "disjuncts":[
   {"field":"reviews.content", "match": "location"},
   {"field":"free_breakfast", "bool": true}
 ]
}
----

A disjunction query is also demonstrated by means of the Java SDK, in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].

[[boolean-query]]
=== Boolean Query

A _boolean query_ is a combination of conjunction and disjunction queries.
A boolean query takes three lists of queries:

* `must`: Result documents must satisfy all of these queries.
* `should`: Result documents should satisfy these queries.
* `must not`: Result documents must not satisfy any of these queries.

[source,json]
----
{
 "must": {
   "conjuncts":[{"field":"reviews.content", "match": "location"}]},
 "must_not": {
   "disjuncts": [{"field":"free_breakfast", "bool": false}]},
 "should": {
   "disjuncts": [{"field":"free_breakfast", "bool": true}]}
}
----

=== Doc ID Query

A _doc ID_ query returns the indexed document or documents among the specified set.
This is typically used in conjunction queries, to restrict the scope of other queries’ output.

[source,json]
----
{ "ids": [ "hotel_10158", "hotel_10159" ] }
----

A doc ID Query is demonstrated by means of the Java SDK, in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].

[#range-queries]
== Range Queries

[[date-range]]
=== Date Range Query

A _date range_ query finds documents containing a date value, in the specified field within the specified range.
Dates should be in the format specified by https://www.ietf.org/rfc/rfc3339.txt[RFC-3339^], which is a specific profile of ISO-8601.
Define the endpoints using the fields [.param]`start` and [.param]`end`.
One endpoint can be omitted, but not both.
The [.param]`inclusiveStart` and [.param]`inclusiveEnd` properties in the query JSON control whether or not the endpoints are included or excluded.

[source,json]
----
{
 "start": "2001-10-09T10:20:30-08:00",
 "end": "2016-10-31",
 "inclusive_start": false,
 "inclusive_end": false,
 "field": "review_date"
}
----

[[numeric-range]]
=== Numeric Range Query

A _numeric range_ query finds documents containing a numeric value in the specified field within the specified range.
Define the endpoints using the fields [.param]`min` and [.param]`max`.
You can omit one endpoint, but not both.
The [.param]`inclusiveMin` and [.param]`inclusiveMax` properties control whether or not the endpoints are included or excluded.
By default, [.param]`min` is inclusive and [.param]`max` is exclusive.

[source,json]
----
{
 "min": 100, "max": 1000,
 "inclusive_min": false,
 "inclusive_max": false,
 "field": "id"
}
----

A numeric range Query is also demonstrated by means of the Java SDK, in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].

[#query-string-query-syntax]
== Query String Query

A _query string_ can be used, to express a given query by means of a special syntax.

[source,json]
----
{ "query": "+nice +view" }
----

A query string Query is demonstrated by means of the Java SDK, in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].
Note also that the Full Text Searches conducted with the Couchbase Web Console themselves use query strings.
(See xref:fts-searching-from-the-ui.adoc[Searching from the UI].)

Certain queries supported by FTS are not yet supported by the query string syntax.
This includes wildcards, regexp, and date range queries.

More detailed information is provided in xref:query-string-queries.adoc[Query String Queries].

[#non-analytic-queries]
== Non-Analytic Queries

_Term_ and _Phrase_ queries support no analysis on their inputs.
This means that only exact matches are returned.

In most cases, given the benefits of using analyzers, use of match and match phrase queries is preferable to that of term and phrase.
For information on analyzers, see xref:fts-using-analyzers.adoc[Understanding Analyzers].

=== Term Query

A _term_ query is the simplest possible query.
It performs an exact match in the index for the provided term.

[source,json]
----
{
  "term": "locate",
  "field": "reviews.content"
}
----

Term queries are also demonstrated by means of the Java SDK, in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].

=== Phrase Query

A _phrase query_ searches for terms occurring in the specified position and offsets.
It performs an exact term-match for all the phrase-constituents, without using an analyzer.

[source,json]
----
{
  "terms": ["nice", "view"],
  "field": "reviews.content"
}
----

A phrase query is also demonstrated by means of the Java SDK, in xref:java-sdk::full-text-searching-with-sdk.adoc[Searching with the SDK].

[#geospatial-queries]
== Geospatial Queries

_Geospatial_ queries return documents that each specify a geographical location.
Each query contains either:

* A single _longitude_-_latitude_ coordinate pair; and a _distance_ value, in miles, which determines a radius measured from the location specified by the coordinate pair.
Documents are returned if they specify (by means of a longitude-latitude coordinate pair) a location that lies within the radius.
* Two longitude-latitude coordinate pairs.
These are respectively taken to indicate the upper left and lower right corners of a bounding box.
Documents are returned if they specify a location that lies within the bounding box.

A geospatial query must be applied to an index that applies the _geopoint_ type mapping to the document-field that contains the target longitude-latitude coordinate pair.

More detailed information is provided in xref:fts-geospatial-queries.adoc[Geospatial Queries].

[#special-queries]
== Special Queries

_Special_ queries are usually employed either in combination with other queries, or to test the system.

=== Match All Query

Matches _all_ documents in an index, irrespective of terms.
For example, if an index is created on the `travel-sample` bucket for documents of type `zucchini`, the _match all_ query returns all document IDs from the `travel-sample` bucket, even though the bucket contains no documents of type `zucchini`.

[source,json]
----
{ "match_all": {} }
----

=== Match None Query

Matches no documents in the index.

[source,json]
----
{ "match_none": {} }
----
