= Consistency Vectors

Consistency Vectors: The value of the scan_vector parameter.

Scan vectors are built of two-element [value, guard] entries:

value: a vBucket’s sequence number (a JSON number)

guard: a vBucket’s UUID (a string)

Scan vectors have two forms:

Full scan vector: an array of [value, guard] entries, giving an entry for every vBucket in the system.

Sparse scan vectors: an object providing entries for specific vBuckets, mapping a vBucket number (a string) to each [value, guard] entry.

Example of a Sparse Scan Vector
{ "5 ": [5409393,"VB5ID"], "19": [47574574, "VB19ID"] }




== Example

----
{
  "ctl": {
    "timeout": 10000,
    "consistency": {
      "vectors": {
        "index1": {
          "607/205096593892159": 2,
          "640/298739127912798": 4
        }
      },
      "level": "at_plus"
    }
  },
  "query": {
    "match": "jack",
    "field": "name"
  }
}
----

== Consistency Vectors

In the above example - this is the consistency vectors.

----
"index1": {
  "607/205096593892159": 2,
  "640/298739127912798": 4
}
----

he query is looking within the FTS index "index1" - for ..


vbucket 607 (with UUID 205096593892159) to contain sequence number 2, and
vbucket 640 (with UUID 298739127912798) to contain sequence number 4
== Syntax

