= What's New in the Current Version?

This section lists the Full Text Search features added in this release:

* Support for Multi-node Setups - Full text search indexes now work over multiple nodes that have full text search service enabled.
Full text indexes are automatically distributed into fragments called _pindexes_, short for "partitioned indexes" that work very similarly to the way that buckets are physically distributed across Couchbase nodes running the data service.
* Dynamic Topology Support - Full text search not only runs on more than one full text search node, it also continues to work during topology changes.
For example, adding or removing nodes running the full text service will results in pindexes being moved to or from those nodes.
Full text indexes can also be replicated for enhanced availability.
Consult release notes for some beta limitations.
* Partial Results Queries - Every search returns the number of index partitions (pindexes) that succeeded along with the search hits from those indexes, merged and sorted into a single result set.
As a fault tolerance mechanism, an application developer has the option of using partial results if some pindexes fail to respond before timeout or respond with an error.
In many cases, even partial results may sufficient so that users can continue using an application, even with some documents missing from the search results.
Consider that most users don’t look past the first few pages of search results.
* Enhanced Indexing Performance - Full text search indexing is now much faster due to more effective use of memory.
* Support for Role Based Access Control (RBAC)
* Audit Logging - Full text search activities now appear in audit logs.
* Additional FTS Indexing and Query Statistics available.
