= Sorting with Strings

You can specify the value of the `sort` field as an array of strings.
These can be of three types:

* _field name_: Specifies the name of a field.
+
If multiple fields are included in the array, the sorting of documents begins according to their values for the field whose name is first in the array.
+
If any number of these values are identical, their documents are sorted again, this time according to their values for the field whose name is second; then, if any number of these values are identical, their documents are sorted a third time, this time according to their values for the field whose name is third; and so on.
+
Any document-field may be specified to hold the value on which sorting is to be based, provided that the field has been indexed in some way, whether dynamically or specifically.
+
The default sort-order is _ascending_.
If a field-name is prefixed with the `-` character, that field's results are sorted in _descending_ order.

* `_id`: Refers to the document identifier.
Whenever encountered in the array, causes sorting to occur by document identifer.

* `_score`: Refers to the score assigned the document in the result-set.
Whenever encountered in the array, causes sorting to occur by score.

== Example
#Need full example here#
----
"sort": ["country", "state", "city","-_score"]
----

This `sort` statement specifies that results will first be sorted by `country`.

If some documents are then found to have the same value in their `country` fields, they are re-sorted by `state`.

Next, if some of these documents are found to have the same value in their `state` fields, they are re-sorted by `city`.

Finally, if some of these documents are found to have the same value in their `city` fields, they are re-sorted by `score`, in _descending_ order.

The following JSON query demonstrates how and where the `sort` property can be specified:

----
{
  "explain": false,
  "fields": [
    "title"
  ],
  "highlight": {},
  "sort": ["country", "-_score","-_id"],
  "query":{
    "query": "beautiful pool"
  }
}
----

The following example shows how the `sort` field accepts _combinations_ of strings and objects as its value.

----
{
   ...
   "sort": [
      "country",
      {
       "by" : "field",
       "field" : "reviews.ratings.Overall",
       "mode" : "max",
       "missing" : "last",
        "type": "number"
      },
      {
       "by" : "field",
       "field" : "reviews.ratings.Location",
       "mode" : "max",
       "missing" : "last",
       "type": "number"
      },
      "-_score"
   ]
}
----