= Creating Indexes

NOTE: Full Text Searches are supported by specially purposed indexes, which can be created either from the Couchbase Web Console, or by means of the REST API.

== Indexes and Full Text Search
Every Full Text Search is performed on a user-created Full Text Index, which contains the targets on which searches are to be performed: these targets are values derived from the textual and other contents of documents within a specified bucket or collections within a scope.

Index-creation is highly configurable, and you can select various attributes to search the specific information. For example, documents can be user-grouped into different types (for example, airline documents versus hotel documents), different scopes (for example, inventory), and collections (for example, airport or hotel).

Based on the document-IDs, or the values of a designated document field, you can perform the following:

* Assign index mapping to each document type

* Assign analyzers to each index mapping

* Apply the index mapping to a specific subset of document fields

* Included or exclude the index mapping from the index

Additionally, searches can be performed across multiple buckets/scopes, by means of index aliases or across multiple collections in a scope by selecting the respective non-default scope/collection(s) option. 

== Multi Collection Index
The multi collection index helps users to perform search across multiple collections within a single scope from a single index.

Following are some of the use cases for multi collection indexes:

* Users have sliced the data across many collections where each collection or namespace could be either a customer account or the brand of a product. (homogeneous data across collections).

* Users have a lot of relatively small-sized collections in their data set due to the logical partitioning of the data. (heterogeneous data across collections).

In these use cases, users might have to create large number of indexes to enable the search on data across numerous collections. Multi-collection indexes are supposed to alleviate the overheads by just letting the user create an umbrella index covering many collections. These collections could be containing homogeneous or heterogeneous data.