= Creating Indexes

[abstract]
Full Text Searches are supported by specially purposed indexes, which can be created either from the Couchbase Web Console, or by means of the REST API.

The PUT request is the only way to create/update indexes. If the user does it from the UI/SDK - under the hood, it translates to HTTP PUT requests that curl does.
Specifying the "uuid" parameter in the index definition is required for the index introduction to be treated as a valid update. 

NOTE: This uuid has to match the one in the system already.
Upon a successful index creation/update, the uuid of the index will be re-initialized.

== Indexes and Full Text Search

Every Full Text Search is performed on a user-created Full Text Index, which contains the targets on which searches are to be performed: these targets are values derived from the textual and other contents of documents within a specified bucket or collections within a scope.

Index-creation is highly configurable, and you can select various attributes to search the specific information. For example, documents can be user-grouped into different types (for example, airline documents versus hotel documents), different scopes (for example, inventory), and collections (for example, airport or hotel).

Based on the document-IDs, or the values of a designated document field, you can perform the following:

* Assign index mapping to each document type

* Assign analyzers to each index mapping

* Apply the index mapping to a specific subset of document fields

* Included or exclude the index mapping from the index

Additionally, searches can be performed across multiple buckets/scopes, by means of index aliases or across multiple collections in a scope by selecting the respective non-default scope/collection(s) option. 

== Scopes and Collections

Couchbase Server Enterprise Edition provides _collections_ and _scopes_.

[#scopes-introduction]
=== Scopes
A _scope_ is a mechanism for the grouping of multiple collections.
Up to 100 scopes can be created per bucket. Collection-names must be unique within their scope.

Collections might be assigned to different scopes according to content-type, or to deployment-phase (i.e., test versus production). Applications can be assigned per-scope access rights, allowing each application to access only those collections it requires.

[#collections-and-scopes]
=== Collections

A _collection_ is a data container, defined on Couchbase Server, within a bucket whose type is either _Couchbase_ or _Ephemeral_.
Up to 1000 collections can be created per bucket.

Bucket-items can optionally be assigned to different collections according to content type.
For example, within a bucket that contains travel information, documents that relate specifically to _airports_ might be assigned to an _airports_ collection, while documents that relate to _hotels_ might be assigned to a _hotels_ collection, and so on.

[#naming-for-scopes-and-collection]
=== Naming for Scopes and Collections

User-defined scopes and collections must be assigned user-defined names.
Such names:

* Must be between 1 and 30 characters in length.
* Can only contain the characters `A-Z`, `a-z`, `0-9`, and the symbols `_`, `-`, and `%`.
* Cannot start with `_` or `%`.

[#default-scope-and-collection]
=== Default Scope and Collection

In the Developer Preview, every created bucket is automatically given a _default scope_, and within it, a _default collection_.
Each is named `_default`.
All documents created within the bucket without reference to specific scopes or collections are saved in the default collection within the default scope.

[#bucket-set-up]
=== Bucket Set-Up

Scopes and collections exist within _buckets_.
Therefore, to test scopes and collections, at least one bucket must be created.

NOTE: In case of a multi-bucket index, absence of a collection does not return an error.

The following options are available for creating a bucket:

* xref:manage:manage-buckets/create-bucket.adoc[Couchbase Web Console]
* xref:rest-api:rest-bucket-create.adoc[Couchbase REST API]
* xref:cli:cbcli/couchbase-cli-bucket-create.adoc[Couchbase CLI]

The examples provided in this section use a bucket named `testBucket`, which is created in turn with the REST API and CLI.
Note that the CLI examples demonstrate how to use the `cbstats` command to return information on collections, including the number of documents each contains.
To provide documents to be counted, the `cbc create` CLI facility is used.

== Multiple Collection Behavior

Couchbase's Full Text Search service is the only Couchbase service that can create indexes that span collections.

The result set of a query that references a multi-collection index returns the collection names alongside the document ID, making it easy for users to identify which collection a document belongs to.
 
//ADD a query example 
 
Users can issue collection(s) scoped queries against a multi-collection index. During search time, no validation is made to check whether the given collection names actually exist. As a result users won’t receive any validation errors for the invalid/incorrect collection(s) names within the search request.
 
//ADD a query example 
