= Full Text Search: Fundamentals
:description: pass:q[_Full Text Search_ (FTS) lets you create, manage, and query specially purposed _indexes_, defined on JSON documents within a Couchbase bucket.]

[abstract]
{description}

[#features-of-full-text-search]
== Features of Full Text Search

_Full Text Search_ provides Google-like search capability on JSON documents.
Couchbase's Global Secondary Indexes (GSI) can be used for range scans and regular pattern search, whereas FTS provides extensive capabilities for natural-language querying.
The query below looks for documents with all of the strings ("paris", "notre", "dame").

[source,json]
----
{
  "explain": false,
  "fields": [
    "*"
  ],
  "highlight": {},
  "query": {
    "query": "+paris +notre +dame"
   }
}
----

This query returns the following result (shown partially) from the FTS index scan on the travel-sample sample bucket.
For each matched document, the hits field shows the document id, the score, the fields in which a matched string occurs, and the position of the matched string.

[source,json]
----
"hits": [
    {
      "index": "trsample_623ab1fb8bfc1297_6ddbfb54",
      "id": "landmark_21603",
      "score": 2.1834097375254955,
      "locations": {
        "city": {
          "paris": [
            {
              "pos": 1,
              "start": 0,
              "end": 5,
              "array_positions": null
            }
          ]
        },
        "content": {
          "dame": [
            {
              "pos": 23,
              "start": 169,
              "end": 173,
              "array_positions": null
            },
...
]
----

Examples of natural language support include:

* _Language-aware_ searching; allowing users to search for, say, the word `beauties`, and additionally obtain results for `beauty` and `beautiful`.
* _Scoring_ of results, according to relevancy; allowing users to obtain result-sets that only contain documents awarded the highest scores.
This keeps result-sets manageably small, even when the total number of documents returned is extremely large.
* _Fast indexes_, which support a wide range of possible text-searches.

Full Text Search is powered by http://www.blevesearch.com/[Bleve^], an open source search and indexing library written in _Go_.
Full Text Search uses Bleve for the indexing of documents, and also makes available Bleve’s extensive range of _query types_.
These include:

* _Match_, _Match Phrase_, _Doc ID_, and _Prefix_ queries
* _Conjunction_, _Disjunction_, and _Boolean field_ queries
* _Numeric Range_ and _Date Range_ queries
* _Geospatial_ queries
* _Query String_ queries, which employ a special syntax to express the details of each query (see xref:fts-query-types.adoc#query-string-query-syntax[Query String Query] for information)

Full Text Search includes pre-built _text analyzers_ for the following languages: Arabic, CJK characters (Chinese, Japanese, and Korean), English, French, Hindi, Italian, Kurdish, Persian, and Portuguese.
Additional languages have been added to Couchbase Server 5.5.

== Authorization for Full Text Search

To access Full Text Search, users require appropriate _roles_.
The role *FTS Admin* must therefore be assigned to those who intend to create indexes; and the role *FTS Searcher* to those who intend to perform searches.
For information on creating users and assigning roles, see xref:learn:security/authorization-overview.adoc[Authorization].
