= Full Text Search: Fundamentals

[abstract]
_Full Text Search_ (FTS) lets you create, manage, and query specially purposed _indexes_, defined on JSON documents within a Couchbase bucket.

[#features-of-full-text-search]
== Features of Full Text Search

_Full Text Search_ provides Google-like search capability on JSON documents.
Couchbase's Global Secondary Indexes (GSI) can be used for range scans and regular pattern search, whereas FTS provides extensive capabilities for natural-language querying.
The query below looks for documents with all of the strings ("paris", "notre", "dame").

[source,json]
----
{
  "explain": false,
  "fields": [
    "*"
  ],
  "highlight": {},
  "query": {
    "query": "+paris +notre +dame"
   }
}
----

This query returns the following result (shown partially) from the FTS index scan on the travel-sample sample bucket.
For each matched document, the hits field shows the document id, the score, the fields in which a matched string occurs, and the position of the matched string.

[source,json]
----
"hits": [
    {
      "index": "trsample_623ab1fb8bfc1297_6ddbfb54",
      "id": "landmark_21603",
      "score": 2.1834097375254955,
      "locations": {
        "city": {
          "paris": [
            {
              "pos": 1,
              "start": 0,
              "end": 5,
              "array_positions": null
            }
          ]
        },
        "content": {
          "dame": [
            {
              "pos": 23,
              "start": 169,
              "end": 173,
              "array_positions": null
            },
...
]
----

Examples of natural language support include:

* _Language-aware_ searching; allowing users to search for, say, the word `beauties`, and additionally obtain results for `beauty` and `beautiful`.
* Multiple pre-constructed language analyzers to enable language aware searches upto xref:fts:fts-using-analyzers.adoc#pre-constructed-analyzers[20 languages].
* _Scoring_ of results, according to relevancy; allowing users to obtain result-sets that only contain documents awarded the highest scores.
This keeps result-sets manageably small, even when the total number of documents returned is extremely large.
* _Fast indexes_, which support a wide range of possible text-searches.

Full Text Search is powered by http://www.blevesearch.com/[Bleve], an open source search and indexing library written in _Go_.
Full Text Search uses Bleve for the indexing of documents, and also makes available Bleve’s extensive range of _query types_.
These include:

* xref:fts-query-types.adoc#match-query[Match], xref:fts-query-types.adoc#match-phrase-query[Match Phrase], xref:fts-query-types.adoc#doc-id-query[Doc ID], and xref:fts-query-types.adoc#prefix-query[Prefix] queries
* xref:fts-query-types.adoc#fuzzy-query[Fuzzy], xref:fts-query-types.adoc#regexp-query[Regex] and xref:fts-query-types.adoc#wildcard-query[Wildcard] queries
* xref:fts-query-types.adoc#conjunction-query-and[Conjunction], xref:fts-query-types.adoc#disjunction-query-or[Disjunction], and xref:fts-query-types.adoc#boolean-query[Boolean] queries
* xref:fts-query-types.adoc#numeric-range[Numeric Range], xref:fts-query-types.adoc#date-range[Date Range] and xref:fts-query-types.adoc#term-range[Term Range] queries
* xref:fts-geospatial-queries.adoc#creating_geospatial_rest_query_radius_based[Geospatial] queries (point radius, bounded rectangle and bounded polygon)
* xref:fts-query-types.adoc#query-string-query-syntax[Query String Queries], which employ a special syntax to express the details of each query

Full Text Search includes pre-built _text analyzers_ for the following languages: Arabic, CJK characters (Chinese, Japanese, and Korean), English, French, Hindi, Italian, Kurdish, Persian, and Portuguese.
Additional languages have been added to Couchbase Server 5.5.

== Authorization for Full Text Search

To access Full Text Search, users require appropriate _roles_.
The role *FTS Admin* must therefore be assigned to those who intend to create indexes; and the role *FTS Searcher* to those who intend to perform searches.
For information on creating users and assigning roles, see xref:learn:security/authorization-overview.adoc[Authorization].
