[#topic_kp4_qth_t5]
= Full Text Search: Fundamentals

[abstract]
_Full Text Search_ (FTS) lets you create, manage, and query specially purposed _indexes_, defined on JSON documents within a Couchbase bucket.

[#features-of-full-text-search]
== Features of Full Text Search

_Full Text Search_ provides extensive capabilities for natural-language querying.
These include:

* _Language-aware_ searching; allowing users to search for, say, the word `beauties`, and additionally obtain results for `beauty` and `beautiful`.
+
{blank}

* _Scoring_ of results, according to relevancy; allowing users to obtain result-sets that only contain documents awarded the highest scores.
This keeps result-sets manageably small, even when the total number of documents returned is extremely large.
+
{blank}

* _Fast indexes_, which support a wide range of possible text-searches.
+
{blank}

Full Text Search is powered by http://www.blevesearch.com/[Bleve], an open source search and indexing library written in _Go_.
Full Text Search uses Bleve for the indexing of documents, and also makes available Bleve’s extensive range of _query types_.
These include:

* _Match_, _Match Phrase_, _Doc ID_, and _Prefix_ queries
* _Conjunction_, _Disjunction_, and _Boolean field_ queries
* _Numeric Range_ and _Date Range_ queries
* _Geospatial_ queries
* _Query String_ queries, which employ a special syntax to express the details of each query (see xref:fts-query-types.adoc#query-string-query-syntax[Query String Query] for information)

Full Text Search also includes Bleve’s general-purpose _text analyzers_, as well as pre-built text analyzers for the following languages: Arabic, English, French, German, Hindi, Italian, Persian, Portuguese, Sorani, and Spanish.
Additionally, Full Text Search _scores_ documents by means of Bleve’s industry standard http://en.wikipedia.org/wiki/Tf%E2%80%93idf[tf-idf] scoring, with _query time boosting_.

[#whats-new-in-this-release]
== Recent Feature-Additions

The following features have recently been added:

* _Support for Multi-Node Setups_.
Within a Couchbase Server-cluster, Full Text Indexes now work over multiple nodes that have the _Search_ service enabled.
Such indexes are automatically distributed into fragments called _pindexes_ (partitioned indexes): this being similar to the way in which buckets are physically distributed across Couchbase nodes that are running the data service.
+
{blank}

* _Dynamic Topology Support_.
Full Text Search not only runs on more than one Full Text Search node, but also continues to work _during topology changes_.
For example, adding or removing nodes running the _Search_ service results in pindexes being correspondingly moved to or from those nodes.
Full Text Search indexes can also be replicated, for enhanced availability.
+
{blank}

* _Partial Results Queries_.
Every search returns the number of pindexes that succeeded, along with the search hits from those indexes, merged and sorted into a single result-set, thus providing a fault tolerance mechanism: the application developer has the option of using partial rather than full result-sets, if some pindexes fail to respond before timeout, or respond with an error.
+
{blank}

* _Enhanced Indexing Performance_.
Full Text Search indexing-speed is considerably enhanced, due to increased memory-efficiency.
+
{blank}

* _Support for Role Based Access Control_ (RBAC).
+
{blank}

* _Audit Logging_.
Full Text Search activities now appear in audit logs.
+
{blank}

* _Extended Statistics_ on Full Text Search indexing and querying are now provided.
+
{blank}

== Authorization for Full Text Search

To access Full Text Search, users require appropriate _roles_.
The role *FTS Admin* must therefore be assigned to those who intend to create indexes; and the role *FTS Searcher* to those who intend to perform searches.
For information on creating users and assigning roles, see xref:security:security-authorization.adoc[Authorization].
