= Auditing
:page-aliases: security:security-auditing

[abstract]
Couchbase Server provides event-auditing, sending corresponding output to target files.

[#introduction-to-auditing]
== Introduction to Auditing

The Couchbase Server _auditing_ facility recognizes specific _events_, which can be selectively logged.
The output is written to target files, each of which is periodically rotated.

This section lists the events that can be logged, and gives examples of the record-structures used within target files.
For information on managing auditing, see xref:manage:manage-security/manage-auditing.adoc[Manage Auditing].

== List of Audit Events

The following tables list Couchbase audit events by technology-area.
The event _name_ is provided with, in some cases, additional, clarifying information.
The event _type_ is also provided: this is either _admin_ or _data_.

Note that events under Data Service, Query and Index Service, Eventing Service, and Analytics are _filterable_.
For information, see xref:manage:manage-security/manage-auditing.adoc[Manage Auditing].

=== Analytics

[cols="3,1"]
|===
| Event | Type

| Service configuration change (was successfully made)
| Admin

| Node configuration change (was successfully made)
| Admin
|===

=== Audit

[cols="3,1"]
|===
| Event | Type

| Audit configuration changed
| Admin

| Auditing enabled or disabled
| Admin
|===

=== Auto-Failover

[cols="3,1"]
|===
| Event | Type

| Auto failover enabled
| Admin

| Auto failover disabled
| Admin

| Auto failover-count reset
| Admin
|===

=== Bucket

[cols="3,1"]
|===
| Event | Type

| Bucket created
| Admin

| Bucket deleted
| Admin

| Bucket flushed
| Admin

| Bucket-settings modified
| Admin

| Compaction settings modified
| Admin

| Bucket compression mode modified
| Admin

| Bucket TTL modified
| Admin
|===

=== Cluster

[cols="3,1"]
|===
| Event | Type

| Cluster rebalanced
| Admin

| Cluster alerts enabled
| Admin

| Cluster alerts disabled
| Admin
|===

=== Configuration

[cols="3,1"]
|===
| Event | Type

| Disk or index path changed
| Admin
|===

=== CPU and Memory

[cols="3,1"]
|===
| Event | Type

| GC run triggered
| Admin

| CPU profiling started
| Admin

| Memory profiling started
| Admin
|===

=== Data Service

[cols="3,1"]
|===
| Event | Type

| opened DCP connection
| Admin

| external memcached bucket flush (was performed)
| Admin

| invalid packet (was rejected)
| Admin

| authentication succeeded
| Admin

| document read (ie was read)
| Data

| document locked (ie was locked)
| Data

| document modify (ie was modified)
| Data

| document delete (ie was deleted)
| Data

| select bucket (ie was selected)
| Admin
|===

=== Eventing Service

[cols="3,1"]
|===
| Event | Type

| Create Function (a function-definition was created/updated)
| Admin

| Delete Function (a function-definition was deleted)
| Admin

| Fetch Functions (function-definitions were read)
| Admin

| List Deployed (the list of deployed functions was read)
| Admin

| Fetch Drafts (draft definitions were read)
| Admin

| Delete Drafts (draft definitions were deleted)
| Admin

| Save Draft (save a draft definition)
| Admin

| Start Debug
| Admin

| Start Tracing
| Admin

| Stop Tracing
| Admin

| Set Settings (save application settings)
| Admin

| Fetch Config (get eventing configuration)
| Admin

| Save Config (save eventing configuration)
| Admin

| Cleanup Eventing (clears up app definitions and settings from metakv)
| Admin

| Get Settings (get application settings)
| Admin

| Import Functions (import a list of functions)
| Admin

| Export Functions (export a list of functions)
| Admin

| List Running (the list of running functions was read)
| Admin
|===

=== Node

[cols="3,1"]
|===
| Event | Type

| Node added to cluster
| Admin

| Node removed from cluster
| Admin

| Node failed over
| Admin

| System started or shut down
| Admin
|===

=== Query and Index Service

[cols="3,1"]
|===
| Event | Type

| Index node added or removed
| Data

| SELECT statement (was executed)
| Data

| EXPLAIN statement (was executed)
| Data

| PREPARE statement (was executed)
| Data

| INFER statement (was executed)
| Data

| INSERT statement (was executed)
| Data

| UPSERT statement (was executed)
| Data

| DELETE statement (was executed)
| Data

| UPDATE statement (was executed)
| Data

| MERGE statement (was executed)
| Data

| CREATE INDEX statement (was executed)
| Data

| DROP INDEX statement (was executed)
| Data

| ALTER INDEX statement (was executed)
| Data

| BUILD INDEX statement (was executed)
| Data

| GRANT ROLE statement (was executed)
| Data

| REVOKE ROLE statement (was executed)
| Data

| UNRECOGNIZED statement (was received)
| Data

| CREATE PRIMARY INDEX statement (was executed)
| Data

| /admin/stats API request (was made)
| Admin

| /admin/vitals API request (was made)
| Admin

| /admin/prepareds API request (was made)
| Admin

| /admin/active_requests API request (was made)
| Admin

| /admin/index/completed_requests API request (was made)
| Admin

| /admin/ping API request (was made)
| Admin

| /admin/config API request (was made)
| Admin

| /admin/ssl_cert API request (was made)
| Admin

| /admin/settings API request (was made)
| Admin

| /admin/clusters API request (was made)
| Admin

| /admin/completed_requests API request (was made)
| Admin
|===

=== Search Service

[cols="3,1"]
|===
| Event | Type

| FTS index created or updated
| Admin

| FTS index deleted
| Admin

| FTS index control-command issued
| Admin

| FTS configuation refreshed
| Admin

| FTS configuration replanned
| Admin
|===

=== Security

[cols="3,1"]
|===
| Event | Type

| Login succeeded or failed
| Admin

| Password changed or reset
| Admin

| Self-signed SSL certificate regenerated
| Admin

| LDAP authentication-settings modified
| Admin

| Encryption key-rotation requested
| Admin
|===

=== Server-Group

[cols="3,1"]
|===
| Event | Type

| Server-group created
| Admin

| Node added to server-group
| Admin

| Node removed from server-group
| Admin

| Server-group deleted
| Admin
|===

=== User Management

[cols="3,1"]
|===
| Event | Type

| User added
| Admin

| User removed
| Admin
|===

=== XDCR

[cols="3,1"]
|===
| Event | Type

| XDCR reference created
| Admin

| XDCR reference updated
| Admin

| XDCR reference deleted
| Admin

| XDCR replication paused or resumed
| Admin

| XDCR replication-settings updated
| Admin

| XDCR replication created
| Admin

| XDCR replication canceled
| Admin
|===

== Audit Fields

The table below contains some frequently used audit fields with corresponding descriptions.
Note that different event-types generate different field-subsets.

[cols="2,3,5"]
|===
| Field | Type | Description

| `type`
| string
| The audit-type.
For example, Login, Startup, Shutdown, Password, AuditStart, AuditStop, AuditTruncate.

| `timestamp`
| document
| Contains the date and UTC time of the event in ISO 8601 format.
For example, http://www.w3.org/TR/NOTE-datetime[^].

| `id`
| integer
| A unique identifier for the event-type.

| `local`
a|
document

[source,json]
----
{ip: <String>,
port: <int>},
----
| A JSON document that contains the local IP-address and the port-number of the running instance.

| `remote`
a|
document

[source,json]
----
{ip: <String>,
port: <int>},
----
| A JSON document that contains the remote IP-address, the port-number, and additional information on the service used on the incoming connection associated with the event.

Possible services include `cbmcd`, `cbhttp`, `cbmgmt`, `cbxdcr`, `cbn1ql`, and `cbsyncgw`.

| `user`
| string
| A string that identifies the user.

| `params`
| document
| Information dependent on the event-type.
For example, for a bucket-operation, the bucket name is captured.

| `result`
| integer or string
| An error-code or other message, related to the attempted operation.
|===

== Audit Target-Files

When auditing is enabled, logged events are written to a default file, named `audit.log`.
After an administrator-specified period — which must be a minimum of 15 minutes and a maximum of 7 days — this file is closed, and is saved under a modified name that features a timestamp corresponding to the time of saving.
A new, empty `audit.log` file is created and saved when a new audit event is generated.
Note that this _rotation_ may happen earlier if the file reaches its maximum size of 20MB.
For instructions on configuring the file's _rotation time_, see xref:manage:manage-security/manage-auditing.adoc[Manage Auditing].

=== Login

An audit-record for a successful login might appear as follows:

[source,json]
----
{
  "timestamp":"2015-02-20T08:48:49.408-08:00",
  "id":8192,
  "name":"login success",
  "description":"Successful login to couchbase cluster",
  "role":"admin",
  "real_userid": {
    "source":"ns_server",
    "user":"bjones"
  },
 "sessionid":"0fd0b5305d1561ca2b10f9d795819b2e",
 "remote":{
  "ip":"172.23.107.165", "port":59383
  }
}
----

In this example, a user named `bjones` has successfully logged into a Couchbase cluster using the domain IP address `172.23.107.165.`

==== Login Failure

The following audit-record indicates that a login attempt failed:

[source,json]
----
{
  "real_userid": {
    "source": "rejected",
    "user": "auditBucketUser"
  },
  "remote": {
    "ip": "127.0.0.1",
    "port": 64416
  },
  "timestamp": "2017-03-16T15:45:27.420Z",
    "id": 8193,
    "name": "login failure",
    "description": "Unsuccessful attempt to login to couchbase cluster"
}
----

This record indicates that a user named `auditBucketUser` incurred an `Unsuccessful attempt to login to couchbase cluster` on `2017-03-16` at `15:45:27`.

=== Bucket Creation

The audit-record below corresponds to the creation of a bucket.

[source,json]
----
{
  "props":{
    "compression_mode":"off",
    "max_ttl":12000,
    "storage_mode":"couchstore",
    "conflict_resolution_type":"seqno",
    "eviction_policy":"value_only",
    "num_threads":3,
    "flush_enabled":false,
    "purge_interval":"undefined",
    "ram_quota":163577856,
    "replica_index":false,
    "num_replicas":1
  },
  "type":"membase",
  "bucket_name":"ProductionBucket",
  "real_userid":{
    "source":"ns_server",
    "user":"Administrator"
  },
  "sessionid":"5dd53fe63703c7fdc45ff75596e39a35",
  "remote":{
    "ip":"127.0.0.1",
    "port":61908
  },
  "timestamp":"2018-02-07T15:22:54.960Z",
  "id":8201,
  "name":"create bucket",
  "description":"Bucket was created"
}
----

This record indicates that a `Bucket was created` on `2018-02-07` at `15:22:54`; that the bucket was named `ProductionBucket`; and that its eviction-policy was defined as `value_only`.
The bucket was created by the system's `Full Administrator`.

=== Bucket TTL Modification

The audit-record below corresponds to the modification of Bucket TTL, for the bucket created immediately above.

[source,json]
----
{
  "props":{
    "max_ttl":15000,
    "storage_mode":"couchstore",
    "eviction_policy":"value_only",
    "num_threads":3,
    "flush_enabled":false,
    "purge_interval":"undefined",
    "ram_quota":163577856,
    "num_replicas":1
  },
  "type":"membase",
  "bucket_name":"ProductionBucket",
  "real_userid":{
    "source":"ns_server",
    "user":"Administrator"
  },
  "sessionid":"12774a2e146c650eeed8c6d9486857ad",
  "remote":{
      "ip":"127.0.0.1","port":61966
  },
  "timestamp":"2018-02-07T15:23:51.350Z",
  "id":8202,
  "name":"modify bucket",
  "description":"Bucket was modified"
}
----

=== User Creation

The audit-record below corresponds to the creation of a user.

[source,json]
----
{
  "roles": [
    "ro_admin"
  ],
  "identity": {
    "source": "builtin",
    "user": "auditBucketUser2"
  },
  "real_userid": {
    "source": "ns_server",
    "user": "Administrator"
  },
  "sessionid": "dca284b5efe1937a1a4085ef88c2fbcb",
  "remote": {
    "ip": "127.0.0.1",
    "port": 64416
  },
  "timestamp": "2017-03-16T15:44:32.254Z",
  "id": 8232,
  "name": "set user",
  "description": "User was added or updated"
}
----

This record indicates that a user named `auditBucketUser2` was created by the `Full Administator` on `2017-03-16` at `15:44:32`; and that the user was given the role of `ro_admin`.

=== Index Creation

The following audit-record indicates that an index was created or updated:

[source,json]
----
{
  "timestamp": "2017-03-16T16:12:36.198Z",
  "real_userid": {
    "source": "ns_server",
    "user": "Administrator"
  },
  "index_name": "def-airportname",
  "id": 24577,
  "name": "Create/Update index",
  "description": "FTS index was created/Updated"
}
----

This record indicates that an `FTS` index named `def-airportname` was created or updated on `201703-16` at `16:12:36`.
