= Understanding Authentication
:description: pass:q[To access Couchbase Server, users must be authenticated. \
_Authentication_ is a process for identifying who is attempting to access a system.]

[abstract]
{description}
Subsequent to successful authentication, _authorization_ can be performed, whereby the user's appropriate access-level is determined.

[#passing-credentials]
== Authentication Options

Couchbase-Server authentication typically relies on a _username_ and a _password_, which must be passed into the system by the _user_ (meaning, the administrator or application) that is attempting access.
The specified username and password must match ones already defined: these must be accessible either on the Couchbase-Server cluster itself, or _externally_.
External accessibility, which is available only with the Enterprise Edition. Couchbase Server supports external authentication using:

* _Lightweight Directory Access Protocol_ (LDAP) provided by a network-accessible directory-server.

* _Pluggable Authentication Modules_ (PAM) authentication framework built into the Linux operating system.

* _Security Assertion Markup Language_ (SAML) authentication supplied by an _Identity Provider_ (IdP). This provider is often run by a third-party, such as Okta, or provided as part of cloud infrastructure, such as Microsoft Azure. This authentication method only grants users access the Couchbase Server Web UI. They can't use it to authenticate for command-line, REST API, or SDK access. See xref:learn:security/authentication-domains.adoc#saml-authentication[SAML Authentication] to learn more about SASL authentication.

If a match is achieved, the user is thereby recognized, and so _may_ be granted access.
If no match is achieved, the user is denied access.

Client applications or systems can also pass credentials to Couchbase Server by means of x.509 _certificates_.

[#introduction-to-password-based-authentication]
== Users, Usernames, and Passwords

To access Couchbase Server, all users and applications must authenticate.
This is typically achieved by means of a _username_ and _password_.

The _Full Administrator_ username and password are established during initialization of Couchbase Server: see xref:manage:manage-nodes/create-cluster.adoc[Create a Cluster] for details.

Subsequently, additional users can be added to the cluster as _local_ users: each is at that time assigned a unique _username_, and a unique _password_.
Passwords can be changed by means of the password-reset tool, xref:cli:cbcli/couchbase-cli-reset-admin-password.adoc[reset-admin-password]; or by Couchbase Web Console, as described in xref:manage:manage-security/manage-users-and-roles.adoc#editing-users-and-groups[Editing Users and Groups].
For best practices for password-definition, and restrictions on username-design, see xref:learn:security/usernames-and-passwords.adoc[Usernames and Passwords].

Users can also be added to the cluster as _external_ users, for whom no password need be specified; since the external user is to be authenticated externally.

[#console-access]
=== Usernames and Passwords for Administrators

When an administrator logs into Couchbase Web Console, if the console is running on the default port, `+http://localhost:8091+`, the specified username and password are passed in the clear, from the browser to the console.

Optionally, Couchbase Web Console can be configured for _secure access_, at `+https://localhost:18091+`; so that the username and password are passed in encrypted form.
For information, see xref:manage:manage-security/manage-console-access.adoc[Manage Console Access].

[#authentication-for-applications]
=== Usernames and Passwords for Applications

To pass credentials, applications must use one of four mechanisms provided by the _Simple Authentication and Security Layer_ (SASL) framework.
These are PLAIN, and three members of the _Salted Challenge Response Authentication Mechanism_ family of hash functions; which are SCRAM-SHA1, SCRAM-SHA256, and SCRAM-SHA512.
The SCRAM mechanisms allow applications to authenticate securely, by transmitting the password only in _protected form_.
Drivers may need to be updated, to support SHA-based hash functions.

[#password-authentication-mechanisms]
In ascending order of strength, the Couchbase password-authentication mechanisms are as follows:

* _PLAIN_: The client sends the password in unencrypted form.
All clients support this authentication-method.
It is insecure, providing no defence against passwords being stolen in transmission.

* _SCRAM-SHA1_: Uses a 160-bit key.

* _SCRAM-SHA256_: One of a group of hash functions referred to as _SHA2_, SCRAM-SHA256 uses a 256-bit key.

* _SCRAM-SHA512_: Another hash function from the _SHA2_ group, SCRAM-SHA512 uses a 512-bit key; and is the strongest supported authentication protocol.

During initial client-server negotiation, the strongest authentication protocol supported by both Couchbase Server and the application's client OS is selected for use.
For example, if the client supports only the PLAIN protocol, the PLAIN protocol is used; but if the client also supports the SCRAM-SHA1 protocol, then SCRAM-SHA1 is used.

A challenge-response method can be transmitted through both encrypted and unencrypted channels.

Note that the SCRAM challenge-response protocols authenticate only the process of password-validation.
To secure the subsequent session, TLS should be used.

[#introduction-to-certificate-based-authentication]
== Certificate-Based Authentication

Couchbase Server supports the use of x.509 certificates, to authenticate clients.
This ensures that only approved users, machines, or endpoints are authenticated.

Certificate-based authentication relies on a _Certificate Authority_ (CA) to validate identities and issue certificates.
The certificate includes information such as the name of the entity it identifies, an expiration date, the name of the CA that issued the certificate, and the digital signature of the issuing CA.

For a complete overview of Couchbase Server's certificate-handling mechanisms, see xref:learn:security/certificates.adoc[Certificates].
For practical steps required to set up client and server certificates, see xref:manage:manage-security/manage-certificates.adoc[Manage Certificates]

[#authorization]
== Authorization

Couchbase-Server features &#8212; including data, settings, and statistics &#8212; can be accessed only by users who have been assigned the appropriate _privileges_.
Privileges include _read_, _read-write_, _execute_, and _manage_.
Privileges are assigned by _Full_ and _Security_ Administrators, in correspondence with _roles_.
When a user successfully authenticates, their assigned roles are examined, and access is granted or denied by Couchbase Server.

Roles can be assigned to a user in either or both of two ways:

* _Directly_.
The user is associated directly with one or more Couchbase-Server roles.

* _By Group_.
A Couchbase-Server _user-group_ is defined, and roles are assigned to the user-group.
The user is made a member of the user-group, and thereby inherits all the roles of the group.
A user can be a member of any number of groups.

Note that by means of _LDAP Group Support_, the roles assigned to a Couchbase-Server user-group can be inherited by users not defined on Couchbase Server; as described in xref:learn:security/authentication-domains.adoc[Authentication Domains].

See
xref:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups, and Roles], for details on creating users and groups, and assigning roles.

[#authentication-domains]
== Authentication Domains

Couchbase Server assigns each user to one of two _authentication domains_; which are _local_ and _external_.
The _local_ domain contains users defined locally, on Couchbase Server.
The _external_ domain contains users defined externally on an LDAP server, a SAML IdP provider, or Linux systems that are accessed by means of _PAM_.
For a complete overview, see xref:learn:security/authentication-domains.adoc[Authentication Domains].




In addition to a username and password requirement, SAML can require _Two-Factor Authentication_ (TFA) such as a one-time code sent via text message or a code generated by an authentication module or app. SAML can also provide _Single Sign On_ (SSO), where a user that has already authenticated with another application is automatically authenticated to use