= Certificates
:description: Couchbase Server supports x.509 and PKCS#12 certificates for client and server.
:page-aliases: security:security-certs-auth,security:security-encryption
:page-toclevels: 3
[abstract]
{description}

[#certificates-in-couchbase]
== Certificates and Couchbase Server

Couchbase Server supports certificates in X.509 and PKCS #12 format. 
Configuring Couchbase Server with these certificates has these benefits:

* Only approved users, applications, machines, and endpoints have access to system resources.

* Clients can verify the identity of Couchbase Server, ensuring that they're not exchanging data with a rogue entity.

Managing certificates requires Full Admin, Local User Security Admin, or External User Security Admin privileges.

This page provides a general overview of using certificates with Couchbase Server and clients.
It assumes you know the basics of Transport Layer Security (TLS) and certificates. 
To learn more about these topics, see the Wikipedia article on  https://en.wikipedia.org/wiki/Public_key_certificate[Public key certificate^],  and this DigitalOcean's https://www.digitalocean.com/community/tutorials/openssl-essentials-working-with-ssl-certificates-private-keys-and-csrs[OpenSSL Essentials: Working with SSL Certificates, Private Keys and CSRs] page.

For step-by-step instructions for creating and deploying certificate for Couchbase Server and clients, see xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates] and xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates].

[#certificate-hierarchies]
== Certificate Hierarchies

A Couchbase Server cluster organizes certificates in a hierarchy.
The certificate with overall authority for the cluster is at the top of the hierarchy.
All certificates on lower tiers of the hierarchy inherit its authority.
You use one certificate to sign other, lower-level certificates. 
This signing lets the new certificate inherit its own authority from the high-level certificate.

In Couchbase Server 7.1 and later, verifying a trust chain uses one of these procedures:

* The entity proving its identity gives its own certificate and all intermediate certificates to the requesting party.
The requesting party then tries to find the CA--the last certificate in the chain--in its own trust store.
If it does, authentication may proceed.

* The entity proving its identity sends only its own certificate to the requesting party.
The requesting party has to find all associated intermediates, and the CA, in its own trust store; and if it does, authentication may proceed.

[#server-certificates]
== Default Certificates and Certificate Substitution

By default, Couchbase Server generates self-signed root and entity certificates to protect cluster and individual nodes.
You can replace these certificates with customized or externally acquired certificates and with corresponding certificate-chains.
You may choose to replace these certificates to use ones signed by a well-known CA, or to add extensions to the certificates.
Administrators must create all client certificates and certificate chains because Couchbase Server does not generate them by default.

The private key of the default self-signed cluster certificate is not available.
Therefore, you cannot create custom certificate-chains based on the default certificate.
To create custom certificate-chains, generate a custom cluster certificate and private key. 
Another option is to get a root CA from an external authority and create intermediate certificates based on it, as described in xref:#intermediate-certificates[Intermediate Certificates].

[#cluster-certificate]
=== Cluster Certificate

Couchbase Server provides a default self-signed cluster certificate which it generates and deploys while creating the first node in a cluster.
You can deploy a new replacement cluster certificate on the cluster using the Couchbase REST API or command line interface.
For example, you can replace the certificate with one supplied by a well-known CA to make authentication with third parties easier.
The current cluster certificate is always visible on the *Root Certificate* panel of the *Security* screen of Couchbase Server Web Console.
See xref:manage:manage-security/manage-security-settings.adoc#root-certificate-security-screen-display[Root Certificate].

You can supply a certificate for the cluster in one of two formats: 

* a Privacy Enhanced Mail (PEM) file. These files have the extension `.pem`. The file can have any name, although `ca.pem` is commonly used. They contain a single certificate. With this format, you supply a separate private key file in  PKCS #1 or PKCS #8 format, with a `.key` extension. The name of the private key often corresponds to the name of the certificate it generates: for example, `ca.key` would be used to generate `ca.pem`.
* a Public-Key Cryptography Standard (PKCS) #12 file. This file type lets you bundle together certificates, private keys, and chains of trust. 


For examples of creating cluster and other certificates based on private keys see in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates]

==== Multiple Root CAs

Couchbase Server supports using multiple root CA certificates.
Together, these certificates constitute a trust store, which Couchbase Server uses to determine whether or not to trust a client. 
If the client's root CA in the client's trust chain is in the cluster's trust store, Couchbase Server trusts the client.

The Couchbase Server trust store provides authority to individual nodes.
Each node has at most one node certificate, potentially with a concatenated trust chain.
The certificate or its chain of trust  points to a single oot CA in the cluster's trust store.
The trust chains of multiple nodes can point to a single root CA.
All root CAs in the trust store are accessible to all nodes.
You can use multiple root CAs when encrypting node-to-node communications.

For more information, see xref:learn:security/using-multiple-cas.adoc[Using Multiple Root Certificates].

[#intermediate-certificates]
=== Intermediate Certificates

An intermediate certificate--sometimes referred to as a subordinate certificate, an intermediate CA, or a signing CA--can be either:

* A certificate signed by the cluster certificate called the root CA.

* One of a chain of intermediate certificates, each of which was signed by one preceding it in the chain. 
The first certificate in the chain must be signed by the cluster certificate.

The main purpose of the intermediate certificate is to sign node certificates, client certificates, or other intermediate certificates. 
Signing node certificates convey the authority of the cluster certificate to the node or client certificates indirectly.
Using the intermediate certificate instead of the cluster certificate's own private key limits the key's use, making it more secure.

The default certificates provided by Couchbase Server do not include intermediates: entity certificates are all signed directly by the cluster certificate.
However, if you use customized certificates and certificate chains, you can define intermediate certificates.

You can upload intermediate certificates to the Couchbase Server trust store.
For information, see xref:learn:security/using-multiple-cas.adoc#adding-intermediate-certificates-to-the-trust-store[Adding Intermediate Certificates to the Trust Store].

[#node-certificate]
=== Node Certificates

Each node has its own certificate  signed  by the cluster certificate. 
Couchbase Server automatically generates the node certificates by creating a new private key and signing the certificate using cluster's certificate. 
This process occurs whenever you create a single-node cluster and when you add additional nodes.

This automated process provides basic out-of-the-box security for all of Couchbase Server's secure ports. 
See xref:install:install-ports.adoc[Couchbase Server Ports] &#8212;  and xref:learn:clusters-and-availability/node-to-node-encryption.adoc[Node-to-Node Encryption] for a description of these ports.

However, using customized certificates with additional extensions that provide subject alternative names and signed by a root authority can provide a higher level of security. 
After you prepare customized node certificates, you must deploy the following to each node to activate the certificates:

* Save the node's private key that you used to create the node's certificate in a file named `pkey.key`.
* The node certificate chain-file.
On each node, this must be named `chain.pem`.
When the node certificate has been signed directly by the cluster certificate, `chain.pem` is nothing more than the node certificate file, renamed.
However, when the node certificate has gained the CA's authority by means of a sequence of one or more intermediate certificates, `chain.pem` may be a correspondingly ordered _concatenation_ of all the certificates in the chain, except the cluster certificate: access to this file allows the authority of the node certificate to be established by progressive examination of the signing authorities in its chain.
+
Alternatively, if indeed the node certificate has gained the CA's authority by means of a sequence of one or more intermediate certificates, `chain.pem` may still be configured to contain only the node certificate; if it is assumed that all intermediates in the chain are already resident in the client's _trust store_.

Couchbase Server requires that these files, when newly created, be manually copied to a specific location in the filesystem: from this location, they are deployed by Couchbase Server.
Examples are provided in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates].

In Couchbase Enterprise Server Version 7.2 and later, each node certificate must contain its node's name specified as a Subject Alternative Name.
See xref:learn:security/certificates.adoc#server-certificate-validation[Server Certificate Validation] for details.

[#client-certificates]
=== Client Certificates

A client can use a client certificate to identify itself to Couchbase Server.
The certificate allows the server to authenticate the client, and to authorize the client's associated user.
Information included in the certificate identifies the user by means of a username.

Couchbase Server creates and uses client certificates by default for inter-node communication.
These certificates are not visible to the user.
Administrators must create the client certificates for XDCR or SDK-client connections explicitly based on a customized replacement cluster certificate.

When authenticating a client that uses certificate-based authentication, Couchbase Server asks the client to present its certificate.
If Couchbase Server finds that the certificate's chain of trust leads to a root authority that it recognizes, it trusts the client.
Couchbase Server then verifies that the certificate has not expired.
After verifying the certificate is still valid, Couchbase Server extracts the username from the certificate.
If the username matches an existing user and the user has the correct roles to access Couchbase Server via the client, Couchbase Server lets the client connect.

NOTE: The client's authentication with the server relies on the private key used to create the client certificate.
The client digitally signs a message with its private key and sends the message to the server.
The server uses the client's public key to verify that the client sent the message.
For an example this private key use when securing XDCR, see xref:manage:manage-xdcr/enable-full-secure-replication.adoc#specify-full-xdcr-security-with-certificates[Specify Root and Client Certificates, and Client Private Key].
Another example is the securing contact with an LDAP host, explained in xref:manage:manage-security/configure-ldap.adoc#client-certificate[Configure LDAP].

A similar process allows the server to authenticate with the client in a process called mutual TLS (mTLS) or https://en.wikipedia.org/wiki/Mutual_authentication[mutual authentication^].

[#identity-encoding-in-client-certificates]
==== Specifying Usernames for Client-Certificate Authentication

The client certificate can contain the username to use for a client connection. 
You can configure Couchbase Server to search for a username among multiple elements within the client certificate.
If it finds an element that could contain a username, Couchbase Server attempts to authenticate and authorize username.

If you configure multiple elements within the client certificate to be potential usernames, Couchbase Server attempts to authenticate each until it either authenticates one or runs out of elements.
You set the order in which Couchbase Server examines the elements in the client certificate for usernames.
See xref:manage:manage-security/enable-client-certificate-handling.adoc[Enable Client Certificate Handling] for details.

[#specifying-usernames-in-certificates]
===== Embedding Usernames in Certificates

You can use the following elements in a certificate to specify a username:

* The `Subject` for the certificate, featuring the Common Name.
For example, when creating the client-certificate using the command line, you can set the subject of the certificate to `clientname` by using the `-subj "/CN=clientuser"` argument. 
+
NOTE: The Internet Engineering Task Force (IETF) has deprecated the Subject Common Name as described in https://tools.ietf.org/html/rfc6125#section-6.4.4[section 6.4.4 of RFC 6125^].
Couchbase Server continues to support using the Subject Common Name.
See also xref:learn:security/certificates.adoc#deprecation-of-subject-common-name[Deprecation of Subject Common Name].

* The `DNS` name, provided as a Subject Alternative Name for the certificate.
For example, if you add `subjectAltName = DNS:node2.cb.com` to the certificate, you can configure Couchbase Server  to use `node2.cb.com` as the username withouy a prefix or delimiter specified in the handling-configuration.
+
Prefix and delimiter are explained later in xref:learn:security/certificates.adoc#identifying-certificate-based-usernames-on-couchbase-server[Identifying Certificate-Based Usernames on Couchbase Server].

* The `email` defined as a Subject Alternative Name for the certificate.
For example, if you add `subjectAltName = email:john.smith@example.com` to the certificate, you can configure Couchbase Server to use `john.smith@example.com` as the username. 
However, because Couchbase Server does not allow the character `@` in  usernames, `john.smith@example.com` is not valid.
You can configure Couchbase Server extract just the account portion of the email address (`john.smith`) by defining `@` as a delimiter.
See xref:learn:security/certificates.adoc#identifying-certificate-based-usernames-on-couchbase-server[Identifying Certificate-Based Usernames on Couchbase Server] form an explanation.

* The `URI` defined as a Subject Alternative Name in the certificate.
For example, if you add `subjectAltName = URI:www.example.com` to the certificate, you can configure Couchbase Server to use `www.example.com` as the username.

For examples of setting Subject Common Names and Subject Alternative Names in certificates, see  xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates] and xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates].

[#identifying-certificate-based-usernames-on-couchbase-server]
===== Identifying Certificate-Based Usernames on Couchbase Server

By default, Couchbase Server does not handle client certificates. 
You can enable client certificate handling so that it is optional or even mandatory.

When you enable client-certificate handling, you can configure Couchbase Server to search for paths within the client certificate that contain usernames for authentication.

Each specified path can be one of the following path-types:

* `subject.cn`: extracts the Subject Common Name.

* `san.dns`. extracts the `DNS` Subject Alternative Name.

* `san.email`: extracts the `email` Subject Alternative Name.

* `san.uri`: extracts the `URI` Subject Alternative Name.

You can specify any number of paths for Couchbase Server to extract. 
You can also have it extract multiple instances of any path-type.

In some cases, the value in the certificate cannot match a Couchbase Server user name. For example, email addresses are not valid usernames because they contain the `@` character.
To handle these case, you can have Couchbase Server parse the value from the certificate to extract the username. 
You can define a prefix, delimiter, or both that Couchbase Server uses to extract a portion of the element it extracts from the path.

* If you define neither a prefix or delimiter for a path, Couchbase Server does not parse element's content. 
It attempts to match the value as-is to an existing username.

* You can define a prefix which is a string of text Couchbase Server attempts to match of the start of the value  extracted from the certificate. 
If the prefix matches the start of the value, Couchbase Server removes the matching prefix from the value. 
It then tries to match the remaining string to a Couchbase Server username.  
If the prefix does not match the start of the value, Couchbase Server tries to match the entire value to a username.
For example, suppose you specify `san.uri` as a path in the certificate to use, and set the prefix to `www.`.
If Couchbase Server extracts the value `www.example.com` from the `san.uri` element in the certificate, the prefix matches leading `www.`, leaving Couchbase Server with `example.com` as the username.
If instead the `san.uri` is `example.com`, the prefix does not match. 
In this case, Couchbase Server attempts to match `example.com` to a username.

* You can define a delimiter, which is a single character that Couchbase Server should use to split the value extracted from the certificate.  
If it finds the delimiter in the value, Couchbase Server uses the portion of the value before the delimiter as the username.
If Couchbase Server does not find the delimiter in the value, it uses the entire value as the username. 
For example, suppose you specify `san.email` as a path in the certificate, and set the delimeter to `@`.
If Couchbase Server extracts the value `john.smit@example.com` as the value of `san.email`, it splits the value at the `@`, leaving it with `john.smith` to match to a username.
+
NOTE: If the value contains multiple instances of the delimiter, Couchbase Server only uses the portion before the first one. For example, if you set the delimiter to `.` and the value is `www.example.com`, Couchbase Server will attempt to match `www` to a username. It will not attempt to match any other portion of the value.

For step-by-step instructions, see xref:manage:manage-security/enable-client-certificate-handling.adoc[Enable Client Certificate Handling].

[#deprecation-of-subject-common-name]
== Deprecation of Subject Common Name
The IETF has deprecated using Subject Common Name to identify either a server or a client (see https://tools.ietf.org/html/rfc6125#section-6.4.4[section 6.4.4 of RFC 6125^]).
For Couchbase Enterprise Server Version 7.2 and later, this means that:

* The node-certificate for each server in the cluster must specify its node-name as a Subject Alternative Name.
See xref:learn:security/certificates.adoc#node-certificate-validation[Node-Certificate Validation] for details.
You can still use Subject Common Name.

* A client-certificate may continue to specify only a Subject Common Name.

Examples of certificate-creation provided in xref:manage:manage-security/manage-certificates.adoc[Manage Certificates] continue to include definitions of Subject Common Name for both server and client.

[#node-certificate-validation]
== Node-Certificate Validation

In Couchbase Enterprise Server Version 7.2 and later, each node certificate must have the node's name specified as a Subject Alternative Name (SAN).

The SAN must meet the following requirements.
(Note that the wildcard character is permitted in all expressions.)

* If the node name is a Fully Qualified Domain Name (FQDN), the SAN must be this FQDN with a `DNS:` prefix.
For example, `DNS:*.localhost.com`.
When the node name is an FQDN, the SAN cannot specify an IP address.

* If the node name is an IPv4 or an IPv6 IP Address, the SAN must be the IP address, with an `IP:` prefix.
For example, `IP:127.0.0.1` or `IP:0:0:0:0:0:0:0:1`.
When the node name is an IP address, the SAN cannot specify an FQDN.

For complete examples of server-certificate configuration, specifying the node-name as a SAN, see xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates].

[#certificate-checking]
=== Certificate Checking

Couchjbase Server checks the validity of certificates in following situations:

* You upload certificate to a node.
If the name of the node is not specified as a SAN:

** If the name of the node can be changed, Couchbase Server issues a warning, and the upload succeeds.

** If the name of the node cannot be changed, Couchbase Server reports an error, and the upload fails.

+
To learn when you can rename a node itself, see xref:learn:clusters-and-availability/nodes.adoc#node-renaming[Node Renaming].

*  You add a node or a node joins the cluster.
Couchbase Server always checks the certificate on the new node to verify the node's name is correctly specified as a SAN. Depending on the cluster's configuration, Couchbase Server may perform the same check on the certificate of the cluster node handling the join. If Couchbase Server finds an issue, its response depends on what sort of check it performed:

** New node: If the node name is not specified as a SAN, Couchbase Server returns an error and the add or join fails.

** Cluster node: If the cluster has two or more nodes prior to the add or join, Couchbase Server does not perform a check.
Otherwise, the Couchbase Server performs the check. If the node-name is not specified as a SAN, the add or join fails.

[#private-key-formats]
== Private Key Formats

In version 7.1 and later, Couchbase Server supports _PKCS #1_ and _PKCS #8_ &#8212; in each case, only for use with private keys:

* _PKCS #1_ can be used for _unencrypted_ private keys only.

* _PKCS #8_ can be used for both _unencrypted_ and _encrypted_ private keys: note that the user-specified `EncryptedPrivateKeyInfo` must use _PKCS #5 v2_ algorithms.

[#json-passphrase-registration]
== JSON Passphrase Registration

If a node-certificate is to be associated with an encrypted private key, a procedure can be defined to allow Couchbase Server to access and use the key's passphrase, when use of the key is required: the passphrase can be _registered_, by specifying a JSON object with the REST API.
For information, see xref:rest-api:upload-retrieve-node-cert.adoc[Upload and Retrieve a Node Certificate].



[#examples]
== Examples

Examples of file-types and their generation, of extension-definition, of intermediate-certificate use, and of Couchbase-Server specific deployment requirements are provided for the server-side in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates], and for the client-side in xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates].
The examples allow _Cross Data Center Replication_ to be secured with certificates only.
They also support secure access to Couchbase Server from Java clients.
