= Certificates
:page-aliases: security:security-certs-auth,security:security-encryption

[abstract]
Couchbase Server supports x.509 certificates for client and server.

[#certificates-in-couchbase]
== Certificates and Couchbase Server

Couchbase Server supports the use of x.509 certificates, for clients and servers.
This ensures that:

* Only approved users, applications, machines, and endpoints have access to system resources.
Consequently, the mechanism can be used by Couchbase SDK clients, to access Couchbase Services; and by source clusters that use XDCR to replicate data to target clusters.

* Clients can verify the identity of Couchbase Server, thereby ensuring that they are not exchanging data with a rogue entity.

Full or Security Administrator privileges are required, for the management of certificates.

This page provides a general overview of certificates, and of their management in the context of Couchbase Server.
For step-by-step instructions on certificate creation and deployment, xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates] and xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates].

[#certificate-content]
== Certificate Content

Certificate-based authentication relies on a _Certificate Authority_ (CA), to validate identities and issue certificates.
Each certificate includes:

* The name of the entity it identifies.

* An expiration date.

* The name of the CA that issued the certificate.

* The digital signature either of the issuing CA, or of an intermediate certificate through which the authority of the issuing CA can be traced.

* A public key, which corresponds to the _private_ key that was used to generate the certificate; and which can therefore potentially be used in conjunction with that private key in handling digital signatures and keys; so as to support authentication and secure communication between client and server.

This information associates the identified entity with the issuing CA, such that third parties who know and trust the CA, but are unfamiliar with the identified entity, may elect to trust the identified entity on the basis of their trust in the CA.
Note that all systems that use certificates for authentication maintain their own collection of trusted CA certificates: if, when an entity attempts to authenticate, the entity proves that it has itself been authorized by a CA whose certificate is included in the system's collection, the entity may be trusted by the system.

Additionally, certificates may each be configured to contain _extensions_, which might be used to constrain the certificate's capabilities (for example, by indicating the IP address of the server on which the certificate must reside; or by indicating the uses to which its public key must be restricted); or to identify a _username_, based on which client-authentication and authorization can proceed.

[#certificate-hierarchies]
=== Certificate Hierarchies

On a Couchbase Server-cluster, certificates are managed and deployed _hierarchically_.
The certificate with overall authority for the cluster is at the top of the hierarchy; and its authority is inherited by all certificates on lower tiers of the hierarchy.
One certificate allows another certificate to inherit its authority (and thereby occupy the tier immediately below itself) by the process of _certificate signing_.

A _two-tier_ certificate hierarchy is one where the CA has issued a certificate directly for one or more _identified entities_ &#8212; each of which could be an individual node within a cluster, or a client application that wishes to interact with the cluster.
If the receiving system trusts the CA, then the identified entity is trusted.
The CA, being at the top of this two-tier hierarchy, is referred to as the _root CA_.

A _two-plus-tier_ certificate hierarchy is one where a root CA has issued a certificate to an _intermediate authority_, which in turn has issued a certificate either to another intermediate authority, or directly to one or more identified entities.
Use of a two-plus-tier hierarchy requires that all intermediate certificates, as well as the entity's certificate, be available for inspection when authentication is attempted; otherwise, the ultimate authority of the root will not be traced, and authentication will fail.
All certificates, both on the server-side and on the client-side should therefore be made available in a complete _trust chain_: which is a file that contains the entity's own certificate, concatenated with all its associated intermediate certificates, in the precise order in which signing occurred.
The root certificate itself is never included in the trust chain.

[#server-certificates]
== Default Certificates and Certificate Substitution

By default Couchbase Server provides minimally defined _root_ and _entity_ certificates to protect cluster and individual nodes.
These can be replaced with customized certificates and certificate-chains, by the administrator.
Certificates and certificate-chains for client-side use need to be created by administrators, as appropriate.

[#cluster-certificate]
=== Cluster Certificate

The cluster certificate is the _root certificate_ issued for the cluster; and contains the public key of corresponding Certificate Authority (CA).
Programs that wish to interact securely with Couchbase Server must elect to trust this CA.
By means of _certificate signing_, the cluster certificate grants its authority to other certificates: this includes both server-side and client-side certificates.
Thus, if client and server share the same root certificate, they are likely to trust one another.

Couchbase Server provides a default, self-signed cluster certificate, which is created and deployed when the first node in a cluster is created.
A new, replacement cluster certificate can be deployed on the cluster by means of the Couchbase REST API or CLI.
The current cluster certificate is always visible on the *Root Certificate* panel of the *Security* screen of Couchbase Web Console.
See xref:manage:manage-security/manage-security-settings.adoc#root-certificate-security-screen-display[Root Certificate].

The file for the cluster (indeed, for any other server or client) certificate is required to be in _Privacy Enhanced Mail_ (or _PEM_) format, with a `.pem` extension.
The file can have any name, although `ca.pem` is commonly used.
On creation, the certificate is generated (indeed, all certificates, whether server-side or client-side are generated) from a corresponding, already created _private key_; whose file is in _RSA key_ format, with a `.key` extension.
The name of the private key often corresponds to the name of the certificate it generates: for example, `ca.key` would be used to generated `ca.pem`.
When an existing certificate is to be used to grant its authority to another, the existing certificate's `.key` and `.pem` files are both specified in the creation-process for the new certificate.

Examples of creating cluster and other certificates based on private keys are provided in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates]

[#intermediate-certificates]
=== Intermediate Certificates

An _intermediate certificate_ can be either:

* A certificate signed by the cluster certificate.

* One of a chain of intermediate certificates, each of which has been signed by the previous in the chain; except the first, which has been signed by the cluster certificate.

The main purpose of the intermediate certificate is to sign _node certificates_ and _client certificates_, and thereby convey the authority of the cluster certificate to the node certificates _indirectly_.
This allows the cluster certificate to be maintained with due privacy, when multiple nodes or clients need to be signed.

The default certificates provided by Couchbase Server do not include intermediates: entity certificates (for nodes) are all signed directly by the root (the cluster certificate).
However, if customized certificates and certificate-chains are substituted by the administrator, intermediate certificates can be defined and used.

[#node-certificate]
=== Node Certificates

Each node in a Couchbase Cluster is an _identifiable entity_, and so has its own _node certificate_.
A default node certificate is provided for each node: this is signed directly by the _cluster_ certificate.
The process whereby, for a node being added or joined to the cluster, its node certificate is generated (based on a new private key) and signed (by means of the current cluster certificate and cluster private key) is entirely automated.
Certificate-based security for a Couchbase Server-cluster is thereby provided out-of-the-box.
However, no extension-based constraints, _Subject Alternative Names_, or other special features are provided: therefore, optimal security is likely to require _administrator-customized_ certificates, based on an administrator-selected root authority.

Administrator-substituted node certificates may be signed either by a replacement cluster certificate, or by a chain of one or more intermediate certificates, ultimately signed by the the replacement cluster certificate.

When customized node certificates have been prepared for a cluster, the following elements must be deployed on each node of the cluster, for its node certificate to become active:

* The node private key, which has been used to create the node certificate for the current node.
On each node, this must be named `pkey.key`.

* The node certificate chain-file.
On each node, this must be named `chain.pem`.
When the node certificate has been signed directly by the cluster certificate, `chain.pem` is nothing more than the node certificate file, renamed.
However, when the node certificate has gained the CA's authority by being signed a sequence of one or more intermediate certificates, `chain.pem` must be a correspondingly ordered _concatenation_ of all the certificates in the chain, except the cluster certificate.
Access to this file allows the authority of the node certificate to be established by progressive examination of the signing authorities in its chain.

Couchbase Server requires that these files, when newly created, be manually copied to a particular location in the filesystem: from this location, they are deployed by Couchbase Server.
Examples are provided in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates].

Unlike the cluster certificate, the text of which is displayed in Couchbase Web Console (as described in xref:manage:manage-security/manage-security-settings.adoc#root-certificate-security-screen-display[Root Certificate]), nodes certificates (whether defaults or customized substitutions) are not displayed to users; nor are the corresponding chain files.

[#client-certificates]
=== Client Certificates

A _client_ of Couchbase Server is an _identifiable entity_ that can be authenticated by means of a certificate.
Information in the certificate should allow the client to be authorized for a certain level of resource-access on Couchbase Server.
Couchbase Server creates and uses client certificates by default, for standard system activities; but these are not visible to the user.
Client certificates specifically required for XDCR or SDK-client access must be explicitly created by the administrator.

When authenticating a client that uses certificate-based authentication, Couchbase Server asks the client to present the client certificate.
Couchbase Server determines whether to trust the client certificate: if the client certificate is determined to have a root authority that is recognized by Couchbase Server, the client certificate may be trusted.
The certificate's time-validity and other details are checked.
If the certificate has not expired and is valid in all other necessary respects, the _username_ provided by the certificate is determined, and this is checked against Couchbase Server-registered users and their roles.
If the user exists, and the associated roles are appropriate, access is granted; otherwise, access is denied.

Note that the private key used to create the client certificate may itself be required for the client to authenticate itself against the server: data encrypted by the client using the client's private key can be provided to the server, and duly decrypted by the server using the client's public key, thereby confirming the identity of the client.
(An example of this, in the context of securing XDCR, is provided in xref:manage:manage-xdcr/enable-full-secure-replication.adoc#specify-full-xdcr-security-with-certificates[Specify Root and Client Certificates, and Client Private Key].)

[#identity-encoding-in-client-certificates]
==== Specifying Usernames for Client-Certificate Authentication

The _username_ to be authorized by Couchbase Server can be specified as any of several elements included in the client certificate.
Couchbase Server can be configured to search for the appropriate element within the client certificate, and then endeavor to authenticate with it as a Couchbase-Server _username_.

[#specifying-usernames-in-certificates]
===== Embedding Usernames in Certificates

Within a certificate presented for authentication, the elements that can be used to specify a username include the following:

* The `Subject` for the certificate, featuring the _Common Name_.
This is a standard for most clients.
For example, on the command-line, during client-certificate preparation, `-subj "/CN=clientuser"` might be specified; to allow `clientuser` to be identified as the username.

* The `DNS` name, provided as a _Subject Alternative Name_ for the certificate.
For example, `subjectAltName = DNS:node2.cb.com` might be specified during client-certificate preparation, to allow `node2.cb.com` to be identified as the username.

* The `EMAIL`, provided as a _Subject Alternative Name_ for the certificate.
For example, `subjectAltName = EMAIL:john.smith@mail.com` would allow `john.smith` to be extracted and identified as the username.

* The `URI` provided as a _Subject Alternative Name_ for the certificate.
For example, `subjectAltName = URI:www.acme.com` would allow `www.acme.com` to be identificed as the username.

Examples of specifying Subject Alternative Names are provided in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates] and xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates].

[#client-certificate-enablement]
===== Identifying Certificate-Based Usernames on Couchbase Server

Client-certificate handling is _disabled_ by default, on Couchbase Server: it can optionally be _enabled_; and if required, specified as _mandatory_.

Whence client-certificate handling has been enabled, multiple combinations of _path_, _prefix_, and _delimiter_ values can be specified to be attemptedly matched with the content of client certificates presented for authentication.
For example, specifying the path `subject.cn` would indicate that the `Subject` for the certificate, featuring the _Common Name_, should be located and used as the _username_ to be authenticated.
Or, specifying the path `san.dns` would indicate that the `DNS` Subject Alternative Name for the certificate should be located and used.

For full details, see xref:manage:manage-security/enable-client-certificate-handling.adoc[Enable Client Certificate Handling].

[#examples]
== Examples

Examples of file-types and their generation, of extension-definition, of intermediate-certificate use, and of Couchbase-Server specific deployment requirements are provided for the server-side in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates], and for the client-side in xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates].
The examples allow _Cross Data Center Replication_ to be secured with certificates only, and support secure access to Couchbase Server from Java clients.
