= Certificates
:page-aliases: security:security-certs-auth,security:security-encryption

[abstract]
Couchbase Server supports x.509 certificates for client and server.

[#certificates-in-couchbase]
== Certificates in Couchbase

Couchbase supports the use of x.509 certificates, for clients and servers.
This ensures that:

* Only approved users, applications, machines, and endpoints have access to system resources.
For example, the mechanism can be used by Couchbase SDK clients, to access Couchbase Services; and by source clusters that use XDCR to replicate data to target clusters.

* Clients can verify the identity of Couchbase Server, thereby ensuring that they are not exchanging data with a rogue entity.

Full or Security Administrator privileges are required, for the management of certificates.

This page provides a general overview of certificates and their management in the context of Couchbase Server.
For step-by-step instructions on certificate creation and deployment, xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates] and xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates].

[#certificate-content]
=== Certificate Content

Certificate-based authentication relies on a Certificate Authority (CA), to validate identities and issue certificates.
Each certificate includes:

* The name of the entity it identifies.

* An expiration date.

* The name of the CA that issued the certificate.

* The digital signature either of the issuing CA, or of an intermediate certificate through which the authority of the issuing CA can be dynamically ascertained.

* A public key, which corresponds to the _private_ key that was used to generate the certificate; and which can therefore be used in conjunction with that private key in handling digital signatures and keys; so as to support authentication and secure communication between client and server.

This information associates the identified entity with the issuing CA, such that third parties who know and trust the CA, but are unfamiliar with the identified entity, may elect to trust the identified entity on the basis of their trust in the CA.
(Note that all systems that support use of certificates maintain a collection of trusted CA certificates, against which comparisons are made.)

Additionally, certificates may each be configured to contain _extensions_, which might be used to constrain the certificate's capabilities (for example, by indicating the IP address of the server on which the certificate must reside; or by indicating the uses to which its public key must be restricted); or to identify a _username_, based on which client-authentication and authorization can proceed.

[#certificate-hierarchies]
=== Certificate Hierarchies

On a Couchbase Server-cluster, certificates are managed and deployed _hierarchically_.
The certificate with overall authority for the cluster is at the top of the hierarchy; and its authority is inherited by all certificates on lower tiers of the hierarchy.
One certificate allows another certificate to inherit its authority by the process of _certificate signing_.

A _single-tier_ certificate hierarchy is one where the CA has issued a certificate directly for the identified entity.
If the receiving system trusts the CA, then the identified entity is trusted.
The CA, since at the top of this two-element hierarchy, is referred to as the root CA.

An _n-tier_ certificate hierarchy is one where a root CA has issued a certificate to an intermediate authority, which in turn has issued a certificate either to another intermediate authority, or directly to the identified entity.
Use of an n-tier hierarchy requires that all intermediate certificates, as well as the entity's certificate, be available for inspection; otherwise, clients will assume that the connection is not secure.
This results in messages warning of an untrusted connection.
All certificates should therefore be made available in a complete _trust chain_: which is a file that contains the entity's certificates, concatenated with all intermediate certificates.

[#server-certificates]
== Server Certificate-Types

Couchbase Server uses different certificate-types to verify its identity in communications with clients.
A _cluster certificate_ establishes the authority for the entire cluster, and individual _node certificates_ (one for each node) inherit that authority.
Optionally, _intermediate_ certificates, which have been signed by the cluster certificate, can themselves be used to sign, and thereby provide authority to the node certificates.

These certificate-types are described below.

[#cluster-certificate]
=== Cluster Certificate

The cluster certificate is the _root certificate_ issued for the cluster; and contains the public key of corersponding Certificate Authority (CA).
Programs that wish to interact securely with Couchbase Server must elect to trust this CA.
By means of _certificate signing_, the cluster certificate grants its authority to other certificates: this includes both server-side and client-side certificates.
Thus, if client and server share the same root certificate, they are likely to trust one another.

Couchbase Server provides a default, self-signed cluster certificate, which is created and deployed when the first node in a cluster is created.
A new cluster certificate can be _deployed_ on the cluster by means of the Couchbase REST API.
The current cluster certificate is visible on the *Root Certificate* panel of the *Security* screen of Couchbase Web Console.
See xref:manage:manage-security/manage-security-settings.adoc#root-certificate-security-screen-display[Root Certificate].

The file for the cluster (indeed, for any other server or client) certificate must be in _Privacy Enhanced Mail_ (or _PEM_) format, with a `.pem` extension.
The file can have any name, although `ca.pem` is commonly used.
On creation, the certificate is generated (indeed, all certificates, whether server-side or client-side are generated) from a corresponding, already created _private key_; whose file is in RSA key format, with a `.key` extension.
The name of the private key often corresponds to the name of the certificate it generates: for example, `ca.key`.

Examples of creating cluster and other certificates based on private keys are provided in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates]

[#intermediate-certificates]
=== Intermediate Certificates

An _intermediate certificate_ can be either:

* A certificate signed by the cluster certificate.

* One of a chain of intermediate certificates, each of which has been signed by the previous in the chain; except the first, which has been signed by the cluster certificate.

The main purpose of the intermediate certificate is to sign _node certificates_ and _client certificates_, and thereby convey the authority of the cluster certificate to the node certificates _indirectly_.
This allows the cluster certificate to be maintained with due privacy, when multiple nodes or clients need to be signed.

[#node-certificate]
=== Node Certificates

Each node in a Couchbase Cluster has its own _node certificate_, which is signed either by the cluster certificate, or by a chain of one or more intermediate certificates, ultimately signed by the cluster certificate.
The process whereby, for a node being added or joined to the cluster, its node certificate is generated (based on a new private key) and signed (by means of the current cluster certificate and cluster private key) is entirely automated.
Certificate-based security for a Couchbase Server-cluster is thereby provided out-of-the-box.
However, no extension-based constraints, Subject Alternative Names, or other special features are provided: therefore, optimal security is likely to require _administrator-customized_ certificates, based on an administrator-selected root authority.

Node certificates _must_ be signed either by the cluster certificate, or by an intermediate certificate.
If the authority of the cluster certificate is not established in a node certificate in one of these ways, authorization failure occurs.

When node certificates have been prepared for a cluster, the following must be deployed on each node, for the certificate to become active:

* The node private key, which has been used to create the node certificate for the current node.
On each node, this must be named `pkey.key`.

* The node certificate chain-file.
On each node, this must be named `chain.pem`.
When the node certificate has been signed directly by the cluster certificate, `chain.pem` is nothing more than the node certificate file, renamed.
However, when the node certificate has gained the CA's authority by being signed a sequence of one or more intermediate certificates, `chain.pem` must be a correspondingly ordered _concatenation_ of all the certificates in the chain, except the cluster certificate.
Access to this file allows the authority of the node certificate to be established by progressive examination of the signing authorities in its chain.

Couchbase Server requires that these files, when newly created, be manually copied to a particular location in the filesystem: from this location, they are deployed by Couchbase Server.
Examples are provided in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates].

Unlike the cluster certificate, the text of which is displayed in Couchbase Web Console (as described in xref:manage:manage-security/manage-security-settings.adoc#root-certificate-security-screen-display[Root Certificate]), nodes certificates are not displayed to users; nor are the corresponding chain files.

[#client-certificates]
== Client Certificates

Client certificates allow a client to authenticate with a Couchbase Cluster.
Each client certificate contains the authentication information appropriate for a certain level of resource-access.

When authenticating a client that uses certificate-based authentication, Couchbase Server asks the client to present the client certificate.
If presented, the certificate's time-validity is checked.
If the certificate has not expired, the _username_ provided by the certificate is determined, and this is checked against Couchbase Server-registered users and their roles.
If the user exists, and the associated roles are appropriate, access is granted; otherwise, access is denied.

The private key used to create the client certificate may itself be required for the client to authenticate itself against the server: a signature that is encrypted by the client using the client's private key, and is then provided to the server, can be decrypted by the server using the client's public key, thereby confirming the identity of the client.
(An example of this, in the context of securing XDCR, is provided in xref:manage:manage-xdcr/enable-full-secure-replication.adoc#specify-full-xdcr-security-with-certificates[Specify Root and Client Certificates, and Client Private Key].)

[#identity-encoding-in-client-certificates]
=== Specifying Usernames for Client-Certificate Authentication

The _username_ to be authorized by Couchbase Server can be specified as any of several elements included in the client certificate.
Couchbase Server can be configured to search for the appropriate element within the client certificate, and then endeavor to authenticate with it as a Couchbase-Server _username_.

[#specifying-usernames-in-certificates]
==== Embedding Usernames in Certificates

Within a certificate presented for authentication, the elements that can be used to specify a username include the following:

* The `Subject` for the certificate, featuring the _Common Name_.
This is a standard for most clients.
For example, on the command-line, during client-certificate preparation, `-subj "/CN=clientuser"` might be specified; to allow `clientuser` to be identified as the username.

* The `DNS` name, provided as a _Subject Alternative Name_ for the certificate.
For example, `subjectAltName = DNS:node2.cb.com` might be specified during client-certificate preparation, to allow `node2.cb.com` to be identified as the username.

* The `EMAIL`, provided as a _Subject Alternative Name_ for the certificate.
For example, `subjectAltName = EMAIL:john.smith@mail.com` would allow `john.smith` to be extracted and identified as the username.

* The `URI` provided as a _Subject Alternative Name_ for the certificate.
For example, `subjectAltName = URI:www.acme.com` would allow `www.acme.com` to be identificed as the username.

Examples of specifying Subject Alternative Names are provided in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates] and xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates].

[#client-certificate-enablement]
=== Identifying Certificate-Based Usernames on Couchbase Server

Client-certificate handling is _disabled_ by default, on Couchbase Server: it can optionally be _enabled_; and if required, specified as _mandatory_.

Whence client-certificate handling has been enabled, multiple combinations of _path_, _prefix_, and _delimiter_ values can be specified to be attemptedly matched with the content of client certificates presented for authentication.
For example, specifying the path `subject.cn` would indicate that the `Subject` for the certificate, featuring the _Common Name_, should be located and used as the _username_ to be authenticated.
Or, specifying the path `san.dns` would indicate that the `DNS` Subject Alternative Name for the certificate should be located and used.

For full details, see xref:manage:manage-security/enable-client-certificate-handling.adoc[Enable Client Certificate Handling].

[#examples]
== Examples

Examples of file-types and their generation, of extension-definition, of intermediate-certificate use, and of Couchbase-Server specific deployment requirements are provided for the server-side in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates], and for the client-side in xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates].
The examples allow _Cross Data Center Replication_ to be secured with certificates only, and support secure access to Couchbase Server from Java clients.
