= Credential Store
:description: The credential store lets you securely store and use credentials for authenticating with external systems that Couchbase Server services and users need to access.
:page-toclevels: 2
:page-edition: Enterprise Edition

[abstract]
{description}
The credential store is for external credentials such as those used to authenticate with AWS S3 or REST APIs.
You only use it to store credentials to authenticate outgoing requests to other hosts. 
It does not play any role in users or clients authenticating with Couchbase Server.
However, you can use it to the store credentials users and services use to authenticate with other Couchbase Server or Capella clusters.

== Credential Store Benefits

The credential store makes managing credentials easier while also reducing the risk of exposing them:

* You grant users and groups the ability to authenticate with external systems without disclosing the credential to them. 
The user chooses a credential from the credential store when authenticating with a supported external host. 
If you have granted them permission to use the credential, Couchbase Server's services use the credential to authenticate on the user's behalf.

* You use roles-based access control (RBAC) to grant and revoke user's access to the credentials.
It works the same way you grant them access to other Couchbase features such as buckets.

* You can also directly grant a service access to credentials. 


* The credential store removes the need for hard-coding credentials in scripts and queries. 
These hard-coded credentials are a security threat.
They are also hard to maintain.

* Centralizing credentials simplifies rotating them. 
You do not need to notify users of credential updates. 
When you update a credential in the credential store, users use the updated credential automatically.

+
Centralization also helps you automate credential rotations. 
You can create a script that periodically renews credentials such as access tokens and stores them in the credential store. 
Your applications transparently use the updated credentials without having to managing renewals on their own.

* You can limit how a user can use credential by setting guardrails on it.  
For more information, see <<#guardrails>>.

## Credential Store Uses

The following Couchbase Server features support authenticating with third parties using the credential store:

* xref:learn:services-and-indexes/services/continuous-backup.adoc[Continuous backup] uses the credential store to authenticate with cloud storage locations.
* The {sqlpp} xref:n1ql:n1ql-language-reference/curl.adoc[`CURL()`] function supports using a credential when authenticating with web sites.
* Querying data from Apache Iceberg tables requires credentials to read from the catalog provider and the data store. 
 
// FIXME: add link to external collections doc once written.

## Supported Credential Types

The credential store supports storing specific types of credentials for the set of providers:


[cols="1,3"]
|===
| Provider | Credential Types

| AWS
| Access keys

| Azure 
| Active Directory, managed identity, SAS, and shared key

| Couchbase
| Basic + TLS, mTLS

| GCP
| HMAC Keys, Service Account Key

| HTTP
| Basic, bearer token, mTLS
|===

Each type of credential has its own required an optional information. 

NOTE: You can create a Couchbase credential type, but currently it cannot be used to authenticate with any Couchbase service. 

== Credential Permissions

You grant users and groups access to credentials using the Credential Consumer RBAC role. 
For more information about roles, see xref:learn:security:roles.adoc[].
You add the IDs of the credentials they can use to the role's parameter list.

Granting a user the ability to use a credential does not let them view the credential's secrets. 
Instead, it allows users to ask a service to use the credential on their behalf when they need to authenticate with an external system. 

You can also directly grant Couchbase services access to a credential for their own use. 
For example, you can configure continuous backup to use a cloud-based storage location to store its backups. 
To let it authenticate with the storage provider, you must grant the Backup Service access to a credential. 

To administer credentials, a user must have the xref:learn:security/roles.adoc#full-admin[Full Admin], xref:learn:security/roles.adoc#credential-admin[Credential Admin], or xref:learn:security/roles.adoc#security-admin[Security Admin] RBAC roles.
For more information about roles, see xref:learn:security/roles.adoc[].

[#guardrails]
## Guardrails

You can limit a credential's use by defining guardrails.  
They let limit the use of a credential to a specific website or even specific URL (such as a single REST API endpoint). 
This limitation prevents exposing the credential to unrelated sites or granting the user access to resources they should not be able to access.

### Guardrail Restrictions

Couchbase Server supports 2 types of guardrail restrictions on credentials:

[#allowed-services]
Which service can use the credential on behalf of a user::
When creating a credential, you choose which services you allow to use the crdential on behalf of a user. 
For example, the Query Service needs credentials to authenticate with catalog providers and storage locations when fulfilling user queries of Apache Iceberg external collections.
When creating these credentials, you must add the Query Service to the list of allowed services.
If you do not, the Query Service cannot use the credential on behalf of the user.

+
If you do not add any services to the list of allowed services, then services cannot use the credential on behalf of a user.
In this case, only services you directly grant access can use the credential for their own use.
Guardrails do not apply to an authorized service using the credential for its own use. 

[#url-restrictions]
URL and endpoint restrictions::
A guardrail can allow or deny the use of a credential based on the URI of the remote system.
You can choose to allow services to use the credential to authenticate the user with any URL. 
Or you can supply a list of URLs that the credential is allowed for. 
You can further refine the list of allowed URLs by supplying a list of disallowed URLs to exempt them from the allowed list.

+
For example, suppose you set a credential's allowed URLs list to `\https://example.com/` and its disallowed list to `\https://example.com/forbidden-endpoint`. 
Then a service can use the credential to authenticate on behalf of the user with most URLs on `example.com`, such as `\https://example.com/some-endpoint`.
However, the disallowed list prevents a service from authenticating with the `\https://example.com/forbidden-endpoint` endpoint or any endpoints under it. 

### Guardrail Enforcement

Service guardrails are enforced in 2 levels.

* Couchbase Server enforces a credential's service restriction.
When a user asks a service to use a credential on their behalf, Couchbase Server makes sure that the service is in the credential's allowed services list.
If it's in the service list, Couchbase Server sends the credential to the service.
Otherwise, Couchbase Server returns an error.

* The service performing an action on behalf of the user enforces any URL and endpoint restrictions.

### When Guardrails Apply

Guardrails only apply to users accessing credentials. 
They do not apply when services use credentials that you have directly granted to them for their own use.

For example, suppose a user calls the xref:n1ql:n1ql-language-reference/curl.adoc[`CURL()`] function in a {sqlpp} query to make a request to an external system.
They can specify a credential in the credential store for  `CURL()` to use when authenticating with the remote host. 
In this case, the Query Service is using the credential on behalf of the user, so it's subject to guardrail restrictions. 
Before allowing the Query Service to access the credential, Couchbase Server verifies that the credential allows the Query Service to use it on behalf of the user.
If the credential has the Query Service (`n1ql`) in its list of allowed services, Couchbase Server sends the credential to the service 

[#expiration]
## Credential Expiration

Credentials can have an expiration timestamp. 
When the expiration date and time for the credential passes, attempts to use the credential fail with a credential expiration error.

It's good practice to set the credential's expiration to earlier than any expiration built into the underlying authentication credentials.
Doing so provides applications with a more predictable error message in case the credentials expire.

For example, suppose you have a credential for an HTTP bearer token that expires every 24 hours. 
You have a script that automatically renews the token with the authentication provider every 12 hours or so.
The 12 hour renewal margin leaves plenty of room for retrying failed renewals caused by the authentication provider being down or network issues.
After renewal, the script calls Couchbase Server's REST API to update the credential containing the token so that the credential remains valid.

In this case, you can have the renewal script set the expiration for the credential to less than 24 hours.
For example, you might choose to have the credential expire in 21 hours.
This value leaves a 3 hour buffer between the expiration of the credential and the bearer token.
With this buffer, any issues with the token renewal result in a Couchbase Server credential error rather than an error from the remote host.
You can then have your applications handle a predictable Couchbase Server error instead of a range of errors that the remote hosts may throw.

