= Encryption

[abstract]
Couchbase Server uses _encryption_, to protect data.

[#encryption-in-couchbase-server]
== Encryption in Couchbase Server

By means of _encryption_, data is encoded such that it cannot be comprehended; other than by _authorized_ parties, who possess the appropriate means of _decryption_.

Support is provided for data encryption and decryption across multiple areas of Couchbase Server.
Essential information is therefore distributed throughout the documentation set.

[#areas-of-encryption]
== Areas of Encryption

The lists below contain the principal areas of encryption-support, and provide a brief summary of each, with appropriate links.

[#encryption-on-the-wire]
=== Encryption on the Wire

This allows data to pass in encrypted form between nodes, clusters, or data centers.

* _Secure Console Access_.
Administrators can connect security with Couchbase Web Console.
Non-secure access can optionally be disabled, for extra security.
See xref:manage:manage-security/manage-console-access.adoc[Manage Console Access].

* _Secure Ports_.
Services are available on secure ports.
See xref:install:install-ports.adoc[Network and Firewall Requirements].

* _General Network Security_.
Best practices for ensuring the security of the network.
See xref:manage:manage-security/manage-connections-and-disks.adoc[Network Security Recommendations].

* _X.509 Certificates_.
These support encrypted communications between the nodes of a cluster, between clusters, and between a cluster and its clients.

** xref:learn:security/certificates.adoc[Certificates] provides an overview of certificates and their management.

** xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates] explains the practical steps towards configuring certificates for Couchbase Server.

** xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates] describes how to create a certificate to allow a client's secure access to Couchbase Server.

** xref:manage:manage-security/enable-client-certificate-handling.adoc[Enable Client-Certificate Handling] explains how to configure Couchbase Server to accept communications from clients that wish to authenticate and communicate securely by means of certificates.

** xref:manage:manage-security/rotate-server-certificates.adoc[Rotate Server Certificates] provides steps whereby server certificates can be _rotated_ periodically, to ensure optimal security.

** xref:manage:manage-security/handle-certificate-errors.adoc[Handle Certificate Errors] explains how to handle errors, related to certificate-based secure communication.

** xref:manage:manage-xdcr/enable-full-secure-replication.adoc[Enable Fully Secure Replications] describes how certificates can be used to ensure that data is replicated securely between clusters.

[#encryption-at-rest]
=== Encryption at Rest

Encryption _at Rest_ (meaning, _on disk_) allows passwords and data in files and directories to be encrypted.

* _Data in Files and Directories_.
Programs are available for the encryption of data in files and directories.
See xref:manage/manage-security/manage-connections-and-disks.adoc#securing-on-disk-data[Securing On-Disk Data].

* _System Secrets_.
Passwords, certificates, and other items essential to security can be written to disk in encrypted format.
See xref:manage/manage-security/manage-system-secrets.adoc[Manage System Secrets].

[#encryption-in-applications]
=== Encryption in Applications

* _Field Level Encryption_.
This allows fields within a document to be securely encrypted by the SDK, to support FIPS-140-2 compliance.
See xref:3.0@java-sdk:concept-docs:encryption.adoc[Encryption at Rest], for an overview.

* _Field Level Encryption from the Java SDK_.
Provides directions for configuring encrypted field-level communication with Couchbase Server.
