= Encryption

[abstract]
Couchbase Server uses _encryption_, to protect data.

[#encryption-in-couchbase-server]
== Encryption in Couchbase Server

By means of _encryption_, data is encoded such that it is non-readable, other than by authorized parties who possess the appropriate means of _decryption_.
Prior to decryption, therefore, encrypted data can be either saved or transmitted securely.
This ensures the privacy of user-data, and the integrity of servers and their clients.

Couchbase Server provides extensive support for data encryption and decryption.
Multiple areas of the system are affected: therefore, essential information is distributed throughout the documentation set.

[#areas-of-encryption]
== Areas of Encryption

The principal areas of Couchbase Server encryption-support are listed below, along with links to further information.

[#encryption-on-the-wire]
=== Encryption on the Wire

This allows data to pass in encrypted form between nodes, clusters, and data centers.

* *Secure Console Access*.
Administrators can connect securely to Couchbase Web Console.
Non-secure access can be disabled, for extra security.
See xref:manage:manage-security/manage-console-access.adoc[Manage Console Access].

* *X.509 Certificates*.
These support encrypted communications between the nodes of a cluster, between clusters, and between a cluster and its clients.

** xref:learn:security/certificates.adoc[Certificates] provides an overview of certificates and their management.

** xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates] explains the practical steps towards configuring certificates for Couchbase Server.
This page also provides information on working with different versions of SSL/TLS, and on supported _ciphers_.

** xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates] describes how to create a certificate to allow a client's secure access to Couchbase Server.

** xref:manage:manage-security/enable-client-certificate-handling.adoc[Enable Client-Certificate Handling] explains how to configure Couchbase Server to accept communications from clients that wish to authenticate and communicate securely by means of certificates.

** xref:manage:manage-security/rotate-server-certificates.adoc[Rotate Server Certificates] provides steps whereby server certificates can be _rotated_ periodically, to ensure optimal security.

** xref:manage:manage-security/handle-certificate-errors.adoc[Handle Certificate Errors] explains how to handle errors related to certificate-based secure communication.

** xref:manage:manage-xdcr/enable-full-secure-replication.adoc[Enable Fully Secure Replications] describes how certificates can be used to ensure that data is replicated securely between clusters.

** xref:rest-api:rest-encryption.adoc[Encryption On-the-Wire API] lists the REST API methods and URIs available for certificate management.
Also see xref:rest-api:security-encrypted-access.adoc[Using REST for Encrypted Access].

** The xref:cli/cbcli/couchbase-cli-ssl-manage.adoc[ssl-manage] CLI command supports management of SSL certificates.

* *Secure Ports*.
Services are available on secure ports.
See xref:install:install-ports.adoc[Network and Firewall Requirements].

* *General Network Security*.
Best practices for ensuring the security of the network are provided in xref:manage:manage-security/manage-connections-and-disks.adoc[Network Security Recommendations].

[#encryption-at-rest]
=== Encryption at Rest

Encryption _at Rest_ (meaning, on disk or other storage-device) allows passwords and data in files and directories to be encrypted.

* *Data in Files and Directories*.
Programs are available for the encryption of data in files and directories.
See xref:manage:manage-security/manage-connections-and-disks.adoc#securing-on-disk-data[Securing On-Disk Data].

* *System Secrets*.
Passwords, certificates, and other items essential to Couchbase-Server security can be written to disk in encrypted format.
See xref:manage:manage-security/manage-system-secrets.adoc[Manage System Secrets].

[#encryption-in-applications]
=== Encryption in Applications

* *Field Level Encryption*.
This allows fields within a document to be securely encrypted by the SDK, to support FIPS-140-2 compliance.
See 3.0@java-sdk:howtos:encrypting-using-sdk.adoc[Field Level Encryption], for an overview.

* *Field Level Encryption from the Java SDK*.
Provides directions for configuring encrypted field-level communication with Couchbase Server.
See 3.0@java-sdk:concept-docs:encryption.adoc[Field Level Encryption from the Java SDK].
