= Native Encryption at Rest Overview
:description: Couchbase Server can encrypt data, configuration, logs, and audit information it saves to disk. This encryption can help reduce the chances or severity of data breaches.
:page-toclevels: 2
:page-edition: Enterprise Edition

[abstract]
{description}
This feature is transparent to the database's users. 
Couchbase Server automatically decrypts data when read from disk and encrypts it when writing it to disk.
For steps to take when managing this feature, see xref:manage:manage-security/manage-native-encryption-at-rest.adoc[].

[#keys]
== Encryption-at-Rest Keys 

To encrypt data at rest, you must create at least one encryption key. 
Couchbase Server uses the keys you create directly to generate Data Encryption Keys (DEKs) which it uses to encrypt the information it stores on disk.
This two-layer system lets Couchbase Server manage the rotation and deletion of the DEKs.

You have two main choices to make when creating an encryption key:

* What system you want to  manage the key. 
The encryption keys can be managed by Couchbase Server, or by a Key Management Service. 
See <<#kms>> for more information about choosing a KMS.

* What data Couchbase Server can use the encryption key to encrypt. 
You can restrict the key to encrypting one or more types of data:

+
** **Other encryption keys** 
Makes the key a Key Encryption Key (KEK). 
You use a KEK to encrypt other encryption keys instead of relying on the database's master password.
** **Data**. 
You can use the key to encrypt all data or restrict its use to specific buckets.
** **Configuration**
** **Logs**
** **Audits**


The following sections explain these choices in greater detail.

== Encrypting Bucket Data

When using native encryption at rest to encrypt data in buckets, you choose which buckets to encrypt.
For example, you can decide to just encrypt buckets containing sensitive data (such as customer information).
You can also choose to leave less-sensitive data unencrypted (product catalog data, for example).
Encrypting just sensitive data can help reduce the overhead of encrypting and decrypting data on your cluster.

Each bucket can have its own encryption key.
This configuration is useful in multi-tenancy configurations where each customer can have their own encryption key.

== Encrypting Audit, Logs, and Configuration Data

In addition to data, you can encrypt audit, logs, and most configuration data. 
You can enable encrypting each type of information separately.
Each of these types of data can have its own encryption key.


[NOTE]
====
Some configuration data is not encrypted.
This includes:

* Bootstrap information
* Node and internal client certificates
* Prometheus configuration, metric data, and tokens used to gather metrics
====


You can use a single encryption key for encrypting all data, logs, audit, and configuration information.
This configuration is easy to configure, but is not flexible.
For more complex environments (such as multi-tenancy databases), you can choose to create multiple encryption keys.
You then choose keys to encrypt one or more buckets as well as logs, audits, and configuration data.
You can also create layers of encryption keys.
For example, you can have a primary encryption key that's managed by an external key management system (see <<#kms>>). 
Then you use the primary key to encrypt additional encryption keys.
You can then use these keys to encrypt bucket, log, configuration, or audit data.   



[#kms]
== Encryption Key Management Services

A key management service generates and stores the encryption keys Couchbase Server uses to encrypt its DEKs.
When you create a key, you choose which key management service you want to manage it.
Couchbase Server works with several key management services:

Couchbase Server Secret Management::
You can have Couchbase Server act as the key management system.
This method does not require any additional configuration.
However, using this method means that Couchbase Server stores your encryption keys locally, leaving them more vulnerable if there is a security breach.

AWS Key Management Service::
You can use the https://docs.aws.amazon.com/kms/latest/developerguide/overview.html[AWS Key Management Service] (AWS KMS) to manage keys for you.
Using this method requires some configuration.
However, this method is more secure because AWS keeps the encryption keys secure internally.
Even if one or more nodes in your cluster suffer a security breach, the encryption keys remain secure within the AWS KMS.
One downside of using the AWS KMS is that the cluster relies on an external source for its encryption keys.
Disruptions in AWS or the network could result in errors because the cluster cannot retrieve encryption keys to encrypt or decrypt data.

+
[#aws-kms-caution]
[CAUTION]
====
Do not use encryption keys managed by AWS KMS to directly encrypt data.
While retrieving individual encryption keys from AWS can take less than a second, cluster startup could result in many synchronous key retrievals.
These key retrievals can cause delays during cluster start.

Only use the encryption keys you store in the AWS KMS as Key Encryption Keys (KEKs).
Use these keys to encrypt Couchbase Server managed encryption keys. 
This method limits the number of retrievals from AWS while maintaining the security advantage of having keys managed by a remote KMS. 
====

KMSs that support Key Management Interoperability Protocol (KMIP)::
https://en.wikipedia.org/wiki/Key_Management_Interoperability_Protocol[KMIP] is a standards protocol implemented by key management services.
Couchbase Server can work with any KMS that implements this standard.
As with AWS KMS, using a KMIP-compliant KMS enhances security by storing the encryption keys remotely instead of locally in the cluster.
If you use a MKIP KMS encryption key as a KEK, you can have the KMS decrypt keys that the KEK encrypted for you. 
This measure improves security because the KMS does not have to send a copy of its encryption key to Couchbase Server.
Using a KMIP-compatile KMS also has the same downside--Couchbase Server may report errors due to KMS downtime or network issues.
Couchbase Server cannot decrypt data without the KMS's encryption keys.
Also, depending on the KMS implementation and its location, decrypting data could introduce performance issues due to latency.



[#kms-and-keys]
== Using Multiple KMSs and Multiple Keys

In a basic setup, you may choose to use a single encryption key managed by Couchbase Server to encrypt all data.
This configuration is easy to manage, but does not offer much flexibility.
Also, because Couchbase Server stores the encryption key locally, it does not provide a high level of security.

Couchbase Server does not limit you to a single KMS.
You can choose any KMS for each encryption key.
For example, you can choose to create one or more encryption keys managed by AWS KMS or a KMIP-compliant KMS.
Use these keys as Key Encryption Keys (KEKs) to encrypt keys that Couchbase Server manages.
This method adds a layer of security to the locally managed encryption keys while reducing the number of key retrievals from the remote KMS.
Remember that you should not use an AWS managed key to directly encrypt data because of the latency of fetching the key remotely.

The following diagram shows a possible configuration using a single primary encryption key hosted by AWS KMS. 
This key encryption key encrypts five encryption-at-rest keys managed by Couchbase Server.
Each of these keys are assigned to different types of data that's written to disk: Audit, Config, and Log data and the data stored in two buckets named "A" and "B."
Each node in the cluster has Data Encryption Keys (DEKs) encrypted by the intermediate encryption keys managed by Couchbase Server.
For simplicity, the diagram only shows two nodes.
However, this configuration can scale to any size cluster. 


image::security/encryption-at-rest-key-hierarchy.svg["Diagram showing a single AWS key encrypting 5 Couchbase Server managed KEKs which in turn encrypt DEKs on each node"]

You can have even more complex hierarchies where there are several keys hosted by AWS KMS or a KMIP KMS.


[#rotation-expiration]
== Encryption Key Rotation and Expiration

Key rotation periodically retires old keys and generates new encryption keys to replace them.
Frequent rotations limit the amount of data encrypted with any one key.
It helps limit the exposure of data if a data breach compromises an encryption key.

You can choose to have Couchbase Server rotate DEKs automatically.
You can also have it automatically rotate encryption keys that it manages.
Rotation of an externally-managed encryption key is handled by the KMS that manage it.
By default, Couchbase Server automatically rotates DEKs but not the encryption keys it manages. 
You choose how frequently Couchbase Server rotates DEKs and (if you enable it) its encryption keys.

When Couchbase Server generates a new encryption key or DEK during rotation, it does not immediately delete the expired key.
It keeps the expired keys so it can decrypt the data encrypted with the older key. 
It uses the new key to encrypt data as it writes it to disk.
When rotating DEKs, Couchbase Server does not re-encrypt existing data unless it's mutated.

Couchbase Server only deletes an expired DEK when either:

* No data uses the DEK for encryption. 
Once the last piece of data that relies on the DEK for decryption is either mutated or deleted, Couchbase Server deletes the unused DEK.

* The DEK's lifetime elapses.
You can set a maximum lifetime for DEKs which limits how long Couchbase Server an keep it after rotation.
When a DEK's lifetime elapses, Couchbase Server uses the active DEK to re-encrypt any data that's still encrypted with the expired DEK.
It then deletes the expired DEK.

You can adjust the rotation and lifetime for encryption keys to suit your environment.

See xref:manage:manage-security/manage-native-encryption-at-rest.adoc[] to learn how to manage native encryption at rest.
