= On-the-Wire Security

[abstract]
To support secure communications between nodes, clusters, and clients, Couchbase Server provides interfaces for the configuration of on-the-wire security.

[#understanding-on-the-wire-security]
== Understanding On-the-Wire Security

The interfaces provided by Couchbase Server for configuring on-the-wire security apply to the following areas:

* _Accessing the UI provided by Couchbase Web Console_.
This can be optionally disabled; over either http or https, or over both.

* _Establishing the Cluster Encryption-Level_.
The level of encryption imposed on inter-node communications within the cluster can be configured: either as _control_ (meaning that only server-management information is passed in encrypted form) or _all_ (meaning that all information, including data handled by services, is passed in encrypted form).
+
This can only be configured after cluster encryption itself has been _enabled_: see xref:learn:clusters-and-availability/node-to-node-encryption.adoc[Node-to-Node Encryption].

* _Configuring TLS and Cipher-Suites_.
This includes establishing the cluster's minimum TLS version; determining whether the server's or the clients' cipher-order is used in a given communication; and configuring the list of cipher-suites that is accepted by the server.
Details are provided immediately below.

[#tls-and-cipher-suites]
== TLS and Cipher-Suites

_Transport Layer Security_ (TLS) is a protocol that provides security over a computer network.
Couchbase Server supports the configuration of TLS, to secure communications between cluster-nodes, clusters, and external clients: this includes selection of an appropriate TLS version.

TLS supports multiple methods for exchanging keys, encrypting data, and authenticating message-integrity.
Appropriate methods, supported by both participants in an intended networked communication, can be specified through selection of an appropriate _cipher-suite_, from defined lists of ones acceptable.

When a TLS connection is established between a client application and Couchbase Server &#8212; for example, using the secure port `18091` &#8212; a _handshake_ occurs, as defined by the https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_handshake[TLS Handshake Protocol].
As part of this exchange, the client sends to the server the client's own cipher-suite list; which specifies the cipher-suites that the client itself supports.
A server-setting is provided to specify whether the server then conforms to its own or the client's preference, in selecting a commonly acceptable cipher-suite to be used for the communication.

Once the selection has been made by Couchbase Server, Couchbase Server notifies the client of the selection, and the handshake process continues.

[#configuring-tls-and-cipher-suites]
=== Configuring TLS and Cipher-Suites
