= Roles
:description: pass:q[Roles grant users access to one or more resources.]
:page-aliases: security:security-roles,security:concepts-rba,security:concepts-rba-for-apps,security:rbac-ro-user,learn:security/resources-under-access-control,security:security-resources-under-access-control
:page-toclevels: 3

[abstract]
{description}
Administrators assign roles to users to enable them to perform the tasks they need to carry out when using Couchbase Server.


[#roles-and-privileges]
== Roles and Privileges

Roles provide a set of privileges for interacting with a resource.
These privileges are often specific. 
For example, the Data Writer role lets a user write data using key-value operations.
This role does not let the user read data.
The Data Reader role grants that ability.

Some roles let the you limit the privileges a role grants to specific collections, scopes, or buckets.
For example, when granting a user the Data Writer role, you can limit the user so they can only write to a specific collection. 
You can also enable the user to write data to multiple collections, multiple scopes, or even to all buckets.
For detailed information about scopes and collections, see xref:learn:data/scopes-and-collections.adoc[].

You can grant a user a set of roles to precisely tailor their privileges so they can perform their tasks in the database.
Some roles, such as Query List Index, are so limited that they're only useful in conjuction with other roles.
For example, you can grant a user the ability to read all data in a specific bucket via the Data Reader role.
In addition, you can grant the user the Data Writer role, but limit them to writing data into a specific collection within the bucket.

[#roles-in-relation-to-buckets]
=== Roles in Relation to Buckets

Some roles provide privileges to resources across the entire cluster. 
For example, most administrator roles grant the user access to resources cluster wide.
Other roles, such as those dealing with managing data, let the administrator granting the role limit its privileges to specific buckets, scopes, or collections.

[#commonly-used-roles]
=== User Categories

Couchbase Server users fall into three categories: administrators, developers, and applications.
Which roles you assign to a user often depends on which category they fall into:

Administrators::
Users with any of the administrator roles can log into Couchbase Server Web Console and perform administrative tasks.
Most of  these roles do not grant the ability to read or write data.
+
The administrative roles grant their users the ability to carry out specific tasks.
For example, a user with the Cluster Admin role can manage all cluster features except for security.
Users with the <<#read-only-admin,Read-Only Admin>> role can access the Couchbase Server Web Console to  read cluster settings, statistics, and backup plans, but not change them.
The Bucket Admin role allows management only of one or more buckets.
See <<#admin-roles>> for details.
+
NOTE: The user interface of the Couchbase Web Console changes based on the role the user has.
For example, only the Full Admin role lets a user access the entire **Security** screen.
Users with either the Local User Admin or the External User Admin roles can only see the **Users & Groups** tab on this screen.

Applications::
An application needs to have a user account to authenticate with Couchbase Server.
You often assign these users roles that let them read or write data or other limited privileges.
Most of the roles you grant applications do not allow them to log into Couchbase Server Web Console or modify cluster settings.
For example, the <<#data-reader>> and <<#data-writer>> roles lets the user read and write data using key-value operations.
You can limit these privileges to one or more collections, scopes, or buckets.
Other roles appropriate for applications are <<#manage-scopes>>, <<#data-dcp-reader>>, and <<#data-backup-and-restore>>.


Developers::
User accounts for developers require more privileges to access data and manage resources than applications.
However, they should not have the unrestricted privileges that most Administrator roles grant.
These roles do let users log into the Couchbase Server Web Console, so they can perform tasks in a GUI environment.
You can tailor the roles you grant to developers so they have just enough privileges to perform their tasks.
For example, the <<#analytics-admin>> and <<#manage-global-external-functions>> roles were designed for interactive users.
They let them maintain some parts of your database.
However, they lack the ability to change cluster settings like most administrator roles.

== Role Overviews

The following sections describe the roles Defined by Couchbase Server. 
The list is broken into the same categories that appear within the Couchbase Server Web Console's *Edit User* dialog.
Each description has a table listing the resources the roles allow users to access, and any limitations on their access.
If a resource does not appear in this table, the role does not grant the user any privileges for it. 

NOTE: THe majority of roles are only availabe in Couchbase Server Enterprise Edition. 
The list indicates when a role is available in Community Edition.


[#admin-roles]
== Administrative Roles

The following roles grant users the ability to administer some aspects of Couchbase Server.

[#full-admin]
=== Full Admin

The Full Admin role (`admin`) grants full privileges to all Couchbase Server features and resources, including security.
The role lets the user log into to the Couchbase Server Web Console.

This role is also available in Couchbase Server Community Edition.

[#read-only-admin]
=== Read-Only Admin

The Read-Only Admin role lets the user read Couchbase Server settings and statistics. 
This information includes registered usernames with roles and authentication domains, but excludes passwords.
Users with this role can also read Backup Service data to monitor backup plans and tasks.

The role lets the user log into the Couchbase Server Web Console.

This role is also available in Couchbase Server Community Edition.

[#table_read_only_admin_role,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Read-Only Admin (`ro_admin`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| View configuration and statistics
| Cannot add, failover, remove, modify services, or rebalance

| *Buckets*
| List buckets, scopes, and collections
| Cannot create, drop, edit settings, read or write data

| *Backup*
| List repositories and plans
| Cannot add or edit repositories or plans. 

| *XDCR* 
| List remote clusters and outgoing replications 
| Cannot list incoming replications, or add or edit replications.

| *Security* 
| Can view settings for SAML, certificates, encryption at rest, audits, and other settings.
| Cannot change settings.

| *Settings*
| View all settings
| Cannot edit settings

| *Logs*
| View logs
| Cannot collect information

| *Indexes*
| Can view index settings and stats
| Cannot add, edit, or drop indexes

| *Query*
| None
| All

| *Search*
| Can view Search indexes
| Cannot edit or add Search indexes

| *Analytics*
| None
| All

| *Eventing*
| None
| All

| *Views*
| Can list defined views
| Cannot change views

|===

[#security-admin]
=== Security Admin

The Security Admin role grants the user the ability manage all security settings except for users and groups.

This role lets the user log into the Couchbase Server Web Console.

[#table_security_admin_role,cols="1,2,2,hrows=2]
|===
3+^| Role: Security Admin (`security_admin`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| View configuration and statistics
| Cannot add, failover, remove, modify services, rebalance

| *Buckets*
| List buckets, scopes, and collections
| Cannot create, drop, edit settings, read or write data

| *Backup*
| None
| All 

| *XDCR* 
| List outgoing replications
| Cannot create, start, alter connections

| *Security* 
| Manage LDAP, SAML, certificates, encryption at rest, audit, and logging settings.
| Cannot view or change users or groups.

| *Settings*
| View
| Change

| *Logs*
| View
| Collect Information

| *Query*
| None
| All

| *Search*
| None
| All

| *Analytics*
| None
| All

| *Eventing*
| None
| All

| *Views*
| None
| All

|===




[#local-user-security-admin]
=== Local User Admin

The Local User Admin role lets a user manage users defined in the xref:learn:security/authentication-domains.adoc#local-domain[local authentication domain].
It also grants the ability to read all cluster statistics such as the settings, logs, and buckets.
It does not grant the ability to read data.

NOTE: While this role does not allow the user to read or write data, they can create users that can read and write data.
This could be considered a privilege escalation, but it's intentional behavior.
This role is intended to manage all non-administratior roles, including those that can read or write data.
You can address any possible privilege escalation concerns by auditing the actions of users with this role to see if they create users to get around the data access limitations. 

This role allows users to edit local users, but they cannot grant these users the Full Admin, Read-Only Admin,  Local User Admin, or External User Admin roles.
They also cannot edit the accounts for any user with those roles (including their own account).

NOTE: This role replaced the Local User Security Admin role available in Couchbase Server prior to version 8.0.
The Local User Security Admin role had additional administration privileges that were split off into the <<#security-admin>> role. 
When upgrading to 8.0 or restoring a backup from a pre-8.0 version to Couchbase Server 8.0 or later, users with the Local User Security Admin role are granted this role and the <<#security-admin>> role.
This conversion ensures the user retains the privileges they had in prior versions.

This role lets users log into the Couchbase Server Web Console.

[#table_security_admin_local_role,cols="1,2,2,hrows=2"]
|===
3+^| Role: Local User Admin (`user_admin_local`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| View statistics
| Add, failover, remove, modify services, rebalance

| *Buckets*
| List buckets, scopes, and collections
| Create, drop, edit settings, read or write data

| *Backup*
| None
| All

| *XDCR* 
| All
| None

| *Security* 
| Add, delete, edit local users. 
Can add, delete, and edit groups.
| Cannot grant Full Admin, Read-Only Admin, Local or External User Admin, or Security Admin roles to users or groups.
Cannot access non-user and group security resources.

| *Settings*
| View
| Change

| *Logs*
| View
| Collect Information

| *Query*
| None
| All

| *Search*
| None
| All

| *Analytics*
| None
| All

| *Eventing*
| None
| All

| *Views*
| None
| All

|===

[#external-user-security-admin]
=== External User Admin

The External User Admin role lets users manage users defined in the xref:learn:security/authentication-domains.adoc#external_domain[external authentication domain].
It also lets the user manage groups and read all cluster statistics.
Users with this role cannot grant external users or groups Full Admin, Read-Only Admin, Security Admin, or Local or External User Admin roles.
They also cannot edit users with those roles. 

NOTE: This role replaced the External User Security Admin role available in Couchbase Server prior to version 8.0.
The External User Security Admin role had additional administration privileges that were split off into the <<#security-admin>> role. 
When upgrading to 8.0 or restoring a backup from a pre-8.0 version to Couchbase Server 8.0 or later, users with the External User Security Admin role are granted this role and the <<#security-admin>> role.
This conversion ensures the user retains the privileges they had in prior versions.

This role lets the user log into the Couchbase Server Web Console.

[#table_security_admin_external_role,cols="1,2,2,hrows=2"]
|===
3+^| Role: External User Admin (`user_admin_external`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| View statistics
| Add, failover, remove, modify services, or rebalance servers

| *Buckets*
| List buckets, scopes, and collections
| Create, drop, edit settings, read or write data

| *Backup*
| None
| All

| *XDCR* 
| View list of outgoing replications
| View incoming replications, remote clusters, add or edit connections

| *Security* 
| Add, delete, edit external users.
Add, delete, and edit groups.
| Cannot grant Full Admin, Read-Only Admin, Local or External User Admin, or Security Admin roles to groups or external users.
Cannot access security resources besides users and groups.

| *Settings*
| View
| Change

| *Logs*
| View
| Collect Information

| *Query*
| None
| All

| *Search*
| None
| All

| *Analytics*
| None
| All

| *Eventing*
| None
| All

| *Views*
| None
| All

|===

[#cluster-admin]
=== Cluster Admin

The Cluster Admin role lets the user manage of all cluster features except security.
Cluster Admins can create, edit, and drop buckets but cannot read or write data.

This role lets users log into the Couchbase Server Web Console.

[#table_cluster_admin_role,cols="1,2,2,hrows=2"]
|===
3+^| Role: Cluster Admin (`cluster_admin`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| All
| None

| *Buckets*
| Create, drop, edit settings
| Read or write data

| *Backup*
| None
| All

| *XDCR* 
| All
| None

| *Security* 
| None
| All

| *Settings*
| All
| None

| *Logs*
| All
| None

| *Query*
| None
| All

| *Search*
| None
| All

| *Analytics*
| None
| All

| *Eventing*
| Import, Change Settings
| Add, remove, edit functions 

| *Views*
| None
| All

|===

[#eventing-full-admin]
=== Eventing Full Admin

The Eventing Full Admin role lets a user create and manage eventing functions as well as other administration tasks.

The role lets the user log into the Couchbase Server Web Console.

[#table_eventing_admin_role,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Eventing Full Admin (`eventing_admin`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| View configuration and statistics
| Cannot add, failover, remove, modify services, rebalance

| *Buckets*
| List buckets, scopes, and collections. 
Can create, compact, and drop buckets, scopes, and collections.
Can read and write data in buckets.
| None

| *Backup*
| List repositories and plans
| Cannot add or edit repositories or plans 

| *XDCR* 
| List outgoing replications 
| Cannot list incoming replications or remote clusters.
Cannot add or edit replications.

| *Security*
| None
| All

| *Settings*
| View all settings and load sample buckets
| Cannot edit settings

| *Logs*
| View logs
| Cannot collect information

| *Indexes*
| All
| None

| *Query*
| All
| None

| *Search*
| All
| None

| *Analytics*
| All   
| None

| *Eventing*
| All
| None

| *Views*
| All  
| None

|===


[#backup-full-admin]
=== Backup Full Admin

The Backup Full Admin role lets the user administer backup-related tasks as well as other aspects of Couchbase Server.

NOTE: This role does not grant the ability to back up or restore users.
For a user to be able to back up both data and users, you must assign them the <<#local-user-security-admin>> and the <<#external-user-security-admin>> roles in addition to this role.

This role lets the user log into Couchbase Server Web Console.

[#table_backup_admin_role,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Backup Full Admin (`backup_admin`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| All
| None

| *Buckets*
| All, including add and drop buckets and edit, add, and drop documents
| None

| *Backup*
| All
| None

| *XDCR* 
| All
| None

| *Security*
| None
| All

| *Settings*
| All
| None

| *Logs*
| View logs
| Cannot collect information

| *Query*
| All
| None

| *Indexes*
| All
| None


| *Search*
| All
| None

| *Analytics*
| All   
| None

| *Eventing*
| All
| None

| *Views*
| All  
| None

|===

[#views-admin]
=== Views Admin

The Views Admin role lets the user create, modify, and drop views in one or more buckets.  
When granting this role, you choose the buckets where the user can manage views.

This role lets the user log into Couchbase Server Web Console.

[#table_views_admin_role,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Views Admin (`views_admin`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| View configuration and statistics
| Cannot add, failover, remove, modify services, or rebalance servers

| *Buckets*
| Can read, write, and edit views for the buckets they have been granted access to. 
Can read data (via key-value), statistics, and settings in these buckets.
| Cannot write data to buckets or alter bucket settings

| *XDCR*
| Can list outgoing replications
| Cannot view incoming replications or change XDCR settings

| *Settings*
| View all settings
| Cannot edit settings

| *Logs*
| Can view logs
| Cannot collect data

| *Query*
| None
| Cannot execute queries

| *Search*
| Can view Search indexes
| Cannot edit or add Search indexes

| *Views*
| Can create, drop, and edit views in buckets they have been granted access to.
| Cannot change views


|===


[#external-stats-reader]
=== External Stats Reader

The External Stats Reader role grants only allows the user to call the `/metrics` and `/prometheus_sd_config` REST API endpoints.
Assign this role to the user Prometheus uses when authenticating with Couchbase Server. 
See xref:manage:monitor/set-up-prometheus-for-monitoring.adoc[] for more information.

This role does not let the user log into the Couchbase Server Web Console.

[#table_external_stats_role,cols="1,2,2,hrows=2]
|===

3+^|  Role: External Stats Reader (`external_stats_reader`)

h| Resource
h| Permissions
h| Restrictions

| *Metrics API*
| Able to call /metrics` and `/prometheus_sd_config` REST API endpoints
| None

|===



[#application_telemetry_writer]
=== Application Telemetry Writer

This role lets the user report application telemetry through SDK calls.
Assign this role to application users that need to report telemetry information to Couchbase Server.

This role does not let the user log into Couchbase Server Web Console.

[#table_application_telemetry_writer,cols="1,2,2,hrows=2]
|===
3+^|  Role: Application Telemetry Writer (`application_telemetry_writer`)

h| Resource
h| Permissions
h| Restrictions


| *Application Telemetry*
| Able to write to telemetry metric websockets
| None

|===

[#bucket-roles]
== Bucket Roles

The following roles give users privileges to manage or access buckets. 
See xref:learn:buckets-memory-and-storage/buckets.adoc[] for more information about buckets.

[#bucket-admin]
=== Bucket Admin

The Bucket Admin role lets the user manage one or more buckets. 
These management abilities include stopping and starting XDCR for a bucket.
When granting this role, you choose which buckets the user can manage.

This role lets the user log into Couchbase Server Web Console.

[#table_bucket_admin_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Bucket Admin (`bucket_admin`)


h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers, view server configuration
| Cannot view configuration, add, failover, remove, modify services, or rebalance servers.

| *Buckets*
| Can drop, compact and edit buckets they have been granted access to.
Can add, edit, and drop scopes and collections in the buckets. 
| Cannot read, insert, or mutate documents.

| *XDCR*
| Can start and stop replications for buckets they have been granted access to.
| Cannot add, remove, or edit XDCR connections.

| *Settings*
| View all cluster settings
| Cannot change cluster settings.


| *Logs*
| Can view logs.
| Cannot collect information 

| *Search*
| Can list Search indexes.
| Cannot create, drop, or edit Search indexes.

| *Eventing*
| All
| None

|===


[#manage-scopes]
=== Manage Scopes

The Manage Scopes role lets a user create and delete scopes and collections within one or more buckets.
When granting this role, you choose the buckets where the user can create scopes and collections.
The user does not have the ability to read, write, or alter data.
Use this role to allow applications to manage a bucket's scopes and collections.

This role does not let the user log into Couchbase Server Web Console.

[#table_scope_admin_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Manage Scopes (`scope_admin`)

h| Resource
h| Permissions
h| Restrictions

| *Buckets*
| Can add and drop scopes and collections in the buckets they have been granted access to.
| Cannot read, insert, or mutate documents.

|===


[#application-access]
=== Application Access

The Application Access role lets a user read and write data in one or more buckets.
This role does not grant the ability to query data via {sqlpp}&#8212;the user can only access data via keys.
When granting this role, you choose the buckets where the user can read and write data.
As its name implies, this role is intended for use by applications instead of interactive users.

[IMPORTANT]
====
This role is deprecated. 
Couchbase Server 5.0 added this role to replace an old method of password authentication to access buckets.
To transition away from bucket passwords, the upgrade process to Couchbase Server 5.0 created new users with the bucket's name and password and assigned this role.
Do not grant this role to users.
Instead, use one of the query or data roles.

====

Versions of Couchbase Server prior to 5.5 referred to this role as Bucket Full Access.

This role does not let the user log into Couchbase Server Web Console.

[#table_bucket_full_access_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Application Access (`bucket_full_access`)

h| Resource
h| Permissions
h| Restrictions

| *Buckets*
| Can read and write data in buckets they have been granted access to.
| Cannot alter bucket, scope, or collection settings.

|===

== Data Roles

These roles give users the ability to read and write data in buckets via key-value operations.
See xref:guides:kv-operations.adoc[] to learn about key-value operations.

[#data-reader]
=== Data Reader

The Data Reader role lets the user read data from one or more collections via key-value retrieval. 
It does not grant the ability to run {sqlpp} queries (see <<#query-roles>> for roles that do).
When granting this role, you choose the collections where the user can read data.
Grant this role to users for applications that need to read data via key-value operations.

This role does not let the user log into Couchbase Server Web Console. 

[#table_data_reader_role,cols="1,2,2,hrows=2"]
|===
3+^| Role: Data Reader (`data_reader`)

h| Resource
h| Permissions
h| Restrictions

| *Buckets*
| Read data from collections, scopes, and buckets to which they have been granted access.
Can read some bucket metadata, XATTR mappings, and pools on buckets they have been granted access to.
| Cannot write data

| *Query*
| None
| All

|===



[#data-writer]
=== Data Writer

The Data Writer role lets the user write data to one or more collections via key-value operations. 
It does not grant the ability to run {sqlpp} queries (see <<#query-roles>> for roles that do).
When granting this role, you choose the collections where the user can write data.
Grant this role to users for applications that need to write data via key-value operations.

This role does not let the user log into Couchbase Server Web Console. 

[#table_data_writer_role,cols="1,2,2,hrows=2"]
|===
3+^| Role: Data Writer (`data_writer`)

h| Resource
h| Permissions
h| Restrictions

| *Buckets*
| Write data to collections, scopes, and buckets to which they have been granted access.
| Cannot read data

| *Query*
| None
| All

|===


[#data-dcp-reader]
=== Data DCP Reader

The Data DCP Reader role lets the user start a xref:learn:clusters-and-availability/intra-cluster-replication.adoc#database-change-protocol[Database Change Protocol (DCP)] stream for one or more collections, scopes, or buckets. 
When granting this role, you choose the collections, scopes, and buckets where the user can start DCP streams.
Grant this role to users for applications that need to start DCP streams.

This role does not let the user log into Couchbase Server Web Console. 

[#table_data_dcp_reader_role,cols="1,2,2,hrows=2"]
|===
3+^| Role: Data DCP Reader (`data_dcp_reader`)

h| Resource
h| Permissions
h| Restrictions

| *Buckets*
| Can start DCP streams for collections, scopes, and buckets they have been granted access to.
Can also read data and XATTRs from these collections, scopes, and buckets.
| Cannot write data

| *Query*
| None
| All

|===


[#data-monitor]
=== Data Monitor

The Data Monitor role lets the user read statistics for a bucket, scope, or collection.
When granting the role, you decide which statistics the user can read.
Use this role for applications that need to read statistics.

NOTE: In versions of Couchbase Server prior to 5.5, this role was called Data Monitoring.

This role does not let the user log into Couchbase Server Web Console. 

[#table_data_monitoring_role,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Data Monitor (`data_monitoring`)

h| Resource
h| Permissions
h| Restrictions

| *Buckets*
| Can read statistics for buckets, scopes, and collections they have been granted access to. 
| None

|===


== Views Roles

The following roles grant users privileges with Views.
Also see the related administrator role <<#views-admin>>.

IMPORTANT: Views were deprecated in Couchbase Server 7.0. 
See xref:learn:views/views-intro.adoc[] for more information.



[#views-reader]
=== Views Reader

The Views Reader role lets a user read data from views in one or more buckets.
When granting this role, you choose which buckets contain views the user can read.
Grant this role to users you create for applications that need to read data from views.

This role does not let the user log into Couchbase Server Web Console. 
 
[#table_views_reader_role,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Views Reader (`views_reader`)

h| Resource
h| Permissions
h| Restrictions

| *Buckets*
| Can read data from views in the buckets they have access to. 
Can read data via key-value from these buckets. 
| Cannot write data to buckets, alter bucket settings, or alter views.

| *Views*
| Can read data from views in buckets they have been granted access to.
| Cannot change views


|===


[#query-roles]
== Query & Index Roles

These roles grant users the ability to perform queries and work with indexes.

[#query-curl-access]
=== Query CURL Access

The Query CURL Access role lets the user call the {sqlpp} curl function in their queries.

CAUTION: The Query CURL Access role allows users to run GET and POST requests to any system on the network Couchbase Server uses for client connections.
If your cluster is not configured to use a private network for internal communication, they also have access to the entire cluster.  
They can interact with any system on this network.

This role only grants the user the ability to read data returned by the {sqlpp} curl function.
Usually, you assign additional roles to the user to allow them to read and write data.

For more information about the {sqlpp} curl function, see xref:n1ql:n1ql-language-reference/curl.adoc[].

This role lets the user log into Couchbase Server Web Console. 

[#table_query_external_access_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Query Curl Access (`query_external_access`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration or add, failover, remove, modify services, or rebalance servers

| *Buckets*
| List buckets
| Cannot list scopes or collections.
Cannot create, drop, or edit buckets.
Cannot read data other than the results of the {sqlpp} curl function call.
Cannot write data.

| *Query*
| Can execute {sqlpp} curl function calls
| Cannot execute any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.

|===


[#query-system-catalog]
=== Query System Catalog

The Query System Catalog role lets the user query the system catalog using {sqlpp}.
This access include querying `system:indexes`, `system:prepareds`, and tables listing current and past queries.
Assign this role to developers who need to query these tables when troubleshooting and debugging queries.

The role grants Couchbase Server Web Console access.

[#table_query_system_catalog_role,cols="1,2,2,hrows=2]
|===

3+^|  Role: Query System Catalog (`query_system_catalog`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers.
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Buckets*
| List buckets and view bucket settings
| Cannot list scopes or collections, create, drop, edit settings, read or write data

| *Query*
| Can query system tables
| Cannot perform any other query actions.
Cannot use the Query Workbench in Couchbase Server Web Console.

|===

[#manage-global-functions]
=== Manage Global Functions

The Manage Global Functions role lets the user create and drop global user-defined {sqlpp} functions. 
See xref:n1ql:n1ql-language-reference/createfunction.adoc[].

This role grants Couchbase Server Web Console access.

[#table_manage_global_functions_role,cols="1,2,2,hrows=2]
|===

3+^|  Role: Manage Global Functions (`query_manage_global_functions`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Buckets*
| List buckets
| Cannot list scopes or collections, create, drop, edit settings, read or write data

| *Query*
| Can execute `CREATE FUNCTION` and `DROP FUNCTION` statements
| Cannot perform any other queries, including calling global functions.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===


[#execute-global-functions]
=== Execute Global Functions

The Execute Global Functions role lets the user call global {sqlpp} user-defined functions.

This role lets the user log into Couchbase Server Web Console. 

[#table_query_execute_global_functions_role,cols="1,2,2,hrows=2]
|===

3+^|   Role: Execute Global Functions (`query_execute_global_functions`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Buckets*
| List buckets
| Cannot list scopes or collections, create, drop, edit settings, read or write data

| *Query*
| Can execute global user-defined functions
| Cannot perform any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===


[#manage-scope-functions]
=== Manage Scope Functions (Query and Index)

The Manage Scope Functions role lets the user create and drop user-defined {sqlpp} functions for one or more scopes.
When granting this role, You select the scopes where  the user can manage user-defined functions.
See xref:n1ql:n1ql-language-reference/createfunction.adoc[].

This role lets the user log into Couchbase Server Web Console. 


[#table_manage_scope_functions_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Manage Scope Functions (`query_manage_functions`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Buckets*
| List buckets
| Cannot list scopes or collections, create, drop, edit settings, read or write data

| *Query*
| Can execute `CREATE FUNCTION` and `DROP FUNCTION` statements to create user-defined functions in specific scopes
| Cannot perform any other queries, including calling the functions.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===

[#query-select]
=== Query Select

The Query Select role lets the user execute `SELECT` statements on the data in one or more collections.
See xref:guides:query.adoc[].
When granting this role, you choose the collections where the user execute `SELECT` statements.


This role lets the user log into Couchbase Server Web Console. 


[#table_query_select_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Query Select (`query_select`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Buckets*
| Can list buckets.
Can read data from specific collections.
| Cannot list scopes or collections, create, drop, edit settings, read or write data

| *Query*
| Can execute `SELECT` statements on data in one or more collections.
Can read data from one or more collections.
| Cannot perform any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change any settings

|===


[#query-update]
=== Query Update

The Query Update role lets the user execute `UPDATE` statements to mutate existing documents in specific collections.  
See xref:n1ql:n1ql-language-reference/update.adoc[] for more information.
When granting this role, you select which collections contain documents the user can mutate.

This role lets the user log into Couchbase Server Web Console. 


[#table_query_update_role,cols="1,2,2,hrows=2]
|===
3+^| Role: Query Update (`query_update`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot  add, failover, remove, modify services, or rebalance servers.

| *Buckets*
| List buckets and view bucket settings
| Cannot list scopes or collections, create, drop, edit settings

| *Query*
| Can execute `UPDATE` statements on documents in one or more collections
| Cannot perform any other queries.
Cannot create new documents.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===

[#query-insert]
=== Query Insert

The Query Insert role lets the user execute the {sqlpp} `INSERT` statement to add new documents to one or more collections.
See xref:n1ql:n1ql-language-reference/insert.adoc[] for more information.
When granting this role, you select the collections where the user can add documents.

This role lets the user log into Couchbase Server Web Console.


[#table_query_insert_role,cols="1,2,2,hrows=2]
|===

3+^|  Role: Query Insert (`query_insert`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Buckets*
| List buckets and view bucket settings
| Cannot list scopes or collections, create, drop, edit settings

| *Query*
| Can execute `INSERT` statements to create documents in one or more collections
| Cannot perform any other queries.
Cannot mutate existing documents.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===

[#query-delete]
=== Query Delete

The Query Delete role lets the user execute the {sqlpp} `DELETE` satatement to delete documents from one or more scopes.
See xref:n1ql:n1ql-language-reference/delete.adoc[] for more information.
When granting this role, you  select the collections where the user can delete documents.

This role lets the user log into Couchbase Server Web Console. 


[#table_query_delete_role,cols="1,2,2,hrows=2]
|===
3+^|  Role: Query Delete (`query_delete`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Buckets*
| List buckets and view bucket settings
| Cannot list scopes or collections.
Cannot edit bucket settings.

| *Query*
| Can execute `DELETE` statements to delete documents from one or more collections
| Cannot perform any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===


[#query-sequential-scan]
=== Query Use Sequential Scan

The Query Use Sequential Scan role allows users' queries to perform a sequential scan of a keyspace.
The query planner only uses a sequential scan when no suitable index exists for the keyspace. 
Only queries by users with this role can use a sequential scan to query data because scanning a large unindexed keyspace can be expensive.  
See xref:indexes:query-without-index.adoc#sequential-scans[Sequential Scans] for more information.

NOTE: Administrator roles automatically have permission to perform sequential scans when necessary.

This role does not let the user log into Couchbase Server Web Console.

[#table_query_use_sequential_scans_role,cols="1,2,2,hrows=2]
|===
3+^|  Role: Query Use Sequential Scan (`query_use_sequential_scans`)

h| Resource
h| Permissions
h| Restrictions

| *Query*
| Can execute a query in a collection that lacks a primary and secondary index
| Cannot perform any other queries

|===


[#query-manage-index]
=== Query Manage Index

The Query Manage Index role allows the user to manage indexes for one or more collections.
When granting this role, you select the collections where the user can manage indexes.

This role lets the user log into Couchbase Server Web Console.

[#table_query_manage_index_role,cols="1,2,2,hrows=2]
|===
3+^| Role: Query Manage Index (`query_manage_index`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Buckets*
| List buckets and view bucket settings
| Cannot list scopes or collections, create, drop, edit settings.
Cannot read or write data.

| *Index*
| Can create, drop, and view indexes for the collections whose indexes they have been given permission to manage
| Cannot use the Query Workbench in Couchbase Server Web Console

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===

[#query-list-index]
=== Query List Index

This role lets the user list indexes defined for one or more buckets, scopes, or collections.
When granting this role, you select the buckets, scopes, or collections where the user can list indexes.

This role lets the user log into Couchbase Server Web Console.

[#table_query_list_index_role,cols="1,2,2,hrows=2]
|===
3+^| Role: Query List Index (`query_list_index`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers and view statistics
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Buckets*
| List and view statistics for buckets, scopes, and collections
| Cannot create, drop, or edit bucket, scope, or collection settings.
Cannot read or write data.

| *Index*
| Can get list of indexes via the stats endpoint  (see xref:index-rest-stats:index.adoc[])
| Cannot add, drop, or edit indexes.
Cannot use the Index Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===

[#execute-scope-functions]
=== Execute Scope Functions

The Execute Scope Functions role lets the user execute {sqlpp} user-defined functions defined within a scope.
When you grant this role, you select the scopes where the user can call user-defined functions.

This role lets the user log into Couchbase Server Web Console.


[#table_query_execute_functions_role,cols="1,2,2,hrows=2]
|===

3+^|   Role: Execute Scope Functions (`query_execute_functions`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.


| *Query*
| Can execute scope user-defined functions in specific scopes
| Cannot perform any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===


[#manage-global-external-functions]
=== Manage Global External Functions

The Manage Global External Functions role lets the user manage global external language functions.
See xref:n1ql:n1ql-language-reference/createfunction.adoc#external-libraries[External Libraries] for more information about external functions.

This role lets the user log into Couchbase Server Web Console.

[#table_manage_global_external_functions_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Manage Global External Functions (`query_manage_global_external_functions`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.


| *Query*
| Can execute `CREATE FUNCTION` statements to create global external functions
| Cannot perform any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===


[#execute-global-external-functions]
=== Execute Global External Functions

The Execute Global External Functions role lets a user execute globally defined external functions.
See xref:n1ql:n1ql-language-reference/createfunction.adoc#external-libraries[External Libraries] for more information about external functions.

This role lets the user log into Couchbase Server Web Console.


[#table_execute_global_external_functions_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Execute Global External Functions (`query_execute_global_external_functions`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.


| *Query*
| Can execute globally defined external functions
| Cannot perform any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===


[#manage-scope-external-functions]
=== Manage Scope External Functions

The Manage Scope External Functions role lets the user create and drop external language functions defined at the scope level.
When you grant this role, you choose the scopes where the user can manage external functions.
See xref:n1ql:n1ql-language-reference/createfunction.adoc#external-libraries[External Libraries] for more information about external functions.

This role lets the user log into Couchbase Server Web Console.


[#table_manage_external_functions_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Manage Scope External Functions (`query_manage_external_functions`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Query*
| Can call globally defined external functions
| Cannot perform any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===


[#execute-scope-external-functions]
=== Execute Scope External Functions

The Execute Scope External Functions role lets the user call external functions defined in a scope. 
When you grant this role, you choose the scopes where the user can call external functions.
See xref:n1ql:n1ql-language-reference/createfunction.adoc#external-libraries[External Libraries] for more information about external functions.

This role lets the user log into Couchbase Server Web Console.

[#table_execute_external_functions_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Execute Scope External Functions (`query_execute_external_functions`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Query*
| Can call globally defined external functions
| Cannot perform any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===

[#query_manage_sequences]
=== Query Manage Sequences

This role lets the user manage sequences for one or more scopes. 
See xref:n1ql:n1ql-language-reference/sequenceops.adoc[] for more information about sequences.
When you grant this role, you  choose the scopes where the user can manage sequences.

This role lets the user log into Couchbase Server Web Console.

[#table_query_manage_sequences_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Query Manage Sequences (`query_manage_sequences`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Query*
| Can create and alter sequences in buckets to which they have been granted access
| Cannot perform any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.
Cannot manage sequences in buckets to which they have not been granted access.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===


[#query_use_sequences]
=== Query Use Sequences

This role lets the user incorporate sequences into their queries in one or more scopes.
When you grant this role, you choose the scopes where the user can use sequences.
See xref:n1ql:n1ql-language-reference/sequenceops.adoc[] for more information about sequences.

This role lets the user log into Couchbase Server Web Console.

[#table_query_use_sequences_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Query Manage Sequences (`query_use_sequences`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers

| *Query*
| Can use sequences in scopes they have been granted access to.
| Cannot perform any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.
Cannot manage sequences.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===


[#query_manage_system_catalog]
=== Query Manage System Catalog

This role lets a user manage all system catalogs for query automatic workload reports using {sqlpp} statements.

// TODO: Add link to the query workload docs when completed

This role lets the user log into Couchbase Server Web Console.

[#table_query_manage_system_catalog_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Query Manage System Catalog (`query_manage_system_catalog`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Query*
| Can manage query workload system catalogs
| Cannot perform any other queries.
Cannot use the Query Workbench in Couchbase Server Web Console.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings.

|===



== Search Roles

The following roles give users privileges to the xref:learn:services-and-indexes/services/search-service.adoc[] features.

[#search-admin]
=== Search Admin

The Search Admin role lets the user manage the Search Service in one or more buckets.
When you grant this role, you choose the buckets where the user can manage search.

NOTE: In versions of Couchbase Server earlier than 5.5, this role was named FTS Admin.

This role lets the user log into Couchbase Server Web Console.


[#table_search_admin_role,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Search Admin (`fts_admin`)

h| Resource
h| Permissions
h| Restrictions

| *Servers*
| Can list servers.
| Cannot view or edit server configuration or statstics.
Cannot rebalance, failover, add, or remove servers.

| *Buckets*
| Can list buckets, scopes, and collections. 
Can view documents. 
| Cannot edit documents or change bucket settings

| *Settings* 
| Can view cluster settings
| Cannot view other settings nor change any settings

| *Query*
| None
| All

| *Search*
| Can add, edit, and drop Search indexes on the buckets they have access to.
| Cannot manage Search indexes of buckets they do not have access to.

|===



[#search-reader]
=== Search Reader

The Search Reader role lets the user execute searches using Full-Text Search indexes in one or more buckets.
When you grant this role, you choose the buckets in which the user can execute searches.

NOTE: In versions of Couchbase Server prior to 5.5, this role was referred to as FTS Searcher.

This role lets the user log into Couchbase Server Web Console.

[#table_fts_searcher_role,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Search Reader (`fts_searcher`)

h| Resource
h| Permissions
h| Restrictions

| *Servers*
| Can list servers.
| Cannot view or edit server configuration or statstics.
Cannot rebalance, failover, add, or remove servers.

| *Buckets*
| Can list buckets
| Cannot read documents


| *Settings* 
| Can view cluster settings
| Cannot view other settings nor change any settings

| *Query*
| None
| All

| *Search*
| Can use search indexes in the buckets they have access to
| Cannot add, drop, or change set4tings for search indexes

|===




== Analytics Roles

The following roles give uses privileges for the Analytics Service.
See xref:learn:services-and-indexes/services/analytics-service.adoc[] for more information.

[#analytics-reader]
=== Analytics Reader

The Analytics Reader role lets the user query all analytic datasets.
For more information, see xref:analytics:introduction.adoc[].

This role lets the user log into Couchbase Server Web Console.

[#table_analytics_reader_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Analytics Reader (`analytics_reader`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings.


| *Analytics*
| Can read any analytic data.
Can use the Couchbase Server Web Console's Analytics query editor.
| Cannot change analytic configuration.

|===


[#analytics-admin]
=== Analytics Admin

The Analytics Admin role lets users manage Analytics Service links, scopes, and datasets for all buckets. 
For more information, see xref:analytics:introduction.adoc[].
 

This role lets the user log into Couchbase Server Web Console.

[#table_analytics_admin_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Analytics Admin (`analytics_admin`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| List servers
| Cannot view configuration.
Cannot add, failover, remove, modify services, or rebalance servers.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings


| *Analytics*
| Can add or drop Analytics Service links, scopes, and dataset

| None

|===

[#analytics-select]
=== Analytics Select

The Analytics Select role lets the user query analytic datasets for one or more buckets, scopes, or collections.
When you grant this role, you choose the buckets, scopes, and collections where the user can execute queries.

This role lets the user log into Couchbase Server Web Console.

[#table_analytics_select_role,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Analytics Select (`analytics_select`)

h| Resource
h| Permissions
h| Restrictions

| *Servers*
| Can list servers.
| Cannot view or edit server configuration or statstics.
Cannot rebalance, failover, add, or remove servers.

| *Settings* 
| Can view cluster settings
| Cannot view other settings nor change any settings

| *Analytics*
| Can query analytics data in the buckets they have access to
| Cannot add or drop Analytic scopes, links, nor collections or change their settings

|===

[#analytics-manager]
=== Analytics Manager

The Analytics Manager role lets the user manage and query the analytic datasets for one or more buckets.
They can also manage xref:analytics:manage-datasets.adoc#creating-a-collection-on-a-local-link[Analytics Service local links].
When you grant this role, you choose the buckets where the user can manage and query analytics.

This role lets the user log into Couchbase Server Web Console.


[#table_analytics_manager_role,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Analytics Manager (`analytics_manager`)

h| Resource
h| Permissions
h| Restrictions

| *Servers*
| Can list servers.
| Cannot view or edit server configuration or statstics.
Cannot rebalance, failover, add, or remove servers.

| *Settings* 
| Can view cluster settings
| Cannot view other settings nor change any settings

| *Analytics*
| Can query analytics data in the buckets they have access to.
Can manage analytics in these buckets, including local links and adding/dropping analytics collections. 
| Cannot manage analytics in buckets they have not been granted access to

|===


== Eventing Roles

These roles control a user's access to the Eventing Service.
Also, see <<#eventing-full-admin>> for the Eventing-related administrator role.
For more information about Eventing, see xref:eventing:eventing-overview.adoc[].

[#eventing-manage-functions]
=== Eventing Manage Scope Functions

The Eventing Manage Scope Functions role lets the user manage the eventing functions in one or more scopes. 
When you grant this role, you choose the scopes where the user can manage eventing functions.

NOTE: In addition to this role, the user must have the <<#data-dcp-reader>> on the collections they want their functions to listen to. 
They must also have read and write permissions on one or more collections to store the function's event data.

This role lets the user log into Couchbase Server Web Console.

[#table_eventing_manage_functions,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Eventing Manage Scope Functions (`eventing_manage_functions`)

h| Resource
h| Permissions
h| Restrictions

| *Server*
| Can list servers
| Cannot view server settings or statistics.
Cannot edit server settings, failover, or rebalance servers.

| *Settings*
| Can view cluster settings
| Cannot view other settings or change any settings

| *Eventing*
| Can add Eventing functions to a scope they have been granted access to.
Can change eventing settings for the scopes.
| None


|===

== XDCR Roles

The following roles give users the ability to manage XDCR settings and features.

[#xdcr-admin]
=== XDCR Admin

The XDCR Admin role grants the user the ability to manage XDCR connections.

This role lets the user log into Couchbase Server Web Console.

[#table_xdcr_admin_role,cols="1,2,2,hrows=2]
|===
3+^| Role: XDCR Admin (`replication_admin`)

h| Resource
h| Permissions
h| Restrictions

| *Servers* 
| View configuration and statistics
| Cannot add, failover, remove, modify services, or rebalance servers

| *Buckets*
| List buckets, scopes, and collections
| Cannot create, drop, edit settings, read or write data

| *Backup*
| None
| All 

| *XDCR* 
| All
| None

| *Security* 
| None
| All

| *Settings*
| View
| Change

| *Logs*
| View
| Collect Information

| *Query*
| None
| All

| *Search*
| None
| All

| *Analytics*
| None
| All

| *Eventing*
| None
| All

| *Views*
| None
| All

|===


[#xdcr-inbound]
=== XDCR Inbound

The XDCR Inbound role lets the user create inbound XDCR streams for one or more buckets.
When granting this role, you choose the buckets where the user can create inbound XDCR connections.
Assign this role to the user that you'll specify when creating an XDCR reference. 
See xref:manage:manage-xdcr/create-xdcr-reference.adoc[Create a Reference] for more information. 

NOTE: Versions of Couchbase Server prior to 5.5 called this role Replication Target.

This role does not let the user log into Couchbase Server Web Console.

[#table_replication_target_role,cols="1,2,2,hrows=2]
|===

3+^| Role: XDCR Inbound (`replication_target`)

h| Resource
h| Permissions
h| Restrictions

| *XDCR*
| Can create inbound connections on buckets they have been granted permissions on.
| Cannot create outbound connections or alter other XDCR settings.

|===


== Backup Roles

The following role gives users the ability to backup and restore data.
Also see the Administrative role <<#backup-full-admin>>.

[#data-backup-and-restore]
=== Data Backup & Restore

The Data Backup & Restore lets users back up and restore data in one or more buckets.  
When you grant this role, you choose the buckets the user can back up.
This role is not intended for interactive users.
Grant this role to users for applications that need to back up and restore data. 

NOTE: This role does not let the user access some important cluster-level data, so it cannot fully backup the cluster. 
See xref:backup-restore:cbbackupmgr-backup.adoc#bucket-level[Bucket Level] in the xref:backup-restore:cbbackupmgr-backup.adoc[] documentation for details.


This role does not let the user log into Couchbase Server Web Console. 

[#table_data_backup_role,cols="1,2,2,hrows=2"]
|===
3+^|  Role: Data Backup & Restore (`data_backup`)

h| Resource
h| Permissions
h| Restrictions

| *Buckets*
| Can read, write, and manage buckets they have been granted access to. 
| None

|*Backup*
| Can backup bucket data, bucket {sqlpp} metadata, and analytics
| Cannot backup other data   

| *Security* 
| Can view settings for SAML, certificates, encryption at rest, audits, and other settings
| Cannot change settings

| *Indexes*
| Can build, create, and list
| Cannot backup, read, or manage

| *Bucket Analytics*
| Can manage and select buvket analytics
| Cannot read bucket analytics

| *Analytics*
| Can select and back up analytics 
| Cannot read analytics synonyms

|===

== Mobile Roles

The mobile roles support connections with the Sync Gateway and related features.
See the xref:sync-gateway::introduction.adoc[Sync Gateway Introduction] for more information.


[#sync-gateway]
=== Sync Gateway

The Sync Gateway role gives the user full access to the data Sync Gateway's data stored in Couchbase Server.
This role also lets the user manage indexes and read some cluster information.
Only assign this role to the user that you create for the Sync Gateway to use when connecting to Couchbase Server.
Choose one or more buckets that contain mobile data that you want this user to manage. 
See xref:sync-gateway::get-started-prepare.adoc#configure-server[Configure Server for Sync Gateway] for more information.

This role does not let the user log into Couchbase Server Web Console. 

[#table_sync_gateway_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Sync Gateway (`mobile_sync_gateway`)

h| Resource
h| Permissions
h| Restrictions

| *Sync Gateway Data*
| Can perform all actions on data (including flushing) and views on the Sync Gateway data stored in the Couchbase Server buckets you grant them access to.
Can view settings of these buckets.
| Cannot change bucket settings

| *Query*
| Can execute queries on data in buckets containing Sync Gateway data
| None

| *Indexes*
| Add and drop indexes and view index statistics in the buckets containing Sync Gateway data
| None.

| *Settings*
| View cluster settings
| Cannot view any other settings or change settings

|===


[#sync-gateway-configurator]
=== Sync Gateway Architect

The Sync Gateway Architect role lets the user manage Sync Gateway databases, users, and roles.
You choose one or more collections, scopes, or buckets where the user can manage Sync Gateway data.
This role also grants access to the Sync Gateway's metrics via the `/metrics` REST API endpoint.
For information about Sync Gateway users and roles, see xref:sync-gateway::access-control-concepts.adoc[Access Control Concepts].

This role does not let the user log into Couchbase Server Web Console. 


[#table_sync_gateway_configurator_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Sync Gateway Architect (`sync_gateway_configurator`)

h| Resource
h| Permissions
h| Restrictions


| *Sync Gateway Data*
| None
| Cannot read or write Sync Gateway application data

| *Sync Gateway Users & Roles*
| Can add, remove, and edit Sync Gateway users and roles
| None

| *Sync Gateway Metrics*
| Can read metrics
| Cannot change metric settings

|===


[#sync-gateway-app]
=== Sync Gateway Application

The Sync Gateway Application role lets the user manage Sync Gateway users, roles, and data.
It also allows the user to read and write application data through the Sync Gateway.
You choose one or more collections, scopes, or buckets where this user can manage mobile users and roles.
For information about Sync Gateway users and roles, see xref:sync-gateway::access-control-concepts.adoc[Access Control Concepts].

This role does not let the user log into Couchbase Server Web Console. 


[#table_sync_gateway_app_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Sync Gateway Application (`sync_gateway_app`)

h| Resource
h| Permissions
h| Restrictions


| *Collection: Data*
| Can read and write application data
| None

| *Sync Gateway Users & Roles*
| Can add, remove, and edit Sync Gateway users and roles
| None

|===


[#sync-gateway-application-read-only]
=== Sync Gateway Application Read Only

The Sync Gateway Application Read Only role lets the user read Sync Gateway users and role settings.
It also lets them read Sync Gateway data.
For information about Sync Gateway users and roles, see xref:sync-gateway::access-control-concepts.adoc[Access Control Concepts].

This role does not let the user log into Couchbase Server Web Console. 

[#table_sync_gateway_app_ro_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Sync Gateway Application Read Only (`sync_gateway_app_ro`)

h| Resource
h| Permissions
h| Restrictions


| *Collection: Data*
| Can read application data
| Cannot write application data

| *Sync Gateway Users & Roles*
| Can read Sync Gateway users and roles
| Cannot add, drop, or edit users or roles

|===


[#sync-gateway-replicator]
=== Sync Gateway Replicator

The Sync Gateway Replicator role lets the user manage Sync Gateway replications.

This role does not let the user log into Couchbase Server Web Console. 


[#table_sync_gateway_replicator_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Sync Gateway Replicator (`sync_gateway_replicator`)

h| Resource
h| Permissions
h| Restrictions


| *Sync Gateway Replication Collection*
| Can read and write replication settings
| None

|===

[#sync-gateway-dev-ops]
=== Sync Gateway Dev Ops

The Sync Gateway Dev Ops role lets the user manage the Sync Gateway's node-level configuration.
It also grants access to Sync Gateway's `/metrics` endpoint for Prometheus integration.

This role does not let the user log into Couchbase Server Web Console. 



[#table_sync_gateway_dev_ops_role,cols="1,2,2,hrows=2]
|===

3+^| Role: Sync Gateway Dev Ops (`sync_gateway_dev_ops`)

h| Resource
h| Permissions
h| Restrictions


| *Sync Gateway Node Configuration*
| Can read and write node-level settings
| None

| *Sync Gateway Metrics*
| Can read metrics
| Cannot change metric settings

|===
