= Usernames and Passwords
:description: pass:q[Couchbase Server requires that administrators and applications _authenticate_, in order to gain access to data, settings, and statistics.]
:page-aliases: security:security-pw-auth,security:security-passwords

[abstract]
{description}
Authentication typically requires that a _username_ and _password_ be provided.

[#introduction-to-usernames-and-passwords]
== Introduction to Usernames and Passwords

_Users_ of Couchbase Server typically require a username and password.
A user may be either an _administrator_ or an _application_.
An application may be a program or server, or may be a simple, single command-line query.
(Note that an application may be permitted to use a _client certificate_ for purposes of authentication, instead of a username-password combination: see xref:learn:security/certificates.adoc[Certificates], for information.)

The _Full Administrator_ who installs and configures Couchbase Server (and so has full read-write access to the whole system), defines their own username and password during the configuration-process: see
xref:manage:manage-nodes/create-cluster.adoc[Create a Cluster], for details.
Subsequently, this administrator can add additional administrators to the system; assigning a username and password to each.
Whenever any needs to log into Couchbase Web Console in order to inspect data, statistics, and settings (and possibly make changes), they must specify their own unique username-password combination, at the authentication-prompt provided by the server.

An application, if it is not using a client certificate for purposes of authentication, must pass its username and password as parameters.
Therefore, Couchbase CLI commands, N1QL queries, and executables supported by the Couchbase SDK all provide syntax to allow the passing of a username and password.

Additionally, a special _master password_ may be designed and used by the
Full Administrator, in order to manage system secrets.
See
xref:manage:manage-security/manage-system-secrets.adoc[Manage System Secrets], for details.

Note that a cluster running Couchbase Server _Enterprise Edition_ can have any number of users.
A cluster running _Community Edition_ can have a maximum of twenty users.

The _Full Administrator_ username and password are established during initialization of Couchbase Server: see xref:manage:manage-nodes/create-cluster.adoc[Create a Cluster] for details.

Subsequently, additional users can be added to the cluster as _local_ users: each is at that time assigned a unique _username_, and a unique _password_.
Passwords can be changed by means of the password-reset tool, xref:cli:cbcli/couchbase-cli-reset-admin-password.adoc[reset-admin-password]; or by Couchbase Web Console, as described in xref:manage:manage-security/manage-users-and-roles.adoc#editing-users-and-groups[Editing Users and Groups].
A local user can change their own password by means of the REST API: see xref:rest-api:rest-set-password.adoc[Change Password].

Users can also be added to the cluster as _external_ users, for whom no password need be specified; since the external user is to be authenticated externally.

[#console-access]
=== Usernames and Passwords for Administrators

When an administrator logs into Couchbase Web Console, if the console is running on the default port, `+http://localhost:8091+`, the specified username and password are passed in the clear, from the browser to the console.

Optionally, Couchbase Web Console can be configured for _secure access_, at `+https://localhost:18091+`; so that the username and password are passed in encrypted form.
For information, see xref:manage:manage-security/manage-console-access.adoc[Manage Console Access].

[#authentication-for-applications]
=== Usernames and Passwords for Applications

Applications should access Couchbase-Server Services over connections that are encrypted by TLS.

==== Access Over an Encrypted Connection

Once an encrypted connection has been established by TLS, usernames and passwords can be passed over that connection.
Couchbase Server checks each received username against the list of locally managed users.
If the username is found, Couchbase Server converts the associated, received password into a _cryptographic hash_, using the _Argon2ID_ algorithm.
Couchbase Server then compares this hash to hashes it has already stored: if a match is achieved, the application is permitted to connect to the service.

==== Access Over an Unencrypted Connection

The procedure for handling access over an unencrypted connection depends on which service is being accessed, as follows:

* When any service _other than the Data Service_ is accessed, Couchbase Server checks the received username against the list of locally managed users.
If the username is found, Couchbase Server converts the associated, received password into a cryptographic hash, using the _Argon2ID_ algorithm.
Couchbase Server then compares this hash to hashes it has already stored: if a match is achieved, the application is permitted to connect to the service.

* When the Data Service is accessed, one of four mechanisms provided by the _Simple Authentication and Security Layer_ (SASL) framework is used.
These mechanisms are PLAIN, and three members of the _Salted Challenge Response Authentication Mechanism_ family of hash functions; which are SCRAM-SHA1, SCRAM-SHA256, and SCRAM-SHA512.
The SCRAM mechanisms allow applications to authenticate securely, by transmitting the password only in _protected form_.
Drivers may need to be updated, to support SHA-based hash functions.

[#password-authentication-mechanisms]
In ascending order of strength, the Couchbase password-authentication mechanisms used for the Data Service are as follows:

* _PLAIN_: The client sends the password in unencrypted form.
All clients support this authentication-method.
It is relatively insecure, providing no defence against passwords being stolen in transmission.
If the password is received in this way, Couchbase Server checks the username against the list of locally managed users.
If the username is found, Couchbase Server converts the received password into a cryptographic hash, using the _Argon2ID_ algorithm.
Couchbase Server then compares this hash to hashes it has already stored: if a match is achieved, the application is permitted to connect to the Data Service.

* _SCRAM-SHA1_: Uses a 160-bit key for the SCRAM challenge-response process.

* _SCRAM-SHA256_: One of a group of hash functions referred to as _SHA2_, SCRAM-SHA256 uses a 256-bit key for the SCRAM challenge-response process.

* _SCRAM-SHA512_: Another hash function from the _SHA2_ group, SCRAM-SHA512 uses a 512-bit key for the SCRAM challenge-response process.
This is the strongest supported SCRAM authentication protocol.

During initial client-server negotiation with the Data Service, the strongest authentication protocol supported by both Couchbase Server and the application's client OS is selected for use.
For example, if the client supports only the PLAIN protocol, the PLAIN protocol is used; but if the client also supports the SCRAM-SHA1 protocol, then SCRAM-SHA1 is used.

Each option other than PLAIN can be disabled, by means of the REST API: in Couchbase Server Version 7.6 and later, this is _recommended_; since even if TLS is not available, the _Argon2ID_ encryption now provided with PLAIN access provides higher security than any of the SCRAM/SHA options.
For instructions on how to disable, see xref:rest-api:rest-setting-security.adoc[Configure On-The-Wire Security].

[#introduction-to-certificate-based-authentication]
== Certificate-Based Authentication

Couchbase Server supports the use of x.509 certificates, to authenticate clients.
This ensures that only approved users, machines, or endpoints are authenticated.
Note also that x.509 certificates are required for the use of TLS.

Certificate-based authentication relies on a _Certificate Authority_ (CA) to validate identities and issue certificates.
The certificate includes information such as the name of the entity it identifies, an expiration date, the name of the CA that issued the certificate, and the digital signature of the issuing CA.

For a complete overview of Couchbase Server's certificate-handling mechanisms, see xref:learn:security/certificates.adoc[Certificates].
For practical steps required to set up client and server certificates, see xref:manage:manage-security/manage-certificates.adoc[Manage Certificates]

[#password-strengthd]
== Password Strength

Couchbase Server provides a default password-policy.
This demands only that the password have a minimum of six characters.

For pre-production purposes, it may be desirable to strengthen this default password-policy.
For production purposes, it should be considered essential to do so.
The password-policy can be set by the Full Administrator, by means either of the Couchbase CLI command xref:cli:cbcli/couchbase-cli-setting-password-policy.adoc[setting-password-policy], or of the REST API &#8212; as described in xref:rest-api:rest-set-password-policy.adoc[Setting Password Policy].
This allows you to specify that every Couchbase Server-password should:

* Contain a minimum-number of characters.
If established with the CLI, this can be any number between 1 and 100.
If established with the REST API, this can be any number between 0 and 100.
(Note that if 0 is selected, the definition of password-free users is thereby enabled: this is highly insecure, and is _not_ recommended.)
* Contain at least one uppercase character.
* Contain at least one lowercase character.
* Contain at least one special character.
* Contain at least one digit.

It is recommended that passwords be managed with a password manager, and that each password be designed as one of the following:

* A password of at least 12 characters that includes letters, numbers, and special characters.

* A unique passphrase of at least 15 characters, with individual words separated from one another by means of one or more special characters.

[#usernames-and-roles]
== Usernames and Roles

Couchbase Server-users can typically authenticate by means of a _username_, specified with a password.
The restrictions on username-design are that each should be unique to the cluster; and that none of the following characters be used: `( ) < > , ; : \ " / [ ]  ? = { }`.
Note additionally that the `@` character cannot be used in a username on any Couchbase Server version before 6.5.1.
On versions 6.5.1 and beyond, a username may contain the `@` character, as long as it does not occur at the start: for example, `first.last@domain`.

Usernames _cannot_ be more than 128 UTF-8 characters in length; and it is recommended that they be no more than 64 UTF-8 characters in length, in order to ensure successful onscreen display.

Each user is associated with one or more _roles_, which permit limited access-privileges.
Therefore, once a user has authenticated, their role-assignment is examined, and an appropriate degree of access is granted to them by Couchbase Server.
See xref:learn:security/authorization-overview.adoc[Authorization], for details.

Note that usernames and role-names are _case sensitive_.
