= Using Multiple Root CA Certificates
:description: Couchbase Server supports use of multiple root CA certificates, for a single cluster.

[abstract]
{description}

== Benefits of Multiple Root CA Certificates

Prior to Couchbase Server Version 7.1, a Couchbase-Server cluster could maintain at most _one_ root CA: all nodes and all clients were obliged to rely on this CA's authority.
From version 7.1, Couchbase Server permits multiple root CAs to maintained in a _trust store_ for the cluster.
This allows:

* Individual nodes either to share a root CA with other nodes, or each to have their own root CA.
Potentially, improves security; by allowing a service and its applications to maintain a certificate-based authentication-mechanism that is entirely separate from that used by others.

* Clients to authenticate with reference to CA's that are not used by Couchbase Server to confer authority on nodes, but are nevertheless maintained in the cluster's trust store.
Potentially, this promotes flexibility; by allowing a cluster and any of its clients to trust authorities other than that used for the signing of its own certificate.

A single Root CA may be pointed to by the trust chains of multiple nodes.
All Root CAs in the trust store are accessible to all nodes, and multiple Root CAs may therefore be used in facilitating encrypted node-to-node communication.

== Multiple Root CA Certificates: An Illustration

A cluster-configuration that uses multiple Root CAs is illustrated as follows:
