[#when-data-is-encrypted]
== When Couchbase Server Encrypts Data
:description: When you enable encryption at rest for a bucket or a type of system data, Couchbase Server encrypts all of the data it writes. However, it does not encrypt existing data in the bucket or already written system data.
:page-toclevels: 2
:page-edition: Enterprise Edition

For example, if you enable encryption at rest for logs, Couchbase Server encrypts new log entries but does not encrypt existing log entries.
Existing unencrypted data in buckets is encrypted when it's mutated or compacted.
Now, this also applies to service-generated data (the "other" data type).

When you enable "other" encryption, services encrypt new service-generated files (such as Query spill files and Index backfill files) but do not retroactively encrypt files written before enablement.

You can use the REST API to force Couchbase Server to encrypt existing unencrypted data. 
See xref:rest-api:security/encryption-at-rest/force-encryption-at-rest.adoc[] for more information.

See xref:manage:manage-security/manage-encryption-at-rest.adoc#force-encryption[Force Encryption of Unencrypted Data] for more information.

=== Encryption States


An encryption data type can be in 1 of the following states:


[cols="1,2"]


|===


| State | Meaning


| Encrypted


| All data of this type on the node is encrypted with the active DEK.


| Partially encrypted


| Some data is encrypted and some is not.


This is the normal state after you enable encryption until all existing data has been mutated, compacted, or force-encrypted.


| Unencrypted


| No data of this type on the node is encrypted.


|===


You can check the encryption state using the `cm_encr_at_rest_data_status` metric or the REST API status endpoints.


See <<key-health-monitoring>> for more information.

[#disabling-encryption]


=== Disabling Encryption


When you disable encryption at rest for a data type, Couchbase Server does not immediately decrypt all encrypted data.


It stops encrypting the new data it writes, but it does not decrypt and rewrite the existing encrypted data.


It still decrypts encrypted data as it reads it.


It only rewrites the data in an unencrypted format when it updates the data.


This means your cluster can be in a mixed state where some data is encrypted and some is not.


The encryption status reports as "partially encrypted" until all encrypted data has been rewritten without encryption.


==== Forcing Decryption


To force all data to be stored unencrypted after disabling encryption, use the Drop DEKs operation.


Dropping DEKs after disabling encryption causes Couchbase Server to:


. Read all encrypted data from disk.


. Rewrite the data without encryption.


. Delete the DEKs that were used to encrypt it.


See xref:manage:manage-security/manage-encryption-at-rest.adoc#drop-deks[Drop DEKs and Re-encrypt Data] for the steps to force decryption.


WARNING: Dropping DEKs is an I/O-intensive operation.


It reads and rewrites all data for the affected data type.


Plan this operation during a maintenance window or a period of low activity.


==== DEK Retention After Disabling


When you disable encryption, Couchbase Server keeps the existing DEKs so it can decrypt data that is still encrypted.


It does not delete DEKs until all data they protect has been rewritten without encryption (or force-decrypted via Drop DEKs).


==== Re-enabling Encryption


You can re-enable encryption at any time after disabling it.


When you re-enable encryption, Couchbase Server generates new DEKs and begins encrypting new data.


Previously encrypted data that was not decrypted remains encrypted with the old DEKs.


Previously decrypted data is encrypted with new DEKs as it is mutated or compacted.




