= Setting Up Buckets

[abstract]
Buckets are logical groups of items, each item consisting of a key and a corresponding value.
Buckets facilitate the management of the items they contain.
By means of the Couchbase Web Console, the CLI, and the REST API, you can configure, create, populate, and delete buckets.

== Buckets and Data

Couchbase uses buckets for storing data.
Once defined, a bucket can have items assigned to it; and the bucket and the items can be inspected and edited by means of Couchbase Web Console.
Applications, as well as users, can access buckets and the data they contain: in both cases, access typically requires authentication; which should itself be established by an appropriately authorized administrator.

Three different types of bucket are provided: _Couchbase_, _Memcached_, and _Ephemeral_.
Buckets of all three types are supported simultaneously by Couchbase Server.
When you create a bucket, the type you choose depends on the data it is to contain, the source of that data, and the context in which the data will be accessed by users and applications.
For a complete architectural description of bucket-types, see xref:understanding-couchbase:buckets-memory-and-storage/buckets.adoc[Buckets].

Multiple options are provided for bucket-configuration.
These options are all accessible at the time of bucket-creation; and a subset remains accessible later, allowing configuration-editing to be performed by the appropriately authorized administrator.

For authorization purposes, Couchbase Server provides a system of _Role-Based Access Control_ (RBAC), which assigns different levels of bucket-access to defined users.
A full account of Couchbase RBAC is provided in xref:security:security-authorization.adoc[Authorization].

Note that Couchbase Server provides a number of _sample buckets_.
These are for testing only.
Sample buckets must be accessed according to the requirements of Couchbase _Role-Based Access Control_: therefore, they should be accessed by a defined user assigned the [.ui]*Full Bucket Access* role: the user's username and password must be specified during access.
See xref:settings:install-sample-buckets.adoc[Sample Buckets] for more information.
