[#mangage-server-groups]
= Manage Server Groups

[abstract]
You can create logical groupings of servers on a cluster where each server group physically belongs to a rack or availability zone.

This section describes how to manage server groups through the Couchbase Web Console.
Server and server groups can also be managed through the Couchbase command-line interface (CLI) and REST API.

NOTE: By default, when a Couchbase cluster is initialized, Group 1 is created.

== Adding a Server Group

To add a new group using the Web Console:

[#server-grp]
. From the [.uicontrol]*Couchbase Web Console > Servers >* click [.uicontrol]*Groups* located on the top right side.
. Click [.uicontrol]*Add Group* to add a new group.
. Enter the group name in the [.uicontrol]*Group Name* field and click [.uicontrol]*Create*.

Once the information is entered successfully, a new group is added in the [.uicontrol]*Server Groups* page.

== Editing a Server Group

To edit a server group name using the Web Console:

[#ol_ef4_tlf_zz]
. From the [.uicontrol]*Couchbase Web Console > Servers > Groups* page, select the group that you want to edit.
. Click [.uicontrol]*edit name* to change the group name.
. In the [.uicontrol]*Edit Group* window, click [.uicontrol]*Rename*.
+
The selected group name is updated.

== Deleting a Server Group

Server groups are deleted by removing all nodes from the server group and then deleting the server group.

To delete a server group using the Web Console:

[#ol_uqn_clf_zz]
. From the [.uicontrol]*Couchbase Web Console > Servers > Groups* page, select the group that you want to delete.
. Click [.uicontrol]*delete group* to delete the group.
. In the [.uicontrol]*Confirm Delete Group* window, click [.uicontrol]*Delete Group*.
+
The selected group is deleted.

== Moving Servers Between Server Groups

Servers can be moved between server groups from the [.uicontrol]*Server Groups* page.

To move a server from one group to another using the Web Console:

[#move-server-grp]
. From the [.uicontrol]*Couchbase Web Console > Servers > Groups* page, select the server that you want to move to another group.
. Select [.uicontrol]*move to* pull-down menu to select the new group name.
Once you select the new group, the [.uicontrol]*pending move to <Group Name>* message appears.
. Click [.uicontrol]*Apply Changes* to confirm the server move.
. Make sure to [.uicontrol]*Rebalance* from the [.uicontrol]*Servers* page.
For more information on how to rebalance, see xref:rebalance.adoc#topic_xsx_1mn_vs[Rebalancing a Cluster].
