= Manage Server Groups

[abstract]
You can create logical groupings of servers on a cluster where each server group physically belongs to a rack or availability zone.

This section describes how to manage server groups through the Couchbase Web Console.
Server and server groups can also be managed through the Couchbase command-line interface (CLI) and REST API.

NOTE: By default, when a Couchbase cluster is initialized, Group 1 is created.

== Adding a Server Group

To add a new group using the Web Console:

[#server-grp]
. From the [.ui]*Couchbase Web Console > Servers >* click [.ui]*Groups* located on the top right side.
. Click [.ui]*Add Group* to add a new group.
. Enter the group name in the [.ui]*Group Name* field and click [.ui]*Create*.

Once the information is entered successfully, a new group is added in the [.ui]*Server Groups* page.

== Editing a Server Group

To edit a server group name using the Web Console:

. From the [.ui]*Couchbase Web Console > Servers > Groups* page, select the group that you want to edit.
. Click [.ui]*edit name* to change the group name.
. In the [.ui]*Edit Group* window, click [.ui]*Rename*.
+
The selected group name is updated.

== Deleting a Server Group

Server groups are deleted by removing all nodes from the server group and then deleting the server group.

To delete a server group using the Web Console:

. From the [.ui]*Couchbase Web Console > Servers > Groups* page, select the group that you want to delete.
. Click [.ui]*delete group* to delete the group.
. In the [.ui]*Confirm Delete Group* window, click [.ui]*Delete Group*.
+
The selected group is deleted.

== Moving Servers Between Server Groups

Servers can be moved between server groups from the [.ui]*Server Groups* page.

To move a server from one group to another using the Web Console:

[#move-server-grp]
. From the [.ui]*Couchbase Web Console > Servers > Groups* page, select the server that you want to move to another group.
. Select [.ui]*move to* pull-down menu to select the new group name.
Once you select the new group, the [.ui]*pending move to <Group Name>* message appears.
. Click [.ui]*Apply Changes* to confirm the server move.
. Make sure to [.ui]*Rebalance* from the [.ui]*Servers* page.
For more information on how to rebalance, see xref:rebalance.adoc[Rebalancing a Cluster].
