= Removing a server

[abstract]
Removing a node marks the node for removal from the cluster.

[NOTE]
====
If you remove a node that is running one of the services, it will have the following result:

* Data service: reduced capacity to handle key/value workload.
* Index service: index data loss on that node.
This service does not support rebalance.
When a node running the index service is removed or failed over, indexes that reside on the node are not moved to another node after rebalancing.
These indexes are no longer available for queries and are dropped.
Fore more details see xref:install:services-upgrade.adoc[Upgrading Services from Version 4.0 to the Latest].
* Query service: loss of query capability in that node.
====

Removing a node does not stop the node from servicing requests.
Instead, it only marks the node as ready for removal from the cluster.
You must perform a rebalance operation to complete the removal process.
Once a node is removed, it is no longer part of the cluster and can be switched off, updated, or upgraded.

IMPORTANT: Before you remove a node from the cluster, ensure that you have the capacity within the remaining nodes to handle the workload.
For the best results, use the xref:install:upgrade-swap.adoc[swap rebalance.]

[WARNING]
====
Occasionally, during an online upgrade if all old nodes are removed from the cluster, clients may no longer know about any nodes and fail to connect.
To prevent such problems, make sure that you provide one of the following solutions:

* At least one of the original nodes is maintained in the cluster, and this node is listed in the client's server configuration.
* The client's server configuration is appropriately updated to include at least one new node before the last old node is removed.
====
