= Failover

[abstract]
_Failover_ is the process whereby a node can be removed from a Couchbase
cluster.

[#failover-types]
== Failover Types

There are two basic types of failover: [.term]_graceful_ and [.term]_hard_.

* _Graceful_: The ability to remove a Data Service node from the cluster proactively, in an orderly and controlled fashion.
This is an online operation, requiring zero downtime.
When the node to be removed contains the Data Service, the process promotes replica vBuckets on the remaining cluster-nodes to _active_ status, and the active vBuckets on the affected node to _dead_.
Throughout the process, the cluster maintains all 1024 active vBuckets for each bucket.
+
Graceful failover can only be used on nodes that run the Data Service.
If controlled removal of a non-Data Service node is required, xref:learn:clusters-and-availability/removal.adoc[Removal] should be used.

* _Hard_: The ability to drop a node from the cluster reactively, because the node has become unavailable or unstable.
If the lost node was running the Data Service, active vBuckets have been lost: therefore the Hard failover process promotes replica vBuckets on the remaining cluster-nodes to _active_ status, until 1024 active vBuckets again exist for each bucket.
+
Hard failover should _not_ be used on an available node, since this may disrupt ongoing operations (such as the writes and replications that occur on a Data Service node).
Instead, available nodes should be taken out of the cluster by means of either Graceful failover (if they are Data Service nodes) or xref:learn:clusters-and-availability/removal.adoc[Removal] (if they are nodes of any kind).

Graceful failover _must_ be manually initiated. Hard failover _can_ be manually initiated.
Hard failover can also be initiated automatically by Couchbase Server: this is known as _automatic_ failover.
The Cluster Manager detects the unavailability of a node, and duly initiates a _hard_ failover, without administrator intervention.

Note that when a node is flagged for _failover_ (as opposed to _removal_), replica vBuckets are lost when rebalance occurs; since some are promoted to _active_ status, and are not replaced with new replica-copies.
By contrast, xref:learn:clusters-and-availability/removal.adoc[Removal] creates new copies of those replica vBuckets that would otherwise be lost. This maintains the cluster's previous level of data-availability; but results in greater competition for memory resources, across the surviving nodes).

[#detecting-node-failure]
== Detecting Node-Failure

Hard failover is performed after a node has failed.
It can be initiated either by administrative intervention, or through _automatic_ failover.

When _automatic_ failover is used, the Cluster Manager handles both the detection of failure, and the initiation of hard failover, without administrative intervention: however, the Cluster Manager does not identify the cause of failure.
Following failover, administrator-intervention is required, to identify and fix problems, and to initiate _rebalance_, whereby the cluster is returned to a healthy state.

If manual failover is to be used, administrative intervention is required to detect that a failure has occurred.
This can be achieved either by assigning an administrator to monitor the cluster; or by creating an externally based monitoring system that uses the Couchbase REST API to monitor the cluster, detect problems, and either provide notifications, or itself trigger failover.
Such a system might be designed to take into account system or network components beyond the scope of Couchbase Server.

[#node-removal]
== Node Removal

_Node removal_ uses the _rebalance_ process to remove a node from a cluster in a controlled fashion.
It creates on the remaining nodes new copies of replica vBuckets that would otherwise be lost when the selected node is taken offline. See xref:learn:clusters-and-availability/removal.adoc[Removal] for a conceptual description of node-removal. For practical steps, see xref:manage:manage-nodes/remove-node-and-rebalance.adoc[Remove a Node and Rebalance].
