= Node-to-Node Encryption
:description: Network traffic between the individual nodes of a Couchbase-Server cluster can be encrypted, in order to optimize cluster-internal security.

[#abstract]
{description}

[#node-to-node-encryption]
== Node-to-Node Encryption

Couchbase Server supports _node-to-node encryption_, whereby network traffic between the individual nodes of a cluster is encrypted, in order to optimize cluster-internal security.

In Couchbase Server Version 6.6.5, node-to-node encryption is supported for _all_ Couchbase services.
Note however, that in versions _before_ 6.6.5, node-to-node encryption is _not_ supported for the Eventing Service.

Node-to-node encryption can be established on either of two levels:

* _Control_. Cluster-management information passed between nodes by the Cluster Manager and related low-level processes is encrypted.
However, the data that is passed between nodes by Couchbase Services continues to be passed in the clear.
When node-to-node encryption is first enabled, this is the default.

* _All_. Both cluster-management information and data is passed in encrypted form.
Node-to-node encryption can be supported by means of either the Couchbase-provided certificates with which nodes are protected by default; or certificates installed by the administrator.

For practical steps towards set-up, see xref:manage:manage-nodes/apply-node-to-node-encryption.adoc[Manage Node-to-Node Encryption].

[#using-node-to-node-encryption]
=== Using Node-to-Node Encryption

Node-to-node encryption is disabled by default.
Note that auto-failover must be switched off both for a change to be made to the cluster’s address-family, and for encryption to be enabled or disabled: auto-failover can be switched back on after the necessary changes have been made.
(This requirement prevents nodes that are undergoing changes from being determined unresponsive during the process, and unnecessarily failed over.)

Note also that in all versions of Couchbase Server that are 6.6 or later, all Eventing functions must be _paused_ before node-to-node encryption for the cluster is enabled, disabled, or is established at a new level: this prevents loss of mutations.
All paused Eventing functions should then be _resumed_, once changes to node-to-node encryption are complete.
For information, see xref:cli:cbcli/couchbase-cli-eventing-function-setup.adoc[eventing-function-setup].

Node-to-node encryption is managed by means of the Couchbase CLI.
The typical sequence of commands and other activities is summarized below.

. Change address family.
Both IPV4 and IPV6 addresses are supported: one or the other must be selected.
The selected setting is applied to every node in the cluster.
The address family is changed by means of the xref:cli:cbcli/couchbase-cli-ip-family.adoc[ip-family] CLI command.

. Pause all Eventing functions.

. Enable cluster encryption.
Cluster encryption must be specifically enabled: by default, it is disabled.
To enable or disable cluster encryption, or to determine the current setting, use the xref:cli:cbcli/couchbase-cli-node-to-node-encryption.adoc[node-to-node-encryption] CLI command.

. Establish cluster encryption-level.
This determines whether only cluster-management information or both cluster-management information and data will be passed in encrypted form: these are respectively the _control_ and _all_ encryption levels.
Use the xref:cli:cbcli/couchbase-cli-setting-security.adoc[setting-security] CLI command to specify or to get the current setting.

. Resume all Eventing functions.

. If required, re-enable auto-failover.

For a more detailed account of this sequence, see xref:manage:manage-nodes/apply-node-to-node-encryption.adoc[Manage Node-to-Node Encryption].

[#certificate-rotation-and-node-to-node-encryption]
=== Certificate Management and Node-to-Node Encryption

Before the _root_ or _intermediate_ certificates for a cluster are either uploaded for the first time, or are subsequently rotated, node-to-node encryption should be disabled:

. Use xref:cli:cbcli/couchbase-cli-node-to-node-encryption.adoc[node-to-node-encryption], to disable node-to-node encryption.
Note that node-to-node encryption cannot be disabled when the encryption-level has been specified as _all_.
Before attempting to disable, determine the encryption-level, and if necessary, change it to _control_.

. Create or rotate the root and/or intermediate certificates as appropriate: see the procedures in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates].
Also see xref:cli:cbcli/couchbase-cli-ssl-manage.adoc[ssl-manage].

. Re-enable node-to-node encryption, using xref:cli:cbcli/couchbase-cli-node-to-node-encryption.adoc[node-to-node-encryption], and establish the appropriate level of encryption.

Note that the _node_ certificates for a cluster can be created or rotated _without_ node-to-node-encryption being disabled.
