= Node-to-Node Encryption
:description: Network traffic between the individual nodes of a Couchbase-Server cluster can be encrypted, in order to optimize cluster-internal security.

[#abstract]
{description}

[#node-to-node-encryption]
== Node-to-Node Encryption

Couchbase Server supports _node-to-node encryption_, whereby network traffic between the individual nodes of a cluster is encrypted, in order to optimize cluster-internal security.

Node-to-node encryption can be established on either of two levels:

* _Control_. Cluster-management information passed between nodes by the Cluster Manager and related low-level processes is encrypted.
However, the data that is passed between nodes by Couchbase Services continues to be passed in the clear.
When node-to-node encryption is first enabled, this is the default.

* _All_. Both cluster-management information and data is passed in encrypted form.
Node-to-node encryption can be supported by means of either the Couchbase-provided certificates with which nodes are protected by default; or certificates installed by the administrator.
+
Note, however, that node-to-node encryption is only available in the Couchbase Server for the Eventing Service in the 7.X train starting with version 7.0.2 and the 6.X train starting with version 6.6.5.
Therefore, on earlier versions (in either train), when _all_ is specified, the data passed to and from all other Couchbase Services is passed in encrypted form, whereas the data passed to and from the Eventing Service continues to be passed in _unencrypted_ form.

For practical steps towards set-up, see xref:manage:manage-nodes/apply-node-to-node-encryption.adoc[Manage Node-to-Node Encryption].

[#using-node-to-node-encryption]
=== Using Node-to-Node Encryption

Node-to-node encryption is disabled by default.

* First auto-failover must be switched off both for a change to be made to the cluster’s address-family, and for encryption to be enabled or disabled: auto-failover can be switched back on after the necessary changes have been made.
(This requirement prevents nodes that are undergoing changes from being determined unresponsive during the process, and unnecessarily failed over.)

* Second any deployed Eventing Functions need to be paused for encryption to be enabled or disabled: the Eventing Functions can be resumed after the necessary changes have been made.
(This requirement prevents the potential loss of mutations during the encryption change.) 

Node-to-node encryption is managed by means of the Couchbase CLI.
The typical command-sequence is summarized below.

. Change address family.
Both IPV4 and IPV6 addresses are supported: one or the other must be selected.
The selected setting is applied to every node in the cluster.
The address family is changed by means of the xref:cli:cbcli/couchbase-cli-ip-family.adoc[ip-family] CLI command.

. Enable cluster encryption.
Cluster encryption must be specifically enabled: by default, it is disabled.
To enable or disable cluster encryption, or to determine the current setting, use the xref:cli:cbcli/couchbase-cli-node-to-node-encryption.adoc[node-to-node-encryption] CLI command.

. Establish cluster encryption-level.
This determines whether only cluster-management information or both cluster-management information and data will be passed in encrypted form: these are respectively the _control_ and _all_ encryption levels.
Use the xref:cli:cbcli/couchbase-cli-setting-security.adoc[setting-security] CLI command to specify or to get the current setting.

. If required, re-enable auto-failover.

For a more detailed account of this sequence, see xref:manage:manage-nodes/apply-node-to-node-encryption.adoc[Manage Node-to-Node Encryption].

[#certificate-rotation-and-node-to-node-encryption]
=== Certificate Management and Node-to-Node Encryption

Before the _root_ or _intermediate_ certificates for a cluster are either uploaded for the first time, or are subsequently rotated, node-to-node encryption should be disabled:

. Use xref:cli:cbcli/couchbase-cli-node-to-node-encryption.adoc[node-to-node-encryption], to disable node-to-node encryption.
Note that node-to-node encryption cannot be disabled when the encryption-level has been specified as _all_.
Before attempting to disable, determine the encryption-level, and if necessary, change it to _control_.

. Create or rotate the root and/or intermediate certificates as appropriate: see the procedures in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates].
Also see xref:cli:cbcli/couchbase-cli-ssl-manage.adoc[ssl-manage].

. Re-enable node-to-node encryption, using xref:cli:cbcli/couchbase-cli-node-to-node-encryption.adoc[node-to-node-encryption], and establish the appropriate level of encryption.

Note that the _node_ certificates for a cluster can be created or rotated _without_ node-to-node-encryption being disabled.
