= XDCR Conflict Logging
:description: pass:q[XDCR detects and logs concurrent conflicts that occur in different clusters but on the same document version due to independent modifications by locally connected applications during Active-Active replication. You can manually review and resolve these conflicts to prevent data loss.]

[abstract]
{description}

During XDCR Active-Active replication, a conflict can occur if different applications connected locally to two different clusters, independently modify the same version of the document at the same time.
These simultaneous modifications happen within the convergence window*, so the changes made in one document are not reflected in the history of the other.

XDCR detects and logs these mutations, which you can manually review, upsert, and continue with the resolution process.

_*A convergence window is a period during which multiple actors, such as users, applications, or clusters, can modify the same document in an active-active topology, before the changes have fully converged across all clusters._

== Adaptibility of XDCR Conflict Logging

* Conflicts are expected to be rare during XDCR replication. Due to any reason, if there is an upsurge of conflicts, XDCR skips logging conflicts and prioritises replication.

* Conflict logging is asynchronous and attempted on the best-effort basis, which makes it the lowest operational priority.
If any error occurs, such as low memory quota or a lag in storing conflict logs, XDCR may pause or stop the logging process, reports the error type for the pipeline, and continues with replication so there is no High Availability issue.

* xref:learn:clusters-and-availability/xdcr-conflict-resolution.adoc[Conflict Resolution] process remains unchanged.

[#overview-of-xdcr-conflict-logging]
== Overview of the XDCR Conflict Logging Process

A conflict logging process has the following steps:

. xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#xdcr-conflict-logging-prerequisites[Prerequisites]: Enable conflict logging by configuring and deploying all replication clusters on Server 8.0.0 or a later version, xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#create-conflict-collection[creating a conflict collection], and configuring xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.#replication-settings-for-conflict-logging[replication settings].
Also, see xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#deploy-xdcr-conflict-logging[Deploying XDCR Active-Active Conflict Logging Setup].

. xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#xdcr-conflict-detection-logging[Conflict Detection and Logging]: Start the XDCR conflict resolution process.
If the same version of the document is modified in the source and target clusters by locally connected different applications at around the same time, XDCR detects these conflicts using Hybrid Logical Vectors (HLVs).
XDCR logs the conflict details such as document ID, document contents, and conflicting document histories, into a collection designated for conflict logging.

. xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#conflict-access-and-review[Conflict Access and Review]: You can access and review the logged conflicts.
Then manually resolve the conflicts, upsert the documents, and contiue the  xref:learn:clusters-and-availability/xdcr-conflict-resolution.adoc[replication process] without data loss.

You can configure an XDCR Active-Active setup for logging conflicts through one of the following methods:

* xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#greenfield-deployment-conflict-logging[Greenfield Deployment]: Set up a new XDCR active-active setup compatible for conflict logging.

* xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#upgrade-xdcr-setup-conflict-logging[Upgrading an Existing XDCR Active-Passive Setup]: Configure an existing XDCR active-passive setup into an XDCR active-active setup compatible for conflict logging.

[#conflict-collection]
== Conflict Collection

Conflict collection is a regular collection created by you, which stores the conflict log messages, the metadata of conflicting documents, and the conflicting document bodies from the affected clusters of the XDCR topology.

* A conflict collection is a regular collection, so you can use regular RBAC to control standard access and programmatic access to the documents in the collection.

* Supports enabling auditing for investigations if a collection or scope associated with the conflict collection is dropped.
For information about enabling auditing and enabling event-auditing, see xref:manage:manage-security/manage-auditing.adoc[Manage Auditing].
For more information about Event Auditing, see xref:audit-event-reference/audit-event-reference.adoc[Audit Event Reference].

* You can store conflict collection in the source bucket or in a separate collection in a bucket that's not used in any XDCR replications.

* You can use a conflict collection for a single or multiple XDCR replications while the document keys are unique.

* XDCR can write into conflict collections associated with the source cluster, however, XDCR cannot modify the conflict collections in any target clusters.

[IMPORTANT]
====
* Use the conflict collection only for storing the conflict data to prevent applications from writing into this collection, and causing data inconsistency and feature issues.

* External documents in the collection can interfere with event retrieval because of the dependency on xref:8.0@server:howtos/kv-operations.adoc#scoped-kv-operations[KV Range Scan].
====

[#create-conflict-collection]
=== Create Conflict Collection

When xref:manage:manage-buckets/create-bucket.adoc[creating a bucket] and a collection (see  and xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc[Manage Scopes and Collections]), designate them as conflict bucket and conflict collection for logging conflicts by using: 

** xref:manage:manage-xdcr/create-xdcr-replication.adoc#xdcr-ui-settings-for-conflict-logging
[Replication Settings for XDCR Conflict Logging], to set from UI.

** xref:rest-api:rest-xdcr-create-replication.adoc[Creating a Replication], to set through REST API.

NOTE: To configure the conflict collection, use the same collection namespace specified in the replication setting, xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#use-conflictlogging-and-loggingrules[Use conflictLogging Key and loggingRules Value in XDCR].

[#replication-settings-for-conflict-logging]
== Replication Settings for Conflict Logging

To enable XDCR conflict logging, you must configure the replication settings for logging conflicts.
The replication settings are as follows:

[#enable-hlv-conflict-logging]
=== Enable Hybrid Logical Vectors (HLVs)

To enable XDCR conflict logging, as a prerequisite, Hybrid Logical Vectors (HLVs) must be enabled on all buckets of all clusters participating in the replication topology. 

XDCR uses HLV metadata to detect conflicts from different clusters and stores the document ID, document contents, and conflicting document histories into a pre-defined xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#create-conflict-collection[Conflict Collection] created by you.

To enable the bucket property `enableCrossClusterVersioning`:

* Using REST API, see xref:rest-api:rest-bucket-create.adoc#example-enablecrossclusterversioning-edit[Example: Turning on enableCrossClusterVersioning, when Editing].

* From the UI, see xref:manage:manage-buckets/edit-bucket.adoc#edit-bucket-for-eccv[Edit a Bucket to Enable Cross Cluster Versioning].

[IMPORTANT]
====
* Once `enableCrossClusterVersioning` is enabled, it cannot be disabled.
As a result, HLV cannot be disabled.

* `enableCrossClusterVersioning` can be enabled only when editing a bucket.

* In the future, to add a new cluster to the existing replication topology, enable HLV on each new cluster to activate conflict logging. Because only the documents mutated after enabling the `enableCrossClusterVersioning` property on both the source and target clusters, are considered for conflict logging.
====

Couchbase recommends to monitor bucket memory quota and storage usage after enabling HLV to ensure adequate resources are available.

For more information about the bucket property `enableCrossClusterVersioning` and HLV, see xref:learn:clusters-and-availability/xdcr-enable-crossclusterversioning.adoc[XDCR enableCrossClusterVersioning].

[#use-conflictlogging-and-loggingrules]
=== Use conflictLogging Key and loggingRules Value in XDCR

To log conflicts, create an XDCR replication by using the following replication settings, which accepts a key and a corresponding JSON object as the value.

* `conflictLogging` is the replication setting key.
* `loggingRules` is the JSON object as the value.

These replication settings are a part of the advanced settings of the XDCR replication. See xref:rest-api:rest-xdcr-adv-settings.adoc[Manage Advanced Settings].

To configure the key and value:

* From UI, see xref:manage:manage-xdcr/create-xdcr-replication.adoc[Create a Replication]. For reference, see xref:manage:manage-xdcr/replicate-using-scopes-and-collections.adoc[Replicate Using Scopes and Collections].

* Using REST API, see xref:rest-api:rest-xdcr-create-replication.adoc[Creating a Replication].

NOTE: By default, conflicts are logged in the conflict collection you create. You can use `loggingRules` to override this default setting.

[#conflictlogging-key]
==== conflictLogging key

`conflictLogging` is the replication setting key and its details are as follows.

|===
| Value | Parameter/Example | Description

| *Disabled*
|`{}`
| An empty JSON object value must be specified to disable the Conflict Logging feature.

| *Enabled for all conflicts*

| Parameter:

`{
   “bucket”: [bucketName],
   “collection”: [scope].[collection]”,
}`

Example:

`{
   “bucket”: “bucket1.prime”,
   “collection”: “scope2.collection3”,
}
{
   “bucket”: “b2.prime”,
   “collection”: “_default.col4”,
}`

| The `bucket` key in the embedded object indicates the bucket in which the conflict collection is located. Periods (`.`) are allowed in bucket names. The `collection` key in the embedded object indicates the scope and collection namespace for the conflict collection. This is required to enable the Conflict Logging feature.

| *Enabled with special logging rules*

| Parameter:

`{
   “bucket”: [bucketName],
   “collection”: [scope].[collection]”,
   “loggingRules”: {<logging_rules>},
}`

| The `loggingRules` key is optional. If you use the `loggingRules` key, then the value must be a non-empty JSON object with specific key-value pairs, where each pair is a specific rule. The mutations that cause conflicts are compared with the rules. If a conflict causing mutation does not belong to a rule from `loggingRules`, that conflict is not logged.

For example explanation, see xref:xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#example-special-loggingrules[Example for Special Logging Rules].

| *Disabled with stored logging rules*

| 
`{
   “bucket”: [bucketName],
   “collection”: [scope].[collection]”,
   “loggingRules”: {...},
   “disabled”: true,
}`

| This is similar in function to the *Disabled* potential value.
However, this value provides the additional benefit of saving the logging rules on disk, which enables the restoration of the rules from the UI.
|===

[#example-special-loggingrules]
==== Example for Special Logging Rules

*Example*:

----
{
    "bucket": "bucket1",
    "collection": "scope2.collection3",
    "loggingRules": {
        "s1": {},
        "s1.privateCol": null,
        "privateScope": null,
        "privateScope.specialCol": {},
        "rbacScope": {
            "bucket": "customBucket",
            "collection": "customScope.customCollection"
        },
        "rbacScope.rbacCollection": {
            "bucket": "customBucket",
            "collection": "specialScope.specialCollection"
        }
    }
}
----

*Explanation*:

* Default logging of conflicts happens in `scope2.collection3` of `bucket1`.

* You can override the defaults by providing special logging rules using `loggingRules`.

** All conflicts from `s1` except mutations that belong in `s1.privateCol` will be logged in the conflict collection `scope2.collection3` of `bucket1`.

** None of the conflicts from `privateScope` will be logged. However, documents from a special collection `privateScope.specialCol` in the same `privateScope` will be logged.

** All conflicts from `rbacScope` will be logged in a separate bucket `customBucket` and collection `customScope.customCollection`.

** If a conflict is caused by a mutation from `rbacScope.rbacCollection`, then that conflict is logged in `specialScope.specialCollection`.


[#logging-rules]
==== loggingRules

This section explains the mapping of conflict logs to their source. The value of `loggingRules` is a JSON object composed of any number of the following Key-Value (KV) formats.

[NOTE]
====
* The keys and their priorities of each KV pair are specified in the format similar to xref:manage:manage-xdcr/replicate-using-scopes-and-collections.adoc##rules-for-explicit-mappings[Rules for Explicit Mappings] and also have the same priority as listed in the mapping rules.

* Similar to explicit mapping mode, if a source scope or collection is not specified, then the conflict from that source is ignored.

* Conflict logging rules can be saved without enabling the Conflict Logging setting, however, the rules will come into effect only when the Conflict Logging setting is enabled.
====

|===
| Key | Value | Description 

| [scope]
| `{}`

Empty JSON object.
| All mutations from the specified scope will be logged in the conflict collection defined by bucket, scope, and collection in the *ConflictLogging* key.

| [scope]
| `null`
| All mutations from the specified scope will not be logged.

| [scope.collection]
| `{}`
| All mutations from the specified collection will be logged in the conflict collection defined by bucket, scope, and collection in the *ConflictLogging* key.

| [scope.collection]
| `null`
| All mutations from the specified collection will not be logged.

| [scope]
|`{
   “bucket”: [otherBucket],
   “collection”: [otherScope].[otherCollection]”
  }`
| All mutations from the chosen scope will be logged in the specific conflict collection defined by otherBucket, otherScope, and otherCollection; instead of the original location mentioned in the *ConflictLogging* key.

| [scope.collection]
|`{
   “bucket”: [otherBucket],
   “collection”: [otherScope].[otherCollection]”
  }`
| All mutations from the chosen scope will be logged in the specific conflict collection defined by bucket, scope, and collection; instead of the original location mentioned in the *ConflictLogging* key.
|===

[#tunable-replication-settings]
==== Tunable Replication Settings

By default, the xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#conflict-logger[Conflict Logger] is tuned to handle a low percentage of conflicts.
Use the following settings to tune the Conflict Logger.

|===
| Setting | Description | Default

| `conflictLogging`
| The main setting which when non-empty and valid enables logging of conflicts.

For more information, see xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#conflictlogging-key[conflictLogging Key].
|

| `cLogSetTimeoutMs`
| Sets the timeout for SetMeta operation for conflict writing.
| 5000ms

| `cLogPoolGetTimeoutMs`
| Timeout for getting connection from connection pool
| 5000ms

| `cLogNetworkRetryCount`
| Number of attempts for a single doc when there is a network error
| 5

| `cLogNetworkRetryIntervalMs`
| Time interval to sleep between attempts to write the conflict doc on network error
| 2000ms

| `cLogWorkerCount`
| Number of workers used by the conflict logger, which actually write conflict documents.
| 20

| `cLogQueueCapacity`
| Queue capacity for the conflict logger.
| 6000

| `cLogMaxErrorCount`
| Max number of errors encountered by conflict logger in a “Error Window” after which the conflict logger will be hibernated.

For information about hibernation, see xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#reliability-components-logger[Reliability Components].
| 10

| `cLogErrorTimeWindowMs`
| This is the time window in which the number of errors in the conflict logger will be checked.
| 120000ms

| `cLogReattemptDurationMs`
| This is the duration for which the conflict logger will be hibernated and after this the logger will be active again.

For information about hibernation, see xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#reliability-components-logger[Reliability Components].
| 600000ms
|===

[#deploy-xdcr-conflict-logging]
== Deploying XDCR Active-Active Conflict Logging Setup

Deploy XDCR active-active setup and enable logging of conflicts using one of the following procedures:

* xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#greenfield-deployment-conflict-logging[Greenfield Deployment]: New installation of Couchbase Server 8.0.0 (or a later version) clusters. Then enable the Conflict Logging feature for each necessary bucket.

* xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#upgrade-xdcr-setup-conflict-logging[Upgrade]: Upgrade an XDCR setup from a Server version earlier than 8.0.0 to the Server version 8.0.0 (or a later version).
Then enable the Conflict Logging feature for each necessary bucket.

[#xdcr-conflict-logging-prerequisites]
=== Prerequisites for XDCR Active-Active Conflict Logging

To use the XDCR Conflict Logging feature, it must be enabled.
The prerequisites for enabling XDCR’s conflict logging capability are as follows:

. *Bi-directional replication setup*: All clusters in the XDCR topology must be running Couchbase Server 8.0.0 or a later version.
XDCR supports conflict logging only in bi-directional replications.
In these replications, mutations from any cluster can be replicated to any other cluster.
+
[#presence-of-conflict-collection]
. *Presence of Conflict Collection*: Ensure you have created a collection in each participating clusters and designated these collections for logging conflicts.
+
For more information, see xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#create-conflict-collection[Create Conflict Collection].

. *Hybrid Logical Vectors (HLVs) compatibility*: Set the bucket property `enableCrossClusterVersioning` to `true` on all the buckets in the XDCR topology clusters to enable HLV.
+
For more information, see xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#enable-hlv-conflict-logging[Enable Hybrid Logical Vectors (HLVs)].

[#greenfield-deployment-conflict-logging]
=== Greenfield Deployment

To configure a new active-active XDCR setup for logging conflicts, do the following:

. Create two clusters, A and B, with all the nodes of both the clusters on Server 8.0.0 (or a later) version.
+
IMPORTANT: Couchbase doesn’t recommend replicating data with Server versions earlier than 8.0.0 because conflicts won’t be logged and HLV metadata won't update properly.
This can result in data loss and undetected conflicts.

. Create buckets, for example, B1 and B2 in Cluster A and Cluster B respectively, between which XDCR will be set up.
Now, do the following:
+
NOTE: If the replication topology has more than two buckets, you must enable ECCV for all those buckets.

.. Enable the `enableCrossClusterVersioning` (ECCV) setting on B1. All mutations in B1 from this point forward will include a new metadata Hybrid Logical Vector (HLV). Refer to this time as T1.
+
[NOTE]
====
* Once enabled, `enableCrossClusterVersioning` cannot be disabled.
* For information about enabling ECCV, see xref:rest-api:rest-bucket-create.adoc#example-enablecrossclusterversioning-edit[Example: Turning on enableCrossClusterVersioning, when Editing] using REST API and xref:manage:manage-buckets/edit-bucket.adoc#edit-bucket-for-eccv[Edit a Bucket to Enable Cross Cluster Versioning] from the UI.
====
.. Enable the ECCV setting on B2. All mutations in B2 from this point forward will include a new metadata HLV. Refer to this time as T2.

. Create bucket(s) and collection(s) for logging conflicts on both Cluster A and Cluster B using the following:
** xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#create-conflict-collection[Create Conflict Collection].
** xref:manage:manage-xdcr/create-xdcr-replication.adoc#xdcr-ui-settings-for-conflict-logging
[Replication Settings for XDCR Conflict Logging] from UI.
** xref:rest-api:rest-xdcr-create-replication.adoc[Creating a Replication] using REST API.
+
NOTE: Ensure to set a size enough to accommodate the expected volume of conflicts.

. Create XDCR from B1 to B2 using xref:manage:manage-xdcr/create-xdcr-replication.adoc#xdcr-ui-settings-for-conflict-logging
[Replication Settings for XDCR Conflict Logging] from UI or see xref:rest-api:rest-xdcr-create-replication.adoc[Creating a Replication] using REST API. Select the target(s) in A, where the conflicts from A, detected by XDCR, must be logged.

. Create XDCR from B2 to B1 using xref:manage:manage-xdcr/create-xdcr-replication.adoc#xdcr-ui-settings-for-conflict-logging
[Replication Settings for XDCR Conflict Logging] from UI or see xref:rest-api:rest-xdcr-create-replication.adoc[Creating a Replication] using REST API. Select the target(s) in B, where the conflicts from B, detected by XDCR, must be logged.

. Fine tune the Conflict Logger on both clusters, A and B, depending on the percentage of expected conflicts, using xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#tunable-replication-settings[Tunable Replication Settings].

After the configuration, this setup is ready to process application traffic on both B1 and B2.
When a document mutated at time t1 (in B1) and another document mutated at time t2 (in B2) are detected to be in conflict, then:

* Both documents are logged along with a conflict metadata document in respective conflict buckets.

* Logging occurs only if t1 > T1 and t2 > T2.

[#upgrade-xdcr-setup-conflict-logging]
=== Upgrading an Existing XDCR Active-Passive Setup

Convert an existing XDCR active-passive setup into XDCR active-active setup for logging conflicts.

For illustration, there are two clusters, A and B.
Cluster A is active in the XDCR setup with bucket B1 connected to passive cluster B in the XDCR setup with bucket B2.
Currently, the application traffic will be only on bucket B1 of Cluster A.

. Upgrade both clusters A and B with all the nodes of the clusters to Server 8.0.0 (or a later) version.
+
NOTE: Couchbase doesn’t recommend replicating data on Server versions earlier than 8.0.0 because conflicts won’t be logged and HLV metadata won't update properly.
This can result in data loss and undetected conflicts.

. On B1 and B2, enable the `enableCrossClusterVersioning` (ECCV) setting.
All mutations in B1 and B2 from this point forward will include a new metadata Hybrid Logical Vector (HLV).
Refer to this time as T1 and T2 for B1 and B2 respectively.
+
[NOTE]
====
* Once enabled, `enableCrossClusterVersioning` cannot be disabled.
* If there are more than two buckets in the replication topology, you must enable ECCV for all those buckets.
* For information about enabling ECCV, see xref:rest-api:rest-bucket-create.adoc#example-enablecrossclusterversioning-edit[Example: Turning on enableCrossClusterVersioning, when Editing] using REST API and xref:manage:manage-buckets/edit-bucket.adoc#edit-bucket-for-eccv[Edit a Bucket to Enable Cross Cluster Versioning] from the UI.
====

. Create bucket(s) and collection(s) for logging conflicts on both Cluster A and Cluster B using the following:
** xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#create-conflict-collection[Create Conflict Collection].
** xref:manage:manage-xdcr/create-xdcr-replication.adoc#xdcr-ui-settings-for-conflict-logging
[Replication Settings for XDCR Conflict Logging] from UI.
** xref:rest-api:rest-xdcr-create-replication.adoc[Creating a Replication] using REST API.
+
NOTE: Ensure to set a size enough to accommodate the expected volume of conflicts.

. Update the existing XDCR replication setting from B1 to B2 by configuring xref:manage:manage-xdcr/create-xdcr-replication.adoc#xdcr-ui-settings-for-conflict-logging
[Replication Settings for XDCR Conflict Logging] from UI or see xref:rest-api:rest-xdcr-create-replication.adoc[Creating a Replication] using REST API.
Select the target(s) in A, where th conflicts from A, detected by XDCR, must be logged.

. Create XDCR from B2 to B1 using xref:manage:manage-xdcr/create-xdcr-replication.adoc#xdcr-ui-settings-for-conflict-logging
[Replication Settings for XDCR Conflict Logging] from UI. Select the target(s) in B, where the conflicts from B, detected by XDCR, must be logged.

. Fine tune the Conflict Logger on both clusters, A and B, depending on the percentage of expected conflicts, using xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#tunable-replication-settings[Tunable Replication Settings].

. Enable application traffic on cluster B.

After the configuration, this setup is ready to process application traffic on both B1 and B2.
When a document mutated at time t1 (in B1) and another document mutated at time t2 (in B2) are detected to be in conflict, then:

* Both documents are logged along with a conflict metadata document in respective conflict buckets.

* Logging occurs only if t1 > T1 and t2 > T2.

[#xdcr-conflict-detection-logging]
== Conflict Detection and Logging

During XDCR replication, conflicts are supposed to be uncommon.
If there are any, then XDCR detects conflicts by comparing the HLV (Hybrid Logical Vector) metadata of the source and target documents.

After detecting conflicts, XDCR defines each logging event as a conflict record in a xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#create-conflict-collection[Conflict Collection].

IMPORTANT: If logging fails, XDCR continues with conflict resolution to ensure High Availability.

[#conflict-record]
=== Conflict Record

A conflict record consists of these three elements:

* *Conflict Record Document (CRD):* It is a JSON record document that contains source and target document key-value pairs. CRD consists of the following elements:
** Metadata document.
** Document key: `crd_<timestamp>_<SHA>`.
** Source document key and target document key. 

* *Source document:* It is a copy of the source document that caused the conflict. This logged source document consists of the following elements:
** Document body and xattrs of the source bucket from the conflict.
** Document key: `src_<timestamp>_<SHA>`.
* *Target document:* It is a copy of the target document that caused the conflict. This logged target document consists of the following elements:
** Document body and xattrs of the target bucket from the conflict.
** Document key: `tgt_<timestamp>_<SHA>`.

The generated `<SHA>` ensures that each conflict for the same document is unique and logs each conflict for each document key.

XDCR adds a hidden system xattribute flag called `_xdcr_conflict` into each of the three documents in a conflict record to prevent the documents from replicating to the target.

[#conflict-record-document-format]
=== Conflict Record Document Format

This is an example of Conflict Record Document.

[source,json]
----
{
 "docId": "ae03ecde-203c-4a3b-a6d0-36b60f627c8a",
 "id": "crd_1749454000005461807_e2f416ed317beb4f16a3587656b3d3450e1bec893cabebd3b9bb857d63824da4",
 "replId": "d976db26a5ce512a243db65a3026073f/bucket1/bucket1-nhuUKw2mOVPRiDvcoF4hJg==",
 "srcDoc": {
   "bucketUUID": "fada12469f1027ecb078d2c19a2802fb",
   "cas": 1749453999768928300,
   "clusterUUID": "1bc375a26b7f822ebe91288c58a6c614",
   "collection": "_default",
   "expiry": 0,
   "flags": 0,
   "id": "src_1749454000005461807_e2f416ed317beb4f16a3587656b3d3450e1bec893cabebd3b9bb857d63824da4",
   "isDeleted": false,
   "nodeId": "127.0.0.1",
   "revSeqno": 2,
   "scope": "_default",
   "xattrs": {
     "_mou": "",
     "_sync": "",
     "_vv": ""
   }
 },
 "tgtDoc": {
   "bucketUUID": "6cd3a35ba2d337d84d4fcd30c3a46fb9",
   "cas": 1749453999840231400,
   "clusterUUID": "d976db26a5ce512a243db65a3026073f",
   "collection": "_default",
   "expiry": 0,
   "flags": 0,
   "id": "tgt_1749454000005461807_e2f416ed317beb4f16a3587656b3d3450e1bec893cabebd3b9bb857d63824da4",
   "isDeleted": false,
   "nodeId": "18.206.194.145",
   "revSeqno": 2,
   "scope": "_default",
   "xattrs": {
     "_mou": "",
     "_sync": "",
     "_vv": "{\"cvCas\":\"0x00003dca244f4718\",\"src\":\"ntR6bcR9VHcjcPpQ5osEiw\",\"ver\":\"0x00003dca244f4718\"}"
   }
 },
 "timestamp": "2025-06-09T07:26:40.005Z"
}
----

Some of the key-value pairs in CRD document are as follows:

|===
| Key | Value

| `timestamp`
| Exact date and time of the event in UTC iso-8601 format:
YYYY-MM-DDThh:mm:ss:SSSZ

The timestamp will be the wall clock of the node that noted the conflict.

| `id`/`srcDoc.id`/`tgtDoc.id`
| CRD document ID prefixed with `crd_`.

A copy of conflict source document ID prefixed with `src_`.

A copy of conflict target document ID prefixed with `tgt_`.

| `docId`
| document id of the actual document in conflict.

| `replId`
| Replication ID.

| `srcDoc` and `tgtDoc`
| Document ID of the “copy” of source document to look up in the conflict collection and the “copy” of the target document to look up in the conflict collection.

| `nodeId`
| Node identification, which can be the hostname or IP address and port.

| `bucketUUID`
| Source/target bucket unique ID.

| `cas`
| Source/target document CAS.

| `clusterUUID`
| Source/target cluster unique ID.

| `isDeleted`
| True or false for is the source/target document deleted?

| `scope` and `collection`
| Name of the scope and collection where the conflict source/target documents exist.

| `revSeqno`
| Source/target document’s revision sequence number.

| `expiry`
| Source/target document’s expiry time.

| `flags`
| Source/target document’s flag.

| `xattrs`
| System xattributes.

| `_vv`
| Document version vector.
HLV metadata.
|===

[#conflict-logger]
=== Conflict Logger

The Logger in XDCR records conflict events detected during a replication.
It operates as an asynchronous component designed to minimize the impact on replication performance and system resources.

Conflict logging is attempted on the best-effort basis, which makes it the lowest operational priority.
If any error occurs, such as low memory quota or a lag in storing conflict logs, XDCR may pause or stop the logging process, reports the error type for the replication pipeline, and continues with replication so there is no High Availability issue.
See  xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#conflict-logging-errors[Conflict Logging Error Scenarios]

By default, the Conflict Logger is tuned to handle a low percentage of conflicts. Use xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#tunable-replication-settings[Tunable Replication Settings] to change the default settings of the Conflict Logger.

`xdcr_clog_status` is a Prometheus stat, which indicates the status of the Conflict Logger.
The status can be one of the following:

* Hibernated: The logger is temporarily disabled due to persistent errors or resource constraints.
+
NOTE: Hibernation prevents the degradation of the replication performance. Logging is re-enabled after a set interval, or after the errors are manually resolved and the logger is manually restarted.

* Running: The logger is actively processing conflict events.

* DNE: The logger does not exist.

[#conflict-access-and-review]
== Conflict Access and Review

XDCR conflict logs are your application documents, so they're added in regular collections called xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#create-conflict-collection[Conflict Collection] designated by you.

You can access, view, and process these documents programmatically, similar to your application documents, using the available utilities, features, and options.

For example, you can use RBAC to manage access to conflict collections.
You can also use Couchbase services and tools such as Eventing and Kafka Connect to process conflict log documents.

For information about the Conflict Record Document, see xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#conflict-record[Conflict Record].

[#retrieve-and-clean-up-conflict-record]
=== Retrieve and Clean Up Conflict Record

You can monitor and manage the conflict records xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#using-kv-range-scan-clog[Using KV Range Scan].

The following is a high-level procedure about using conflict logs from a conflict collection:

. Connect an SDK to the conflict collection.

. Issue a KV range start with the following parameters:

** Start: `crd_` (the prefix for conflict record document)
** End: Not specified

. KV range scan returns an ID, which you use for the scan.

. Issue a KV range scan `continue` command using the ID repeatedly.

. Each `continue` command returns a single CRD document.

. Examine the CRD document. Within the document, perform GET on source and target document ID. Open the document ID that matches your search with the following format.

** `src_<timestamp>_<SHA>` for source conflict document.
** `tgt_<timestamp>_<SHA>` for target conflict document.

. Resolve conflicts manually and write back to the source bucket.

. Optional step: Clean up by starting a transaction.

.. Delete the Conflict Record Document (CRD).
.. Delete the conflict source document.
.. Delete the conflict target document.

[#using-query-clog]
==== Using Query

KV range scan can work only using Data Service capability.
You can also use query instead of KV range scan.
However, this potentially requires creation of secondary indexes.
Additionally, it requires Index service and Query service to be activated in the cluster.
To access, view, and retrieve conflict logs using query, see xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#using-sdk-sqlpp-for-conflict-logs[Using Couchbase SDK with SQL++ for Conflict Logs].

[#using-sdk-sqlpp-for-conflict-logs]
=== Using Couchbase SDK with SQL++ for Conflict Logs

The most common way to view these documents is by using the Couchbase SDK with SQL++.

The following are a few examples.
In the examples, the conflict logs are stored in the collection `conflictlogs.bucket1.app1logs`.

[#sqlpp-examples-clog]
==== SQL++ Examples

For queries, you can create a custom index or a primary index.

* Create a primary index as follows.
+
[source,sqlpp]
----
CREATE PRIMARY INDEX `#primary` ON `conflictlogs`.`bucket1`.`app1logs`
----

* Create a custom index as follows.
+
You can use the `WHERE` clause with `SUBSTR(META().id,0,3) = “crd”` by making it an indexed field instead of `WHERE META().id LIKE "crd%"`.
+
For example:
+
[source,sqlpp]
----
CREATE INDEX `idx_crd_timestamp_docId` ON `conflictlogs`.`bucket1`.`applogs`(SUBSTR(META().id,0,3), `timestamp`,`docId`)
----
+
NOTE: When creating custom indexes, `META().id` is already a part of the index key.
When using `LIKE` in the queries, underscore is a wildcard. 
If you use underscore in comparison strings, ensure you use the escape character, so that it's used as an exact comparison instead of a wildcard comparison.
For example, `WHERE META().id LIKE “crd\\_%”`.

*Query example 1:* List all `docId` that had conflicts between two time periods.

[source,sqlpp]
----
SELECT META().id, b.docId, b.timestamp
FROM `conflictlogs`.`bucket1`.`app1logs` AS b
WHERE META().id LIKE "crd%" and b.timestamp between "2025-06-04T18:15:16.363Z" AND "2025-06-09T07:26:40.326Z"
----

*Query example 2:* Number of conflicts logged between two time periods.

[source,sqlpp]
----
SELECT count(*) AS num_conflicts
FROM `conflictlogs`.`bucket1`.`app1logs` AS b
WHERE META().id LIKE "crd%" and b.timestamp between "2025-06-04T18:15:16.363Z" AND "2025-06-09T07:26:40.326Z"
----

*Query example 3:* Number of different `docIds` that had conflicts between two time periods.

[source,sqlpp]
----
SELECT count (distinct b.docId) as num_different_docIds
FROM `conflictlogs`.`bucket1`.`app1logs` AS b
WHERE META().id LIKE "crd%" and b.timestamp between "2025-06-04T18:15:16.363Z" AND "2025-06-09T07:26:40.326Z"
----

*Query example 4:* List all `docIds` and the number of times each `docId` had a logged conflict between two time periods.

[source,sqlpp]
----
SELECT b.docId AS DOCID, COUNT(1) AS num_times_seen
FROM `conflictlogs`.`bucket1`.`app1logs` AS b
WHERE META(b).id LIKE "crd%" AND b.timestamp BETWEEN "2025-06-04T18:15:16.363Z" AND "2025-06-09T07:26:40.326Z"
GROUP BY b.docId
ORDER BY num_times_seen DESC LIMIT 20
----

The query result is as follows:

----
[
  {
    "DOCID": "4d9d18e7-5fa2-4eae-b32b-60d3d369da94",
    "num_times_seen": 2   
  },
  {
    "DOCID": "ae03ecde-203c-4a3b-a6d0-36b60f627c8a",
    "num_times_seen": 1   
  }
]
----

*Query example 5:* List all `docIds` and fields from the `src` and `tgt` documents that were in conflict, to view only the `docId` that had conflict with select fields from the `src` and `tgt` documents.

[source,sqlpp]
----
SELECT b.docId, b.srcDoc.id AS srcDocId, b.tgtDoc.id AS tgtDocId,
(SELECT b2.country, b2.note
FROM `conflictlogs`.`bucket1`.`app1logs` AS b2 USE KEYS b.srcDoc.id)[0] AS src_doc_fields,
(SELECT b3.country, b3.note
FROM `conflictlogs`.`bucket1`.`app1logs` AS b3 USE KEYS b.tgtDoc.id)[0] AS tgt_doc_fields
FROM `conflictlogs`.`bucket1`.`app1logs` AS b
WHERE META(b).id LIKE "crd%" AND b.timestamp BETWEEN "2025-06-04T18:15:16.363Z" AND "2025-06-09T07:26:40.326Z"
----

The query result is as follows:
----
[
   {
    "docId": "ae03ecde-203c-4a3b-a6d0-36b60f627c8a",
    "srcDocId": "src_1749454000005461807_e2f416ed317beb4f16a3587656b3d3450e1bec893cabebd3b9bb857d63824da4",
    "tgtDocId": "tgt_1749454000005461807_e2f416ed317beb4f16a3587656b3d3450e1bec893cabebd3b9bb857d63824da4",
    "src_doc_fields": {
        "country": "UK",
        “note”: “need review”
      },
    "tgt_doc_fields": {
        "country": "CA",
        “note”: “ok”
      } 
   }
]
----

NOTE: As the conflict log documents won’t be replicated, if you need to replicate them, copy them into a different document.

[#using-eventing-for-conflict-logs]
=== Using Eventing for Conflict Logs

The conflict logs and conflict documents are not replicated as XDCR’s special attribute (system xattrs called `_xdcr_conflict`) prevents replication:

----
"xattrs": {
    "_xdcr_conflict": true
    }
----

To force replicate the conflict logs and conflict documents, do the following:

. Use Eventing to copy the document to a new collection along with other modifications.

. Replicate the new document from the new collection.

You cannot update system xattrs, however, following is an example of an Eventing function you can deploy to combine the `crd_`, `src_`, and `tgt_` documents into one new document that does not have the system attribute.
Here, it is assumed that the documents are small.
If the documents are large, then you can copy only the relevant fields from the `src` and `tgt` documents to a single document.

[#eventing-example-clog]
==== Eventing example

This is an Eventing function example to copy the conflict log documents into a single new document.

Eventing bucket alias:  `src` for `conflictlogs._default.bucket1logs` with read only access.

Eventing bucket alias: `copy` for `conflictlogs._default.bucket1logs_copy` with read/write access.

[source,javascript]
----
function OnUpdate(doc, meta, xattrs) {
    if (meta.id.startsWith("crd_") === true)
    {
    log("crd doc created/updated", meta.id);

    //get the conflict source and target document id's
    var suffix = (meta.id).substring(4);
    var srcId = "src_" + suffix;
    var tgtId = "tgt_" + suffix;

    //read the conflicting source and target documents
    var src_doc = src[srcId];
    var tgt_doc = src[tgtId];

    //add the conflicting source and target documents to the crd doc
    doc["src_doc"] = src_doc;
    doc["tgt_doc"] = tgt_doc;

    //copy the resulting new crd doc to a different collection
    copy[meta.id] = doc;
    }
}
----

Resultant document example:

NOTE: See xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#conflict-record-document-format[Conflict Record Document Format] to understand the document format.

----
{
  "timestamp": "2025-05-20T19:25:55.308Z",
  "id": "crd_1747769155308581666_c0468a42632daabce649b1fb7e174a530946c04b1dde75218290c4885ad11669",
  "docId": "ASHUNK100",
  "replId": "1bc375a26b7f822ebe91288c58a6c614/bucket1/bucket1-PN8-oFADADCOe6S6A8YuIw==",
  "srcDoc": {
    "id": "src_1747769155308581666_c0468a42632daabce649b1fb7e174a530946c04b1dde75218290c4885ad11669",
    "nodeId": "127.0.0.1",
    "bucketUUID": "6cd3a35ba2d337d84d4fcd30c3a46fb9",
    "clusterUUID": "d976db26a5ce512a243db65a3026073f",
    "isDeleted": false,
    "collection": "_default",
    "scope": "_default",
    "expiry": 0,
    "flags": 33554438,
    "cas": 1747769124557291500,
    "revSeqno": 4,
    "xattrs": {
      "_vv": "{\"cvCas\":\"0x00002a1777524118\",\"src\":\"ntR6bcR9VHcjcPpQ5osEiw\",\"ver\":\"0x00002a1777524118\",\"pv\":[\"000018fe76524118@8DdrZBqHaACpmDeYJIv+kg\"]}",
      "_sync": "",
      "_mou": ""
    }
  },
  "tgtDoc": {
    "id": "tgt_1747769155308581666_c0468a42632daabce649b1fb7e174a530946c04b1dde75218290c4885ad11669",
    "nodeId": "34.213.22.102",
    "bucketUUID": "fada12469f1027ecb078d2c19a2802fb",
    "clusterUUID": "1bc375a26b7f822ebe91288c58a6c614",
    "isDeleted": false,
    "collection": "_default",
    "scope": "_default",
    "expiry": 0,
    "flags": 33554438,
    "cas": 1747769104359030800,
    "revSeqno": 4,
    "xattrs": {
      "_vv": "{\"cvCas\":\"0x000018fe76524118\",\"src\":\"8DdrZBqHaACpmDeYJIv+kg\",\"ver\":\"0x000018fe76524118\"}",
      "_sync": "",
      "_mou": ""
    }
  },
  "src_doc": {
    "author": "Unknown",
    "create_date_utc": "2025-05-20T07:56:26",
    "res_from": "WEST",
    "res_name": "Harry West",
    "res_note": "visitor -- HJV NOTE EAST",
    "reserved": true,
    "title": "Ashmole 782",
    "type": "book",
    "unix_time": "1747768801",
    "update_date_utc": "2025-05-20T19:20:01"
  },
  "tgt_doc": {
    "author": "Unknown",
    "create_date_utc": "2025-05-20T07:56:26",
    "res_from": "WEST",
    "res_name": "Harry West",
    "res_note": "visitor -- HJV NOTE WEST",
    "reserved": true,
    "title": "Ashmole 782",
    "type": "book",
    "unix_time": "1747768801",
    "update_date_utc": "2025-05-20T19:20:01"
  }
}
----

[#using-kv-range-scan-clog]
=== Using KV Range Scan

To use only KV, use Couchbase SDK with KV APIs including xref:8.0@server:howtos/kv-operations.adoc#kv-range-scan[KV Range Scan].

For example, to get a list of all `crd` prefix documents (CRD documents) using the KV Range Scan xref:8.0@server:howtos/kv-operations.adoc#kv-range-scan-prefix[PrefixScan], use KV `collection.get` to get the conflicting `src` and `tgt` docs.
You can also use KV sub-document API `lookupIn` to retrieve only the selected fields.
After processing the documents, you can remove the conflict log documents using the KV `collection.remove`.

For more information about KV Range Scan operations and data operations, see xref:8.0@server:howtos/kv-operations.adoc[Data Operations]. For more information about data operations on sub-documents, see xref:8.0@server:howtos/subdocument-operations.adoc[Sub-Document Operations].

[#xdcr-kv-range-scan-examples]
==== KV Range Scan examples

The following example uses Couchbase Python SDK.

[source,python]
----
from datetime import timedelta
import json

from couchbase.auth import PasswordAuthenticator
from couchbase.cluster import Cluster
from couchbase.collection import (GetOptions, RemoveOptions)
from couchbase.collection import DeltaValue, SignedInt64
from couchbase.exceptions import (
    CouchbaseException,
    PathNotFoundException,
    SubdocPathMismatchException)
from couchbase.options import ScanOptions
from couchbase.kv_range_scan import PrefixScan
import couchbase.subdocument as SD

# connection info
connection_string = "couchbase://localhost"
username = "username1"
password = "Some!password"

# conflict logs collection location
bucket_name = "conflictlogs"
scope_name = "bucket1"
collection_name = "app1logs"

cluster = Cluster(
    connection_string,
    authenticator=PasswordAuthenticator(username, password));

cluster.wait_until_ready(timedelta(seconds=5))
cb = cluster.bucket(bucket_name);
logs_coll = cb.scope(scope_name).collection(collection_name)

# Using KV PrefixScan to get list of crd doc ids
# Get crd document ids only
crd_list = logs_coll.scan(PrefixScan('crd'), ScanOptions(ids_only=True))

# For each crd document, get the docId, timestamp, srcDoc.id, tgtDoc.id
# Then, get the src and tgt docs from the conflict log collection
for crd in crd_list:
 crdlookup = logs_coll.lookup_in(crd.id,
                    [ SD.get("docId"),
                      SD.get("timestamp"),
                      SD.get("srcDoc.id"),
                      SD.get("tgtDoc.id") ])

 doc_id = crdlookup.content_as[str](0)
 timestamp = crdlookup.content_as[str](1)
 src_doc_id = crdlookup.content_as[str](2)
 tgt_doc_id = crdlookup.content_as[str](3)

 # Get the src and tgt documents in conflict
 src_doc = logs_coll.get(src_doc_id);
 tgt_doc = logs_coll.get(tgt_doc_id);

 # Print the info as json
 output = { "docId": doc_id, "log_timestamp": timestamp,
            "src_doc": src_doc.content_as[dict],
            "tgt_doc": tgt_doc.content_as[dict] }
 print (json.dumps(output))
----

[replication-continuation]
== Replication Continuation

After you resolve conflicts and xref:n1ql:n1ql-language-reference/upsert.adoc[upsert] the documents, you can continue the replication process without data loss, through xref:learn:clusters-and-availability/xdcr-conflict-resolution.adoc#revision-id-based-conflict-resolution[Sequence number-based Conflict Resolution] or xref:learn:clusters-and-availability/xdcr-conflict-resolution.adoc#timestamp-based-conflict-resolution[Timestamp-based Conflict Resolution].

[#disable-conflict-logging]
== Disable XDCR Conflict Logging

This section explains disabling XDCR Conflict Logging feature.

* *HLV*: The bucket property `enableCrossClusterVersioning` cannot be disabled once it is enabled.
For more information, see xref:learn:clusters-and-availability/xdcr-enable-crossclusterversioning.adoc[XDCR enableCrossClusterVersioning].
Enabling HLV depends on `enableCrossClusterVersioning`, so HLV also cannot be disabled after it is enabled.

* *Setting the replication setting off*: Set the `conflictLogging` parameter to `{}` or `{ "disabled": true }` because an empty JSON object value must be specified to disable the Conflict Logging capability of XDCR.
+
For configuration information, see xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc#use-conflictlogging-and-loggingrules[Use conflictLogging and loggingRules].
When it is disabled, any conflict documents previously created by XDCR in the conflict collections remain in place.

* *Deleting a Replication*: When you delete a replication, conflict record documents in the conflict collection remain until you manually delete them.
As you can change the conflict collection multiple times during the lifecycle of a replication, XDCR does not automatically clean up previously created conflict records.

[#conflict-logging-errors]
== Conflict Logging Error Scenarios

This section explains errors and their causes that may occur during the conflict logging process.

[#error-source-side-network-partition]
=== Source-Side Network Partition

A network partition on the source side can prevent XDCR from reading or writing to the conflict collection if the transaction mode is enabled.
The following scenarios may occur:

* *Replication Creation/Change/Deletion*: If you create a replication and specify a conflict collection, the operation fails during a network partition.
However, by design, replication of conflict collection is not supported by XDCR.
So, replication creation would fail under these conditions regardless.
+
Any replication change during a network partition is not recommended, as metakv may also encounter issues.
Problems with accessing the conflict collection during a network partition may not introduce new issues but may prevent some conflicts from being logged.

* *Live Replication*: Standard XDCR replication is generally not affected by a source-side network partition.
However, certain features, such as Peer-to-Peer protocols used for checkpoint migration may be impacted.

[#error-conflict-collection-quota]
=== Conflict Collection Usage Quota

If the bucket containing the conflict collection reaches its quota and cannot accept more data, for example, if the Resident Ratio guardrail is triggered, XDCR cannot log conflicts but the replication continues.
This approach is intended to prioritize continued replication and maintain High Availability, even if some conflict events are not logged.

[#error-handling-conflict-logging]
=== Error Handling

In all error scenarios described above, XDCR makes a best-effort attempt to record the conflict document.
If logging fails, XDCR advances the sequence number to continue processing replication.
