= System Events
:description: Couchbase Server logs system events for the cluster, and allows their retrieval.

[abstract]
{description}

== Understanding System Events

_System events_ are generated to record significant occurrences on the cluster.
Events are provided by the Cluster Manager, the Data Service, the Index Service, the Search Service, the Eventing Service, the Backup Service, and the Analytics Service.
Events are also provided to cover security and Views.

Each event is provided as a JSON document containing a number of key-value pairs: some keys are included in all system events, others are specific to the service that generates the event.
Each system event that a service generates is of a certain _type_; and this is indicated by an _ID_ and a _description_.
Informationally, system events are considered to be at different levels of _severity_: supported levels are _info_, _warn_, _error_, and _fatal_.

The goal of system-event generation is to provide users with a clear account of what occurs on the cluster: however, system events are not intended to provide detailed, diagnostic information.

System events are recorded in a _system log_, which is maintained by the Cluster Manager.
Each node in the cluster has a copy of the system log; and each log is kept up to date by means of _gossip-replication_, between the nodes.
(See xref:learn:clusters-and-availability/metadata-management.adoc[Metadata Management], for information on gossip-replication.)

System events can be retrieved from the system log by means of the REST API.
Two methods of retrieval are supported:

* _Batch_ retrieval.
Either all events or a specified number are retrieved in a single array, either from the beginning of the system log or from a specified time.

* _Dynamic retrieval_.
Each event is returned as it happens.

For detailed information, see xref:rest-api:rest-get-system-events.adoc[Getting System Events].

Note that system events are different from, and should not be confused with, two other facilities provided by Couchbase Server:

* _Auditing_.
Audit events are generated by Couchbase Server to maintain a record of security-related occurrences across the cluster.
For information, see xref:learn:security/auditing.adoc[Auditing].

* _Logging_.
This provides a series of _per node_ log files, which are concatenated by different services, to maintain an account of service activities and consequences, and other incidents.
For information, see xref:manage:manage-logging/manage-logging.adoc[Manage Logging].

== System-Event Structure

Every system event always contains the following fields.

[options="header", cols="2,2,7"]
|===

| Field | Value Type | Description

| timestamp | string | Date and time of the event in UTC iso-8601 format, which is `YYYY-MM-DDThh:mm:ss:SSSZ`.
For more information, see https://www.w3.org/TR/NOTE-datetime[Date and Time Formats^].

| component | string | Name of the service generating the event.
This can be `ns_server`, `query`, `indexing`, `search`, `eventing`, `analytics`, `backup`, `xdcr`, `data`, `security`, or `views`.

| severity | string | The degree of significance of the type of occurrence.
This can be `info`, `warn`, `error`, or `fatal`.

| id | unsigned integer | The identifier for the type of occurrence.
For example, whenever a bucket is created, the Data Service generates a `Bucket created` event, whose id `8192`.

| description | string | The description of the type of occurrence.
For example, whenever a bucket is created, the Data Service generates an event whose description is `Bucket created`.

| uuid | string | A universally unique identifier provided for each specific instance of an occurrence-type.
For example, if two buckets are created, two `Bucket created` events are generated by the Data Service, both with the id `8192`, and each with its own uuid.

|===

Note that all system events contain additional fields that are specific to the service that is generating the event.
