= XDCR Filtering Expressions

[abstract]
_XDCR filtering expressions_ allow documents' fields and values to be specified, so as to determine which documents are included in a filtered replication.

[#understanding-filtering-expressions]
== Understanding Filtering Expressions

The expressions provided to support XDCR Advanced Filtering allow documents' fields and values to be specified.
This includes each document's:

* _ID_

* _Meta-data_ field-names and values, nested to any degree

* _Data_ field-names and values, nested to any degree

Special syntax is provided, to allow _ID_ and _meta-data_ to be specified.

Each document that provides a match on the specified expression is included in the filtered replication.

XDCR filtering expressions constitute a subset of _N1QL_ expressions, with some additions.
The sections below list the available XDCR filtering expressions, and provide links to documentation for the comparable N1QL expressions where appropriate.

XDCR Advanced Filtering can be managed by means of Couchbase Web Console (see xref:manage:manage-xdcr/filter-xdcr-replication.adoc[Filter a Replication]), the CLI (see xref:cli:cbcli/couchbase-cli-xdcr-replicate.adoc[xdcr-replicate]), and the REST API (see xref:rest-api:rest-xdcr-create-replication.adoc[Creating XDCR Replications]).

Sections on this page list the available expressions, and provide examples of their usage.
The concluding section expresses the relationships between expressions in BNF (_Backus-Naur Form_) notation.

[#list-of-filtering-expressions]
== List of Filtering Expressions

The available filtering expressions are listed in the following subsections.
Note that examples assume that the `travel-sample` bucket is the source of the filtered replication.

[#pattern-matching]
=== Pattern Matching

Pattern matching is supported with the following syntax:

[cols="1"]
|===
| `REGEXP_CONTAINS` (_expression_, _pattern_)
|===

For example, the following expression specifies `country` as the _expression_, and `"France"` as the pattern:

----
REGEXP_CONTAINS(country, "France")
----

If `travel-sample` is used as the source bucket, every document that contains a field `country` whose value is `"France"` is replicated to the target.
For example, this would include the document `airline_1191`:

----
{
  "callsign": "REUNION",
  "country": "France",
  "iata": "UU",
  "icao": "REU",
  "id": 1191,
  "name": "Air Austral",
  "type": "airline"
}
----


[#mata-data-access]
==== Meta-Data Access

[#lookahead]
==== Lookahead

[#checking-for-existence]
=== Checking for Existence

[#using-logical-operators]
=== Using Logical Operators

[#using-comparison-operators]
=== Using Comparison Operators

[#using-arithmetic-operators]
=== Using Arithmetic Operators

[#selecting-fields-and-elements]
=== Selecting Fields and Elements

[#handling-dates]
=== Handling Dates

[#filtering-expression-bnf]
== Filtering Expression BNF

The relationships between available expressions for XDCR Advanced Filtering are expressed in the following table, in _Backus-Naur Form_.

[cols="4,5"]
|===
| Expression | Is Equal To

| AndCondition
| { OpenParens } Condition { "AND" Condition } { CloseParen }

| Condition
| ( [ "NOT" ] Condition ) | Operand

| Operand
| BooleanExpr | ( LHS ( CheckOp | ( CompareOp RHS) ) )

| BooleanExpr
| Boolean | BooleanFuncExpr

| LHS
| ConstFuncExpr | Boolean | Field | Value

| RHS
| ConstFuncExpr | Boolean | Value | Field

| CompareOp
| "=" | "==" | "<>" | "!=" | ">" | ">=" | "<" | "<="

| CheckOp
| ( "IS" [ "NOT" ] ( NULL | MISSING ) )

| Field
| { @"-" } OnePath { "." OnePath } { MathOp MathValue }

| OnePath
| ( PathFuncExpression | StringType ){ ArrayIndex }

| StringType
| @String | @Ident | @RawString | @Char

| ArrayIndex
| "[" @Int "]"

| Value
| @String

| ConstFuncExpr
| ConstFuncNoArg | ConstFuncOneArg | ConstFuncTwoArgs

| ConstFuncNoArg
| ConstFuncNoArgName "(" ")"

| ConstFuncNoArgName
| "PI" | "E"

| ConstFuncOneArg
| ConstFuncOneArgName "(" ConstFuncArgument ")"

| ConstFuncOneArgName
| "ABS" | "ACOS"...

| ConstFuncTwoArgs
| ConstFuncTwoArgsName "(" ConstFuncArgument "," ConstFuncArgument ")"

| ConstFuncTwoArgsName
| "ATAN2" | "POW"

| ConstFuncArgument
| Field | Value | ConstFuncExpr

| ConstFuncArgumentRHS
| Value

| PathFuncExpression
| OnePathFuncNoArg

| OnePathFuncNoArg
| OnePathFuncNoArgName "(" ")"

| MathOp
| @"+" | @"-" | @"*" | @"/" | @"%"

| MathValue
| @Int | @Float

| OnePathFuncNoArgName
| "META"

| BooleanFuncExpr
| BooleanFuncTwoArgs | ExistsClause
|===
