= XDCR Cloud Deployment
:page-aliases install:deployments-xdcr

[abstract]
XDCR can be used to replicate data between cloud-deployed clusters.

[#cloud-based-replication]
== Cloud-Based Replication
When configuring replication between two or more clusters deployed in the cloud,
the following requirements apply:

Use public names and addresses::
Public DNS names and IP addresses can be used for cloud-based cluster-nodes.
Within the cloud deployment-environment, each public IP address is
resolved internally within the cluster, but nevertheless allows
external communication.

When using Amazon EC2, make sure that:

* The public interface is enabled in the instance configuration.
* Security parameters allow communication to the required ports.
* The public DNS record exposed by Amazon is used as the reference name.

Configure the cluster with a fixed IP address, and configure
the public DNS name
according to the recommendations for using Couchbase Server in the cloud.

Use a DNS service::
Use a DNS service to identify or register a `CNAME` that points to the public
DNS address of each node within the cluster.

The `CNAME` will be constant, even though the underlying public DNS address may
change within the cloud service.
The `CNAME` record entry can then be used as the destination IP address, when
configuring replication between the clusters using XDCR.

If a transient failure causes the public DNS address for a given cluster-node
to change, update the `CNAME` to point to the updated public DNS address
provided by the cloud service.
When the `CNAME` records are updated, replication should be able to persist
over a public, internet-based connection, even though the individual IP
addresses of
cluster nodes have been referenced in XDCR configuration.

For additional security, configure security groups to allow
traffic only on the required ports between the IP addresses for each cluster.
To configure security groups, specify the inbound port and IP address-range.
Ensure that the security configuration includes the correct
port and IP addresses
for the other cluster-nodes, so that communication between them can occur.
