= XDCR enableCrossClusterVersioning
:description: pass:q[Enabling Cross Cluster Versioning allows XDCR to add metadata to each replicated document.]

[abstract]
{description}


Enabling Cross Cluster Versioning for all buckets in the replication topology is a pre-requisite for some XDCR features. The bucket property `enableCrossClusterVersioning` cannot be disabled once it is set to `true`. Therefore, you must not enable `enableCrossClusterVersioning` casually.

When you set the bucket property `enableCrossClusterVersioning` (ECCV) to `true`, for each document processed by XDCR, XDCR stores additional metadata for the document in the extended attributes. This metadata is also called Hybrid Logical Vector (HLV), which is a set of Hybrid Logical Clock (HLC) information.

[#hlv-data-maintained-in-xattr]
== Hybrid Logical Vector (HLV) data maintained in the extended attributes

The new metadata, HLV, is stored as a system created extended attribute (xattr) called `_vv` (`xattrs._vv`). The HLV metadata is also called Version Vectors.

The HLV metadata takes up `109 + 40N` bytes of space per document, where N is the number of buckets mutating the document in the replication topology. 

NOTE: As long as your replication topology is constant, the size of the HLV metadata will grow to 109 + 40N and remain constant. However, the HLV data accumulation occurs when the replication topology changes and the document copy goes through different clusters, for example, when being restored to a new cluster.

To remove the accumulated or outdated HLV data, the HLV metadata is pruned periodically. You can control the pruning frequency by setting the bucket property `versionPruningWindowHrs`.

[#remove-hlv-metadata]
=== Remove HLV metadata

After enabling, you cannot disable the bucket property `enableCrossClusterVersioning`. You can, however, backup and restore the data to a bucket where `enableCrossClusterVersioning` is set to `false`, and remove the xattr information added by XDCR using the option `cbbackupmgr restore --disable-hlv`. 

NOTE: To remove the on-going maintenance of HLV information, you must remove the xattr information previously added to the documents. To completely remove the effects of enabling HLV, only restoring the data to a bucket where `enableCrossClusterVersioning` is set to `false` is not enough.

[#modify-enablecrossclusterversioning]
== Modify the bucket property enableCrossClusterVersioning

You can modify the bucket property `enableCrossClusterVersioning` through REST API. For information about modifying `enableCrossClusterVersioning` through REST API, see xref:rest-api:rest-bucket-create.adoc#example-enablecrossclusterversioning-edit[Example: Turning on enableCrossClusterVersioning, when Editing].

NOTE: You cannot enable the bucket property `enableCrossClusterVersioning` while creating the bucket.

[#version-pruning-window-hrs]
== versionPruningWindowHrs

`versionPruningWindowHrs` is a bucket property, which controls the pruning frequency of the HLV metadata. The default value of versionPruningWindowHrs is 720 hours (30 days), which means that any HLV data older than 720 hours is pruned to remove the outdated entries. 

NOTE: `versionPruningWindowHrs` must be set to the same value for all buckets in an XDCR replication topology.

[#manage-version-pruning-window-hrs]
=== Manage the bucket property versionPruningWindowHrs

For information about modifying the bucket property `versionPruningWindowHrs` through REST API, see xref:rest-api:rest-bucket-create.adoc#example-versionpruningwindowhrs-edit[Example: Specifying time value for versionPruningWindowHrs, when Editing].

[#features-requiring-crossclusterversioning-enabled]
== Features for which Cross Cluster Versioning must be enabled

The bi-directional, active-active replication with Sync Gateway 4.0+ and XDCR requires enabling Cross Cluster Versioning. For more information, including important limitations, see xref:learn:clusters-and-availability/xdcr-active-active-sgw.adoc[XDCR Active-Active with Sync Gateway].
