/* Data Control Language */

dcl-statement ::= grant
                | revoke

/* tag::grant[] */
grant ::= 'GRANT' role ( ',' role )* ( 'ON' keyspace-ref ( ',' keyspace-ref )* )?
          'TO' user ( ',' user )*
/* end::grant[] */

/* tag::revoke[] */
revoke ::= 'REVOKE' role ( ',' role )* ( 'ON' keyspace-ref ( ',' keyspace-ref )* )?
           'FROM' user ( ',' user )*
/* end::revoke[] */

role ::= identifier
user ::= identifier