expr ::= literal |
         identifier |
         arithmetic-term |
         comparison-term |
         concatenation-term |
         logical-term |
         case-expr |
         collection-expr |
         construction-expr |
         nested-expr |
         function-call | /* inc window function */
         subquery-expr |
         '(' expr ')'

logical-term ::= and |
                 or |
                 not

/* tag::and[] */
and ::= condition 'AND' condition
/* end::and[] */

/* tag::or[] */
or ::= condition 'OR' condition
/* end::or[] */

/* tag::not[] */
not ::= 'NOT' condition
/* end::not[] */