/* Transaction Control Language */

tcl-statement ::= begin-transaction
                | set-transaction
                | savepoint
                | rollback-transaction
                | commit-transaction

/* tag::begin-transaction[] */
begin-transaction ::= ( 'BEGIN' | 'START' ) ( 'WORK' | 'TRAN' | 'TRANSACTION' )
                      ( 'ISOLATION' 'LEVEL' 'READ' 'COMMITTED' )?
/* end::begin-transaction[] */

/* tag::set-transaction[] */
set-transaction ::= 'SET' 'TRANSACTION' 'ISOLATION' 'LEVEL' 'READ' 'COMMITTED'
/* end::set-transaction[] */

/* tag::savepoint[] */
savepoint ::= 'SAVEPOINT' savepointname
/* end::savepoint[] */

/* tag::rollback-transaction[] */
rollback-transaction ::= 'ROLLBACK' ( 'WORK' | 'TRAN' | 'TRANSACTION' )?
                       ( 'TO' 'SAVEPOINT' savepointname )?
/* end::rollback-transaction[] */

/* tag::commit-transaction[] */
commit-transaction ::= 'COMMIT' ( 'WORK' | 'TRAN' | 'TRANSACTION' )?
/* end::commit-transaction[] */

savepointname ::= identifier