/* Utility Statements */

utility-statement ::= advise
                    | explain
                    | infer
                    | prepare
                    | execute
                    | update-statistics

/* tag::advise[] */
advise ::= 'ADVISE' 'INDEX'? ( select | update | delete | merge )
/* end::advise[] */

/* tag::explain[] */
explain ::= 'EXPLAIN' statement
/* end::explain[] */

/* tag::infer[] */
infer ::= 'INFER' ( 'COLLECTION' | 'KEYSPACE' )? keyspace-ref ( 'WITH' options )?
/* end::infer[] */

options ::= object-constructor

/***********************
 * Prepared Statements *
 ***********************/

/* tag::prepare[] */
prepare ::= 'PREPARE' 'FORCE'? ( name ( 'FROM' | 'AS' ) )? statement
/* end::prepare[] */

/* tag::execute[] */
execute ::= 'EXECUTE' name ( 'USING' parameters )?
/* end::execute[] */

name ::= identifier
parameters ::= array-constructor | object-constructor