// tag::multiple-references[]
[plantuml, subs="attributes"]
....
@startuml

package "my-library" {
  [getBusinessDays(startDate,endDate)] as jsGBDFunction
  [add(x,y)]
  
}

[{sqlpp} function: GetBusinessDays('02 January 2022',\n '31 January 2023')] --> jsGBDFunction : references
[{sqlpp} function: GetWeekDays('02/14/2022', '4/16/2022')] --> jsGBDFunction : references

@enduml
....
// end::multiple-references[]


// tag::inline-call-sequence[]
[plantuml, subs="attributes"]
....
@startuml
 
 actor Dev
 participant JSEngine
 participant QueryEngine
 database Bucket
 
 Dev ->> JSEngine: JS: var q = select …
 activate JSEngine
 JSEngine ->> QueryEngine : N1QL(…) call
 activate QueryEngine
 QueryEngine ->> JSEngine  : return query
 deactivate QueryEngine
 JSEngine ->> Dev : return q
 deactivate JSEngine

    loop Every document in q
      Dev ->> JSEngine   : operate on document
      JSEngine ->> QueryEngine ++ : get document
      QueryEngine ->> Bucket ++ : get document
      Bucket ->> QueryEngine -- : retrieved document
      QueryEngine ->> JSEngine -- : retrieved document
    end
@enduml
....
// end::inline-call-sequence[]

// tag::data-transformation[]
[plantuml, subs="attributes"]
....
@startuml

skinparam componentStyle rectangle

left to right direction

[Run {sqlpp} statement] --> [Transform JSON data] : {item1, item2, item3}
[Transform JSON data] -->  return  : {item1, item3}

@enduml
....
// end::data-transformation[]

// tag::transactions-and-iterators[]
[plantuml, subs="attributes"]
....
@startuml

start

:start transaction;
note right: Transaction started before initial\n{sqlpp} statement is called
: var q = execute {sqlpp} statement;
 
 while (next q?) is (yes)
 
   : process q;
   
 endwhile (no)
 
:commit or rollback;

stop

@enduml
....
// end::transactions-and-iterators[]

// tag::udf-scopes-diagram[]
[plantuml]
----
@startuml

skinparam monochrome true
allow_mixing

package MyLibrary {
   file "getBusinessDays(startDate, \nendDate)" as getBusinessDays
}
 
actor "user" as user

node "Couchbase cluster" as cluster

database "Bucket" as bucket

rectangle "Inventory Scope" as inventory
rectangle "Tenant Scope" as tenant

folder "Collection" as collection


file "Document 1" as document1
file "Document 2" as document2
file "Document 3" as document3

cluster -- bucket
bucket -- inventory
bucket -- tenant
inventory -- collection
collection -- document1
collection -- document2
collection -- document3

inventory --- MyLibrary

user ---> MyLibrary

note left of user
  User can access the getBusinessDays function
  as long as s/he is working 
  inside the '"Inventory Scope" context
end note
@enduml
----
// end::udf-scopes-diagram[]

