// tag::multiple-references[]
[plantuml, subs="attributes"]
....
@startuml

package "my-library" {
  [getBusinessDays(startDate,endDate)] as jsGBDFunction
  [add(x,y)]
  
}

[{sqlpp} function: GetBusinessDays('02 January 2022',\n '31 January 2023')] --> jsGBDFunction : references
[{sqlpp} function: GetWeekDays('02/14/2022', '4/16/2022')] --> jsGBDFunction : references

@enduml
....
// end::multiple-references[]


// tag::inline-call-sequence[]
[plantuml, subs="attributes"]
....
@startuml
 
 actor Dev
 participant JSEngine
 participant QueryEngine
 database Bucket
 
 Dev ->> JSEngine: JS: var q = select …
 activate JSEngine
 JSEngine ->> QueryEngine : N1QL(…) call
 activate QueryEngine
 QueryEngine ->> JSEngine  : return query
 deactivate QueryEngine
 JSEngine ->> Dev : return q
 deactivate JSEngine

    loop Every document in q
      Dev ->> JSEngine   : operate on document
      JSEngine ->> QueryEngine ++ : get document
      QueryEngine ->> Bucket ++ : get document
      Bucket ->> QueryEngine -- : retrieved document
      QueryEngine ->> JSEngine -- : retrieved document
    end
@enduml
....
// end::inline-call-sequence[]

// tag::data-transformation[]
[plantuml, subs="attributes"]
....
@startuml

skinparam componentStyle rectangle

left to right direction

[Run {sqlpp} statement] --> [Transform JSON data] : {item1, item2, item3}
[Transform JSON data] -->  return  : {item1, item3}

@enduml
....
// end::data-transformation[]

// tag::transactions-and-iterators[]
[plantuml, subs="attributes"]
....
@startuml

start

:start transaction;
note right: Transaction started before initial\n{sqlpp} statement is called
: var q = execute {sqlpp} statement;
 
 while (next q?) is (yes)
 
   : process q;
   
 endwhile (no)
 
:commit or rollback;

stop

@enduml
....
// end::transactions-and-iterators[]

// tag::udf-scopes-diagram[]
[plantuml]
----
@startuml

skinparam monochrome true
allow_mixing

package "my-library" as MyLibrary {
   file "getBusinessDays(startDate, \nendDate)" as getBusinessDays
}
 
actor "user" as user

node "Couchbase cluster" as cluster

database "travel-sample" as bucket

rectangle "inventory scope" as inventory
rectangle "tenant scope" as tenant


cluster -- bucket
bucket -- inventory
bucket -- tenant

inventory --- MyLibrary

user ---right---> MyLibrary

note top of user
  can access the getBusinessDays function
  as long as s/he is working 
  inside the '"Inventory Scope" context
end note

@enduml
----
// end::udf-scopes-diagram[]

