= cbq: The Command Line Shell for N1QL

[abstract]
[.cmd]`cbq` is a comprehensive new command line shell for N1QL.
It is a powerful, developer friendly tool that enables you to query and update data from Couchbase Server.
The cbq shell enables you to perform all the operations that are supported by the Query REST API and more, such as additional scripting functionality.

The cbq shell executable, [.cmd]`cbq`, is available in your applications directory.
For example on Mac OS, [.path]_/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin_.

The cbq shell interface accepts both shell commands as well as N1QL commands.
All the cbq shell commands start with a back-slash (\).
If the command does not start with a back-slash (\), the cbq shell interprets the command as a N1QL command.

When starting the cbq shell you can provide a set of command line options.
If no options are present then it assumes default values for expected options.

NOTE: The cbq shell commands are case insensitive.
However, the command line option are case sensitive.

For the complete list of command line options and shell commands, see tables <<table_a3h_rhz_dw>> and <<table_htk_hgc_fw>>.

The cbq shell enables you to manipulate parameters based on the REST API.
See <<cbq-parameter-manipulation>> for details.

*Executing a Single Command*

You can use the [.param]`--script` option to execute a single N1QL query and exit the shell:

----
./cbq --script="select \* from \`travel-sample\` LIMIT 1"
----

.Results
----
Connected to : http://localhost:8091/. Type Ctrl-D to exit.
{
    ...
}
----

*Support for Multi-line Queries*

The cbq shell supports multi-line queries by default, enabling you to enter a query over multiple lines.
When entering a query, you can hit Enter without specifying a semi-colon (;) at the end of the line to move the cursor to the next line.
The prompt ">" indicates that the shell is in multi-line mode.
For example:

----
cbq> select *
> from `travel-sample`
> LIMIT 1;
----

When you're done, use a semi-colon ";" to indicate the end of the query, and then Enter key to execute the query.

*Handling Comments*

You can add comments in your query by preceding the comment with a '&#35;' or '--'.
The cbq shell interprets a line that starts with '&#35;' or '--' as a comment, logs the line into history, and returns a new prompt.
No other action is taken.

----
cbq> select *
 > #This is the first comment
 > from `travel-sample`
 > --This is the second comment
 > LIMIT 1;
----

However, if a comment exists within a statement, it is considered as part of the N1QL command.
If the cbq shell encounters a block comment (enclosed between /* \... */) within a statement, it sends the block comment to the query service.

----
cbq> select * from `travel-sample` /* This statement includes a block comment */ LIMIT 1;
----

*File Based Operations*

The cbq shell can execute N1QL and shell commands contained in files using file-based commands and options.
See <<cbq-file-based-ops>> for more information.

*History*

The [.cmd]`cbq` shell stores the history for every session.
All the commands executed in a session are stored in history.
By default, history is stored in [.path]_~/.cbq_history_.
You can change the name of the file using the SET command to set the predefined parameter [.var]`HISTFILE`.

----
\SET HISTFILE filename;
----

By default, all the commands are stored in the specified file.
You can scroll through history and retrieve the commands from history using the scrolling arrow keys.
Once the query is on the command prompt, you can edit it before executing the updated query.

*Exit Status*

The cbq shell returns the exit status 0 for successful exit with no errors and 1 if an error was encountered before exiting.

*Exit On Error*

When you specify the argument `--exit-on-error`, the cbq shell checks the result returned after executing the query for any error and exits when the first error is encountered.

*Help*

Help displays the help information for the shell commands and for the general usage of cbq.
Use the help option when bringing up the shell to display the information for all available options:

 $ ./cbq -h
 $ ./cbq --help

Use the [.cmd]`\HELP` shell command during a session to display information for specific shell commands.
If you specify one or more commands, the shell displays the usage information for the specified commands.

----
cbq> \HELP command-name;
----

If you do not specify a command, the cbq shell lists all the commands for which syntax help is available.

----
cbq> \HELP;
----

== Available Command Line Options and Shell Commands

.Command Line Options for cbq Shell
[#table_a3h_rhz_dw,cols="1,1,1,4"]
|===
| Option | Arguments | Default Value | Description and Examples

| `-e`

`--engine`
| <[.var]``url``>
| `+http://localhost:8091+`
a|
The connection string consists of a protocol scheme followed by a host, including a port number to connect to the query service (8093) or the Couchbase cluster (8091).

The cbq shell supports [.path]_http://_, [.path]_https://_, [.path]_couchbase://_ and [.path]_couchbases://_ protocol schemes.
When using the [.path]_couchbase://_ or [.path]_couchbases://_ protocol schemes, you need not specify the port when connecting to the Couchbase cluster.

Shell command: <<cbq-connect,\CONNECT>>

*Examples*

 $ ./cbq -e couchbase://localhost

 $ ./cbq --engine http://localhost:8093

 $ ./cbq -e http://localhost:8091

.Result
----
Connected to : http://localhost:8091/. Type Ctrl-D or \QUIT to exit.
Path to history file for the shell : /Users/myuser1/.cbq_history
cbq>
----

| `-ne`

`--no-engine`
| None
| false
a|
The cbq shell does not connect to any query service.
You must explicitly connect to a query service using the [.cmd]`\CONNECT` shell command.

*Examples*

 $ ./cbq --no-engine

| `-q`

`--quiet`
| None
| false
a|
Enables or disables the startup connection message for the cbq shell.

*Examples*

 $ ./cbq -q -e http://localhost:8091

.Result
----
 cbq>
----

| `-b`

`--batch`
| None
| None
a|
This option is available only with Analytics service.
When invoked with the batch option, cbq sends the queries to server only when you hit EOF or \ to indicate the end of the batch input.

 $ ./cbq --batch

You can also set the batch mode in the interactive session using the following commands:

----
\set batch on
\set batch off
----

| `-t`

`--timeout`
| [.var]`value`
| None
a|
Sets the query timeout parameter.

*Examples*

 $ ./cbq -e http://localhost:8091 --timeout="1s"

| `-u`

`--user`
| [.var]`username`
| None
a|
Specifies a single user name to log in to Couchbase.
When used by itself, without the -p option to specify the password, you will be prompted for the password.

This option requires administration credentials and you cannot switch the credentials during a session.

Couchbase recommends using the `-u` and `-p` option if your password contains special characters such as #, $, %, &, (,), or '.

*Examples*

 $ ./cbq -e http://localhost:8091 -u=Administrator
                     Enter Password:

| `-p`

`--password`
| [.var]`password`
| None
a|
Specifies the password for the given user name.
You cannot use this option by itself.
It must be used with the -u option to specify the user name.

This option requires administration credentials and you cannot switch the credentials during a session.

Couchbase recommends using the `-u` and `-p` option if your password contains special characters such as #, $, %, &, (,), or '.

*Examples*

 $ ./cbq -e http://localhost:8091 -u=Administrator -p=password

| `-c`

`--credentials`
| [.var]`list of credentials`
| None
a|
Specify the login credentials in the form of [.var]`username`:[.var]``password``.
You can specify credentials for different buckets by separating them with a comma.

Shell command: <<cbq-set,\SET>> `-creds`

REST API: `-creds` parameter

*Examples*

 $ ./cbq -e http://localhost:8091 -c=beer-sample:password,Administrator:password

| `-v`

`--version`
| None
| false
a|
Provides the version of the cbq shell.
To display the query engine version of Couchbase Server (this is not the same as the version of Couchbase Server itself), use one of the following N1QL queries:

----
select version();
----

----
select min_version();
----

*Examples*

 $ ./cbq --version

.Result
----
 SHELL VERSION  : 1.5

                Use N1QL queries select version();
                or select min_version(); to display server version.
----

| `-h`

`--help`
| None
| None
a|
Provides help for the command line options.

Shell command: <<cbq-help,\HELP>>

*Examples*

 $ ./cbq --help

| `-s`

`-script`
| [.var]`query`
| None
a|
Provides a single command mode to execute a query from the command line.

You can also use multiple "-s" options on the command line.
If one of the commands is incorrect, an error is displayed for that command and cbq continues to execute the remaining commands.

*Examples*

[source,console]
----
$ ./cbq -s="select * from \`travel-sample\` limit 1"

$ ./cbq  -s="\SET v 1" -s="\SET b 2" -s="\PUSH b3" -s="\SET b 5" -s="\SET"  -ne
 Path to history file for the shell : /Users/isha/.cbq_history
 \PUSH b3
 ERROR 139 : Too few input arguments to command.
 Query Parameters :
 Named Parameters :
 User Defined Session Parameters :
 Predefined Session Parameters :
 Parameter name : v
 Value : [1]
 Parameter name : b
 Value : [5]
 Parameter name : histfile
 Value : [".cbq_history"]
 Parameter name : batch
 Value : ["off"]
----

| `-f`

`--file`
| [.var]`input-file`
| None
a|
Provides an input file which contains all the commands to be run.

Shell command: <<cbq-source,\SOURCE>>

 $ ./cbq --file="sample.txt"

| `-o`

`--output`
| [.var]`output-file`
| None
a|
Specifies an output file where the commands and their results are to be written.

Shell command: <<cbq-redirect,\REDIRECT>>

*Examples*

 $ ./cbq -o="results.txt" -s="select * from `travel-sample` limit 1"

| `--exit-on-error`
| None
| false
a|
Specifies that the cbq shell must exit when it encounters the first error.

*Examples*

 $ ./cbq --exit-on-error -f="sample.txt"

| `--no-ssl-verify` or

`-skip-verify`
| None
| false
a|
Specifies that cbq shell can skip the verification of certificates.

The default ports are 18091 and 18093.
You need not specify the port when connecting to the cluster.

*Examples*

 $ ./cbq --no-ssl-verify -f="sample.txt"
 $ ./cbq -skip-verify https://127.0.0.1:18091
|===

.cbq Shell Commands
[#table_htk_hgc_fw,cols="1,2,3"]
|===
| Shell Command | Arguments | Description and Examples

| [.cmd]`\CONNECT`
| [.var]`url`
a|
Connects cbq shell to the specified query engine or Couchbase cluster.

The connection string consists of a protocol scheme followed by a host, including a port number to connect to the query service (8093) or the Couchbase cluster (8091).

The cbq shell supports [.path]_http://_, [.path]_https://_, [.path]_couchbase://_ and [.path]_couchbases://_ protocol schemes.
When using the [.path]_couchbase://_ or [.path]_couchbases://_ protocol schemes, you need not specify the port when connecting to the Couchbase cluster.

Command Line Option: `-e` or `--engine`

*Example*

----
cbq> \CONNECT http://localhost:8093;
----

| [.cmd]`\DISCONNECT`
| None
a|
Disconnects the cbq shell from the query service or cluster endpoint.

*Example*

----
cbq> \DISCONNECT;

 Couchbase query shell not connected to any endpoint.
 Use \CONNECT command to connect.
----

| [.cmd]`\EXIT`

[.cmd]`\QUIT`
| None
a|
Exits cbq shell.

*Examples*

----
cbq> \EXIT;
----

----
cbq> \QUIT;
----

| [.cmd]`\SET`
| [.var]`parameter`[.var]`value`

[.var]`parameter`=[.var]`prefix`:[.var]``variable name``
a|
Sets the top most value of the stack for the given variable with the specified value.

Variables can be of the following types:

* Query parameters
* Session variables
* User-defined
* Pre-defined and named parameters.

When the [.cmd]`\SET` command is used without any arguments, it displays the values for all the parameters of the current session.

*Examples*

----
cbq> \SET -args [5, "12-14-1987"];
----

----
cbq> \SET -args [6,7];
----

| [.cmd]`\PUSH`
| [.var]`parameter value`
a|
Pushes the specified value on to the given parameter stack.

When the [.cmd]`\PUSH` command is used without any arguments, it copies the top element of every variable's stack, and then pushes that copy to the top of the respective variable's stack.

While each variable stack grows by 1, the previous values are preserved.

*Examples*

----
cbq> \PUSH -args  [8];
----

----
cbq> \PUSH;
----

.Resulting variable stack
----
cbq> \SET;
 Query Parameters :
 Parameter name : args
 Value : [[6,7] [8] [8]]
...
cbq>
----

| [.cmd]`\UNSET`
| [.var]`parameter`
a|
Deletes or resets the entire stack for the specified parameter.

*Examples*

----
cbq> \UNSET -args;
----

----
cbq> \SET;
 Query Parameters :
 ...
cbq>
----

| [.cmd]`\POP`
| [.var]`parameter`
a|
Pops the top most value from the specified parameter's stack.

When the [.cmd]`\POP` command is used without any arguments, it pops the top most value of every variable's stack.

*Examples*

----
\POP -args;
----

----
cbq> \SET;
 Query Parameters :
 Parameter name : args
 Value : [[6,7] [8]]
----

| [.cmd]`\ALIAS`
| [.var]`shell-command` or [.var]`n1ql-statement`
a|
Creates a command alias for the specified cbq shell command or N1QL statement.
You can then execute the alias using `\\alias-name;`.

When the [.cmd]`\ALIAS` command is used without any arguments, it lists all the available aliases.

*Examples*

----
cbq> \ALIAS travel-limit1 select * from `travel-sample` limit 1;
----

----
cbq> \ALIAS;
serverversion  select version()
travel-limit1  select * from `travel-sample` limit 1
cbq>
----

----
cbq> \\serverversion;
{
    "requestID": "21b0efdb-b1ec-44bc-adab-071831792c03",
    "signature": {
        "$1": "string"
    },
    "results": [
        {
            "$1": "1.5.0"
        }
    ],
    "status": "success",
    "metrics": {
        "elapsedTime": "4.03243ms",
        "executionTime": "4.001382ms",
        "resultCount": 1,
        "resultSize": 37
    }
}
----

| [.cmd]`\UNALIAS`
| [.var]`alias-name`
a|
Deletes the specified alias.

*Examples*

----
cbq> \UNALIAS travel-limit1;
----

----
cbq> \ALIAS;
serverversion  select version()
cbq>
----

| [.cmd]`\ECHO`
| [.var]`args`

where [.var]`args` can be parameters, aliases, or any input.
a|
If the input is a parameter, this command echoes (displays) the value of the parameter.
The parameter must be prefixed according to it's type.
See <<table_ltk_c5s_5v>> for details.

If the input is not a parameter, the command echoes the statement as is.

If the input is an alias, the command displays the value of an alias command.

*Examples*

----
cbq> \ECHO -$r;
----

----
cbq> \ECHO \\serverversion;
select version()
----

| [.cmd]`\VERSION`
| None
a|
Displays the version of the client shell.

*Example*

----
cbq> \VERSION;
 SHELL VERSION  : 1.5
----

| [.cmd]`\HELP`
| [.var]`command`
a|
Displays the help information for the specified command.
When used without any arguments, it lists all the commands supported by the cbq shell.

*Example*

----
cbq> \HELP ECHO;
\ECHO args ...
Echo the input value. args can be a name (a prefixed-parameter), an alias (command alias) or
a value (any input statement).
Example :
\ECHO -$r ;
\ECHO \\tempalias;
----

| [.cmd]`\COPYRIGHT`
| None
a|
Displays the copyright, attributions, and distribution terms.

*Example*

----
cbq> \COPYRIGHT;
----

| [.cmd]`\SOURCE`
| [.var]`input-file`
a|
Reads and executes the commands from a file.
Multiple commands in the input file must be separated by "; [.var]``<newline>``"

For example, sample.txt contains the following commands:

----
select * from `travel-sample` limit 1;
\\ECHO this;
#This is a comment;
EOF
----

*Example*

----
cbq> \SOURCE sample.txt;
----

| [.cmd]`\REDIRECT`
| [.var]`filename`
a|
Redirects the output of all the commands to the specified file until the cbq shell receives the [.cmd]`\REDIRECT OFF` command.
By default, the file is created in the [.path]_/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin_ directory.
You can specify a different location using relative paths.

*Example*

----
cbq> \REDIRECT temp_out.txt;
cbq> select * from `travel-sample` limit 1;
cbq>
----

| [.cmd]`\REDIRECT OFF`
| None
a|
Redirects the output of subsequent commands from a custom file to standard output (os.stdout).

*Example*

----
cbq> \REDIRECT OFF;
----
|===

[#cbq-connect-to-cluster]
== Connecting to the Cluster or Query Node

You can connect the cbq shell to Couchbase Server either through the query service or through the cluster endpoint.
There are two ways to establish a connection:

* Using an option on startup:
+
----
-e <url to query engine or Couchbase cluster>
--engine=<url to query engine or Couchbase cluster>
----

* Using a shell command:
+
----
cbq> \CONNECT url;
----

The [.var]`url` is made up of two components: the URL and a port number.
The URL can be any valid IP address or URL.
The URL is optional and if it is not specified, the default URL `+http://localhost:8091+` is used.
An error is thrown if the URL is invalid.

The port number to connect to the query service is 8093 and to the Couchbase cluster is 8091.

The cbq shell supports [.path]_http://_, [.path]_https://_, [.path]_couchbase://_ and [.path]_couchbases://_ protocol schemes.
When using the [.path]_couchbase://_ or [.path]_couchbases://_ protocol schemes, you need not specify the port when connecting to the Couchbase cluster.

When connecting to the query service, use the query port 8093.
When connecting to the cluster, you don't need to specify the port as the connection uses round robin to find a query service to connect to.
If you want to specify a port, use the admin port 8091.

You can close the connection with an existing node or cluster without exiting the shell at any given time during the session using the [.cmd]`\DISCONNECT;` command.
If the shell is not connected to any endpoint, an error with a message that the shell is not connected to any instance is thrown.

.Examples
----
./cbq -e=http://localhost:8091;
Connected to : http://localhost:8091/. Type Ctrl-D to exit.

cbq> \DISCONNECT;
Couchbase query shell not connected to any endpoint. Use \CONNECT command to connect.

cbq> \CONNECT http://127.0.0.1:8091;
Connected to : http://127.0.0.1:8091 . Type Ctrl-D / \exit / \quit to exit.

cbq> \EXIT;
Exiting the shell.

$./cbq -e=http://127.0.0.1:8091;
Connected to : http://127.0.0.1:8091/. Type Ctrl-D to exit.
cbq>
----

*Bringing Up an Unconnected Instance*

You can bring up the shell without connecting to any query service or cluster endpoint by using the [.opt]`-ne` or [.opt]`--no-engine` option.
After starting cbq without any service, you can connect to a specific endpoint using the [.cmd]`CONNECT` command.

.Example
 $ ./cbq -ne
 cbq> \CONNECT http://127.0.0.1:8091;
 Connected to : http://127.0.0.1:8091 . Type Ctrl-D / \exit / \quit to exit.

*Exiting the cbq Shell*

You can exit the cbq shell using one of the following commands:

----
\EXIT; | \QUIT; | Ctrl-D
----

When you run the exit command, the cbq shell first saves the history, closes existing connections, saves the current session in a session file, resets all environment variables, and then closes the shell liner interface.

.Example
[source,console]
----
$ ./cbq
 No Input Credentials. In order to connect to a server with authentication, please provide credentials.
 Connected to : http://localhost:8091/. Type Ctrl-D to exit.

cbq> select name from `travel-sample` WHERE type="airline"  LIMIT 1;
{
   "requestID":"3a86dcf2-3bb4-445c-b419-a5eabd327a1d",
   "signature":{
      "name":"json"
   },
   "results":[
      {
         "name":"40-Mile Air"
      }
   ],
   "status":"success",
   "metrics":{
      "elapsedTime":"20.564ms",
      "executionTime":"20.539035ms",
      "resultCount":1,
      "resultSize":45
   }
}

cbq> \EXIT;
Exiting the shell.
$
----

[#cbq-single-cred]
== Providing Single User Credentials

You can pass a single user name credential to the cbq shell on startup using the command line options:

----
-u=username
--user=username
----

The shell then prompts you for a password.
You can also provide a single password credential using the -p option.
You cannot use this option by itself.
It must be used with the `-u` option to specify the user name that the password is associated with.

----
-p=password
--password=password
----

.Example
[source,console]
----
$ ./cbq -u=Administrator
Enter Password:
Connected to : http://localhost:8091/. Type Ctrl-D to exit.

$ ./cbq -e http://localhost:8091 -u=Administrator -p=password
Connected to : http://localhost:8091/. Type Ctrl-D to exit.
cbq>
----

For information on passing the user name and password credentials using other mechanisms, see <<pass-cred-shell-cmd,Passing Credentials Using the SET Shell Command>> and <<pass-cred-rest-api,Passing Credentials Using REST API>>.

[#cbq-multiple-creds]
== Providing Multiple Credentials for Authorization

The cbq shell supports self-signed certificates for encrypting communication between clusters.

Using the cbq shell, you can set the credentials for different users on startup or by using the SET shell commands to set the credentials query parameter.
You can also use this to provide authentication credentials for multiple SASL buckets per session.
Depending on the type of credential being set, there are multiple possible values for the credentials query parameter.

To set the credentials for different users on startup, use one of the following options:

----
-c=list-of-creds
--credentials=list-of-creds
----

The [.var]`list-of-creds` can take either one or multiple credentials.
The credentials consist of an identity and a password separated by a colon ":".
To specify multiple credentials, append all the user names and passwords to the same credentials array.
For example:

----
-c=travel-sample:pwd1,beer-sample:pwd2
----

For information on passing a single user name credential to the cbq shell, see <<cbq-single-cred>>.

[#pass-cred-shell-cmd]
*Passing Credentials Using the SET Shell Command*

You can provide the credential types using the SET command.

NOTE: The credentials are set for the shell session and not on a per query basis.
You can use the SET, PUSH, POP and UNSET commands to reset the credentials during a session.

To pass authentication credentials per query, set the query parameter to a new value using the SET shell command before executing the query.

You can also switch between users and change credentials during a session.
To do so, set the [.param]`-creds` query parameter for the session using the following command:

----
\SET -creds travel-sample:b1, session:s1;
----

[#pass-cred-rest-api]
*Passing Credentials Using Query REST API*

You can use query REST API to pass credentials from clients.

For SASL buckets, you can pass the credentials as:

----
[  {
     "user":"travel-sample",
     "pass":"password"
   }  ]
----

If you are using the Administrator credentials:

----
[  {
        "user":"Administrator",
        "pass":"password"
   }  ]
----

For multiple SASL protected buckets, you can pass an array of authentication credentials:

----
[  {
        "user":"beer-sample",
        "pass":"password1"
        },
        {
        "user":"travel-sample",
        "pass":"password2"
   }  ]
----

*Displaying the Credentials*

You can display the credentials for the current session using the <<cbq-echo,ECHO>> shell command.
This command displays only the user names (and not the passwords).

----
cbq> \ECHO -creds;

Administrator:*
----

You can also display a full list of variables using the SET command specified without any arguments.

----
cbq> \SET;
Query Parameters ::
Parameter name : timeout Value  ["3ms" "4s"]

Named Parameters ::
Parameter name : r Value  [9.5 9.5]

User Defined Session Parameters ::

Predefined Session Parameters ::
Parameter name : histfile Value  [".cbq_history"]
----

[#cbq-parameter-manipulation]
== Parameter Manipulation

The cbq shell categorizes parameters into the following types:

* Named Parameters
* REST API Parameters
* Session or Pre-defined Parameters
* User-defined Parameters

*Parameter Configuration*

When using parameters, you can set a stack of values for each parameter.
You can either push a new value onto the stack using the PUSH command, or set the current value for a parameter using the SET command.
The SET command always modifies the top of a variable's stack while the PUSH command adds to the stack.
When you use PUSH with no arguments, it copies the top element of every parameter's (except the predefined parameters) stack and pushes that copy to the top of its respective stack.
As a result, each stack grows by 1, but the values are preserved.
You can then use the SET command to modify the top value.

To unset the values from a parameter's stack, you can use the UNSET command to remove all the values from the stack and delete the corresponding parameter stack.
However, if you want to delete a single value from the settings, use the POP command.
When you use the POP command with no arguments, it pops the one value from the top of each parameter's stack.

*Setting Variable Values*

Each variable has a separate stack associated with it and the [.var]`prefix` [.var]`name` argument helps distinguish between the stacks.

The SET command always modifies the top value of a variable.
You can use the SET command to set different kinds of parameters: query parameter, predefined session variables, user-defined session variables and named parameters.

----
\SET <prefix><name> value;
----

where [.var]`name` is the name of the parameter, [.var]`value` is the value to be set, and [.var]`prefix` is one of the following depending on the parameter type.
The cbq shell uses the prefix to differentiate between the different types of parameters.

.Prefixes for Parameters
[#table_ltk_c5s_5v,cols="2,5"]
|===
| Prefix | Parameter Type

| -
| Query parameter

| -$
| Named parameters

| No prefix
| Predefined (built-in) session variable

| $
| User defined session variable
|===

NOTE: Positional parameters are set using the [.param]`-args` query parameter.

You can use the cbq shell to set all the REST API settings by specifying the settings as query parameters prefixed by '-'.
As a best practice, we recommend that you save the initial set of basic parameters and their default values using the [.cmd]`\PUSH` command (with no arguments).

.Examples
----
cbq> \SET -$airport "SJC";
cbq> \PUSH -args ["LAX", 6];
cbq> \SET;
Query Parameters ::
Parameter name : args Value  [["LAX",6]]

Named Parameters ::
Parameter name : airport Value  ["SJC"]

User Defined Session Parameters ::

Predefined Session Parameters ::
Parameter name : histfile Value  [".cbq_history"]

cbq> \PUSH -$airport "SFO";
cbq> \PUSH;
cbq> \SET;
Query Parameters ::
Parameter name : args Value  [["LAX",6] ["LAX",6]]

Named Parameters ::
Parameter name : airport Value  ["SJC" "SFO" "SFO"]

User Defined Session Parameters ::

Predefined Session Parameters ::
Parameter name : histfile Value  [".cbq_history"]

cbq> \SET -args ["SFO", 8];
cbq> \SET;
Query Parameters ::
Parameter name : args Value  [["LAX",6] ["SFO",8]]

Named Parameters ::
Parameter name : airport Value  ["SJC" "SFO" "SFO"]

User Defined Session Parameters ::

Predefined Session Parameters ::
Parameter name : histfile Value  [".cbq_history"]

cbq> \POP;
cbq> \SET;
Query Parameters ::
Parameter name : args Value  [["LAX",6]]

Named Parameters ::
Parameter name : airport Value  ["SJC" "SFO"]

User Defined Session Parameters ::

Predefined Session Parameters ::
Parameter name : histfile Value  [".cbq_history"]

cbq> \POP -$airport;
cbq> \SET;
Query Parameters ::
Parameter name : args Value  [["LAX",6]]

Named Parameters ::
Parameter name : airport Value  ["SJC"]

User Defined Session Parameters ::

Predefined Session Parameters ::
Parameter name : histfile Value  [".cbq_history"]

cbq> \UNSET -$airport;
cbq> \SET;
Query Parameters ::
Parameter name : args Value  [["LAX",6]]

Named Parameters ::

User Defined Session Parameters ::

Predefined Session Parameters ::
Parameter name : histfile Value  [".cbq_history"]
----

To display all the parameters defined in a session, use the SET command with no arguments.

----
cbq> \SET;
Query Parameters ::
Parameter name : timeout Value  ["100m"]

Named Parameters ::
Parameter name : r Value  [9.5]

User Defined Session Parameters ::

Predefined Session Parameters ::
Parameter name : histfile Value  [".cbq_history"]
----

The following table lists the available predefined session variables.

.Predefined Session Variables
[cols="1,1,2"]
|===
| Variable Name | Possible Values | Description

| HISTFILE
| Valid file name
| Specifies the file name to store the command history.
By default the file is saved in the user's home directory.

Default:[.path]__.cbq_history__
|===

*Handling Named Parameters*

Use the \SET command to define named parameters.
For each named parameter, prefix the variable name with '-$'.
The following example creates named parameters 'r' and 'date' with values 9.5 and "1-1-2016" respectively.

----
\SET -$r 9.5;
\SET -$date "1-1-2016";
----

*Handling Positional Parameters*

Use the SET shell command with the [.param]`-args` query parameter to define positional parameters:

----
\SET -args value;
----

The [.var]`value` contains the different values that correspond to positions within the query.
For example,

----
\SET -args [ 9.5, "1-1-2016"];
----

*Resetting Variable Values*

You can reset the value of a variable by either popping it or deleting it altogether.
To pop the top of a parameter's stack use:

----
cbq>\POP <prefix><name>;
----

To pop the top of every parameter's stack once, use the POP command without any arguments:

----
cbq>\POP;
----

To pop all the values of a parameter's stack and then delete the parameter, use:

----
cbq> \UNSET <prefix><name>;
----

[#cbq-shell-cmd-echo]
== Using ECHO to Display Values of Parameters and More

The ECHO command displays the current values of the parameters set for a session.
You can use it to display any input string or command aliases that have been created using the ALIAS shell command.
To display parameters, you must include their prefixes.
If not, the shell considers the parameters as generic statements and displays the parameter as is.

----
\ECHO input ... ;
----

where [.var]`input` can be a parameter with prefix ([.var]`<prefix><parameter-name>`), an alias (\\[.var]`command-alias`), a N1QL statement, or a string.

.Examples
----
cbq> \ECHO hello;
hello

cbq> \ECHO \\travel-alias1;
SELECT * from `travel-sample` LIMIT 1

cbq> \ECHO -$r;
9.5
----

[#cbq-shell-cmd-alias]
== Command Alias

Using the ALIAS shell command, you can define and store aliases for commands.
This is useful when you have lengthy queries that need to be executed often.
Run the following command to define an alias:

----
\ALIAS command-alias command
----

.Example
----
cbq> \ALIAS travel-alias1 SELECT * from `travel-sample` LIMIT 1;
----

To run the command alias, use `\\command-alias`.

.Example
----
cbq> \\travel-alias1;

{
    "requestID": "01f25f87-bd6c-4686-8852-ab81795290d1",
    "signature": {
        "*": "*"
    },
    "results": [
        {
            "travel-sample": {
                "callsign": "MILE-AIR",
                "country": "United States",
                "iata": "Q5",
                "icao": "MLA",
                "id": 10,
                "name": "40-Mile Air",
                "type": "airline"
            }
        }
    ],
    "status": "success",
    ...
}
----

To list all the existing aliases, use:

----
\ALIAS;
----

.Example
----
cbq> \ALIAS;
serverversion  select version()
travel-alias1  SELECT * from `travel-sample` LIMIT 1
----

You can delete a defined alias using the \UNLIAS command.

----
\UNALIAS alias-name ... ;
----

----
cbq> \UNALIAS serverversion travel-alias1;

/* Check existing aliases */
cbq> \ALIAS;
 ERROR 141 : Alias does not exist :
----

This command can take multiple arguments and deletes the defined alias for every input name.

[#cbq-prepared-stmts]
== Executing Prepared Statements

You can use the shell command to execute prepared statements.
As a pre-requisite, you must first prepare a statement using the N1QL xref:n1ql:n1ql-language-reference/prepare.adoc[PREPARE] statement.
To execute prepared statements, follow these steps:

. Set the named and positional parameters that are present in the prepared statement.
. Prepare using the N1QL PREPARE statement.
This can be either prepared statement or a named prepared statement.
If you do not specify a name for the prepared statement (`PREPARE query;`), a unique name is assigned.
You can use this auto-assigned name when executing the prepared statement.
If you specify a name (PREPARE [.var]`name` FROM [.var]`query`;), you can use this name to run the prepared statement.
. Execute the prepared statement using the shell command:
+
----
EXECUTE name-of-prepared-stmt;
----

== Canceling a Query

You can cancel a running query by using the Ctrl+C keys.

*Connection Timeout Parameter*

You can use the timeout parameter to limit the running time of a query.
This parameter specifies the time to wait before returning an error when executing a query.

----
--t=value
--timeout=value
----

Timeout can be specified in the following units: "ns" for nanoseconds, "μs" for microseconds, "ms" for milliseconds, "s" for seconds, "m" for minutes, and "h" for hours.
Examples of valid values include "0.5s", "10ms", or "1m".

You can also the SET shell command to set this parameter.
An error is thrown if the timeout is invalid.

[source,console]
----
$ ./cbq --timeout="2s"

$ ./cbq -q
cbq> \SET -TIMEOUT 1ms
----

[#cbq-file-based-ops]
== File Based Operations

Using the file based commands and options, the cbq shell can execute N1QL and shell commands contained in files.
There are two ways to accomplish this:

* Using an option on startup:
+
----
-f=input-file
--file=input-file
----
+
The cbq shell executes the commands present in the input file, prints them to stdout (or to a file if using redirects), and exits.

* Using a shell command:
+
----
\SOURCE input-file;
----
+
Runs the commands present in the input file and prints the result to stdout.

Consider the input file, [.path]_sample.txt_, containing the following commands:

----
CREATE PRIMARY INDEX on `beer-sample` USING GSI;
SELECT * from `beer-sample` LIMIT 2;
SELECT abv from `beer-sample` LIMIT 3;
\HELP;
----

To execute the commands contained in [.path]_sample.txt_ using the -f option, run `$./cbq -f=sample.txt`

.Results
----
Connected to : http://localhost:8091/. Type Ctrl-D to exit.
CREATE PRIMARY INDEX on `beer-sample` USING GSI;
{ ...
  "results": [ ],
  ...
}
SELECT * from `beer-sample` LIMIT 2;
{ ...
  "results": [ ],
  ...
}
SELECT abv from `beer-sample` LIMIT 3;
{ ...
  "results": [ ],
  ...
}
\HELP;
Help Information for all Shell Commands
…
$
----

To execute the commands contained in [.path]_sample.txt_ using the shell command, run `cbq> \SOURCE sample.txt;`

.Results
----
CREATE PRIMARY INDEX on `beer-sample` USING GSI;
{ ...
  "results": [ ],
 ...
}
SELECT * from `beer-sample` LIMIT 2;
{ ...
  "results": [ ],
  ...
}
SELECT abv from `beer-sample` LIMIT 3;
{ ...
  "results": [ ],
  ...
}
\HELP;
Help Information for all Shell Commands
…
cbq>
----

*Redirecting Results to a File*

You can redirect all the output for a session or part of a session to a specified file by using the following option:

----
-o filename
--output=filename
----

To redirect a specific set of commands during a session, you must specify the commands between REDIRECT and REDIRECT OFF as shown:

----
cbq> \REDIRECT filename;
command-1; command-2;, ..., command-n;
\REDIRECT OFF;
----

All the commands specified after `\REDIRECT` and before `\REDIRECT OFF` are saved into the specified output file.
If the file doesn't exist then it is created.

.Example
----
cbq> \REDIRECT temp_output.txt;
> CREATE PRIMARY INDEX on `beer-sample` USING GSI;
> SELECT * from `beer-sample` LIMIT 1;
> \HELP;
> \REDIRECT OFF;
----

You can specify multiple `REDIRECT` commands.
When you do so, the output file changes to the specified files and switches back to [.out]`stdout` only when you specify "[.code]``\REDIRECT OFF``;".

[#cbq-server-shell-info]
== Server and Shell Information

The cbq shell provides commands that convey information about the shell or cluster endpoints.

Version::
You can find the version of the client (shell) by using either the command line option to display the current version of the shell and exit, or as a shell command to print the version of the shell during the shell session.
+
.Example Using the Command-line Option
----
./cbq -v
SHELL VERSION : 1.0

$ ./cbq --version
SHELL VERSION : 1.0
----
+
.Example Using the Shell Command
----
cbq> \VERSION;
SHELL VERSION : 1.0
----
+
To display the version of the query service, use the N1QL commands `SELECT version();` and `SELECT min_version();`.

Copyright::
You can view the copyright, attributions, and distribution terms of the command line query tool using the `\COPYRIGHT;` command.
+
----
cbq> \COPYRIGHT;
Copyright (c) 2015 Couchbase, Inc. Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the
License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the specific language governing permissions
cbq>
----

== Shortcut Keys for cbq Shell

The following table lists the shortcut keys used by the [.cmd]`cbq` shell.

.Shortcut Keys for cbq Shell
[cols="100,197"]
|===
| Keystroke | Action

| Ctrl-A, Home
| Move cursor to beginning of line

| Ctrl-E, End
| Move cursor to end of line

| Ctrl-B, Left
| Move cursor one character left

| Ctrl-F, Right
| Move cursor one character right

| Ctrl-Left
| Move cursor to previous word

| Ctrl-Right
| Move cursor to next word

| Ctrl-D, Del
| (if line is not empty) Delete character under cursor

| Ctrl-D
| (if line is empty) End of File - usually quits application

| Ctrl-C
| Reset input (create new empty prompt)

| Ctrl-L
| Clear screen (line is unmodified)

| Ctrl-T
| Transpose previous character with current character

| Ctrl-H, BackSpace
| Delete character before cursor

| Ctrl-W
| Delete word leading up to cursor

| Ctrl-K
| Delete from cursor to end of line

| Ctrl-U
| Delete from start of line to cursor

| Ctrl-P, Up
| Previous match from history

| Ctrl-N, Down
| Next match from history

| Ctrl-R
| Reverse Search history (Ctrl-S forward, Ctrl-G cancel)

| Ctrl-Y
| Paste from Yank buffer (Alt-Y to paste next yank instead)

| Tab
| Next completion

| Shift-Tab
| (after Tab) Previous completion
|===

Source: [.cite]_\https://github.com/peterh/liner_
