= Couchbase: Getting started

:page-pagination: ''

:description: pass:q[A short tutorial that will guide the developer in downloading and installing Couchbase, then creating a database to store student records.]

[abstract]
{description}

== Introduction
Couchbase is a schema-less document database engine designed for high performance, scalability, and rapid development. During this tutorial, we'll introduce you to some of the key concepts behind Couchbase and how they differ from traditional SQL database systems such as MySQL and Oracle. We're going to examine the advantages of a schema-less engine by building a document database for storing student records.

== A typical relational database design [[database-design]]
So, what would our database schema look like as a relational database model?
[cols="50%, 50%"]
|===
^| Relational model ^| Document model

a|

include::partial$student-database-diagrams.adoc[tags="student-record-erd"]
a|
[source,json]
----
include::partial$hilary-smith.json[]
----
|===


Nothing too dramatic: the database contains a list of students and a list of courses. Each student can enrol on any number of courses, and the record of each of the student's enrolments is stored in a separate table called `enrolment` which links to the student's record and the courses he/she is enrolling on.

The `enrolment` table highlights one of the problems with the relational database model: each table is based on a fixed schema that can only support a single data object type. You cannot store, for example, the enrolment records in the same table as the student, even though it may more natural to do so; after all, an `enrolment` cannot exist without a `student`, so why not store them together?

Couchbase uses a document model which stores each database record as a `json` document. The document can can contain both simple scalar types, and complex types such as nested records and arrays.

Hilary's enrolments are stored in the same document as her student details. As well as being a more natural way to store child information with its parent, this structure allows for all of Hilary's details (enrolments included) in one search, without the need for complex table joins to retrieve the enrolment information.


== What's next …?

Okay, now that we've got the basic idea behind the document database model, let's continue with a few exercises:


|===
|Step | Tutorial

|Step {counter:step}
|xref:install-couchbase-server.adoc[]

| Step {counter:step}
|xref:buckets-scopes-and-collections.adoc[]

|Step {counter:step}
|xref:java-tutorial/install-couchbase-java-sdk.adoc[]

|Step {counter:step}
|xref:java-tutorial/first-couchbase-application.adoc[]

|Step {counter:step}
|xref:java-tutorial/second-couchbase-application.adoc[]

| Step {counter:step}
| xref:java-tutorial/retrieving-documents.adoc[]

| Step {counter:step}
| xref:java-tutorial/adding-enrolments.adoc[]
|===

TIP: It is *strongly* recommended that you follow the sections in order.

In the next part of the tutorial, you're going to begin your exploration of Couchbase by xref:install-couchbase-server.adoc[installing the Couchbase Server: Community edition].
