= Couchbase: Up and running in twenty minutes

:description: A short tutorial that will guide the developer in downloading and installing Couchbase, then creating a database to store our student records.

[abstract]
{description}

== Introduction
Couchbase is a schemaless document database engine designed for high performance, scalability, and rapid development. During this tutorial, we'll introduce you to some of the key concepts behind Couchbase and how they differ from traditional SQL database systems such as MySQL and Oracle. We're going to examine the advantages of a schemaless database engine by building a document database for storing student records.

== A typical relational database design
So, what would our database schema look like as a relational database model?

include::partial$student-database-diagrams.adoc[tags="student-record-erd"]

Nothing too dramatic:  the database contains a list of students and a list of courses. Each student can enrol on any number of courses, and the record of each of the student's enrolments is stored in a separate table called `enrolment` which links to the student's record and the course he/she is enrolling on.

The `enrolment` table highlights one of the problems with the relational database model: each table is based on a fixed schema that can only support singular data items. It may feel more natural to store the list of enrolments inside the student record.

Couchbase uses a document model which treats stores each database record as a `json` document. The document can can contain both simple scalar types, and complex types such as nested records and arrays.

[source,json]
.Hilary's student record
----
{
  "student-id": "000001",
  "name": "Hilary Smith",
  "date-of-birth": "21-12-1980",
  "enrolments": [
    {
      "course-id": "ART-HISTORY-00003",
      "date-enrolled": "07-9-2021"
    },
    {
      "course-id": "GRAPHIC-DESIGN-00001",
      "date-enrolled": "15-9-2021"
    }
  ]
}
----

Hilary's enrolments are stored in the same document as her student details. As well as being a more natural way to store child information with its parent, this structure allows for all of Hilary's details (enrolments included) in one search, without the need for joining tables to retrieve the enrolment information.


== What's next …?

Okay, now that we've got the basic idea behind the document database model, let's carry on and build the first cut of our student record database:

[cols="1,1,1", grid=none, frame=none]
|===
| xref:installing-couchbase-community-edition.adoc[]
| xref:install-couchbase-java-sdk.adoc[]
| xref:first-couchbase-application.adoc[]
|===

TIP: It is *strongly* recommended that you follow the sections in order.

In the next part of the tutorial, you're going to begin your exploration of Couchbase by xref:installing-couchbase-community-edition.adoc[installing the Couchbase Server: Community edition].
