= Create a Search Index with the UI 
:description: You can create a Search Index with the Couchbase Server, Couchbase Capella, and Couchbase ? UI. 
:page-topic-type: guide
:tabs:

[abstract]
{description}

== Prerequisites

* You've deployed the Search Service on a node in your database. 

* Your user account has the ** role. 

* You've logged in to the Couchbase Server Web Console or Capella UI. 

== Procedure 

[{tabs}]
====
Couchbase Server::
+
--
. Go to *Search*.
. Click btn:[Add Index].
. In the *Index Name* field, enter a name for the index. 
+
NOTE: Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

. In the *Bucket* list, select the bucket where you want to create the index. 
. Expand *Customize Index*. 
. (Optional) To create the index on a scope other than `_default`, select *Use non-default scope/collection(s)*.
.. In the *Scope* list, select the scope where you want to create the index. 
. Configure additional settings for the index: 
+
|====
|Option 2+|Description 

.4+|Type Identifier 2+|Choose a type identifier option to set how the index sets a document's type: 

|JSON Type Field |Use the value of a field in the document as that document's type. Enter the field name in the provided field. 

|Doc ID up to separator |Use the document's ID value, up to a given separator, as the document's type. Enter the separator in the provided field.

|Doc ID with regex |Use the document's ID value with a regular expression applied as the document's type. Enter the regular expression in the provided field. 

|Mappings 2+a|

Set a type mapping to include or exclude specific documents in a scope or collection from the index.

For more information about how to add a type mapping to an index, see xref:guides:search/create-type-mapping.adoc[].

|Analyzers 2+a|

Create a custom analyzer to improve and customize the search results from an index. 

For more information about how to create a custom analyzer, see xref:guides:search/create-custom-analyzer.adoc[].

|Custom Filters 2+a|

Create character filters, tokenizers, token filters, and wordlists to add more customization to a custom analyzer.

For more information about how to create these components, see xref:guides:search/customize-index.adoc[].

|Date/Time Parsers 2+a|

If the documents in your index contain date and time data in a format other than RFC-3339 (ISO-8601), then you need to create a date/time parser.

For more information about how to add a custom date/time parser, see xref:guides:search/create-custom-date-time-parser.adoc[].

.10+|Advanced 2+|Configure advanced settings for your index: 

|Default Type |Change the default type assigned to documents in the index. The default value is `_default`.

|Default Analyzer a|

Change the default analyzer assigned to type mappings in the index. 

For more information about the available default analyzers, see xref:guides:search/default-analyzers-reference.adoc[].

|Default Date/Time Parser |Change the default date/time parser used for date data. 

|[[all-field]]Default Field a|

When you xref:guides:search/create-child-field.adoc[create a child field] in a type mapping, you can choose to include that field in an `_all` field. 

You can add fields to the `_all` field to search their contents without specifying their field name in your search query. 

Enter a value in the *Default Field* field to change the name of this default field. 

|Store Dynamic Fields |Select *Store Dynamic Fields* to include field values in search results from a xref:guides:search/customize-index.adoc#type-mappings[dynamic type mapping], select .

|Index Dynamic Fields |Select *Index Dynamic Fields* to include fields from a xref:guides:search/customize-index.adoc#type-mappings[dynamic type mapping] in the index. 

|DocValues for Dynamic Fields |Select *DocValues for Dynamic Fields* to include the values of each field from a xref:guides:search/customize-index.adoc#type-mappings[dynamic type mapping] in the index.

|Index Replicas a|

Set the number of replicas that the Search Service creates for the index. 

For more information about replication and the Search Service, see xref:[].

|Index Type |This setting is included for compatibility only. For new indexes, this setting is always *Version 6.0 (Scorch)*.

|Index Partitions |Enter a number greater than one to to divide the index into partitions across multiple nodes running the Search Service. 

|====
. Click btn:[Create Index].
--

Couchbase Capella::
+
--
. From your organization page, select the database where you want to create a search index. 
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
. In the *Name* field, enter a name for the index. 
+
NOTE: Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).
. In the *Bucket* list, select the bucket where you want to create the index. 
. (Optional) To create the index on a scope other than `_default`, select *Use non-default scope/collection(s)*.
.. In the *Scope* list, select the scope where you want to create the index. 
. Expand *Advanced Configuration*.
. Configure advanced settings for the index:
+
|====
|Option 3+|Description 

.15+|General Settings 3+|Configure general settings for your index: 

.4+|Type Identifier 2+|Choose a type identifier option to set how the index sets a document's type: 

|JSON Type Field |Use the value of a field in the document as that document's type. Enter the field name in the provided field. 

|Doc ID up to separator |Use the document's ID value, up to a given separator, as the document's type. Enter the separator in the provided field.

|Doc ID with regex |Use the document's ID value with a regular expression applied as the document's type. Enter the regular expression in the provided field. 

|Default Type 2+|Change the default type assigned to documents in the index. The default value is `_default`.

|Default Analyzer 2+a|

Change the default analyzer assigned to type mappings in the index. 

For more information about the available default analyzers, see xref:guides:search/default-analyzers-reference.adoc[].

|Default Date/Time Parser 2+|Change the default date/time parser used for date data. 

|Default Field 2+a|

When you xref:guides:search/create-child-field.adoc[create a child field] in a type mapping, you can choose to include that field in an `_all` field. 

You can add fields to the `_all` field to search their contents without specifying their field name in your search query. 

Enter a value in the *Default Field* field to change the name of this default field. 

|Store Dynamic Fields 2+|Select *Store Dynamic Fields* to include field values in search results from a xref:guides:search/customize-index.adoc#type-mappings[dynamic type mapping], select .

|Index Dynamic Fields 2+|Select *Index Dynamic Fields* to include fields from a xref:guides:search/customize-index.adoc#type-mappings[dynamic type mapping] in the index. 

|DocValues for Dynamic Fields 2+|Select *DocValues for Dynamic Fields* to include the values of each field from a xref:guides:search/customize-index.adoc#type-mappings[dynamic type mapping] in the index.

|Index Replicas 2+a|

Set the number of replicas that the Search Service creates for the index. 

For more information about replication and the Search Service, see xref:[].

|Index Type 2+|This setting is included for compatibility only. For new indexes, this setting is always *Version 6.0 (Scorch)*.

|Index Partitions 2+|Enter a number greater than one to to divide the index into partitions across multiple nodes running the Search Service.

|Type Mappings 3+a|

Set a type mapping to include or exclude specific documents in a scope or collection from the index.

For more information about how to add a type mapping to an index, see xref:guides:search/create-type-mapping.adoc[].

|Analyzers 3+a|

Create a custom analyzer to improve and customize the search results from an index. 

For more information about how to create a custom analyzer, see xref:guides:search/create-custom-analyzer.adoc[].

|Custom Filters 3+a|

Create character filters, tokenizers, token filters, and wordlists to add more customization to a custom analyzer.

For more information about how to create these components, see xref:guides:search/customize-index.adoc[].

|Date/Time Parsers 3+a|

If the documents in your index contain date and time data in a format other than RFC-3339 (ISO-8601), then you need to create a date/time parser.

For more information about how to add a custom date/time parser, see xref:guides:search/create-custom-date-time-parser.adoc[].


|====
. Click btn:[Create Index].
--
====