= Create a Basic Search Index with the UI 
:description: You can create a Search index with the Couchbase Server, Couchbase Capella, and Couchbase ? UI. 
:page-topic-type: guide
:tabs:

[abstract]
{description}

== Prerequisites

* You've deployed the Search Service on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* Your user account has the *Search Admin* role for the bucket where you want to create the index.  

* You've logged in to the Couchbase Server Web Console or Capella UI. 

== Procedure 

To create a Search index with the Couchbase Server Web Console or Couchbase Capella UI: 

[{tabs}]
====
Couchbase Server::
+
--
. Go to *Search*.
. Click btn:[Add Index].
. In the *Index Name* field, enter a name for the index. 
+
NOTE: Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

. In the *Bucket* list, select the bucket where you want to create the index. 
. Expand *Customize Index*. 
. (Optional) To create the index on a scope other than `_default`, select *Use non-default scope/collection(s)*.
.. In the *Scope* list, select the scope where you want to create the index. 
. Click btn:[Create Index].
--

Couchbase Capella::
+
--
. From your organization page, select the database where you want to create a search index. 
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
. In the *Name* field, enter a name for the index. 
+
NOTE: Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).
. In the *Bucket* list, select the bucket where you want to create the index. 
. (Optional) To create the index on a scope other than `_default`, select *Use non-default scope/collection(s)*.
.. In the *Scope* list, select the scope where you want to create the index. 
. Click btn:[Create Index].
--
====

== Next Steps 

This basic index includes all documents from the bucket and scope you selected.
You can run a search against this index, but it's recommended that you customize your index to improve performance and reduce the index size. 
 
For more information about how to customize an index, see xref:guides:search/customize-index.adoc[].

For more information about how to run a search, see xref:guides:search/simple-search-ui.adoc[].