= Create a Search Index with the REST API 
:description: You can create a Search index with the Search Service API. 
:page-topic-type: guide

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* Your user account has the *Search Admin* role for the bucket where you want to create the index. 

* You've installed the Couchbase command-line tool (CLI).

* You have the hostname or IP address for your database. 

== Procedure 

. In the command-line tool, start a `curl` command with the `XPUT` verb. 
. Set your header content to include `Content-Type: application/json`.
. Enter your username, password, and the Search Service endpoint on port `8094` with the name of the index you want to create: 
+
[source,console]
----
include::example$search/create-search-index-header.sh[]
----
. Enter the JSON payload for the settings you want in your index. 
+
TIP: You can copy the Index Definition from the Couchbase Server or Couchbase Capella UI to use in your REST API call.
For more information about how to create an index with the UI, see xref:guides:search/create-search-index-ui.adoc[].

+
In the following example, the JSON payload creates a simple index named `landmark-content-index` on the `travel-sample` bucket. It creates a type mapping for the `inventory.landmark` collection, with a child field, `content`:
+
[source,console]
----
include::example$search/create-search-index-payload.sh[]
----
+
For more information on the available JSON properties for a Search index, see xref:guides:search/search-index-params.adoc[].