= Search Request Properties 

[cols="1,1,1,2"]
|====
|Property |Type |Required? |Description

|explain |Boolean |Yes a|

To create an explanation for a search result's score in search results, set `explain` to `true`.

To turn off explanations for search result scoring, set `explain` to `false`.

|fields |Array |Yes a|

An array of strings for each indexed field to return in search results. 

If you didn't add a field and its content to the index, you can't view it in search results.

|highlight |Object |No |

|query |Object |Yes |Contains the search query. See <<query,>>.

|sort |Array |Yes a|

Contains an array of strings or JSON objects to set how to sort search results. 

The strings can be: 

* `{field_name}`: Specify the name of a field to use to sort the search results.
* `_id`: Use the document's identifier to sort the search results. 
* `_score`: Use the document's score from the search query to sort the search results.
* A JSON object. 

For more information on the properties for a `sort` JSON object, see <<sort,>>.

|search_after |Array |No a|

NOTE: If you use `search_after` in a search request, you can't use `search_before`.


|search_before |Array |No a|

NOTE: If you use `search_before` in a search request, you can't use `search_after`.

|score |String |No |To disable document relevancy scoring in search results, set `score` to `none`.

|size/limit |Integer |Yes |Set the total number of results to return for a single page of search results. 

|from/offset |Integer |Yes |Set 

|collections |Array |No |Contains an array of strings that specify the collections where you want to run the query. 

|====

[#highlight]
== Highlight Object 

Use the `highlight` object to control how the Search Service highlights matches in search results. 

[cols="1,1,1,2"]
|====
|Property |Type |Required? |Description

|style |String |No |

|fields |Array |No a|

Contains an array of strings for each field name where you want to highlight a search query match. 

If you include the `fields` array, the Search Service doesn't highlight any fields that aren't in the array.

|====

[#sort]
== Sort Object 

Use the `sort` object to control how the Search Service sorts search results. 

[cols="1,1,1,2"]
|====
|Property |Type |Required? |Description 

|by |String |Yes a|

Sets what value to use for the sort: 

* `id`: Uses the document's ID value. 
* `score`: Uses the document's score. 
* `field`: Uses the value of a specific field to sort. See <<field,field>>.

|[[field]]field |String |No |When `by` is set to `field`, specify the name of the field to use to sort search results.

|mode |String |Yes a|

Set the order for search results when the `field` contains multiple values: 

* `default`: 
* `min`:
* `max`: 

|missing |String |Yes a|

Set how the Search Service sorts documents that don't have a value for the field specified in `field`:

* `first`: Documents with a missing value appear first and before other results in search results. 
* `last`: Documents with a missing value appear last and after other results in search results. 

|type |String |Yes a|

Set the data type of the field specified in `field`:

* `string`: The field contains a string. 
* `date`: The field contains date/time data. 
* `number`: The field contains a number or geographic data, like a latitude or longitude value. 

|====

[#query]
== Query Object 

[cols="1,1,1,2"]
|====
|Property |Type |Required? |Description 

|match |String |

|field |String |

|analyzer |String |
|====