= Search Index JSON Properties


|====
|Property 2+|Description

|type 2+a|

The type of index you want to create: 

* `fulltext-index`: Create a search index.
* `fulltext-alias`: Create an alias for a search index. 
For more information about search index alias, see xref:[]

|name 2+|The name of the index.

|sourceType 2+|Set to `"gocbcore"`.

|sourceName 2+a|
The name of the bucket where you want to create the index. 

The Search Service automatically finds the UUID for the bucket.

.4+|*planParams* 2+|An object that sets specific parameters for how to create the index. 
|maxPartitionsPerPIndex |This setting is deprecated. Use `indexPartitions`, instead.
|indexPartitions |The number of partitions to split the index into. 
|numReplicas |The number of replicas to create for index partitions. 

|params 2+|An object that sets how the index determines a document's type. 
For more information, see <<params,>>.

|====

[#params]
== `params` Object 

The `params` object sets an index's type identifier and type mappings. 

|====
|Property 3+|Description 

.4+|*doc_config*

|mode 2+a|

Set how the index identifies a document's type: 

* `type_field`: Use the value from a specific field in the documents. 
* `docid_prefix_delim`: Use the characters in the documents' ID values, up to but not including a specified separator.
* `docid_regexp`: Use a regular expression on the documents' ID values.

NOTE: If your index uses a specific collection, the `mode` value must be `"scope.collection.{mode}"`.

|docid_prefix_delim 2+|If `mode` is `docid_prefix_delim`, set the separator character to use on a document's ID value to determine its type.

|docid_regexp 2+|If `mode` is `docid_regexp`, set the regular expression to use on a document's ID value to determine its type. 

|type_field 2+|If `mode` is `type_field`, set the name of the field to use to determine a document's type.

.13+|*mapping*

|analysis 2+|

|default_analyzer 2+a|
The name of the default analyzer to use for the type mapping.

For more information about analyzers, see xref:[]

|default_datetime_parser 2+a|
The name of the default date/time parser to use for the type mapping. 

For more information about date/time parsers, see xref:[]

|default_field 2+a|
Set a name for the type mapping's `all` field.

If you enable `include_in_all` for a child field, the contents of that child field can be searched by specifying this field's name in your search. 

.3+|*default_mapping* 

2+|Specifies the index's default type mapping, for the `_default` scope and `_default` collection in the bucket. 
Contains the following properties: 

|dynamic a|
To index all available fields in a document with the default type mapping, set `dynamic` to `true`. 

To only index the fields you specify in the type mapping, set `dynamic` to `false`.

|enabled a|
To enable the Search Service's default type mapping, set `enabled` to `true`. 

The default type mapping includes all documents in the bucket in the index, even if they don't match another configured type mapping.
This can increase index size and indexing time. 

To disable the default type mapping, set `enabled` to `false`.

|default_type 2+|Set the default type for any documents in  

|docvalues_dynamic 2+a|
To include the values for an indexed field in search results, set `docvalues_dynamic` to `true`.

To exclude the values for an indexed field in search results, set `docvalues_dynamic` to `false`.

|index_dynamic 2+a|

To index any fields in the index where `dynamic` is `true`, set `index_dynamic` to `true`.

To exclude dynamic fields from the index, set `index_dynamic` to `false`.

|store_dynamic 2+a|

To return the content from an indexed field in search results, set `store_dynamic` to `true`.

To exclude field content from search results, set `store_dynamic` to `false`.

|type_field 2+|Use the same value assigned to the `type_field` in `doc_config`, if applicable.

|types 2+| Contains any additional user-defined type mappings for the index. Contains any number of `{scope}.{collection}` objects. For more information, see <<types,>>.

|====

[#types]
== `types` Object

The `types` object contains any additional user-defined type mappings for an index. 

|====
|Property 2+|Description

.3+|*{scope}.{collection}* 2+a|

The name of the type mapping. Corresponds to the selected scope and collection where the type mapping applies. For example, `inventory.airline`. 

Contains the `enabled`, `dynamic`, and `properties` properties.

|dynamic a|

To index all fields under the specified scope and collection, set `dynamic` to `true`.

To only index the fields you specify and enable the `properties` block, set `dynamic` to `false`. 

|enabled a| 

To enable the type mapping and include any documents that match it in the index, set `enabled` to `true`. 

To remove any documents that match this type mapping from the index, set `enabled` to `false`.

.10+|properties 2+a|

The `properties` object is only enabled if `dynamic` is set to `false`. 

Specifies properties for the fields to index in the type mapping. Contains the `{fieldname}` object. 

For more information, see <<child-fields,>>

|====

[#child-fields]
=== `{fieldname}` Object

The `{fieldname}` object contains settings and an array for a child field in a type mapping. You can have multiple `{fieldname}` objects in a `properties` object.

|====
|Property 2+|Description

.3+|*{fieldname}* 2+|The name of the child field you want to index in the type mapping. For example, `city`.

|enabled a|

To add this child field to the index, set `enabled` to `true`.

To remove this child field from the index, set `enabled` to `false`.

|dynamic a|

To , set `dynamic` to `true`.

To , set `dynamic` to `false`.

.9+|*fields* 2+|An array that contains settings for each child field to index in the type mapping.

|name |The child field's name. 

|type |The child field's type. Can be one of `text`, `number`, `datetime`, `boolean`, `geopoint`, `geoshape`, or `disabled`.

|store a|

To include the content of the child field in the index and allow its content to be viewed in search results, set `store` to `true`.

To exclude the content of the child field from the index, set `store` to `false`.

|index a|

To include the child field in the index, set `index` to `true`.

To exclude the child field from the index, set `index` to `false`.

|include_term_vectors a|

NOTE: To use term vectors, `store` must be set to `true`.

To allow the Search Service to highlight matching search terms in search results for this field, set `include_term_vectors` to `true`.

To disable term highlighting and reduce index size, set `include_term_vectors` to `false`.

|include_in_all a|

To allow this field to be searched without specifying the specific field's name in the search, set `include_in_all` to `true`.

When enabled, you can search this field through the specified `default_field` set in the type mapping.

To only search this field by specifying the field name, set `include_in_all` to `false`.

|docvalues a|

To include the value for each instance of the field in the index to support xref:[Facets] and sorting search results, set `docvalues` to `true`.

To exclude the values for each instance of this field from the index, set `docvalues` to `false`.
|====