= Deploying Couchbase with Terraform on AWS

https://www.terraform.io/intro/index.html[Terraform] is an Infrastructure as Code (IaC) technology that allows you to build, version, and deploy your datacenter resources in a descriptive manner, much like software source code.
This makes Terraform uniquely suited for deploying Couchbase on AWS, because you can quickly organize and execute infrastructure code that maintains a Couchbase cloud environment to your exact specifications.

== Getting Started

The best way to use Terraform with Couchbase is through the creation of _modules_.

[quote,, 'https://aws.amazon.com/blogs/apn/terraform-beyond-the-basics-with-aws/[AWS Partner Network Blog: "Terraform: Beyond the Basics with AWS"]']
____
Modules are logical groupings of Terraform configuration files.
Modules are intended to be shared and re-used across projects, but can also be used within a project to help better structure a complex service [like a distributed database] that includes many infrastructure components.
____

Instead of creating your own Terraform modules from scratch, https://www.gruntwork.io/[Gruntwork] has developed a set of fully-featured, open source modules that define an ideal set of infrastructure components for Couchbase.
These modules support features like multi-dimensional scaling (MDS) and Cross Data Center Replication (XDCR), and even include a full test suite.

https://blog.gruntwork.io/get-couchbase-running-on-aws-in-5-minutes-732d3be36784[Get started] with Terraform modules from Gruntwork, available on https://github.com/gruntwork-io/terraform-aws-couchbase[GitHub].
