[#topic_ghd_55f_nbb]
= Microsoft Azure and Couchbase

Couchbase partners with Microsoft to enable a seamless user experience on Azure.
At the core of this experience are best practices codified as Azure Resource Manager (ARM) templates.
These templates are developed in close collaboration with the Microsoft Azure Engineering team and leverage the latest Azure features, including Virtual Machine Scale Sets (VMSS), Managed Disks, and Premium Storage.
This simplifies both deployment and operations.

Couchbase is available through the Microsoft Azure Marketplace (AMP) with hourly pricing or through a Bring Your Own License (BYOL) model.
For more information, see xref:couchbase-azure-marketplace.adoc[Deploying Couchbase from Azure Marketplace].
// You can also deploy Couchbase
// using the ARM templates we host on GitHub.
// For more information, see <xref
// href="#topic_ghd_55f_nbb/azure-cli" format="dita"/>.

Best practices when deploying on Azure are available xref:couchbase-azure-best-practices.adoc#topic_ghd_55f_nbb[here].
For other resources detailing the Microsoft and Couchbase partnership, see our https://www.couchbase.com/partners/microsoft[partners page].
