[#topic_ghd_55f_nbb]
= Google Cloud Platform and Couchbase

Couchbase partners with Google to provide a packaged solution on Google Cloud Launcher, Google Deployment Manager (DM) templates, and best practices.
These enable you to be up and running with Couchbase on Google Cloud Platform (GCP) quickly and easily.

The Deployment Manager (DM) templates are developed in close collaboration with the GCP Engineering team to adopt the latest features.
These templates leverage Google’s globally flat network for extremely secure geographical replication.
Couchbase is the first software vendor to leverage Instance Group Manager (IGM) in a Cloud Launcher template, simplifying cluster management and scaling while improving resilience to hardware failures.

Couchbase is available through Google Cloud Launcher with hourly pricing or through a Bring Your Own License (BYOL) model.
For more information, see xref:couchbase-gcp-cloud-launcher.adoc#topic_rfg_qjt_xs[Deploying Couchbase on Google Cloud Launcher].
// You can also deploy Couchbase
// with the DM templates we host on GitHub.
// For more information, see <xref
// href="#topic_ghd_55f_nbb/gcp-cli" format="dita"/>.

Best practices when deploying on GCP are available here.
For other resources detailing the Google and Couchbase partnership, see the https://console.cloud.google.com/launcher/partners/couchbase-public[Google Cloud Launcher Partners page].
