= Frequently Asked Questions about Couchbase Containers
:description: Frequently asked questions about Couchbase Containers 

[abstract]
{description}

== Do we support modifying the official Couchbase container?


== Do we support custom containers (i.e. not based on the official Couchbase one)?


The Official Couchbase container image gets built with our Dockerfile, which consists of the commands to assemble the image and some best practices. In this process, the Couchbase binaries do not get changed or altered. 
Users customizing Couchbase container images will update and rebuild the Dockerfile with their environment-specific settings or best practice guidelines. Even in this process, the Couchbase binaries do not get changed or altered. 
So the answer to the question of whether we support users modifying the Dockerfile to build a customized Couchbase container image is 'Yes' we support them. 

Couchbase container images shipped on the DockerHub and Red Hat Registry are not just Doockerfile but actual binaries.
For Couchbase container images, when published, has 'automated build' turned-on. In which case, when new security vulnerabilities get detected, the Couchbase container image will automatically get rebuilt and updated. 
On Docker Hub, what happens is that every so often, the Ubuntu (not Docker) team will release an updated version of the Ubuntu base image that our image uses. Docker Hub then will rebuild all Official images that are based on that version of Ubuntu.

== Can we provide alternative containers with different base OS's?

We currently only support Ubuntu as the base OS for DockerHub and RHEL for Red Hat Registry. If there is enough demand from users to support a particular base OS, we will consider adding them to our product roadmap for future releases. 

== Are there any restrictions on using a container we make for OpenShift/RHCC in a non-OpenShift environment?

We build the Official Couchbase image for Red Hat Catalog with base OS as the Red Hat Enterprise Linux (RHEL). Other than that, we don't put any restrictions on the usage of the image itself. 

== Do we support Kubernetes deployments that do not use Couchbase Autonomus Operator?

Users who are considering deploying and running Couchbase Server on the Kubernetes platform get highly recommended to utilize our fully automated advanced Couchbase Autonomous Operator. If users choose to deploy Couchbase Server on the Kubernetes platform on their own, we only support product issues with container images.  