= Amazon Web Services (AWS) and Couchbase

Couchbase partners with Amazon to enable a seamless user experience on Amazon Web Services(AWS).
At the core of this experience are best practices codified as Cloud Formation templates.
These templates are developed in close collaboration with the Amazon Web Services Engineering team and leverage the latest AWS features.
The Amazon Machine Images (AMI) provide the information required to launch an instance of a virtual server in the AWS cloud.
Thus making it easier and faster to deploy Couchbase Server in the AWS cloud without having to create and manage schemas, or need to normalize, shard or tune the database.

Couchbase is available through the Amazon Web Services (AWS) Marketplace with hourly pricing or through a Bring Your Own License (BYOL) model.
For more information, see xref:couchbase-aws-marketplace.adoc[Deploying Couchbase from AWS Marketplace].
// You can also deploy Couchbase
// using the Cloud Formation templates we host on GitHub.
// For more information, see <xref
// href="#topic_knp_njt_xs/aws-cft" format="dita"/>.

Best practices when deploying on AWS are available xref:couchbase-aws-best-practices.adoc[here].
For other resources detailing the Amazon Web Services and Couchbase partnership, see our https://www.couchbase.com/partners/aws[partners page^].
