[#section-new-feature-810-platform-support]
=== Platform Support

Couchbase Server 8.1 adds support for the following operating systems:

* TDB

For more information about supported operating systems, see xref:install:install-platforms.adoc[].

=== Global Secondary Indexing (GSI) Vector Indexes

TDB

=== Data Service Changes

Couchbase Server 8.1 introduces several new features for the Data Service.

TDB


=== Non-Data Services

Couchbase Server 8.1 release has key non-Data Services enhancements. 


=== Couchbase Cluster

Couchbase Server 8.1 release has added cluster enhancements and diagnostic capabilities.

[#unstable-metric]
==== New Metric to Detect Unstable Nodes

Couchbase Server 8.1.0 introduces a new metric, `cm_node_unreachable_total`, to help you monitor for unstable nodes in your cluster.
An unstable node periodically becomes unavailable but recovers before the auto failover timeout expires.
This metric counts the number of times a node has been unable to reach another node in the cluster.
By monitoring it, you can identify nodes that are having issues before they become unavailable for long enough to be automatically failed over.

See xref:learn:clusters-and-availability/unstable-nodes.adoc[] for more information about using this metric to identify unstable nodes.

=== XDCR

Couchbase Server 8.1 release has key cross datacenter replication (XDCR) enhancements and diagnostic capabilities. 

TDB.

=== Security and Authentication

Couchbase Server 8.1 release has key security and authentication enhancements.

TDB.

=== Query Service

Couchbase Server 8.1 release adds these Query Service features. 


TDB.

=== Search Service

Couchbase Server 8.1 introduces several new features for the xref:search:search.adoc[Search Service].

TDB.
