[#section-new-feature-800-couchbase-cluster]
=== Couchbase Cluster



https://jira.issues.couchbase.com/browse/MB-61457[MB-61457]::
The following settings have been added to the `/pools/default/buckets` REST APIs.
+

|===
|Argument Name |Type |Valid values |Default

|`accessScannerEnabled`
|bool
|true, false
|true

|`expiryPagerSleepTime`
|int
|0 to maxInt
|600

|`warmupBehavior`
|string
|background, blocking, none
|background

|`memoryLowWatermark`
|int
|50 to 89
|75

|`memoryHighWatermark`
|int
|51 to 90
|85
|===

https://jira.issues.couchbase.com/browse/MB-61946[MB-61946]::
The `/pools/default/nodeServices` endpoint results now include the UUID and name of the cluster.
+
[source, shell]
----
 "clusterUUID": "0e23ca344ef4aafaf2b48ed90c5335ef",
  "clusterName": "CouchbaseTestLab"
----

https://jira.issues.couchbase.com/browse/MB-62583[MB-62583]::
The `/prometheus_sd_config` endpoint  provides a new option “clusterLabels” which species the cluster name and cluster UUID be returned. Prometheus will use them as labels in time series data. This provides a method to guarantee uniqueness for stats with the same name gathered from multiple clusters.
+
[source, shell]
----
curl --get -u <username:password> \
    https://<ip-address-or-domain-name>:<port-number>/prometheus_sd_config
    -d disposition=[attachment|inline]
    -d network=[default|external]
    -d port=[insecure|secure]
    -d type=[json|yaml]
    -d clusterLabels=none|uuidOnly|uuidAndName
----

[#section-new-feature-data-service]
=== Data Service


https://jira.issues.couchbase.com/browse/MB-9418[MB-9418]::
The previous warmup behavior was to load values and not complete warmup until the Bucket reaches one of:
+
--
* `warmup_min_memory_threshold` — defaults to 100%.
* `warmup_min_items_threshold` — defaults to 100%.
* The bucket low watermark (i.e., 75% of the Bucket quota)
--
+
*Resolution:* Couchbase Server adds a new parameter, `warmup_behavior`. 
This new parameter can be used to change the thresholds using a single command. 
+
`warmup_behavior` takes one of three settings:
+
[horizontal]
`blocking`:::
Warmup behaves the same as it did before with no background warmup
`background`:::
Warmup now loads items in the background, allowing the bucket to have write availability much quicker than blocking.
`none`:::
Warmup is disabled; the bucket comes online with no items loaded.

https://jira.issues.couchbase.com/browse/MB-64071[MB-64071]::
Couchbase Server has a new metric
tracking the version information from a user agent character string connected to the data service.
This appears at the cluster’s `/metrics` endpoint and supplies a count of the top connected clients.
For example, in this case the `Java SDK 3.7.6` has connected once and the `Golang SDK core IO` has connected three times:
+
[source, shell]
----
# TYPE kv_current_external_client_connections untyped 
kv_current_external_client_connections\{sdk="gocbcore/v10.5.2"} 3 
kv_current_external_client_connections\{sdk="java/3.7.6"} 1

----
+
To use this most effectively, it should be captured in a time-series to observe changes in the counter over time.
This will avoid misinterpretation of the metric, so that clients that connected long ago
but are no longer connected will not be considered.
+
The metric includes the first 32 characters sent by any clients up to the first space character
and limits the number of metrics to 100. 
Additional information sent by clients at connection time can be found in the logs.

[#section-new-feature-800-disk-limits]
https://jira.issues.couchbase.com/browse/MB-59113[MB-59113] Prevent buckets from causing nodes to run out of disk space::
 You can configure Couchbase Server to prevent writes to buckets from consuming all of the disk space in a node.
 You set a minimum amount of space every node must have free in the filesystem used by the data service.
 If the node's has less free space than this limit, Couchbase Server prevents  writes to buckets.
 Even if you do not set this limit, Couchbase Server now  alerts you when a node starts to run out of disk space.
 See xref:learn:buckets-memory-and-storage/storage-settings.adoc#filesystem-free-space-and-usage-limits[Filesystem Free Space and Usage Limits] for more information.


[#section-new-feature-800-XDCR]
=== XDCR
https://jira.issues.couchbase.com/browse/MB-61048[MB-61048]::
Once faulty remote cluster credentials are fixed, XDCR will now be able to more quickly restart replications that depend on the repaired references.

[#section-new-feature-800-query-service]
=== Query Service

https://jira.issues.couchbase.com/browse/MB-63459[MB-63459]::
New to `8.0.0` is the ability to manipulate document extended attributes (xattrs) via a common SQL++ statement.
+
`INSERT` and `UPSERT` statement options may now include a “xattrs” object element detailing additions and changes to the xattrs (omissions do not delete xattrs).
+
The `UPDATE` statement now supports `SET` and `UNSET` of `meta().xattrs.+{attribute}+ elements.`

[#section-new-feature-800-vector-search]
=== Vector Search

* On x86 platforms, Vector Search now uses the processor's Advanced Vector Extensions 2 (AVX2) feature to improve performance.
Because of this change,  Couchbase Server running on x86 platforms requires a processor that supports these AVX2 instructions.
For more information, see xref:install:pre-install.adoc#vector_cpu_requirements[Vector Search CPU Requirements].

[#section-new-feature-800-index-service]
=== Index Service

https://jira.issues.couchbase.com/browse/MB-60953[MB-60953]::
We have improved the creation of large replicated partitioned index definitions
to create all replicas and partitions in the same iteration,
rather than doing it asynchronously in the background.
This leads to better utilization of DCP streams.


[#section-new-features-800-roles]
=== Roles

To support new features, Couchbase Server 8.0 has added, removed, or changed some roles:

https://jira.issues.couchbase.com/browse/MB-64960[MB-64960]::
The new Application Telemetry Writer (`application_telemetry_writer`) role supports the new application telemetry feature.
Users with this role can call the telemetry endpoint to report telemetry to Couchbase Server.

https://jira.issues.couchbase.com/browse/MB-65045[MB-65045]::
The new Query List Index (`query_list_index`) lets the user list indexes without being able to alter them. 

https://jira.issues.couchbase.com/browse/MB-63584[MB-63584]::
The new Query Manage System Catalog (`query_manage_system_catalog`) role lets the user manage the system catalogs created by the new query workload report feature.


https://jira.issues.couchbase.com/browse/MB-59606[MB-59606]::
Couchbase Server 8.0 adds, removes, and changes some roles to split user management privileges from other security administration privileges.
These changes are necessary to allow users to backup and restore users without requiring them to have the Full Admin role. 

+
The following two roles have been removed:

+
--
* Local User Security Admin (`security_admin_local`)
* External User Security Admin (`security_admin_external`)
--
+
Couchbase Server adds the following three roles to replace the removed roles:

+
--
* Security Admin (`security_admin`) has all of the non-user-related security privileges as the old Local User Security Admin and External User Security Admin roles had.
* Local User Admin (`user_admin_local`) lets a user manage users and groups defined in the local authentication domain.  
It does not have the other security privileges that the old Local User Security Admin role.
* External User Admin (`user_admin_external`) lets a user manage users defined in the external authentication domain. 
It does not have the other security privileges that the old External User Security Admin had.
--
+
In addition, the Backup Full Admin (`backup_admin`) role now lets a user backup and restore users. 
In prior versions of Couchbase Server, users required the Full Admin role to be able to backup and restore users.

+
Couchbase Server 8.0 upgrade process reassigns roles to users who have the now-deleted roles:

+
* Users with the deleted Local User Security Admin role get the new Local User Admin and Security Admin roles.
* Users with the deleted External User Security Admin role get the new External User Admin and  Security Admin roles.

+
These role changes ensure that the users with the Local User Security Admin or External User Security Admin roles still have the same privileges they did before the upgrade.

+
The Backup Service in  Couchbase Sever 8.0 or later also performs these changes when restoring a backup from a pre-8.0 Couchbase Server version. 

+
NOTE: If the user restoring a backup does not have a role that allows them to restore specific roles to a user in the backup, the backup server skips restoring that user. 

See xref:learn:security/roles.adoc[] for more information.

[#section-new-feature-800--tools]
=== Tools

https://jira.issues.couchbase.com/browse/MB-44863[MB-44863]::
When using the Backup Service, you can now configure a retention period for a repository,
automating the deletion of old backups if desired.
You can choose a default retention period,
and you can choose to override this default for individual backups if desired.


https://jira.issues.couchbase.com/browse/MB-60337[MB-60337]::
Previously,
it was possible to remove backups which would cause dependent incremental backups
to become invalid if they depended on those deleted backups.
With this release, such deletes are prevented by default but can be overridden with the new `--disable-safe-remove-check` flag

https://jira.issues.couchbase.com/browse/MB-60676[MB-60676]::
When there are multiple backup service nodes in a cluster,
we now prevent more than one job for a repo from being run concurrently.
Previously this could happen, even though it always results in one of the jobs failing.

https://jira.issues.couchbase.com/browse/MB-61073[MB-61073]::
It is now possible to change the plan used by a repository.
The repository first needs to be paused, and then the plan can be changed,
and the repository resumed, where it will now execute the tasks from its new plan.

