=== Platform Support

* Couchbase Server 7.6 adds support for the following platforms:
+
--
** Alma Linux 9
** Debian Linux 12 (Bookworm)
** Rocky Linux 9
** macOS 13 "Ventura"
** macOS 14 "Sonoma"
--
+
See xref:install:install-platforms.adoc[] for a full list of supported platforms.

* In response to
 https://nvd.nist.gov/vuln/detail/CVE-2023-5363[CVE-2023-5363^] and
  https://nvd.nist.gov/vuln/detail/CVE-2023-5678[CVE-2023-5678^],
  OpenSSL upgraded to version{nbsp}3.1.4.
+
NOTE: This update changes the available ciphers for TLS connections.
If you have not updated your client applications to use recent TLS libraries,
you may experience an inability to connect and TLS handshake failures.
Before upgrading, we recommend testing compatibility in a separate environment –
especially if you are unsure that your platform TLS (OpenSSL,
Java Secure Socket Extensions, .NET Security Provider, etc.) has compatible ciphers.

=== Cluster Manager

* A required minimum can be established for the number of replicas configured for a bucket.
See xref:rest-api:setting-minimum-replicas.adoc[Setting a Replica-Minimum].

* In each user-created or sample bucket, a `_system` scope is created and maintained by default. This scope contains collections used by Couchbase services, for service-specific data.
See xref:learn:data/scopes-and-collections.adoc#system-scope-and-its-collections[_system Scope and its Collections].

* A _rank_ can be assigned to each bucket on the cluster, whereby each bucket's handling by the _rebalance_ process is appropriately prioritized.
Assignment can be made by means of either the CLI or the REST API.
This feature allows the cluster's most mission-critical data to be rebalanced most quickly.
See xref:rest-api:rest-bucket-create.adoc[Creating and Editing Buckets].

* You can now have Couchbase Server prune rotated audit logs after a period of time.
You set how long  Couchbase Server should keep audit logs by using the new `pruneAge` parameter for the `/settings/audit` endpoint.
The default value of 0 means that Couchbase Server does not prune audit logs.
See xref:rest-api:rest-auditing.adoc[Configure Auditing].

* You can add one or more arbiter nodes to a cluster.
include::learn:partial$arbiter-node-benefits.adoc[]

* The `sampleBuckets/install` REST API method now returns a JSON object containing the list of tasks Couchbase Server started to load the buckets.
In addition, the `/pools/default/tasks` REST API endpoint now takes an optional `taskId` parameter to view details about a sample bucket loading task.
See xref:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-rest-api[Install Sample Buckets with the REST API] for more information.

=== Backup and Restore

* The Role-Based Access Control (RBAC) REST API has a new `backup` endpoint that lets you backup and restore user and user groups. See xref:rest-api:rbac.adoc#backup-and-restore-users-and-groups[Backup and Restore Users and Groups].

* The `cbbackupmgr` command has a new `--enable-users` flag that backs up user groups and users including roles and permissions.
When you supply the new argument, `cbbackupmgr` saves user passwords in the backup in a hashed format.
When restoring a backup, `cbbackupmgr` defaults to not overwriting existing users in the database with identically named users in the backup.
You can change this default behavior using the new `--overwrite-users` command-line argument.
See xref:backup-restore:cbbackupmgr-config.adoc[cbbackupmgr config] and xref:backup-restore:cbbackupmgr-restore.adoc[cbbackupmgr restore] for more about user backup.

* The `cbbackupmgr` encrypted backups feature is now GA for both cbbackupmgr CLI and the Backup Service. See xref:backup-restore:cbbackupmgr-encryption.adoc[Backup Encryption].

=== Cross Data Center Replication (XDCR)

* Node-connectivity can be checked, prior to the creation of an XDCR reference.
See xref:rest-api:rest-xdcr-connection-precheck.adoc[Checking Connections].

* Binary documents can optionally be included in, or excluded from XDCR replications.
See xref:learn:clusters-and-availability/xdcr-overview.adoc#xdcr-filter-binary[Filtering Binary Documents].

=== Performance

* You can now migrate buckets from one storage backend to another.
This feature supports migrating buckets from Couchstore to Magma and from Magma to Couchstore.
You can migrate buckets while the database continues running.
To complete the migration you must trigger a swap rebalance or a graceful failover followed by a full recovery on each node that contains the bucket.
See xref:manage:manage-buckets/migrate-bucket.adoc[].

=== Security and Authentication

* Security settings now provide additional parameters, for the configuration of Couchbase-Server user-password hashing.
See xref:rest-api:rest-setting-security.adoc[Configure On-the-Wire Security].

* Credentials for Couchbase-Server internal users can now be rotated at any time, by means of the REST API.
See xref:rest-api:rest-rotate-internal-credentials.adoc[Rotate Internal Credentials].

* LDAP authentication now supports using regular expressions to map users to LDAP users and groups.
You can supply multiple regular expressions that Couchbase attempts to match against the user name supplied during an authentication attempt.
This feature gives you greater flexibility when authenticating users.
For example, you can use a regular expression to map the domain name in an email address to an LDAP organization.
See xref:manage:manage-security/configure-ldap.adoc#ldap-advanced-mapping[Advanced Query] under xref:manage:manage-security/configure-ldap.adoc#enable-ldap-user-authentication[User Authentication Enablement].

* The Couchbase Server Web Console now supports using Structured Authentication Markup Language (SAML) for authentication.
When you enable SAML authentication, a btn:[Sign In Using SSO] button appears on the Web Console login screen.
This button lets users who have already authenticated with the SAML identity provider (Okta, for example) to skip having to enter credentials.
See xref:learn:security/authentication-domains.adoc#saml-authentication[SAML Authentication] for more information.

* Couchbase Server's LDAP support now has a setting that turns on and off TLS middlebox compatibility.
This setting controls low-level network communication options when Couchbase Server securely connects to an LDAP server through intermediate systems such as proxies and firewalls.
See xref:manage:manage-security/configure-ldap.adoc#advanced-settings[Advanced Settings] on the xref:manage:manage-security/configure-ldap.adoc[] page for more information about this setting.

* Couchbase Server now supports using Public-Key Cryptography Standard (PKCS) #12 format certificates for node certificates.
This format lets you bundle the node's private key, public key, and certificate chain into a single file.
See xref:learn:security/certificates.adoc#pkcs12[PKCS #12 Certificates for Nodes] for more information.

* Couchbase Server now supports the X.509 Elliptic Curve Key cipher suites.
Elliptic Curve Key ciphers are less resource-intensive than other cipher suites.
They're useful when communicating with resource-constrained devices such as IoT hardware.
See xref:learn:security/certificates.adoc#private-key-formats[Private Keys] for more information.

* Couchbase Server no longer supports TLS versions 1.0 and 1.1.
When upgrading to version 7.6 or later, the upgrade process automatically sets  `minTLSVersion` to `tlsv1.2` if it's set to `tlsv1` or `tlsv1.1`.
Before you upgrade, be sure all the clients you use support TLS 1.2 or greater.
See xref:learn:security/on-the-wire-security.adoc[] for more information.

* To prevent https://en.wikipedia.org/wiki/Lucky_Thirteen_attack[LUCKY13 attacks^], Couchbase Server 7.6 removes the following ciphers from the default cipher list:
** TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
** TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
** TLS_RSA_WITH_AES_256_CBC_SHA
** TLS_RSA_WITH_AES_128_CBC_SHAa

* You can now enable alerts for certificate expiration.
When enabled, Couchbase Server alerts you when server, node, or XDCR certificates are within 30 days of expiration.
You can change the alert period via the new `certExpirationDays` alert limit setting.
Couchbase Server sends a second alert when certificates expire.
See xref:learn:security/certificates.adoc#certificate-expiration[Certificate Expiration] for more information.

* Couchbase Server now defaults to using the (https://en.wikipedia.org/wiki/Argon2)[Argon2id^] algorithm to hash passwords for new users. 
This hashing algorithm is more secure than the SHA1 algorithm used to hash passwords in earlier server versions.

* If you upgrade a database to Couchbase Server 7.6 or later, it continues to use the older SHA1 hashing algorithm for existing user passwords.
You can enable a new setting that has Couchbase Server migrate user passwords from SHA1 to Argon2id when a user authenticates.
This setting works only if the entire cluster  is running Couchbase Server version 7.6 or later.
For more information, see xref:learn:security/authentication-overview.adoc#password-hash-migration[Automatic Password Hash Migration]. 


=== Metrics

* Couchbase Server has a new service discovery endpoint to help you configure the Prometheus event monitoring system.
The old endpoint, named `/prometheus_sd_config.yaml` is now deprecated.
The new endpoint is able to produce the same output as the old endpoint and has additional features.
See xref:manage:monitor/set-up-prometheus-for-monitoring.adoc[Configure Prometheus to Collect Couchbase Metrics].

* Disk usage statistics now  include transient files in progress, state files, and configuration files.

=== Index Service

* You can choose to have the rebalance process move an index's files between nodes instead of rebuilding them from scratch.
This setting improves rebalance performance as moving the files is faster than rebuilding them.
See xref:learn:clusters-and-availability/rebalance.adoc#index-rebalance-methods[Index Rebalance Methods].

=== Search Service

* Couchbase Server 7.6 introduces Vector Search to enable AI integration, semantic search, and the RAG framework.
A developer-friendly vector indexing engine exposes a vector database and search functionality.
With Couchbase Vector Search, you can enable fast and highly accurate semantic search, ground LLM responses in relevant data to reduce hallucinations, and enhance or enable use cases like personalized searches in e-commerce and media & entertainment, product recommendations, fraud detection, and reverse image search.
You can also enable full access to an AI ecosystem with a Langchain integration, the most popular open-source framework for LLM-driven applications.
+
A Vector Search database includes:
+
** Standard Couchbase vertical/horizontal scaling
** Indexing capable of efficient Insert/Update/Removal of Items (or documents)
** Storage of raw Embedding Vectors in the Data Service in the documents themselves
** Querying Vector Indexes (REST and UI via a JSON object/fragment, Couchbase SDKs, and {sqlpp})
** {sqlpp}/N1QL integration
** Third-party framework integration: Langchain (later Llamaindex + others)
** Full support for Replicas Partitions and file-based Rebalance

NOTE: Vector Search is currently only supported on Couchbase Server 7.6.0 deployments running on Linux platforms.
MacOS and Windows platforms are not supported. 

For more information about vector search, see xref:vector-search:vector-search.adoc[]

=== Data Service

* Introduces KV Range Scan, used to retrieve all documents in a specified range directly from the Data service.
Note that in this initial version, you will achieve better performance using a direct fetch or retrieval from a Query with an Index.
See the xref:java-sdk:howtos:kv-operations.adoc#kv-range-scan[SDK docs] for more information.

* Two changes in Couchbase Server 7.6 affect the `maxTTL` setting for collections:

** In earlier versions, you could only set a collection's `maxTTL` setting when creating the collection.
You can now change the `maxTTL` setting on a collection after creation.
** You can now set a collection's `maxTTL` to -1 to prevent a bucket's non-zero `maxTTL` setting from causing documents in the collection to expire automatically.
This new setting is useful if you want most of the documents in a bucket to automatically expire, but want to prevent the documents in one or more collections from expiring by default.

+
See xref:learn:data/expiration.adoc[] for more information.

=== Query Service

* {sqlpp} language additions:

** OFFSET clause added to the DELETE statement.
See xref:n1ql:n1ql-language-reference/delete.adoc[].

** GROUP AS clause added to the GROUP BY clause.
See xref:n1ql:n1ql-language-reference/groupby.adoc[].

** FORMALIZE() function.
See xref:n1ql:n1ql-language-reference/metafun.adoc#formalize[FORMALIZE()].

** Multi-byte aware string functions.
See xref:n1ql:n1ql-language-reference/stringfun.adoc[].

** Support for sequences.
See xref:n1ql:n1ql-language-reference/sequenceops.adoc[].

** EXPLAIN FUNCTION statement.
See xref:n1ql:n1ql-language-reference/explainfunction.adoc[].

* cbq shell additions.
See xref:n1ql:n1ql-intro/cbq.adoc[cbq]:

** The `-query_context` command line option.
** The `-advise` command line option.

* The WITH clause adds support for recursive CTEs.
See xref:n1ql:n1ql-language-reference/with-recursive.adoc[].

* The CREATE COLLECTION statement adds support for maxTTL.
See xref:n1ql:n1ql-language-reference/createcollection.adoc[].

* The `/clusterInit` endpoint in the Nodes and Clusters REST API adds support for Query memory quotas.
See xref:rest-api:rest-initialize-cluster.adoc[].

* Named and positional parameters can now be prefixed by `$` or `@` in a query.
See xref:settings:query-settings.adoc#section_srh_tlm_n1b[Named Parameters and Positional Parameters].

* The `system:indexes` catalog now enables you to find the number of replicas configured for each index.
See xref:n1ql:n1ql-intro/sysinfo.adoc#querying-indexes[Query Indexes].

* The Query Service adds cluster-level and node-level parameters to limit the size of explain plans in the cache.
See xref:settings:query-settings.adoc#queryPreparedLimit[queryPreparedLimit] and xref:settings:query-settings.adoc#prepared-limit[prepared-limit].

* The Query Service adds support for sequential scans, controlled by RBAC, which enables querying without an index.
See xref:learn:services-and-indexes/indexes/query-without-index.adoc[].

* The node-level N1QL Feature Control parameter now accepts hexadecimal strings or decimal integers.
See xref:settings:query-settings.adoc#n1ql-feat-ctrl[n1ql-feat-ctrl].

* Queries can now read from replica vBuckets when active vBuckets are inaccessible.
The Query service adds new cluster-level, node-level, and request-level parameters to configure this feature.
See xref:manage:manage-settings/general-settings.adoc#query-settings[Query Settings].

* The CREATE FUNCTION statement now enables users to create a {sqlpp} user-defined function and the corresponding external JavaScript code in a single operation, without having to create an external library.
See xref:n1ql:n1ql-language-reference/createfunction.adoc#sql-managed-user-defined-functions[{sqlpp} Managed User-Defined Functions].

* When a query executes a user-defined function, profiling information is now available for any queries within the UDF.
See xref:manage:monitor/monitoring-n1ql-query.adoc[].

* The Query service collects statistics for the cost-based optimizer automatically when an index is created or built.
See xref:n1ql:n1ql-language-reference/cost-based-optimizer.adoc[].

* The ORDER BY and GROUP BY operations overspill to disk if they exceed the Query service memory quota.

=== Eventing Service

* The optional parameter `{ "self_recursion": true }` can be used with the INSERT, UPSERT, and REPLACE advanced operations to prevent the suppression of recursive source bucket mutations.
For more information, see xref:server:eventing:eventing-advanced-keyspace-accessors.adoc#optional-params-recursion[Optional `{ "self_recursion": true }` Parameter].

* The built-in `ANALYTICS()` function allows the Eventing Service to integrate directly with {sqlpp} Analytics.
This integration simplifies Eventing code logic and lets Eventing benefit from the high availability and load balancing of {sqlpp} Analytics.
For more information, see xref:server:eventing:eventing-language-constructs.adoc#analytics_call[`ANALYTICS()` Function Call].

* The advanced TOUCH operation allows you to modify the expiration time of a document without having to access that document first.
For more information, see xref:server:eventing:eventing-advanced-keyspace-accessors.adoc#advanced-touch-op[Advanced TOUCH Operation].

* The Sub-Document MUTATEIN operation allows you to modify only parts of a document instead of the entire document.
This Sub-Document operation is faster and more efficient than a full-document operation like REPLACE or UPSERT.
For more information, see xref:server:eventing:eventing-advanced-keyspace-accessors.adoc#advanced-subdoc-array-op[Sub-Document MUTATEIN Operation].

=== Analytics

[#power-bi-connector-1-0-release]
* Power BI Connector version{nbsp}1.0 released.
(xref:power-bi-connector:ROOT:index.adoc[Power BI Connector documentation])
+
You can download the installation package from the following location: +
+
[horizontal]
Binaries::
https://packages.couchbase.com/releases/couchbase-powerbi-connector/1.0/couchbase-powerbi-connector-1.0.mez[powerbi-connector-1.0.mez]
Binaries SHAs::
https://packages.couchbase.com/releases/couchbase-powerbi-connector/1.0/couchbase-powerbi-connector-1.0.mez.sha256[powerbi-connector-1.0.mez.sha256]

=== Install & Upgrade

* Due to an Erlang compatibility issue, you cannot directly upgrade to Couchbase Server 7.6 from version 6.5 through 7.0.
To upgrade a database running one of these earlier versions to 7.6, first upgrade it to Couchbase Server 7.1 or 7.2.
See xref:install:upgrade.adoc[] for more information.

=== Couchbase Server Community Edition

* You can no longer set the `sendStats` to `false` in Couchbase Server Community Edition clusters.
You can still set `sendStats` to `false` on Couchbase Server Enterprise Edition clusters.
