[#backup_762]
=== Backup

* Users with the xref:learn:security/roles.adoc#read-only-admin[Read-Only Admin] role can now read backup information from the following Backup Service REST API endpoints:

** xref:rest-api:backup-get-cluster-info.adoc[`/api/v1/cluster/self`]
** xref:rest-api:backup-manage-config.adoc[`/api/v1/config`]
** xref:rest-api:backup-get-repository-info.adoc[`/api/v1/cluster/self/repository/{repo-state}`]
** xref:rest-api:backup-get-task-info.adoc[`/api/v1/cluster/self/repository/{repo-state}/{task-name}/taskHistory`]
** xref:rest-api:backup-get-plan-info.adoc[`/api/v1/plan/`]

[#index_762]
=== Index Service

* In Couchbase Server Versions 7.6.0 and 7.6.1, enabling file-based index rebalance prevented controlling which Index Service nodes contain an index. 
Version 7.6.2 removes this restriction.
Having file-based index rebalance enabled no longer prevents you from using the `WITH <node>` clause of the `ALTER INDEX` and `CREATE INDEX` SQL++ statements.
See xref:learn:clusters-and-availability/rebalance.adoc#index-rebalance-methods[Index Rebalance Methods] for more information.
