[#section-new-feature-800-platform-support]
=== Platform Support

Couchbase Server 8.0 adds support for the following operating systems:

* Alma Linux 10
* Debian Linux 13
* macOS 15 "Sequoia" (for development and testing only)
* Oracle Linux 10
* RHEL 10
* Rocky Linux 10
* Windows Server 2025

Couchbase Server 8.0 no longer supports the following operating systems:

* Amazon Linux 2
* macOS 12 "Monterey"
* SUSE Linux Enterprise Server (SLES) 12
* Ubuntu 20.04 LTS
* Windows 10
* Windows Server 2019

For more information about supported operating systems, see xref:install:install-platforms.adoc[].

[#section-new-feature-800-couchbase-cluster]
=== Couchbase Cluster


[#anchor-61457]
https://jira.issues.couchbase.com/browse/MB-61457[MB-61457]::
The following settings have been added to the `/pools/default/buckets` REST APIs.
+
|===
|Argument Name |Type |Valid values |Default

|`accessScannerEnabled`
|bool
|true, false
|true

|`expiryPagerSleepTime`
|int
|0 to maxInt
|600

|`warmupBehavior`
|string
|background, blocking, none
|background

|`memoryLowWatermark`
|int
|50 to 89
|75

|`memoryHighWatermark`
|int
|51 to 90
|85
|===
+
The above new settings are added and made accessible through the REST API.
For more information, see the xref:rest-api:rest-bucket-create.adoc[Creating and Editing Buckets] and xref:learn:buckets-memory-and-storage/memory.adoc[Memory].
The settings `warmup_min_items_threshold`, `warmup_min_memory_threshold`, `exp_pager_stime`, `mem_high_wat`, and `mem_low_wat` are removed from `cbepctl`.
+
The same changes in the warmup behavior settings are applicable to the Data Services.
For more information, see xref:anchor-9418[MB-9418].

https://jira.issues.couchbase.com/browse/MB-61946[MB-61946]::
The `/pools/default/nodeServices` endpoint results now include the UUID and name of the cluster.
+
[source, shell]
----
 "clusterUUID": "0e23ca344ef4aafaf2b48ed90c5335ef",
  "clusterName": "CouchbaseTestLab"
----

https://jira.issues.couchbase.com/browse/MB-62583[MB-62583]::
The `/prometheus_sd_config` endpoint  provides a new option “clusterLabels” which species the cluster name and cluster UUID be returned. Prometheus will use them as labels in time series data. This provides a method to guarantee uniqueness for stats with the same name gathered from multiple clusters.
+
[source, shell]
----
curl --get -u <username:password> \
    https://<ip-address-or-domain-name>:<port-number>/prometheus_sd_config
    -d disposition=[attachment|inline]
    -d network=[default|external]
    -d port=[insecure|secure]
    -d type=[json|yaml]
    -d clusterLabels=none|uuidOnly|uuidAndName
----

[#section-new-feature-800-services]
=== Services

https://jira.issues.couchbase.com/browse/MB-60349[MB-60349]::
Now you can add or remove non-Data Services dynamically on existing nodes in a cluster, without adding or removing nodes.
Rebalancing is automatically triggered to distribute service workloads and complete the modification.
These are the services that can be modified:

** `index` (Index Service)
** `n1ql` (Query Service)
** `fts` (Search Service)
** `cbas` (Analytics Service)
** `eventing` (Eventing Service)
** `backup` (Backup Service)

You can modify these services using the Couchbase xref:manage:manage-nodes/modify-services-on-nodes-and-rebalance.adoc#modify-mds-services-from-ui[UI], xref:rest-api:rest-set-up-services-existing-nodes.adoc[REST API], or xref:manage:manage-nodes/modify-services-on-nodes-and-rebalance.adoc#modify-mds-services-using-cli[CLI].

[#section-new-feature-data-service]
=== Data Service

[#mb-62777]
https://jira.issues.couchbase.com/browse/MB-62777[MB-62777] Magma with 128 vBuckets is now the default storage engine::
In earlier versions of Couchbase Server, if you did not specify which storage engine to use when creating a new bucket, it would use Couchstore.
Once you upgrade your entire cluster to Couchbase Server Enterprise 8.0, the default storage engine for new buckets is Magma with 128 vBuckets.

+
Magma buckets with 128 vBuckets is a new feature that provides the advantages of the Magma storage engine while reducing the minimum memory quota. 
Before Couchbase Server 8.0, Magma only supported using 1024 vBuckets and had a minimum memory quota of 1{nbsp}GiB per node.
Buckets that use Magma with 128 vBuckets have a minimum memory quota of 100{nbsp}MiB per node, which is the same as Couchstore.

+
NOTE: These changes do not affect Couchbase Server Community Edition because it does not support the Magma storage engine.

+
This change in the default storage engine does not affect existing buckets.
You can still create buckets that use the Couchstore storage engine or the Magma storage engine with 1024 vBuckets by explicitly specifying them when you create the bucket.

+
See xref:learn:buckets-memory-and-storage/storage-engines.adoc[] for more information about storage engines.

+
.default behavior change
[IMPORTANT] 
====
The new default storage backend for buckets is a behavior change that may cause issues if you rely on the previous behavior.

Before upgrading to Couchbase Server 8.0, consider the following:

* If you have deployment scripts that create buckets without specifying the storage engine, those scripts create Magma buckets with 128 vBuckets instead of Couchstore buckets after the upgrade.
This may affect your deployment if you depend on buckets using the Couchstore storage engine.
* If you have existing deployment scripts that create Magma buckets, in Couchbase Server 8.0 they create buckets with 128 vBuckets instead of the 1024 vBuckets they did previously. 
To have them create the same Magma buckets with 1024 vBuckets they did prior to 8.0, set the number of vBuckets when creating the bucket using the `numVbuckets` parameter in xref:rest-api:rest-bucket-create.adoc#numvbuckets[the REST API] or `--num-vbuckets` in the xref:cli:cbcli/couchbase-cli-bucket-create.adoc[couchbase-cli command line tool]. 
If you can allocate at least 1 GiB of memory for the Magma bucket, you should create a Magma bucket with 1024 vBuckets for better performance at scale.
* You cannot use XDCR to replicate from Magma buckets on pre-8.0 clusters to Magma buckets using 128 vBuckets. 
XDCR in pre-8.0 clusters only supports replication between buckets that contain the same number of vBuckets.
Pre-8.0 versions of Couchbase Server only support Couchstore and Magma buckets with 1024 vBuckets (or 64 vBuckets on macOS).

+
If you're manually deploying a new cluster, set the number of vBuckets to 1024 for any Magma bucket that is the target of a replication from a pre-8.0 cluster.
See xref:manage:manage-buckets/create-bucket.adoc[] for more information about creating buckets.
If you have a deployment script that creates Magma buckets that are an XDCR target for a pre-8.0 cluster, have it set the number of vBuckets to 1024.
To set this value, use the `numVbuckets` parameter in xref:rest-api:rest-bucket-create.adoc#numvbuckets[the REST API] or `--num-vbuckets` in the xref:cli:cbcli/couchbase-cli-bucket-create.adoc[`couchbase-cli` command line tool].
====

https://jira.issues.couchbase.com/browse/MB-38452[MB-38452] Memcached buckets have been removed::
Couchbase Server 8.0 has removed support for Memcached buckets.
They were deprecated in version 6.5.1.
Before upgrading to Couchbase Server 8.0, you must remove any Memcached buckets from your cluster.
You can replace them with ephemeral buckets which are similar to Memcached buckets but support features such as rebalance, backup, query, and eventing.
See the https://docs-archive.couchbase.com/server/6.6/learn/buckets-memory-and-storage/buckets.html#bucket-capabilities[Bucket Capabilities in the Version 6.6 documentation] for a summary of the differences between Memcached and ephemeral buckets.
If you do not remove your Memcached buckets, the upgrade process reports an error message telling you to remove the Memcached buckets before proceeding.

[#anchor-9418]
https://jira.issues.couchbase.com/browse/MB-9418[MB-9418]::
**Configurable Warmup Behavior (Background Warmup):**
+
The new `warmup_behavior` setting, configured using `warmupBehavior` in the REST API, controls when a persistent bucket becomes fully available for `read` and `write` operations after a bucket restart.
This setting replaces multiple warmup threshold parameters with a single configuration point:
+
--
* **background** (default): The bucket becomes fully available as soon as required metadata is loaded from storage.
The bucket’s cache is then filled in the background until memory usage reaches the low watermark (memoryLowWatermark).
* **blocking**: This is the original behaviour.
The bucket becomes read-available as soon as required metadata is loaded from storage, then continues filling the cache until memory usage reaches the low watermark (`memoryLowWatermark`).
The bucket becomes fully available only after this point.
* **none**: Disables warmup.
The bucket becomes fully available as soon as required metadata is loaded from storage.
The cache remains empty.
+
For more information, see xref:learn:buckets-memory-and-storage/memory.adoc#initialization-and-warmup[Initialization and Warmup].
--
+
**API Changes:**
+
The REST API now includes the per-bucket setting `warmupBehavior`.
The previous advanced tuning settings `warmup_min_items_threshold` and `warmup_min_memory_threshold` have been removed from the `cbepctl` interface.
For the REST API information, see xref:rest-api:rest-bucket-create.adoc#warmupbehavior[warmupBehavior].
+
The same changes in the warmup behavior settings are applicable to the Couchbase Cluster.
For more information, see xref:anchor-61457[MB-61457].

https://jira.issues.couchbase.com/browse/MB-64071[MB-64071]::
Couchbase Server has a new metric
tracking the version information from a user agent character string connected to the data service.
This appears at the cluster’s `/metrics` endpoint and supplies a count of the top connected clients.
For example, in this case the `Java SDK 3.7.6` has connected once and the `Golang SDK core IO` has connected three times:
+
[source, shell]
----
# TYPE kv_current_external_client_connections untyped 
kv_current_external_client_connections\{sdk="gocbcore/v10.5.2"} 3 
kv_current_external_client_connections\{sdk="java/3.7.6"} 1

----
+
To use this most effectively, it should be captured in a time-series to observe changes in the counter over time.
This will avoid misinterpretation of the metric, so that clients that connected long ago
but are no longer connected will not be considered.
+
The metric includes the first 32 characters sent by any clients up to the first space character
and limits the number of metrics to 100. 
Additional information sent by clients at connection time can be found in the logs.

[#section-new-feature-800-backup-service]
=== Backup and Restore
https://jira.issues.couchbase.com/browse/MB-44863[MB-44863]::
Backup Service now supports configurable retention periods for repositories and pruning of old backups from the UI and REST API.
A default retention period can be set or overridden for individual backups as needed.
Pruning can be scheduled to run automatically, or it can be run manually.
For more information, see xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc#backup-retention[Retain Backups] and xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc#schedule-backup-pruning[Schedule Pruning].

https://jira.issues.couchbase.com/browse/MB-60337[MB-60337]::
Incremental backups now keep track of which backups they depend on.
You cannot delete a backup if another incremental backup needs it, however, you can choose to override this protection from the UI and REST API.
For more information, see xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc#delete-backups[Delete Backups].

[#section-new-feature-800-XDCR]
=== XDCR

https://jira.issues.couchbase.com/browse/MB-62564[MB-62564]::

`xdcrDiffer` is a diagnostic utility included in the Couchbase Server package.
This utility verifies data consistency between XDCR clusters.
It identifies missing or mismatched documents by comparing metadata and content hashes across source and target clusters.
+
For more information, see xref:manage:pages/manage-xdcr/xdcr-differ.adoc[xdcrDiffer Utility].


https://jira.issues.couchbase.com/browse/MB-62507[MB-62507]::
XDCR supports Generic Services Log Level configuration using the REST API through the `genericServicesLogLevel` settings.
For more information, see xref:rest-api:rest-xdcr-adv-settings.adoc[XDCR Advanced Settings].

[#section-new-features-800-security-authentication]
=== Security and Authentication

https://jira.issues.couchbase.com/browse/MB-16143[MB-16143]::
Couchbase Server Enterprise now supports native encryption at rest.
You can encrypt bucket data, audits, and most logging and configuration information.
You choose which buckets to encrypt and which remain unencrypted.
See xref:learn:security/native-encryption-at-rest-overview.adoc[] for more information.

https://jira.issues.couchbase.com/browse/MB-50939[MB-50939]::
Added support for the Hybrid authentication mode in the certificate-based client authentication.
When Hybrid is selected:
+
--
* Clients can authenticate using either certificates or username/password credentials.
* All nodes must use mutual TLS (mTLS) for inter-node communication.
* The prerequisite is that the property `clusterEncryptionLevel` be set to `all` or `strict`.
--
+
This mode enhances flexibility for clients while enforcing strict security for node-to-node communication.
+
For more information, see xref:manage:manage-security/enable-client-certificate-handling.adoc[Enable Client Certificate Handling].


https://jira.issues.couchbase.com/browse/MB-11575[MB-11575]::
XDCR now supports the identification of Incoming Replications on a cluster.
The Incoming Replications can be:

* Viewed on the XDCR tab of the UI. See xref:manage:manage-xdcr/incoming-xdcr-replications.adoc#view-incoming-replications[View Incoming Replications] in xref:manage:manage-xdcr/incoming-xdcr-replications.adoc[Incoming Replications].
* Retrieved by using the REST API command `GET /xdcr/sourceClusters`. See xref:rest-api:rest-xdcr-list-incoming-replications.adoc[Listing Incoming Replications].

https://jira.issues.couchbase.com/browse/MB-58989[MB-58989]::
XDCR detects and logs concurrent conflicts that occur in different clusters but on the same document version due to independent modifications by locally connected applications during Active-Active replication.
The conflict logs are for your information only.
For more information, see xref:learn:clusters-and-availability/xdcr-conflict-logging-feature.adoc[XDCR Conflict Logging Feature].

[#section-new-feature-800-query-service]
=== Query Service

https://jira.issues.couchbase.com/browse/MB-63459[MB-63459]::
New to `8.0.0` is the ability to manipulate document extended attributes (xattrs) via a common SQL++ statement.
+
`INSERT` and `UPSERT` statement options may now include a “xattrs” object element detailing additions and changes to the xattrs (omissions do not delete xattrs).
+
The `UPDATE` statement now supports `SET` and `UNSET` of `meta().xattrs.+{attribute}+ elements.`

[#section-new-feature-800-vector-search]
=== Vector Search

* On x86 platforms, Vector Search now uses the processor's Advanced Vector Extensions 2 (AVX2) feature to improve performance.
Because of this change,  Couchbase Server running on x86 platforms requires a processor that supports these AVX2 instructions.
For more information, see xref:install:pre-install.adoc#vector_cpu_requirements[Vector Search CPU Requirements].

[#section-new-feature-800-index-service]
=== Index Service

https://jira.issues.couchbase.com/browse/MB-60953[MB-60953]::
We have improved the creation of large replicated partitioned index definitions
to create all replicas and partitions in the same iteration,
rather than doing it asynchronously in the background.
This leads to better utilization of DCP streams.


[#section-new-features-800-roles]
=== Roles

To support new features, Couchbase Server 8.0 has added, removed, or changed some roles:

https://jira.issues.couchbase.com/browse/MB-64960[MB-64960]::
The new Application Telemetry Writer (`application_telemetry_writer`) role supports the new application telemetry feature.
Users with this role can call the telemetry endpoint to report telemetry to Couchbase Server.

https://jira.issues.couchbase.com/browse/MB-65045[MB-65045]::
The new Query List Index (`query_list_index`) lets the user list indexes without being able to alter them. 

https://jira.issues.couchbase.com/browse/MB-63584[MB-63584]::
The new Query Manage System Catalog (`query_manage_system_catalog`) role lets the user manage the system catalogs created by the new query workload report feature.


https://jira.issues.couchbase.com/browse/MB-59606[MB-59606]::
Couchbase Server 8.0 adds, removes, and changes some roles to split user management privileges from other security administration privileges.
These changes are necessary to allow users to backup and restore users without requiring them to have the Full Admin role. 

+
The following two roles have been removed:

+
--
* Local User Security Admin (`security_admin_local`)
* External User Security Admin (`security_admin_external`)
--
+
Couchbase Server adds the following three roles to replace the removed roles:

+
--
* Security Admin (`security_admin`) has all of the non-user-related security privileges as the old Local User Security Admin and External User Security Admin roles had.
* Local User Admin (`user_admin_local`) lets a user manage users and groups defined in the local authentication domain.  
It does not have the other security privileges that the old Local User Security Admin role.
* External User Admin (`user_admin_external`) lets a user manage users defined in the external authentication domain. 
It does not have the other security privileges that the old External User Security Admin had.
--
+
In addition, the Backup Full Admin (`backup_admin`) role now lets a user backup and restore users. 
In prior versions of Couchbase Server, users required the Full Admin role to be able to backup and restore users.

+
Couchbase Server 8.0 upgrade process reassigns roles to users who have the now-deleted roles:

+
* Users with the deleted Local User Security Admin role get the new Local User Admin and Security Admin roles.
* Users with the deleted External User Security Admin role get the new External User Admin and  Security Admin roles.

+
These role changes ensure that the users with the Local User Security Admin or External User Security Admin roles still have the same privileges they did before the upgrade.

+
The Backup Service in  Couchbase Sever 8.0 or later also performs these changes when restoring a backup from a pre-8.0 Couchbase Server version. 

+
NOTE: If the user restoring a backup does not have a role that allows them to restore specific roles to a user in the backup, the backup server skips restoring that user. 

See xref:learn:security/roles.adoc[] for more information.

[#section-new-feature-800--tools]
=== Tools

https://jira.issues.couchbase.com/browse/MB-44863[MB-44863]::
When using the Backup Service, you can now configure a retention period for a repository,
automating the deletion of old backups if desired.
You can choose a default retention period,
and you can choose to override this default for individual backups if desired.


https://jira.issues.couchbase.com/browse/MB-60337[MB-60337]::
Previously,
it was possible to remove backups which would cause dependent incremental backups
to become invalid if they depended on those deleted backups.
With this release, such deletes are prevented by default but can be overridden with the new `--disable-safe-remove-check` flag

https://jira.issues.couchbase.com/browse/MB-60676[MB-60676]::
When there are multiple backup service nodes in a cluster,
we now prevent more than one job for a repo from being run concurrently.
Previously this could happen, even though it always results in one of the jobs failing.

https://jira.issues.couchbase.com/browse/MB-61073[MB-61073]::
It is now possible to change the plan used by a repository.
The repository first needs to be paused, and then the plan can be changed,
and the repository resumed, where it will now execute the tasks from its new plan.




