[#section-new-feature-810-platform-support]
=== Platform Support

Couchbase Server 8.5 adds support for the following operating systems:

* TBD

For more information about supported operating systems, see xref:install:install-platforms.adoc[].

=== Global Secondary Indexing (GSI) Vector Indexes

TBD

=== Data Service Changes

Couchbase Server 8.5 introduces several new features for the Data Service.

TBD


=== Non-Data Services

Couchbase Server 8.5 release has key non-Data Services enhancements. 


=== Couchbase Cluster

Couchbase Server 8.5 release has added cluster enhancements and diagnostic capabilities.

[#unstable-metric]
==== New Metric to Detect Unstable Nodes

Couchbase Server 8.5.0 introduces a new metric, `cm_node_unreachable_total`, to help you monitor for unstable nodes in your cluster.
An unstable node periodically becomes unavailable but recovers before the auto failover timeout expires.
This metric counts the number of times a node has been unable to reach another node in the cluster.
By monitoring it, you can identify nodes that are having issues before they become unavailable for long enough to be automatically failed over.

See xref:learn:clusters-and-availability/unstable-nodes.adoc[] for more information about using this metric to identify unstable nodes.

=== XDCR

Couchbase Server 8.5 release has key cross datacenter replication (XDCR) enhancements and diagnostic capabilities. 

TBD.

=== Security and Authentication

Couchbase Server 8.5 release has key security and authentication enhancements.

TBD.

=== Query Service

Couchbase Server 8.5 release adds these Query Service features. 


TBD.

=== Search Service

Couchbase Server 8.5 introduces several new features for the xref:search:search.adoc[Search Service].

TBD.

=== Backup & Restore

Couchbase Server 8.5 introduces several new features for xref:backup:backup.adoc[Backup and Restore].

* The new continuous backup feature supplements traditional periodic backups by frequently backing up changes to Magma buckets.
This backup can limit the loss of data updates that occur between full and incremental backups.
In addition to backing up data, it also backs up the timestamps of mutations.
These timestamps let you perform Point-in-Time Recovery (PITR) to restore the Magma bucket's data to the state it was in at a specific moment.
For more information, see xref:learn:services-and-indexes/services/continuous-backup.adoc[].
