@startuml query_service

skinparam defaultTextAlignment center

rectangle Client

rectangle "Query Service"{
  rectangle Parse [
    Parse


    ▢



  ]
  rectangle Plan [
    Plan


    ▢



  ]
  rectangle Scan [
    Scan


    ▢

    ▢

  ]
  rectangle Fetch [
    Fetch


    ▢
    ▢
    ▢
    ▢
  ]
  rectangle Join [
    Join


    ▢
    ▢
    ▢
    ▢
  ]
  rectangle Filter [
    Filter


    ▢
    ▢
    ▢
    ▢
  ]
  rectangle PreAggregate [
    Pre-
    Aggregate

    ▢
    ▢
    ▢
    ▢
  ]
  rectangle Aggregate [
    Aggregate


    ▢



  ]
  rectangle Sort [
    Sort


    ▢
    ▢
    ▢
    ▢
  ]
  rectangle Offset [
    Offset


    ▢
    
    

  ]
  rectangle Limit [
    Limit


    ▢
    
    
    
  ]
  rectangle Project [
    Project


    ▢
    ▢
    ▢
    ▢
  ]
}

database "Data\nService" as Data
database "Index\nService" as Index
database "Search\nService" as Search

() " " as End

Client .d.> Parse
Parse -> Plan
Plan -> Scan
Scan -> Fetch
Fetch -> Join
Join -> Filter
Filter -> PreAggregate
PreAggregate -> Aggregate
Aggregate -> Sort
Sort -> Offset
Offset -> Limit
Limit -> Project
Project .u.> End

Scan .. Index
Scan .. Search
Fetch .. Data
Join .. Data

@enduml