@startuml query_execution

skinparam maxMessageSize 125
skinparam roundcorner 5
skinparam responseMessageBelowArrow true
skinparam sequenceMessageAlign direction
skinparam ParticipantPadding 10
skinparam BoxPadding 60
skinparam box {
BackgroundColor PaleGreen
ArrowColor SeaGreen
BorderColor SpringGreen
}

participant Clients

box Couchbase Server Cluster #White
collections "Query Service" as Query
collections "Index Service" as Index
collections "Data Service" as Data
end box

Clients -> Query: Submit the\nquery
activate Query #teal
' tag::example[]
note left
  SELECT airportname, city
  FROM airport
  WHERE tz = "America/Anchorage"
  AND geo.alt >= 2100;
end note
' end::example[]

Query -[#transparent]-> Query: Parse, analyze, create plan

Query -> Index: Scan request; index filters
activate Index #deepskyblue
|||
Index -> Query: Get qualified doc keys and index keys
deactivate Index

' tag::fetch[]
Query -> Data: Fetch request, doc keys
activate Data #midnightblue
|||
Data -> Query: Fetch the\ndocuments
deactivate Data
' end::fetch[]

Query -[#transparent]> Query: Evaluate; documents to results

Query -> Clients: Query\nresult
deactivate Query
' tag::example[]
note left
  {
    "airportname": "Analtuvuk",
    "city": "Anaktuvuk Pass"
  }
end note
' end::example[]

@enduml