= Listing Catalogs
:description: pass:q[You can list the catalogs defined in the cluster, or retrieve one by name, using the `/pools/default/externalCatalogs` REST API endpoint.]
:page-edition: Enterprise Edition
:page-topic-type: reference

[abstract]
{description}
An external catalog defines a connection to an external Apache Iceberg catalog provider such as AWS Glue or a Nessie server.
For more information about external catalogs and collections, see xref:learn:data/external-catalogs-and-collections.adoc[].

== Description

Send a `GET` request to `/pools/default/externalCatalogs` to list every catalog in the cluster, or to `/pools/default/externalCatalogs/<catalog-name>` to get one catalog's details.

== HTTP Method and URI

----
GET /pools/default/externalCatalogs

GET /pools/default/externalCatalogs/<catalog-name>
----

== curl Syntax

[source,bash]
----
curl -X GET http[s]://<host>:<port>/pools/default/externalCatalogs[/<catalog-name>] \
  -u <username>:<password>
----

== Path Parameters

`catalog-name`::
(optional) The name of the catalog to retrieve.
Omit this parameter to list every catalog in the cluster.

== Required Privileges

Your account needs at least 1 of the following roles:

* xref:learn:security/roles.adoc#external-catalog-reader[External Catalog Read-Only Admin]
* xref:learn:security/roles.adoc#external-catalog-admin[External Catalog Admin]
* xref:learn:security/roles.adoc#full-admin[Full Admin]

== Responses

200 OK::
Couchbase Server returns a JSON object describing the requested catalog, or a JSON array of catalog objects when you omit `catalog-name`.

404 Not Found::
No catalog with that name exists.

== Example

The following example retrieves the catalog named `analytics_catalog`:

[source,bash]
----
curl -X GET -u $CB_USER:$CB_PASS \
  http://node1.example.com:8091/pools/default/externalCatalogs/analytics_catalog | jq
----

If successful, the call returns the catalog's stored definition:

[source,json]
----
{
  "name": "analytics_catalog",
  "catalogType": "ICEBERG",
  "catalogSource": "AWS_GLUE_REST",
  "credentialId": "query/external/iceberg-analytics-catalog",
  "uri": "https://glue.us-east-1.amazonaws.com/iceberg",
  "sigv4SigningRegion": "us-east-1",
  "rev": 1
}
----

== See Also

* xref:rest-api:external-catalogs/creating-a-catalog.adoc[]
* xref:rest-api:external-catalogs/editing-a-catalog.adoc[]
* xref:rest-api:external-catalogs/dropping-a-catalog.adoc[]
* xref:rest-api:external-catalogs/get-external-catalog-information.adoc[]
* xref:rest-api:scopes-and-collections-api.adoc[]
* xref:rest-api:creating-a-collection.adoc[]
