= Running N1QL Queries from a Command Line
:tabs:
:page-topic-type: concept

[abstract]
[.cmd]`cbq` is the command line shell that you can use to issue N1QL queries on Couchbase Server.

To run [.cmd]`cbq` on the local host:

. Log in to a Couchbase Server node that has the query service enabled.
. Open a command window.
. Change to the Couchbase tools directory.
+
[{tabs}]
====
Linux::
+
--
[source,console]
----
$ cd /opt/couchbase/bin
----
--

macOS::
+
--
[source,console]
----
$ cd /Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/bin
----
--

Microsoft Windows::
+
--
[source,console]
----
> cd C:\Program Files\Couchbase\Server\bin
----
--
====

. Run the following command to connect to the local query node and start the interactive query shell:
+
[{tabs}]
====
Linux / macOS::
+
--
[source,console]
----
$ ./cbq
----
--

Microsoft Windows::
+
--
[source,console]
----
> cbq
----
--
====
+
[NOTE]
====
Run the following command to connect to the cluster, the IP address can be any node in the cluster as cbq will automatically discover the query nodes:

[source,console]
----
./cbq -engine=http://123.45.67.89:8091
----
====

. At the [.cmd]`cbq` prompt, enter a N1QL query and end the query with a semicolon.
Press kbd:[Return] to execute the query.
For example:
+
[source,console]
----
cbq> create primary index on `beer-sample`;
----
+
.Result
[source,json]
----
{
    "requestID": "fd4086fa-9ed0-465d-9a99-422c5d8e9506",
    "signature": null,
    "results": [
    ],
    "status": "success",
    "metrics": {
        "elapsedTime": "598.972353ms",
        "executionTime": "598.936382ms",
        "resultCount": 0,
        "resultSize": 0
    }
}
----
+
[source,console]
----
cbq> select * from `beer-sample` limit 1;
----
+
.Results
[source,json]
----
{
    "requestID": "b9f6490d-91c6-4a18-b0b9-a2345cb58b88",
    "signature": {
        "*": "*"
    },
    "results": [
        {
            "beer-sample": {
                "abv": 5,
                "brewery_id": "21st_amendment_brewery_cafe",
                "category": "North American Ale",
                "description": "Light golden color. Sweet dry aroma with crisp, clear bitterness. Brewed with imported German hops.The perfect beer to have when you'd like to have more than one.",
                "ibu": 0,
                "name": "South Park Blonde",
                "srm": 0,
                "style": "Golden or Blonde Ale",
                "type": "beer",
                "upc": 0,
                "updated": "2010-07-22 20:00:20"
            }
        }
    ],
    "status": "success",
    "metrics": {
        "elapsedTime": "24.994186ms",
        "executionTime": "24.936945ms",
        "resultCount": 1,
        "resultSize": 641
    }
}
----

== Accessing a Secure Bucket

If your bucket has a password, you can pass the bucket name and bucket password like so:

[source,console]
----
./cbq -engine="http://<bucketname>:<bucketpassword>@123.45.67.89:8091/"
----

For the 'beer-sample' bucket, if you add a password to it of _w1fg2Uhj89_ (as by default it has none), the command to start [.cmd]`cbq` would look like this:

[source,console]
----
./cbq -engine="http://beer-sample:w1fg2Uhj89@123.45.67.89:8091/"
----

If you want to access all of the buckets in the same cbq session, you would pass in the Administrator username and password instead of the bucket level.

[source,console]
----
./cbq -engine="http://Administrator:password@123.45.67.89:8091/"
----

NOTE: These commands execute successfully only if you have loaded sample bucket 'beer-sample' either at install or from the Settings menu in the web UI.

== Exiting [.cmd]`cbq`

Type kbd:[Ctrl+D] to exit [.cmd]`cbq`.

== Keyboard Shortcuts for cbq

The following table lists the keyboard shortcuts for N1QL commands.
These shortcuts are similar to those used in the Emacs text editor.

.Shortcut Keys for cbq Shell
[cols="100,197"]
|===
| Keystroke | Action

| kbd:[Ctrl+A], kbd:[Home]
| Move cursor to beginning of line

| kbd:[Ctrl+E], kbd:[End]
| Move cursor to end of line

| kbd:[Ctrl+B], kbd:[Left]
| Move cursor one character left

| kbd:[Ctrl+F], kbd:[Right]
| Move cursor one character right

| kbd:[Ctrl+Left]
| Move cursor to previous word

| kbd:[Ctrl+Right]
| Move cursor to next word

| kbd:[Ctrl+D], kbd:[Del]
| (if line is not empty) Delete character under cursor

| kbd:[Ctrl+D]
| (if line is empty) End of File - usually quits application

| kbd:[Ctrl+C]
| Reset input (create new empty prompt)

| kbd:[Ctrl+L]
| Clear screen (line is unmodified)

| kbd:[Ctrl+T]
| Transpose previous character with current character

| kbd:[Ctrl+H], kbd:[BackSpace]
| Delete character before cursor

| kbd:[Ctrl+W]
| Delete word leading up to cursor

| kbd:[Ctrl+K]
| Delete from cursor to end of line

| kbd:[Ctrl+U]
| Delete from start of line to cursor

| kbd:[Ctrl+P], kbd:[Up]
| Previous match from history

| kbd:[Ctrl+N], kbd:[Down]
| Next match from history

| kbd:[Ctrl+R]
| Reverse Search history (kbd:[Ctrl+S] forward, kbd:[Ctrl+G] cancel)

| kbd:[Ctrl+Y]
| Paste from Yank buffer (kbd:[Alt+Y] to paste next yank instead)

| kbd:[Tab]
| Next completion

| kbd:[Shift+Tab]
| (after kbd:[Tab]) Previous completion
|===

Source: [.cite]_\https://github.com/peterh/liner_
