= Running Queries
:page-role: tiles -toc
:!sectids:

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

== Queries and Results

An overview of common concepts that you will need to understand in order to use the Query service.

* xref:n1ql:n1ql-intro/queriesandresults.adoc[N1QL Queries and Results]

== Getting System Information

N1QL has a system catalog that stores metadata about a database.
The system catalog is a namespace called system.

* xref:n1ql:n1ql-intro/sysinfo.adoc[Getting System Information]

== N1QL Error Codes

All of the N1QL error codes, their error messages, and some tips to resolve them.

* xref:n1ql:n1ql-language-reference/n1ql-error-codes.adoc[N1QL Error Codes]

== Related Links

The Query services provides the following tools for running queries:

* xref:tools:cbq-shell.adoc[cbq: The Command Line Shell for N1QL]
* xref:tools:query-workbench.adoc[Query Workbench]
