= Manage Settings

[abstract]
Couchbase-Server _settings_ can be established by the administrator.

[#couchbase-server-settings-overview]
== Settings Overview

The _settings_ for Couchbase Server cover:

* _Name_, _memory quotas_ and _storage modes_ for the cluster; and _advanced settings_ for the Index and Query Services.
These are described in xref:manage:manage-settings/cluster-settings.adoc[Cluster].

* _Software updates_, whereby periodic email notifications are provided to the administrator, in relation to software-update availability.
These are described in xref:manage:manage-settings/update-notification.adoc[Software Updates].

* _Node availability_, whereby automatic failover is configured.
These are described in xref:manage:manage-settings/change-failover-settings.adoc[Node Availability].

* _Email alerts_, whereby users can be notified of critical system-events.
These are described in xref:manage:manage-settings/configure-alerts.adoc[Email Alerts].

* _Auto compaction_, whereby data on the server is automatically compacted if specified thresholds are met.
These are described in xref:manage:manage-settings/configure-compact-settings.adoc[Auto-Compaction].

* _Sample buckets_, whereby buckets pre-populated with documents can be installed, for the purpose of experimentation and testing.
These are described in xref:manage:manage-settings/install-sample-buckets.adoc[Sample Buckets]
