override:
    asciidoc:
        attributes:
            kroki-server-url: http://127.0.0.1:8000
            kroki-fetch-diagram: true
sources:
    docs-devex:
        branches: DOC-12565_vector_search_concepts
        url: ../docs-devex

