= Recover a Node

[abstract]
After a node has been failed over, it can be _recovered_: that is, added back
into the cluster from which it was failed over, by means of the _rebalance_
operation.

[#understanding-recovery]
== Understanding Recovery

After failover has occurred, before the failed over node has been rebalanced
out of the cluster, the node can be _recovered_, and thereby reintegrated
into the cluster. This is useful in circumstances where, following failover,
the unhealthy node has been fixed, and is therefore now
assumed fit for re-addition.

There are two options for recovery, which are _full_ and _delta_. These
are explained in
xref:understanding-couchbase:clusters-and-availability/recovery.adoc[Recovery].

[#examples-on-this-page-recover-node]
== Examples on This Page

[#examples-on-this-page-graceful-failover]
== Examples on This Page

The examples in the subsections below show how to perform both _full_ and
_delta_ recovery on the same failed over node in the same cluster; using the
xref:managing-clusters:managing-nodes/recover-nodes.adoc#recover-node-with-the-ui[UI],
the
xref:managing-clusters:managing-nodes/recover-nodes.adoc#recover-node-with-the-cli[CLI],
and the
xref:managing-clusters:managing-nodes/recover-nodes.adoc#recover-node-with-the-rest-api[REST
API] respectively. The examples assume:

The examples assume:

* A two-node cluster already exists, as
at the conclusion of
xref:managing-clusters:managing-nodes/join-cluster-and-rebalance.adoc[Join a
Cluster and Rebalance].

* The cluster has the Full Administrator username of
`Administrator`, and password of `password`.

[#recover-node-with-the-ui]
== Recover a Node with the UI

[#recover-node-with-the-cli]
== Recover a Node with the CLI

[#recover-node-with-the-rest-api]
== Recover a Node with the REST API
