
[#release-7610]
== Release 7.6.10 (February 2026)

Couchbase Server 7.6.10 was released in February 2026.
This maintenance release contains fixes to issues.

== Fixed Issues




=== Cluster Manager
[#table-fixed-issues-7610-cluster-manager, cols='10,40,40']
|===
|Issue | Description | Resolution


|https://jira.issues.couchbase.com/browse/MB-69026/[MB-69026]

a|The latest builds for Couchbase Server and Enterprise Analytics have addressed the issue of broken stuck rebalance email alerts.

// Generated by [openai:gpt-4o]

| Issue resolved


|https://jira.issues.couchbase.com/browse/MB-69650/[MB-69650]

a|A problem was introduced in 7.6.2 where the presence of Cloud Native Gateway in the cluster would cause issues for services connecting to the cluster manager.

The presence of Cloud Native Gateway no longer causes these issues.

| Issue resolved


|https://jira.issues.couchbase.com/browse/MB-70441/[MB-70441]

a|The upgrade to erlang version 26 introduced a change in behavior which requires peer certification when TLS is being used for Alert emails.
The peer certification introduced with the changes for this ticket uses the trusted CA certificates provided by the operating system.

| Issue resolved


|===



=== Data Service
[#table-fixed-issues-7610-data-service, cols='10,40,40']
|===
|Issue | Description | Resolution


|https://jira.issues.couchbase.com/browse/MB-54274/[MB-54274]

a|The latest update introduces a change to the kv_engine where temporary initial or deleted items in the HashTable are no longer removed immediately.
This adjustment is aimed at improving the stability of the system as part of the resolution for issue MB-54274.
This update helps prevent potential inconsistencies or errors that may arise from immediate deletion processes.

// Generated by [openai:gpt-4o]

| Issue resolved


|===





=== XDCR
[#table-fixed-issues-7610-xdcr, cols='10,40,40']
|===
|Issue | Description | Resolution


|https://jira.issues.couchbase.com/browse/MB-70294/[MB-70294]

a|Filter Expressions referencing only the document keys are now applicable to be applied on deletions
and expirations using the new `filterDeletionsWithExpression`
and `filterExpirationsWithExpression` replication settings via the REST API.

| Issue resolved


|===



=== Query Service
[#table-fixed-issues-7610-query-service, cols='10,40,40']
|===
|Issue | Description | Resolution


|https://jira.issues.couchbase.com/browse/MB-68969/[MB-68969]

a|This update focuses on enhancing the sargability of multi-collection indexes when the `include_in_all` setting is applied to child fields.
Changes have been made to build Full-Text Search (FTS) index objects with only pertinent type mappings, optimizing their performance and efficiency.
Improvements have been incorporated across multiple builds for each involved server version, ensuring consistent behavior for index management.
Additionally, steps have been taken to address the sargability of the FTS index's _all composite field, providing better query performance.
These enhancements aim to streamline the indexing process and improve response times for relevant queries.
Users should experience enhanced indexing capabilities and efficiencies in database management with the updated implementations.

// Generated by [openai:gpt-4o]

| Issue resolved


|https://jira.issues.couchbase.com/browse/MB-69081/[MB-69081]

a|To retrieve a document's expiration, the user had to specify the sub-path explicitly, i.e `META().expiration`.
A call to the `META()` function without the sub-path would return the default expiration value 0 always which was incorrect.


Now, when a user’s query invokes META() function without explicitly specifying the sub-path the document's expiration value is returned.

| Issue resolved


|https://jira.issues.couchbase.com/browse/MB-69083/[MB-69083]

a|Problem:

A query may return an incorrect result under the following conditions:

* query contains one or more joins
* one of the joins involves a sub-query (FROM clause subquery)
* the FROM clause sub-query has a GROUP BY and/or aggregates
* the FROM clause sub-query can take advantage of index group/aggregate pushdown
(this requires an appropriate secondary index)
* CBO is ON, and UPDATE STATISTICS has been run on all keyspaces/indexes involved

| Issue resolved


|https://jira.issues.couchbase.com/browse/MB-69387/[MB-69387]

a|The auto-reprepare feature is available in this release.
It is an opt-in feature that automatically re-prepares a prepared statement before execution if any GSI changes (such as indexes being created or dropped) have occurred since the statement's plan was last created.
This allows prepared statements to adopt better suited indexes in their plans.


Enable this feature by setting bit 23 (0x800000 or 8388608)  of the n1ql-feat-ctrl Query setting.
Capella users should contact support to opt in.

| Issue resolved


|https://jira.issues.couchbase.com/browse/MB-69955/[MB-69955]

a|`CYCLE` was added as a KEYWORD for RECURSIVE WITH’s CYCLE sub-clause.

This causes a syntax error when a path or sub-path’s case-insensitive identifier is named `cycle`  when users upgraded to a version that supported the recursive with feature https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/with-recursive.html[WITH recursive clause]

This is now handled by allowing `cycle` keyword as a permitted identifier.

| Issue resolved


|https://jira.issues.couchbase.com/browse/MB-70112/[MB-70112]

a|When a prepared request with the  `auto_execute` request parameter set as `true`,
the request would incorrectly error out with error: `Unrecognizable prepared statement - cause: JSON unmarshalling error: auto_execute did not produce a prepared statement`

In this release the server silently ignores the `auto_execute` request parameter when the request is a prepared request.

| Issue resolved


|===







=== Index Service
[#table-fixed-issues-7610-index-service, cols='10,40,40']
|===
|Issue | Description | Resolution


|https://jira.issues.couchbase.com/browse/MB-69934/[MB-69934]

a|Updated chronology for certain storage API calls to avoid rare corner case of shard metadata mismatch.

| Issue resolved


|===



=== Search Service
[#table-fixed-issues-7610-search-service, cols='10,40,40']
|===
|Issue | Description | Resolution


|https://jira.issues.couchbase.com/browse/MB-68969/[MB-68969]

a|This update focuses on enhancing the sargability of multi-collection indexes when the `include_in_all` setting is applied to child fields.
Changes have been made to build Full-Text Search (FTS) index objects with only pertinent type mappings, optimizing their performance and efficiency.
Additionally, steps have been taken to address the sargability of the FTS index's `_all` composite field, providing better query performance.
These enhancements aim to streamline the indexing process and improve response times for relevant queries.

// Generated by [openai:gpt-4o]

| Issue resolved


|===



=== Tools
[#table-fixed-issues-7610-tools, cols='10,40,40']
|===
|Issue | Description | Resolution


|https://jira.issues.couchbase.com/browse/MB-70255/[MB-70255]

a|Fixes bug where buckets with cross-cluster versioning enabled (link:https://docs.couchbase.com/server/current/learn/clusters-and-availability/xdcr-enable-crossclusterversioning.html[XDCR enable cross cluster versioning] ) would cause a merge to fail

| Issue resolved


|===



