




[#release-80]
== Release 8.0 (September 2025)

Couchbase Server 8.0 was released in September 2025.
This maintenance release contains fixes to issues.

== Fixed Issues




=== Cluster Manager

[#dlist-known-issues-80-cluster-manager]


*https://jira.issues.couchbase.com/browse/MB-60568/[MB-60568]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-60883/[MB-60883]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61946/[MB-61946]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-62583/[MB-62583]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-67106/[MB-67106]*::

*Metric Rename – Cache Miss Ratio → Miss Ratio*
The _Cache Miss Ratio_ metric name suggested it measured memory or disk caching performance. In reality, as of version 7.6.2, it was redefined to measure the proportion of read (`get`) operations that fail because the requested key is not present in the bucket at all.  To eliminate this confusion, the metric has been renamed to *Get Miss Ratio*.


=== Data Service

[#dlist-known-issues-80-data-service]


*https://jira.issues.couchbase.com/browse/MB-9418/[MB-9418]*::

*Configurable Warmup Behavior (Background Warmup)* – Added a new `warmup_behavior` setting (`warmupBehavior` in the REST API) to control when a persistent bucket becomes fully available (reads and write operations can be peformed) after a bucket restarts, a bucket is available to read. This setting replaces multiple warmup threshold parameters with a single configuration point:

* *background* _(default)_ – bucket becomes fully available as soon as required metadata is loaded from storage, the buckets cache is then filled in the background until memory usage reaches the low watermark.
* *blocking* – Original behavior; bucket becomes read available as soon as required metadata is loaded from storage, the buckets cache is then filled until memory usage reaches the low watermark, after this is reached the bucket becomes fully available.
* *none* – Disables warmup; bucket becomes fully available as soon as required metadata is loaded from storage, the cache will remain empty.

+

*API changes* – The REST API has a new per-Bucket setting (`warmupBehavior`),  and the previous advanced tunings (`warmup_min_items_threshold` and `warmup_min_memory_threshold`) have been removed from the `cbepctl` interface.

*https://jira.issues.couchbase.com/browse/MB-55290/[MB-55290]*::

When the HashTable of the document cache of a vBucket is resized, operations on documents in that vBucket were blocked until the resize has completed, increasing latencies.

+

A new resizing algorithm was introduced which processes HashTable items in batches, allowing operations on documents to proceed while resizing.

*https://jira.issues.couchbase.com/browse/MB-60542/[MB-60542]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61154/[MB-61154]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61385/[MB-61385]*::

SET and DELETE with Meta operations could distort the vbucket max_cas if a faulty CAS value is provided in the operation, setting the vbuckets max_cas to an unusually high or inconsistent value. Inadvertently affecting the Hybrid Logical Clock (HLC) and Last Write Wins (LLW) conflict resolution via XDCR. In certain cases, this resulted in legitimate mutations being skipped or ignored during replication. For this reason, the system now fails front-end operations with a CAS value that exceeds the `hlc_max_future_threshold`, default value of 65 minutes, to prevent a vbucket’s max_cas from getting distorted.

*https://jira.issues.couchbase.com/browse/MB-62295/[MB-62295]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-62547/[MB-62547]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-62647/[MB-62647]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-63261/[MB-63261]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-63827/[MB-63827]*::

[horizontal]

Version::: 7.2.7

Description::: DCP connection metrics for connection names not conforming to server format are not exposed to Prometheus.

Resolution::: The metrics are aggregated and exposed with `connection_type="_unknown"`.

Version::: 7.6.6 ,8.0.0

Description::: DCP connection metrics for connection names not conforming to server format are not aggregated by connection type when exposing to Prometheus, potentially producing a large number of time series.

Resolution::: The metrics are aggregated and exposed with `connection_type="_unknown"`.

*https://jira.issues.couchbase.com/browse/MB-63938/[MB-63938]*::

It is no longer possible to run commands such as `mcstat [options] statgroup1 statgroup2` to fetch multiple stat groups. In 8.0 this no longer supported to make it easier to pass arguments to the various stat groups.

+

Pre 8.0 a user would need to add quotes (or escape the whitespace) between the stat group like:

+

`$ mcstat [options] "vbucket-details 1"`

+

In 8.0 this may be written as

+

`mcstat [options] vbucket-details 1`

*https://jira.issues.couchbase.com/browse/MB-63946/[MB-63946]*::

When using `mcstat` it is no longer possible to use `--json=pretty`.

+
The request to pretty-print the JSON is ignored
+
Users can use a pipe in conjunction with an external formatting tool such as jq to obtain formatted output:

+

`-./mcstat [options] --json [statgroup] \\| jq .`

*https://jira.issues.couchbase.com/browse/MB-64071/[MB-64071]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-64353/[MB-64353]*::

Hard failover of ephemeral buckets could lead to the rollback of DCP clients back to 0. There is currently no work-around this & currently the only solution is to upgrade to version with the fix for this. 7.6.3 is the oldest release with the fix. 

+

Details:

* Hard failover of an ephemeral bucket.
* Replica promoted to active. 
* DCP client reconnect to the new active.
* DCP clients rollback to zero & have to re-stream all the mutations from the new active.

*https://jira.issues.couchbase.com/browse/MB-64742/[MB-64742]*::

An issue in the plasma tracking stats flagged a stale recovery point in the recovery log as valid data.
This made the log cleaning run slowly at a low mutation rate,
and therefore, unable to trim the recovery point history effectively.
At a higher mutation rate, the mutations alone could push the fragmentation ratio high enough to start the log cleaner,
and therefore, was  able to trim rp history despite the issue with tracking stats.

+

_Resolution_ We  mark the latest version of the recovery point that exists in both the recovery log and the data log.
This effectively means that plasma will keep the recovery point history list to 1 in the recovery log.
In addition,
the plasma tracking stats are fixed such that it no longer treats the older recovery point as valid data in the recovery log.
This allows the log cleaner to run even at a low mutation rate.

*https://jira.issues.couchbase.com/browse/MB-65644/[MB-65644]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-67106/[MB-67106]*::

*Metric Rename – Cache Miss Ratio → Miss Ratio*
The _Cache Miss Ratio_ metric name suggested it measured memory or disk caching performance. In reality, as of version 7.6.2, it was redefined to measure the proportion of read (`get`) operations that fail because the requested key is not present in the bucket at all.  To eliminate this confusion, the metric has been renamed to *Get Miss Ratio*.


=== Views

[#dlist-known-issues-80-views]


*https://jira.issues.couchbase.com/browse/MB-62919/[MB-62919]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-63212/[MB-63212]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-67213/[MB-67213]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-67280/[MB-67280]*::

*Change to Bucket Priority Settings*

+

As part of improving background task scheduling, we have replaced the legacy implementation with a standardized, more advanced scheduler. As a result, setting a bucket’s priority to high or low no longer affects system behavior. Consequently, the option to set bucket priority has been removed from the UI.

+

Previously, task scheduling relied on a basic two-priority queue (high and low), which had limitations—such as busy polling. The new scheduling mechanism (introduced in MB-36956) eliminates these issues.

+

NOTE: Bucket priority settings are still available via the REST API and CLI to maintain compatibility with existing customer scripts and tooling.


=== XDCR

[#dlist-known-issues-80-xdcr]


*https://jira.issues.couchbase.com/browse/MB-23798/[MB-23798]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-55758/[MB-55758]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-58809/[MB-58809]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-60186/[MB-60186]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-60448/[MB-60448]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-60674/[MB-60674]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-60920/[MB-60920]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-60992/[MB-60992]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61048/[MB-61048]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61312/[MB-61312]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61378/[MB-61378]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61575/[MB-61575]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61657/[MB-61657]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61949/[MB-61949]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61976/[MB-61976]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61977/[MB-61977]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-62092/[MB-62092]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-62294/[MB-62294]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-63527/[MB-63527]*::

XDCR dashboard on Source cluster now shows a UI alert when a pipeline is stuck due to EACCESS errors while writing to Target cluster.

*https://jira.issues.couchbase.com/browse/MB-66140/[MB-66140]*::

In some scenarios, due to race conditions, changing the filter expression or explicit/migration mapping may cause the replication to fail streaming from the beginning. As a consequence, some Source bucket documents may get missed from being replicated to the Target bucket.

+

This has been fixed in 8.0. It is advised to avoid changing these three replication settings:

* filterExpression
* collectionsExplicitMapping
* collectionsMigrationMode

+

until all nodes in the cluster have been upgraded.


=== Query Service

[#dlist-known-issues-80-query-service]


*https://jira.issues.couchbase.com/browse/MB-39484/[MB-39484]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-51629/[MB-51629]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61508/[MB-61508]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-62793/[MB-62793]*::

The original limit of one XATTR per KV op was relaxed to a maximum of 16 in KV server version 7.6; this ticket explores extending that relaxation to queries.
+
With this change, users can:


. Use up to 15 XATTR fields in their query.


. CREATE INDEX no longer imposes a limit on the number of XATTR fields that can be indexed.

*https://jira.issues.couchbase.com/browse/MB-62932/[MB-62932]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-63069/[MB-63069]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-63459/[MB-63459]*::

New to 7.7.0 is the ability to manipulate document extended attributes (xattrs) via common SQL++ statements.  

+

INSERT and UPSERT statement OPTIONS may now include an “xattrs” object element detailing additions and changes to the xattrs (omissions do not delete xattrs).  The UPDATE statement now supports SET and UNSET of meta().xattrs.{attribute} elements.

*https://jira.issues.couchbase.com/browse/MB-63518/[MB-63518]*::

An API issue has been resolved where attempting to set the completed-stream-size to zero when it was already zero via the administrative REST API would:

+

* Prevent stream completion

* Block access to the system:vitals keyspace or vitals end-point

* Require a full Query process restart on affected nodes as the only previous workaround

*https://jira.issues.couchbase.com/browse/MB-65055/[MB-65055]*::

In a cluster with multiple query nodes, rolling upgrade to 7.6.x cluster from an earlier version (e.g. 7.2) may result in prepared statements not working properly on  an upgraded query node if a prepared statement has a WITH clause defined.

*https://jira.issues.couchbase.com/browse/MB-67849/[MB-67849]*::

The recent builds of Couchbase Server versions 7.2.7 through 8.1.0 and Enterprise Analytics 2.1.0 include updates from the go_json library to address int64 overflow issues reported under MB-67849. The updates involve implementing proper checks for int64 overflow in order to properly represent large numbers (greater than stem:[2^63] or less than stem:[-2^63]).


=== Eventing Service

[#dlist-known-issues-80-eventing-service]


*https://jira.issues.couchbase.com/browse/MB-61488/[MB-61488]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-62403/[MB-62403]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-64081/[MB-64081]*::

{empty}






=== Index Service

[#dlist-known-issues-80-index-service]


*https://jira.issues.couchbase.com/browse/MB-60953/[MB-60953]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61387/[MB-61387]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-62919/[MB-62919]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-63193/[MB-63193]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-64982/[MB-64982]*::

When shard affinity is enabled, the indexer internally maps all replicas of an index to an alternateID. If such an alternateID exists on a node outside the list of nodes, instead of preventing replica creation, the system creates a new replica with the same alternateID on different nodes. This leads to rebalance failures on the affected nodes.


=== Search Service

[#dlist-known-issues-80-search-service]


*https://jira.issues.couchbase.com/browse/MB-64766/[MB-64766]*::

{empty}




=== Tools

[#dlist-known-issues-80-tools]


*https://jira.issues.couchbase.com/browse/MB-44863/[MB-44863]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-60337/[MB-60337]*::

Previously, it was possible to remove backups which would cause dependent incremental backups to become invalid if they depended on those deleted backups. With this release, such deletes are prevented by default, but can be overridden with the new `--disable-safe-remove-check` flag.

*https://jira.issues.couchbase.com/browse/MB-60676/[MB-60676]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-61073/[MB-61073]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-62655/[MB-62655]*::

The new Query AWR (Automatic Workload Repository) Report Generator tool allows customers to generate reports on query performance statistics. This tool requires AWR to be enabled on the cluster.

*https://jira.issues.couchbase.com/browse/MB-63389/[MB-63389]*::

*Memcached bucket removal* – Memcached buckets, deprecated in 6.5.1, have been fully removed in 8.0.0. Cluster upgrades from earlier versions will fail if Memcached buckets are present. Remove all Memcached buckets before upgrading.


