[#release-722]
== Release 7.2.2 (September 2023)
Couchbase Server 7.2.2 was released in September 2023

// tag::721-deprecated[]
[IMPORTANT]
====
*Couchbase release 7.2.1 is no longer available for download.* +
Customers upgrading from 7.2.0 should upgrade to 7.2.2,
which contains all 7.2.1 fixes and several additional critical fixes.
====
// end::721-deprecated[]

This release contains:

* Fixes to issues

=== Fixed issues

==== Analytics Service

[#table-fixed-issues-722-analytics-service,cols="1,2,2",options="header"]
|===
|Issue | Description | Resolution

| https://issues.couchbase.com/browse/MB-58694[MB-58694^]
a| Some DCP messages were unnecessarily processed multiple times. +
In addition, if the Analytics Service had high CPU usage, unnecessary flushes of DCP state to storage could occur;
this also contributed to additional high CPU usage.
| DCP messages are now processed once, regardless of the configured `dcpIdleQueueFlushThresholdMillis`. +
High CPU usage will not trigger unnecessary flushes of DCP state.

| https://issues.couchbase.com/browse/MB-58723[MB-58723^]
| Frames that contain only DCP data were unnecessarily processed by the complete ingestion pipeline, resulting in performance degradation.
| The complete ingestion pipeline no longer processes frames that only contain DCP data. +
Instead, they are processed specifically by the ingestion operators that update DCP metadata, resulting in better performance.

|===

==== Search Service

[#table-fixed-issues-722-search-service,cols="1,2,2",options="header"]
|===
|Issue | Description | Resolution

| https://issues.couchbase.com/browse/MB-58450[MB-58450^]
| An issue occurred with a node failover. +
If a user did not bring in a replacement node before the failover occurred, then lost active or lost replica search indexes that had partitions on the replaced node were not rebuilt.
  As a result, search requests returned partial/incomplete results. In addition, existing indexes with defined replica(s) became vulnerable to potential node failures. +

This issue is only pertinent to the 7.2.1 release, and does not affect older builds.

| During rebalancing, a check is now made for missing partitions. +
If missing partitions are found, they are rebuilt before the rebalance is complete.


|===