
[#release-7612]
== Release 7.6.12 (July 2026)

Couchbase Server 7.6.12 was released in July 2026.
This maintenance release contains fixes to issues.

== Fixed Issues

=== XDCR
[#table-fixed-issues-7612-xdcr, cols='10,40,40']
|===
|Issue | Description | Resolution


|https://jira.issues.couchbase.com/browse/MB-71258/[MB-71258]

a|When pausing or deleting a replication that is replicating to or from a cluster that recently underwent a failover and needs to rollback to 0,
there could be a race condition that causes the goroutines to be stuck indefinitely.
This has now been fixed.

| Issue resolved


|===



=== Query Service
[#table-fixed-issues-7612-query-service, cols='10,40,40']
|===
|Issue | Description | Resolution


|https://jira.issues.couchbase.com/browse/MB-71824/[MB-71824]

a|This fix solves the issue whereby hibernated process failed to wake up.


The issue manifested as stuck REST API requests.

| Issue resolved


|===


=== Analytics Service
[#table-fixed-issues-7612-analytics-service, cols='10,40,40']
|===
|Issue | Description | Resolution


|https://jira.issues.couchbase.com/browse/MB-71453/[MB-71453]

a|Queries that combine a `LIMIT` clause with an index-nested-loop join (specified via the `/*+ indexnl */` hint) and include additional filter conditions on the joined collection may return incorrect results,
since these conditions are not fully evaluated before the `LIMIT` is applied.

| Issue resolved


|===
