
[#release-7611]
== Release 7.6.11 (April 2026)

Couchbase Server 7.6.11 was released in April 2026.
This maintenance release contains fixes to issues.

== Fixed Issues




=== Cluster Manager
[#table-fixed-issues-7611-cluster-manager, cols='10,40,40']
|===
|Issue | Description | Resolution


|https://jira.issues.couchbase.com/browse/MB-70577/[MB-70577]

a|Client certificate authentication for views was fixed (broken in 7.6.4)

| Issue resolved


|https://jira.issues.couchbase.com/browse/MB-70951/[MB-70951]

a|The following stats were reported twice by the `/metrics` REST API.
This has been corrected to only report each once.

`<count>cm_rest_request_enters_total{}<count>`

`<count>cm_rest_request_leaves_total{}<count>`

| Issue resolved


|===







=== XDCR
[#table-fixed-issues-7611-xdcr, cols='10,40,40']
|===
|Issue | Description | Resolution


| https://jira.issues.couchbase.com/browse/MB-70512[MB-70512]

| DELETE returns a 400 error code

| XDCR now returns a 404 status code if a resource is not found,
for replication and remote cluster reference related REST APIs.


|https://jira.issues.couchbase.com/browse/MB-70906/[MB-70906]

a|Due to rare race conditions,
Backfill Manager could be stuck due to deadlock.

| Issue resolved


|https://jira.issues.couchbase.com/browse/MB-71034/[MB-71034]

a|In rare circumstances when a replication is deleted and recreated in short succession,
stale checkpoints that are not slow to be cleaned could lead to repeated pipeline restarts.

| Issue resolved


|===

