


[#release-81]
== Release 8.1 (June 2026)

Couchbase Server 8.1 was released in June 2026.
This maintenance release contains fixes to issues.

[#dlist-fixed-issues-81]
== Fixed Issues




[#dlist-fixed-issues-81-cluster-manager]
=== Cluster Manager

*https://jira.issues.couchbase.com/browse/MB-70629/[MB-70629]*::

RBAC groups containing security_admin_local,
security_admin_external,
or ro_admin roles are not handled correctly on upgrade to 8.0. The upgrade handling should replace:

+

--

* security_admin_local with security_admin + local_user_admin
* security_admin_external with security_admin + external_user_admin
* ro_admin with ro_admin + ro_security_admin

--

+

The issue also occurs when restoring users from a backup taken on a release prior to 8.0.

+

The workaround for both the upgrade and restore case is to manually correct the affected users after the upgrade/restore completes.

*https://jira.issues.couchbase.com/browse/MB-70951/[MB-70951]*::

The following stats were reported twice by the `/metrics` REST API. This has been corrected to only report each once.

+

`<count>cm_rest_request_enters_total{}<count>`

+

`<count>cm_rest_request_leaves_total{}<count>`



[#dlist-fixed-issues-81-data-service]
=== Data Service

*https://jira.issues.couchbase.com/browse/MB-68779/[MB-68779]*::

{empty}

*https://jira.issues.couchbase.com/browse/MB-69568/[MB-69568]*::

The bucket state named "clients" however it tracks all sort of clients currently holding a reference to the bucket (this could be other subcomponents _within_ the same process trying to iterate over buckets etc).  Therefore a new stat is introduced called `curr_bucket_connections`,
to track client connections.

*https://jira.issues.couchbase.com/browse/MB-70471/[MB-70471]*::

{empty}



[#dlist-fixed-issues-81-views]
=== Views

*https://jira.issues.couchbase.com/browse/MB-67213/[MB-67213]*::

*Metric Rename – Cache Miss Ratio → Get Miss Ratio*
The _Cache Miss Ratio_ metric name suggested it measured memory or disk caching performance. In reality,
as of version 7.6.2,
it was redefined to measure the proportion of read (`get`) operations that fail because the requested key is not present in the bucket at all.  To eliminate this confusion,
the metric has been renamed to *Get Miss Ratio*.

*https://jira.issues.couchbase.com/browse/MB-67280/[MB-67280]*::

*Change to Bucket Priority Settings*

+

As part of improving background task scheduling,
we have replaced the legacy implementation with a standardized,
more advanced scheduler. As a result,
setting a bucket's priority to high or low no longer affects system behavior. Consequently,
the option to set bucket priority has been removed from the UI.

+

Previously,
task scheduling relied on a basic two-priority queue (high and low),
which had limitations—such as busy polling. The new scheduling mechanism (introduced in MB-36956) eliminates these issues.

+

NOTE: Bucket priority settings are still available via the REST API and CLI to maintain compatibility with existing customer scripts and tooling.



[#dlist-fixed-issues-81-xdcr]
=== XDCR

*https://jira.issues.couchbase.com/browse/MB-68340/[MB-68340]*::

+Note on deprecation of internal settings+ `UprFeedDataChanLength` +and+ `UprFeedBufferSize`:

+

To allow for finer-grained control over the footprint of an individual pipeline,
this change deprecates internal settings `UprFeedDataChanLength` and `UprFeedBufferSize` (which would apply one value to all replications),
in favour of a new replication setting `dcpFlowControlThrottle`.

+

`dcpFlowControlThrottle` is a percentage (legal values in the range `[5,
100]`),
which will be applied to the previous default values of both `UprFeedDataChanLength` (`20000`) and `UprFeedBufferSize` (`1024*1024 bytes`). Thus users can now specify a common percentage for both the values instead of specifying them individually.

+

As a result of this,
following care needs to be taken until all nodes in the cluster have been upgraded:

. New replications MUST be created via the upgraded nodes (either API request or UI)

. All https://docs.couchbase.com/server/current/rest-api/rest-xdcr-adv-settings.html#xdcr-advanced-settings-rest[replication settings] changes (especially to the new settings `dcpFlowControlThrottle` and `componentEventsChanLength`) MUST be made via the upgraded nodes (either API request or UI)

. The change is resilient to replication "pause" & "resume" being triggered from legacy nodes. However,
it is still advised to do so via the upgraded nodes.

.. All internal-setting changes MUST be made via the legacy nodes.

. If the internal-settings `UprFeedDataChanLength` and `UprFeedBufferSize` on the legacy nodes were set to a value other than their default (20000 and 1048576,
respectively),
then they need to be set on the upgraded nodes by updating the `dcpFlowControlThrottle` replication-setting.

+

General documentation changes will be mentioned in https://jira.issues.couchbase.com/browse/DOC-13921[DOC-13921]

*https://jira.issues.couchbase.com/browse/MB-71244/[MB-71244]*::

When pausing or deleting a replication that is replicating to or from a cluster that recently underwent a failover and needs to rollback to 0,
there could be a race condition that causes the goroutines to be stuck indefinitely. This has now been fixed.



[#dlist-fixed-issues-81-query-service]
=== Query Service

*https://jira.issues.couchbase.com/browse/MB-68969/[MB-68969]*::

* With multi-collection indexes that contained fields with `include in _all` setting enabled - there was a possibility for false positives to show up for field agnostic (composite field) queries. This has been addressed by denying the sargability for such indexes.
* Addressed an issue where fields not belonging to a particular keyspace were being included in multi-collection indexes.
* Addressed a bug that could influence composite field (`_all`) availability based on the order in which fields were processed.

*https://jira.issues.couchbase.com/browse/MB-69081/[MB-69081]*::

To retrieve a document's expiration,
the user had to specify the sub-path explicitly,
i.e.,
`META().expiration`. A call to the `META()` function without the sub-path would return the default expiration value 0 always which was incorrect. 

+

Now,
when a user's query invokes the `META()` function without explicitly specifying the subpath,
the document's expiration value is returned.

*https://jira.issues.couchbase.com/browse/MB-69083/[MB-69083]*::

Problem:

+

A query may return an incorrect result under the following conditions:

+

* query contains one or more joins
* one of the joins involves a sub-query (FROM clause subquery)
* the FROM clause sub-query has a GROUP BY and/or aggregates
* the FROM clause sub-query can take advantage of index group/aggregate pushdown
(this requires an appropriate secondary index)
* CBO is ON,
and UPDATE STATISTICS has been run on all keyspaces/indexes involved

*https://jira.issues.couchbase.com/browse/MB-69955/[MB-69955]*::

`CYCLE` was added as a KEYWORD for RECURSIVE WITH's CYCLE subclause.
+
This causes a syntax error when a path or subpath's case-insensitive identifier is named `cycle`  when users upgraded to a version that supported the recursive with feature https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/with-recursive.html[WITH recursive clause]
+
This is now handled by allowing `cycle` keyword as a permitted identifier.

*https://jira.issues.couchbase.com/browse/MB-70112/[MB-70112]*::

When a prepared request is made with the  `auto_execute` request parameter set as `true`,
the request would incorrectly error out with error: `Unrecognizable prepared statement - cause: JSON unmarshalling error: auto_execute did not produce a prepared statement`
+
In this release the server silently ignores the `auto_execute` request parameter when the request is a prepared request.

*https://jira.issues.couchbase.com/browse/MB-70543/[MB-70543]*::

Execution of a scope-level UDF (user-defined function) may fail and get `Invalid Function` error under the following conditions:

* Running Couchbase Server version 7.6.0 through 7.6.10.
* A query node is starting.
* The query node is NOT being upgraded from an earlier version (for example,
7.2)
* A scope-level UDF was already present (created before the query node started)
* A call to execute the scope-level UDF is issued against the query node shortly after the query node started.

*https://jira.issues.couchbase.com/browse/MB-70745/[MB-70745]*::

A restore may fail under the following conditions:

* Couchbase version 7.6.0 through 7.6.10
* CBO (Cost-Based Optimizer) was enabled
* An index exists where one of the index keys contains `'::'`,
for example,
`SPLIT(<field>,
"::")`
* UPDATE STATISTICS (or ANALYZE) has been run on the index
* a backup was taken after UPDATE STATISTICS was run
* a restore was attempted with the backup









[#dlist-fixed-issues-81-search-service]
=== Search Service

*https://jira.issues.couchbase.com/browse/MB-68681/[MB-68681]*::

{empty}

*https://jira.issues.couchbase.com/browse/MB-70388/[MB-70388]*::

Fixed an issue where we did not set `docvalues` for `geopoint` fields internally,
causing it to be computed on demand for every query



[#dlist-fixed-issues-81-tools]
=== Tools

*https://jira.issues.couchbase.com/browse/MB-68392/[MB-68392]*::

{empty}

*https://jira.issues.couchbase.com/browse/MB-69453/[MB-69453]*::

{empty}

*https://jira.issues.couchbase.com/browse/MB-70255/[MB-70255]*::

Addressed a bug where buckets with cross-cluster versioning enabled (link:https://docs.couchbase.com/server/current/learn/clusters-and-availability/xdcr-enable-crossclusterversioning.html[XDCR enable cross-cluster versioning]) would cause a merge to fail.



