== Release 8.0.0 (December 2024)


Couchbase Server 8.0.0  was released in December 2024. This maintenance release contains new features and fixes several known issues.

For detailed information on new features and enhancements, please see xref:introduction:whats-new.adoc[].

[#section-fixed-issues-800]
=== Fixed Issues

This release contains the following fixes:

[#section-fixed-issues-800-cluster-manager]
==== Cluster Manager


[#section-fixed-issues-800-storage-engine]
==== Storage Engine



[#section-fixed-issues-800-query-service]
==== Query Service

https://jira.issues.couchbase.com/browse/MB-63420[MB-63420]::
A server panic when processing a request containing a composite aggregate with a reference to the source (e.g., `MAX([d.date, d][1])` — note the order and the array element access being within the aggregate) has been resolved.
+
The more common form, (e.g., `MAX([d.date, d])[1]` was not affected.


https://jira.issues.couchbase.com/browse/MB-63518[MB-63518]::
An issue occurs
when setting `completed-stream-size` to 0 when it is already set to 0 via the admin REST API, but the API call did not complete.
Thereafter, access to vital information was blocked. +
The issue has now been resolved.
Prior to this fix, the only way to rectify the situation was to restart the query process on the affected node(s).

[#section-fixed-issues-800-index-service]
==== Index Service



[#section-fixed-issues-800-anaytics-service]
==== Analytics Service



[#section-known-issues-800]
=== Known Issues

This release contains the following known issues:

[#section-known-issues-800-query-service]
==== Query Service




