== Release 7.6.5 (January 2025)

Couchbase Server 7.6.5 was released in January 2025.
This maintenance release contains fixes several for known issues.

For detailed information on new features and enhancements, see xref:introduction:whats-new.adoc[].

[#fixed-issues-765]
=== Fixed Issues

This release contains the following fixes:


==== Data Service

[#table-fixed-issues-765-data-service,cols="10,40,40"]
|===
|Issue | Description | Resolution


| https://jira.issues.couchbase.com/browse/MB-64353[MB-64353]
| Hard failover of ephemeral buckets could lead to the rollback of DCP clients back to zero.

| Fixed in version `7.6.3`. 

Upgrading to `7.6.5` will enable the fix.

| https://jira.issues.couchbase.com/browse/MB-64742[MB-64742]
a|A bug in the plasma tracking statistics incorrectly marked stale recovery points in the recovery log as valid data. This caused two problems:

* At low mutation rates, the log cleaning process ran slowly and couldn't effectively trim recovery point history.
* At higher mutation rates, the system worked around this issue because mutations would increase the fragmentation ratio enough to trigger the log cleaner, which could then trim recovery point history despite the tracking statistics bug.

| The system now marks only the latest recovery point that exists in both the recovery log and data log. This change effectively limits the recovery point history list to a single entry in the recovery log. The plasma tracking statistics have been fixed to correctly identify older recovery points as stale data in the recovery log. These improvements allow the log cleaner to run efficiently even at low mutation rates.


|===

==== Query Service

[#table-fixed-issues-765-query-service,cols="10,40,40"]
|===
|Issue | Description | Resolution

| https://jira.issues.couchbase.com/browse/MB-64684[MB-64684]
a| An issue occurred when an inline user-defined function (UDF) included a query with a nested `Array` construct,
and the innermost `Array` construct referred to both:

* a UDF argument, and
* the binding variable of an outer `ARRAY` construct,
  
Then the UDF creation or execution could fail.

| Issue resolved

|===


==== Search Service

[#table-fixed-issues-765-search-service,cols="10,40,40"]
|===
|Issue | Description | Resolution
| https://jira.issues.couchbase.com/browse/MB-64652[MB-64652]
a| An issue in versioning caused an online upgrade-rebalance operation
to fail on account of a planning algorithm improvement. 
The bug would also impact the failover-recovery online upgrade path.

NOTE: This issue only surfaced when an upgrade was attempted over a system with search indexes from `7.6.[0–3]` to `7.6.4`.

| The issue has been resolved in version `7.6.5`. 
Our recommendation is to avoid the issue by moving directly to this version.

| https://jira.issues.couchbase.com/browse/MB-64764[MB-64764]
| If an index was created during rebalance,
and the rebalance was stopped before plans were computed for that index,
then no plans or partitions were created for the index until a subsequent rebalance was completed.

In `7.6.4` we introduced a change
to compute the plans for indexes created during a rebalance even when the rebalance stops midway. 
This inadvertently caused a regression where a subsequent rebalance could get stuck and fail continuously on timeouts.

| In `7.6.5` we reverted the change: if the user aborts an ongoing rebalance, then plans for an index introduced during the operation may not be deployed until a subsequent rebalance operation is triggered and completed. 

|===


[#known-issues-765]
=== Known Issues

This release contains the following known issues:

==== Query Service

[#table-known-issues-765-query-service, cols="10,40,40"]
|===
|Issue | Description | Workaround

include::partial$docs-server-7.6.0-release-note.adoc[tag="MB-64966"]

|===


