




[#breaking-changes-80]
== Breaking changes 8.0 (August 2025)

Couchbase Server 8.0 was released in August 2025.
This maintenance release contains the following breaking changes:






=== Data Service

[#breaking-changes-80-data-service]


*https://jira.issues.couchbase.com/browse/MB-63946/[MB-63946]*::

When using `mcstat` it is no longer possible to use `--json=pretty`.
The request to pretty-print the JSON is ignored
+
Users can use a pipe in conjunction with an external formatting tool such as `jq` to obtain formatted output:
+
[source, shell]

----

./mcstat [options] --json [statgroup] \| jq .

----

*https://jira.issues.couchbase.com/browse/MB-63938/[MB-63938]*::

It is no longer possible to run commands such as `mcstat [options] statgroup1 statgroup2` to fetch multiple stat groups. In 8.0 this no longer supported to make it easier to pass arguments to the various stat groups.

+

Pre 8.0 a user would need to add quotes (or escape the whitespace) between the stat group like:

+

`$ mcstat [options] "vbucket-details 1"`

+

In 8.0 this may be written as

+

`mcstat [options] vbucket-details 1`

*https://jira.issues.couchbase.com/browse/MB-9418/[MB-9418]*::

{empty}




=== Views

[#breaking-changes-80-views]


*https://jira.issues.couchbase.com/browse/MB-67280/[MB-67280]*::

*Change to Bucket Priority Settings*

+

As part of improving background task scheduling, we have replaced the legacy implementation with a standardized, more advanced scheduler. As a result, setting a bucket’s priority to high or low no longer affects system behavior. Consequently, the option to set bucket priority has been removed from the UI.

+

Previously, task scheduling relied on a basic two-priority queue (high and low), which had limitations—such as busy polling. The new scheduling mechanism (introduced in MB-36956) eliminates these issues.

+

NOTE: Bucket priority settings are still available via the REST API and CLI to maintain compatibility with existing customer scripts and tooling.

*https://jira.issues.couchbase.com/browse/MB-63212/[MB-63212]*::

{empty}












=== Index Service

[#breaking-changes-80-index-service]


*https://jira.issues.couchbase.com/browse/MB-63192/[MB-63192]*::

{empty}






=== Tools

[#breaking-changes-80-tools]


*https://jira.issues.couchbase.com/browse/MB-63389/[MB-63389]*::

{empty}



*https://jira.issues.couchbase.com/browse/MB-60337/[MB-60337]*::

Previously, it was possible to remove backups which would cause dependent incremental backups to become invalid if they depended on those deleted backups. With this release, such deletes are prevented by default, but can be overridden with the new `--disable-safe-remove-check` flag.


