




[#breaking-changes-80]
== Breaking changes 8.0 (September 2025)

Couchbase Server 8.0 was released in September 2025.
This maintenance release contains the following breaking changes:




=== Cluster Manager

[#breaking-changes-80-cluster-manager]


*https://jira.issues.couchbase.com/browse/MB-47905/[MB-47905]*::

We have  introduced the ability to support both client certificate authentication and n2n encryption at the same time.

+

However, the client certificate will not work with the old OOTB CA certificates due to the extended attribute. 

+

Therefore,  you will need to regenerate your OOTB CA certificates (if the CA certificate is the one from before `7.6` or if they have the attribute above) before this feature is enabled. 


=== Data Service

[#breaking-changes-80-data-service]


*https://jira.issues.couchbase.com/browse/MB-63946/[MB-63946]*::

When using `mcstat` it is no longer possible to use `--json=pretty`.

+
The request to pretty-print the JSON is ignored
+
Users can use a pipe in conjunction with an external formatting tool such as jq to obtain formatted output:

+

`-./mcstat [options] --json [statgroup] \\| jq .`

*https://jira.issues.couchbase.com/browse/MB-63938/[MB-63938]*::

It is no longer possible to run commands such as `mcstat [options] statgroup1 statgroup2` to fetch multiple stat groups. In 8.0 this no longer supported to make it easier to pass arguments to the various stat groups.

+

Pre 8.0 a user would need to add quotes (or escape the whitespace) between the stat group like:

+

`$ mcstat [options] "vbucket-details 1"`

+

In 8.0 this may be written as

+

`mcstat [options] vbucket-details 1`

*https://jira.issues.couchbase.com/browse/MB-9418/[MB-9418]*::

*Configurable Warmup Behavior (Background Warmup)* – Added a new `warmup_behavior` setting (`warmupBehavior` in the REST API) to control when a persistent bucket becomes fully available (reads and write operations can be peformed) after a bucket restarts, a bucket is available to read. This setting replaces multiple warmup threshold parameters with a single configuration point:

* *background* _(default)_ – bucket becomes fully available as soon as required metadata is loaded from storage, the buckets cache is then filled in the background until memory usage reaches the low watermark.
* *blocking* – Original behavior; bucket becomes read available as soon as required metadata is loaded from storage, the buckets cache is then filled until memory usage reaches the low watermark, after this is reached the bucket becomes fully available.
* *none* – Disables warmup; bucket becomes fully available as soon as required metadata is loaded from storage, the cache will remain empty.

+

*API changes* – The REST API has a new per-Bucket setting (`warmupBehavior`),  and the previous advanced tunings (`warmup_min_items_threshold` and `warmup_min_memory_threshold`) have been removed from the `cbepctl` interface.


=== Views

[#breaking-changes-80-views]


*https://jira.issues.couchbase.com/browse/MB-67280/[MB-67280]*::

*Change to Bucket Priority Settings*

+

As part of improving background task scheduling, we have replaced the legacy implementation with a standardized, more advanced scheduler. As a result, setting a bucket’s priority to high or low no longer affects system behavior. Consequently, the option to set bucket priority has been removed from the UI.

+

Previously, task scheduling relied on a basic two-priority queue (high and low), which had limitations—such as busy polling. The new scheduling mechanism (introduced in MB-36956) eliminates these issues.

+

NOTE: Bucket priority settings are still available via the REST API and CLI to maintain compatibility with existing customer scripts and tooling.

*https://jira.issues.couchbase.com/browse/MB-63212/[MB-63212]*::

{empty}












=== Index Service

[#breaking-changes-80-index-service]


*https://jira.issues.couchbase.com/browse/MB-63192/[MB-63192]*::

{empty}






=== Tools

[#breaking-changes-80-tools]


*https://jira.issues.couchbase.com/browse/MB-63389/[MB-63389]*::

*Memcached bucket removal* – Memcached buckets, deprecated in 6.5.1, have been fully removed in 8.0.0. Cluster upgrades from earlier versions will fail if Memcached buckets are present. Remove all Memcached buckets before upgrading.

*https://jira.issues.couchbase.com/browse/MB-60337/[MB-60337]*::

Previously, it was possible to remove backups which would cause dependent incremental backups to become invalid if they depended on those deleted backups. With this release, such deletes are prevented by default, but can be overridden with the new `--disable-safe-remove-check` flag.


