[#clusters_and_availability]
= Clusters and Availability
:page-aliases: concepts:distributed-data-management.adoc

[abstract]
One or more instances of Couchbase Server constitute a _cluster_, which replicates data across server-instances, and across clusters; and so ensures high availability.

== Clusters

A Couchbase _cluster_ consists of one or more instances of Couchbase Server, each running on an independent node.
Data and services are shared across the cluster.

When Couchbase Server is being configured on a node, it can be specified either as its own, new cluster, or as a participant in an existing cluster.
Thus, once a cluster exists, successive nodes can be added to it; each node running Couchbase Server.
When a cluster has multiple nodes, the Couchbase _Cluster Manager_ runs on each node: this manages communications between nodes, and ensures that all nodes are healthy.
The Cluster Manager provides information on the cluster to the user interface of _Couchbase Web Console_.

Services can be configured to run on all or some nodes in a cluster.
For example, given a cluster of five nodes, a small dataset might require the Data Service on only one of the nodes; a large on four or five.
Alternatively, a heavy query workload might require the Query Service to run on multiple nodes, rather than just one.
This ability to scale services individually promotes optimal hardware-resource utilization.

== Availability

Data is automatically distributed across a cluster by Couchbase Server: applications are not involved.
Each defined bucket is stored by the Data Service as 1024 _vBuckets_ (virtual buckets), which are spread evenly across all available Data Service nodes.
Documents are stored intact within vBuckets.
vBuckets can also be _replicated_, across the cluster, by means of the _Database Change Protocol_; with each replica always existing on a node different from that of its original.

Couchbase Server automatically handles the addition and removal of nodes, and the failure of nodes; such that no data-loss occurs.
vBuckets and their replicas are redistributed across available nodes whenever a change of configuration is detected.

_High_ Availability is achieved by means of _Cross Datacenter Replication_ (_XDCR_); whereby the contents of a bucket can be selectively replicated to a bucket maintained on a remote cluster.
Additionally, xref:clusters-and-availability/groups.adoc#groups[Server Group Awareness] allows _groups_ of nodes to be defined, within the cluster, to protect the cluster against significant infrastructure-failure.
