= Rebalance

[abstract]
Rebalance is a process of re-distributing data and indexes among the available nodes.

[#understanding-rebalance]
== Understanding Rebalance

When one or nodes have been added to or removed from a cluster, _rebalance_
redistributes data and indexes among the available nodes, and the
Cluster Map is appropriate updated and distributed to clients.
The process can occur while the cluster continues to run and service requests:
reads and writes continue to be made to an existing structure, while the
data is moved in the background among nodes.

The rebalance is performed differently, depending on which services are
deployed.

[#rebalancing-the-data-service]
== Rebalancing the Data Service

As explained in
xref:understanding-couchbase:clusters-and-availability/clusters-and-availability.adoc[Clusters
and Availability], data is logically partitioned across the
cluster-nodes running the Data Service.
On rebalance, vBuckets are redistributed evenly among those nodes.
If nodes are removed, each vBucket from the removed node is replicated to the
new active node for that vBucket.
A special case of this a _swap rebalance_ where the number of nodes coming
into the cluster is equal to the number of nodes leaving the cluster,
ensuring that data is only moved between these nodes.
Once vBucket data-transfer is complete, the new vBucket is made active,
and operations are directed to it as appropriate.
This process ensures uninterrupted data-access for applications.

vBucket data-transfer occurs sequentially: therefore, if rebalance stops for any
reason, it can be restarted from the point at which it was stopped.

[#rebalancing-the-index-service]
== Rebalancing the Index Service

The Index service maintains a cluster-wide set of index definitions and metadata which allows it to redistribute indexes and index replicas (if they are used) from ejected nodes to other nodes in the cluster.
However, indexes already residing on nodes in the cluster will not be redistributed as part of rebalance, even if it would mean creating a more desirable distribution of indexes.
This distribution is based on balancing the CPU and RAM utilization of the nodes, aiming to balance this across all index nodes where possible.
When these indexes are moved, the actual index data is not sent directly to the new node, the indexes are instead created and then built from scratch using the data from the Data service.
While the rebalance process does recreate missing replicas and move them if necessary, if there are more replicas of an index than available nodes, the Index service will drop the replicas instead of creating duplicate indexes on a node.
If later, more index nodes are added to the cluster, then the Index service will then intelligently be able to bring the number of replicas up to the desired value.

The Index service ensures uninterrupted index access within the cluster by not removing index nodes as part of the rebalance operation until the indexes residing on those nodes have finished building on the new nodes.
This means that the time that it takes to rebalance the Index service is highly dependent on the overall data set size and size of the indexes on the ejected nodes.

== Rebalancing the Search Service

Similarly to the Data service, the Search service automatically partitions its indexes across all search nodes in the cluster, ensuring that during rebalance the distribution across all nodes is balanced.

== Rebalancing the Query Service

When adding or removing nodes running the Query service during rebalance, the changes are immediately effective.
If adding a node, this means that it will be immediately available to serve queries.
When removing a node, this means that it will immediately stop serving queries and any ongoing queries running on the node will be terminated, so you may have to handle this within your application.

== Rebalancing Multiple Services

Frequently, Couchbase Server production-deployments have no more than one service deployed on each node, see xref:understanding-couchbase:services-and-indexes/services/services.adoc[Services].
In instances where this is not the case, the rebalance behavior will be the combination of all services deployed on the node.
