= Cross Data Center Replication (XDCR)

[abstract]
_Cross Data Center Replication_ (XDCR) allows data to be replicated across clusters
that are potentially located in different data centers.

[#introduction-to-xdcr]
== Introduction to XDCR

Cross Data Center Replication (XDCR) replicates data between clusters: this
provides protection against data center failure, and also provides
high-performance data-access for globally distributed, mission-critical
applications.

XDCR replicates data from a specific bucket on the source cluster to a
specific bucket on the target cluster. Data from the source bucket is pushed
to the target bucket by means of an XDCR agent, running on the source cluster,
using the Database Change Protocol. Any bucket (Couchbase or Ephemeral) on any
cluster can be specified as a source or a target for one or more
XDCR definitions.

Cross Data Center Replication differs from intra-cluster replication in
the following, significant ways:

* Whereas intra-cluster replication creates only _replica_ vBuckets, XDCR
creates only _active_ vBuckets, which duly become available for the serving of
data on the target cluster.
* Whereas intra-cluster replication is configured and performed with
reference to only a single bucket (to which all active and replica vBuckets
will correspond), XDCR requires _two_ buckets to be administrator-specified,
for a replication to occur: one is the bucket on the source cluster, which
provides the data to be replicated; the other is the bucket on the target
cluster, which receives the replicated data.
* Whereas intra-cluster replication is configured at bucket-creation, XDCR
is configured _following_ the creation of both the source and target buckets.

XDCR is started, paused, and stopped independently of the process of
intra-cluster replication on either source or target cluster. The XDCR
process continuously
propagates mutations from the source to the target bucket. The source and
target clusters can have different node-configurations.

[#direction-and-topology]
== Direction and Topology

XDCR allows replication to occur between source and target clusters in
either of the following ways:

* _unidirectionally_: The data contained in a specified source bucket is
replicated to a specified target bucket. Although the replicated data on
the source _could_ be used for the routine serving of
data, it is in fact intended
principally as
a backup, to support disaster recovery.
* _bidirectionally_: The data contained in a specified source bucket is
replicated to a specified target bucket; and the data contained in the
target bucket is, in turn, replicated back to the source
bucket. This allows both buckets to be used for the serving of data, which
may provide faster data-access for users and applications in remote
geographies.

Note, however, that XDCR provides only a single basic mechanism from which
replications are built: this is the _unidirectional_ replication.
A _bidirectional_ topology
is created by implementing two _unidirectional_ replications: one from
source to target, the other from target to source.

Unidirectional and bidirectional replication can be used to create
complex topologies; an example being the _ring_ topology, where
multiple clusters each connect to exactly two peers, so that a complete
ring of connections is formed.

Alternatively, multiple clusters might
use XDCR to maintain a consistent view of the same data, represented as
an individual, replicated bucket on each cluster.

Note that when a bucket is specified as the source for an XDCR replication,
_all_ data in the bucket is replicated. Thus, if replication is
configured between source and target buckets that initially contain
different data-sets, the replication-process places the
superset on each bucket.

[#xdcr-conflict-resolution]
== XDCR Conflict Resolution

In some cases, especially when bidirectionally replicated data is being
modified by applications in different locations, _conflicts_ may arise:
meaning that the data of one or more documents has been differently
modified more or less simultaneously, requiring resolution.
XDCR provides options for
_conflict resolution_, based on either _revision ID_ or _timestamp_,
whereby conflicted data can be saved consistently on source and target.
