= XDCR Advanced Settings

[abstract]
XDCR performance can be fine-tuned.

[#xdcr-adv]
== Table of XDCR Advanced Settings

[cols="1,4"]
|===
| Option | Description

| XDCR Compression Type
| Defines whether documents are to be compressed for XDCR, and if so,
which  compression type is to be used.The default is `None`.
The only compression type currently supported is *Snappy*.
Note that compression is only used in accordance with the bucket's _compression
mode_ setting. For further information, see
xref:understanding-couchbase:buckets-memory-and-storage/compression.adoc[Compression].

| XDCR Source Nozzles per Node
| Determines the number of XDCR source nozzles per node.
This value must be less than or equal to that specified for
`XDCR Target Nozzles per Node`, to ensure that
all mutations transmitted from the source can be handled by the target.

A small value of 2 or 4 is often sufficient.
The default is 2. The value-range is 1-100.

| XDCR Target Nozzles per Node
|
Determines the number of XDCR target nozzles (concurrent XDCR worker threads)
per node. A high value can be
used if the target nodes have high processing power.
The default is 2. The value-range is 1-100. This value must be greater than
or equal to that specified for `XDCR Target Nozzles per Node`, to ensure that
all mutations transmitted from the source can be handled by the target.

| XDCR Checkpoint Interval
| Specifies the duraction of the Checkpoint Interval. During this interval
(which does not affect the persistence of data),
XDCR computes and persists checkpoint documents, which contain the high
sequence number for each vBucket successfully replicated to the target cluster.

If the replication is restarted by user, or recovers from an error, the
checkpoint documents can be used to determine the starting point of the
replication, to avoid unnecessary work.
The shorter the interval, the more accurate the checkpoint documents, and the
smaller the amount of work needed at replication restart.
Note that the computation and persistence of checkpoint documents use
considerable system resources and may impact XDCR performance.

| XDCR Batch Count
| Specifies the document batching count, in the range of 500 to 10000.
The default is 500.

In general, increasing this value by 2 or 3 times improves XDCR
transmission-rates, since larger batches of data are sent in the specified
interval. Overall replication performance is correspondingly improved,
provided that disk-persistence can be adequately managed on the target
cluster. (Note that the volume or reads and writes may be significantly
greater on clusters that function both as sources and targets for bidirectional
replication.)

| XDCR Batch Size (kilobytes)
| Specifies the document batching size, in the range of
10 to 100000 (kilobytes).
The default is 2048.

In general, increasing this value by 2 or 3 times improves XDCR transmissions
rates, since larger batches of data are sent in the specified interval.
Overall replication performance is correspondingly improved,
provided that disk-persistence can be adequately managed on the target
cluster. (Note that the volume or reads and writes may be significantly
greater on clusters that function both as sources and targets for bidirectional
replication.)

| XDCR Failure Retry Interval
| Specifies the interval during which XDCR waits before attempting to
restart replication, after a server or network failure.
The value-range is 1 to 300 seconds, with the default being 10.
Lower values are suitable for handling more frequently expected failures.

| XDCR Optimistic Replication Threshold
| This option improves XDCR latency and represents the compressed document size in bytes that spans from 0 to 20MB (default is 256 Bytes).
XDCR will get metadata for documents larger than this size on a single time before replicating the uncompressed document to a destination cluster.

| XDCR Conflict Resolution
| The XDCR conflict resolution strategy is set on a per bucket basis.
It is chosen during bucket creation and cannot be changed.
The default conflict resolution setting is "Sequence number" (revision id).
Starting Server version 4.6, you can choose to use timestamp-based conflict resolution by selecting the strategy "Timestamp".
For more information, see xref:clustersetup:create-bucket.adoc[Create a Bucket] setting during bucket creation.

| XDCR Statistics Collection Interval
| Shows how often XDCR Statistics is updated.

| XDCR Network Usage Limit (MB/sec)
| The upper limit for network usage during replication, per source node, specified in megabytes per second.
The default is 0, which means no limit is applied.

| XDCR Logging Level
| The log level for the replication.
It can be `Error`, `Info`, `Debug` or `Trace`.
|===
