[#concept_xh5_l3j_vs]
= Connectivity Architecture

[abstract]
Couchbase Server is a fully distributed database, making connection management and efficient communication key components of the architecture.
This section provides information about client to cluster, node to node, cluster to cluster, and cluster to external products communications.

[#section-client-2-cluster-comm]
== Client to Cluster Communication

There are four main types of access points that drive the majority of client to server communications.

.Communication ports
[#table_yph_ppc_ws]
|===
| Type | Port | API | 

| REST
| 8091, 18091 (SSL)
| Admin operations with the REST Admin API
| Direct Connect to a single node in the cluster to perform admin operations, monitoring, and alerting.

| REST
| 8092, 18092 (SSL)
| Query with View (View and Spatial View API)
| Load balanced connection across nodes of the cluster that run the data service for View queries.

| REST
| 8093, 18093 (SSL)
| Query with N1QL (N1QL API)
| Load balanced connection across nodes of the cluster that run the query service for N1QL queries.

| ONLINE
| 11210, 11207 (SSL)
| Core Data operations
| Stateful connections from client app to nodes of the cluster that runs data service for CRUD operations.

| REST
| 8094, 18094 (SSL)
| Search Service (Developer Preview)
| Load balanced connections across nodes of the cluster that run the search service for full text search queries.
|===

For information on how a connection is established when a request from the client side is received, see xref:connection-phases.adoc[Connectivity Phases].

== Node to Node Communication

Node to node communication is optimized for high efficiency operations and may not go through all the connectivity phases (authentication, discovery, and service connection).
For more information about connectivity phases, see <<section-client-2-cluster-comm>>.

== Cluster to Cluster Communication

XDCR communication is set up from a source cluster to a destination cluster.
For more information, see xref:cross-datacenter-replication.adoc[Cross Datacenter Replication].

== External Connector Communication

Couchbase has built and supports connectors for Spark, Kafka, Elasticsearch, SOLR, and so on.
For more information about the connectors built by Couchbase, see xref:connectors:intro.adoc[Connector Guides].
The community and other companies have also built more connectors for ODBC driver, JDBC driver, Flume, Storm, Nagios connectors for Couchbase, and so on.
External connectors are typically built using the existing client SDKs, the direct service or admin APIs listed in the client to cluster communication section, or feed directly from the internal APIs such as the Database Change Protocol (DCP) API.
For more information about Database Change Protocol, see xref:intra-cluster-replication.adoc[Intra-cluster replication].
