= Installing Couchbase Server on Amazon Linux 2
:page-edition: enterprise
:tabs:

[abstract]
Install Couchbase Server on Amazon Linux 2.
Root and non-root installations are supported.

Amazon Linux 2 is supported with Couchbase Server 6.0.1+.
See xref:install-platforms.adoc[Supported Operating Systems] for details.

Use the instructions on this page to install Couchbase Server on Amazon Linux 2 using the officially-supported `.rpm` packages provided by Couchbase.
The instructions support both Enterprise and Community editions.

[IMPORTANT]
====
The installation procedures assume that you're working from a clean system and that you've xref:install-uninstalling.adoc[uninstalled] any previous installations of Couchbase Server.

If you're upgrading an existing installation of Couchbase Server, refer to xref:upgrade.adoc[Upgrading Couchbase Server].
====

== Before You Install

Couchbase Server works out-of-the-box on most Amazon Linux 2 configurations.
However, you should review the following material before installing, especially if you're deploying Couchbase into production:

* Ensure that you've met the xref:plan-for-production.adoc[minimum system requirements] and that your operating system version is xref:install-platforms.adoc[supported].
* Follow the xref:install-production-deployment.adoc[deployment guidelines] to ensure that your systems and environment are properly sized and configured.

== Basic Installation

You must be logged in as root (superuser) or use `sudo` to run the installation commands.

=== Install Using `.rpm` Package

Install Couchbase Server on Amazon Linux 2 using the full `.rpm` package that you downloaded from Couchbase.

. Download the appropriate package for your operating system from the Couchbase https://www.couchbase.com/downloads[downloads page^].

. Install Couchbase Server.
+
[source,console]
----
sudo rpm --install couchbase-server-*.rpm
----
+
...where `*` is the edition and version of the downloaded package.
+
Once installation is complete, Couchbase Server will start automatically (and will continue to start automatically at run levels 2, 3, 4, and 5, and explicitly shut down at run levels 0, 1, and 6).
You can use the `systemctl` command (`service` on older operating systems) to start and stop the Couchbase Server service, as well as check the current status.
Refer to xref:startup-shutdown.adoc[Couchbase Server Startup and Shutdown] for more information.

. Open a web browser and access the Couchbase Server Web Console to xref:testing.adoc[verify] that the installation was successful and the node is available.

[#amzn-lnx2-nonroot-nonsudo-]
== Installing as non-root, non-sudo

A non-sudo, non-root installation still runs Couchbase Server and all Couchbase command-line tools.

. Place the Couchbase Server RPM into a directory where Couchbase Server is to be installed.

. Go to that directory and extract the RPM:
+
[source,bash]
----
cd /home/me/couchbase-non-root/
----
+
[source,bash]
----
rpm2cpio couchbase-server-enterprise-version-amzn2.x86_64.rpm | cpio --extract --make-directories --no-absolute-filenames
----
+
In the directory where the files were extracted, the `opt` and `etc` sub-directories are now available.

. After you extract the Couchbase Server installation files, go to the sub-directory:
+
[source,bash]
----
cd opt/couchbase
----

. Run the following script to complete the non-root Couchbase Server installation:
+
[source,bash]
----
./bin/install/reloc.sh `pwd`
----
+
This enables you to continue the installation as a non-root, non-sudo user.

. To run the server, use
+
[source,bash]
----
./bin/couchbase-server \-- -noinput -detached
----

. To stop the server, use
+
[source,bash]
----
./bin/couchbase-server -k
----