= Amazon Linux 2 Installation
:page-edition: enterprise

[abstract]
Couchbase Server version 6.0.1 adds support for the Amazon Linux 2 platform.

== Installing Using [.cmd]`rpm`

Install Couchbase Server on Amazon Linux 2 using the [.cmd]`rpm` command-line tool with the downloaded RPM package.

See xref:install-platforms.adoc[Supported Operating Systems] for details.

*Disable Transparent Huge Pages (THP)*

Newer Linux distributions are known to have the Transparent Huge Pages (THP) feature enabled by default.
THP can cause issues in database software, including Couchbase Server.
THP can cause nodes to lose cluster heartbeats, resulting in erroneous automatic fail overs.
xref:thp-disable.adoc[Disabling Transparent Huge Pages (THP)] prior to installing Couchbase Server is strongly encouraged.

*Complete the Installation*

You must be logged in as `root` (superuser) or use the [.cmd]`sudo` command to complete the installation.
Use the following command to install the Couchbase Server package:

[source,bash]
----
rpm --install couchbase-server-enterprise-version-amzn2.x86_64.rpm
----

where [.var]`version` is the version number of the downloaded package.

After the [.cmd]`rpm` command completes, the Couchbase Server service starts automatically.

After installation is completed, the installation process displays a message similar to the following:

----
    Minimum RAM required : 4 GB
    System RAM configured : 8174464 kilobytes
    Minimum number of processors required :  4 cores
    Number of processors on the system : 4 cores


    Starting couchbase-server[ OK ]

    You have successfully installed Couchbase Server.
    Browse to http://host_name:8091/ to configure your server.
    Refer to http://couchbase.com for additional resources.

    Update your firewall configuration
    to allow connections to the following ports:

    11211, 11210, 11209, 4369, 8091, 8092 and from 21100 to 21299.


    By using this software you agree to the End User License Agreement.
    See /opt/couchbase/LICENSE.txt.
----

After the installation is completed, use the [.cmd]`service` command to manage the Couchbase Server service, including checking the current status.
Refer to the Amazon Linux 2 documentation for instructions.

To perform the initial Couchbase Server setup, open a web browser and access the Couchbase Web Console.
