= Install Couchbase Server on Amazon Linux 2
:page-edition: enterprise
:tabs:

[abstract]
Couchbase Server can be installed on Amazon Linux 2 for production and development use-cases.
Root and non-root installations are supported.

Amazon Linux 2 is supported with Couchbase Server 6.0.1+.
See xref:install-platforms.adoc[Supported Operating Systems] for details.

Use the instructions on this page to install Couchbase Server on Amazon Linux 2 using Couchbase-provided RPM packages.
The instructions support both Enterprise and Community https://www.couchbase.com/products/editions[editions^].

If you're upgrading an existing installation of Couchbase Server, refer to xref:upgrade.adoc[Upgrading Couchbase Server].

== Before You Install

Couchbase Server works out-of-the-box with most OS configurations.
However, the procedures on this page assume the following:

* Your system meets the xref:pre-install.adoc[minimum requirements] and that your operating system version is xref:install-platforms.adoc[supported].
* You're working from a clean system and that you've xref:install-uninstalling.adoc[uninstalled] any previous versions of Couchbase Server.
+
If you're upgrading an existing installation of Couchbase Server, refer to xref:upgrade.adoc[Upgrading Couchbase Server].

For production deployments, make sure to follow the xref:install-production-deployment.adoc[deployment guidelines] so that your systems and environment are properly sized and configured before installation.

== Basic Installation

You must be logged in as root (superuser) or use `sudo` to run the installation commands.

=== Install Using RPM Package

Install Couchbase Server on Amazon Linux 2 using a full RPM package provided by Couchbase.

. Download the appropriate package from the Couchbase https://www.couchbase.com/downloads[downloads page^].

. Install Couchbase Server.
+
[source,console,subs=+quotes]
----
sudo rpm --install [.var]_package-name_.rpm
----
+
Once installation is complete, Couchbase Server will start automatically (and will continue to start automatically at run levels 2, 3, 4, and 5, and explicitly shut down at run levels 0, 1, and 6).
You can use the `systemctl` command (`service` on older operating systems) to start and stop the Couchbase Server service, as well as check the current status.
Refer to xref:startup-shutdown.adoc[Couchbase Server Startup and Shutdown] for more information.

. Open a web browser and access the Couchbase Web Console to xref:testing.adoc[verify] that the installation was successful and the node is available.

[#amzn-lnx2-nonroot-nonsudo-]
== Installing as non-root, non-sudo

A non-sudo, non-root installation still runs Couchbase Server and all Couchbase command-line tools.

. Place the Couchbase Server RPM into a directory where Couchbase Server is to be installed.

. Go to that directory and extract the RPM:
+
[source,bash]
----
cd /home/me/couchbase-non-root/
----
+
[source,bash]
----
rpm2cpio couchbase-server-enterprise-version-amzn2.x86_64.rpm | cpio --extract --make-directories --no-absolute-filenames
----
+
In the directory where the files were extracted, the `opt` and `etc` sub-directories are now available.

. After you extract the Couchbase Server installation files, go to the sub-directory:
+
[source,bash]
----
cd opt/couchbase
----

. Run the following script to complete the non-root Couchbase Server installation:
+
[source,bash]
----
./bin/install/reloc.sh `pwd`
----
+
This enables you to continue the installation as a non-root, non-sudo user.

. To run the server, use
+
[source,bash]
----
./bin/couchbase-server \-- -noinput -detached
----

. To stop the server, use
+
[source,bash]
----
./bin/couchbase-server -k
----

== Next Steps

Following installation and start-up of Couchbase Server, a node must be _initialized_ and _provisioned_.

* If it is the first node in a deployment, initialization and provisioning happens all at once when you create a _cluster of one_.
+
Refer to xref:manage:manage-nodes/create-cluster.adoc[Create a Cluster]

* If you already have an existing cluster, the node is initialized and provisioned when you add it to the cluster.
+
Refer to xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a Node and Rebalance]
+
* Optionally, initialization can be performed explicitly and independently of provisioning, as a prior process, in order to establish certain configurations, such as custom disk-paths.
+
Refer to xref:manage:manage-nodes/initialize-node.adoc[Initialize a Node]