= Manual installation

[abstract]
Manual AWS installation using the Amazon Linux 64-bit AMI.

To install Couchbase Server manually, follow these steps:

. Launch an Amazon EC2 instance using the AMI of your choice.
. Create an EBS volume to use for your Couchbase Server storage, and attach it to the instance.
. Connect to the instance over SSH.
. Install the openssl098e that Couchbase Server X.X.X requires.

  $ sudo yum install openssl098e
+
You might also want to check the latest http://aws.amazon.com/security/security-bulletins/aws-services-updated-to-address-openssl-vulnerability/[AWS security bulletin^] to upgrade your OpenSSL version if it is affected.

. Download and install the Couchbase Server RHEL package.
At the SSH command prompt, type the following, and then press Enter:

  $ sudo rpm -i couchbase-server-enterprise_x86_64_X.X.X.rpm

. Couchbase Server will start automatically when the installation is complete.
The setup process, which configures Couchbase Server and sets the data location and other details, is run separately.
. Make a file system on your Amazon Elastic Block Store (EBS) volume:

  $ sudo mkfs -t ext4
           /dev/*the_connection_you_attached_the_volume_to_for_example_sdf*

. Make a directory and mount the file system:

  $ sudo mkdir -p /data/db/

. Edit your file system configuration to enumerate the volume on startup:

  $ sudo su
           $ sudo echo '/dev/sdf /data/db auto noatime,noexec,nodiratime 0 0' >> /etc/fstab
           $ exit

. Mount the volume:

  $ sudo mount -a /dev/sdf /data/db

. Set the owner of the mounted volume:

   $ sudo chown couchbase /data/db

. Configure the instance to use the Amazon EBS directory for storage:

   $ /opt/couchbase/bin/couchbase-cli node-init -c localhost:8091 --node-init-data- path=/data/db

. Set the security group for the new instance, allowing connectivity for ports 8091, 8092, 11210, 4369 and 21100 to 21199.
For communication between clients and instances, you need only ports 8091, 8092, and 11210.
For the complete list of ports used for Couchbase Server, see xref:install-ports.adoc[Network Configuration].
. Initialize the cluster by setting the [.param]`username`, [.param]`password`, [.param]`cluster port` (default 8091) and RAM allocated to Couchbase Server for data storage.
To do so, access the Couchbase Server setup service through the Web-based administration console, which is initially exposed on port 8091.
If you have not configured a public IP address, or if you want to automate the process, you can use the command-line tools to perform the setup operation as follows:

  $ /opt/couchbase/bin/couchbase-cli cluster-init -c localhost:8091 \ --cluster-init-username=Administrator \
           --cluster-init-password=password \
           --cluster-init-port=8091 \
           --cluster-init-ramsize=8000

. When the cluster is initialized, you can access the Web Administration console by visiting the public DNS on the port configured in the command in the previous step, for example, `+http://publicdns:8091+`.
You must log in with the username and password configured in the previous step.
