= Installing with AMI

[abstract]
You can find the Couchbase Server's Amazon Machine Images (AMIs) by searching for `couchbase` in the Amazon’s EC2 portal.

To install the Couchbase Server AMI:

. Log into AWS Console.
. Select the AWS Region where you want to launch your Couchbase Server instance in the [.ui]*Region* section.
. Click on EC2 and Launch Instance and Navigate to Community AMI and search for Couchbase.
. Choose a AMI that suits your needs (mainly operating system).
. Choose your preferred `instance type` in the Amazon EC2 [.ui]*Instance Type* section. 
. Ensure the instance type satisfies the minimum hardware requirements as below.
+
----
https://docs.couchbase.com/server/5.1/install/pre-install.html
----
+
. Ensure you have the right security group settings in place (ports and ip address accessible).
. Choose a `Key Pair` to associate with the instance in the [.ui]*Key Pair* section.
. Select the `Key Pair` you want to use when connecting to the instance over Secure Shell (SSH) in the [.ui]*Key Pair* section.
. Click [.ui]*Launch* with 1-Click to create your new instance.
. After the instance is created, you will be presented with the deployment details.
Take note of the `Instance ID`.
. Sign into the AWS Management Console, select [.ui]*EC2* and click the ID for the instance just created.
In the instance detail panel, make a note of the Public DNS hostname.
You will need this to log into your Couchbase Server installation.
. To connect to your Couchbase Server installation, open a browser and connect to the instance URL on port `8091`.
For example,
+
----
http://ec2-107-21-64-139.compute-1.amazonaws.com:8091
----
+
Answer the prompts for the username and password for the Couchbase Server web console:

 ** Username is `Administrator`
 ** Password is your instance ID

. When you have successfully logged in, you should be presented with the Couchbase Server Administration Web Console [.ui]*Cluster Overview* window.
The server is automatically configured for you.

After the instance has started, it will operate just like any Couchbase Server instance.
This single instance can operate independently, or can be added to a group of similar instances to create a cluster.
