= Installing on Windows

[abstract]
Installation using a package management system on Windows.

This installation guide only supports 64-bit systems.
See xref:install-platforms.adoc[Supported platforms] for the complete list of platforms supported by Couchbase Server.

== Prerequisites

To install Couchbase Server on Windows, you need to perform following prerequisites:

. Make sure that you have no anti-virus software running on the machine before you start the installation process.
. Verify that you have administrator privileges using a local system account on the machine where you are performing the installation.
. By default, on Windows the TCP/IP has default number of ports available for client communication.
+
You need to follow the information provided in https://msdn.microsoft.com/en-us/library/aa560610(v=bts.20).aspx[Avoiding TCP/IP Port Exhaustion^] to adjust the configuration and increase the number of available ports.

. By default, the Windows system does not provide an adequate number of ephemeral ports for Couchbase Server clusters.
Without the correct number of open ephemeral ports, you can experience errors during rebalance, timeouts on clients, and failed backups.
+
The Couchbase Server installer will automatically check for your current port setting and adjust it if needed.
See https://support.microsoft.com/en-us/kb/196271[Microsoft KB-196271^].

// Removing note as Windows Server 2008 is no longer supported in 5.0
// <note type="important">Couchbase Server uses the Microsoft C++ redistributable package, which
// is automatically downloaded during installation.
// However, if another application on your
// machine is already using the package, your installation process can fail.
// To make sure that
// your installation process completes successfully, shut down all other running applications
// during installation.
// For Windows 2008, you must upgrade your Windows Server 2008 R2
// installation with Service Pack 1 installed before running Couchbase Server.
// You can obtain
// Service Pack 1 from <xref
// href="https://technet.microsoft.com/en-us/library/ff817647(v=ws.10).aspx" format="html"
// scope="external">Microsoft TechNet</xref>.
// </note>

NOTE: On Windows earlier than 10 or Server 2016, Windows Updates need to be applied to ensure the universal CRT is installed.
For other versions of Windows, see https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows[Update for Universal C Runtime in Windows^].

For information on installing Couchbase Server on IPv6 systems, see xref:ipv6-setup.adoc[IP Version 6: Set-Up Procedures].

== Downloading on Windows Systems

// DOC-2724: Do not encourage downloading directly using wget.
// <p>You can download Couchbase Server directly using the <cmdname>wget.exe</cmdname> command for
// Windows or Powershell scripting.
// </p>
// <p>The basic syntax of the <cmdname>wget</cmdname> command is:
// <codeblock>$ wget [option]...
// [url]...</codeblock>For example, the following command
// downloads Couchbase Server Enterprise Edition for Windows Server 2012 R2:
// <codeblock>$ wget.exe -\-no-check-certificate http://packages.couchbase.com/releases/<varname>version</varname>/couchbase-server-enterprise-<varname>version</varname>-windows_amd64.msi </codeblock></p>

Download the installation package from the https://www.couchbase.com/downloads#couchbase-server[Downloads^] page.

== Interactive Installation

To install Couchbase Server on Windows using interactive install wizard follow the steps below:

. In Windows Explorer, locate the downloaded `couchbase-server-enterprise_version-windows_amd64.msi` file, which typically is located in the default Downloads folder.
Double click on the executable file.
// DOC-2724: Remove paragraphs noted in the ticket
. You will be prompted with the Installation Location screen.
You can change the location where the Couchbase Server application is located, which configures the server location and not the location where the persistent data is stored.
. Click [.ui]*Yes* to continue.
. After installation, follow the instructions to xref:init-setup.adoc[setup Couchbase Server].

// <note type="attention">If the Windows installer hangs on the Computing Space Requirements screen,
// there is an issue with your setup or installation environment, such as other running applications.
// </note>
// <p>You can implement this workaround to complete the installation:</p>
// <ol>
// <li>Stop any other browsers and applications that were running when you started installing Couchbase Server.</li>
// <li>Kill the installation process and uninstall the failed setup.</li>
// <li>Delete or rename the temp location under <filepath>C:\Users\[logonuser]\AppData\Temp</filepath>.</li>
// <li>Reboot and try again.</li>
// </ol>

== Unattended Installation

To perform an unattended installation, also referred to as silent or headless installation, use the `\qn` or `\quiet` options with [.cmd]`msiexec` executable.
Note that for a completely unattended installation, you must run the command from an Administrator command prompt.

The following command installs Couchbase Server Enterprise Edition on the default directory:

----
start /wait msiexec /i couchbase-server-enterprise-version-windows_amd64.msi /qn
----

To install to a non-standard directory, use the following command:

----
start /wait msiexec /i couchbase-server-enterprise-version-windows_amd64.msi /qn INSTALLDIR=C:\my-install-dir
----

NOTE: If you do not prepend `start /wait` to the command, [.cmd]`msiexec` immediately returns control to the command prompt and does not wait for the installation to complete or report any errors.
In which case, you may have to wait a minute or two for the actual installation to complete.
