= Installing Couchbase Server

[abstract]
Couchbase Server installation covers pre-installation, installation on supported platforms, post-installation, upgrading, cloud deployment and migration procedures.

Installation involves picking up the platform and the correct software edition for your needs, downloading the software, and running the installer.

Before you install Couchbase Server, review the hardware requirements, supported platforms, network configuration, security considerations, and production deployment considerations.
Then follow the installation instructions for your operating system or cloud environment.

== Download Couchbase Server

Couchbase Server is supported on numerous popular operating systems.
Look for the binaries for your operating system on the http://www.couchbase.com/nosql-databases/downloads[Couchbase download page^].

Each of the binaries listed on the download page has appropriate installation instructions.

For example, when selecting installation instructions next to the Ubuntu package, the following is shown:

. Download or transfer the download to your Ubuntu system.
. Install the package using the [.cmd]`dpkg` command as a privileged user under sudo.
For example:
+
----
 sudo dpkg -i couchbase-server-enterprise_5.0.0-ubuntu14.04_amd64.deb
----
