= Supported Operating Systems

[abstract]
Couchbase Server is supported on several popular operating systems and virtual environments.

Make sure that your chosen platform is listed in one of the following tables before you install Couchbase Server.
See the xref:release-notes:relnotes.adoc[release notes] for information about platform support changes, including deprecated platforms.
For information about supported web browsers, see xref:install-browsers.adoc[Supported Web Browsers].

IMPORTANT: Couchbase clusters on mixed platforms are not supported.
Nodes in a Couchbase cluster should all be running on the same OS, and every effort should be made to apply the same OS patches across the entire cluster.

.Supported Operating Systems for Development, Testing, and Production
[cols="100,135",options="header"]
|===
| Operating System | Supported Versions (64-bit)

| Amazon Linux 2
| LTS

| Amazon Linux AMI
| 2018.03

2017.09

| CentOS
| 8.x

7.x

| Debian
| 9.x

8.x

| Oracle Linuxfootnote:[Only the Red Hat Compatible Kernel (RHCK) is supported. The Unbreakable Enterprise Kernel (UEK) is not supported.]
| 8.x

7.x

| Red Hat Enterprise Linux (RHEL)
| 8.x

7.x

| SUSE Linux Enterprise Server (SLES)
| 15.x

12.x

| Ubuntu
| 18.04

16.04

| Windows Server
| 2019

2016
|===

.Supported Operating Systems for Development and Testing Only
[cols="100,135",options="header"]
|===
| Operating System | Supported Versions (64-bit)

| macOS
| 10.14 "Mojave"

10.13 "High Sierra"

| Windows Desktop
| 10 (requires Anniversary Update)
|===
