[#concept_jgc_ddp_ts]
= Production Deployment and Cluster Setup

[abstract]
To configure the Couchbase Server production environment, follow the recommendations about the cluster setup, sizing guidelines, swap space, and client server deployment strategies.

Proper configuration of I/O subsystems is critical for the optimal performance and operation and performance of Couchbase Server.
These are the most common best practices recommended for storage configuration:

== General Recommendations

Use RAID 1+0 (or RAID 1) if Couchbase bucket replication is 1 or lower:: If bucket replicas are set to 2 or higher, the administrator might rely on database-level replication for data durability.

xref:architecture:services-archi-multi-dimensional-scaling.adoc#concept_v4w_zmj_vs[Multi-Dimensional Scaling] (MDS)::
MDS functionality allows separation of Index and Query services from the traditional Couchbase Server data/view services.
With MDS and if it fits your use case needs, you can have different disk storage configurations for cluster nodes running the Data service and different ones running the Index service.
For example, nodes running the Index service could have SSD backed storage for better performance.
Refer to xref:sizing-general.adoc#topic_axp_glg_xs[Sizing Guidelines]for more details.

Windows OS:: For Windows OS, use 64k allocation sizes on NTFS file systems.

== Nodes Running the Data Service

Isolate the data and indexes:: For the best performance, isolate the data and indexes (note that these are different from the Index Service) at the physical disk level.

Combine different workloads::
Combining different workloads (workloads with very different I/O and latency characteristics) can have a negative effect on the overall performance.
In case of combined workloads, it might be appropriate to have objects in different buckets and the files for each bucket on different mount points/paths.
