[#concept_ixr_wsp_ts]
= Uninstalling Couchbase Server

[abstract]
Uninstallation steps are provided for each of the supported platforms.

== Uninstalling on RHEL or CentOS

Uninstall Couchbase Server on RHEL or CentOS using the [.cmd]`rpm` command-line tool with the downloaded `RPM` package.

Before uninstalling Couchbase Server:

. Shut down Couchbase Server.
. If your machine is a part of an active cluster, rebalance the cluster to take the node out of the configuration.
. Update any clients to point to an available node within the Couchbase Server cluster.

Uninstall Couchbase Server:

. Log in as a root (superuser) to complete the installation.
. Run the following command:
+
[source,bash]
----
> sudo rpm -e couchbase-server
----

You might need to delete the data files associated with your installation.
The default installation location is [.path]_/opt_.
If an alternative location for your data files was specified, each data directory must be individually deleted from your system.

== Uninstalling on Ubuntu or Debian

Uninstall Couchbase Server on Ubuntu or Debian using the [.cmd]`dpkg` command-line tool with the downloaded DEB package.

Before uninstalling Couchbase Server:

. Shut down Couchbase Server.
. If your machine is a part of an active cluster, rebalance the cluster to take the node out of the configuration.
. Update any clients to point to an available node within the Couchbase Server cluster.

Uninstall Couchbase Server:

. Log in as a root (superuser) to complete the installation.
. Run the following command:
+
----
 > sudo dpkg -r couchbase-server
----

Refer to the Ubuntu documentation for more information about uninstalling packages using [.cmd]`dpkg`.

You might need to delete the data files associated with your installation.
The default installation location is [.path]_/opt_.
If an alternative location for your data files was specified, each data directory must be individually deleted from your system.

== Uninstalling on SUSE and Oracle

Uninstall Couchbase Server on SUSE or Oracle Enterprise Linux using the [.cmd]`rpm` command-line tool with the downloaded RPM package.

Before uninstalling Couchbase Server

. Shut down Couchbase Server.
. If your machine is a part of an active cluster, rebalance the cluster to take the node out of the configuration.
. Update any clients to point to an available node within the Couchbase Server cluster.

Uninstall Couchbase Server

. Log in as a root (superuser) to complete the installation.
. Run the following command:
+
----
 > sudo rpm -e couchbase-server
----

You might need to delete the data files associated with your installation.
The default installation location is [.path]_/opt_.
If an alternative location for your data files was specified, each data directory must be individually deleted from your system.

== Uninstalling on Windows

To uninstall Couchbase Server on a Windows system, you must have Administrator or Power User privileges.

Before uninstalling Couchbase Server

. Shut down Couchbase Server.
. If your machine is a part of an active cluster, rebalance the cluster to take the node out of the configuration.
. Update any clients to point to an available node within the Couchbase Server cluster.

Uninstall Couchbase Server

. Navigate to *Start > Settings > Control Panel*
. Select [.uicontrol]*Add or Remove Programs*.
. Remove the Couchbase Server software.

== Uninstalling on Mac OS X

To uninstall Couchbase Server follow these steps.

. Open the `Applications` folder and drag the `Couchbase Server` icon to the trash.
Alternatively, delete the previous installation from the command line.
If required, provide administrator credentials to complete the deletion.
. Delete the `Couchbase` and `Membase` folders from the [.path]_~/Library/Application Support_ folder for the user that was running Couchbase Server.
This operation removes the application data.
+
[source,bash]
----
> rm -rf ~/Library/Application\ Support/Couchbase
> rm -rf ~/Library/Application\ Support/Membase
----
