= Supported Operating Systems

[abstract]
Couchbase Server is supported on numerous popular operating systems and virtual environments.

*Certified*: Couchbase has performed an extensive testing and review process to make sure that Couchbase Server runs well out of the box on the specified platform.

*Supported*: Couchbase believes that Couchbase Server will run well out of the box on the specified platform, but extensive testing has not been performed.
Couchbase will make a best effort to investigate issues on a Supported platform version, but it is recommended that you run Couchbase on a Certified platform version.

IMPORTANT: Couchbase clusters on mixed platforms are not supported.
Nodes in a Couchbase cluster should all be running on the same OS, and every effort should be made to apply the same OS patches across the entire cluster.

NOTE: All listed operating systems are 64-bit.

.Supported Operating Systems for Development, Testing, and Production
[cols="100,129"]
|===
| *Operating System* | *Version*

| Amazon Linux*
| Certified 2018.03

Supported 2017.09

| CentOS
| Certified 7.2, 7.4; Supported 7.x

Certified 6.7, 6.9; Supported 6.x

| Debian
| Certified 9; Supported 9.x

Certified 8

| Oracle Linux**
| Certified 7.3

Certified 6.6

| Red Hat Enterprise Linux (RHEL)
| Certified 7.2; Supported 7.x

Certified 6.5; Supported 6.x

| SUSE Linux Enterprise Server (SLES)
| Certified 12; Supported 12.x

Certified 11.4; Supported 11.x

| Ubuntu
| Certified 16.04

Certified 14.04

| Windows Server
| Certified 2016 Standard; Supported with monthly rollups

Certified 2012 R2 Standard; Supported with monthly rollups
|===

* _Amazon Linux is only supported when it is run using the official Couchbase Server AMI on AWS_.

** _Only the Red Hat Compatible Kernel (RHCK) is supported.
The Unbreakable Enterprise Kernel (UEK) is not supported_.

.Supported Operating Systems for Development and Testing
[cols="100,187"]
|===
| *Operating System* | *Version*

| macOS
| Certified 10.11 (El Capitan), 10.12 (Sierra), 10.13 (High Sierra)

| Windows
| Certified 10 Anniversary Update
|===

[NOTE]
====
For information about the platform support changes in this release, see the xref:release-notes:relnotes.adoc[release notes].

For information about supported web browsers, see xref:install-browsers.adoc[Supported Web Browsers].
====
