= Installing on Linux
:page-topic-type: concept

[abstract]
Couchbase Server runs on several Linux systems: Red Hat, CentOS, Ubuntu, Debian, SuSE Enterprise, and Oracle Enterprise.

You can download Couchbase Server directly to a Linux system by using the [.cmd]`wget` or [.cmd]`curl` command.

The basic syntax of the [.cmd]`wget` command is:

 $ wget [option]... [url]...

For example, the following command downloads a version of Couchbase Server that runs on CentOS 7:

 $ wget http://packages.couchbase.com/releases/version/couchbase-server-enterprise-version-centos7_x86_64.rpm

TIP: To find the proper URL to specify in the [.cmd]`wget` command, go to http://www.couchbase.com/nosql-databases/downloads[^] and copy the download link for your specific operating system.

IMPORTANT: RHEL6 and other newer Linux distributions are known to have the Transparent Huge Pages (THP) feature enabled by default.
THP can cause issues in database software, including Couchbase Server.
THP can cause nodes to lose cluster heartbeats and auto-fail-over.
xref:thp-disable.adoc[Disabling THP] prior to installing Couchbase Server is strongly encouraged.
