[#topic1634]
= Supported Platforms

[abstract]
Couchbase Server is supported on numerous popular operating systems and virtual environments.
All options listed below are 64-bit compatible.

.Supported Platforms for Development, Testing, and Production
[cols="13,10"]
|===
| *Platform* | *Version*

| Red Hat Enterprise Linux
| Certified 7.2, Supported 7.x

| Red Hat Enterprise Linux
| Certified 6.5, Supported 6.x

| SUSE Enterprise Linux
| Certified 12

| SUSE Enterprise Linux
| Certified 11.4, Supported 11.x

| Oracle Enterprise Linux*
| Certified 7

| Oracle Enterprise Linux*
| Certified 6.6

| Ubuntu Linux
| Certified 16.04

| Ubuntu Linux
| Certified 14.04

| CentOS
| Certified 7.2, Supported 7.x

| CentOS
| Certified 6.5, 6.7, Supported 6.x

| Debian Linux
| Certified 9

| Debian Linux
| Certified 8

| Amazon Linux**
| 2017.09

| Windows 2016
| Certified Standard, Supported with monthly roll-up updates

| Windows 2012
| Certified Standard R2, Supported with monthly roll-up updates
|===

.Supported Platforms for Development and Testing
|===
| *Platform* | *Version*

| Windows 10
| Anniversary Edition

| Mac OS X
| Certified 10.12 (Sierra)

| Mac OS X
| Certified 10.11
|===

Certified: Certified means that on this OS version, Couchbase Server has passed our extensive testing and review process to make sure it runs well out of the box.

Supported: Supported means that on this OS version, we believe that Couchbase Server will run well out of the box but extensive testing has not been carried out with that OS version.
We will make our best effort to investigate the issue on a compatible OS version, but recommend you run Couchbase on the certified OS version.

* _ Only the Red Hat Compatible Kernel (RHCK) is supported, the Unbreakable Enterprise Kernel is not a supported platform_.

** _Amazon Linux only supported when run using the official Couchbase Server AMI on AWS_.

[NOTE]
====
The following platforms are no longer supported:

[#ul_arx_kgx_4y]
* Microsoft Windows 7
* Microsoft Windows 8
* Microsoft Windows 2008
* Amazon Linux 2014.03, 2016.03
* Ubuntu Linux 12.04
* Debian Linux 7
* Mac OS X 10.10, 10.9, 10.8
====

For more information on the supported web browsers, see xref:install-browsers.adoc#topic765[Supported Web Browsers].

For more information on deprecated items, see xref:release-notes:relnotes.adoc#topic_gbk_tyh_t5[Release Notes].
