[#ipv6-setup]
= IP Version 6: Set-Up Procedures

[abstract]
Couchbase Server supports IP version 6.
Set-up is required for each platform.

[#ipv6-overview]
== IP Version 6 Overview

Support for IP version 6 is provided only by Couchbase Server _Enterprise Edition_.
Set-up is required for each platform, as described in the sections below.
Note that while the steps for Linux and MacOS are to be performed _after_ the basic installation procedure is complete; the steps for Windows are integrated into the basic installation procedure itself.

See xref:get-started.adoc[Couchbase Server Installation Home] for all information on server-installation.

[#linux-ipv6-setup]
== IPv6 Set-Up for Linux

After the couchbase package (rpm or deb file) has been installed, the `couchbase` service is started by default.
To enable IPv6, proceed as follows:

. Stop the `couchbase` service.

. In `/opt/couchbase/etc/couchbase/static_config`, set `ipv6` to `true`.

. Delete `/opt/couchbase/var/lib/couchbase/config/config.dat`.

. Restart the `couchbase` service: this starts Couchbase Server in IPv6 mode.
To check, point the browser at `+http://[::1]:8091+`, which is the IPv6 address and port number on which Couchbase Server should be running.

[#windows-ipv6-setup]
== IPv6 Set-Up for Windows

IPv6 set-up requirements are incorporated into the InstallShield wizard itself: during installation of the Couchbase package, a checkbox allows the user to enable IPv6 mode.
(Note that after installation, any subsequent mode-change requires reinstallation.)

[#macos-ipv6-setup]
== IPv6 Set-Up for MacOS

After installation of the Couchbase package, proceed as follows:

. Stop the `coudhbase` service.

. In `/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/etc/couchbase/static_config.in`, set `ipv6` to `true`.

. Delete `~/Library/Application\ Support/Couchbase/var/lib/couchbase/config/config.dat`.

. Restart the `couchbase` service: this starts the server in IPv6 mode.
To check, point the browser at `+http://[::1]:8091+`, which is the IPv6 address and port number on which Couchbase Server should be running.
