= Using IPv6 With Couchbase

[abstract]
Couchbase Server supports IP version 6 (IPv6).
Set-up is required for each platform.

[caption=Attention]
IMPORTANT: IPv6 support is only available in Couchbase Server Enterprise Edition.

[#ipv6-overview]
== IPv6 Overview

By default, when Couchbase Server starts up, it uses IPv4.
To enable IPv6, set-up is required for each platform, as described in the sections below.
Note that the steps for Linux and macOS are to be performed _after_ the basic Couchbase Server installation is complete, and the steps for Windows are integrated into the basic installation procedure itself.

NOTE: In a clustered setup, IPv6 is enabled only when IPv6 is enabled on all of the nodes.

See xref:install-intro.adoc[Installing the Couchbase Server Cluster] for more information about installation procedures.

[#linux-ipv6-setup]
== IPv6 Set-Up for Linux

After the Couchbase Server package has been installed, the `couchbase` service is started by default.
Select the appropriate set-up procedure from the two procedures provided below, according to the cluster’s Couchbase _server-version_.

=== Version 6.0.0

Proceed as follows:

. Stop the `couchbase-server` service.
. In `/opt/couchbase/etc/couchbase/static_config`, set `ipv6` to `true`.
. Delete `/opt/couchbase/var/lib/couchbase/config/config.dat`.
. Restart the `couchbase-server` service (this starts Couchbase Server in IPv6 mode).
To check, point a supported web browser to  `http://[::1]:8091`, which is the IPv6 address and port number on which Couchbase Server should be running.

This concludes the procedure.

=== Version 6.0.1

Proceed as follows:

. On each node, execute the following command:
+
----
curl http://<node-ip-address>:8091/node/controller/setupNetConfig -u <AdminName> -d 'afamily=ipv6'
----

. Restart the node.
(See xref:install:startup-shutdown.adoc[Startup and Shutdown] for instructions.)

This concludes the procedure.

[#windows-ipv6-setup]
== IPv6 Set-Up for Windows

IPv6 set-up requirements are incorporated into the InstallShield wizard itself.
During installation of the Couchbase package, a check box is available to enable IPv6 mode.
(Note that after installation, any subsequent mode-change requires re-installation.)

[#macos-ipv6-setup]
== IPv6 Set-Up for macOS

For a macOS-based cluster, after installing the Couchbase Server application, select the appropriate set-up procedure from the two procedures provided below, according to the cluster’s Couchbase server-version.

=== Version 6.0.0

Proceed as follows:

. Ensure that the `couchbase-server` service is stopped.
(Quit the Couchbase Server application, if it is running.)
. In `/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/etc/couchbase/static_config.in`, set `ipv6` to `true`.
. Delete `~/Library/Application\ Support/Couchbase/var/lib/couchbase/config/config.dat`.
. Restart the `couchbase-server` service (this starts Couchbase Server in IPv6 mode).
To check, point a supported web browser to  `http://[::1]:8091`, which is the IPv6 address and port number on which Couchbase Server should be running.

This concludes the procedure.

=== Version 6.0.1

Proceed as follows:

. On each node, execute the following command:
+
----
curl http://<node-ip-address>:8091/node/controller/setupNetConfig -u <AdminName> -d 'afamily=ipv6'
----

. Restart the node.
(See xref:install:startup-shutdown.adoc[Startup and Shutdown], for instructions.)

This concludes the procedure.
