[#topic3637]
= Installing on Mac OS X

[abstract]
Mac OS 10.9, 10.10, and 10.11 are supported for development purposes only.

When installing Mac OSX nodes, only 64 bit systems are supported.
Before you install, verify the list of xref:install-platforms.adoc#topic1634[supported platforms].

The Mac OS X installation uses a zip file with a stand-alone application that must be copied to the `Applications` folder.
The installation location is not the same as the location of the Couchbase data files.

Use Archive Utility, the default archive file handler in Mac OS X, to unpack the Couchbase Server distribution.
It is more difficult to diagnose non-functioning or damaged installations after extraction by other third party archive extraction tools.

For information on installing Couchbase Server on IPv6 systems, see xref:ipv6-setup.adoc[IP Version 6: Set-Up Procedures].

== Prerequisites

Delete any previous installations of Couchbase Server using the command line or by dragging the icon to the Trash can.

Remove remaining files from previous installations using these commands:

----
 rm -rf ~/Library/Application\ Support/Couchbase
 rm -rf ~/Library/Application\ Support/Membase
----

== Installing with UI or CLI

To install Couchbase Server on Mac OSX use the GUI or the command line interface.

. Locate the downloaded Couchbase Server `.zip` file, which typically is located in the default [.path]_/Downloads_ folder.
. Double-click the downloaded `.zip` installation file to extract the server.
This creates a single folder, the `Couchbase Server.app` application.
. Drag-and-drop `Couchbase Server.app` to the system [.path]_/Applications_ folder.

After the installation completes, double-click on `Couchbase Server.app` to start Couchbase Server.
The Couchbase Server icon appears in the menu bar on the right-hand side.
If the server was not configured, the setup process can be completed from the Couchbase Web Console.

Couchbase Server runs as a background application.
Click on the icon in the menu bar for list of operations that can be performed.

The command line interface (CLI) tools are included in the Couchbase Server application directory.
Access the CLI from a terminal window and use the full path of the Couchbase Server installation.
This is [.path]_/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin/_ by default.

[IMPORTANT,caption=Attention]
====
The initial sample Couchbase Server administrator user credentials are as follows:

* Username: [.in]`Administrator`
* Password: [.in]`password`.
====

Change the user name and password to your preferred values immediately after the initial login to the Couchbase Web Console.

== Installing as non-root, non-sudo

When installing Mac OSX nodes, only 64 bit systems are supported.

If you perform a non-sudo, non-root installation, you can run Couchbase Server and all its command-line tools.

To install as non-root, non-sudo:

. After downloading Couchbase Server, open terminal and go to the Downloads directory:
+
----
cd ~/Downloads/
----

. Unzip the package containing Couchbase Server:
+
----
open couchbase-server-version.zip
----

. Move Couchbase Server application to your [.path]_/Applications_ folder:
+
----
mv couchbase-server-version/Couchbase\ Server.app /Applications/
----

. Start Couchbase Server from the terminal:
+
----
open /Applications/Couchbase\ Server.app
----
+
This enables you to use Couchbase Server as a non-sudo, non-root user.

. To stop the Couchbase Server, click on its icon in the menu bar and select [.uicontrol]*Quit Couchbase Server*.
