= Enabling Timestamp-based Conflict Resolution for Migrated Data

[abstract]
The Timestamp-based Conflict Resolution is a new conflict resolution type added in version 4.6.0.
This new feature is supported for *new* buckets that are created in Couchbase Server version 4.6.0.
You cannot change the conflict resolution mode to the _Timestamp-based Conflict Resolution_ for existing buckets after upgrading to version 4.6.0.

If you wish to enable the timestamp-based conflict resolution for your existing data, then you must migrate your data to version 4.6.0 cluster using the `cbbackupmgr` tool.
To learn more about the tool, see xref:backup-restore:enterprise-backup-restore.adoc[cbbackupmgr tool].

IMPORTANT: This is a one time migration and the bucket must be switched to a new conflict resolution type as part of the migration.

To understand more about timestamp-based Conflict Resolution, see
xref:learn:clusters-and-availability/xdcr-conflict-resolution.adoc#timestamp-based-conflict-resolution[Timestamp-Based
Conflict Resolution].

Here are two scenarios:

* Scenario 1 - In case of unidirectional replication, for example, for a disaster recovery where Cluster 1 (Bucket A) has one way replication streams to Cluster 2 (Bucket A’).
* Scenario 2 - In case of bidirectional replication, for example, for data locality where Cluster 1 (Bucket A) has both ways replication streams to Cluster 2 (Bucket A’).

For Scenario 1, perform the following steps to migrate your data to a new cluster:

. Stop application traffic coming into Cluster 1 (Bucket A).
+
NOTE: Allow __enough tim__e for the replication queues to drain.
Check the *outbound XDCR mutation* statistics to confirm.
For instructions, see xref:monitoring:ui-monitoring-statistics.adoc#outgoing_xdcr_stats[Monitoring Outgoing XDCR].

. Stop and delete Replication stream to Cluster 2 (Bucket A’).
For instructions, see xref:xdcr:xdcr-create.adoc#delete-replication[Delete Replication].
. Run the `cbbackupmgr` tool to backup the entire bucket’s (Bucket A) data.
For instructions, see  xref:backup-restore:enterprise-backup-restore.adoc[cbbackupmgr tool].
. Delete Bucket A from Cluster 1.
For instructions, see xref:clustersetup:delete-bucket.adoc[Delete a Bucket].
. Upgrade Cluster 1 to Couchbase Server version 4.6.0.
For instructions, see xref:upgrade.adoc[Upgrading Couchbase Server].
. Create a new Bucket B with the conflict resolution type as *Timestamp* selected.
For instructions, see xref:clustersetup:create-bucket.adoc[Create a New Bucket].
. Run the `cbbackupmgr` tool to restore data.
When restoring data from backup (use the [.cmd]`--force-updates` option).
Make sure to disable the *Conflict Resolution* option during the restore.
This is required since the conflict resolution types of the source and destination clusters do not match.
. Once the restore operation is completed on Cluster 1, delete Bucket A’ from Cluster 2.
. Upgrade Cluster 2 to Couchbase Server version 4.6.0.
. Create a new Bucket B’ with the Conflict Resolution type as *Timestamp* selected.
. Create a new unidirectional replication for Bucket B.
For instructions, see xref:xdcr:xdcr-create.adoc#create-replication[Create Replication].

For Scenario 2, perform the following steps to migrate your data to a new cluster:

. Stop application traffic coming to Cluster 1 (Bucket A) and Cluster 2 (Bucket A’).
+
NOTE: Note: Allow _enough time_ for the replication queues to drain.
Check the *outbound XDCR mutation* statistics to confirm.
For instructions, see xref:monitoring:ui-monitoring-statistics.adoc#outgoing_xdcr_stats[Monitoring Outgoing XDCR].

. Stop and delete replication to both clusters.
For instructions, see xref:xdcr:xdcr-create.adoc#delete-replication[Delete Replication].
. Run the `cbbackupmgr` tool to backup the entire bucket data on both clusters.
For instructions, see  xref:backup-restore:enterprise-backup-restore.adoc[cbbackupmgr tool].
. Delete the Bucket A from Cluster 1 and Bucket A’ from Cluster 2.
For instructions, see xref:clustersetup:delete-bucket.adoc[Delete a Bucket].
. Upgrade both clusters to Couchbase Server version 4.6.0.
For instructions, see xref:upgrade.adoc[Upgrading Couchbase Server].
. Create new buckets on both clusters with the conflict resolution type as *Timestamp* selected.
For instructions, see xref:clustersetup:create-bucket.adoc[Create a New Bucket].
. Run the `cbbackupmgr` tool to restore data.
When restoring data from backup (use the [.cmd]`--force-updates` option).
Make sure to disable *Conflict Resolution* option during the restore.
This is required because the conflict resolution types of the source and destination do not match.
. Once the restore operation is completed on both clusters, create replication streams both ways from Cluster 1 and Cluster 2.
For instructions, see xref:xdcr:xdcr-create.adoc#create-replication[Create Replication].
