= Migrating from Relational Databases
:description: Migration guidelines for relational database users. \
In this section, we use MySQL as an example relational database.
:page-topic-type: concept

[abstract]
{description}

When migrating from MySQL to Couchbase Server, there are several things that you might want to think about, starting with the data model, data types, and feature set differences.

== Data Model -- Mapping from MySQL to Couchbase Server

Data modeling for RDBMS has been a well-defined discipline for many years.
Professionals, including novice users, have been practicing techniques such as logical to physical mapping and normalization / de-normalization.
However, the old-school RDBMS data modeling techniques still play a meaningful role for those who are new to the NoSQL technology.

.Concept mapping between MySQL and Couchbase Server
|===
| MySQL | Couchbase Server

| Database
| Bucket

| Table
| Bucket(s)/Keyspaces

| Row
| Document

| Column
| Field

| Fixed schema
| Flexible schema
|===

.Datatype mapping between MySQL and Couchbase Server
|===
| Data type | MySQL | Couchbase Server

| Case sensitive
| Yes/No
| Yes

| Numbers
| Yes
| Yes

| String
| Yes
| Yes

| Boolean
| Yes (as `tinyint`)
| Yes

| Date time
| Yes
| Yes (as a string in JSON)

| Spatial data
| Yes
| Yes

| MISSING
| No
| Yes

| NULL
| Yes
| Yes

| Object/Arrays
| No
| Yes

| Blobs
| Yes
| Yes
|===

== Feature Set

Like MySQL, Couchbase Server offers a rich set of features and functionality far beyond those offered in simple key-value stores.

With Couchbase Server, you also get an expressive SQL-like query language and query engine called xref:n1ql:n1ql-language-reference/index.adoc[{sqlpp}], which is combined with a new powerful indexing mechanism -- xref:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[Global Secondary Indexes].

.Feature differences between MySQL and Couchbase Server
[cols="1,3"]
|===
| Feature | Key difference

| Keys/Indexes
| Primary keys on keys of (key, value) pair

| SQL statements
a|
. The result is set in JSON instead of rows and columns.
. NEST, UNNEST
. Operations on datetime fields require datetime functions in {sqlpp}.
. JSON-induced functions in {sqlpp}: JSON, Object, and array functions.
. Type and comparison functions.
. JOIN, sub-query format differences.
. `USING KEYS` and ON KEYS functions

| Explain and metadata
| Variation in command and results (JSON).
|===

== ETL Tools

You might have a spectrum of relational, operational, and analytical data sources in your environment.
You might also need more sophistication applied to a data movement situation, such as more than just simple extract-load.
Various tools are available, but the most common use cases are best served by combining our xref:connectors:odbc-jdbc-drivers.adoc[JDBC drivers] with our xref:java-sdk:hello-world:start-using-sdk.adoc[Java SDK].
