= Enabling Timestamp-based Conflict Resolution for Migrated Data
:description: The Timestamp-based Conflict Resolution method is the latest conflict resolution type available for a bucket.

Use timestamp-based conflict resolution for transactions and the latest Couchbase features.
You cannot change the conflict resolution type of an existing bucket.
If the bucket was not created with timestamp-based conflict resolution, migrate the data to use it.

[abstract]
{description}
Couchbase Server supports this feature for new buckets.

To enable timestamp-based conflict resolution for existing data, migrate the data to a new bucket with the timestamp-based conflict resolution type,
using the `cbbackupmgr` tool.
For more information about the `cbbackupmgr` tool, see xref:backup-restore:backup-restore.adoc[Backup and Restore].

IMPORTANT: This is a one time migration.
The bucket without timestamp-based conflict resolution must be removed and a new bucket with the xref:learn:clusters-and-availability/xdcr-conflict-resolution.adoc#timestamp-based-conflict-resolution[timestamp-based conflict resolution] type must be created as part of the migration.

These are 2 scenarios:

* Scenario 1: Unidirectional replication for disaster recovery -
Cluster 1 (Bucket A) continuously replicates data into Cluster 2 (Bucket A'), which is one way.

* Scenario 2: Bidirectional replication for data locality -
Cluster 1 (Bucket A) and Cluster 2 (Bucket A’) replicate data into each other.

== Migration during Unidirectional Replication

Follow these steps to migrate your data to a new bucket during unidirectional replication:

. Stop application traffic coming into Cluster 1 (Bucket A).
+
NOTE: Allow enough time for the replication queues to drain.
Confirm by reviewing the XDCR Total Outbound Mutations statistic derived from `xdcr_changes_left_total`.
For more information, see xref:manage:monitor/monitor-intro.html#monitoring-with-the-ui[].

. Stop and delete the replication stream to Cluster 2 (Bucket A’).
For instructions, see
xref:manage:manage-xdcr/xdcr-management-overview.adoc[XDCR Management Overview].

. Run the `cbbackupmgr` tool to back up the bucket’s (Bucket A) data.
For instructions, see xref:backup-restore:enterprise-backup-restore.adoc[Backup].

. Delete Bucket A from Cluster 1.
For instructions, see
xref:manage:manage-buckets/delete-bucket.adoc[Delete a Bucket].

. Create Bucket B on Cluster 1 and select the Timestamp-based Conflict Resolution type.
For instructions, see
xref:manage:manage-buckets/create-bucket.adoc[Create a Bucket].

. Run the `cbbackupmgr` tool on Cluster 1 to restore data to Bucket B.
Use the xref:backup-restore/ccbackupmgr-restore.adoc[`cbbackupmgr restore`] command with the option `--force-updates` to restore data from the backup.
This option turns off conflict resolution during the restore,
and it's needed because the bucket you're restoring to has a different conflict resolution type than the bucket the backup is from.
+
NOTE: The `--force-updates` option also updates the CAS of the restored documents.

. After the data restore operation is complete on Cluster 1, delete Bucket A’ from Cluster 2.

. Create Bucket B’ on Cluster 2 and select the Timestamp-based Conflict Resolution type.

. Create a new unidirectional replication for Bucket B.
See xref:manage:manage-xdcr/xdcr-management-overview.adoc[XDCR Management Overview].

== Migration during Bidirectional Replication

Follow these steps to migrate your data to a new bucket during bidirectional replication:

. Stop application traffic coming into Cluster 1 (Bucket A) and Cluster 2 (Bucket A’).
+
NOTE: Allow enough time for the replication queues to drain.
Confirm by reviewing the XDCR Total Outbound Mutations statistic derived from `xdcr_changes_left_total`.
For more information, see xref:manage:monitor/monitor-intro.html#monitoring-with-the-ui[].

. Stop and delete the replication streams to both clusters.
For instructions, see
xref:manage:manage-xdcr/xdcr-management-overview.adoc[XDCR Management Overview].

. Run the `cbbackupmgr` tool on both clusters to backup the bucket data.
For instructions, see
xref:backup-restore:enterprise-backup-restore.adoc[Backup].

. Delete the Bucket A from Cluster 1 and Bucket A’ from Cluster 2.
For instructions, see
xref:manage:manage-buckets/delete-bucket.adoc[Delete a Bucket].

. Create buckets on both clusters and select the Timestamp-based Conflict Resolution type.
For instructions, see xref:manage:manage-buckets/create-bucket.adoc[Create a Bucket].

. Run the `cbbackupmgr` tool to restore data.
Turn off the Conflict Resolution setting on the destination cluster and then use the `--force-updates` option to restore data from backup.
Do this because the source and destination clusters have different conflict resolution types.
Use the xref:backup-restore/ccbackupmgr-restore.adoc[`cbbackupmgr restore`] command with the option `--force-updates` to restore data from the backup.
This option turns off conflict resolution during the restore,
and it's needed because the bucket you're restoring to has a different conflict resolution type than the bucket the backup is from.
+
NOTE: The `--force-updates` option also updates the CAS of the restored documents.

. After the restore operation is complete on both clusters, create replication streams both ways between Cluster 1 and Cluster 2.
For more information, see xref:manage:manage-xdcr/xdcr-management-overview.adoc[XDCR Management Overview].
