= Software, Hardware, and Network Requirements

[abstract]
This section provides information to set up Couchbase Server on production environment.
Planning for production involves ensuring that the hardware and software requirements are met, and the deployment and security consideration are taken into account before installing the server.
You can choose to install Couchbase Server on-premises on supported platforms or on virtualization platforms.

For installation instructions on different platforms, see:

* xref:install-intro.adoc[On-premises]
* xref:getting-started-docker.adoc[Docker]
* xref:cloud:couchbase-cloud-deployment.adoc[Cloud]

== Select Couchbase Server Edition

Couchbase Server comes in two different editions: Enterprise Edition and Community Edition.
Each edition offers different features and levels of support.
For a comparison between the features between Enterprise and Community editions, see xref:introduction:editions.adoc[Couchbase Server Editions].
We recommend using the Enterprise Edition for production environments.
