[#topic_tqm_rcx_fw]
= Software, Hardware, and Network Requirements

[abstract]
This section provides information to set up Couchbase Server on production environment.
Planning for production involves ensuring that the hardware and software requirements are met, and the deployment and security consideration are taken into account before installing the server.
You can choose to install Couchbase Server on-premises on supported platforms or on virtualization platforms.

Before you begin the actual installation, ensure that you go through the section .

For installation instructions on different platforms, see:

[#ul_wv3_zbx_fw]
* xref:install-intro.adoc[On-premises]
* xref:getting-started-docker.adoc[Docker container]
* xref:cloud-deployment.adoc[Virtualization platforms]

== Select Couchbase Server Edition

Couchbase Server comes in two different editions: Enterprise Edition and Community Edition.
Each edition offers different features and levels of support.
The https://www.couchbase.com/products/editions[Couchbase Editions^] page provides a comparison between the features between Enterprise and Community editions.
We recommend using the Enterprise Edition for production environments.
