= System Resource Requirements

[abstract]
Although resource requirements will largely depend on the size and resource demands of your Couchbase deployment, there are some minimum and recommended specifications that you should follow.

[cols="80,180,180"]
|===
| | Minimum Specifications* | Recommended Specifications**

| *CPU*
| 2 GHz dual core x86_64
| 3 GHz quad core x86_64 and above

3 GHz six core x86_64 when using Cross Datacenter Replication (XDCR) and Views

| *RAM*
| 4 GB (physical)
| 16 GB (physical) and above

| *Storage (disk space)*
a|
8 GB (block-based; HDD, SSD, EBS, iSCSI)

Network file systems such as CIFS and NFS are not supported.
a|
16 GB and above (block-based; HDD, SSD, EBS, iSCSI)

Network file systems such as CIFS and NFS are not supported.
|===

*_You can reduce the CPU and RAM resources below the Minimum Specifications for development and testing purposes.
Resources can be as low as 1 GB of free RAM beyond operating system requirements, and a single CPU core.
However, you must adhere to the Minimum Specifications for production._

**_The Recommended Specifications don't take into account your intended workload.
You should follow the xref:sizing-general.adoc[sizing guidelines] when determining system specifications for your Couchbase Server deployment._
