= Installing Using rpm

[abstract]
Install Couchbase Server on RHEL using the [.cmd]`rpm` command-line tool with the downloaded RPM package.

Only 64-bit systems are supported.
See xref:install-platforms.adoc[Supported platforms] for details.

== Disable Transparent Huge Pages (THP)

To disable THP, see xref:thp-disable.adoc[Transparent Huge Pages (THP)].

== Complete the Installation

You must be logged in as `root` (superuser) or use the [.cmd]`sudo` command to complete the installation.
Use the following command to install the Couchbase Server package:

----
rpm --install couchbase-server-version.rpm
----

where [.var]`version` is the version number of the downloaded package.

After the [.cmd]`rpm` command completes, the Couchbase Server service starts automatically.
It is configured to start automatically under OS runlevels 2, 3, 4, and 5.
Refer to the Red Hat RPM documentation for more information about installing packages using RPM.

After installation is completed, the installation process displays a message similar to the following:

----
Minimum RAM required : 4 GB
System RAM configured : 8174464 kilobytes
    Minimum number of processors required :  4 cores
    Number of processors on the system : 4 cores


Starting couchbase-server[ OK ]

You have successfully installed Couchbase Server.
    Browse to http://host_name:8091/ to configure your server.
   Refer to http://couchbase.com for additional resources.

   Update your firewall configuration
    to allow connections to the following ports:

    11211, 11210, 11209, 4369, 8091, 8092 and from 21100 to 21299.


By using this software you agree to the End User License Agreement.
See /opt/couchbase/LICENSE.txt.
----

After the installation is completed, use the [.cmd]`service` command to manage the Couchbase Server service, including checking the current status.
Refer to the Ubuntu documentation for instructions.

To perform the initial Couchbase Server setup, open a web browser and access the Couchbase Web Console.
