= Install Couchbase Server on Red Hat Enterprise, Oracle Linux, or Amazon Linux 2023
:description: Couchbase Server can be installed on Red Hat Enterprise Linux, Oracle Linux, or Amazon Linux 2023 for production and development use-cases.
:tabs:

[abstract]
{description}

Couchbase Server supports both root and non-root installations of Red Hat Enterprise Linux, Oracle Linux, and Amazon Linux 2023.

Use the instructions on this page to install Couchbase Server on Red Hat Enterprise Linux, Oracle Linux, or Amazon Linux 2023 using Couchbase-provided RPM packages.
The instructions support both Enterprise and Community https://www.couchbase.com/products/editions[editions^].

If you're upgrading an existing Couchbase Server instance, see xref:upgrade.adoc[Upgrading Couchbase Server].

== Before You Install

Couchbase Server works out-of-the-box with most OS configurations.
However, the following are the prerequisites for installation:

* Your system meets the xref:pre-install.adoc[minimum requirements] and that your operating system version is xref:install-platforms.adoc[supported].

* You're working from a clean system and that you have xref:install-uninstalling.adoc[uninstalled] any previous versions of Couchbase Server.
+
If you're upgrading an existing installation of Couchbase Server, see xref:upgrade.adoc[Upgrading Couchbase Server].

* For Oracle Linux, only the Red Hat Compatible Kernel (RHCK) is supported.
The Unbreakable Enterprise Kernel (UEK) is not supported.

* For production deployments, make sure to follow the xref:install-production-deployment.adoc[deployment guidelines] so that your systems and environment are properly sized and configured before installation.

== Basic Installation

This section explains installation using both `yum` and RPM package methods.

NOTE: You must be logged in as root user (superuser) or use `sudo` to run the installation commands.

=== Install Using Yum

The Red Hat package manager `yum` provides the simplest and most comprehensive way to install Couchbase Server on Red Hat Enterprise or Oracle Linux.
This method involves downloading and installing a small meta package from Couchbase, which is used by `yum` to automatically download and install Couchbase Server and all of its dependencies.

. Download the meta package.
+
[source,console]
----
curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0.noarch.rpm
----

. Install the meta package.
+
[source,console]
----
sudo rpm -i ./couchbase-release-1.0.noarch.rpm
----
+
The meta package installs the necessary information for `yum` to retrieve all necessary Couchbase Server installation packages and dependencies.

. Install Couchbase Server.
+
[{tabs}]
====
Enterprise::
+
--
.To install the latest release
[source,console]
----
sudo yum install couchbase-server
----
You'll be prompted to start the download of Couchbase Server (plus any dependencies), as well as import several GPG keys.
For each of these prompts, type `y` to accept and continue.

.To install a specific release
. List the available releases.
+
[source,console]
----
yum list --showduplicates couchbase-server
----
+
Available releases are listed with their complete `version-build` number:
+
[subs=+quotes]
----
couchbase-server.x86_64 <version_number>-<build_number>
----
+
The following is an example of the listing:
[subs=+quotes]
----
couchbase-server.x86_64 *8.0.0-3777*
----

. Specify a release to install it.
+
[source,console,subs=+quotes]
----
sudo yum install couchbase-server-<version_number>-<build_number>
----
+
The following is an example of the installation command:
+
[subs=+quotes]
----
sudo yum install couchbase-server-*8.0.0-3777*
----
+
You'll be prompted to start the download of Couchbase Server and its dependencies, and import several GPG keys.
For each of these prompts, type `y` to accept and continue.
--

Community::
+
--
.To install the latest release
[source,console]
----
sudo yum install couchbase-server-community
----
You'll be prompted to start the download of Couchbase Server and its dependencies, and import several GPG keys.
For each of these prompts, type `y` to accept and continue.

.To install a specific release
. List the available releases.
+
[source,console]
----
yum list --showduplicates couchbase-server-community
----
+
Available releases are listed with their full `version-build` number:
+
[subs=+quotes]
----
couchbase-server-community.x86_64 <version_number>-<build_number>
----
+
The following is an example of the listing:
[subs=+quotes]
----
couchbase-server-community.x86_64 *8.0.0-3777*
----

. Specify a release to install it.
+
[source,console,subs=+quotes]
----
sudo yum install couchbase-server-community-<version_number>-<build_number>
----
+
The following is an example of the installation command:
+
[subs=+quotes]
----
sudo yum install couchbase-server-community-*8.0.0-3777*
----
+
You'll be prompted to start the download of Couchbase Server and its dependencies, and import several GPG keys.
For each of these prompts, type `y` to accept and continue.
--
====
+
After the installation is complete, Couchbase Server starts automatically.
Couchbase Server continues to start automatically at run levels 2, 3, 4, and 5, and explicitly shuts down at run levels 0, 1, and 6.
You can use the `systemctl` command, a `service` on older operating systems, to start and stop the Couchbase Server service, and to verify the current status.
For more information, see xref:startup-shutdown.adoc[Couchbase Server Startup and Shutdown].
+
. Open the Couchbase Web Console in a browser to xref:testing.adoc[verify] that the installation was successful and that the node is available.

=== Install Using RPM Package

Install Couchbase Server on Red Hat Enterprise or Oracle Linux or Amazon Linux 2023 using a full RPM package provided by Couchbase.

. Download the appropriate package from the Couchbase https://www.couchbase.com/downloads[downloads page^].

. Install Couchbase Server.
+
** For Red Hat Enterprise, use the following command:
+
[source,console,subs=+quotes]
----
sudo yum upgrade ./[.var]_package-name_.rpm
----
+
** For Oralce Linux, use the following command:
+
[source,console,subs=+quotes]
----
sudo yum install ./[.var]_package-name_.rpm
----
+
** For Amazon Linux 2023, use the following command:
+
[source,console,subs=+quotes]
----
sudo rpm --install [.var]_package-name_.rpm
----
+
If any Couchbase Server dependencies are missing on your system, `yum` automatically downloads and installs them as part of the installation process.
+
After the installation is complete, Couchbase Server starts automatically.
Couchbase Server starts automatically at run levels 2, 3, 4, and 5, and explicitly shuts down at run levels 0, 1, and 6.
You can use the `systemctl` command, a `service` on older operating systems, to start and stop the Couchbase Server service, and to verify the current status.
For more information, see xref:startup-shutdown.adoc[Couchbase Server Startup and Shutdown].

. Open the Couchbase Web Console in a browser to xref:testing.adoc[verify] that the installation was successful and that the node is available.

[#rh-nonroot-nonsudo-]
== Installing as Non-Root

Non-root installation process is identical for all supported Linux distributions, including Red Hat Enterprise, Oracle Linux, and Amazon Linux 2023.
For instructions, see xref:install:non-root.adoc[Non-Root Install and Upgrade].

== Setting Max Process Limits

Couchbase recommends that, on Red Hat Enterprise, you increase the maximum process limits for Couchbase.

To set the process limits, create a `.conf` file in the `/etc/security/limits.d` directory such as `91-couchbase.conf`, and add the following values:

[source,console]
----
couchbase soft nproc 4096
couchbase hard nproc 16384
----

For more information about non-root installation and upgrade, see xref:install:non-root.adoc#establish-limits-for-user-processes-and-file-descriptors[Establish Limits for User Processes and File Descriptors].

== Next Steps

After you install and start Couchbase Server, initialize and provision a node.

* If it's the first node in a deployment, initialization and provisioning happens all at once when you create a cluster of one.
+
For more information, see xref:manage:manage-nodes/create-cluster.adoc[Create a Cluster].

* If you already have an existing cluster, the node is initialized and provisioned when you add it to the cluster.

For more information, see xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a Node and Rebalance].

* Optionally, you can initialize a node explicitly and independently of provisioning, as a prior process.
This is to establish configurations such as custom disk-paths.

For more information, see xref:manage:manage-nodes/initialize-node.adoc[Initialize a Node].
