= Install Couchbase Server on Red Hat Enterprise
:description: Couchbase Server can be installed on Red Hat Enterprise Linux for production and development use-cases.
:tabs:

[abstract]
{description}
Root and non-root installations are supported.

Use the instructions on this page to install Couchbase Server on Red Hat Enterprise Linux using Couchbase-provided RPM packages.
The instructions support both Enterprise and Community https://www.couchbase.com/products/editions[editions^].

If you're upgrading an existing installation of Couchbase Server, refer to xref:upgrade.adoc[Upgrading Couchbase Server].

== Before You Install

Couchbase Server works out-of-the-box with most OS configurations.
However, the procedures on this page assume the following:

* Your system meets the xref:pre-install.adoc[minimum requirements] and that your operating system version is xref:install-platforms.adoc[supported].
* You're working from a clean system and that you've xref:install-uninstalling.adoc[uninstalled] any previous versions of Couchbase Server.
+
If you're upgrading an existing installation of Couchbase Server, refer to xref:upgrade.adoc[Upgrading Couchbase Server].

For production deployments, make sure to follow the xref:install-production-deployment.adoc[deployment guidelines] so that your systems and environment are properly sized and configured before installation.

== Basic Installation

You must be logged in as root (superuser) or use `sudo` to run the installation commands.

=== Install Using Yum

The Red Hat package manager (`yum`) provides the simplest and most comprehensive way to install Couchbase Server on Red Hat Enterprise.
This method involves downloading and installing a small meta package from Couchbase, which `yum` can then use to automatically download and install Couchbase Server and all of its dependencies.

. Download the meta package.
+
[source,console]
----
curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0.noarch.rpm
----

. Install the meta package.
+
[source,console]
----
sudo rpm -i ./couchbase-release-1.0.noarch.rpm
----
+
The meta package installs the necessary information for `yum` to be able to retrieve all of the necessary Couchbase Server installation packages and dependencies.

. Install Couchbase Server.
+
[{tabs}]
====
Enterprise::
+
--
.To install the latest release
[source,console]
----
sudo yum install couchbase-server
----
You'll be prompted to start the download of Couchbase Server (plus any dependencies), as well as import several GPG keys.
For each of these prompts, type `y` to accept and continue.

.To install a specific release
. List the available releases.
+
[source,console]
----
yum list --showduplicates couchbase-server
----
+
Available releases are listed with their full `version-build` number:
+
[subs=+quotes]
----
couchbase-server.x86_64   *6.0.0-1693*
----
+
. Specify a release to install it.
+
[source,console,subs=+quotes]
----
sudo yum install couchbase-server-[.var]_version-build_
----
+
Using the example listing from the previous step, the resulting installation command would be:
+
[subs=+quotes]
----
sudo yum install couchbase-server-*6.0.0-1693*
----
+
You'll be prompted to start the download of Couchbase Server (plus any dependencies), as well as import several GPG keys.
For each of these prompts, type `y` to accept and continue.
--

Community::
+
--
.To install the latest release
[source,console]
----
sudo yum install couchbase-server-community
----
You'll be prompted to start the download of Couchbase Server (plus any dependencies), as well as import several GPG keys.
For each of these prompts, type `y` to accept and continue.

.To install a specific release
. List the available releases.
+
[source,console]
----
yum list --showduplicates couchbase-server-community
----
+
Available releases are listed with their full `version-build` number:
+
[subs=+quotes]
----
couchbase-server-community.x86_64   *6.0.0-1693*
----
+
. Specify a release to install it.
+
[source,console,subs=+quotes]
----
sudo yum install couchbase-server-community-[.var]_version-build_
----
+
Using the example listing from the previous step, the resulting installation command would be:
+
[subs=+quotes]
----
sudo yum install couchbase-server-community-*6.0.0-1693*
----
+
You'll be prompted to start the download of Couchbase Server (plus any dependencies), as well as import several GPG keys.
For each of these prompts, type `y` to accept and continue.
--
====
+
Once installation is complete, Couchbase Server will start automatically (and will continue to start automatically at run levels 2, 3, 4, and 5, and explicitly shut down at run levels 0, 1, and 6).
You can use the `systemctl` command (`service` on older operating systems) to start and stop the Couchbase Server service, as well as check the current status.
Refer to xref:startup-shutdown.adoc[Couchbase Server Startup and Shutdown] for more information.
+
. Open a web browser and access the Couchbase Web Console to xref:testing.adoc[verify] that the installation was successful and that the node is available.

=== Install Using RPM Package

Install Couchbase Server on Red Hat Enterprise using a full RPM package provided by Couchbase.

. Download the appropriate package from the Couchbase https://www.couchbase.com/downloads[downloads page^].

. Install Couchbase Server.
+
[source,console,subs=+quotes]
----
sudo yum upgrade ./[.var]_package-name_.rpm
----
+
If any Couchbase Server dependencies are missing on your system, `yum` will automatically download and install them as part of the installation process.
+
Once installation is complete, Couchbase Server will start automatically (and will continue to start automatically at run levels 2, 3, 4, and 5, and explicitly shut down at run levels 0, 1, and 6).
You can use the `systemctl` command (`service` on older operating systems) to start and stop the Couchbase Server service, as well as check the current status.
Refer to xref:startup-shutdown.adoc[Couchbase Server Startup and Shutdown] for more information.

. Open a web browser and access the Couchbase Web Console to xref:testing.adoc[verify] that the installation was successful and the node is available.

[#rh-nonroot-nonsudo-]
== Installing as Non-Root

Non-root installation is performed identically for all supported Linux distributions, including Red Hat Enterprise.
For instructions, see xref:install:non-root.adoc[Non-Root Install and Upgrade].

== Setting Max Process Limits

On Red Hat Enterprise, it's recommended that you increase the maximum process limits for Couchbase.

To set the process limits, create a `.conf` file in the `/etc/security/limits.d` directory (such as `91-couchbase.conf`), and add the following values:

[source,console]
----
couchbase soft nproc 4096
couchbase hard nproc 16384
----

For more information (provided in the context of _non-root_ install and upgrade), see xref:install:non-root.adoc#establish-limits-for-user-processes-and-file-descriptors[Establish Limits for User Processes and File Descriptors].

== Next Steps

Following installation and start-up of Couchbase Server, a node must be _initialized_ and _provisioned_.

* If it is the first node in a deployment, initialization and provisioning happens all at once when you create a _cluster of one_.
+
Refer to xref:manage:manage-nodes/create-cluster.adoc[Create a Cluster]

* If you already have an existing cluster, the node is initialized and provisioned when you add it to the cluster.
+
Refer to xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a Node and Rebalance]
+
* Optionally, initialization can be performed explicitly and independently of provisioning, as a prior process, in order to establish certain configurations, such as custom disk-paths.
+
Refer to xref:manage:manage-nodes/initialize-node.adoc[Initialize a Node]
