= Deploying Couchbase Server in Containers

[abstract]
Couchbase Server is designed to run in the most popular container environments.
Use this topic to explore the different ways that you can deploy Couchbase in containers.

<<<<<<< HEAD
With the xref:operator::overview.adoc[Couchbase Autonomous Operator], you can easily automate the deployment of Couchbase Server on container orchestration platforms like Kubernetes and Red Hat OpenShift.

If you want to do a more traditional container deployment in a data center, or simply want to install Couchbase in a container on your laptop, you can download and install the official images from Docker Hub.

.Container Deployment Methods
|===
| Couchbase Autonomous Operator (Beta) ^| Docker

| Automate your Couchbase deployment with native Kubernetes and OpenShift integration.
| Run Couchbase Server using a traditional Docker deployment.

| xref:operator::overview.adoc[About the Couchbase Autonomous Operator for Kubernetes]
=======
.Container Deployment Methods
|===
| Couchbase Autonomous Operator (Kubernetes) ^| Docker

| With the Couchbase Autonomous Operator, you can easily automate the deployment of Couchbase Server on container orchestration platforms like open source Kubernetes and Red Hat OpenShift.
| Run Couchbase Server using a traditional Docker deployment.

| xref:operator::overview.adoc[About the Couchbase Autonomous Operator]
>>>>>>> 410e17157f915875034f4610572bd61e46bf52c6
a|
* xref:getting-started-docker.adoc[Running Couchbase Server Using Docker]
|===
