= Deploying Couchbase Server in Containers

[abstract]
Couchbase Server is designed to run in the most popular container environments.
Use this topic to explore different ways to deploy Couchbase in containers.

With the xref:operator::overview.adoc[Couchbase Autonomous Operator], you can easily automate the deployment of Couchbase Server on container orchestration platforms like Kubernetes and Red Hat OpenShift.

If you want to do a more traditional container deployment in a data center, or simply want to install Couchbase in a container on your laptop, you can download and install the official images from Docker Hub.

.Container Deployment Methods
|===
^| Couchbase Autonomous Operator (Kubernetes) ^| Docker

| Automate your Couchbase deployment with native Kubernetes and OpenShift integration.

xref:operator::overview.adoc[About the Couchbase Autonomous Operator for Kubernetes]
| Run Couchbase Server using a traditional Docker deployment.

xref:getting-started-docker.adoc[Running Couchbase Server Using Docker]
|===
