[#topic_gmm_mz5_c5]
= Upgrading Services from Version 4.0 to the Latest

[abstract]
You can upgrade services (data, index, and query) in any order.
During the upgrade, your cluster can have a mix of the new and current versions of the query, index, or data services.

== Data Service

You can upgrade the Data service from version 4.0 directly to the latest version 4.1 using any supported upgrade strategy

== Index Service

The Index service with global secondary indexes (GSI) does not provide built-in replicas.
Administrators need to create identical indexes on the separate index service nodes to gain high availability.

The Index service also comes with no rebalancing support.
When a node is removed, GSI on that node are also removed and not moved to another node.
The index traffic is automatically moved to another node that contains an identical index so that the application does not experience downtime.
However, when the upgraded Index service node is brought back into the cluster, administrators have to rebuild the indexes on this node again.

When upgrading the Index service, make sure to fulfill these requirements:

* Before you upgrade an index service node, ensure there are identical indexes on other index service nodes for each index on the node being upgraded.
* Upgrade the node with the Index service and add it back to the cluster using one of the recommended techniques (swap rebalance, offline upgrade, and so on).
* Recreate all indexes on the upgraded node.

== Query Service

The Query service can be upgraded to a new version by taking the node offline.
However, there are few things to keep in mind:

* Make sure there are no running or executing queries since those will be killed when the node is taken offline.
* To avoid downtime for your application, add a new query service node with the new version and swap the older node out.
