[#topic_axp_glg_xs]
= Sizing guidelines

[abstract]
Evaluate the overall performance and capacity requirements and determine the hardware and other resources.

When you plan to deploy a Couchbase Server cluster, perhaps the most common (and important) question that comes up is: how many nodes do I need and what size do they need to be? To learn more, contact Couchbase Support for sizing help.
You can also read about sizing in http://blog.couchbase.com/how-many-nodes-part-1-introduction-sizing-couchbase-server-20-cluster[How many nodes].

With the introduction of xref:architecture:services-archi-multi-dimensional-scaling.adoc#concept_v4w_zmj_vs[Multi-Dimensional Scalability (MDS)], sizing is becoming more challenging, and this guideline aims to help users better size their clusters.

== General considerations

The sizing of your Couchbase Server cluster is critical to its overall stability and performance.
While there are obviously many variables that go into this, the idea is to evaluate the overall performance and capacity requirements for your workload and dataset.
Then divide that into the hardware and resources you have available.
Your application wants the majority of reads coming out of the cache, and the I/O capacity to handle its writes.
There needs to be enough capacity in all areas to support everything the system is doing while maintaining the required level of performance.

This guideline will refer to five determining factors one should be aware of when sizing a Couchbase Server cluster: RAM, Disk (I/O and space), CPU and network bandwidth.

RAM::
Frequently one of the most crucial areas to size correctly.
Cached documents allow the reads to be served at very low latency and consistently high throughput.

Disk:: The requirements of your disk subsystem are broken down into two components: size and I/O.
Disk size refers to the amount disk storage space that needed to hold your entire data set.
Disk I/O is a combination of your sustained read/write rate, the need for compacting the database files and anything else that requires disk access.

CPU:: CPU refers to the number of cores required to run your workload.

Network::
Enough network bandwidth is vital to the performance of Couchbase Server.
A reliable high-speed network for intra-cluster and inter-cluster communications has a huge effect on overall performance and scalability of Couchbase Server.
Most people can do this with a 1GB interface, some need 10GB.
