= Index Service Nodes

[abstract]
A node running the Index Service must be sized properly to create and maintain secondary indexes and to perform index scan for N1QL queries.

Similarly to the nodes running the data service, there is a set of questions you need to answer to take care of your application needs:

. What is the length of the document key?
. Which fields need to be indexed?
. Will you be using simple or compound indexes?
. What is the minimum, maximum, or average value size of the index field?
. How many indexes do you need?
. How many documents need to be indexed?
. How often do you want compaction to run?

Answers to the above questions can help you better understand the capacity requirement of your cluster and provide a better estimation for sizing.
At Couchbase, we looked at performance data and customer use cases to provide sizing calculations for each of the areas: CPU, Memory, Disk and Disk I/O.

Here is a disk size example:

.Disk Sizes
|===
| Input variable | Value

| docID
| 20 bytes

| Number of index fields
| 1

| Secondary index
| 24 bytes

| Number of documents to be indexed
| 20M
|===

When we calculate disk usage for the above test cases, there are a few factors we need to keep in mind:

. Compaction is disabled.
This case illustrates the worst-case scenario for disk usage.
. Couchbase Server uses an append-only storage format.
Therefore, actual disk usage will be larger than data size.
. Fragmentation will affect the disk usage.
The larger the fragmentation, the more disk you will need.

Based on our experiment, we noticed that the above index consumes 6GB of disk space.
