= Verifying the Couchbase Server Installation
:page-topic-type: concept

[abstract]
Testing the connection to Couchbase Server can be performed in a number of different ways.

== Basic Verification

Connecting to the Couchbase Server Web Console with a Web browser provides basic confirmation that a node is available.

On all platforms, you can access the Web Console by connecting to the embedded Web server on port 8091.
For example, if your server can be identified on your network as `serverA`, you can access the Web Console by going to `+http://serverA:8091/+` or `+http://<serverA's-IP-address>:8091/+`.
(If you set up Couchbase Server on a port other than `8091`, go to that specified port.) You should clear your browser's cache before attempting to access to the Web Console.

If you are logged into the node itself, you can go to `+http://localhost:8091+`.
You can also use the `couchbase-cli` command to query node to confirm that it is available.

NOTE: The Web Console uses the same port as smart clients when communicating with Couchbase Server.
If you can connect to the Web Console from a particular machine, then administration and database clients on the same machine can also connect to the core cluster port and perform operations.
The Web Console will provide a warning if the Web browser loses connectivity to the node.

== Detailed Verification

To verify that clients can connect to the node, you can use either <<testing-with-cbworkloadgen,cbworkloadgen>> or <<testing-with-telnet,telnet>>.

The [.cmd]`cbworkloadgen` command is a python program that performs basic operations (reads and writes) against the Couchbase Server cluster.

Using [.cmd]`telnet` only checks the memcached compatibility ports and the memcached text-only protocol.

[[testing-with-cbworkloadgen]]Testing With cbworkloadgen::
The command [.cmd]`cbworkloadgen` generates random data, then performs reads and writes of this data in Couchbase Server.
It is not intended to be a performance benchmarking tool.
+
To test a Couchbase Server installation using [.cmd]`cbworkloadgen`, execute the following command, supplying the IP address of the running node:
+
----
> cbworkloadgen -n [host]:8091
        Thread 0 - average set time : 0.0257480939229 seconds , min : 0.00325512886047 seconds , max : 0.0705931186676 seconds , operation timeouts 0
----
+
The progress and activity of the tool can also be monitored within the Web Console.
+
Further details about `cbworkloadgen` can be found on xref:cli:cbworkloadgen-tool.adoc[its CLI reference page].
