= Install Couchbase Server on Ubuntu and Debian
:description: Couchbase Server can be installed on Ubuntu Linux and Debian Linux for production and development use-cases. \
Root and non-root installations are supported.
:tabs:

[abstract]
{description}

Use the instructions on this page to install Couchbase Server on Ubuntu and Debian platforms using Couchbase-provided _deb_ packages.
The instructions support both Enterprise and Community https://www.couchbase.com/products/editions[editions^].

If you're upgrading an existing installation of Couchbase Server, refer to xref:upgrade.adoc[Upgrading Couchbase Server].

== Before You Install

Couchbase Server works out-of-the-box with most OS configurations.
However, the procedures on this page assume the following:

* Your system meets the xref:pre-install.adoc[minimum requirements] and that your operating system version is xref:install-platforms.adoc[supported].
* You're working from a clean system and that you've xref:install-uninstalling.adoc[uninstalled] any previous versions of Couchbase Server.
+
If you're upgrading an existing installation of Couchbase Server, refer to xref:upgrade.adoc[Upgrading Couchbase Server].

For production deployments, make sure to follow the xref:install-production-deployment.adoc[deployment guidelines] so that your systems and environment are properly sized and configured before installation.

== Basic Installation

You must be logged in as root (superuser) or use `sudo` to run the installation commands.

=== Install Using Apt

The Advanced Package Tool (`apt`) provides the simplest and most comprehensive way to install Couchbase Server on Ubuntu and Debian platforms.
This method involves downloading and installing a small meta package from Couchbase, which `apt` can then use to automatically download and install Couchbase Server and all of its dependencies.

. Download the meta package.
+
[source,console]
----
curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-amd64.deb
----

. Install the meta package.
+
[source,console]
----
sudo apt-get install -y ./couchbase-release-1.0-amd64.deb
----
+
The meta package installs the necessary information for `apt` to be able to retrieve all of the necessary Couchbase Server installation packages and dependencies.

. Reload the local package database.
+
[source,console]
----
sudo apt-get update
----

. Install Couchbase Server.
+
[{tabs}]
====
Enterprise::
+
--
.To install the latest release
[source,console]
----
sudo apt-get install couchbase-server
----
.To install a specific release
. List the available releases.
+
[source,console]
----
apt list -a couchbase-server
----
+
Available releases are listed with their full `version-build` number:
+
[subs=+quotes]
----
couchbase-server/xenial *7.0.3-223-1* amd64
----
+
. Specify a release to install it.
+
[source,console,subs=+quotes]
----
sudo apt-get install couchbase-server=[.var]_version-string_
----
+
Using the example listing from the previous step, the resulting installation command would be:
+
[subs=+quotes]
----
sudo apt-get install couchbase-server=*7.0.3-223-1*
----
--

Community::
+
--
.To install the latest release
[source,console]
----
sudo apt-get install couchbase-server-community
----
.To install a specific release
. List the available releases.
+
[source,console]
----
apt list -a couchbase-server-community
----
+
Available releases are listed with their full `version-build` number:
+
[subs=+quotes]
----
couchbase-server-community/xenial *7.0.3-223-1* amd64
----
+
. Specify a release to install it.
+
[source,console,subs=+quotes]
----
sudo apt-get install couchbase-server-community=[.var]_version-string_
----
+
Using the example listing from the previous step, the resulting installation command would be:
+
[subs=+quotes]
----
sudo apt-get install couchbase-server-community=*7.0.3-223-1*
----
--
====
+
The `apt-get` command automatically downloads and installs the latest version of Couchbase Server, along with all of its dependencies.
+
Once installation is complete, Couchbase Server will start automatically (and will continue to start automatically at run levels 2, 3, 4, and 5, and explicitly shut down at run levels 0, 1, and 6).
You can use the `systemctl` command (`service` on older operating systems) to start and stop the Couchbase Server service, as well as check the current status.
Refer to xref:startup-shutdown.adoc[Couchbase Server Startup and Shutdown] for more information.

. Open a web browser and access the Couchbase Web Console to xref:testing.adoc[verify] that the installation was successful and that the node is available.

=== Install Using Deb Package

Install Couchbase Server on Ubuntu and Debian using a full _deb_ package provided by Couchbase.

. Download the appropriate package from the Couchbase https://www.couchbase.com/downloads[downloads page^].

. Reload the local package database.
+
[source,console]
----
sudo apt-get update
----

. Install Couchbase Server.
+
[source,console,subs=+quotes]
----
sudo apt-get install -y ./[.var]_package-name_.deb
----
+
Once installation is complete, Couchbase Server will start automatically (and will continue to start automatically at run levels 2, 3, 4, and 5, and explicitly shut down at run levels 0, 1, and 6).
You can use the `systemctl` command (`service` on older operating systems) to start and stop the Couchbase Server service, as well as check the current status.
Refer to xref:startup-shutdown.adoc[Couchbase Server Startup and Shutdown] for more information.

. Open a web browser and access the Couchbase Web Console to xref:testing.adoc[verify] that the installation was successful and that the node is available.

[#deb-nonroot-nonsudo]
== Installing as Non-Root

Non-root installation is performed identically for all supported Linux distributions, including Ubuntu and Debian.
For instructions, see xref:install:non-root.adoc[Non-Root Install and Upgrade].

== Next Steps

Following installation and start-up of Couchbase Server, a node must be _initialized_ and _provisioned_.

* If it is the first node in a deployment, initialization and provisioning happens all at once when you create a _cluster of one_.
+
Refer to xref:manage:manage-nodes/create-cluster.adoc[Create a Cluster]

* If you already have an existing cluster, the node is initialized and provisioned when you add it to the cluster.
+
Refer to xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a Node and Rebalance]
+
* Optionally, initialization can be performed explicitly and independently of provisioning, as a prior process, in order to establish certain configurations, such as custom disk-paths.
+
Refer to xref:manage:manage-nodes/initialize-node.adoc[Initialize a Node]
