= Installing Couchbase Server on Ubuntu and Debian
:tabs:

[abstract]
Install Couchbase Server on Ubuntu and Debian Linux.
Root and non-root installations are supported.

Use the instructions on this page to install Couchbase Server on Ubuntu and Debian platforms using the officially-supported `.deb` packages provided by Couchbase.
The instructions support both Enterprise and Community editions.

[IMPORTANT]
====
The installation procedures assume that you're working from a clean system and that you've xref:install-uninstalling.adoc[uninstalled] any previous installations of Couchbase Server.

If you're upgrading an existing installation of Couchbase Server, refer to xref:upgrade.adoc[Upgrading Couchbase Server].
====

== Before You Install

Couchbase Server works out-of-the-box on most Ubuntu and Debian configurations.
However, you should review the following material before installing, especially if you're deploying Couchbase into production:

* Ensure that you've met the xref:plan-for-production.adoc[minimum system requirements] and that your operating system version is xref:install-platforms.adoc[supported].
* Follow the xref:install-production-deployment.adoc[deployment guidelines] to ensure that your systems and environment are properly sized and configured.

== Basic Installation

You must be logged in as root (superuser) or use `sudo` to run the installation commands.

=== Install Using `apt`

The Advanced Package Tool (`apt`) provides the simplest and most comprehensive way to install Couchbase on Ubuntu and Debian platforms.
This method involves downloading and installing a small meta package from Couchbase, which `apt` can then use to automatically download and install Couchbase Server and all of its dependencies.

. Download and install the `.deb` meta package.
+
[source,console]
----
curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-6-amd64.deb
----
+
[source,console]
----
sudo dpkg -i ./couchbase-release-1.0-6-amd64.deb
----
+
The meta package installs the necessary information for `apt` to retrieve all of the necessary packages, and also imports the necessary Couchbase public signing keys.

. Reload the local package database.
+
[source,console]
----
sudo apt-get update
----

. Install Couchbase Server.
+
[{tabs}] 
==== 
Enterprise:: 
+ 
--
Install the latest release of Couchbase Server Enterprise::
+
[source,console]
----
sudo apt-get install couchbase-server
----
Install a specific release of Couchbase Server Enterprise::
+
. List the available releases.
+
[source,console]
----
apt list -a couchbase-server
----
+
An example listing might be: `couchbase-server/xenial *6.0.0-1693-1* amd64`.
+
. Specify a release to install it.
+
[source,console]
----
sudo apt-get install couchbase-server-<version>
----
+
...where `<version>` is the full version string of the release.
+
Using the example listing from the previous step, the version string would be `*6.0.0-1693-1*`, and thus the installation command would be: `sudo apt-get install couchbase-server-6.0.0-1693-1`
--

Community::
+
-- 
Install the latest release of Couchbase Server Community::
+
[source,console]
----
sudo apt-get install couchbase-server-community
----
Install a specific release of Couchbase Server Community::
+
. List the available releases.
+
[source,console]
----
apt list -a couchbase-server-community
----
+
An example listing might be: `couchbase-server-community/xenial *6.0.0-1693-1* amd64`.
+
. Specify a release to install it.
+
[source,console]
----
sudo apt-get install couchbase-server-community-<version>
----
+
...where `<version>` is the full version string of the release.
+
Using the example listing from the previous step, the version string would be `*6.0.0-1693-1*`, and thus the installation command would be: `sudo apt-get install couchbase-server-community-6.0.0-1693-1`
--
====
+
The `apt-get` command automatically downloads and installs the latest version of Couchbase Server, along with all of its dependencies.
+
Once installation is complete, Couchbase Server will start automatically (and will continue to start automatically at run levels 2, 3, 4, and 5, and explicitly shut down at run levels 0, 1, and 6).
You can use the `systemctl` command (`service` on older operating systems) to start and stop the Couchbase Server service, as well as check the current status.
Refer to xref:startup-shutdown.adoc[Couchbase Server Startup and Shutdown] for more information.
+
[NOTE]
====
Microsoft Azure Ubuntu 14.04 images from Canonical may throw the following warning messages during installation:

[source,console]
----
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
----

The installation completes without a problem and it is safe to ignore these messages.
====

. Open a web browser and access the Couchbase Server Web Console to xref:testing.adoc[verify] that the installation was successful and the node is available.

=== Install using `dpkg`

Install Couchbase Server on Ubuntu and Debian using the `dpkg` command-line tool with the `.deb` package that you downloaded from Couchbase.

. Download the appropriate package for your operating system from the Couchbase https://www.couchbase.com/downloads[downloads page^].

. Install Couchbase Server.
+
[source,console]
----
sudo dpkg -i ./couchbase-server-*.deb
----
+
...where `*` is the edition and version of the downloaded package.
+
Once installation is complete, Couchbase Server will start automatically (and will continue to start automatically at run levels 2, 3, 4, and 5, and explicitly shut down at run levels 0, 1, and 6).
You can use the `systemctl` command (`service` on older operating systems) to start and stop the Couchbase Server service, as well as check the current status.
Refer to xref:startup-shutdown.adoc[Couchbase Server Startup and Shutdown] for more information.
+
[NOTE]
====
Microsoft Azure Ubuntu 14.04 images from Canonical may throw the following warning messages during installation:

[source,console]
----
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
----

The installation completes without a problem and it is safe to ignore these messages.
====

. Open a web browser and access the Couchbase Server Web Console to xref:testing.adoc[verify] that the installation was successful and the node is available.


[#deb-nonroot-nonsudo]
== Installing as non-root, non-sudo

// Removing the note as this has been verified by QE to be production ready
// <p>Installation on Ubuntu as non-root, non-sudo user is used only for development purposes.</p>
// <note type="important">This installation method is intended only for development purposes and is
// not supported in production.</note>
// <p>Only 64 bit systems are supported.</p>

A non-root, non-sudo installation will run Couchbase Server and all Couchbase Server command-line tools.

NOTE: Only 64 bit systems are supported.

. After downloading the Couchbase Server DEB package, go to the directory where it is located and extract it:
+
[source,bash]
----
dpkg-deb -x couchbase-server-version.deb $HOME
----
+
In the directory where you extracted the files, you will see [.path]_/opt_ and [.path]_/etc_ subdirectories.

. After you extract the Couchbase Server installation files, go to the subdirectory:
+
[source,bash]
----
cd opt/couchbase
----

. Run the following script to relocate the Couchbase Server installation to the present working directory (PWD):
+
[source,bash]
----
./bin/install/reloc.sh `pwd`
----
+
This allows you to continue the installation as a non-root, non-sudo user.

. To run the server use
+
[source,bash]
----
./bin/couchbase-server -- -noinput -detached
----

. To stop the server use
+
[source,bash]
----
./bin/couchbase-server -k
----
