= Installing as non-root, non-sudo

[abstract]
Installation on Ubuntu as non-root, non-sudo user is used is used only for development purposes.

IMPORTANT: This installation method is intended only for development purposes and is not supported in production.

Only 64 bit systems are supported.

A non-root, non-sudo installation will run Couchbase Server and all Couchbase Server command-line tools.

. After downloading the Couchbase Server DEB package, go to the directory where it is located and extract it:
+
----
dpkg-deb -x couchbase-server-version.deb $HOME
----
+
In the directory where you extracted the files, you will see [.path]_/opt_ and [.path]_/etc_ subdirectories.

. After you extract the Couchbase Server installation files, go to the subdirectory:
+
----
 cd opt/couchbase
----

. Run the following script to relocate the Couchbase Server installation to the present working directory (PWD):
+
----
./bin/install/reloc.sh `pwd`
----
+
This allows you to continue the installation as a non-root, non-sudo user.

. To run the server use
+
----
./bin/couchbase-server -- -noinput -detached
----

. To stop the server use
+
----
./bin/couchbase-server -k
----
