= Upgrade an Offline, Single-Node Cluster

:description: An earlier version of Couchbase Server, running on a single-node cluster, can be upgraded to a later version.
:tabs:

[abstract]
{description}

== Understanding Single-Node Cluster-Upgrade

Single-node clusters are _unsupported_, but are frequently used in development.
This page provides instructions for the upgrade of a single-node cluster.
Note that these instructions do _not_ apply to MacOS.

== Perform Single-Node Cluster-Upgrade

Proceed as follows:

=== Stage One: Prepare the Node

. Stop all applications on the node.
Monitor the _disk-write queue_, to ensure that all data has been persisted to disk.
A command of the following form can be used.
+
----
curl -s -u '${USERNAME}:${PASSWORD}' ${NODE_HOSTNAME}:${NODE_MANGEMENT_PORT}/pools/default/buckets/${BUCKET}/stats | jq ".op.samples.disk_write_queue[-1]"
----
+
When this command returns `0`, all data has been persisted to disk.

. Back up the node's user-data.
+
Backup can be performed either with xref:backup-restore:enterprise-backup-restore.adoc[cbbackupmgr] or with the xref:learn:services-and-indexes/services/backup-service.adoc[Backup Service]; and should be a _full_ (rather than an incremental) backup.
+
For example, to use `cbbackupmgr` to configure an archive and repository for the backup, a command of the following form should be entered:
+
[source,bash]
----
cbbackupmgr config --archive ${ABS_PATH_TO_ARCHIVE} --repo ${REPO_NAME}
----
+
Here, `ABS_PATH_TO_ARCHIVE` is an absolute path to a filesystem location that will serve as the archive within which the backed up data will reside.
The `REPO_NAME` is the name of the repository that will be associated with the location.
+
Once the archive and repository have been created, a command such as the following performs a full backup:
+
[source,bash]
----
cbbackupmgr backup --archive ${ABS_PATH_TO_ARCHIVE} --repo ${REPO_NAME} --cluster ${CLUSTER_ADDRESS} --username ${USERNAME} --password ${PASSWORD} --full-backup
----
+
Here, the `CLUSTER_ADDRESS` is the IP address or domain name of the node.
The `full-backup` flag ensures that the backup is indeed a _full_ backup.
+
For the equivalent procedure as performed by the Backup Service, see xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc#run-an-immediate-backup[Run an Immediate Backup].
+
In the event of node-upgrade failing, the backed-up data can be restored by means of xref:backup-restore:cbbackupmgr-restore.adoc[cbbackupmgr restore] or xref:cli:cbtools/cbrecovery.adoc[cbrecovery]; or by means of the Backup Service (see xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc#restore-backups[Restore Backups]).

. Manually back up the node's configuration files.
These files reside in `/opt/couchbase/var/lib/couchbase/config`.
It is recommended that the path to the backup-location for these files contain the node's domain name or IP address, to ensure accurate recovery.
It is also recommended that the backup-location be on a separate machine.
+
Enter a command such as the following;
+
----
cp -r /opt/couchbase/var/lib/couchbase/config ${PATH_TO_A_SAFE_LOCATION}/${NODE_IP}_config_files
----

[#stage-two-upgrade-the-node]
=== Stage Two: Upgrade the Node

. Stop the `couchbase-server.service` service.
Enter the following command:
+
----
systemctl stop couchbase-server.service
----
+
This _stops_ the service; and so allows it to be restarted after reboot.
Note that, optionally, at this point, the service can also be _disabled_; which prevents it from restarting after reboot.
This may be useful if additional tasks, such as OS upgrade, need to be performed.
If such disabling _is_ appropriate, enter the following.
(Note that this command disables Couchbase Server _Enterprise_ Edition: to disable _Community_ Edition instead, substitute `couchbase-server-community.service` for `couchbase-server.service`.)
+
----
systemctl disable --now couchbase-server.service
----

. If using Couchbase-provided repositories/PPAs, _unpin_ (or _unhold_) the Couchbase-Server version, to allow it to be upgraded.
Proceed as follows, for the appropriate platform:
+
[{tabs}]
====
RedHat & Centos::
+
--

Open the file `/etc/yum/yum.conf`, and remove the reference to the `couchbase-server` package (or, if using Community Edition, the `couchbase-server-community` package) from the `exclude` section.
The line appears as follows:

----
exclude=couchbase-server
----

--

Ubuntu & Debian::
+
--

Run the following command (specifying, if using Community Edition, `couchbase-server-community`, rather than `couchbase-server`):

----
apt-mark unhold couchbase-server
----

--
====

. Upgrade the Couchbase Server package.
The following examples use `couchbase-server`, to specify Enterprise Edition.
To specify Community Edition, use `couchbase-server-community`.
+
If using a Couchbase-provided `yum` repository, enter the following:
+
----
yum update couchbase-server
----
+
If using a Couchbase-provided PPA, enter the following:
+
----
apt --only-upgrade install couchbase-server
----
+
If using a downloaded package-archive, enter the command appropriate for the platform, as follows:
+
[{tabs}]
====
RedHat & Centos::
+
--
----
yum install ${PATH_TO_RPM_PACKAGE}
----
--

Ubuntu & Debian::
+
--
----
dpkg -i ${PATH_TO_DEB_PACKAGE}
----
--
====

. If using Couchbase-provided repositories/PPAs, _repin_ (or _hold_) future package-upgrades for Couchbase Server, so that none occurs before the administrator's next manually driven upgrade.
Proceed as follows for the appropriate platform:
+
[{tabs}]
====
RedHat & Centos::
+
--
Add the `couchbase-server` (or `couchbase-server-community`) package
to the `exclude` section of the `yum.conf` file, which is located at `/etc/yum/yum.conf`.
The line should appear as follows:

----
exclude=couchbase-server
----
--

Ubuntu & Debian::
+
--
Run the following command (substituting, if running Community Edition, `couchbase-server-community` for `couchbase-server`):

----
apt-mark hold couchbase-server
----

--
====

. Enable and start the `couchbase-server` (or `couchbase-server-community`) service.
+
(Note that the package-manager may already have performed enablement: however, explicit enablement is nevertheless recommended.)
+
Enter the following commands (substituting, if using Community Edition, `couchbase-server-community.service` for `couchbase-server.service`).
+
----
systemctl enable couchbase-server.service

systemctl is-active --quiet couchbase-server.service || systemctl start couchbase-server.service
----

. Wait for the completion of _warmup_, for all _Couchbase_ buckets.
Note that this may take some time, if the buckets contain large amounts of data.
+
The status of warmup can be checked as follows:
+
----
cbstats ${NODE_ADDRESS}:${NODE_KV_PORT} -u ${USERNAME} -p ${PASSWORD} -b ${BUCKET} warmup | grep state
----
+
For example:
+
----
/opt/couchbase/bin/cbstats localhost:11210 -u Administrator -p password -b travel-sample warmup | grep state
----
+
When warmup is complete, the command returns the following:
+
----
ep_warmup_state:                 done
----
+
Note that _Ephemeral_ buckets do not require warmup.
If an Ephemeral bucket is specified in this command, an error is returned.

. Following warmup, restart applications.

This concludes the upgrade process for the single-node cluster.
