= Upgrade Matrix

[abstract]
Couchbase Server supports upgrade paths from one major version to another.

Be aware of the currently supported versions and versions at or near their end of life.
The support information is available in the http://www.couchbase.com/support-policy[Couchbase Support Policy^].

WARNING: Use the same Couchbase Server version number when upgrading from the Community Edition to the Enterprise Edition.
Version differences can result in a failed upgrade.

The following table shows the supported upgrade paths to version 5.0:

|===
| Current Version | Edition | Upgrade Option | Support

| 4.0.0
| Enterprise Edition
| Offline or Online
| Direct upgrade to 5.0

| 4.1.x
| Enterprise Edition
| Offline or Online
| Direct upgrade to 5.0

| 4.5.x
| Enterprise Edition
| Offline or Online
| Direct upgrade to 5.0

| 4.6.x
| Enterprise Edition
| Offline or Online
| Direct upgrade to 5.0
|===

[IMPORTANT]
====
For Windows, `.exe` installers were removed in version 5.0 and replaced with industry-standard MSI installer files.
Consequently, any upgrade on Windows from a pre-5.0 version of Couchbase will need to be done via a xref:upgrade-online.adoc[rolling upgrade].

When upgrading Couchbase on a Windows node during a rolling upgrade, you must uninstall any version of Couchbase that is older than 5.0, and then do a fresh installation of 5.x.x before adding the node back into the cluster. This is because the new MSI installer is not compatible with pre-existing installations that are older than 5.0.
====

The following table shows some commonly supported upgrade paths:

.Couchbase Server upgrade matrix
[cols="1,1,3"]
|===
| Current version | Target version | Process

| 2.5.x
| 3.x
| Upgrade from version 2.5.x directly to the latest version 3.x using any supported upgrade strategy.

| 3.x
| 4.x
| Upgrade from the latest version 3.x directly to version 4.x using any supported upgrade strategy.

| 2.5.x
| 4.x
| Upgrade from the latest version 2.5.x directly to version 4.x using any supported upgrade strategy.

| 4.0
| 4.x (> 4.0)
| Services require more planning during an upgrade.

| 4.x
| 5.x
| Services require more planning during an upgrade.
|===
