= Upgrade matrix

[abstract]
Couchbase Server supports upgrade paths from one major version to another.

Be aware of the currently supported versions and versions at or near their end of life.
This information is available in the http://www.couchbase.com/support-policy[Couchbase Support Policy^].

NOTE: Use the same Couchbase Server version number when upgrading from the Community Edition to the Enterprise Edition.
Version differences can result in a failed upgrade.

The following table shows some commonly supported upgrade paths:

.Couchbase Server upgrade matrix
[cols="1,1,3"]
|===
| Current version | Target version | Process

| 2.5.x
| 3.x
| Upgrade from version 2.5.x directly to the latest version 3.x using any supported upgrade strategy.

| 3.x
| 4.x
| Upgrade from the latest version 3.x directly to version 4.0 using any supported upgrade strategy.

| 2.5.x
| 4.x
| Upgrade from the latest version 2.5.x directly to version 4.0 using any supported upgrade strategy.

| 4.0
| 4.x
| Services require more planning during an upgrade.
Read the explanation provided in xref:services-upgrade.adoc[Upgrading services].
|===
