= Upgrade Procedures

:description: Multiple procedures are provided for the upgrade of a Couchbase-Server cluster.
//:page-aliases: install:upgrade-strategy-for-features

[abstract]
{description}

The pages in this section each provide step-by-step instructions for the upgrade of a Couchbase-Server cluster.
Each procedure addresses a specific context and its associated dependencies: for information on how to select the appropriate procedure, see the information provided in xref:install:upgrade-strategies.adoc[Upgrade Procedure-Selection].

To perform any of these procedures, the administrator must have the *Full Admin* or the *Cluster Admin* role.
For information, see xref:learn:security/roles.adoc[Roles].

Note that information specific to the upgrade of IPv6 clusters is provided in xref:install:upgrade-to-ipv6.adoc[Upgrade IPv6 Clusters].

The procedures are presented as follows:

* xref:install:upgrade-a-single-node-cluster.adoc[Upgrade a Single-Node Cluster].
_Single-node_ clusters are unsupported, but are frequently used for development.
An upgrade-procedure is therefore provided. 

* xref:install:upgrade-cluster-offline.adoc[Upgrade an Offline Cluster].
This is the simplest procedure for cluster-upgrade.
Note, however, that it requires cluster-downtime.

* xref:install:upgrade-cluster-online-reduced-capacity.adoc[Upgrade a Reduced-Capacity, Online Cluster].
If no additional nodes are available to facilitate the upgrade-procedure, the procedure can be completed with the existing cluster-nodes, provided that it is acceptable for the cluster to serve data, during the upgrade, at reduced capacity.

* xref:install:upgrade-cluster-online-full-capacity.adoc[Upgrade a Full-Capacity, Online Cluster].
If additional nodes are available to facilitate the upgrade-procedure, the procedure can be completed with the cluster continuing to serve data at full capacity.
