= Upgrade
:description: Periodically upgrading Couchbase Server helps maintain a properly functioning cluster and offers new features.

[abstract]
{description}
Upgrading Couchbase Server means revising its _version_ of the server upwards.

[#understanding-upgrade]
== Understanding Upgrade

To _upgrade_ a Couchbase-Server cluster means to revise its _version_ of the server upwards.
For example, a cluster each of whose nodes has been running Couchbase Server Enterprise Edition Version 6.6 is modified; such that each of its nodes subsequently runs Couchbase Server Enterprise Edition Version 7.0.

An _upgrade_ procedure, like an _install_ procedure, must be performed on an individual node.
Therefore, to be upgraded, a cluster must have each of its nodes individually upgraded, in turn.
An explanation of the context whereby an appropriate upgrade-procedure can be selected is provided in xref:install:upgrade-procedure-selection.adoc[Upgrade Procedure-Selection].

[#supported-upgrade-paths]
== Supported Upgrade Paths

An upgrade _path_ declares that upgrade between one version of Couchbase Server and another is _supported_.
In the following table, the sign -> indicates that upgrade of the server-version on the left of the sign to that on the right is supported.
Note that upgrade between non-contiguous version-numbers is frequently _not_ supported: for example, to upgrade from 5.5.0+ to 7.0, upgrade must be performed _twice_; first from 5.5.0+ to 6.6, and secondly from 6.6 to 7.0.

.Couchbase Server 7.0 Enterprise Edition Upgrade Paths
[#table-upgrade-enterprise]
|===
| Current Version | Edition | Upgrade Option | Path

| 5.x
| Enterprise Edition
| Offline or Online
| 5.0.x and 5.1.x -> 6.0.4+ -> 6.6 -> 7.0

5.0.x and 5.1.x -> 6.6 -> 7.0

5.5.0+ -> 6.6 -> 7.0

| 6.x
| Enterprise Edition
| Offline or Online
| Direct upgrade to 6.6

6.6 -> 7.0

|===

.Couchbase Server 7.0 Community Edition Upgrade Paths
[#table-upgrade-community]
|===
| Current Version | Edition | Upgrade Option | Path

| 5.x
| Community Edition
| Offline or Online
| 5.x -> 6.0 -> 6.5 -> 6.6

| 6.x
| Community Edition
| Offline or Online
| 6.0 -> 6.5 -> 6.6 -> 7.0

|===

[#upgrade-community-enterprise]
=== Upgrade from Community Edition to Enterprise

To upgrade a cluster running Community Edition to a cluster running Enterprise Edition, the version-number of the Enterprise Edition must be identical to that of the Community Edition.
Therefore, if the target version-number of the Enterprise Edition is higher, the cluster should first be upgraded to the Enterprise version-number that is identical to the Community Edition version-number, then upgraded to the target Enterprise Edition version-number, according to the paths described above, in xref:install:upgrade.adoc#supported-upgrade-paths[Supported Upgrade Paths].

See xref:install:upgrade-procedure-selection.adoc[Upgrade Procedure-Selection], for a list of procedures that can be used.
Note, however, that _Graceful Failover_ for Data Service nodes, with _Delta Recovery_, is _not_ supported: instead, _removal_, _addition_, and _swap rebalance_ should be used; for all nodes.

=== Downgrade

Once an upgrade of a Couchbase-Server cluster has started, _downgrade_ to the earlier version of Couchbase Server can be performed, as long as one node is still running the earlier version.
Once all nodes are running the later version, downgrade cannot be performed: therefore, an entirely new cluster, running the previous version, would need to be created.
