= Upgrade Cluster Online, with Reduced Capacity

:description: A cluster can be upgraded while still online, without additional nodes required.
//:page-aliases: install:upgrade-strategy-for-features

[abstract]
{description}

[#online-upgrade-with-reduced-capacity]
== Understanding Reduced-Capacity Upgrade

The context and overall requirements for upgrading a live cluster without the introduction of one or more additional nodes are described in xref:install:upgrade-strategies.adoc[Upgrade Options]: this fully explains the node-by-node upgrade of the cluster, using _swap rebalance_ to minimize overhead.
It also explains how, if additional nodes are not available, the procedure can be completed with no more than the existing cluster-nodes, provided that the cluster can perform acceptably at reduced capacity, during the upgrade.

The precise steps for this procedure are detailed on this page, below.
A full understanding of xref:install:upgrade-strategies.adoc[Upgrade Options] should be acquired, before proceeding.

[#perform-upgrade-with-reduced-capacity]
== Perform a Reduced-Capacity Upgrade

The following procedure assumes that:

* The cluster to be upgraded must continue to serve data throughout the cluster-upgrade process.

* No additional node is available, to act as a _swap_ node.
Therefore, a swap node must be _created_; by withdrawal of a node from the cluster &#8212; thereby reducing the capacity of the cluster.

* During the cluster-upgrade process, _swap_ nodes and _upgraded_ nodes will be introduced to the cluster by the _node-addition_ procedure; while _failed over swap nodes_ and _nodes to be upgraded_ will be withdrawn from the cluster by means of the _node removal_ and _swap rebalance_ procedures.
+
For information on node-addition, see xref:learn:clusters-and-availability/nodes.adoc#clusters[Clusters].
For information on node-removal, see xref:learn:clusters-and-availability/removal.adoc[Removal].
For information on _swap rebalance_, see xref:install:upgrade-strategies.adoc#swap-rebalance[Swap Rebalance].

* Nodes will be upgraded _one at a time_.

Proceed as follows:

. Back up all cluster-data.
This can be performed either with xref:backup-restore:enterprise-backup-restore.adoc[cbbackupmgr] or with the xref:learn:services-and-indexes/services/backup-service.adoc[Backup Service]; and should be a _full_ (rather than an incremental) backup.
+
For example, to use `cbbackupmgr` to configure an archive and repository for the backup, a command of the following form should be entered:
+
[source,bash]
----
cbbackupmgr config --archive ${ABS_PATH_TO_ARCHIVE} --repo ${REPO_NAME}
----
+
Here, `ABS_PATH_TO_ARCHIVE` is an absolute path to a filesystem location that will serve as the archive within which the backed up data will reside.
The `REPO_NAME` is the name of the repository that will be associated with the location.
+
Once the archive and repository have been created, a command such as the following performs a full backup:
+
[source,bash]
----
cbbackupmgr backup --archive ${ABS_PATH_TO_ARCHIVE} --repo ${REPO_NAME} \
--cluster ${CLUSTER_ADDRESS} --username ${USERNAME} --password ${PASSWORD} \
--full-backup
----
+
Here, the `CLUSTER_ADDRESS` is the IP address or domain name of the cluster that is being backed up.
The `full-backup` flag ensures that the backup is indeed a _full_ backup.
+
For the equivalent procedure as performed by the Backup Service, see xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc#run-an-immediate-backup[Run an Immediate Backup].

. Remove a node from the cluster.
+
This node will not be restored to the cluster until the very end of the upgrade procedure &#8212; the final stage of which will be the upgrade of this node itself.
Until then, this node will function as a _spare_ node; allowing _swap rebalance_ to be performed on each successive node to be upgraded; and in consequence, the cluster will continue to serve data with reduced capacity.
For information, see xref:install:upgrade-strategies.adoc#using-spare-nodes[Using Spare Nodes].
+
To remove a node with the Couchbase CLI, a command such as the following can be used:
+
[source,bash]
----
couchbase-cli rebalance -c ${CLUSTER_NODE_HOSTNAME_OR_IP} \
-u ${USERNAME} -p ${PASSWORD} \
--server-remove ${TARGET_NODE_HOSTNAME_OR_IP}
----
+
Here, the `CLUSTER_NODE_HOSTNAME_OR_IP` is the IP address or domain name of any node in the cluster.
The `NODE_HOSTNAME_OR_IP` is the IP address or domain name of the node that is to be removed from the cluster.
+
For a full description of steps whereby nodes can be removed from the cluster &#8212; using the UI, CLI, and REST API &#8212; see xref:manage:manage-nodes/remove-node-and-rebalance.adoc[Remove a Node and Rebalance].
