= Upgrade an IPv6 Cluster
:description: All pre-7.0 clusters using the IPv6 address family can be upgraded to Couchbase Server Enterprise Edition 7.0: in some cases, additional steps are required in the upgrade-procedure.
:page-aliases: install:upgrade-to-ipv6

[abstract]
{description}

== IPv6 Cluster-Upgrade to 7.0{plus}

A pre-7.0 Couchbase Server-cluster that is currently using the IPv6 address family can be upgraded to run 7.0{plus} _and_ to continue using IPv6:

* _All_ IPv6 clusters running a pre-7.0 version of Couchbase Server Enterprise Edition can perform _online_ upgrade as explained in xref:upgrade-cluster-online.adoc[Performing the Rolling Online Upgrade].

* IPv6 clusters currently running Couchbase Server Enterprise Edition Version 6.0.1 or higher can perform _offline_ upgrade as explained in xref:install:upgrade-cluster-offline.adoc[Upgrade an Offline Cluster].

* IPv6 clusters currently running Couchbase Server Enterprise Edition Version 6.0.0 can perform _offline_ upgrade as explained in xref:install:upgrade-cluster-offline.adoc[Upgrade and Offline Cluster], but must then perform the additional steps described below.

Note that pre-7.0 clusters that are to be upgraded to 7.0{plus}, and whose address family is to be changed, should _first_ be upgraded to 7.0{plus}, and _subsequently_ be assigned the new address family (since upgrade and address-family change _cannot_ be performed simultaneously).
Note also that if a pre-7.0 cluster is not using IPv6 and no address-family change is required, the cluster can be upgraded to 7.0{plus} by either an _offline_ or an _online_ procedure, with its address-family setting remaining unchanged.

=== Additional Upgrade Steps for Some Clusters

To complete _offline_ upgrade to 7.0{plus} for a 6.0.0 cluster that has already been running IPv6 and is intended to continue doing so, after completion of the instructions in xref:install:upgrade-offline.adoc[Performing the Offline Upgrade], proceed as follows:

. Stop Couchbase Server.
For instructions on stopping a server installed by the standard, _package-based_ procedure, see xref:install:startup-shutdown.adoc[Start and Stop Couchbase Server].
For instructions on stopping a server installed by the _non-root_ procedure, see xref:install:non-root.adoc[Non-Root Install and Upgrade], in the section xref:install:non-root.adoc#start-stop-and-get-status[Stop, Start, and Get Status].

. As either _root_ or _couchbase user_, enter the following command:
+
----
if [ -e /opt/couchbase/var/lib/couchbase/config/dist_cfg ] && [ ! -s /opt/couchbase/var/lib/couchbase/config/dist_cfg ]; then
  echo "[{preferred_external_proto,inet6_tcp_dist}, {preferred_local_proto, inet6_tcp_dist}]." > /opt/couchbase/var/lib/couchbase/config/dist_cfg;
fi
----

. Start Couchbase Server.

This concludes the upgrade-process.
