= Upgrade a Full-Capacity, Online Cluster

:description: A cluster can be upgraded while still online, and maintained at full capacity.
:tabs:

[abstract]
{description}

[#online-upgrade-with-full-capacity]
== Understanding Full-Capacity Upgrade

The context and overall requirements for upgrading a live cluster by means of the introduction of one or more additional nodes are described in xref:install:upgrade-procedure-selection.adoc[Upgrade-Procedure Selection]: this fully explains the node-by-node upgrade of the cluster, using _swap rebalance_ to minimize overhead.
It also explains how, if additional nodes are available, the cluster can be maintained at full capacity during the upgrade.

The precise steps for this procedure are detailed on this page, below.
A full understanding of the information in xref:install:upgrade-procedure-selection.adoc[Upgrade-Procedure Selection] should be acquired, before proceeding.
The procedure assumes that:

* The cluster to be upgraded must continue to serve data throughout the cluster-upgrade process.

* A single, additional node is available; to act as a _swap_ node.
The node _either_ has not previously run Couchbase Server, _or_ has run a version that can, with all its configuration files and other data, be overwritten: therefore, the latest version of Couchbase Server will be installed on the node.
(Prior to installation, if necessary, remove any old configuration files from `/opt/couchbase`, using the command `rm -r /opt/couchbase`.)

* During the cluster-upgrade process, _swap_ nodes and _upgraded_ nodes will be introduced to the cluster by the _node-addition_ procedure; while _failed over spare nodes_ and _nodes to be upgraded_ will be withdrawn from the cluster by means of the _node removal_ and _swap rebalance_ procedures.
+
For information on node-addition, see xref:learn:clusters-and-availability/nodes.adoc#clusters[Clusters].
For information on node-removal, see xref:learn:clusters-and-availability/removal.adoc[Removal].
For information on _swap rebalance_, see xref:install:upgrade-procedure-selection.adoc#swap-rebalance[Swap Rebalance].

* Nodes will be upgraded _one at a time_.

The overall procedure is described in seven stages, below.

[#prepare-a-spare-node]
== Stage One: Prepare a Spare Node

Install the latest version of Couchbase Server on the spare node.
For instructions, see xref:install:install-intro.adoc[Install]; and follow steps 1, 2, and 3.

[#prepare-the-cluster]
== Stage Two: Prepare the Cluster

Back up all cluster-data.
This can be performed either with xref:backup-restore:enterprise-backup-restore.adoc[cbbackupmgr] or with the xref:learn:services-and-indexes/services/backup-service.adoc[Backup Service]; and should be a _full_ (rather than an incremental) backup.

For example, to use `cbbackupmgr` to configure an archive and repository for the backup, a command of the following form should be entered:

[source,bash]
----
cbbackupmgr config --archive ${ABS_PATH_TO_ARCHIVE} --repo ${REPO_NAME}
----

Here, `ABS_PATH_TO_ARCHIVE` is an absolute path to a filesystem location that will serve as the archive within which the backed up data will reside.
The `REPO_NAME` is the name of the repository that will be associated with the location.

Once the archive and repository have been created, a command such as the following performs a full backup:

[source,bash]
----
cbbackupmgr backup --archive ${ABS_PATH_TO_ARCHIVE} --repo ${REPO_NAME} \
--cluster ${CLUSTER_ADDRESS} --username ${USERNAME} --password ${PASSWORD} \
--full-backup
----

Here, the `CLUSTER_ADDRESS` is the IP address or domain name of the cluster that is being backed up.
The `--full-backup` flag ensures that the backup is indeed a _full_ backup.

For the equivalent procedure as performed by the Backup Service, see xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc#run-an-immediate-backup[Run an Immediate Backup].

[#add-and-remove-a-node]
== Stage Three: Add the Spare Node, and Remove a Node

_Add_ the upgraded, removed node back into the cluster, and _remove_ a node that is currently part of the cluster.
The node that is being added should be configured to run the same service (or services) as on the node that is to be removed.
For example, if the node to be removed is running the Data Service, configure the node to be added to run the Data Service.
Couchbase Server will execute the rebalance as a _swap rebalance_, to maximize efficiency.

For an overview of node-removal, see xref:learn:clusters-and-availability/removal.adoc[Removal]; and for practical examples of performing removal, see xref:manage:manage-nodes/remove-node-and-rebalance.adoc.
For an overview of node-addition, see xref:learn:clusters-and-availability/nodes.html#clusters[Clusters]; and for practical examples of node-addition, see xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a Node and Rebalance].

Note that for the CLI and REST API, the staging of a swap rebalance requires _two_ separate commands.

* The first specifies that one or more nodes be _added_ to the cluster: however, this command requires a subsequent rebalance to be performed, to complete the process.
+
For an example of performing addition with the CLI, see xref:manage:manage-nodes/add-node-and-rebalance.adoc#add-a-node-with-the-cli[Add a Node and Rebalance with the CLI].
For an example of performing addition with the REST API, see xref:manage:manage-nodes/add-node-and-rebalance.adoc#add-a-node-with-the-rest-api[Add a Node and Rebalance with the REST API].

* The second command indeed specifies that subsequent rebalance, but also includes an instruction to _remove_ one or more nodes from the cluster: therefore, as the rebalance occurs, it finalizes both node-addition and node-removal.
+
For an example of using rebalance to remove a node with the CLI, see xref:manage:manage-nodes/remove-node-and-rebalance.adoc#remove-a-node-with-the-cli[Remove a Node with the CLI].
For an example of using rebalance to remove a node with the REST API, see xref:manage:manage-nodes/remove-node-and-rebalance.adoc#remove-a-node-with-the-rest-api[Remove a Node with the REST API].

[#upgrade-the-removed-node]
== Stage Four: Upgrade the Removed Node

Upgrade the node that has just been removed, by proceeding as follows:

. Stop the `couchbase-server.service` service, on the node.
Enter the following command:
+
[source,bash]
----
systemctl stop couchbase-server.service
----
+
This _stops_ the service; and so allows it to be restarted after reboot.
Note that, optionally, at this point, the service can also be _disabled_; which prevents it from restarting after reboot.
This may be useful if additional tasks, such as OS upgrade, need to be performed.
If such disabling is desired, enter the following command:
+
[source,bash]
----
systemctl disable --now couchbase-server.service
----

. Back up the configuration files for the removed node.
On a Linux system, these files are to be found in `/opt/couchbase/var/lib/couchbase/config`.
Ideally, these should be backed up onto a different machine.
The command takes the following form:
+
[source,bash]
----
cp -r /opt/couchbase/var/lib/couchbase/config ${PATH_TO_A_SAFE_LOCATION}/${NODE_IP}_config_files
----

. Uninstall `couchbase-server` and its dependencies from the removed node.
Enter the command that is appropriate for the platform.
Note that the following examples remove _Enterprise Edition_ of Couchbase Server: to remove _Community Edition_, specify `couchbase-server-community` (instead of `couchbase-server`).
+
[{tabs}]
====
RedHat & Centos::
+
--

[source,bash]
----
yum autoremove couchbase-server
----

--

Ubuntu & Debian::
+
--

[source,bash]
----
apt autoremove --purge couchbase-server
----

--
====

. Manually remove files from `/opt/couchbase`.
This folder contains configuration files for the previous server-version; which need to be overwritten by configuration files for the new version.
If the administrator has manually included in this folder any files that were not provided by Couchbase Server, and need to be retained, these should be individually identified and backed up with xref:backup-restore:enterprise-backup-restore.adoc[cbbackupmgr] or with the xref:learn:services-and-indexes/services/backup-service.adoc[Backup Service].
Note also that care should be taken regarding the potential removal of files used in network sharing.
+
Enter the following command:
+

[source,bash]
----
rm -r /opt/couchbase
----

. Determine whether any other files, still resident on the node, need to be either removed, or backed up and removed.
If such files exist, deal with them accordingly.

. Install Couchbase Server on the node.
Follow steps 1, 2, and 3; provided in xref:install:install-intro.adoc[Install].

. _Pin_ (or _hold_) automated Couchbase-Server updates for the node.
This ensures that no further upgrade can occur to this node until the next time the administrator selectively performs the process.
+
[{tabs}]
====

RedHat & Centos::
+
--
For Couchbase Server Enterprise Edition, ensure that the package-name appears in the list that follows the `exclude` statement, in the file `/etc/yum/yum.conf`.
For example:

[source,bash]
----
exclude=couchbase-server
----

(For Couchbase Server Community edition, specify `couchbase-server-community`, instead of `couchbase-server`).

--

Ubuntu & Debian::
+
For Couchbase Server Enterprise Edition, run the following command:
+
--
[source,bash]
----
apt-mark hold couchbase-server
----

(For Couchbase Server Community edition, specify `couchbase-server-community`, instead of `couchbase-server`).

--
====

. Assuming that the `couchbase-server.service` service was _stopped_ on the node to be upgraded prior to that node's upgrade, restart the service.
+
Note that if the service was also _disabled_, it must be _re-enabled_, prior to being started.
To re-enable the service, if necessary, enter the following command:
+
[source,bash]
----
systemctl enable --now couchbase-server.service
----
+
To restart the service, enter the following command:
+
[source,bash]
----
systemctl start couchbase-server.service
----

[#add-back-the-upgraded-node-and-remove-another-node]
== Stage Five: Add Back the Upgraded Node, and Remove Another Node

_Add_ the upgraded, removed node back into the cluster, and _remove_ a node that is currently part of the cluster.
The node that is being added should be configured to run the same service as that running on the node that is to be removed.
For example, if the node to be removed is running the Data Service, configure the node to be added to run the Data Service.
Couchbase Server will execute the rebalance as a _swap rebalance_, to maximize efficiency.

[#repeat-stages-three-and-four]
== Stage Six: Continually Repeat Stages Four and Five

Upgrade the newly removed node as described above, in xref:install:upgrade-cluster-online-full-capacity.adoc#upgrade-the-removed-node[Stage Four: Upgrade the Removed Node].
Then, add the upgraded node back into the cluster, and remove another node to be upgraded: as described above, in xref:install:upgrade-cluster-online-full-capacity.adoc#add-back-the-upgraded-node-and-remove-another-node[Stage Five: Add Back the Upgraded Node, and Remove Another Node].

Continue to remove, upgrade, and restore nodes in this way; until the cluster is fully upgraded, and only the spare node remains outside the cluster.

[#add-back-the-last-node]
== Stage Seven: Repurpose the Spare Node

Once the cluster has been fully upgraded, the spare node can be repurposed.
This concludes the overall cluster-upgrade process.
