= Upgrade an Online Cluster

:description: A cluster can be upgraded while continuing to serve data.

[abstract]
{description}

== Online Upgrade at Reduced and Full Capacity

A Couchbase-Server cluster can be upgraded while continuing to serve data.
A _spare node_ must be used, if the cluster is to serve data at full capacity for the duration of the upgrade.
If no spare node is available, the cluster must serve data at reduced capacity, for the duration of the upgrade.
The available procedures are provided as follows:

* xref:upgrade-cluster-online-reduced-capacity.adoc[Upgrade a Reduced-Capacity, Online Cluster]

* xref:upgrade-cluster-online-full-capacity.adoc[Upgrade a Full-Capacity, Online Cluster]

* xref:upgrade-docker-cluster-online-full-capacity.adoc[]
+
include::partial$cannot-upgrade-docker-single-node.adoc[tag=cannot-upgrade-single-docker-node-note]

[#tls-address-family-restriction-and-node-addition]
=== TLS, Address-Family Restriction, and Node Addition

Couchbase Server Version 7.0.2+ allows TLS to be specified as mandatory for all internal and external cluster-communications -- see xref:manage:manage-security/manage-tls.adoc[Manage On-the-Wire Security].
It also allows the cluster's address family to be specifically restricted to either IPv4 or IPv6 -- see xref:manage:manage-nodes/manage-address-families.adoc[Manage Address Families].

The procedures described in the current section both involve the introduction of upgraded nodes into an existing, online cluster.
If the cluster is running Version 6.0.x, and the upgraded node is running Version 7.0.2{plus}, and the upgraded node has TLS specified as mandatory, and/or has its address family restricted to either IPv4 or IPv6, the upgraded node _cannot_ be added to the cluster.

To add the node to the cluster, change the node's TLS setting so that TLS is _not_ mandatory for all communications, and/or change the node's address family so that it is _not_ specifically restricted to either IPv4 or IPv6.
Then, _restart_ the node.
After the node has restarted, it can be added to the 6.0.x cluster.
