= Feature Availability During Upgrade
:description: During the cluster-upgrade procedure, some features may not be available.
:page-aliases: install:upgrade-strategy-for-features

{description}

[#understanding-feature-availability]
== Understanding Feature Availability

The process of upgrading a cluster involves upgrading each node individually, from a lower version of Couchbase Server to a higher.
Node-upgrades occur sequentially.
Consequently, during the overall cluster-upgrade process, the cluster runs in _mixed mode_; meaning that some nodes are running the lower version, and others the higher.

Since a higher version of Couchbase Server always introduces features not provided by a lower, such features should not be used during the upgrade process, unless such use is explicitly supported in mixed-mode conditions.
When cluster-upgrade is complete, all the features of the higher version of Couchbase Server can be used.

The following table summarizes the new features in Couchbase Server Enterprise Edition Version 7.0 and later, and indicates whether or not they can be used in the mixed-mode conditions that exist during the cluster-upgrade process.
_Usable in mixed mode_ indicates that the feature can be used (though not necessarily across the entire cluster) as long as one node is running the higher version.
_Not usable in mixed mode_ indicates that cluster-upgrade must be fully completed, before the feature can be used in any way.

[cols="2,6"]
|===
| Feature | Whether Usable in Mixed Mode

| xref:learn:data/scopes-and-collections.adoc[Scopes & Collections]
| Not usable in mixed mode.
During upgrade, all documents on an upgraded node appear in the `_default` collection, within the `_default` scope.
No new scope or collection can be defined until all nodes have been upgraded.

XDCR cannot be used to specify scopes or collections as either sources or targets for replication until all nodes have been upgraded.

| xref:metrics-reference:metrics-reference.adoc[Metrics]
| Usable in mixed mode for upgraded nodes.
When all nodes have been upgraded, usable for entire cluster.

Note that pre-7.0 statistics are deleted from each node when the node is upgraded.

| Magma
| Not usable in mixed mode.
Magma is a Developer Preview feature that is switched on per bucket.
Magma should not be switched on until all nodes have been upgraded.

| xref:learn:data/durability.adoc#specifying-levels[Bucket-Assigned Durability Levels]
| When a Data Service node is upgraded from a version less than 6.6, the durability-level setting for all the node's vBuckets is set to _none_.

Bucket durability-levels should not be modified until after the completion of cluster-upgrade.

When a Data Service node is upgraded from Version 6.6, all bucket durability-level settings remain unchanged.
Applications that use durable writes can continue to access data throughout the upgrade.

| xref:learn:security/on-the-wire-security.adoc[On-the-Wire Security]
| On-the-wire security-features introduced in 7.0 are not usable in mixed mode.
These features, including TLS 1.3 support, should be used only following the completion of cluster-upgrade.
If, at that time, a TLS version is changed, existing connections are not dropped, and so continue with their previously established TLS version: the new TLS version will be established for future connections.

| xref:learn:services-and-indexes/services/backup-service.adoc[Backup Service]
| Not usable in mixed mode.
All nodes in the cluster should first be upgraded.

| Analytics Service
| No new Analytics-Service feature is usable in mixed mode.
All nodes in the cluster must be upgraded, before new Analytics-Service features can be used.

| Query Service
| The xref:tools:query-workbench.adoc#index-advisor[Index Advisor] and xref:settings:query-settings.adoc[Memory-Usage Quota Setting] are usable in mixed mode.

xref:n1ql:n1ql-language-reference/flex-indexes.adoc[Flex Indexes], though not a new feature, are usable in mixed mode only if the cluster being upgraded is at least version 6.5.

The xref:n1ql:n1ql-language-reference/cost-based-optimizer.adoc[], xref:n1ql:n1ql-language-reference/transactions.adoc[], and xref:n1ql:n1ql-language-reference/userfun.adoc[] are not usable in mixed mode.
|===
