= Upgrading to Couchbase Server 6.0

Upgrading to the latest version of Couchbase Server allows you to leverage the latest features and helps keep your cluster running well.
The following table summarizes the new features in this release, and describes what parts of the cluster need to be upgraded to enable them.

.Couchbase Server 6.0 Feature Upgrade Matrix
[cols="5,2,2,2,2,2,2"]
|===
| Feature | Upgrade Level | xref:upgrade-strategies.adoc[Upgrade Type] | xref:upgrade.adoc#table_swd_vpc_rbb[Upgrade Path] | Mixed Mode <<feature-mixed-mode,†>> | Dependencies | Additional Information

| Analytics Service
| Cluster
| Offline/Online
| Direct
| No
| If you plan to use the production release of Couchbase Analytics in version 6.0, you must perform a fresh installation of Couchbase Server 6.0 on any existing Analytics nodes that are running a previous version.
Otherwise, the Analytics Service will not function properly.
| Analytics data from Developer Preview releases cannot be upgraded.

| Timers (Eventing Service)
| Cluster
| Offline/Online
| Direct
| No
| All Eventing nodes must be running version 6.0 to enable this feature.
| None

| Scorch indexing system (Full Text Search)
| Cluster
| Offline/Online
| Direct
| Yes*
| *FTS nodes running version 6.0 use the Scorch indexing system by default for new indexes.
You can continue to use previous indexes in version 6.0, but they will not use Scorch.
| To upgrade previous indexes to use Scorch, simply xref:fts:fts-creating-indexes.adoc[recreate] them using the new index type option.
|===

[[feature-mixed-mode]]† _Mixed Mode in this context refers to only the nodes that are running the indicated service.
So if 'No' is marked in the Mixed Mode column of a given feature, then all nodes that are running that service must be upgraded to the same version in order to enable that feature._

[#upgrade-ipv6]
== Migrating Data from an IPv4 Cluster to an IPv6 Cluster

You can migrate data from an IPv4 cluster to an IPv6 cluster with an offline upgrade, or online by using unilateral replication.
You must ensure that your operating system has dual stack support.

*Offline Upgrade from an IPv4 Cluster to an IPv6 Cluster*

_Prerequisites_: Ensure that the source cluster is on an operating system with dual stack support.

Follow the instructions available in the section xref:upgrade-offline.adoc[Performing the Offline Upgrade].
When all the nodes are offline, restart each node with IPv6 enabled.
See xref:ipv6-setup.adoc[Using IPv6 With Couchbase] for instructions to enable IPv6.

*Online Upgrade from an IPv4 Cluster to an IPv6 Cluster using XDCR*

_Prerequisites_: Ensure that the source cluster is running Couchbase Server 5.5 or newer on an operating system with dual stack support, and the destination cluster is running Couchbase Server 5.5 or newer on an IPv6 network.

_Steps_:

. Upgrade the source cluster to Couchbase Server 5.5 or newer.
. Create a new cluster with IPv6 enabled and configured.
See xref:ipv6-setup.adoc[Using IPv6 With Couchbase] for instructions to enable IPv6.
Note that this cluster needs to be sized appropriately for the workload, but does not need to be identical to the source cluster.
. xref:xdcr:xdcr-create.adoc[Create a cluster reference and replication stream] from the source to the destination cluster.
At this point, the destination cluster is not receiving any application load directly, other than the replication traffic from the source cluster.
. xref:monitoring:ui-monitoring-statistics.adoc#outgoing_xdcr_stats[Monitor the XDCR queue] from the source until all mutations are replicated to the destination cluster.
. Reconfigure the application to start accessing the destination cluster.
. Once all your applications have been moved, you can decommission the source cluster.

IMPORTANT: IPv4 and IPv6 clusters cannot be paired for bi-directional (active-active) XDCR replication.
For bi-directional replication, both clusters need to be using IPv4 or IPv6.
