[#topic_y23_jjv_xs]
= Upgrade Strategies

[abstract]
Upgrade a Couchbase Server cluster in a manner that is best suited to your operations.

The following upgrade strategies are available:

* Standard online upgrade
* Swap rebalance online upgrade
* Offline upgrade
* Cross Datacenter Replication (XDCR)

Both the online and offline upgrade processes have trade-offs.
The following table illustrates some important aspects of the two upgrade strategies.

.Differences between online and offline upgrades
[#table_shv_yr2_zs]
|===
| Feature | Online upgrade | Offline upgrade

| Applications remain available
| Yes
| No

| Cluster stays in operation
| Yes
| No

| Cluster must be shut down
| No
| Yes

| Typically required steps
| Rebalance, upgrade, rebalance per node
| All cluster nodes are upgraded at once.
|===

IMPORTANT: Mac OSX does not support a direct upgrade.
When upgrading on this platform, first back up your data and perform a clean uninstall of the old version.
Once you install the new version, restore the data back to the new cluster.
