= Upgrading IPv6 Clusters

[abstract]
All pre-6.5 clusters using the IPv6 address family can be upgraded to Couchbase Server Enterprise Edition 6.5: in some cases, additional steps are required in the upgrade-procedure.

== IPv6 Cluster-Upgrade to 6.5

A pre-6.5 Couchbase Server-cluster that is currently using the IPv6 address family can be upgraded to run 6.5 _and_ to continue using IPv6:

* _All_ IPv6 clusters running a pre-6.5 version of Couchbase Server Enterprise Edition can perform _online_ upgrade as explained in xref:install:online-upgrade.adoc[Performing the Online Upgrade].

* IPv6 clusters currently running Couchbase Server Enterprise Edition Version 5.5.3, 6.0.1, or higher can perform _offline_ upgrade as explained in xref:install:offline-upgrade.adoc[Performing the Offline Upgrade].

* IPv6 clusters currently running Couchbase Server Enterprise Edition Version 5.5.0, 5.5.1, 5.5.2, or 6.0.0 must perform _offline_ upgrade as explained in xref:install:offline-upgrade.adoc[Performing the Offline Upgrade], and then perform the additional steps described below.

Note that pre-6.5 clusters that are to be upgraded to 6.5, and whose address family is to be changed, are recommended _first_ to be upgraded to 6.5, and _subsequently_ assigned the new address family.
Note also that if a pre-6.5 cluster is not using IPv6 and no address-family change is required, the cluster can be upgraded to 6.5 by either an _offline_ or an _online_ procedure, with its address-family setting remaining unchanged.

=== Additional Upgrade Steps for Some Clusters

To complete _offline_ upgrade to 6.5 for a 5.5.0, 5.5.1, 5.5.2, or 6.0.0 cluster, after completion of the instructions in xref:install:offline-upgrade.adoc[Performing the Offline Upgrade], proceed as follows:

. Stop Couchbase Server.
For instructions, see xref:install:startup-shutdown.adoc[Start and Stop Couchbase Server].

. As either _root_ or _couchbase user_, enter the following command:
+
----
if [ -e /opt/couchbase/var/lib/couchbase/config/dist_cfg ] && [ ! -s /opt/couchbase/var/lib/couchbase/config/dist_cfg ]; then
  echo "[{preferred_external_proto,inet6_tcp_dist}, {preferred_local_proto, inet6_tcp_dist}]." > /opt/couchbase/var/lib/couchbase/config/dist_cfg;
fi
----

. Start Couchbase Server.

This concludes the upgrade-process.
