= Upgrade
:description: To upgrade a Couchbase-Server cluster means to revise upwards the version of Couchbase Server that is running on every node.

[abstract]
{description}

[#understanding-upgrade]
== Understanding Upgrade

To _upgrade_ a Couchbase-Server cluster means to revise upwards the version of the server that is running on every node.
For example, a cluster each of whose nodes has been running Couchbase Server Enterprise Edition Version 6.6 is modified; such that each of its nodes subsequently runs Couchbase Server Enterprise Edition Version 7.2.

An _upgrade procedure_, like an install procedure, involves both preparation routines and specific upgrade commands that are performed on each individual node.
To be upgraded, a cluster must have each of its nodes individually upgraded in turn; and the upgrade procedure for the cluster must therefore be selected with regards to whether the cluster is required to continue serving data, or to cease serving data, during the course of the cluster-upgrade.
A review of the factors that determine the appropriateness of an upgrade-procedure is provided in xref:install:upgrade-procedure-selection.adoc[Upgrade Procedure-Selection].

== Before You Upgrade

Before upgrading Couchbase Server, consider the following compatibility concerns:


=== Upgrading to Version 7.x With Earlier Versions of .NET SDK

// So long as upgrading from 6.x is supported, this notice will need to stay in some form in each new release.
If you're upgrading Couchbase Server versions 6.5 or 6.6 to version 7.0 or later and using a .NET SDK version earlier to 3.2.9 make sure your cluster is not running in `mixed mode`.
Mixed mode occurs when some nodes are using IPv4 addressing while others are using IPv6.
Using an earlier version of the .NET SDK with a Couchbase Server in mixed mode can result issues when executing write operations on the cluster.
To learn how to determine if your cluster is in mixed mode and how to resolve the issue, see xref:manage:manage-nodes/manage-address-families.adoc#changing-address-family-to-IPv6[Changing Address Family]

=== TLS Version Support Changes in Version 7.6 and Later

// Remove after you can no longer upgrade from pre-7.6 to 7.6.
Transport Layer Security (TLS) controls how servers and clients negotiate secure connections. 
The TLS standard has multiple versions. 
Couchbase Server Enterprise Edition lets you enable TLS so that clients can securely connect to the server.
You can set a minimum version of TLS that Couchbase Server allows globally and for individual services using the setting named `tlsMinVersion`.

Earlier versions of TLS are no longer considered secure.
Couchbase Server version 7.2 deprecated versions 1.0 and 1.1 of TLS.
Couchbase Server 7.6 and later no longer support these versions. 

The upgrade process to 7.6 or later checks to see if the cluster or services setting of `tlsMinVersion` is set to `tlsv1` or `tlsv1.1`. 
If it finds any `tlsMinVersion` settings with these values, it automatically changes them to `tlsv1.2`, the new minimum version that Couchbase Server supports.

Before upgrading, make sure all client applications that connect to your database using secure connections support at least TLS version 1.2. 
If they do not, they cannot securely connect to your database after you upgrade to Couchbase Server version 7.6 or later.
If your cluster requires secure connections, the clients that do not support TLS 1.2 or later will not be able to connect at all.

[#supported-upgrade-paths]
== Upgrade Paths

An upgrade _path_ declares that the upgrade of one version of Couchbase Server to another is _supported_.
The tables in the following subsections list upgrade paths for Enterprise Edition and for Community Edition, respectively.
Each instance of the sign -> declares support for the upgrade of the server-version on the left of the sign to the server-version on the right.
Note that upgrade between non-adjacent version-numbers is frequently _not_ supported: for example, to upgrade from 5.5.0+ to 7.2, upgrade must be performed _twice_; first from 5.5.0+ to 6.6, and secondly from 6.6 to 7.2.

All supported upgrades can be performed with the cluster either _offline_ or _online_.

[IMPORTANT]
====
If you are upgrading several nodes at once, then the version of the software on each node must be kept in step throughout the upgrade process. +
For example, if you are upgrading three enterprise nodes (`*Node{nbsp}1*`, `*Node{nbsp}2*` and `*Node{nbsp}3*`) from version 5.0x to 7.2, then you would use the following sequence:

[cols="1,2,2"]
|===
| Step | Description | Upgrades

| {counter: upgrade}
| Upgrade all nodes from 5.0x to 5.1x
|
`*Node{nbsp}1*` => 5.0x -> 5.1x +
`*Node{nbsp}2*` => 5.0x -> 5.1x +
`*Node{nbsp}3*` => 5.0x -> 5.1x

| {counter: upgrade}
| Upgrade all nodes from 5.1x to 6.6
|

`*Node{nbsp}1*` => 5.1x -> 6.6 +
`*Node{nbsp}2*` => 5.1x -> 6.6 +
`*Node{nbsp}3*` => 5.1x -> 6.6

| {counter: upgrade}
| Upgrade all nodes from 6.6 to 7.2
|
`*Node{nbsp}1*` => 6.6 -> 7.2 +
`*Node{nbsp}2*` =>  6.6 -> 7.2 +
`*Node{nbsp}3*` => 6.6 -> 7.2

|===


====

[#table-upgrade-enterprise]
=== Enterprise Edition Upgrade Paths

[cols="2,6"]
|===
| Starting Version |  Path to Current Version

| 5.0.x
| 5.0.x and 5.1.x -> 6.0.4+ -> 6.6 -> 7.2x

5.0.x and 5.1.x -> 6.6 -> 7.2x

5.5.0+ -> 6.6 -> 7.2x

| 6.x
| 6.0 -> 6.5 -> 7.2x
|===

[#table-upgrade-community]
=== Community Edition Upgrade Paths

[cols="2,6"]
|===
| Starting Version | Path to Current Version

| 5.x
| 5.x -> 6.0 -> 6.5 -> 7.2x

| 6.x
| 6.0 -> 6.5 -> 7.2x


|===

.Important note when upgrading from 7.0.4 to 7.2x on Windows 2019
[sidebar]
****
Upgrading from version 7.0.4 -> 7.2x on Windows Server 2019 may result in a missing `java` executable files.

The problem is caused by the way Windows handles upgrades when dealing with older files, resulting in files being removed from the Couchbase installation without being replaced.

The server can be fixed by invoking the Windows Repair operation on the Couchbase installation.
This will restore the missing files.

****
[#upgrade-community-enterprise]
== Upgrade from Community Edition to Enterprise


If you're currently operating a Couchbase Server cluster on Community Edition, you can upgrade it to Enterprise Edition by way of a xref:upgrade-strategies.adoc#online-upgrade[rolling online upgrade].
This involves switching out the Community Edition nodes with fresh, net-new Enterprise Edition nodes.
Both 'swap rebalance' and 'remove and reblance' methods are supported.
(Delta Recovery is not supported since the new nodes must be fresh Enterprise Edition installations without any pre-existing Community Edition data remaining on them.)

NOTE: Rolling upgrades from CE to EE are not supported if there are index service nodes running in the cluster.

The Enterprise Edition nodes must be running the same version number of Couchbase Server as the Community Edition nodes that they are replacing, otherwise the upgrade may fail.
This means you can't upgrade to a newer version of Couchbase Server while also upgrading to Enterprise Edition during the same rolling upgrade.

If you want to upgrade from an older version of _Community Edition_ to a newer version of _Enterprise Edition_, you need to perform two separate upgrade procedures:

. Upgrade the entire cluster to Enterprise Edition via a rolling online upgrade
. Upgrade to the desired version number of Couchbase Server using any supported type of upgrade

For example, if you wanted to upgrade from Couchbase Server 6.6 Community Edition to Couchbase Server 7.2 Enterprise Edition, the process would look like the following:

.Example Upgrade Path from Community to Enterprise
include::partial$diagrams.adoc[tag="upgrade-diagram"]

.Additional Notes about Upgrading from Community to Enterprise
[sidebar]
****
* Couchbase Server clusters _must_ be run either entirely on Enterprise Edition nodes, or entirely on Community Edition nodes. +
Once you've upgraded one node to Enterprise Edition, you must upgrade all the other nodes before the cluster is considered as being in a steady, supportable state.
* CE does not support index service rebalancing.
So, when the cluster is running with one or more CE nodes, then the indexes hosted on nodes being removed may be lost. +
 Users can create equivalent indexes (same index with different name) on different nodes, to avoid loss of index functionality.
* If a rolling online upgrade to Enterprise Edition isn't possible in your environment, contact Couchbase for assistance.
****

[IMPORTANT]
====
Remember that Enterprise Edition is not free to run in production.
If you're interested in upgrading to Couchbase Server Enterprise Edition, check out the https://www.couchbase.com/products/editions[editions page^].
====


See xref:install:upgrade-procedure-selection.adoc[Upgrade Procedure-Selection], for a list of procedures that can be used when upgrading from Community Edition to Enterprise.
Note, however, that _Graceful Failover_ for Data Service nodes, with _Delta Recovery_, is _not_ supported for such upgrades: instead, _removal_, _addition_, and _swap rebalance_ should be used; for all nodes.

[#node-naming-and-upgrade]
== Node-Naming and Upgrade

In Couchbase Enterprise Server Version 7.2 or later, the node-name _must_ be correctly identified in the node-certificate as a Subject Alternative Name.
If the node-name is _not_ correctly identified, failure may occur during upgrade.
For information, see xref:learn:security/certificates.adoc#node-certificate-validation[Node-Certificate Validation].

[#downgrade]
== Downgrade

Once an upgrade of a Couchbase-Server cluster has started, _downgrade_ to the earlier version of Couchbase Server can be performed, provided that one node continues to run the earlier version.
However, once all nodes are running the later version, downgrade can no longer be performed: therefore, once all nodes are running the later version, should application-support require the earlier version, an entirely new cluster must be created, running the earlier version.
