[#topic_q11_1my_p4]
= Performing the Offline Upgrade

[abstract]
During an offline upgrade, the cluster must be shut down and all applications built on it will not be available during that time.

You should schedule offline upgrades into an appropriate maintenance window, and you might also consider using a systems orchestration tool to automate the process to ensure the accuracy and further process efficiency.

TIP: Check that the disk write queue is completely drained to make sure that all data has been persisted to disk and will be available after the upgrade.
It is recommended that you turn off your application and allow the queue to drain before upgrading.

To perform an offline upgrade:

. Disable auto-failover for all nodes in the cluster.
Use the Couchbase Web Console under menu:Settings[Auto-Failover].
+
If you do not disable auto-failover, the first node that you shut down will be failed over automatically by the cluster.

. Shut down your application so that the Couchbase Server cluster handles no more requests.
. You can use the Couchbase Web Console to monitor cluster activity.
The cluster must finish writing all information to disk.
When you restart your cluster, all of your data can be brought back into the caching layer from disk.
+
You can monitor the Disk Write Queue statistics for each bucket in your cluster.
When the queue reaches zero, no more data remains to be written to disk.

. Open the Couchbase Web Console at a node in your cluster.
. Click [.ui]*Data Buckets |your_bucket*.
In the [.ui]*Summary* section, check that [.ui]*Disk write queue* is equal to 0.
If you have more than one data bucket in your cluster, repeat this check on each bucket.
. Create a backup of your cluster data using the xref:backup-restore:cbbackupmgr.adoc#cbbackupmgr.1[cbbackupmgr] tool.
. Stop the Couchbase Server service on each cluster node.
. After you shut down the services, perform a standard node upgrade to the new version of Couchbase Server as explained in xref:upgrade-individual-nodes.adoc[Performing the Single Node Upgrade].
+
Couchbase Server starts automatically on each node after you perform the node upgrade.

. You can monitor the warmup process status after starting the cluster with the xref:cli:cbstats-intro.adoc#cbstats-intro[cbstats tool] to determine when the cluster can begin servicing application requests.

After the cluster finishes warmup, your applications can use the upgraded cluster.
