= Unattended Installation

[abstract]
An unattended installation uses a script to install Couchbase Server.

To use the unattended installation process:

. Record your installation settings in the wizard installation.
These settings are saved to a file, which is used to silently install other nodes of the same version.
 .. Open a Command Terminal or Power and start the installation executable with the `/r` command-line option:
+
----
> couchbase_server_version.exe /r /f1your_file_name.iss
----

 .. Provide your installation options when prompted.
The wizard completes the server installation and provides a file with your recorded options at [.path]_C:\Windows\your_file_name.iss_.
+
NOTE: Accept an increase in `MaxUserPort` (recommended).
. Copy the `your_file_name.iss` file into the same directory as the installer executable.
Run the installer from the command-line using the `/s` option:
+
----
> couchbase_server_version.exe /s -f1your_file_name.iss
----

. To repeat this process on multiple machines, copy the installation package and the `your_file_name.iss` file to the same directory on each machine.
