= Calling JavaScript from {sqlpp} User-Defined Functions
:description: Using an {sqlpp} User-Defined Function to call JavaScript functions.
:page-edition: Enterprise Edition
:page-toclevels: 2
:keywords: scopes, variadic
[abstract]
{description}

== Introduction

Before you can call a JavaScript function, you must first create an {sqlpp} User-Defined Function it.
The process to do this is explained in the  xref:guides:create-user-defined-function.adoc#creating-the-n1ql-udf-function[Creating the {sqlpp} User-Defined Function] section of our xref:guides:javascript-udfs.adoc[] guide.

If you are unfamiliar with creating User-Defined Functions to call JavaScript, then the xref:guides:javascript-udfs.adoc[guide] is the best place to start.

In this section, we're going to take a closer look at concepts around {sqlpp} User-Defined Functions, such as variadic parameter lists.

== Scopes and {sqlpp} User-Defined Functions

A JavaScript function can be xref:guides:create-javascript-library.adoc#creating-the-library-and-adding-your-first-function[created through the WorkBench or through the REST API]. 

[source, javascript, role="no-callouts"]
----
include::example$get-business-days.js[]
----

And the corresponding {sqlpp} User-Defined Function can be created through the xref:guides:create-user-defined-function.adoc#creating-the-n1ql-udf-function[Query Workbench] or by executing a {sqlpp} statement:

[source, sqlpp]
----
include::example$create-scoped-n1ql-udf.n1ql[] 
----
<.> The new {sqlpp} User-Defined Function is called `GetBusinessDays` and takes the `inventory` scope inside the `travel-sample` bucket.
As well as providing a logical separation between JavaScript libraries, using scopes provides a means of securing access to the library: a user must have a context that matches the scope of the library in order to access it.
<.> This function will reference the `getBusinessDays` JavaScript function …
<.> … in a library called `my-library` which is set to the `inventory` scope within the `travel-sample` bucket.

=== Global Library Path

Of course, you can define the library at the cluster level, where it will be accessible to anyone who has access rights to the cluster. 
Functions in the global library are accessible across the cluster.

.Creating an {sqlpp} User-Defined Function to access the JavaScript function in the global library
[source, sqlpp]
----
include::example$create-globally-scoped-n1ql-udf.n1ql[]
----
<.> There is no prefix path before `my-library` which means the library is a globally accessible library defined at the cluster level.

=== Relative Library Path

You can also use relative paths for the library location:

[source, sqlpp]
----
include::example$create-relatively-scoped-n1ql-udf.n1ql[]
----
<.> In this case, the User-Defined Function will be created for the JavaScript function under the current xref:tools:query-workbench.adoc#query-context[query context].

== Calling the Function

Once the {sqlpp} User-Defined Function is defined, it can be called as if it were a built-in {sqlpp} function:

.Query
[source, sqlpp]
----
include::example$select-get-business-days.n1ql[]
---- 

which will return the following result:

.Result
[source, json]
----
include::example$select-get-business-days-response.jsonc[]
----

You can also use the `EXECUTE FUNCTION` statement to execute the function:

[source, sqlpp]
----
include::example$execute-javascript-function.n1ql[]
----

or as part of a complex statement:

[source, n1ql, role=no-callouts]
----
include::example$select-true-alias-get-business-days.n1ql[]
----

[#variadic-parameters]
== Variadic Parameters

You can define an {sqlpp} User-Defined Function with a variadic parameter, which means that the parameter will accept a list of values which it will pass to the JavaScript function it references.
We can create the `GetBusinessDays` function using a variadic parameter rather than the `startDate` and `endDate` parameters:

[source, sqlpp]
----
include::example$create-variadic-n1ql-udf.n1ql[]
----
Note that the statement used three dots (...) rather than a list of parameter list. This indicates a variable length parameter list. 
The underlying JavaScript function will reference the parameter list as named variables:

[source, javascript, role=no-callouts]
----
include::example$get-business-days-no-ops.js[]
----

You can also use a variable length parameter list in the JavaScript function itself:

[source, javascript]
----
include::example$variadic-sum.js[]
----
<.> JavaScript uses three dots (...) followed by a parameter name to denote a parameter that is an array of values.
<.> Scans through the variadic parameter list, summing all the numbers it contains.

An {sqlpp} User-Defined Function can now be created that takes a variable length list of numbers as an argument:

[source, sqlpp]
----
include::example$create-sum-function.n1ql[]
----

which can then be called with a variable length list of numbers as a parameter

.Query
[source, sqlpp]
----
include::example$execute-sum-function.n1ql[]
----

.Result
[source, json]
----
include::example$execute-sum-function-result.jsonc[]
----
