= JavaScript User-Defined Functions
:description: Writing Couchbase Server extension functions in the JavaScript Language.
:page-edition: Enterprise Edition
:page-toclevels: 2

[abstract]
{description}

== Introduction

N1QL includes a large number of xref:n1ql:n1ql-language-reference/index.adoc[operations and generic functions] that cover every aspect of data manipulation. 
In addition to the built-in functions, Couchbase also allows you to create your own extensions to the language using Javascript.
Using Javascript user-defined functions, you can:

* Create reuseable, domain-specific functions for use in your applications.
* Execute complex logic that may be difficult to do in N1QL.
* Migrate from RDBMS stored procedures.
* Use  N1QL statements embedded in your Javascript to access and modify your data.

If you want to learn how to create JavaScript User-Defined functions using the administration console and/or the REST-API then take a look at our xref:guides:javascript-udfs.adoc[JavaScript UDF Guides]

In this section, we're going to look at the concepts behind JavaScript User-Defined Functions:

* xref:javascript-and-json-objects.adoc[]
* xref:calling-javascript-from-n1ql.adoc[]
* xref:calling-n1ql-from-javascript.adoc[]
* xref:handling-errors-javascript-udf.adoc[]



