= JavaScript and JSON Objects
:description: A brief guide to handling JSON objects in JavaScript.
:page-pagination: 
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2

[abstract]
{description}

== Introduction

Couchbase uses JSON has its native data format, so when building JavaScript User-Defined functions, it's important to know how to build JSON data structures natively in JavaScript.

You can read more about the JSON data format at https://www.json.org/[json.org^].

Using JSON, you can Couchbase records that store simple data such as numbers and strings, as well as complex types such as objects, dictionaries and arrays.

This guide will show to create JSON data structures using JavaScript.

== Arrays

A JSON array is simply a list of values or objects delimited by brackets:

.JSON array
[source, json]
----
include::example$array.jsonc[]
----

.Code to generate array
[source, javascript]
----
include::example$array.js[]
----
<.> Create an empty array.
<.> Add a string to the array
<.> Add a number to the array.
<.> Use `JSON.stringify` to convert the array into a JSON string, and then output the value using `console.log`. 
<.> To reference a value from an array, just use the index number. 
Array elements are numbered from zero upward, so in this example, `a[2]` will access the third element in the array.

NOTE: JavaScript does not prevent you from missing different data types in the same array.

== Key-Value Pairs

These are also called `dictionaries` or `associative arrays` and allow a key value to be stored along with associated data in a list structure.

.JSON Key-Value Pairs
[source, json]
----
include::example$key-value.jsonc[]
----
<.> You can build even more complex structures by including arrays and other key-value pairs in a parent array or key-value pair.

.Create Key-Value Pairs
[source, javascript]
----
include::example$key-value.js[]
----
<.> Create the empty list to hold the key-value pairs.
<.> Use the dot notation to add an item to the list associated with the given name. 
In this case `COUCH{nbsp}AIR` will be assigned the name `airline` in the list.
<.> Whole data structures such as arrays or other key-value pairs can be assigned to elements in the list. In this example, array `a` has been assigned to the index `coverage` in the list `kv`.
<.> The whole list can be converted to a JSON object and written out, or
<.> an individual element can be accessed using the dot notation.
<.> Alternatively, elements can be accessed by using the array index notation. 
Instead of using an index number however, you use the name associated with the element.

== Handling Dates

Although JSON doesn't have a discrete date type, it is recommended that you make use of the https://en.wikipedia.org/wiki/ISO_8601[ISO-8601^] standard, since Javascript has a number of built-in date conversion functions based around this format. 

.Create Key-Value Pairs with date
[source, javascript]
----
include::example$key-value-dates.js[]
----
<.> Use the `toJSON()` call on `Date` to create a string in ISO-8601 format.

[source, json]
----
include::example$key-values-dates.jsonc[]
----
<.> `date_established` added as a key-value pair, with the date in ISO-8601 format.



 