= JavaScript User-Defined Functions
:description: Writing Couchbase Server extension functions in the JavaScript Language.
:page-edition: Enterprise Edition
:page-toclevels: 2

[abstract]
{description}

== Introduction

N1QL includes a large number of xref:n1ql:n1ql-language-reference/index.adoc[operations and generic functions] that cover every aspect of data manipulation. 
In addition to the built-in functions, Couchbase also allows you to create your own extensions to the language using Javascript.
Using Javascript user-defined functions, you can:

* Create reuseable, domain-specific functions for use in your applications.
* Execute complex logic that may be difficult to do in N1QL.
* Migrate from RDBMS stored procedures.
* Use  N1QL statements embedded in your Javascript to access and modify your data.

If you want to learn how to create JavaScript User-Defined functions using the administration console and/or the REST-API then take a look at our xref:guides:javascript-udfs.adoc[JavaScript UDF Guides]

== Added Constructs

Javascript functions in Couchbase support most of the language constructs available in https://en.wikipedia.org/wiki/ECMAScript[ECMAScript], though there are a number of restrictions related to the Couchbase environment. 
There are also additions that have been made to the language for working specifically in the Couchbase environment.

=== N1QL Embedded Statements

Top level N1QL keywords, such as SELECT, UPDATE, INSERT and DELETE, are available as inline keywords in Eventing Functions. 
Operations that return values such as SELECT are accessible through a returned iterable handle. 
N1QL Query results, via a SELECT, are streamed in batches to the iterable handle as the iteration progresses through the result set.

[source, javascript]
----
include::example$select-airline-inline.js[]
----
<1> The N1QL is written directly into the JavaScript code without having to be used as part of a function call. 
We can even provide parameters than can be used in the N1QL statement.
<2> A standard JavaScript iterator is used to the values returned from the N1QL statement.

include::partial$libraries-and-scopes.adoc[leveloffset=+2]

== Unsupported Features

=== Browser Extensions

Because JavaScript UDF functions do not execute in the context of a browser, the extensions that browsers add to the core language, such as window methods, DOM events etc. are not available.

=== Global State
All variables  must be local to the function; global state is not permitted.

[source, javascript]
----
include::example$illegal-global-variable.js[]
----

In the rest of this section, we're going to look at the concepts behind JavaScript User-Defined Functions:

* xref:javascript-and-json-objects.adoc[]
* xref:calling-javascript-from-n1ql.adoc[]
* xref:calling-n1ql-from-javascript.adoc[]
* xref:handling-errors-javascript-udf.adoc[]



