= Migrate a Bucket's Storage Backend
:description: Full and Cluster Administrators can migrate a bucket's storage backend by calling the REST API and then performing full restores on the nodes containing the bucket.

== Storage Backend Migration Overview

[.edition]#{enterprise}#

You can migrate a bucket's storage backend if you find the bucket's current backend isn't appropriate. For example, you can migrate a bucket from Couchstore to Magma if the bucket's working set grows beyond its memory quota. 

You start a bucket's migration by calling the REST API to edit the bucket's `storageBackend` parameter. This call changes the bucket's global storage backend setting. However, it doesn't trigger an immediate conversion of the vBuckets to the new backend. Instead, Couchbase adds override settings to each node to indicate its vBuckets still use the old storage backend. To complete the migration, you must force the vBuckets to be rewritten. The two ways to trigger this rewrite is by performing a swap rebalance or a graceful failover followed by a full recovery. As Couchbase writes the vBuckets during these processes, it removes the storage override and saves the vBuckets using the new storage backend.

== Prerequisites

Before migrating a bucket, verify that the bucket's settings meet the requirements for the new storage backend. For example, a Magma bucket must have a memory quota of at least 1{nbsp}GB. The REST API call to change the bucket's storage backend fails with an error message if the bucket doesn't meet the new storage backend's requirements. See xref:learn:buckets-memory-and-storage/storage-engines.adoc[] for a list of storage backend requirements.


== Perform a Migration

. Call the REST API to change the bucket's `storageBackend` parameter. For example, the following command changes the storage backend of the travel-sample bucket to Magma.
+
[source,sh]
----
include::manage:example$migrate-bucket-storage-backend.sh[tag=change-backend]
----
. Verify that the nodes containing the bucket now have overrides of the storage backend setings for their vBuckets. The following example calls the REST API to get the bucket configuration and filters the result through the `jq` command to list the node names and their storage backend formats.
+
[source,sh]
----
include::manage:example$migrate-bucket-storage-backend.sh[tag=get-node-overrides]
----
+
The output of the previous command lists each node and the backend storage format used locally by the vBuckets:
+
----

----
. For every node that contains the bucket, perform either a [swap rebalance] or a graceful failover followed by a full recovery and rebalance to rewrite the vBuckets on the node. Each of these methods have their own limitations. Swap rebalance requires that you add an additional node to the cluster. The graceful failover and full recovery method temporarily removes a node from your cluster. The following example demonstrates using graceful failover and full recovery on a node named node3 to trigger its vBuckets to be migrated to the new storage backend.