[#topic4685]
= System logs

[abstract]
Couchbase Server creates a number of different log files depending on the components of the system that produce the error and the level and severity of the reported problem.

[cols="1,6"]
|===
| Platform | Location

| Linux
| [.path]_/opt/couchbase/var/lib/couchbase/logs_

| Windows
| [.path]_C:\Program Files\Couchbase\Server\var\lib\couchbase\logs_

Assumes default installation location

| Mac OS X
| [.path]_/Users/couchbase/Library/Application Support/Couchbase/var/lib/couchbase/logs_
|===

The table below summarizes the log files for the different components in Couchbase.

.Couchbase log files for various components
[cols="1,4"]
|===
| File | Log Contents

| `audit`
| Security auditing for administrators.

| `babysitter`
| The `babysitter` process log captures when the larger processes are spawned for cluster management, cross data center replication, views, query, and N1QL.

| `couchdb`
| Errors relating to the CouchDB subsystem that supports views, indexes, and related REST API issues.

| `debug`
| Debug level error messages related to the core server management subsystem, excluding information included in the `couchdb`, `xdcr` and `stats` logs.

| `error`
| Error level messages for all subsystems excluding cross datacenter replication.

| `goxdcr`
| Log messages related to Cross Datacenter Replication (XDCR) written in Go.

| `http_access.log`
| The admin access log records server requests (including administrator logins) to the REST API or Couchbase Server web console.
It is output in common log format and contains several important fields such as remote client IP, timestamp, GET/POST request and resource requested, HTTP status code, and so on.

| `info`
| Information level error messages related to the core server management subsystem, excluding information included in the CouchDB, cross datacenter replication, and stats logs.

| `mapreduce_errors`
| JavaScript and other view-processing errors are reported in this file.

| `memcached.log`
| Contains information relating to the core memcached component, including vBucket and replica and rebalance data streams requests.

| `ns-couchdb`
| Contains information related to starting up the CouchDB subsystem.

| `Projector`
| Contains information for the projector process that runs on each KV node and sends requested index data to the index nodes.

| `reports.log`
| Contains only progress report and crash reports for the Erlang processes.

| `ssl_proxy`
| 

| `crash-log.bin`
| Used to pass service crash reports from the babysitter to the `ns_server`.
For example, if the `ns_server` is available, any crash of the babysitter's child is passed directly to the special crash logger service within the `ns_server`.
If the logger service is not attached to the babysiter, then the babysitter saves that crash report to the disk and the `ns_server` can later obtain and log it even if the babysitter is restarted.

| `stats`
| Contains periodic reports of the core statistics.

| `tmpfail`
| For XDCR, the destination cluster is not able to eject items fast enough to make room for new mutations.
XDCR retries several times, without throwing errors, but after a fixed number of attempts the errors are shown to the user.
Nevertheless, if a user waits long enough, XDCR eventually retries and can replicate the remaining data.

| `views`
| Errors relating to the integration of the view system and the core server subsystem.

| `xdcr`
| Log messages related to starting up the cross datacenter replication subsystem.

| `xcdr_trace`
| Cross datacenter replication trace messages
|===

Some logs are automatically rotated after a certain fixed size.
For example, individual log files are automatically numbered with the number suffix incremented for each new log, and with a maximum of 20 files per log.
Individual log file sizes are limited to 10MB by default.

For other logs, when a log file reaches 40MB it will be rotated and compressed.
The file will keep 5 rotations (the current rotation plus four compressed rotations).
Here is an example list of log files:

----
-rw-rw---- 1 couchbase couchbase 12M Feb 2 16:15 couchdb.log 
			-rw-rw---- 1 couchbase couchbase 4.8M Feb 2 16:13 couchdb.log.1.gz 
			-rw-rw---- 1 couchbase couchbase 4.5M Jan 30 17:35 couchdb.log.2.gz 
			-rw-rw---- 1 couchbase couchbase 3.9M Jan 30 17:34 couchdb.log.3.gz 
			-rw-rw---- 1 couchbase couchbase 5.7M Jan 30 17:30 couchdb.log.4.gz
----

In this list, the oldest file has the largest number.

To provide custom rotation settings for each component, use the following :

----
{disk_sink_opts_disk_debug, 
			[{rotation, [{size, 10485760}, 
			{num_files, 10}]}]}.
----

This will rotate the debug.log at 10M and keep 10 copies of the log (the current log and 9 compressed logs).
