= Troubleshooting
:page-topic-type: concept

[abstract]
Troubleshooting lists most common errors, gives general tips, and explains system logs.

This section describes the most commonly encountered errors when using Couchbase Server and what you should do when you encounter them.
You will also learn some general tips to keep in mind when troubleshooting your cluster, the various log files you might want to look into when troubleshooting an issue, and how you can report an issue to the Couchbase support.

== Reporting issues to Couchbase

When reporting issues to Couchbase, add the following information to JIRA issues:

* Provide a description of your environment (for example, package installation, cluster_run, build number, operating system, and so on).
* Show all the steps necessary to reproduce the issue (if applicable).
* Show the full content of all the design documents.
* Describe how your documents are structured (for example, if they are all same structure or if they have different structures).
* If you generated the data with a tool, identify the tool name and all the parameters given to it (full command line).
* Show the queries you were performing (include all query parameters and the full URL).
For example, if you are using curl, use the verbose option `(-v`) and show the full output.
+
The following request uses curl with the `-v` option with test as the bucket, example as the design document, and Python (installed separately) as the tool used to format the output.
Replace node and bucket name in example as appropriate:
+
----
curl -v http://couchbase:8092/test/_design/example | python -m json.tool
----

* Repeat the query with different values for the stale parameter and show the output
* Attach logs from all nodes in the cluster
* Try all view related operations, including creating, updating, and deleting design documents from the command line.
The goal is to isolate UI problems from the view engine.
* If you suspect the indexer is stuck or blocked, use curl against the `_active_tasks` API to isolate UI issues from view-engine issues.
For example:
+
----
curl -s http://10.5.2.54:8092/_active_tasks
----
