= Override Credential Store Requirements
:description: pass:q[You can use this API to override the credential store's node-to-node encryption and encryption at rest requirements.]
:page-edition: Enterprise Edition
:page-topic-type: reference
:page-toclevels: 3

[abstract]
{description}

== Description

This API lets you view, override, and reset the credential store's security requirements: node-to-node encryption, and encryption at rest for configuration files.
To learn more about when you might need to do this, see xref:manage:manage-security/manage-credentials/override-credential-store-requirements.adoc[].

CAUTION: Overriding these requirements can expose authentication secrets such as bearer tokens, keys, and passwords.
Only override them in non-production environments such as testing or development.

== HTTP Methods

This API endpoint supports the following methods:

* <<#view-override>>
* <<#set-override>>
* <<#reset-override>>

[[view-override]]
== View the Current Override Settings

View the current override settings, and any warnings about credentials left unprotected by an overridden requirement.

.View the Current Settings
----
GET /settings/credentialStore
----

=== curl Syntax

[source,bash]
----
curl -u $USER:$PASSWORD -X GET \
     'http://{HOST}:{PORT}/settings/credentialStore'
----

.*Path Parameters*
:priv-link: view-privs
include::partial$user-pw-host-port-params.adoc[]

[[view-privs]]
=== Required Privileges

You must have at least 1 of the following roles:

* xref:learn:security/roles.adoc#full-admin[Full Admin]
* xref:learn:security/roles.adoc#security-admin[Security Admin]

=== Responses

`200 OK`::
Returns a JSON object containing the current override settings.
See <<#view-example>> for the schema of the output.

`403 Forbidden`::
Returned if the user does not have 1 of the roles listed in <<#view-privs>>.

[#view-example]
=== Examples

The following example views the current override settings, on a cluster where neither requirement is overridden:

[source,bash]
----
curl -u Administrator:password -X GET \
     'http://127.0.0.1:8091/settings/credentialStore' | jq
----

The JSON returned by this command shows both requirements enforced:

[source,json]
----
{
  "configEncryptionOverride": false,
  "n2nEncryptionOverride": false
}
----

If the credential store contains 1 or more credentials, and an overridden requirement leaves those credentials unprotected, the response also includes a `warnings` array:

[source,json]
----
{
  "configEncryptionOverride": false,
  "n2nEncryptionOverride": true,
  "warnings": [
    "Stored credentials risk being sent unencrypted unless node-to-node encryption is enabled on every node in the cluster"
  ]
}
----

NOTE: Couchbase Server only returns a warning for a requirement that's both overridden and currently unmet, and only when the credential store contains at least 1 credential.
Overriding a requirement while the credential store is empty does not produce a warning.

[[set-override]]
== Override the Requirements

Override 1 or both of the credential store's security requirements.

.Override the Requirements
----
PUT /settings/credentialStore
----

You must set both `configEncryptionOverride` and `n2nEncryptionOverride`, even if you only want to override 1 requirement.

=== curl Syntax

[source,bash]
----
curl -u $USER:$PASSWORD -X PUT \
     'http://{HOST}:{PORT}/settings/credentialStore' \
     -H 'Content-Type: application/json' \
     -d '{"configEncryptionOverride": <true|false>, "n2nEncryptionOverride": <true|false>}'
----

.*Path Parameters*
:priv-link: set-privs
include::partial$user-pw-host-port-params.adoc[]

.*Fields*

`configEncryptionOverride` (Boolean, required)::
Set to `true` to override the encryption at rest requirement for configuration files, or `false` to enforce it.

`n2nEncryptionOverride` (Boolean, required)::
Set to `true` to override the node-to-node encryption requirement, or `false` to enforce it.

NOTE: This endpoint requires a JSON request body.
It does not accept form-encoded parameters.

[[set-privs]]
=== Required Privileges

You must have at least 1 of the following roles:

* xref:learn:security/roles.adoc#full-admin[Full Admin]
* xref:learn:security/roles.adoc#security-admin[Security Admin]

=== Responses

`200 OK`::
Returns a JSON object containing the settings you set.
See <<#set-example>> for the schema of the output.

`400 Bad Request`::
Returned if you omit either field, or supply a non-Boolean value.

`403 Forbidden`::
Returned if the user does not have 1 of the roles listed in <<#set-privs>>.

[#set-example]
=== Examples

The following example overrides the node-to-node encryption requirement, while leaving the encryption at rest requirement enforced:

[source,bash]
----
curl -u Administrator:password -X PUT \
     'http://127.0.0.1:8091/settings/credentialStore' \
     -H 'Content-Type: application/json' \
     -d '{"configEncryptionOverride": false, "n2nEncryptionOverride": true}' | jq
----

The JSON returned by this command shows the settings you set:

[source,json]
----
{
  "configEncryptionOverride": false,
  "n2nEncryptionOverride": true
}
----

[[reset-override]]
== Reset the Requirements to Their Defaults

Remove any overrides and enforce both requirements again.

.Reset the Requirements
----
DELETE /settings/credentialStore
----

=== curl Syntax

[source,bash]
----
curl -u $USER:$PASSWORD -X DELETE \
     'http://{HOST}:{PORT}/settings/credentialStore'
----

.*Path Parameters*
:priv-link: reset-privs
include::partial$user-pw-host-port-params.adoc[]

[[reset-privs]]
=== Required Privileges

You must have at least 1 of the following roles:

* xref:learn:security/roles.adoc#full-admin[Full Admin]
* xref:learn:security/roles.adoc#security-admin[Security Admin]

=== Responses

`200 OK`::
Returned when Couchbase Server resets both requirements to their defaults.
This has the same effect as setting both `configEncryptionOverride` and `n2nEncryptionOverride` to `false`.
A successful call does not return any additional content.

`403 Forbidden`::
Returned if the user does not have 1 of the roles listed in <<#reset-privs>>.

=== Examples

The following example resets both requirements to their defaults:

[source,bash]
----
curl -u Administrator:password -X DELETE \
     'http://127.0.0.1:8091/settings/credentialStore'
----

== See Also

* xref:learn:security/credential-store.adoc[]
* xref:manage:manage-security/manage-credentials/override-credential-store-requirements.adoc[]
* xref:rest-api:security/credential-store/manage-credentials.adoc[]
