= Backup Service API
:description: pass:q[The Backup Service API allows full and incremental data-backups to be planned and scheduled; allows the scheduling of _merges_ of previously made backups; and allows existing backups to be archived.]
:page-topic-type: reference

[abstract]
{description}

== APIs in this Section

The Backup Service API provides endpoints categorized as follows: _Cluster_, _Configuration_, _Repository_, _Plan_, _Task_, and _Data_.
For a conceptual overview of the Backup Service, see xref:learn:services-and-indexes/services/backup-service.adoc[Backup Service].
For information on using Couchbase Web Console to configure and use the Backup Service, see xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc[Manage Backup and Restore].

All calls require the Full Admin role, and use port `8097`.
Each URI, in Couchbase Server Enterprise Edition Version 7.0, must be prefixed with `/api/v1`.
Note that for all cluster references, in Couchbase Server Enterprise Edition Version 7.0 and 7.1, only the host cluster is supported, and is referred to as `self`.

For a list of the methods and URIs covered in these pages, see the tables below.

include::partial$rest-backup-service-table.adoc[]
