= Backup Service API
:page-topic-type: reference

[abstract]
The Backup Service API allows full and incremental data-backups to be planned and scheduled; allows the scheduling of _merges_ of previously made backups; and allows existing backups to be archived.

== API Overview

The Backup Service API provides endpoints categorized as follows: _Cluster_, _Configuration_, _Repository_, _Plan_, _Task_, and _Data_.
The individual endpoints are listed by category, in the tables below.
Each table-entry provides a link to an associated reference page, where more detailed information, including curl examples, is provided.
For a conceptual overview of the Backup Service, see xref:learn:services-and-indexes/services/backup-service.adoc[Backup Service].
For information on using Couchbase Web Console to configure and use the Backup Service, see xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc[Manage Backup and Restore].

All calls listed below require the Full Admin role, and use port `8097`.
Each URI, in Couchbase Server Enterprise Edition Version 7.0, must be prefixed with `/api/v1`.
Note that for all cluster references, in Couchbase Server Enterprise Edition Version 7.0, only the host cluster is supported, and is referred to as `self`.

== Cluster

[cols="76,215,249"]
|===
| HTTP method | URI | Description

| GET
| `/cluster/self`
| Retrieves information on all active, archived, and imported repositories defined on a cluster.

See xref:rest-api:backup-get-cluster-info.adoc[Get Cluster Information].
|===

== Configuration

[cols="76,215,249"]
|===
| HTTP method | URI | Description

| GET
| `/config`
| Returns the rotation-configuration for the Backup Service.

See xref:rest-api:backup-manage-config.adoc[Manage Backup Configuration].

| POST
| `/config`
| Creates the rotation-configuration for the Backup Service.

See xref:rest-api:backup-manage-config.adoc[Manage Backup Configuration].

| PUT
| `/config`
| Edits the existing rotation-configuration for the Backup Service.

See xref:rest-api:backup-manage-config.adoc[Manage Backup Configuration].

|===

== Repository

[cols="76,215,249"]
|===
| HTTP method | URI | Description

| GET
| `/cluster/self/repository/active`
| Retrieves information on all active repositories, defined on a cluster.
Information includes repository names, file or cluster paths, and plan details.

See xref:rest-api:backup-get-repository-info.adoc[Get Information on Repositories].

| GET
| `/cluster/self/repository/active/<repository-id>`
| Retrieves information on a specific, active repository, defined on a cluster.
Information includes repository names, file or cluster paths, and plan details.

See xref:rest-api:backup-get-repository-info.adoc[Get Information on Repositories].

| GET
| `/cluster/self/repository/active/info`
| Retrieves information on all active repositories, defined on a cluster.
Information includes backup names and dates, buckets, items, and mutations.

See xref:rest-api:backup-get-backup-info.adoc[Get Information on Backups].

| POST
| `/cluster/self/repository/active/`
| Creates an active repository on the cluster, specifying an associated _plan_.

See xref:rest-api:backup-create-repository.adoc[Create a Repository].

| POST
| `/cluster/self/repository/<'archived'&#124;'imported'>/<repository-id>/restore`
| Restores data from a specified archived, or imported repository to the cluster.

See xref:rest-api:backup-restore-data.adoc[Restore Data].

| POST
| `/cluster/self/repository/import`
| Imports an existing repository into the Backup Service.

See xref:rest-api:backup-import-repository.adoc[Import a Repository].

| POST
| `/cluster/self/repository/<'active'&#124;'archived'&#124;'imported'>/<repository-id>/examine`
| Returns information on a specified document, within a specified scope and collection, within the specified active, archived, or imported repository.

See xref:rest-api:backup-examine-data.adoc[Examine Backed-Up Data].

| POST
| `/cluster/self/repository/active/<repository-id>/backup`
| Triggers an immediate backup of the cluster, to the specified repository; specifying whether the backup should be incremental or full.

See xref:rest-api:backup-trigger-backup.adoc[Perform an Immediate Backup].

| POST
| `/cluster/self/repository/active/<repository-id>/merge`
| Triggers an immediate merge of specified repositories; providing the start and end dates for the period of time within which backups are to be merged.

See xref:rest-api:backup-trigger-merge.adoc[Perform an Immediate Merge].

| POST
| `/cluster/self/repository/active/<repository-id>/pause`
| Triggers an immediate pause of the specified repository, so that all task-processing ceases.

See xref:rest-api:backup-get-task-info.adoc[Get Information on Tasks].

| POST
| `/cluster/self/repository/active/<repository-id>/resume`
| Triggers an immediate resumption of task-processing, on the specified, _paused_ repository.

See xref:rest-api:backup-get-task-info.adoc[Get Information on Tasks].

| POST
| `/cluster/self/repository/active/<repository-id>/archive`
| Archives the specified, active repository.

See xref:rest-api:backup-archive-a-repository.adoc[Archive a Repository].

| GET
| `/cluster/self/repository/<'archived'&#124;'imported'>`
| Returns information on all the cluster's archived and imported repositories.
Information includes repository names, file or cluster paths, and plan details.

See xref:rest-api:backup-inspect-archive-info.adoc[Get Information on Archived and Imported Repositories].

| GET
| `/cluster/self/repository/<'archived'&#124;'imported'>/<repository-id>`
| Returns information on a single archived or imported repository.
Information includes repository names, file or cluster paths, and plan details.

See xref:rest-api:backup-inspect-archive-info.adoc[Get Information on Archived and Imported Repositories].

| GET
| `/cluster/self/repository/<'archived'&#124;'imported'>/<repository-id>/info`
| Returns information on a single archived or imported repository.
Information includes backup names and dates, buckets, items, and mutations.

See xref:rest-api:backup-inspect-archive-info.adoc[Get Information on Archived and Imported Repositories].

| DELETE
| `/cluster/self/repository/<'archived'&#124;'imported'>/<repository-id>?remove_repository`
| Deletes an archived repository.

See xref:rest-api:backup-delete-repository.adoc[Delete a Repository].
|===

== Plan

[cols="76,215,249"]
|===
| HTTP method | URI | Description

| GET
| `/cluster/plan`
| Returns an array containing all plans defined on the cluster.

See xref:rest-api:backup-get-plan-info.adoc[Get Information on Plans].

| GET
| `/cluster/plan/<plan-id>`
| Returns a specific plan, defined on the cluster.

See xref:rest-api:backup-get-plan-info.adoc[Get Information on Plans].

| POST
| `/cluster/plan/<plan-id>`
| Creates a new plan on the cluster.

See xref:rest-api:backup-create-and-edit-plans.adoc[Create and Edit Plans].

| PUT
| `/cluster/plan/<plan-id>`
| Edits an existing plan, defined on the cluster.

See xref:rest-api:backup-create-and-edit-plans.adoc[Create and Edit Plans].

|===

== Task

[cols="76,215,249"]
|===
| HTTP method | URI | Description

| GET
| `/cluster/self/repository/active/<repository-id>/taskHistory`
| Returns an array, containing the history of all tasks performed for the specified repository.

See xref:rest-api:backup-manage-tasks.adoc[Get Information on Tasks].

| GET
| `/cluster/self/repository/active/<repository-id>/taskHistory?<task-subset-specification-string>`
| Returns an array, containing the history of a specific subset of tasks performed for the specified repository.

See xref:rest-api:backup-manage-tasks.adoc[Get Information on Tasks].

|===

== Data

[cols="76,215,249"]
|===
| HTTP method | URI | Description

| DELETE
| `/cluster/self/repository/active/<repository-id>/backups/<backup-id>`
| Deletes the specified backup from the specified active repository..

See xref:rest-api:backup-delete-backups.adoc[Delete Backups].
