= Backup Service API
:page-topic-type: reference

[abstract]
The Backup Service API allows full and incremental data-backups to be planned and scheduled; allows the scheduling of _merges_ of previously made backups; and allow existing backups to be archived.

== API Overview

The Backup Service API provides endpoints categorized as follows: _Cluster_, _Repository_, _Plan_, _Configuration_, _Task_, _Plan_, and _Data_.
The individual endpoints are listed by category, in the tables below.
Each table-entry provides a link to an associated reference page, where more detailed information, including curl examples, is provided.
For a conceptual overview of the Backup Service, see xref:learn:services-and-indexes/services/backup-service.adoc[Backup Service].
For information on using Couchbase Web Console to configure and use the Backup Service, see xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc[Manage Backup and Restore].

All calls require the Full Admin role, and use port `8097`.
Each URI must be prefixed with `/api/v1`.
Note that for all cluster references, in Couchbase Server Enterprise Edition Version 7.0, only the host cluster is supported, and is referred to as `self`.

== Cluster API

[cols="80,215,249"]
|===
| HTTP method | URI | Description

| GET
| `/cluster/self`
| Retrieves information on all active, archived, and imported repositories defined on a cluster.

See xref:rest-api:backup-rest-get-cluster-info.adoc[Get Cluster Information].
|===

== Repository API

[cols="80,215,249"]
|===
| HTTP method | URI | Description

| GET
| `/cluster/self/repository/active`
| Retrieves information on all active repositories, defined on a cluster.
Information includes repository names, file or cluster paths, and plan details.

See xref:rest-api:backup-rest-get-repository-info.adoc[Get Repository Information].

| GET
| `/cluster/self/repository/active/<id>`
| Retrieves information on a specific, active repository, defined on a cluster.
Information includes repository names, file or cluster paths, and plan details.

See xref:rest-api:backup-rest-get-repository-info.adoc[Get Repository Information].

| GET
| `/cluster/self/repository/active/info`
| Retrieves information on all active repositories, defined on a cluster.
Information includes backup names and dates, buckets, items, and mutations,

See xref:rest-api:backup-rest-get-repository-info.adoc[Get Repository Information].


|==
