= Get Information on Active Repositories

[abstract]
The Backup Service REST API allows information to be retrieved on currenntly defined, active repositories.

[#http-methods-and-uris]
== HTTP Methods and URIs

----
GET /cluster/self/repository/active

GET /cluster/self/repository/active/<active-repository-id>
----

[#description]
== Description

The `GET /cluster/self/repository/active` http method and URI return an array, each of whose members is an object containing information on a currently defined _active_ repository.
An active repository is one whose associated plan and its constituent tasks continue to be processed as scheduled (this _not_ being the case with an _archived_ or _imported_ repository).

The `GET /cluster/self/repository/active/<active-repository-id>` http method and URI return a single object, containing information on the currently defined, active repository whose name is specified by the `active-repository-id` path parameter.

[#curl-syntax]
== Curl Syntax

----
curl -X GET /cluster/self/repository/active \
-u <username>:<password>

curl -X GET /cluster/self/repository/active/<active-repository-id> \
-u <username>:<password>
----

The `active-repository-id` path parameter must be the name of a currently defined, active repository.

[#responses]
== Responses


[#examples]
== Examples


[#see-also]
== See Also
