= Changing the Master Password
:description: The master password can be changed, by means of the REST API.

[abstract]
{description}

[#http-methods-and-uris]
== HTTP Method and URI

----
POST /node/controller/changeMasterPassword
----

== Description

This command sets the master password.
The *Full Admin*, *Local User Security Admin*, or *External User Security Admin* role is required.

For a full description of system secrets and their management, see xref:manage:manage-security/manage-system-secrets.adoc[Manage System Secrets].

== Curl Syntax

----
curl -X POST http://127.0.0.1:8091/node/controller/changeMasterPassword
 -u Administrator:password
 -d newPassword=<new-password>
----

== Responses

Success returns `200 OK`.
Failure to authenticate due to incorrect credentials returns `401 Unauthorized`.
Attempt to authenticate with the wrong role returns `403 Forbidden`, and a message such as `{"message":"Forbidden. User needs the following permissions","permissions":["cluster.admin.security!write"]}`.
An incorrectly expressed URI fails with `404 Object Not Found`.

== Example

The following example changes the master password.

----
curl -v -X POST http://localhost:8091/node/controller/changeMasterPassword \
-u Administrator:password \
-d newPassword=o12m2Bb?ufh3*a
----

== See Also

For a full description of system secrets and their management, see xref:manage:manage-security/manage-system-secrets.adoc[Manage System Secrets].
