= Creating and Editing a Collection
:description: pass:q[Collections can be _created_ by means of the REST API.]
:page-topic-type: reference

[abstract]
{description}

== Description

Collections are _created_ by means of the `POST /pools/default/buckets/_<bucket_name>_/scopes/_<scope_name>_/collections` HTTP method and URI.
Collections are _edited_ by means of the `PATCH /pools/default/buckets/_<bucket_name>_/scopes/_<scope_name>_/collections/_<collection_name>_` HTTP method and URI.

== HTTP Methods and URIs

----
POST /pools/default/buckets/<bucket_name>/scopes/<scope_name>/collections

PATCH /pools/default/buckets/\
    <bucket_name>/scopes/<scope_name>/collections/<collection_name>
----

== Curl Syntax

The curl syntax is as follows:

----
curl -X POST -u [admin]:[password]
  http://<hostname-or-ip>:8091/pools/default/buckets/\
    <bucket_name>/scopes/<scope_name>/collections
  -d name=<collection-name>
  -d maxTTL=[integer]
  -d history=[ true | false ]

curl -X PATCH -u [admin]:[password]
  http://<hostname-or-ip>:8091/pools/default/buckets/\
    <bucket_name>/scopes/<scope_name>/collections/<collection_name>
  -d history=[ true | false ]
----

The `<bucket_name>` path-parameter specifies the name of the bucket within which the new collection is to reside.
The `<scope_name>` path-parameter provides the name of the scope within which the new collection is to reside.
The `name` parameter specifies the name of a collection to be created.
Used with the `PATCH` method, the `<collection_name>` path-parameter specifies the name of an existing collection to be edited.
Optionally, the `maxTTL` flag can be used to specify an expiration value for the collection: the specified value must be an integer representing seconds; with the maximum permissible value being 2147483648 (or 68.096 years).
The default value for `maxTTL` is `0`, which disables TTL for the collection.
For more information, see xref:learn:data/expiration.adoc[Expiration].

The value of the optional `history` parameter can be `true` (the default) or `false`.
This establishes whether _deduplication_ should be applied to the collection's change history.
If the value is `true`, deduplication is _not_ applied; and if the value is `false`, deduplication _is_ applied.
This parameter is ignored unless a change history is being created: which is to say, the value of `storageBackend` is specified as `magma`, the value of `historyRetentionCollectionDefault` is specified as `true`, and a positive value is specified for either `historyRetentionSeconds` or `historyRetentionBytes`, or for both (see xref:rest-api:rest-bucket-create.adoc[Creating and Editing Buckets]).
Note that `history` is the only parameter that can be edited (by means of the `PATCH` method), subsequent to the collection's creation.

== Responses

Success returns `200 OK`, for each call.
Failure to authenticate gives `401 Unauthorized`.
A malformed URI fails with `404 Object Not Found`.
If the collection-name is improperly specified, a notification such as `"name":"Length must be in range from 1 to 30"` or `"name":"Can only contain characters A-Z, a-z, 0-9 and the following symbols _ - %"` is displayed.
See xref:learn:data/scopes-and-collections.adoc#naming-for-scopes-and-collections[Naming for Scopes and Collections], for an account of naming conventions.

== Examples

The following call creates a collection named `my_collection_in_my_scope`, within an existing scope named `my_scope`, and specifies an expiration value in seconds that is equivalent to two years.
It also specifies that deduplication should be applied to the change history for the collection.

----
curl -X POST -v -u Administrator:password \
http://10.143.210.101:8091/pools/default/buckets/\
testBucket/scopes/my_scope/collections \
-d name=my_collection_in_my_scope \
-d maxTTL=63113904 \
-d history=false
----

If successful, the call returns a `uid`, such as the following:

----
{"uid":18}
----

The following call modifies the definition of the collection `my_collection_in_my_scope`; specifying that deduplication should not be applied to the change history for the collection:

----
curl -X PATCH http://localhost:8091/pools/default/buckets/testBucket/scopes/my_scope/collections/my_collection_in_my_scope \
-u Administrator:password \
-d history=true
----

== See Also

An overview of scopes and collections is provided in xref:learn:data/scopes-and-collections.adoc[Scopes and Collections].
Step-by-step procedures for management are provided in xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc[Manage Scopes and Collections].
See also the CLI reference page for the xref:cli:cbcli/couchbase-cli-collection-manage.adoc[collection-manage] command.

For information on establishing change history defaults for collections within a bucket, see xref:rest-api:rest-bucket-create.adoc[Creating and Editing a Bucket].
