= Configure File-Based Data Rebalance
:description: pass:q[You can turn Data Service File-Based Rebalance (FBR) on or off using the `/internalSettings` REST API endpoint.]
:page-edition: Enterprise Edition
:page-topic-type: reference
:page-toclevels: 3

[abstract]
{description}

== Description

The file-based rebalance option for the Data Service directly copies vBucket data files between nodes during rebalance.
It's enabled by default. 
It usually improves rebalance speed compared to DCP-based backfill method.

See xref:learn:clusters-and-availability/rebalance.adoc#file-based-rebalance[File-Based Rebalance] for more information about file-based rebalance and how it compares to DCP-based rebalance. 



== HTTP Methods 

This API endpoint supports the following methods:

* <<get-settings>>
* <<set-settings>>

[#get-settings]
== Determine if FBR is Enabled 

You can get the current status of FBT by posting a GET request to the `/internalSettings` endpoint.
The FBR settings are part of the internal settings, so this API returns all internal settings.

.List Internal Settings
----
GET /internalSettings
----

=== curl Syntax

[source,bash]
----
curl -u ${USER}:${PASSWORD} -X GET \
        http[s]://${HOST}:${PORT}/internalSettings 
----

.Path Parameters
:required-privileges: get-privs
include::partial$user_pwd_host_port_params.adoc[]


[#get-privs]
=== Required Privileges

You must have at least 1 of the following roles to get the FBR settings:

* xref:learn:security/roles.adoc#full-admin[Full Admin]
* xref:learn:security/roles.adoc#cluster-admin[Cluster Admin]
* xref:learn:security/roles.adoc#ro-security-admin[Read-Only Security Admin]
* xref:learn:security/roles.adoc#security-admin[Security Admin]
* xref:learn:security/roles.adoc#local-user-security-admin[Local User Admin]

=== Responses

`200 OK`::
Returns the internal settings. 
See examples for an example of the settings.

`401 Unauthorized`::
Returned when authentication fails, such as when the password is incorrect.

`403 Forbidden`::
Returned if you do not have 1 of the roles listed in <<get-privs>>.

[#get-settings-example]
=== Examples

The following example gets the current value of the FBR setting.
It filters the internal settings using the `jq` command to show only the setting that controls whether FBR is enabled.

[source,bash]
----
curl -s -u $USERNAME:$PASSWORD \
     -X GET http://node1.example.com:8091///internalSettings \
     | jq '{dataServiceFileBasedRebalanceEnabled}'
----

Running the example returns a JSON object containing the current FBR settings, such as the following:

[source,json]
----
{
  "dataServiceFileBasedRebalanceEnabled": true,
}
----

The key returned by the previous example controls whether FBR is enabled.
When `true`, eligible vBucket moves use FBR; when `false`, all vBucket moves use DCP.

[#set-settings]
== Turn FBR On or Off

You can turn FBR on or off by making a `POST` request to `dataServiceFileBasedRebalanceEnabled`.


.Change FBR Settings
----
POST /internalSettings
----

=== curl Syntax

[source,bash]
----
curl -sS -u ${USER}:${PASSWORD} \
  -X POST http[s]://${host}:${port}/internalSettings \
  [-d dataServiceFileBasedRebalanceEnabled={true|false}] \
----

=== Path Parameters
:priv-link: settings-privs
include::partial$user-pw-host-port-params.adoc[]

=== Parameters

`dataServiceFileBasedRebalanceEnabled`::
Set to `true` (the default) to allow the Data Service to use FBR when rebalancing data in eligible vBuckets.
Set to `false` to force the Data Service to use DCP when rebalancing data.

+
NOTE: This setting can be overridden on a per-bucket basis using the bucket's  `dataServiceRebalanceType` setting.
See xref:manage:manage-buckets/edit-bucket.adoc#bucket-rebalance-type[Bucket-Level Rebalance Type] for more information.

[#settings-privs]
=== Required Privileges

You must have 1 of the following roles to change the FBR settings:

* xref:learn:security/roles.adoc#full-admin[Full Admin]
* xref:learn:security/roles.adoc#cluster-admin[Cluster Admin]

=== Responses

`200 OK`::
Updating the value or values succeeded.

`400 Bad Request`::
Returned if you specify an invalid value for .

+ 
Also returns a JSON object that describes the error, such as the following:

+
[source,json]
----
{
  "errors": [
    "dataServiceFileBasedRebalanceEnabled - Accepted values are 'true' and 'false'."
  ]
}

----

`401 Unauthorized`::
Returned when authentication fails, such as when the password is incorrect.

`403 Forbidden`::
Returned if you do not have the proper roles to call this API.
See <<#settings-privs>>.


[#settings-examples]
=== Examples

[#disable-fbr-example]
.Disable FBR

The following example prevents the Data Service from using FBR cluster-wide:

[source,bash]
----
curl -u $USERNAME:$PASSWORD \
     -X POST http://node1.example.com:8091/internalSettings \
     -d dataServiceFileBasedRebalanceEnabled=false 
----

=== See Also

* xref:learn:clusters-and-availability/rebalance.adoc#file-based-rebalance[File-Based Rebalance (FBR)].
* xref:manage:manage-settings/general-settings.adoc#rebalance-settings[Rebalance Settings].
* xref:manage:manage-buckets/edit-bucket.adoc#bucket-rebalance-type[Bucket-Level Rebalance Type].