= Verifying Shard Affinity Metadata
:description: The Index service REST API provides configuration options for the Index service.
:page-topic-type: reference

[abstract]
{description}

== Description

This endpoint returns the status of the index service, including shard affinity metadata.

== HTTP Method and URI

[source,http]
----
GET http://<index_node>:9102/getIndexStatus?getAll=true
----

== Response Codes

[cols="1,4"]
|===
| Response Code | Description

| 200
| Success.

| 401
| Unauthorized.
|===

== Sample Curl Command

The following example retrieves the index service status, including shard affinity metadata.

[source#example-curl,bash]
----
curl -X GET http://<index_node>:9102/getIndexStatus?getAll=true /
-u Administrator:password
----

== Sample Response

If the call is successful, it returns a `200` response code along with a JSON body similar to the following:


[source,json]
----
{


}
----

In the response, an `alternateShardIds` field is associated with each index.
The outcome is one of the following:

* If `alternateShardIds` contains entries for all partitions, the index has shard affinity.
* If `alternateShardIds` is empty or missing, the index does not have shard affinity.

== See Also

* For more information about Index Rebalance and Shard Affinity metadata, see xref:learn/clusters-and-availability/rebalance-and-index-service.adoc[Index Rebalance].