= Rebalancing Nodes
:page-topic-type: reference

[abstract]
Nodes are rebalanced with the `POST /controller/rebalance` HTTP method and URI.

[#rest-cluster-rebalance-description]
== Description

When one or more nodes have been brought into a cluster, or have been taken out of a cluster, _rebalance_ redistributes data and indexes among available nodes.
The _cluster map_ is correspondingly updated and distributed to clients.
The process occurs while the cluster continues to service requests for data.

The following parameters are used.

* `knownNodes`.
Must always be specified.
Its value is a list containing all nodes that are in the cluster at the start of the rebalance process.

* `ejectedNodes`.
Must only be specified when one or more nodes are to be ejected from the cluster by the rebalance process.
Its value is a list containing all nodes to be ejected.

Therefore, node-list specified by `ejectedNodes` is a subset of that specified by `knownNodes`.
If either value contains an unknown node, or if a node currently in the cluster is omitted from the value of `knownNodes`, the following error is returned:

----
{"mismatch":1}
----

If `knownNodes` is not specified and `ejectNodes` _is_ specified, the following error is returned:

----
{"empty_known_nodes":1}
----

=== HTTP method and URI

----
POST /controller/rebalance
----

=== Syntax

----
curl -v -X POST -u [admin]:[password]
  http://[localhost]:8091/controller/rebalance
  [-d ejectedNodes | -d knownNodes]
----

== Examples

The following examples demonstrate how to determine which nodes are currently in the cluster; how to rebalance, such that a node is ejected; how to return status on the ongoing rebalance; and how to re-add the ejected node to the cluster.


=== Return Cluster Nodes

To determine the nodes currently in the cluster, use the `GET /pools/default` HTTP method and URI.
In this examine, the (extensive) output is piped to the `jq` tool for formatting, and the lines featuring the `hostname` filtered, to ensure readabiliy.

----
curl  -u Administrator:password -X GET \
http://10.143.190.101:8091/pools/default | jq '.' | grep hostname
----

The HTTP request contains the following:

----
GET /pools/default HTTP/1.1
Host: 10.143.190.101:8091
Authorization: Basic QWRtaW5pc3RyYXRvcjpwYXNzd29yZA==
Accept: */*
----

The output contains the following lines, which specify all nodes in the cluster:

----
"hostname": "10.143.190.101:8091",
"hostname": "10.143.190.102:8091",
"hostname": "10.143.190.103:8091",
----

=== Rebalance Following Hard Failover

The _Hard Failover_ of a node results in that node continuing to be a member of the cluster, but being unable to serve data.
Since its active vBuckets are unavailable, corresponding replica vBuckets are promoted to active status on the still-available nodes.
This means that data is still being served, but is imbalanced across the cluster.
This requires rebalance.

Specify all cluster-nodes in the `knownNodes` parameter, including the one or ones that have been failed-over hard:

----
curl  -u Administrator:password -v -X POST \
http://10.143.190.101:8091/controller/rebalance \
-d 'knownNodes=ns_1%4010.143.190.101%2Cns_1%4010.143.190.102%2Cns_1%4010.143.190.103'
----

The HTTP request contains the following:

----
POST /controller/rebalance HTTP/1.1
Host: 10.143.190.101:8091
Authorization: Basic QWRtaW5pc3RyYXRvcjpwYXNzd29yZA==
User-Agent: curl/7.43.0
Accept: */*
Content-Length: 115
Content-Type: application/x-www-form-urlencoded
----

No object is returned.
The failed-over node has been removed, and the data is now distributed evenly across the surviving nodes.
This is confirmed by again examining the current cluster nodes:

----
curl  -u Administrator:password -X GET \
http://10.143.190.101:8091/pools/default | jq '.' | grep hostname
----

The output indicates which nodes are still in the cluster:

----
"hostname": "10.143.190.101:8091",
"hostname": "10.143.190.102:8091",
----

=== Add a Node to a Cluster, then Rebalance

Adding a node to a cluster is a two-step process.

. The `POST /controller/addNode` HTTP method and URI are used to add the node.
This allows service-deployment for the node to be specified.
A placeholder username and password can be specified, when adding an unprovisioned node.

. The `POST /controller/rebalance` HTTP method and URI are used to rebalance the added node into the cluster.
Include the new node in the `knownNodes` node-list.

For example, the following command adds node `10.143.1990.103` to the cluster from which it was removed, and deploys the Data Service to it:

----
curl -u Administrator:password -X POST \
10.142.181.101:8091/controller/addNode \
-d 'hostname=10.143.190.103&user=someName&password=somePassword&services=kv'
----

The HTTP request contains the following:

----
POST /controller/addNode HTTP/1.1
Host: 10.142.181.101:8091
Authorization: Basic QWRtaW5pc3RyYXRvcjpwYXNzd29yZA==
User-Agent: curl/7.43.0
Accept: */*
Content-Length: 71
Content-Type: application/x-www-form-urlencoded
----

If successful, this returns the following output, indicating that the node is now recognized as a member of the cluster:

----
{"otpNode":"ns_1@10.143.190.103"}
----

Next, the added node is rebalanced into the cluster.
This will allow it to take its share of the data-distribution.

----
curl  -u Administrator:password -v -X POST \
http://10.143.190.101:8091/controller/rebalance \
-d 'knownNodes=ns_1%4010.143.190.101%2Cns_1%4010.143.190.102%2Cns_1%4010.143.190.103'
----

No object is returned.
The cluster is now rebalanced.
At the conclusion, the cluster can again be checked for its current membership:

----
curl  -u Administrator:password -X GET \
http://10.143.190.101:8091/pools/default | jq '.' | grep hostname
----

The output now includes the following:

----
"hostname": "10.143.190.101:8091",
"hostname": "10.143.190.102:8091",
"hostname": "10.143.190.103:8091",
----

=== Eject a Node

To eject a node, use the `POST /controller/rebalance` HTTP method and URI.
Specify the entire current node-list for the cluster as the value of the `knownNodes` parameter.
Specify the list of nodes to be ejected as the value of the `ejectedNodes` parameter.

For example, the following command ejects node `10.143.190.103` from the cluster:

----
curl  -u Administrator:password -v -X POST \
http://10.143.190.101:8091/controller/rebalance \
-d 'ejectedNodes=ns_1%4010.143.190.103' \
-d 'knownNodes=ns_1%4010.143.190.101%2Cns_1%4010.143.190.102%2Cns_1%4010.143.190.103'
----

No object is returned.
The response code is `200 (OK)`, on success.
At the conclusion, the cluster can again be checked for its current membership:

----
curl  -u Administrator:password -X GET \
http://10.143.190.101:8091/pools/default | jq '.' | grep hostname
----

The output now includes the following:

----
"hostname": "10.143.190.101:8091",
"hostname": "10.143.190.102:8091",
----


[#rest-cluster-rebalance-adjustduringcompaction]
== Adjusting Rebalance During Compaction

=== Description

If a rebalance is performed while a node is undergoing index compaction, rebalance delays may be experienced.
The parameter, `rebalanceMovesBeforeCompaction`, is used to improve rebalance performance.
If this selection is made, index compaction performance is reduced, which can result in larger index file size.

This setting is established with the `POST /internalSettings` endpoint.
By default, this setting is 64, which specifies the number of vBuckets moved per node until all vBucket movement pauses.
After this pause, the system triggers index compaction.
Index compaction is not performed while vBuckets are being moved: therefore, if a larger value is specified, the server spends less time compacting the index.
This results in larger index files, which take up more disk space.

=== HTTP method and URI

----
POST /internalSettings rebalanceMovesBeforeCompaction
----

=== Syntax

Curl request syntax:

----
curl -X POST -u admin:password 'http://[localhost]:8091/internalSettings'
    -d rebalanceMovesBeforeCompaction=[value]
----

=== Example

Curl request example:

----
curl -X POST -u Administrator:password 'http://10.5.2.54:8091/internalSettings' \
    -d 'rebalanceMovesBeforeCompaction=256'
----
