= Retrieving Auto-Failover Settings
:description: pass:q[Use the  `/settings/autoFailover` endpoint to get the current auto-failover settings.]
:page-topic-type: reference

[abstract]
{description}

== HTTP Method and URI

[source,bourne]
----
GET /settings/autoFailover
----

== Description

The `GET /settings/autoFailover` HTTP method and URI retrieve auto-failover settings for the cluster.

Auto-failover settings are global applying to all nodes in the cluster.


== Curl Syntax

[source,bourne]
----
curl -X GET http://<ip-address-or-hostname>:8091/settings/autoFailover \
     -u <username>:<password>
----

== Required Permissions

You must have one of the following roles to be able to read the auto-failover settings: 

* xref:learn:security/roles.adoc#backup-full-admin[Backup Full Admin]
* xref:learn:security/roles.adoc#bucket-admin[Bucket Admin]
* xref:learn:security/roles.adoc#cluster-admin[Cluster Admin]
* xref:learn:security/roles.adoc#eventing-full-admin[Eventing Full Admin]
* xref:learn:security/roles.adoc#external-user-security-admin[External User Admin]
* xref:learn:security/roles.adoc#full-admin[Full Admin]
* xref:learn:security/roles.adoc#local-user-security-admin[Local User Admin]
* xref:learn:security/roles.adoc#read-only-admin[Read-Only Admin]
* xref:learn:security/roles.adoc#security-admin[Security Admin]
* xref:learn:security/roles.adoc#views-admin[Views Admin]


== Responses

200 OK::
The call was successful. 
Also returns an object containing the current state of the auto-failover settings.
See <<#example>> for an example of the response.

401 Unauthorized::
The user credentials supplied with the call do not have the correct permissions to read the auto-failover settings.

404 Not Found::
The URL was incorrect.

[#example]
== Example

The following example returns the auto-failover settings for the cluster.
It pipes the output through the https://stedolan.github.io/jq[jq^] command to improve readability.

[source,console]
----
curl -X GET http://localhost:8091/settings/autoFailover \
     -u Administrator:password | jq '.'
----

If successful, execution returns the auto-failover settings for the cluster.
For example:

[source,json]
----
{
  "enabled": true,
  "timeout": 120,
  "count": 0,
  "failoverOnDataDiskIssues": {
    "enabled": false,
    "timePeriod": 120
  },
  "maxCount": 1,
  "canAbortRebalance": true,
  "failoverPreserveDurabilityMajority": false,
  "failoverOnDataDiskNonResponsiveness": {
    "enabled": false,
    "timePeriod": 120
  },
  "allowFailoverEphemeralNoReplicas": false
}
----

// Note: avoiding mention of disableMaxCount here intentionally -- gg 7-22-2025

The keys in the object returned in the example are:

* `enabled`
Whether automatic failover is on (a value of `true`) or off (`false`).

* `timeout`
The number of seconds Couchbase Server waits after a node has become unavailable before it performs an automatic failover.
This value can be between 5 and 3600.
The default value is 120.

* `count`.
The number of nodes that Couchbase Server has auto-failed over.
COucbase Server resets this value to zero either when the cluster rebalances to remove or rejoin the failed nodes, or when an administrator manually resets the count (see xref:rest-api:rest-cluster-autofailover-reset.adoc[]). 
The parameter's default value is 0.
If number of failed-over nodes reaches the maximum count set by `maxCount`, Couchbase Server refuses to auto-failover more nodes until you reset the count or resolve the auto-failovers with a recovery and rebalance.

* `failoverOnDataDiskIssues`.
This object contains two keys:

** `enabled` indicates whether auto-failover can occur when a disk has been unresponsive, and which can be `true` or `false` (the default).

** `timePeriod`, which indicates the administrator-specified time-period, in seconds, after which auto-failover is triggered, when a disk is unresponsive.
The value is an integer between 5 and 3600.

* `maxCount`.
The maximum number of nodes that can be auto-failed over at the same time.
When the count of auto-failed over nodes reaches this value, Couchbase Server does not trigger additional auto-failovers.
You must either resolve the auto-failovers through rebalancing the cluster to remove or recover the failed-over nodes or reset the count of failed over nodes.
The default value is 1.

* `canAbortRebalance`
Whether or not Couchbase Server can auto-failover a node while a rebalance is taking place.
This feature is only available in Couchbase Server Enterprise Edition.
The value can be either `true` (the default) or `false`.

* `failoverPreserveDurabilityMajority`
Indicates whether Couchbase Server refuses to auto-failover a node if doing so could result in the loss of durably written data. 

* `failoverOnDataDiskNonResponsiveness`
This object contains two keys that control auto-failover when a data disk is non-responsive:
+
--
** `enabled` indicates whether Couchbase Server initiates an  auto-failover on a node when when its data disk has failed to complete an operation in the period set by `timePeriod`.
This value can be `true`, which enables the auto-failover,  or teh default `false` which does not trigger a failover due to disk unresponsiveness.

** `timePeriod` 
Indicates amount of time a data disk on a node has to be unresponsive before Couchbase Server can trigger an auto-failover.
This value defaults to 120.
--
+
For more information about these values, see xref:learn:clusters-and-availability/automatic-failover.adoc#failover-on-data-disk-non-responsiveness[Failover on Data Disk Non-Responsiveness].

* `allowFailoverEphemeralNoReplicas` 
Indicates whether Couchbase Server can auto-failover a node that contains vBuckets for an unreplicated ephemeral bucket.
This value can be `true`, which allows auto-failover of such nodes, or the default `false` which prevents auto-failover of such nodes.

+
For more information about this value, see xref:learn:clusters-and-availability/automatic-failover.adoc#ephemeral-buckets-with-no-replicas[Auto-failover for Ephemeral Buckets with No Replicas].

== See Also

* For information about setting auto-failover parameters with the REST API, see xref:rest-api:rest-cluster-autofailover-enable.adoc[Enabling and Disabling Auto-Failover].

* The Couchbase Server command line tool xref:cli:cbcli/couchbase-cli-setting-autofailover.adoc[setting-autofailover] lets you manage auto-failover.

* For information about managing auto-failover with Couchbase Server Web Console, see xref:manage:manage-settings/general-settings.adoc#node-availability[Node Availability].

* For information about auto-failover see xref:learn:clusters-and-availability/automatic-failover.adoc[].
