= Identifying the Target in Replication
:description: pass:q[]

[abstract]
{description}

== HTTP Method and URI

----
GET /xdcr/sourceClusters

POST /xdcr/internalSettings
----

== Description

When on a current cluster, XDCR lets you:

* Retrieve the list of remote clusters that replicate to the current cluster.
If the system finds a list of replicating source clusters, it makes the current cluster the target cluster.

* Inspect the incoming XDCR replication streams on current cluster from each remote cluster.
It makes the current cluster the target cluster and remote cluster the source cluster.

Being on the target cluster, you can query incoming replications and relevant heartbeat information.

=== List the Source Clusters Replicating to the Target Cluster

Returns information about all source clusters that have a remote cluster reference pointing to the current cluster (target cluster). For each source cluster, the API returns replication specifications, current settings, source nodes, and heartbeat status.

==== Curl Syntax

----
curl -X GET -u <user-name>:<password> http://<ip-address-or-domain-name>:8091/xdcr/sourceClusters | jq
[
  {
    "SourceClusterNodes": [
      "http://<ip-address-or-domain-name-or-node-name>"
    ],
    "SourceClusterReplSpecs": "<list-of-replication-specifications-from-source-cluster-to-this-target>",
    "SourceClusterUUID": "<source-cluster-UUID>",
    "SourceClusterName": “<source-cluster-name>”,
    "SourceClusterHBReceiveTime": "<time-of-last-received-heartbeat>",
    "SourceClusterHBExpiryTime": "<heartbeat-expiry-time>"
  }
]





----
curl -X GET -u <user-name>:<password> http://<ip-address-or-domain-name>:8091/xdcr/sourceClusters | jq
[
  {
    "SourceClusterNodes": [
      "127.0.0.1:9002"
    ],
    "SourceClusterReplSpecs": null,
    "SourceClusterUUID": "d4b15b1069e4aaac1d6d0cb7d15b1dde",
    "SourceClusterName": “m1”,
    "SourceClusterHBReceiveTime": "2024-10-24T20:52:21.902848+05:30",
    "SourceClusterHBExpiryTime": "2024-10-24T21:02:21.902848+05:30"
  }
]



configure the Target Awareness feature on their Source & Target clusters


curl -X POST -u <user-name>:<password> http://<ip-address-or-domain-name>:8091/xdcr/internalSettings | jq
-d SrcHeartbeatEnabled=[ true|false ]
-d SrcHeartbeatIgnoreIncoming=[ false|true ]
-d SrcHeartbeatMinInterval=<seconds>
-d SrcHeartbeatMaxIntervalFactor=<minutes>
----




curl -X POST -u Administrator:pw http://127.0.0.1:9000/xdcr/internalSettings | jq
-d SrcHeartbeatEnabled=[ true|false ]
-d SrcHeartbeatIgnoreIncoming=[ false|true ]
-d SrcHeartbeatMinInterval=[ 60 seconds]
-d SrcHeartbeatMaxIntervalFactor=[ 5 minutes ]
----

In the `POST` statement, the `name` must be the name assigned locally to the target cluster.
In the `GET` statement, the `taskID` specified as the query parameter is one previously returned from a successful `POST`.

[#responses]
== Responses
