= Changing Bucket Memory Quota
:page-type: reference

[abstract]
To increase or decrease bucket memory quota, use the `POST /pools/default/buckets/newBucket` HTTP method and URI and the `ramQuotaMB` option.

== Description

A bucket’s ramQuotaMB can be increased and decreased from its current level.
However, while increasing will do no harm, decreasing should be done with proper sizing.
Decreasing the bucket’s ramQuotaMB lowers the watermark, and some items may be unexpectedly ejected if the ramQuotaMB is set too low.

NOTE: There are some known issues with changing the ramQuotaMB for memcached bucket types.

IMPORTANT: When changing the active bucket configuration, specify the existing configuration parameters and the changed authentication parameters.

== Syntax

Curl request syntax:

----
curl -X POST -u [admin]:[password]
  -d ramQuotaMB=[value] -d authType=[none | sasl]
  -d proxyPort=[port]
  http://[localhost]:8091/pools/default/buckets/[bucket-name]
----

== Example

Curl request example:

----
curl -X POST -u Administrator:password \
  -d 'ramQuotaMB=130' \
  -d 'authType=none' \
  -d 'proxyPort=11215' \
  http://10.5.2.117:8091/pools/default/buckets/newBucket
----

== Response

A 202 response indicates that the quota will be changed asynchronously throughout the servers in the cluster.

----
HTTP/1.1 202 OK
Server: Couchbase Server 1.6.0
Pragma: no-cache
Date: Wed, 29 Sep 2010 20:01:37 GMT
Content-Length: 0
Cache-Control: no-cache no-store max-age=0
----

If the RAM quota is too low, an error and usage summary is returned:

----
{
    "errors": {
        "ramQuotaMB": "RAM quota cannot be less than 100 MB"
    },
    "summaries": {
        "hddSummary": {
            "free": 46214973056,
            "otherBuckets": 16839602,
            "otherData": 10095646158,
            "thisUsed": 26456826,
            "total": 56327458816
        },
        "ramSummary": {
            "free": 242221056,
            "nodesCount": 1,
            "otherBuckets": 268435456,
            "perNodeMegs": 25,
            "thisAlloc": 26214400,
            "thisUsed": 33911144,
            "total": 536870912
        }
    }
}
----

== Response codes

----
202 OK
----
