= Getting Multiple Statistics

[abstract]
The REST API allows individual cluster-statistics to be retrieved by a single call, from one or more nodes.

[#http-methods-and-uris]
== HTTP Method and URI

----
POST /pools/default/stats/range
----


[#description]
== Description

This method and URI allows multiple cluster-statistics to be retrieved, based on the specification of metrics, and functions that determine the nature of the statistics to be derived from the metrics.
Metrics, functions, and other parameters are expressed as an array of JSON objects, which is provided as data accompanying the call..


[#curl-syntax]
== Curl Syntax

----
curl -X POST /pools/default/stats/range
 -d [<data>]
----

Each `data` object within the array can contain the following parameters:

----
{
  "metric": [
      [ <metric-specification> ],
      "applyFunctions": [ <function> ],
      "nodes": [ <node> ],
      "aggregationFunction": <function>,
      "start": <start_timestamp>,
      "end":  <end_timestmamp>,
      "step": <step>,
      "timeout": <timeout>,
      "alignTimestamps": true | false
  ]
}
----

The parameters are as follows:

* One or more `metric-specification` objects must be provided as an array.
Each object takes the following form:

----
{
  "label": <label_name>,
  "value": <label_val>,
  "operator": "=" | "!=" | "=~" | "~="
  }
----

The value of the key `label`, `label_name`, must be a string that specifies how the metric is identified: typically, this value is `"name"`.
The value of the key `value`, `label_val`, must be a string that is the actual name used to identify the metric: for example, `"sys_cpu_utilization_rate"`.
The value of the key `"operator"` must be 


[#responses]
== Responses


[#examples]
== Examples


[#see-also]
== See Also
