= Configuring saslauthd
:description: pass:q[The Couchbase REST API supports enablement of `saslauthd` for the cluster; and the addition of administrator and read-only administrator users to the cluster.]
:page-topic-type: reference

[abstract]
{description}

== HTTP Methods and URIs

----
POST /settings/saslauthdAuth

GET /settings/saslauthdAuth
----

== Description

The `POST` method enables _saslauthd_ for the cluster, and establishes _administrators_ and/or _read-only administrators_ for saslauthd.
Note that appropriate installation and preparation must have occurred, for the `POST` method to succeed (see xref:manage:manage-security/configure-saslauthd.adoc[Configure saslauthd]).

The `GET` method returns the current saslauthd settings for the cluster.

The Full Admin, Cluster Admin, or External Security Admin role is required for each method.

== Curl Syntax

----
 curl -X POST -u <administrator>:<password>
    http://<ip-address-or-hostname>:8091/settings/saslauthdAuth
    -d enabled=< 1 | 0 >
    -d admins=[<admin-name>]
    -d roAdmins=[<admin-name>]

curl -X GET -u <administrator>:<password>
   http://<ip-address-or-hostname>:8091/settings/saslauthdAuth
----

The `enabled` parameter is a required parameter, whose value determines whether saslauthd is enabled or disabled on the cluster: if the value is `1`, SASL is enabled.

The values of the optional `admins` and the `roAdmins` parameters can in each case be a comma-separated list of SASL users, who are to be given administrator or read-only administrator privileges on the cluster.
If an empty list is specified, no SASL users will have the privileges associated with the parameter.

Note that use of the `POST` method is not incremental: each specified list explicitly defines the new list of administrators and privileges that will exist from the point of execution &¢8212; administrators who previously had privileges, but are subsequently omitted from the list, _lose_ their former privileges.

== Responses

Successful use of GET returns `200 OK`, and a JSON object containing three key-value pairs, which respectively indicate whether saslauthd is enabled, the current list of administrators, and the current list of read-only administrators.

Successful use of POST returns `200 OK`, and a JSON object containing three key-value pairs, which respectively indicate whether saslauthd is enabled, the current list of administrators, and the current list of read-only administrators.

A malformed URI returns `404 Object Not Found`.

Failure to authenticate returns `401 Unauthorized`.
Successful authentication with an inappropriate role returns `403 Forbidden`, and an object such as the following: `{"message":"Forbidden. User needs the following permissions","permissions":["cluster.admin.security.external!write"]}`.

== Examples

The following example assigns saslauthd roles to three users, who have already been established as members of the `sasl` group on a Ubuntu Linux system:

----
curl -X POST http://localhost:8091/settings/saslauthdAuth -u Administrator:password -d admins=[couchbase] -d roAdmins=[abc,def] -d enabled=true
----

If the call is successful, an object such as the following is returned.

----
{"enabled":true,"admins":["[couchbase]"],"roAdmins":["[abc,def]"]}
----

The following example retrieves the current saslauthd settings for the cluster:

----
curl -X GET http://localhost:8091/settings/saslauthdAuth -u Administrator:password
----

If the call is successful, an object such as the following is returned:

----
{"enabled":true,"admins":["[tjh]"],"roAdmins":["[tjh,ajh]"]}
----

== See Also

Information on configuring saslauthd is provided in see xref:manage:manage-security/configure-saslauthd.adoc[Configure saslauthd].
Information on Couchbase-Server _authentication domains_ is provided in xref:learn:security/authentication-domains.adoc[Authentication Domains].
