= Identifying the Target in Replication
:description: pass:q[]

[abstract]
{description}

== HTTP Method and URI

----
GET /xdcr/sourceClusters
----

== Description

When on a current cluster, XDCR lets you:

* Retrieve the list of remote clusters that replicate to the current cluster.
If XDCR finds a list of replicating source clusters, it makes the current cluster the target cluster.

* Inspect the incoming XDCR replication streams on current cluster from each remote cluster.
It makes the current cluster the target cluster and remote cluster the source cluster.

Being on the target cluster, you can query incoming replications and relevant heartbeat information.

== Required Permissions

You must have Full Admin, Cluster Admin, or XDCR Admin role to call this API.

== curl Syntax

This API call retrieves information about all source clusters that are replicating to the current cluster (target cluster).

Run the following command on the target cluster.

----
curl -X GET -u <user-name>:<password> http://<ip-address-or-domain-name>:<port-number>/xdcr/sourceClusters | jq
----

=== Response

For each source cluster, the API returns replication specifications, current settings, source nodes, and heartbeat status as a JSON array, if the call is successful.

[source,json]
----
[
  {
    "SourceClusterNodes": [
      "http://<ip-address-or-domain-name-or-node-name>:<port-number>",
    ],
    "SourceClusterReplSpecs": "<list-of-replication-specifications-from-source-cluster-to-this-target>",
    "SourceClusterUUID": "<source-cluster-UUID>",
    "SourceClusterName": “<source-cluster-name>”,
    "SourceClusterHBReceiveTime": "<time-of-last-received-heartbeat>",
    "SourceClusterHBExpiryTime": "<heartbeat-expiry-time>"
  }
]
----

[#responses]
=== Other Responses

|===
|Value | Description  

| `200 OK` and JSON array containing repository information depending on the specific endpoint.
| Successful call.

| `400`
| Invalid parameter.

| `400 Object Not found`
| The repository in the endpoint URI does not exist.

| `401 Unauthorized`
|  Authorization failure due to incorrect username or password.

| `403 Forbidden`, plus a JSON message explaining the minimum permissions.
| The provided username has insufficient privileges to call this method.

| `404 Object Not Found`
| Error in the URI path.

| `500 Could not retrieve the requested repository`
| Error in Couchbase Server.

|===

== Examples

The following examples demonstrate how to use the `xdcr/sourceClusters` API to identify the target cluster in a replication and inspect the incoming replication streams.

[#example-source-without-replication-specs]
=== Cluster without replication specifications

----
curl -X GET -u Administrator:pw http://127.0.0.1:9000/xdcr/sourceClusters | jq
----

This call retrieves the following details of a source cluster with one node.
This source cluster has created a remote cluster reference to a target cluster but has not yet created a replication specification.

----
[
  {
    "SourceClusterNodes": [
      "127.0.0.1:9002"
    ],
    "SourceClusterReplSpecs": null,
    "SourceClusterUUID": "d4b15b1069e4aaac1d6d0cb7d15b1dde",
    "SourceClusterName": “m1”,
    "SourceClusterHBReceiveTime": "2024-10-24T20:52:21.902848+05:30",
    "SourceClusterHBExpiryTime": "2024-10-24T21:02:21.902848+05:30"
  }
]
----

[#example-source-with-replication-specs]
=== Cluster with replication specifications

----
curl -X GET -u Administrator:pw http://127.0.0.1:9002/xdcr/sourceClusters | jq
----

This source cluster has two nodes, has a reference established with the target cluster, and is replicating to the target cluster.
This call retrieves source cluster information and its replication specifications to the target cluster.

----
[
  {
    "SourceClusterNodes": [
      "10.100.172.24:9000",
      "127.0.0.1:9001"
    ],
    "SourceClusterReplSpecs": [
      {
        "id": "d4b15b1069e4aaac1d6d0cb7d15b1dde/B0/B1",
        "internalId": "ZsrIjhmEaf9232WGyoSexg==",
        "sourceBucketName": "B0",
        "sourceBucketUUID": "64b784ca2b3e8df7ab1cbf70ab89772f",
        "targetClusterUUID": "d4b15b1069e4aaac1d6d0cb7d15b1dde",
        "targetBucketName": "B1",
        "targetBucketUUID": "1d86409fe13ffbeb36ba3bf382005480",
        "replicationSettings": {
          "values": {
            "CollectionsMgtMulti": 8,
            "active": true,
          ....
          "Revision": null
        },
        "Revision": "g2gCYQBsAAAAAWgCbQAAACA2OGRiNmU0ZDE0YWQwNTFlODM3ZDM1N2FjYTYxMGIzZWgCYQNuBQAUvLneDmo="
      }
    ],
    "SourceClusterUUID": "6aa2a7cc7d9a42c253e76f832055ccea",
    "SourceClusterName": “m2”,
    "SourceClusterHBReceiveTime": "2024-10-24T20:52:21.902848+05:30",
    "SourceClusterHBExpiryTime": "2024-10-24T21:02:21.902848+05:30"
  }
]
----

[#complete-response]
=== Cluster with replication specifications - a full example

----
curl -s -X GET -u Administrator:password http://localhost:8091/xdcr/sourceClusters | jq
----
This call retrieves the source cluster information and its replication specifications to the target cluster.

The output of the call is piped to https://stedolan.github.io/jq/[jq^] to improve readability.

[source, json]
----
include::partial$get_source_clusters_sample.json[]
----

== See Also

* From the UI, to identify the target cluster in a replication and inspect its incoming replication streams, see xref:manage:manage-xdcr/create-xdcr-replication.adoc#identify-target-cluster-in-xdcr[Identify the Target Cluster in a Replication] in xref:manage:manage-xdcr/create-xdcr-replication.adoc[Create a Replication].

* To learn about using REST API to create or edit an XDCR reference to a target cluster, see xref:rest-api/rest-xdcr-create-ref.adoc[Creating or Editing a Reference].