= Manage Cluster Connections

:page-topic-type: reference

[abstract]
By means of the REST API, the maximum permitted numbers of connections can be established and retrieved for memcached connections, and for system-user connections, for the cluster.

== HTTP Methods and URIs

----
POST /pools/default/settings/memcached/global

GET /pools/default/settings/memcached/global
----

== Description

A Couchbase-Server cluster allows connections to be established by both memcached and authenticated system-users.
In each case, a maximum permitted number of connections can be established for the cluster, and can be retrieved.

== Curl Syntax

----
curl -u <username>:<password> -X POST
  <ip-address-or-domain-name>:8091/pools/default/settings/memcached/global
  -d [ max_connections=<integer> | system_connections=<integer> ]

curl -u <username>:<password> -X GET
  <ip-address-or-domain-name>:8091/pools/default/settings/memcached/global
----

The `integer` specified as the value for `max_connections` determines the maximum number of connections that can be established by memcached for the cluster.
The `integer` specified as the value for `system_connections` determines the maximum number of connections that can be established by authenticated system-users for the cluster.

== Responses

Successful use of GET returns `200 OK`, and an object containing a key-value pair for each established setting.

Successful use of POST returns `202 Accepted`, and an object containing a key-value pair for any established setting.

Failure to authenticate returns `401 Unauthorized`.
A malformed URI returns `404 Object Not Found`.
Specifying an `integer` of excessive size in a POST returns `400 Bad Request`, and an object such as the following: `{"system_connections":"too_large"}`.

== Examples

The following example sets the maximum number of connections for authenticated system-users to `50000`:

----
curl -u Administrator:password -v -X POST \
localhost:8091/pools/default/settings/memcached/global \
-d system_connections=50000
----

If successful, the call returns an object such as the following:

----
{"system_connections":50000}
----

The following example sets the maximum number of connections for memcached to `650000`:

----
curl -u Administrator:password -X POST \
localhost:8091/pools/default/settings/memcached/global \
-d  max_connections=650000
----

If successful, the call returns an object such as the following:

----
{"max_connections":650000,"system_connections":50000}
----

The returned object thus indicates that both `max_connections` and `system_connections` have now been set.

The following example returns the current settings for the cluster:

----
curl -u Administrator:password -v -X GET \
localhost:8091/pools/default/settings/memcached/global
----

If successful, the call returns an object such as the following:

----
{"max_connections":650000,"system_connections":50000}
----

== See Also
