= Configure Rebalance Retries
:page-topic-type: reference

== HTTP methods and URI

----
GET /pools/default/retryRebalance

POST /pools/default/retryRebalance
----

[#description]
== Description

This gets and sets the configuration for rebalance retries.
For an overview of rebalance and rebalance retries, see xref:learn:clusters-and-availability/rebalance.adoc[Rebalance].

[#curl-syntax]
== Curl Syntax

----
curl -X GET -u <administrator>:<password>
http://<host>:<port>/pools/default/retryRebalance

curl -X POST -u Administrator:password
http://<host>:<port>/settings/retryRebalance
    -d enabled=[ true | false ]
    -d afterTimePeriod=[number-of-seconds]
    -d maxAttempts=[number-of-attempts]
----

The `afterTimePeriod` parameter specifies the number of seconds that must elapse between successive retries: this must be an integer in the range of 5 to 3600.

The `maxAttempts` parameter specifies the maximum number of successive retries to be attempted: this must be an integer in the range of 1 to 3.

[#responses]
== Responses
Success gives `200 OK`, and returns an object containing status on pending rebalance retries.
Failure to authenticate gives `401 Unauthorized`.
A malformed URI gives `404 Object Not Found`.

[#example]
== Example

To obtain the cluster’s current rebalance settings by means of the REST API, use the `GET /settings/retryRebalance` http method and URI, as follows:

----
curl -X GET -u Administrator:password \
http://10.143.192.101:8091/settings/retryRebalance
----

If successful, the command returns the following object:

----
{"enabled":true,"afterTimePeriod":200,"maxAttempts":3}
----

This output shows that rebalance retry is enabled, with `200` seconds required to elapse before a retry is attempted, and a maximum of `3` retries possible.

To change the rebalance settings, use the `POST` method with the same URI, specifying appropriate values:

----
curl -X POST -u Administrator:password \
http://10.143.192.101:8091/settings/retryRebalance \
-d enabled=false \
-d afterTimePeriod=100 \
-d maxAttempts=2
----

If successful, the command returns the following object:

----
{"enabled":false,"afterTimePeriod":100,"maxAttempts":2}
----

This verifies that rebalance retry has been disabled, the required period between retries changed to `100` seconds, and the maximum number of retries changed to `2`.

[#see-also]
== See Also

For an overview of rebalance with the Data Service and other services, see xref:learn:clusters-and-availability/rebalance.adoc[Rebalance].
For practical examples of adding a node, rebalancing, and cancelling rebalance retries, see xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a Node and Rebalance].

For information on using the REST API to retrieve current status on and to cancel pending rebalance retries, see
xref:rest-api:rest-get-rebalance-retry.adoc[Get Rebalance-Retry Status] abd xref:rest-api:rest-cancel-rebalance-retry.adoc[Cancel Rebalance Retries].
For information on obtaining and reading _rebalance reports_, see the xref:rebalance-reference:rebalance-reference.adoc[Rebalance Reference].
