= Disabling consistent query results on rebalance
:page-topic-type: reference

[abstract]
Ensuring query results consistency is performed with the `POST /internalSettings -d indexAwareRebalanceDisabled` HTTP method, URI, and parameter.

== Description

If queries are performed during rebalance, this setting ensures that query results are consistent with the original bucket and data organization prior to rebalancing.
In other words, the query results reflect the data on an original node prior to rebalance rather than data on a node after rebalance started.
By default, this functionality is enabled.

NOTE: Be aware that rebalance may take significantly more time if you implemented views for indexing and querying.
If rebalance time becomes a critical factor for your application, this feature can be disabled, however, it is not recommend.
Do not disable this functionality for production applications without thorough testing.
To do so may lead to unpredictable query results during rebalance.

== HTTP method and URI

----
POST /internalSettings -d indexAwareRebalanceDisabled
----

== Syntax

Curl request syntax:

----
curl -v -u [admin]:[password] -X POST
  http://[localhost]:8091/internalSettings
  -d indexAwareRebalanceDisabled=[true | false]
----

== Example

Curl request example to disable this feature:

----
curl -v -u Administrator:password -X POST \
http://10.5.2.54:8091/internalSettings \
-d 'indexAwareRebalanceDisabled=true'
----

== Response

----
HTTP/1.1 200 OK
Content-Type: application/json
----
