= Getting a destination cluster reference
:page-topic-type: reference

[abstract]
To retrieve an XDCR reference to a destination cluster, use the `GET /pools/default/remoteClusters` HTTP method and URI.

== Description

To use XDCR, source and destination clusters must be established.
A source cluster is the cluster where the original data is stored.
A destination cluster is the cluster where the replica data is stored.
Data is copied from the source cluster to the destination cluster.

== HTTP method and URI

----
GET /pools/default/remoteClusters
----

== Syntax

Curl request syntax:

----
curl -u [admin]:[password]
    http://[localhost]:8091/pools/default/remoteClusters
----

== Example

When requesting the remote cluster reference, provide credentials for the local cluster and the hostname and port for the remote cluster.

Curl request example:

----
curl -u [admin]:[password]
    http://10.4.2.4:8091/pools/default/remoteClusters
----

Raw HTTP request example:

----
GET /pools/default/remoteClusters HTTP/1.1
Authorization: Basic QWRtaW5pc3RyYXRvcjpwYXNzd29yZA==
User-Agent: curl/7.21.4 (universal-apple-darwin11.0) libcurl/7.21.4 OpenSSL/0.9.8r zlib/1.2.5
Host: 10.4.2.4:8091
Accept: */*
----

== Response

If successful, Couchbase Server responds with a JSON response similar to the following:

----
[{
"name":"remote1",
"uri":"/pools/default/remoteClusters/remote1",
"validateURI":"/pools/default/remoteClusters/remote1?just_validate=1",
"hostname":"10.4.2.6:8091",
"username":"Administrator",
"uuid":"9eee38236f3bf28406920213d93981a3",
"deleted":false
}]
----

The following describes the response elements:

* (String) name: Name of the destination cluster referenced for XDCR.
* (String) uri: URI for destination cluster information.
* (String) validateURI: URI to validate details of cluster reference.
* (String) hostname: Hostname/IP (and :port) of the remote cluster.
* (String) uuid: UUID of the remote cluster reference.
* (String) username: Username for the destination cluster administrator.
* (Boolean) deleted: Indicates whether the reference to the destination cluster has been deleted or not.
