= Node Addition and Removal

:description: pass:q[Nodes can be added to and removed from a cluster, by means of the REST API.]
:page-topic-type: reference

[abstract]
{description}

== APIs in this Section

A Couchbase-Server cluster consists of one or more nodes, each of which is a system running an instance of Couchbase Server.
Nodes can be added to and removed from the cluster, by means of the REST API.

The routine for _adding_ a new node to the existing cluster is executed on the existing cluster.
The routine for _joining_ an existing cluster is executed on the new node.
These procedures are described in detail in xref:learn:clusters-and-availability/nodes.adoc[Nodes].

_Removal_ provides the most highly controlled means of taking a node out of a cluster.
Any node, whatever its service-configuration, can be removed. However, removal should be used only when all nodes in the cluster are responsive, and those intended to remain in the cluster after removal have the capacity to support the results.
This is described in detail in xref:learn:clusters-and-availability/removal.adoc[Removal].

The REST API described in this section is summarized below.

include::partial$node-addition-and-removal-list.adoc[]
