= Get Rebalance-Retry Information
:page-topic-type: reference

== HTTP method and URI

----
GET /pools/default/pendingRetryRebalance
----

[#description]
== Description

This returns information on pending rebalance retries.
The returned information can subsequently be used to cancel the retries.

[#curl-syntax]
== Curl Syntax

----
curl -X GET -u <administrator>:<password>
http://<host>:<port>/pools/default/pendingRetryRebalance
----

[#responses]
== Responses
Success gives `200 OK`, and returns an object containing information on pending rebalance retries.
Failure to authenticate gives `401 Unauthorized`.

[#example]
== Example

The following example obtains information on pending reblance-retries.
Note that the command is piped to the https://stedolan.github.io/jq/[jq] tool, to facilitate output-readability.

----
curl -u Administrator:password -v -X GET \
http://10.143.192.101:8091/pools/default/pendingRetryRebalance | jq '.'
----

If successful, the command returns the following object:

----
{
  "retry_rebalance": "pending",
  "rebalance_id": "ff5845cdce693db2dce9a9308cbf885d",
  "type": "rebalance",
  "attempts_remaining": 2,
  "retry_after_secs": 291,
  "known_nodes": [
    "ns_1@10.143.192.101",
    "ns_1@10.143.192.103"
  ],
  "eject_nodes": [],
  "delta_recovery_buckets": "all"
}
----

This indicates that the status of `retry_rebalance` is `pending`; and provides a `rebalance_id` for the process, of `ff5845cdce693db2dce9a9308cbf885d`.
This id can be used to cancel the retry.
The output also lists the cluster's nodes, indicates that `2` retry attempts are scheduled to occur if necessary after the current one, and indicates that `291` seconds are still to elapse before the pending retry.

Note that if no rebalance is pending, the following object is returned:

----
{
  "retry_rebalance": "not_pending"
}
----

[#see-also]
== See Also

For an overview of rebalance with the Data Service and other services, see xref:learn:clusters-and-availability/rebalance.adoc[Rebalance].
For practical examples of adding a node, rebalancing, and cancelling rebalance retries, see xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a Node and Rebalance].
For information on using the REST API to cancel pending rebalance retries, see xref:rest-api:rest-cancel-rebalance-retry.adoc[Cancel Rebalance Retries].
