= Establishing Auto-Compaction Settings
:page-topic-type: reference

[abstract]
Auto-compaction settings can be established for the cluster.

== Description

Auto-Compaction settings determine the compaction process; whereby databases and their respective view-indexes are compacted.

== HTTP method and URI

----
POST /controller/setAutoCompaction
----

== Syntax

Curl syntax is as follows:

----
curl -u Administrator:password -v -X POST
http://[cluster-ip-address]:8091/controller/setAutoCompaction
  -d databaseFragmentationThreshold[percentage]=[percentage]
  -d databaseFragmentationThreshold[size]=[size]
  -d viewFragmentationThreshold[percentage]=[percentage]
  -d viewFragmentationThreshold[size]=[percentage]
  -d allowedTimePeriod[fromHour]=[integer]
  -d allowedTimePeriod[fromMinute]=[integer]
  -d allowedTimePeriod[toHour]=[integer]
  -d allowedTimePeriod[toMinute]=[integer]
  -d allowedTimePeriod[abortOutside]=[ true | false ]
  -d parallelDBAndViewCompaction=[ true | false ]
  -d purgeInterval=[numberofdays]
  -d indexCompactionMode=[ standard | circular ]
  -d indexCircularCompaction[daysOfWeek]=[daynames-comma-separated]
  -d indexCircularCompaction[interval][fromHour]=[integer]
  -d indexCircularCompaction[interval][fromMinute]=[integer]
  -d indexCircularCompaction[interval][toHour]=[integer]
  -d indexCircularCompaction[interval][toMinute]=[integer]\
  -d indexCircularCompaction[interval][abortOutside]=[ true | false ]
----

== Controller Parameters

[cols="20,20"]
|===
| Function | Description

| `databaseFragmentationThreshold[percentage]`
| Integer specifying the database fragmentation percentage that is the point at which compaction is triggered.

| `databaseFragmentationThreshold[size]`
| Integer specifying the megabytes of database fragmentation that is the point at which compaction is triggered.

| `viewFragmentationThreshold[percentage]`
| Integer specifying the view fragmentation percentage that is the point at which compaction is triggered.

| `viewFragmentationThreshold[size]`
| Integer specifying the megabytes of view fragmentation that is the point at which compaction is triggered.

| `allowedTimePeriod[fromHour]`
| Integer between 0 and 23 inclusive, specifying the starting hour of the time-period during which compaction can run.

| `allowedTimePeriod[fromMinute]`
| Integer between 0 and 59 inclusive, specifying the starting minute (within the specified starting hour) of the time-period during which compaction can run.

| `allowedTimePeriod[toHour]`
| Integer between 0 and 23 inclusive, specifying the concluding hour of the time-period during which compaction can run.

| `allowedTimePeriod[toMinute]`
| Integer between 0 and 59 inclusive, specifying the concluding minute (within the specified concluding hour) of the time-period during which compaction can run.

| `allowedTimePeriod[abortOutside]`
| Either `true` or `false`, indicating respectively that compaction _should_ or _should not_ be aborted, if its running extends beyond the specified time of conclusion.

| `parallelDBAndViewCompaction`
| Either `true` or `false`, indicating respectively that compaction of databases and views _should_ or _should not_ run in parallel.

| `purgeInterval`
| The frequency with which the _tombstone purge_ is run, specified as either an integer or a decimal number.
If a decimal is specified, the fractional part is rounded at fifteen places.
The default value is 3.0; the minimum 0.04; the maximum 60.

| `indexCompactionMode`
| The compaction mode for indexes.
Can be either `standard` or `circular`.





|===
