= REST API Endpoint List
:description: pass:q[This section lists all Couchbase Server REST API endpoints.]
:page-topic-type: reference

[abstract]
{description}

== HTTP Methods and URIs

This page lists all HTTP Methods and URIs provided by the Couchbase-Server REST API.
Detailed information can be accessed by means of the page-name links in the *Page* column.
Calls are organized according to functional areas.

== Cluster API

The Cluster API provides support for managing and retrieving information on clusters.
It also provides support for managing _rebalance_, _failover_, and _server group awareness_.
The APIs for each area are assigned a table, below.

=== Adding and Removing Nodes

include::partial$rest-node-addition-and-removal-table.adoc[]

=== Rebalance

include::partial$rest-rebalance-table.adoc[]

=== Auto-Failover

include::partial$rest-auto-failover-table.adoc[]

=== Settings and Connections

include::partial$rest-settings-and-connections-table.adoc[]

=== Status and Events

include::partial$rest-status-and-events-table.adoc[]

=== Statistics

include::partial$rest-statistics-table.adoc[]

=== Notifications

include::partial$rest-notifications-table.adoc[]

== Nodes API

A Couchbase-Server instance is known as a _node_.
A node can be a physical or a virtual machine.
Each node is a member of a cluster.
The REST API listed in the table below can be used to manage nodes.

include::partial$rest-nodes-table.adoc[]

== Server Groups API

_Server Group Awareness_ provides enhanced availability.
Specifically, it protects a cluster from large-scale infrastructure failure, through the definition of groups.
Its REST API is expressed by the following table.

include::partial$rest-server-groups-table.adoc[]

== Buckets API

Couchbase Server keeps items in _buckets_.
Before an item can be saved, a bucket must exist for it.
Buckets can be created and managed by means of the following REST API.

include::partial$rest-buckets-table.adoc[]

== Scopes and Collections API

Couchbase Server provides _scopes_ and _collections_; allowing documents to be categorized and organized, within a bucket.
The REST API provided for the creation and management of scopes and collections is listed below.

include::partial$rest-scopes-and-collections-table.adoc[]

== Compaction API

_Compaction_ is used by Couchbase Server to relocate on-disk data; so as to ensure the data’s closest-possible proximity, and thereby reclaim fragments of unused disk-space.
The periodic compaction of a bucket’s data helps to ensure the ongoing efficiency of both reads and writes.
The REST API provided for compaction management is detailed below.

include::partial$rest-compaction-table.adoc[]

== Query Service API

The _Query Service_ provides a REST API that covers three requirements; which are the administration of Query Service nodes, the execution of N1QL statements, and the management of JavaScript libraries and objects used to create N1QL user-defined functions.
The REST API is detailed in the tables below.

include::partial$rest-query-service-table.adoc[]

== Index Service API

The _Index Service_ REST API provides configuration options for the Index Service.
The API is listed below.

include::partial$rest-index-service-table.adoc[]

== Backup Service API

The _Backup Service API_ supports management of the Backup Service, providing endpoints categorized as follows: _Cluster_, _Configuration_, _Repository_, _Plan_, _Task_, and _Data_.
All calls require the Full Admin role, and use port `8097`.
Each URI, in Couchbase Server Enterprise Edition Version 7.0, must be prefixed with `/api/v1`.

The individual endpoints are listed by category, in the tables below.

include::partial$rest-backup-service-table.adoc[]

== Search Service API

The Search Service allows users to create, manage, and query _Full Text Indexes_, whereby searches can be performed and matches attained on character strings.
The Search Service REST API allows such indexes to be created and maintained.
The API is listed in the tables below.

include::partial$rest-search-service-table.adoc[]

== Eventing Service API

The _Eventing Service_ REST API provides methods for working with _Eventing Functions_.
The complete API is listed at xref:eventing:eventing-api.adoc[Eventing REST API].

== Analytics Service API

The _Analytics Service_ provides a REST API for querying, configuration, and the management of links and libraries.
The API is listed in the following tables.

include::partial$rest-analytics-service-table.adoc[]

== XDCR API

Cross Data Center Replication (XDCR) replicates data between a source bucket and a target bucket.
The buckets may be located on different clusters, and in different data centers: this provides protection against data-center failure, and also provides high-performance data-access for globally distributed, mission-critical applications.
XDCR is supported by the REST API shown in the table below.

include::partial$rest-xdcr-table.adoc[]

== Logging API

The Logging REST API provides the following endpoints, for retrieving logging and diagnostic information.

include::partial$rest-logging-table.adoc[]

== Security API

The Security REST API provides the endpoints for general security, for authentication, and for authorization.
These APIs are listed in the tables below.

=== General Security

include::partial$rest-security-general-table.adoc[]

=== Authentication

include::partial$rest-security-authentication-table.adoc[]

=== Authorization

include::partial$rest-security-authorization-table.adoc[]
