= Manage Encryption Settings
:page-topic-type: reference

[abstract]
Establish and retrieve cluster-wide settings for the use of encryption and cipher-suites.

== HTTP method and URI

----
GET /settings/security

POST /settings/security
----

== Description

Allows settings to be established for the use of encryption.
This includes the encryption _level_, for node-to-node encryption within the cluster;
UI disablement over insecure connections; TLS minimum version; and the names and ordering of accepted cipher suites.

[#curl-syntax]
== Curl Syntax

----
curl -X GET -d hostname=<host>:<port>
  -d user=<administrator>
  -d password=<password>
  -u <administrator>:<password>

curl -X POST -d hostname=<host>:<port>
  -d user=<administrator>
  -d password=<password>
  -u <administrator>:<password>
  -d disableUIOverHttp=<true|false>
  -d disableUIOverHttps=<true|false>
  -d clusterEncryptionLevel=<all|control>
  -d tlsMinVersion=<tlsv1.1|tslv1.2>
  -d honorCipherOrder=<true|false>
  -d 'cipherSuites=<list-of-accepted-cipher-suites>
  http://<host>:<port>/settings/security
----

The syntax for the POST method includes the following:

* `disableUIOverHttp`.
Whether access to Couchbase Web Console should be disabled over http.
Default is `false`, meaning that the console can be accessed over http.

* `disableUIOverHttps`.
Whether access to Couchbase Web Console should be disabled over https.
Default is `false`, meaning that the console can be accessed over https.

* `clusterEncryptionLevel`.
Controls the level of encryption imposed on inter-node communications within the cluster.
Can be either `control` (meaning that only server-management information is passed in encrypted form) or `all` (meaning that all information, including data handled by services, is passed in encrypted form).

* `tlsMinVersion`.
Specifies the minimum TLS version accepted by the cluster.
Can be either `tlsv1.1` or `tlsv1.1`.
This parameter can only be set when encryption between cluster-nodes has been explicitly enabled: see xref:manage:manage-nodes/apply-node-to-node-encryption.adoc[Apply Node-to-Node Encryption], for details.

* `honorCipherOrder`.
Specifies whether the cluster uses its own cipher-suite preference, rather than the client's.
The cluster's accepted cipher-suite can be specified in order of preference with the `cipherSuites` flag (see below).
The default value of `honorCipherOrder` is `true`: a setting of `false` is _not_ recommended, since insecure.

* `cipherSuites`.
Specifies a list of the cipher suites to be used by the cluster, in order of preference.
The argument must be a list of cipher suites, each of which is supported by the underlying operating system.
The most preferred cipher is at the top of the list, the least preferred at the bottom.
Use `openssl ciphers -v` at the Linux command-line, to display a list of available ciphers.

[#responses]
== Responses

The GET method, if successful, gives `200 OK`, and returns an object containing each parameter with its current value.
The POST method, if successful, gives `200 OK`, and returns an empty array.

For both methods, an incorrect URI gives `404 Object Not Found`, with a `Not found` error message.
Use of improper credentials gives `401 Unauthorized`.
An improper port number returns an error message such as `Failed to connect`, or `Port number out of range`.

For the POST method, incorrectly specified parameters fail with `404 Bad Request`, and return an `error` object that lists the errors in an array.
For example, a call that specifies every significant parameter-value incorrectly returns an object such as the following:

----
{
  "errors": [
    "honorCipherOrder - Accepted values are 'true' and 'false'.",
    "cipherSuites - Invalid cipher suite names = TLS_RSA_WITH_AES_256_CBC_SHA33",
    "tlsMinVersion - Supported TLS versions are ['tlsv1.2','tlsv1.1',tlsv1]",
    "clusterEncryptionLevel - Cluster encryption level must be one of ['control', 'all'].",
    "disableUIOverHttps - Accepted values are 'true' and 'false'.",
    "disableUIOverHttp - Accepted values are 'true' and 'false'."
  ]
}
----

== Examples

The methods and the URI can be used as shown below.

[#establish-encryption-settings]
=== Establish Encryption Settings

The following establishes encryption settings for the cluster:

----
curl  -u Administrator:password -v -X POST \
http://10.143.192.101:8091/settings/security \
-d disableUIOverHttp=false \
-d clusterEncryptionLevel=control \
-d tlsMinVersion=tlsv1.1 \
-d 'cipherSuites=["TLS_RSA_WITH_AES_128_CBC_SHA", "TLS_RSA_WITH_AES_256_CBC_SHA"]'
----

The `disableUIOverHttp` flag is given a value of `false`, indicating that access to Couchbase Web Console will _not_ be disabled over http.
The `disableUIOverHttps` flag is _not_ specified, meaning that access to Couchbase Web Console will _not_ be disabled over https, by default.
The `clusterEncryptionLevel` is specified as `control`, indicating that only server-management information is passed in encrypted form between cluster-nodes.
The `tlsMinVersion` is specified as version 1.1.
The `honorCipherOrder` parameter is _not_ specified, ensuring that the default of `true` is used; so that the cluster's own cipher-suites preference is used, rather than the client's.
The `cipherSuites` parameter is given a list of two cipher suites to be used.

If successful, the call returns an empty array:

----
[]
----

[#retrieve-encryption-settings]
=== Retrieve Encryption Settings

The following retrieves encryption settings for the cluster.
Note that, in this example, the output is piped to the https://stedolan.github.io/jq/[jq] tool, to facilitate readability:

----
curl  -u Administrator:password -v -GET \
http://10.143.192.101:8091/settings/security | jq '.'
----

If the call is successful, the output is approximately as follows:

----
{
  "disableUIOverHttp": false,
  "disableUIOverHttps": false,
  "tlsMinVersion": "tlsv1.1",
  "cipherSuites": [
    "TLS_RSA_WITH_AES_128_CBC_SHA",
    "TLS_RSA_WITH_AES_256_CBC_SHA"
  ],
  "honorCipherOrder": false,
  "clusterEncryptionLevel": "control"
}
----

The returned object lists each of the settings with its current value.
An array containing the complete list of acceptable cipher suites is provided as the value of `cipherSuites`.
