= Configure saslauthd

[abstract]
The Couchbase REST API supports enablement of `saslauthd` for the cluster; and the addition of administrator and read-only administrator users to the cluster.

== GET /pools

*Description*

This command enables `saslauthd` for the cluster.
Note that the appropriate installation and preparation procedures must have been performed.
See xref:manage:manage-security/configure-saslauthd.adoc[Configure saslauthd].

*Syntax:*

----
 curl -X GET -u <administrator>:<password>
    http://<host>:<port>/settings/saslauthdAuth
    -d args
    .
    .
----

HTTP request syntax:

----
GET /settings/saslauthdAuth
Host: localhost:8091
Authorization: Basic xxxxxxxxxxxxxxxxxxx
Accept: */*
Content-Type: application/x-www-form-urlencoded
----

*Example*

----
curl -v -X GET -u Administrator:password \
http://10.143.192.101:8091/settings/saslauthdAuth \
-d enabled=true \
-d admins=alice,barry \
-d roadmins=clair,daniel
----

.Controller parameters
[cols="40,70"]
|===
| Function | Description

| admins
| Comma-separated list of SASL users to be given administrator privileges on the cluster.
If either an asterisk or the word 'asterisk' is specified as the value, all SASL users not specified to be granted a different set of privileges are granted administrator privileges.

| roadmins
| Comma-separated list of SASL users to be given read-only administrator privileges on the cluster.
If either an asterisk or the word 'asterisk' is specified as the value, all SASL users not specified to be granted a different set of privileges are granted read-only administrator privileges.

| enabled
| Enables or disables SASL on the cluster. 1 enables, 0 disables.

|==
