[#rest-cluster-autofailover]
= Managing Auto-Failover

[abstract]
Auto-failover is managed with with the `GET /settings/autoFailover` HTTP method and URI.

== Description

This section provides information about retrieving, enabling, disabling and resetting auto-failover.

.Auto-failover endpoints
[cols="100,229,367"]
|===
| HTTP method | URI path | Description

| GET
| [.path]_/settings/autoFailover_
 Enabled=`[true|false] `: True to enable failover; false to disable failover.
 timeout=`[value]` : Integer between 30 and 3600.
Specifies the amount of time (in seconds) that a node is down before failover in initiated.
 count=`[0|1]`: Value is 0 or 1.
It shows whether any node in a cluster can be automatically failed-over.
After one auto-failover occurs, the count is set to 1 and Couchbase Server does not perform another auto-failover for the cluster unless the count is reset to 0.
To failover more than one node at a time in a cluster, perform a manual failover.
| Retrieves automatic failover settings.
Parameters include:



| POST
| [.path]_/settings/autoFailover_
| Enables and disables automatic failover.
To enable or disable failover, use the `enabled=[true|false]` parameter.
To specify the number of seconds that a node must be down before initiating failover, use the `timeout` parameter.

| POST
| [.path]_/settings/autoFailover/resetCount_
| Resets automatic failover count to 0.
|===
