= REST API reference
:description: The REST API supports the management of Couchbase-Server clusters.
:page-aliases: rest-api:rest-node-provisioning.adoc,rest-api:rest-endpoints-all.adoc

[abstract]
{description}

The REST API supports the management of Couchbase-Server clusters.
This includes cluster-creation and the definition of nodes, services, and server groups.
The API also supports the extensive retrieval of statistics.

This page provides a complete list of HTTP methods and URIs.
It also lists xref:rest-api:rest-intro.adoc#http-request-headers[HTTP Request Headers] and xref:rest-api:rest-intro.adoc#http-response-codes[HTTP Response Codes].

== Nodes and Clusters API

The Cluster API provides support for managing and retrieving information on clusters.
It also provides support for managing _rebalance_, _failover_, and _server group awareness_.
The APIs for each area are assigned a table, below.

=== Cluster Initialization and Provisioning

include::partial$rest-cluster-init-and-configuration-table.adoc[]

=== Node Addition and Removal

include::partial$rest-node-addition-and-removal-table.adoc[]

=== Rebalance

include::partial$rest-rebalance-table.adoc[]

=== Manual-Failover

include::partial$rest-manual-failover-table.adoc[]

=== Auto-Failover

include::partial$rest-auto-failover-table.adoc[]

=== Settings and Connections

include::partial$rest-settings-and-connections-table.adoc[]

=== Status and Events

include::partial$rest-status-and-events-table.adoc[]

=== Statistics

include::partial$rest-statistics-table.adoc[]

=== Logging

include::partial$rest-logging-table.adoc[]

== Buckets API

Couchbase Server keeps items in _buckets_.
Before an item can be saved, a bucket must exist for it.
Buckets can be created and managed by means of the following REST API.

include::partial$rest-buckets-table.adoc[]

== Scopes and Collections API

Couchbase Server provides _scopes_ and _collections_; allowing documents to be categorized and organized, within a bucket.
The REST API provided for the creation and management of scopes and collections is listed below.

include::partial$rest-scopes-and-collections-table.adoc[]

== Memory and Storage API

_Memory quotas_ can be allocated to services, and the current allocations retrieved.
During cluster initialization, the _on-disk paths_ for services can be specified on a _per node_ basis.

Reader and writer threads can be configured, to ensure that disk access is highly performant.

_Compaction_ can be managed: this is used by Couchbase Server to relocate on-disk data; so as to ensure the data’s closest-possible proximity, and thereby reclaim fragments of unused disk-space.
The periodic compaction of a bucket’s data helps to ensure the ongoing efficiency of both reads and writes.

include::partial$rest-memory-and-storage-table.adoc[]

== Server Groups API

_Server Group Awareness_ provides enhanced availability.
Specifically, it protects a cluster from large-scale infrastructure failure, through the definition of groups.
Its REST API is expressed by the following table.

include::partial$rest-server-groups-table.adoc[]

== XDCR API

Cross Data Center Replication (XDCR) replicates data between a source bucket and a target bucket.
The buckets may be located on different clusters, and in different data centers: this provides protection against data-center failure, and also provides high-performance data-access for globally distributed, mission-critical applications.
XDCR is supported by the REST API shown in the table below.

include::partial$rest-xdcr-table.adoc[]

== Security API

The Security REST API provides the endpoints for general security, for authentication, and for authorization.
These APIs are listed in the tables below.

=== General Security

include::partial$rest-security-general-table.adoc[]

=== Authentication

include::partial$rest-security-authentication-table.adoc[]

=== Authorization

include::partial$rest-security-authorization-table.adoc[]

=== System-Secrets Management

include::partial$rest-system-secrets-management-table.adoc[]

== Query Service API

The _Query Service_ provides a REST API that covers four requirements; which are the administration of Query Service nodes, the configuration of the Query Service, the execution of {sqlpp} statements, and the management of JavaScript libraries and objects used to create {sqlpp} user-defined functions.
The REST API is detailed in the tables below.

include::partial$rest-query-service-table.adoc[]

== Index Service API

The _Index Service_ REST API provides configuration options for the Index Service.
The API is listed below.

include::partial$rest-index-service-table.adoc[]

== Backup Service API

The _Backup Service API_ supports management of the Backup Service, providing endpoints categorized as follows: _Cluster_, _Configuration_, _Repository_, _Plan_, _Task_, and _Data_.
All calls require the Full Admin role, and use port `8097`.
Each URI, in Couchbase Server Enterprise Edition Version 7.0 and later, must be prefixed with `/api/v1`.

The individual endpoints are listed by category, in the tables below.

include::partial$rest-backup-service-table.adoc[]

== Search Service API

The Search Service allows users to create, manage, and query _Full Text Indexes_, whereby searches can be performed and matches attained on character strings.
The Search Service REST API allows such indexes to be created and maintained.
The API is listed in the tables below.

include::partial$rest-search-service-table.adoc[]

== Eventing Service API

The _Eventing Service_ REST API provides methods for working with _Eventing Functions_.
The complete API is listed at xref:eventing:eventing-api.adoc[Eventing REST API].

== Analytics Service API

The _Analytics Service_ provides a REST API for querying, configuration, and the management of links and libraries.
The API is listed in the following tables.

include::partial$rest-analytics-service-table.adoc[]



== HTTP Request Headers

The following HTTP request headers are used to create requests:

|===
| Header | Supported Values | Description of Use | Required

| Accept
| Comma-delimited list of media types or media type patterns.
| Indicates to the server what media type(s) this client is prepared to accept.
| Recommended

| Authorization
| `Basic` plus username and password (per RFC 2617).
| Identifies the authorized user making this request.
| No, unless secured

| Content-Length
| Body Length (in bytes)
| Describes the size of the message body.
| Yes, on requests that contain a message body.

| Content-Type
| Content type
| Describes the representation and syntax of the request message body.
| Yes, on requests that contain a message body.

| Host
| Origin host name
| Required to allow support of multiple origin hosts at a single IP address.
| All requests

| X-YYYYY-Client-Specification-Version
| String
| Declares the specification version of the YYYYY API that this client was programmed against.
| No
|===

== HTTP Response Codes

The Couchbase Server  returns one of the following HTTP status codes in response to REST API requests:

[cols="1,3"]
|===
| HTTP response | Description

| 200 OK
| Successful request and an HTTP response body returns.
If this creates a new resource with a URI, the 200 status will also have a location header containing the canonical URI for the newly created resource.

| 201 Created
| Request to create a new resource is successful, but no HTTP response body returns.
The URI for the newly created resource returns with the status code.

| 202 Accepted
| The request is accepted for processing, but processing is not complete.
Per HTTP/1.1, the response, if any, SHOULD include an indication of the request’s current status, and either a pointer to a status monitor or some estimate of when the request will be fulfilled.

| 204 No Content
| The server fulfilled the request, but does not need to return a response body.

| 400 Bad Request
| The request could not be processed because it contains missing or invalid information, such as validation error on an input field, a missing required value, and so on.

| 401 Unauthorized
| The credentials provided with this request are missing or invalid.

| 403 Forbidden
| The server recognized the given credentials, but you do not possess proper access to perform this request.

| 404 Not Found
| URI provided in a request does not exist.

| 405 Method Not Allowed
| The HTTP verb specified in the request (DELETE, GET, HEAD, POST, PUT) is not supported for this URI.

| 406 Not Acceptable
| The resource identified by this request cannot create a response corresponding to one of the media types in the Accept header of the request.

| 409 Conflict
| A create or update request could not be completed, because it would cause a conflict in the current state of the resources supported by the server.
For example, an attempt to create a new resource with a unique identifier already assigned to some existing resource.

| 500 Internal Server Error
| The server encountered an unexpected condition which prevented it from fulfilling the request.

| 501 Not Implemented
| The server does not currently support the functionality required to fulfill the request.

| 503 Service Unavailable
| The server is currently unable to handle the request due to temporary overloading or maintenance of the server.
|===
