= Managing Sample Buckets
:page-topic-type: reference

[abstract]
Couchbase Server allows _sample buckets_ to be installed.
These contain data ready to be used for development and testing.

== Description

Couchbase Server allows _sample buckets_ to be installed, so that development and test activities can be supported.

== HTTP methods and URIs

The following methods and URIs respectively allow the names of the currently available sample buckets to be retrieved, and one or more to be installed on the cluster.

----
GET /sampleBuckets

POST /sampleBuckets/install
----

== Curl Syntax

----
curl -X GET -u <username>:<password>
  http://[node-name-or-ip-address]:8091/sampleBuckets

curl -X POST -u <username>:<password>
  http://[node-name-or-ip-address]:8091/sampleBuckets/install
  -d '[ <bucketname>, <bucketname> ]'
----

The `node-name-or-ip-address` can be that of any node in the cluster.
Each `bucketname` must be the name of an available sample bucket, specified as a string.

== Responses

If the call is successful, `200 OK` is given, and an object containing group-related information is returned.
An incorrectly specified bucket-name or URI gives `404 Object Not Found`.
Failure to authenticate gives `401 Unauthorized`.

== Example

The following example performs compaction on the bucket `travel-sample`:

----
curl -i -v -X POST -u Administrator:password \
http://10.143.193.101:8091/pools/default/buckets/travel-sample/controller/compactBucket
----

Once initiated, the compaction-process can be terminated, with a call such as the following:

----
curl -i -v -X POST -u Administrator:password \
http://10.143.193.101:8091/pools/default/buckets/travel-sample/controller/cancelBucketCompaction
----

== See Also

REST APIs for establishing and retrieving auto-compaction settings are provided in xref:rest-api:rest-autocompact-global.adoc[Auto-Compaction: Global] and xref:rest-api:rest-autocompact-per-bucket.adoc[Auto-Compaction: Per Bucket].

See xref:manage:manage-settings/configure-compact-settings.adoc[Auto-Compaction], for information on managing auto-compaction with Couchbase Web Console.
