= Auto-Failover
:description: pass:q[Auto-failover can be managed by means of the REST API.]
:page-topic-type: reference

[abstract]
{description}

== APIs in this Section

The APIs described in this section support _Automatic Failover_ —- or _auto-failover_; which can be configured to fail over one or more nodes automatically.
No immediate administrator-intervention is required. Specifically, the Cluster Manager autonomously detects and verifies that the nodes are unresponsive, and then initiates the hard failover process.
Auto-failover does not fix or identify problems that may have occurred.
Once appropriate fixes have been applied to the cluster by the administrator, a rebalance is required.
Auto-failover is always _hard_ failover.

A complete overview of auto-failover is provided in xref:learn:clusters-and-availability/automatic-failover.adoc[Automatic Failover].

The APIs for auto-failover are listed in the following table.

include::partial$rest-auto-failover-table.adoc[]

[#auto-failover-and-durability]
== Auto-Failover and Durability

Couchbase Server provides _durability_, which ensures the greatest likelihood of data-writes surviving unexpected anomalies, such as node-outages.
The auto-failover maximum should be established to support guarantees of durability.
See xref:learn:data/durability.adoc[Durability], for information.
