= Performing Graceful Failover
:description: pass:q[Graceful failover is initiated via the `POST /controller/startGracefulFailover` HTTP method and URI.]
:page-topic-type: reference

[abstract]
{description}

== HTTP method and URI

Initiates graceful failover for a specific server node.
The server node is specified with the `otpNode=[node@hostname]` parameter.

----
POST /controller/startGracefulFailover
----

NOTE: The failover progress can be tracked just like rebalance.
After the data is persisted to disk and replicas are up-to-date, the node is put into the failed over state.

== Syntax

----
POST /controller/startGracefulFailover
    otpNode=[node@hostname]
----

NOTE: Be sure to update any scripts that implement failover.

== Example

To fail a node over gracefully with the REST API, use the `/controller/startGracefulFailover` URI, specifying the node to be failed over, as follows:

----
curl -v -X POST -u Administrator:password \
http://10.142.181.101:8091/controller/startGracefulFailover \
-d 'otpNode=ns_1@10.142.181.102'
----

Note that the `optNode` flag can accept multiple values, separated by commas: every referenced node is gracefully failed over.

Subsequently, the cluster can be rebalanced, and the failed-over node removed, with the `/controller/rebalance` URI:

----
curl  -u Administrator:password -v -X POST \
http://10.142.181.101:8091/controller/rebalance \
-d 'knownNodes=ns_1@10.142.181.101,ns_1@10.142.181.102&ejectedNodes=ns_1@10.142.181.102'
----

For more information on `/controller/rebalance`, see xref:rest-api:rest-cluster-rebalance.adoc[Rebalancing the Cluster].
