= Naming a Node

:description: pass:q[A node can be named, by means of the REST API.]
:page-topic-type: reference

[abstract]
{description}

[#http-method-and-uri]
== HTTP Method and URI

----
POST /node/controller/rename
----

[#description]
== Description

Names and, if required, renames an individual node.
This API is therefore used as part of the node-provisioning process, and can also be used or reused subsequent to all other aspects of node-provisioning, including specification of username and password for the Full Administrator.
However, the API can only be used while the node constitutes a _single-node cluster_: once the node has become part of a multi-node cluster, the API can no longer be used.

== Curl Syntax

----
curl -X POST -u <username>:<password> \
http://<ip-address-or-domain-name>:8091/node/controller/rename \
-d hostname=<name>
----

The `name` argument must be one of the following:

* The IP address of the underlying host (either IPv4 or IPv6).

* A fully qualified hostname that corresponds, in the appropriate network maps, to the IP address of the underlying host.

* The loopback address, `127.0.0.1`.

== Responses

Success returns `200 OK`.
Failure to specify the `name` argument correctly returns `400 Bad Request`, and a message such as the following: `["Could not listen on address \"10.144.220.107\": eaddrnotavail"]`.
If a username and password have already been assigned, failure to authenticate returns `401 Unauthorized`.
An incorrectly expressed URI or flag returns `404 Object Not Found`.

== Example

The following example specifies the IP of the underlying host as the name of the node.

----
curl -X POST -u Administrator:password \
http://10.144.220.101:8091/node/controller/rename \
-d hostname='10.144.220.101'
----

== See Also

The sequence of tasks divided into _initialization_ and _provisioning_ is explained in xref:rest-api:rest-cluster-init-and-provisioning.adoc[Cluster Initialization and Provisioning].

For each of the other specific steps required in the provisioning process, see xref:rest-api:rest-configure-memory.adoc[Configuring Memory], xref:rest-name-cluster.adoc[Naming a Cluster], xref:rest-api:rest-set-up-services.adoc[Assigning Services], and xref:rest-api:rest-establish-credentials.adoc[Establishing Credentials].

For general information on naming, see xref:learn:clusters-and-availability/nodes.adoc#naming-clusters-and-nodes[Naming Clusters and Nodes].

For further information on initialization and provisioning -- using the UI, the CLI, and the REST API -- see xref:manage:manage-nodes/node-management-overview.adoc[Manage Nodes and Clusters].
