= Getting Search Statistics
:description: Get statistics for the Search Service and your Search indexes.
:page-topic-type: reference

[abstract]
{description}

== Get Search Index Statistics 

Use the following API to retrieve statistics on documents, partition indexes, mutations, compactions, and queries for the Search Service and any Search indexes. 

=== Endpoint

----
GET <host>:<port>/api/nsstats
----

Set `host` to a node that runs the Search Service. 

Set `port` to `8094` for http or `18094` for https. 

=== Permission Required 

cluster.fts!read

=== Role Required 

xref:learn:security/roles.adoc#full-admin[Full Admin], xref:learn:security/roles.adoc#cluster-admin[Cluster Admin], or the xref:learn:security/roles.adoc#bucket-admin[Bucket Admin] role for the bucket or buckets where you created Search indexes.


[#responses]
=== Responses

If the call is successful, the API returns a `200 OK` response with an object containing search-related statistics.

A malformed URI gives `400 Object Not Found`.
Failure to authenticate gives `401 Unauthorized`.

If a user authenticates but does not have the appropriate permissions, the API returns a `403 Forbidden` response with an object similar to the following:

----
{
  "message": "Forbidden. User needs one of the following permissions",
  "permissions": [
    "cluster.fts!read"
  ]
}
----

A successful response would return an object like the following, which contains statistics on 2 indexes, `travel-sample-index` and `geoIndex`: 

----
{
  "batch_bytes_added": 0,
  "batch_bytes_removed": 0,
  "curr_batches_blocked_by_herder": 0,
  "num_bytes_used_ram": 213924088,
  "pct_cpu_gc": 0.001428879394431173,
  "tot_batches_flushed_on_maxops": 0,
  "tot_batches_flushed_on_timer": 0,
  "tot_bleve_dest_closed": 0,
  "tot_bleve_dest_opened": 12,
  "tot_grpc_listeners_closed": 0,
  "tot_grpc_listeners_opened": 1,
  "tot_grpc_queryreject_on_memquota": 0,
  "tot_grpcs_listeners_closed": 0,
  "tot_grpcs_listeners_opened": 1,
  "tot_http_limitlisteners_closed": 0,
  "tot_http_limitlisteners_opened": 1,
  "tot_https_limitlisteners_closed": 0,
  "tot_https_limitlisteners_opened": 1,
  "tot_queryreject_on_memquota": 0,
  "tot_remote_grpc": 0,
  "tot_remote_grpc_tls": 0,
  "tot_remote_http": 0,
  "tot_remote_http2": 0,
  "total_gc": 1861,
  "total_queries_rejected_by_herder": 0,
  "travel-sample:geoIndex:avg_grpc_internal_queries_latency": 0,
  "travel-sample:geoIndex:avg_grpc_queries_latency": 0,
  "travel-sample:geoIndex:avg_internal_queries_latency": 0,
  "travel-sample:geoIndex:avg_queries_latency": 41.771365,
  "travel-sample:geoIndex:batch_merge_count": 0,
  "travel-sample:geoIndex:doc_count": 16694,
  "travel-sample:geoIndex:iterator_next_count": 0,
  "travel-sample:geoIndex:iterator_seek_count": 0,
  "travel-sample:geoIndex:last_access_time": "2020-03-30T04:42:53.701-07:00",
  "travel-sample:geoIndex:num_bytes_live_data": 0,
  "travel-sample:geoIndex:num_bytes_used_disk": 295152367,
  "travel-sample:geoIndex:num_bytes_used_disk_by_root": 99845092,
  "travel-sample:geoIndex:num_files_on_disk": 52,
  "travel-sample:geoIndex:num_mutations_to_index": 0,
  "travel-sample:geoIndex:num_persister_nap_merger_break": 6,
  "travel-sample:geoIndex:num_persister_nap_pause_completed": 6,
  "travel-sample:geoIndex:num_pindexes_actual": 6,
  "travel-sample:geoIndex:num_pindexes_target": 6,
  "travel-sample:geoIndex:num_recs_to_persist": 0,
  "travel-sample:geoIndex:num_root_filesegments": 6,
  "travel-sample:geoIndex:num_root_memorysegments": 0,
  "travel-sample:geoIndex:reader_get_count": 0,
  "travel-sample:geoIndex:reader_multi_get_count": 0,
  "travel-sample:geoIndex:reader_prefix_iterator_count": 0,
  "travel-sample:geoIndex:reader_range_iterator_count": 0,
  "travel-sample:geoIndex:timer_batch_store_count": 0,
  "travel-sample:geoIndex:timer_data_delete_count": 0,
  "travel-sample:geoIndex:timer_data_update_count": 0,
  "travel-sample:geoIndex:timer_opaque_get_count": 2731,
  "travel-sample:geoIndex:timer_opaque_set_count": 1024,
  "travel-sample:geoIndex:timer_rollback_count": 0,
  "travel-sample:geoIndex:timer_snapshot_start_count": 0,
  "travel-sample:geoIndex:total_bytes_indexed": 0,
  "travel-sample:geoIndex:total_bytes_query_results": 13730,
  "travel-sample:geoIndex:total_compaction_written_bytes": 0,
  "travel-sample:geoIndex:total_compactions": 0,
  "travel-sample:geoIndex:total_grpc_internal_queries": 0,
  "travel-sample:geoIndex:total_grpc_queries": 0,
  "travel-sample:geoIndex:total_grpc_queries_error": 0,
  "travel-sample:geoIndex:total_grpc_queries_slow": 0,
  "travel-sample:geoIndex:total_grpc_queries_timeout": 0,
  "travel-sample:geoIndex:total_grpc_request_time": 0,
  "travel-sample:geoIndex:total_internal_queries": 0,
  "travel-sample:geoIndex:total_queries": 9,
  "travel-sample:geoIndex:total_queries_error": 1,
  "travel-sample:geoIndex:total_queries_slow": 0,
  "travel-sample:geoIndex:total_queries_timeout": 0,
  "travel-sample:geoIndex:total_request_time": 376022106,
  "travel-sample:geoIndex:total_term_searchers": 2226,
  "travel-sample:geoIndex:total_term_searchers_finished": 2226,
  "travel-sample:geoIndex:writer_execute_batch_count": 0,
  "travel-sample:travel-sample-index:avg_grpc_internal_queries_latency": 0,
  "travel-sample:travel-sample-index:avg_grpc_queries_latency": 0,
  "travel-sample:travel-sample-index:avg_internal_queries_latency": 0,
  "travel-sample:travel-sample-index:avg_queries_latency": 18.477376,
  "travel-sample:travel-sample-index:batch_merge_count": 0,
  "travel-sample:travel-sample-index:doc_count": 16694,
  "travel-sample:travel-sample-index:iterator_next_count": 0,
  "travel-sample:travel-sample-index:iterator_seek_count": 0,
  "travel-sample:travel-sample-index:last_access_time": "2020-03-31T05:56:15.264-07:00",
  "travel-sample:travel-sample-index:num_bytes_live_data": 0,
  "travel-sample:travel-sample-index:num_bytes_used_disk": 247966801,
  "travel-sample:travel-sample-index:num_bytes_used_disk_by_root": 104572509,
  "travel-sample:travel-sample-index:num_files_on_disk": 54,
  "travel-sample:travel-sample-index:num_mutations_to_index": 0,
  "travel-sample:travel-sample-index:num_persister_nap_merger_break": 6,
  "travel-sample:travel-sample-index:num_persister_nap_pause_completed": 6,
  "travel-sample:travel-sample-index:num_pindexes_actual": 6,
  "travel-sample:travel-sample-index:num_pindexes_target": 6,
  "travel-sample:travel-sample-index:num_recs_to_persist": 0,
  "travel-sample:travel-sample-index:num_root_filesegments": 10,
  "travel-sample:travel-sample-index:num_root_memorysegments": 0,
  "travel-sample:travel-sample-index:reader_get_count": 0,
  "travel-sample:travel-sample-index:reader_multi_get_count": 0,
  "travel-sample:travel-sample-index:reader_prefix_iterator_count": 0,
  "travel-sample:travel-sample-index:reader_range_iterator_count": 0,
  "travel-sample:travel-sample-index:timer_batch_store_count": 0,
  "travel-sample:travel-sample-index:timer_data_delete_count": 0,
  "travel-sample:travel-sample-index:timer_data_update_count": 0,
  "travel-sample:travel-sample-index:timer_opaque_get_count": 2715,
  "travel-sample:travel-sample-index:timer_opaque_set_count": 1024,
  "travel-sample:travel-sample-index:timer_rollback_count": 0,
  "travel-sample:travel-sample-index:timer_snapshot_start_count": 0,
  "travel-sample:travel-sample-index:total_bytes_indexed": 0,
  "travel-sample:travel-sample-index:total_bytes_query_results": 308694,
  "travel-sample:travel-sample-index:total_compaction_written_bytes": 0,
  "travel-sample:travel-sample-index:total_compactions": 0,
  "travel-sample:travel-sample-index:total_grpc_internal_queries": 0,
  "travel-sample:travel-sample-index:total_grpc_queries": 0,
  "travel-sample:travel-sample-index:total_grpc_queries_error": 0,
  "travel-sample:travel-sample-index:total_grpc_queries_slow": 0,
  "travel-sample:travel-sample-index:total_grpc_queries_timeout": 0,
  "travel-sample:travel-sample-index:total_grpc_request_time": 0,
  "travel-sample:travel-sample-index:total_internal_queries": 0,
  "travel-sample:travel-sample-index:total_queries": 34,
  "travel-sample:travel-sample-index:total_queries_error": 5,
  "travel-sample:travel-sample-index:total_queries_slow": 0,
  "travel-sample:travel-sample-index:total_queries_timeout": 0,
  "travel-sample:travel-sample-index:total_request_time": 628280816,
  "travel-sample:travel-sample-index:total_term_searchers": 1669,
  "travel-sample:travel-sample-index:total_term_searchers_finished": 1669,
  "travel-sample:travel-sample-index:writer_execute_batch_count": 0
}
----

==== Returned Statistics 

The Search Service returns the following statistics from the `nsstats` endpoint: 

|====
|Statistic |Description 

| `batch_bytes_added`
a| The total number of bytes in batches that have not yet been added to the Search index. 

Batches are a data structure in the Search Service, used for processing data coming in from DCP to the documents in a Search index. 

| `batch_bytes_removed`
a| The total number of bytes in batches that have been added to the Search index. 

Use together with `batch_bytes_added` to understand when indexing operations complete. 

Batches are a data structure in the Search Service, used for processing data coming in from DCP to the documents in a Search index. 

| `curr_batches_blocked_by_herder`
a| The difference between the number of batches that have been indexed (`batch_bytes_removed`) and batches that have not yet been indexed (`batch_bytes_added`). 

The Search Service blocks batch indexing until there is sufficient memory available on a node. 

| `num_bytes_used_ram`
| The number of bytes used in memory by the Search Service. 

| `pct_cpu_gc`
| The percentage of CPU time spent by a Search index in garbage collection. 
Garbage collection involves cleanup actions like removing unnecessary index entries. 

| `tot_batches_flushed_on_maxops`
a| The total number of batches executed due to the batch size being greater than the maximum number of operations per batch.

Batches are a data structure in the Search Service, used for processing data coming in from DCP to the documents in a Search index. 
A batch is executed when it's flushed to disk. 
// Accurate?

| `tot_batches_flushed_on_timer`
a| The total number of batches executed at regular intervals. 

Batches are a data structure in the Search Service, used for processing data coming in from DCP to the documents in a Search index. 
A batch is executed when it's flushed to disk. 
// Accurate? 

| `tot_bleve_dest_closed`
| The total number of times a Search index partition closed to new Search requests. 
// Accurate?

| `tot_bleve_dest_opened`
a| The total number of times Search index partitions were created or reopened for new Search requests, or for ingesting data coming in from DCP.

Opening an index partition creates a file lock for concurrent access requests. 
// Accurate?

| `tot_grpc_listeners_closed`
a| The total number of gRPC listeners closed. 

gRPC listeners handle incoming connection requests to the Search Service.

The Search Service uses gRPC to manage scatter-gather operations across nodes when there are multiple nodes running the Search Service in a cluster. 
// Is this accurate? Over what time period?

| `tot_grpc_listeners_opened`
a| The total number of gRPC listeners opened. 

gRPC listeners handle incoming connection requests to the Search Service.

The Search Service uses gRPC to manage scatter-gather operations across nodes when there are multiple nodes running the Search Service in a cluster.
// Is this accurate? Over what time period?

| `tot_grpc_queryreject_on_memquota`
a| The total number of gRPC queries rejected because of the memory quota for the Search Service being less than the estimated memory required for merging search results from all partitions for the query. 

For more information about how to set this quota, see xref:fts:fts-advanced-settings-ftsMemoryQuota.adoc[].

The Search Service uses gRPC to manage scatter-gather operations across nodes when there are multiple nodes running the Search Service in a cluster.

| `tot_grpcs_listeners_closed`
a| The total number of gRPC SSL listeners closed. 

gRPC SSL listeners handle incoming SSL connection requests to the Search Service.

The Search Service uses gRPC to manage scatter-gather operations across nodes when there are multiple nodes running the Search Service in a cluster.
// Is this accurate? Over what time period? 

| `tot_grpcs_listeners_opened`
a| The total number of gRPC SSL listeners opened. 

gRPC SSL listeners handle incoming SSL connection requests to the Search Service.

The Search Service uses gRPC to manage scatter-gather operations across nodes when there are multiple nodes running the Search Service in a cluster.
// Is this accurate? Over what time period?

| `tot_http_limitlisteners_closed`
a| The total number of HTTP limit listeners closed. 

HTTP limit listeners manage limits on incoming HTTP requests to the Search Service. 
// Is this accurate? Over what time period?

| `tot_http_limitlisteners_opened`
a| The total number of HTTP limit listeners opened. 

HTTP limit listeners manage limits on incoming HTTP requests to the Search Service. 
// Is this accurate? Over what time period?

| `tot_https_limitlisteners_closed`
a| The total number of HTTPS limit listeners closed. 

HTTPS limit listeners manage limits on incoming HTTPS requests to the Search Service. 
// Is this accurate? Over what time period?

| `tot_https_limitlisteners_opened`
a| The total number of HTTPS limit listeners opened. 

HTTPS limit listeners manage limits on incoming HTTPS requests to the Search Service. 
// Is this accurate? Over what time period?

| `tot_queryreject_on_memquota`
a| The total number of Search queries rejected because of the memory quota for the Search Service being less than the estimated memory required for merging search results from all partitions for the query. 

For more information about how to set this quota, see xref:fts:fts-advanced-settings-ftsMemoryQuota.adoc[].
// Still the same setting?

| `tot_remote_grpc`
a| The total number of remote gRPC requests made to the Search Service. 

A request is remote if it comes from a different node in the cluster. 
// Accurate?

| `tot_remote_grpc_tls`
a| The total number of gRPC SSL requests made to the Search Service when adding clients. 
// WHAT DOES THIS MEAN 

| `tot_remote_http`
a| The total number of remote HTTP requests made to the Search Service. 

A request is remote if it comes from a different node in the cluster.

Remote HTTP requests are deprecated.
Use gRPC requests, instead. 
// Accurate?

| `tot_remote_http2`
a| The total number of remote HTTP SSL requests made to the Search Service. 

A request is remote if it comes from a different node in the cluster.

Remote HTTP requests are deprecated.
Use gRPC requests, instead. 
// Accurate?

| `total_gc`
a| The total number of garbage collection events triggered by the Search Service. 

Garbage collection events include removing unnecessary index entries. 
// Accurate?

| `total_queries_rejected_by_herder`
a| The total number of queries rejected by the Search Service when the memory used exceeds the quota set for a query. 

For more information about how to set this quota, see xref:fts:fts-advanced-settings-ftsMemoryQuota.adoc[].
// Is this the correct quota? 

| `BUCKET_NAME:INDEX_NAME:avg_grpc_internal_queries_latency`
a| The average time taken for a Search query's scatter-gather requests between the coordinator and other nodes running the Search Service.

The Search Service uses gRPC to manage scatter-gather operations across nodes when there are multiple nodes running the Search Service in a cluster.
The coordinator is the Search node that receives the Search request and scatters it to all other Search index partitions on other nodes. 

| `BUCKET_NAME:INDEX_NAME:avg_grpc_queries_latency`
a| The average time taken for each Search query that uses gRPC, in milliseconds for the given Search index. 

The Search Service uses gRPC to manage scatter-gather operations across nodes when there are multiple nodes running the Search Service in a cluster.

| `BUCKET_NAME:INDEX_NAME:avg_internal_queries_latency`
| The average latency, in milliseconds, for inter-node queries for the given Search index. 

| `BUCKET_NAME:INDEX_NAME:avg_queries_latency`
| The average latency, in milliseconds, for all Search queries on the given Search index. 

| `BUCKET_NAME:INDEX_NAME:batch_merge_count`
| This metric is for legacy index formats that are no longer supported.

| `BUCKET_NAME:INDEX_NAME:doc_count`
| The total number of documents in the given Search index. 

| `BUCKET_NAME:INDEX_NAME:iterator_next_count`
| This metric is for legacy index formats that are no longer supported.

| `BUCKET_NAME:INDEX_NAME:iterator_seek_count`
| This metric is for legacy index formats that are no longer supported.

| `BUCKET_NAME:INDEX_NAME:last_access_time`
| The last date and time that a query ran against the given Search index.

| `BUCKET_NAME:INDEX_NAME:num_bytes_live_data`
| This metric is no longer used.  

| `BUCKET_NAME:INDEX_NAME:num_bytes_used_disk`
| The total number of bytes used on disk by the given Search index. 

| `BUCKET_NAME:INDEX_NAME:num_bytes_used_disk_by_root`
a| The total number of bytes used on disk by the root segment of the given Search index.

The root segment includes all data for the Search index, excluding any segments that might be stale and will be removed by the persister or merger.
Segments are stale when they're replaced by a new merged segment created by the merger.
Stale segments are deleted when they're not used by any new queries. 

The `num_bytes_used_disk_by_root` value will be less than the `num_bytes_used_disk` value.

| `BUCKET_NAME:INDEX_NAME:num_files_on_disk`
| The total number of files on disk for the given Search index. 

| `BUCKET_NAME:INDEX_NAME:num_mutations_to_index`
| The DCP sequence numbers of changes that have not yet been indexed for the given Search index. 
// Accurate? 

| `BUCKET_NAME:INDEX_NAME:num_persister_nap_merger_break`
a| The number of times the persister was interrupted by the merger during a nap period. 

Each Search index partition has a merger and a persister. 

The persister reads in-memory segments from the disk write queue and flushes them to disk. 
The merger consolidates flushed files from the persister and flushes the consolidated result to disk through the persister, while purging the smaller, older files.
The persister and merger interact to continuously flush and merge new in-memory segments to disk. 

| `BUCKET_NAME:INDEX_NAME:num_persister_nap_pause_completed`
a| The number of times the persister completed its configured nap period before flushing content to disk, without being interrupted by the merger.

Each Search index partition has a merger and a persister. 

The persister reads in-memory segments from the disk write queue and flushes them to disk. 
The merger consolidates the flushed files from the persister and flushes the consolidated result to disk through the persister, while purging the smaller, older files.
The persister and merger interact to continuously flush and merge new in-memory segments to disk.  

| `BUCKET_NAME:INDEX_NAME:num_pindexes_actual`
| The total number of partitions currently in the given Search index. 

| `BUCKET_NAME:INDEX_NAME:num_pindexes_target`
| The total number of planned or expected partitions for the given Search index.

| `BUCKET_NAME:INDEX_NAME:num_recs_to_persist`
| The total number of entries, including terms, records, and dictionary rows, that have not yet been persisted to disk. 
// Accurate? What does this mean? 

| `BUCKET_NAME:INDEX_NAME:num_root_filesegments`
| The total number of file segments in the root segment. 
// What does this mean? 

| `BUCKET_NAME:INDEX_NAME:num_root_memorysegments`
| The total number of memory segments in the root segment. 
// What does this mean? 

| `BUCKET_NAME:INDEX_NAME:reader_get_count`
| This metric is for legacy index formats that are no longer supported.

| `BUCKET_NAME:INDEX_NAME:reader_multi_get_count`
| This metric is for legacy index formats that are no longer supported.

| `BUCKET_NAME:INDEX_NAME:reader_prefix_iterator_count`
| This metric is for legacy index formats that are no longer supported.

| `BUCKET_NAME:INDEX_NAME:reader_range_iterator_count`
| This metric is for legacy index formats that are no longer supported.

| `BUCKET_NAME:INDEX_NAME:timer_batch_store_count`
|
// ???

| `BUCKET_NAME:INDEX_NAME:timer_data_delete_count`
|
// ???

| `BUCKET_NAME:INDEX_NAME:timer_data_update_count`
|
// ???

| `BUCKET_NAME:INDEX_NAME:timer_opaque_get_count`
|
// ???

| `BUCKET_NAME:INDEX_NAME:timer_opaque_set_count`
|
// ???

| `BUCKET_NAME:INDEX_NAME:timer_rollback_count`
|
// ???

| `BUCKET_NAME:INDEX_NAME:timer_snapshot_start_count`
|
// ???

| `BUCKET_NAME:INDEX_NAME:total_bytes_indexed`
| The rate, in bytes per second, of content indexed in the given Search index. 
// Accurate?

| `BUCKET_NAME:INDEX_NAME:total_bytes_query_results`
| The size of results returned for Search queries on the given Search index.
This includes the size of all JSON sent. 

| `BUCKET_NAME:INDEX_NAME:total_compaction_written_bytes`
| The total number of bytes written to disk as a result of compaction operations on the given Search index.

| `BUCKET_NAME:INDEX_NAME:total_compactions`
| This metric is for legacy index formats that are no longer supported.

| `BUCKET_NAME:INDEX_NAME:total_grpc_internal_queries`
a| The total number of internal gRPC requests from the coordinating node for a Search query to other nodes running the Search Service, for the given Search index.

The Search Service uses gRPC to manage scatter-gather operations across nodes when there are multiple nodes running the Search Service in a cluster.
The coordinating node is the Search node that receives the Search request and scatters it to all other Search index partitions on other nodes.
The coordinating node applies filters to the results from all Search index partitions and returns the final result set. 

| `BUCKET_NAME:INDEX_NAME:total_grpc_queries`
| The total number of queries, using gRPC for streaming, for the given Search index.

| `BUCKET_NAME:INDEX_NAME:total_grpc_queries_error`
| The total number of queries that resulted in an error that used gRPC for streaming on the given Search index. 

| `BUCKET_NAME:INDEX_NAME:total_grpc_queries_slow`
| The total number of queries added to the slow query log that used gRPC for streaming on the given Search index. 

| `BUCKET_NAME:INDEX_NAME:total_grpc_queries_timeout`
| The total number of queries that timed out that used gRPC for streaming on the given Search index. 

| `BUCKET_NAME:INDEX_NAME:total_grpc_request_time`
a| The total time, in nanoseconds, for internal scatter-gather requests. 

The Search Service uses gRPC to manage scatter-gather operations across nodes when there are multiple nodes running the Search Service in a cluster.
The coordinating node is the Search node that receives the Search request and scatters it to all other Search index partitions on other nodes. 
The coordinating node applies filters to the results from all Search index partitions and returns the final result set.

| `BUCKET_NAME:INDEX_NAME:total_internal_queries`
a| The number of internal queries from the coordinating node for a Search query to other nodes running the Search Service, for the given Search index. 

The Search Service uses gRPC to manage scatter-gather operations across nodes when there are multiple nodes running the Search Service in a cluster.
The coordinating node is the Search node that receives the Search request and scatters it to all other Search index partitions on other nodes. 
The coordinating node applies filters to the results from all Search index partitions and returns the final result set. 
// What's the note about "per unit time"?

| `BUCKET_NAME:INDEX_NAME:total_queries`
| The total number of Search queries per second on the given Search index. 

| `BUCKET_NAME:INDEX_NAME:total_queries_error`
| The total number of Search queries on the given Search index that resulted in an error. 

| `BUCKET_NAME:INDEX_NAME:total_queries_slow`
a| The total number of Search queries on the given Search index in the slow query log. 

Slow queries are any queries that take longer than 5 seconds to run. 

| `BUCKET_NAME:INDEX_NAME:total_queries_timeout`
| The total number of Search queries on the given Search index that timed out. 

| `BUCKET_NAME:INDEX_NAME:total_request_time`
| The total time, in nanoseconds, spent processing Search query requests for the given Search index. 

| `BUCKET_NAME:INDEX_NAME:total_term_searchers`
a| The total number of term searchers for the given Search index. 

Every Search query requires one or more term searchers. 
More complex Search queries typically require more term searchers.

Use this statistic to approximate how complex a query is. 

| `BUCKET_NAME:INDEX_NAME:total_term_searchers_finished`
| The total number of term searchers on the given Search index that have finished serving a Search query.

| `BUCKET_NAME:INDEX_NAME:writer_execute_batch_count`
| This metric is for legacy index formats that are no longer supported.

|====