[#rest-bucket-change]
= Changing Bucket Parameters
:page-type: reference

[abstract]
To modify bucket parameters, use the `POST /pools/default/buckets/[bucket-name]` HTTP method and URI with the bucket name being the REST API endpoint.

== Description

You can modify existing bucket parameters by posting the updated parameters used to create the bucket to the bucket’s URI.
Do not omit a parameter in your request since this is equivalent to not setting it in many cases.
We recommend you do a request to get current bucket settings, make modifications as needed and then make your POST request to the bucket URI.

NOTE: The bucket name cannot be changed via the REST API.

IMPORTANT: When changing the active bucket configuration, specify the existing configuration parameters and the changed authentication parameters.

== Syntax

Curl request syntax:

----
curl -v -X POST -u [admin]:[password]
  -d name=[customer]
  -d flushEnabled=[0 | 1]
  -d replicaNumber=[value from 0 to 3]
  -d authType=[none | sasl]
  -d ramQuotaMB=[value]
  -d proxyPort=[port]
  http://[localhost]:8091/pools/default/buckets/[bucket-name]
----

== Example

Curl request example:

To edit the bucket `customer` on server node `10.5.2.54`:

----
curl -v -X POST -u Administrator:password \
  -d 'name=customer' \
  -d 'flushEnabled=0' \
  -d 'replicaNumber=1' \
  -d 'authType=none' \
  -d 'ramQuotaMB=200' \
  -d 'proxyPort=11212' \
  http://10.5.2.117:8091/pools/default/buckets/customer
----

== Response

If the request is successful, HTTP response 200 is returned with an empty data content.

----
202 OK
----

== Response codes

[cols="20,57"]
|===
| Response codes | Description

| 200
| OK
|===
