= Managing Index parameters
:page-topic-type: reference

[abstract]
The Index service parameters are retrieved and changed with the `GET` and `POST` HTTP methods and the `/settings/indexes` URI.

== Description

The Index service parameters include:

`indexerThreads`::
Number of dedicated threads the indexer uses.
On multi-core machines increasing this number increases the amount of CPU available to the indexer.
Default: 4

`maxRollbackPoints`::
The maximum number of committed rollback points.
Default: 5

`memorySnapshotInterval`::
Specifies the frequency of in-memory snapshots.
This determines the earliest possibility of a scan seeing a given KV mutation.
Specified in milleseconds (ms).
Default: 200

`stableSnapshotInterval`::
Specifies the frequency of persisted snapshots for recovery.
Specified in seconds (sec).
Default: 30000

== HTTP method and URI

----
GET /settings/indexes
POST /settings/indexes
----

== Syntax

Curl request syntax:

----
curl -X GET http://[localhost]:[port]/settings/indexes -u [admin-name]:[password]
----

== Example

Curl request example:

----
curl -X GET http://10.3.5.205:8091/settings/indexes -u Administrator:password
----

== Response

Example response:

----
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
102   102  102   102    0     0  52550      0 --:--:-- --:--:-- --:--:--   99k
{
    "indexerThreads": 4,
    "maxRollbackPoints": 5,
    "memorySnapshotInterval": 200,
    "stableSnapshotInterval": 30000
}
----
