= Rebalance API
:description: pass:q[When one or more nodes have been brought into or taken out of a cluster, _rebalance_ redistributes data, indexes, event processing, and query processing among available nodes.]
:page-topic-type: reference

[abstract]
{description}
Rebalance can be performed and configured by means of the REST API.

[#rest-rebalance-overview]
== REST Rebalance Overview

_Rebalance_ must be performed whenever the number of nodes in a cluster have changed, and whenever buckets have been added or removed.
A complete overview is provided in xref:learn:clusters-and-availability/rebalance.adoc[Rebalance].

The REST API supports the following:

* xref:rest-api:rest-cluster-rebalance.adoc[Rebalancing the Cluster].
Rebalance can be performed; specifying all current cluster-nodes, and specifying which (if any) are to be ejected.

* xref:rest-api:rest-get-rebalance-progress.adoc[Getting Rebalance Progress].
The progress of an ongoing rebalance to be ascertained.

* xref:rest-api:rest-configure-rebalance-retry.adoc[Configuring Rebalance Retries].
Rebalance failures can be responded to automatically, with up to 3 retries.
The number of seconds required to elapse between retries can also be configured.

* xref:rest-api:rest-get-rebalance-retry.adoc[Getting Rebalance-Retry Status].
The status of pending rebalance retries can be returned.

* xref:rest-api:rest-cancel-rebalance-retry.adoc[Canceling Rebalance Retries].
Rebalance retries can be canceled.

* xref:rest-api:rest-limit-rebalance-moves.adoc[Limiting Concurrent vBucket Moves].
The number of concurrent moves of vBuckets that occur during rebalance can be limited, with the limit applied to every node in the cluster; so as to increase rebalance performance.
