= Naming a Cluster

:description: pass:q[A cluster can be named, by means of the REST API.]
:page-topic-type: reference

[abstract]
{description}

[#http-method-and-uri]
== HTTP Method and URI

----
POST /pools/default
----

[#description]
== Description

Establishes a name for the cluster.
Either the Full Admin or the Cluster Admin role is required.

Once defined, the cluster name provides a convenient, verbal reference, which will never be used in programmatic or networked access.
The name can be of any length, can make use of any symbols (for example: %, $, !, #), and can include spaces.
The name can be changed at any time during the life of the cluster, irrespective of the cluster’s configuration.

== Curl Syntax

----
curl -X POST http://<ip-address-or-domain-name>:8091/pools/default \
-d clusterName=<cluster-name>
-u <username>:<password>
----

== Responses

Success returns `200 OK`.
If a username and password have already been assigned, failure to authenticate returns `401 Unauthorized`.
An incorrectly expressed URI or flag returns `404 Object Not Found`.

== Example

The following example establishes a name for the cluster.

----
curl -X POST http://10.144.220.101:8091/pools/default \
-d clusterName=MyNewCluster -u Administrator:password
----

== See Also

The sequence of tasks divided into _initialization_ and _provisioning_ is explained in xref:rest-api:rest-cluster-init-and-provisioning.adoc[Cluster Initialization and Provisioning].

For each of the other specific steps required in the provisioning process, see xref:rest-api:rest-configure-memory.adoc[Configuring Memory], xref:rest-api:rest-name-node.adoc[Naming a Node], xref:rest-api:rest-set-up-services.adoc[Assigning Services], and xref:rest-api:rest-establish-credentials.adoc[Establishing Credentials].

For general information on naming, see xref:learn:clusters-and-availability/nodes.adoc#naming-clusters-and-nodes[Naming Clusters and Nodes].

For further information on initialization and provisioning -- using the UI, the CLI, and the REST API -- see xref:manage:manage-nodes/node-management-overview.adoc[Manage Nodes and Clusters].
