= Setting Disk I/O Priority
:page-type: reference

[abstract]
The disk I/O priority for a bucket is set with the `/pools/default/buckets/[bucket-name]` URI and the `threadNumber` setting.

== HTTP method and URI

To set the maximum of thread workers, use the `threadsNumber` option.
To specify high priority, assign eight (8) threads.
To specify low priority, assign three (3) threads.
Default: `threadsNumber=3`.
Only high or low priority are allowed.

----
POST /pools/default/buckets/[bucket_name]
----

The ``threadNumber``parameter is used to specify disk I/O priority for a bucket.

IMPORTANT: When editing bucket properties, be sure to specify all bucket properties.
If a bucket property is not specified (whether or not you are changing the existing value), Couchbase Server may reset the property to the default.
Even if you do not intend to change a certain property, re-specify the existing value to avoid this behavior.

== Syntax

Curl request syntax:

----
curl -v -X POST -u [admin]:[password]
  http://[localhost]:8091/pools/default/buckets/[bucket-name]
  -d threadsNumber=[3 | 8]
----

== Example

The following example sets the `threadsNumber` for the default bucket to eight (8), which is high priority, from the default of three (3), which is low priority.

----
curl -v -X POST -u Administrator:password \
  http://10.5.2.54:8091/pools/default/buckets/default \
  -d 'threadsNumber=8'
----
