= Assigning Services on an Existing Node

:description: pass:q[Use the REST API to assign or remove services on an existing node in a cluster, and rebalance the cluster.]
:page-topic-type: reference

[abstract]
{description}

[#http-method-and-uri]

=== HTTP Method and URI

----
POST /controller/rebalance
----

== Description

Use the following REST API to add or remove non-Data services on the existing nodes in a cluster.
Then trigger a rebalance operation.

[NOTE]
====
* Follow the xref:manage:manage-nodes/modify-services-and-rebalance.adoc#prerequisites[Prerequisites] in xref:manage:manage-nodes/modify-services-and-rebalance.adoc[Modify Services and Rebalance] before using the REST API.

* For information about using the `POST /controller/rebalance` REST API to rebalance after node additions and removals, after a graceful failover and recovery, and after a hard failover, see xref:rest-api:rest-cluster-rebalance.adoc[Rebalancing the Cluster].
====

=== curl Syntax

You must specify all known nodes in the cluster and the necessary cluster services topology.

----
curl -v -X POST -u [admin]:[password] \
http://[localhost]:8091/controller/rebalance \
[-d knownNodes | -d topology]
----

These are services related parameters:

* `knownNodes`: The value is a list containing all nodes that are in the cluster at the start of the rebalance process.

* `topology`: The value is a list of services and the nodes in which services must reside, after the rebalance operation completes.
+
The value is `topology[<service>]=<list of nodes>`.
+
Where,

** `<service>` can be one of the following services:

*** `fts` for the Search Service.
*** `index` for the Index Service.
*** `n1ql` for the Query Service.
*** `backup` for the Backup Service.
*** `cbas` for the Analytics Service.

** `<list of nodes>` indicate the nodes on which the `<service>` must reside in after the rebalance operation is complete.
The node names are separated by commas.
+
If a `<service>` is running on any node in the cluster that's not in this list, Couchbase Server removes that `<service>` during the rebalance operation.
For more information, see xref:rest-api:rest-cluster-rebalance.adoc[Rebalancing the Cluster].

** For example, `-d topology[<service>]=otp_node1,otp_node2`.

NOTE: The rebalance occurs even if no `<service>` is changed.

Each service you assign uses the memory quota currently configured for that service on the cluster.
You can modify the services memory quotas, if needed, prior to running the services reconfiguration command for the cluster nodes.

For information about allocating memory per service, see xref:rest-api:rest-configure-memory.adoc[Configuring Memory].

To fetch the details of current memory allocation for each service, see xref:rest-api:rest-get-memory-information.adoc[Getting Memory Information].

== Required Permissions

`Full Admin` role.

[#responses]
== Responses

|===
|Value | Description  

| `200 OK` and JSON array containing the expired backups and their details.
| Successful call.

| `400`
| Invalid parameter.

| `400 Object Not found`
| The repository in the endpoint URI does not exist.

| `401 Unauthorized`
|  Authorization failure due to incorrect username or password.

| `403 Forbidden`, plus a JSON message explaining the minimum permissions.
| The provided username has insufficient privileges to call this method.

| `404 Object Not Found`
| Error in the URI path.

| `500 Internal Server Error`
| Error in Couchbase Server.
|===

=== Example

For illustration, consider 5 nodes in the cluster with the following services:

* 172.23.108.69 – Data, Index, Query
* 172.23.108.70 – Data, Search, Query
* 172.23.108.71 – Query
* 172.23.108.72 – Backup
* 172.23.108.73 – Analytics

Reconfigure the services on the existing nodes so that the following is the required output of services on each of the 5 nodes:

* 172.23.108.69 – Data, Query
* 172.23.108.70 – Data, Index
* 172.23.108.71 – Index, Query
* 172.23.108.72 – Search, Query
* 172.23.108.73 – Analytics

Because the Backup service is not in the topology list, it will be removed from the cluster.
After the topology change and rebalance, two nodes (172.23.108.71 and 172.23.108.72) that previously had no services using the index disk storage path will now have services using it.

Run the following command to reconfigure the services on the existing nodes and get the required output.

----
curl -u Administrator:password -X POST 172.23.108.69:8091/controller/rebalance \
-d "knownNodes=ns_1@172.23.108.69,ns_1@172.23.108.70,ns_1@172.23.108.71,ns_1@172.23.108.72,ns_1@172.23.108.73"  \
-d "topology[index]=ns_1@172.23.108.70,ns_1@172.23.108.71"  \
-d "topology[fts]=ns_1@172.23.108.72"  \
-d "topology[n1ql]=ns_1@172.23.108.69,ns_1@172.23.108.71,ns_1@172.23.108.72" \
-d "topology[cbas]=ns_1@172.23.108.73"
---- 

== See Also

* To retrieve the list of services running on a node, see xref:rest-api:rest-list-node-services.adoc[Listing Node Services].

* For information about allocating memory per service, see xref:rest-api:rest-configure-memory.adoc[Configuring Memory].

* To fetch the details of current memory allocation for each service, see xref:rest-api:rest-get-memory-information.adoc[Getting Memory Information].

* For information about assigning services to existing nodes from the UI and CLI, see xref:manage:manage-nodes/modify-services-and-rebalance.adoc[Modify Services and Rebalance].

* For information about assigning services to a new node, see xref:rest-api:rest-set-up-services.adoc[Assigning Services to a New Single Node].

* For information about rebalancing, see xref:rest-api:rest-cluster-rebalance.adoc[Rebalancing the Cluster].