= Getting Rebalance Progress
:page-topic-type: reference

[abstract]
The progress of rebalance can be ascertained with either the `POST /pools/default/rebalanceProgress` HTTP method and URI.

[#rest-cluster-rebalance-description]
== Description

When one or more nodes have been brought into a cluster, or have been taken out of a cluster, _rebalance_ redistributes data and indexes among available nodes.
The ongoing progress of the rebalance operation can be monitored.

=== HTTP method and URI

----
POST /pools/default/rebalanceProgress
----

=== Curl Syntax

----
curl -v -X POST -u [admin]:[password]
  http://[localhost]:8091/pools/default/rebalanceProgress
----

== Examples

{"status":"none"}

Node `10.143.190.103` has been added to a cluster of two nodes, which are `10.143.190.101` and `10.143.190.102`.

Rebalance is then initiated.
During rebalance, progress is ascertained as follows.
Note that output is piped to the tool `jq`, to ensure readability.

----
curl -u Administrator:password -v -X GET 10.143.190.101:8091/pools/default/rebalanceProgress | jq '.'
----

The output is as follows:

----
{
  "status": "running",
  "ns_1@10.143.190.101": {
    "progress": 0.1103515625
  },
  "ns_1@10.143.190.102": {
    "progress": 0.1095890410958904
  },
  "ns_1@10.143.190.103": {
    "progress": 0.3299120234604106
  }
}
----

The output thus features `progress` for each of the three nodes, specified as a ten-place floating-point number.
(Note that if Couchbase Web Console is simultaneously used to monitor the rebalance, these decimals are represented as _11.0%_, _10.9%_, and _32.9%_ respectively.)

When rebalance has concluded, running the method again returns the following:

----
{
  "status": "none"
}
