= Creating XDCR Replications
:page-topic-type: reference

[abstract]
To create an XDCR replication, use the `POST /controller/createReplication` HTTP method and URI.

== Description

Data replication occurs from a source cluster to a destination cluster.
Once a replication is created, data replication between clusters automatically begins.

== HTTP method and URI

----
POST /controller/createReplication
----

== Syntax

Curl request syntax:

----
curl -v -X POST -u [admin]:[password]
  http://[localhost]:[port]/controller/createReplication
  -d fromBucket=[bucket-name]
  -d toCluster=[cluster-name]
  -d toBucket=[bucket-name]
  -d replicationType=continuous
  -d type=[capi | xmem]
  -d compressionType=["None" | "Auto" | "Snappy"]
  -d filterExpression=[expression]
  -d filterDeletion=[true | false]
  -d filterExpiration=[true | false]
----

The `type` values, capi and xmem, are respectively represented by Version 1 and Version 2 in the web console.
The default value is xmem.
If the default is to be used, this parameter does not need to be specified.

The `replicationType` value is always `continuous`.

A `compressionType` value of `None` specifies that data compression is not used during replication.
A value of `Snappy` specifies that the open-source Snappy library is used to provide data compression during replication: however, this is only supported for target clusters running Couchbase Server 5.5 and later.
If `Snappy` is specified for a pre-5.5 cluster, an error is returned, and replication does not proceed.
The default value, `Auto`, specifies that either None or Snappy is applied, depending on the version of the target cluster. If the target cluster is running version 5.5 or later, Auto is resolved to Snappy, and replication proceeds in compressed form.
If the target cluster is running a pre-5.5 version, Auto is resolved to None, and replication proceeds in uncompressed form.

The optional `filterExpression` is matched against the _id_s, field-names, values, and extended attributes of documents in the source bucket.
Each document that produces a successful match is replicated; other documents are not replicated.
For supported expressions, see xref:xdcr-reference:xdcr-filtering-reference-intro.adoc[XDCR Advanced Filtering Reference].

The optional `filterDeletion` and `filterExpiration` flags indicate whether mutations corresponding respectively to the deletion and expiration of documents on the source cluster should be either _filtered out_ of the replication to the target cluster, or allowed to remain in.
For each flag, a value of `true` means that the mutation _is_ filtered out, ensuring that it is _not_ replicated to the target cluster; while a value of `false` (the default) means that the mutation is _not_ filtered out, ensuring that it _is_ replicated to the target cluster.

== Example

The following example creates a replication between the `source` and `remote` buckets.
The `remote` bucket is located on a cluster named `10.142.171.101`.
Note that data compression is enabled, by specifying the value `1` (specifying `0` disables compression).

----
curl -v -X POST -u Administrator:password \
http://127.0.0.1:8091/controller/createReplication \
-d fromBucket=source \
-d toCluster=10.142.171.101 \
-d toBucket=remote \
-d replicationType=continuous \
-d compressionType="Snappy"
----

Raw HTTP request:

----
POST / HTTP/1.1
Authorization: Basic QWRtaW5pc3RyYXRvcjpwYXNzd29yZDE=
User-Agent: curl/7.21.4 (universal-apple-darwin11.0) libcurl/7.21.4 OpenSSL/0.9.8r zlib/1.2.5
Host: 10.4.2.4:8091
Accept: */*
Content-Length: 126
Content-Type: application/x-www-form-urlencoded
----

== Response

If the replication is created, data replication immediately begins replicating data from the source to destination cluster and a response similar to the following is returned.

----
{
  "id": "9eee38236f3bf28406920213d93981a3/beer-sample/remote_beer"
  }
----

The unique document ID returned in the JSON is a reference that can be used to delete the replication.
