= Cluster Initialization and Provisioning

:description: pass:q[The Couchbase REST API can be used to initialize an individual node, and to provision it so that it becomes a single-node cluster, to which further nodes can be added.]
:page-topic-type: reference

[abstract]
{description}

== APIs in this Section

Once a newly installed instance of Couchbase Server has been started for the first time, the Couchbase REST API can be used to:

* _Initialize_.
This means optionally to specify, for the current node, the following:

** Custom disk paths for the Data, Index, Eventing, and Analytics Services.

** A custom location for the Java SDK to be used by the Analytics Service.

** A node-name.

* _Provision_.
This means to establish, for the current node:

** The default disk paths for the Data, Index, Eventing, and Analytics Services; when custom disk paths have not been previously established through initialization.

** The default location for the Java SDK to be used by the Analytics Service; when no custom location has been previously established through initialization.

** A node-name, if no such name has previously been established through initialization.

** A name for the entire cluster.

** Services that will reside on the node, and their memory allocations.

** Username and password for the administrator creating the cluster -- the administrator will have Full Admin credentials.
Once the username and password are established, the cluster is considered fully provisioned, and can be accessed by means of user login.

Note, therefore, that _initializing_ is an optional first step, which allows certain access-paths to be established for and retained by the node, even after it is is subsequently added to a different cluster.

Once the one-node cluster has been provisioned, other nodes can be added to the cluster, to form a multi-node cluster.

Note that when an already provisioned node is added to another cluster, the node loses its former provisioning, and must be reprovisioned.

For detailed conceptual information, see xref:learn:clusters-and-availability/nodes.adoc[Nodes].

The REST API described in this section is summarized below.

include::partial$rest-cluster-init-and-configuration-table.adoc[]
