= Managing XDCR Internal Settings
:description: Internal settings for XDCR can be inspected and modified.
:page-topic-type: reference

[abstract]
{description}

== HTTP methods and URIs

----
GET /xdcr/internalSettings

POST /xdcr/internalSettings
----

[#description]
== Description

Internal settings for XDCR can be inspected and modified by means of the `/xdcr/internalSettings` URI, and the `GET` and `POST` methods.
When the `POST` method is used, one or more individual settings should be specified as arguments, each with an accompanying value.

[#curl-syntax]
== Curl Syntax

----
curl -u <username>:<password> -X GET \
  http://[ localhost | 127.0.0.1 ]:9998/xdcr/internalSettings

curl -u <username>:<password> -X POST \
  http://[ localhost | 127.0.0.1 ]:9998/xdcr/internalSettings
    [ -d <internalSetting>=<value> ]*
----

Note that although these commands return and modify XDCR internal settings for the entire cluster, each command must be executed on an individual cluster-node; and must refer to that node by means of the _loopback_ naming convention: that is, either as `localhost` or as `127.0.0.1`.
In each case, the XDCR port `9998` must be specified.

The node on which execution occurs does not need to be a Data-Service node.

[#responses]
== Responses

If successful, `GET` and `POST` commands return `200 OK`; and a JSON object containing all current XDCR internal settings.

Failure to authenticate returns `401 Unauthorized`.
A URI featuring an incorrect hostname or port returns a `failure to connect` message.

[#example]
== Examples

The following example returns the current XDCR internal settings for the current node.
Note that the output is piped to the https://stedolan.github.io/jq/[jq^] command, to facilitate readability.

----
curl -u Administrator:password -X GET http://localhost:9998/xdcr/internalSettings | jq '.'
----

If successful, the command returns output such as the following:

----
{
  "AuditReadTimeout": 1,
  "AuditWriteTimeout": 1,
  "BackfillPersistInterval": 1000,
  "BypassSanInCertificateCheck": 0,
  "CapiBatchTimeout": 180,
  "CapiDataChanSizeMultiplier": 1,
  "CapiMaxRetryBatchUpdateDocs": 6,
  "CapiReadTimeout": 60,
  "CapiRetryInterval": 500,
  "CapiWriteTimeout": 10,
  "ChangesLeftThresholdForOngoingReplication": 200000,
  "CpuCollectionInterval": 2000,
  "DefaultHttpTimeout": 180,
  "ExtraQuotaForUnderutilizedCPU": 10,
  "FilteringInternalKeyKey": "[$%XDCRInternalKey*%$]",
  "FilteringInternalXattrKey": "[$%XDCRInternalMeta*%$]",
  "HELOTimeout": 120,
  "HealthCheckIntervalSec": 120,
  "HealthCheckTimeoutSec": 10,
  "IntervalForThrottlerCalibration": 4,
  "JsNumWorkers": 4,
  "JsWorkerMemQuotaBytes": 1572864,
  "KeepAlivePeriod": 30,
  "ManifestRefreshSrcInterval": 2,
  "ManifestRefreshTgtInterval": 60,
  "MaxCheckpointRecordsToKeep": 5,
  "MaxCheckpointRecordsToRead": 5,
  "MaxCountBacklogForSetDcpPriority": 5,
  "MaxCountCpuNotMaxed": 3,
  "MaxCountDCPStreamsInactive": 10,
  "MaxCountNoBacklogForResetDcpPriority": 300,
  "MaxCountThroughputDrop": 3,
  "MaxLengthSnapshotHistory": 200,
  "MaxNumOfMetakvRetries": 4,
  "MaxNumberOfAsyncListeners": 4,
  "MaxRetryCapiService": 5,
  "MaxRetryForLiveUpdatePipeline": 5,
  "MaxRetryTargetStats": 6,
  "MaxTopologyChangeCountBeforeRestart": 30,
  "MaxTopologyStableCountBeforeRestart": 30,
  "MaxWorkersForCheckpointing": 5,
  "MemStatsLogInterval": 120,
  "NumberOfSlotsForBandwidthThrottling": 10,
  "NumberOfSlotsForThroughputThrottling": 10,
  "PercentageOfBytesToSendAsMin": 30,
  "RefreshRemoteClusterRefInterval": 15,
  "RemoteClusterAlternateAddrChangeKey": 5,
  "ReplSpecCheckInterval": 15,
  "ReplStatusExportBrokenMapTimeoutSec": 5,
  "ReplStatusLoadBrokenMapTimeoutSec": 5,
  "ReplicationSpecGCCnt": 4,
  "ResourceManagementInterval": 1000,
  "ResourceManagementRatioBase": 100,
  "ResourceManagementRatioUpperBound": 90,
  "ResourceManagementStatsInterval": 10000,
  "ResourceMgrKVDetectionRetryInterval": 60,
  "RetryIntervalMetakv": 500,
  "RetryIntervalTargetStats": 1000,
  "ShortHttpTimeout": 20,
  "StatsLogInterval": 30,
  "StopwatchDiagExternalThresholdMs": 5000,
  "StopwatchDiagInternalThresholdMs": 2000,
  "ThresholdForThroughSeqnoComputation": 100,
  "ThresholdPercentageForEventChanSizeLogging": 90,
  "ThresholdRatioForProcessCpu": 95,
  "ThresholdRatioForTotalCpu": 95,
  "ThroughputSampleAlpha": 15,
  "ThroughputSampleSize": 1028,
  "ThroughputThrottlerClearTokensInterval": 3000,
  "ThroughputThrottlerLogInterval": 10000,
  "TimeoutCheckpointBeforeStop": 180,
  "TimeoutDcpCloseUprFeed": 3,
  "TimeoutDcpCloseUprStreams": 3,
  "TimeoutHttpsPortLookup": 2,
  "TimeoutPartsStart": 30,
  "TimeoutPartsStop": 10,
  "TimeoutRuntimeContextStart": 30,
  "TimeoutRuntimeContextStop": 5,
  "TopologyChangeCheckInterval": 10,
  "TopologySvcCooldownPeriodSec": 60,
  "TopologySvcErrCooldownPeriodSec": 120,
  "UprFeedBufferSize": 1048576,
  "UprFeedDataChanLength": 20000,
  "WaitTimeBetweenMetadataChangeListeners": 500,
  "WaitTimeForLiveUpdatePipeline": 2000,
  "XmemBackoffTimeNewConn": 1000,
  "XmemBackoffWaitTime": 10,
  "XmemDefaultRespTimeout": 1000,
  "XmemMaxBackoffFactor": 10,
  "XmemMaxBatchSize": 50,
  "XmemMaxDataChanSize": 10485760,
  "XmemMaxIdleCount": 60,
  "XmemMaxIdleCountLowerBound": 10,
  "XmemMaxIdleCountUpperBound": 120,
  "XmemMaxReadDownTime": 60,
  "XmemMaxRetry": 5,
  "XmemMaxRetryInterval": 300,
  "XmemMaxRetryIntervalMutationLocked": 30,
  "XmemMaxRetryMutationLocked": 20,
  "XmemMaxRetryNewConn": 10,
  "XmemReadTimeout": 120,
  "XmemSelfMonitorInterval": 6,
  "XmemWriteTimeout": 120
}
----

To modify a value (for example, that of `HealthCheckIntervalSec`), enter a command such as the following.
Note that the output of the command is piped both to https://stedolan.github.io/jq/[jq^] and to the standard utility `grep`, to delimit the output.

----
curl -u Administrator:password -X POST http://localhost:9998/xdcr/internalSettings -d HealthCheckIntervalSec=190 | jq '.' | grep 'Health'
----

If execution is successful, output such as the following is displayed:

----
"HealthCheckIntervalSec": 190,
"HealthCheckTimeoutSec": 10,
----

This confirms that the value of `HealthCheckIntervalSec` has been successfully changed.

[#see-also]
== See Also

The REST call for creating a replication and specifying parameters is described in xref:rest-api:rest-xdcr-create-replication.adoc[Creating XDCR Replications].
An overview of XDCR is provided in xref:learn:clusters-and-availability/xdcr-overview[XDCR Overview].
Additional, _advanced_ settings that can be configured by means of the REST API are provided at xref:rest-api:rest-xdcr-adv-settings.adoc[Managing XDCR Advanced Settings].
