= Cluster Initialization and Provisioning

:description: pass:q[The Couchbase REST API can be used to initialize an individual node; and to provision it, so that it becomes a single-node cluster, to which further nodes can then be added.]
:page-topic-type: reference

[abstract]
{description}

== APIs in this Section

Once a newly installed instance of Couchbase Server has been started for the first time, the Couchbase REST API can be used to:

* _Initialize_.
This means optionally to specify, for the current node, the following:

** Custom disk paths for the Data, Index, Eventing, and Analytics Services.

** A custom location for the Java Runtime Environment to be used by the Analytics Service.

** A node-name.

* _Provision_.
This means to establish, for the current node:

** The default disk paths for the Data, Index, Eventing, and Analytics Services; in cases where custom disk paths have not been previously established through initialization.

** The default location for the Java Runtime Environment to be used by the Analytics Service; in cases where no custom location has been previously established through initialization.

** A node-name, in cases where no such name has previously been established through initialization.

** A name for the entire cluster.

** Services that will reside on the node, and their individual memory allocations.

** A username and password for the administrator creating the cluster -- the administrator will have Full Admin credentials.
Once the username and password are established, the cluster is considered fully provisioned, and Couchbase Web Console can be accessed by means of user login.

If username and password are established _before_ the other provisioning APIs have been used, any such calls made subsequently must be authenticated: however, prior to username and password being established, the other provisioning APIs can be used without authentication.
For information on roles, see xref:learn:security/roles.adoc[Roles].

Note that _initializing_ is an optional first step in node-configuration, which allows custom access-paths to be established for the node.
Note also that these paths will be retained even should the node subsequently added to a different cluster.

Once the one-node cluster has been provisioned, other nodes can be added to the cluster, to form a multi-node cluster.

Note that when a provisioned node is added to another cluster, the node loses all aspects its provisioning; and must be reprovisioned, as part of the node-addition process.

For detailed conceptual information on initialization, provisioning and all other principal aspects of node-management, see xref:learn:clusters-and-availability/nodes.adoc[Nodes].
For information on specifying a Java Runtime Environment, see the description of xref:install:install-environments.adoc[Additional Requirements] provided for the install process.
For information on creating and maintaining buckets, subsequent to cluster-creation, see xref:rest-api:rest-bucket-intro.adoc[Buckets API].

The REST API described in this section is summarized below.

include::partial$rest-cluster-init-and-configuration-table.adoc[]
