= Retrieving Log Information
:page-topic-type: reference

[abstract]
Log information can be retrieved with either the `GET /diag` or the `GET /sasl_logs` http method and URI.

== HTTP method and URI

----
GET /diag

GET /sasl_logs/[log-name]
----

[#description]
== Description

The `GET /diag` http method and URI returns general Couchbase Server diagnostic information.

The `GET /sasl_logs` http method and URI returns all the information currently residing in the Couchbase Server _log_ files.
Specifying an individual `log-name` returns the information contained in that log file, if the log file exists.

For general information on logging and log files, including the location of all log files, see xref:manage:manage-logging/manage-logging.adoc[Manage Logging].

== Curl Syntax

----
curl -v -X GET -u [admin]:[password] http://[hostname]:8091/diag

curl -v -X GET -u [admin]:[password] http://[hostname]:8091/sasl_logs[log-name]
----

The `log-name` argument can be any one of the following, each of which is a Couchbase Server log file:

[cols="2,2"]
|===
| `audit`
| `babysitter`
| `couchdb`

| `debug`
| `error`
| `goxdcr`

| `http_access`
| `info`
| `json_rpc`

| `mapreduce_errors`
| `memcached`
| `metakv`

| `ns_couchdb`
| `reports`
| `ssl_proxy`

| `stats`
| `views`
| `xdcr_target`

|===

If no `log-name` argument is specified, the default value is `debug`; whereby the contents of the `debug.log` file are displayed.

[#responses]
== Responses
Success gives `200 OK`, displays a message confirming the name of the log file to be displayed, and then displays the current contents of the log file.
A `log-name` that is either incorrectly specified, or corresponds to a log file that does not currently exist, gives `404 Object Not Found.``
Failure to authenticate gives `401 Unauthorized`.

=== Example

Curl request example to retrieve SSL proxy log information:

----
curl -v -X GET -u Administrator:password \
  http://10.5.2.118:8091/sasl_logs/ssl_proxy
----

=== Response

Returns information similar to the following:

----
* About to connect() to 10.5.2.118 port 8091 (#0)
*   Trying 10.5.2.118... connected
* Connected to 10.5.2.118 (10.5.2.118) port 8091 (#0)
* Server auth using Basic with user 'Administrator'
> GET /sasl_logs/ssl_proxy HTTP/1.1
> Authorization: Basic QWRtaW5pc3RyYXRvcjpwYXNzd29yZA==
> User-Agent: curl/7.21.4 (x86_64-unknown-linux-gnu) libcurl/7.21.4 OpenSSL/0.9.8b zlib/1.2.3
> Host: 10.5.2.118:8091
> Accept: */*
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Server: Couchbase Server
< Pragma: no-cache
< Date: Thu, 06 Feb 2014 22:50:12 GMT
< Content-Type: text/plain; charset=utf-8
< Cache-Control: no-cache
<
logs_node (ssl_proxy):
-------------------------------
[ns_server:info,2014-01-24T11:25:18.066,nonode@nohost:<0.30.0>:ns_ssl_proxy:init_logging:84]Brought up ns_ssl_proxy logging
[error_logger:info,2014-01-24T11:25:18.082,nonode@nohost:error_logger<0.5.0>:ale_error_logger_handler:log_report:72]
=========================PROGRESS REPORT=========================
          supervisor: {local,ns_ssl_proxy_sup}
             started: [{pid,<0.64.0>},
                       {name,ns_ssl_proxy_server_sup},
                       {mfargs,{ns_ssl_proxy_server_sup,start_link,[]}},
                       {restart_type,permanent},
                       {shutdown,infinity},
                       {child_type,supervisor}]
----
