= Authentication API
:description: Couchbase Server supports authentication via local and external domains.

[abstract]
{description}

[#authenticating-externally]
== Authenticating Locally and Externally

Couchbase users may be given an identity _locally_ on a cluster.
This allows their credentials to be maintained and updated on the local cluster.
A _password policy_ is enforced for the cluster: the defaults for this policy can be modified.
A local user can change their own password.

Enterprises frequently centralize directory services, allowing all user-authentication to be handled by a single server or server-group.
LDAP is frequently used in support of such centralization.
The authentication handled in this way is therefore _external_ to Couchbase Server.

Couchbase Server supports external authentication.
Users are registered as _external_, for authentication purposes.
When such users pass their credentials to Couchbase Server, Couchbase Server recognizes the user as external, and duly passes the credentials to the external authentication facility: if the authentication succeeds there, Couchbase Server is informed, and the user is given appropriate access, based on the roles and privileges on Couchbase Server that they have been assigned.

The default password policy is described in xref:learn:security/native-authentication.adoc#password-strength[Password Strength].
For further information on _local_ and _external_ domains, see xref:learn:security/authentication-domains.adoc[Authentication Domains].

[#ldap-groups]
=== LDAP Groups

LDAP supports _groups_, of which multiple users can be members.
Couchbase Server supports the association of LDAP groups with Couchbase-Server groups: a user successfully authenticated on an LDAP server may have their LDAP group information duly returned to Couchbase Server.
If Couchbase Server has configured an association between one or more of the user's LDAP groups and corresponding groups defined on Couchbase Server, the user is assigned the roles and privileges for the corresponding Couchbase-Server groups.

[#external-authentication-configuration-options]
== Configuration Options

Couchbase provides a recommended REST method for simple and expedited configuration of LDAP-based authentication.
This is described in xref:rest-api:rest-configure-ldap.adoc[Configure LDAP].

Couchbase Server can also accept a signed token from an identity provider, in place of a username and password.
Configure this with xref:rest-api:rest-configure-jwt.adoc[Configure JWT].
Once configured, you authenticate a REST API call by sending the token in the `Authorization` header as a bearer token instead of using basic authentication:

[source,console]
----
curl -H "Authorization: Bearer $TOKEN"      https://localhost:18091/pools/default
----

For more information, see xref:manage:manage-security/authenticate-using-jwt.adoc[Authenticate Using a JWT].

Alternatively, a xref:rest-api:rest-configure-saslauthd.adoc[legacy] REST API for establishing SASL administrator credentials can be used.
Note that this requires prior, manual set-up of saslauthd for the cluster: see xref:manage:manage-security/configure-saslauthd.adoc[Configure saslauthd].

== APIs in this section

A complete list of APIs described in this section is provided in the table below.

=== Authentication

include::partial$rest-security-authentication-table.adoc[]
