= Configure Auditing

[abstract]
Couchbase Server _event auditing_ can be configured, per node.

== HTTP methods and URIs

----
GET /settings/audit

POST /settings/audit

GET /settings/audit/descriptors
----

[#description]
== Description

The `GET` and `POST` methods used with the `/settings/audit` URI respectively read and write the configuration of Couchbase-Server _event auditing_.
This includes the enablement and disablement of auditing, the establishment of an audit-log location, the specification of the time-period on completion of which log files are to be rotated, and the retrieval of current settings.

The `GET` method used with the `/settings/audit/descriptors` URI returns a document that lists available audit events; providing an _id_, _name_, _module_, and _description_ for each.
The _id_ can be used in interpreting the output from `POST /settings/audit`, and in determining input-values for `GET /settings/audit`.

*Syntax:*

----
curl -X GET -u Administrator:password http://<host>:<port>/settings/audit

curl -X POST -u Administrator:password http://<host>:<port>/settings/audit
  -d auditdEnabled=[ true | false ]
  -d logPath=[ pathname ]
  -d rotateInterval=[ integer ]
  -d rotateSize=[ integer ]
  -d disabled=[ *{ event-id }, ]
  -d disabledusers=[ *{ local-user | external-user | internal-user }, ]

curl -X GET -u Administrator:password
  http://<host>:<port>/settings/audit/descriptors
----

The parameters for the POST method are all optional, and are as follows:

* The `auditdEnabled` parameter takes a value of `true` or `false`, and thereby either enables or disables auditing on the node.
Other values can still be configured, even if `auditdEnabled` is set to `false`.
Note that even when `auditEnabled` is `false`, a default subset of important events will continue to be audited, unless and until explicitly disabled.

* The `logPath` parameter specifies the pathname of the directory to which the `audit.log` file is written.

* The `rotateInterval` parameter specifies the maximum time-period that is to elapse between log-rotations.
Its value must be a number of seconds, in the range of 900 (15 minutes) to 604800 (7 days), inclusive.

* The `rotateSize` parameter specifes the maximum size to which the `audit.log` file is permitted to grow, before being rotated.
It value must be a number of bytes, in the range of 0 to 524288000 (500 MB), inclusive.

* The `disabled` parameter indicates which individual events are disabled.
Its value must be one or more audit-event ids, specified as a comma-separated list, without spaces.
Audit-event ids can be retrieved by means of the `GET /settings/audit/descriptors` method and URI.
+
If `auditdEnabled` is `true`, and `disabled` is not specified, a default subset of available audit events is disabled.

* The `disabledUsers` parameter disables event-auditing on a per user basis.
Its value must be a list of users, specified as a comma-separated list, with no spaces.
Each user may be:

** A local user, specified in the form `localusername/local`.

** An external user, specified in the form `externalusername/external`.

** An internal user, specified in the form `@internalusername/local`.

+
Available internal users are `@eventing`, `@cbq-engine`, `@ns_server`, `@index`, `@projector`, `@goxdcr`, `@fts`, and `@cbas`.

+
If `auditdEnabled` is `true`, and one or more users are specified as the value to `disabledUsers`, a subset of important events will continue to be audited for those users by default; unless and until such events are individually, explicitly disabled.

== Responses

For each method and URI, success gives `200 OK`.
A malformed URI gives `400 Object Not Found`.
Failure to authenticate gives `401 Unauthorized`.

=== Returned-Object Contents

The `GET /settings/audit/descriptors` method and URI return a document containing a list of available audit events.
For each audit event, the following are provided:

* _id_: An integer, such as `20489`, which is the identifier for the event.

* _name_: A string, which is the name of the event.
For example, `"document read"`.

* _module_: A string, specifying the system-module within which the event was generated.
For example, `"memcached"`.

* _description_: A string, providing a description of the event.
For example, `"Document was read"`.

The `GET /setttings/audit` method and URI return an object that contains the following:

* _disabled_: An array of event-ids, each of which corresponds to an event currently disabled.

* _uid_: An identifier for system use, corresponding to the current state of the audit-configuration.

* _auditEnabled_: A boolean value, indicating whether or not auditing is enabled on the node.

* _disabledusers_: An array, each of whose members is a currently disabled user.
Each member is an object of two elements, which are the _name_ of the disabled user and their _domain_.

* _logPath_: The current value of the pathname to which the `audit.log` file is being written.

* _rotateInterval_: An integer that is the number of seconds in the maximum timeperiod on who elapse the log file is rotated.

* _rotateSize_: An integer that is the number of bytes that is the maximum size to which the `audit.log` file can grow before being rotated.

== Examples

The following examples demonstrate how the auditing REST API can be used.

=== List Auditable Events

In the following example, the current list of auditable events is requested.
Note that the output is piped to the http://stedolan.github.io/jq[jq] program, to facilitate readability.

----
curl -v -X GET -u Administrator:password http://10.143.192.101:8091/settings/audit/descriptors | jq
----

If successful, the call returns an object the initial part of which appears as follows:

----
[
  {
    "id": 8243,
    "name": "mutate document",
    "module": "ns_server",
    "description": "Document was mutated via the REST API"
  },
  {
    "id": 8255,
    "name": "read document",
    "module": "ns_server",
    "description": "Document was read via the REST API"
  },
  {
    "id": 8257,
    "name": "alert email sent",
    "module": "ns_server",
    "description": "An alert email was successfully sent"
  },
          .
          .
          ,
----

Each element in the array thus features the `id, `name`, `module`, and `description` of an auditable event.

=== Return the Current Event-Auditing Configuration

The current event-auditing configuration can be returned as follows:

----
curl -v -X GET -u Administrator:password \
http://10.143.192.101:8091/settings/audit | jq
----

If the call is successful, the output resembles the following:

----
{
  "disabled": [
    8243,
    8255,
    8257,
    32770,
    32771,
    32772,
    32780,
    32783,
    32784,
    32785,
    32786,
    40963
  ],
  "uid": "40580060",
  "auditdEnabled": true,
  "disabledUsers": [
    {
      "name": "testuser",
      "domain": "local"
    },
    {
      "name": "@eventing",
      "domain": "local"
    },
    {
      "name": "@cbq-engine",
      "domain": "local"
    }
  ],
  "logPath": "/opt/couchbase/var/lib/couchbase/logs",
  "rotateInterval": 7200,
  "rotateSize": 524288000
}
----

The output thus provides a list of `disabled` event-ids.
It confirms that event auditing is enabled, and lists `disabledUsers`: this list contains one local user, and two internal.
The current `logpath`, `rotateInterval`, and `rotateSize` are also provided.

=== Change the Event-Auditing Configuration

The following call can be used to modify the event-auditing configuration for the node:

----
curl -v -X POST -u Administrator:password \
http://10.143.192.101:8091/settings/audit \
-d auditdEnabled=true \
-d disabled=8243,8255,8257,32770,32771,32772,32780,32783,32784,32785,32786,40963 \
-d disabledUsers=testuser/local,@eventing/local,@cbq-engine/local \
-d rotateSize=524288000 \
-d rotateInterval=7200 \
-d logPath='/opt/couchbase/var/lib/couchbase/logs'
----

This call enables event auditing for the current node, by setting `auditdEnabled` to `true`.
It specifies a list of event ids as `disabled`; and specifies one local user and two internal users as `disabledUser`, ensuring that all but the default list of most important events from these users will not be audited.
It also specifies values for `rotateSize`, `rotateInterval`, and `logPath`.

== See Also

A general overview of auditing is provided in xref:learn:security/auditing.adoc[Auditing].
This overview provides the full list of auditable events, in tabular form.
Instructions on managing auditing from the UI of Couchbase Web Console is provided in xref:manage:manage-security/managing-auditing.adoc[Managing Auditing].
To manage the current auditing configuration with Couchbase CLI, see xref:cli:cbcli/couchbase-cli-setting-audit.adoc[setting-audit].
