= Setting a Target-Cluster Reference
:description: pass:q[To create an XDCR reference to a destination cluster, use the `POST /pools/default/remoteClusters` HTTP method and URI.]
:page-topic-type: reference

[abstract]
{description}

== Description

To use XDCR, source and destination clusters must be established.
A source cluster is the cluster where the original data is stored.
A destination cluster is the cluster where the replica data is stored.
Data is copied from the source cluster to the destination cluster.

== HTTP method and URI

----
POST /pools/default/remoteClusters

POST /pools/default/remoteClusters/<target-cluster-local-name>
----

== Syntax

Curl request syntax:

----
curl -v -u <source-cluster-username>:<source-cluster-password>
  http://<source-cluster-ip-address-or-domain-name>]:8091/pools/default/remoteClusters/[<target-cluster-local-name>]
  -d name=<target-cluster-local-name>
  -d hostname=<target-cluster-ip-address-or-domain-name][:<port-number>]
  -d network_type=[ 'internal' | 'external' ]
  -d username=<target-cluster-username>
  -d password=<target-cluster-password>
  -d demandEncryption=[ 0 | 1 ]
  -d secureType=[ 'half' | 'full'] --data-urlencode "certificate=$(cat <local-pathname-to-target-root-certificate>)"
----

The value of `name`, `target-cluster-local-name`, is for local reference only, and so need not correspond to any network-visible name established for the target cluster.
If an existing reference is being edited, the value of `name` should be specified as a path parameter that terminates the endpoint.

The value of the `target-cluster-ip-address-or-domain-name` parameter determines the target cluster to which the connection will be made.
This value can specify either the _internal_ or (if one has been configured) the _external_ address of the target cluster.
For information on using DNS SRV in this context, see xref:xdcr-reference:xdcr-security-and-networking.adoc[XDCR Security and Networking].

The value of the `network_type` parameter can be either `internal`, which is the default, or `external`.
If `external` is specified, use of the target cluster's external address is enforced, irrespective of the value established for the `target-cluster-ip-address-or-domain-name` parameter.

The `username` and `password` must be those for the target cluster.

If `1`, the value of the `demandEncryption` parameter specifies that encryption must be used for the connection; otherwise, encryption is not used.
The default value is `0`.

The `secureType` parameter can be `half` or `full`, and thus specifies the type of security to be used for the connection.
For information, see xref:manage:manage-security/secure-xdcr-replication.adoc[Secure a Replication].

== Example

Credentials are provided for the source cluster and information, including credentials and UUID for the destination cluster.

Curl request example:

----
curl -v -u Administrator:password1 \
  http://10.4.2.4:8091/pools/default/remoteClusters \
  -d 'uuid=9eee38236f3bf28406920213d93981a3' \
  -d 'name=remote1' \
  -d 'hostname=10.4.2.6:8091' \
  -d 'username=admin' \
  -d 'password=password2'
----

Raw HTTP request example:

----
POST /pools/default/remoteClusters HTTP/1.1
Authorization: Basic QWRtaW5pc3RyYXRvcjpwYXNzd29yZA==
User-Agent: curl/7.21.4 (universal-apple-darwin11.0) libcurl/7.21.4 \
     OpenSSL/0.9.8r zlib/1.2.5
Host: 10.4.2.4:8091
Accept: */*
Content-Length: 114
Content-Type: application/x-www-form-urlencoded
----

== Response

If successful, Couchbase Server responds with a JSON response similar to the following:

----
{"name":"remote1","uri":"/pools/default/remoteClusters/remote1",
"validateURI":"/pools/default/remoteClusters/remote1?just_validate=1",
"hostname":"10.4.2.6:8091",
"username":"Administrator",
"uuid":"9eee38236f3bf28406920213d93981a3",
"deleted":false}
----

The following describes the response elements:

* (String) name: Name of the destination cluster referenced for XDCR.
* (String) validateURI: URI to validate details of cluster reference.
* (String) hostname: Hostname/IP (and :port) of the remote cluster.
* (String) username: Username for the destination cluster administrator.
* (String) uuid: UUID of the remote cluster reference.
* (Boolean) deleted: Indicates whether the reference to the destination cluster has been deleted or not.
