= Search Index Management and Monitoring
:page-toclevels: 2
:description: Use the following endpoints in the Search Service API to manage and monitor your Search indexes. 

[abstract]
{description}

== Search Index Definitions

Use the following APIs to retrieve Search index definitions, create new Search indexes, or delete an existing Search index. 

[#g-api-index]
=== Get All Search Index Definitions

Returns all Search index definitions from the bucket where you have read permissions, as a JSON object.

NOTE: This endpoint is for legacy Search indexes and may be deprecated in a future release. 
Use <<g-api-scoped-indexes,>>, instead. 

==== Endpoint

GET /api/index

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!read

==== Role Required

*Search Reader* or *Search Admin*

.Sample Response
----
{
    "indexDefs": {
        "implVersion": "4.0.0",
        "indexDefs": {
            "myFirstIndex": {
            "name": "myFirstIndex",
            "params": "",
            "planParams": {
                "hierarchyRules": null,
                "maxPartitionsPerPIndex": 0,
                "nodePlanParams": null,
                "numReplicas": 0,
                "planFrozen": false
             },
             "sourceName": "",
             "sourceParams": "",
             "sourceType": "nil",
             "sourceUUID": "",
             "type": "fulltext-index",
             "uuid": "6cc599ab7a85bf3b"
          }
       },
       "uuid": "6cc599ab7a85bf3b"
    },
    "status": "ok"
}
----

[#g-api-scoped-indexes]
=== GET All Search Index Definitions (Scoped)

Returns all Search index definitions inside the bucket and scope specified in the endpoint URL as a JSON object. 

==== Endpoint

GET /api/bucket/`{$BUCKET_NAME}`/scope/`{$SCOPE_NAME}`/index

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!read

==== Role Required

*Search Reader* or *Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description 

|[.param]`{$BUCKET_NAME}`
| Yes
| String, URL path parameter
| The name of the bucket where you want to return Search index definitions. 

|[.param]`{$SCOPE_NAME}`
| Yes
| String, URL path parameter
| The name of the scope where you want to return Search index definitions.

|====

.Sample response
----
{
    "status": "ok",
    "indexDefs": {
        "uuid": "23cf9530131858b8",
        "indexDefs": {
            "travel-sample.inventory.travel-hotel": {
                "type": "fulltext-index",
                "name": "travel-hotel",
                "uuid": "a04a16f178846bc4",
                "sourceType": "gocbcore",
                "sourceName": "travel-sample",
                "sourceUUID": "8f866261438f8b0d415a437552f3ae99",
                "planParams": {
                    "maxPartitionsPerPIndex": 1024,
                    "indexPartitions": 1
                },
                "params": {
                    "doc_config": {
                        "docid_prefix_delim": "",
                        "docid_regexp": "",
                        "mode": "scope.collection.type_field",
                        "type_field": "type"
                    },
                    "mapping": {
                        "analysis": {},
                        "default_analyzer": "standard",
                        "default_datetime_parser": "dateTimeOptional",
                        "default_field": "_all",
                        "default_mapping": {
                            "dynamic": true,
                            "enabled": false
                        },
                        "default_type": "_default",
                        "docvalues_dynamic": false,
                        "index_dynamic": true,
                        "store_dynamic": false,
                        "type_field": "_type",
                        "types": {
                            "inventory.hotel": {
                                "dynamic": false,
                                "enabled": true,
                                "properties": {
                                    "reviews": {
                                        "dynamic": false,
                                        "enabled": true,
                                        "properties": {
                                            "content": {
                                                "dynamic": false,
                                                "enabled": true,
                                                "fields": [
                                                    {
                                                        "docvalues": true,
                                                        "include_in_all": true,
                                                        "include_term_vectors": true,
                                                        "index": true,
                                                        "name": "content",
                                                        "store": true,
                                                        "type": "text"
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "store": {
                        "indexType": "scorch",
                        "segmentVersion": 15
                    }
                },
                "sourceParams": {}
            },
            "travel-sample.inventory.travel-test": {
                "type": "fulltext-index",
                "name": "travel-test",
                "uuid": "766ddce5d41a3b41",
                "sourceType": "gocbcore",
                "sourceName": "travel-sample",
                "sourceUUID": "8f866261438f8b0d415a437552f3ae99",
                "planParams": {
                    "maxPartitionsPerPIndex": 1024,
                    "indexPartitions": 1
                },
                "params": {
                    "doc_config": {
                        "docid_prefix_delim": "",
                        "docid_regexp": "",
                        "mode": "scope.collection.type_field",
                        "type_field": "type"
                    },
                    "mapping": {
                    "analysis": {},
                    "default_analyzer": "standard",
                    "default_datetime_parser": "dateTimeOptional",
                    "default_field": "_all",
                    "default_mapping": {
                        "dynamic": true,
                        "enabled": true
                    },
                    "default_type": "_default",
                    "docvalues_dynamic": false,
                    "index_dynamic": true,
                    "store_dynamic": false,
                    "type_field": "_type"
                    },
                    "store": {
                        "indexType": "scorch",
                        "segmentVersion": 15
                    }
                },
                "sourceParams": {}
            }
        },
        "implVersion": "5.7.0"
    }
}
----


[#g-api-index-name]
=== GET Index Definition 

Returns the definition of the Search index specified in the endpoint URL as a JSON object.

NOTE: This endpoint is for legacy Search indexes and may be deprecated in a future release. 
Use <<g-api-scoped-index-name,>>, instead. 

==== Endpoint 

GET /api/index/`{$INDEX_NAME}` 

==== Permission Required 

cluster.bucket[[.var]`$BUCKET_NAME`].fts!read

==== Role Required  

*Search Reader* or *Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description 

| [.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
a| The name of the Search index definition you want to return. 
You must use the fully qualified name for the index, which includes the bucket and scope.

To view the full, scoped name for an index for use with this endpoint: 

. Go to the *Search* tab in the Couchbase Server Web Console.
. Point to the *Index Name* for an index.

|====

.Sample response
----
{
    "indexDef": {
        "name": "myFirstIndex",
        "params": "",
        "planParams": {
            "hierarchyRules": null,
            "maxPartitionsPerPIndex": 0,
            "nodePlanParams": null,
            "numReplicas": 0,
            "planFrozen": false
        },
        "sourceName": "",
        "sourceParams": "",
        "source
            ": "nil",
        "sourceUUID": "",
        "type": "fulltext-index",
        "uuid": "6cc599ab7a85bf3b"
      },
      "planPIndexes": [
        {
         "indexName": "myFirstIndex",
         "indexParams": "",
         "indexType": "bleve",
         "indexUUID": "6cc599ab7a85bf3b",
         "name": "myFirstIndex_6cc599ab7a85bf3b_0",
         "nodes": {
            "78fc2ffac2fd9401": {
              "canRead": true,
              "canWrite": true,
              "priority": 0
            }
         },
         "sourceName": "",
         "sourceParams": "",
         "sourcePartitions": "",
         "sourceType": "nil",
         "sourceUUID": "",
         "uuid": "64bed6e2edf354c3"
         }
       ],
       "status": "ok",
       "warnings": []
       }
----

[#g-api-scoped-index-name]
=== GET Index Definition (Scoped)

Returns the Search index definition for the Search index specified in the endpoint URL as a JSON object. 
Unlike <<g-api-index-name,GET /api/index/\{indexName}>>, this endpoint is scoped and does not require a fully qualified `${INDEX_NAME}` value.

==== Endpoint

GET /api/bucket/`{$BUCKET_NAME}`/scope/`{$SCOPE_NAME}`/index/`{$INDEX_NAME}`

==== Permission Required 

cluster.bucket[[.var]`$BUCKET_NAME`].fts!read

==== Role Required 

*Search Reader* or *Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description 

|[.param]`{$BUCKET_NAME}`
| Yes 
| String, URL path parameter
| The name of the bucket used to create the Search index definition. 

|[.param]`{$SCOPE_NAME}`
| Yes
| String, URL path parameter
| The name of the scope used to create the Search index definition. 

|[.param]`{$INDEX_NAME}`
| Yes 
| String, URL path parameter
| The name of the Search index definition to return. 

|====

.Sample Response for a Vector Search index
[source,json]
----
include::example$fts-sample-index-def-response.jsonc[]
----

[#p-api-index-name]
=== PUT Create or Update an Index Definition

If the Search index in the endpoint URL does not exist, this endpoint uses a JSON object in the request body to create a new index.
If the Search index already exists, this endpoint updates the Search index definition.

NOTE: This endpoint is for legacy Search indexes and may be deprecated in a future release.
Use <<p-api-scoped-index-name,>>, instead. 

==== Endpoint

PUT /api/index/`{$INDEX_NAME}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!write

==== Role Required

*Search Admin*

==== Parameters

For a detailed list of all parameters for the Request Body for the PUT /api/index/`{$INDEX_NAME}` endpoint, see xref:search:search-index-params.adoc[].

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description 

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
a| The name of the Search index definition to create or update.
The name must satisfy the regular expression `^[A-Za-z][0-9A-Za-z_\-]*$`.

If you want to update an index definition, you must use the fully qualified name for the index, which includes the bucket and scope.

To view the full, scoped name for an index for use with this endpoint: 

. Go to the *Search* tab in the Couchbase Server Web Console.
. Point to the *Index Name* for an index.

|[.param]`params`
| Yes
| String (JSON), form parameter
| Sets the Search index's type identifier, type mappings, and analyzers.
For more information, see xref:search:search-index-params.adoc#params[Params Object].

|[.param]`type`
| Yes
| String, form parameter
a|The type of Search index you want to create.
For more information, see xref:search:search-index-params.adoc#initial[Initial Settings].

|[.param]`planParams`
| Yes
| String (JSON), form parameter
| Set a Search index's partition and replication settings.
For more information, see xref:search:search-index-params.adoc#planparams[planParams Object].

|[.param]`prevIndexUUID`
| No
| String, form parameter
| Intended for clients that want to check that they are not overwriting the Search index definition updates of concurrent clients.

|[.param]`sourceName`
| No
| String, form parameter
| The name of the bucket where you want to create the Search index.
For more information, see xref:search:search-index-params.adoc#initial[Initial Settings].

|[.param]`sourceUUID`
| No
| String, form parameter
| The UUID of the bucket where you want to create the Search index. 
For more information, see xref:search:search-index-params.adoc#initial[Initial Settings].

|====

.Sample failure response
----
{
    "error": "rest_create_index: index type is required, indexName: travel-test",
    "request": "",
    "status": "fail"
}
----
The Search Service returns a non-200 HTTP error code when a request fails.

.Sample success response
----
{
    "status": "ok",
    "name": "travel-test",
    "uuid": "565ca041af3baf9d"
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

[#p-api-scoped-index-name]
=== PUT Create or Update an Index Definition (Scoped)

If the Search index in the endpoint URL does not exist, this endpoint uses a JSON object in the request body to create a new index.
If the Search index already exists, this endpoint updates the Search index definition. 
Unlike <<p-api-index-name,PUT /api/index/{indexName}>>, this endpoint is scoped and does not require a fully qualified `${INDEX_NAME}` value.

==== Endpoint

PUT /api/bucket/`{$BUCKET_NAME}`/scope/`{$SCOPE_NAME}`/index/`{$INDEX_NAME}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!write

==== Role Required

*Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description 

| `{$BUCKET_NAME}`
|Yes 
|String, URL path parameter
|The name of the bucket where the Search Service should create or update the Search index definition. 

|`{$SCOPE_NAME}`
| Yes
| String, URL path parameter
| The name of the scope where the Search Service should create or update the Search index definition. 

|`{$INDEX_NAME}`
| Yes
| String, URL path parameter
| The name of the Search index definition to create or update.
The name must satisfy the regular expression `^[A-Za-z][0-9A-Za-z_\-]*$`.
|====

==== Request Body

Add a JSON object with the full Search index definition you want to create or update.
For more information about how to create an index definition JSON, see xref:search:search-index-params.adoc[].

.Sample failure response
----
{
    "error": "rest_create_index: index type is required, indexName: travel-test",
    "request": {},
    "status": "fail"
}
----
The Search Service returns a non-200 HTTP error code when a request fails. 

.Sample success response
----
{
    "status": "ok",
    "name": "travel-sample.inventory.travel-test",[.var]`{$BUCKET_NAME}`
    "uuid": "654cb62baebf2d26"
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

[#d-api-index-name]
=== DELETE Index Definition 

Deletes the Search index definition specified in the endpoint URL.

NOTE: This endpoint is for legacy Search indexes and may be deprecated in a future release.
Use <<d-api-scoped-index-name,>>, instead. 

==== Endpoint

DELETE /api/index/{$INDEX_NAME}

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!write

==== Role Required 

*Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description 

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
a| The name of the Search index definition you want to delete.
You must use the fully qualified name for the index, which includes the bucket and scope.

To view the full, scoped name for an index for use with this endpoint: 

. Go to the *Search* tab in the Couchbase Server Web Console.
. Point to the *Index Name* for an index.

|====

.Sample failure response
----
{
    "error": "rest_auth: preparePerms, err: index not found",
    "request": "",
    "status": "fail"
}
----
The Search Service returns a non-200 HTTP error code when a request fails.

.Sample success response
----
{
    "status": "ok",
    "uuid": "123294e5a4efbe39"
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

[#d-api-scoped-index-name]
=== DELETE Index Definition (Scoped)

Delete the Search index definition from the bucket and scope specified in the endpoint URL. 
Unlike <<d-api-index-name,DELETE /api/index/{indexName}>>, this endpoint is scoped and does not require a fully qualified `${INDEX_NAME}` value.

==== Endpoint

DELETE /api/bucket/`{$BUCKET_NAME}`/scope/`{$SCOPE_NAME}`/index/`{$INDEX_NAME}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!write

==== Role Required

*Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description 

|[.param]`{$BUCKET_NAME}`
| Yes
| String, URL path parameter
| The name of the bucket used to create the Search index definition. 

|[.param]`{$SCOPE_NAME}`
| Yes
| String, URL path parameter
| The name of the scope used to create the Search index definition. 

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
| The name of the Search index definition you want to delete.

|====

.Sample failure response
----
{
    "error": "rest_auth: preparePerms, err: index not found",
    "request": "",
    "status": "fail"
}
----
The Search Service returns a non-200 HTTP error code when a request fails. 

.Sample success response
----
{
    "status": "ok",
    "uuid": "687be6a2ad647c34"
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

== Index Management

Use the following endpoints to manage index controls, such as document ingestion, partition assignment, and queries.

[#p-api-idx-name-ingestcontrol]
=== POST Set Index IngestControl

For the Search index specified in the endpoint URL, pause or resume index updates and maintenance.
While paused, the Search index does not load any new document mutations.

NOTE: This endpoint is for legacy Search indexes and may be deprecated in a future release. 
Use <<p-api-scoped-ingestcontrol,>>, instead. 

==== Endpoint
POST /api/index/`{$INDEX_NAME}`/ingestControl/`{$OP}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!manage

==== Role Required

*Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description 

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
a| The name of the Search index definition where you want to pause or resume document loading.
You must use the fully qualified name for the index, which includes the bucket and scope.

To view the full, scoped name for an index for use with this endpoint: 

. Go to the *Search* tab in the Couchbase Server Web Console.
. Point to the *Index Name* for an index.

|[.param]`{$OP}`
| Yes
| String, URL path parameter
|To pause ingestion and maintenance, set `{$OP}` to `pause`.
To resume ingestion and maintenance on a paused index, set `{$OP}` to `resume`.

|====

.Sample success response
----
{
    "status": "ok",
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

[#p-api-scoped-ingestcontrol]
=== POST Set Index IngestControl (Scoped)

For the Search index specified in the endpoint URL, pause or resume index updates and maintenance.
While paused, the Search index does not load any new document mutations.
Unlike <<p-api-idx-name-ingestcontrol,POST /api/index/{indexName}/ingestControl/{$OP}>>, this endpoint is scoped and does not require a fully qualified `${INDEX_NAME}` value.

==== Endpoint 

POST /api/bucket/`{$BUCKET_NAME}`/scope/`{$SCOPE_NAME}`/index/`{$INDEX_NAME}`/ingestControl/`{$OP}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!manage

==== Role Required

*Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$BUCKET_NAME}`
| Yes
| String, URL path parameter
| The name of the bucket used to create the Search index definition. 

|[.param]`{$SCOPE_NAME}`
| Yes
| String, URL path parameter
| The name of the scope used to create the Search index definition. 

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
| The name of the Search index definition where you want to pause or resume document loading.

|[.param]`{$OP}`
| Yes
| String, URL path parameter
| To pause ingestion and maintenance, set `{$OP}` to `pause`.
To resume ingestion and maintenance on a paused index, set `{$OP}` to `resume`.

|====

.Sample success response
----
{
    "status": "ok",
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

[#p-api-idx-name-planfreezecontrol]
=== POST Freeze Index Partition Assignment

For the Search index specified in the endpoint URL, freeze or unfreeze the assignment of index partitions to nodes.
While frozen, the Search index stops assigning partitions during index rebalancing and index definition updates.

NOTE: This endpoint is for legacy Search indexes and may be deprecated in a future release.
Use <<p-api-scoped-planfreezecontrol,>>, instead. 

==== Endpoint

POST /api/index/`{$INDEX_NAME}`/planFreezeControl/`{$OP}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!manage

==== Role Required

*Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
a| The name of the Search index definition to freeze or unfreeze for partition assignment.
You must use the fully qualified name for the index, which includes the bucket and scope.

To view the full, scoped name for an index for use with this endpoint: 

. Go to the *Search* tab in the Couchbase Server Web Console.
. Point to the *Index Name* for an index.

|[.param]`{$OP}`
| Yes
| String, URL path parameter
| To freeze partition assignment, set `{$OP}` to `freeze`.
To unfreeze partition assignment on a frozen index, set `{$OP}` to `unfreeze`.

|====

.Sample success response
----
{
    "status": "ok",
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

[#p-api-scoped-planfreezecontrol]
=== POST Freeze Index Partition Assignment (Scoped)

For the Search index specified in the endpoint URL, freeze or unfreeze the assignment of index partitions to nodes.
While frozen, the Search index stops assigning partitions during index rebalancing and index definition updates.
Unlike <<p-api-idx-name-planfreezecontrol,POST /api/index/{indexName}/planFreezeControl/{$OP}>>, this endpoint is scoped and does not require a fully qualified `${INDEX_NAME}` value. 

==== Endpoint

POST /api/bucket/`{$BUCKET_NAME}`/scope/`{$SCOPE_NAME}`/index/`{$INDEX_NAME}`/planFreezeControl/`{$OP}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!manage

==== Role Required

*Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$BUCKET_NAME}`
| Yes
| String, URL path parameter
| The name of the bucket used to create the Search index definition. 

|[.param]`{$SCOPE_NAME}`
| Yes
| String, URL path parameter
| The name of the scope used to create the Search index definition. 

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
| The name of the Search index definition to freeze or unfreeze for partition assignment.

|[.param]`{$OP}`
| Yes
| String, URL path parameter
| To freeze partition assignment, set `{$OP}` to `freeze`.
To unfreeze partition assignment on a frozen index, set `{$OP}` to `unfreeze`.

|====

.Sample success response
----
{
    "status": "ok",
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

[#p-api-idx-name-querycontrol]
=== POST Stop Queries on an Index

For the Search index specified in the endpoint URL, disallow or allow queries. 
While queries are disallowed, users see an error that the Search index's partitions could not be reached. 

NOTE: This endpoint is for legacy Search indexes and may be deprecated in a future release. 
Use <<p-api-scoped-querycontrol,>>, instead. 

==== Endpoint

POST /api/index/`{$INDEX_NAME}`/queryControl/`{$OP}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!manage

==== Role Required

*Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
a| The name of the Search index definition where you want to allow or disallow Search queries.
You must use the fully qualified name for the index, which includes the bucket and scope.

To view the full, scoped name for an index for use with this endpoint: 

. Go to the *Search* tab in the Couchbase Server Web Console.
. Point to the *Index Name* for an index.

|[.param]`{$OP}`
| Yes
| String, URL path parameter
| To allow queries against a Search index, set `{$OP}` to `allow`.
To block queries against a Search index, set `{$OP}` to `disallow`.

|====

.Sample success response
----
{
    "status": "ok",
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

[#p-api-scoped-querycontrol]
=== POST Stop Queries on an Index (Scoped)

For the Search index specified in the endpoint URL, disallow or allow queries. 
While queries are disallowed, users see an error that the Search index's partitions could not be reached. 
Unlike <<p-api-idx-name-querycontrol,POST /api/index/{indexName}/queryControl/{$OP}>>, this endpoint is scoped and does not require a fully qualified `${INDEX_NAME}` value. 

==== Endpoint

POST /api/bucket/`{$BUCKET_NAME}`/scope/`{$SCOPE_NAME}`/index/`{$INDEX_NAME}`/queryControl/`{$OP}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!manage

==== Role Required

*Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$BUCKET_NAME}`
| Yes
| String, URL path parameter
| The name of the bucket used to create the Search index definition. 

|[.param]`{$SCOPE_NAME}`
| Yes
| String, URL path parameter
| The name of the scope used to create the Search index definition. 

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
| The name of the Search index definition where you want to allow or disallow Search queries.

|[.param]`{$OP}`
| Yes
| String, URL path parameter
| To allow queries against a Search index, set `{$OP}` to `allow`.
To block queries against a Search index, set `{$OP}` to `disallow`.

|==== 

.Sample success response
----
{
    "status": "ok",
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

== Index Monitoring And Debugging

Use the following endpoints to get statistics about Search indexes for monitoring and debugging. 

[#g-api-stats]
=== GET Indexing and Data Metrics for All Indexes

Use this endpoint to get indexing and data related metrics, timings, and counters from the node running the Search Service, for all Search indexes. 
The endpoint returns the data as a JSON object.

==== Endpoint

GET /api/stats

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].stats!read

==== Role Required

*Search Admin*

.Sample response
----
{
    "feeds": {
        "myFirstIndex_6cc599ab7a85bf3b": {}
    },
    "manager": {
        "TotCreateIndex": 1,
        "TotCreateIndexOk": 1,
        "TotDeleteIndex": 0,
        "TotDeleteIndexOk": 0,
        "TotIndexControl": 0,
        "TotIndexControlOk": 0,
        "TotJanitorClosePIndex": 0,
        "TotJanitorKick": 2,
        "TotJanitorKickErr": 0,
        "TotJanitorKickOk": 2,
        "TotJanitorKickStart": 2,
        "TotJanitorNOOP": 0,
        "TotJanitorNOOPOk": 0,
        "TotJanitorRemovePIndex": 0,
        "TotJanitorSubscriptionEvent": 0,
        "TotJanitorUnknownErr": 0,
        "TotKick": 0,
        "TotPlannerKick": 2,
        "TotPlannerKickChanged": 1,
        "TotPlannerKickErr": 0,
        "TotPlannerKickOk": 2,
        "TotPlannerKickStart": 2,
        "TotPlannerNOOP": 0,
        "TotPlannerNOOPOk": 0,
        "TotPlannerSubscriptionEvent": 0,
        "TotPlannerUnknownErr": 0,
        "TotSaveNodeDef": 2,
        "TotSaveNodeDefGetErr": 0,
        "TotSaveNodeDefOk": 2,
        "TotSaveNodeDefSame": 0,
        "TotSaveNodeDefSetErr": 0
     },
     "pindexes": {
         "myFirstIndex_6cc599ab7a85bf3b_0": null
     }
}
----

[#g-api-nsstats-index-name]
=== GET Search Index Statistics 

Return indexing and data related metrics, timings, and counters for the Search index specified in the endpoint URL. 
The endpoint returns the data as a JSON object. 

Use this endpoint for monitoring the number of requests, documents, and more for a specific index. 
For more detailed partition information and more overall statistics for an index, see <<g-api-stats-index-name,>>.

==== Endpoint

GET /api/nsstats/index/`{$INDEX_NAME}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].stats!read

==== Role Required 

FTS-Searcher, FTS-Admin

.Sample response 
----
{
    "avg_grpc_internal_queries_latency": 0,
    "avg_grpc_queries_latency": 0,
    "avg_internal_queries_latency": 0,
    "avg_queries_latency": 1.523718,
    "batch_merge_count": 0,
    "doc_count": 15000,
    "iterator_next_count": 0,
    "iterator_seek_count": 0,
    "last_access_time": "2023-09-20T03:05:55.440-07:00",
    "num_bytes_live_data": 0,
    "num_bytes_read_at_query_time": 4638582,
    "num_bytes_used_disk": 28062406,
    "num_bytes_used_disk_by_root": 23651161,
    "num_bytes_used_disk_by_root_reclaimable": 0,
    "num_bytes_written_at_index_time": 21208735,
    "num_files_on_disk": 6,
    "num_mutations_to_index": 0,
    "num_persister_nap_merger_break": 40,
    "num_persister_nap_pause_completed": 7,
    "num_pindexes_actual": 1,
    "num_pindexes_target": 1,
    "num_recs_to_persist": 0,
    "num_root_filesegments": 4,
    "num_root_memorysegments": 0,
    "reader_get_count": 0,
    "reader_multi_get_count": 0,
    "reader_prefix_iterator_count": 0,
    "reader_range_iterator_count": 0,
    "timer_batch_store_count": 0,
    "timer_data_delete_count": 0,
    "timer_data_update_count": 15000,
    "timer_opaque_get_count": 2048,
    "timer_opaque_set_count": 2048,
    "timer_rollback_count": 0,
    "timer_snapshot_start_count": 1024,
    "tot_seq_received": 19096,
    "total_bytes_indexed": 4866486,
    "total_bytes_query_results": 1798,
    "total_compaction_written_bytes": 87917849,
    "total_compactions": 0,
    "total_grpc_internal_queries": 0,
    "total_grpc_queries": 0,
    "total_grpc_queries_error": 0,
    "total_grpc_queries_slow": 0,
    "total_grpc_queries_timeout": 0,
    "total_grpc_request_time": 0,
    "total_internal_queries": 0,
    "total_queries": 4,
    "total_queries_error": 1,
    "total_queries_slow": 0,
    "total_queries_timeout": 0,
    "total_request_time": 6276461,
    "total_term_searchers": 7,
    "total_term_searchers_finished": 7,
    "writer_execute_batch_count": 0
} 
----

[#g-api-stats-index-name]
=== GET Indexing and Data Metrics, Timings, and Other Statistics

Return indexing and data related metrics, timings, and counters for the Search index specified in the endpoint URL. 
The endpoint returns the data as a JSON object.

Use this endpoint for more detailed partition information and more available statistics than <<g-api-nsstats-index-name,>>.

==== Endpoint

GET /api/stats/index/`{$INDEX_NAME}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].stats!read

==== Role Required

*Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
a| The name of the Search index where you want to retrieve statistics.
You must use the fully qualified name for the index, which includes the bucket and scope.

To view the full, scoped name for an index for use with this endpoint: 

. Go to the *Search* tab in the Couchbase Server Web Console.
. Point to the *Index Name* for an index.

|====

.Sample response
----
{
    "feeds": {},
    "pindexes": {
        "travel-sample.inventory.travel-test_3858c70e4d4d8df9_4c1c5584": {
            "pindexStoreStats": {
                "TimerBatchStore": {
                    "count": 0,
                    "min": 0,
                    "max": 0,
                    "mean": 0.00,
                    "stddev": 0.00,
                    "percentiles": {
                        "99%": 0.00,
                        "99.9%": 0.00,
                        "median": 0.00,
                        "75%": 0.00,
                        "95%": 0.00
                    },
                    "rates": {
                        "mean": 0.00,
                        "1-min": 0.00,
                        "5-min": 0.00,
                        "15-min": 0.00
                    }
                },
                "Errors": []
            },
            "bleveIndexStats": {
                "index": {
                    "CurFilesIneligibleForRemoval": 0,
                    "CurOnDiskBytes": 34007668,
                    "CurOnDiskFiles": 4,
                    "CurRootEpoch": 0,
                    "LastMergedEpoch": 44,
                    "LastPersistedEpoch": 44,
                    "MaxBatchIntroTime": 0,
                    "MaxFileMergeZapIntroductionTime": 0,
                    "MaxFileMergeZapTime": 0,
                    "MaxMemMergeZapTime": 0,
                    "TotAnalysisTime": 0,
                    "TotBatchIntroTime": 0,
                    "TotBatches": 0,
                    "TotBatchesEmpty": 0,
                    "TotBytesReadAtQueryTime": 294892,
                    "TotBytesWrittenAtIndexTime": 0,
                    "TotDeletes": 0,
                    "TotEventTriggerCompleted": 2,
                    "TotEventTriggerStarted": 2,
                    "TotFileMergeForceOpsCompleted": 0,
                    "TotFileMergeForceOpsStarted": 0,
                    "TotFileMergeIntroductions": 0,
                    "TotFileMergeIntroductionsDone": 0,
                    "TotFileMergeIntroductionsObsoleted": 0,
                    "TotFileMergeIntroductionsSkipped": 0,
                    "TotFileMergeLoopBeg": 2,
                    "TotFileMergeLoopEnd": 1,
                    "TotFileMergeLoopErr": 0,
                    "TotFileMergePlan": 1,
                    "TotFileMergePlanErr": 0,
                    "TotFileMergePlanNone": 1,
                    "TotFileMergePlanOk": 0,
                    "TotFileMergePlanTasks": 0,
                    "TotFileMergePlanTasksDone": 0,
                    "TotFileMergePlanTasksErr": 0,
                    "TotFileMergePlanTasksSegments": 0,
                    "TotFileMergePlanTasksSegmentsEmpty": 0,
                    "TotFileMergeSegments": 0,
                    "TotFileMergeSegmentsEmpty": 0,
                    "TotFileMergeWrittenBytes": 0,
                    "TotFileMergeZapBeg": 0,
                    "TotFileMergeZapEnd": 0,
                    "TotFileMergeZapIntroductionTime": 0,
                    "TotFileMergeZapTime": 0,
                    "TotFileSegmentsAtRoot": 1,
                    "TotIndexTime": 0,
                    "TotIndexedPlainTextBytes": 0,
                    "TotIntroduceLoop": 3,
                    "TotIntroduceMergeBeg": 0,
                    "TotIntroduceMergeEnd": 0,
                    "TotIntroducePersistBeg": 0,
                    "TotIntroducePersistEnd": 0,
                    "TotIntroduceRevertBeg": 0,
                    "TotIntroduceRevertEnd": 0,
                    "TotIntroduceSegmentBeg": 0,
                    "TotIntroduceSegmentEnd": 0,
                    "TotIntroducedItems": 0,
                    "TotIntroducedSegmentsBatch": 0,
                    "TotIntroducedSegmentsMerge": 0,
                    "TotItemsToPersist": 0,
                    "TotMemMergeBeg": 0,
                    "TotMemMergeDone": 0,
                    "TotMemMergeErr": 0,
                    "TotMemMergeSegments": 0,
                    "TotMemMergeZapBeg": 0,
                    "TotMemMergeZapEnd": 0,
                    "TotMemMergeZapTime": 0,
                    "TotMemorySegmentsAtRoot": 0,
                    "TotOnErrors": 0,
                    "TotPersistLoopBeg": 2,
                    "TotPersistLoopEnd": 1,
                    "TotPersistLoopErr": 0,
                    "TotPersistLoopProgress": 0,
                    "TotPersistLoopWait": 2,
                    "TotPersistLoopWaitNotified": 0,
                    "TotPersistedItems": 0,
                    "TotPersistedSegments": 0,
                    "TotPersisterMergerNapBreak": 1,
                    "TotPersisterNapPauseCompleted": 1,
                    "TotPersisterSlowMergerPause": 0,
                    "TotPersisterSlowMergerResume": 0,
                    "TotSnapshotsRemovedFromMetaStore": 0,
                    "TotTermSearchersFinished": 13,
                    "TotTermSearchersStarted": 13,
                    "TotUpdates": 0,
                    "analysis_time": 0,
                    "batches": 0,
                    "deletes": 0,
                    "errors": 0,
                    "index_time": 0,
                    "num_bytes_read_at_query_time": 294892,
                    "num_bytes_used_disk": 34007668,
                    "num_bytes_used_disk_by_root": 15644303,
                    "num_bytes_used_disk_by_root_reclaimable": 0,
                    "num_bytes_written_at_index_time": 0,
                    "num_files_on_disk": 4,
                    "num_items_introduced": 0,
                    "num_items_persisted": 0,
                    "num_persister_nap_merger_break": 1,
                    "num_persister_nap_pause_completed": 1,
                    "num_plain_text_bytes_indexed": 0,
                    "num_recs_to_persist": 0,
                    "num_root_filesegments": 1,
                    "num_root_memorysegments": 0,
                    "term_searchers_finished": 13,
                    "term_searchers_started": 13,
                    "total_compaction_written_bytes": 0,
                    "updates": 0
                },
                "search_time": 40353204,
                "searches": 1
            },
            "basic": {
                "DocCount": 917
            },
            "partitions": {},
            "copyPartitionStats": {
                "TotCopyPartitionStart": 0,
                "TotCopyPartitionFinished": 0,
                "TotCopyPartitionTimeInMs": 0,
                "TotCopyPartitionFailed": 0,
                "TotCopyPartitionRetries": 0,
                "TotCopyPartitionErrors": 0,
                "TotCopyPartitionSkipped": 0,
                "TotCopyPartitionCancelled": 0,
                "TotCopyPartitionOnHttp2": 0
            }
        }
    }
}
----

[#g-api-nsstats-index-name]
=== GET Query, Mutation, Partition, and Other Index Statistics 

Return query, mutation, document, partition, and compaction statistics for the Search index specified in the endpoint URL. 
The endpoint returns the data as a JSON object.

==== Endpoint

GET /api/nsstats/index/`{$INDEX_NAME}`

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].stats!read

==== Role Required

*Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
a| The name of the Search index where you want to retrieve statistics.
You must use the fully qualified name for the index, which includes the bucket and scope.

To view the full, scoped name for an index for use with this endpoint: 

. Go to the *Search* tab in the Couchbase Server Web Console.
. Point to the *Index Name* for an index.

|====

.Sample response
----
{
    "avg_grpc_internal_queries_latency": 0,
    "avg_grpc_queries_latency": 0,
    "avg_internal_queries_latency": 0,
    "avg_queries_latency": 12.971812,
    "batch_merge_count": 0,
    "doc_count": 917,
    "iterator_next_count": 0,
    "iterator_seek_count": 0,
    "last_access_time": "2023-12-05T17:09:09.326+00:00",
    "num_bytes_live_data": 0,
    "num_bytes_read_at_query_time": 269399,
    "num_bytes_used_disk": 16692286,
    "num_bytes_used_disk_by_root": 15643710,
    "num_bytes_used_disk_by_root_reclaimable": 0,
    "num_bytes_written_at_index_time": 12524609,
    "num_files_on_disk": 2,
    "num_mutations_to_index": 0,
    "num_persister_nap_merger_break": 2,
    "num_persister_nap_pause_completed": 2,
    "num_pindexes_actual": 1,
    "num_pindexes_target": 1,
    "num_recs_to_persist": 0,
    "num_root_filesegments": 1,
    "num_root_memorysegments": 0,
    "reader_get_count": 0,
    "reader_multi_get_count": 0,
    "reader_prefix_iterator_count": 0,
    "reader_range_iterator_count": 0,
    "timer_batch_store_count": 0,
    "timer_data_delete_count": 0,
    "timer_data_update_count": 917,
    "timer_opaque_get_count": 2048,
    "timer_opaque_set_count": 2048,
    "timer_rollback_count": 0,
    "timer_snapshot_start_count": 96,
    "tot_seq_received": 87974,
    "total_bytes_indexed": 8523422,
    "total_bytes_query_results": 35846,
    "total_compaction_written_bytes": 15643710,
    "total_compactions": 0,
    "total_grpc_internal_queries": 0,
    "total_grpc_queries": 0,
    "total_grpc_queries_error": 0,
    "total_grpc_queries_slow": 0,
    "total_grpc_queries_timeout": 0,
    "total_grpc_request_time": 0,
    "total_internal_queries": 0,
    "total_queries": 2,
    "total_queries_error": 0,
    "total_queries_slow": 0,
    "total_queries_timeout": 0,
    "total_request_time": 25947312,
    "total_term_searchers": 15,
    "total_term_searchers_finished": 15,
    "writer_execute_batch_count": 0
}
----

[#g-api-stats-index-name-analyzeDoc]
=== POST Analyze Document 

Use the Search index specified in the endpoint URL to analyze a document from the request body.

==== Endpoint 

POST /api/index/`{$INDEX_NAME}`/analyzeDoc

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!read

==== Role Required

*Search Reader* or *Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
a| The name of the Search index to use to analyze the document in the request body.
You must use the fully qualified name for the index, which includes the bucket and scope.

To view the full, scoped name for an index for use with this endpoint: 

. Go to the *Search* tab in the Couchbase Server Web Console.
. Point to the *Index Name* for an index.

|====

==== Request Body 

Add any valid JSON document to the request body. 
For example:

----
{
   "name": "hello world",
   "title": "couchbase blr"
}
----

==== Response Object

In the following example, a Search index with the following settings analyzed the document from the sample Request Body: 

* A `keyword` analyzer for the `title` field. 
* An `ngram` token filter with a `min` of 2 and a `max` of 5 for the `name` field.

----
{
  "status": "ok",
  "analyzed": [
    {
      "couchbase blr": {
        "Term": "Y291Y2hiYXNlIGJscg==",
        "Locations": [
          {
            "Field": "title",
            "ArrayPositions": [],
            "Start": 0,
            "End": 13,
            "Position": 1
          }
        ]
      }
    },
    {
      "he": {
        "Term": "aGU=",
        "Locations": [
          {
            "Field": "name",
            "ArrayPositions": [],
            "Start": 0,
            "End": 5,
            "Position": 1
          }
        ]
      },
      "hel": {
        "Term": "aGVs",
        "Locations": [
          {
            "Field": "name",
            "ArrayPositions": [],
            "Start": 0,
            "End": 5,
            "Position": 1
          }
        ]
      },
      "hell": {
        "Term": "aGVsbA==",
        "Locations": [
          {
            "Field": "name",
            "ArrayPositions": [],
            "Start": 0,
            "End": 5,
            "Position": 1
          }
        ]
      },
      "hello": {
        "Term": "aGVsbG8=",
        "Locations": [
          {
            "Field": "name",
            "ArrayPositions": [],
            "Start": 0,
            "End": 5,
            "Position": 1
          }
        ]
      },
      "wo": {
        "Term": "d28=",
        "Locations": [
          {
            "Field": "name",
            "ArrayPositions": [],
            "Start": 6,
            "End": 11,
            "Position": 2
          }
        ]
      },
      "wor": {
        "Term": "d29y",
        "Locations": [
          {
            "Field": "name",
            "ArrayPositions": [],
            "Start": 6,
            "End": 11,
            "Position": 2
          }
        ]
      },
      "worl": {
        "Term": "d29ybA==",
        "Locations": [
          {
            "Field": "name",
            "ArrayPositions": [],
            "Start": 6,
            "End": 11,
            "Position": 2
          }
        ]
      },
      "world": {
        "Term": "d29ybGQ=",
        "Locations": [
          {
            "Field": "name",
            "ArrayPositions": [],
            "Start": 6,
            "End": 11,
            "Position": 2
          }
        ]
      }
    },
    null
  ]
}
----

[#g-api-scoped-status]
=== GET Index Status (Scoped)

Returns the status of the Search index specified in the endpoint URL, including whether all index partitions are created and ready to use. 

==== Endpoint

GET /api/bucket/`{$BUCKET_NAME}`/scope/`{$SCOPE_NAME}`/index/`{$INDEX_NAME}`/status

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!read

==== Role Required

*Search Reader* or *Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$BUCKET_NAME}`
| Yes
| String, URL path parameter
| The name of the bucket used to create the Search index definition. 

|[.param]`{$SCOPE_NAME}`
| Yes
| String, URL path parameter
| The name of the scope used to create the Search index definition. 

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
| The name of the Search index definition to status check. 

|====

.Sample success response
----
{
    "status": "ok",
    "indexStatus": "Ready"
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

== Index Querying

Use the following endpoints to query the contents of a Search index. 

[#g-api-index-name-count]
=== GET Indexed Documents Count

Returns the number of indexed documents inside the Search index specified in the endpoint URL.

==== Endpoint

GET /api/index/`{$INDEX_NAME}`/count

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!read

==== Role Required

*Search Reader* or *Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
a| The name of the index where you want to count the number of available documents.
You must use the fully qualified name for the index, which includes the bucket and scope.

To view the full, scoped name for an index for use with this endpoint: 

. Go to the *Search* tab in the Couchbase Server Web Console.
. Point to the *Index Name* for an index.

|====

.Sample success response
----
{
    "status": "ok",
    "count": 285
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

[#p-api-pindex-lookup]
=== POST Return the Index Partition and ID for a Document (Scoped)

Send a document ID in the request body and return the Search index partition ID for where the document is stored. 
The endpoint returns a JSON object as a response.  

==== Endpoint

POST /api/bucket/`{$BUCKET_NAME}`/scope/`{$SCOPE_NAME}`/index/`{$INDEX_NAME}`/pindexLookup

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!read

==== Role Required

*Search Reader* or *Search Admin*

==== Parameters 

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$BUCKET_NAME}`
| Yes
| String, URL path parameter
| The name of the bucket used to create the Search index definition. 

|[.param]`{$SCOPE_NAME}`
| Yes
| String, URL path parameter
| The name of the scope used to create the Search index definition. 

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
| The name of the Search index definition that contains the document. 

|====

==== Request Body 

Add a valid JSON object that contains the `docID` property, with a value that matches the document ID for a document in the Search index. 

For example: 
----
{
    "docID": "hotel_5848"
}
----

.Sample success response
----
{
    "status": "ok",
    "pindexes": {
        "travel-sample.inventory.travel-test": {
            "id": "travel-sample.inventory.travel-test_123294e5a4efbe39_4c1c5584"
        }
    }
}
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

[#p-api-index-name-query]
=== POST Query a Search Index

Run a query formatted as a JSON object against the Search index definition specified in the endpoint URL.
The endpoint returns a JSON object as a response.  

NOTE: This endpoint is for legacy Search indexes and may be deprecated in a future release.
Use <<p-api-scoped-query,>>, instead. 

==== Endpoint

POST /api/index/`{$INDEX_NAME}`/query

==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!read

==== Role Required

*Search Reader* or *Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
a| The name of the Search index definition to query with the request body.
You must use the fully qualified name for the index, which includes the bucket and scope.

To view the full, scoped name for an index for use with this endpoint: 

. Go to the *Search* tab in the Couchbase Server Web Console.
. Point to the *Index Name* for an index.

|====

==== Request Body

For more detailed information about how to format the request body for the POST /api/index/`{$INDEX_NAME}`/query endpoint, see xref:search:search-request-params.adoc[].

For example, the following request body searches for the text `a sample query` in the documents included in the Search index:

----
{
    "query": {
        "query": "a sample query",
        "boost": 1
    },
    "size": 10,
    "from": 0,
    "highlight": null,
    "fields": null,
    "facets": null,
    "explain": false
    }
----

The following request body uses from/size for results paging, uses ctl for a timeout and the "at_plus" consistency level.
On consistency, the index must have incorporated at least mutation sequence-number 123 for partition (vbucket) 0 and mutation sequence-number 234 for partition (vbucket) 1 (where vbucket 1 should have a vbucketUUID of a0b1c2):

----
{
    "ctl": {
        "timeout": 10000,
        "consistency": {
            "level": "at_plus",
                "vectors": {
                    "customerIndex": {
                        "0": 123,
                        "1/a0b1c2": 234
                    }
                }
            }
        },
        "query": {
            "query": "alice smith",
            "boost": 1
        },
        "size": 10,
        "from": 20,
        "highlight": {
            "style": null,
            "fields": null
        },
        "fields": [
            "*"
        ],
        "facets": null,
        "explain": true
}
----

The following hybrid search request body searches for a specified normalized color vector in `colorvect_dot`, but uses regular query parameters to limit the `brightness` value of the returned color to the range of `70-80`:

----
{
      "fields": ["*"], 
      "query": { 
        "min": 70, 
        "max": 80,  
        "inclusive_min": false,  
        "inclusive_max": true,  
        "field": "brightness" 
      }, 
      "knn": [
        {
          "k": 10, 
          "field": "colorvect_dot", 
          "vector": [ 0.707106781186548, 0, 0.707106781186548 ]
        }
      ], 
      "size": 10
}
----

For more information about vector searches, see xref:vector-search:vector-search.adoc[].

==== Response Object

The response object has a status section that must be checked for every request.
Under nearly all circumstances, the query response will be HTTP 200 even though individual index shards (pindexes) may encounter a timeout or return an error.

==== Consistency and Timeouts

A query can specify a timeout value, a consistency requirement, or both.
This section explains how this affects the query behavior and how to handle the resulting query return values.

* logical first phase consistency wait - if timeout in this period, get 416 error with message saying request could not be satisfied).
* If consistency wait times out with 416, return value to client will indicate the sequence number range processed so the client will have an idea how far the processing got and has the option of retrying more intelligently.
* In phase 2, you have the normal pindex timeout.
This will start whenever the first phase completes.
At this point, request will return 200 HTTP response code unless there is an internal server error.
* Client must check response status, which will return any errors or timeouts for each pindex.
If The response includes the number of errors, and the client can determine whether they need the complete results or can continue as long as enough pindexes return to give a reasonable user experience.
Note that the query return status will be 200 even if all pindexes return errors so it's critical to check the response status and code accordingly.
* If client sets timeout very low, e.g.
1ms, you may receive a 200 error with all timeouts instead of a consistency wait timeout.


[#p-api-scoped-query]
=== POST Query a Search Index (Scoped)

Run a query formatted as a JSON object against the Search index definition specified in the endpoint URL.
The endpoint returns a JSON object as a response. 
Unlike <<p-api-index-name-query,POST /api/index/{indexName}/query>>, this endpoint is scoped and does not require a fully qualified `${INDEX_NAME}` value.

==== Endpoint

POST /api/bucket/`{$BUCKET_NAME}`/scope/`{$SCOPE_NAME}`/index/`{$INDEX_NAME}`/query
 
==== Permission Required

cluster.bucket[[.var]`$BUCKET_NAME`].fts!read

==== Role Required

*Search Reader* or *Search Admin*

==== Parameters

[cols="1,1,1,2"]
|====
|Parameter |Required? |Type |Description

|[.param]`{$BUCKET_NAME}`
| Yes
| String, URL path parameter
| The name of the bucket used to create the Search index definition. 

|[.param]`{$SCOPE_NAME}`
| Yes
| String, URL path parameter
| The name of the scope used to create the Search index definition. 

|[.param]`{$INDEX_NAME}`
| Yes
| String, URL path parameter
| The name of the Search index definition to query with the request body. 

|==== 

==== Request Body

Add a JSON object to define the settings for your Search query.
For more information about how to create a Search query JSON object, see xref:search:search-request-params.adoc[].

.Sample failure response
----
{
    "error": "rest_index: Query, indexName: travel-sample.inventory.travel-test, err: bleve: QueryBleve parsing searchRequest, err: unknown query type",
    "request": {
        "collections": [
            "hotel"
        ],
        "ctl": {
            "consistency": {
                "level": "at_plus",
                "results": "complete",
                "vectors": {
                    "searchIndexName": {
                        "607/205096593892159": 2,
                        "640/298739127912798": 4
                    }
                }
            },
            "timeout": 10000
        },
        "explain": true,
        "from": 0,
        "highlight": {
            "fields": [
                "reviews.content"
            ],
            "style": "html"
        },
        "includeLocations": false,
        "limit": 10,
        "offset": 0,
        "query": {},
        "score": "none",
        "size": 10,
        "sort": [
            "reviews.Ratings.Cleanliness",
            {
                "by": "field",
                "desc": false,
                "field": "reviews.Ratings.Cleanliness",
                "missing": "last",
                "mode": "default",
                "type": "number"
            },
            "-_score",
            "-_id"
        ]
    },
    "status": "fail"
}
----
The Search Service returns a non-200 HTTP error code when a request fails. 

.Sample success response - regular query
[source,json]
----
include::example$fts-sample-success-response.jsonc[]
----
The Search Service returns a HTTP 200 status code with a response that includes `"status": "ok"`.

.Sample success response - hybrid vector search
[source,json]
----
include::example$fts-sample-success-response-vector-search.jsonc[]
----