= Managing Internal Settings
:description: Couchbase Server lets you retrieve and modify internal settings that control cluster performance.
:page-topic-type: reference

[abstract]
{description}

== HTTP Method and URI

.Get General Internal Settings
[source,url]
----
GET /internalSettings
----

.Set General Internal Settings
[source]
----
POST /internalSettings
----

.Get Max Parallel Indexers Setting
[source,url]
----
GET /settings/maxParallelIndexers
----

.Set Max Parallel Indexers Setting
[source]
----
POST /settings/maxParallelIndexers
----

[#description]
== Description

Couchbase Server lets you inspect and modify internal settings to control cluster performance.

[#warning]
[WARNING]
.Use With Care
====
Couchbase intends the settings on this page for performance tuning.
Always test any changes to these settings in a non-production environment that represents the load and scale of your production data before you implement them in production.
Incorrect settings can severely degrade cluster performance and operation through excessive resource consumption.
Couchbase does not recommend tuning beyond the default settings.
Couchbase does not support any changes to these settings unless a Couchbase employee explicitly recommends them.
====

== Getting Internal Settings

To get the current general internal settings for Couchbase Server, send a GET request to the `/internalSettings` endpoint.

[#get-curl-syntax]
=== curl Syntax

[source,bash]
----
curl -X GET http[s]://{host}:{port}/internalSettings
     -u $USER:$PASSWORD
----

==== Path Parameters
:required-privileges: required-privileges-get-internal
include::partial$user_pwd_host_port_params.adoc[]

[#required-privileges-get-internal]
=== Required Privileges

Your account must have at least 1 of the following roles to make a GET request to this endpoint:

* xref:learn:security/roles.adoc#full-admin[Full Admin]
* xref:learn:security/roles.adoc#cluster-admin[Cluster Admin]
* xref:learn:security/roles.adoc#ro-security-admin[Read-Only Security Admin]
* xref:learn:security/roles.adoc#security-admin[Security Admin]
* xref:learn:security/roles.adoc#local-user-security-admin[Local User Admin]

=== Responses

200 OK::
The request was successful.
Returns a JSON object containing all current general internal settings.

401 Unauthorized::
Authentication failed.

403 Forbidden::
The account making the request does not have 1 of the roles listed in <<required-privileges-get-internal>>.

404 Not Found::
The URI specified an incorrect hostname or port.
Also returns a JSON object containing an error message, such as the following:
+
[source,json]
----
{
  "error": "not_found",
  "reason": "missing"
}
----

=== Example

The following example gets the general internal settings for the cluster.
It pipes the output to the https://stedolan.github.io/jq/[jq^] command to make it easier to read.

[source,bash]
----
curl -X GET -u $USERNAME:$PASSWORD \
http://node1.example.com:8091/internalSettings | jq '.'
----

If successful, the call returns a JSON object such as the following:

[source,json]
----
{
  "indexAwareRebalanceDisabled": false,
  "rebalanceIndexWaitingDisabled": false,
  "rebalanceIndexPausingDisabled": false,
  "rebalanceIgnoreViewCompactions": false,
  "internalTlsMinVersion": "tlsv1.3",
  "rebalanceMovesBeforeCompaction": 64,
  "maxParallelIndexers": 4,
  "maxParallelReplicaIndexers": 2,
  "maxBucketCount": 30,
  "magmaMinMemoryQuota": 100,
  "eventLogsLimit": 10000,
  "gotraceback": "single",
  "failoverBulkJanitorFactor": 1,
  "certUseSha1": false,
  "clientCertNotAfterDurationSeconds": 71193600,
  "httpNodeAddition": false,
  "appTelemetryMinScrapeIntervalSeconds": 60,
  "appTelemetryMaxScrapeIntervalSeconds": 600,
  "argon2idTime": 3,
  "argon2idMem": 524288,
  "pbkdf2HmacSha512Iterations": 10000,
  "scramShaIterations": 15000,
  "useRelativeWebRedirects": true,
  "maxDocsSkip": 1000,
  "maxDocsLimit": 1000,
  "includeUsernameInUICookie": false,
  "dataServiceFileBasedRebalanceEnabled": true
}
----

== Setting Internal Settings

To change a general internal setting, send a `POST` to the `/internalSettings` endpoint, specifying the setting as an argument along with its new value.

[#curl-syntax]
=== curl Syntax

[source,bash]
----
curl -X POST http[s]://{host}:{port}/internalSettings
  -u $USER:$PASSWORD
  [-d eventLogsLimit=<integer>]
  [-d dataServiceFileBasedRebalanceEnabled=<true|false>]
  [-d <internal-setting>=<value>]
----

==== Path Parameters
:required-privileges: required-privileges-post-internal
include::partial$user_pwd_host_port_params.adoc[]

==== Parameters


`eventLogsLimit`::
(optional) Sets the maximum number of entries Couchbase Server retains in the xref:learn:clusters-and-availability/system-events.adoc[system event log].
Valid values are integers from `3000` to `20000`.

+
You can only change this value when every node in the cluster runs Couchbase Server 7.1 or higher.
If a cluster contains any node running a version of Couchbase Server less than 7.1, an attempt to change `eventLogsLimit` produces the following error message: `not supported in mixed version clusters`.


`dataServiceFileBasedRebalanceEnabled`::
(optional) Controls whether the data service's rebalance can use file-based backfills.
This value defaults to `true`.
For more information, see xref:learn:clusters-and-availability/rebalance.adoc#file-based-rebalance[File-Based Rebalance (FBR)].

`<internal-setting>`::
(optional) The name of any general internal setting, set to its new value.
See the <<#warning,warning at the top of this page>> before changing any settings in this REST API endpoint.


[#required-privileges-post-internal]
=== Required Privileges

Your account must have at least 1 of the following roles to make a POST request to this endpoint:

* xref:learn:security/roles.adoc#full-admin[Full Admin]
* xref:learn:security/roles.adoc#cluster-admin[Cluster Admin]

=== Responses

200 OK::
The request was successful.
Returns an empty array.

400 Bad Request::
The request specified an unknown setting or an invalid value.
Also returns a JSON object containing an error message, such as the following:
+
[source,json]
----
{"errors":["Unknown key rebalanceMovesPerNoede"]}
----

401 Unauthorized::
Authentication failed.

403 Forbidden::
The account making the request does not have 1 of the roles listed in <<required-privileges-post-internal>>.

404 Not Found::
The URI specified an incorrect hostname or port.

=== Examples


The following example changes the size of the system log to 15,000 entries:

[source,bash]
----
curl -X POST -u $USERNAME:$PASSWORD \
http://node1.example.com:8091/internalSettings \
-d eventLogsLimit=15000
----

If successful, the call returns an empty array.
Use the `GET` method to verify the modified value, which returns output such as the following:

[source,json]
----
{
  "indexAwareRebalanceDisabled": false,
  "rebalanceIndexWaitingDisabled": false,
  "rebalanceIndexPausingDisabled": false,
  "rebalanceIgnoreViewCompactions": false,
  "internalTlsMinVersion": "tlsv1.3",
  "rebalanceMovesBeforeCompaction": 64,
  "maxParallelIndexers": 4,
  "maxParallelReplicaIndexers": 2,
  "maxBucketCount": 30,
  "magmaMinMemoryQuota": 100,
  "eventLogsLimit": 15000,
  "gotraceback": "single",
  "failoverBulkJanitorFactor": 1,
  "certUseSha1": false,
  "clientCertNotAfterDurationSeconds": 71193600,
  "httpNodeAddition": false,
  "appTelemetryMinScrapeIntervalSeconds": 60,
  "appTelemetryMaxScrapeIntervalSeconds": 600,
  "argon2idTime": 3,
  "argon2idMem": 524288,
  "pbkdf2HmacSha512Iterations": 10000,
  "scramShaIterations": 15000,
  "useRelativeWebRedirects": true,
  "maxDocsSkip": 1000,
  "maxDocsLimit": 1000,
  "includeUsernameInUICookie": false,
  "dataServiceFileBasedRebalanceEnabled": true
}
----

The output confirms that `eventLogsLimit` is now `15000`.

== Getting the Max Parallel Indexers Setting

To get the current setting for the maximum number of parallel indexers, send a GET request to the `/settings/maxParallelIndexers` endpoint.

This setting applies only to View index configuration.
It does not apply to the GSI indexes that the Index Service provides.

[#get-mpi-curl-syntax]
=== curl Syntax

[source,bash]
----
curl -X GET http[s]://{host}:{port}/settings/maxParallelIndexers
     -u $USER:$PASSWORD
----

==== Path Parameters
:required-privileges: required-privileges-get-mpi
include::partial$user_pwd_host_port_params.adoc[]

[#required-privileges-get-mpi]
=== Required Privileges

Your account must have at least 1 of the following roles to make a GET request to this endpoint:

* xref:learn:security/roles.adoc#full-admin[Full Admin]
* xref:learn:security/roles.adoc#backup-full-admin[Backup Full Admin]
* xref:learn:security/roles.adoc#bucket-admin[Bucket Admin]
* xref:learn:security/roles.adoc#cluster-admin[Cluster Admin]
* xref:learn:security/roles.adoc#eventing-full-admin[Eventing Full Admin]
* xref:learn:security/roles.adoc#query-list-index[Query List Index]
* xref:learn:security/roles.adoc#query-manage-index[Query Manage Index]
* xref:learn:security/roles.adoc#query-system-catalog[Query System Catalog]
* xref:learn:security/roles.adoc#xdcr-admin[XDCR Admin]
* xref:learn:security/roles.adoc#read-only-admin[Read-Only Admin]
* xref:learn:security/roles.adoc#ro-security-admin[Read-Only Security Admin]
* xref:learn:security/roles.adoc#security-admin[Security Admin]
* xref:learn:security/roles.adoc#external-user-security-admin[External User Admin]
* xref:learn:security/roles.adoc#local-user-security-admin[Local User Admin]
* xref:learn:security/roles.adoc#views-admin[Views Admin (deprecated)]


=== Responses

200 OK::
The request was successful.
Returns a JSON object containing the current global value and the value for each node.

401 Unauthorized::
Authentication failed.

403 Forbidden::
The account making the request does not have 1 of the roles listed in <<required-privileges-get-mpi>>.

404 Not Found::
The URI specified an incorrect hostname or port.

=== Example

The following example gets the current setting for `maxParallelIndexers`:

[source,bash]
----
curl -X GET -u $USERNAME:$PASSWORD \
http://node1.example.com:8091/settings/maxParallelIndexers
----

If successful, the call returns a JSON object such as the following:

[source,json]
----
{"globalValue":4,"nodes":{"ns_1@node1.example.com":4}}
----

== Setting the Max Parallel Indexers Setting

To change the maximum number of parallel indexers, send a `POST` to the `/settings/maxParallelIndexers` endpoint, specifying the new value with the `globalValue` parameter.

[#set-mpi-curl-syntax]
=== curl Syntax

[source,bash]
----
curl -X POST http[s]://{host}:{port}/settings/maxParallelIndexers
  -u $COUCHBASE_USER:$PASSWORD
  -d globalValue=<integer>
----

==== Path Parameters
:required-privileges: required-privileges-post-mpi
include::partial$user_pwd_host_port_params.adoc[]

==== Parameters

`globalValue`::
(required) Sets the maximum number of parallel indexers cluster-wide.

+
Valid values are integers from `1` to `1024`.
The default value is `4`.

[#required-privileges-post-mpi]
=== Required Privileges

Your account must have at least 1 of the following roles to make a POST request to this endpoint:

* xref:learn:security/roles.adoc#full-admin[Full Admin]
* xref:learn:security/roles.adoc#backup-full-admin[Backup Full Admin]
* xref:learn:security/roles.adoc#cluster-admin[Cluster Admin]


=== Responses

200 OK::
The request was successful.
Returns a JSON object containing the new global value and the value for each node.

400 Bad Request::
The request specified a `globalValue` outside the valid range.

401 Unauthorized::
Authentication failed.

403 Forbidden::
The account making the request does not have 1 of the roles listed in <<required-privileges-post-mpi>>.

404 Not Found::
The URI specified an incorrect hostname or port.

=== Example

The following example sets `maxParallelIndexers` to `3`:

[source,bash]
----
curl -X POST -u $USERNAME:$PASSWORD \
http://node1.example.com:8091/settings/maxParallelIndexers \
-d globalValue=3
----

If successful, the call returns a JSON object confirming the new value cluster-wide:

[source,json]
----
{"globalValue":3,"nodes":{"ns_1@node1.example.com":3}}
----

[#see-also]
== See Also

* xref:rest-api:rest-limit-rebalance-moves.adoc[Limiting Concurrent vBucket Moves]
* xref:learn:clusters-and-availability/system-events.adoc[System Events]
* xref:manage:manage-settings/manage-settings.adoc[Manage Settings]
