= Certificate Management API

[abstract]
The REST API can be used to manage the root and node certificates of a cluster.

[#performing-certificate-management]
== Performing Certificate Management

Couchbase Server supports the use of x.509 certificates, for clients and servers.
The REST API allows the server certificates to be managed.
Server certificates are of two kinds:

* _Root_ certificates.
A single root certificate exists for each cluster.
This certificate, which is sometimes referred to as the _cluster_ certificate, contains the public key of a Certificate Authority (CA).
Programs that wish to interact securely with Couchbase Server must elect to trust this CA.

* _Node_ certificates.
One node certificate exists for, and is installed on each node in the cluster.
This certificate is _signed_ by the root certificate (or by an intermediate certificate that itself has gained authority from the root), and is itself therefore granted the authority of the CA.
Clients that contact the node can determine the identity of the CA by examining the node certificate, and verifying its signature chain to the root certificate.

A complete overview of certificate management for Couchbase Server is provided in xref:learn:security/certificates.adoc[Certificates].
Examples of certificate creation and deployment are provided in xref:manage:manage-security/manage-certificates.adoc[Manage Certificates].

[#the-rest-api-for-certificate-management]
== The REST API for Certificate Management

The Couchbase Server REST API supports certificate management as follows:

* The current root certificate can be retrieved and examined; and can be used to gather information on the cluster.
A new root certificate can be uploaded.
See xref:rest-api:upload-retrieve-root-cert.adoc[Upload and Retrieve the Root Certificate].

* The current certificate for a specific node can be retrieved and examined.
A new node certificate can be uploaded.
See xref:rest-api:upload-retrieve-node-cert.adoc[Upload and Retrieve a Node Certificate].

* All certificates &#8212; root and node &#8212; can be _regenerated_ (that is, restored to their automatically provided default values).
See xref:rest-api:rest-regenerate-all-certs.adoc[Regenerate All Certificates].
