[#rest-bucket-flush]
= Flushing buckets

[abstract]
The `doFlush` operation empties the contents of the specified bucket, deleting all stored data.

== Syntax

The syntax is as follows:

----
curl -X POST -u [admin]:[password]
  [localhost]:8091/pools/default/buckets/[bucket-name]/controller/doFlush
----

Raw HTTP request syntax:

----
POST /pools/default/buckets/default/controller/doFlush
Host: localhost:8091
Authorization: Basic xxxxxxxxxxxxxxxxxxx
----

== Description

The `doFlush` operation succeeds only if flush is enabled on the configured bucket.

WARNING: This operation is data destructive.
The service makes no attempt to confirm or double check the request.
Client applications using this are advised to double check with the end user before sending such a request.
You can control and limit the ability to flush individual buckets by setting the `flushEnabled` parameter on a bucket in Couchbase Web Console or via `cbepctl flush_param`.

Parameters and payload data are ignored, but the request must including the authorization header if the system has been secured.

IMPORTANT: The flush request may lead to significant disk activity as the data in the bucket is deleted from the database.
The high disk utilization may affect the performance of your server until the data has been successfully deleted.

NOTE: The flush request is not transmitted over XDCR replication configurations;.
The remote bucket is not flushed.

Couchbase Server returns a HTTP 404 response if the URI is invalid or if it does not correspond to an active bucket in the system.

== HTTP method and URI

----
POST /pools/default/buckets/default/controller/doFlush
----

== Example

This is an example of flushing the default bucket:

----
curl -X POST 'http://Administrator:password@localhost:8091/pools/ \
        default/buckets/default/controller/doFlush'
----

Raw HTTP request example:

----
POST /pools/default/buckets/default/controller/doFlush
Host: 10.5.2.54:8091
Authorization: Basic xxxxxxxxxxxxxxxxxxx
----

== Response codes

If the flush is successful, the HTTP response code is `200` is returned.

----
HTTP/1.1 200 OK
----

If flushing is disable for the specified bucket, a 400 response code is returned with the bucket status.
For example:

----
{"_":"Flush is disabled for the bucket"}
----

If the bucket does not exist, a 404 response code is returned.

----
404 Not Found
----
