= Certificate Management API
:description: The REST API can be used to manage the root and node certificates of a cluster.

[abstract]
{description}

[#performing-certificate-management]
== Performing Certificate Management

Couchbase Server supports the use of x.509 certificates, for clients and servers.
The REST API allows the server certificates to be managed.
From a management perspective, server certificates can be considered to be of two kinds:

* _Root_ certificates.
At least one root certificate exists for each cluster.
Any number of root certificates can be uploaded: together, these constitute the cluster's _trust store_.
Each root certificate contains the public key of a Certificate Authority (CA).
+
Couchbase Server uses its list of trusted certificates to verify:

** Client certificates (when client certificate authentication is enabled: for information, see xref:manage:manage-security/enable-client-certificate-handling.adoc[Enable Client-Certificate Handling]).

** The identities of cluster nodes (when node-to-node encryption is enabled: for information, see xref:manage:manage-nodes/apply-node-to-node-encryption.adoc[Manage Node-to-Node Encryption]).

** The identities of nodes that join the cluster (when the server has been provisioned with certificates).

** The identity of LDAP servers (when TLS has been turned on, in the LDAP settings: for information, see xref:manage:manage-security/configure-ldap.adoc#ldap-host-configuration[LDAP Host Configuration]).

* _Node_ certificates.
A different node certificate is installed on each node in the cluster.
This certificate is _signed_ by a root certificate (or by an intermediate certificate that itself has gained authority from that root certificate), and is itself therefore granted the authority of that root certificate.
Clients that contact the node can determine the identity of the root certificate by examining the node certificate, and verifying its signature chain &#8212;  which leads to the responsible root certificate.

A complete overview of certificate management for Couchbase Server is provided in xref:learn:security/certificates.adoc[Certificates].
Examples of certificate creation and deployment are provided in xref:manage:manage-security/manage-certificates.adoc[Manage Certificates].

[#the-rest-api-for-certificate-management]
== The REST API for Certificate Management

The Couchbase Server supports certificate management with the following, principal APIs:

* Root certificates can be uploaded, retrieved, and deleted.
See xref:rest-api:load-trusted-cas.adoc[Load Root Certificates], xref:rest-api:get-trusted-cas.adoc[Get Root Certificates], and xref:rest-api:delete-trusted-cas.adoc[Delete Root Certificates].

* The current certificate for a specific node can be uploaded and retrieved.
See xref:rest-api:upload-retrieve-node-cert.adoc[Upload and Retrieve a Node Certificate].
Additionally, all current node certificates for the cluster can be retrieved: see xref:rest-api:retrieve-all-node-certs.adoc[Retrieve All Node Certificates].

* All certificates &#8212; root and node &#8212; can be _regenerated_ (that is, restored to their automatically provided default values).
See xref:rest-api:rest-regenerate-all-certs.adoc[Regenerate All Certificates].
