= Failing over Nodes
:page-topic-type: reference

[abstract]
Nodes are failed over via hard failover via the `POST /controller/failOver` HTTP method and URI.

== HTTP method and URI

Failing over a node indicates that the node is no longer available in a cluster and replicated data on another node should be made available to clients.
This endpoint along with the `otpNode` parameter (internal node name) fails over a specific node.

----
POST /controller/failOver
----

== Syntax

HTTP request syntax:

----
POST /controller/failOver HTTP/1.1
Authorization: Basic
----

Curl request syntax:

----
curl -v -X POST
-u admin:password http://localhost:port/controller/failOver -d otpNode=[node@hostname]
----

== Example

The following examples fails over server node `10.3.3.63` from a cluster with the local host, 10.5.2.54.

----
curl -v -X POST \
  -u Administrator:password http://10.5.2.54:8091/controller/failOver \
  -d 'otpNode=ns_2@10.3.3.63'
----

== Response codes

[cols="100,471"]
|===
| Response codes | Description

| 200
| OK

| 400
| Bad Request JSON: The RAM Quota value is too small.

| 401
| Unauthorized
|===

The following example is a successful response:

----
HTTP/1.1 200 OK
----

The following example is an unsuccessful response, for example, if the node does not exist in the cluster.

----
HTTP/1.1 400
----
