= Performing Hard Failover
:page-topic-type: reference

[abstract]
_Hard_ failover drops a node from a cluster reactively, because the node has become unresponsive or unstable.

[#http-method-and-uri]
== HTTP Method and URI

----
POST /controller/failOver
----

[#description]
== Description

Hard failover should be performed when a node is no longer available to the rest of the cluster.
In consequence of hard failover, replica vBuckets on surviving nodes are promoted to _active_ status, so that data can continue to be served.

A rebalance is always required following hard failover.

== Curl Syntax

----
curl -v -X POST -u <username>:<password>
  http://<ip-address-or-hostname>:<port>/controller/failOver
  -d otpNode=[ node@hostname ]
  -d allowUnsafe=< true | false >
----

The value of the `optNode` parameter must be one or more node-names, comma-separated; which correspond to the nodes that will be hard-failed over.

The value of `allowUnsafe` must be either `true` or `false` (which is the default); indicating whether the hard failover should be attempted in either _safe_ or _unsafe_ mode.
For information, see xref:learn:clusters-and-availability/hard-failover.adoc#safe-and-unsafe[Hard-Failover Modes: Safe and Unsafe].

[#responses]
== Responses

Success returns `200 OK`.

Incorrectly specifying the target cluster returns `Failed to connect`.
Incorrectly specifying the URI returns a `404 Object Not Found` error, and a `Requested resource not found` notification.

Specifying an unknown server to be failed over returns a `400 Bad Request` notification, and an error message such as the following: `Unknown server given: ["ns_1@10.143.201.106"]`.

Failure to authenticate returns a `401 Unauthorized` notification.

[#examples]
== Examples

The following curl statement performs a safe, hard failover of server node 10.142.180.102 from a cluster with localhost 10.142.180.1.

[source,bourne]
----
curl -v -X POST -u Administrator:password \
http://10.142.180.1:8091/controller/failOver \
-d 'otpNode=ns_1@10.142.180.102'
----

The following curl statement performs a safe, hard failover of server nodes 10.142.180.102 and 10.142.180.103 from a cluster with localhost 10.142.180.1.
Note that multi-node failover is always _hard_ failover.

[source,bourne]
----
curl -v -X POST -u Administrator:password \
http://10.142.180.1:8091/controller/failOver \
-d 'otpNode=ns_1@10.142.180.102' \
-d 'otpNode=ns_1@10.142.180.103'
----

The following performs an _unsafe_, hard failover of server nodes 10.142.180.102 and 10.142.180.103 from a cluster with localhost 10.142.180.1.

[source,bourne]
----
curl -v -X POST -u Administrator:password \
http://10.142.180.1:8091/controller/failOver \
-d 'otpNode=ns_1@10.142.180.102' \
-d 'otpNode=ns_1@10.142.180.103'\
-d 'allowUnsafe=true'
----
