= Setting Password Policy
:page-topic-type: reference

[abstract]
The REST API allows the  _password policy_ for a cluster to be established and retrieved by means of the `POST` and `GET` methods respectively, using the `/settings/passwordPolicy` URI.

[#http-method-and-uri]
== HTTP methods and URI

----
GET /settings/passwordPolicy
POST /settings/passwordPolicy
----

[#rest-password-policy-description]
== Description

A cluster's _password policy_ specifies a set of character-related requirements to be met by all passwords whose definition occurs subsequent to the establishing of the policy.
Previously defined passwords continue to be valid, even if they do not meet the most recently specified requirements.

To establish the cluster's password policy, the user must have been assigned either the Full Admin or the Security Admin role.

[#curl-syntax]
== Curl Syntax

----
curl -v -X POST -u [username]:[password]
  http://[ip-address-or-domain-name]:8091/settings/passwordPolicy
  -d minlength=<integer>
  -d enforceUpperCase=[ true | false ]
  -d enforceLowerCase=[ true | false ]
  -d enforceDigits=[ true | false ]
  -d enforceSpecialChars=[ true | false ]

curl -v -X GET -u [username]:[password]
  http://[ip-address-or-domain-name]:8091/settings/passwordPolicy
----

The `minLength` parameter establishes a minimum length for the password: this must be an integer between `0` and `100`, inclusive.
The `enforceUpperCase` and `enforceLowerCase` flags establish whether the password must contain at least one uppercase or lowercase character, respectively: the value of each must be either `true` or `false`.
The `enforceDigits` and `enforceSpecialChars` flags establish whether the password must contain at least one digit or special character, respectively: the value of each must be either `true` or `false`.
