= Getting Bucket Information
:description: Information on buckets defined on the cluster can be retrieved, by means of the REST API.
:page-topic-type: reference
:page-aliases: rest-bucket-info

[abstract]
{description}

[#http-methods-and-uris]
== HTTP Methods and URIs

----
GET /pools/default/buckets

GET /pools/default/buckets/<bucket-name>
----

[#description]
== Description

`GET /pools/default/buckets` retrieves information on all buckets defined on the cluster.
If the `<bucket-name>` path-parameter is added, only information on the specified bucket is retrieved.


[#curl-syntax]
== Curl Syntax

----
curl -X GET http://<ip-address-or-domain-name>:8091/pools/default/buckets/<bucket-name>
----

[#responses]
== Responses

Successful execution returns `200 OK`, and either an object containing information on the individual bucket specified by the path-parameter; or an array of such objects, each containing information on one of the buckets defined on the cluster.

Failure to authenticate returns `401 Unauthorized`.
An incorrectly specified URI returns `404 Object Not Found`.
If an internal error prevents successful execution, `500 Internal Server Error` is returned.

[#example]
== Example

The following example returns information on a single bucket, which is `testBucket`.
The output of the call is piped to https://stedolan.github.io/jq/[jq^], to facilitate readability.

----
curl -X GET -u Administrator:password \
http://localhost:8091/pools/default/buckets/testBucket | jq '.'
----

If successful, the call returns `200 OK`, and an object such as the following.
(Note that actual console-output contains an extensive array of vBucket-information: this has been omitted from this example.)

The fields `historyRetentionCollectionDefault`, `historyRetentionCollectionBytes`, and `historyRetentionCollectionSeconds` are specific to _Magma_ storage: if `magma` is not the value of `storageBackend`, these parameters are not displayed.

[source, json]
----
include::partial$get_bucket_travel_sample.json[]
----

NOTE: Couchbase Server version 7.6.2 added a property named `enableCrossClusterVersioning` to support a future feature. 
Do not change the value of this field. 
Once enabled, you cannot turn it off. 
See the xref:rest-bucket-create.adoc#notes[Notes] section of xref:rest-bucket-create.adoc[] for more information.


[#see-also]
== See Also

An overview of buckets is provided in xref:learn:buckets-memory-and-storage/buckets.adoc[Buckets].
An introduction to scopes and collections is provided in xref:learn:data/scopes-and-collections.adoc[Scopes and Collections].
