= Retrieving Auto-Failover Settings
:description: pass:q[Auto-failover settings are retrieved by means of the `GET /settings/autoFailover` HTTP method and URI.]
:page-topic-type: reference

[abstract]
{description}

== HTTP method and URI

[source,bourne]
----
GET /settings/autoFailover
----

== Description

The `GET /settings/autoFailover` HTTP method and URI retrieve auto-failover settings for the cluster.

Auto-failover settings are global, and apply to all nodes in the cluster.


== Curl Syntax

[source,bourne]
----
curl -X GET http://<ip-address-or-hostname>:8091/settings/autoFailover
  -u <username>:<password>
----

== Required Privileges

You must have one of the following roles to retrieve auto-failover settings:

* xref:learn:security/roles.adoc#full-admin[Full Admin]
* xref:learn:security/roles.adoc#backup-full-admin[Backup Full Admin]
* xref:learn:security/roles.adoc#bucket-admin[Bucket Admin]
* xref:learn:security/roles.adoc#cluster-admin[Cluster Admin]
* xref:learn:security/roles.adoc#eventing-full-admin[Eventing Full Admin]
* xref:learn:security/roles.adoc#xdcr-admin[XDCR Admin]
* xref:learn:security/roles.adoc#read-only-admin[Read-Only Admin]
* xref:learn:security/roles.adoc#ro-security-admin[Read-Only Security Admin]
* xref:learn:security/roles.adoc#security-admin[Security Admin]
* xref:learn:security/roles.adoc#external-user-security-admin[External User Admin]
* xref:learn:security/roles.adoc#local-user-security-admin[Local User Admin]
* xref:learn:security/roles.adoc#views-admin[Views Admin]

== Responses

Success returns `200 OK`, and an object that contains the following parameters:

* `enabled`.
Indicates whether automatic failover is enabled (a value of `true`) or disabled (a value of `false`).

* `timeout`.
Returns an integer between 5 and 3600, which specifies the number of seconds set to elapse, after a node has become unavailable, before automatic failover is triggered.
The default value is 120.

* `count`.
This parameter represents how many auto-failover nodes have occurred since the parameter was itself last reset, to a value of 0, through administrator intervention.
The parameter's default value is 1.
Couchbase Server increments this value by 1 for every node that is auto-failed over, up to the administrator-specified _maximum count_.
If nodes are failed over automatically until the _maximum count_ is reached, no further auto-failover is triggered until a parameter-reset is performed.

* `failoverOnDataDiskIssues`.
This contains two values, which are:

** `enabled`, which indicates whether auto-failover can occur when a disk has been unresponsive, and which can be `true` or `false` (the default).

** `timePeriod`, which indicates the administrator-specified time-period, in seconds, after which auto-failover is triggered, when a disk is unresponsive.
The value is an integer between 5 and 3600.

* `maxCount`.
The administrator-specified maximum number of nodes that can be concurrently auto-failed over.
If nodes are auto-failed over until the value of `maxCount` is reached, no further auto-failover is triggered until a parameter-reset is performed.
The default value is 1.

* `canAbortRebalance`.
Whether or not auto-failover can be triggered if a _rebalance_ is in progress.
This feature is only available in Couchbase Enterprise Edition.
The value can be either `true` (the default) or `false`.

Failure to authenticate returns `401 Unauthorized`.
An incorrectly specified URL returns `404 Object Not Found`.

== Example

The following example returns the auto-failover settings for the cluster.
The output is piped to the https://stedolan.github.io/jq[jq^] command, to facilitate readability.

[source,bourne]
----
curl -X GET http://localhost:8091/settings/autoFailover -u Administrator:password | jq '.'
----

If successful, execution returns the auto-failover settings for the cluster.
For example:

[source,json]
----
{
  "enabled": true,
  "timeout": 72,
  "count": 0,
  "failoverOnDataDiskIssues": {
    "enabled": true,
    "timePeriod": 89
  },
  "maxCount": 2,
  "canAbortRebalance": true
}
----

== See Also

For information on setting auto-failover parameters with the REST API, see xref:rest-api:rest-cluster-autofailover-enable.adoc[Enabling and Disabling Auto-Failover].

The Couchbase CLI allows auto-failover to be managed by means of the xref:cli:cbcli/couchbase-cli-setting-autofailover.adoc[setting-autofailover] command.
For information on managing auto-failover with Couchbase Web Console, see xref:manage:manage-settings/general-settings.adoc#node-availability[Node Availability].

A full description of auto-failover is provided in xref:learn:clusters-and-availability/automatic-failover.adoc[Automatic Failover].
