= Assigning Services

:description: pass:q[By means of the REST API, services can be assigned to a new, single-node cluster.]
:page-topic-type: reference

[abstract]
{description}

[#http-method-and-uri]
== HTTP Method and URI

----
POST /node/controller/rename
----

[#description]
== Description

Sets up the services for a one-node cluster, as part of its initial provisioning.

== Curl Syntax

----
curl  -X POST http://<ip-address-or-domain-name>:8091/node/controller/setupServices \
-d 'services=<list-of-service-names>'
----

The `list-of-service-names` must consist of one or more of the following: `kv` (Data Service), `n1ql` (Query Service), `index` (Index Service), `fts` (Search Service),`eventing` (Eventing Service), `cbas` (Analytics Service), `backup` (Backup Service).
Each name must be separated from the following name with a comma.

Each service is allocated a default amount of memory, unless custom allocations have been made.
See xref:rest-api:rest-configure-memory-allocations.adoc[Configuring Memory] for information on allocating memory per service, and on the default minimum values per service.

== Responses

Success returns `200 OK`.




== Example

The following example establishes data paths for the Data, Index, and Eventing Services.
Commas in the list of service-names have been encoded.

----
curl  -v -X POST http://10.144.220.101:8091/node/controller/setupServices \
-d 'services=kv%2Cn1ql%2Cindex%2Ceventing'
----

== See Also

See xref:rest-api:rest-configure-memory-allocations.adoc[Configuring Memory] for information on allocating memory per service, and on the default minimum values per service.
