= Naming a Cluster

:description: pass:q[A cluster can be named, by means of the REST API.]
:page-topic-type: reference

[abstract]
{description}

[#http-method-and-uri]
== HTTP Method and URI

----
POST /pools/default
----

[#description]
== Description

Establishes a name for the cluster.
Either the Full Admin or the Cluster Admin role is required.

Once defined, the cluster name provides a convenient, verbal reference, which will never be used in programmatic or networked access.
The name can be of any length, can make use of any symbols (for example: %, $, !, #), and can include spaces.
The name can be changed at any time during the life of the cluster, irrespective of the cluster’s configuration.

== Curl Syntax

----
curl -X POST http://<ip-address-or-domain-name>:8091/pools/default \
-d clusterName=<cluster-name>
-u <username>:<password>
----

== Responses

Success returns `200 OK`.
If a username and password have already been assigned, failure to authenticate returns `401 Unauthorized`.
An incorrectly expressed URI or flag returns `404 Object Not Found`.

== Example

----
curl -X POST http://10.144.220.101:8091/pools/default \
-d clusterName=MyNewCluster3 -u Administrator:password
----

== See Also

For general information on naming, see xref:learn:clusters-and-availability/nodes.adoc#naming-clusters-and-nodes[Naming Clusters and Nodes].
