= Managing Sample Buckets
:description: pass:q[Couchbase Server offers several sample buckets you can install for development and testing.]
:page-topic-type: reference

[abstract]


== Description

{description}


== HTTP Methods and URIs

----
GET /sampleBuckets

POST /sampleBuckets/install
----

== Description

Gets the list of sample buckets available in Couchbase Server and installs one or more sample buckets.

== Curl Syntax

[source,console]
----
curl -X GET -u USERNAME:PASSWORD
  http://NODE_NAME_OR_IP:PORT/sampleBuckets

curl -X POST -u USERNAME:PASSWORD
  http://NODE_NAME_OR_IP:PORT/sampleBuckets/install
  -d '[ "SAMPLE_BUCKET_NAME", ... ]'
----

* *`NODENAME_OR_IP`*: a node in the cluster.
* *`"SAMPLE_BUCKET_NAME"`*: the name of a sample bucket, specified as a string. You can provide a comma separated list of sample buckets to install.

== Responses

If the GET succeeds, it returns `200 OK` and a JSON object describing available sample buckets.

If the POST succeeds, it returns `200 OK` and a JSON array containing information about the tasks Couchbase Server started to load the buckets.

For either endpoint, an incorrectly specified bucket-name or URI gives `404 Object Not Found`; and failure to authenticate gives `401 Unauthorized`.

Calling the POST endpoint to install one or more sample buckets that are already installed returns a list containing a message for each error; such as `["Sample bucket travel-sample is already loaded.","Sample bucket beer-sample is already loaded."]`.

== Examples

The following example retrieves a list of the currently available sample buckets.
Note that the output is piped to the https://https://stedolan.github.io/jq/[jq] program, to facilitate readability.

[source,console]
----
curl -X GET -u Administrator:password \
http://10.143.194.101:8091/sampleBuckets | jq
----

If successful, the call returns output similar to the following:

[source,json]
----
[
  {
    "name": "beer-sample",
    "installed": false,
    "quotaNeeded": 104857600
  },
  {
    "name": "gamesim-sample",
    "installed": false,
    "quotaNeeded": 104857600
  },
  {
    "name": "travel-sample",
    "installed": false,
    "quotaNeeded": 104857600
  }
]
----

The output lists the available sample buckets and whether it's installed and the memory required to install the bucket.

NOTE: the `quotaNeeded` value is the minimum that Couchbase Server must have available. 
The sample bucket might not consume this entire value when you install it.

The following example installs the `travel-sample` and `beer-sample` sample buckets:

[source,console]
----
include::rest-api:example$install-sample-bucket.sh[]
----

If successful, the call returns a JSON array containing the tasks that Couchbase Server started to load the buckets:

[source,json]
----
include::rest-api:example$sample-bucket-install-response.json[]
----

You can monitor the status of these tasks by calling the `/pools/default/tasks` REST API endpoint. 
See xref:rest-get-cluster-tasks.adoc[] for more information.

== See Also

* For an overview of sample buckets, see xref:manage:manage-settings/install-sample-buckets.adoc[].
* xref:rest-api:rest-bucket-delete.adoc[] explains deleting buckets using the REST-API.
* xref:cli:cbdocloader-tool.adoc[cbdocloader] explains how to install sample buckets using the command line interface.
* xref:manage:manage-settings/install-sample-buckets.adoc[] explains how to load sample buckets using the Couchbase Server Web Console.
