= Server Groups API
:page-topic-type: reference

[abstract]
The _Server Groups REST API_ manages _Server Group Awareness_.
This enables logical server-groupings to be defined across the cluster: each group may be physically located on a specific rack or availability zone.

[#description]
== Description

_Server Group Awareness_, which is only available in Couchbase Server Enterprise Edition, provides enhanced availability.
Specifically, it protects a cluster from large-scale infrastructure failure, through the definition of _groups_.
Each group is created by an appropriately authorized administrator, and specified to contain a subset of the nodes within a Couchbase Cluster.
Following group-definition and rebalance, the active vBuckets for any defined bucket are located on one group, while the corresponding replicas are located on another group.
This allows _Group Failover_ to be enabled, so that if an entire group goes offline, its replica vBuckets, which remain available on another group, can be automatically promoted to active status.

For a complete conceptual overview, see xref:learn:clusters-and-availability/groups.adoc[Server Group Awareness].

_Server Group Awareness_ is supported by the _Server Groups REST API_, whose capabilites are summarized below.

.Server group endpoints
[cols="100,318,207,120"]
|===
| HTTP method | URI path | Description | Required Role

| GET
| [.path]_/pools/default/serverGroups_
| xref:rest-api:rest-servergroup-get.adoc[Retrieves] information about the current server-group configuration.
| Full, Cluster

| POST
| [.path]_/pools/default/serverGroups_
| xref:rest-api:rest-servergroup-post-create.adoc[Creates] and uniquely names a server group.
| Full, Cluster

| POST
| [.path]_/pools/default/serverGroups/<:uuid>/addNode
| xref:rest-api:rest-servergroup-post-add.adoc[Adds] a node to the cluster, and simultaneously assigns it to an existing server group.
| Full, Cluster

| PUT
| [.path]_/pools/default/serverGroups/<:uuid>_
| xref:rest-api:rest-servergroup-put.adoc[Renames] a server group.
| Full, Cluster

| PUT
| [.path]_/pools/default/serverGroups?rev=<:number>_
| xref:rest-api:rest-servergroup-put-membership.adoc[Updates] the assignment of nodes to server groups.
| Full, Cluster

| DELETE
| [.path]_/pools/default/serverGroups/<:uuid>_
| xref:rest-api:rest-servergroup-delete.adoc[Deletes] a specific server group.
| Full, Cluster
|===

For information on Couchbase _Role-Based Access Control_, see xref:learn:security/roles.adoc[Roles].
