= Managing Bloom Filters
:description: pass:q[The REST API allows Bloom filters to be enabled for Plasma storage.]

[abstract]
{description}


[#http-methods-and-uris]
== HTTP Methods and URIs

----
GET /settings

POST /settings
----

[#description]
== Description

A https://en.wikipedia.org/wiki/Bloom_filter[Bloom filter^] is used by the Index Service to give guidance as to whether a searched-for item resides on disk.
By indicating that the item is _not_ on disk, the filter prevents unnecessary on-disk searches.

Bloom filters can be enabled for _Plasma_ storage: either the Full Admin or the Cluster Admin role is required.
For an overview, see xref:learn:services-and-indexes/indexes/storage-modes.adoc#per-page-bloom-filters[Per Page Bloom Filters].

== Curl Syntax

----
curl -X GET -u <username:password> \
  http://<ip-address-or-domain-name>:<port-number>/settings

curl -X POST -u <username:password> \
  http://<ip-address-or-domain-name>:<port-number>/settings \
  -d '{"indexer.plasma.backIndex.enablePageBloomFilter":< true | false >}'
----

The `port-number` must be either `9102` or `19102`. which are the `indexer_http_port` and `indexer_https_port` respectively, of an Index-Service node in the cluster.
A value of `true`, specified for the key `"indexer.plasma.backIndex.enablePageBloomFilter"`, _enables_ Bloom filters for all Index-Service nodes; a value of `false` _disables_.
By default, Bloom filters are disabled.

== Responses

Successful use of the `GET` method returns `200 OK` and an object containing indexer settings.
Successful use of the `POST` method returns `200 OK`, and the notification `OK`.

Failure to authenticate returns `401 Unauthorized`.
Successful authentication with an inappropriate role returns `403 Forbidden`.
An incorrectly specified URI returns `404 Object Not Found`.
An incorrectly specified method returns `400 Bad Request`.

== Examples

The following use of the `GET` method returns indexer statistics.
Note that the output of the command is piped to the https://stedolan.github.io/jq/[jq^] command, to enhance readability:

----
curl -X GET -u Administrator:password http://localhost:9102/settings | jq '.'
----

If successful, the command returns `200 OK` and a list of index settings, a subset of which is shown below:

----
{
  "indexer.settings.allow_large_keys": true,
  "indexer.settings.bufferPoolBlockSize": 16384,
  "indexer.settings.build.batch_size": 5,
  "indexer.settings.compaction.abort_exceed_interval": false,
                      .
                      .
                      .
  "indexer.settings.enable_page_bloom_filter": false,
                      .
                      .
                      .
  "queryport.client.settings.poolSize": 5000,
  "queryport.client.settings.relConnBatchSize": 100
}
----

This indicates that Bloom filters are _not_ enabled.

To enable Bloom filters, enter the following:

----
curl -X POST -u Administrator:password http://localhost:9102/settings \
-d '{"indexer.plasma.backIndex.enablePageBloomFilter":true}'
----

If successful, the command returns the following notification:

----
OK
----

Successful enablement of Bloom filters can now be confirmed by further use of the `GET` method.

== See Also

Bloom filters for the Index Service are described in xref:learn:services-and-indexes/indexes/storage-modes.adoc#per-page-bloom-filters[Per Page Bloom Filters].
