= Views API
:page-topic-type: reference

[abstract]
The Views REST API is used to index and query JSON documents.

== Description

Views are functions written in JavaScript that can serve several purposes in your application.
You can use them to: find all the documents in your database, create a copy of data in a document and present it in a specific order, create an index to efficiently find documents by a particular value or by a particular structure in the document, represent relationships between documents, and perform calculations on data contained in documents.

NOTE: View functions are stored in a design document as JSON.
You can use the REST API to manage your design documents.

.Views endpoints
[cols="100,252,171,167"]
|===
| HTTP method | URI path | Description | Admin Role

| GET
| [.path]_/[bucket_name]/_design/[ddoc-name]_
| Retrieves all views design documents.
| Full, Cluster, View

| GET
| [.path]_/[bucket_name]/_design/[ddoc-name]/_view/[view-name]_
| Retrieves views.
| Full, Cluster, View

| PUT
| [.path]_/[bucket_name]/_design/[ddoc-name]_
| Creates a new design document with one or more views.
| Full, Cluster

| DELETE
| [.path]_/[bucket_name]/_design/[ddoc-name]_
| Deletes design documents.
| Full, Cluster

| POST
| [.path]_/internalSettings_
| Changes the number of simultaneous requests each node can accept.
| Full, Cluster
|===
