= Change Password
:description: A local user of Couchbase Server can change their password.

[abstract]
{description}

[#http-methods-and-uris]
== HTTP Method and URI

----
POST /controller/changePassword 
----

[#description]
== Description

Changes the current, locally defined user-password to a new user-password.

[#curl-syntax]
== Curl Syntax

----
curl -X POST http://<ip-address-or-domain-name>:8091/controller/changePassword
  -u <username>:<password>
  -d <new-password>
----

The specified `new-password` must be for a locally defined user, and must conform to the currently established _password policy_ for the cluster.
The default policy is described in xref:learn:security/usernames-and-passwords.adoc#password-strengthd[Password Strength].
For instructions on changing the current password policy, see xref:rest-api:rest-set-password-policy.adoc[Set Password Policy].
For information on _local_ and _external_ domains, see xref:learn:security/authentication-domains.adoc[Authentication Domains].

[#responses]
== Responses

Success returns `200 OK`.
Failure to authenticate returns `401 Unauthorized`.
A malformed URI returns `404 Object Not Found`.

[#examples]
== Examples

The following example changes the locally defined password of user `localUser` from `localUserPassword` to `localUserNewPassword`:

----
curl -v -X POST http://localhost:8091/controller/changePassword \
-u localUser:localUserPassword \
-d password=localUserNewPassword
----


[#see-also]
== See Also

The default policy is described in xref:learn:security/usernames-and-passwords.adoc#password-strengthd[Password Strength].
For instructions on changing the current password policy, see xref:rest-api:rest-set-password-policy.adoc[Set Password Policy].
For information on _local_ and _external_ domains, see xref:learn:security/authentication-domains.adoc[Authentication Domains].
