= Active Queries REST API

== Overview

The Active Queries REST API is provided by the Search service.
This API enables you to get information about active FTS queries.

The API schemes and host URLs are as follows:{blank}

* `+http://node:8094/+`
* `+https://node:18094/+` (for secure access)

where [.var]`node` is the host name or IP address of a computer running the Search service.


=== Version information
[%hardbreaks]
__Version__ : 7.0

=== Produces

* `application/json`

== Paths

*{toc-title}*

* <<api-query-index>>
* <<api-query>>
* <<api-query-cancel>>

[#api-query-index]
=== View Active Index Queries

....
GET /api/query/index/{indexName}
....

==== Description

Gets the details of all the active queries for any given FTS index in the system.

==== Parameters

[options="header", cols=".<2a,.<3a,.<9a,.<4a"]
|===
|Type|Name|Description|Schema
|**Path**
|**indexName** +
__required__
a|The name of a full-text index.
|string

|**Query**
|**longerThan** +
__optional__
a|Filters the queries running beyond the given span of time.

The duration string is a signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as `20s`, `-1.5h` or `2h45m`.
Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
|string (duration)
|===

==== Example HTTP request

[#request-1]
====
Request 1: Find queries on the index `DemoIndex1` that have been running for longer than 1 ms.

.Curl request
[source,shell]
----
curl -XGET -H "Content-Type: application/json" \
-u <username>:<password> \
'http://localhost:8094/api/query/index/DemoIndex1?longerThan=1ms'
----
====

==== Example HTTP response

====
Result of <<request-1,request 1>>.

.Response 200
[source,json]
----
{
  "status": "ok",
  "stats": {
    "total": 3,
    "successful": 3
  },
  "totalActiveQueryCount": 4,
  "filteredActiveQueries": {
    "indexName": "DemoIndex1",
    "longerThan": "1ms",
    "queryCount": 2,
    "queryMap": {
      "b91d75480470f979f65f04e8f20a1f7b-16": {
        "QueryContext": {
          "query": {
            "query": "good restraunts in france"
          },
          "size": 10,
          "from": 0,
          "timeout": 120000,
          "index": "DemoIndex1"
        },
        "executionTime": "1.059754811s"
      },
      "f76b2d51397feee28c1e757ed426ef93-2": {
        "QueryContext": {
          "query": {
            "query": "mexican food in england"
          },
          "size": 10,
          "from": 0,
          "timeout": 120000,
          "index": "DemoIndex1"
        },
        "executionTime": "1.058247896s"
      }
    }
  }
}
----
====

[#api-query]
=== View Active Node Queries

....
GET /api/query
....

==== Description

Gets the details of all the active queries in any FTS node in a cluster. The response of the endpoint will have the entries in `queryMap` whose key is of the format "nodeUUID-queryID". So, the key tells that the active query, which is the value, is running on the node with uuid equal to `nodeUUID` and has an ID `queryID` on that node.

==== Parameters

[options="header", cols=".<2a,.<3a,.<9a,.<4a"]
|===
|Type|Name|Description|Schema
|**Query**
|**longerThan** +
__optional__
a|Filters the queries running beyond the given span of time.

The duration string is a signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as `20s`, `-1.5h` or `2h45m`.
Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
|string (duration)
|===

==== Example HTTP request

[#request-2]
====
Request 2: Find all active queries across the fts cluster.

.Curl request
[source,shell]
---- 
curl -XGET -H "Content-Type: application/json" \
-u <username>:<password> \
http://localhost:8094/api/query
----
====

[#request-3]
====
Request 3: Find all queries across cluster that have been running for longer than 7s.

.Curl request
[source,shell]
----
curl -XGET -H "Content-Type: application/json" \
-u <username>:<password> \
'http://localhost:8094/api/query?longerThan=7s'
----
====

==== Example HTTP response

====
Result of <<request-2, request 2>>.

.Response 200
[source,json]
----
{
  "status": "ok",
  "stats": {
    "total": 3,
    "successful": 3
  },
  "totalActiveQueryCount": 4,
  "filteredActiveQueries": {
    "queryCount": 4,
    "queryMap": {
      "b91d75480470f979f65f04e8f20a1f7b-17": {
        "QueryContext": {
          "query": {
            "query": "good restraunts in france"
          },
          "size": 10,
          "from": 0,
          "timeout": 120000,
          "index": "DemoIndex1"
        },
        "executionTime": "2.144802122s"
      },
      "b91d75480470f979f65f04e8f20a1f7b-18": {
        "QueryContext": {
          "query": {
            "query": "decent hotel with a pool in italy"
          },
          "size": 10,
          "from": 0,
          "timeout": 120000,
          "index": "DemoIndex2"
        },
        "executionTime": "2.144712787s"
      },
      "b91d75480470f979f65f04e8f20a1f7b-19": {
        "QueryContext": {
          "query": {
            "query": "germany"
          },
          "size": 10,
          "from": 0,
          "timeout": 120000,
          "index": "DemoIndex2"
        },
        "executionTime": "2.143957727s"
      },
      "f76b2d51397feee28c1e757ed426ef93-3": {
        "QueryContext": {
          "query": {
            "query": "mexican food in england"
          },
          "size": 10,
          "from": 0,
          "timeout": 120000,
          "index": "DemoIndex1"
        },
        "executionTime": "2.14286421s"
      }
    }
  }
}
----
====

====
Result of <<request-3, request 3>>.

.Response 200
[source,json]
----
{
  "status": "ok",
  "stats": {
    "total": 3,
    "successful": 3
  },
  "totalActiveQueryCount": 3,
  "filteredActiveQueries": {
    "longerThan": "7s",
    "queryCount": 1,
    "queryMap": {
      "b91d75480470f979f65f04e8f20a1f7b-21": {
        "QueryContext": {
          "query": {
            "query": "decent hotel with a pool in italy"
          },
          "size": 10,
          "from": 0,
          "timeout": 120000,
          "index": "DemoIndex1"
        },
        "executionTime": "10.541956741s"
      }
    }
  }
}
----
====

[#api-query-cancel]
=== Cancel Active Queries

....
POST /api/query/{queryID}/cancel
....

==== Description

Allows the user to cancel an active query that's running longer than expected. This API is used along side the view active queries API to get the parameters `queryID` and `uuid` which will be used to cancel the query.

==== Parameters

[options="header", cols=".<2a,.<3a,.<9a,.<4a"]
|===
|Type|Name|Description|Schema
|**Query ID**
|**queryID** +
__required__
a|The active query's ID
|integer

|**Node UUID**
|**uuid** +
__optional__
a|Passed as a body parameter. `uuid` represents the active query's coordinator node's UUID, where the query will be canceled. This parameter allows the user to cancel a query anywhere in the system by specifying its coordinator node's UUID.
|string (duration)
|===

==== Example HTTP request

[#request-4]
====
Request 4: Cancel a long running query with query ID 24 whose coordinator node has a uuid b91d75480470f979f65f04e8f20a1f7b.

.Curl request
[source,shell]
----
curl -X POST -H "Content-Type: application/json" -u <username>:<password> \
http://localhost:8094/api/query/24/cancel -d \
'{ "uuid": "b91d75480470f979f65f04e8f20a1f7b" }'
----
====

==== Example HTTP response

====
Result of <<request-4,request 4>>.

.Response 200
[source,json]
----
{
  "status": "ok",
  "msg": "query with ID '24' on node 'b91d75480470f979f65f04e8f20a1f7b' was aborted!"
}
----
====