= Prometheus Discovery API
:description: pass:q[The discovery API generates a list of Couchbase Server nodes that tools such Prometheus can use to collect metrics.]

[abstract]
{description}

You can use Prometheus or similar tools to collect statistics and alerts from your Couchbase Database. 
In order for these tools to collect metrics, they must have a list of nodes in your Couchbase Server database. 
The discovery API provides this list to these tools.

NOTE: This endpoint is a replacement for the earlier `/prometheus_sd-config.yaml` endpoint. 
That endpoint is now deprecated. 

== HTTP Method and URI

----
GET /prometheus_sd_config
----

[#description]
== Description

By default, the discovery endpoint returns the list of nodes in your database in JSON format. 
The list contains the primary address of the nodes and their secure port number. 

The user account you use to call endpoint must have the xref:learn:security/roles.adoc#external-stats-reader[External Stats Reader] role. This is the same role Couchbase Server requires to retrieve metrics, 

== Curl Syntax

----
curl -X GET -u <username:password> \
    http://<ip-address-or-domain-name>:<port-number>/prometheus_sd_config
    -d disposition=[attachment|inline]
    -d network=[default|external]
    -d port=[insecure|secure]
    -d type=[json|yaml]
----

=== Parameters

disposition=[attachment|inline]::
Controls how Couchbase Server returns the list of nodes in the response. 
When set to the default `inline`, it returns the list inline within the respose.
When set to `attachment`, it returns the list as an attachment to the response.

network=[default|external]::
Controls which network address Couchbase Server uses in the list. 
When set to the default value of `default`, it uses the nodes's default address.
When set to `external`, it uses the node's xref:learn:clusters-and-availability:connectivity.adoc#alternate-addresses[alternate address]. 

port=[insecure|secure]::
Controls which port Couchbase Server uses in the list of nodes. 
When set to the default `secure`, it uses the node's secure port in the list.
When set to `insecure`, it uses the node's unencrypted port.

type=[json|yaml]::
Controls the data format Couchbase Server uses for the node list. 
When set ot the default `json`, it returns the list of nodes in JSON format.
When set to `yaml`, it returns the list of nodes in YAML format. 

