= Identifying the Orchestrator Node

[abstract]
The node currently running the _orchestrator_ (sometimes referred to as the _master services_) can be identified by means of the REST API

== HTTP Method and URI

----
GET /pools/default/terseClusterInfo
----

== Description

The _orchestrator_ manages cluster-wide operations; such as vBucket-placement, failover, node addition and subtraction, rebalance, cluster configuration-mapping, and aggregation of statistical data.
Every Couchbase-Server node contains an instance of the orchestrator.
However, at any given time, on a multi-node cluster, only one instance of the orchestrator, on one particular node, is active; and thereby responsible for performing _all_ the management tasks.
If the current instance becomes unavailable, another instance, on another node, takes over.

The `GET /pools/default/terseClusterInfo` http method and URI identify the node on which the active orchestrator currently resides.

For more information on the orchestrator and the cluster manager, see xref:learn:clusters-and-availability/cluster-manager.adoc[Cluster Manager].
