= Updating Server Group Memberships
:page-topic-type: reference

[abstract]
To change server group membership, use the `PUT /pools/default/serverGroups` HTTP method and URI.

== HTTP method and URI

----
PUT /pools/default/serverGroups?rev=<:number>
----

[#description]
== Description

This method and URI change the membership of the groups that currently exist for the specified cluster.
It does not permit the creation, removal, or renaming of groups.
Every node must be specified once, as an intended member of an existing group.
Existing groups that are intended to contain no nodes must be explicitly specified as empty.
A statement of the intended relationship of nodes to groups is provided as a JSON document: when `curl` is used, the document can be specified either explicitly, as a parameter-value on the command-line; or as a `.json` file.

This request is transactional: it either succeeds completely, or fails without impact.

[#syntax]
== Syntax

----
curl -d @<jsonInput> -X PUT
  -u <administrator>:<password>
  http://<host>:<port>/pools/default/serverGroups?rev=<number>
----

The syntax includes the following:

* `jsonInput`.
A statement of the revised configuration of nodes and groups, provided as a JSON document.
When `curl` is used, the document can be provided either explicitly, as a parameter-value on the command-line; or as a `.json` file.
See below for information on format.

* `rev=<number>`.
The revision number for the current group-configuration.
This number can be retrieved by means of the `GET /pools/default/serverGroups` HTTP method and URI: see xref:rest-api:rest-servergroup-get.adoc[Getting Server Group Information].
Note that this revision number changes whenever the group-configuration changes.

[#configuration-statement]
== Configuration Statement

The following JSON document specifies the membership of three nodes to two groups:

----
{
  "groups": [
  {
    "nodes": [
      {"otpNode": "ns_1@10.143.190.101"},
      {"otpNode": "ns_1@10.143.190.102"},
      {"otpNode": "ns_1@10.143.190.103"}
    ],
    "name": "Group 1",
    "uri": "/pools/default/serverGroups/0"
  },
  {
    "nodes": [],
    "name": "Group 2",
    "uri": "/pools/default/serverGroups/3b66b3c3177f44a3ffa6771ffeb31f36"
    }
  ]
}
----

The value of the `groups` key is an array, each of whose elements is an object that corresponds to one of the server groups for the cluster.
Each group must be specified with the following keys:

* `nodes`.
An array of the nodes in the group.
Each node is itself specifies with the key `otpNode` and the value `ns_1@node-ip-address`.

* `uri`.
The URI for the server group.
This can be retrieved by means of the `GET /pools/default/serverGroups` HTTP method and URI: see xref:rest-api:rest-servergroup-get.adoc[Getting Server Group Information].
Each URI is terminated with the unique UUID string for the group: for the default group, `Group 1`, this is always `0`.

Optionally, the `name` of the group can be specified.

[#responses]
== Responses
Success gives `200 OK`, and returns an empty array.
Malformed JSON, or failure to address all nodes and groups, gives `400 BAD REQUEST` and returns a `Bad input` array, featuring the submitted JSON document.

[#examples]
== Examples

In this example, the cluster has two groups defined:

* _Group 1_ contains nodes `10.143.190.101` and `10.143.190.102`.

* _Group 2_ contains the node `10.143.190.103`.

The JSON document shown above in xref:rest-api:rest-servergroup-put-membership.adoc#configuration-statement[Configuration Statement] can thus be used to locate all nodes in _Group 1_, thus leaving _Group 2_ empty.

The JSON document can be specified as a file in the local directory, as follows:

----
curl -d@groupChangeDefinition.json -X PUT \
http://Administrator:asdasd@10.143.190.101:8091/pools/default/serverGroups?rev=112632175
----

Alternatively, the JSON document can be provided on the command line.

----
curl -u Administrator:password -v -X PUT \
http://10.143.190.101:8091/pools/default/serverGroups?rev=112632175 \
-d '{"groups": [{"nodes": [{"otpNode": "ns_1@10.143.190.101"}, {"otpNode": "ns_1@10.143.190.102"}, {"otpNode": "ns_1@10.143.190.103"}], "name": "Group 1", "uri": "/pools/default/serverGroups/0"}, {"nodes": [], "name": "Group 2", "uri": "/pools/default/serverGroups/3b66b3c3177f44a3ffa6771ffeb31f36"}] }'
----

To check results, use `GET /pools/default/serverGroups` HTTP method and URI: see xref:rest-api:rest-servergroup-get.adoc[Getting Server Group Information].
