= Getting Bucket Information
:description: information about buckets defined on the cluster can be retrieved, by means of the REST API.
:page-topic-type: reference
:page-aliases: rest-bucket-info

[abstract]
{description}

[#http-methods-and-uris]
== HTTP Methods and URIs

----
GET /pools/default/buckets

GET /pools/default/buckets/<bucket-name>
----

[#description]
== Description

`GET /pools/default/buckets` retrieves information about all buckets defined on the cluster.
If the `<bucket-name>` path-parameter is added, only information about the specified bucket is retrieved.


[#curl-syntax]
== Curl Syntax

----
curl -X GET http://<ip-address-or-domain-name>:8091/pools/default/buckets/<bucket-name>
----

[#responses]
== Responses

Successful execution returns `200 OK`, and either an object containing information about the individual bucket specified by the path-parameter; or an array of such objects, each containing information about one of the buckets defined on the cluster.

Failure to authenticate returns `401 Unauthorized`.
An incorrectly specified URI returns `404 Object Not Found`.
If an internal error prevents successful execution, `500 Internal Server Error` is returned.

[#example]
== Example

The following example returns information about a single bucket named `travel-sample`.
The example pipes the output to https://stedolan.github.io/jq/[jq^] to format the output.
It also removes the `nodes` and `vBucketMap` lists which are not important for understanding the bucket's settings.

[source,bash]
----
curl -X GET -u Administrator:password \
      http://localhost:8091/pools/default/buckets/travel-sample | \
      jq '.vBucketServerMap.vBucketMap = "<vBucketMap omitted>" 
         | .nodes = "<node details omitted>"'
----

If successful, the call returns `200 OK`, and an object similar to the one shown in the following example:

[source, json]
----
include::partial$get_bucket_travel_sample.json[]
----

The fields `historyRetentionCollectionDefault`, `historyRetentionCollectionBytes`, and `historyRetentionCollectionSeconds` are specific to Magma storage. 
When the bucket does not use Magma as its storage backend, these properties do not appear in the output.

NOTE: Couchbase Server version 7.6.2 added a property named `enableCrossClusterVersioning` to support a future feature. 
Do not change the value of this field. 
Once enabled, you cannot turn it off. 
See the xref:rest-bucket-create.adoc#notes[Notes] section of xref:rest-bucket-create.adoc[] for more information.


[#see-also]
== See Also

* For an overview of buckets, see xref:learn:buckets-memory-and-storage/buckets.adoc[Buckets].
* For introduction to scopes and collections, see xref:learn:data/scopes-and-collections.adoc[Scopes and Collections].
