= Server Groups API
:page-topic-type: reference

[abstract]
The server groups REST API refers to the Server Group Awareness feature, which enables logical groupings of servers on a cluster where each server group physically belongs to a rack or availability zone.

== Description

[caption=Attention]
IMPORTANT: The Server Group Awareness feature is only available in Couchbase Server Enterprise Edition.

This feature provides the ability to specify that active and corresponding replica partitions be created on servers that are part of a separate rack or zone.
For purposes of the server group REST API, racks or availability zones are represented as flat space of server groups with group names.

The Server groups REST API provides the following capability:

* Create server groups
* Edit server groups
* Delete server groups
* Assign servers to server groups.

.Server group endpoints
[cols="100,318,197,131"]
|===
| HTTP method | URI path | Description | Admin Role

| GET
| [.path]_/pools/default/serverGroups_
| Retrieves information about a server group.
| Full, Cluster

| POST
| [.path]_/pools/default/serverGroups_
| Creates a server group with a specific name.
| Full, Cluster

| PUT
| [.path]_/pools/default/serverGroups/<:uuid>_
| Updates the server group information.
| Full, Cluster

| PUT
| [.path]_/pools/default/serverGroups?rev=<:number>_
| Updates a server’s group memberships.
| Full, Cluster

| DELETE
| [.path]_/pools/default/serverGroups/<:uuid>_
| Deletes a specific server group.
| Full, Cluster
|===
