= Retrieve All Node Certificates
:description: The REST API can be used to retrieve the node certificate for each node in the cluster.
:page-topic-type: reference

[abstract]
{description}

[#http-method-and-uri]
== Http Methods and URIs

----
GET /pools/default/certificates
----

[#description]
== Description

Retrieves all node certificates in the cluster.

Although this API _can_ be used on clusters that are running in mixed mode (which is to say, different nodes are running different versions of Couchbase Server), it ignores nodes not running at least version 7.1.

[#curl-syntax]
== Curl Syntax

The curl syntax for this call is as follows:

----
curl -X GET http://<ip-address-or-domain-name>:8091/pools/default/certificates
  -u <username>:<password>
----

[#responses]
== Responses

Success returns `200 OK`.
The `GET` also returns an array, each of whose objects is a node certificate on the cluster.

A malformed URI fails, with `404 Object Not Found`; failure to authenticate gives `401 Unauthorized`; and insufficient privileges gives `403 Forbidden`, with a notification such as `"Forbidden. User needs one of the following permissions","permissions":["cluster.admin.security!read"]`.
An incorrectly specified IP address or domain name causes the attempted connection to time out, with a `Failed to connect` notification.

== Example

The following example returns each node certificate on the cluster of which node `10.144.220.101` is a member.

----
curl -X GET http://10.144.220.101:8091/pools/default/certificates -u Administrator:password | jq '.'
----

If successful, the call provides a response such as the following:

----
[
  {
    "node": "127.0.0.1:8091",
    "warnings": [],
    "subject": "CN=Couchbase Server",
    "expires": "2022-11-24T10:59:14.000Z",
    "type": "uploaded",
    "pem": "-----BEGIN CERTIFICATE-----\nMIIDfzCCAmegAwIBAgIUOxOtDnRCYpwkIp2jSpWbm7a8OWMwDQYJKoZIhvcNAQEL\nBQAwHDEaMBgGA1UEAwwRQ291Y2hiYXNlIFJvb3QgQ0EwHhcNMjExMTI0MTA1OTE0\nWhcNMjIxMTI0MTA1OTE0WjAbMRkwFwYDVQQDDBBDb3VjaGJhc2UgU2VydmVyMIIB\nIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo6x7II3SJF10hN89GMWeNiqs\nqc5yXrZyuWJiglXIJRV4AOFxYixrH8CRUJ10aM0RNHAjwcLGtvX2LyEXWz7xtGAs\nGT1gW4ETqlNmEtCc4AoVrQaJErgDsXToz8cOdpoc/nknywZrOPSWUVTpBuF64+cl\nGFdCEP/1JQzYi4VViSQSC+kon7wQgxYPvDmiEVO1EchuDkj6XbyFm9l7FxVsMCZj\nfxxlVbg7Zbu0dm8NKvhCvinNW30Rx0hRsL+pZHhx9Mt6z+nhPR9/dm4cAI6DqjRD\n81C8bFeuQJt8+D8fZCs5oBXcE48ZqzohSZqq5mQdVu1RbtJAA8wf8+Kq8WawxwID\nAQABo4G5MIG2MAkGA1UdEwQCMAAwHQYDVR0OBBYEFIENyRo7ft8MJYQai7HqNFLL\n13S6MFcGA1UdIwRQME6AFLflaf6xW4BktvacNPsE1xvZpeOJoSCkHjAcMRowGAYD\nVQQDDBFDb3VjaGJhc2UgUm9vdCBDQYIUa8hxqSu6XNGYCYVC9QEHYvS7OFAwEwYD\nVR0lBAwwCgYIKwYBBQUHAwEwCwYDVR0PBAQDAgWgMA8GA1UdEQQIMAaHBAqQ3GUw\nDQYJKoZIhvcNAQELBQADggEBACaJURed/tejjGrtvRWBv19DXDYN0BRAknKWQAf/\nBGpbg+3RPLgqVbEyjsGtaTYr6UjeW81/kwMaS6IyJtGiFa1X8EizeYPMIT2w0D5m\nDdzO648EbB/4sda8aEr2vfyn4Bk4kC1KCuQXE80uIULFAuFsFWsTWvrb7jsHpdYx\neJSmLKbN7Z7JtSRScXFN4reJn6r5hCP+mmMbVKKVDO9APSGw0RrVfvZo9FxmmoD6\nzrKknGSrorRvqkjiqxYQzRdwcaDn2TGotVKDxbVvV82eX+FjgUYIEBJZlbOJvc0B\nwrKiAgmemNiOFiF4BvWbKTojot7BTJs9SGAU2JLCUZVfBrs=\n-----END CERTIFICATE-----\n\n",
    "privateKeyPassphrase": {
      "type": "plain",
      "password": "********"
    }
  }
]
----

The returned array contains a single JSON object, indicating that a single node certificate is defined for the cluster.
The object contains fields for warnings, the Subject Common Name, the expiry date, the type (whether _generated_ by Couchbase Server, or _uploaded_ by the administrator), the pem-encoded contents of the node certificate, and the passphrase for the private key (securely displayed as asterisks).
