= Upload and Retrieve a Node Certificate
:description: The REST API can be used to upload and retrieve an uploaded node certificate.
:page-topic-type: reference
:page-aliases: rest-api:rest-encryption

[abstract]
{description}

[#http-method-and-uri]
== Http Methods and URIs

----
POST /node/controller/reloadCertificate

GET /pools/default/certificate/node/<ip-address-or-domain-name>
----

[#description]
== Description

The `POST` method and `/node/controller/reloadCertificate` URI allow an administrator-configured node certificate to be _loaded_ and _reloaded_ onto its intended node.
Prior to loading, the node certificate must have been placed in an appropriately created `inbox` directory: see xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates], for information.

The `GET` method and `/pools/default/certificate/node/<ip-address-or-domain-name>` URI allow an administrator-configured node certificate to be retrieved.
Note that such retrieval can only be performed with an administrator-configured node certificate: it cannot be performed with the default node certificate that is automatically provided to a node by Couchbase Server on initial configuration.

Both calls require either the Full Admin or the Security Admin role.

[#curl-syntax]
== Curl Syntax

The curl syntax for these calls is as follows:

----
curl -X POST http://<ip-address-or-domain-name>:8091/node/controller/reloadCertificate
 -u <username>:<password>
 -d <json-passphrase-definition>

curl -X GET http://<ip-address-or-domain-name>:8091/pools/default/certificate/node/<ip-address-or-domain-name>
  -u <username>:<password>
----

The copy of the node certificate returned by the `GET` method should be saved appropriately: for example, by means of `> <node-certificate-copy>`, on the local filesystem.

=== JSON Passphrase Definition

A _passphrase_ can be established, to control access to a node certificate's private key, by means of the `json-passphrase-definition` argument; whose value must be a JSON object.
Note that if the node-certificate has already been loaded, in order to impose a passphrase on its key, the certificate can be _reloaded_, with the `json-passphrase-definition` specified: for this to be successful, the corresponding `pem` and `key` files must both still be within the created `inbox`, or must be recopied into it.

The following example shows how to register a passphrase in association with the private key:

----
{"privateKeyPassphrase": {"type": "plain",
                          "password": "124!*oU"}}
----

The specified passphrase is transmitted in the clear (unless Https is used), and is stored on the node with the Couchbase-Server procedures for managing system secrets.
See xref:manage:manage-security/manage-system-secrets.adoc[Manage System Secrets].

The following example shows how to register a script in association with the private key:

----
{"privateKeyPassphrase": {"type": "script",
                          "path": "<path to script>",
                          "args": ["arg1", "arg2"],
                          "trim": false,
                          "timeout": 5000}}
----

The endpoint verifies that the script is present on the node, and is located in the `data/scripts` directory.
(For example, on Linux, `/opt/couchbase/var/lib/couchbase/data/scripts`.)

The following example locates the script at a URL:

----
{"privateKeyPassphrase": {"type": "rest",
                          "url": "<url to call>",
                          "addressFamily": inet6,
                          "httpsOpts": {"verifyPeer": true}
                          "timeout": 5000}}
----

[#responses]
== Responses

For both the `POST` and the `GET`, success returns `200 OK`.
The `GET` also returns an object whose fields specify the details of the certificate.
For both, a malformed URI fails, with `404 Object Not Found`; failure to authenticate gives `401 Unauthorized`; and insufficient privileges gives `403 Forbidden`, with a notification such as `"Forbidden. User needs one of the following permissions","permissions":["cluster.admin.security!read"]`.
An incorrectly specified IP address or domain name causes the attempted connection to time out, with a `Failed to connect` notification.

If the `POST` is called with either no node certificate or no node-private key in the `inbox` directory, the call fails with `400 Bad Request`, and either the notification `"Unable to read private key file /opt/couchbase/var/lib/couchbase/inbox/pkey.key. The file does not exist."`; or the notification `"Unable to read certificate chain file /opt/couchbase/var/lib/couchbase/inbox/chain.pem. The file does not exist."`.

If the `GET` method is used with no administrator-configured node certificate having been uploaded, the call fails with `404 Object Not Found`, and the notification `Certificate is not set up on this node`.

[#examples]
== Examples

The following call uploads an appropriately configured node certificate from the node's `inbox` directory:

----
curl -X POST http://10.143.201.101:8091/node/controller/reloadCertificate \
-u Administrator:password
----

If successful, the call returns `200 OK`.

The following call retrieves the node certificate that is currently uploaded:

----
curl -v -X GET http://10.143.201.101:8091/pools/default/certificate/node/10.143.201.101:8091 \
-u Administrator:password
----

If successful, the call returns `200 OK`, and an object whose fields specify warnings, the Subject Common Name, the expiry date, the type (whether _generated_ by Couchbase Server, or _uploaded_ by the administrator), the pem-encoded contents of the node certificate, and the passphrase for the private key (securely displayed as asterisks), if one has been established:

----
{
  "warnings": [],
  "subject": "CN=Couchbase Server",
  "expires": "2022-11-24T10:59:14.000Z",
  "type": "uploaded",
  "pem": "-----BEGIN CERTIFICATE-----
            .
            .
            .
  -----END CERTIFICATE-----\n\n",
  "privateKeyPassphrase": {}
}

----

[#see-also]
== See Also

Information on uploading and retrieving the cluster's root certificate with the REST API is provided in xref:rest-api:upload-retrieve-root-cert.adoc[Upload and Retrieve the Root Certificate].
Information on certificate regeneration is provided in xref:rest-api:rest-regenerate-all-certs.adoc[Regenerate All Certificates].
A general introduction to certificates is provided in xref:learn:security/certificates.adoc[Certificates].
Routines for generating and deploying server and client certificates are provided in xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates] and xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates], respectively.
