= Application Telemetry Metrics
:description: Couchbase can be configured to collect metrics related to Couchbase SDK calls made from applications.
:stem: asciimath

[abstract]
{description}

== Prerequisites

=== Activating Telemetry on Couchbase Server

Before generating metrics from application telemetry, you must enable application telemetry on your Couchbase Server installation. 
You can do this by executing the following CURL command:

[source, bash, subs="+quotes"]
----
curl -u Administrator:password -X POST \
https://##{host}##:##{port}##/settings/appTelemetry \
-d enabled=true 
----

For more information on enabling application telemetry, see xref:rest-api:application-telemetry.adoc[]

=== Activating Telemetry in your Application

To activate telemetry recording, you will need to set the telemetry endpoint within your application.

[source]
----
couchbases://abc.cloud.couchbase.com?app_telemetry_endpoint=ws://localhost:9090/app_telemetry
----

Alternatively, you can set the endpoint using `ClusterOptions`.

[source]
----
ClusterOptions options;
options.appTelemetryEndpoint("ws://localhost:9090/app_telemetry");
----

== Telemetry Counters

Couchbase can record the number of SDK calls made for specific services. The metrics follow the same basic patterns:

[%header]
|===
| Metric| Description

| `sdk_\{service}_r_total`
| The total number of operations

|`sdk_\{service}_r_canceled`
| The total number of operations that were canceled.

| `sdk_\{service}_r_timedout`
| The total number of operations that timed out.

|===

To access the counter for a particular service, you replace `\{service}` with one of the following:

* `kv`
* `query`
* `search`
* `analytics`
* `management`
* `eventing`

So to access the number of calls that timed out for the query service, 
you would use the command: `sdk_query_r_timedout`.

== Histograms

The same service labeling is used in the retrieval of histograms:


[%header, cols="2,1"]
|===
| Metric| Description

| `sdk_\{service}_retrieval_duration_milliseconds_bucket`
| Time take for retrieval

|`sdk_\{service}_mutation_nondurable`
| Time taken for non-durable mutations.

| `sdk_\{service}__mutation_durable`
| Time taken for ndurable mutations.
|===

The histogram metrics can take the same `service` values as the metric counters.

* `kv`
* `query`
* `search`
* `analytics`
* `management`
* `eventing`

[#histogram-output]
.Histogram output
====
[source]
----
sdk_kv_retrieval_duration_milliseconds_bucket{le="1",agent="sdk/2.4.5.0",bucket="travel-sample",node="node1",node_uuid="91442eb8202e0e16bbb59624d9ccdb0a"} 24054
sdk_kv_retrieval_duration_milliseconds_bucket{le="10",agent="sdk/2.4.5.0",bucket="travel-sample",node="node1",node_uuid="91442eb8202e0e16bbb59624d9ccdb0a"} 33444
sdk_kv_retrieval_duration_milliseconds_bucket{le="100",agent="sdk/2.4.5.0",bucket="travel-sample",node="node1",node_uuid="91442eb8202e0e16bbb59624d9ccdb0a"} 100392
sdk_kv_retrieval_duration_milliseconds_bucket{le="500",agent="sdk/2.4.5.0",bucket="travel-sample",node="node1",node_uuid="91442eb8202e0e16bbb59624d9ccdb0a"} 129389
sdk_kv_retrieval_duration_milliseconds_bucket{le="1000",agent="sdk/2.4.5.0",bucket="travel-sample",node="node1",node_uuid="91442eb8202e0e16bbb59624d9ccdb0a"} 133988
sdk_kv_retrieval_duration_milliseconds_bucket{le="2500",agent="sdk/2.4.5.0",bucket="travel-sample",node="node1",node_uuid="91442eb8202e0e16bbb59624d9ccdb0a"} 139823
sdk_kv_retrieval_duration_milliseconds_bucket{le="+Inf",agent="sdk/2.4.5.0",bucket="travel-sample",node="node1",node_uuid="91442eb8202e0e16bbb59624d9ccdb0a"} 144320
sdk_kv_retrieval_duration_milliseconds_sum{agent="sdk/2.4.5.0",bucket="travel-sample",node="node1",node_uuid="91442eb8202e0e16bbb59624d9ccdb0a"} 53423000
sdk_kv_retrieval_duration_milliseconds_count{agent="sdk/2.4.5.0",bucket="travel-sample",node="node1",node_uuid="91442eb8202e0e16bbb59624d9ccdb0a"} 144320 
----
====
xref:histogram-output[xrefstyle=short] demonstrates a series of `kv` retrieval times for the buckets in a node.
Each line gives the retrieval count for a particular range. 
The retrieval duration counts are grouped by latency buckets: for example, requests completed in stem:[le 1] ms total 24,054, those in stem:[le 10] ms total 33,444, and so on.

There are two special metrics associated with each histogram: `_sum` and `_count` that represent the overall sum of all buckets, and total number of the points in the histogram. 
