= Cluster Administration

[abstract]
Administration of Couchbase Server is provided through a number of different tools and systems.

Administration tools used with Couchbase Server are the Couchbase Web Console, Command-line interface (CLI) and REST API.

Couchbase Web Console:: The built-in web administration console that provides a complete interface for configuring, managing, and monitoring your Couchbase Server installation.

Command-line Interface (CLI)::
A suite of command-line tools that provide information and control over your Couchbase Server and cluster installation.
The CLI tools make use of the REST API.
You can use CLI in combination with your scripts and management procedures to provide additional functionality, such as automated failover, backups, and other procedures.

REST API::
In addition to the Couchbase Web Console, Couchbase Server incorporates a management interface exposed through the standard HTTP REST protocol.
This REST interface can be called from your custom management and administration scripts to support different operations.

== Accessing Couchbase Server Directly

To access Couchbase Server directly, log into the node and use the CLI or REST API.
You can also access Couchbase Server from a different machine with network access to your Couchbase Server node.

To access Couchbase Server and use the Couchbase Web Console, log into the server through a browser such as Firefox, Chrome, Safari, or Internet Explorer.

== Accessing Couchbase Server with a Client

If you already have an application that uses the memcached protocol, you can start using your Couchbase Server immediately.
If so, you can simply point your application to this server as you would do with any other memcached server.
No code changes or special libraries are needed, and the application behaves as it would against a standard memcached server.
Without the client knowing anything about it, the data is being replicated, persisted, and the cluster can be expanded or contracted completely transparently.

If you do not already have an application, then you should investigate one of the available Couchbase client libraries to connect to your server and start storing and retrieving information.
