= Rebalance Reference

[abstract]
Couchbase Server creates a _report_ for every rebalance that occurs.
This section describes the report-content.

[#Obtaining-a-rebalance-report]
== Obtaining a Rebalance Report

Couchbase Server automatically creates a _rebalance report_ for every rebalance that occurs on the cluster.
The report's content consists of a JSON document, which provide statistics for every service that has been involved in the rebalance.
On conclusion of the rebalance, the report can be accessed in any of the following ways:

* By means of Couchbase Web Console, as described in xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a Node and Rebalance].

* By means of the REST API, as described in xref:rest-api:rest-get-cluster-tasks.adoc[Getting Cluster Tasks].

* By accessing the directory `/opt/couchbase/var/lib/couchbase/logs/reblance` on _any_ of the cluster nodes.
Each successive rebalance report is provided as a `*.json` file, whose name indicates the time at which the report was run &#8212; for example, `rebalance_report_2020-03-17T11:10:17Z.json`.

[#reading-a-rebalance-report]
== Reading a Rebalance Report

Each rebalance report consists of a JSON document whose principal object is `stage_info`.
This itself contains an object corresponding to each rebalance _stage_: one stage has occurred for each of the services deployed on the cluster.
Therefore, if all six services have been deployed, six stages have occurred; and objects for `analytics`, `eventing`, `search`, `index` `query`, and `data` are provided.

[#standard-report-fields]
== Standard Report Fields

Standard fields are provided for each stage.
These are as follows:

* `startTime`.
The point in time at which the stage was started (or possibly, was determined _not_ to have started).
Specified as a UTC date/time string.

* `completedTime`.
The point in time at which the stage was completed (or possibly, was determined _not_ to have completed).
Specified as a UTC date/time string.

* `timeTaken`.
The amount of elapsed time since `startTime`.
Specified as an integer, in milliseconds.
The value is `undefined`, if the stage has been determined _not_ to have started.

* `totalProgress`.
The current, total progress that has been achieved for the stage.
Specified as a percentage.
In a completed report, the value is expected to be `100`.
This is an _optional_ field, which may not appear, if not implemented for the stage.

* `perNodeProgress`.
The current progress that has been achieved for the stage for each node.
The value is an object, which itself provides a progress figure for each node.
Each progress figure is specified as a floating-point number between `0.0` and `1.0`.
In a completed report, the value is expected to be `1`.
This is an _optional_ field, which may not appear, if not implemented for the stage.

* `subStage`.
Details on any _substages_ that the stage may contain.
For each substage, the standard fields are identical to those for each stage.
This is an _optional_ field, which does not appear, if the stage contains no substages.

* `events`.
An array of strings, each of which provides information on a significant event.
The information may be a warning, an error message, or otherwise informational.
This is an _optional_ field, which does not appear, if not implemented for the stage, or if no significant events have occurred.

* `details`.
Further details of the stage.
This is an _optional_ field, which is currently implemented for the `data` stage only (information provided below).

[#stage-info-standard-field-examples]
=== Standard Field Examples

The following example displays the initial section of a rebalance report, following a rebalance performed on a cluster consisting of the following nodes:

* `10.143.194.101`, running the Data, Query, and Index Services.

* `10.143.194.102`, running the Data and Search Services.

* `10.143.194.103`, running the Analytics and Eventing Services.

* `10.143.194.104`, running the Data Service.

The rebalance follows an edit made to both buckets resident on the cluster, `beer-sample` and `travel-sample`, changing the number of replicas from 1 to 2, for each.
This excerpt stops at the point the Data Service `details` begin (these are described further below).

----
{
  "stageInfo": {
    "analytics": {
      "totalProgress": 100,
      "perNodeProgress": {
        "ns_1@10.143.194.103": 1
      },
      "startTime": "2020-03-18T00:34:13.415-07:00",
      "completedTime": "2020-03-18T00:34:14.724-07:00",
      "timeTaken": 1310
    },
    "eventing": {
      "totalProgress": 100,
      "perNodeProgress": {
        "ns_1@10.143.194.103": 1
      },
      "startTime": "2020-03-18T00:34:14.724-07:00",
      "completedTime": "2020-03-18T00:34:14.939-07:00",
      "timeTaken": 214
    },
    "search": {
      "totalProgress": 100,
      "perNodeProgress": {
        "ns_1@10.143.194.102": 1,
        "ns_1@10.143.194.104": 1
      },
      "startTime": "2020-03-18T00:34:12.453-07:00",
      "completedTime": "2020-03-18T00:34:12.758-07:00",
      "timeTaken": 306
    },
    "index": {
      "totalProgress": 100,
      "perNodeProgress": {
        "ns_1@10.143.194.101": 1
      },
      "startTime": "2020-03-18T00:34:12.758-07:00",
      "completedTime": "2020-03-18T00:34:13.415-07:00",
      "timeTaken": 656
    },
    "data": {
      "totalProgress": 100,
      "perNodeProgress": {
        "ns_1@10.143.194.101": 1,
        "ns_1@10.143.194.102": 1,
        "ns_1@10.143.194.104": 1
      },
      "startTime": "2020-03-18T00:33:36.969-07:00",
      "completedTime": "2020-03-18T00:34:12.452-07:00",
      "timeTaken": 35483,
      "details": {
        .
        .
        .
----

Each service thus has its stage-information provided in an object named after the service.
Progress is provided for the whole cluster, and per node.
Start times and completion times are provided, as are elapsed times.
The Data Service contains the additional object, `details`.
