= Adding or Removing the Data Service on Existing Nodes
:description: pass:q[You can add or remove the Data Service on an existing node of a cluster by adding or removing the node from the cluster, and then completing the addition or removal of the node by running a rebalance operation.]
:page-toclevels: 3

[abstract]
{description}

Unlike other services, you cannot dynamically add or remove the Data Service on an existing node of a cluster.

You can add any service, including the Data Service (kv), when you add or join a new node to a cluster.
Also, when you remove a node, you are removing all the services on that node.
To complete the process of adding or removing a node, the rebalance operation must be run.
For more information about adding or removing a node and rebalacing using the UI, REST API, or CLI, see: 

* xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a Node and Rebalance]
* xref:manage:manage-nodes/remove-node-and-rebalance.adoc[Remove a Node and Rebalance] 

== Add the Data Service on an Existing Node

To add the Data Service on an existing node of a cluster:

. Remove the node that you want to add the Data Service to using xref:manage:manage-nodes/remove-node-and-rebalance.adoc[Remove a Node and Rebalance].
. Then xref:manage:manage-nodes/add-node-and-rebalance.html[add the node] back to the cluster after enabling the Data Service.

Alternatively, you can add a new node with the necessary services configuration, including the Data Service, using xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a New Node and Rebalance].
Then remove the extraneous node that you no longer need using xref:manage:manage-nodes/remove-node-and-rebalance.adoc[Remove a Node and Rebalance].

== Remove the Data Service from an Existing Node

To remove the Data Service from an existing node of a cluster:

. Remove the node with the Data Service that you want to remove using xref:manage:manage-nodes/remove-node-and-rebalance.adoc[Remove a Node and Rebalance].
. Then xref:manage:manage-nodes/add-node-and-rebalance.html[add the node] back to the cluster after disabling the Data Service.

NOTE: During the node removal operation, if there are other services on the node that you're removing for the Data Service reconfiguration, and you do not want those services to be impacted when the node is removed from the cluster, you may need to add those services to another node temporarily.
You can also add a new node temporarily with those services enabled.

== See Also

For more information about modifying non-Data Services on existing nodes, see xref:manage:manage-nodes/modify-services-and-rebalance.adoc[Modify Services and Rebalance].