= Modify Services and Rebalance
:description: pass:q[Add or remove non-Data Services on existing nodes in a cluster and rebalance the cluster without adding or removing nodes.]
:page-toclevels: 3

[abstract]
{description}

Dynamically add or remove the following Multi-Dimensional Scaling (MDS) services on existing nodes in a cluster from the Couchbase xref:manage:manage-nodes/modify-services-on-nodes-and-rebalance.adoc#modify-mds-services-from-ui[UI], xref:rest-api:rest-set-up-services-existing-nodes.adoc[REST API], or xref:manage:manage-nodes/modify-services-on-nodes-and-rebalance.adoc#modify-mds-services-using-cli[CLI]:

* `index` (Index Service)
* `n1ql` (Query Service)
* `fts` (Search Service)
* `cbas` (Analytics Service)
* `eventing` (Eventing Service)
* `backup` (Backup Service)

Then a rebalance operation is automatically triggered to evenly distribute the service workload across the nodes.

You do not have to add or remove a node to add or remove a non-Data Service on a node in a cluster.

NOTE: You cannot add or remove kv (Data Service) using this method.

Adding or removing of the Data Service on an existing node is supported only through adding or removing nodes.

To add a Data Service on a node from the UI:

* xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a New Node and Rebalance] along with enabling the Data Service.

* xref:manage:manage-nodes/remove-node-and-rebalance.adoc[Remove a Node and Rebalance].
Then xref:manage:manage-nodes/add-node-and-rebalance.html[add the node] back to the cluster along with enabling the Data Service.

To remove a Data Service from an existing node using the UI:

* xref:manage:manage-nodes/remove-node-and-rebalance.adoc[Remove a Node and Rebalance].
Then xref:manage:manage-nodes/add-node-and-rebalance.html[add the node] back to the cluster by disabling the Data Service.

* xref:manage:manage-nodes/add-node-and-rebalance.adoc[Add a New Node and Rebalance] along with disabling the Data Service.

== Prerequisites

Before modifying non-data services on nodes, ensure you have the following:

* Full Administrator access.
* A clear understanding of the current service distribution across the nodes.
* Service Memory Quota:
When you add a service that wasn’t earlier present in the cluster, the new service uses the service-specific default memory quota.
This applies to the Index, Search, Eventing, and Analytics services.
+
Verify that the memory quota for the new service meets your requirements using one of the following:

** The REST API from xref:rest-api:rest-get-memory-information.adoc[Getting Memory Information].
** The UI from xref:manage:manage-settings/general-settings.adoc#configure-general-settings-with-the-ui[Configure General Settings with the UI].
+
NOTE: The default service memory quota is set per server node and is reflected in the `GET /pools/default` REST API response.
 
[#modify-mds-services-from-ui]
== Modify Services from the UI

To manage non-data services from the UI, follow these steps:

. Open Couchbase Web Console.

. Click [.ui]*Servers*.

. Click btn:[Modify Services].
+
The [.ui]*Modify Cluster Services* dialog appears, which lists all the nodes in all the clusters and their current services.
+
--
Services that can be modified are:

** *index* (Index Service)
** *n1ql* (Query Service)
** *fts* (Search Service)
** *cbas* (Analytics Service)
** *eventing* (Eventing Service)
** *backup* (Backup Service).
--
+
kv (Data Service) cannot be modified.

. Select the services you want to add for each node and deselect the services you want to remove from each node.
+
NOTE: Adding or removing any service triggers a rebalance operation.

. Click btn:[Rebalance and Change Services].
+
If you're only removing services, then rebalancing is triggered immediately.

. If you are adding services, then the *New Service Settings* dialog appears.
This dialog lists the services you selected to add, the existing active services, and their current memory quotas.

.. Enter the memory quota for each service you're adding.
You can also edit the memory quota for existing services.
+
For Index Service, choose either *Standard Global Secondary* or *Memory-Optimized*. For more information about index storage, see xref:learn:services-and-indexes:indexes/storage-modes.adoc[Index Storage Settings].
+
For information about managing memory quotas for services from the UI, see xref:manage:manage-settings/general-settings.adoc#memory-quotas[Memory Quotas].

.. Click btn:[Save Settings].

The rebalancing operation is automatically triggered, which evenly distributes the service workload across the nodes.
Status progress is displayed on the UI.

When the rebalance operation is successful, an acknowledgment message appears on the UI and an option to download the rebalance report using btn:[Download Report].

[#modify-mds-services-using-cli]
== Modify Services Using CLI

To modify non-data services on the existing nodes of a cluster using the CLI, use the following `couchbase-cli rebalance` command.

----
couchbase-cli rebalance -c <network_address> \
--username <username> \
--password <password> \
--update-services [--index-[add|remove] <list-of-nodes>] [--n1ql-[add|remove] <list-of-nodes>] [--fts-[add|remove] <list-of-nodes>] [--cbas-[add|remove] <list-of-nodes>] [--eventing-[add|remove] <list-of-nodes>] [--backup-[add|remove] <list-of-nodes>]
----

These are the options for modifying non-data services:

* `--update-services`: Indicates that the rebalance will make changes to the services on the cluster.

* `--<service>-add <node>`: Adds the specified service to the specified node.
`<service>` can be one of the following:

** `index` for the Index Service.
** `n1ql` for the Query Service.
** `fts` for the Search Service.
** `cbas` for the Analytics Service.
** `eventing` for the Eventing Service.
** `backup` for the Backup Service.

* `--<service>-remove <node>`: Removes the specified service from the specified node.

=== Examples

* The `–fts-add` argument adds the full-text search service to the list of nodes.

* The `–index-remove` argument removes the index service from the list of nodes.

* To add the index service to `node2`, use the following command.
+
----
couchbase-cli rebalance -c 127.0.0.1 -u Administrator -p password --update-services --index-add node2
----

* To remove the index service from `node3`, use the following command.
+
----
couchbase-cli rebalance -c 127.0.0.1 -u Administrator -p password --update-services --index-remove node3
----

* Trying to remove a service that's not present on the node results in an error.
From the previous example, if `node3` was not running the index service, the following error occurs.
+
----
ERROR: Node ns_1@node3 does not provide the index service
----

For more information about the `couchbase-cli rebalance` command, see xref:cli:cbcli/couchbase-cli-rebalance.adoc[rebalance].