= Apply Node-to-Node Encryption

[abstract]
Network traffic between the individual nodes of a Couchbase-Server cluster can be encrypted, in order to optimize cluster-internal security.

[#understanding-node-to-node-encryption]
== Understanding Node-to-Node Encryption

Couchbase Server supports _node-to-node encryption_, whereby network traffic between the individual nodes of a cluster is encrypted, in order to optimize cluster-internal security.
Node-to-node encryption can be established on either of two levels:

* _Control_. Cluster-management information passed between nodes by the Cluster Manager and related low-level processes is encrypted.
However, the data that is passed between nodes by Couchbase Services continues to be passed in the clear.
When node-to-node encryption is enabled, this is the default.

* _All_. Both cluster-management information and data is passed in encrypted form.

Both the IPV4 and IPV6 address-families are supported, as is the ability to switch the cluster between them.

Node-to-node encryption is managed by means of the Couchbase CLI.
This page provides a sequence of calls, to exemplify how a cluster can be optionally transitioned from one address-family to another, and then secured by means of node-to-node encryption.
For a complete conceptual overview, see xref:learn:clusters-and-availability/nodes.adoc#node-to-node-encryption[Node-to-Node Encryption].

[#set-up-node-to-node-encryption]
== Set Up Node-to-Node Encryption

The following sequence demonstrates how to set up node-to-node encryption for a cluster, using the Couchbase CLI.
The sequence assumes:

* The reader's familiarity with the information provided at xref:learn:clusters-and-availability/nodes.adoc#node-to-node-encryption[Node-to-Node Encryption].

* A pre-existing cluster of two nodes, `node1-devcluster.com` and `node2-devcluster.com`, both running Couchbase Enterprise Server Version 6.5.

* The cluster's initial use of the IPV6 address-family.

* Node-to-node encryption initially disabled.

* Auto-failover initially enabled.

Proceed as follows:

. Turn off auto-failover.
Use the `setting-autofailover` CLI command, as follows
+
----
/opt/couchbase/bin/couchbase-cli setting-autofailover \
-c http://node1-devcluster.com:8091 \
-u Administrator \
-p password \
--enable-auto-failover 0
----
+
The value of `0` assigned to the `--enable-auto-failover` flag specifies that auto-failover be switched off.
If the command is successful, the following output is displayed:
+
----
SUCCESS: Auto-failover settings modified
----

. Ensure that the IP family of the cluster is the right one for your needs: either IPV4 or IPV6. To set the family, use the `change-ip-family` CLI command:
+
----
/opt/couchbase/bin/couchbase-cli change-ip-family \
-c http://node1-devcluster.com:8091 \
-u Administrator \
-p password \
--set \
--ipv4
----
+
The `--set` flag indicates that an IP-family setting is to be made.
The `--ipv4` flag specifies that the cluster will from this point use the IPV4 family.
+
If successful, the command provides the following output:
+
----
Switched ip family for node: http://node1-devcluster.com:8091
Switched ip family for node: http://node2-devcluster.com:8091
SUCCESS: Switched ip family of the cluster
----
