= Manage Nodes and Clusters

[abstract]
A Couchbase-Server _cluster_ consists of one or more _nodes_, each of which is a system running an instance of Couchbase Server.

[#managing-nodes-and-clusters]
== Managing Nodes and Clusters

A Couchbase Server _node_ is a physical or virtual machine that hosts a single instance of Couchbase Server.
A conceptual overview is provided in xref:learn:clusters-and-availability/nodes.adoc[Nodes].
The current section provides step-by-step procedures for node-management.
This includes:

* _Initializing_ and _provisioning_ a node, thereby making it a one-node cluster.
* _Adding_ and _removing_ nodes from clusters.
* _Listing_ nodes currently in the cluster.
* Performing _failover_ on nodes, when they need to be removed from the cluster.
* _Rebalancing_ the cluster, after a node has been removed for scheduled or otherwise planned maintenance.
* _Recovering_ a node, following failover.

[#prerequisites]
== Prerequisites

Before proceeding with the instructions provided throughout this section, you must have installed and started Couchbase Server.

For links to all per platform installation-instructions, see xref:install:install-intro.adoc[Install].

For information on starting and stopping Couchbase Server on different platforms, see xref:install:startup-shutdown.adoc[Startup and Shutdown].
