= Backend Storage
:description: pass:q[Couchbase supports two different backend storage mechanisms: `CouchStore` and `Magma`. It is important to understand which backend storage is best suited to your requirements.]

[abstract]
{description}

== CouchStore

CouchStore is the default backend storage engine that has been in use for more than ten years. It's optimised for high performance with large data sets while using fewer system resources (the minimum bucket size for CouchStore backend is 100 MB). If you have a small data set that can fit in memory, then you should consider using CouchStore.

== Magma

Magma is Couchbase's latest backend engine is designed for high performance with larger datasets (the smallest bucket you can have with a Magma backend is 256 MB). It is optimised for SSD disk access and higher transaction performance, and has such has higher hardware resource requirements. It is especially suited to data sets that will not fit into available memory.

IMPORTANT: Currently, Magma does not support Full Text Searching, Eventing or Analytics.

== CouchStore and Magma at a Glance

|===
| {empty} | CouchStore |Magma

| Maximum storage per node
| 3 TB
| 5 TB

| Maximum storage per cluster
| 30 TB
| 100+ TB

| Full text search
| Yes
| No

| Eventing
| Yes
| No

| Analytics
| Yes
| No
|===

