= Backend Storage
:description: pass:q[Couchbase supports two different backend storage mechanisms: `Couchstore` and `Magma`. It is important to understand which backend storage is best suited to your requirements.]

[abstract]
{description}

== Couchstore

Couchstore is the default backend storage engine that has been in use for more than ten years. It's optimised for high performance with large data sets while using fewer system resources (the minimum bucket size for Couchstore backend is 100 MB). If you have a small data set that can fit in memory, then you should consider using Couchstore.

== Magma

Magma is Couchbase's latest backend engine is designed for high performance with larger datasets (the smallest bucket you can have with a Magma backend is 256 MB). It is optimised for SSD disk access and higher transaction performance, and has such has higher hardware resource requirements. It is especially suited to data sets that will not fit into available memory.

IMPORTANT: Currently, Magma does not support Full Text Searching, Eventing or Analytics.

== Couchstore and Magma at a Glance

|===
| {empty} | Couchstore |Magma

| Minimum bucket size
| 100 MB
| 256 MB

| Maximum storage per node
| 3 TB
| 5 TB

| Maximum storage per cluster
| 30 TB
| 100+ TB

| Full text search
| Yes
| No

| Eventing
| Yes
| No

| Analytics
| Yes
| No
|===

== When should you use Couchstore?

You should use the Couchstore backend if:

* you have a dataset that will fit in available memory.
* you're running the Couchbase server on low-end hardware.
* your Couchbase server needs to support full text searching, eventing, or analytics.

== When should you use Magma?

You should use the Magma backend if:

* your data set won't fit in available memory.
* you need to store large amounts of data in a single node (> 5 TB)
* your application(s) makes heavy use of transactions.


