= Backend Storage
:description: pass:q[Couchbase supports two different backend storage mechanisms: Couchstore and Magma. It is important to understand which backend storage is best suited to your requirements.]

[abstract]
{description}

== Couchstore

Couchstore is the default backend storage engine that has been in use for more than ten years. 
It's optimised for high performance with large data sets while using fewer system resources (the minimum bucket size for Couchstore backend is 100 MB). 
If you have a small data set that can fit in memory, then you should consider using Couchstore.

== Magma

Magma is Couchbase's latest storage engine that is designed for high performance with very large datasets that do not fit in memory. It is ideal for such disk-oriented use cases that primarily rely on disk access. The performance of disk access will be as good as the underlying disk subsystems. e.g. using NVMe SSDs will give higher performance.  
Magma can work with very low amounts of memory for large datasets. e.g. for a node holding 5TB of data, Magma can be used with only 64GB RAM. Magma buckets do require a minimum of 256MB RAM and you should not go below a RAM allocation of 1% of your total data size. 
It is optimised for SSD disk access and higher transaction performance, and has such has higher hardware resource requirements. 
It is especially suited to data sets that will not fit into available memory.

IMPORTANT: Currently, Magma does not support Full Text Searching, Eventing or Analytics.

== Couchstore and Magma at a Glance

|===
| {empty} | Couchstore |Magma

| Minimum bucket size
| 100 MB
| 256 MB

| Maximum storage per node
| 3 TB
| 5 TB

| Maximum storage per cluster
| 30 TB
| 100+ TB

| Full text search
| Yes
| No

| Eventing
| Yes
| No

| Analytics
| Yes
| No
|===

== When should you use Couchstore?

You should use the Couchstore backend if:

* you have a dataset that will fit in available memory.
* you're running the Couchbase server on low-end hardware.
* your Couchbase server needs to support full text searching, eventing, or analytics.

== When should you use Magma?

You should use the Magma backend if:

* your data set won't fit in available memory.
* you need to store large amounts of data in a single node (> 5 TB)
* your application(s) makes heavy use of transactions.


