= Storage Engines
:description: pass:q[Couchbase supports two different backend storage mechanisms: Couchstore and Magma.]

[abstract]
{description}
It is important to understand which backend storage is best suited to your requirements.

== Couchstore

Couchstore is the default bucket storage engine.
It is optimised for high performance with large data sets, while using fewer system resources (the minimum bucket size for the Couchstore backend is 100{nbsp}MB).
If you have a small data set that can fit in memory, then you should consider using Couchstore.

[#storage-engine-magma]
== Magma

[.edition]#{enterprise}#

Magma is designed for high performance with very large datasets that do not fit in memory.
It is ideal for use cases that rely primarily on disk access.
The performance of disk access will be as good as the underlying disk subsystems -- e.g. using NVMe SSDs will give higher performance.

In order to get maximum performance from Magma for disk-oriented workloads, it is recommended to set the Writer Threads to `Disk i/o optimized`. This setting will ensure there are enough threads to sustain high write rates.

To learn more about Writer Thread settings, see xref:manage:manage-settings/general-settings.adoc#data-settings[Data Settings]

Magma can work with very low amounts of memory for large datasets -- e.g. for a node holding 5{nbsp}TB of data, Magma can be used with only 64{nbsp}GB RAM.


.Magma Supported Services
|===
|Couchbase Version |Services Added

|*Version 7.1*
|Query, Index, XDCR, Backup

|*Version 7.1.2*
|[[magma-support-ref]]Search, Eventing, Analytics<<magma-support-note, ^[1]^>>
|===

[horizontal]
[[magma-support-note]]<<magma-support-ref, ^1^>>:: If these services are required in versions prior to 7.1.2, Couchstore should be used.

== Couchstore and Magma at a Glance

|===
| {empty} | Couchstore |Magma

| Minimum bucket memory quota
| 100{nbsp}MB
| [[quota-ref]]1{nbsp}GB<<quota-note, ^[1]^>>

| Minimum memory to data ratio
| 10%
| 1%

| Maximum data per node
| 3{nbsp}TB
| 10{nbsp}TB

|===
[horizontal]
[[quota-note]]<<quota-ref, ^1^>>:: Magma's minimum memory requirement is higher at 1GB per node due to the more complex data structures it has to maintain.

== When should you use Couchstore?

The choice of Couchstore or Magma is set at the bucket level xref:manage:manage-buckets/create-bucket.adoc[when the bucket is created].
A single Couchbase cluster can have a mix of Couchstore and Magma buckets.

You should use the Couchstore backend if:

* You have a dataset with a working set that will fit into available memory (and the working set is >{nbsp}20%).
* You are running the Couchbase server on low-end hardware.
* You are running a version prior to 7.1.2, and your bucket needs to support the Search, Eventing, or Analytics Service.

== When should you use Magma?

You should use the Magma backend if:

* Your working set is much larger than the available memory, and you need high disk-access speed.
* You need to store and access large amounts of data (several terabytes) using a small amount of memory.
* Your applications make heavy use of transactions with persistence-based durability.

== Migrating a Couchstore Bucket to Magma

If you have an existing Couchstore bucket that you would like to migrate to Magma, create a new Magma bucket, and then copy the data to the Magma bucket.

To copy the data, either use xref:xdcr-reference:xdcr-reference-intro.adoc[XDCR] or xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc[backup] the Couchstore bucket and then _restore_ to the Magma bucket.
