= Storage Engines
:description: pass:q[Couchbase supports two different backend storage mechanisms: Couchstore and Magma.]

[abstract]
{description}
It is important to understand which backend storage is best suited to your requirements.

== Couchstore

Couchstore is the default bucket storage engine that has been in use for more than ten years. 
It's optimised for high performance with large data sets while using fewer system resources (the minimum bucket size for Couchstore backend is 100{nbsp}MB). 
If you have a small data set that can fit in memory, then you should consider using Couchstore.

[#storage-engine-magma]
== Magma

[.edition]#{enterprise}#

Magma is Couchbase's latest storage engine that is designed for high performance with very large datasets that do not fit in memory. It is ideal for use cases that rely primarily on disk access. The performance of disk access will be as good as the underlying disk subsystems. e.g. using NVMe SSDs will give higher performance.  
Magma can work with very low amounts of memory for large datasets. e.g. for a node holding 5{nbsp}TB of data, Magma can be used with only 64{nbsp}GB RAM. Magma buckets do require a minimum of 256{nbsp}MB RAM and you should not go below a RAM allocation of 1% of your total data size. 
It is especially suited to data sets that will not fit into available memory.

IMPORTANT: Currently, Magma does not support Full Text Searching, Eventing or Analytics. If the use case requires these features, Couchstore should be used.

== Couchstore and Magma at a Glance

|===
| {empty} | Couchstore |Magma

| Minimum bucket memory quota
| 100{nbsp}MB
| 256{nbsp}MB

| Minimum memory to data ratio
| 10%
| 1%

| Maximum data per node
| 3{nbsp}TB
| 10{nbsp}TB

|===

NOTE: You cannot use FTS, Eventing, or Analytics in Magma buckets. We intend to remove this restriction soon in a follow-up release

== When should you use Couchstore?

The choice of Couchstore or Magma is available at the Bucket level. A single Couchbase cluster can have a mix of Couchstore and Magma buckets.

You should use the Couchstore backend if:

* you have a dataset with a working set that will fit in available memory (and the working set is >{nbsp}20%)
* you're running the Couchbase server on low-end hardware.
* your bucket  needs to support full text searching, eventing, or analytics.

== When should you use Magma?

You should use the Magma backend if:

* your working set is much larger than the available memory and you need disk access speed only
* you need to store large amounts of data in a single node (>{nbsp}5{nbsp}TB) using lowest amount of memory
* your application(s) makes heavy use of transactions with persistence based durability.

== Migrating a Couchstore bucket to Magma

If you have an existing Couchstore bucket that you would like to migrate to Magma, you have to create a new bucket with Magma storage engine and then copy the data.

To copy the data you can either use xref:xdcr-reference:xdcr-reference-intro.adoc[XDCR] or you can xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc[backup] the Couchstore bucket and restore to the new Magma bucket. 


