= Storage Properties
:description: Couchbase Server stores certain items on disk as well as in memory to provide persistence and enhance reliability.
:page-aliases: understanding-couchbase:buckets-memory-and-storage/storage,architecture:storage-architecture,learn:buckets-memory-and-storage/storage.adoc

[abstract]
{description}

[#understanding-couchbase-storage]
== Understanding Couchbase Storage

In addition to storing data in memory, Couchbase Server also stores data in Couchbase buckets on disk.
Saving data to disk provides persistence so that data is not lost if a node restarts or fails.
It also lets your data sets exceed the limits of the memory in your cluster.
Couchbase Server restores data that's not in memory from disk when needed.


Ephemeral buckets and their items exist only in memory and are never written to disk.
For more details, see xref:buckets-memory-and-storage/buckets.adoc[Buckets].

Couchbase Server compresses the data it writes to disk.
Compression reduces the amount of disk space used which can help reduce costs.
It also makes the backup and restore procedures easier.
In addition to compressing data written to disk, Couchbase Server can also compress data in memory.
See xref:buckets-memory-and-storage/compression.adoc[Compression] for more information.

Disk access does not interrupt most client interactions.
However, if a client requests an item that's on disk, it must wait while Couchbase Server reads, decompresses, and copies the data into memory. 

You can remove items from disk based on a configured expiration time, called time to live.
See xref:data/expiration.adoc[Expiration] for details.

To see how Couchbase Server saves new items and updates existing items in Couchbase buckets, using both memory and storage, seexref:buckets-memory-and-storage/memory-and-storage.adoc[Memory and Storage].

[#threading]
== Threading


Couchbase Server uses synchronized, multi-threaded readers and writers to provide high-performance, simultaneous operations for data on disk.
Readers and writers each have their own set of threads.
To prevent conflicts, each thread is responsible for reading or writing a subset of the vBuckets in a Couchbase bucket.

You can control the number of reader and writer threads. 
In the Couchbase Server Web Console, you can have Couchbase Server automatically choose a default value or a value that optimizes disk I/O. 
You can also manually set the number of threads per node to a value between 1 and 64.
Using a higher number of threads may improve performance if your hardware supports it, such as when your CPU has a high large of cores.
Increasing the number of writer threads helps optimize durable writes.
For more information, see xref:learn:data/durability.adoc[Durability].

Setting the number of threads higher than your hardware supports can reduce performance.
Test changes to the default thread allocation before applying them to production systems.
As a starting point, set the number of reader and writer threads to match the queue depth of your I/O subsystem.

For details on setting reader and writer thread counts, see xref:manage:manage-settings/general-settings.adoc#data-settings[Data Settings].

You can also configure thread counts for the NonIO and AuxIO thread pools.
The NonIO thread pool runs in-memory tasks, such as the durability timeout task.
The AuxIO thread pool runs auxiliary I/O tasks, such as the access log task.
Set the thread count for each between 1 and 64.

To view thread status, use the [.cmd]`cbstats` command with the [.param]`raw workload` option.
For more information, see xref:cli:cbstats-intro.adoc[cbstats].

* The NonIO thread pool is used to run in memory tasks--for example, the durability timeout task.

* The AuxIO thread pool is used to run auxiliary I/O tasks--for example, the _access log_ task.

Again, the maximum thread-allocation that can be specified for each is _64_, the minimum is _1_.

Thread-status can be viewed, by means of the [.cmd]`cbstats` command, specified with the [.param]`raw workload` option.
See xref:cli:cbstats-intro.adoc[cbstats] for information.

For information on using the REST API to manage thread counts, see xref:rest-api:rest-reader-writer-thread-config.adoc[Setting Thread Allocations].

[#deletion]
== Deletion

You can delete items either explicitly or by setting a time to live (TTL) value.
When the TTL expires, Couchbase Server deletes the item.

After deletion, Couchbase Server keeps a tombstone as a record (see the next section for more information).

You can set an item's TTL directly on the item or at the bucket level.
For more information, see xref:data/expiration.adoc[Expiration].

== Tombstones

A tombstone records an item removed from the database.
Couchbase Server uses tombstones to maintain consistency between nodes and clusters.
ed to provide eventual consistency, between nodes and between clusters.

Couchbase Server creates tombstones when you:

* Delete an individual document. 
Couchbase Server creates a tombstone that contains the document's key and metadata.

* Drop a collection. 
Couchbase Server creates a tombstone that includes the collection ID, scope ID, and a manifest ID that records the drop event.
+
When you drop a collection, Couchbase Server deletes all documents in it.
It does not maintain tombstones for those deleted documents.
Couchbase Server also deletes any document tombstones that were in the collection before you dropped it.
After you drop a collection, only the collection tombstone remains.
Couchbase Server replicates the collection tombstone as a single message (ordered with respect to mutations in the vBucket) to replicas and other DCP clients.
This message notifies recipients that you dropped the collection.
Each recipient is then responsible for purging anything it still contains from the dropped collection.

The Metadata Purge Interval setting controls how often Couchbase Server purges tombstones of both kinds.
When Couchbase Server purges a tombstone, it removes it completely.
The Metadata Purge Interval runs as part of auto-compaction.
See xref:learn:buckets-memory-and-storage/storage.adoc#append-only-writes-and-auto-compaction[Append-Only Writes and Auto-Compaction] for more information.

For more information, see xref:data/expiration.adoc#post-expiration-purging[Post-Expiration Purging] in xref:data/expiration.adoc[Expiration].

[#disk-paths]
== Disk Paths

When you initialize a node, you choose where Couchbase Server stores data for most services.
You can specify the location where Couchbase Server stores data on a node for the following services:

* Data Service
* Index Service
* Analytics Service
* Eventing Service

In addition, you can use local paths for backup repositories.
See xref:learn:services-and-indexes/services/backup-service.adoc#repositories[Repositories] for more information.

Couchbase Server has a default storage location for logs that's platform-specific. 
For example, on Linux, the default location is `/opt/couchbase/var/lib/couchbase/logs`.

For information about setting data paths, see xref:manage:manage-nodes/initialize-node.adoc[Initialize a Node].

[[filesystem-free-space-and-usage-limits]]
=== Filesystem Free Space and Usage Limits

Running out of disk space on any filesystem can cause errors. 
In particular, running out of disk space on the filesystem containing the Data Service storage path can make recovery difficult.
Recovery problems could lead to data loss.

By default, Couchbase Server alerts you if the filesystem containing the following storage paths becomes more than 90% full:

* Data Service
* Index Service
* `ns_log` and `audit_log` paths`


See xref:manage:manage-settings/configure-alerts.adoc[] for more information about alerts.
You can change how full the disk becomes before triggering this alert by changing the  xref:rest-api:rest-cluster-email-notifications.adoc#maxdatadiskusedperc[maxDiskUsedPerc] alert limit.

Couchbase Server only appends to files.
Appending-only helps to ensure the internal consistency of the files and reduces the risk of corruption.
However, this means that every change made to a file&#8212;whether an addition, a mutation,
or a deletion&#8212; results in a new entry being appended to the file.
Therefore, even if you delete data from a file, the result is that the file size grows larger.
The deletion just appends a record to the file indicating that the data was deleted.

To reduce file size, enable compaction.
This operation can be performed either manually, on a specified bucket; or on an automated, scheduled basis, either for specified buckets or for all buckets.

For all information on using the REST API for compaction, see the xref:rest-api:rest-autocompact-global.adoc[Global Compaction API] 
or xref:rest-api:rest-autocompact-per-bucket.adoc[Per-bucket Compaction API].

You can enable a feature to have Couchbase Server stop writing to the Data Service storage path when it reaches a certain percentage of disk usage.
The default (and recommended) limit is 85% full which means Couchbase Server stops writing data if the filesystem is 85% or more full. 
Enabling this limit helps avoid potential issues with recovery.

When you set a disk usage limit, Couchbase Server starts alerting you when the filesystem fills to within 10% of the threshold you set.
This alert is in addition to the default alert when the filesystem is 90% full. 
For example, if you use the default limit of 85%, Couchbase Server alerts you when the filesystem reaches 75% full.

When the filesystem reaches the limit, Couchbase Server stops writing to the Data Service storage path.
Any attempts to write to the Data Service storage path results in an `EBucketDiskSpace` error. 
To re-enable writes, you must reduce the disk usage below the limit you set.

To learn how to set the disk usage limit using the Couchbase Server Web Console, see xref:manage:manage-settings/general-settings.adoc#data-settings[Data Settings].
To set the limits using the REST API, see xref:rest-api:disk-usage-limits.adoc[].

[#append-only-writes-and-auto-compaction]
== Append-Only Writes and Auto-Compaction

When mutating data, Couchbase Server only appends to data files, instead of rewriting them.
This approach helps maintain file consistency and reduces the risk of file corruption.
Every time you add, modify, or delete data, Couchbase Server creates a new entry at the end of the data files.
As a result, files grow in size even when you delete data.

To prevent data files from growing too large, Couchbase Server periodically compacts them.
Compaction rewrites the file, applying additions, modifications, and deletions before saving a new version of the file.
You can change the schedule Couchbase Server follows to compact data.
See xref:manage:manage-settings/configure-compact-settings.asdoc[Auto-Compaction] for more information.
For information about configuring auto-compaction with the command line, see xref:cli:cbcli/couchbase-cli-setting-compaction.adoc[setting-compaction].

You can also perform compaction manually on a specific bucket.
For information about performing manual compaction with the command line, see xref:cli:cbcli/couchbase-cli-bucket-compact.adoc[bucket-compact].

For all information about using the REST API for compaction, see the xref:rest-api:compaction-rest-api.adoc[Compaction API].

== Disk I/O Priority

Disk I/O means reading items from and writing them to disk.
Disk I/O does not block client interactions because it runs as a background task.
You can configure the priority of disk I/O and other background tasks, such as item paging and DCP stream processing, for each bucket.
For example, you can give one bucket a higher disk I/O priority than another.
For further information, see
xref:manage:manage-buckets/create-bucket.adoc[Create a Bucket].

[#storage-settings-ejection-policy]
== Ejection Policy

To improve performance, Couchbase Server tries to keep as much data as possible in memory.
When memory fills, Couchbase Server ejects data from memory to make room for new data.
Ejection policies control how Couchbase Server decides what data to remove.

Ejection has a different effect on different bucket types.
In an ephemeral bucket, data that Couchbase Server ejects is lost, because it only exists in memory.
In Couchbase buckets, data is removed from memory but still exists on disk.
If the data is needed again, Couchbase Server can reload the data from disk back into memory.

The available ejection policies depend on the bucket type, as shown in the following table.


.Ejection policies
|===
|Policy |Bucket type |Description

|No Ejection
|Ephemeral
|When memory runs out, the bucket becomes read-only to prevent data loss.
This is the default setting.

|Not Recently Used (NRU) Ejection
|Ephemeral
|The server removes from memory the documents that have not been used for the longest time.

|Value Only Ejection
|Couchbase
|When memory is low, Couchbase Server ejects values and data from memory but keeps keys and metadata.
This is the default policy for Couchbase buckets.

|Full Ejection
|Couchbase
|The server ejects data, keys, and metadata from memory.

|===

You can set the policy using the xref:rest-api:rest-bucket-create.adoc#evictionpolicy[REST API] when you create the bucket.
For more information about ejection policies, read https://blog.couchbase.com/a-tale-of-two-ejection-methods-value-only-vs-full/

include::partial$full-ejection-note.adoc[]

NOTE: In Capella, Couchbase buckets are called Memory and Disk buckets.
Ephemeral buckets are called Memory Only buckets.
