= Storage
:page-aliases: understanding-couchbase:buckets-memory-and-storage/storage

[abstract]
Couchbase Server provides persistence, whereby certain items are stored on disk as well as in memory; and reliability is thereby enhanced.

[#understanding-couchbase-storage]
== Understanding Couchbase Storage

Couchbase Server stores certain items in compressed form on disk; and, whenever required, removes them.
This allows data-sets to exceed the size permitted by existing memory-resources; since undeleted items not currently in memory can be restored to memory from disk, as needed.
It also facilitates backup-and-restore procedures.

Generally, a client's interactions with the server are not blocked during disk-access procedures.
However, if a specific item is being restored from disk to memory, the item is not made available to the client until the item's restoration is complete.

Not all items are written to disk: _Ephemeral_ buckets and their items are maintained in memory only.
See xref:buckets-memory-and-storage/buckets.adoc[Buckets] for information.

Items written to disk are always written in compressed form.
Based on bucket configuration, items may be maintained in compressed form in memory also.
See xref:buckets-memory-and-storage/compression.adoc[Compression] for information.

Items can be removed from disk based on a configured point of expiration, referred to as _Time-To-Live_.
See xref:buckets-memory-and-storage/expiration.adoc[Expiration] for information.

For illustrations of how Couchbase Server saves new and updates existing Couchbase-bucket items, thereby employing both memory and storage resources, see xref:buckets-memory-and-storage/memory-and-storage.adoc[Memory and Storage].

[#threading]
== Threading

Synchronized, multi-threaded _readers_ and _writers_ provide simultaneous, high-performance read-write operations for data on disk.
Conflicts are avoided by assigning each thread (reader or writer) a specific subset of the 1024 vBuckets for each Couchbase bucket.
For example, the first of five reader-threads is assigned vBuckets 0, 5, 10, 15, 20, and so on; while the second is assigned vBuckets 1, 6, 11, 16, 21, and so on.
Thread-status can be viewed, by means of the [.cmd]`cbstats` command, specified with the [.param]`raw workload` option.

See xref:cli:cbstats-intro.adoc[cbstats] and xref:buckets-memory-and-storage/vbuckets.adoc[vBuckets] for information.

[#deletion]
== Deletion

Items can be deleted by a client application: either by immediate action, or by setting a _Time-To-Live_ (TTL) value: this value is established through accessing the `TTL` metadata field of the item, which establishes a future point-in-time for the item's _expiration_.
When the point-in-time is reached, Couchbase Server deletes the item.

Following deletion by either method, a _tombstone_ is maintained by Couchbase Server, as a record (see below).

An item's TTL can be established either directly on the item itself, or via the bucket that contains the item.
For information, see xref:buckets-memory-and-storage/expiration.adoc[Expiration].

== Tombstones

A _tombstone_ is the record of a deleted item.
Each tombstone includes the item's key and metadata.
Tombstones are maintained in order to provide eventual consistency both between nodes and between clusters.

The _Metadata Purge Interval_ establishes the frequency with which Couchbase Server _purges_ itself of tombstones: which means, removes them fully and finally.
The Metadata Purge Interval setting runs as part of auto-compaction.

For more information, see xref:buckets-memory-and-storage/expiration.adoc#post-expiration-purging[Post-Expiration Purging], in xref:buckets-memory-and-storage/expiration.adoc[Expiration].

== Disk I/O Priority

_Disk I/O_ — reading items from and writing them to disk — does not block client-interactions: disk I/O is thus considered a _background task_.
The priority of disk I/O (along with that of other background tasks, such as item-paging and DCP stream-processing) is configurable _per bucket_.
This means, for example, that one bucket's disk I/O can be granted priority over another's.
For further information, see
xref:manage:manage-buckets/create-bucket.adoc[Create a Bucket].
