= Drop DEKs and Re-encrypt Data 
:description: pass:q[You can use the REST API to drop data encryption keys (DEKs) and re-encrypt the data encrypted with the old keys.]
:page-edition: Enterprise Edition
:page-topic-type: reference
:tabs:
:page-toclevels: 3

[abstract]
{description}

== Description

You may want to drop data encryption keys (DEKs) if you believe they have been compromised.
When you have Couchbase Server drop DEKs, it creates new a DEK to replace the active and all historical DEKs for the bucket or data type.
It then re-encrypts all data using the new DEK and deletes the old DEKs.
This re-encryption includes any unencrypted data that was written before you enabled encryption at rest.

NOTE: If you just want to encrypt any unencrypted data, you can do so without dropping the DEKs. 
See xref:rest-api:security/encryption-at-rest/force-encryption-at-rest.adoc[] for more information.

Dropping the DEKs is not the same as rotating them.
When it rotates a DEK, Couchbase Server just creates a new DEK and makes it active.
It does not re-encrypt data, and it keeps the inactive DEKs for a period of time.
You cannot manually rotate DEKs.
When you drop DEKs, Couchbase Server creates new a new DEK, re-encrypts all data with it, and deletes the old DEKs.

IMPORTANT: The process of dropping DEKs for a bucket with a large amount of data may take a long time and could affect performance.
Couchbase Server has to re-encrypt all data in the bucket with the new DEK.
Dropping DEKs for a type of data usually results in re-encrypting less data than a bucket.

See xref:manage:security/manage-native-encryption-at-rest.adoc#drop-deks[Manually Drop DEKs and Re-encrypt Data] for instructions on dropping DEKs using the Couchbase Server Web Console.

== HTTP Methods

This API endpoint supports the following methods:

* <<#drop-bucket>>
* <<#drop-type>>

[#drop-bucket]
== Drop DEKs and Re-encrypt Data for a Bucket

Drop all DEKs for a bucket and re-encrypt all data in that bucket with new DEK.

.Drop DEKs for Bucket and Re-encrypt Data
----
POST /controller/dropEncryptionAtRestDeks/bucket/{BUCKET_NAME}
----

.Path Parameters
`BUCKET_NAME`::
The name of the bucket where you want to drop the  DEKs and re-encrypt.
This bucket must already have encryption at rest enabled.

=== curl Syntax

[source,bash]
----
curl -sS -u $USER:$PASSWORD \
     -X POST 'http[s]://<hostname>:{PORT}/controller/dropEncryptionAtRestDeks/bucket/{BUCKET_NAME}' 
----

.Path Parameters
:priv-link: bucket-privs
include::partial$user-pw-host-port-params.adoc[]

`BUCKET_NAME`::
The name of the bucket where you want to drop DEKs and re-encrypt data.
This bucket must already have encryption at rest enabled.

[#bucket-privs]
=== Required Privileges

* xref:learn:security/roles.adoc#backup_admin[Backup Admin]
* xref:learn:security/roles.adoc#bucket_admin[Bucket Admin] that has privileges on the bucket to be encrypted.
* xref:learn:security/roles.adoc#cluster_admin[Cluster Admin]
* xref:learn:security/roles.adoc#eventing_admin[Eventing Admin]
* xref:learn:security/roles.adoc#admin[Full Admin]

=== Responses

`200 OK`::
The DEKs for the bucket were dropped and the data was re-encrypted with the new DEK. 
It also returns a JSON object containing a timestamp of when the drop  and re-encryption process started.
See <<#drop-bucket-example,the example in the next section>> for an example of the response.

`403 Forbidden`::
You do not have the required privileges to drop the DEKs for the bucket.

`404 Not Found`::
The bucket passed in the `BUCKET_NAME` path parameter does not exist.

[#drop-bucket-example]
=== Example

The following example drops the DEKs for the `travel-sample` bucket and re-encrypts all data in that bucket with the new DEK.

[source,bash]
----
curl -sS -u Administrator:password -X POST \
     http://localhost:8091/controller/dropEncryptionAtRestDeks/bucket/travel-sample \
     | jq
----

The result of the command is a JSON object similar to the following:

[source,json]
----
{
  "dropKeysDate": "2025-08-06T19:00:42Z"
}
----

[#drop-type]
== Drop DEKs and Re-encrypt Audit, Configuration, or Log Data

Drop the DEKs for a type of system data and re-encrypt all data with the new DEKs.
The data types you can re-encrypt are:

* Audit
* Configuration 
* Logs


.Drop DEKs for Audit, Configuration, or Logs and Re-encrypt Data
----
POST /controller/dropEncryptionAtRestDeks/{TYPE}
----

.Path Parameters
`TYPE`::
The type of data whose DEKs you want dropped and data re-encrypted.
Can be one of the following values:

+
* `audit`: Encrypts unencrypted audit data.
* `config`: Encrypts unencrypted configuration data.
* `log`: Encrypts unencrypted log data.

=== curl Syntax

[source,bash]
----
curl -sS -u $USER:$PASSWORD \
     -X POST 'http[s]://<hostname>:{PORT}/controller/dropEncryptionAtRestDeks/{TYPE}' 
----

.Path Parameters
:priv-link: type-privs
include::partial$user-pw-host-port-params.adoc[]

`TYPE`::
The type of data whose DEKs you want dropped and data re-encrypted.
Can be one of the following values:

+
* `audit`: Encrypts unencrypted audit data.
* `config`: Encrypts unencrypted configuration data.
* `log`: Encrypts unencrypted log data.

[#type-privs]
=== Required Privileges

* xref:learn:security/roles.adoc#cluster_admin[Cluster Admin]
* xref:learn:security/roles.adoc#eventing_admin[Eventing Admin]
* xref:learn:security/roles.adoc#admin[Full Admin]

=== Responses

`200 OK`::
The DEKs for the type of data were dropped and its data was re-encrypted with the new DEK.
It also returns a JSON object containing a timestamp of when the drop and re-encryption process started.
See <<#drop-type-example,the example in the next section>> for an example of the response.

`403 Forbidden`::
You do not have the required privileges to drop the DEKs for system data.

`404 Not Found`::
The type of data passed in the `TYPE` path parameter does not exist.

[#drop-type-example]
=== Example

The following example drops the DEKs for the `audit` data and re-encrypts all data of that type with the new DEK.

[source,bash]
----
curl -v -u Administrator:password -X POST \
     http://localhost:8091/controller/dropEncryptionAtRestDeks/audit \
     | jq
----

The result of the command is a JSON object similar to the following:
[source,json]
----
{
  "dropKeysDate": "2025-08-06T19:05:42Z"
}
----

