= Drop DEKs and Re-encrypt Data 
:description: pass:q[You can use the REST API to force the dropping (rotatation) of data encryption keys (DEKs) and re-encrypt the data encrypted with the old keys.]
:page-edition: Enterprise Edition
:page-topic-type: reference
:tabs:
:page-toclevels: 3

[abstract]
{description}

== Description

You may want to drop data encryption keys (DEKs) if you believe they have been compromised or you want to adjust the DEK lifetimes.

NOTE: This method is similar to the xref:rest-api:security/encryption-at-rest/force-encryption-at-rest.adoc[`/controller/forceEncryptionAtRest`] endpoint.
It rotates the DEKs and encrypts all data (including historical data written before encryption at rest was enabled) with the new DEKs.
The `/controller/forceEncryptionAtRest` endpoint only encrypts unencrypted data and does not rotate DEKs.

See xref:learn:security/native-encryption-at-rest-overview.adoc#rotation-expiration[Encryption Key Rotation and Expiration] for more information about key rotation.

== HTTP Methods

This API endpoint supports the following methods:

* <<#drop-bucket>>
* <<#drop-type>>

[#drop-bucket]
== Rotate DEKs and Re-encrypt Data for a Bucket

Drop the DEKs for a bucket and re-encrypt all data in that bucket with new DEK.

.Drop DEKs for Bucket and Re-encrypt Data
----
POST /controller/dropEncryptionAtRestDeks/bucket/{BUCKET_NAME}
----

.Path Parameters
`BUCKET_NAME`::
The name of the bucket whose DEKs you want rotate and re-encrypt the data in.
This bucket must already have encryption at rest enabled.

=== curl Syntax

[source,bash]
----
curl -sS -u $USER:$PASSWORD \
     -X POST 'http[s]://<hostname>:{PORT}/controller/dropEncryptionAtRestDeks/bucket/{BUCKET_NAME}' 
----

.Path Parameters
:priv-link: bucket-privs
include::partial$user-pw-host-port-params.adoc[]

`BUCKET_NAME`::
The name of the bucket whose DEKs you want rotate and re-encrypt the data in.
This bucket must already have encryption at rest enabled.

[#bucket-privs]
=== Required Privileges

* xref:learn:security/roles.adoc#backup_admin[Backup Admin]
* xref:learn:security/roles.adoc#bucket_admin[Bucket Admin] that has privileges on the bucket to be encrypted.
* xref:learn:security/roles.adoc#cluster_admin[Cluster Admin]
* xref:learn:security/roles.adoc#eventing_admin[Eventing Admin]
* xref:learn:security/roles.adoc#admin[Full Admin]

=== Responses

`200 OK`::
The DEKs for the bucket were rotated and the data was re-encrypted with the new DEKs. 
It also returns a JSON object containing a timestamp of when the rotation and re-encryption process started.
See <<#drop-bucket-example,the example in the next section>> for an example of the response.

`403 Forbidden`::
You do not have the required privileges to rotate the DEKs for the bucket.

`404 Not Found`::
The bucket passed in the `BUCKET_NAME` path parameter does not exist.

[#drop-bucket-example]
=== Example

The following example rotates the DEKs for the `travel-sample` bucket and re-encrypts all data in that bucket with the new DEKs.

[source,bash]
----
curl -sS -u Administrator:password -X POST \
     http://localhost:8091/controller/dropEncryptionAtRestDeks/bucket/travel-sample \
     | jq
----

The result of the command is a JSON object similar to the following:

[source,json]
----
{
  "dropKeysDate": "2025-08-06T19:00:42Z"
}
----

[#drop-type]
== Rotate DEKs and Re-encrypt Type of Data

Drop the DEKs for a type of system data and re-encrypt all data with the new DEKs.
The data types you can re-encrypt are:

* Audit
* Configuration 
* Logging


.Drop DEKs for Data Type and Re-encrypt Data
----
POST /controller/dropEncryptionAtRestDeks/{TYPE}
----

.Path Parameters
`TYPE`::
The type of data whose DEKs you want rotated and data re-encrypted.
Can be one of the following values:

+
* `audit`: Encrypts unencrypted audit data.
* `config`: Encrypts unencrypted configuration data.
* `log`: Encrypts unencrypted log data.

=== curl Syntax

[source,bash]
----
curl -sS -u $USER:$PASSWORD \
     -X POST 'http[s]://<hostname>:{PORT}/controller/dropEncryptionAtRestDeks/{TYPE}' 
----

.Path Parameters
:priv-link: type-privs
include::partial$user-pw-host-port-params.adoc[]

`TYPE`::
The type of data whose DEKs you want rotated and data re-encrypted.
Can be one of the following values:

+
* `audit`: Encrypts unencrypted audit data.
* `config`: Encrypts unencrypted configuration data.
* `log`: Encrypts unencrypted log data.

[#type-privs]
=== Required Privileges

* xref:learn:security/roles.adoc#cluster_admin[Cluster Admin]
* xref:learn:security/roles.adoc#eventing_admin[Eventing Admin]
* xref:learn:security/roles.adoc#admin[Full Admin]

=== Responses

`200 OK`::
The DEKs for the type of data were rotated and the data was re-encrypted with the new DEKs.
It also returns a JSON object containing a timestamp of when the rotation and re-encryption process started.
See <<#drop-type-example,the example in the next section>> for an example of the response.

`403 Forbidden`::
You do not have the required privileges to rotate the DEKs for system data.

`404 Not Found`::
The type of data passed in the `TYPE` path parameter does not exist.

[#drop-type-example]
=== Example

The following example rotates the DEKs for the `audit` data type and re-encrypts all data of that type with the new DEKs.

[source,bash]
----
curl -v -u Administrator:password -X POST \
     http://localhost:8091/controller/dropEncryptionAtRestDeks/audit \
     | jq
----

The result of the command is a JSON object similar to the following:
[source,json]
----
{
  "dropKeysDate": "2025-08-06T19:05:42Z"
}
----
