= Manage Encryption at Rest Keys
:description: pass:q[You must create encryption at rest keys before you can have Couchbase Server encrypt data as it saves it to disk.]
:page-edition: Enterprise Edition
:page-topic-type: reference
:page-toclevels: 3

[abstract]
{description}

== Description

These APIs let you list, create, change, and delete encryption at rest keys.
See xref:learn:security/native-encryption-at-rest-overview.adoc[] for more information about encryption at rest.

== HTTP Methods and URIs

This API endpoint supports the following calls.

[#list-keys]
=== List Encryption at Rest Keys

List one or all encryption at rest keys defined in the cluster.

.List All Keys
----
GET  /settings/encryptionKey/
----

.Get details of a specific key
----
GET  /settings/encryptionKey/{KEY-ID}
----

.Path Parameters
[cols="2,3,2", caption=]
|===
|Name | Description | Schema

| `KEY-ID`
| The `id` attribute of the key you want to view. 
| Integer
|===

==== curl Syntax

[source,bash]
----
curl -sS -u <username>:<password> \
     -X GET 'http[s]://<hostname>>:[8091|18091]/settings/encryptionKeys/[key-id]' 
----

.GET Path Parameters
`key-id`::
*Optional* The id of the single encryption at rest key whose details you want to retrieve.


==== Required Privileges

Any of the following roles:

* Full Admin
* security_admin_local
* security_admin_external
* ro_admin

==== Responses

`200 OK`::

Returned even if user does not have permission to view keys. 

