= Manage Encryption-at-Rest Keys
:description: pass:q[You must create encryption-at-rest keys before you can have Couchbase Server encrypt data as it saves it to disk.]
:page-edition: Enterprise Edition
:page-topic-type: reference
:tabs:
:page-toclevels: 3

[abstract]
{description}

== Description

These APIs let you list, create, change, and delete encryption-at-rest keys.
See xref:learn:security/native-encryption-at-rest-overview.adoc[] for more information about encryption at rest.

== HTTP Methods 

This API endpoint supports the following methods:

* <<#list-keys>>
* <<#create-key>>
* <<#delete-key>>



[#list-keys]
== List Encryption-at-Rest Keys

List one or all encryption-at-rest keys defined in the cluster.

.List All Keys
----
GET /settings/encryptionKey/
----

.Get details of a specific key
----
GET /settings/encryptionKey/{KEY_ID}
----

.Path Parameters
`KEY_ID` (integer)::
The `id` attribute of the key you want to view. 
See the <<#gey-keys-example,example>> for an explanation of getting this value.

=== curl Syntax

[source,bash]
----
curl -sS -u $USER:$PASSWORD \
     -X GET 'http[s]://<hostname>:{PORT}/settings/encryptionKeys/[{KEY_ID}]' 
----

.Path Parameters
:priv-link: get-privs
include::partial$user-pw-host-port-params.adoc[]

`KEY_ID`::
*Optional* The id of the single encryption-at-rest key whose details you want to retrieve.


[[get-privs]]
=== Required Privileges

You must have at least on one of the following roles:

* xref:learn:security/roles.adoc#security_admin_external[External User Admin]
* xref:learn:security/roles.adoc#admin[Full Admin]
* xref:learn:security/roles.adoc#security_admin_local[Local User Admin]
* xref:learn:security/roles.adoc#read-only-admin[Read-Only Admin]
* xref:learn:security/roles.adoc#security_admin[Security Admin]

=== Responses

`200 OK`::
Returns the encryption-at-rest keys or a particular key if you specified the `KEY_ID` path parameter. 
See examples for an example of the keys.

+
NOTE: Call returns `200 OK` and an empty JSON message if user does not have permission to view keys. 

`404 Object Not Found`::
Returned if you specified a `KEY_ID` path parameter which does not match the ID of an encryption-at-rest key.

[#gey-keys-example]
=== Examples

The following example gets all of the encryption-at-rest keys defined in the system.

[source,bash]
----
 curl -v -u Administrator:password \
      -X GET 'http://127.0.0.1:8091/settings/encryptionKeys/' | jq
----

An example of running the previous command:

[source,json]
----
[
  {
    "data": {
      "keys": [
        {
          "id": "b3dd8518-e747-4a64-ad6b-db9c5d306a6c",
          "active": true,
          "creationDateTime": "2025-04-23T16:22:39Z",
          "keyMaterial": "******"
        }
      ],
      "encryptWith": "nodeSecretManager",
      "canBeCached": true,
      "autoRotation": false
    },
    "id": 7,
    "name": "data-one-buckey-key",
    "type": "auto-generated-aes-key-256",
    "usage": [
      "bucket-encryption-beer-sample",
      "bucket-encryption-test"
    ],
    "creationDateTime": "2025-04-23T16:22:39Z"
  },
  {
    "data": {
      "port": 5696,
      "host": "https://kms.example.com",
      "reqTimeoutMs": 1000,
      "keyPath": "/scripts/certs/cb_key.pem",
      "keyPassphrase": "******",
      "encryptionApproach": "useGet",
      "certPath": "/scripts/certs/cb_cert.pem",
      "caSelection": "useSysAndCbCa",
      "encryptWith": "nodeSecretManager",
      "historicalKeys": [],
      "activeKey": {
        "id": "0788edb1-1418-4225-903b-bc1f9f59aa4d",
        "kmipId": "550e8400-e29b-41d4-a716-446655440000",
        "creationDateTime": "2025-04-23T14:44:20Z"
      },
      "encryptWithKeyId": -1
    },
    "id": 2,
    "name": "kmip-key",
    "type": "kmip-aes-key-256",
    "usage": [
      "KEK-encryption",
      "bucket-encryption",
      "config-encryption",
      "log-encryption",
      "audit-encryption"
    ],
    "creationDateTime": "2025-04-23T14:44:20Z"
  },
  {
    "data": {
      "profile": "",
      "configFile": "",
      "useIMDS": true,
      "region": "us-east-1",
      "keyARN": "arn:aws:kms:us-east-1:000000000000:key/aaaaaaaa-bbbb-dddd-eeee-ffffffffffff",
      "credentialsFile": "",
      "storedKeyIds": [
        {
          "id": "c1cddf80-720e-47f0-adb7-641f5cb2ce22",
          "creationDateTime": "2025-04-23T16:00:22Z"
        }
      ]
    },
    "id": 6,
    "name": "Example AWS key",
    "type": "awskms-aes-key-256",
    "usage": [
      "KEK-encryption"
    ],
    "creationDateTime": "2025-04-23T16:00:22Z"
  }
]
----


All keys have the following fields:

* `id`: the integer identifying the encryption key
* `name`: the friendly name assigned by the administrator who created the key.
* `usage`: what the key is allowed to encrypt.
* `type`: which key management system (KMS) manages the key.
+
NOTE: The `type` also contains the encryption algorithm used for the encryption-at-rest key. 
Currently, this is always `aes-key-256`.

The `data` object defines the KMS-specific details for each encryption key.
You'll notice different fields for each type of key:

Keys managed by Couchbase Server::

* The `keys` list contains the current and expired encryption keys. 
The other key types have their contents stored within the remote KMS.
* The `autorotation` field indicates whether Couchbase Server automatically rotates the key.
When set to `true``, additional fields, such as  `data.rotationIntervalInDays` and `nextRotationTime` show details of the key's rotation.
* 

Keys managed by a KMIP-compatible KMS::

* The fields configure the authentication with the KMS.   

Keys Managed by AWS::

* `keyANN` is the identity of the key in the AWS KMS.
* The `profile`, `credentialsFile`, and `configFile` hold the credentials Couchbase Server uses to authenticaste with AWS KMS. 
These values are empty when Couchbase Server uses IAM to authenticate with AWS instead of stored credentials.

[[create-key]]
== Create or Update an Encryption-at-Rest Key

You can create or update an encryption-at-rest-key key using the REST API.


.Create an Encryption Key
----
POST /settings/encryptionKey/
----

.Update a Key
----
PUT /settings/encryptionKey/{KEY_ID}
----

.Path Parameters
`KEY_ID` (integer)::
The `id` attribute of the key you want to update. 


=== curl Syntax

.Create an Encryption at Rest Key
[source,bash]
----
curl -sS -u $USER:$PASSWORD \
  -X POST http://{HOST}:{PORT}/settings/encryptionKeys \
  --data-binary @- <<EOF | jq
{
  "name": "<keyname>",
  "usage": [
    "<usage>"[."<usage>"...]
  ],
  "type": "<KMS>",
  "data": {
    <KMS-specific-fields>
  }
}
EOF
----

.Update an Encryption at Rest Key
[source,bash]
----
curl -sS -u $USER:$PASSWORD \
  -X PUT http://{HOST}:{PORT}/settings/encryptionKeys/<KEY_ID> \
  --data-binary @- <<EOF | jq
{
  "name": "<keyname>",
  "usage": [
    "<usage>"[."<usage>"...]
  ],
  "type": "<KMS>",
  "data": {
    <KMS-specific-fields>
  }
}
EOF
----

NOTE: Updating a key has the same required fields as the creating a new key. 
For example, you must supply the `name` field, even if you want the key's name to remain the same.
Any value you do not supply in the update call is set ot the default value (if any) or is left empty, overwriting any existing value.


:priv-link: create-privs
.Path Parameters
include::partial$user-pw-host-port-params.adoc[]

`KEY_ID` (integer)::
 The `id` attribute of the key you want to update.

.Fields

`name`::
A name to give to the key. 
This name must be different from any other encryption-at-rest key.

[#usage]
`usage`::
A comma-separated list of what this key can encrypt.
Allowed values for this list are:

+
* `"KEK-encryption"`: Can encrypt other encryption-at-rest keys (KEK).
* `"bucket-encryption"`: Can encrypt any bucket in the cluster.
* `"bucket-encryotion-<bucket-name>"`: Can encrypt the bucket named `bucket-name`.
You can have multiple entries so the key can encrypt multiple buckets.
* `"config-encryption"`: Can encrypt onfiguration information.
* `"log-encryption"`: Can encrypt logs.
* `"audit-encryption"`: Can encrypt audit data.

`type`::
Defines the encryption standard and the key management system for the key.
All encryption-at-rest keys use AES 256 encryption.
Allowed values are:  

+
* `"awskms-aes-key-256"`: AWS KMS manages the key.
* `"kmip-aes-key-256"`: A KMIP-compatible KMS manages the key.
* `"auto-generated-aes-key-256"`: Couchbase Server manages the key.

`data`::
The contents of the `data` object depend on the KMS set in the `type` field because each KMS has unique settings.


[{tabs}]
====
AWS::
+
--

When using the AWS KMS, the `data` object has the following schema:

[source,json]
----
  "data": {
    "keyARN": "<arn>",
    "region": "<region>",
    "useIMDS": <true|false>,
    "profile": "<profile-file-path>",
    "credentiials-file": "<credential-file-path>",
    "configFile": "<config-file-path>"
  }
----

.Fields

* `keyARN`: The https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html[Amazon Resource Name (ARN)^] that identifies the encryption key in the AWS KMS. 
* `region` (optional): The region hosting your AWS KMS.
* `useIMDS` (Boolean, optional): Whether to use Amazon's https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html[Instance Metadata Service (IMD)^] when contacting  the AWS KMS. 
Set this to `true` when your cluster runs on AWS EC2 instances.
Defaults to `false`.


You must give Couchbase Server a way to authenticate with the AWS KMS. 
See Amazon's https://docs.aws.amazon.com/kms/latest/developerguide/control-access.html[KMS key access and permissions] for details of configuring authentication. 

You can use https://docs.aws.amazon.com/kms/latest/developerguide/iam-policies.html[IAM policies^] to allow Couchbase Server to transparently connect to the AWS KMS.
If you configure IAM, you do not need any additional authentication configuration within Couchbase Server.
Always use this method if your database runs on an AWS EC2 cluster.
It's also possible to configure IAM for your cluster when it's not running in AWS.
See the AWS documentation for using https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_non-aws.html[IAM Roles Anywhere^].

The other authentication method is to use three optional parameters to pass Couchbase Server the necessary credentials in several files.
These files must exist on all servers in your cluster.

Use the following parameters to tell Couchbase Server where these files are located:

* `credentials-file` the absolute path to a file containing the AWS credentials to use when authenticating with the AWS KMS.
When you supply this path, the file must exist on all nodes.
This file often stored at `~/.aws/credentials` on Linux systems.
For example:

+
[source,ini]
----
[my-profile]
aws_access_key_id = ABCDE...
aws_secret_access_key = xyz123...
----

* `configFile`: the absolute path to a file that defines one or more profiles for accessing AWS.
 This file is often stored in `~/.aws/config` on Linux systems.
 The format of 

+
[source,ini]
----
[profile profile-name]
region = us-east-1
output = json
role_arn = arn:aws:iam::123456789012:role/RoleName
source_profile = base
----

* `profile`: Path to a file containing the name of the profile defined in the `credentials-file` to use when authenticating with AWS KMS.

NOTE: Couchbase Server does not verify the information you give it during key creation. 
It only attempts to connect to AWS when you select the key to encrypt data or another key. 
--

KMIP KMS::
+
--
When using a KMIP-compatible KMS, the `data` object has the following schema:  

[source,json]
----
"data": {
      "port": <kms-port>,
      "host": "<kms-host-url>",
      "reqTimeoutMs": <timeout-ms>,
      "keyPath": "<path-to-key-pem>",
      "keyPassphrase": "<passphrase>",
      "encryptionApproach": "<local-or-kms>",
      "certPath": "<certificate-path>",
      "caSelection": "<trust-store>",
      "encryptWith": "<password-or-key>",
      "activeKey": {
        "kmipId": "<kmip-KEY_ID>"
      },
      "encryptWithKeyId": <local-KEY_ID>
    }
----

.Fields

* `port`: Integer port number for the KMS server. 
Most KMS servers use port 5696.
* `host`: The URL for the KMS.
* `reqTimeoutMs` (integer, optional): The timeout for network communication with the KMS in milliseconds.
Defaults to 1000.
* `keyPath`: Absolute path on each server to the private key Couchbase Server uses to authenticate with the KMS.
This key file must be in PEM format.
* `keyPassphrase` (optional): The private key's passphrase, if it has one.
* `encryptWith`: Controls which system performs the decryption of keys.
Can be one of the following values:

** `"useGet"`: Couchbase Server retrieves the encryption key from the KMS and uses it to decrypt local DEKs and encryption keys.
** `"useEncryptDecrypt"`: Send local DEKs and encryption keys to the KMS.
The KMS decrypts the keys locally and returns the decrypted keys back to Couchbase Server.

* `certPath`: The absolute path on all servers to the certificate to use when authenticating with the KMS.  
The certificate file must be in PEM format.
* `caSelection` (optional): Where to look for certificates when verifying the identity of the KMS.
Can be one of the following values:

** `"useSysAndCbCa"` (default): Use the certificates in both the operating system's and Couchbase Server's trust stores.
** `"useSysCa"`: Use the certificates in the operating system's trust store.
** `"useCbCa"`: Use the certificates in Couchbase Server's trust store.
** `"skipServerCertVerification"`: Skip verification of the KMS.
+
CAUTION: Not verifying the identity of the KMS is insecure. 

* `encryptWith` (optional): controls how the passphrase for the private key is encrypted for local storage. 
The two options are:

** `"nodeSecretManager"` (default): Couchbase Server encrypts the passphrase using the database's master password.
** `"encryptionKey"`: Use a KEK-enabled encryption key to encrypt the passphrase.
If you choose this option, you must also supply the `encryptWithKeyId` parameter.

* `activeKey.kmipId`: The ID of the encryption key stored in the KMS.
The format of this value depends on the KMS.
It's often in the form of a UUID or a friendly name.

* `encryptWithKeyId` (integer): The `id` attribute of the encryption key Couchbase Server uses to encrypt the private key's passphrase when storing it locally. 
See <<#list-keys>> to learn how to get an encryption key's `id`.
Required if you set `encryptWith` to `encryptionKey`. 

NOTE: Couchbase Server does not verify the information you give it during key creation. 
It only attempts to connect to the KMS when you assign the key to encrypt something. 
--

Couchbase Server::
+
--

When having Couchbase Server manage the key, the `data` object has the following schema:

[source,json]
----
    "data": {
      "autoRotation": <true|false>,
      "encryptWith": "<key-or-secrets-manager>",
      "encryptWithKeyId": <KEY_ID>
      "canBeCached": <true|false>
      "nextRotationTime": "<iso-8601-date",
      "rotationIntervalInDays": <days>
    }
----

.Fields

* `autoRotation` (Boolean, optional):  Controls whether Couchbase Server automatically rotates the key.
See xref:learn:security/native-encryption-at-rest-overview.adoc#rotation-expiration[Encryption Key Rotation and Expiration] for more information about key rotation.
Defaults to `true`, which means that the key will be automatically rotated. 
In this case, you must supply both the `nextRotationTime` and `rotationIntervalInDays` fields as well.
* `encryptWith` (optional): How Couchbase Server should encrypt this key for storage.
The two options are:

** `"nodeSecretManager"`: (default): Couchbase Server encrypts the key using the database's master password.
** `"encryptionKey"`: Couchbase Server uses a KEK-enabled encryption key to encrypt the key.
If you choose this option, you must also supply the `encryptWithKeyId` field.

* `encryptWithKeyId` (integer): The `id` attribute of an existing encryption-at-rest key to use to encrypt this key. 
The key you select must have `KEK-encryption` in its `usage` list.
* `canBeCached` (Boolean, optional): Determines if Couchbase Server is allowed to cache the decrypted key in memory. 
Setting this to `true` (the default) makes using the key more efficient because Couchbase Server does not have to decrypt it each time it needs to use it. 
Disabling caching by setting this value to `false` slightly increases the overhead of using encryption at rest but helps reduce the chance of in-memory key exposure attacks. 
* `nextRotationTime`: A date and time string in https://en.wikipedia.org/wiki/ISO_8601[ISO 8601 format^] that sets when Couchbase Server must rotate this key.   
This value is required if you set `autoRotation` to `true`.
* `rotationIntervalInDays` (integer): How often, in days, Couchbase Server rotates this key. 
This field is required if you set `autoRotation` to `true`.
--
====

[#create-privs]
=== Required Privileges

You must have at least on one of the following roles:

* xref:learn:security/roles.adoc#admin[Full Admin]
* xref:learn:security/roles.adoc#security_admin[Security Admin]


=== Responses

`200 OK`::
Returns a JSON message containing the new encryption-at-rest key. 
See <<#create-examples>> for examples of the returned JSON.

`400 Bad Request`::
Returned when errors occur, such as leaving out a required setting or invalid JSON. 
Also returns a descriptive JSON message.
For example, if you set `encryptWith` to `encryptionKey` but do not set `encryptWithKeyID`, you receive this message:

+
[source,json]
----
{
  "errors": {
    "data": {
      "encryptWith": "encryptWithKeyId must be set when 'encryptionKey' is used"
    }
  }
}
----

`403 Forbidden`::
Returned if you do not have the proper roles to call this API.
See <<#create-privs>>.

`404 Object Not Found`::
Returned if you specified a `encryptWithKeyId` field or a `KEY_ID` path parameter which does not match the `id` field of an existing encryption-at-rest key.


[#create-examples]
=== Examples

[#create-managed-example]
.Create a Couchbase Server Managed Key

The following example creates an auto-generated key (one managed by Couchbase Server). 
The only data it can encrypt is the travel sample bucket.
It can also encrypt the configuration and logs.

[source,bash]
----
curl -v -u Administrator:password \
  -X POST \
  http://127.0.0.1:8091/settings/encryptionKeys \
  --data-binary @- <<EOF | jq
{
  "name": "Example Auto-Generated Key",
  "type": "auto-generated-aes-key-256",
  "usage": [
    "bucket-encryption-travel-sample", "config-encryption", "log-encryption" 
  ],
  "data": {
    "rotationIntervalInDays": 90,
    "nextRotationTime": "2025-07-31T19:27:19Z"
  }
}
EOF
----

The output of running the previous command in the previous example looks like this:

[source,json]
----
{
  "data": {
    "keys": [
      {
        "id": "fad3d3ae-9195-4779-994e-69266c9360c9",
        "active": true,
        "creationDateTime": "2025-05-02T19:34:07Z",
        "keyMaterial": "******"
      }
    ],
    "encryptWith": "nodeSecretManager",
    "canBeCached": true,
    "nextRotationTime": "2025-07-31T19:27:19Z",
    "autoRotation": true,
    "rotationIntervalInDays": 90
  },
  "id": 13,
  "name": "Example Auto-Generated Key",
  "type": "auto-generated-aes-key-256",
  "usage": [
    "bucket-encryption-travel-sample",
    "config-encryption",
    "log-encryption"
  ],
  "creationDateTime": "2025-05-02T19:34:07Z"
}
----


.Create AWS KMS Managed Key

The following example creates a key managed by the AWS KMS.
It relies on IAM roles configured outside of Couchbase Server to authenticate with AWS KMS.
The key it creates can only encrypt other encryption-at-rest keys.
This is the best practice when using AWS KMS to store encryption-at-rest keys.
See xref:learn:security/native-encryption-at-rest-overview.adoc#aws-kms-caution[this caution] for more information.

[source,bash]
----
curl -sS -u Administrator:password \
  -X POST \
  http://127.0.0.1:8091/settings/encryptionKeys \
  --data-binary @- <<EOF | jq
{
  "name": "Example AWS key",
  "type": "awskms-aes-key-256",
  "usage": [
    "KEK-encryption"
  ],
  "data": {
    "keyARN": "arn:aws:kms:us-east-1:000000000000:key/aaaaaaaa-bbbb-dddd-eeee-ffffffffffff",
    "region": "us-east-1",
    "useIMDS": true
  }
}
EOF
----

The following example shows the result of running the command from the previous example:

[source,json]
----
{
  "data": {
    "profile": "",
    "configFile": "",
    "useIMDS": true,
    "region": "us-east-1",
    "keyARN": "arn:aws:kms:us-east-1:000000000000:key/aaaaaaaa-bbbb-dddd-eeee-ffffffffffff",
    "credentialsFile": "",
    "storedKeyIds": [
      {
        "id": "dd01645e-e59c-462d-8e08-4cc8c3b1a53b",
        "creationDateTime": "2025-05-05T15:10:02Z"
      }
    ]
  },
  "id": 14,
  "name": "Example AWS key",
  "type": "awskms-aes-key-256",
  "usage": [
    "KEK-encryption"
  ],
  "creationDateTime": "2025-05-05T15:10:02Z"
}
----

.Create a KMIP-compatible KMS Managed Key

[source,bash]
----
curl -v -u Administrator:password  \
     -X POST   http://127.0.0.1:8091/settings/encryptionKeys   \
       --data-binary @- <<EOF | jq
{
  "name": "Example KMIP key",
  "type": "kmip-aes-key-256",
  "usage": [
    "KEK-encryption"
  ],
  "data": {
    "port": 5696,
    "host": "https://kms.example.com",
    "reqTimeoutMs": 1000,
    "keyPath": "/scripts/certs/cb_key.pem",
    "encryptionApproach": "useEncryptDecrypt",
    "certPath": "/scripts/certs/cb_cert.pem",
    "keyPassphrase": "Password1234",
    "caSelection": "useSysAndCbCa",
    "encryptWith": "nodeSecretManager",
    "activeKey": {
      "kmipId": "0788edb1-1418-4225-903b-bc1f9f59aa4d"
    }
  }
}
EOF
----

The following example shows the output from running the previous example.

[source,json]
----
{
  "data": {
    "port": 5696,
    "host": "https://kms.example.com",
    "reqTimeoutMs": 1000,
    "keyPath": "/scripts/certs/cb_key.pem",
    "keyPassphrase": "******",
    "encryptionApproach": "useEncryptDecrypt",
    "certPath": "/scripts/certs/cb_cert.pem",
    "caSelection": "useSysAndCbCa",
    "encryptWith": "nodeSecretManager",
    "historicalKeys": [],
    "activeKey": {
      "id": "52ab2528-ab90-4d6e-a523-cf42c2d64b50",
      "kmipId": "0788edb1-1418-4225-903b-bc1f9f59aa4d",
      "creationDateTime": "2025-05-06T12:58:04Z"
    }
  },
  "id": 15,
  "name": "Example KMIP key",
  "type": "kmip-aes-key-256",
  "usage": [
    "KEK-encryption"
  ],
  "creationDateTime": "2025-05-06T12:58:04Z"
}
----


.Update the Couchbase Server Managed Key

The following example updates the key created in <<#create-managed-example>>.
The update makes the key able to encrypt any bucket and sets the next rotation time to a later date. 

[source,bash]
----
curl -v -u Administrator:password \
  -X PUT \
  http://127.0.0.1:8091/settings/encryptionKeys/13 \
  --data-binary @- <<EOF | jq
{
  "name": "Example Auto-Generated Key2",
  "type": "auto-generated-aes-key-256",
  "usage": [
    "bucket-encryption", "config-encryption", "log-encryption" 
  ],
  "data": {
    "rotationIntervalInDays": 90,
    "nextRotationTime": "2025-08-30T00:00:01Z"
  }
}
EOF
----

The output from the previous example looks like this:

[source,json]
----
{
  "data": {
    "keys": [
      {
        "id": "fad3d3ae-9195-4779-994e-69266c9360c9",
        "active": true,
        "creationDateTime": "2025-05-02T19:34:07Z",
        "keyMaterial": "******"
      }
    ],
    "encryptWith": "nodeSecretManager",
    "canBeCached": true,
    "nextRotationTime": "2025-07-31T19:27:19Z",
    "autoRotation": true,
    "rotationIntervalInDays": 90
  },
  "id": 13,
  "name": "Example Auto-Generated Key",
  "type": "auto-generated-aes-key-256",
  "usage": [
    "bucket-encryption",
    "config-encryption",
    "log-encryption"
  ],
  "creationDateTime": "2025-05-02T19:34:07Z"
}
----

[#delete-key]
== Delete an Encryption-at-Rest Key

You can delete an encryption-at-rest key as long as Couchbase Server is not using it to encrypt data or another encryption key.
See XXX for more formation about deleting keys.

.Delete an Encryption Key
----
DELETE /settings/encryptionKeys/{KEY_ID}
----

.Path Parameters
`KEY_ID` (integer)::
The `id` attribute of the key you want to delete. 


=== curl Syntax
[source,bash.]
----
curl -sS -u $USER:$PASSWORD   -X DELETE \
     http://{HOST}:{PORT}/settings/encryptionKeys/<KEY_ID>
----

.Path Parameters
:priv-link: del-privs
include::partial$user-pw-host-port-params.adoc[]

`KEY_ID` (integer)::
 The `id` attribute of the key you want to delete.


[[del-privs]]
=== Required Privileges

You must have at least on one of the following roles:

* xref:learn:security/roles.adoc#admin[Full Admin]
* xref:learn:security/roles.adoc#security_admin[Security Admin]

=== Responses

`200 OK`::
Returned when Couchbase Server was able to delete the key. 
A successful call does not return any additional message.

`400 Bad Request`::
Returned when the key you tried to delete is in use.
In addition, you receive a JSON message that explains why Couchbase Server cannot delete the key.
For example:

+
[source,json]
----
{
  "errors": {
    "_": "Can't be removed because this key is configured to encrypt configuration, logs, 
          audit, bucket \"beer-sample\", keys \"encrypted-with-kek\", \"kmip-key\""
  }
}
----

`404 Object Not Found`::
Returned if the key you tried to delete does not exist.

=== Examples

The following example deletes the Couchbase Server managed key named Example Auto-Generated Key shown in earlier examples.

[source,bash]
----
 curl -v -u Administrator:password -X DELETE \
      http://127.0.0.1:8091/settings/encryptionKeys/13 | jq
----


