= Manage Encryption-at-Rest Keys
:description: pass:q[You must create encryption-at-rest keys before you can have Couchbase Server encrypt data as it saves it to disk.]
:page-edition: Enterprise Edition
:page-topic-type: reference
:tabs:
:page-toclevels: 3

[abstract]
{description}

== Description

These APIs let you list, create, change, test, and delete encryption-at-rest keys.
See xref:learn:security/native-encryption-at-rest-overview.adoc[] for more information about encryption at rest.

== HTTP Methods 

This API endpoint supports the following methods:

* <<#list-keys>>
* <<#create-key>>
* <<#test-key>>
* <<#test-key-changes>>
* <<#delete-key>>

[#list-keys]
== List Encryption-at-Rest Keys

List one or all encryption-at-rest keys defined in the cluster.

.List All Keys
----
GET /settings/encryptionKeys/
----

.Get details of a specific key
----
GET /settings/encryptionKeys/{KEY_ID}
----

.Path Parameters
`KEY_ID` (integer)::
The `id` attribute of the key you want to view. 
See the <<#gey-keys-example,example>> for an explanation of getting this value.

=== curl Syntax

[source,bash]
----
curl -sS -u $USER:$PASSWORD \
     -X GET 'http[s]://<hostname>:{PORT}/settings/encryptionKeys/[{KEY_ID}]' 
----

.Path Parameters
:priv-link: get-privs
include::partial$user-pw-host-port-params.adoc[]

`KEY_ID` (optional)::
The id of the single encryption-at-rest key whose details you want to retrieve.


[[get-privs]]
=== Required Privileges

The role you need to view specific keys depends on their use.

The following roles let you view all keys, including keys that can encrypt other keys (KEKs), audit, logs, and configuration data:

* xref:learn:security/roles.adoc#admin[Full Admin]
* xref:learn:security/roles.adoc#read-only-admin[Read-Only Admin]
* xref:learn:security/roles.adoc#security_admin[Security Admin]

The following roles let you view keys that can encrypt data in buckets. 
Some of the role's ability to read keys depends on whether you have rights to access the bucket.
For example, the Data Reader role only grants you access to keys that can encrypt data in buckets you have read access to.

* xref:learn:security/roles.adoc#admin[Full Admin]
* xref:learn:security/roles.adoc#read-only-admin[Read-Only Admin]
* xref:learn:security/roles.adoc#security-admin[Security Admin]
* xref:learn:security/roles.adoc#local-user-security-admin[Local User Admin]
* xref:learn:security/roles.adoc#external-user-security-admin[External User Admin]
* xref:learn:security/roles.adoc#cluster-admin[Cluster Admin]
* xref:learn:security/roles.adoc#eventing-full-admin[Eventing Full Admin]
* xref:learn:security/roles.adoc#admin[Backup Full Admin]
* xref:learn:security/roles.adoc#backup-full-admin[Bucket Admin]
* xref:learn:security/roles.adoc#application-access[Application Access]
* xref:learn:security/roles.adoc#views-admin[Views Admin]
* xref:learn:security/roles.adoc#xdcr-admin[XDCR Admin]
* xref:learn:security/roles.adoc#data-reader[Data Reader]
* xref:learn:security/roles.adoc#data-writer[Data Writer]
* xref:learn:security/roles.adoc#data-dcp-reader[Data DCP Reader]
* xref:learn:security/roles.adoc#data-backup-and-restore[Data Backup & Restore]
* xref:learn:security/roles.adoc#data-monitor[Data Monitor]
* xref:learn:security/roles.adoc#search-admin[Search Admin]
* xref:learn:security/roles.adoc#search-reader[Search Reader]
* xref:learn:security/roles.adoc#query-select][Query Select]
* xref:learn:security/roles.adoc#query-update[Query Update]
* xref:learn:security/roles.adoc#query-insert[Query Insert]
* xref:learn:security/roles.adoc#query-delete[Query Delete]
* xref:learn:security/roles.adoc#query-manage-index[Query Manage Index]
* xref:learn:security/roles.adoc#query-list-index[Query List Index]
* xref:learn:security/roles.adoc#query-system-catalog[Query System Catalog]
* xref:learn:security/roles.adoc#query-curl-access[Query CURL Access]
* xref:learn:security/roles.adoc#xdcr-inbound[XDCR Inbound]
* xref:learn:security/roles.adoc#sync-gateway[Sync Gateway]

=== Responses

`200 OK`::
Returns the encryption-at-rest keys or a particular key if you specified the `KEY_ID` path parameter. 
See examples for an example of the keys.

+
NOTE: Call returns `200 OK` and an empty JSON message if user does not have permission to view keys. 

`404 Object Not Found`::
Returned if you specified a `KEY_ID` path parameter which does not match the ID of an encryption-at-rest key.

[#gey-keys-example]
=== Examples

The following example gets all of the encryption-at-rest keys defined in the system.

[source,bash]
----
 curl -sS -u Administrator:password \
      -X GET 'http://127.0.0.1:8091/settings/encryptionKeys/' | jq
----

An example of running the previous command:

[source,json]
----
[
  {
    "data": {
      "keys": [
        {
          "id": "b3dd8518-e747-4a64-ad6b-db9c5d306a6c",
          "active": true,
          "creationDateTime": "2025-04-23T16:22:39Z",
          "keyMaterial": "******"
        }
      ],
      "encryptionApproach": "nodeSecretManager",
      "canBeCached": true,
      "autoRotation": false
    },
    "id": 7,
    "name": "data-one-buckey-key",
    "type": "cb-server-managed-aes-key-256",
    "usage": [
      "bucket-encryption-beer-sample",
      "bucket-encryption-test"
    ],
    "creationDateTime": "2025-04-23T16:22:39Z"
  },
  {
    "data": {
      "port": 5696,
      "host": "https://kms.example.com",
      "reqTimeoutMs": 1000,
      "keyPath": "/scripts/certs/cb_key.pem",
      "keyPassphrase": "******",
      "encryptionApproach": "useGet",
      "certPath": "/scripts/certs/cb_cert.pem",
      "caSelection": "useSysAndCbCa",
      "encryptionApproach": "nodeSecretManager",
      "historicalKeys": [],
      "activeKey": {
        "id": "0788edb1-1418-4225-903b-bc1f9f59aa4d",
        "kmipId": "550e8400-e29b-41d4-a716-446655440000",
        "creationDateTime": "2025-04-23T14:44:20Z"
      },
      "encryptionApproachKeyId": -1
    },
    "id": 2,
    "name": "kmip-key",
    "type": "kmip-aes-key-256",
    "usage": [
      "KEK-encryption",
      "bucket-encryption",
      "config-encryption",
      "log-encryption",
      "audit-encryption"
    ],
    "creationDateTime": "2025-04-23T14:44:20Z"
  },
  {
    "data": {
      "profile": "",
      "configFile": "",
      "useIMDS": true,
      "region": "us-east-1",
      "keyARN": "arn:aws:kms:us-east-1:000000000000:key/aaaaaaaa-bbbb-dddd-eeee-ffffffffffff",
      "credentialsFile": "",
      "storedKeyIds": [
        {
          "id": "c1cddf80-720e-47f0-adb7-641f5cb2ce22",
          "creationDateTime": "2025-04-23T16:00:22Z"
        }
      ]
    },
    "id": 6,
    "name": "Example AWS key",
    "type": "awskms-symmetric-key",
    "usage": [
      "KEK-encryption"
    ],
    "creationDateTime": "2025-04-23T16:00:22Z"
  }
]
----


All keys have the following fields:

* `id`: the integer identifying the encryption key
* `name`: the friendly name assigned by the administrator who created the key.
* `usage`: what the key is allowed to encrypt.
* `type`: which key management system (KMS) manages the key.
+
NOTE: The `type` also contains the encryption algorithm used for the encryption-at-rest key. 
Currently, this is always `aes-key-256`.

The `data` object defines the KMS-specific details for each encryption key.
You'll notice different fields for each type of key:

Keys managed by Couchbase Server::

* The `keys` list contains the current and expired encryption keys. 
The other key types have their contents stored within the remote KMS.
* The `autorotation` field indicates whether Couchbase Server automatically rotates the key.
When set to `true``, additional fields, such as  `data.rotationIntervalInDays` and `nextRotationTime` show details of the key's rotation.
* 

Keys managed by a KMIP-compatible KMS::

* The fields configure the authentication with the KMS.   

Keys Managed by AWS::

* `keyANN` is the identity of the key in the AWS KMS.
* The `profile`, `credentialsFile`, and `configFile` hold the credentials Couchbase Server uses to authenticate with AWS KMS. 
These values are empty when Couchbase Server uses IAM to authenticate with AWS instead of stored credentials.

[[create-key]]
== Create or Update an Encryption-at-Rest Key

You can create or update an encryption-at-rest-key key using the REST API.

.Create an Encryption Key
----
POST /settings/encryptionKeys/
----

.Update a Key
----
PUT /settings/encryptionKeys/{KEY_ID}
----

.Path Parameters
`KEY_ID` (integer)::
The `id` attribute of the key you want to update. 


=== curl Syntax

.Create an Encryption at Rest Key
[source,bash]
----
curl -sS -u $USER:$PASSWORD \
  -X POST http://{HOST}:{PORT}/settings/encryptionKeys \
  --data-binary @- <<EOF | jq
{
  "name": "<keyname>",
  "usage": [
    "<usage>"[."<usage>"...]
  ],
  "type": "<KMS>",
  "data": {
    <KMS-specific-fields>
  }
}
EOF
----

.Update an Encryption at Rest Key
[source,bash]
----
curl -sS -u $USER:$PASSWORD \
  -X PUT http://{HOST}:{PORT}/settings/encryptionKeys/{KEY_ID} \
  --data-binary @- <<EOF | jq
{
  "name": "<keyname>",
  "usage": [
    "<usage>"[."<usage>"...]
  ],
  "type": "<KMS>",
  "data": {
    <KMS-specific-fields>
  }
}
EOF
----

NOTE: Updating a key has the same required fields as the creating a new key. 
For example, you must supply the `name` field, even if you want the key's name to remain the same.
Couchbase Server sets any value you do not supply in the update call to the default value (if any) or is left empty, overwriting any existing value.


:priv-link: create-privs
.Path Parameters
include::partial$user-pw-host-port-params.adoc[]

`KEY_ID` (integer)::
 The `id` attribute of the key you want to update.

.Fields
:field-use: create 
include::partial$encryption-at-rest-post-put-fields.adoc[]

[#create-privs]
=== Required Privileges

The role you need to create or update keys depends on what the key you're creating or updating can encrypt:

include::rest-api:partial$encryption-at-rest-key-write-roles.adoc[]

=== Responses

`200 OK`::
Returns a JSON message containing the new encryption-at-rest key. 
See <<#create-examples>> for examples of the returned JSON.

`400 Bad Request`::
Returned when errors occur, such as leaving out a required setting or invalid JSON. 
Also returns a descriptive JSON message.
For example, if you set `encryptionApproach` to `encryptionKey` but do not set `encryptionApproachKeyID`, you receive this message:

+
[source,json]
----
{
  "errors": {
    "data": {
      "encryptionApproach": "encryptionApproachKeyId must be set when 'encryptionKey' is used"
    }
  }
}
----

`403 Forbidden`::
Returned if you do not have the proper roles to call this API.
See <<#create-privs>>.

`404 Object Not Found`::
Returned if you specified a `encryptionApproachKeyId` field or a `KEY_ID` path parameter which does not match the `id` field of an existing encryption-at-rest key.


[#create-examples]
=== Examples

[#create-managed-example]
.Create a Couchbase Server Managed Key

The following example creates an auto-generated key (one managed by Couchbase Server). 
The only data it can encrypt is the travel sample bucket.
It can also encrypt the configuration and logs.

include::example$encryption-at-rest/create-auto-generated-key.adoc[]

The output of running the previous command in the previous example looks like this:

include::example$encryption-at-rest/create-auto-generated-key-response.adoc[]


.Create AWS KMS Managed Key

The following example creates a key managed by the AWS KMS.
It relies on IAM roles configured outside of Couchbase Server to authenticate with AWS KMS.
The key it creates can only encrypt other encryption-at-rest keys.
This is the best practice when using AWS KMS to store encryption-at-rest keys.
See xref:learn:security/native-encryption-at-rest-overview.adoc#aws-kms-caution[this caution] for more information.

[source,bash]
----
curl -sS -u Administrator:password \
  -X POST \
  http://127.0.0.1:8091/settings/encryptionKeys \
  --data-binary @- <<EOF | jq
{
  "name": "Example AWS key",
  "type": "awskms-symmetric-key",
  "usage": [
    "KEK-encryption"
  ],
  "data": {
    "keyARN": "arn:aws:kms:us-east-1:000000000000:key/aaaaaaaa-bbbb-dddd-eeee-ffffffffffff",
    "region": "us-east-1",
    "useIMDS": true
  }
}
EOF
----

The following example shows the result of running the command from the previous example:

[source,json]
----
{
  "data": {
    "profile": "",
    "configFile": "",
    "useIMDS": true,
    "region": "us-east-1",
    "keyARN": "arn:aws:kms:us-east-1:000000000000:key/aaaaaaaa-bbbb-dddd-eeee-ffffffffffff",
    "credentialsFile": "",
    "storedKeyIds": [
      {
        "id": "dd01645e-e59c-462d-8e08-4cc8c3b1a53b",
        "creationDateTime": "2025-05-05T15:10:02Z"
      }
    ]
  },
  "id": 14,
  "name": "Example AWS key",
  "type": "awskms-symmetric-key",
  "usage": [
    "KEK-encryption"
  ],
  "creationDateTime": "2025-05-05T15:10:02Z"
}
----

[#create-kmip-example]
.Create a KMIP-compatible KMS Managed Key

[source,bash]
----
curl -sS -u Administrator:password  \
     -X POST   http://127.0.0.1:8091/settings/encryptionKeys   \
       --data-binary @- <<EOF | jq
{
  "name": "Example KMIP Key",
  "type": "kmip-aes-key-256",
  "usage": [
    "KEK-encryption"
  ],
"data": {
      "port": 5696,
      "host": "https://kms.example.com",
      "reqTimeoutMs": 1000,
      "keyPath": "/scripts/certs/cb_key.pem",
      "keyPassphrase": "Passwprd1234",
      "encryptionApproach": "useGet",
      "certPath": "/scripts/certs/cb_cert.pem",
      "caSelection": "skipServerCertVerification",
      "encryptWith": "nodeSecretManager",
      "activeKey": {
        "kmipId": "0788edb1-1418-4225-903b-bc1f9f59aa4d"
    }
  }
}
EOF
----

The following example shows the output from running the previous example.

[source,json]
----
{
  "data": {
    "port": 5696,
    "host": "https://kms.example.com",
    "reqTimeoutMs": 1000,
    "keyPath": "/scripts/certs/cb_key.pem",
    "keyPassphrase": "******",
    "encryptionApproach": "useGet",
    "certPath": "/scripts/certs/cb_cert.pem",
    "caSelection": "skipServerCertVerification",
    "encryptWith": "nodeSecretManager",
    "historicalKeys": [],
    "activeKey": {
      "id": "11c9195b-0d20-41c4-9f3c-550cb5d2c5f3",
      "kmipId": "0788edb1-1418-4225-903b-bc1f9f59aa4d",
      "creationDateTime": "2025-08-05T14:32:21Z"
    }
  },
  "id": 1,
  "name": "Example KMIP Key",
  "type": "kmip-aes-key-256",
  "usage": [
    "KEK-encryption"
  ],
  "creationDateTime": "2025-08-05T14:32:21Z"
}
----


.Update the Couchbase Server Managed Key

The following example updates the key created in <<#create-managed-example>>.
The update makes the key able to encrypt any bucket and sets the next rotation time to a later date. 

[source,bash]
----
curl -sS -u Administrator:password \
  -X PUT \
  http://127.0.0.1:8091/settings/encryptionKeys/13 \
  --data-binary @- <<EOF | jq
{
  "name": "Example Auto-Generated Key2",
  "type": "cb-server-managed-aes-key-256",
  "usage": [
    "bucket-encryption", "config-encryption", "log-encryption" 
  ],
  "data": {
    "rotationIntervalInDays": 90,
    "nextRotationTime": "2025-08-30T00:00:01Z"
  }
}
EOF
----

The output from the previous example looks like this:

[source,json]
----
{
  "data": {
    "keys": [
      {
        "id": "fad3d3ae-9195-4779-994e-69266c9360c9",
        "active": true,
        "creationDateTime": "2025-05-02T19:34:07Z",
        "keyMaterial": "******"
      }
    ],
    "encryptionApproach": "nodeSecretManager",
    "canBeCached": true,
    "nextRotationTime": "2025-07-31T19:27:19Z",
    "autoRotation": true,
    "rotationIntervalInDays": 90
  },
  "id": 13,
  "name": "Example Auto-Generated Key",
  "type": "cb-server-managed-aes-key-256",
  "usage": [
    "bucket-encryption",
    "config-encryption",
    "log-encryption"
  ],
  "creationDateTime": "2025-05-02T19:34:07Z"
}
----


[#test-key]
== Test Existing Encryption-at-Rest Key

Test an encryption-at-rest keys defined in the cluster.
Couchbase Server does not verify that a key is valid when creating it.
You can use this call to verify that the key is valid and can encrypt data before you assign it to encrypt data or another key.


.Test a Key
----
POST /settings/encryptionKeys/{KEY_ID}/test
----

.Path Parameters
`KEY_ID` (integer)::
The `id` attribute of the key you want to test. 
See the <<#gey-keys-example,example>> for an explanation of getting this value.

=== curl Syntax

[source,bash]
----
curl -sS -u $USER:$PASSWORD \
     -X POST 'http[s]://<hostname>:{PORT}/settings/encryptionKeys/{KEY_ID}/test' 
----

.Path Parameters
:priv-link: test-privs
include::partial$user-pw-host-port-params.adoc[]

`KEY_ID`::
The `id` attribute of the encryption-at-rest key that you want to test.

[#test-privs]
=== Required Privileges

You must have at least one of the following roles:

* xref:learn:security/roles.adoc#security_admin_external[External User Admin]
* xref:learn:security/roles.adoc#admin[Full Admin]
* xref:learn:security/roles.adoc#security_admin_local[Local User Admin]
* xref:learn:security/roles.adoc#read-only-admin[Read-Only Admin]
* xref:learn:security/roles.adoc#security_admin[Security Admin]

=== Responses

`200 OK`::
If Couchbase Server was able to use the key to encrypt and decrypt some sample data, it just returns this return code and nothing else.

`404 Object Not Found`::
Returned if you specified a `KEY_ID` path parameter which does not match the ID of an encryption-at-rest key.

`400 Bad Request`::
Returned if the key you tried to test is misconfigured or cannot access the remote KMS.
You also receive an error message in JSON format describing the problem.  


[#gey-keys-example]
=== Examples

The following example tests the encryption-at-rest key with `id` 2.

[source,bash]
----
 curl -v -u Administrator:password \
      -X POST 'http://127.0.0.1:8091/settings/encryptionKeys/2/test'
----

If successful, the previous example just returns the `200 OK` status code and nothing else.
The verbose output of the `curl` command looks like this (notice the `HTTP/1.1 200 OK` indicating the successful call):

[source,console]
----
*   Trying 127.0.0.1:8091...
* Connected to 127.0.0.1 (127.0.0.1) port 8091
* Server auth using Basic with user 'Administrator'
> POST /settings/encryptionKeys/2/test HTTP/1.1
> Host: 127.0.0.1:8091
> Authorization: Basic QWRtaW5pc3RyYXRvcjpwYXNzd29yZA==
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Cache-Control: no-cache,no-store,must-revalidate
< Content-Length: 0
< Date: Tue, 05 Aug 2025 14:42:23 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Pragma: no-cache
< Server: Couchbase Server
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Permitted-Cross-Domain-Policies: none
< X-XSS-Protection: 1; mode=block
< 
* Connection #0 to host 127.0.0.1 left intact
----

[#test-key-changes]
== Test Possible Changes to an Encryption-at-Rest Key

You can test changes you want to make to an encryption-at-rest key managed by a remote KMS before you actually make them.
Calling this REST API method does not actually make the changes to the key. 
It just tests an altered copy of the key to determine if it able to encrypt and decrypt data.
The call to this API method is the same as altering the key using the xref:rest-api:security/encryption-at-rest/manage-encryption-keys.adoc#create-key[Create or Update an Encryption-at-Rest Key] API method, except it adds a `/test` suffix to the URL.

NOTE: This endpoint only works for AWS and KMIP keys.
It does not work for Couchbase Server managed keys.

.Test Possible CHanges to a Key
----
PUT /settings/encryptionKeys/{KEY_ID}/test
----

.Path Parameters
`KEY_ID` (integer)::
The `id` attribute of the key you want to test. 
See the <<#gey-keys-example,example>> for an explanation of getting this value.

=== curl Syntax

[source,bash]
----
curl -sS -u $USER:$PASSWORD \
     -X PUT 'http[s]://<hostname>:{PORT}/settings/encryptionKeys/{KEY_ID}/test' 
{
  "name": "<keyname>",
  "usage": [
    "<usage>"[."<usage>"...]
  ],
  "type": "<KMS>",
  "data": {
    <KMS-specific-fields>
  }
}
EOF
----

.Path Parameters
:priv-link: test-changes-privs
include::partial$user-pw-host-port-params.adoc[]

`KEY_ID`::
The id of the single encryption-at-rest key that you want to test.

.Fields
// Variable to hide the CB managed key fields because they do not apply for this APi call
:field-use: test  
include::partial$encryption-at-rest-post-put-fields.adoc[]

[[test-changes-privs]]
=== Required Privileges

The role you need to test changes to a key depends on what the key you're testing can encrypt:

include::rest-api:partial$encryption-at-rest-key-write-roles.adoc[]

=== Responses

`200 OK`::
Couchbase Server returns this status and nothing else if it was able encrypt and decrypt some sample data with your changes applied to the key.

`404 Object Not Found`::
Returned if you specified a `KEY_ID` path parameter which does not match the ID of an encryption-at-rest key.

`400 Bad Request`::
Returned if the key you tried to test is misconfigured or cannot access the remote KMS.
Couchbase Server also returns an error message in JSON format describing the problem.
For example, the following error message occurs when Couchbase Server cannot unlock the key file specified in the `keyPath` field:

+
[source,json]
----
{
  "errors": {
    "_": "Encryption key test failed on node1.:8091, node2.:8091, node3.:8091: encryption failed: incorrect password for private key: full error: x509KeyPair: parsePrivateKey returned err: parsePrivateKey: failed to parse private key. Error: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:95 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @2; pkcs8: incorrect password; x509: failed to parse EC private key: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:95 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @2"
  }
}
----

[#test-changes-example]
=== Example

The following example tests changing the hostname of the KMIP key created in <<#create-kmip-example>>.

[source,bash]
----
 curl -v -u Administrator:password  \
     -X PUT   http://127.0.0.1:8091/settings/encryptionKeys/1/test \
       --data-binary @- <<EOF | jq
{
  "name": "Example KMIP Key",
  "type": "kmip-aes-key-256",
  "usage": [
    "KEK-encryption"
  ],
"data": {
      "port": 5696,
      "host": "https://kms2.example.com",
      "keyPath": "/scripts/certs/cb_key.pem",
      "certPath": "/scripts/certs/cb_cert.pem",
      "activeKey": {
        "kmipId": "0788edb1-1418-4225-903b-bc1f9f59aa4d"
      }
  }
}
EOF
----

The previous example returns the code `200 OK` if the test was successful with no further output. 


[#delete-key]
== Delete an Encryption-at-Rest Key

You can delete an encryption-at-rest key as long as Couchbase Server is not using it to encrypt data or another encryption key.
// See  for more formation about deleting keys.

.Delete an Encryption Key
----
DELETE /settings/encryptionKeys/{KEY_ID}
----

.Path Parameters
`KEY_ID` (integer)::
The `id` attribute of the key you want to delete. 


=== curl Syntax
[source,bash]
----
curl -sS -u $USER:$PASSWORD   -X DELETE \
     'http://{HOST}:{PORT}/settings/encryptionKeys/{KEY_ID}'
----

.Path Parameters
:priv-link: del-privs
include::partial$user-pw-host-port-params.adoc[]

`KEY_ID` (integer)::
 The `id` attribute of the key you want to delete.


[[del-privs]]
=== Required Privileges

The role you need to delete a key depends on what the key you're deleting can encrypt:

include::rest-api:partial$encryption-at-rest-key-write-roles.adoc[]

=== Responses

`200 OK`::
Returned when Couchbase Server was able to delete the key. 
A successful call does not return any additional message.

`400 Bad Request`::
Returned when the key you tried to delete is in use.
In addition, you receive a JSON message that explains why Couchbase Server cannot delete the key.
For example:

+
[source,json]
----
{
  "errors": {
    "_": "Can't be removed because this key is configured to encrypt configuration, logs, 
          audit, bucket \"beer-sample\", keys \"encrypted-with-kek\", \"kmip-key\""
  }
}
----

`404 Object Not Found`::
Returned if the key you tried to delete does not exist.

=== Examples

The following example deletes the Couchbase Server managed key named Example Auto-Generated Key shown in earlier examples.

include::example$encryption-at-rest/manage-encryption-kets.adoc[tag=delete-key]




