= Bulk Operations
:description: How to perform bulk CRUD operations in Couchbase.
:page-pagination: prev 
:page-topic-type: guide
:tabs:
:github: Click the GitHub button icon:github[] to view this code in context.

include::partial$example-attributes.adoc[]

[abstract]
{description}

Performing bulk operations with Couchbase Server can be done in several ways, depending on the SDK or command line tool used to perform them.
In the following sections you will find some basic examples of how to perform bulk CRUD 
operations on Couchbase documents.

== Creating Multiple Documents

To create multiple documents in Couchbase perform a bulk `insert` operation.

[{tabs}]
====
pass:[.NET]::
+ 
--
. Create some structured JSON documents to insert.

. Initialize a list of `IMutationResult` tasks.

. Perform an `insert` operation on each document and store the result in the tasks list. 

. Wait for all the tasks to complete before accessing the results.

{kv-bulk-insert-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-users,indent=0]

include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-bulk-insert,indent=0]

----

{github}
--

Java::
+ 
--
. Create some structured JSON documents to insert.

. Using the `reactor.core.publisher.Flux` reactive library, call the `fromIterable()` method to perform multiple insert operations.

{kv-bulk-insert-example}

[source,java]
----
include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-users,indent=0]

include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-bulk-insert,indent=0]

----

NOTE: A `JsonDocument` class is used to supplement the example.

[source,java]
----
include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-bulk-class,indent=0]
----

{github}
--

Node.js::
+ 
--
. Create some structured JSON documents to insert.

. Perform an `insert` operation on each document and wait for all the promises to complete before accessing the results.

{kv-bulk-insert-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-bulk-hello-world.js[tags=kv-users;kv-bulk-insert,indent=0]
----

{github}
--

Python::
+ 
--
. Create a dictionary of structured JSON documents.

. Pass the dictionary to the `insert_multi()` function. This will insert all the documents in the database.

. A dictionary of `MutationResult` objects is returned.

CAUTION: `CBCollection.insert_multi` is a xref:python-sdk:project-docs:compatibility.adoc#interface-stability[volatile] API call that is still in flux and may likely be changed.

{kv-bulk-insert-example}

[source,python]
----
include::python-sdk:hello-world:example$kv_bulk_hello_world.py[tags=kv-users;kv-bulk-insert,indent=0]
----

{github}
--
====

== Reading Multiple Documents

To read multiple documents in Couchbase perform a bulk `get` operation.

[{tabs}]
====
cbc::
+ 
--
Use the `cbc cat` command to retrieve multiple documents by their IDs. 

{kv-bulk-get-example}

[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-bulk-get]
----

.Result
[source,console]
----
0                    CAS=0x16be2392ca2e0000, Flags=0x0, Size=904, Datatype=0x01(JSON)
{
  "name": "Keon Hoppe",
  "addresses": [
    {
      "type": "home",
      "address": "222 Sauer Neck",
      "city": "London",
      "country": "United Kingdom"
    },
  ],
  ...
}
1                    CAS=0x16be2392c9870000, Flags=0x0, Size=697, Datatype=0x01(JSON)
{
  "name": "Rigoberto Bernier",
  "addresses": [
    {
      "type": "home",
      "address": "0622 Adams Mills",
      "city": "Manchester",
      "country": "United Kingdom"
    }
  ],
  ...
}
----
--

.NET::
+ 
--
. Initialize a list of `IGetResult` tasks.

. Perform a `get` operation on each document and store the results in the tasks list.

. Wait for all the tasks to complete before accessing the results.

{kv-bulk-get-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-users,indent=0]

include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-bulk-get,indent=0]

----

{github}
--

Java::
+ 
--
Using the `reactor.core.publisher.Flux` reactive library, call the `fromIterable()` method to perform multiple `get` operations.

{kv-bulk-get-example}

[source,java]
----
include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-users,indent=0]

include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-bulk-get,indent=0]

----

{github}
--

Node.js::
+ 
--
Perform a `get` operation on each document and wait for all the promises to complete before accessing the results.

{kv-bulk-get-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-bulk-hello-world.js[tags=kv-users;kv-bulk-get,indent=0]
----

{github}
--

Python::
+ 
--
. Pass some document IDs to fetch to the `get_multi()` function. This will fetch the documents from the database.

. A dictionary of `GetResult` objects is returned.

CAUTION: `CBCollection.get_multi` is a xref:python-sdk:project-docs:compatibility.adoc#interface-stability[volatile] API call that is still in flux and may likely be changed.

{kv-bulk-get-example}

[source,python]
----
include::python-sdk:hello-world:example$kv_bulk_hello_world.py[tags=kv-users;kv-bulk-get,indent=0]
----

{github}
--
====

== Updating Multiple Documents

To update multiple documents in Couchbase perform a bulk `upsert` or `replace` operation.

[{tabs}]
====
pass:[.NET]::
+ 
--
. Add new data to update some existing JSON documents.

. Initialize a list of `IMutationResult` tasks.

. Perform an `upsert` or `replace` operation on each document and store the results in the tasks list.

. Wait for all the tasks to complete before accessing the results.

{kv-bulk-insert-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-users,indent=0]

include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-bulk-insert,indent=0]

----

{github}
--

Java::
+ 
--
. Add new data to update some existing JSON documents.

. Using the `reactor.core.publisher.Flux` reactive library, call the `fromIterable()` method to perform multiple `upsert` or `replace` operations.

{kv-bulk-update-example}

[source,java]
----
include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-users,indent=0]

include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-bulk-upsert,indent=0]

----

{github}
--

Node.js::
+ 
--
. Add new data to update some existing JSON documents.

. Perform an `upsert` operation on each document and wait for all the promises to complete before accessing the results.

{kv-bulk-update-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-bulk-hello-world.js[tags=kv-users;kv-bulk-upsert,indent=0]
----

{github}
--

Python::
+ 
--
. Add new data to update some existing JSON documents.

. Pass the new document data to `upsert_multi()`. This will update all the documents in the database.

. A dictionary of `MutationResult` objects is returned.

CAUTION: `CBCollection.upsert_multi` is a xref:python-sdk:project-docs:compatibility.adoc#interface-stability[volatile] API call that is still in flux and may likely be changed.

{kv-bulk-update-example}

[source,python]
----
include::python-sdk:hello-world:example$kv_bulk_hello_world.py[tags=kv-users;kv-bulk-upsert,indent=0]
----

{github}
--
====

== Deleting Multiple Documents

To delete multiple documents in Couchbase perform a bulk `remove` operation.

[{tabs}]
====
pass:[.NET]::
+ 
--
. Initialize a list of tasks.

. Perform a `remove` operation on each document and store the results in the tasks list.

. Wait for all the tasks to complete.

{kv-bulk-delete-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-users,indent=0]

include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-bulk-remove,indent=0]

----

{github}
--

Java::
+ 
--
Using the `reactor.core.publisher.Flux` reactive library, call the `fromIterable()` method to perform multiple `remove` operations.

{kv-bulk-delete-example}

[source,java]
----
include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-users,indent=0]

include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-bulk-remove,indent=0]

----

{github}
--

Node.js::
+ 
--
Perform a `remove` operation on each document and wait for all the promises to complete before accessing the results.

{kv-bulk-delete-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-bulk-hello-world.js[tags=kv-users;kv-bulk-remove,indent=0]
----

{github}
--

Python::
+ 
--
. Pass some document IDs to remove to the `remove_multi()` function. This will delete the documents from the database.

. A dictionary of `MutationResult` objects is returned.

CAUTION: `CBCollection.remove_multi` is a xref:python-sdk:project-docs:compatibility.adoc#interface-stability[volatile] API call that is still in flux and may likely be changed.

{kv-bulk-delete-example}

[source,python]
----
include::python-sdk:hello-world:example$kv_bulk_hello_world.py[tags=kv-users;kv-bulk-remove,indent=0]
----

{github}
--
====

== Related Links

Bulk Operations with SDKs:

* xref:c-sdk:howtos:concurrent-async-apis.adoc[C]
| xref:dotnet-sdk:howtos:concurrent-async-apis.adoc[.NET]
| xref:go-sdk:howtos:concurrent-async-apis.adoc[Go]
| xref:java-sdk:howtos:concurrent-async-apis.adoc[Java]
| xref:nodejs-sdk:howtos:concurrent-async-apis.adoc[Node.js]
| xref:php-sdk:howtos:concurrent-async-apis.adoc[PHP]
| xref:python-sdk:howtos:concurrent-async-apis.adoc[Python]
| xref:ruby-sdk:howtos:concurrent-async-apis.adoc[Ruby]
| xref:scala-sdk:howtos:concurrent-async-apis.adoc[Scala]
