= Connect to Couchbase
:description: How to connect to a Couchbase Cluster.
:page-topic-type: guide
:page-toclevels: 2
:tabs:
:github: Click the GitHub button icon:github[] to view this code in context.

include::partial$example-attributes.adoc[]

[abstract]
{description}

== Introduction

Connecting to Couchbase can be done in several ways.
This guide will take you through some of the most common methods used to access a Couchbase cluster with an SDK client or cli tool.

A Couchbase xref:learn:clusters-and-availability/clusters-and-availability.adoc[Cluster] is a combination of multiple server nodes, which can be accessed by users or applications with a xref:learn:security/usernames-and-passwords.adoc[username and password].
Each server node can also be its own cluster or join an existing multi-node setup.

Couchbase uses xref:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to its various xref:learn:services-and-indexes/services/services.adoc[services].
A user or application can connect to a cluster and use these services, assuming that valid credentials with relevant access roles are provided.

include::partial$before-you-begin.adoc[]

include::partial$clients.adoc[tags=!refs-ui]

== Connecting to Couchbase Server

Couchbase Server can be configured to run with _unencrypted_ or _encrypted_ network access. 
When running Couchbase in a production environment, the latter is always recommended.

=== Basic Auth

To connect to a standalone or Docker installation with _unencrypted_ network access, setup a user with appropriate access levels and a secure password.

NOTE: To access a cluster via the Couchbase Server Web Console over an _unencrypted_ connection, navigate to the default configuration address on `localhost:8091` from your browser and enter your credentials.
See xref:getting-started:look-at-the-results.adoc[Explore the Server Configuration] for more information.

[{tabs}]
====
cbc::
+ 
-- 
Most `cbc` sub-commands will require some form of authentication to access a cluster or perform operations on data within a bucket.

. To connect to Couchbase Server using `cbc`, pass `-u` for the username, `-P` for the password and `-U` for the connection url immediately after a sub-command.

. Provide the bucket name required in the connection url (i.e., couchbase://localhost/<bucket-name>).

'''

The example below connects to the `travel-sample` bucket with _Admin_ level credentials and performs a `ping` to check what services are running in a single-node cluster environment.

[source,shell]
----
include::example$connect/connect-cbc.sh[tag=cbc-connect]
----

.Result
[source,console]
----
-------------------------------------------------------------------------------
| type  | id       | status | latency, us | remote          | local           |
-------------------------------------------------------------------------------
| cbas  | 0xec22b0 | ok     |        3003 | localhost:8095  | 127.0.0.1:38612 |
| fts   | 0xec0dc0 | ok     |        3842 | localhost:8094  | 127.0.0.1:35636 |
| kv    | 0xeaa220 | ok     |        4446 | localhost:11210 | 127.0.0.1:49426 |
| n1ql  | 0xead260 | ok     |        4249 | localhost:8093  | 127.0.0.1:56740 |
| views | 0xec0430 | ok     |        4045 | localhost:8092  | 127.0.0.1:60088 |
-------------------------------------------------------------------------------
----

NOTE: If the user credentials are invalid, [.cmd]`cbc` will return a `LCB_ERR_AUTHENTICATION_FAILURE` error.

{cbc-api-url}
--

.NET::
+ 
--

Call the `Cluster.ConnectAsync()` method with a connection url, username and password.

'''

{connect-example}

[source,csharp]
----
include::dotnet-sdk:howtos:example$ManagingConnections.csx[tag=simpleconnect,indent=0]
----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.Cluster.html[Cluster^].
--

Java::
+ 
--

Call the `Cluster.connect()` method with a connection url, username and password.

'''

{connect-example}

[source,java]
----
include::java-sdk:howtos:example$ManagingConnections.java[tag=simpleconnect,indent=0]
----

NOTE: If the user credentials provided are invalid, the SDK will return a `AuthenticationFailureException` error.

{github}

For further details, refer to {java-api-url}/Cluster.html[Cluster^].
--

Node.js::
+ 
--
Call the `connect()` function with a connection url, and a `ConnectOptions` object containing the username and password.

'''

{connect-example}

[source,nodejs]
----
include::nodejs-sdk:howtos:example$auth.js[tag=rbac-auth,indent=0]
----

NOTE: If the user credentials provided are invalid, the SDK will return a `AuthenticationFailureError` error.

{github}

For further details, refer to {nodejs-api-url}/Cluster.html[Cluster^].
--

Python::
+ 
--
. Call the `Cluster.connect()` function with a connection url, and a `ClusterOptions` object containing a `PasswordAutheticator`.

. Provide a username and password to the `PasswordAutheticator`.

'''

{connect-example}

[source,python]
----
include::python-sdk:howtos:example$managing_connections.py[tag=simpleconnect,indent=0]
----

NOTE: If the user credentials provided are invalid, the SDK will return a `AuthenticationException` error.

{github}

For further details, refer to {python-api-url}#cluster-object[Cluster^].
--
====

=== TLS 

To connect to a cluster configured with TLS (Transport Layer Security), for _encrypted_ network access, you must supply an xref:learn:security/certificates.adoc[X.509 certificate].
Before using X.509 certificate based authentication, you should run through the following:

* xref:manage:manage-security/configure-server-certificates.adoc[Configure Server Certificates]

* xref:manage:manage-security/configure-client-certificates.adoc[Configure Client Certificates]

NOTE: To access a cluster via the Couchbase Server Web Console over an _encrypted_ connection, navigate to the default configuration address on `https://localhost:18091` from your browser and enter your credentials.
See xref:manage:manage-security/manage-console-access.adoc[Manage Console Access] for more information.

[{tabs}]
====
cbc::
+ 
-- 
. To securely connect to Couchbase Server using `cbc`, pass `-U` for the connection url immediately after a sub-command.

. Provide the bucket name required in the connection url (i.e., couchbases://127.0.0.1/<bucket-name>). Note that "couchbases://" implies an encrypted connection scheme is used.

. Pass a `certpath` query parameter to the connection url, after the bucket name.

'''

The example below connects to the `travel-sample` bucket with a client certificate, and performs a `ping` to check what services are running in a single-node _secured_ cluster environment.

[source,shell]
----
include::example$connect/connect-cbc.sh[tag=cbc-connect-cert]
----

{cbc-api-url}
--

.NET::
+ 
--
. Call the `WithX509CertificateFactory()` method on a `ClusterOptions()` object.

. Provide the certificate store information to the `WithX509CertificateFactory()` method.

. Call the `ConnectAsync()` method and pass it the cluster options object.

'''

{connect-tls-example}

It is assumed that a valid client certificate and certificate store have been setup.

[source,csharp]
----
include::dotnet-sdk:howtos:example$Auth.cs[tag=auth,indent=0]
----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.Cluster.html[Cluster^].
--

Java::
+ 
--
. Load a Java keystore file containing your client certificate and pass it to the `CertificateAuthenticator.fromKeyStore()` method along with the required password.

. Call the `Cluster.connect()` method and pass the connection string along with cluster options containing the `CertificateAuthenticator` object previously created.

'''

{connect-tls-example}

It is assumed that a valid client certificate and a Java keystore have been setup.

[source,java]
----
include::java-sdk:howtos:example$Auth.java[tag=certauth,indent=0]
----

{github}

For further details, refer to {java-api-url}/Cluster.html[Cluster^].
--

Node.js::
+ 
--
Call the `connect()` function with a connection url, and a `ConnectOptions` object containing a certificate `trustStorePath` and user credentials.

'''

{connect-tls-example}

It is assumed that a valid client certificate has been setup.

[source,nodejs]
----
include::nodejs-sdk:howtos:example$auth.js[tag=tls-cacert,indent=0]
----

{github}

For further details, refer to {nodejs-api-url}/Cluster.html[Cluster^].
--

Python::
+ 
--
. Call the `Cluster.connect()` function with a connection url, and a `ClusterOptions` object containing a `PasswordAutheticator`.

. Provide a username and password to the `PasswordAutheticator`.

. Supply a certificate path to the `PasswordAutheticator`.

'''

{connect-tls-example}

It is assumed that a valid client certificate has been setup.

[source,python]
----
include::python-sdk:howtos:example$managing_connections.py[tag=tls,indent=0]
----

{github}

For further details, refer to {python-api-url}#cluster-object[Cluser^].
--
====

== Connecting to Couchbase Capella

To connect to the database via Couchbase Capella cloud, ensure that you have setup some credentials for your cloud setup, including a client certificate.

[{tabs}]
====
cbc::
+ 
-- 
. To connect to Couchbase Capella using `cbc`, pass `-u` for the username, `-P` for the password and `-U` for the connection url immediately after a sub-command.

. Provide the bucket name required in the connection url (i.e., cb.<your endpoint address>.dp.cloud.couchbase.com/<bucket-name>).

'''

The example below connects to a bucket on Couchbase Capella with a client certificate, and performs a `ping` to check what services are running.

[source,shell]
----
include::example$connect/connect-cbc.sh[tag=cbc-connect-capella]
----

{cbc-api-url}
--

.NET::
+ 
--

Call the `Cluster.ConnectAsync()` method with a Capella cloud endpoint, username, password, and client certificate.

'''

{connect-cloud-example}

[source,csharp]
----
include::dotnet-sdk:devguide:example$dotnet/Cloud.cs[]
----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.Cluster.html[Cluster^].
--

Java::
+ 
--

Call the `Cluster.connect()` method method with a Capella cloud endpoint, username, password, and client certificate.

'''

{connect-cloud-example}

[source,java]
----
include::java-sdk:devguide:example$Cloud.java[]
----

{github}

For further details, refer to {java-api-url}/Cluster.html[Cluster^].
--

Node.js::
+ 
--
Call the `connect()` function with a Capella cloud endpoint, and a `ConnectOptions` object containing the username, password and client certificate.

'''

{connect-cloud-example}

[source,nodejs]
----
include::nodejs-sdk:devguide:example$nodejs/cloud.js[]
----

{github}

For further details, refer to {nodejs-api-url}/Cluster.html[Cluster^].
--

Python::
+ 
--
. Call the `Cluster.connect()` function with a Capella cloud endpoint, and a `ClusterOptions` object containing a `PasswordAutheticator`.

. Provide a username and password to the `PasswordAutheticator`.

. Provide a client certificate path to the `PasswordAutheticator`.

'''

{connect-cloud-example}

[source,python]
----
include::python-sdk:hello-world:example$cloud.py[]
----

{github}

For further details, refer to {python-api-url}#cluster-object[Cluster^].
--
====

== Related Links

Reference and explanation:

* xref:learn:security/security-overview.adoc[Security Overview]
* xref:learn:clusters-and-availability/clusters-and-availability.adoc[Clusters and Availability]
* xref:cloud:get-started:connect-to-cluster.adoc[Couchbase Capella]

Connecting with SDKs:

* xref:c-sdk:howtos:managing-connections.adoc[C]
| xref:dotnet-sdk:howtos:managing-connections.adoc[.NET]
| xref:go-sdk:howtos:managing-connections.adoc[Go]
| xref:java-sdk:howtos:managing-connections.adoc[Java]
| xref:nodejs-sdk:howtos:managing-connections.adoc[Node.js]
| xref:php-sdk:howtos:managing-connections.adoc[PHP]
| xref:python-sdk:howtos:managing-connections.adoc[Python]
| xref:ruby-sdk:howtos:managing-connections.adoc[Ruby]
| xref:scala-sdk:howtos:managing-connections.adoc[Scala]
