= Creating Data
:description: How to create documents in Couchbase.
:page-pagination: full 
:page-topic-type: guide
:page-toclevels: 2
:tabs:
:github: Click the GitHub button icon:github[] to view this code in context.

include::partial$example-attributes.adoc[]

[abstract]
{description}

Couchbase stores its xref:learn:data/data.adoc[data] as either JSON or Binary _documents_ with unique IDs (primary keys) by which they can be located.

Documents are organized and grouped in _buckets_ using xref:tutorials:buckets-scopes-and-collections.adoc[scopes and collections]. 
If a scope or collection is not provided when creating a document, Couchbase will automatically store data in the `_default` collection or `_default` scope.

TIP: We highly recommend that you provide user-defined scopes and collections to logically group your data.

== Inserting a Document

To create a single document in Couchbase perform an `insert` operation.

[{tabs}]
====
cbc::
+ 
-- 
. Create a structured JSON document to insert in the database.

. Use the `cbc create` command with `--mode insert` to create the document. 

. Pass the `--scope` and `--collection` parameters to specify the keyspace in which to store the document, and use `<` to specify the JSON document to insert.

{kv-insert-example}

.hotel-123.json
[source,json]
----
include::example$kv/hotel-123.json[]
----

[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-kv-insert]
----

.Result
[source,console]
----
hotel-123          Stored. CAS=0x16b37e5081690000
                   SYNCTOKEN=829,51260943619833,92
----

NOTE: If the document already exists, [.cmd]`cbc` will return a `LCB_ERR_DOCUMENT_EXISTS` error.
--

.NET::
+ 
--
. Create a structured document object containing your data.

. Use the `InsertAsync()` method to insert the document in a given keyspace. 

. A `MutationResult` object is returned containing the result and metadata relevant to the insert operation.

{kv-insert-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-insert,indent=0]
----

NOTE: If the document already exists, the SDK will return a `DocumentExistsException` error.

{github}
--

Java::
+ 
--
. Create a structured document object containing your data.

. Use the `insert()` method to insert the document in a given keyspace. 

. A `MutationResult` object is returned containing the result and metadata relevant to the insert operation.

{kv-insert-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-insert,indent=0]
----

NOTE: If the document already exists, the SDK will return a `DocumentExistsException` error.

{github}
--

Node.js::
+ 
--
. Create a structured document object containing your data.

. Use the `insert()` method to insert the document in a given keyspace. 

. A `MutationResult` promise is returned containing the result and metadata relevant to the insert operation.

{kv-insert-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-insert,indent=0]
----

NOTE: If the document already exists, the SDK will return a `DocumentExistsError` error.

{github}
--

Python::
+ 
--
. Create a structured document object containing your data.

. Use the `insert()` function to insert the document in a given keyspace.

. A `MutationResult` object is returned containing the result and metadata relevant to the insert operation.

{kv-insert-example}

[source,python]
----
include::python-sdk:hello-world:example$kv_hello_world_scoped.py[tag=kv-insert,indent=0]
----

NOTE: If the document already exists, the SDK will return a `DocumentExistsException` error.

{github}
--
====

When a document is created, Couchbase assigns it a xref:java-sdk:howtos:concurrent-document-mutations.adoc[CAS (Compare And Swap)] value to keep track of the document’s state within the database. 
Each time a document is mutated the CAS will change accordingly. 
This unique value allows the database to protect against concurrent updates to the same document.

=== Inserting with Options

It is also possible to add `options` to an insert operation.

[{tabs}]
====
cbc::
+ 
--
. Use the `cbc create` command with `--mode insert` to create the document. 

. Pass the `--scope` and `--collection` parameters to specify the keyspace in which to store the document.

. Pass an option, `--expiry`, and use `<` to specify the JSON document to insert

{kv-insert-with-options-example}

.hotel-456.json
[source,json]
----
include::example$kv/hotel-456.json[]
----

[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-kv-insert-expiry]
----

.Result
[source,console]
----
hotel-456          Stored. CAS=0x16b5dc9223f30000
                   SYNCTOKEN=733,211618429638288,95
----
--

.NET::
+ 
--
. Create a structured document object containing your data.

. Use the `InsertAsync()` method to insert the document with a given option parameter.

{kv-insert-with-options-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-insert-with-opts,indent=0]
----

{github}
--

Java::
+ 
--
. Create a structured document object containing your data.

. Use the `insert()` method to insert the document with a given option parameter.

{kv-insert-with-options-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-insert-with-opts,indent=0]
----

{github}
--

Node.js::
+ 
--
. Create a structured document object containing your data.

. Use the `insert()` function to insert the document with a given option parameter.

{kv-insert-with-options-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-insert-with-opts,indent=0]
----

{github}
--

Python::
+ 
--
. Create a structured document object containing your data.

. Use the `insert()` function to insert the document with a given option parameter.

{kv-insert-with-options-example}

[source,python]
----
include::python-sdk:hello-world:example$kv_hello_world_scoped.py[tag=kv-insert-with-opts,indent=0]
----

{github}
--
====

== Related Links

Key Value Operations with SDKs:

* xref:c-sdk:howtos:kv-operations.adoc[C]
| xref:dotnet-sdk:howtos:kv-operations.adoc[.NET]
| xref:go-sdk:howtos:kv-operations.adoc[Go]
| xref:java-sdk:howtos:kv-operations.adoc[Java]
| xref:nodejs-sdk:howtos:kv-operations.adoc[Node.js]
| xref:php-sdk:howtos:kv-operations.adoc[PHP]
| xref:python-sdk:howtos:kv-operations.adoc[Python]
| xref:ruby-sdk:howtos:kv-operations.adoc[Ruby]
| xref:scala-sdk:howtos:kv-operations.adoc[Scala]
