= Creating Indexes
:page-topic-type: guide
:imagesdir: ../assets/images
:tabs:
:page-pagination:
:github: Click the GitHub button icon:github[] to view this code in context.
:description: How to create primary indexes and secondary indexes.

[abstract]
{description}

== Introduction

You must create an index on a keyspace to be able to query that keyspace.
The index service supports two types of index: primary indexes and secondary indexes.

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

== Creating a Primary Index

A primary index is an index of document keys.
Primary indexes are optional and are only required for running ad-hoc queries that are not supported by a secondary index.

To create a primary index:

[{tabs}]
====
N1QL::
+
--
Use the `CREATE PRIMARY INDEX` command.

1. If required, specify a name for the primary index.
If you don't specify a name, the index is called `#primary`.

2. Use the `ON` keyword to specify the keyspace on which to create the index.

The following example creates an unnamed primary index on the `airline` keyspace.

[source,N1QL]
----
include::n1ql:example$n1ql-language-reference/create-pri-nameless.n1ql[tag=query]
----

The following example creates a primary index named `travel_primary` on the `airline` keyspace.

[source,N1QL]
----
include::n1ql:example$n1ql-language-reference/create-pri-name.n1ql[]
----

For further details and examples, refer to xref:n1ql:n1ql-language-reference/createprimaryindex.adoc[CREATE PRIMARY INDEX].
--

.NET::
+
--
Use the task `CreatePrimaryIndexAsync()` on the interface `IQueryIndexManager`.

The following example creates an unnamed primary index.

[source,csharp]
----
include::example$index/create-index.cs[tag=primary]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Management.Query.IQueryIndexManager.html[IQueryIndexManager].
--

Java::
+
--
Use the `createPrimaryIndex` method.

The following example creates an unnamed primary index.

[source,java]
----
include::example$index/create-index.java[tag=primary]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/query/QueryIndexManager.html[QueryIndexManager].
--

Node.js::
+
--
Use the `createPrimaryIndex` function on a `QueryIndexManager` object.

The following example creates an unnamed primary index.

[source,nodejs]
----
include::example$index/create-index.js[tag=primary]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-node-client/classes/QueryIndexManager.html[QueryIndexManager].
--

Python::
+
--
Use the `create_primary_index` function on a `QueryIndexManager` object.

The following example creates an unnamed primary index.

[source,python]
----
include::example$index/create-index.py[tag=primary]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html?highlight=index#n1ql-index-management[N1QL Index Management].
--
====

== Creating a Secondary Index

A secondary index is actually the main type of index that queries use.
You can create a secondary index on any fields or expressions necessary to support your queries.

To create a secondary index:

[{tabs}]
====
N1QL::
+
--
Use the `CREATE INDEX` statement.

1. Specify a name for the index.

2. Use the `ON` keyword to specify the keyspace on which to create the index.

3. Specify the index key (the expression or expressions to index) in parentheses `()`.

The following example creates a secondary index on the `name` field in the `airline` keyspace.

[source,N1QL]
----
include::n1ql:example$n1ql-language-reference/create-idx-name.n1ql[]
----

The following example creates a secondary index on an expression using the `name` field in the `airline` keyspace.

[source,N1QL]
----
include::learn:example$services-and-indexes/indexes/create-idx-expr.n1ql[]
----

For further details and examples, refer to xref:n1ql:n1ql-language-reference/createindex.adoc[CREATE INDEX].
--

.NET::
+
--
Use the task `CreateIndexAsync()` on the interface `IQueryIndexManager`.

The following example creates a secondary index on the `name` field in the `airline` keyspace.

[source,csharp]
----
include::example$index/create-index.cs[tag=secondary]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Management.Query.IQueryIndexManager.html[IQueryIndexManager].
--

Java::
+
--
Use the `createIndex` method.

The following example creates a secondary index on the `name` field.

[source,java]
----
include::example$index/create-index.java[tag=secondary]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/query/QueryIndexManager.html[QueryIndexManager].
--

Node.js::
+
--
Use the `createIndex` function on a `QueryIndexManager` object.

The following example creates a secondary index on the `name` field.

[source,nodejs]
----
include::example$index/create-index.js[tag=secondary]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-node-client/classes/QueryIndexManager.html[QueryIndexManager].
--

Python::
+
--
Use the `create_index` function on a `QueryIndexManager` object.

The following example creates a secondary index on the `name` field.

[source,python]
----
include::example$index/create-index.py[tag=secondary]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html?highlight=index#n1ql-index-management[N1QL Index Management].
--
====

=== Creating a Composite Index

A _composite index_ is a secondary index which contains multiple index keys.

To create a composite index, include multiple index keys in the index definition, separated by commas.

====
The following example creates a secondary index on the `name`, `id`, `icao`, and `iata` fields in the `airline` keyspace.

[source,N1QL]
----
include::learn:example$services-and-indexes/indexes/create-idx-composite.n1ql[]
----
====

=== Creating an Index on Metadata

You can also create a secondary index using document metadata.

To index metadata information, use the xref:n1ql:n1ql-language-reference/metafun.adoc#meta[META()] function in the index key.

====
The following example creates a secondary index on the document key.

[source,n1ql]
----
include::n1ql:example$n1ql-language-reference/meta-idx-id.n1ql[]
----
====

For further details and examples, refer to xref:n1ql:n1ql-language-reference/indexing-meta-info.adoc[Indexing Metadata Information].

=== Creating an Index on an Array

You can use an _array index_ to optimize queries on fields which are nested within array elements.

To create an array index, specify the index key as follows:

1. Use the `ALL` keyword to index all values in the specified fields, or `DISTINCT` to index only distinct values.

2. Use a field name to index the entire array, or use an xref:n1ql:n1ql-language-reference/collectionops.adoc#array[ARRAY] operator to index nested fields within the array.

====
The following example creates an index on distinct values of the `day` field within the `schedule` field.

[source,n1ql]
----
include::learn:example$services-and-indexes/indexes/create-idx-array.n1ql[]
----
====

For further details and examples, refer to xref:n1ql:n1ql-language-reference/indexing-arrays.adoc[Array Indexing].

=== Creating a Partial Index

A _partial index_ is an index on a subset of documents within a keyspace -- for example, just the documents which have a specific schema.

To create an index on a subset of documents, use the WHERE clause to specify the distinguishing field(s) for that subset.

====
The following example creates an index on documents in which the value of the `activity` field is `eat`.

[source,n1ql]
----
include::learn:example$services-and-indexes/indexes/create-idx-partial.n1ql[]
----
====

For further details and examples, refer to xref:n1ql:n1ql-language-reference/indexing-and-query-perf.adoc#partial-index[Partial Index].

=== Creating a Covering Index

A _covering index_ is an index which contains all the fields in the query projection, not just the fields that are required for joins or filtering.
A covering index is therefore usually a composite index.
If a query uses a covering index, the query can get all the data it needs from the index, and the Query service does not have to make a fetch request to the Data service.

To create a covering index, make sure the index includes all the fields and expressions required by the query.

For further details and examples, refer to xref:n1ql:n1ql-language-reference/covering-indexes.adoc[Covering Indexes].

== Related Links

Reference and explanation:

* xref:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[Using Indexes]

Administrator guides:

* xref:manage:manage-indexes/manage-indexes.adoc[Manage Indexes]
* xref:manage:monitor/monitoring-indexes.adoc[Monitor Indexes]

Querying with SDKs:

* xref:c-sdk:howtos:n1ql-queries-with-sdk.adoc[C]
| xref:dotnet-sdk:howtos:n1ql-queries-with-sdk.adoc[.NET]
| xref:go-sdk:howtos:n1ql-queries-with-sdk.adoc[Go]
| xref:java-sdk:howtos:n1ql-queries-with-sdk.adoc[Java]
| xref:nodejs-sdk:howtos:n1ql-queries-with-sdk.adoc[Node.js]
| xref:php-sdk:howtos:n1ql-queries-with-sdk.adoc[PHP]
| xref:python-sdk:howtos:n1ql-queries-with-sdk.adoc[Python]
| xref:ruby-sdk:howtos:n1ql-queries-with-sdk.adoc[Ruby]
| xref:scala-sdk:howtos:n1ql-queries-with-sdk.adoc[Scala]
