= Deferring Indexes
:page-topic-type: guide
:imagesdir: ../assets/images
:tabs:
:page-partial:
:page-pagination:
:github: Click the GitHub button icon:github[] to view this code in context.
:description: How to create deferred indexes and build them later.

[abstract]
{description}

== Introduction

// tag::intro[]
When you create a primary or secondary index, you can mark it as _deferred_.
This means the index is not built at once; you can build the deferred index later.
This enables you to build multiple indexes more efficiently.
// end::intro[]

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

== Deferring an Index

You can also defer an index to be built later using an SDK call.

To defer a primary or secondary index to be built later:

[{tabs}]
====
N1QL::
+
--
1. Use the `WITH` clause to specify the index options.

2. In the index options, set the `defer_build` attribute to `true`.

The following queries create a set of primary and secondary indexes in the `landmark` keyspace, with build deferred until later.

[source,N1QL]
----
include::n1ql:example$n1ql-language-reference/create-idx-defer-1.n1ql[]
----

[source,N1QL]
----
include::n1ql:example$n1ql-language-reference/create-idx-defer-2.n1ql[]
----

[source,N1QL]
----
include::n1ql:example$n1ql-language-reference/create-idx-defer-3.n1ql[]
----

For further details and examples, refer to xref:n1ql:n1ql-language-reference/createprimaryindex.adoc[CREATE PRIMARY INDEX] and xref:n1ql:n1ql-language-reference/createindex.adoc[CREATE INDEX].
--

.NET::
+
--
1. Use the task `CreatePrimaryIndexAsync()` or the task `CreateIndexAsync()` to create the index.

2. In the index options, invoke the `Deferred` method with the argument `true`.

The following example creates a set of primary and secondary indexes in the `landmark` keyspace, with build deferred until later.

[source,csharp]
----
include::example$index/build-index.cs[tag=defer]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Management.Query.CreatePrimaryQueryIndexOptions.html[CreatePrimaryQueryIndexOptions] and https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Management.Query.CreateQueryIndexOptions.html[CreateQueryIndexOptions].
--

Java::
+
--
1. Use the `createIndex` method or the `createPrimaryIndex` method to create the index.

2. In the index options, invoke the `deferred` method with the argument `true`.

The following example creates a set of primary and secondary indexes in the `landmark` keyspace, with build deferred until later.

[source,java]
----
include::example$index/build-index.java[tag=defer]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/query/CreatePrimaryQueryIndexOptions.html[CreatePrimaryQueryIndexOptions] and https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/query/CreateQueryIndexOptions.html[CreateQueryIndexOptions].
--

Node.js::
+
--
1. Use the `createPrimaryIndex` function or the `createIndex` function to create the index.

2. In the index options, set the `deferred` property to `true`.

The following example creates a set of primary and secondary indexes in the `landmark` keyspace, with build deferred until later.

[source,nodejs]
----
include::example$index/build-index.js[tag=defer]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-node-client/interfaces/CreatePrimaryQueryIndexOptions.html[CreatePrimaryQueryIndexOptions] and https://docs.couchbase.com/sdk-api/couchbase-node-client/interfaces/CreateQueryIndexOptions.html[CreateQueryIndexOptions].
--

Python::
+
--
1. Use the `create_primary_index` function or the `create_index` function to create the index.

2. In the index options, set the `deferred` property to `true`.

The following example creates a set of primary and secondary indexes in the `landmark` keyspace, with build deferred until later.

[source,python]
----
include::example$index/build-index.py[tag=defer]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html?highlight=index#n1ql-index-management[N1QL Index Management].
--
====

== Building a Deferred Index

You can also build a deferred index using an SDK call.

To build a deferred primary or secondary index:

[{tabs}]
====
N1QL::
+
--
Use the `BUILD INDEX` statement:

1. Use the `ON` keyword to specify the keyspace which contains the index or indexes.

2. Specify the index or indexes that you want to build in parentheses `()`.

The following example builds a single deferred index.

[source,n1ql]
----
include::n1ql:example$n1ql-language-reference/build-idx-single.n1ql[]
----

The following example builds multiple deferred indexes.

[source,n1ql]
----
include::n1ql:example$n1ql-language-reference/build-idx-multiple.n1ql[]
----

For further details and examples, refer to xref:n1ql:n1ql-language-reference/build-index.adoc[BUILD INDEX].
--

.NET::
+
--
Use the task `BuildDeferredIndexesAsync` on the interface `IQueryIndexManager`.

The following example builds all deferred indexes in the keyspace.

[source,csharp]
----
include::example$index/build-index.cs[tag=build]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Management.Query.IQueryIndexManager.html[IQueryIndexManager()].
--

Java::
+
--
Use the `buildDeferredIndexes` method.

The following example builds all deferred indexes in the keyspace.

[source,java]
----
include::example$index/build-index.java[tag=build]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/query/QueryIndexManager.html[QueryIndexManager].
--

Node.js::
+
--
Use the `buildDeferredIndexes` function on a `QueryIndexManager` object.

The following example builds all deferred indexes in the keyspace.

[source,nodejs]
----
include::example$index/build-index.js[tag=build]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-node-client/classes/QueryIndexManager.html[QueryIndexManager].
--

Python::
+
--
// `FIXME: Use the `build_index` function on a `QueryIndexManager` object.
//
The following example builds all deferred indexes in the keyspace.

[source,python]
----
include::example$index/build-index.py[tag=build]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html?highlight=index#n1ql-index-management[N1QL Index Management].
--
====

== Related Links

Reference and explanation:

* xref:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[Using Indexes]

Administrator guides:

* xref:manage:manage-indexes/manage-indexes.adoc[Manage Indexes]
* xref:manage:monitor/monitoring-indexes.adoc[Monitor Indexes]

Indexes with SDKs:

* xref:c-sdk:concept-docs:n1ql-query.adoc#indexes[C]
| xref:dotnet-sdk:concept-docs:n1ql-query.adoc#indexes[.NET]
| xref:go-sdk:concept-docs:n1ql-query.adoc#indexes[Go]
| xref:java-sdk:concept-docs:n1ql-query.adoc#indexes[Java]
| xref:nodejs-sdk:concept-docs:n1ql-query.adoc#indexes[Node.js]
| xref:php-sdk:concept-docs:n1ql-query.adoc#indexes[PHP]
| xref:python-sdk:concept-docs:n1ql-query.adoc#indexes[Python]
| xref:ruby-sdk:concept-docs:n1ql-query.adoc#indexes[Ruby]
| xref:scala-sdk:concept-docs:n1ql-query.adoc#indexes[Scala]
