= Deferring Indexes
:page-topic-type: guide
:imagesdir: ../assets/images
:tabs:
:page-pagination:
:description: How to create deferred indexes and build them later.

[abstract]
{description}

== Introduction

When you create a primary or secondary index, you can mark it as _deferred_.
This means the index is not built at once; you can build the deferred index later.
This may enable you to build multiple indexes more efficiently.

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

== Deferring an Index

To defer a primary or secondary index to be built later:

1. Use the `WITH` clause to specify the index options.

2. In the index options, set the `defer_build` attribute to `true`.

====
The following queries create a set of primary and secondary indexes in the `landmark` keyspace with build deferred until later.

[source,N1QL]
----
include::example$n1ql-language-reference/create-idx-defer-1.n1ql[]
----

[source,N1QL]
----
include::example$n1ql-language-reference/create-idx-defer-2.n1ql[]
----

[source,N1QL]
----
include::example$n1ql-language-reference/create-idx-defer-3.n1ql[]
----
====

For further details and examples, refer to xref:n1ql:n1ql-language-reference/createprimaryindex.adoc[CREATE PRIMARY INDEX] and xref:n1ql:n1ql-language-reference/createindex.adoc[CREATE INDEX].

== Building a Deferred Index

To build a deferred primary or secondary index, use the `BUILD INDEX` statement:

1. Use the `ON` keyword to specify the keyspace which contains the index or indexes.

2. Specify the index or indexes that you want to build in parentheses `()`.

====
The following query builds a single deferred index.

[source,n1ql]
----
include::n1ql:example$n1ql-language-reference/build-idx-single.n1ql[]
----
====

====
The following query builds multiple deferred indexes.

[source,n1ql]
----
include::n1ql:example$n1ql-language-reference/build-idx-multiple.n1ql[]
----
====

For further details and examples, refer to xref:n1ql:n1ql-language-reference/build-index.adoc[BUILD INDEX].

== Related Links

Reference and explanation:

* xref:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[Using Indexes]

Administrator guides:

* xref:manage:manage-indexes/manage-indexes.adoc[Manage Indexes]
* xref:manage:monitor/monitoring-indexes.adoc[Monitor Indexes]

Querying with SDKs:

* xref:c-sdk:howtos:n1ql-queries-with-sdk.adoc[C]
| xref:dotnet-sdk:howtos:n1ql-queries-with-sdk.adoc[.NET]
| xref:go-sdk:howtos:n1ql-queries-with-sdk.adoc[Go]
| xref:java-sdk:howtos:n1ql-queries-with-sdk.adoc[Java]
| xref:nodejs-sdk:howtos:n1ql-queries-with-sdk.adoc[Node.js]
| xref:php-sdk:howtos:n1ql-queries-with-sdk.adoc[PHP]
| xref:python-sdk:howtos:n1ql-queries-with-sdk.adoc[Python]
| xref:ruby-sdk:howtos:n1ql-queries-with-sdk.adoc[Ruby]
| xref:scala-sdk:howtos:n1ql-queries-with-sdk.adoc[Scala]
