= Deleting Data with {sqlpp}
:page-topic-type: guide
:imagesdir: ../../assets/images
:tabs:
:page-partial:
:page-pagination: prev
:description: How to delete documents using {sqlpp}.

[abstract]
{description}

== Introduction

// tag::intro[]
To delete documents from a keyspace, you can use the DELETE statement or the MERGE statement.
// end::intro[]

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

include::partial$data-warning.adoc[]

== Deleting Documents by Key

To delete one or more documents by key, use the DELETE statement with the USE KEYS hint:

. Use the FROM keyword to specify the keyspace which contains the documents to be deleted.
. Use the USE KEYS hint to specify a document keys or array of document keys.
. If required, use the RETURNING clause to specify what should be returned when the documents are deleted.

You can combine this approach with the WHERE clause if necessary.

====
The following query deletes a document with the key `"airline_4444"` and returns the deleted document.

.Context
include::ROOT:partial$query-context.adoc[tag=step]

.Query
[source,sqlpp]
----
include::n1ql:example$dml/delete-key.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$dml/delete-key.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/delete.adoc[DELETE].

== Deleting Documents by Filter

To delete documents by filter, use the DELETE statement with the WHERE clause:

. Use the FROM keyword to specify the keyspace which contains the documents to be deleted.
. Use the WHERE clause to specify the condition that needs to be met for documents to be deleted.
. If required, use the LIMIT clause to specify the greatest number of documents that may be deleted.
. If required, use the RETURNING clause to specify what should be returned when the documents are deleted.

You can combine this approach with the USE KEYS hint if necessary.

====
The following query deletes any airline whose callsign is `"AIR-X"`, returning the content of the airline's `id` field.

.Context
include::ROOT:partial$query-context.adoc[tag=step]

.Query
[source,sqlpp]
----
include::n1ql:example$dml/delete-filter.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$dml/delete-filter.jsonc[]
----
====

== Deleting Documents by Subquery

To delete documents based on the results returned by a SELECT query, use a subquery in the filter.

====
The following query finds the last city in alphanumeric order in the `airport` keyspace, and deletes any airports in that city.

.Context
include::ROOT:partial$query-context.adoc[tag=step]

.Query
[source,sqlpp]
----
include::n1ql:example$dml/delete-sub-same.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$dml/delete-sub-same.jsonc[]
----
====

== Merging and Deleting Documents

You can also delete documents by merging: that is, by joining one keyspace to another, and deleting any documents that match.

To delete documents using a merge, use the MERGE statement with the DELETE action:

. Use the INTO keyword to specify the target.
This is the data source containing the documents to delete.

. Use the USING keyword to specify the source.
This is the data source to check against the target.

. Use the ON keyword to specify the merge predicate.
This is a condition that must be met to match an object in the source with an object in the target.

. Use WHEN MATCHED THEN DELETE to specify that when a document in the source matches a document in the target, the document in the target should be deleted.

. If necessary, use the WHERE clause to specify any further conditions that must be met for documents to be deleted.

. If required, use the LIMIT clause to specify the greatest number of documents that may be deleted.

. If required, use the RETURNING clause to specify what should be returned when the documents are deleted.

====
The following query finds all BA routes whose source airport is in France.
If any flights are using equipment 319, they are updated to use 797.
If any flights are using equipment 757, they are deleted.

.Context
include::ROOT:partial$query-context.adoc[tag=step]

.Query
[source,sqlpp]
----
include::n1ql:example$dml/ansi-merge-keyspace.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$dml/ansi-merge-keyspace.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/merge.adoc[MERGE].

== Related Links

Reference and explanation:

* xref:n1ql:n1ql-language-reference/delete.adoc[DELETE]
* xref:n1ql:n1ql-language-reference/merge.adoc[MERGE]

Querying with SDKs:

* xref:c-sdk:howtos:n1ql-queries-with-sdk.adoc[C]
| xref:dotnet-sdk:howtos:n1ql-queries-with-sdk.adoc[.NET]
| xref:go-sdk:howtos:n1ql-queries-with-sdk.adoc[Go]
| xref:java-sdk:howtos:n1ql-queries-with-sdk.adoc[Java]
| xref:nodejs-sdk:howtos:n1ql-queries-with-sdk.adoc[Node.js]
| xref:php-sdk:howtos:n1ql-queries-with-sdk.adoc[PHP]
| xref:python-sdk:howtos:n1ql-queries-with-sdk.adoc[Python]
| xref:ruby-sdk:howtos:n1ql-queries-with-sdk.adoc[Ruby]
| xref:scala-sdk:howtos:n1ql-queries-with-sdk.adoc[Scala]
