= Deleting Data
:description: How to delete documents in Couchbase.
:page-pagination: full 
:page-topic-type: guide
:tabs:
:github: Click the GitHub button icon:github[] to view this code in context.

include::partial$example-attributes.adoc[]

[abstract]
{description}

In situations where data is no longer needed, Couchbase Server provides a `remove` operation to delete a document from the database permanently. 

== Deleting a Document

To delete a document from the database perform a `remove` operation.

[{tabs}]
====
cbc::
+ 
--
Use the `cbc rm` command to delete a document from the database.

The example below deletes document `airport-123` from the database.

[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-simple-delete]
----

.Result
[source,console]
----
airport-123          Deleted
----
--

.NET::
+ 
--
Use the `RemoveAsync()` method to delete a document from the database.

{kv-delete-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-remove,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}
--

Java::
+ 
--
Use the `remove()` method to delete a document from the database.

{kv-delete-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-remove,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}
--

Node.js::
+ 
--
Use the `remove()` function to delete a document from the database.

{kv-delete-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-remove,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundError` error.

{github}
--

Python::
+ 
--
Use the `remove()` function to delete a document from the database.

{kv-delete-example}

[source,python]
----
include::python-sdk:hello-world:example$kv_hello_world_scoped.py[tag=kv-remove,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}
--
====

== Deleting a Sub-Document

To delete a specific field within a document you can perform a _Sub-Document_ `remove` operation.

[{tabs}]
====
cbc-subdoc::
+ 
--
. Connect to the `cbc-subdoc` interactive shell.

. Use the `remove` command to delete a field from a document.
	Pass the field to remove with the `--path` argument.

{kv-subdoc-delete-example}

[source,console]
----
cbc-subdoc -u Administrator -P password -U couchbase://localhost/travel-sample
subdoc> remove hotel-123 --path url
----

.Result
[source,console]
----
hotel-123          CAS=0x16be2f11c6040000
0. Size=0, RC=LCB_SUCCESS (0)
----

NOTE: If the path cannot be found, `cbc-subdoc` will return a `LCB_ERR_SUBDOC_PATH_NOT_FOUND` error. 
--

.NET::
+ 
--
. To remove a specific field inside a document, call the `MutateInAsync()` method, which takes a document ID and an IEnumerable containing `MutateInSpec` objects. 
`MutateInSpec` represents the sub-operation to be performed within the lookup.

. A `MutateInResult` object is returned containing the result and metadata relevant to the sub-document update operation.

{kv-subdoc-delete-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-remove-subdoc,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}
--

Java::
+ 
--
. To remove a specific field inside a document, call the `mutateIn()` method, which takes a document ID and an array of `MutateInSpec` objects. `MutateInSpec` represents the sub-operation to be performed within the lookup.

. A `MutateInResult` object is returned containing the result and metadata relevant to the sub-document update operation.

{kv-subdoc-delete-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-remove-subdoc,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}
--

Node.js::
+ 
--
. To remove a specific field inside a document, call the `mutateIn()` method, which takes a document ID and an array of `MutateInSpec` objects. `MutateInSpec` represents the sub-operation to be performed within the lookup.

. A `MutateInResult` object is returned containing the result and metadata relevant to the sub-document update operation.

{kv-subdoc-delete-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-remove-subdoc,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundError` error.

{github}
--

Python::
+ 
--
. To remove a specific field inside a document, call the `lookup_in()` function, which takes a document ID and a list of `MutateInSpec` objects. 
`MutateInSpec` represents the sub-operation to be performed within the lookup.

. A `MutateInResult` object is returned containing the result and metadata relevant to the sub-document get operation.

{kv-subdoc-delete-example}

[source,python]
----
include::python-sdk:hello-world:example$kv_hello_world_scoped.py[tag=kv-remove-subdoc,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}
--
====

== Related Links

Key Value Operations with SDKs:

* xref:c-sdk:howtos:kv-operations.adoc[C]
| xref:dotnet-sdk:howtos:kv-operations.adoc[.NET]
| xref:go-sdk:howtos:kv-operations.adoc[Go]
| xref:java-sdk:howtos:kv-operations.adoc[Java]
| xref:nodejs-sdk:howtos:kv-operations.adoc[Node.js]
| xref:php-sdk:howtos:kv-operations.adoc[PHP]
| xref:python-sdk:howtos:kv-operations.adoc[Python]
| xref:ruby-sdk:howtos:kv-operations.adoc[Ruby]
| xref:scala-sdk:howtos:kv-operations.adoc[Scala]

Sub-Document operations with SDKs:

* xref:c-sdk:howtos:subdocument-operations.adoc[C]
| xref:dotnet-sdk:howtos:subdocument-operations.adoc[.NET]
| xref:go-sdk:howtos:subdocument-operations.adoc[Go]
| xref:java-sdk:howtos:subdocument-operations.adoc[Java]
| xref:nodejs-sdk:howtos:subdocument-operations.adoc[Node.js]
| xref:php-sdk:howtos:subdocument-operations.adoc[PHP]
| xref:python-sdk:howtos:subdocument-operations.adoc[Python]
| xref:ruby-sdk:howtos:subdocument-operations.adoc[Ruby]
| xref:scala-sdk:howtos:subdocument-operations.adoc[Scala]
