= Dropping Indexes
:page-topic-type: guide
:imagesdir: ../assets/images
:tabs:
:page-partial:
:page-pagination:
:github: Click the GitHub button icon:github[] to view this code in context.
:work-with: drop
:description: How to drop primary and secondary indexes.

[abstract]
{description}

== Introduction

// tag::intro[]
You can drop primary and secondary indexes when you do not need them any more.
// end::intro[]
Dropping an index that has replicas will also drop all of the replica indexes too.

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

== Dropping a Primary Index

You can drop a primary index using a {sqlpp} statement or an SDK call.

include::partial$index-context.adoc[]

[{tabs}]
====
{sqlpp}::
+
--
To drop an unnamed primary index, use the `DROP PRIMARY INDEX` statement.

To drop a named primary index, use the `DROP INDEX` statement.
There are two possible syntaxes:

* Specify the index name, then use the `ON` keyword to specify the keyspace which contains the index.

* Specify the keyspace and index name using dotted notation.

'''

The following example drops an unnamed primary index from the `airline` keyspace.

[source,sqlpp]
----
include::n1ql:example$n1ql-language-reference/drop-pri-nameless.n1ql[tag=query]
----

The following example drops a named primary index from the `airline` keyspace.

[source,sqlpp]
----
include::n1ql:example$n1ql-language-reference/drop-pri-name.n1ql[]
----

The following example drops the index in exactly the same way, but uses alternative syntax.

[source,sqlpp]
----
include::n1ql:example$n1ql-language-reference/drop-pri-alt.n1ql[]
----

For further details and examples, refer to xref:n1ql:n1ql-language-reference/dropprimaryindex.adoc[DROP PRIMARY INDEX] and  xref:n1ql:n1ql-language-reference/dropindex.adoc[DROP INDEX].
--

.NET::
+
--
To drop a primary index, use the task `DropPrimaryIndexAsync()` on the interface `IQueryIndexManager`.

1. Specify the keyspace which contains the index.

2. If the index has a name:

  a. Use `DropPrimaryQueryIndexOptions` to specify the index options.

  b. In the index options, invoke the `IndexName` method.

'''

The following example drops an unnamed primary index from the specified keyspace.

[source,csharp]
----
include::dotnet-sdk:hello-world:example$IndexHelloWorld.csx[tag=drop-primary,indent=0]
----

The following example drops a named primary index from the specified keyspace.

[source,csharp]
----
include::dotnet-sdk:hello-world:example$IndexHelloWorld.csx[tag=drop-named-primary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Management.Query.IQueryIndexManager.html[IQueryIndexManager()^].
--

Java::
+
--
To drop a primary index, use the `dropPrimaryIndex` method and specify the keyspace which contains the index.

NOTE: The Java SDK does not provide a call for dropping a named primary index.
To drop a named primary index, use a {sqlpp} query.

'''

The following example drops an unnamed primary index from the specified keyspace.

[source,java]
----
include::java-sdk:hello-world:example$IndexHelloWorld.java[tag=drop-primary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/query/QueryIndexManager.html[QueryIndexManager^].
--

Node.js::
+
--
To drop a primary index, use the `dropPrimaryIndex` function on a `QueryIndexManager` object.

1. Specify the keyspace which contains the index.

2. If the index has a name:

  a. Use `DropPrimaryQueryIndexOptions` to specify the index options.

  b. In the index options, use the `name` property to specify the index name.

'''

The following example drops an unnamed primary index from the specified keyspace.

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$index-hello-world.js[tag=drop-primary,indent=0]
----

The following example drops a named primary index from the specified keyspace.

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$index-hello-world.js[tag=drop-named-primary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-node-client/classes/QueryIndexManager.html[QueryIndexManager^].
--

Python::
+
--
To drop a primary index, use the `drop_primary_index` function on a `QueryIndexManager` object.

1. Specify the keyspace which contains the index.

2. If the index has a name:

  a. Use `DropPrimaryQueryIndexOptions` to specify the index options.

  b. In the index options, use the `index_name` property to specify the index name.

'''

The following example drops an unnamed primary index from the specified keyspace.

[source,python]
----
include::python-sdk:hello-world:example$index_hello_world.py[tag=drop-primary,indent=0]
----

The following example drops a named primary index from the specified keyspace.

[source,python]
----
include::python-sdk:hello-world:example$index_hello_world.py[tag=drop-named-primary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html#n1ql-index-management[{sqlpp} Index Management^].
--
====

== Dropping a Secondary Index

You can drop a secondary index using a {sqlpp} statement or an SDK call.

include::partial$index-context.adoc[]

[{tabs}]
====
{sqlpp}::
+
--
To drop a a secondary index, use the `DROP INDEX` statement.
There are two possible syntaxes:

* Specify the index name, then use the `ON` keyword to specify the keyspace which contains the index.

* Specify the keyspace and index name using dotted notation.

'''

The following example drops a named index from the `airline` keyspace.

[source,sqlpp]
----
include::n1ql:example$n1ql-language-reference/drop-idx-name.n1ql[]
----

The following example drops the index in exactly the same way, but uses alternative syntax.

[source,sqlpp]
----
include::n1ql:example$n1ql-language-reference/drop-idx-alt.n1ql[]
----

For further details and examples, refer to xref:n1ql:n1ql-language-reference/dropindex.adoc[DROP INDEX].
--

.NET::
+
--
To drop a secondary index, use the task `DropIndexAsync()` on the interface `IQueryIndexManager`.

1. Specify the keyspace which contains the index.

2. Specify the name of the index.

'''

The following example drops a named index from the specified keyspace.

[source,csharp]
----
include::dotnet-sdk:hello-world:example$IndexHelloWorld.csx[tag=drop-secondary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Management.Query.IQueryIndexManager.html[IQueryIndexManager()^].
--

Java::
+
--
To drop a secondary index, use the `dropIndex` method.

1. Specify the keyspace which contains the index.

2. Specify the name of the index.

'''

The following example drops a named index from the specified keyspace.

[source,java]
----
include::java-sdk:hello-world:example$IndexHelloWorld.java[tag=drop-secondary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/query/QueryIndexManager.html[QueryIndexManager^].
--

Node.js::
+
--
To drop a secondary index, use the `dropIndex` function on a `QueryIndexManager` object.

1. Specify the keyspace which contains the index.

2. Specify the name of the index.

'''

The following example drops a named index from the specified keyspace.

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$index-hello-world.js[tag=drop-secondary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-node-client/classes/QueryIndexManager.html[QueryIndexManager^].
--

Python::
+
--
To drop a secondary index, use the `drop_index` function on a `QueryIndexManager` object.

1. Specify the keyspace which contains the index.

2. Specify the name of the index.

'''

The following example drops a named index from the specified keyspace.

[source,python]
----
include::python-sdk:hello-world:example$index_hello_world.py[tag=drop-secondary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html#n1ql-index-management[{sqlpp} Index Management^].
--
====

== Related Links

Reference and explanation:

* xref:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[Using Indexes]

Administrator guides:

* xref:manage:manage-indexes/manage-indexes.adoc[Manage Indexes]
* xref:manage:monitor/monitoring-indexes.adoc[Monitor Indexes]

Indexes with SDKs:

* xref:c-sdk:concept-docs:n1ql-query.adoc#indexes[C]
| xref:dotnet-sdk:concept-docs:n1ql-query.adoc#indexes[.NET]
| xref:go-sdk:concept-docs:n1ql-query.adoc#indexes[Go]
| xref:java-sdk:concept-docs:n1ql-query.adoc#indexes[Java]
| xref:nodejs-sdk:concept-docs:n1ql-query.adoc#indexes[Node.js]
| xref:php-sdk:concept-docs:n1ql-query.adoc#indexes[PHP]
| xref:python-sdk:concept-docs:n1ql-query.adoc#indexes[Python]
| xref:ruby-sdk:concept-docs:n1ql-query.adoc#indexes[Ruby]
| xref:scala-sdk:concept-docs:n1ql-query.adoc#indexes[Scala]
