= Dropping Indexes
:page-topic-type: guide
:imagesdir: ../assets/images
:tabs:
:page-partial:
:page-pagination: last
:github: Click the GitHub button icon:github[] to view this code in context.
:description: How to drop primary and secondary indexes.

[abstract]
{description}

== Introduction

// tag::intro[]
You can drop primary and secondary indexes when you do not need them any more.
// end::intro[]
Dropping an index that has replicas will also drop all of the replica indexes too.

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

== Dropping an Unnamed Primary Index

You can drop an unnamed primary index using a N1QL statement or an SDK call.

To drop an unnamed primary index:

[{tabs}]
====
N1QL::
+
--
Use the `DROP PRIMARY INDEX` statement.

The following example drops an unnamed primary index from the `airline` keyspace.

[source,N1QL]
----
include::n1ql:example$n1ql-language-reference/drop-pri-nameless.n1ql[tag=query]
----

For further details and examples, refer to xref:n1ql:n1ql-language-reference/dropprimaryindex.adoc[DROP PRIMARY INDEX].
--

.NET::
+
--
Use the task `DropPrimaryIndexAsync()` on the interface `IQueryIndexManager`.

The following example drops an unnamed primary index from the `airline` keyspace.

[source,csharp]
----
include::example$index/drop-index.cs[tags=manager;primary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Management.Query.IQueryIndexManager.html[IQueryIndexManager()].
--

Java::
+
--
Use the `dropPrimaryIndex` method.

The following example drops an unnamed primary index from the `airline` keyspace.

[source,java]
----
include::example$index/drop-index.java[tags=manager;primary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/query/QueryIndexManager.html[QueryIndexManager].
--

Node.js::
+
--
Use the `dropPrimaryIndex` function on a `QueryIndexManager` object.

The following example drops an unnamed primary index from the `airline` keyspace.

[source,nodejs]
----
include::example$index/drop-index.js[tags=manager;primary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-node-client/classes/QueryIndexManager.html[QueryIndexManager].
--

Python::
+
--
// `FIXME: Use the `drop_primary_index` function on a `QueryIndexManager` object.
//
The following example drops an unnamed primary index from the `airline` keyspace.

[source,python]
----
include::example$index/drop-index.py[tags=manager;primary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html?highlight=index#n1ql-index-management[N1QL Index Management].
--
====

== Dropping a Named Primary or Secondary Index

You can drop a named primary or secondary index using a N1QL statement or an SDK call.

To drop a named primary or secondary index:

[{tabs}]
====
N1QL::
+
--
Use the `DROP INDEX` statement.
There are two possible syntaxes:

* Specify the index name, then use the `ON` keyword to specify the keyspace which contains the index.

* Specify the keyspace and index name using dotted notation.

The following example drops a named index from the `airline` keyspace.

[source,n1ql]
----
include::n1ql:example$n1ql-language-reference/drop-idx-name.n1ql[]
----

The following example drops the index in exactly the same way, but uses alternative syntax.

[source,n1ql]
----
include::n1ql:example$n1ql-language-reference/drop-idx-alt.n1ql[]
----

For further details and examples, refer to xref:n1ql:n1ql-language-reference/dropindex.adoc[DROP INDEX].
--

.NET::
+
--
Use the task `DropIndexAsync()` on the interface `IQueryIndexManager`.

The following example drops a named index from the `airline` keyspace.

[source,csharp]
----
include::example$index/drop-index.cs[tags=manager;secondary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Management.Query.IQueryIndexManager.html[IQueryIndexManager()].
--

Java::
+
--
Use the `dropIndex` method.

The following example drops a named index from the `airline` keyspace.

[source,java]
----
include::example$index/drop-index.java[tags=manager;secondary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/manager/query/QueryIndexManager.html[QueryIndexManager].
--

Node.js::
+
--
Use the `dropIndex` function on a `QueryIndexManager` object.

The following example drops a named index from the `airline` keyspace.

[source,nodejs]
----
include::example$index/drop-index.js[tags=manager;secondary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-node-client/classes/QueryIndexManager.html[QueryIndexManager].
--

Python::
+
--
// `FIXME: Use the `drop_index` function on a `QueryIndexManager` object.
//
The following example drops a named index from the `airline` keyspace.

[source,python]
----
include::example$index/drop-index.py[tags=manager;secondary,indent=0]
----

{github}

For further details, refer to https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html?highlight=index#n1ql-index-management[N1QL Index Management].
--
====

== Related Links

Reference and explanation:

* xref:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[Using Indexes]

Administrator guides:

* xref:manage:manage-indexes/manage-indexes.adoc[Manage Indexes]
* xref:manage:monitor/monitoring-indexes.adoc[Monitor Indexes]

Indexes with SDKs:

* xref:c-sdk:concept-docs:n1ql-query.adoc#indexes[C]
| xref:dotnet-sdk:concept-docs:n1ql-query.adoc#indexes[.NET]
| xref:go-sdk:concept-docs:n1ql-query.adoc#indexes[Go]
| xref:java-sdk:concept-docs:n1ql-query.adoc#indexes[Java]
| xref:nodejs-sdk:concept-docs:n1ql-query.adoc#indexes[Node.js]
| xref:php-sdk:concept-docs:n1ql-query.adoc#indexes[PHP]
| xref:python-sdk:concept-docs:n1ql-query.adoc#indexes[Python]
| xref:ruby-sdk:concept-docs:n1ql-query.adoc#indexes[Ruby]
| xref:scala-sdk:concept-docs:n1ql-query.adoc#indexes[Scala]
