= Dropping Indexes
:page-topic-type: guide
:imagesdir: ../assets/images
:tabs:
:page-pagination:
:description: How to drop primary and secondary indexes.

[abstract]
{description}

== Introduction

You can drop primary and secondary indexes when you do not need them any more.
Dropping an index that has replicas will also drop all of the replica indexes too.

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

== Dropping an Unnamed Primary Index

To drop an unnamed primary index, use the `DROP PRIMARY INDEX` statement.

====
The following query drops an unnamed primary index from the `airline` keyspace.

[source,N1QL]
----
include::n1ql:example$n1ql-language-reference/drop-pri-nameless.n1ql[tag=query]
----
====

For further details and examples, refer to xref:n1ql:n1ql-language-reference/dropprimaryindex.adoc[DROP PRIMARY INDEX].

== Dropping a Named Primary or Secondary Index

To drop a named primary or secondary index, use the `DROP INDEX` statement.
There are two possible syntaxes:

* Specify the index name, then use the `ON` keyword to specify the keyspace which contains the index.

* Specify the keyspace and index name using dotted notation.

====
The following query drops a named index from the `airline` keyspace.

[source,n1ql]
----
include::n1ql:example$n1ql-language-reference/drop-idx-name.n1ql[]
----
====

====
The following query drops the index in exactly the same way, but uses alternative syntax.

[source,n1ql]
----
include::n1ql:example$n1ql-language-reference/drop-idx-alt.n1ql[]
----
====

For further details and examples, refer to xref:n1ql:n1ql-language-reference/dropindex.adoc[DROP INDEX].

== Related Links

Reference and explanation:

* xref:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[Using Indexes]

Administrator guides:

* xref:manage:manage-indexes/manage-indexes.adoc[Manage Indexes]
* xref:manage:monitor/monitoring-indexes.adoc[Monitor Indexes]

Querying with SDKs:

* xref:c-sdk:howtos:n1ql-queries-with-sdk.adoc[C]
| xref:dotnet-sdk:howtos:n1ql-queries-with-sdk.adoc[.NET]
| xref:go-sdk:howtos:n1ql-queries-with-sdk.adoc[Go]
| xref:java-sdk:howtos:n1ql-queries-with-sdk.adoc[Java]
| xref:nodejs-sdk:howtos:n1ql-queries-with-sdk.adoc[Node.js]
| xref:php-sdk:howtos:n1ql-queries-with-sdk.adoc[PHP]
| xref:python-sdk:howtos:n1ql-queries-with-sdk.adoc[Python]
| xref:ruby-sdk:howtos:n1ql-queries-with-sdk.adoc[Ruby]
| xref:scala-sdk:howtos:n1ql-queries-with-sdk.adoc[Scala]
