= Grouping and Aggregation
:page-topic-type: guide
:page-partial:
:page-pagination: prev
:imagesdir: ../../assets/images
:tabs:
:description: How to calculate aggregates and group the results.

[abstract]
{description}

== Introduction

// tag::intro[]
You can use aggregate functions to perform calculations over multiple values.
Grouping enables you to display the results in groups.
// end::intro[]

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

== Aggregate Functions

To take multiple values from documents, perform calculations, and return a single value as the result, use an aggregate function, such as
xref:n1ql:n1ql-language-reference/aggregatefun.adoc#avg[AVG()],
xref:n1ql:n1ql-language-reference/aggregatefun.adoc#count[COUNT()],
xref:n1ql:n1ql-language-reference/aggregatefun.adoc#min[MIN()],
xref:n1ql:n1ql-language-reference/aggregatefun.adoc#max[MAX()], or
xref:n1ql:n1ql-language-reference/aggregatefun.adoc#sum[SUM()].

====
For example, the following query finds the average altitude of airports in the airport keyspace.

.Query
[source,n1ql]
----
include::n1ql:example$functions/avg.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$functions/avg.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/aggregatefun.adoc[Aggregate Functions].

=== Aggregating Distinct Values

To aggregate all values, omit the aggregate quantifier, or optionally include the `ALL` keyword before the function arguments.

====
For example, the following query finds the average number of stops per route.

.Query
[source,n1ql]
----
include::n1ql:example$functions/avg-all.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$functions/avg-all.jsonc[]
----

Results in 0.0002 since nearly all routes have 0 stops.
====

To aggregate distinct values only, include the `DISTINCT` keyword before the function arguments.

====
For example, the following query finds the average of the distinct numbers of stops.

.Query
[source,n1ql]
----
include::n1ql:example$functions/avg-distinct.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$functions/avg-distinct.jsonc[]
----

Results in 0.5 since the routes contain only 1 or 0 stops.
====

For more information, refer to xref:n1ql:n1ql-language-reference/aggregatefun.adoc#aggregate-quantifier[Aggregate Quantifier].

=== Filtering the Aggregates

To filter the values used by an aggregate function, use the FILTER clause after the function.

====
For example, the following query finds the minimum value of a string field, only including strings that start with `"A"` or greater.

.Query
[source,n1ql]
----
include::n1ql:example$functions/min-filter.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$functions/min-filter.jsonc[]
----
====

For more information, refer to xref:n1ql:n1ql-language-reference/aggregatefun.adoc#filter-clause[FILTER Clause].

== Grouping the Results

By default, an aggregate function returns a single result for all the documents that the query selects.
It is often more useful to group the documents (by a different field) and return the aggregate result for each group.

To group the results of an aggregate query, use the GROUP BY clause.

====
For example, the following query groups unique landmarks by city.

.Query
[source,n1ql]
----
include::n1ql:example$select/group-by.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$select/group-by.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/groupby.adoc[GROUP BY Clause].

=== Filtering the Groups

To filter the groups by an aggregate function, use the HAVING clause within the GROUP BY clause.

====
For example, the following query groups unique landmarks by city, and specifies cities that have more than 180 landmarks.

.Query
[source,n1ql]
----
include::n1ql:example$select/group-by-having.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$select/group-by-having.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/groupby.adoc#having-clause[HAVING Clause].

=== Defining an Expression within the GROUP BY Clause

To define an expression for use within the GROUP BY clause, use the LETTING clause before the HAVING clause.

====
For example, the following clause uses an expression to define the minimum number of landmarks for each city.

.Query
[source,n1ql]
----
include::n1ql:example$select/group-by-letting.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$select/group-by-letting.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/groupby.adoc#letting-clause[LETTING Clause].

== Related Links

Reference and explanation:

* xref:n1ql:n1ql-language-reference/aggregatefun.adoc[Aggregate Functions]
* xref:n1ql:n1ql-language-reference/groupby.adoc[GROUP BY Clause]

Tutorials:

* https://query-tutorial.couchbase.com/tutorial/#1[N1QL Query Language Tutorial^]

Querying with SDKs:

* xref:c-sdk:howtos:n1ql-queries-with-sdk.adoc[C]
| xref:dotnet-sdk:howtos:n1ql-queries-with-sdk.adoc[.NET]
| xref:go-sdk:howtos:n1ql-queries-with-sdk.adoc[Go]
| xref:java-sdk:howtos:n1ql-queries-with-sdk.adoc[Java]
| xref:nodejs-sdk:howtos:n1ql-queries-with-sdk.adoc[Node.js]
| xref:php-sdk:howtos:n1ql-queries-with-sdk.adoc[PHP]
| xref:python-sdk:howtos:n1ql-queries-with-sdk.adoc[Python]
| xref:ruby-sdk:howtos:n1ql-queries-with-sdk.adoc[Ruby]
| xref:scala-sdk:howtos:n1ql-queries-with-sdk.adoc[Scala]
