= Inserting Data with N1QL
:page-topic-type: guide
:imagesdir: ../../assets/images
:tabs:
:page-partial:
:page-pagination:
:description: How to insert documents using N1QL.

[abstract]
{description}

== Introduction

// tag::intro[]
To insert documents in a keyspace, you can use the INSERT statement, the UPSERT statement, or the MERGE statement.
// end::intro[]

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

include::partial$data-warning.adoc[]

== Inserting a Document

To insert a document by providing the value, use the INSERT statement with the VALUES clause:

. Use the INTO keyword to specify the keyspace into which the document is inserted.

. Optionally, use the bracketed KEY and VALUE keywords to specify that you're inserting a document key and body.

. Use the VALUES clause to specify the document key and the body of the document.

. If required, use the RETURNING clause specifies what the query returns when the document is inserted.

====
The following query creates a document in the `airline` keyspace.

.Query
[source,n1ql]
----
include::n1ql:example$dml/insert-doc.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$dml/insert-doc.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/insert.adoc[INSERT].

=== Inserting Documents in Bulk

To insert several documents at once, use multiple VALUES clauses.
The VALUES keyword itself is optional in the second and later iterations of the clause.

====
The following query creates two documents in the `airline` keyspace.

.Query
[source,n1ql]
----
include::n1ql:example$dml/insert-batch.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$dml/insert-batch.jsonc[]
----
====

=== Inserting the Results of a Query

To insert documents using a query, use the INSERT statement with a SELECT statement.

. Use the bracketed KEY keyword to specify the document key.

. Use the optional VALUE keyword to specify the body of the document to insert.
The body of the inserted document is usually based on the result returned by the SELECT statement.

. Use the SELECT statement to return a resultset which is used as a basis for the inserted documents.
The INSERT statement inserts a document for every result returned by the SELECT statement.

. If required, use the RETURNING clause specifies what the query returns when the document is inserted.

[NOTE]
The document key that you specify must be unique for every document that you insert.
For example, you can use the xref:n1ql:n1ql-language-reference/metafun.adoc#uuid[UUID()] function to generate a unique key for each document.

====
The following query creates a copy in the `airport` keyspace of any document whose `airportname` is "Heathrow".

.Query
[source,n1ql]
----
include::n1ql:example$dml/insert-select.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$dml/insert-select.jsonc[]
----
====

== Replacing Existing Documents

The INSERT statement fails if a document with the same document key already exists in the keyspace.

To insert documents into a keyspace and replace any existing documents with the same key, use the UPSERT statement.
This has the same syntax as the INSERT statement.

====
The following query creates two documents in the `landmark` keyspace.
If documents with the same keys already exist, the existing documents are replaced.

.Query
[source,n1ql]
----
include::n1ql:example$dml/upsert-batch.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$dml/upsert-batch.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/upsert.adoc[UPSERT].

== Merging and Inserting Documents

You can also insert documents by merging: that is, by joining one data source to another, and inserting documents any documents that do not match.

To insert documents using a merge, use the MERGE statement with the INSERT action:

. Use the INTO keyword to specify the target data source.
This is the data source into which documents will be inserted.

. Use the USING keyword to specify the source.
This is the data source to check against the target.

. Use the ON keyword to specify the merge predicate.
This is a condition that must be met to match an object in the source with an object in the target.

. Use WHEN NOT MATCHED THEN INSERT to specify that when a document in the source does not match a document in the target, the document should be inserted in the target.

 .. If necessary, use the bracketed KEY keyword to specify the document key.

 .. If necessary, use the bracketed VALUE keyword to specify the body of the document to insert.

 .. If necessary, use the WHERE clause to specify any further conditions that must be met for documents to be inserted.

. If required, use the LIMIT clause to specify the greatest number of documents that may be inserted.

. If required, use the RETURNING clause to specify what should be returned when the documents are inserted.

====
The following query compares a source set of airport data with the target `airport` keyspace.
If the airport already exists in the `airport` keyspace, the record is updated.
If the airport does not exist in the `airport` keyspace, a new record is inserted.

.Query
[source,n1ql]
----
include::n1ql:example$dml/ansi-merge-else.n1ql[]
----

.Results
[source,json]
----
include::n1ql:example$dml/ansi-merge-else.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/merge.adoc[MERGE].

== Related Links

Reference and explanation:

* xref:n1ql:n1ql-language-reference/insert.adoc[INSERT]
* xref:n1ql:n1ql-language-reference/upsert.adoc[UPSERT]
* xref:n1ql:n1ql-language-reference/merge.adoc[MERGE]

Querying with SDKs:

* xref:c-sdk:howtos:n1ql-queries-with-sdk.adoc[C]
| xref:dotnet-sdk:howtos:n1ql-queries-with-sdk.adoc[.NET]
| xref:go-sdk:howtos:n1ql-queries-with-sdk.adoc[Go]
| xref:java-sdk:howtos:n1ql-queries-with-sdk.adoc[Java]
| xref:nodejs-sdk:howtos:n1ql-queries-with-sdk.adoc[Node.js]
| xref:php-sdk:howtos:n1ql-queries-with-sdk.adoc[PHP]
| xref:python-sdk:howtos:n1ql-queries-with-sdk.adoc[Python]
| xref:ruby-sdk:howtos:n1ql-queries-with-sdk.adoc[Ruby]
| xref:scala-sdk:howtos:n1ql-queries-with-sdk.adoc[Scala]
