= Developer How-to Guides
:page-role: tiles -toc
:description: This section contains how-to guides for developers.
:!sectids:

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

This section contains how-to guides, which walk you through common tasks for Couchbase Server development.
The Developer Information section contains explanations to help you understand the services offered by Couchbase Server.
For reference material, refer to 

== Key-Value Operations

* Create Data
* Read Data
* Update Data
* Delete Data
* Bulk Operations
* Durable Operations

== Query

* xref:guides:query.adoc[Read Data]
* Manipulate Data
* Prepared Statements
* Indexes

== Transactions

Aute exercitation do laborum minim qui incididunt. Voluptate cillum non tempor laborum irure amet minim proident mollit laboris ut nulla labore elit. Lorem ullamco dolore aliquip labore est aliquip aliqua elit magna non incididunt.

== Text Search

Fugiat Lorem quis sit occaecat consequat do non quis sunt id cillum. Duis officia deserunt est enim eiusmod. Ea pariatur consectetur consequat aliquip ex aliquip aute ullamco exercitation. Veniam minim id non enim amet. Nisi laboris proident nisi exercitation. Consectetur cupidatat ex non eu eu Lorem nostrud ad aliquip pariatur.

== Geospatial Queries

Ullamco mollit consequat sint duis occaecat quis ullamco sunt consequat. Consectetur nisi fugiat eu ea nisi. Voluptate in laboris id nisi laborum enim et. Dolore mollit eu enim exercitation nostrud pariatur non. Elit veniam consequat cillum sit sit minim sit. Ex sit eiusmod duis adipisicing duis. Eu reprehenderit enim dolore excepteur ut.

== Analytical Queries

Cupidatat laborum ea ex consectetur aliquip ullamco irure esse commodo incididunt aute eu reprehenderit mollit. Eiusmod sit cillum ea pariatur ut proident dolor exercitation ad. Enim elit ullamco esse eu aliqua aute fugiat. Duis incididunt nisi tempor non ex deserunt deserunt commodo dolore labore laboris. Consequat et incididunt velit exercitation cupidatat ex. Mollit Lorem ullamco consectetur eu dolore sint sint veniam ipsum cupidatat.

== Server-Side Programming
* User-Defined Functions for Query
 ** xref:guides:udf.adoc[Create UDFs in N1QL]
 ** Use UDFs in N1QL
 ** Update UDFs in N1QL
 ** Delete UDFs in N1QL
* Eventing Functions

== Import and Stream Data

* Import data from files
* Stream data using Kafka

== Optimize Performance

* Index Advisor
* Cost-Based Optimizer