= Developer Guides
:page-role: tiles -toc
:description: This section contains how-to guides for developers.
:!sectids:

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title,
  div.contributor-list-box,
  div#preamble,
  nav.pagination {
    flex-basis: 100%;
  }
</style>
++++
endif::[]

This section contains _how-to guides_ that walk you through common tasks for Couchbase Server development, such as storing, retrieving, and querying documents.

== Connecting to Couchbase

This guide explains how to connect to a Couchbase cluster.

* xref:connect.adoc[]

== Key-Value Operations

This guide explains how to use Couchbase SDKs to carry out key-value operations on documents.

* xref:kv-operations.adoc[]

== Selection Queries

This guide explains how to read data with a N1QL query.

* xref:query.adoc[]

== Indexes

This guide explains how to create and use primary and secondary indexes for N1QL queries.

* xref:indexes.adoc[]

== Data Manipulation Queries

This guide explains how to create, update, and delete data with a N1QL query.

* xref:manipulate.adoc[]

== Transactions

This guide explains how to carry out ACID transactions on the database.

* xref:transactions.adoc[]

== Importing Data

This guide explains how to import data from files.

* xref:import.adoc[]

== JavaScript User-Defined Functions

This guide explains how to create JavaScript User-Defined Functions, and how to call them through the Query WorkBench and the REST API.

* xref:javascript-udfs.adoc[]
