= User-defined Functions in JavaScript
:description: Extending the N1QL query language by adding your own functions written in JavaScript
:page-pagination: next
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2
:xrefstyle: short

[abstract]
{description}

== Introduction

N1QL includes a large number of xref:n1ql:n1ql-language-reference/index.adoc[operations and generic functions] that cover every aspect of data manipulation. 
In addition to the built-in functions, Couchbase also allows you to create your own extensions to the language using JavaScript.
Using JavaScript user-defined functions, you can:

* Create reuseable, domain-specific functions for use in your applications.
* Execute complex logic that may be difficult to do in N1QL.
* Migrate from RDBMS stored procedures.
* Use  N1QL statements embedded in your JavaScript to access and modify your data.

== JavaScript User-Defined Functions

Javascript functions in Couchbase support most of the language constructs available in https://en.wikipedia.org/wiki/ECMAScript[ECMAScript], though there are a number of restrictions related to the Couchbase environment. 
There are also additions that have been made to the language for working specifically in the Couchbase environment.

include::javascript-udfs:partial$libraries-and-scopes.adoc[leveloffset=+1, tags=!scoping-diagram]

== Next Steps

If you're looking to creating your own JavaScript libraries then there are number of guides to get you started.
 
* xref:create-javascript-library.adoc[]
* xref:call-user-defined-function.adoc[]

If you wish to look into the constructs and available in the language itself, then you can have a look through the following pages:

* xref:javascript-udfs:javascript-udfs.adoc[]
* xref:javascript-udfs:calling-javascript-from-n1ql.adoc[]
* xref:javascript-udfs:calling-n1ql-from-javascript.adoc[]
* xref:javascript-udfs:handling-errors-javascript-udf.adoc[]














