= User-defined Functions with JavaScript
:description: Extending the N1QL query language by adding your own functions written in JavaScript
:page-pagination: next
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2
:xrefstyle: short

[abstract]
{description}

== Introduction

include::javascript-udfs:partial$javascript-udf-introduction.adoc[]

== User-Defined Functions with JavaScript

When you use JavaScript for the User Defined Function, the JavaScript that is supported in Couchbase shares the same constructs of the https://en.wikipedia.org/wiki/ECMAScript[ECMAScript], though there are a number of restrictions and also extensions with the Couchbase JavaScript implementation.

== Next Steps

If you're looking to creating your own JavaScript libraries then there are number of guides to get you started.
 
* xref:create-javascript-library.adoc[]
* xref:call-user-defined-function.adoc[]

If you wish to look into the constructs and available in the language itself, then you can have a look through the following pages:

* xref:javascript-udfs:javascript-udfs.adoc[]
* xref:javascript-udfs:calling-javascript-from-n1ql.adoc[]
* xref:javascript-udfs:calling-n1ql-from-javascript.adoc[]
* xref:javascript-udfs:handling-errors-javascript-udf.adoc[]














