= Key Value Operations
:description: How to perform CRUD key value operations in Couchbase.
:page-pagination: next
:page-topic-type: guide
:page-toclevels: 2
:tabs:
:github: Click the GitHub button icon:github[] to view this code in context.

[abstract]
{description}

== Introduction

Every item in a database goes through the basic _CRUD_ cycle, which is typical of an application’s use of data.
CRUD stands for create, read, update, and delete:

* **C**reate: when data is first inserted into the cluster
* **R**ead: when an application retrieves the data
* **U**pdate: when data is modified to reflect a change in the state represented by the data
* **D**elete: when the data is no longer needed

The xref:learn:services-and-indexes/services/data-service.adoc[Key Value(KV) or Data Service] offers Couchbase clients the fastest and simplest way to create, retrieve or mutate data where the key is known.

include::partial$before-you-begin.adoc[]

include::partial$clients.adoc[]

The following examples demonstrate the basic CRUD operations.

== Creating Documents

Creating a document means inserting new data into the database.
The example below shows you how to insert a document with ID `airport-123`.

[{tabs}]
====
cbc::
+ 
-- 
Create the document _airport-123.json_.
It can be anywhere on your file system (i.e. /tmp):

[source,json]
----
include::example$kv/airport-123.json[]
----

Now, insert the document into Couchbase using the _cbc_ utility:

[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-simple-insert]
----

`airport-123` is the document’s ID, which is redirected (`<`) to the [.cmd]`cbc` command’s standard input.
--

Java::
+ 
--
[source,java,indent=0]
----
include::java-sdk:hello-world:example$KvHelloWorldDefault.java[tag=kv-simple-insert]
----

{github}
--

Node.js::
+ 
--
[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-default.js[tag=kv-simple-insert]
----

{github}
--
====

For more information, see xref:create-data.adoc[Create Data].

== Reading Documents

Documents can be retrieved using their IDs.
Retrieving a document by ID is extremely fast.
The following query takes about 1 millisecond.

[{tabs}]
====
cbc::
+ 
-- 
[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-simple-get]
----

.Result
[source,json]
----
include::example$kv/airport-123.json[]
----
--

Java::
+ 
--
[source,java,indent=0]
----
include::java-sdk:hello-world:example$KvHelloWorldDefault.java[tag=kv-simple-get]
----

{github}
--

Node.js::
+ 
--
[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-default.js[tag=kv-simple-get]
----

{github}
--
====

For more information, see xref:read-data.adoc[Read Data].

== Updating Documents

Updating a document means changing the existing data with different or new values. 
The example below shows how to update the `country` field from the `airport-123` document.

[{tabs}]
====
cbc::
+ 
-- 
Take the file from the previous section and edit the `country` field:

....
    ...
    "country": "United States"
    ....
....

Then use the [.cmd]`cbc` tool to update the document in Couchbase:

[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-simple-update]
----
--

Java::
+ 
--
[source,java,indent=0]
----
include::java-sdk:hello-world:example$KvHelloWorldDefault.java[tag=kv-simple-update]
----

{github}
--

Node.js::
+ 
--
[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-default.js[tag=kv-simple-update]
----

{github}
--
====

For more information, see xref:update-data.adoc[Update Data].

== Deleting Documents

When data is no longer required we can perform a delete operation to permanently remove a document.
In this example we delete the document with ID `airport-123`.

[{tabs}]
====
cbc::
+ 
--

[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-simple-delete]
----
--

Java::
+ 
--
[source,java,indent=0]
----
include::java-sdk:hello-world:example$KvHelloWorldDefault.java[tag=kv-simple-delete]
----

{github}
--

Node.js::
+ 
--
[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-default.js[tag=kv-simple-delete]
----

{github}
--
====

For more information, see xref:delete-data.adoc[Delete Data].
