= Key Value Operations
:description: How to perform CRUD key value operations on Couchbase documents.
:page-pagination: next
:page-topic-type: guide
:page-toclevels: 2
:tabs:
:github: Click the GitHub button icon:github[] to view this code in context.

[abstract]
{description}

== Introduction

Every item in a database goes through the basic _CRUD_ cycle, which is typical of an application’s use of data.
CRUD stands for create, read, update, and delete:

* **C**reate: when data is first inserted into the cluster
* **R**ead: when an application retrieves the data
* **U**pdate: when data is modified to reflect a change in the state represented by the data
* **D**elete: when the data is no longer needed

The Couchbase xref:learn:services-and-indexes/services/data-service.adoc[Key Value(KV) or Data Service] offers the fastest and simplest way to create, retrieve or mutate data where the key is known.

include::partial$before-you-begin.adoc[]

include::partial$data-tools.adoc[]

== Create Data

Couchbase stores its xref:learn:data/data.adoc[data] as either JSON or Binary _documents_ with unique IDs(primary keys) by which they can be located.

Documents are organized and grouped in _buckets_ using xref:learn:data/scopes-and-collections.adoc[scopes and collections]. If a scope or collection is not provided when creating a document, Couchbase will automatically store data in the `_default` collection or `_default` scope.

TIP: We highly recommend that you provide user-defined scopes and collections to logically group your data.

To create a document you can perform an `insert` operation.

[{tabs}]
====
cbc::
+ 
-- 
.Insert
An example JSON document called `airport-123.json` is used here to represent our data.

[source,json]
----
include::example$kv/airport-123.json[]
----

Using the `cbc create` command with `--mode insert` we create the document in the `travel-sample.inventory.airport` keyspace.

[source,shell,indent=0]
----
include::example$kv/kv-cbc.sh[tag=cbc-kv-insert]
----

`airport-123` is the document’s ID, which is redirected (`<`) to the [.cmd]`cbc` command’s standard input.

.Result
[source,console]
----
airport-123          Stored. CAS=0x16b37e5081690000
                     SYNCTOKEN=829,51260943619833,92
----

.Insert (with options)
The `cbc create` command also allows you to set options like a document's expiry time.
In this example, we insert a new document and set it to expire after 60 seconds.

[source,shell,indent=0]
----
include::example$kv/kv-cbc.sh[tag=cbc-kv-insert-expiry]
----

.Result
[source,console]
----
airport-456          Stored. CAS=0x16b5dc9223f30000
                     SYNCTOKEN=733,211618429638288,95
----

NOTE: If the document already exists, Couchbase will return a `LCB_ERR_DOCUMENT_EXISTS` error. 
--

Node.js::
+ 
--
.Insert
The following example uses the `insert()` function to create a single document in the `travel-sample.inventory.airport` keyspace.

[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world.js[tag=kv-insert]
----

A `MutationResult` promise is returned containing the result and metadata relevant to the insert operation.

.Insert (with options)
It is also possible to perform an `insert()` with options. For example, we can set an expiry time to ensure a document is no longer available after 60 seconds.

[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world.js[tag=kv-insert-with-opts]
----

NOTE: If the document already exists, Couchbase will return a `DocumentExistsError` error. 

{github}
--
====

When a document is created, Couchbase assigns it a xref:java-sdk:howtos:concurrent-document-mutations.adoc[CAS(Compare And Swap)] value to keep track of the document’s state within the database. 
Each time a document is mutated the CAS will change accordingly. This unique value allows the database to protect against concurrent updates to the same document.

== Read Data

Retrieving documents by ID is the fastest and simplest way to read data in Couchbase.
The Data Service allows you to retrieve a full document when you need to fetch all of the data stored. However, in instances where this can be costly and unnecessary, Couchbase allows you to access only specific _paths_ within a document as well.

=== Full Documents

To read a full document you can perform a simple `get` operation.

[{tabs}]
====
cbc::
+ 
--
.Get
The `cbc cat` command allows you to retrieve a document by ID and output its content to the console.
For example, in the example below, we retrieve the `airport-123` document from the `travel-sample.inventory.airport` keyspace.

[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-kv-get]
----

.Result
[source,json]
----
include::example$kv/airport-123.json[]
----

Note that the output has been prettified for readability.

NOTE: If the document cannot be found, `cbc` will return a `LCB_ERR_DOCUMENT_NOT_FOUND` error. 
--

Node.js::
+ 
--
.Get
The following example uses the `get()` function to retrieve a document by ID from the `travel-sample.inventory.airport` keyspace.

[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world.js[tag=kv-get]
----

When fetching data, the SDK will deserialize the JSON document into a native data type that can be later manipulated. 

A `GetResult` promise is returned containing the deserialized `content`, the `cas` value, and other valuable metadata.

.Get (with options)
Using the same `get()` function, we can pass additional options when reading data from the database.

As an example, the code below shows how you can set a `withExpiry` option to indicate that expiry time metadata should be fetched alongside a document.

[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world.js[tag=kv-get-with-opts]
----

NOTE: If the document doesn't exists, Couchbase will return a `DocumentNotFoundError` error. 

{github}
--
====

=== Sub-Documents

JSON documents can contain a lot of nested data -- which might not necessarily need to be accessed all at once. Reading full documents to access a field or two is not ideal and could cause performance issues in your application. Instead, it is better practice to access specific paths, or _sub-documents_, to perform more efficient read operations.

To read portions of JSON document we can perform a sub-document `get` operation.

[{tabs}]
====
cbc-subdoc::
+ 
--
.airport_1254
[source,json]
----
{
  "id": 1254,
...
  "geo": {
    "lat": 50.962097,
    "lon": 1.954764,
    "alt": 12
  }
}
----

.Get
The `cbc-subdoc get` command allows you to access specific paths in a JSON document using the `--path` argument. 
For example, in the snippet below, we narrow down a get operation to only read the `geo` data from the `airport_1254` document.

[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-subdoc-get]
----

.Result
[source,console]
----
airport_1254         CAS=0x16b46197cae90000
0. Size=43, RC=LCB_SUCCESS (0)
{"lat":50.962097,"lon":1.954764,"alt":12.0}
----

As expected, only the nested `geo` data is returned in the result.

NOTE: If the path cannot be found, `cbc-subdoc` will return a `LCB_ERR_SUBDOC_PATH_NOT_FOUND` error. 
--

Node.js::
+ 
--
.Get
// The following example uses the `get()` function to retrieve a document by ID from the `travel-sample.inventory.airport` keyspace.

// [source,nodejs,indent=0]
// ----
// include::nodejs-sdk:hello-world:example$kv-hello-world.js[tag=kv-get]
// ----

// When fetching data, the SDK will deserialize the JSON document into a native data type that can be later manipulated. 

// A `GetResult` promise is returned containing the deserialized `content`, the `cas` value, and other valuable metadata.

// .Get (with options)
// Using the same `get()` function, we can pass additional options when reading data from the database.

// As an example, the code below shows how you can set a `withExpiry` option to indicate that expiry time metadata should be fetched alongside a document.

// [source,nodejs,indent=0]
// ----
// include::nodejs-sdk:hello-world:example$kv-hello-world.js[tag=kv-get-with-opts]
// ----

NOTE: If the path doesn't exists, Couchbase will return a `` error. 

{github}
--
====


== Update Data

// Updating a document means changing the existing document.
// For example, take the file above and edit the `likes` field:

// ....
//     ...
//     "likes": ["dogs", "pastries", "couchbase"]
//     ....
// ....

// Then use the [.cmd]`cbc` tool to update the document in Couchbase:

//  $ cbc create --mode replace josmith < josmith.json

// == Deleting documents

// This example shows how to delete the document with the ID `josmith`.

//  $ cbc rm josmith

// == Couchbase clients

== Delete Data


== Bulk Operations


== Durable Operations 


== Related Links

// In-depth explanation:

// * xref:n1ql:n1ql-language-reference/selectintro.adoc[SELECT]

// Reference:

// * xref:n1ql:n1ql-language-reference/select-syntax.adoc[SELECT Syntax]

// Tutorials:

// * https://query-tutorial.couchbase.com/tutorial/#1[N1QL Query Language Tutorial^]

Key Value Operations with SDKs:

* xref:c-sdk:howtos:kv-operations.adoc[C]
| xref:dotnet-sdk:howtos:kv-operations.adoc[.NET]
| xref:go-sdk:howtos:kv-operations.adoc[Go]
| xref:java-sdk:howtos:kv-operations.adoc[Java]
| xref:nodejs-sdk:howtos:kv-operations.adoc[Node.js]
| xref:php-sdk:howtos:kv-operations.adoc[PHP]
| xref:python-sdk:howtos:kv-operations.adoc[Python]
| xref:ruby-sdk:howtos:kv-operations.adoc[Ruby]
| xref:scala-sdk:howtos:kv-operations.adoc[Scala]
