= Key-Value Operations
:description: How to perform CRUD key-value operations in Couchbase.
:page-pagination: next
:page-topic-type: guide
:page-toclevels: 2

[abstract]
{description}

== Introduction

Every item in a database goes through the basic _CRUD_ cycle, which is typical of an application’s use of data.
CRUD stands for create, read, update, and delete:

* **C**reate: when data is first inserted into the cluster
* **R**ead: when an application retrieves the data
* **U**pdate: when data is modified to reflect a change in the state represented by the data
* **D**elete: when the data is no longer needed

The xref:learn:services-and-indexes/services/data-service.adoc[Key-Value (KV) or Data Service] offers Couchbase clients the fastest and simplest way to create, retrieve or mutate data where the key is known.

include::partial$before-you-begin.adoc[]

include::partial$clients.adoc[]


== Next Steps

Key-Value Operations guides:

* xref:creating-data.adoc[Creating Data]
* xref:reading-data.adoc[Reading Data]
* xref:updating-data.adoc[Updating Data]
* xref:deleting-data.adoc[Deleting Data]
* xref:bulk-operations.adoc[Bulk Operations]
