= Read Data
:description: How to read documents in Couchbase.
:page-pagination: full
:page-topic-type: guide
:tabs:
:github: Click the GitHub button icon:github[] to view this code in context.

[abstract]
{description}

Retrieving documents by ID is the fastest and simplest way to read data in Couchbase.
The Data Service allows you to retrieve a full document when you need to fetch all of the data stored. However, in instances where this can be costly and unnecessary, Couchbase allows you to access only specific _paths_ within a document as well.

== Full Documents

To read a single document in Couchbase you can perform a `get` operation.

[{tabs}]
====
cbc::
+ 
--
.Get
The `cbc cat` command allows you to retrieve a document by ID and output its content to the console.
For example, in the example below, we retrieve the `airport-123` document from the `travel-sample.inventory.airport` keyspace.

[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-kv-get]
----

.Result
[source,json]
----
include::example$kv/airport-123.json[]
----

Note that the output has been prettified for readability.

NOTE: If the document cannot be found, `cbc` will return a `LCB_ERR_DOCUMENT_NOT_FOUND` error. 
--

Node.js::
+ 
--
.Get
The following example uses the `get()` function to retrieve a document by ID from the `travel-sample.inventory.airport` keyspace.

[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-get]
----

When fetching data, the SDK will deserialize the JSON document into a native data type that can be later manipulated. 

A `GetResult` promise is returned containing the deserialized `content`, the `cas` value, and other valuable metadata.

.Get (with options)
Using the same `get()` function, we can pass additional options when reading data from the database.

As an example, the code below shows how you can set a `withExpiry` option to indicate that expiry time metadata should be fetched alongside a document.

[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-get-with-opts]
----

NOTE: If the document doesn't exists, Couchbase will return a `DocumentNotFoundError` error. 

{github}
--
====

== Sub-Documents

JSON documents can contain a lot of nested data -- which might not necessarily need to be accessed all at once. Reading full documents to access a field or two is not ideal and could cause performance issues in your application. Instead, it is better practice to access specific paths, or _sub-documents_, to perform more efficient read operations.

To read specific fields or document paths we can perform a sub-document `get` operation.

.airport_1254
[source,json]
----
{
  "id": 1254,
  ...
  "geo": {
    "lat": 50.962097,
    "lon": 1.954764,
    "alt": 12
  }
}
----

[{tabs}]
====
cbc-subdoc::
+ 
--
.Sub-Document Get
The `cbc-subdoc get` command allows you to access specific paths in a JSON document using the `--path` argument. 

For example, in the snippet below, we fetch only the `geo` data from the `airport_1254` document.

[source,shell]
----
include::example$kv/kv-cbc.sh[tag=cbc-subdoc-get]
----

.Result
[source,console]
----
airport_1254         CAS=0x16b46197cae90000
0. Size=43, RC=LCB_SUCCESS (0)
{"lat":50.962097,"lon":1.954764,"alt":12.0}
----

As expected, only the nested `geo` data is returned in the result.

NOTE: If the path cannot be found, `cbc-subdoc` will return a `LCB_ERR_SUBDOC_PATH_NOT_FOUND` error. 
--

Node.js::
+ 
--
.Sub-Document Get
To fetch a specific field inside a document, you can call the `lookup-in()` function. This function takes a document ID and `LookUpInSpec` as arguments. 

`LookUpInSpec` represents the sub-operation you want to perform within the lookup -- which in this case is a `get` operation.

For example, in the snippet below, we fetch only the `geo` data from the `airport_1254` document.

[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-get-subdoc]
----

A `LookupInResult` promise is returned containing the result and metadata relevant to the get operation.

{github}
--
====

== Related Links

Key Value Operations with SDKs:

* xref:c-sdk:howtos:kv-operations.adoc[C]
| xref:dotnet-sdk:howtos:kv-operations.adoc[.NET]
| xref:go-sdk:howtos:kv-operations.adoc[Go]
| xref:java-sdk:howtos:kv-operations.adoc[Java]
| xref:nodejs-sdk:howtos:kv-operations.adoc[Node.js]
| xref:php-sdk:howtos:kv-operations.adoc[PHP]
| xref:python-sdk:howtos:kv-operations.adoc[Python]
| xref:ruby-sdk:howtos:kv-operations.adoc[Ruby]
| xref:scala-sdk:howtos:kv-operations.adoc[Scala]

Sub-Document operations with SDKs:

* xref:c-sdk:howtos:subdocument-operations.adoc[C]
| xref:dotnet-sdk:howtos:subdocument-operations.adoc[.NET]
| xref:go-sdk:howtos:subdocument-operations.adoc[Go]
| xref:java-sdk:howtos:subdocument-operations.adoc[Java]
| xref:nodejs-sdk:howtos:subdocument-operations.adoc[Node.js]
| xref:php-sdk:howtos:subdocument-operations.adoc[PHP]
| xref:python-sdk:howtos:subdocument-operations.adoc[Python]
| xref:ruby-sdk:howtos:subdocument-operations.adoc[Ruby]
| xref:scala-sdk:howtos:subdocument-operations.adoc[Scala]
