= Select Data with N1QL
:page-topic-type: guide
:imagesdir: ../../assets/images
:tabs:
:description: How to use a N1QL selection query to read data from a data source and return results.
:github: Click the GitHub button icon:github[] to view this code in context.

[abstract]
{description}

== Introduction

The xref:n1ql:query.adoc[Query Service] enables you to create, read, update, and delete data by means of xref:n1ql:n1ql-language-reference/index.adoc[N1QL], the Couchbase Server query language.
To read data from a data source using N1QL, you must use a selection query; that is, a query using the `SELECT` statement.

include::partial$before-you-begin.adoc[]

include::partial$query-tools.adoc[tags=!rest]

== Selecting

A selection query enables you to read information from a data source, perform operations on the data, and return the results.

To specify what the query should return, use the SELECT clause.

[{tabs}]
====
N1QL::
+
--
The following example uses the SELECT clause by itself to evaluate an expression.

.Query
[source,n1ql]
----
include::example$query/select-clause.n1ql[]
----

.Result
[source,json]
----
include::example$query/select-clause.jsonc[]
----
--

.NET::
+
--
The following example uses the `Cluster.QueryAsync<T>` method to execute the query.
The result includes each row found.

[source,csharp]
----
include::dotnet-sdk:hello-world:example$StartUsing.cs[tag=n1ql-query,indent=0]
----

{github}
--

Java::
+
--
The following example uses the `query()` method to execute the query.
The result object includes each row found.

[source,java]
----
include::java-sdk:hello-world:example$StartUsing.java[tag=n1ql-query,indent=0]
----

{github}
--

Node.js::
+
--
The following example uses the `query()` function to execute a query.
The result object includes an array of rows found.

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$n1ql-hello-world.js[tag=n1ql-query,indent=0]
----

{github}
--

Python::
+
--
The following example uses the `query()` function to execute a query.
The result object includes an array of rows found.

[source,python]
----
include::python-sdk:hello-world:example$n1ql_hello_world.py[tag=n1ql-query,indent=0]
----

{github}
--
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/selectclause.adoc[SELECT Clause].

== Specifying a Data Source

To specify the data source for a query, use the FROM clause.
For example, to get data from a collection, specify the path to that collection.

When you specify a FROM clause, you can use the SELECT clause to specify the fields that you want to return from that data source.
The set of fields returned by the query is known as the _projection_.

====
The following query gets the name and city of every airport.

.Query
[source,n1ql]
----
include::example$query/from-clause.n1ql[]
----

.Result
[source,json]
----
include::example$query/from-clause.jsonc[tags=extract;ellipsis]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/from.adoc[FROM Clause].

== Filtering

To filter the results of the query, use the WHERE clause to specify a comparison expression.
Only records that satisfy the comparison expression are returned.

====
For example, the following query finds the name and city of every airport in the Anchorage timezone whose altitude is greater than or equal to 2100.

.Query
[source,n1ql]
----
include::n1ql:example$select/query-keyspace-idx.n1ql[]
----

.Result
[source,json]
----
include::n1ql:example$select/query-keyspace-idx.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/where.adoc[WHERE Clause].

== Limiting Results

To limit the number of documents returned by a query, use the `LIMIT` clause.

====
For example, the following query finds only 2 hotels with an empty room.

.Query
[source,n1ql]
----
include::n1ql:example$select/limit-number.n1ql[]
----

.Result
[source,json]
----
include::n1ql:example$select/limit-result.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/limit.adoc[LIMIT Clause].

== Ordering Results

To sort the documents in the resultset by one or more fields, use the `ORDER BY` clause.

====
For example, the following query lists cities in descending order and then landmarks in ascending order.

.Query
[source,n1ql]
----
include::n1ql:example$select/order-by.n1ql[]
----

.Results:
[source,json]
----
include::n1ql:example$select/order-by.jsonc[]
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/orderby.adoc[ORDER BY Clause].

== Next Steps

* xref:join.adoc[Querying Across Relationships]

== Related Links

In-depth explanation:

* xref:n1ql:n1ql-language-reference/selectintro.adoc[SELECT]

Reference:

* xref:n1ql:n1ql-language-reference/select-syntax.adoc[SELECT Syntax]

Tutorials:

* https://query-tutorial.couchbase.com/tutorial/#1[N1QL Query Language Tutorial^]

Querying with SDKs:

* xref:c-sdk:howtos:n1ql-queries-with-sdk.adoc[C]
| xref:dotnet-sdk:howtos:n1ql-queries-with-sdk.adoc[.NET]
| xref:go-sdk:howtos:n1ql-queries-with-sdk.adoc[Go]
| xref:java-sdk:howtos:n1ql-queries-with-sdk.adoc[Java]
| xref:nodejs-sdk:howtos:n1ql-queries-with-sdk.adoc[Node.js]
| xref:php-sdk:howtos:n1ql-queries-with-sdk.adoc[PHP]
| xref:python-sdk:howtos:n1ql-queries-with-sdk.adoc[Python]
| xref:ruby-sdk:howtos:n1ql-queries-with-sdk.adoc[Ruby]
| xref:scala-sdk:howtos:n1ql-queries-with-sdk.adoc[Scala]

