= Selecting Indexes
:page-topic-type: guide
:imagesdir: ../assets/images
:tabs:
:page-pagination:
:description: How to select an index for a query.

[abstract]
{description}

== Introduction

Couchbase Server attempts to select an appropriate secondary index for a query, based on the filters in the WHERE clause.
If it cannot select a secondary query, the query service falls back on the the primary index for the keyspace, if one exists.

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

== Specifying Predicates to Select an Index

To specify an index using query predicates, specify the leading query predicates in the WHERE clause in the same order as the index keys in the index.

TIP: Use `IS NOT MISSING` as the predicate for any fields which are required by the index, but which are not actually used for filtering data in the query.

For further details and examples, refer to xref:n1ql:n1ql-language-reference/selectintro.adoc.adoc#index-selection[Index Selection].

====
The following query creates a secondary index on the `image_direct_url` field in the `landmark` keyspace.

[source,N1QL]
----
include::n1ql:example$n1ql-language-reference/create-idx-predicate.n1ql[]
----

The following query uses a minimal filter on the `image_direct_url` field to select the `idx_image_direct_url` index.

[source,N1QL]
----
include::n1ql:example$n1ql-language-reference/select-idx-filter.n1ql[]
----
====

== Specifying an Index Hint

You can use an index hint to specify that a query should use a particular index.
The index must be applicable to the query.

To specify an index by name:

. Use the USE clause within the FROM clause.

. Specify the index name in parentheses.

====
The following query creates an index of airlines and destination airports.

[source,n1ql]
----
include::n1ql:example$n1ql-language-reference/create-idx-hints.n1ql[]
----

The following query uses an index hint to select the `idx_destinations` index.

[source,n1ql]
----
include::n1ql:example$n1ql-language-reference/select-idx-hints.n1ql[]
----
====

For further details and examples, refer to xref:n1ql:n1ql-language-reference/hints.adoc[USE Clause].

== Related Links

Reference and explanation:

* xref:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[Using Indexes]
* xref:n1ql:n1ql-language-reference/selectintro.adoc[SELECT]
* xref:n1ql:n1ql-language-reference/select-syntax.adoc[SELECT Syntax]

Administrator guides:

* xref:manage:manage-indexes/manage-indexes.adoc[Manage Indexes]
* xref:manage:monitor/monitoring-indexes.adoc[Monitor Indexes]

Tutorials:

* https://query-tutorial.couchbase.com/tutorial/#1[N1QL Query Language Tutorial^]

Querying with SDKs:

* xref:c-sdk:howtos:n1ql-queries-with-sdk.adoc[C]
| xref:dotnet-sdk:howtos:n1ql-queries-with-sdk.adoc[.NET]
| xref:go-sdk:howtos:n1ql-queries-with-sdk.adoc[Go]
| xref:java-sdk:howtos:n1ql-queries-with-sdk.adoc[Java]
| xref:nodejs-sdk:howtos:n1ql-queries-with-sdk.adoc[Node.js]
| xref:php-sdk:howtos:n1ql-queries-with-sdk.adoc[PHP]
| xref:python-sdk:howtos:n1ql-queries-with-sdk.adoc[Python]
| xref:ruby-sdk:howtos:n1ql-queries-with-sdk.adoc[Ruby]
| xref:scala-sdk:howtos:n1ql-queries-with-sdk.adoc[Scala]
