= Couchbase Transactions
:page-topic-type: guide
:imagesdir: ../assets/images
:tabs:
:description: How to create Couchbase transactions using N1QL.
:github: Click the GitHub button icon:github[] to view this code in context.

[abstract]
{description}

Use Couchbase transactions to perform ACID (atomic, consistent, isolated, and durable) actions on your database.

You can use N1QL or an SDK with Couchbase transactions. 
For more information on how to use an SDK with Couchbase transactions, see the <<related-links>> section.

You can only use Data Modification Language (DML) statements inside a transaction:

* xref:n1ql:n1ql-language-reference/insert.adoc[INSERT]
* xref:n1ql:n1ql-language-reference/upsert.adoc[UPSERT]
* xref:n1ql:n1ql-language-reference/delete.adoc[DELETE]
* xref:n1ql:n1ql-language-reference/update.adoc[UPDATE]
* xref:n1ql:n1ql-language-reference/merge.adoc[MERGE]
* xref:n1ql:n1ql-language-reference/select.adoc[SELECT]
* xref:n1ql:n1ql-language-reference/execfunction.adoc[EXECUTE FUNCTION]
* xref:n1ql:n1ql-language-reference/prepare.adoc[PREPARE]
* xref:n1ql:n1ql-language-reference/execute.adoc[EXECUTE]

TIP: For a walkthrough of an example transaction with each query tool, see xref:n1ql:n1ql-language-reference/transactions-walkthrough.adoc[].

[[settings]]
== Transaction Parameters

You can change settings and parameters to control how transactions work.
Change transaction settings and parameters with any Query tool, such as the Query Workbench or the cbq shell.

[tabs]
====
Query Workbench::
+
--
To set parameters for a Couchbase transaction, use the Query Run-Time Preferences window.

. To open the *Run-Time Preferences* window, click btn:[Settings] (icon:cog[]).

. Change any of the available settings in the *Query Preferences* window. 
For more information about the available settings, see xref:guides/query.adoc#query-preferences[Query Preferences].

. Click btn:[Save Preferences].

--

CBQ Shell::
+
--
To specify parameters for a Couchbase transaction, use the `\SET` command.

For more information about the available settings and parameters for transactions, see xref:n1ql:n1ql-language-reference/transactions.adoc#settings-and-parameters[Settings and Parameters].
--
====

[[single-statement]]
== Single Statement Transactions

You can create a Couchbase transaction containing a single DML statement.

[tabs]
====
Query Workbench::
+
--
To execute a single statement as a transaction, simply enter the statement in the Query Editor and click btn:[Run as TX].

[source,n1ql]
----
include::n1ql:example$transactions/single.n1ql[tag=query]
----
--

CBQ Shell::
+
--
To execute a single statement as a transaction, set the `tximplicit` parameter to `true`.

[source,n1ql]
----
include::n1ql:example$transactions/single.n1ql[tags=**]
----
--
====

For more information, see xref:n1ql:n1ql-language-reference/transactions.adoc#query-tools[Query Tools].

[[multiple-statement]]
== Multiple Statement Transactions
:co-txid: After beginning the transaction, each subsequent statement in the transaction must specify the transaction ID that was generated when the transaction began.
:result: When the transaction is committed, the document is added with the attributes that were present after rolling back to the second savepoint.
:lead: The following example demonstrates a complete transaction using N1QL. \
Individual N1QL transaction statements are described in the sections below.

A Couchbase transaction can have multiple DML statements.
To create a transaction with multiple DML statements, use N1QL transaction statements:

* Use <<begin,BEGIN TRANSACTION>> to start the transaction.
* Use <<set,SET TRANSACTION>> to specify transaction settings.
* Use <<savepoint,SAVEPOINT>> to set a transaction savepoint.
* Use <<rollback,ROLLBACK TRANSACTION>> to roll back a transaction.
* Use <<commit,COMMIT TRANSACTION>> to commit a transaction.

[tabs]
====
Query Workbench::
+
--
To execute a transaction containing multiple statements:

. Enter the first statement of your transaction in the Query Editor.

. End the statement with a semicolon. 

. Press press kbd:[Shift+Enter] to start a new line. 

. Repeat Steps 1-2 until you've entered the entire transaction. 

. To execute the transaction, click btn:[Execute].

--

CBQ Shell::
+
--
To execute a transaction containing multiple statements, enter one statement at a time.

Once you start a transaction, your cbq shell session assumes all statements are part of the same transaction until you rollback or commit the transaction.

NOTE: You must be using cbq shell version 2.0 or above to use the automatic transaction ID functionality.

--
====

For more information on how to use each query tool with transactions, see xref:n1ql:n1ql-language-reference/transactions.adoc#query-tools[Query Tools].

[[begin]]
=== Begin a Transaction

To start a transaction, use the `BEGIN TRANSACTION` statement.

====
The following statement begins a transaction and returns the transaction ID.

[source,n1ql]
----
include::n1ql:example$transactions/multiple.n1ql[tag=begin]
----

{github}

.Result
[source.no-callouts,json,indent=0]
----
include::n1ql:example$transactions/results.jsonc[tag=begin]
----

====

For more information on the `BEGIN TRANSACTION` statement, see xref:n1ql:n1ql-language-reference/begin-transaction.adoc[BEGIN TRANSACTION].

[[set]]
=== Specify Transaction Settings

To set optional transaction settings, use the `SET TRANSACTION` statement.

NOTE: Currently, the only available transaction setting is "isolation level read committed".
This setting is enabled by default.

====
The following statement specifies transaction settings.

[source,n1ql]
----
include::n1ql:example$transactions/multiple.n1ql[tag=set]
----

{github}
====

For more information on the `SET TRANSACTION` statement, see xref:n1ql:n1ql-language-reference/set-transaction.adoc[SET TRANSACTION].

[[savepoint]]
=== Set a Savepoint

To set a savepoint within a transaction, use the `SAVEPOINT` statement and specify a name for the savepoint.

====
The following statement sets a savepoint.

[source,n1ql]
----
include::n1ql:example$transactions/multiple.n1ql[tag=savepoint-1]
----

{github}
====

For more information on the `SAVEPOINT` statement, see xref:n1ql:n1ql-language-reference/savepoint.adoc[SAVEPOINT].

[[rollback]]
=== Roll Back a Transaction

To roll back a transaction, use the `ROLLBACK TRANSACTION` statement.

By default, this statement rolls back the entire transaction.
If you want to roll back to a savepoint, use the `TO SAVEPOINT` keyword and specify the savepoint name.

====
The following statement rolls back a transaction to a specified savepoint.

[source,n1ql]
----
include::n1ql:example$transactions/multiple.n1ql[tag=rollback]
----

{github}
====

For more information on the `ROLLBACK TRANSACTION` statement, see xref:n1ql:n1ql-language-reference/rollback-transaction.adoc[ROLLBACK TRANSACTION].

[[commit]]
=== Commit a Transaction

To commit a transaction, use the `COMMIT TRANSACTION` statement.

====
The following statement commits a transaction.

[source,n1ql]
----
include::n1ql:example$transactions/multiple.n1ql[tag=commit]
----

{github}
====

For more information on the `COMMIT TRANSACTION` statement, see xref:n1ql:n1ql-language-reference/commit-transaction.adoc[COMMIT TRANSACTION].

[[related-links]]
== Related Links

Reference and explanation:

* xref:learn:data/transactions.adoc[]
* xref:n1ql:n1ql-language-reference/transactions.adoc[]
* xref:n1ql:n1ql-language-reference/transactions-walkthrough.adoc[]

Online transaction simulator:

* https://transactions.couchbase.com[Query Transaction Simulator^]

Transactions with SDKs:

* xref:java-sdk:howtos:distributed-acid-transactions-from-the-sdk.adoc[]
* xref:cxx-txns::distributed-acid-transactions-from-the-sdk.adoc[]
* xref:dotnet-sdk:howtos:distributed-acid-transactions-from-the-sdk.adoc[]
* xref:go-sdk:howtos:distributed-acid-transactions-from-the-sdk.adoc[]
* xref:nodejs-sdk:howtos:distributed-acid-transactions-from-the-sdk.adoc[]
