= Create User-Defined Functions in N1QL
:page-topic-type: guide
:imagesdir: ../../assets/images
:tabs:
:description: How to create and use user-defined functions.

[abstract]
{description}

== Before You Begin

If you want to try out the examples in this section, follow the instructions given in xref:getting-started:do-a-quick-install.adoc[Do a Quick Install] to install Couchbase Server, configure a cluster, and load a sample dataset.

== Query Tools

Read the following for further information about the tools available for editing and executing queries:

* xref:tools:cbq-shell.adoc[cbq: The Command Line Shell for N1QL]
* xref:tools:query-workbench.adoc[Query Workbench]

== Create an Internal User-Defined Function

.To create an inline function for N1QL:

* Use the `CREATE FUNCTION` statement with the `LANGUAGE INLINE` keywords.
For example:
+
====
[source,n1ql]
----
CREATE FUNCTION celsius(...) LANGUAGE INLINE AS (args[0] - 32) * 5/9;
----
====

* Alternatively, use the `CREATE FUNCTION` statement with the braces syntax.
For example:
+
====
[source,n1ql]
----
CREATE FUNCTION fahrenheit(...) { (args[0] * 9/5) + 32 };
----
====

For more information and examples, refer to xref:n1ql:n1ql-language-reference/createfunction.adoc[CREATE FUNCTION].

== Create an External User-Defined Function

.To create an external user-defined function for N1QL:

. Write the functions in JavaScript.

. Use the Functions REST API to add the functions to a function library.
For example:
+
====
[source,shell]
----
curl -X POST \
http://localhost:8093/evaluator/v1/libraries/math \
-u Administrator:password \
-H 'content-type: application/json' \
-d 'function add(a, b) { let data = a + b; return data; }
    function sub(a, b) { let data = a - b; return data; }'
----
====
+
For more information and examples, refer to xref:n1ql-rest-api/functions.adoc[Functions REST API].

. Create the function using the `CREATE FUNCTION` command with the `LANGUAGE JAVA` keywords.
+
====
[source,n1ql]
----
CREATE FUNCTION javaScriptAdd(augend, addend)
  LANGUAGE JAVASCRIPT AS "add" AT "math";

CREATE FUNCTION javaScriptSubtract(minuend, subtrahend)
  LANGUAGE JAVASCRIPT AS "sub" AT "math";
----
====
+
For more information and examples, refer to xref:n1ql:n1ql-language-reference/createfunction.adoc[CREATE FUNCTION].

== Global Functions and Scope Functions

Aliqua incididunt et ex deserunt cillum sunt elit ad mollit proident. Dolore quis proident commodo tempor velit ea aliqua. Tempor ullamco voluptate est do minim proident velit est ad velit minim reprehenderit culpa. Id eu laboris quis dolore ipsum ea cillum reprehenderit occaecat irure qui proident proident. Eiusmod cupidatat nostrud in fugiat duis nostrud eiusmod eu aute exercitation laborum aute incididunt. Amet id irure exercitation anim. Qui eu et consequat do adipisicing ea ex culpa quis amet aliqua qui ex.

== Arguments

Fugiat nisi labore aliqua est adipisicing eiusmod Lorem qui velit esse nisi labore quis. Nisi minim ipsum labore exercitation minim reprehenderit labore sunt ut ullamco adipisicing. Labore exercitation in ea tempor fugiat laborum minim laboris elit.

== Next Steps

* Use User-Defined Functions in N1QL

== Related Links

User-Defined Functions in the Analytics Service:

* Overview
* N1QL for Analytics Language Reference
* Evaluator REST API

User-Defined Functions in the Eventing Service:

* Eventing Lifecycle
* Eventing REST API