= Manage User and Groups Access to Credentials
:description: Once you have created credentials in the credential store, you can grant users and groups access to them.
:page-toclevels: 2
:page-edition: Enterprise Edition

[abstract]
{description}

[#overview]
== Overview

* You assign users and groups the *Credential Consumer* role and list which credentials they can access.
* You can also grant a service direct access to a credential, without requiring a user's permission.
For more information, see *Grant Services Access to Credentials*.
* You can use wildcards to grant users access to multiple matching credentials.
For more information, see xref:learn:security/roles.adoc#roles-parameter-lists[Role Parameter Lists].

[#prerequisites]
== Prerequisites

* Your cluster must have the credential store enabled.
For more information, see xref:manage-security/manage-credentials/manage-credential-store.adoc[].
* You must have the xref:learn:security/roles.adoc#full-admin[Full Admin] or xref:learn:security/roles.adoc#security-admin[Security Admin] role.

[#grant-access-web-console]
== Grant Users and Groups Access to Credentials Using the Web Console

[#add-role-to-user]
=== Add the Credential Consumer Role to a User

. Go to menu:Security[Users & Groups].
. Click btn:[Add User], or click an existing user's entry and click btn:[Edit].
. In the *Roles* list, add the *Credential Consumer* role.
. In the *Credential Consumer* role's parameter list, specify the ID of each credential the user can access.
You can also specify a wildcard pattern to match multiple credentials.
For more information, see xref:learn:security/roles.adoc#roles-parameter-lists[Role Parameter Lists].
. Click btn:[Save].

Granting the *Credential Consumer* role to a group works the same way.
Go to menu:Security[Users & Groups], select an existing group or create a new one, and add the *Credential Consumer* role with the credentials the group's members can access.

[#grant-access-rest-api]
== Grant Users and Groups Access to Credentials Using the REST API

[#grant-user-rest-api]
=== Grant a User Access to a Credential

To grant a user access to 1 or more credentials, make a `PUT` request to `/settings/rbac/users/[local|external]/<USERNAME>` and add the `credential_consumer` role to the `roles` parameter.
List the credentials the user can access in the role's parameter list.

CAUTION: Updating a user's roles using the REST API is a full-replacement operation.
If you want to add the `credential_consumer` role for an existing user, include a copy of their current roles in the request.
Otherwise, Couchbase Server removes any roles you don't include.

For more information about creating and managing users, see xref:manage-security/manage-users-and-roles.adoc#create-a-local-user-with-the-rest-api[Create a Local User Using the REST API] and xref:manage-security/manage-users-and-roles.adoc#adding-roles[Assign Roles to a User].

[#example-grant-user-rest-api]
==== Example

The following example creates a user, `analyst1`, and grants them the `query_select` role and the `credential_consumer` role for a credential used with a REST API endpoint:

[source,bash]
----
curl -u $USER:$PASSWORD -X PUT \
     'http://{HOST}:{PORT}/settings/rbac/users/local/analyst1' \
     -d password=$NEW_USER_PASSWORD \
     -d roles=query_select,credential_consumer[query/rest-apis/weather]
----

[#grant-group-rest-api]
=== Grant a Group Access to a Credential

Granting a group access to a credential works the same way.
Make a `PUT` request to `/settings/rbac/groups/<GROUP_NAME>` and add the `credential_consumer` role, with the credentials the group's members can access, to the `roles` parameter.

For more information about creating and managing groups, see xref:manage-security/manage-users-and-roles.adoc[Manage Groups Using the REST API].

[#grant-access-ddl]
== Grant Users and Groups Access to Credentials Using DDL

Use the `GRANT CONSUME CREDENTIALSTORE` statement to grant a user or group the `credential_consumer` role and the ability to use 1 or more specific credentials.

For example, the following statement grants the user `analyst1` access to an AWS credential:

[source,n1ql]
----
GRANT CONSUME CREDENTIALSTORE ON `iceberg/aws/sales-data` TO analyst1;
----

[#revoke-access]
== Revoke Credential Access

You can revoke a user's or group's ability to use a credential using the Web Console, the REST API, or DDL.

[tabs]
====
Web Console::
+
--
. Go to menu:Security[Users & Groups] > *Users*.
. Click the user's entry, then click btn:[Edit].
. In the *Roles* list, expand *Administrator*, then remove the credential from the *Credential Consumer* role's parameter list, or remove the role entirely.
--

REST API::
+
--
Make a `PUT` request to `/settings/rbac/users/[local|external]/<USERNAME>` and set the `roles` parameter to the full list of roles the user should have.

* If the user should no longer access any credentials, leave the `credential_consumer` role out of the list.
* If the user should still access some credentials, include the `credential_consumer` role with only the credentials they should still be able to use.

Groups work the same way.
Make a `PUT` request to `/settings/rbac/groups/<GROUP_NAME>`, instead.
--

DDL::
+
--
Use the `REVOKE CONSUME CREDENTIALSTORE` statement to remove a user's or group's access to a specific credential:

[source,n1ql]
----
REVOKE CONSUME CREDENTIALSTORE ON `iceberg/aws/sales-data` FROM analyst1;
----
--
====

NOTE: Deleting a credential also revokes every user's and group's access to it.
You don't need to revoke access before you delete a credential.

[#next-steps]
== Next Steps

* For an overview of the credential store, see xref:learn:security/credential-store.adoc[].
* For a full list of roles and their parameters, see xref:learn:security/roles.adoc[].

