= Manage Services Access to Credentials
:description: You can grant Couchbase Server services direct access to credentials for their own use.
:page-toclevels: 2
:page-edition: Enterprise Edition

[abstract]
{description}
For example, you can configure continuous backup to save its backup data to a cloud provider such as AWS S3.
When you do, you must grant the Backup Service access to a credential it can use to authenticate with the storage location.

== Prerequisites

* The cluster's credential store must be enabled.
For more information, see xref:manage-security/manage-credentials/manage-credential-store.adoc[].
* The credential that you want to grant access to must already exist.
This credential does not require guardrail settings to allow the service to use the credential. 
Guardrails (including service restriction guardrails) do not apply to services directly using a credential. 
See xref:learn:security/credential-store.adoc#guardrails[Guardrails] for more information.
* Your user account must have the xref:learn:security/roles.adoc#full-admin[Full Admin] role.
+
NOTE: Unlike granting credential access to users and groups, the xref:learn:security/roles.adoc#security-admin[Security Admin] role cannot grant, view, or revoke a service's access to a credential.
This restriction prevents a Security Admin from indirectly using a credential by granting it to a service, because Security Admins cannot use stored credentials themselves.

[#grant-role-to-service]
== Grant a Service Access to a Credential

You grant a service access to a credential using the REST API.

To grant a service access to 1 or more credentials, make a `PUT` request to `/settings/rbac/services/{SERVICE_IDENTITY}/roles` and add the `credential_consumer` role, with the credentials the service can access, to the `roles` parameter.

[source,bash]
----
curl -u $CB_USER:$CB_PASS -X PUT \
     http://$CB_HOST:$CB_PORT/settings/rbac/services/{SERVICE_IDENTITY}/roles \
     -d 'roles=credential_consumer[<CREDENTIAL_ID>]'
----

To grant access to more than 1 credential, add a separate `credential_consumer[<CREDENTIAL_ID>]` entry for each credential, separated by commas.

CAUTION: Updating a service's roles using the REST API is a full-replacement operation.
If you are adding access to an additional credential, you must include the existing credentials in the request.
Otherwise, Couchbase Server removes the credentials you do not include.

The `credential_consumer` role is the only role you can grant to a service.
Couchbase Server rejects a request that tries to grant a service any other role.

Use the following table to find the identity to use for a service:

|====
|Service |Identity

|Backup Service |`backup`

|Enterprise Analytics |`cbas`

|Eventing Service |`eventing`

|Index Service |`index`

|Query Service |`n1ql`

|Search Service |`fts`

|XDCR |`xdcr`

|====

[#example-grant-role-to-service]
=== Example

The following example grants the Backup Service access to a credential it can use to authenticate with an AWS S3 bucket for continuous backup:

[source,bash]
----
curl -u $CB_USER:$CB_PASS -X PUT \
     http://$CB_HOST:$CB_PORT/settings/rbac/services/backup/roles \
     -d 'roles=credential_consumer[backup/aws/continuous-s3]'
----

[#view-service-credentials]
== View Credentials Granted to a Service

To view the credentials granted to a service, make a `GET` request to `/settings/rbac/services/{SERVICE_IDENTITY}/roles`:

[source,bash]
----
curl -u $CB_USER:$CB_PASS \
     http://$CB_HOST:$CB_PORT/settings/rbac/services/backup/roles | jq
----

If successful, the call returns the service's granted roles:

[source,json]
----
{
  "roles": [
    {
      "role": "credential_consumer",
      "credential_id": "backup/aws/continuous-s3"
    }
  ]
}
----

[#revoke-service-credentials]
== Revoke a Service's Access to a Credential

To revoke a service's access to 1 or more credentials while leaving its access to other credentials in place, make a `PUT` request to `/settings/rbac/services/{SERVICE_IDENTITY}/roles`.
Set the `credential_consumer` role's parameter list to the credentials the service should still be able to access.
The `PUT` request is a full-replace operation, so leaving out the credentials you want to revoke removes them from the list.

To revoke all of a service's credential access at once, make a `DELETE` request to `/settings/rbac/services/{SERVICE_IDENTITY}/roles`.
The following example removes all of the roles from the Backup Service:

[source,bash]
----
curl -u $CB_USER:$CB_PASS -X DELETE \
      http://$CB_HOST:$CB_PORT/settings/rbac/services/backup/roles
----

NOTE: Deleting a credential also revokes every service's access to it (as well as any users or groups who also have access).
You do not need to revoke a service's access before you delete a credential.

[#next-steps]
== Next Steps

* For an overview of the credential store, see xref:learn:security/credential-store.adoc[].
* To grant users and groups access to credentials, see xref:manage-security/manage-credentials/manage-user-access-credentials.adoc[].
