= Manage User and Groups Access to Credentials
:description: Once you have created credentials in the credential store, you can grant users and groups access to them.
:page-toclevels: 2
:page-edition: Enterprise Edition

[abstract]
{description}

[#overview]
== Overview

To let a user or group use a credential, assign them the xref:learn:security/roles.adoc#credential-consumer[Credential Consumer] RBAC role.
When assigning this role, you list the credential IDs that they can use to the role's parameter list. 
You can use wildcards in the role's parameter list to grant users or groups permission to use multiple matching credentials.
When using a wildcard to grant a user or group permission to use a credential, the wildcard expression must match at least one existing credential.
You cannot grant a user permission to use a credential that does not yet exist.

Granting a user the ability to use a credential does not let them view the credentials details, including its secrets. 
For more about the credential store, see xref:learn:security/credential-store.adoc[]


NOTE: You can also grant a service direct access to a credential, without requiring a user's permission.
For more information, see *Grant Services Access to Credentials*.


[#prerequisites]
== Prerequisites

* The cluster's credential store enabled must be enabled. 
For more information, see xref:manage-security/manage-credentials/manage-credential-store.adoc[].
* The credential that you want to grant access to must already exist.
* Your user account must have the xref:learn:security/roles.adoc#full-admin[Full Admin] or xref:learn:security/roles.adoc#security-admin[Security Admin] role to grant roles to users or groups.

[#grant-access-web-console]
== Grant Users and Groups Access to Credentials Using the Web Console

To grant a user permission to use a credential:

. Go to menu:Security[Users & Groups].
. Click btn:[Add User], or click an existing user's entry and click btn:[Edit].
. In the *Roles* list, expand the *Administrative* category.
. Under *Credential Consumer*, select the credential IDs the user should have, or enter  wildcard expressions to allow multiple credentials.
For more information, see xref:learn:security/roles.adoc#roles-parameter-lists[Role Parameter Lists].
. Click btn:[Save Changes].

Granting the *Credential Consumer* role to a group using the Couchbase Server Web Console works the same way.
Go to menu:Security[Users & Groups], and follow steps 2 through 5 in the previous 

[#grant-access-rest-api]
== Grant Users and Groups Access to Credentials Using the REST API

[#grant-user-rest-api]
=== Grant a User Access to a Credential

To grant a user access to 1 or more credentials, make a `PUT` request to `/settings/rbac/users/[local|external]/{username}` and add the `credential_consumer` role to the `roles` parameter.
List the credentials the user can access in the role's parameter list.

CAUTION: Updating a user's roles using the REST API is a full-replacement operation.
If you want to add the `credential_consumer` role for an existing user, include a copy of their current roles in the request.
Otherwise, Couchbase Server removes any existing roles you do not include.

For more information about creating and managing users, see xref:manage-security/manage-users-and-roles.adoc#create-a-local-user-with-the-rest-api[Create a Local User Using the REST API] and xref:manage-security/manage-users-and-roles.adoc#adding-roles[Assign Roles to a User].

[#example-grant-user-rest-api]
==== Example

The following example creates a user, `analyst1`, and grants them the `query_select` role and the `credential_consumer` role for a credential used with a REST API endpoint:

[source,bash]
----
curl -u $CB_USER:$CB_PASS -X PUT \
     "http://${CB_HOST}:${CB_PORT}/settings/rbac/users/local/analyst1" \
     -d password=$NEW_USER_PASSWORD \
     -d 'roles=query_select[travel-sample],'\
'credential_consumer[query/rest-apis/weather]' 
----

This example grants the existing `iceberg-querier` user permission to use 2 credentials: 
`iceberg/aws/s3-data` and `iceberg/http/catalog.example.com`.
The `roles` parameter also includes the `query_select` role for the `my-bucket.external.iceberg-collection` table which they had previously. 

[source,bash]
----
curl -u $CB_USER:$CB_PASS -X PUT \
     "http://${CB_HOST}:${CB_PORT}/settings/rbac/users/local/iceberg-querier" \
     -d 'roles=query_select[my-bucket:external:iceberg-collection],'\
'credential_consumer[iceberg/aws/s3-data],'\
'credential_consumer[iceberg/http/catalog.example.com]'
----

This example grants the user `iceberg-querier2` permission to use all of the credentials that are under the `iceberg` path.
That's both credentials granted in the previous example, plus any others whose IDs start with  `iceberg` (and any future ones created there as well).

[source,bash]
----
curl -u $CB_USER:$CB_PASS -X PUT \
     "http://${CB_HOST}:${CB_PORT}/settings/rbac/users/local/iceberg-querier2" \
     -d 'roles=query_select[my-bucket:external:iceberg-collection],'\
'credential_consumer[iceberg/*]'
----

[#grant-group-rest-api]
=== Grant a Group Access to a Credential

Granting a group access to a credential works the same way.
Make a `PUT` request to `/settings/rbac/groups/{group_name}` and add the `credential_consumer` role, with the credentials the group's members can access, to the `roles` parameter.

The following example creates a group named `iceberg_query` that has the xref:learn:security/roles.adoc#query-select[Query Select] role for all collections in the `my-bucket.external` scope.
It can also use all of the credentials whose ID starts with `iceberg/`.

[source,bash]
----
curl -u $CB_USER:$CB_PASS -X PUT \
     http://$CB_HOST:$CB_PORT/settings/rbac/groups/iceberg_query \
     -d 'roles=query_select[my-bucket:external],'\
'credential_consumer[iceberg/*]'
----

For more information about creating and managing groups, see xref:manage-security/manage-users-and-roles.adoc[Manage Groups Using the REST API].

[#grant-access-ddl]
== Grant Users and Groups Access to Credentials Using DDL

Use the `GRANT CONSUME CREDENTIALSTORE` statement to grant a user or group the `credential_consumer` role and the ability to use 1 or more specific credentials.

For example, the following statement grants the user `analyst1` access to an AWS credential:

[source,n1ql]
----
GRANT CONSUME CREDENTIALSTORE ON `iceberg/aws/sales-data` TO analyst1;
----

The following example grants the group `iceburg_query` permission to use all of the credentials starting with `iceburg/`:

[source,n1ql]
----
GRANT CONSUME CREDENTIALSTORE ON `iceberg/*` TO GROUP `iceberg_query`;
----

[#revoke-access]
== Revoke Credential Access

You can revoke a user's or group's ability to use a credential using the Coucbase Server Web Console, the REST API, or DDL.

[tabs]
====
Web Console::
+
--
. Go to menu:Security[Users & Groups] > *Users*.
. Click the user's entry, then click btn:[Edit].
. In the *Roles* list, expand *Administrator*, then remove the credential from the *Credential Consumer* role's parameter list.
You can also remove the role entirely.
--

REST API::
+
--
Make a `PUT` request to `/settings/rbac/users/[local|external]/<USERNAME>` and set the `roles` parameter to the full list of roles the user should have.

* If the user should no longer access any credentials, leave the `credential_consumer` role out of the list.
* If the user should still access some credentials, include the `credential_consumer` role with only the credentials they should still be able to use.

Groups work the same way.
Make a `PUT` request to `/settings/rbac/groups/<GROUP_NAME>`, instead.
--

DDL::
+
--
Use the `REVOKE CONSUME CREDENTIALSTORE` statement to remove a user's or group's access to a specific credential:

[source,n1ql]
----
REVOKE CONSUME CREDENTIALSTORE ON `iceberg/aws/sales-data` FROM analyst1;
----
--
====

NOTE: Deleting a credential also revokes every user's and group's access to it.
You do not need to revoke access before you delete a credential.

[#next-steps]
== Next Steps

* To learn how to grant Couchbase Server services access to credentials for their own use, see 
* For an overview of the credential store, see xref:learn:security/credential-store.adoc[].
* For a full list of roles and their parameters, see xref:learn:security/roles.adoc[].

