= Couchbase ODBC and JDBC Drivers

The ODBC and JDBC drivers enable any application based on the ODBC/JDBC standards, for example Microsoft Excel, QlikView, SAP Lumira, or Tableau, to connect to a Couchbase Server or cluster. These drivers enable fast and seamless access to Couchbase data. Using these drivers, the applications can leverage on the powerful N1QL functionality to efficiently store and process JSON documents at scale.

CData Software has developed standards-based drivers to connect your Couchbase data to the BI, reporting, and ETL tools that you are already using.
With drivers that adhere to time- and industry-proven standards, like JDBC, ODBC, and ADO.NET, users are freed to quickly connect with their Couchbase data in their favorite tools, saving them the time and hassle of managing the data integration.

The CData Drivers are built to modern standards (JDBC 4, ODBC 3.8, Excel 2007-2016, .NET 4.7, OData 4) and can process SQL-92 queries and translate them into N1QL, simultaneously granting you access to your data in tools you already use and leveraging the utility of Couchbase Server data storage and querying technology.
For more information and to download a free trial, refer to the CData Couchbase landing page http://www.cdata.com/drivers/couchbase/[^].
