= Advanced Features
:page-role: tiles -toc
:!sectids:
:page-topic-type: reference

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

== Tuning and Query Performance

Refer to the following pages to learn more about query performance.

* xref:learn:services-and-indexes/indexes/indexing-and-query-perf.adoc[Indexing and Query Performance]
* xref:learn:services-and-indexes/indexes/index-scans.adoc[Understanding Index Scans]
* xref:learn:services-and-indexes/indexes/index_pushdowns.adoc[Index Pushdown Optimizations]

== Group By and Aggregate Performance

N1QL Pushdowns optimize the performance of N1QL queries by supporting GROUP BY and Aggregate expressions.

* xref:n1ql:n1ql-language-reference/groupby-aggregate-performance.adoc[Group By and Aggregate Performance]

== Covering Indexes

A covering index includes the actual values of all the fields specified in the query, and does not need to fetch the values from the data service.
Covered queries are faster and deliver better performance. 

* xref:n1ql:n1ql-language-reference/covering-indexes.adoc[Covering Indexes]

== Flex Indexes

In Couchbase Server 6.6 Enterprise Edition and later, the Flex Index feature provides the ability for a N1QL query to use a Full Text Search index transparently with standard N1QL syntax.

* xref:n1ql:n1ql-language-reference/flex-indexes.adoc[Flex Indexes]

== Cost-Based Optimizer

The cost-based optimizer takes into account the cost of memory, CPU, network transport, and disk usage when choosing the optimal plan to execute a query.

* xref:n1ql:n1ql-language-reference/cost-based-optimizer.adoc[Cost-Based Optimizer]
