= Tutorials
:page-role: tiles -toc
:!sectids:

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

== Run Your First {sqlpp} Query

If you have not done so already, refer to this page to run your first {sqlpp} query.

* xref:getting-started:try-a-query.adoc[]

== Developer Tutorial

An introductory worked example for developers, showing how to use a software development kit to query a simple database using {sqlpp}.

* xref:tutorials:couchbase-tutorial-student-records.adoc[]

== Interactive {sqlpp} Tutorial

Provides interactive web modules where you can learn about {sqlpp} without having Couchbase Server installed in your own environment.
The modules are self-contained and let you modify and run sample queries.

* https://query-tutorial.couchbase.com/tutorial/#1[{sqlpp} Query Language Tutorial^]

== Related Links

The {sqlpp} cheat sheet provides a concise summary of the basic syntax elements of {sqlpp}.

* xref:cheatsheets:attachment$Couchbase-N1QL-CheatSheet.pdf[{sqlpp} Cheat Sheet]
