= Manage Point-in-Time Recovery (PITR)
:description: pass:q[Point-in-time recovery lets you restore a bucket to the state it was in at a specific time.]
:enterprise-only:
:toclevels: 3

[abstract]
{description}
See xref:learn:services-and-indexes/services/continuous-backup.adoc[] for an overview of continuous backup and point-in-time recovery.

== Prerequisites

* Your Couchbase Server account must have the xref:learn:security/roles.adoc#full-admin[Full Admin] or xref:learn:security/roles.adoc#backup-full-admin[Backup Full Admin] role.

* You must have a Magma bucket configured with continuous backup. 
See xref:manage:manage-backup-and-restore/manage-continuous-backup.adoc[] for the steps to configure continuous backup for a Magma bucket.

* Continuous backup must have made at least a single backup to the continuous backup location.
This means continuous backup must have been active for a bit longer than its continuous backup interval.

* You must have a traditional periodic backups for the bucket you're restoring. 
Continuous backup restores the most recent full backup taken before the point in time you're restoring to.
It then restores any incremental backups taken between the full backup and the point in time you chose.
It uses the data in the continuous backup location to fill the gap between the last traditional backup it restored and the target point in time.

[#backup-overlap]
* Your continuous backups and periodic backups for the bucket made by either the Backup Service or `cbbackupmgr` must overlap.
Overlapping means the bucket must have a full or incremental periodic backup that has occurred since you enabled continuous backup on it.
For example, to make sure you can perform a PITR, you can:

+
. Enable continuous backup for the bucket.
. Wait at least until the continuous backup interval elapses so that continuous backup copies data into the continuous backup location.
. Trigger a full or incremental backup on the bucket using either the Backup Service or `cbbackupmgr`.

+
Once you complete this process, your continuous backup and traditional backups overlap and you can perform a PITR.

* You must choose which point in time you want to restore the bucket to.

+
The earliest point in time you can restore to is determined by your continuous backup retention period. 
The exception is if you enabled continuous backup more recently than the retention period. 
In that case, the earliest moment you can restore to is shortly after you enabled continuous backup.
If you need to restore your cluster to a point earlier than this time, you can only restore a traditional backup, assuming you have one that covers the time you need to restore to.
However, you cannot restore to a specific point in time with traditional backup.

+
The latest time you can restore to is whenever the continuous backup agent last copied data to the continuous backup location. 
This may be as far back in the past as the continuous backup interval period you set when configuring continuous backup.
If you stopped continuous backup, then you can only restore up to the moment you stopped it.

+
See xref:manage:manage-backup-and-restore/monitor-continuous-backup.adoc#get-cont-backup-info[Get Information About a Continuous Backup Location] to learn how to find the range of time backed up by a continuous backup location.

* You must have a bucket where you want to restore to. 
This can be:
+
--
** The original bucket. 
** A new bucket in the same cluster.
** A bucket in a different cluster.
--
+
PITR recovery does not flush the target bucket before a restore.
By default, it does not overwrite existing documents already in the bucket.
If you want to restore the bucket to its exact state at the point in time you choose, flush the bucket before restoring.
See xref:manage:manage-buckets/flush-bucket.adoc[] for more information about flushing buckets.

+
NOTE: You can have PITR overwrite existing documents in the bucket with documents in the backup by passing the `--force-updates` option to `cbcontbk`.
See the documentation for xref:continuous-backup:cbcontbk.adoc[`cbcontbk`] for details.

* To prevent consistency issues, stop continuous backup on the bucket you're restoring.
You must stop continuous backup even if you're not restoring to the original bucket.
Once the PITR finishes, you can restart continuous backup.
See xref:manage:manage-backup-and-restore/manage-continuous-backup.adoc#stop-continuous-backup[Stop Continuous Backup] to learn how to stop continuous backup for a bucket.

NOTE: You do not need to stop traditional periodic backups or XDCR for the bucket when performing PITR.

== Restore to a Point in Time

You use the `cbcontbk` command line tool to restore a bucket backed up using continuous backup to point in time.

When calling `cbcontbk`, you must supply the following arguments:

* `--target` is the date and time you want to restore the bucket to in an https://www.rfc-editor.org/info/rfc3339/[RFC3339 timestamp^]. 
* `-u` and `-p` are the username and password for the full administrator.
* `--tmp-dir` a temporary directory the `cbcontbk` can use when restoring data.
* `-l` the continuous backup storage location.
This is either:
** The absolute path to the e the backup storage location's NFS mount point.
** The URI of the cloud storage location.
* `-a` the filesystem path or S3 URI storing the traditional backup repository.
* `-r` is the UUID for the repository containing the bucket's traditional backup.
* `-c` is the URL for a node in the cluster running the Backup Service.

In addition, you must supply credentials `cbcontbk` can use to authenticate with the continuous backup location and the traditional backup repository if they're stored in the cloud.
If you have encrypted backups, you must also supply credentials to decrypt them.
See the documentation for xref:continuous-backup:cbcontbk.adoc[`cbcontbk`] for details.

For example, suppose you want to restore the `travel-sample` bucket that uses locally mounted NFS shares for continuous backup and traditional backup. 
Also suppose you want to restore to the original bucket and want it to be in the state it was in at your chosen restoration time.
In this case, you can follow these steps to perform the PITR:

. Stop continuous backup for the bucket. 
Because you'll need to use the command line to run `cbcontbk` anyhow, this example uses the command line on a node to stop continuous backup:

+
[source,bash]
```
couchbase-cli bucket-edit --cluster couchbase://localhost \
              --username $USERNAME --password $PASSWORD \
              --bucket travel-sample \
              --continuous-backup-enabled 0
```

. In this example, the goal is to have the bucket to be the exact state it was at your chosen recovery time.
Therefore, you must flush the bucket before performing PITR.

+
If the bucket does not have flushing enabled, you must first enable it:

+
[source,bash]
```
couchbase-cli bucket-edit --cluster couchbase://localhost \
              --username $USERNAME --password $PASSWORD \
              --bucket travel-sample \
              --enable-flush 1
```

+
Then flush the bucket:

+
[source,bash]
```
couchbase-cli bucket-flush --cluster couchbase://localhost \
              --username $USERNAME --password $PASSWORD \
              --bucket travel-sample 
```

+
NOTE: After finishing PITR, consider turning off the ability to flush the bucket to prevent accidental data loss.

. Before performing the restore, you should verify the point in time you want to restore to is available in the continuous backup location.
You can find the range of times you can restore to using the `cbcontbk` command line tool.

+
[source,bash]
```
include::manage:example$continuous-backup.sh[tag=get-backup-info]
```

+
The result of the previous command looks like the following:

+
[source,log]
```
include::manage:example$continuous-backup.log[tag=get-backup-info]
```

+ 
The result in the example shows that you can restore to any point in time between June 6th at 14:57 GMT and June 23rd at 17:55 GMT. 

. Use the `cbcontbk restore` command to restore the bucket. 
The following command restores `travel-sample` to the state it was in at June 8th, 2026 at 19:54:10 GMT.

+
[source,bash]
```
include::manage:example$continuous-backup.sh[tag=restore-bucket]
```

+
The output from this command looks like this:

+
[source,log]
```
include::manage:example$continuous-backup.log[tag=restore-output]
```

+
You can see that PITR restores a traditional full backup and possibly multiple incremental backups.
Then it replays mutations from the continuous backup until it reaches the selected point in time.

. After you have finished the PITR, start continuous backup again.
The following example restarts continuous backup on the `travel-sample` bucket.

+
[source,bash]
```
couchbase-cli bucket-edit --cluster couchbase://localhost \
              --username $USERNAME --password $PASSWORD  \
              --bucket travel-sample \
              --continuous-backup-enabled 1
```
