= Monitor Continuous Backup
:description: pass:q[Once you have enabled continuous backup for a bucket, you can monitor its status.]
:page-edition: Enterprise Edition
:page-toclevels: 3

[abstract]
{description}
For an overview of continuous backup and point-in-time recovery, see xref:learn:services-and-indexes/services/continuous-backup.adoc[].

== Prerequisites

* Your Couchbase Server account must have the xref:learn:security/roles.adoc#full-admin[Full Admin] or xref:learn:security/roles.adoc#backup-full-admin[Backup Full Admin] role.
* You must have a Magma bucket with continuous backup enabled.
For more information about how to configure continuous backup for a Magma bucket, see xref:manage:manage-backup-and-restore/manage-continuous-backup.adoc[].


[#get-cont-backup-info]
== Get Information About a Continuous Backup Location

Once you have enabled continuous backup, you can get information about your backup location using the `cbcontbk` command line tool's `info` command.
The information includes the earliest and latest data in the location.

To get continuous backup information about a location, use the command:

[source,bash]
```
cbcontbk info -l <continuous-backup-location>
```

Where `<continuous-backup-location>` is either the local path to the Network File System (NFS) mount or the URI of the cloud storage location where the backup is stored.
If the storage location is cloud-based, you must also supply the credentials and other settings `cbcontbk` needs to read data from the location.
For more information, see the xref:continuous-backup:cbcontbk.adoc[`cbcontbk`] documentation.

The following example gets information about the continuous backup location stored on an NFS share mounted at `/shared/continuous-backup` on all nodes in the cluster:

[source,bash]
```
include::manage:example$continuous-backup.sh[tag=get-backup-info]
```

The following example shows the output of the previous command for a location backing up the `travel-sample` bucket:

[source,log]
```
include::manage:example$continuous-backup.log[tag=get-backup-info]
```

The timestamps under the `Range` heading in the output show you the earliest and latest times you can restore the bucket to using Point-in-Time Recovery (PITR).
For more information about performing a PITR, see xref:manage:manage-backup-and-restore/manage-pitr.adoc[].

== Continuous Backup Metrics

Continuous backup exposes several metrics that let you monitor its status.
You can use these metrics to monitor its status in tools such as Prometheus.
These metrics all start with the `contbk_` (continuous backup) prefix.

// FIXME: link to metrics whenever they show up in the metrics_metadata file in the server build.. They aren't there as of build #2395

For more information about monitoring Couchbase Server using metrics, see xref:manage:monitor/set-up-prometheus-for-monitoring.adoc[].

== Next Steps

* xref:manage:manage-backup-and-restore/manage-pitr.adoc[Perform a Point-in-Time Recovery]
* xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc#inspect-backups[Inspect periodic backups]

