= Change XDCR Data Encryption

[abstract]
Regenerate the SSL certificate to update XDCR data encryption.

In some situations, such as updating SSL data security, the SSL certificate is regenerated, and the XDCR data encryption is updated.
To change XDCR data encryption:

. On the destination cluster, navigate to menu:Settings[Cluster].
. Click [.ui]*Regenerate* and copy the certificate.
. On the source cluster, select the [.ui]*XDCR* tab.
. In the [.ui]*Remote Clusters* panel, for the destination cluster, click [.ui]*Edit*.
. Paste the regenerated certificate in the provided area and click [.ui]*Save*.
Anytime you regenerate the destination cluster’s certificate, update the corresponding source cluster(s) with that regenerated certificate.
+
For example, if source clusters A, B, and C use XDCR data encryption to replicate to destination cluster D, update each of the source clusters whenever you regenerate the certificate on the destination cluster D.

IMPORTANT: Replication will stop if you regenerate the destination cluster's certificate and don't update the source cluster(s) with the new 	certificate.
