= Recovery dry-run

[abstract]
Preview a list of buckets that are no longer available in the cluster.

Before you recover vBuckets, you may want to preview a list of buckets that are no longer available in the cluster.
Use this command and options:

----
shell> ./cbrecovery http://Administrator:password@10.3.3.72:8091 http://Administrator:password@10.3.3.61:8091 -n
----

The administrative credentials are provided for the node in the cluster, as well as the option `-n`.
The command  returns a list of vBuckets in the remote secondary cluster that are no longer in the first cluster.
If there are any unavailable buckets in the cluster with failed nodes, you will see output as follows:

----
2013-04-29 18:16:54,384: MainThread Missing vbuckets to be recovered:[{"node": "ns_1@10.3.3.61",
"vbuckets": [513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,, 528, 529,
530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,, 547, 548,
549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567,
568, 569, 570, 571, 572,....
----

In this case, the `vbuckets` array contains all the vBuckets that are no longer available in the cluster.
These are the buckets you can recover from the remotes cluster using the following command:

----
shell> ./cbrecovery http://Administrator:password@<From_IP>:8091 \
 http://Administrator:password@<To_IP>:8091 -B bucket_name
----

You can run the command either on the cluster with unavailable vBuckets, or on the remote cluster.

Provide the hostname, port, and credentials for the remote cluster and the cluster with missing vBuckets, in that order.
If you do not provide the parameter `-B`, the tool assumes you will recover unavailable vBuckets for the default bucket.
