= XDCR Data-Type Conversion

[abstract]
_XDCR filtering expressions_ are supported by data-type _conversion_ and _collation_, when different data-types are referred to.

== Understanding Data-Type Conversion

_XDCR filtering expressions_ allow case-sensitive matches, comparisons, logical and other operations to be performed on values within documents.
When values referenced by a filtering expression have different data-types, either _conversion_ or _collation_ is performed:

* _Conversion_ means that one or more of the values is converted from its existing data-type to another, so that the operation is performed on values of the same data-type.

* _Collation_ means that conversion is not possible; and that therefore, the operation will be otherwise resolved, according to a set of rules.

All conversion performed by XDCR is _implicit_, meaning that it is performed automatically within the system.
No _explicit_ conversion (that is, data-type conversion selected and imposed by the administrator) is supported.

[#supported-data-types]
== Supported Data Types

The data-types supported by XDCR Filtering are listed below, in order of _precedence_.

[#data-type-precedence-table]
[cols="1,4"]
|===
| *Precedence* | *Data Type*
| 0 | Invalid
| 1 | Missing
| 2 | Null
| 3 | Boolean
| 4 | Numeric
| 5 | String
| 6 | Time
| 7 | Array
| 8 | Object
| 9 | Binary
|===

When an expression entails values of the same data-type, no conversion is required.
When the data-types differ, and conversion or collation is therefore required, data-types take precedence in accordance with their closeness to the top of the list.
For example, if an operation refers to two values, one of which is _Invalid_ and the other of which is _Boolean_, the _Invalid_ value determines the result.
As another example, if an operation refers to two values, one of which is _Boolean_ and the other _Numeric_, the _Numeric_ value is if possible converted to _Boolean_, and the operation performed.
