= XDCR Security and Networking
:description: Specific requirements must be satisfied in order to ensure the successful securing of XDCR replications over different network configurations.

[abstract]
{description}

== Security and Networking Contexts

This page considers three specific contexts in which XDCR replications must sometimes be established.
These respectively involve:

* Handling _Couchbase Schemes_, using _DNS SRV_

* Using _Alternate Addresses_

* Using _Certificates_, including _Third Party CAs_

Each is explained below.

[#dnssrv]
== Handling Couchbase Schemes, using DNS SRV

Targets for XDCR replication can be specified using the schemes _http://_ and _https://_, and with the standard port number `8091` or `18091`, as applicable.
Targets _cannot_ be specified with the _Couchbase_ schemes _couchbase://_ and _couchbases://_, which are, instead, used to support the memcached protocol on ports `11210` and `11207`, respectively.

Targets _can_, however, be specified with a _Fully Qualified Domain Name_ (_FQDN_) that is either tagged with one of the standard port numbers, or is untagged.
In such cases, XDCR performs a https://go.dev/src/net/lookup.go[LookupSRV^] on the FQDN, using the local machine’s _DNS resolver_.
LookupSRV obtains the appropriate name from a local DNS https://en.wikipedia.org/wiki/SRV_record[SRV record^]: which is a specification of data in the Domain Name System that defines the _location_ (the hostname and port number) of a server for a particular service.
When LookupSRV has returned the name, XDCR concatenates a standard port number to the name, and uses the resulting concatenation as the target-reference.

Consequently, resources named by means of the Couchbase schemes can be resolved to appropriate XDCR-target names: by first removing the _couchbase_ or _couchbases_ prefix, and then specifying the remaining symbol, which is the FQDN -- so that LookupSRV resolves the FQDN to a name that XDCR can include in the ultimate target-reference.
Note, however, that this does assume the target's use of one of the standard port numbers -- `8091` or `18091` -- for XDCR access.

=== Example

Suppose a resource is provided with the Couchbase scheme as follows: `couchbases://7cb51b5b-d9cd-410d-9cc7-1be93e2f31d9.dp.cloud.couchbase.com`.
The scheme's prefix `couchbases://` can be removed, so as to leave an FQDN as follows: `7cb51b5b-d9cd-410d-9cc7-1be93e2f31d9.dp.cloud.couchbase.com`.
This FQDN can be specified by the administrator as the _hostname_ of the target cluster for XDCR replication.

Note that the command `nslookup -type=srv` can be used manually to determine whether this hostname corresponds to one or more true, DNS SVR records.
The form of an SRV record is as follows:

----
_service._proto.name. ttl IN SRV priority weight port target
----

See https://en.wikipedia.org/wiki/SRV_record[SRV record^], for a full explanation of this syntax.

To perform the manual lookup, we provide values for the `_service._proto.name.` arguments.
Thus, we use `couchbases` for the `service` argument; `tcp` for the `proto` argument; and the hostname `7cb51b5b-d9cd-410d-9cc7-1be93e2f31d9.dp.cloud.couchbase.com` for the `name` argument.
Our command is therefore executed as follows:

----
nslookup -type=srv _couchbases._tcp.7cb51b5b-d9cd-410d-9cc7-1be93e2f31d9.dp.cloud.couchbase.com
----

If successful, the command returns output similar to the following:

----
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
_couchbases._tcp.7cb51b5b-d9cd-410d-9cc7-1be93e2f31d9.dp.cloud.couchbase.com	service = 0 0 11207 cb-0001.7cb51b5b-d9cd-410d-9cc7-1be93e2f31d9.dp.cloud.couchbase.com.
_couchbases._tcp.7cb51b5b-d9cd-410d-9cc7-1be93e2f31d9.dp.cloud.couchbase.com	service = 0 0 11207 cb-0002.7cb51b5b-d9cd-410d-9cc7-1be93e2f31d9.dp.cloud.couchbase.com.
_couchbases._tcp.7cb51b5b-d9cd-410d-9cc7-1be93e2f31d9.dp.cloud.couchbase.com	service = 0 0 11207 cb-0000.7cb51b5b-d9cd-410d-9cc7-1be93e2f31d9.dp.cloud.couchbase.com.
----

This output shows that three SRV records have been found to correspond with the values we specified.
The final value of each displayed record is the `target` for the record: each is a name beginning with `cb-`; and each name corresponds to an individual, server node.
Any of these `target` names can now be used as an XDCR target-reference, if either `:8091` or `18091` is appended to it.

The process shown manually above is essentially that followed programmatically by LookupSRV.
Note that XDCR ignores the value of the `port` argument returned in the record (which is in each case the secure memcached port, `11207`).

Using the final, _derived FQDN_, XDCR then performs its usual _cluster add_ procedure, to contact the other server nodes.

== Using Alternate Addresses

_Alternate addresses_ are used to allow a cluster to keep its _internally visible_ addresses private, while using a router or other networked entity to provide _externally visible_ addresses that are to be used by networked clients of the cluster.
Instances of _Kubernetes_ and _AWS_ frequently use alternate addresses for their connections with external entities.

Alternate addresses used in this way are said to constitute an _external network_.
Any cluster that is established within an external network must have its nodes configured to use the corresponding alternate addresses for external communications; and if the cluster is to be used as an XDCR target, these addresses must be referenced by the XDCR source.
This involves, on the target, _port forwarding_, which is described in xref:learn:clusters-and-availability/connectivity.adoc#alternate-addresses[Alternate Addresses].
It also involves, on the source, specification of the external network interface, either as an FQDN, or an IP address.

When a cluster has been configured in this way for external networking, and status on the cluster is returned by means of Couchbase Web Console, the CLI, or the REST API, both the internal and the external addresses are represented.

The REST API reference page xref:rest-api:rest-set-up-alternate-address.adoc[Managing Alternate Addresses] explains how alternate addresses can be established for and removed from nodes.
The REST API reference page xref:rest-api:rest-list-node-services.adoc[Listing Node Services] explains how to retrieve all internal and external address settings.

=== Kubernetes

_Kubernetes_ employs a dual network environment, where an external interface is established for the reception of externally generated network traffic.
Such traffic includes inbound XDCR mutations: therefore, the source cluster must use the external interface established for Kubernetes.

A diagram of dual-network setup is provided in xref:learn:clusters-and-availability/connectivity.adoc#dual-network[Dual Network].

=== AWS and Cloud

If a cluster is established on a public cloud such as AWS, or is a Kubernetes cluster, and is intended to become the target for XDCR, the cluster must be configured with alternate addresses, to support the source cluster's access.
A diagram is provided in xref:learn:clusters-and-availability/connectivity.adoc#internal-network-or-cloud-access[Internal Network or Cloud Access].

== Specifying Addresses

If a target cluster is configured with alternate addresses, the particular address to which a connection should be made can be specified on the source cluster.
The following options are available for specifying the target-cluster address:

* When using Couchbase Web Console, from the *XDCR Replications* screen, left-clicking the *ADD REMOTE* tab brings up the *Add Remote Cluster* dialog, which provides an *IP/Hostname* interactive field.
(See xref:manage:manage-xdcr/create-xdcr-reference.adoc[Create a Reference].)

* When using the CLI, the `xdcr-setup` command provides the `--xdcr-hostname` field.
(See xref:cli:cbcli/couchbase-cli-xdcr-setup.adoc[xdcr-setup].)

* When using the REST API, the `POST /pools/default/remoteClusters` method and URI provide the `hostname` field.
(See xref:rest-api:rest-xdcr-create-ref.adoc[Setting a Target-Cluster Reference].)

In each case:

* An IP address or a qualified domain name can be specified.
The name can optionally be tagged with the port number `8091` or `18091`.

* If the specified name corresponds to the external address of the target cluster, the external address is used for the connection.
If the specified name corresponds to the internal address of the target cluster, the internal address is used for the connection.
If the name is not tagged with a port number, the connection defaults to `8091`; unless a secure connection is specified in another field, in which case `18091` is used.
(Note that the REST API provides a `network_type` parameter, which can be set to `external`, so as to enforce a secure connection: see xref:rest-api:rest-xdcr-create-ref.adoc[Setting a Target-Cluster Reference].)

* If the specified name corresponds to a DNS SRV entry, this entry is located by LookupSRV.
If at least one of the underlying names points to the external FQDN for the target cluster, then the external address is used for the connection.
Otherwise, the internal address is used.
(See xref:xdcr-reference:xdcr-security-and-networking.adoc#dnssrv[Handling Couchbase Schemes, using DNS SRV], above.)

== XDCR and Certificate Management

To be fully secure, XDCR requires _x.509 certificates_ to have been established on the target cluster.
The source cluster can authenticate with the target by means _either_ of a username and password _or_ of its own x.509 certificates.

=== Preparing to Configure Secure Replications

A complete overview of certificate management for Couchbase Server is provided in xref:learn:security/certificates.adoc[Certificates]; examples of establishing secure connections are provided in xref:manage:manage-xdcr/secure-xdcr-replication.adoc[Secure a Replication].
An overview of _Transport Layer Security_ is provided in xref:learn:security/on-the-wire-security.adoc[On-the-Wire Security]; and examples are provided in xref:manage:manage-security/manage-tls.adoc[Manage On-the-Wire Security].
Detailed information on the communication _handshake_ implemented by _Transport Layer Security_ can be found in https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_handshake[TLS Handshake^].
Administrators intending to establish secure replications should be familiar with all of the above content.
A number of key issues are summarized below.

=== Defining Client and Server

When a fully secure XDCR replication is configured, the source cluster should be considered the _client_, and the target cluster the _server_.

=== Understanding Root, Intermediate, and Node Certificates

As described in xref:learn:security/certificates.adoc[Certificates], the authority of a networked entity, such as a cluster or an application, is, in a production context, represented by a _root_ certificate, provided by a known _Certificate Authority_.
This root certificate (or _CA_) must be included in the _trust store_ of the target cluster.
See xref:learn:security/using-multiple-cas.adoc[Using Multiple Root Certificates] for information on the trust store, and see xref:rest-api:load-trusted-cas.adoc[Load Root Certificates] for information on loading a CA into a trust store.

Note that when the known authority's CA has been successfully loaded, it is visible by means of Couchbase Web Console, as shown in the documentation for the xref:manage:manage-security/manage-security-settings.adoc#root-certificate-security-screen-display[Certificates Security Screen].
If, on the target cluster, the CA is not visible here, it has not been loaded, and no fully secure replication will be supported.

Each node in the target cluster must be represented by its own _node_ certificate.
The CA for the target cluster must have been used to _digitally sign_ each node certificate: either directly, or (more likely) _indirectly_, by means of an _intermediate_ certificate.
When signing is complete, each node certificate must be _concatenated_ with however many intermediate certificates have been used, and appropriately posted on the node it is representing.
An overview of node-certificate preparation is provided in xref:learn:security/certificates.adoc#certificate-hierarchies[Certificate Hierarchies], and examples are provided in xref:manage:manage-security/manage-certificates.adoc[Manage Certificates].

=== Performing Certificate-Based Authentication

When the XDCR source cluster authenticates with the target cluster, the https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_handshake[TLS Handshake^] is performed.
During the course of this, the _server_ (which is the contacted target-cluster node) provides its certificate chain to the _client_ (which is the source cluster).
The source cluster validates the chain as described in xref:learn:security/certificates.adoc#node-certificate[Node Certificates].

=== Recognizing CAs

The top certificate in the chain provided to the client points to the CA for the target cluster.
As explained above, this CA must have been loaded into the trust store for the target.
Additionally, this CA must be recognizable to the client: the Couchbase Web Console interface therefore provides the ability to copy-and-paste the CA from the target cluster into the appropriate dialogue for the client: when the CA possessed by the client is determined to be the authority for the server, the connection can occur.
See xref:manage:manage-xdcr/enable-full-secure-replication.adoc#enable-fully-secure-replications-with-the-ui[Enable Fully Secure Replications with the UI], for examples.

Note that, in Couchbase Server 7.1+, _multiple root certificates_ are supported (see xref:learn:security/using-multiple-cas.adoc[Using Multiple Root Certificates].
Therefore, source and target clusters need not use the authority of the same CA: however, each must trust the CA of the other, if the client authenticates with certificates.
Therefore, if the CAs are different, the CA of the client must have been loaded into the trust store of the server, for authentication to succeed.

=== Handling Client Certificates

If the source cluster (the _client_) wishes to authenticate with the target cluster (the _server_) by means of _client certificates_, the administrator for the source must xref:manage:manage-security/enable-client-certificate-handling.adoc[Enable Client-Certificate Handling].

See xref:manage:manage-xdcr/enable-full-secure-replication.adoc#specify-full-xdcr-security-with-certificates[Specify Root and Client Certificates, and Client Private Key], for an example.
