= Settings and Parameters
:page-aliases: manage:manage-settings/query-settings

// Cluster-level settings from node-level
:queryCompletedLimit: xref:queryCompletedLimit
:queryCompletedThreshold: xref:queryCompletedThreshold
:queryLogLevel: xref:queryLogLevel
:queryN1QLFeatCtrl: xref:queryN1qlFeatCtrl
:queryPreparedLimit: xref:queryPreparedLimit

// Node-level settings from cluster-level
:completed-limit-srv: xref:completed-limit
:completed-threshold-srv: xref:completed-threshold
:loglevel-srv: xref:loglevel
:prepared-limit-srv: xref:prepared-limit
:n1ql-feat-ctrl: xref:n1ql-feat-ctrl

// Node-level settings from request-level
:controls-srv: xref:controls-srv
:pretty-srv: xref:pretty-srv
:profile-srv: xref:profile-srv

// Request-level parameters from node-level
:controls_req: xref:controls_req
:pretty_req: xref:pretty_req
:profile_req: xref:profile_req
:client_context_id: xref:client_context_id

// Cluster-level settings from node-level and request-level
:queryMaxParallelism: xref:queryMaxParallelism
:queryPipelineBatch: xref:queryPipelineBatch
:queryPipelineCap: xref:queryPipelineCap
:queryScanCap: xref:queryScanCap
:queryTimeout: xref:queryTimeout

// Node-level settings from cluster-level and request-level
:max-parallelism-srv: xref:max-parallelism-srv
:pipeline-batch-srv: xref:pipeline-batch-srv
:pipeline-cap-srv: xref:pipeline-cap-srv
:scan-cap-srv: xref:scan-cap-srv
:timeout-srv: xref:timeout-srv

// Request-level parameters from node-level and cluster-level
:max_parallelism_req: xref:max_parallelism_req
:pipeline_batch_req: xref:pipeline_batch_req
:pipeline_cap_req: xref:pipeline_cap_req
:scan_cap_req: xref:scan_cap_req
:timeout_req: xref:timeout_req

// Pass through HTML table styles for this page

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* No maximum width for table cells */
  .doc table.spread > tbody > tr > *,
  .doc table.stretch > tbody > tr > * {
    max-width: none !important;
  }

  /* Ignore fixed column widths */
  table:not(.fixed-width) col{
    width: auto !important;
  }

  /* Do not hyphenate words in the table */
  td.tableblock p,
  p.tableblock{
    hyphens: manual !important;
  }

  /* Vertical alignment */
  td.tableblock{
    vertical-align: top !important;
  }
</style>
++++
endif::[]

[abstract]
You can configure the Query service using cluster-level query settings, node-level query settings, and request-level query parameters.

There are three ways of configuring the Query service.
You can specify cluster-level settings for all nodes running the Query service in the cluster.
You can specify node-level settings for a single node running the Query service.
You can also specify parameters for individual requests.
Cluster-level query settings, node-level query settings, and request-level parameters must be set and used in different ways.

.Comparison of Query Settings and Parameters
[cols="216h,145,145,145,230"]
|===
| | Setting Per | Set By | Set On | Set Via

| Cluster-level query settings
| Cluster
| The administrator at the system level
| Server side
| The CLI, cURL statements, or the UI

| Node-level query settings
| Service Node
| The administrator at the system level
| Server side
| cURL statements

| Request-level parameters
| Request (statement)
| Each user
| Client side
| `cbq` command-line parameters, cURL statements, or client programming
|===

NOTE: Cluster-level settings and node-level settings are collectively referred to as [def]_service-level settings_.

== Query Setting Levels and Equivalents

Some query settings are cluster-level, node-level, or request-level only, while some apply to more than one level with slightly different names.

If a cluster-level setting has an equivalent node-level setting, then changing the cluster-level setting overwrites the node-level setting for all Query nodes in the cluster.

You can change a node-level setting for a single node to be different to the equivalent cluster-level setting.
Changing the node-level setting does not affect the equivalent cluster-level setting.
However, you should note that the node-level setting may be overwritten by subsequent changes at the cluster-level.
In particular, specifying query settings via the CLI or the UI makes changes at the cluster-level.

If a request-level parameter has an equivalent node-level setting, the node-level setting _usually_ acts as the default for the request-level parameter, as described in the tables below.
Setting a request-level parameter overrides the equivalent node-level setting.

Furthermore, for numeric values, if a request-level parameter has an equivalent node-level setting, the node-level setting dictates the upper-bound value of the request-level parameter.
For example, if the node-level `timeout` is set to 500, then the request-level parameter cannot be set to 501 or any value higher.

.Single-Level Settings
[.fixed-width, cols="1,1,1"]
|===
| Cluster-Level Only Settings | Node-Level Only Settings | Request-Level Only Parameters

a| <<queryTmpSpaceDir,queryTmpSpaceDir>>

<<queryTmpSpaceSize,queryTmpSpaceSize>>

<<queryCurlWhitelist,queryCurlWhitelist>>

a| <<auto-prepare,auto-prepare>>

<<completed,completed>>

<<cpuprofile,cpuprofile>>

<<debug,debug>>

<<distribute,distribute>>

<<keep-alive-length,keep-alive-length>>

<<max-index-api,max-index-api>>

<<memprofile,memprofile>>

<<mutexprofile,mutexprofile>>

<<request-size-cap,request-size-cap>>

<<servicers,servicers>>

a| <<args,args>>

<<auto_execute,auto_execute>>

<<batch_args,batch_args>>

<<batch_named_args,batch_named_args>>

<<client_context_id,client_context_id>>

<<compression,compression>>

<<creds,creds>>

<<encoded_plan,encoded_plan>> (deprecated)

<<encoding,encoding>>

<<format,format>>

<<metrics,metrics>>

<<namespace,namespace>>

<<prepared,prepared>>

<<readonly,readonly>>

<<scan_consistency,scan_consistency>>

<<scan_vector,scan_vector>>

<<scan_vectors,scan_vectors>>

<<scan_wait,scan_wait>>

<<signature,signature>>

<<statement,statement>>

<<use_fts,use_fts>>

<<identifier,${lt}__identifier__{gt}>>
|===

.Settings for Cluster-Level and Node-Level
[.fixed-width, cols="1,1,1"]
|===
| Cluster-Level Name | Node-Level Name | Request-Level Name

a| <<queryCompletedLimit,queryCompletedLimit>>

<<queryCompletedThreshold,queryCompletedThreshold>>

<<queryLogLevel,queryLogLevel>>

<<queryN1QLFeatCtrl,queryN1QLFeatCtrl>>

<<queryPreparedLimit,queryPreparedLimit>>

a| <<completed-limit,completed-limit>>

<<completed-threshold,completed-threshold>>

<<loglevel,loglevel>>

<<n1ql-feat-ctrl,n1ql-feat-ctrl>>

<<prepared-limit,prepared-limit>>

a| N/A
|===

.Settings for Node-Level and Request-Level
[.fixed-width, cols="1,1,1"]
|===
| Cluster-Level Name | Node-Level Name | Request-Level Name

a| N/A

a| <<controls-srv,controls>>

<<pretty-srv,pretty>>

<<profile-srv,profile>>

a| <<controls_req,controls>>

<<pretty_req,pretty>>

<<profile_req,profile>>
|===

.Settings for Cluster-Level, Node-Level, and Request-Level
[.fixed-width, cols="1,1,1"]
|===
| Cluster-Level Name | Node-Level Name | Request-Level Name

a| <<queryMaxParallelism,queryMaxParallelism>>

<<queryPipelineBatch,queryPipelineBatch>>

<<queryPipelineCap,queryPipelineCap>>

<<queryScanCap,queryScanCap>>

<<queryTimeout,queryTimeout>>

a| <<max-parallelism-srv,max-parallelism>>

<<pipeline-batch-srv,pipeline-batch>>

<<pipeline-cap-srv,pipeline-cap>>

<<scan-cap-srv,scan-cap>>

<<timeout-srv,timeout>>

a| <<max_parallelism_req,max_parallelism>>

<<pipeline_batch_req,pipeline_batch>>

<<pipeline_cap_req,pipeline_cap>>

<<scan_cap_req,scan_cap>>

<<timeout_req,timeout>>
|===

[[cluster-level-query-settings]]
== Cluster-Level Query Settings

To set a cluster-level query setting, use the xref:rest-api:rest-cluster-query-settings.adoc[Query Settings REST API] (`/settings/querySettings` endpoint) with a cURL statement, or the xref:manage:manage-settings/general-settings.adoc#query-settings[Advanced Query Settings] in the Couchbase Web Console.
You can also set all of the cluster-level query settings, except for the CURL() access list settings, using the xref:cli:cbcli/couchbase-cli-setting-query.adoc[setting-query] command.

The table below contains details of all cluster-level query settings.

.Cluster-Level Query Settings
include::rest-api:partial$query-settings/definitions.adoc[tag=settings]

[[_access]]
**Access**
include::rest-api:partial$query-settings/definitions.adoc[tag=access]

[[service-level-query-settings]]
== Node-Level Query Settings

To set a node-level query setting, use the xref:n1ql:n1ql-rest-api/admin.adoc[Admin REST API] (`/admin/settings` endpoint) with a cURL statement.

NOTE: These settings cannot be set by `cbq`.

====
To see a list of the current Query Settings, while the Query Service is running, enter:

[source,shell]
----
$ curl http://hostname:8093/admin/settings -u user:pword
----

This will output the entire list of node-level query settings:

[source,json]
----
{"auto-prepare":false,"completed":{"aborted":null,"threshold":1000},"completed-limit":4000,"completed-threshold":1000,"controls":false,"cpuprofile":"","debug":false,"functions-limit":16384,"keep-alive-length":16384,"loglevel":"INFO","max-index-api":4,"max-parallelism":1,"memprofile":"","mutexprofile":false,"n1ql-feat-ctrl":12,"pipeline-batch":16,"pipeline-cap":512,"prepared-limit":16384,"pretty":false,"profile":"off","request-size-cap":67108864,"scan-cap":512,"servicers":4,"timeout":0}
----

To output to a file for editing multiple settings at a single time, add the [.var]`-o filename` option.
For example:

[source,shell]
----
$ curl http://hostname:8093/admin/settings -u user:pword -o settings.txt
----
====

The table below contains details of all node-level query settings.

.Node-Level Query Settings
[[_settings]]
include::n1ql:partial$n1ql-rest-api/admin/definitions.adoc[tag=settings]

[#section_nnj_sjk_k1b]
== Request-Level Parameters

To set a request-level parameter, use the xref:n1ql:n1ql-rest-api/index.adoc[N1QL REST API] (`/query/service` endpoint) with a cURL statement, or the xref:tools:cbq-shell.adoc[cbq] command, or a client program.

While `cbq` is a sandbox to test code on your local machine, your production query settings are set with the cURL commands on your server.

The table below contains details of all request-level parameters, along with examples.

.Request-Level Parameters
[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema

| [[args]]
**args** +
__Optional__
| If the statement has 1 or more positional parameters, this parameter needs to be in the request; this is an array of JSON values, one for each positional parameter in the statement.

NOTE: Positional parameters apply to `prepared` also.

See section <<section_srh_tlm_n1b,Named Parameters VS. Positional Parameters>> for details.

.Example
[source,shell]
----
cbq> \set -args ["LAX", 6];
----
| array

| [[auto_execute]]
**auto_execute** +
__Optional__
| Specifies that prepared statements should be executed automatically as soon as they are created.
This saves you from having to make two separate requests in cases where you want to prepare a statement and execute it immediately.

Refer to xref:n1ql:n1ql-language-reference/prepare.adoc#auto-execute[Auto-Execute] for more information.

.Default
`false`

.Example
[source,shell]
----
cbq> \set -auto_execute true;

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=prepare select * from default&auto_execute=true'
----
| boolean

| [[batch_args]]
**batch_args** +
__Optional__
| Applies to POST requests only, containing UPDATE, INSERT, DELETE statements (DML statements) with _positional_ parameters.

.Example
[source,n1ql]
----
INSERT INTO location (id, name) VALUES ($1, $2)
----

These require the values to be given in `batch_args`, which contains an array of arrays.

NOTE: The inner arrays need to match the positional parameters in the `statement`.
| array of arrays

| [[batch_named_args]]
**batch_named_args** +
__Optional__
| Applies to POST requests only, containing UPDATE, INSERT, DELETE statements (DML statements) with _named_ parameters.

.Example
[source,n1ql]
----
INSERT INTO location (id, name) VALUES ($id, $n)
----

These require the values to be given in `batch_named_args`, which contains an array of objects.

NOTE: The keys in each object need to match the named parameters in the `statement`.
| array of objects

| [[client_context_id]]
**client_context_id** +
__Optional__
| A piece of data supplied by the client that is echoed in the response, if present.
N1QL is agnostic about the content of this parameter; it is just echoed in the response.

[NOTE]
--
* Maximum allowed size is 64 characters; all others will be cut.
* If it contains an escape character (‘/’) or quote ("), it will be rejected as Error code 1110.
--
| string

| [[compression]]
**compression** +
__Optional__
| Compression format to use for response data on the wire.

Values are case-insensitive.

.Default
`"NONE"`

.Example
[source,shell]
----
cbq> \set -compression "zip";
----
| enum (ZIP, RLE, LZMA, LZO, NONE)

| [[controls_req]]
**controls** +
__Optional__
| Specifies if there should be a controls section returned with the request results.

When set to `true`, the query response document includes a controls section with runtime information provided along with the request, such as positional and named parameters or settings.

NOTE: If the request qualifies for caching, these values will also be cached in the `completed_requests` system keyspace.

The {controls-srv}[node-level] `controls` setting specifies the default for this parameter for a single node.
The request-level parameter overrides the node-level setting.

.Example
[source,shell]
----
cbq> \set -controls true;

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=select * from default&controls=true'
----
| boolean

| [[creds]]
**creds** +
__Optional__
| Specify the login credentials in the form of `user:password`.

You can specify credentials for different keyspaces by separating them with a comma.

If credentials are supplied in the request header, then `creds` is ignored since HTTP Basic Authentication takes precedence and overrides `creds`.

.Example
[source,shell]
----
cbq> \set -creds travel-sample user:pword, beer-sample user:pword;
----
| array

// To be added after confirming the latest info
// <p>See Authentication Parameters
// section <?oxy_custom_start type="oxy_content_highlight" color="255,255,0"?>at GD:
// N1QL Query API<?oxy_custom_end?> for full spec.</p>

| [[encoded_plan]]
**encoded_plan** +
__Optional__
| In Couchbase Server 6.5 and later, this parameter is ignored and has no effect.
It is included for compatibility with previous versions of Couchbase Server.
| string

| [[encoding]]
**encoding** +
__Optional__
| Desired character encoding for the query results.

Only possible value is `UTF-8` and is case-insensitive.

.Default
`"UTF-8"`

| string

| [[format]]
**format** +
__Optional__
| Desired format for the query results.

Values are case-insensitive.

.Default
`"JSON"`

.Example
[source,shell]
----
cbq> \set -format "XML";
----
| enum (JSON, XML, CSV, TSV)

| [[max_parallelism_req]]
**max_parallelism** +
__Optional__
| Specifies the maximum parallelism for the query.

The {max-parallelism-srv}[node-level] `max_parallelism` setting specifies the ceiling for this parameter for a single node.
If the request-level parameter is zero or negative, the parallelism for the query is set to the node-level setting.
Similarly, if the request-level parameter is greater than the node-level setting, the parallelism for the query is limited to the node-level setting.

In addition, the {queryMaxParallelism}[cluster-level] `queryMaxParallelism` setting specifies the ceiling for this parameter for the whole cluster.
When you change the cluster-level setting, the node-level setting is overwritten for all nodes in the cluster.

[NOTE]
To enable queries to run in parallel, you must specify the cluster-level `queryMaxParallelism` parameter, or specify the node-level `max-parallelism` parameter on all Query nodes.

.Default
The same as the number of partitions of the index selected for the query.

.Example
[source,shell]
----
cbq> \set -max_parallelism 3;

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=select * from default&max_parallelism=3'
----
| integer (int32)

| [[metrics]]
**metrics** +
__Optional__
| Specifies that metrics should be returned with query results.

.Default
`true`

.Example
[source,shell]
----
cbq> \set -metrics false;

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=select * from default&metrics=false'
----
| boolean

| [[namespace]]
**namespace** +
__Optional__
| Specifies the namespace to use.

.Example
[source,shell]
----
cbq> \set -namespace travel-sample;
----
| string

| [[pipeline_batch_req]]
**pipeline_batch** +
__Optional__
| Controls the number of items execution operators can batch for Fetch from the KV.

The {pipeline-batch-srv}[node-level] `pipeline-batch` setting specifies the default for this parameter for a single node.
The request-level parameter overrides the node-level setting, but only if it is lower than the node-level setting.

In addition, the {queryPipelineBatch}[cluster-level] `queryPipelineBatch` setting specifies the default for this parameter for the whole cluster.
When you change the cluster-level setting, the node-level setting is overwritten for all nodes in the cluster.

.Example
[source,shell]
----
cbq> \set -pipeline_batch 64;

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=select * from default&pipeline_batch=64'
----
| integer (int32)

| [[pipeline_cap_req]]
**pipeline_cap** +
__Optional__
| Maximum number of items each execution operator can buffer between various operators.

The {pipeline-cap-srv}[node-level] `pipeline-cap` setting specifies the default for this parameter for a single node.
The request-level parameter overrides the node-level setting, but only if it is lower than the node-level setting.

In addition, the {queryPipelineCap}[cluster-level] `queryPipelineCap` setting specifies the default for this parameter for the whole cluster.
When you change the cluster-level setting, the node-level setting is overwritten for all nodes in the cluster.

.Example
[source,shell]
----
cbq> \set -pipeline_cap 1024;

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=select * from default&pipeline_cap=1024'
----
| integer (int32)

| **prepared** +
__Required if__ `statement` __not provided__
| [[prepared]]
The prepared form of the N1QL statement to be executed.

NOTE: If both `prepared` and `statement` are present and non-empty, an error is returned.

.Example
Prepare the query result of the most expensive hotel:
[source,shell]
$ curl -v http://localhost:8093/query/service -d 'statement=PREPARE pricy_hotel FROM SELECT MAX(price) FROM `travel-sample` WHERE type="hotel";'

Response:
[source,json]
----
{
  "requestID": "b7f03c4e-06f6-4d23-bd14-b5c8ecfe0e2e",
  "signature": "json",
  "results": [
    {"encoded_plan":"H4sIAAAAAAAA/wEAAP//AAAAAAAAAAA=",
    "featureControls":12,
    "indexApiVersion":3,
    "name":"[127.0.0.1:8091]pricy_hotel",
...
    }
  ]
}
----

Execute the prepared statement:

[source,shell]
$ curl -v http://localhost:8093/query/service -H "Content-Type: application/json" -d '{ "prepared":"[127.0.0.1:8091]pricy_hotel" }'
| string

| [[pretty_req]]
**pretty** +
__Optional__
| Specifies the query results returned in pretty format.

The {pretty-srv}[node-level] `pretty` setting specifies the default for this parameter for a single node.
The request-level parameter overrides the node-level setting.

.Example
[source,shell]
----
cbq> \set -pretty false;

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=select * from default&pretty=false'
----
| boolean

| [[profile_req]]
**profile** +
__Optional__
| Specifies if there should be a profile section returned with the request results.
The valid values are:

`off`:: No profiling information is added to the query response.

`phases`::
The query response includes a profile section with stats and details about various phases of the query plan and execution.
Three phase times will be included in the `system:active_requests` and `system:completed_requests` monitoring keyspaces.

`timings`::
Besides the phase times, the profile section of the query response document will include a full query plan with timing and information about the number of processed documents at each phase.
This information will be included in the `system:active_requests` and `system:completed_requests` keyspaces.

NOTE: If `profile` is not set as one of the above values, then the profile setting does not change.

The {profile-srv}[node-level] `profile` setting specifies the default for this parameter for a single node.
The request-level parameter overrides the node-level setting.

.Example
[source,shell]
----
cbq> \set -profile "phases";

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=select * from default&profile=phases'
----
| enum (off, phases, timings)

| [[readonly]]
**readonly** +
__Optional__
| Controls whether a query can change a resulting recordset.

If `readonly` is `true`, then the following statements are not allowed:

* CREATE INDEX
* DROP INDEX
* INSERT
* MERGE
* UPDATE
* UPSERT

NOTE: When using GET requests, it's best to set `readonly` to `true`.

.Default
`false`

.Example
[source,shell]
----
cbq> \set -readonly true;
----
| boolean

| [[scan_cap_req]]
**scan_cap** +
__Optional__
| Maximum buffered channel size between the indexer client and the query service for index scans.
This parameter controls when to use scan backfill.

Use `0` or a negative number to disable.
Smaller values reduce GC, while larger values reduce indexer backfill.

The {scan-cap-srv}[node-level] `scan-cap` setting specifies the default for this parameter for a single node.
The request-level parameter overrides the node-level setting, but only if it is lower than the node-level setting.

In addition, the {queryPipelineCap}[cluster-level] `queryPipelineCap` setting specifies the default for this parameter for the whole cluster.
When you change the cluster-level setting, the node-level setting is overwritten for all nodes in the cluster.

.Example
[source,shell]
----
cbq> \set -scan_cap 1024;

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=select * from default&scan_cap=1024'
----
| integer (int32)

| [[scan_consistency]]
**scan_consistency** +
__Optional__
| Specify the consistency guarantee/constraint for index scanning.
The valid values are:

`not_bounded`::
No timestamp vector is used in the index scan.
This is the fastest mode, because it avoids the costs of obtaining the vector and waiting for the index to catch up to the vector.

`at_plus`::
This implements bounded consistency.
The request includes a scan_vector parameter and value, which is used as a lower bound.
This can be used to implement read-your-own-writes (RYOW).

`request_plus`::
This implements strong consistency per request.
Before processing the request, a current vector is obtained.
The vector is used as a lower bound for the statements in the request.
If there are DML statements in the request, RYOW is also applied within the request.

`statement_plus`::
This implements strong consistency per statement.
Before processing each statement, a current vector is obtained and used as a lower bound for that statement.

NOTE: The default behavior is RYOW within the request, however, if you want to disable RYOW within a request, add a separate `request_consistency` parameter that can be set to `not_bounded`.

Values are case-insensitive.

.Default
`"not_bounded"`

.Example
[source,shell]
----
cbq> \set -scan_consistency "at_plus";
----
| enum (not_bounded, at_plus, request_plus, statement_plus)

| [[scan_vector]]
**scan_vector** +
__Required if__ `scan_consistency` __is__ `at_plus` __and__ `scan_vectors` __not provided__
| Specify the lower bound vector timestamp for one keyspace when using `at_plus` scan consistency.

Scan vectors are built of two-element +[+[.var]`value`, [.var]`guard`] entries:

* [.var]`value`: a vBucket's sequence number (a JSON number)
* [.var]`guard`: a vBucket's UUID (a string)

Scan vectors have two forms:

. *Full scan vector*: an array of +[+[.var]`value`, [.var]`guard`] entries, giving an entry for every vBucket in the system.
. *Sparse scan vectors*: an object providing entries for specific vBuckets, mapping a vBucket number (a string) to each +[+[.var]`value`, [.var]`guard`] entry.

NOTE: `scan_vector` can only be used if the query uses at most one keyspace; if it is used for a query referencing more than one keyspace, the query will fail with an error.

For queries referencing multiple keyspaces, use `scan_vectors`.

.Example
[source,shell]
----
scan_vector={ "5 ": [5409393,"VB5ID"], "19": [47574574, "VB19ID"] }
----
| array, object

| [[scan_vectors]]
**scan_vectors** +
__Required if__ `scan_consistency` __is__ `at_plus` __and__ `scan_vector` __not provided__
| A map from keyspace names to scan vectors.
See `scan_vector`.

The scan vectors can be Full or Sparse.
| object

| [[scan_wait]]
**scan_wait** +
__Optional__
| Can be supplied with `scan_consistency` values of `request_plus`, `statement_plus` and `at_plus`.

Specifies the maximum time the client is willing to wait for an index to catch up to the vector timestamp in the request.

NOTE: If an index has to catch up, and the `scan_wait` time is exceeded while waiting, an error is returned.

Its format includes an amount and a mandatory unit, e.g. `10ms` (10 milliseconds) or `0.5s` (half a second).
Valid units are:

* `ns` (nanoseconds)
* `us` (microseconds)
* `ms` (milliseconds)
* `s` (seconds)
* `m` (minutes)
* `h` (hours)

NOTE: Specify `0` or a negative integer to disable.

.Default
`""`

.Example
[source,shell]
----
cbq> \set -scan_wait "30m";
----
| string (duration)

| [[signature]]
**signature** +
__Optional__
| Include a header for the results schema in the response.

.Default
`true`

.Example
[source,shell]
----
cbq> \set -signature false;

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=select * from default&signature=false'
----
| boolean

| [[statement]]
**statement** +
__Required if__ `prepared` __not provided__
| Any valid N1QL statement for a POST request, or a read-only N1QL statement (SELECT, EXPLAIN) for a GET request.

NOTE: If both `prepared` and `statement` are present and non-empty, an error is returned.
| string

| [[timeout_req]]
**timeout** +
__Optional__
| Maximum time to spend on the request before timing out.

Specify a duration of `0` or a negative duration to disable.
When disabled, no timeout is applied and the request runs for however long it takes.

The {timeout-srv}[node-level] `timeout` setting specifies the default for this parameter for a single node.
The request-level parameter overrides the node-level setting, but only if it is lower than the node-level setting.

In addition, the {queryTimeout}[cluster-level] `queryTimeout` setting specifies the default for this parameter for the whole cluster.
When you change the cluster-level setting, the node-level setting is overwritten for all nodes in the cluster.

The request-level `timeout` parameter is a string.
Its format includes an amount and a mandatory unit, e.g. `10ms` (10 milliseconds) or `0.5s` (half a second).
Valid units are:

* `ns` (nanoseconds)
* `us` (microseconds)
* `ms` (milliseconds)
* `s` (seconds)
* `m` (minutes)
* `h` (hours)

.Example
[source,shell]
----
cbq> \set -timeout "30m";

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=select * from default&timeout=30m'
----
| string (duration)

| [[use_fts]]
**use_fts** +
__Optional__
| [.edition]#{enterprise}#

Specifies that the query should use a full-text index.

If the query contains a `USING FTS` hint, that takes priority over this parameter.

If the query does not contain a `USING FTS` hint, and this parameter is set to true, all full-text indexes are considered for the query.
If a qualified full-text index is available, it is selected for the query.
If none of the available full-text indexes are qualified, the available GSI indexes are considered instead.

Refer to xref:n1ql:n1ql-language-reference/flex-indexes.adoc[Flex Indexes] for more information.

.Default
`false`

.Example
[source,shell]
----
cbq> \set -use_fts true;

$ curl http://localhost:8093/query/service -u user:pword -d 'statement=select * from default&use_fts=true'
----
| boolean

| [[identifier]]
**$<identifier>** +
__Optional__
| If the `statement` has 1 or more named parameters, there should be 1 or more named parameters in the request.

A named parameter consists of two parts:

. The $ character
. An identifier that starts with an alpha character followed by one or more alphanumeric characters.

Named parameters apply to `prepared` also.

See section <<section_srh_tlm_n1b,Named Parameters VS.
Positional Parameters>> for examples.
| JSON value
|===

[#section_srh_tlm_n1b]
== Named Parameters VS. Positional Parameters

Named Parameters use a variable name to refer to each one, while Positional Parameters refer to the position each variable is used.
As summarized in the below table, these two types of requests should contain the following parameters:

.Named Parameters VS. Positional Parameters
[cols="2h,5,2"]
|===
| | Statement | Args

| Named Parameters
a| [source,n1ql]
SELECT detail FROM emp WHERE name = $nval AND age > $aval
| $nval = "smith"

$aval = 45

| Positional Parameters
a| [source,n1ql]
SELECT detail FROM emp WHERE name = $1 AND age > $2

[source,n1ql]
SELECT detail FROM emp WHERE name = ? AND age > ?
| [ "smith", 45 ]
|===

NOTE: Positional Parameters can also be specified in a statement using *?* as an alternative way to specify the same query.

== Related Links

For more details about the N1QL REST API, refer to  xref:n1ql:n1ql-rest-api/index.adoc[N1QL REST API].

For more details about the Admin REST API, refer to xref:n1ql:n1ql-rest-api/admin.adoc[Admin REST API].

For more details about the Query Settings API, refer to xref:rest-api:rest-cluster-query-settings.adoc[Cluster Query Settings API].

For more details about API content and settings, refer to xref:rest-api:rest-intro.adoc[REST API reference].
