= Settings and Parameters
:description: You can configure the Query service using cluster-level query settings, node-level query settings, and request-level query parameters.
:page-aliases: manage:manage-settings/query-settings
:tabs:

// External cross-references
:rest-cluster-query-settings: xref:rest-api:rest-cluster-query-settings.adoc
:general-settings-query-settings: xref:manage:manage-settings/general-settings.adoc#query-settings
:couchbase-cli-setting-query: xref:cli:cbcli/couchbase-cli-setting-query.adoc
:n1ql-rest-api-admin: xref:n1ql:n1ql-rest-api/admin.adoc
:n1ql-rest-api-index: xref:n1ql:n1ql-rest-api/index.adoc
:cbq-shell: xref:tools:cbq-shell.adoc
:rest-intro: xref:rest-api:rest-intro.adoc
:query-preferences: xref:tools:query-workbench.adoc#query-preferences

// Pass through HTML table styles for this page

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* No maximum width for table cells */
  .doc table.spread > tbody > tr > *,
  .doc table.stretch > tbody > tr > * {
    max-width: none !important;
  }

  /* Wrap code listings in table cells */
  td .listingblock .content pre code {
    white-space: pre-wrap !important;
  }

  /* Ignore fixed column widths */
  table:not(.fixed-width) col{
    width: auto !important;
  }

  /* Do not hyphenate words in the table */
  td.tableblock p,
  p.tableblock{
    hyphens: manual !important;
  }

  /* Vertical alignment */
  td.tableblock{
    vertical-align: top !important;
  }
</style>
++++
endif::[]

[abstract]
{description}

There are three ways of configuring the Query service.
You can specify cluster-level settings for all nodes running the Query service in the cluster.
You can specify node-level settings for a single node running the Query service.
You can also specify parameters for individual requests.
Cluster-level query settings, node-level query settings, and request-level parameters must be set and used in different ways.

.Comparison of Query Settings and Parameters
[cols="216s,145,145,145,230"]
|===
| | Setting Per | Set By | Set On | Set Via

| Cluster-level query settings
| Cluster
| The administrator at the system level
| Server side
| The CLI, cURL statements, or the UI

| Node-level query settings
| Service Node
| The administrator at the system level
| Server side
| cURL statements

| Request-level parameters
| Request (statement)
| Each user
| Client side
| `cbq` command-line parameters, cURL statements, client programming, or the UI
|===

NOTE: Cluster-level settings and node-level settings are collectively referred to as [def]_service-level settings_.

== Query Setting Levels and Equivalents

Some query settings are cluster-level, node-level, or request-level only, while some apply to more than one level with slightly different names.

If a cluster-level setting has an equivalent node-level setting, then changing the cluster-level setting overwrites the node-level setting for all Query nodes in the cluster.

You can change a node-level setting for a single node to be different to the equivalent cluster-level setting.
Changing the node-level setting does not affect the equivalent cluster-level setting.
However, you should note that the node-level setting may be overwritten by subsequent changes at the cluster-level.
In particular, specifying query settings via the CLI or the UI makes changes at the cluster-level.

If a request-level parameter has an equivalent node-level setting, the node-level setting _usually_ acts as the default for the request-level parameter, as described in the tables below.
Setting a request-level parameter overrides the equivalent node-level setting.

Furthermore, for numeric values, if a request-level parameter has an equivalent node-level setting, the node-level setting dictates the upper-bound value of the request-level parameter.
For example, if the node-level `timeout` is set to 500, then the request-level parameter cannot be set to 501 or any value higher.

== All Query Settings

.Single-Level Settings -- Not Equivalent
[.fixed-width, cols="1,1,1"]
|===
| Cluster-Level Only Settings | Node-Level Only Settings | Request-Level Only Parameters

a| [%hardbreaks]
<<queryTmpSpaceDir,queryTmpSpaceDir>>
<<queryTmpSpaceSize,queryTmpSpaceSize>>
<<queryCurlWhitelist,queryCurlWhitelist>>

a| [%hardbreaks]
<<auto-prepare,auto-prepare>>
<<completed,completed>>
<<cpuprofile,cpuprofile>>
<<debug,debug>>
<<distribute,distribute>>
<<functions-limit,functions-limit>>
<<keep-alive-length,keep-alive-length>>
<<max-index-api,max-index-api>>
<<memprofile,memprofile>>
<<mutexprofile,mutexprofile>>
<<plus-servicers,plus-servicers>>
<<request-size-cap,request-size-cap>>
<<servicers,servicers>>

a| [%hardbreaks]
<<args,args>>
<<auto_execute,auto_execute>>
<<client_context_id,client_context_id>>
<<compression,compression>>
<<creds,creds>>
<<durability_level,durability_level>>
<<encoded_plan,encoded_plan>> (deprecated)
<<encoding,encoding>>
<<format,format>>
<<kvtimeout,kvtimeout>>
<<metrics,metrics>>
<<namespace,namespace>>
<<prepared,prepared>>
<<preserve_expiry,preserve_expiry>>
<<query_context,query_context>>
<<readonly,readonly>>
<<scan_consistency,scan_consistency>>
<<scan_vector,scan_vector>>
<<scan_vectors,scan_vectors>>
<<scan_wait,scan_wait>>
<<signature,signature>>
<<statement,statement>>
<<txid,txid>>
<<txstmtnum,txstmtnum>>
<<tximplicit,tximplicit>>
<<txdata,txdata>>
<<use_fts,use_fts>>
<<identifier,${lt}__identifier__{gt}>>
|===

.Equivalent Settings for Cluster-Level and Node-Level
[.fixed-width, cols="1,1,1"]
|===
| Cluster-Level Name | Node-Level Name | Request-Level Name

a| [%hardbreaks]
<<queryCleanupClientAttempts,queryCleanupClientAttempts>>
<<queryCleanupLostAttempts,queryCleanupLostAttempts>>
<<queryCleanupWindow,queryCleanupWindow>>
<<queryCompletedLimit,queryCompletedLimit>>
<<queryCompletedThreshold,queryCompletedThreshold>>
<<queryLogLevel,queryLogLevel>>
<<queryN1qlFeatCtrl,queryN1qlFeatCtrl>>
<<queryPreparedLimit,queryPreparedLimit>>

a| [%hardbreaks]
<<cleanupclientattempts,cleanupclientattempts>>
<<cleanuplostattempts,cleanuplostattempts>>
<<cleanupwindow,cleanupwindow>>
<<completed-limit,completed-limit>>
<<completed-threshold,completed-threshold>>
<<loglevel,loglevel>>
<<n1ql-feat-ctrl,n1ql-feat-ctrl>>
<<prepared-limit,prepared-limit>>

a| N/A
|===

.Equivalent Settings for Node-Level and Request-Level
[.fixed-width, cols="1,1,1"]
|===
| Cluster-Level Name | Node-Level Name | Request-Level Name

a| N/A

a| [%hardbreaks]
<<atrcollection-srv,atrcollection>>
<<controls-srv,controls>>
<<pretty-srv,pretty>>
<<profile-srv,profile>>

a| [%hardbreaks]
<<atrcollection_req,atrcollection>>
<<controls_req,controls>>
<<pretty_req,pretty>>
<<profile_req,profile>>
|===

.Equivalent Settings for Cluster-Level, Node-Level, and Request-Level
[.fixed-width, cols="1,1,1"]
|===
| Cluster-Level Name | Node-Level Name | Request-Level Name

a| [%hardbreaks]
<<queryMaxParallelism,queryMaxParallelism>>
<<queryMemoryQuota,queryMemoryQuota>>
<<queryNumAtrs,queryNumAtrs>>
<<queryPipelineBatch,queryPipelineBatch>>
<<queryPipelineCap,queryPipelineCap>>
<<queryScanCap,queryScanCap>>
<<queryTimeout,queryTimeout>>
<<queryTxTimeout,queryTxTimeout>>
<<queryUseCBO,queryUseCBO>>

a| [%hardbreaks]
<<max-parallelism-srv,max-parallelism>>
<<memory-quota-srv,memory-quota>>
<<numatrs-srv,numatrs>>
<<pipeline-batch-srv,pipeline-batch>>
<<pipeline-cap-srv,pipeline-cap>>
<<scan-cap-srv,scan-cap>>
<<timeout-srv,timeout>>
<<txtimeout-srv,txtimeout>>
<<use-cbo-srv,use-cbo>>

a| [%hardbreaks]
<<max_parallelism_req,max_parallelism>>
<<memory_quota_req,memory_quota>>
<<numatrs_req,numatrs>>
<<pipeline_batch_req,pipeline_batch>>
<<pipeline_cap_req,pipeline_cap>>
<<scan_cap_req,scan_cap>>
<<timeout_req,timeout>>
<<txtimeout_req,txtimeout>>
<<use_cbo_req,use_cbo>>
|===

[[cluster-level-query-settings]]
== Cluster-Level Query Settings

To set a cluster-level query setting, use the {rest-cluster-query-settings}[Query Settings REST API] (`/settings/querySettings` endpoint) with a cURL statement, or the {general-settings-query-settings}[Advanced Query Settings] in the Couchbase Web Console.
You can also set all of the cluster-level query settings using the {couchbase-cli-setting-query}[setting-query] command.

The table below contains details of all cluster-level query settings.

.Cluster-Level Query Settings
include::rest-api:partial$query-settings/definitions.adoc[tag=settings]

[[_access]]
**Access**
include::rest-api:partial$query-settings/definitions.adoc[tag=access]

[[service-level-query-settings]]
== Node-Level Query Settings

To set a node-level query setting, use the {n1ql-rest-api-admin}[Admin REST API] (`/admin/settings` endpoint) with a cURL statement.
These settings cannot be set by `cbq`.

====
To see a list of the current Query Settings, while the Query Service is running, enter:

[source,sh]
----
include::example$node-level-settings.sh[tag=curl]
----

This will output the entire list of node-level query settings:

[source,json]
----
include::example$node-level-settings.jsonc[]
----

To output to a file for editing multiple settings at a single time, add the [.var]`-o filename` option.
For example:

[source,sh]
----
include::example$save-node-level-settings.sh[tag=curl]
----
====

The table below contains details of all node-level query settings.

.Node-Level Query Settings
[[_settings]]
include::n1ql:partial$n1ql-rest-api/admin/definitions.adoc[tag=settings]

[#section_nnj_sjk_k1b]
== Request-Level Parameters

To set a request-level parameter, use the {n1ql-rest-api-index}[] (`/query/service` endpoint) with a cURL statement, or the {cbq-shell}[cbq] command, or a client program.
You can also set request-level parameters using the {query-preferences}[Run-Time Preferences] window in the Query Workbench.

While `cbq` is a sandbox to test code on your local machine, your production query settings are set with the cURL commands on your server.

[tabs]
====
CBQ Shell::
+
--
To set request-level parameters in `cbq`, use the `\SET` command.
The parameter name must be prefixed by a hyphen.

[source,sqlpp]
----
\SET -timeout "30m";
\SET -pretty true;
\SET -max_parallelism 3;
SELECT * FROM "world" AS hello;
----
--

REST API::
+
--
To set request-level parameters with the REST API, specify the parameters in the request body or the query URI.

[source,sh]
----
curl http://localhost:8093/admin/settings -u Administrator:password \
  -d 'statement=SELECT * FROM "world" AS hello;
    & timeout=30m
    & pretty=true
    & max_parallelism=3'
----
--
====

The table below contains details of all request-level parameters, along with examples.

.Request-Level Parameters
include::n1ql:partial$n1ql-rest-api/query/definitions.adoc[tag=settings]

[[_credentials]]
**Credentials**
include::n1ql:partial$n1ql-rest-api/query/definitions.adoc[tag=credentials]

[discrete,#transactional-scan-consistency]
===== Transactional Scan Consistency

If the request contains a `BEGIN TRANSACTION` statement, or a DML statement with the {tximplicit}[tximplicit] parameter set to `true`, then the <<scan_consistency,scan_consistency>> parameter sets the [def]__transactional scan consistency__.
If you specify a transactional scan consistency of `request_plus`, `statement_plus`, or `at_plus`, or if you specify no transactional scan consistency, the transactional scan consistency is set to `request_plus`; otherwise, the transactional scan consistency is set as specified.

.Transactional scan consistency
[%header, cols="2"]
|===
| Scan consistency at start of transaction
| Transactional scan consistency

| Not set
| `request_plus`

| `not_bounded`
| `not_bounded`

| `request_plus` +
  `statement_plus` +
  `at_plus`
| `request_plus`
|===

Any DML statements within the transaction that have no scan consistency set will inherit from the transactional scan consistency.
Individual DML statements within the transaction may override the transactional scan consistency.
If you specify a scan consistency of `not_bounded` for a statement within the transaction, the scan consistency for the statement is set as specified.
When you specify a scan consistency of `request_plus`, `statement_plus`, or `at_plus` for a statement within the transaction, the scan consistency for the statement is set to `request_plus`.

However, `request_plus` consistency is not supported for statements using a full-text index.
If any statement within the transaction uses a full-text index, by means of the SEARCH function or the Flex Index feature, the scan consistency is set to `not_bounded` for the duration of the full-text search.

.Overriding the transactional scan consistency
[%header, cols="2"]
|===
| Scan consistency for statement within transaction
| Inherited scan consistency

| Not set
| Transactional scan consistency +
 (`not_bounded` for full-text search)

| `not_bounded`
| `not_bounded`

| `request_plus` +
  `statement_plus` +
  `at_plus`
| `request_plus` +
 (`not_bounded` for full-text search)
|===

[#section_srh_tlm_n1b]
== Named Parameters and Positional Parameters

_Named parameters_ use a <<identifier,variable name>> to define the value of each parameter, while numbered and unnumbered _positional parameters_ use a <<args,list of arguments>> to define the value of each parameter by position.
Requests which use named parameters and positional parameters should contain the appropriate placeholders, as summarized in the table below.

include::ROOT:partial$query-context.adoc[tag=section]

.Named Parameters and Positional Parameters
[cols="2a,3a"]
|===
| Arguments | Statement

|
.Named Parameters
[source.no-callouts,sqlpp]
----
include::example$param-names.n1ql[tag=arguments]
----

|
.{nbsp}
[source,sqlpp]
----
include::example$param-names.n1ql[tag=statement]
----

|
.Positional Parameters
[source.no-callouts,sqlpp]
----
include::example$param-numbers.n1ql[tag=arguments]
----

|
.{nbsp}
[source,sqlpp]
----
include::example$param-numbers.n1ql[tag=statement]
----

[source,sqlpp]
----
include::example$param-positions.n1ql[tag=statement]
----
|===

== Related Links

* For more details about the {sqlpp} REST API, refer to {n1ql-rest-api-index}[].
* For more details about the Admin REST API, refer to {n1ql-rest-api-admin}[].
* For more details about the Query Settings API, refer to {rest-cluster-query-settings}[].
* For more details about API content and settings, refer to {rest-intro}[].
