= Authorization for administrators
:page-topic-type: concept

[abstract]
Authorization defines what Couchbase administrators can perform after they connect to the system.

There are two types of Couchbase administrators: full administrators and read-only administrators.

== Authorization for full administrators

Full Couchbase administrator::
The initial built-in full Couchbase administrator authenticated during Couchbase Server installation has the full access and privileges to manage all Couchbase Server functions.
There is one full administrator per Couchbase Server and his user ID is mapped from the LDAP server using the Couchbase Web Console, as explained in xref:security-authentication.adoc[Authentication].

Full LDAP administrators::
The full LDAP administrators are set up only when then LDAP authentication is enabled for Couchbase Server.
There can be multiple LDAP administrators per Couchbase Server and they are set using the Couchbase Web Console.

== Authorization for read-only administrators

Read-only Couchbase administrator::
The read-only Couchbase administrator has a restricted read-only access to Couchbase Server functions.
The read-only administrator can view certain activities without having ability to edit.
+
These administrators are set up using the Couchbase Web Console.

Read-only LDAP administrators::
Read-only LDAP administrators are set up only when LDAP authentication is enabled for Couchbase Server.
They can view certain activities without having ability to edit.
+
These administrators are set up using the Couchbase Web Console.
