= RBAC User Management

[abstract]
Couchbase RBAC allows defined _users_ to be assigned roles, which permit access to resources.

== Specifying Names

Both role-names and user-names are _case sensitive_.

== Authentication Domains

Couchbase Server assigns users to different authentication domains, based on whether their definition is local (that is, on Couchbase Server itself) or external (that is, by means of LDAP or PAM).

For information, see xref:security-authentication.adoc[Authentication].

== Creating Users

Users can be created in the following ways:

* With the Couchbase Web Console: See xref:security-rbac-for-admins-and-apps.adoc[Creating and Managing Users with the UI].

* By means of the Couchbase CLI command xref:cli:cbcli/couchbase-cli-user-manage.adoc[user-manage].

For restrictions on username-design, see xref:security-passwords.adoc[Couchbase Passwords].

== Resetting a User Password

A user's password can be set in the following ways:

* With the Couchbase Web Console.
See xref:security-rbac-for-admins-and-apps.adoc[Creating and Managing Users with the UI].

* By means of the Couchbase CLI command xref:cli:cbcli/couchbase-cli-user-manage.adoc[user-manage].

Note that a default Couchbase password policy is provided: this can be modified by the Full Administrator.
See the Couchbase CLI command xref:cli:cbcli/couchbase-cli-setting-password-policy.adoc[setting-password-policy].

For best practices for password-definition, see xref:security-passwords.adoc[Couchbase Passwords].

== Viewing Users

Currently defined users can be viewed in the following ways:

* With the Couchbase Web Console.
See xref:security-rbac-for-admins-and-apps.adoc[Creating and Managing Users with the UI].

== Granting and Revoking Roles

Roles can be granted and revoked as follows:

* *Granted*: With the N1QL `GRANT ROLE` statement.
See xref:n1ql:n1ql-language-reference/grant.adoc#topic_11_5[GRANT].

* *Revoked*: With the N1QL `REVOKE ROLE` statement.
See xref:n1ql:n1ql-language-reference/revoke.adoc#topic_11_5[REVOKE].
