= Security Best Practices
:page-topic-type: concept

[abstract]
Security best practices consist of guidelines and tips to provide security features throughout the network.

Security is needed on the whole Couchbase infrastructure including the internal, perimeter, and outside network.
It must be maintained and continually kept up-to-date to safeguard against malware and hackers.

You must enforce security throughout the network:

Inside Couchbase Server:: Inside the server, security is safeguarded by:

* xref:security-passwords.adoc[password enforcement]
* xref:security-bucket-protection.adoc[bucket authentication and protection]
* xref:security-authentication.adoc[secure administrative access]
* xref:security-access-logs.adoc[access logs]

+
To secure the host machine where Couchbase Server is installed, follow the security best practices and encrypt certain data locations with transparent data encryption technologies offered by 3rd party on-disk encryption software vendors such as:

* Vormetric: http://www.couchbase.com/binaries/content/assets/us/partner-collateral/vormetric/couchbase-vormetric-solution-brief.pdf[click^] to download more information.
* SafeNet
* Protegrity

Outside Couchbase Server:: Outside the server, security is enforced by properly configuring xref:security-iptables.adoc[IP tables and ports.]

In applications:: Security in applications is enforced by paying attention to xref:security-config-cache.adoc[client configuration cache] and xref:security-user-input.adoc[user input validation].

In the cloud:: To enforce security in the Couchbase cloud, you must securely configure the xref:security-acls-new.adoc[Network Access Control Lists (ACLs) and security groups] as well as xref:xdcr:xdcr-intro.adoc[Cross Datacenter Replication (XDCR)].
