= Troubleshooting LDAP settings
:page-topic-type: concept

[abstract]
What can go wrong with the LDAP setup?

After you set up the LDAP server, `saslauthd`, and LDAP administrators, some issues might remain such as:

* Firewall ports are not open for LDAP.
* The Proxy did not start or has started with an inappropriate protocol or hostname.
* The configuration of saslauthd is incorrect (look at [.path]_/etc/sysconfig/saslauthd_ or [.path]_/etc/saslauthd.conf_)
* The LDAP filters are not correct.
* You can also encounter error messages from the system.
These errors belong either to issues caused by `saslauthd` or the LDAP server.

== Common error messages

Errors caused by `saslauthd`:::
+
----
.....
      "dial unix /var/run.sasl2/mux: no such file or directory"
----
+
Possible reason for the error: no LDAP server was installed.

* Before installing the server again, you can try to resolve the issue by creating a symbolic link as follows:
+
----
ln -s /var/run/saslauthd/ /var/run/sasl2
----

* If the suggested solution doesn't work, install the server and test it again.

+
----
....
      "dial unix /var/run/saslauthd/mux: permission denied"
----
+
To fix this problem, [.cmd]`chmod 755` to the directory to give access.

Errors  caused by  LDAP server::: Look at the external LDAP server logs to find the cause.
