[#topic_gcz_rpm_lq]
= Encryption at Rest

[abstract]
Encryption at rest obfuscates and secures data on the physical machines so that it can be accessed only by authenticated and authorized users.

To secure the host machine where Couchbase Server is installed, the security best practices include encrypting certain data locations using transparent data encryption technologies offered by 3rd party on-disk encryption software vendors,  such as http://www.vormetric.com/products/transparent-encryption[Vormetric].
To see more details, see the webinar provided at http://www.couchbase.com/nosql-resources/webinar/recorded[Understanding Database Encryption with Couchbase and Vormetric].

When your sensitive data in Couchbase is encrypted at-rest on disk, it cannot be compromised if your database is stolen, copied, lost, or improperly accessed.

The following data locations and files should be encrypted:

* Data and index file paths:
 ** Linux: [.path]_/opt/couchbase/var/lib/couchbase/data_
 ** Windows: [.path]_C:\Program Files\couchbase\server\var\lib\couchbase\data_
* Global Secondary Index file paths:
 ** Linux: [.path]_/opt/couchbase/var/lib/couchbase/data/@2i_
 ** Windows: [.path]_C:\Program Files\couchbase\server\var\lib\couchbase\data\@2i_
* Tools path at:
 ** Linux: [.path]_/opt/couchbase/bin/_
 ** Windows: [.path]_C:\Program Files\couchbase\server\bin_
* Couchbase password files at:
 ** Linux: [.path]_/opt/couchbase/var/lib/couchbase/isasl.pw_ and [.path]_/opt/couchbase/var/lib/couchbase/config/_.
 ** Windows: [.path]_C:\Program Files\couchbase\server\var\lib\couchbase\isasl.pw_ and [.path]_C:\Program Files\couchbase\server\var\lib\couchbase\var\lib\couchbase\config\_.
