[#concept_h5v_5jc_bq]
= Network and ACLs

[abstract]
Security outside Couchbase Server involves the configuration of IP tables and ports.

Security best practices include encrypting certain data locations using transparent data encryption technologies.
These technologies are offered by 3rd party on-disk encryption software vendors, such as Vormetric.
To see more details, see the webinar provided at http://www.couchbase.com/nosql-resources/webinar/recorded[Understanding Database Encryption with Couchbase and Vormetric].

* Data and index file path (the default data path on Linux) at [.path]_/opt/couchbase/var/lib/couchbase/data_.
* Tools path at [.path]_/opt/couchbase/bin/_.
* Password files at [.path]_/opt/couchbase/var/lib/couchbase/isasl.pw_ and [.path]_/opt/couchbase/var/lib/config/_.

For additional security:

* Allow administrative access to Couchbase Server only through specific machines, e.g., jump servers.
To audit access, turn on OS level auditing on these machines.
* Use IPSec on your local network.
+
Here are some of the good online sources about IPSec and its configuration:
 ** http://en.wikipedia.org/wiki/Ipsec[About IPSec]
 ** https://www.youtube.com/watch?v=3hve3ZQJIdk[Configuring IPSec on Windows]
 ** http://www.infond.fr/2010/04/basics-9-tutorial-ipsec-transport-mode.html[Configuring IPSec on Linux]

== Access Control

Some of the methods to specify access control information at file/directory level are:

* SELinux - https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security-Enhanced_Linux/[RedHat]
* https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Storage_Administration_Guide/ch-acls.html[Access Control Lists] in Linux

You can also use the traditional file permissions to restrict user access to files or directories.

The other method is to allow administrative access to Couchbase Server only through specific machines by:

* Restricting the access to couchbase administrative ports 8091/8092 on the Couchbase Server.
* Restricting the SSH access to the machine.

Access restriction to the machines must be performed at the network level or the system level using https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sect-Security_Guide-IPTables.html[IPtables rules.]

== Configuring IP Tables and Ports

To configure IP tables for Linux, you can choose among one of these two options:

* Use the [.cmd]`iptables` command.
* Edit the file [.path]_/etc/sysconfig/iptables_:
+
----
##allow everyone to access port 80 and 443##
      -A INPUT -m state --state NEW -p tcp --dport 80 -j ACCEPT
      -A INPUT -m state --state NEW -p tcp --dport 443 -j ACCEPT
----

A sample of the IP tables rules is available in this http://blog.couchbase.com/iptables-firewall-settings-couchbase-db-and-couchbase-mobile-syncgateway[blog].

Keep in mind that certain Couchbase ports are used for node-to-node and some for node-to-client communication.
For a complete list of Couchbase ports, see xref:install:install-ports.adoc#topic2659[Network Configuration].

.Important Couchbase Ports
[cols="100,206,101,193"]
|===
| Port | Description | Node to node | Node to client

| 8091
| Web administration port
| Yes
| Yes

| 8092
| Couchbase API port
| Yes
| Yes

| 8093
| Used by query services for REST/HTTP traffic.
| Yes
| Yes

| 11207
| Internal/external bucket port for SSL
| No
| Yes

| 11209
| Internal bucket port
| Yes
| No

| 11210
| Internal/external bucket port
| Yes
| Yes

| 11211
| Client interface (proxy)
| No
| Yes

| 11214
| Incoming SSL proxy
| No
| No

| 11215
| Internal outgoing SSL proxy
| No
| No

| 18091
| Internal REST HTTPS for SSL
| No
| Yes

| 18092
| Internal CAPI HTTPS for SSL
| No
| Yes

| 4369
| Erlang port mapper (epmd)
| Yes
| No

| 21100 to 21199 (inclusive)
| Node data exchange
| Yes
| No
|===

NOTE: You can find a sample script for configuring the IP tables firewall settings in the following blog posting: http://blog.couchbase.com/iptables-firewall-settings-couchbase-db-and-couchbase-mobile-syncgateway[IPTables Firewall Settings for Couchbase DB and Couchbase Mobile Sync_gateway]

== #Anonymous Section#

In order to keep Couchbase Server secure, you need to perform the following:

[#ol_bg4_n41_hy]
. Setup a firewall to block `epmd` port 4369 from access outside of the cluster network.
. Setup a firewall to block `erlang` ports from access outside of the cluster network.
These ports are configurable and in the default installation, the range is: 21100-21299.
. Restrict read and write access to the following directories:
+
On Linux:
+
----
/opt/couchbase
----
+
On Mac OS X:
+
----
/Users/<user>/Library/Application Support/Couchbase/var/lib/couchbase
----
+
----
/Applications/Couchbase Server.app/Contents/Resources/couchbase-core
----
+
On Windows (assuming the default install location):
+
----
C:\Program Files\Couchbase Server\
----
+
Make sure to secure the root and user passwords under which Couchbase is installed.

. Make sure to secure the Administrator password as well, see xref:secret-mgmt.adoc#topic_s2r_2yt_gy[Secret Management and Hardening] for details.
