= Eventing Language Constructs
:description: The language constructs are fundamental units of a language.
:page-edition: Enterprise Edition

[abstract]
{description}
This topic discusses the JavaScript constructs that have been removed and new constructs that have been added in order to support the requirements of Couchbase Functions.

Using JavaScript, you can write your custom Functions.
Couchbase Functions inherit support for most ECMAScript constructs by using Google v8 as the execution container.
However, to support the ability to shard and scale Function-execution automatically, some capabilities have been removed.
Additionally, to optimize language-utilization of the server environment, some new constructs have been added. Read xref:javascript-udfs:javascript-udf-language-constructs.adoc#added-lang-features[JavaScript: added features] for more details.

NOTE: While every effort is made to ensure the accuracy of the content of the Eventing documentation herein, it should be noted that the controlling technical document is the https://github.com/couchbase/eventing/blob/master/docs/specification-70.pdf[Couchbase 7.0 Eventing Specification] available on GitHub.

[#added-lang-features]
== Added Language Features

The following constructs have been added:

* <<bucket_accessors,Basic Keyspace Accessors>>
* <<advanced_bucket_accessors,Advanced Keyspace Accessors>>

[#bucket_accessors]
=== Basic Keyspace Accessors

Couchbase buckets, when bound to a Function, appear as a global JavaScript map.
The map operations such as get, set and delete are exposed to the Data Service providers get, set, and delete operations respectively.

[source,javascript]
----
function OnUpdate(doc, meta) {
  // Assuming 'dest' is a bucket alias or binding to a keyspace
  var val = dest[meta.id];         // this is a bucket GET operation.
  dest[meta.id] = {"status":3};    // this is a bucket SET operation.
  delete dest[meta.id];            // this is a bucket DEL operation.
}
----

* *The GET operation* _(operator [] applied on a bucket binding and used as a value expression)_
+
This fetches the corresponding object from the KV bucket the variable is bound to, and returns the parsed JSON value as a JavaScript object. Fetching a non-existent object from a bucket will return JavaScript undefined value. This operation throws an exception if the underlying bucket GET operation fails with an unexpected error.

* *The SET operation* _(operator [] appearing on left of = assignment statement)_
+
This sets the provided JavaScript value into the KV bucket the variable is bound to, replacing any existing value with the specified key. This operation throws an exception if the underlying bucket SET operation fails with an unexpected error.

* *The DELETE operation* _(operator [] appearing after JavaScript delete keyword)_
+
This deletes the provided key from the KV bucket the variable is bound to. If the object does not exist, this call is treated as a no-op. This operation throws an exception if the underlying bucket DELETE operation fails with an unexpected error.


[#advanced_bucket_accessors]
=== Advanced Keyspace Accessors

The following advanced bucket accessors have been added to expose a richer set of options and operators.  
Unlike the basic bucket accessors these operations have non-trivial argument sets and return values for complete details refer to xref:eventing:eventing-advanced-keyspace-accessors.adoc[Advanced Keyspace Accessors Details].

[#advanced-get-op]
* *The Advanced GET operation*: _result = couchbase.get(binding, meta)_
+
This operation allows reading a document from the bucket with an ability to specify the CAS value to be matched during the read.
For more information see xref:eventing:eventing-advanced-keyspace-accessors.adoc#advanced-get-op[advanced GET operation].

[#advanced-insert-op]

* *The Advanced INSERT operation*: _result = couchbase.insert(binding, meta, doc)_
+
This operation allows creating a fresh document in the bucket.
This operation will fail if the document with the specified key already exists. 
It allows specifying an expiration time (or TTL) to be set on the document.
For more information see xref:eventing:eventing-advanced-keyspace-accessors.adoc#advanced-insert-op[advanced INSERT operation].

[#advanced-upsert-op]

* *The Advanced UPSERT operation*: _result = couchbase.upsert(binding, meta, doc)_
+
This operation allows updating an existing document in the bucket, or if absent, creating a fresh document with the specified key.
The operation does not allow specifying CAS (it will silently ignore it).
It also allows specifying an expiration time (or TTL) to be set on the document.
For more information see xref:eventing:eventing-advanced-keyspace-accessors.adoc#advanced-upsert-op[advanced UPSERT operation].

[#advanced-replace-op]

* *The Advanced REPLACE operation*: _result = couchbase.replace(binding, meta, doc)_
+
This operation replaces an existing document in the bucket
This operation will fail if the document with the specified key does not exist. 
This operation allows specifying a CAS value that must be matched as a pre-condition before proceeding with the operation. 
It also allows specifying an expiration time (or TTL) to be set on the document. 
For more information see xref:eventing:eventing-advanced-keyspace-accessors.adoc#advanced-replace-op[advanced REPLACE operation].

[#advanced-delete-op]

* *The Advanced DELETE operation*: _result = couchbase.delete(binding, meta)_
+
This operation allows deleting a document in the bucket specified by key.
Optionally, a CAS value may be specified which will be matched as a pre-condition to proceed with the operation.
For more information see xref:eventiong:eventing-advanced-keyspace-accessors.adoc#advanced-delete-op[advanced DELETE operation].

[#advanced-increment-op]

* *The Advanced INCREMENT operation*: _result = couchbase.incrment(binding, meta)_
+
This operation atomically increments the field _"count"_ in the specified document.
For more information see xref:eventing:eventing-advanced-keyspace-accessors.adoc#advanced-increment-op[advanced INCREMENT operation].
+
The document must have the below structure:
+
[source,json5]
----
{"count": 23} // 23 is the current counter value
----
+
The _increment_ operation returns the post-increment value. 
+
If the specified counter document does not exist, one is created with _count_ value as 0 and the structure noted above. And so, the first returned value will be 1.
+
Due to limitations in KV engine API, this operation cannot currently manipulate full document counters.

[#advanced-decrement-op]

* *The Advanced DECREMENT operation*: _result = couchbase.decrement(binding, meta)_
+
This operation atomically decrements the field _"count"_ in the specified document.
For more information see xref:eventing:eventing-advanced-keyspace-accessors.adoc#advanced-decrement-op[advanced DECREMENT operation].
+
The document must have the below structure:
+
[source,json5]
----
{"count": 23} // 23 is the current counter value
----
+
The _decrement_ operation returns the post-decrement value. 
+
If the specified counter document does not exist, one is created with _count_ value as 0 and the structure noted above. And so, the first returned value will be -1.
+
Due to limitations in KV engine API, this operation cannot currently manipulate full document counters.



[source,javascript]
----
function OnUpdate(doc, meta) {
  log("Now processing: " + meta.id);
}
----

The Eventing Service also creates a system log file named *eventing.log* common across all Eventing Functions to capture management and lifecycle information, however the end-user cannot write to this file. 
For more information see xref:eventing:eventing-debugging-and-diagnosability.adoc#system-log[system log].

[#handler-signatures]
== Handler Signatures

The Eventing Service calls the following entry points or JavaScript functions on events (mutations or fired timers).

* <<onupdate_handler,OnUpdate Handler>>
* <<ondelete_handler,OnDelete Handler>>
* <<timer_callback_handler,Timer Callback Handler>>

[#onupdate_handler]
=== OnUpdate Handler

The *OnUpdate* handler gets called when a document is created or modified, e.g. Insert/Update. The entry point OnUpdate(doc,meta) listens to mutations (the creation or modification of documents) in the associated source Bucket.

In this handler the following limitations exist, both limitations arise due to KV engine design choices and may be revisited in the future:

* If a document is modified several times in a short duration, the calls may be coalesced into a single event due to deduplication.
* It is not possible to distinguish between a Create and an Update operation.

A sample *OnUpdate* handler is displayed below:

[source,javascript]
----
function OnUpdate(doc, meta) {
  if (doc.type === 'order' && doc.value > 5000) {
    // ‘phonverify’ is a bucket alias or binding to a keyspace.
    phoneverify[meta.id] = doc.customer;
  }
}
----


[#ondelete_handler]
=== OnDelete Handler

The *OnDelete* handler gets called when a document is deleted or removed due to an expiry.

The entry point OnDelete(meta,options) listens to mutations (deletions or expirations) in the associated source Bucket.  You can determine if the document was deleted or expired via inspecting the optional argument "options" (a JavaScript map object with a boolean property named 'expired').

In this handler the following limitation exists. This limitation arises due to KV engine design choices and may be revisited in the future:

* it is not possible to get the value of the document that was just deleted or expired.

A sample *OnDelete* handler is displayed below:

[source,javascript]
----
function OnDelete(meta,options) {
    if (options.expired) {
        log("Document expired", meta.id);
    } else {
        log("Document deleted", meta.id);
    }
    var addr = meta.id;
    var res = SELECT id from mybucket.myscope.orders WHERE shipaddr = $addr;
    for (var id of res) {
        log("Address invalidated for pending order: " + id);
    }
}
----

Note that the pre-6.6.0 argument syntax, OnDelete(meta), that lacks "options" is still fully supported, but you will not be able to differentiate deletion from expiration.

[source,javascript]
----
function OnDelete(meta) {
    log("Document deleted or expired", meta.id);
}
----

[#timer_callback_handler]
=== Timer Callback Handler

Timer callbacks are user defined JavaScript functions passed as the callback argument to the built-in createTimer(callback, date, reference, context) function call.

These handlers (JavaScript functions) are the entry points for the event when a timer (created by the specific Eventing Function) matures and fires.

A sample Timer Callback Handler, the user defined JavaScript function *DocTimerCallback*, is displayed below:

[source,javascript]
----
// Timer Callback Handler (user defined entry point)
function DocTimerCallback(context) {
	log("Timer fired running callback 'DocTimerCallback' with context: " + context);
}

// Insert/Update Handler or entry point
function OnUpdate(doc, meta) {
	// filter out docs of no interest.
	if (meta.id != 'make_timer:1') return;
	// Create a Date value 60 seconds from now
	var oneMinuteFromNow = new Date(); // Get current time & add 60 sec. to it.
	oneMinuteFromNow.setSeconds(oneMinuteFromNow.getSeconds() + 60);
	// Create a doc to hold context to pass state to the callback function.
	var context = { docId: meta.id, random_text: "arbitrary text" };
	// Create a timer that will fire an event in the future.
	log("createTimer with callback 'DocTimerCallback'");
	createTimer(DocTimerCallback, oneMinuteFromNow, meta.id, context);
}
----

For more information see the <<timers_general,Timers>> section above and the detailed xref:eventing-timers.adoc[Timers] documentation.
