= Eventing Language Constructs
:description: The language constructs are fundamental units of a language.
:page-edition: Enterprise Edition

[abstract]
{description}
This topic discusses the JavaScript constructs that have been removed and new constructs that have been added in order to support the requirements of Couchbase Functions.

Using JavaScript, you can write your custom Functions.
Couchbase Functions inherit support for most ECMAScript constructs by using Google v8 as the execution container.
However, to support the ability to shard and scale Function-execution automatically, some capabilities have been removed.
Additionally, to optimize language-utilization of the server environment, some new constructs have been added. Read xref:javascript-udfs:javascript-udf-language-constructs.adoc#added-lang-features[JavaScript: added features] for more details.

NOTE: While every effort is made to ensure the accuracy of the content of the Eventing documentation herein, it should be noted that the controlling technical document is the https://github.com/couchbase/eventing/blob/master/docs/specification-70.pdf[Couchbase 7.0 Eventing Specification] available on GitHub.

[#handler-signatures]
== Handler Signatures

The Eventing Service calls the following entry points or JavaScript functions on events (mutations or fired timers).

* <<onupdate_handler,OnUpdate Handler>>
* <<ondelete_handler,OnDelete Handler>>
* <<timer_callback_handler,Timer Callback Handler>>

[#onupdate_handler]
=== OnUpdate Handler

The *OnUpdate* handler gets called when a document is created or modified, e.g. Insert/Update. The entry point OnUpdate(doc,meta) listens to mutations (the creation or modification of documents) in the associated source Bucket.

In this handler the following limitations exist, both limitations arise due to KV engine design choices and may be revisited in the future:

* If a document is modified several times in a short duration, the calls may be coalesced into a single event due to deduplication.
* It is not possible to distinguish between a Create and an Update operation.

A sample *OnUpdate* handler is displayed below:

[source,javascript]
----
function OnUpdate(doc, meta) {
  if (doc.type === 'order' && doc.value > 5000) {
    // ‘phonverify’ is a bucket alias or binding to a keyspace.
    phoneverify[meta.id] = doc.customer;
  }
}
----


[#ondelete_handler]
=== OnDelete Handler

The *OnDelete* handler gets called when a document is deleted or removed due to an expiry.

The entry point OnDelete(meta,options) listens to mutations (deletions or expirations) in the associated source Bucket.  You can determine if the document was deleted or expired via inspecting the optional argument "options" (a JavaScript map object with a boolean property named 'expired').

In this handler the following limitation exists. This limitation arises due to KV engine design choices and may be revisited in the future:

* it is not possible to get the value of the document that was just deleted or expired.

A sample *OnDelete* handler is displayed below:

[source,javascript]
----
function OnDelete(meta,options) {
    if (options.expired) {
        log("Document expired", meta.id);
    } else {
        log("Document deleted", meta.id);
    }
    var addr = meta.id;
    var res = SELECT id from mybucket.myscope.orders WHERE shipaddr = $addr;
    for (var id of res) {
        log("Address invalidated for pending order: " + id);
    }
}
----

Note that the pre-6.6.0 argument syntax, OnDelete(meta), that lacks "options" is still fully supported, but you will not be able to differentiate deletion from expiration.

[source,javascript]
----
function OnDelete(meta) {
    log("Document deleted or expired", meta.id);
}
----

[#timer_callback_handler]
=== Timer Callback Handler

Timer callbacks are user defined JavaScript functions passed as the callback argument to the built-in createTimer(callback, date, reference, context) function call.

These handlers (JavaScript functions) are the entry points for the event when a timer (created by the specific Eventing Function) matures and fires.

A sample Timer Callback Handler, the user defined JavaScript function *DocTimerCallback*, is displayed below:

[source,javascript]
----
// Timer Callback Handler (user defined entry point)
function DocTimerCallback(context) {
	log("Timer fired running callback 'DocTimerCallback' with context: " + context);
}

// Insert/Update Handler or entry point
function OnUpdate(doc, meta) {
	// filter out docs of no interest.
	if (meta.id != 'make_timer:1') return;
	// Create a Date value 60 seconds from now
	var oneMinuteFromNow = new Date(); // Get current time & add 60 sec. to it.
	oneMinuteFromNow.setSeconds(oneMinuteFromNow.getSeconds() + 60);
	// Create a doc to hold context to pass state to the callback function.
	var context = { docId: meta.id, random_text: "arbitrary text" };
	// Create a timer that will fire an event in the future.
	log("createTimer with callback 'DocTimerCallback'");
	createTimer(DocTimerCallback, oneMinuteFromNow, meta.id, context);
}
----

For more information see the <<timers_general,Timers>> section above and the detailed xref:eventing-timers.adoc[Timers] documentation.
