= Eventing REST API
:page-edition: Enterprise Edition

[abstract]
The Eventing REST API, available by default at port 8096, provides the methods available to work with Couchbase Eventing Functions.

NOTE: The Eventing Functions REST API endpoints on this page are supported, as long as the content of the handler body is not created or modified externally (as the internal format of the body is not yet standardized).


.Eventing Functions API (basic activation/deactivation)
[cols="2,3,6"]
|===
| HTTP Method | *URI Path* | *Description*

| POST
| [.path]_/api/v1/functions/[sample_name]/deploy_
a|
Deploys an undeployed Function. Starting version 6.5.0, this is the preferred invocation.
A deploy CURL example is provided for reference.

Sample API:

[source,console]
----
curl -XPOST http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/deploy
----

| POST
| [.path]_/api/v1/functions/[sample_name]/undeploy_
a|
Undeploys a Function. Starting version 6.5.0, this is the preferred invocation.
An undeploy CURL example is provided for reference.

Sample API:

[source,console]
----
curl -XPOST http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/undeploy
----

| POST
| [.path]_/api/v1/functions/[sample_name]/pause_
a|
Pauses a Function and creates a DCP checkpoint such that on a subsequent resume no mutations will be lost. Starting version 6.5.0, this is the preferred invocation.
A pause CURL example is provided for reference.

Sample API:

[source,console]
----
curl -XPOST http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/pause
----

| POST
| [.path]_/api/v1/functions/[sample_name]/resume_
a|
Resumes a paused function from its paused DCP checkpoint. Starting version 6.5.0, this is the preferred invocation.
A resume CURL example is provided for reference.

Sample API:

[source,console]
----
curl -XPOST http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/resume
----

|===


.Eventing Functions API (advanced)
[cols="2,3,6"]
|===
| HTTP Method | *URI Path* | *Description*

| POST
| [.path]_/api/v1/functions/[function_name]_
| Import or create a single Function.
The Function name in the body must match that on the URL.
Function definition includes current settings.

| POST
| [.path]_/api/v1/functions/_
| Imports or creates multiple Functions.
Function names must be unique.
When multiple Functions have the same name, an error is reported.

| POST
| [.path]_/api/v1/import/_
| Imports multiple Functions.
Function names must be unique.
When multiple Functions have the same name, an error is reported. Note if any Function's language_compatibility field is missing the value will be set to 6.0.0 (unlike the [.path]_/api/v1/functions_ above which will set the value to the highest version supported by the server).

| GET
| [.path]_/api/v1/functions_
| View a list of Functions.
Provides a list of Functions available in the cluster.
The list includes both the deployed and the undeployed Functions.

| DELETE
| [.path]_/api/v1/functions/[function_name]_
| Deletes a specific Functions from the cluster.

| DELETE
| [.path]_/api/v1/functions_
| Deletes multiple Functions from the cluster.

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
| Edit Function settings.
During an edit, settings provided are merged.
Unspecified attributes retain their prior values.

| POST
| [.path]_/api/v1/config_
| Modify global configuration.
During an edit, settings provided are merged.
Unspecified attributes retain their prior values.
The response indicates whether the Eventing service must be restarted for the new changes to take effect.

| GET
| [.path]_/api/v1/functions/[function_name]/settings_
a|
Export or return the full definition for one Eventing Function in the cluster.  The definition can be subseqently imported.  However any changes to the function definition made outside the UI are not supported.

Sample API (to standard out):

[source,console]
----
curl http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

Sample API (to file):

[source,console]
----
curl http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings -o [sample_name.json]
----

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a| 
Updates an undeployed Function with the provided setting. Do not update settings for a deployed or paused function.
Note that you must always specify deployment_status (deployed/undeployed) and processing_status (paused/not-paused) when using this REST endpoint to update any option(s).

Sample API (alter worker_count):

[source,console]
----
curl -XPOST -d '{"deployment_status":false,"processing_status":false,"worker_count":6}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a| 
Updates an undeployed Function with the provided settings. Do not update settings for a deployed or paused function.
Note that you must always specify deployment_status (deployed/undeployed) and processing_status (paused/not-paused) when using this REST endpoint to update any option(s).

Sample API (alter app_log_max_files and app_log_max_size):

[source,console]
----
curl -XPOST -d '{"deployment_status":false,"processing_status":false,"app_log_max_files":5,"app_log_max_size":10485760}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

Sample API (alter timer_context_size):

[source,console]
----
curl -XPOST -d '{"deployment_status":false,"processing_status":false,"timer_context_size":2048}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

| GET
| [.path]_/api/v1/status_
a|
Returns a list (arrary) of all Eventing Functions showing their corresponding *composite_status*. It can have one of the following values - _undeployed_, _deploying_, _deployed_, _undeploying_, _paused_, and '_pausing_.  Note, there is no value of _resuming_ when resuming a paused Eventing Function the *composite_status* will return _deploying_ until it reaches the _deployed_ state.

Sample API (status):

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/api/v1/status
----

|===


.Eventing Functions API (deprecated activation/deactivation)
[cols="2,3,6"]
|===
| HTTP Method | *URI Path* | *Description*

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a|
Deploys an undeployed Function or resumes a paused function from its paused DCP checkpoint.  Deprecated, see (basic activation/deactivation) for preferred invocation.
A deploy/resume CURL example is provided for reference.

Sample API:

[source,console]
----
curl -XPOST -d '{"deployment_status":true,"processing_status":true}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a|
Undeploys a Function. Deprecated, see (basic activation/deactivation) for preferred invocation.
An undeploy CURL example is provided for reference.

Sample API:

[source,console]
----
curl -XPOST -d '{"deployment_status":false,"processing_status":false}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a|
Pauses a Function and creates a DCP checkpoint such that on a subsequent resume no mutations will be lost. Deprecated, see (basic activation/deactivation) for preferred invocation.
A pause CURL example is provided for reference.

Sample API:

[source,console]
----
curl -XPOST -d '{"deployment_status":true,"processing_status":false}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

|===


.Eventing Statistics API
[cols="2,3,4"]
|===
| HTTP Method | *URI Path* | *Description*

| GET
| [.path]_/api/v1/stats?type=full_
| Retrieve all statistics for the node.
This will return the full statistics set inclusive of events processing, events remaining, execution, failure, latency, worker PIDs and sequence processed.

Note, omitting the parameter type=full will exclude dcp_event_backlog_per_vb, doc_timer_debug_stats, latency_stats, plasma_stats and seqs_processed from the response.

| GET
| [.path]_/getExecutionStats?name=[function_name]_
| Retrieve only execution statistics.
This will return the the subset of statistics for the node.

| GET
| [.path]_/getLatencyStats?name=[function_name]_
| Retrieve only latency statistics.
This will return the the subset of statistics for the node.

| GET
| [.path]_/getFailureStats?name=[function_name]_
| Retrieve only failure statistics.
This will return the the subset of statistics for the node.
|===
