= Eventing REST API
:page-edition: Enterprise Edition

[abstract]
 The Eventing REST API, available by default at port 8096, provides the methods available to work with Couchbase Eventing Functions.

NOTE: The Eventing Functions REST API endpoints on this page are supported, as long as the content of the handler body is not created or modified externally (as the internal format of the body is not yet standardized).


.Eventing Functions API (basic activation/deactivation)
[cols="2,10,18"]
|===
| HTTP Method | *URI Path* | *Description*

| POST
| [.path]_/api/v1/functions/[sample_name]/deploy_
a|
Deploys an undeployed Function. Starting with version 6.5.0, this is the preferred invocation.
A deploy CURL example is provided for reference.

|
2+a|
Sample API:
[source,console]
----
curl -XPOST http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/deploy
----

| POST
| [.path]_/api/v1/functions/[sample_name]/undeploy_
a|
Undeploys a Function. Starting with version 6.5.0, this is the preferred invocation.
An undeploy CURL example is provided for reference.

|
2+a|
Sample API:

[source,console]
----
curl -XPOST http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/undeploy
----

| POST
| [.path]_/api/v1/functions/[sample_name]/pause_
a|
Pauses a Function and creates a DCP checkpoint such that on a subsequent resume no mutations will be lost. Starting with version 6.5.0, this is the preferred invocation.
A pause CURL example is provided for reference.

|
2+a|
Sample API:

[source,console]
----
curl -XPOST http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/pause
----

| POST
| [.path]_/api/v1/functions/[sample_name]/resume_
a|
Resumes a paused function from its paused DCP checkpoint. Starting with version 6.5.0, this is the preferred invocation.
A resume CURL example is provided for reference.

|
2+a|
Sample API:

[source,console]
----
curl -XPOST http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/resume
----

|===


.Eventing Functions API (advanced)
[cols="2,10,18"]
|===
| HTTP Method | *URI Path* | *Description*

| POST
| [.path]_/api/v1/functions/[function_name]_
a| Import or create a single Function.
The Function name in the body must match that on the URL.
Function definition includes current settings.
The POST data or POST data file must be a single JSON object or an array containing a single JSON object

|
2+a|
Sample API (from file):

[source,console]
----
curl -XPOST  -d @./[sample_name].json http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]
----

| POST
| [.path]_/api/v1/functions/_
a| Imports or creates multiple Functions.
Function names must be unique.
When multiple Functions have the same name, an error is reported.
The POST data or POST data file must be either a single JSON object or an array containing a one or more JSON objects

|
2+a|
Sample API (from file):

[source,console]
----
curl -XPOST  -d @./[array_of_functions].json http://Administrator:password@192.168.1.5:8096/api/v1/functions
----

| POST
| [.path]_/api/v1/import/_
a| Imports multiple Functions.
Function names must be unique.
When multiple Functions have the same name, an error is reported. 
The POST data or POST data file must be either a single JSON object or an array containing a one or more JSON objects
Note if any Function's language_compatibility field is missing the value will be set to 6.0.0 (unlike the [.path]_/api/v1/functions_ above which will set the value to the highest version supported by the server).

|
2+a|
Sample API (from file):

[source,console]
----
curl -XPOST  -d @./[array_of_functions].json http://Administrator:password@192.168.1.5:8096/api/v1/import
----

| GET
| [.path]_/api/v1/functions/[sample_name]_
a| View a definition of a Function.
Provides a listing of a complete Function definition available in the cluster.
The Function could be in any state: deployed, undeployed, or paused.
If saved to a file the function definition can be imputed into the cluster or a different cluster. 
However any changes to the function definition made to the file outside the UI are discouraged and not supported.

|
2+a|
Sample API (to standard out):

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]
----

|
2+a|
Sample API (to file):

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name] -o [sample_name].json
----

| GET
| [.path]_/api/v1/functions_
a| View definitions of all Functions.
Provides an array of definitions of all Functions available in the cluster.
The Functions could be in any state: deployed, undeployed, or paused.
If saved to a file the function definitions can be imputed into the cluster or a different cluster. 
However any changes to the function definition made to the file outside the UI are discouraged and not supported.

|
2+a|
Sample API (to standard out):

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/api/v1/functions 
----

|
2+a|
Sample API (to file):

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/api/v1/functions -o array_of_functions.json
----

| DELETE
| [.path]_/api/v1/functions/[function_name]_
a| Deletes a specific Function from the cluster.
WARNING: Use this API with caution as it is irreversible.

|
2+a|
Sample API:

[source,console]
----
curl -XDELETE http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]
----

| DELETE
| [.path]_/api/v1/functions_
a| Deletes multiple Functions from the cluster.
WARNING: Use this API with caution as it is irreversible.

|
2+a|
Sample API:

[source,console]
----
curl -XDELETE http://Administrator:password@192.168.1.5:8096/api/v1/functions
----

| GET
| [.path]_/api/v1/config_
a| List global configuration.
The response shows all global Eventing settings.

|
2+a|
Sample API:

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/api/v1/config
----

| POST
| [.path]_/api/v1/config_
a| Modify global configuration.
During an edit, settings provided are merged. Unspecified attributes retain their prior values.
The response indicates whether the Eventing service must be restarted for the new changes to take effect.

|
2+a|
Sample API (alter ram_quota):

[source,console]
----
curl -XPOST -d '{"ram_quota": 512}' http://Administrator:password@192.168.1.5:8096/api/v1/config
----

| GET
| [.path]_/api/v1/functions/[function_name]/settings_
a|
Export or return the full definition for one Eventing Function in the cluster.  The definition can be subsequently imported.  
However any changes to the function definition made to the file outside the UI are discouraged and not supported.

|
2+a|
Sample API (to standard out):

[source,console]
----
curl http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

|
2+a|
Sample API (to file):

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings -o [sample_name].json
----

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a| 
Updates an undeployed Function with the provided setting. Do not update settings for a deployed or paused function.
During an edit, settings provided are merged. Unspecified attributes retain their prior values.
Note that you must always specify deployment_status (deployed/undeployed) and processing_status (paused/not-paused) 
when using this REST endpoint to update any option or set of options.

|
2+a|
Sample API (alter worker_count):

[source,console]
----
curl -XPOST -d '{"deployment_status":false,"processing_status":false,"worker_count":6}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

|
2+a|
Sample API (alter app_log_max_files and app_log_max_size):

[source,console]
----
curl -XPOST -d '{"deployment_status":false,"processing_status":false,"app_log_max_files":5,"app_log_max_size":10485760}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

|
2+a|
Sample API (alter timer_context_size):

[source,console]
----
curl -XPOST -d '{"deployment_status":false,"processing_status":false,"timer_context_size":2048}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

| GET
| [.path]_/api/v1/status_
a|
Returns a list (arrary) of all Eventing Functions showing their corresponding *composite_status*. 
It can have one of the following values - _undeployed_, _deploying_, _deployed_, _undeploying_, _paused_, and '_pausing_.  
Note, there is no value of _resuming_ when resuming a paused Eventing Function the *composite_status* will return _deploying_ until it reaches the _deployed_ state.

|
2+a|
Sample API (status):

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/api/v1/status
----

|===

.Eventing Functions API (deprecated activation/deactivation)
[cols="2,10,18"]
|===
| HTTP Method | *URI Path* | *Description*

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a|
Deploys an undeployed Function or resumes a paused function from its paused DCP checkpoint.  Deprecated, see (basic activation/deactivation) for preferred invocation.
A deploy/resume CURL example is provided for reference.

|
2+a|
Sample API:

[source,console]
----
curl -XPOST -d '{"deployment_status":true,"processing_status":true}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a|
Undeploys a Function. Deprecated, see (basic activation/deactivation) for preferred invocation.
An undeploy CURL example is provided for reference.

|
2+a|
Sample API:

[source,console]
----
curl -XPOST -d '{"deployment_status":false,"processing_status":false}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a|
Pauses a Function and creates a DCP checkpoint such that on a subsequent resume no mutations will be lost. 
Deprecated, see (basic activation/deactivation) for preferred invocation.
A pause CURL example is provided for reference.

|
2+a|
Sample API:

[source,console]
----
curl -XPOST -d '{"deployment_status":true,"processing_status":false}' http://Administrator:password@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

|===


.Eventing Statistics API
[cols="2,10,18"]
|===
| HTTP Method | *URI Path* | *Description*

| GET
| [.path]_/api/v1/stats?type=full_
a| Retrieve all statistics for the node.
This will return the full statistics set inclusive of events processing, events remaining, execution, failure, latency, worker PIDs and sequence processed.

|
2+a|
NOTE: Omitting the parameter `type=full` will exclude `dcp_event_backlog_per_vb`, `doc_timer_debug_stats`, `latency_stats`, `plasma_stats`, and `seqs_processed` from the response.

|
2+a|
Sample API (basic):

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/api/v1/stats
----

|
2+a|
Sample API (full):

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/api/v1/stats?type=full
----

| GET
| [.path]_/getExecutionStats?name=[function_name]_
a| Retrieve only execution statistics.
This will return the subset of statistics for the node.

|
2+a|
Sample API:

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/getExecutionStats?name=[function_name]
----

| GET
| [.path]_/getLatencyStats?name=[function_name]_
a| Retrieve only latency statistics.
This will return the subset of statistics for the node.

|
2+a|
Sample API:

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/getLatencyStats?name=[function_name]
----

| GET
| [.path]_/getFailureStats?name=[function_name]_
a| Retrieve only failure statistics.
This will return the subset of statistics for the node.

|
2+a|
Sample API:

[source,console]
----
curl -XGET http://Administrator:password@192.168.1.5:8096/getFailureStats?name=[function_name]
----

|===
