[#eventing_api]
= Functions API

[abstract]
The tabular column lists the methods available for Functions.

[#section_kzm_vyy_m2b]
--
.{empty}
[#table_z5x_vyy_m2b,cols="243,100,559"]
|===
| *API* | *Method* | *Description*

| 
| 
| 

| POST /api/v1/functions/<name>
| POST
| Create a single Function.
The Function name in the body must match that on the URL.
Function definition includes current settings.

| POST /api/v1/functions/
| POST
| Creates multiple Functions.
Function names must be unique.
When multiple Functions have the same name, an error is reported.

| GET /api/v1/functions
| GET
| View a list of Functions.
Provides a list of Functions available in the cluster.
The list includes both the deployed and the undeployed Functions.

| DELETE /api/v1/functions/<name>
| DELETE
| Deletes a specific Functions from the cluster.

| DELETE /api/v1/functions
| DELETE
| Deletes multiple Functions from the cluster.

| POST /api/v1/functions/<name>/settings
| POST
| Edit Function settings.
During an edit, settings provided are merged.
Unspecified attributes retain their prior values.

| POST /api/v1/config
| POST
| Modify global configuration.
During an edit, settings provided are merged.
Unspecified attributes retain their prior values.
The response indicates whether the Eventing service must be restarted for the new changes to take effect.

| POST /api/v1/functions/<app_name>/settings
| POST
| Deploys a Function.
A deploy CURL example is provided for reference.

Sample API: curl -XPOST -d '{"deployment_status":true,"processing_status":true}'

\http://Administrator@192.168.1.5:8091/api/v1/functions/<sample_name>/settings

| POST /api/v1/functions/<app_name>/settings
| POST
| Undeploys a Function.
An undeploy CURL example is provided for reference.

Sample API:

curl -XPOST -d '{"deployment_status":false,"processing_status":false}'

\http://Administrator@192.168.1.5:8091/api/v1/functions/<sample_name>/settings

| POST /api/v1/functions/<app_name>/settings
| POST
| Deploys a Function with the provided code.
A sample deploy CURL example is provided for reference.
|===
--
