= Eventing REST API

[abstract]
The Eventing REST API, available by default at port 8096, provides the methods available to work with Couchbase Eventing Functions.

NOTE: The Eventing REST API is a Beta feature intended for development purposes only, do not use them in production; no Enterprise Support is provided for Beta features.

.Eventing API
[cols="2,3,6"]
|===
| HTTP Method | *URI Path* | *Description*

| POST
| [.path]_/api/v1/functions/[function_name]_
| Create a single Function.
The Function name in the body must match that on the URL.
Function definition includes current settings.

| POST
| [.path]_/api/v1/functions/_
| Creates multiple Functions.
Function names must be unique.
When multiple Functions have the same name, an error is reported.

| POST
| [.path]_/api/v1/import/_
| Imports multiple Functions.
Function names must be unique.
When multiple Functions have the same name, an error is reported. Note if any Function's langauge_compatibility field is missing the value will be set to 6.0.0 (unlike the [.path]_/api/v1/functions_ above which will set the value to the highest version supported by the server).

| GET
| [.path]_/api/v1/functions_
| View a list of Functions.
Provides a list of Functions available in the cluster.
The list includes both the deployed and the undeployed Functions.

| DELETE
| [.path]_/api/v1/functions/[function_name]_
| Deletes a specific Functions from the cluster.

| DELETE
| [.path]_/api/v1/functions_
| Deletes multiple Functions from the cluster.

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
| Edit Function settings.
During an edit, settings provided are merged.
Unspecified attributes retain their prior values.

| POST
| [.path]_/api/v1/config_
| Modify global configuration.
During an edit, settings provided are merged.
Unspecified attributes retain their prior values.
The response indicates whether the Eventing service must be restarted for the new changes to take effect.

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a|
Deploys a Function.
A deploy CURL example is provided for reference.

Sample API:

----
curl -XPOST -d '{"deployment_status":true,"processing_status":true}'
http://Administrator@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a|
Undeploys a Function.
An undeploy CURL example is provided for reference.

Sample API:

----
curl -XPOST -d '{"deployment_status":false,"processing_status":false}'
http://Administrator@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----

| POST
| [.path]_/api/v1/functions/[function_name]/settings_
a| 
Updates an undeployed a Function with the provided settings. Do not update settings for a deployed or paused function.

Sample API (alter worker_count):

----
curl -XPOST -d '{"deployment_status":false,"processing_status":false,"worker_count":6}'
http://Administrator@192.168.1.5:8096/api/v1/functions/[sample_name]/settings
----
|===
