[#couchbase-editions]
= Couchbase Server Editions

[abstract]
Couchbase Server is available in several editions: enterprise, community, and open source.

Each edition offers different features and levels of support.
// For more information on each feature, see the <xref href="#couchbase-editions/ee-vs-ce" format="dita">Enterprise and community edition feature matrix</xref>.

Enterprise Edition::
The Enterprise edition (EE) represents the latest, most stable, production-ready release of Couchbase Server.
We recommend the enterprise edition binaries for commercial production systems running Couchbase Server.
The enterprise edition contains some unique features that make it the best fit for production deployments running in data centers or a public cloud infrastructure.
// These
// features, which are not available in the community edition, are listed in the
// <xref href="#couchbase-editions/ee-vs-ce" format="dita"/>.
Use of EE in development and test environments is free.
EE requires a paid subscription for production use.
Our http://www.couchbase.com/subscriptions-and-support[paid annual subscriptions] for EE include a commercial license, better availability capabilities, enhanced security features, advanced tooling and higher performance and scale.
It also includes technical support with service level commitments via our 24x7 support organization and hot fixes for releases.
One important principle for CE and EE is to ensure full portability of applications between two editions.
The capabilities ensure that an application running on EE should simply transition to CE without code changes and visa versa.

Community Edition::
The Community Edition (CE) is best for noncommercial developers where basic availability, performance, scale, tooling, security capabilities and community support is sufficient.
CE comes free and there are no constraints on using these binaries in production systems.
However, CE is not subjected to the iterative "test, fix, and verify" quality assurance cycle that is a part of the enterprise edition release process.
The release version of CE is several months behind EE.
CE also do not include the latest bug fixes.
Documentation, mailing lists, and forums provide support for the Couchbase user community to help troubleshoot issues and answer questions.

Open source project::
The Couchbase Server open source project is a platform for innovation.
Couchbase is committed to open source development and the open source project continues to serve as the foundation for both the community edition and the enterprise edition.
There are many ways to contribute to the open source project: You can contribute code to our core engine, to our SDKs, connectors and other integration components that help us connect to other products through https://github.com/couchbase[github.com/couchbase], you can report issues on our tracking system: https://issues.couchbase.com/projects/MB?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page[JIRA] and contribute to documentation either through http://github.com/couchbase/docs-cb4[github.com/couchbase/docs-cb4] or by simply clicking the "Feedback" link in our online documentation.
The full details on contributing to open source can be found on the open source page http://developer.couchbase.com/open-source-projects[developer.couchbase.com/open-source-projects].

For a feature comparison between the editions, take a look at https://www.couchbase.com/products/editions.
