= What's New?

Couchbase Server 6.0 brings significant updates to the Analytics, Eventing and Full-text Search services.

Take a look at the xref:release-notes:relnotes.adoc[release notes] for a list of known issues in this release.

[#new-features]
== New features

*Couchbase Analytics*

Couchbase Server 6.0 delivers the first production release of Couchbase Analytics.
Our Analytics service enables you to analyze your JSON data in real time without the need to extract, transform, load (ETL) your data into a separate system.
It allows you to develop insight-driven applications quickly and easily using the same SDKs.

It supports hybrid operational and analytical processing (HOAP) workloads and allows NoSQL users to run ad hoc analytical queries leveraging a massively parallel processing (n MPP) query engine without impacting application performance.

Couchbase’s unique architecture for Multi-Dimensional Scaling (MDS) allows operational and analytical queries to run concurrently without impacting one another, providing the workload isolation required for production deployments.

To learn more about this service, or to see what's new in this production release, see xref:analytics:introduction.adoc[Couchbase Analytics].

*N1QL for Analytics*

SQL++ builds on the popularity and power of the SQL standard. It is the language used for querying schemaless, semi-structured, JSON data found in the Couchbase Data Platform.

Couchbase Server 6.0 brings the first commercial implementation of the SQL++ language and uses it in the new Analytics service.

For more information, see the xref:https://docs.couchbase.com/server/6.0/analytics/1_intro.html[N1QL for Analytics Language Reference].

*Support for Timers in Couchbase Functions*

This release adds support for timers in Couchbase Functions.

Timers enable the ability to trigger routines at specific timestamps. They are constructs by which developers can specify logic routines that are to be triggered at a future time. By having them run directly in a Couchbase Service they’re close to your data and highly efficient.

For more information, see xref:eventing:eventing-language-constructs.adoc#timers[Timers].

*Full-Text Search improvements*

The Full-Text Search indexing capabilities have been greatly improved.
The indexing time has been cut in half and the index space requirements are as much as 70% lower.
These new indexing features are on by default and upgrading is as simple as recreating the index using the new 6.0 index type option.
For more information, see xref:fts:fts-creating-indexes.adoc[Creating Indexes].
