= What's New in Version 7.6
:description: Couchbase is the modern database for enterprise applications. Couchbase Server 7.6 combines the strengths of relational databases with the flexibility, performance, and scale of Couchbase.
:page-aliases: security:security-watsnew
:page-toclevels: 2

[abstract]
{description}

For information about platform support changes, deprecation notifications, notable improvements, and fixed and known issues, refer to the xref:release-notes:relnotes.adoc[Release Notes].

.deprecation notice
[IMPORTANT]
====
Using older x86 processors that do not have the AVX2 instruction set is deprecated in Couchbase Server 7.6.x.
Deprecated processors include pre-2013 Intel Core processors, pre-2020 Celeron or Pentium processors, and pre-2015 AMD processors.
See xref:install:pre-install.adoc[] for details.
====

.note regarding `cbbackupmgr`
[IMPORTANT]
====
If you are performing a backup/restore operation on a Couchbase Server 7.6.x cluster,
ensure that you use `cbbackupmgr` version 7.6.
====


[#new-features-766]
== New Features and Enhancements in 7.6.6

The following new features are provided in this release

include::partial$new_features-76_6.adoc[]

[#new-features-764]
== New Features and Enhancements in 7.6.4

The following new features are provided in this release
=======


include::partial$new_features-76_6.adoc[]
include::partial$new_features-76_4.adoc[]
include::partial$new-features-76_2.adoc[]
include::partial$new-features-76.adoc[]
