= What's New in Version 7.1?
:description: Couchbase is the modern database for enterprise applications. Couchbase Server 7.1 combines the strengths of relational databases with the flexibility, performance, and scale of Couchbase.
:page-aliases: security:security-watsnew

[abstract]
{description}

For information about platform support changes, deprecation notifications, notable improvements, and fixed and known issues, refer to the xref:release-notes:relnotes.adoc[Release Notes].

[#new-features]
== New Features and Enhancements

This section describes the new features and enhancements in this release.

=== Multiple Root Certificates

Prior to Couchbase Server Version 7.1, a Couchbase-Server cluster could maintain at most _one_ root certificate: all nodes and all clients were obliged to rely on this certificate's authority.
From version 7.1, Couchbase Server permits multiple root certificates to maintained in a _trust store_ for the cluster.
This allows an individual node either to use a CA that is also used by one or more other nodes; or to use a CA that is used by no other node.
This may be used during CA certificate rotation: a new CA is uploaded, node certificates are changed one by one, and finally, the old CA is removed.

Couchbase Server additionally uses its list of trusted certificates to verify:

* Client certificates (when client certificate authentication is enabled).

* The identities of cluster nodes (when node-to-node encryption is enabled).

* The identities of nodes that join the cluster (when the server has been provisioned with certificates).

* The identity of LDAP servers (when TLS has been turned on, in the LDAP settings).

For more information, see xref:learn:security/using-multiple-cas.adoc[Using Multiple Root Certificates].

=== Private Key Formats

In version 7.1, Couchbase Server supports _PKCS #1_ and _PKCS #8_ &#8212; in each case, only for use with private keys:

* _PKCS #1_ can be used for _unencrypted_ private keys only.

* _PKCS #8_ can be used for both _unencrypted_ and _encrypted_ private keys: note that the user-specified `EncryptedPrivateKeyInfo` must use _PKCS #5 v2_ algorithms.

=== JSON Passphrase Registration

If a node-certificate to be loaded is associated with an encrypted private key, a procedure can be defined to allow Couchbase Server to access and use the key’s passphrase, when use of the key is required: the passphrase can be registered by means of a JSON object.
For information, see xref:rest-api:upload-retrieve-node-cert.adoc#json-passphrase-registration[JSON Passphrase Registration].

=== System Events

_System events_ are generated to record significant occurrences on the cluster.
Events are provided for the Cluster Manager, the Data Service, the Index Service, the Search Service, the Eventing Service, the Backup Service, and the Analytics Service.
Events are also generated for XDCR, security, and Views.

Each event is provided as a JSON document containing a number of key-value pairs: some key-value pairs are included in all system events, others are specific to the service for which the event is generated.
Each key-value pair provides definitive information on the event.

For detailed information, see xref:learn:clusters-and-availability/system-events.adoc[System Events].

=== Sync Gateway Roles

New roles are provided for the administration of _Sync Gateway_, especially in the context of Couchbase Capella.
These roles are listed at xref:learn:security/roles.adoc[Roles].

=== TLS

TLS 1.3 cipher-suites can now by used by all services; and by the Cluster Manager, XDCR, and Views.
For information, see xref:learn:security/on-the-wire-security.adoc#tls-3-cipher-suite-limitations[On the Wire Security].
