= What's New in Version 6.6?
:page-aliases: security:security-watsnew

Couchbase Server 6.6 adds features and enhancements to improve developer productivity, foster Cloud deployments, and enable operational analytics on globally distributed data.

For more information about platform support changes, deprecation notifications, notable improvements, and fixed and known issues, refer to the xref:release-notes:relnotes.adoc[release notes].

[#new-features]
== New Features and Enhancements

_Quick Links_: <<whats-new-data-660>> | <<whats-new-analytics-660>> | <<whats-new-eventing-660>> | <<whats-new-query-660>> | <<whats-new-tools-660>>

[#whats-new-data-660]
=== Data Service

==== Bucket Level Durability Setting

You can now specify the durability level for your writes at the Bucket level in addition to the existing flexibility of choosing it at a per write level. The bucket level setting enables you to ensure that writes are done with a certain minimum level of durability, and hence be able to provide equivalent data protection guarantees.

To learn more about this feature, see xref:learn:data/durability.adoc#specifying-levels[Specifying Durability Level].

[#whats-new-analytics-660]
=== Analytics Service

==== External Datasets

Couchbase Analytics Service adds the ability to access external data from AWS S3 storage buckets, thereby enabling you to combine and analyze data in real time, sourced from both outside (AWS S3) and inside your Couchbase cluster(s). To learn more about this feature, see xref:analytics:5_ddl.adoc#External_datasets[External Datasets].


==== Remote Links

Couchbase Analytics Service introduces Remote Links which enable real-time operational analytics to obtain and analyze data from multiple Couchbase data clusters and datacenters in a separate cluster dedicated to the Analytics Service. To learn more about the feature, see xref:analytics:5_ddl.adoc#Remote_external_links[Remote Links and External Links].

[#whats-new-eventing-660]
=== Eventing Service

==== Timer Functionality

Couchbase Eventing Service introduces new Eventing timers that can be cancelled using the cancelTimer() function, or by creating a new timer with the same reference identifier as an existing timer.

Recurring timers are also fully supported, and can easily be used to create repetitive logic by using a timer callback to create fresh timers.

Timer scheduling enables timers to be created for days, weeks, or years in the future with no adverse performance impact.

For detailed examples on how to use these new Eventing timers, see xref:eventing:eventing-examples-cancel-overwrite-timer.adoc[Cancel or Overwrite Timer] and xref:eventing:eventing-examples-recurring-timer.adoc[Recurring Timer].

==== OnDelete Handler and UI Enhancements

The OnDelete Handler provides a new "options" parameter to indicate if a document was deleted or expired.

Key Eventing statistics in the UI are now co-located with each Function's lifecycle control.

These enhancements simplify the effort and code required to make robust business logic.

[#whats-new-query-660]
=== Query Service

==== Flex Index

Further to the N1QL and Full-Text Search (FTS) integration introduced in release 6.5, release 6.6 introduces N1QL Flex Index, which enables applications to leverage a Couchbase FTS index transparently in N1QL statements.

Applications with ad hoc queries can now benefit from FTS indexes while using standard N1QL predicates. The USE INDEX (USE FTS) hint steers the Query Service to automatically choose an applicable FTS index that is best suited for the query.

To learn more about the Flex Index feature, see xref:n1ql:n1ql-language-reference/flex-indexes.adoc[Flex Indexes].

==== Index Advisor

The Index Advisor has been promoted out of Beta to a fully supported feature, and is also now available online as an interactive tutorial.


The Index Advisor eliminates the guesswork in index creation and recommends changes to existing indexes wherever applicable. By providing recommendations for a specific query, or a set of queries from the Couchbase server log, it helps you create optimum indexes for your queries.

The Index Advisor also enables you to monitor performance and manage indexes to reflect the current usage pattern.

Starting with this release, the Index Advisor is a supported production feature and is available through graphical interfaces like the https://index-advisor.couchbase.com[online tutorial (new)^] and the xref:tools:query-workbench.adoc#index-advisor[Query Workbench]. It can also be invoked by using the xref:n1ql:n1ql-language-reference/advise.adoc[ADVISE Statement].

==== TTL Support in Query

Document expiration (Time to Live) is supported in Couchbase at both the bucket and the document level. The setting is intended for use on documents that can be automatically removed after a certain period of time. Before this release, expiration time was normally set during the document creation time using the Couchbase SDK.

With N1QL TTL, the expiration time can now be set and updated directly using the N1QL syntax. This enhancement allows administrators to change the document expiration policy after the document was created, or selectively choose documents for deletion via the document expiration mechanism.

[#whats-new-tools-660]
=== Tools

==== Non-root Install and Upgrade

Couchbase Server 6.6 standardizes the non-root install and upgrade for rpm packages to match the root install and upgrade procedures. By enabling you to easily install, upgrade, and maintain Couchbase Server as a non-root user, this update adds an extra layer of security and complies with the de facto standard in containerized environments.

To learn more, see xref:install:non-root.adoc[Non-Root Install and Upgrade].

==== Data Import via the UI

The Couchbase Web Console now provides a graphical interface to import data in JSON, CSV, or TSV formats. While the command-line utilities are recommended for high-performance data import and for importing large datasets, the graphical interface enables quick data ingestion for development or testing.

To learn more about importing data using the Couchbase Web Console, see xref:manage:import-documents/import-documents.adoc[Import Documents].

==== Backup to AWS S3 or any S3 Compatible Object Store

The `cbbackupmgr` utility adds support for object store and enables you to directly back up to and restore from AWS S3 or any other S3-compatible object store.

With the ability to backup large datasets directly to the cloud, you can leverage cloud-based object stores for your disaster recovery or archival use cases, or build containerized applications.

To learn more about this feature, see xref:backup-restore:cbbackupmgr-backup.adoc#cloud-integration[cbbackupmgr backup] and xref:backup-restore:cbbackupmgr-restore.adoc#cloud-integration[cbbackupmgr restore].

==== Backup Info Command

The `cbbackupmgr info` command provides additional information such as type of backup, start and end dates for merged backups, and the number of views, global secondary indexes (GSI), and FTS indexes. You can obtain the output in JSON format for automation purposes.

To learn more about the command, see xref:backup-restore:cbbackupmgr-info.adoc[cbbackupmgr info].

==== Backup Examine (Developer Preview)

The `cbbackupmgr examine` command is a new feature in Developer Preview that allows you to search one or more backups for a specific document using its ID. This command can be used to learn about what was previously backed up, to identify the backup to restore, to verify a document in the backup, and also to review the historic view of document transformation.

To learn more about the command, see xref:backup-restore:cbbackupmgr-examine.adoc[cbbackupmgr examine].

== What's New in Couchbase Server Version 7.0

In Version 7.0, Couchbase Server provides the following new features:

=== Scopes and Collections

Couchbase Server provides _scopes_ and _collections_; allowing documents to be categorized and organized, within a bucket.

A _collection_ is a data container, defined on Couchbase Server, within a bucket whose type is either _Couchbase_ or _Ephemeral_.
Bucket-items can optionally be assigned to different collections according to content-type.
For example, within a bucket that contains travel information, documents that relate specifically to _airports_ might be assigned to an _airports_ collection, while documents that relate to _hotels_ might be assigned to a _hotels_ collection, and so on.

A _scope_ is a mechanism for the grouping of multiple collections.
Collections might be assigned to different scopes according to content-type, or to deployment-phase (ie, test versus production). Applications can be assigned per-scope access-rights; allowing each application to access only those collections it requires.

The benefits of scopes and collections include:

* The logical grouping of similar documents; potentially simplifying operations such as query, XDCR, and backup and restore.

* The increased efficiency of indexing, due to the Data Service being able to provide documents from specific collections to the Index Service.

* Simplified querying, since query statements are able more easily to specify particular subsets of documents.

* Easier migration from relational databases to Couchbase Server, since collections can be designed to correspond to pre-existing relational tables.

* Secure isolation of different document-types, within a bucket; allowing applications to be specifically authorized to use only their appropriate subsets of data.

A complete overview of scopes and collections is provided in xref:learn:data/scopes-and-collections.adoc[Scopes and Collections].

==== Creating Scopes and Collections

Scopes and collections can be created by means of the Couchbase Web Console UI, the Couchbase CLI, and the Couchbase REST API.
See xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc[Manage Scopes and Collections] for instructions.

==== Assigning Roles with Reference to Scopes and Collections

Roles can be assigned to users with reference to specific scopes and collections, as well as to buckets.
To see how this can be performed by means of the Couchbase Web Console UI, see xref:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups, and Roles].

==== Importing Documents into Scopes and Collections

Couchbase Server Version 7.0 allows documents to be imported into specific collections.
For a step-by-step guide, see xref:manage:import-documents/import-documents.adoc[Import Documents].

==== Getting Information on Scopes and Collections

Informtion on currently defined scopes and collections can be returned by means of the `cbstats` xref:cli:cbstats/cbstats-collections.adoc[collections], xref:cli:cbstats/cbstats-collections-details.adoc[collections-details], xref:cli:cbstats/cbstats-scopes.adoc[scopes], and xref:cli:cbstats/cbstats-scopes-details.adoc[scopes-details] commands.
Additionally, collection-specific information on _keys_ and _vkeys_ can be returned, by means of the `cbstats` xref:cli:cbstats/cbstats-key.adoc[key] and xref:cli:cbstats/cbstats-vkey.adoc[vkey] commands, respectively.

=== The Backup Service

The Backup Service supports the scheduling of full and incremental data backups, either for specific individual buckets, or for all buckets on the cluster.
It also allows the scheduling of _merges_ of previously made backups.
Data to be backed up can also be selected by _service_: for example, the data for the _Data_ and _Index_ Services alone might be selected for backup, with no other service's data included.

The service &#8212; which is also referred to as _cbbs_ (Couchbase Backup Service) &#8212; can be configured and administered by means of the Couchbase Web Console UI, the CLI, or the REST API.

A complete overview of the Backup Service is provided in xref:learn:services-and-indexes/services/backup-service.adoc[Backup Service].
Step-by-step instructions for using the service by means of Couchbase Web Console are provided in xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc[Manage Backup and Restore].
A complete list of commands provided with the Couchbase REST API for the Backup Service is provided in xref:rest-api:backup-rest-api.adoc[Backup Service API].
