= What's New in Version 7.0 Beta?
:page-aliases: security:security-watsnew

Couchbase Server 7.0, now in Beta, introduces scopes and collections that provide new database organizaion structures within Couchbase. It also brings new capabilities to the Query Service in addition to support for scopes and collections. Read 

For more information about platform support changes, deprecation notifications, notable improvements, and fixed and known issues, refer to the xref:release-notes:relnotes.adoc[release notes].

[#new-features]
== New Features and Enhancements

_Quick Links_: <<whats-new-server-700>> | <<whats-new-services-query-700>> | <<whats-new-tools-700>>

In Version 7.0, Couchbase Server provides the following new features:

[#whats-new-server-700]
=== Scopes and Collections

Couchbase Server provides scopes and collections to easily build and deploy microservice based multi-tenant applications. Scopes and collections allow logical isolation of different types of data, independent lifecycle management, and security control at multiple levels of granularity. 

Couchbase Server provides _scopes_ and _collections_; allowing documents to be categorized and organized, within a bucket.

A _collection_ is a data container, defined on Couchbase Server, within a bucket whose type is either _Couchbase_ or _Ephemeral_.
Bucket-items can optionally be assigned to different collections according to content-type.
For example, within a bucket that contains travel information, documents that relate specifically to _airports_ might be assigned to an _airports_ collection, while documents that relate to _hotels_ might be assigned to a _hotels_ collection, and so on.

A _scope_ is a mechanism for the grouping of multiple collections.
Collections might be assigned to different scopes according to content-type, or to deployment-phase (ie, test versus production).
Applications can be assigned per-scope access-rights; allowing each application to access only those collections it requires.

The benefits of scopes and collections include:

* The logical grouping of similar documents; potentially simplifying operations such as query, XDCR, and backup and restore.

* The increased efficiency of indexing, due to the Data Service being able to provide documents from specific collections to the Index Service.

* Simplified querying, since query statements are able more easily to specify particular subsets of documents.

* Easier migration from relational databases to Couchbase Server, since collections can be designed to correspond to pre-existing relational tables.

* Secure isolation of different document-types, within a bucket; allowing applications to be specifically authorized to use only their appropriate subsets of data.

A complete overview of scopes and collections is provided in xref:learn:data/scopes-and-collections.adoc[Scopes and Collections].

==== Creating Scopes and Collections

Scopes and collections can be created by means of the Couchbase Web Console UI, the Couchbase CLI, and the Couchbase REST API.
See xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc[Manage Scopes and Collections] for instructions.

==== Assigning Roles with Reference to Scopes and Collections

Roles can be assigned to users with reference to specific scopes and collections, as well as to buckets.
To see how this can be performed by means of the Couchbase Web Console UI, see xref:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups, and Roles].

==== Importing Documents into Scopes and Collections

Couchbase Server Version 7.0 allows documents to be imported into specific collections.
For a step-by-step guide, see xref:manage:import-documents/import-documents.adoc[Import Documents].

==== Getting Information on Scopes and Collections

Information on currently defined scopes and collections can be returned by means of the `cbstats` xref:cli:cbstats/cbstats-collections.adoc[collections], xref:cli:cbstats/cbstats-collections-details.adoc[collections-details], xref:cli:cbstats/cbstats-scopes.adoc[scopes], and xref:cli:cbstats/cbstats-scopes-details.adoc[scopes-details] commands.
Additionally, collection-specific information on _keys_ and _vkeys_ can be returned, by means of the `cbstats` xref:cli:cbstats/cbstats-key.adoc[key] and xref:cli:cbstats/cbstats-vkey.adoc[vkey] commands, respectively.

==== Using XDCR with Scopes and Collections

XDCR can replicate to a specific scope or collection.
Examples are provided in xref:manage:manage-xdcr/replicate-using-scopes-and-collections.adoc[Replicate Using Scopes and Collections].

=== Per-Service On-the-Wire Security Settings

Cluster-settings for on-the-wire security &#8212; including specifying TLS version and cipher-suite list &#8212; can now be set _per service_, as well as globally.
For information, see xref:manage:manage-security/manage-tls.adoc[Manage TLS].


[#whats-new-services-query-700]
=== Query Enhancements

In addition to support for scopes and collections, this release adds the following capabilities to the Query Service: 

==== Couchbase Transactions with N1QL

Couchbase Server 7.0 Beta extends the support of transactions to the Couchbase query language, N1QL. 
The support for multi-document ACID transactions was introduced in version 6.5 and the feature is available to application developers through Couchbase SDK and APIs. 

With this release, application developers and RDBMS users can use familiar transactional constructs such as START TRANSACTION, SAVEPOINT, ROLLBACK and COMMIT.  And similar to RDBMS transactions, all N1QL DML support transactions. 

To learn more about using transactions with N1QL, see xref:n1ql:n1ql-language-reference/begin-transaction.adoc[], xref:n1ql:n1ql-language-reference/commit-transaction.adoc, xref:n1ql:n1ql-language-reference/savepoint.adoc[], xref:n1ql:n1ql-language-reference/rollback-transaction.adoc[], and xref:n1ql:n1ql-language-reference/set-transaction.adoc[]. 

==== Cost-based Optimizer

==== Index Advisor

==== User Defined Functions

==== Memory Usage Quota Setting

[#whats-new-tools-700]
=== The Backup Service

The Backup Service supports the scheduling of full and incremental data backups, either for specific individual buckets, or for all buckets on the cluster.
It also allows the scheduling of _merges_ of previously made backups.
Data to be backed up can also be selected by _service_: for example, the data for the _Data_ and _Index_ Services alone might be selected for backup, with no other service's data included.

The service &#8212; which is also referred to as _cbbs_ (Couchbase Backup Service) &#8212; can be configured and administered by means of the Couchbase Web Console UI, the CLI, or the REST API.

A complete overview of the Backup Service is provided in xref:learn:services-and-indexes/services/backup-service.adoc[Backup Service].
Step-by-step instructions for using the service by means of Couchbase Web Console are provided in xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc[Manage Backup and Restore].
A complete list of commands provided with the Couchbase REST API for the Backup Service is provided in xref:rest-api:backup-rest-api.adoc[Backup Service API].
