= What's New in Version 7.1?
:description: Couchbase is the modern database for enterprise applications. Couchbase Server 7.1 combines the strengths of relational databases with the flexibility, performance, and scale of Couchbase.
:page-aliases: security:security-watsnew

[abstract]
{description}

For information about platform support changes, deprecation notifications, notable improvements, and fixed and known issues, refer to the xref:release-notes:relnotes.adoc[Release Notes].

[#new-features]
== New Features and Enhancements

This section describes the new features and enhancements in this release.

=== Multiple Root Certificates

Prior to Couchbase Server Version 7.1, a Couchbase-Server cluster could maintain at most _one_ root certificate: all nodes and all clients were obliged to rely on this certificate's authority.
From version 7.1, Couchbase Server permits multiple root certificates to maintained in a _trust store_ for the cluster.
This allows an individual node either to use a CA that is also used by one or more other nodes; or to use a CA that is used by no other node.
This may be used during CA certificate rotation: a new CA is uploaded, node certificates are changed one by one, and finally, the old CA is removed.

Couchbase Server additionally uses its list of trusted certificates to verify:

* Client certificates (when client certificate authentication is enabled).

* The identities of cluster nodes (when node-to-node encryption is enabled).

* The identities of nodes that join the cluster (when the server has been provisioned with certificates).

* The identity of LDAP servers (when TLS has been turned on, in the LDAP settings).

For more information, see xref:learn:security/using-multiple-cas.adoc[Using Multiple Root Certificates].

=== Private Key Formats

In version 7.1, Couchbase Server supports _PKCS #1_ and _PKCS #8_ &#8212; in each case, only for use with private keys:

* _PKCS #1_ can be used for _unencrypted_ private keys only.

* _PKCS #8_ can be used for both _unencrypted_ and _encrypted_ private keys: note that the user-specified `EncryptedPrivateKeyInfo` must use _PKCS #5 v2_ algorithms.

=== JSON Passphrase Registration

If a node-certificate to be loaded is associated with an encrypted private key, a procedure can be defined to allow Couchbase Server to access and use the key’s passphrase, when use of the key is required: the passphrase can be registered by means of a JSON object.
For information, see xref:rest-api:upload-retrieve-node-cert.adoc#json-passphrase-registration[JSON Passphrase Registration].

=== System Events

_System events_ are generated to record significant occurrences on the cluster.
Events are provided for the Cluster Manager, the Data Service, the Index Service, the Search Service, the Eventing Service, the Backup Service, and the Analytics Service.
Events are also generated for XDCR, security, and Views.

Each event is provided as a JSON document containing a number of key-value pairs: some key-value pairs are included in all system events, others are specific to the service for which the event is generated.
Each key-value pair provides definitive information on the event.

For detailed information, see xref:learn:clusters-and-availability/system-events.adoc[System Events].

=== Sync Gateway Roles

New roles are provided for the administration of _Sync Gateway_, especially in the context of Couchbase Capella.
These roles are listed at xref:learn:security/roles.adoc[Roles].

=== TLS

TLS 1.3 cipher-suites can now be used by all services; and by the Cluster Manager, XDCR, and Views.
For information, see xref:learn:security/on-the-wire-security.adoc#tls-3-cipher-suite-limitations[On the Wire Security].

=== ARM Support

Amazon Linux is now supported on the ARM platform.
See xref:release-notes:relnotes.adoc[] and xref:install:install-platforms.adoc[]

=== Magma Storage Engine
[.edition]#{enterprise}#

The new Magma Storage Engine has been added to 7.1 as an Enterprise Edition feature, allowing for higher performance with very large datasets.
Magma is a disk-based engine, so is highly suited to datasets that will not fit in available memory.
You can find more details on Magma in xref:learn:buckets-memory-and-storage/storage-engines.adoc[]

=== Improved Auto-Failover

Automatic Failover can now failover several nodes concurrently and automatic failover of index services is now supported.
Improvements have also been made to rebalancing algorithms so that active and all replicas will be spread across different server groups even when server groups are unequal.

See xref:learn:clusters-and-availability/automatic-failover.adoc[] and xref:learn:clusters-and-availability/groups.adoc[]


=== Improvements to JavaScript User-Defined Functions

//TODO: Add links to the documents when they're merged.

Scope Hierarchy Support::
The JavaScript UDF libraries can now be stored within collection scopes, allowing access to be restricted to users with the necessary security permissions.

UI Support::
Javascript libraries and functions can now be added through the Query tool in the administration console.

=== Improvements to Full-Text Search

A number of improvements have been made to Full-Text Search:

Croatian Language Support::
The FTS engine now supports the Croatian language for search-term input.

Improved Search in the UI::
The FTS UI will now accept complex full text search terms as well as basic search strings.

File-Based Rebalance in FTS::
Prior to version{nbsp}7.1, FTS index partitions were rebuilt from scratch on each node during rebalance operations. 
Under version{nbsp}7.1, the index partition files are copied to the nodes, allowing for faster rebalancing.

Increase in the Number of Full-Text Indexes Supported::
FTS now supports up 500 index partitions per cluster.

=== Index Service Enhancements

The Index Service now provides:

Smart Batching:: 
Allows the rebuilding of indexes, during rebalance, to be maintained at an optimal performance-level.
For information, see xref:learn:clusters-and-availability/rebalance.adoc#smart-batching[Smart Batching].

Array Flattening::
Whereby the elements of arrays can be more efficiently indexed.
See xref:n1ql:n1ql-language-reference/metafun.adoc#flatten_keys[FLATTEN_KEYS].
