= Sink Configuration Options
:page-topic-type: concept

[abstract]
Reference of the source connector options.

== Database

`connection.cluster_address`

Couchbase Cluster addresses to listen (use comma to specify several).

* Type: list
* Importance: high

`connection.bucket`

Couchbase bucket name.

* Type: string
* Importance: high

`connection.username`

Couchbase username for Couchbase Server 5.0 and later.

* Type: string
* Importance: high
* Default: the bucket name specified by `connection.bucket`

`connection.password`

Couchbase password.
For Couchbase Server versions prior to 5.0 this is the bucket password.
For versions 5.0 and later, this is the password associated with `connection.username`.

* Type: password
* Importance: low
* Default: `""`

`connection.timeout.ms`

Connection timeout in milliseconds.

* Type: long
* Importance: low

`connection.ssl.enabled`

Use SSL to connect to Couchbase.
This feature only available in Couchbase Enterprise.

* Type: boolean
* Importance: low
* Default: `false`
* Dependents: `connection.ssl.keystore.location`, `connection.ssl.keystore.password`

`connection.ssl.keystore.location`

The location of the key store file.

* Type: string
* Importance: low

`connection.ssl.keystore.password`

The password of the private key in the key store file.

* Type: password
* Importance: low
* Default: `""`
