[#concept_hyp_xpf_vs]
= Deployment and operations

[abstract]
An important feature of Couchbase Server is that all operations and deployment can be done online, without changing or impacting running applications.
This includes routine maintenance including software upgrades and provisioning and removing nodes, manual or automated processes such as compaction and rebalances, and exceptional processes such as failing over nodes.

Administration and monitoring can be performed using the web-based administration console, through the command line interface, or using REST APIs.
The same methods are used to manually configure and tune operations that can be automated, such as compaction and failover.

Common administrative tasks include:

* *Deployment:* Install and configure a cluster and its nodes.
* *Upgrade:* Upgrade Couchbase software without reconfiguration or disrupting running applications.
For more information, see xref:install:upgrading.adoc[Upgrading Couchbase Server].
* *Scaling:* Add or remove nodes from the cluster as the application demands change, then initiate a rebalance to replicate the data to the new or remaining nodes (if shrinking the cluster).
* *Failover:* Activate replica copies within the data service for a node that is no longer responding.
(Automatic or Manual)
* *Monitoring:* Watch and react to the various statistics reported by the server to ensure that the cluster is operating at its highest performance level.
* *Compaction:* Reduce fragmentation and reclaim disk space by compacting data and index files.
(Automatic or Manual)
* *Manage security:* Grant authorizations, configure encryption, and audit logs of administrative actions performed.
* *Manage buckets:* Create, delete, flush, and change settings of buckets.
* *Recover node:* Initiate delta-node or full recovery on a node that failed and is ready to rejoin the cluster.
* *Backup:* Create a full or partial archive of the cluster, node or vBucket.
* *Cross Data Center Replication:* Configure and manage XDCR to replicate data from one cluster to another.
