= Data handling in Javascript UDFs
:description: Moving data between Javascript UDFs and {sqlpp}.
:page-pagination: 
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2

[abstract]
{description}

== Introduction

Javascript is procedural object-based language, and {sqlpp} is declarative in nature. 
Moreover, Couchbase naturally works with https://www.w3schools.com/whatis/whatis_json.asp[json] in its data handling, so the data returned from {sqlpp} statements are json objects. 

== Packing and unpacking JSON data in Javascript

If we look back at the `add` function:

[source, javascript]
----
include::example$javascript-udfs/add.js[]
----

When it's called as part of a {sqlpp} statement:

[source, n1ql]
----
include::example$javascript-udfs/add-statement.n1ql[]
----

It returns its result packaged as a `json` object instead of a Javascript number:

[source, json]
----
include::example$javascript-udfs/add-response.json5[]
----

When using the function as part of a statement call, the unpacking processing is handled by the query engine, so that a query such as:

[source, N1SQL]
----
select "true" as response where MyAdd(2000, 1) > 2000
----

will unpack the result of `MyAdd(2,2)` and apply the result to the `WHERE` clause:

[source, json]
----
[
  {
    "response": "true"
  }
]
----

== Transforming data in a Javascript UDF

If you're using a user-defined function, then the chances are that you want to perform some kind of transformation on the data received back from an embedded {sqlpp} call, then returning the transformed from your Javascript function:

include::partial$javascript-udfs/diagrams-plantuml.adoc[tags="javascript-udf-data-transformation"]

Fortunately, Javascript is very adept at working with JSON data, which is the native data format used by Couchbase.

The following function will retrieve all the airlines from the database and return just those that are based in the country supplied as a parameter.
And rather than the whole document, we just want a list of the airline's name and call sign.

[source, javascript]
----
include::example$javascript-udfs/select-airline.js[]
----

Running this as function:

[source, N1QL]
----
EXECUTE FUNCTION selectAirlines('United Kingdom');
----

will a list formatted in JSON:

[source, javascript]
----
[
  [
    {
      "callsign": null,
      "name": "Jc royal.britannica"
    },
    {
      "callsign": "FLYSTAR",
      "name": "Astraeus"
    },
    {
      "callsign": "SPEEDBIRD",
      "name": "British Airways"
    },
    {
      "callsign": "BRINTEL",
      "name": "British International Helicopters"
    },
    {
      "callsign": "MIDLAND",
      "name": "bmi"
    },
    {
      "callsign": "BABY",
      "name": "bmibaby"
    }
  ]
]
----

TIP: It would far easier to do this directly as a {sqlpp} instead of a Javascript UDF. 
This is just a demonstration.

== Handling Dates

Couchbase, like JSON, doesn't have a native date type, but it is recommended that you make use of the https://en.wikipedia.org/wiki/ISO_8601[ISO-8601^] standard, since Javascript has a number of built-in date functions that use this format as their base.
The following function creates a new airline, but will add an extra field recording the date it began operating.

[source,javascript]
----
include::example$javascript-udfs/add-airline-with-date.js[]
----
<.> Create a key for the new record from the supplied `id` number.
<.> Create a constant that contains the current date. 
Using the `to.JSON()` call on the `Date` object, we create a string of the current date in ISO-8601 format and assign to `d`.
<.> The ISO-8601 data string is used in the embedded {sqlpp} call to supply the ISO-8601 date.

The record added to the bucket will look something like this:

[source, json]
----
[
  {
    "airline": {
      "ca1": "Q5",
      "callsign": "RAZ-AIR",
      "country": "United Kingdom",
      "icao": "MLA",
      "id": 1220,
      "name": "Raz Air",
      "opdate": "2022-02-25T09:40:57.589Z",    // <.>
      "type": "airline"
    }
  }
]
----
<.> Note that the date is in ISO-8601 format.

[WARNING]
====
You may be tempted to save a few lines of code by trying something like this:

[source, javascript]
----
    const d = new Date()
    
    var q = insert into `travel-sample`.`inventory`.`airline` values(
        $full_id, 
        {"id": $id, 
            "type": "airline", 
            "name": $name, 
            "ca1": "Q5", 
            "icao": "MLA", 
            "callsign": $callsign, 
            "country": $country, 
            "opdate": $d.toJSON()});    // <.>
----
<.> Although this appears to be a valid shortcut, the Javascript transpiler will only translate simple constants and variable names. Expressions and method calls are not allowed.
====


== Further Reading

include::partial$javascript-udfs/further-reading.adoc[tags="insert;execute-function"]


