= Handling Errors in Javascript UDFs
:description: Error handling in Javascript user-defined functions use the same standard exception mechanism as part of the language standard.
:page-pagination: prev
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2

[abstract]
{description}

Runtime errors that occur during the execution of an {sqlpp} statement are usually handled by the runtime, which will return a JSON object giving details of the error. 
For example, if we execute a record insertion function with a key that already exists:

[source, n1ql]
----
include::example$javascript-udfs/execute-airline-function-with-date.n1ql[]
----

If the key already exists, then an error object is returned:

[source, json]
----
include::example$javascript-udfs/duplicate-key-error.json5[]
----

In most cases, it's a lot better if the Javascript function itself can handle errors that are likely to occur. 
This gives the developer the option of responding with a more user-friendly message, or taking an alternative course of action.

The following function will add an airline record, but will return an `failure` message if the attempt isn't successful.

[source, javascript]
----
include::example$javascript-udfs/add-airline-with-check.js[]
----

If the record key already exists, then calling this method with `EXECUTE FUNCTION`  will produce the following result:

[source, json]
----
include::example$javascript-udfs/add-airline-with-check-failure-response.json5[]
----

Unfortunately, this doesn't tell use very much about what caused the error, or indeed, the possiblity of taking an alternative course of action depending on the type of error encountered. 
To make the error-handling a bit more useful, we first have to parse the error using  `JSON.parse`.

[source, javascript]
----
include::example$javascript-udfs/add-airline-check-parse.js[]
----
<.> The `error` object contains a JSON string (`message`) detailing the nature of the error. 
It is much easier to interrogate the message if it's converted back into a JSON object on its own.
This code will send back the entire message structure.

[source, json]
----
include::example$javascript-udfs/parsed-error-in-full.json5[]
----

Once we know the structure of the error message, there's no reason why we can't carry out alternative actions depending on the type of error encountered:

[source, javascript]
----
include::example$javascript-udfs/add-airline-parse-check-2.js[]
----
<.> Check to see if this is a message that can be handled by the function itself.
<.> Strips out the `"Duplicate Key: "` part of the message, leaving just the duplicate key.

== Further Reading

include::partial$javascript-udfs/further-reading.adoc[tags="query-workbench;select;execute-function"]
