= Data handling in Javascript UDFs
:description: Moving data between Javascript UDFs and {sqlpp}.
:page-pagination: 
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2

[abstract]
{description}

== Introduction

Javascript is procedural object-based language, and {sqlpp} is declarative in nature. 
Moreover, Couchbase naturally works with https://www.w3schools.com/whatis/whatis_json.asp[json] in its data handling, so the data returned from {sqlpp} statements are json objects. 

include::javascript-udfs.adoc[tags="what-you-need"]

== Packing and unpacking JSON data in Javascript

The runtime will automatically format into JSON objects when they're returned from a function.

For example:

[source, javascript]
----
include::example$javascript-udfs/get-business-days.js[]
----
<.> Function returns a number.

When the function is called:

[source, n1ql]
----
include::example$javascript-udfs/execute-get-business-days.n1ql[]
----

it returns its result packaged as a `json` object instead of a Javascript number:

[source, json]
----
include::example$javascript-udfs/execute-get-business-days-response.jsonc[]
----

When using the function as part of a statement call, the unpacking processing is handled by the query engine, so that a query such as:

[source, N1SQL]
----
include::example$javascript-udfs/select-true-get-business-days.n1ql[]
----

will unpack the result of the `GetBusinessDays` call and apply the result to the `WHERE` clause:

[source, json]
----
include::example$javascript-udfs/true-response.jsonc[]
----

== Using Field Aliases

There may be cases where you will need to provide your own field names in returned objects. 
(For example, when you are returning a calculated field instead of a field that exists in the record.)
In order to do this, use a field alias in your {sqlpp} statement:

[source, n1ql]
----
include::example$javascript-udfs/select-true-alias-get-business-days.n1ql[]
----
<.> The `alias` clause names the result as `response` when it's built into the return object:


[source, json]
----
include::example$javascript-udfs/true-alias-response.jsonc[]
----
== Transforming data in a Javascript UDF

If you're using a user-defined function, then the chances are that you want to perform some kind of transformation on the data received back from an embedded {sqlpp} call, then returning the transformed from your Javascript function:

include::partial$javascript-udfs/diagrams-plantuml.adoc[tags="data-transformation"]

The following function will retrieve all the airlines from the database and return just those that are based in the country supplied as a parameter.
And rather than the whole document, we just want a list of the airline's name and call sign.

[tabs]
====
inline::
+
[source, javascript]
----
include::example$javascript-udfs/select-airline-inline.js[]
----

N1QL() call::
+
[source, javascript]
----
include::example$javascript-udfs/select-airline-n1ql.js[]
----
====
<.> Using the `AS` clause in the {sqlpp} statement renames the specified fields extracted from the collection. 
<.> The aliased fields are used in the JavaScript code.

Running this as function:

[source, N1QL]
----
include::example$javascript-udfs/execute-airline-function.n1ql[]
----

will a list formatted in JSON:

[source, json]
----
include::example$javascript-udfs/execute-airline-function-response.jsonc[]
----

== Handling Dates

Couchbase, like JSON, doesn't have a native date type, but it is recommended that you make use of the https://en.wikipedia.org/wiki/ISO_8601[ISO-8601^] standard, since Javascript has a number of built-in date functions that use this format as their base.
The following function creates a new airline, but will add an extra field recording the date it began operating.

[tabs]
====
inline::
+
[source,javascript]
----
include::example$javascript-udfs/add-airline-with-date-inline.js[]
----

n1ql() call::
+
[source,javascript]
----
include::example$javascript-udfs/add-airline-with-date-n1ql.js[]
----
====

<.> Create a key for the new record from the supplied `id` number.
<.> Create a constant that contains the current date. 
Using the `to.JSON()` call on the `Date` object, we create a string of the current date in ISO-8601 format and assign to `d`.
<.> The ISO-8601 data string is used in the embedded {sqlpp} call to supply the ISO-8601 date.

The record added to the bucket will look something like this:

[source, json]
----
include::example$javascript-udfs/add-airline-with-date-response.jsonc[]
----
<.> Note that the date is in ISO-8601 format.


== Further Reading

include::partial$javascript-udfs/further-reading.adoc[tags="insert;execute-function"]


