= User-defined Functions in Javascript
:description: Extending the SQL++ query language by adding your own functions written in Javascript
:page-pagination: next
:page-topic-type: guide
:page-toclevels: 2

[.edition]#{enterprise}#
[abstract]
{description}

== Introduction

{sqlpp} includes a large number of xref:n1ql:n1ql-language-reference/index.adoc[operations and generic functions] that cover every aspect of data manipulation. 
In addition to the built-in functions, Couchbase also allows you to create your own extensions to the language using Javascript.
Using Javascript user-defined functions, you can:

* Create reuseable, domain-specific functions for use in your applications.
* Migrate from RDBMS stored procedures.
* Use  SQL++ statements embedded in your Javascript to access and modify your data.

== Before you begin

You're going to need a basic working knowledge of https://www.w3schools.com/js/[Javascript^].

You're going to be running through some live examples, so will need access to a Couchbase server. 
If you don't have one available then you have a number of options:

* You can https://www.couchbase.com/products/capella[sign up to Capella], the Couchbase cloud service.
* You can xref:install:install-intro.adoc[install a standalone server on your local machine].
* You can run Couchbase as a xref:install:getting-started-docker.adoc[Docker instance].

NOTE: User-defined functions require the Couchbase Server Enterprise Edition.
This guide assumes that you are running version 7.1 or greater.

If you need to create a cluster on your server, then follow the instructions in xref:manage:manage-nodes/create-cluster.adoc[].

You will also need the `travel-sample` bucket to work through the examples.
You will find instructions for installing the `travel-sample` in xref:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Install Sample Buckets]. 
 
You will also need a basic understanding of Couchbase SQL++. (You can find tutorials for the query language xref:n1ql:tutorial.adoc[here]).

== Next Steps

It's recommended that you follow these steps in order.
 
'''
. xref:javascript-udfs/creating-javascript-udf.adoc[]

. xref:javascript-udfs/calling-javascript-udf.adoc[]

. xref:javascript-udfs/data-handling-javascript-udf.adoc[]

'''










