= Change History
:description: pass:q[When Magma storage is used for a bucket, the changes made to documents within the bucket's collections can be recorded, in a _change history_.]

[abstract]
{description}

[#understanding-change-history]
== Understanding Change History

When xref:learn:buckets-memory-and-storage/storage-engines.adoc#storage-engine-magma[Magma] storage is used for a bucket, the changes made to documents within the bucket's collections can be recorded, in a _change history_.
The change history resides on disk.
Its capacity is administrator-specified.
When the change history is full, old records are automatically removed (by means of compaction), to allow space for new records.

Change history can be either _on_ or _off_.
This is determined at bucket-level: if the change history is _on_, it is active for _all collections_ in the bucket.

For a bucket's change history to be switched _on_, the capacity of the change history must be established, as a positive integer corresponding either to _bytes_ or _seconds_.
If no capacity is specified, no change history is generated.
Optionally, positive integers can be specified for _both_ bytes and seconds: in such cases, record-removal occurs as soon as either capacity is reached.
Note that the change history is created _per bucket_, and is replicated in accordance with the number of intra-cluster replicas defined for the bucket.

If the change history for a bucket is switched _on_, the recording of changes can be performed in either of two ways, which are:

* _Deduplication off_.
All changes to documents in the collection are recorded.

* _Deduplication on_.
Only a subset of changes to documents in the collection is recorded.

Deduplication is manually configured at collection-level; either when the collection is created; or subsequently, when the collection's existing setting is modified.
The default setting for all collections is controlled at bucket-level.

== Change-History Management

The following interfaces are provided for configuring change history.

[#change-history-enablement]
=== Change-History Enablement and Capacity Settings

The recording of change history is enabled at bucket level.
By default, it is _disabled_.
It can be enabled at bucket-creation, and can subsequently be disabled and enabled by changing the existing bucket's configuration.

Enablement occurs by defining a capacity for the on-disk change history.
This can be specified with a positive integer, corresponding either to _bytes_ or to _seconds_.
Optionally, positive integers can be specified for both bytes and seconds.
If, as the change history's size increases, either capacity is reached, records are removed from the change history (by means of compaction), to make room for new records.

If the default value of zero is retained in both cases, the recording of change history is disabled.

Change history can be enabled with either:

* The REST API, using `POST /pools/default/buckets` (to create a bucket) or `POST /pools/default/buckets/<bucketName>` (to edit); specifying one or both of the parameters `historyRetentionBytes` and `historyRetentionSeconds`.
See xref:rest-api:rest-bucket-create.adoc[Creating and Editing Buckets].

* The CLI, using `couchbase-cli bucket-create` (to create a bucket) or `couchbase-cli bucket-edit` (to edit a bucket); specifying one or both of the parameters `history-retention-bytes` and `history-retention-seconds`.
See xref:cli:cbcli/couchbase-cli-bucket-create.adoc[bucket-create] and xref:cli:cbcli/couchbase-cli-bucket-edit.adoc[bucket-edit].

[#deduplication-bucket-wide]
=== Deduplication Bucket-Wide Default Settings

A change history can be created with _deduplication_ either _off_ or _on_.
If deduplication is _off_, the change history is more complete.
If deduplication is _on_, the change history is more compact.

The setting for deduplication can be made at collection-level.
However, the default for all collections within a bucket can be established when a bucket is either created or edited.
By default, this setting has a value of `true`, which means that deduplication is _off_ for every collection; unless the setting is overridden in the creating or editing of the individual collection.

The bucket-wide default deduplication setting can be established with either:

* The REST API, using `POST /pools/default/buckets` (to create a bucket) or `POST /pools/default/buckets/<bucketName>` (to edit); specifying the parameter `historyRetentionCollectionDefault`.
See xref:rest-api:rest-bucket-create.adoc[Creating and Editing Buckets].

* The CLI, using `couchbase-cli bucket-create` (to create a bucket) or `couchbase-cli bucket-edit` (to edit a bucket); specifying the parameter `enable-history-retention-by-default`.
See xref:cli:cbcli/couchbase-cli-bucket-create.adoc[bucket-create] and xref:cli:cbcli/couchbase-cli-bucket-edit.adoc[bucket-edit].

=== Deduplication Collection-Specific Settings

A change history can be made with deduplication either _off_ or _on_.
A default setting that applies to all collections can be established at bucket level; as described in xref:learn:data/change-history.adoc##deduplication-bucket-wide[Deduplication Bucket-Wide Default Setting], above.

However, deduplication can also be switched off or on for each individual collection, overriding the established, bucket-wide default.
This setting can be made either when the collection is created, or subsequently, by editing the collection's configuration.

The setting can be established with either:

* The REST API, using `POST /pools/default/buckets/<bucket_name>/scopes/<scope_name>/collections` (to create a collection) or `PATCH /pools/default/buckets/<bucket_name>/scopes/<scope_name>/collections/<collection_name>` (to edit); specifying the parameter `history`.
See xref:rest-api:creating-a-collection.adoc[Creating and Editing a Collection].

* The CLI, using `couchbase-cli collection-manage` (to create or edit a collection); specifying the parameter `enable-history-retention`.
See xref:cli:cbcli/couchbase-cli-collection-manage.adoc[collection-manage].

=== Change-History Status and Content-Access

The deduplication status of each collection can be returned by means of the `cbstats` tool, with the arguments `collections` and `collection-details`.
Output indicates a status of `true` (deduplication is _off_) or `false` (deduplication is _on_).
See the xref:cli:cbstats/cbstats-collections.adoc[collections] and xref:cli:cbstats/cbstats-collections-details.adoc[collections-details] reference pages for xref:cli:cbstats/cbstats-intro.adoc[cbstats].

To access the change history and examine its contents, use the xref:4.1@kafka-connector::index.adoc[Kafka 4.1 Connector].

=== Change-History Statistics



== See Also

For information on establishing change-history default settings, at bucket-creation time, see xref:rest-api:rest-bucket-create.adoc[Creating and Editing Buckets].
For information on switching on or off _deduplication_ of the change-record for a specific collection, see xref:rest-api:creating-a-collection.adoc[Creating and Editing a Collection].
To examine the deduplication status for each collection in a bucket, see the xref:cli:cbstats/cbstats-collections.adoc[collections] option for `cbstats`.
