= Expiration
:description: pass:q[_Time To Live_ (TTL) imposes a maximum lifespan on items within a bucket or a collection, and thus ensures the expiration of such items, once the specified period is complete.]

:page-aliases: understanding-couchbase:buckets-memory-and-storage/expiration, learn:buckets-memory-and-storage/expiration

[abstract]
{description}

[#bucket-data-expiration-overview]
== Overview

TTL is a non-negative integer-value, specified per bucket or per collection, that determines the maximum expiration time of individual items within the bucket or collection: if TTL is enabled, each newly created item lives for the number of seconds specified by TTL, following the item's creation.
After its expiration time is reached, the item will be deleted by Couchbase Server.
Deleted items and their contents are no longer available: access-attempts are treated as if the items never existed.

The maximum value for TTL is MAX32INT seconds (2147483648, or 68.096 years).
The default value is 0, which indicates that TTL is disabled.
If TTL is changed from the default, it is thereby enabled.

Whenever TTL is modified, items that existed _prior_ to the modification:

* Remain subject to the previous TTL, if TTL was previously enabled.
* Remain subject to no TTL, if TTL was not previously enabled.

Items created or modified _following_ the modification of TTL are subject to the modified TTL.

TTL can be established on Couchbase and Ephemeral buckets: it cannot be established on Memcached buckets.
TTL can be established on collections: it cannot be established on scopes.
Note that TTL is only available in the Enterprise Edition of Couchbase Server.

[#expiration-bucket-versus-item]
== Expiration: Bucket, Collection, and Item

As described in xref:java-sdk:howtos:kv-operations.adoc#document-expiration[Document Expiration], an expiration time can be specified per document, by means of Couchbase SDK APIs: this is referred to as the item’s TTL.

In cases where an item has a TTL, the item's TTL may need to be modified, depending on the TTL of either its bucket or its collection:

* If an item resides within a collection that has no TTL, and the collection resides within a bucket that _does_ have a TTL, the bucket's TTL is used to determine whether and how the item's TTL is modified.

* If an item resides within a collection that has its own TTL, and the collection resides within a bucket that has no TTL, the collection's TTL is used to determine whether and how the item's TTL is modified.

* If an item resides within a collection that has its own TTL, and the collection resides within a bucket that also has its own TTL, the bucket's TTL is ignored, and only the collection's TTL is used, to determine whether and how the item's TTL is modified.

Determination of whether and how to modify the item's TTL is as follows.
If a new item’s TTL is:

* Above that of the bucket's or the collection's TTL, the item's TTL is reduced to the value of the bucket's or the collection's TTL.
* Below that of the bucket's or the collection's TTL, the item's TTL is left unchanged.
* 0, the item's TTL is reset to the value of the bucket's or the collection's TTL.

[#bucket_ttl_use_cases]
== TTL Use Cases

TTL is intended for use with buckets and collections containing data that either must or can be permitted to expire after a certain period of time.

TTL _must not_ be used with buckets whose data is required not to expire: for example, the buckets that support Couchbase Eventing and Couchbase Mobile.
If TTL is used with such buckets, system failures may result.

[#post-expiration-purging]
== Post-Expiration Purging

When its expiration time is reached, an item is deleted as soon as one of the following occurs:

* An attempt is made to access the item.
* The _expiry pager_ is run.
For information on the expiry pager, see xref:buckets-memory-and-storage/memory.adoc[Memory].
* _Compaction_ is run.
For information on performing compaction with the Couchbase CLI, see xref:cli:cbcli/couchbase-cli-bucket-compact.adoc[bucket-compact]; with Couchbase REST APIs, see xref:rest-api:compaction-rest-api.adoc[Compaction API]; with the Couchbase Web Console (as _auto-compaction_), see
xref:manage:manage-settings/configure-compact-settings.adoc[Auto-Compaction].

As described in xref:buckets-memory-and-storage/storage.adoc[Storage Settings], for each collection or item that is deleted, a _tombstone_ continues to be maintained by Couchbase Server for some period of time, as a record: this applies to all instances of item-deletion, including those achieved by specifying TTL.
To ensure that no trace of deleted items remains, tombstones are removed through a _Metadata Purge_.
This is an automatic, non-disruptive background-process, which can be scheduled if necessary by means of Couchbase Web Console; as described in
xref:manage:manage-settings/configure-compact-settings.adoc[Auto-Compaction].
Note that the console allows the intervals between purges to be established as appropriately low, so that tombstones are removed promptly.

[#bucket-expiration-and-xdcr]
== Expiration and XDCR

When Cross Data-Center Replication occurs, the bucket or collection TTL setting does not get propagated from the source to the target.
However, items within the source that have individual expiration times, including ones derived from the source bucket or collection TTL setting, are replicated to the target along with their individual expiration times.

Buckets and collections on the target cluster can have their own TTL settings, which may differ from those of the buckets and collections in the source.
If, on the target cluster, the TTL of a replicated item is:

* Above that of the bucket's or the collection's TTL, the item's TTL is reduced to the value of the bucket's or the collection's TTL.
* Below that of the bucket's or the collection's TTL, the item's TTL is left unchanged.
* 0, the item's TTL is reset to the value of the bucket's or the collection's TTL.

Note that in cases where the TTL of the replicated item is above that of the bucket's or the collection's TTL or is 0, if bi-directional XDCR has been set up, the TTL of the item at the source is eventually also either reduced or reset to the value of the target's bucket or collection TTL.

Note also that when an item is replicated by XDCR, its expiration time is communicated to the target as absolute.
This requires that the system clocks of the respective clusters be fully synchronized; otherwise, inconsistent behavior may result (as, for example, in the case where an item arrives at the target-cluster with an absolute expiration time that is earlier than the current time acknowledged by the target-cluster).
See xref:install:synchronize-clocks-using-ntp.adoc[Clock Sync with NTP].

Note that optionally, TTL can be _omitted_ from a document replicated by means of XDCR.
For details, see xref:manage:manage-xdcr/filter-xdcr-replication.adoc#deletion-filters[Deletion Filters].

[#setting-bucket-data-expiration]
== Setting Expiration on Buckets and Collections

An expiration time can be set for a bucket by means of any of the following:

* The UI provided by Couchbase Web Console.
See xref:manage:manage-buckets/create-bucket.adoc[Create a Bucket].

* The Couchbase CLI.
See xref:cli:cbcli/couchbase-cli-bucket-create.adoc[bucket-create].

* The Couchbase REST API.
See xref:rest-api:rest-bucket-create.adoc[Creating and Editing Buckets].

An expiration time can be set for a collection by means of:

* The UI provided by Couchbase Web Console.
See xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc#manage-scopes-and-collections-with-the-ui[Manage Scopes and Collections with the UI].

* The Couchbase ClI.
See xref:cli:cbcli/couchbase-cli-collection-manage.adoc[collection-manage].

* The REST API.
See xref:rest-api:creating-a-collection.adoc[Creating a Collection].

For information on roles that allow modification of bucket and collection settings, see
xref:learn:security/roles.adoc[Roles].

[#auditing]
== Auditing

If _auditing_ is switched on, changes to each bucket's expiration time are recorded, and can be subsequently viewed.
See xref:learn:security/auditing.adoc[Auditing].
