= Scopes and Collections
:description: pass:q[Couchbase Server provides _scopes_ and _collections_; allowing documents to be categorized and organized, within a bucket.]
:page-aliases: developer-preview:collections/collections-overview

[abstract]
{description}

This page contains an in-depth look at scopes and collections in Couchbase.
If you are looking for an introduction to logically partitioning your data with scopes and collections, you may like to start with the xref:tutorials:buckets-scopes-and-collections.adoc#scopes-and-collections[introduction to the topic] in our developer tutorial.


[#understanding-scopes-and-collections]
== Understanding Scopes and Collections

A _collection_ is a data container, defined on Couchbase Server, within a bucket whose type is either _Couchbase_ or _Ephemeral_.
Up to 1000 collections can be created per cluster.
Item-names must be unique within their collection.
Items can optionally be assigned to different collections according to content-type.
For example, within a bucket that contains travel information, documents that relate specifically to _airports_ might be assigned to an _airports_ collection, while documents that relate to _hotels_ might be assigned to a _hotels_ collection, and so on.
Applications can be assigned per-collection access-rights; allowing each application to access only those collections it requires.

A collection can be created and managed by means of the Couchbase Web Console UI, the Couchbase CLI, the Couchbase REST API, and N1QL.
It can also be created and managed by means of the SDK: see xref:3.3@java-sdk:howtos:provisioning-cluster-resources.adoc#collection-management[Collection Management].
A collection can be indexed; and it can be dropped.
The data in a collection can be replicated, by means of _Cross Data Center Replication_ (XDCR), to another collection in the same or in a different bucket.

A _scope_ is a mechanism for the grouping of multiple collections.
Up to 1000 scopes can be created per cluster.
Collection-names must be unique within their scope.
Collections might be assigned to different scopes according to content-type, or to deployment-phase (ie, test versus production).
Applications can be assigned per-scope access-rights; allowing each application to access only those scopes it requires.

A scope can be created and managed by means of the Couchbase Web Console UI, the Couchbase CLI, the Couchbase REST API, and N1QL.
It can also be created and managed by means of the SDK: see xref:3.3@java-sdk:howtos:provisioning-cluster-resources.adoc#collection-management[Collection Management].
A scope can be dropped.
A scope cannot be indexed.
The contents of a scope can be replicated, by means of _Cross Data Center Replication_ (XDCR), to another scope in the same or in a different bucket.

[#benefits-of-scopes-and-collections]
=== Benefits of Scopes and Collections

The benefits of scopes and collections include:

* The logical grouping of similar documents; potentially simplifying operations such as query, XDCR, and backup and restore.

* The increased efficiency of indexing, due to the Data Service being able to provide documents from specific collections to the Index Service.

* Simplified querying, since query statements are able to easily specify particular subsets of documents.

* Easier migration from relational databases to Couchbase Server, since collections can be designed to correspond to pre-existing relational tables.

* Secure isolation of different document-types, within a bucket; allowing applications to be specifically authorized to use only their appropriate subsets of data (see xref:learn:data/scopes-and-collections.adoc#access-to-scopes-and-collections[Access to Scopes and Collections], below).

[#naming-for-scopes-and-collections]
== Naming for Scopes and Collections

User-defined scopes and collections must be assigned user-defined names.
Such names:

* Must be between 1 and 251 characters in length.
* Can only contain the characters `A-Z`, `a-z`, `0-9`, and the symbols `&#95;`, `-`, and `%`.
Note that scope and collection names are _case sensitive_.
* Cannot start with `&#95;` or `%`.

The namespace within a scope is independent of any other namespace within any other scope: consequently, the same collection-name can exist in multiple scopes, within a single bucket.
Similarly, the namespace within a collection is independent of any other namespace within any other collection: consequently, the same document-key can exist in multiple collections, within a single scope.

[#default-scope-and-collection]
== Default Scope and Collection

Every created bucket is automatically given a _default scope_, and within it, a _default collection_.
Each is named `_default`.
All documents created within the bucket without reference to specific scopes or collections are saved in the default collection, within the default scope.
On upgrade from a version of Couchbase Server prior to 7.0, all existing data is automatically placed in the default scope and default collection.

The default scope cannot be dropped.
The default collection _can_ be dropped, by means of either the Couchbase CLI, or the REST API.
Once dropped, the default collection cannot be recreated.

[#access-to-scopes-and-collections]
== Access to Scopes and Collections

Access to scopes and collections is protected by _Role-Based Access Control_ (RBAC): therefore, appropriate roles must be assigned.

For information on RBAC, see xref:learn:security/authorization-overview.adoc[Authorization].
For a list of roles, see xref:learn:security/roles.adoc[Roles].
For examples of how to assign roles to scopes and collections, see xref:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups, and Roles].

[#expiration-and-collections]
== Expiration and Collections

An _expiration_ value can be established on a collection: this determines the maximum expiration time of individual items within the collection.
For information, see xref:data/expiration.adoc[Expiration].

[#managing-scopes-and-collections]
== Managing Scopes and Collections

See xref:manage:manage-scopes-and-collections/manage-scopes-and-collections.adoc[Manage Scopes and Collections], for information on how to use the CLI and REST API to create, maintain, and delete scopes and collections.

For information on using the Backup Service to _inspect_ scopes and collections within backed-up data, and to _restore_ data to specific scopes and collections, see xref:manage:manage-backup-and-restore/manage-backup-and-restore.adoc[Manage Backup and Restore].

For information on using scopes and collections with _Cross Data Center Replication_ (XDCR), see xref:manage:manage-xdcr/replicate-using-scopes-and-collections.adoc[Replicate Using Scopes and Collections].

For a complete reference to the CLI command for managing scopes and collections, see xref:cli:cbcli/couchbase-cli-collection-manage.adoc[collection-manage].

For reference pages for the REST API commands that manage scopes and collections, see xref:rest-api:scopes-and-collections-api.adoc[Scopes and Collections REST API].

For the `cbstats` reference pages for scopes and collections, see xref:cli:cbstats/cbstats-scopes.adoc[scopes], xref:cli:cbstats/cbstats-scopes-details.adoc[scopes-details], xref:cli:cbstats/cbstats-collections.adoc[collections], and xref:cli:cbstats/cbstats-collections-details.adoc[collections-details].

As indicated above, it is possible to create, maintain, and delete scopes and collections using the N1QL query language.
See the xref:n1ql:n1ql-language-reference/index.adoc[N1QL Language Reference] for further details.

[#working-with-collections-from-couchbase-sdks]
== Working with Scopes and Collections from Couchbase SDKs

The 3.x API versions of Couchbase SDKs work with scopes and collections.
For information, see the xref:3.3@java-sdk:howtos:working-with-collections.adoc[Java Howto doc].
