= Transactions
:description: pass:q[_Transactions_ guarantee that multiple documents can be updated atomically.]
:page-aliases: acid-transactions,transactions,learn:data/distributed-acid-transactions,introduction:distributed-acid-transactions

[abstract]
{description}


Couchbase provides Distributed ACID Transactions for K-V (data) and Query operations -- these are available through APIs in 
xref:cxx-txns::distributed-acid-transactions-from-the-sdk.adoc[C++], 
xref:dotnet-sdk:howtos:distributed-acid-transactions-from-the-sdk.adoc[.NET], and 
xref:java-sdk:howtos:distributed-acid-transactions-from-the-sdk.adoc[Java].


== Understanding Transactions

_Distributed ACID Transactions_ are operations that ensure that when multiple documents need to be modified such that only the successful modification of all justifies the modification of any, either all the modifications do occur successfully; or none of them occurs.
This _Atomicity_ supports _insert_, _update_, and _delete_ operations, across any number of documents.
It also enables seemless integration between KV and xref:n1ql:n1ql-language-reference/begin-transaction.adoc#purpose[Query] operations within transactions.

Only following commit of the documents modified by the transaction -- when the modified data-copy is removed from the meta data area (which uses xref:learn:data/extended-attributes-fundamentals.adoc[Extended Attributes]), and is written over the main body of the document’s data -- do the corresponding changes become readable by other transactions and operations.
This is https://jepsen.io/consistency/models/read-committed[Read Committed^] isolation.

A transaction can be performed across multiple buckets.
Only nodes that contain data to be updated are affected by a transaction.

Multiple transactions can read the same document at the same time.
If two transactions simultaneously attempt to write to the same document, one is allowed to proceed, while the other is obliged to retry.

Use of transactions requires _Network Time Protocol_ (NTP) to be used to synchronize time across all cluster-nodes.
See xref:install:synchronize-clocks-using-ntp.adoc[Clock Sync with NTP], for details.

=== Services and Transactions

The indexes provided by the Index, Search, and Analytics Services are _not_ atomically updated with the commits performed by transactions: however, they are updated with https://en.wikipedia.org/wiki/Eventual_consistency[Eventual Consistency].

Neither the Query Service nor the Search Service sees uncommitted data.
However, https://jepsen.io/consistency/models/snapshot-isolation[Snapshot Isolation] is _not_ provided: consequently, if a transaction performs a commit while a query or search is ongoing, then the query or search may return data from both prior to and subsequent to the commit.


// == Custom Metadata
include::java-sdk:howtos:distributed-acid-transactions-from-the-sdk.adoc[tag=custom-metadata]


== Limitations

Couchbase Distributed ACID Transactions currently have the following limitations:

* Only documents whose initial size is 10 MB or less can be included in a transaction.

* Non-transactional updates should not be made to any document involved in a transaction while the transaction is itself in progress: this prevents the non-transactional update from being overwritten.

* The number of writes required by a transactional update is greater than the number required for a non-transactional update.
Thus transactional updates may be less performant than non-transactional updates.
+
Note that data within a single document is _always_ updated atomically (without the need for transactions): therefore, whenever multiple key-value pairs consistently require atomic update, their co-location within a single document may best ensure high performance.

* xref:learn:clusters-and-availability/xdcr-overview.adoc[Cross Data Center Replication (XDCR)] supports _eventual consistency_: however, it does not support atomicity -- nor does
xref:learn:clusters-and-availability/xdcr-conflict-resolution.adoc[XDCR Conflict Resolution].
Consequently, transactionally modified documents should only be replicated across clusters if no transactions involving the same documents can occur on those clusters simultaneously.
In other words, Active-Active XDCR deployment (that is, where both clusters are being written to simultaneously) is not supported with the use of transactions and can lead to unexpected behavior and data loss.
+
See xref:learn:clusters-and-availability/xdcr-overview.adoc#xdcr-direction-and-topology[XDCR Direction and Topology], for a description of _bidirectional_ XDCR.
See xref:learn:clusters-and-availability/xdcr-conflict-resolution.adoc#ensuring_safe_failover[Ensuring Safe Failover], for information on failing a transactional application from one data center to another.

* Since transactions make use of the xref:learn:data/durability.adoc[Durability] provided by _synchronous writes_, in order to use transactions in development on a _single-node cluster_, the number of replicas assigned to any bucket to be used transactionally must be established as _zero_: if the number is greater than zero, the required durability level is unattainable, and the write fails.
+
If, on a single-node cluster, a bucket's replica-assignment was previously greater than zero, and the number is reduced to zero in order to support synchronous writes, a rebalance must be performed prior to any synchronous write.

* A Transactional N1QL Query using `AT_PLUS` will be automatically upgraded to `REQUEST_PLUS`.

=== Additional storage use

Transactions make use of the xref:learn:data/durability.adoc[Durability] provided by _synchronous writes_.
As well as making use of individual documents' extended attributes, transactions also create additional documents in each bucket that they access.
These include:

*  _Active Transaction Records_.
Multiple Active Transaction Records can exist per bucket.
Each of these documents can contain entries for multiple transactions.
Collectively, these documents record all currently active transactions for the bucket.
The name of each document is prefixed with `&#95;txn:atr-`.

* _Transaction Client Records_.
One of these exists per bucket, covering all clients currently accessing the bucket transactionally.
The document is named `&#95;txn:client-record`.

These documents, which may persist indefinitely, are automatically maintained by Couchbase Server, and should not be modified by any application.


== Creating and Using Transactions

For examples of creating and using transactions on Couchbase Server, see:

* xref:cxx-txns::distributed-acid-transactions-from-the-sdk.adoc[Distributed Transactions through the C++ API].
* xref:dotnet-sdk:howtos:distributed-acid-transactions-from-the-sdk.adoc[Distributed Transactions from the .NET SDK].
* xref:java-sdk:howtos:distributed-acid-transactions-from-the-sdk.adoc[Distributed Transactions from the Java SDK].

NOTE: SDK Transactions Version 1.0.x do not support N1QL operations, but can be used with Couchbase Server 6.6.
SDK Transactions Version 1.1.x require at least Server 7.0, and will work with N1QL operations.


It is also possible to create and use transactions using the N1QL query language.
Refer to the xref:n1ql:n1ql-language-reference/index.adoc[N1QL Language Reference] for further details.
