= Validity Guarantees (ACID)

[abstract]
Couchbase Server supports _Atomicity_, _Consistency_, _Isolation_, and _Durability_ in the handling of data.

[#understanding-acid]
== Understanding ACID

Couchbase Server guarantees the validity of data that it handles.
The properties whereby this is achieved are by convention referred to by the acronym _ACID_; which stands for _Atomicity_, _Consistency_, _Isolation_, and _Durability_.

The meanings of these properties, and the ways they are achieved by Couchbase Server, are described below.

[#atomicity-definition-and-implementation]
=== Atomicity

_Atomicity_ guarantees that when multiple data-elements need to be modified such that only the successful modification of all justifies the modification of any, _either_ all the modifications do occur successfully; _or_ none of them occurs.

Atomicity is innately supported by the xref:learn:data/document-data-model.adoc[Couchbase Data Model]; which is naturally expressive of hierarchical data, and therefore typically only requires a single document for data that, under a relational model, would require multiple tables; and would therefore maintain data-elements discretely.
On Couchbase Server, changes made to a single document are all written simultaneously, thereby guaranteeing atomicity of all data-elements within the document for every write.

Additionally, Couchbase Server supports the atomic inserting, updating, and deleting of data-elements across multiple documents by means of _Distributed ACID Transactions_.

[#consistency-definition-and-implementation]
=== Consistency

_Consistency_ requires that modifications to data occur only in accordance with required equivalencies and invariants.
For example, multiple copies of a single data-element must all be updated identically, when an update to any one occurs.

Couchbase Server provides xref:learn:clusters-and-availability/intra-cluster-replication.adoc[Intra-Cluster Replication]; which ensure data-availability with up to three replicas, deployed across the cluster.
The _Database Change Protocol_ (DCP) is continuously used to keep active and replica data-elements both consistent and up-to-date.

Couchbase Server provides an xref:learn:services-and-indexes/services/index-service.adoc[Index Service], which provides high-performance data-access to the xref:learn:services-and-indexes/services/query-service.adoc[Query Service]; and as such, maintains fast-access copies of specified data.
Such copies are updated with _eventual consistency_, across the cluster; and a xref:n1ql:n1ql-rest-api/index.adoc#table_xmr_grl_lt[Read Your Own Writes] mechanism is available to allow queries to determine the earliest point at which consistency is achieved.

When data-elements must be updated consistently across multiple documents, _Distributed ACID Transactions_ can be used.

[#isolation-definition-and-implementation]
=== Isolation

An operation that performs an atomic update, involving multiple discrete data-elements, is referred to as a _transaction_.
A transaction's ongoing updates to data should not be visible to any other transaction or operation, until fully complete.
_Isolation_ ensures this: while data is undergoing modification by a particular transaction, no other transaction or operation can read that data.

Couchbase _Distributed ACID Transactions_ provide the level of isolation referred to as https://jepsen.io/consistency/models/read-committed[Read Committed].
This ensures that no transaction or operations sees the uncommitted data of another transaction.
It also ensures that if two transactions try to update the same document, this is detected; and only one transaction is allowed to proceed.

[#durability-definition-and-implementation]
=== Durability

_Durability_ guarantees that data written into a database is fully conserved; and is not lost even in the event of significant system-failure.

Couchbase Server implements durability by means of _durable writes_ (sometimes referred to as _synchronous writes_).
These may be appropriate when saving data whose loss could have a considerable, negative impact.
For example, data corresponding to a financial transaction.
A durable write must be completed on a majority of those cluster-nodes that bear the active and replica copies of the data, before the application is informed that the data has been committed.
A successful commit may be considered to have occurred when the written data is either in the memory or on the disk of each of the nodes that constitute the majority.

[#transactions-and-durability]
== Transactions and Durability

As indicated above, a _transaction_ is an operation that performs atomic updates involving multiple, discrete data-elements.
Couchbase Server implements transactions as _Distributed ACID Transactions_, which isolate the data that is being updated, and allow it to be read by other transactions and operations only after it is committed.
For more details, see xref:learn:data/transactions.adoc[Transactions].

_Durability_ guarantees that data written into a database is fully conserved; and is implemented by Couchbase Server as _durable writes_.
For details, see xref:learn:data/durability.adoc[Durability].
