= Validity Guarantees (ACID)

[abstract]
Couchbase Server provides semantics that support _Atomicity_, _Consistency_, _Isolation_, and _Durability_ in the handling of data.

[#understanding-acid]
== Understanding ACID

Couchbase Server is designed to support the validity of data that it handles.
The properties whereby this is achieved are by convention referred to by the acronym _ACID_; which stands for _Atomicity_, _Consistency_, _Isolation_, and _Durability_.

The meaning of these properties, and the way they are achieved by Couchbase Server, is described below.

[#atomicity-definition-and-implementation]
=== Atomicity

_Atomicity_ guarantees that when multiple data-elements need to be modified such that only the successful modification of all justifies the modification of any, _either_ all the modifications do occur successfully; _or_ none of them occurs.

Atomicity is innately supported by the xref:learn:data/document-data-model.adoc[Couchbase Data Model]; which is naturally expressive of hierarchical data, and therefore typically only requires a single document for data that, under a relational model, would require multiple tables; and would therefore maintain data-elements discretely.
On Couchbase Server, changes made to a single document are all written simultaneously, thereby guaranteeing atomicity of all data-elements within the document for every write.

Additionally, Couchbase Server supports the atomic inserting, updating, and deleting of data-elements across multiple documents by means of _Distributed ACID Transactions_.

[#consistency-definition-and-implementation]
=== Consistency

_Consistency_ requires that modifications to data occur only in accordance with required equivalencies and invariants.
For example, multiple copies of a single data-element must all be updated identically, when an update to any one occurs.

Couchbase Server provides xref:learn:clusters-and-availability/intra-cluster-replication.adoc[Intra-Cluster Replication]; which ensure data-availability with up to three replicas, deployed across the cluster.
The _Database Change Protocol_ (DCP) is continuously used to keep active and replica data-elements both consistent and up-to-date.

Couchbase Server provides an xref:learn:services-and-indexes/services/index-service.adoc[Index Service], which provides high-performance data-access to the xref:learn:services-and-indexes/services/query-service.adoc[Query Service]; and as such, maintains fast-access copies of specified data.
Such copies are updated with _eventual consistency_, across the cluster; and a xref:n1ql:n1ql-rest-api/index.adoc#table_xmr_grl_lt[Read Your Own Writes] mechanism is available to allow queries to determine the earliest point at which consistency is achieved.

When data-elements must be updated consistently across multiple documents, _Distributed ACID Transactions_ can be used.

[#isolation-definition-and-implementation]
=== Isolation


[#durability-definition-and-implementation]
=== Durability
