= Global Secondary Indexes
:page-aliases: indexes:indexing-overview,indexes:view-indexes-for-n1ql,understanding-couchbase:services-and-indexes/indexes/global-secondary-indexes

[abstract]
A _Global Secondary Index_ (GSI) supports queries made by the _Query Service_ on attributes within documents.
Extensive filtering is supported.

Global Secondary Indexes provide the following:

* _Predictable Performance_: Key-based operations maintain predictable low-latency, even in the presence of a large number of indexes.
Index-maintenance is non-competitive with key-based operations, even when data-mutation workloads are heavy.
* _Low Latency Querying_: Since the xref:services-and-indexes/services/query-service.adoc[Query Service] accesses GSIs, rather than data maintained in documents, it is not obliged to track how original and replica
xref:buckets-memory-and-storage/vbuckets.adoc[vBuckets] are dispersed across nodes running the
xref:services-and-indexes/services/data-service.adoc[Data Service].
Moreover, since the GSIs reside on specific cluster-nodes running the _Index Service_, the Query Service can access the GSIs directly, without needing to use hashing routines.
* _Advanced Scaling_: GSIs can be assigned independently to selected nodes, without existing workloads being affected.

== Creating Global Secondary Indexes

Both Primary and Secondary indexes can be created by means of the N1QL query-language; using the CREATE INDEX statement and the USING GSI clause.
For more information, see xref:n1ql:n1ql-language-reference/createindex.adoc[CREATE INDEX].
