= Services and Indexes
:page-aliases: understanding-couchbase:services-and-indexes/services-and-indexes,architecture:views-indexing-index-service

[abstract]
Couchbase _Services_ support access to and maintenance of data.
_Indexes_ enhance the performance of query and search operations.

== Services

Services are configured and deployed by the Full Administrator who initializes Couchbase Server on one or more nodes.
The standard configuration-sequence allows a subset of services to be selected per node, with an individual memory-allocation for each.
Each service supports a particular form of data-access.
Services not required need not be deployed.
Services intended to support a heavy workload can be deployed across multiple cluster-nodes, to ensure optimal performance and resource-availability.

== Indexes

_Indexes_ are used by certain services, such as _Query_, _Analytics_, and _Search_, as targets for search-routines.
Each index makes a predefined subset of bucket-data available for the search.

The _Query_ and _Analytics_ services both rely on indexes provided by the _Index_ service.
The _Search_ service provides its own indexes, internally.

Indexes, when well-designed, provide significant enhancements to the performance of search-operations.
