[#topic9764]
= Views

[abstract]
The Views section allows you to manage your development and production views.

You can access the View section in two ways:

* Click *Data Buckets > Views*, or
* Select the [.uicontrol]*Views* tab on the main Couchbase Web Console panel.

The individual elements of this interface are:

Dropdown list on the top left:: Allows you to select the data bucket to view.

Create Development Spatial View:: Enables you to create a new spatial function either within the current design document or a new document.

Create Development View:: Enables you to create a new view either within the current design document or a new document.
You can switch between Production Views and Development Views.

Views screen:: The final section provides a list of the design documents and each defined view within each document.

== Development views

Compact::
Compact the view index with an associated design document.
This action compacts the view index and recovers space used to store the view index on the disk.

Delete::
Delete a design document.
This action deletes all of the views defined within the design document.

Add View:: [.uicontrol]*Add View* creates a new view for the corresponding design document.

Publish:: Publish your design document (and all of the defined views) as a production design document.

For each view listed, you can:

Edit:: Clicking on [.uicontrol]*Edit* or clicking the view name opens the view editor for the current view name.

Delete:: Deletes an individual view.

== Production views

Compact::
Compact the view index with an associated design document.
This action will compact the view index and recover space used to store the view index on the disk.

Delete::
Delete a design document.
This action will delete all of the views defined within the design document.

Copy to Dev::
[.uicontrol]*Copy to Dev* copies the view definition to the development area of the view editor.
This action enables you to edit the view definition.
Once you have finished making changes, click the btn:[Publish] button if you want to overwrite the existing view definition.

For each view, you can:

Show:: By clicking the view name or the btn:[Show] button, execute and examine the results of a production view.
